### ISSUE TITLE
AppConfigLocal.xml not pulled by 2.3.0.0 update

### ISSUE THREAD

**Issue by Majkl578** [EDDiscovery/EDDiscovery#10]
Hi,
while investigating 2.3.0.0 crash report [on the forums](https://forums.frontier.co.uk/showthread.php?t=138155&p=2466022&viewfull=1#post2466022), I discovered that AppConfigLocal.xml is missing in the directory of installed EDDiscovery.
Although this should not cause crashes (it's checked for exceptions explicitly), it will never create local AppConfigLocal.xml since source file is not found.
Not sure what hapenned though, file is marked as "Copy always".

**Comment by finwen** [comment]
solved in commit aebd9286eac0daf9ebb5e99a79798f54cff366ef  V 2.3.3
