### ISSUE TITLE
Feature request: Set a start point for 3d map history

### ISSUE THREAD

**Issue by tivec** [EDDiscovery/EDDiscovery#1004]
As you can see in the screenshot, all my travels within the bubble can be seen as one tangled mess. It'd be nice to be able to set a starting point for what is drawn on the 3d map, so you can visualize your current expedition, and not the complete history.

![Screenshot](http://i.imgur.com/2ZKDgpI.png)

**Comment by andreaspada** [comment]
Yes, please!

**Comment by robbyxp1** [comment]
The code is easy, the UI interface to do this is not.. hmmm.  we could use the start/end markers which are used for travel computation, set by the right click on the travel history to show only sections marked.

Doing it via the maps may be possible to set the start/end markers, but if you've turned it off you can't see where you've gone.

**Comment by tivec** [comment]
Using the travel history markers in the journal seem to be a good way of
doing it, considering it's already in there. Maybe a toggle button or
option in the map window "show from start marker"?

**Comment by finwen** [comment]
Well you can show it from a date  press on the calendar icon before ? on toolbar select cutom.  

Then you can show  only travelpoints after a specific date.   We could also add a range between 2 times if you need it

**Comment by finwen** [comment]
Is the current function that exist enough?

Closing soon otherwise....

**Comment by tivec** [comment]
A range between two dates/times would be optimal, if that is possible, as I keep track on when I set out on my exploration journeys.

**Comment by robbyxp1** [comment]
There is a filter option on there.
