### ISSUE TITLE
Unhandled exception when deleting the last commander

### ISSUE THREAD

**Issue by wwwutz** [EDDiscovery/EDDiscovery#1005]
(because of reasons)

When selecting the one and only left commander in the "Settings" tab and pressing the "Delete Commander" button an unhandled exception pops up.

7.0.3.0 / W7
![unhaexwhdeco](https://cloud.githubusercontent.com/assets/463828/25251528/efaff5c4-2619-11e7-9035-28cdcd29f121.png)

**Comment by robbyxp1** [comment]
I will check this, we have redesigned the settings dialog.

**Comment by robbyxp1** [comment]
Fixed, for 8.0
