### ISSUE TITLE
Estimated Scan Value Not pre/post 2.3aware?

### ISSUE THREAD

**Issue by markjfisher** [EDDiscovery/EDDiscovery#1006]
It looks like the current 2.3 upgrade values for scans have been updated, but as I've been out in the void for over a year, about 95% of my data is pre 2.3.
So, it looks like my total estimated scan value shot up massively.

As much as I'd love to believe I'm this close to elite on exploring, I'm guessing that actually the estimate is all systems based on the new scan values, and not split between pre and post 2.3 scans.
Are my assumptions here correct?

This is one of those things that will go away over time as noone will be left with pre-2.3 scans, but for us old timers still out in the void with oldish data, is it possible to split the totals up by applying values pre-2.3 and post-2.3 separately?

(As per patch notes:
"Increased the credit values of exploration data for scans after this release. Unsold data from previous scans is unaffected by this change.")

**Comment by markjfisher** [comment]
What details do you need?
I'm running the 7.0.2.0 client.

I see things like HMC Body scans (terraforming candidates) now coming in at 412,249 estimated value, which I'm pretty sure are off the scale compared to last week (IIRC they were about 40k?).

From my travel logs, star scans I have 893 N type, 193 M type, 139 H type, 59 G type, etc.
Body scans I have 412 HMC, 191 Rocky, 110 Icy, 101 Sudarsky class 1, 90 Sudarsky class 3.

I had previously estimated I would need 1500 system scans of 100k (e.g. black hole + neutron star) value to reach the magic 150M elite status. I was averaging around 50k estimated value per system last week (so needed 3000 systems), but now my stats show i have 1146 jumps, and a total scan value of 144M, so definitely higher than I would expect.

**Comment by markjfisher** [comment]
Last comment for now, looking at my bug report picture from https://github.com/EDDiscovery/EDDiscovery/issues/965 I had 1900 scans worth about 38M. After a busy weekend I have 2640 scans worth 145M. So 700 scans adding 107M scan value is either because the old estimate was too low or the new one is too high.

**Comment by finwen** [comment]
I have no idea if seling iold scans will give you new or old values yet.

All scan values are preliminary.  Estimation will be better then the community figures out rules for the new scan values.  But it will take some time befeore it will be calculated more correct.

**Comment by AnthorNet** [comment]
Only scans after the patch should have the new values.

**Comment by klightspeed** [comment]
So scans before e.g. 2017-04-11T12:00:00Z would use the old scan values, and scans after that would use the new scan values.

**Comment by markjfisher** [comment]
Exactly, I added the patch note comment about it in the original comment, i.e.

    Unsold data from previous scans is unaffected by this change

**Comment by robbyxp1** [comment]
Frontier like to make our lives complicated

**Comment by finwen** [comment]
Well it was a good change to increase the value for scans.

2017-04-21 9:05 GMT+02:00 robbyxp1 <notifications@github.com>:

**Comment by finwen** [comment]
Refining values for 2.3 will be another later issue.

**Comment by markjfisher** [comment]
thanks for this.

**Comment by markjfisher** [comment]
New prices are on https://i.redd.it/5khvftdue6ry.jpg
