### ISSUE TITLE
[Feature Request] Additional "History" Tab [Low Priority]

### ISSUE THREAD

**Issue by Gimi1967** [EDDiscovery/EDDiscovery#1007]
As the number of different roles available in EDD is increasing I would love to have a single, full page "tab" similar to the Journal tab, but configurable so that you can pick up any of the different roles available.

So like the current multi-functional windows on the history tab, but as a dedicated tab next to the journal tab that can be switched between available roles quickly. 

I am aware of the pop out functionality, but this can become messy when  you want to switch between views without opening too many windows/pop outs.

Very much a nice to have feature though.

**Comment by robbyxp1** [comment]
I feel the problem.. there is just too much in this program now ;-)

I've been thinking of a new major tab where you can place 1 to N panels, and arrange them as you will.  

Its on the list of things to do

**Comment by finwen** [comment]
We also planing on a popout panel that can have many panels inside it in the future.

**Comment by Gimi1967** [comment]
EDD [8.2.0](https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_8.2.0) adds the requested functionality and more. Thank you all for the update.
