### ISSUE TITLE
Different icon themes for scan window

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#1008]
Personally I'd prefer to have a more abstract icon set for stars/planets instead of the more realistic body images.

Each icon should include the type of object (star-class for stars, planet-type for planets).

Existing overlays (for landable, and the proposed terraformable (#962) etc) could be carried over and/or supplied as part of the icon pack in order to provide a custom colour scheme.

To generalise this, allow people to create their own icon sets for the scan window. An approach is a folder containing the actual images, and an XML/JSON/whatever file which maps the body-types to the images (thus allowing a single image file to be used for multiple objects, for example).

**Comment by robbyxp1** [comment]
Does not appear as any inclination or widespread req for this. closing to keep the list shorter.
