### ISSUE TITLE
Feature Request: Reformat Statistics Travel cr values for easier readability

### ISSUE THREAD

**Issue by hst12** [EDDiscovery/EDDiscovery#1010]
Currently the credit values displayed in Statistics->Travel->Summary have the digits all together making it a bit difficult to see how many millions you are making.

Suggestion: Use the "N0" instead of "0" format for easier readability.

The following code change in UserControlStats.cs at line 304 is what I have in mind:
                strarr[0] = hl.GetScanValue(DateTime.Now.AddDays(-1), DateTime.Now).ToString("N0");
                strarr[1] = hl.GetScanValue(DateTime.Now.AddDays(-7), DateTime.Now).ToString("N0");
                strarr[2] = hl.GetScanValue(DateTime.Now.AddDays(-30), DateTime.Now).ToString("N0");
                strarr[3] = hl.GetScanValue(new DateTime(2012, 1, 1), DateTime.Now).ToString("N0");

**Comment by robbyxp1** [comment]
All appears done, N0 everywhere
