### ISSUE TITLE
Mission deliveries show destination faction rather than source

### ISSUE THREAD

**Issue by DRY411S** [EDDiscovery/EDDiscovery#1013]
On delivery missions, the log entries show the receiving faction, but not the sending faction. Is it possible to show both? Example. In this case, the faction listed is the receiver not to receiver. So at the least, the text should say "Civil Unrest to"

`Mission Delivery Civil Unrest from Tewi'xilak Independents, Reward:248222, System:Tewi'xilak, Station:Mach City`

**Comment by klightspeed** [comment]
Please paste in the related journal entry from the journal file.

**Comment by DRY411S** [comment]
I will take a new mission and get the journal entry for that, just to double check that this isn't a mistake by me taking missions from the wrong faction!

**Comment by klightspeed** [comment]
If you look at the detailed info in either the tooltip or in the journal tab, are the `from` in the info and the `Target Faction` in the detailed info the same?

**Comment by robbyxp1** [comment]
Closed.. no further reports. Checked code.  TargetFaction is coming from TargetFaction JSON, Faction from Faction json, Field builder is saying from Faction.. TargetFaction from TargetFaction, checked thru with mission display, its displaying mission.Faction, Mission.TargetFaction
