### ISSUE TITLE
Feature Request: Per-jump notes

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#1014]
https://forums.frontier.co.uk/showthread.php/138155-EDDiscovery?p=5421316&viewfull=1#post5421316

The current note is for the system.

User requests a per-jump note, which would be attached to the journal entry instead of the system.

**Comment by andreaspada** [comment]
Already asked for something very similar. #813 and #578. Seems something very useful for many of us...

**Comment by robbyxp1** [comment]
This is complicated, especially with regards to the 3dmap.  Hence the original design decision when we implemented journals to say FSD jump note were per system, the rest per journal entry

**Comment by robbyxp1** [comment]
So its not as simple as it seems.  we need to change this all over the place, and it needs careful integration.

Closed other ones.

**Comment by mwerle** [comment]
I don't think we'd need to show per-jump notes (or any notes other than the System Note) on the 3dmap - at least to start off with. But yes, agree this needs some thinking about not only from a data/implementation perspective, but also a GUI/usage one.

From a GUI perspective, an initial way could be to use the grid views' note entry as the per-jump/journal note, and leave the big note field as the System Note. That would also mean we'd no longer need to keep those two fields in sync, and, IMHO, makes the GUI more consistent. It's currently a bit confusing to have the "static" system note pop up in every journal entry row.

Second stage add a special "Note" view, which is not (directly) editable, which shows the System Note at the top, and then the per-jump notes into the system as a list in chronological order.

**Comment by andreaspada** [comment]
I agree with @mwerle. We do not need to shows ALL notes on 3d Map. Just the system note - the one synced with EDSM, by the way, is enough...

A grid view for additional notes cna be used, like the grid on the Journal view. Per-Jump notes must link every notes on a journal jump, so maybe give too much complexion to the db. A CMDR log, just need to link every note to a system, so it avoid link to multiples jumps. The date field already can do that job: if we choose to show only the notes taken on a jump - for example - the date field can shows just the entries between a particular jump date and the next. So we achieve both functionalities with just an implementation:

Fields:
1) CMDR id
2) System   - sortable
3) Date      - sortable
4) Title
5) Note

**Comment by robbyxp1** [comment]
Well, its on my back burner, sorry, but there are more important things to do at the moment ;-)

**Comment by robbyxp1** [comment]
Notes are set on a journal record, for new notes. Only EDSM downloaded ones or old ones are on a system basis.  Its solved.
