### ISSUE TITLE
EDSM

### ISSUE THREAD

**Issue by VonDugard** [EDDiscovery/EDDiscovery#1015]
When I send info to EDSM from Discovery to my flight log I get this:
![2017-04-23](https://cloud.githubusercontent.com/assets/17255194/25316458/8a3a2ea6-285f-11e7-86bd-0b68ef210e2b.png)
![2017-04-23](https://cloud.githubusercontent.com/assets/17255194/25316462/98c44628-285f-11e7-95cd-4e112d31354a.png)
can you help us?

**Comment by klightspeed** [comment]
It looks like you are trying to import the netlogs using the EDSM user interface.  If you want to use the EDSM user interface, please try using the journal files from `%USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous`

**Comment by VonDugard** [comment]
Hi Ben, Thanks so much for your help I had been using NetLog up till the
10th April so was confuse when it stop working after the last up date.

**Comment by robbyxp1** [comment]
Closed.
