### ISSUE TITLE
Crash in Trilateration calculation when entering distance in a row with no system

### ISSUE THREAD

**Issue by Sheepzz** [EDDiscovery/EDDiscovery#102]
I get a reproducible crash when trilaterating in v 2.6.18. 

To reproduce:
1) Enter enough distances to systems such that the distances can begin to be calculated. 
2) Enter a distance in a row with a blank system
3) EDDiscovery will stop responding and crash.

The crash does not occur if not enough distances to systems have been entered to enable the distances to be calculated. Therefore, I guess it is related to calculated the distance to a blank system?

Cheers

Sheepz

**Comment by mwerle** [comment]
Fixed in 9f5be7c27830ff5262eb76e2f4c9a50c46660296 - please confirm and close.

**Comment by Sheepzz** [comment]
Thanks, I will test and confirm it fixed once the next version has been released.

Cheers

Sheez

**Comment by Sheepzz** [comment]
I can confirm that this bug is fixed for me in version 2.7.5. Thanks.
