### ISSUE TITLE
Engineering GUI

### ISSUE THREAD

**Issue by ZexMaxwell001** [EDDiscovery/EDDiscovery#1024]
Engineering was confusing to me. I saw it as a table to reference then a table to interact. the link below leads to a picture with color coded notations. 
this is just a list of suggestions and to start brainstorming for a better user friendly UI design.

http://imgur.com/a/HdCin

1 green box:
* Add down arrow to indicate more options
* shrink drop down box to match button size
* maybe continue the drop downs trend with the rest of the application.

2 blue box: 
* center number in cell.
* allow column to shrink more

3 red box:
* could not shrink it.

4 purple box:
* change cells in this column to indicate that the cells are editable.

5 cyan box:
* add link to abbreviated wiki

6 gray box:
* double click row or cell. the action will jump to wanted cell for editing the needed amount.

7 yellow box:
* remove notes column until its needed. it looks like the user can edit it.

**Comment by robbyxp1** [comment]
Thanks.  Not sure when we are going to rework this though.  next time we are in this and the synth box we will take a look.
