### ISSUE TITLE
Idea: using Kepler's third law to determine if planet is orbiting barycentre

### ISSUE THREAD

**Issue by klightspeed** [EDDiscovery/EDDiscovery#1027]
An idea to determine whether a planet is orbiting a star, the barycentre of a multi-star system, the barycentre between itself and another planet, or the barycentre of itself and another barycentre of other planets / stars, might be to use Kepler's third law along with the semi-major axis, orbital period, and mass of the planet / star to determine what the mass of the other object or group of objects.

```c#
double Msol = 1.9891e30; // Solar mass in kg
double Mearth = 5.9722e24; // Earth mass in kg
double G = 6.6740831e-11;
double othres = 50.0; // threshold from co-orbital to orbiting

double MassKG;
if (IsStar)
    MassKG = StellarMass * Msol;
else
    MassKG = MassEM * Mearth;

double k = 4 * Math.PI * Math.PI * Math.Pow(SemiMajorAxis, 3) / (G * OrbitalPeriod * OrbitalPeriod);
double m2;
if (k > MassKG * othres)
    m2 = k;
else
    double p = k * MassKG / 3.0 + k * k / 9.0;
    double q = k * k * MassKG / 3.0 + k * MassKG * MassKG / 2.0 + k * k * k / 27.0;
    double w = Math.Pow(q + Math.Sqrt(q * q - p * p * p), 1.0 / 3.0);
    m2 = w + (2 * k * MassKG + k * k / 3.0) / (3.0 * w) + k / 3.0;
```

Then match m2 against the mass of any neighbouring bodies or groups of bodies.

The equation of course assumes that the mass of any planets or moons orbiting the body are negligible in comparison to the mass of the body.

With this, we could then potentially indicate co-orbital planets, as indicated in the system map.

Of course, without the semi-major axis of the barycentres, we still can't place anything else in relation to the planets except around the arrival star or arrival binary.

**Comment by klightspeed** [comment]
Looks like I made a mistake with that formula.

**Comment by robbyxp1** [comment]
If only they would have included a parent body field..

**Comment by klightspeed** [comment]
Looks like that formula still gives the wrong answer.

**Comment by klightspeed** [comment]
Fixed my math:
[![math](http://quicklatex.com/cache3/3b/ql_f8d1a1f4ec9468dac56eac0b99cb403b_l3.png)](https://gist.github.com/klightspeed/06c57bd844efa21a2c181cfe9381a5e2)

**Comment by dobb13** [comment]
A better way to go about this may be to match up partners that orbit each other. Every pair of double planets will each have an identical period (P), eccentricity (e), inclination (i), argument of periapsis (ω), mean anomaly (M), and an ascending node (Ω) that is 180° different (opposite). This won't cover all cases (like double planets co-orbiting a barycentre opposite a gas giant), but it's a good start.

**Comment by andreaspada** [comment]
Awesome! I was thinking at that today morning. I was tweaking with that - http://www.calctool.org/CALC/phys/astronomy/planet_orbit - for another thing, trying to figure out how to get the distance from the stars which a planet orbits, even if it's a secondary star, and I thought that it could be used for binary planets, maybe.

**Comment by klightspeed** [comment]
The only orbital parameter we have for barycentres is the distance from arrival of an orbiting body, which is only really useful if the planet orbits the primary star.  For a body orbiting the secondary star, it'd only set a minimum on the current distance from the secondary star.  The maximum would be either the orbit of the next planet out, or the radius of the hill sphere of the secondary star if the planet is the most distant from the secondary star.

**Comment by robbyxp1** [comment]
I think this is superseded by the Parent field in the scans.  Closing.  Reopen if you think relevant
