### ISSUE TITLE
Unknown module type report from Loadout->Coriolis button

### ISSUE THREAD

**Issue by hst12** [EDDiscovery/EDDiscovery#1028]
Unknown Module Type
This is probably a new or powerplay module
Report to EDD Team by Github giving the full text above

Steps to reproduce: Loadout->Coriolis button and have bobble head text cockpit decorations installed

Loadout text contains:
Bobble Text B:Bobble_TextB
Bobble Text I:Bobble_TextI
Bobble Text G:Bobble_TextG
Bobble Text R:Bobble_TextR
Bobble Text E:Bobble_TextE
Bobble Text D:Bobble_TextD

**Comment by klightspeed** [comment]
These would be the cockpit dash slots.

**Comment by hst12** [comment]
Yes, they are. Reporting it since I get a popup message from EDD about it.

**Comment by robbyxp1** [comment]
Gosh, i'll have to put my Braben on the dash and debug it, thanks

**Comment by hst12** [comment]
The position of the bobble isn't in the error string. As I recall the 1st and 2nd slots are empty on my ship, next 3 filled, then 1 blank and 3 filled slots.
Probably not important what slot has what I guess.

**Comment by Culinarytracker** [comment]
I am getting the same error message. 
Bobble Pilot Male:Bobble_PilotMale
This is probably a new or powerplay module

**Comment by robbyxp1** [comment]
Fixed on master for 8.0
