### ISSUE TITLE
Creating an unhandled exception at launch

### ISSUE THREAD

**Issue by Nemesis2310** [EDDiscovery/EDDiscovery#1033]
I just updated my client, since i haven't done so in a while, but when the installation finished and i started EDD i recieved a message about "data disk image" being deformed. I attached the log file, hope you can help me :)
[Trace_20170503141322.zip](https://github.com/EDDiscovery/EDDiscovery/files/973259/Trace_20170503141322.zip)

**Comment by klightspeed** [comment]
This error suggests that either you have bad sectors in EDDUser.sqlite, or that e.g. an unexpected restart corrupted the database.

**Comment by Nemesis2310** [comment]
Do you have any tips on how to resolve this?

**Comment by klightspeed** [comment]
Some people find that just running scandisk or chkdsk (by e.g. right-clicking the drive, clicking properties, tools, and under Error Checking clicking Check) resolves the problem if it's a filesystem error (e.g. from an unexpected restart).

If a scandisk doesn't resolve it, you may need to move `%LOCALAPPDATA%\EDDiscovery\EDDUser.sqlite` somewhere else, and re-import your journals and any old netlogs.

The lack of any appreciable delay suggests it was not a bad sector.

**Comment by Nemesis2310** [comment]
The scandisk did not resolve the issue but relocating the EDDUser.sqlite did work. Thanks for the help.
