### ISSUE TITLE
Download of EDSM systems failed

### ISSUE THREAD

**Issue by theunkn0wn1** [EDDiscovery/EDDiscovery#1041]
occurs with EDDiscovery version 8.0.0.0 built against 9a2b7516d63630caaa0dee5f8ca73d95d564461c 
(also occurs with released build 7.0.4) 
OS: Windows 10 (x64)

I am unable to connect to EDSM via EDDiscovery. As a result, any exploration data I gather in the course of my travels do not get pushed to EDSM nor any data from EDSM reaches me. 

I have correctly set my API key and commander name and triple checked that it is consistent with EDSM.
I have tried un-installing and re-installing EDDiscovery as well as building it from source to no avail. EDDiscovery's log states
> Download of EDSM systems from the server failed (no data returned), will try next time program is run

After a little digging, `System.Net.HttpWebRequest.GetResponse()` is throwing the following exception:
>Exception thrown: 'System.Net.WebException' in System.dll
   at System.Net.HttpWebRequest.GetResponse()
   at EDDiscovery.HTTP.HttpCom.RequestGet(String action, NameValueCollection headers, Boolean handleException) in C:\Users\aa\Documents\GitHub\EDDiscovery\EDDiscovery\HTTP\HttpCom.cs:line 259
WebException : The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at EDDiscovery.HTTP.HttpCom.RequestGet(String action, NameValueCollection headers, Boolean handleException) in C:\Users\aa\Documents\GitHub\EDDiscovery\EDDiscovery\HTTP\HttpCom.cs:line 259

**Comment by phroggster** [comment]
> WebException : The request was aborted: Could not create SSL/TLS secure channel.

For sheer curiosity, try stopping the Windows Firewall service, or any installed third-party firewalls, and see if you can get through. Re-enable the firewall when complete.

If that didn't make a bit a difference (and I don't believe it will, it's just something fairly easy to check), have you made any modifications to the [EDDiscovery.config](https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/App.config) file, or is it vanilla?

Are you able to access [edsm.net](https://www.edsm.net/) directly in your preferred browser? What about the Edge browser?

Lastly, 9a2b7516d63630caaa0dee5f8ca73d95d564461c wouldn't affect this. Do you recall which release/commit last worked for you?

**Comment by theunkn0wn1** [comment]
Disabled both Windows Firewall service and my AV's firewall. No change.
No modifications to EDDiscovery.config, using default options.
I can successfully access EDSM.net Via Google Chrome (my default browser) but, interestingly, Edge throws an error. No idea exactly what error as it doesn't show me.

As for the last successful build/release, It appears to never have been functional as EDSM has no records under my user.

**Comment by phroggster** [comment]
I just verified that Edge was functional, and was able to complete an initial EDSM sync using a fresh portable EDDiscovery build, so it doesn't appear that anything is out of the ordinary on their end. In other words, there's something out of the ordinary on your machine/network, and there's a lot of possibilities as to what that might be. I suspect that it's the third-party firewall performing a [MITM](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) "attack", so let's take a look into that.

1. Revisit [edsm.net](https://www.edsm.net/) in Chrome.
2. Open up the Developer Tools (`CTRL+SHIFT+I`).
3. Select the Security tab, and click the `View Certificate` button.
4. Select the Certification Path tab. Does the Certification Path match the following?<ul><li>The USERTrust Network™</li><li>COMODO ECC Certification Authority</li><li>COMODO ECC Domain Validation Secure Server CA 2</li><li>($randomtext).cloudfaressl.com</li></ul>
6. Click on each certificate in the path. Does the bottom text (Certificate status) maintain `This certificate is OK.`? (Since Chrome seemed to work, I suspect these will all say OK.)
7. Double-click the topmost certificate (should be: The USERTrust Network™), and select the Details page. Scroll down to Thumbprint. Assuming that Thumbprint Algorithm is sha1 (let me know if the algorithm is different), does the thumbprint match `‎02fa f3e2 9143 5468 6078 5769 4df5 e45b 6885 1868`?

Assuming that nothing has set off a red flag in the above steps, can you expand on what the Edge browser does when you visit [edsm.net](https://www.edsm.net/) with it? Maybe take a screenshot of the error and post that? Also, please advise as to which third-party firewall you are using.

**Comment by theunkn0wn1** [comment]
Third party Firewalls: AVG Internet Security(on my endpoint) and there is also an upstream network firewall that i have no access to. I have never had a problem with the upstream one so i doubt its causing issues/ doing an MITM attack; I would know by now as far more interesting bits of data have gone through it...

--------------
As for the certificate: The Root Certificate is "The USERTrust Network<sup>tm</sup> with SHA1 Thumbprint of `02 fa f3 e2 91 43 54 68 60 78 57 69 4d f5 e4 5b 68 85 18 68` which matches your above.
The Cert Path matches your above and chrome states they are all OK.
![image](https://cloud.githubusercontent.com/assets/3110986/25782198/c8e2e828-32fa-11e7-833a-3ddfe508ea03.png)

----------------
As for Edge: 
![image](https://cloud.githubusercontent.com/assets/3110986/25782212/2e5105f0-32fb-11e7-9900-27eb3c0b32a9.png)

**Comment by phroggster** [comment]
Yeah, certs and cipher negotiation look fine, so an MITM is extremely unlikely.

Edge seems to think there's a DNS error (the dnserror.html down in the Console). I'll have to play around for a bit and see how to break DNS requests for Windows (Edge and .NET), but not break them for Chrome. 

To quote Lewis Carroll via Alice (a very common name in network communications theory and troubleshooting), 
> Curiouser and curiouser.

**Comment by phroggster** [comment]
If you pull up an administrative command prompt (press WindowsKey+X, then click `Command Prompt (Admin)`), can you provide the full output from the following commands:
```sh
ipconfig /flushdns
nslookup
set type=NS
edsm.net
set type=AAAA
www.edsm.net
set type=A
edsm.net
exit
```

Double check that the default server (shown as `ns1.redacted.example.com` in the following excerpt) shows your expected DNS server name and address. Anyways, here's how mine looks, and you should see something rather similar:
```
C:\WINDOWS\system32>ipconfig /flushdns

Windows IP Configuration

Successfully flushed the DNS Resolver Cache.

C:\WINDOWS\system32>nslookup
Default Server:  ns1.redacted.example.com
Address:  10.10.20.30

> set type=NS
> edsm.net
Server:  ns1.redacted.example.com
Address:  10.10.20.30

Non-authoritative answer:
edsm.net        nameserver = tori.ns.cloudflare.com
edsm.net        nameserver = walt.ns.cloudflare.com
> set type=AAAA
> www.edsm.net
Server:  ns1.redacted.example.com
Address:  10.10.20.30

Non-authoritative answer:
Name:    www.edsm.net
Addresses:  2400:cb00:2048:1::681b:8be7
            2400:cb00:2048:1::681b:8ae7

> set type=A
> edsm.net
Server:  ns1.redacted.example.com
Address:  10.10.20.30

Non-authoritative answer:
Name:    edsm.net
Addresses:  104.27.139.231
            104.27.138.231

> exit

C:\WINDOWS\system32>
```

**Comment by theunkn0wn1** [comment]
output of the requested commands:

```Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>ipconfig /flushdns

Windows IP Configuration

Successfully flushed the DNS Resolver Cache.

C:\WINDOWS\system32>nslookup
Default Server:  UnKnown
Address:  192.168.0.1

> set type=NS
> edsm.net
Server:  UnKnown
Address:  192.168.0.1

Non-authoritative answer:
edsm.net        nameserver = tori.ns.cloudflare.com
edsm.net        nameserver = walt.ns.cloudflare.com
> set type=AAAA
> www.edsm.net
Server:  UnKnown
Address:  192.168.0.1

Non-authoritative answer:
Name:    www.edsm.net
Addresses:  2400:cb00:2048:1::681b:8ae7
          2400:cb00:2048:1::681b:8be7

> set type=A
> edsm.net
Server:  UnKnown
Address:  192.168.0.1

Non-authoritative answer:
Name:    edsm.net
Addresses:  104.27.139.231
          104.27.138.231

> exit

C:\WINDOWS\system32>
```

**Comment by phroggster** [comment]
I always forget about gist.github.com; good call.

Is Edge able to browse other sites, particularly something from the [Alexa Top 500](http://www.alexa.com/topsites) such as [Google](https://www.google.com) or [Wikipedia](https://www.wikipedia.org)?

**Comment by theunkn0wn1** [comment]
>Is Edge able to browse other sites, particularly something from the Alexa Top 500 such as Google or Wikipedia?

Yes. Edge can browse other sites just fine.

**Comment by theunkn0wn1** [comment]
Alright... did a packet capture of the traffic and i *think* i found a problem. The TLS handshake fails when a .NET application (powershell) or Edge attempts to connect while chrome is just fine...
The client hello from .NET doesn't support the same Cipher Suites as Chrome does, and the server resets the connection as a result.

**Comment by phroggster** [comment]
Try replacing your App.config with [this one](https://gist.github.com/phroggster/12396ee5177771dc81bac910e71d5a7a), then rebuilding and debugging it inside of Visual Studio for as briefly as possible to encounter the issue. Or even just a minimally simple "HelloWorldS" project with only the `<system.diagnostics>` section from the linked App.config. In either case, the Output > Debug console should dump enough information to figure out next steps.

**Comment by klightspeed** [comment]
Surely it's not an export version of Windows with various crypto bits disabled?

**Comment by theunkn0wn1** [comment]
@klightspeed No, its a proper and full version of Windows 10 Pro with a Valid license.

**Comment by theunkn0wn1** [comment]
@phroggster The issue does not appear to occur with your App.config! It actually started pulling data from EDSM. I left it running for half an hour and it went through 8E5 systems before i stopped it.

**Comment by AnthorNet** [comment]
May be it was related to CloudFlare trouble.
We deactivated it for now and see how the server respond.

**Comment by phroggster** [comment]
@theunkn0wn1 I don't even want to know how many GiB of RAM that log would have taken up while pulling down `systemsWithCoordinates.json`... Anyways, glad that this got sorted out, and that we didn't even have to dissect that log file!

@AnthorNet Wishing now that I would've looked on Discord earlier to see the discussions with OtisB. Oh well, live and learn. Hope that things get worked out with CF.
