### ISSUE TITLE
3D Map not showing

### ISSUE THREAD

**Issue by Shasokias** [EDDiscovery/EDDiscovery#1042]
When I press the 3D Map button the Window is opening somewhere I cant see it. Not sure if its off screen or thinks its on another monitor. Definitely seems to be opening it, Its just not visible to me.

**Comment by klightspeed** [comment]
Please try selecting the window (e.g. using alt+tab), then press alt+space, press m, then press an arrow key.  Move the window where you want it, then click to drop.

We probably need to clamp the saved position when restoring it.

**Comment by finwen** [comment]
I had this issue to once.  Its an EDD issue then  position is store outside my 2 monitors someway....  We need a mecanism to restore or reset windows positions if it goes bad.

**Comment by robbyxp1** [comment]
Clamping the save position is an interesting problem.. maybe there is a windows call but working with all the variations of screens/pos and checking it all works would be a lot of work.


http://stackoverflow.com/questions/937298/restoring-window-size-position-with-multiple-monitors

has ideas.
