### ISSUE TITLE
Trigger EDSM calculation on distance submission

### ISSUE THREAD

**Issue by gregmcdougall** [EDDiscovery/EDDiscovery#1043]
I've been noticing for a while that a system [awaiting distances](https://www.edsm.net/en/systems/front) will 'go green' when i load the page as EDSM is performing a distance calculation. It would appear that EDD isn't asking EDSM to try and re-calculate the star's co-ordinates awaiting giving the site another distance. This is leaving stars with unknown co-ordinates when in fact EDSM has enough distances to successfully locate it.

**Comment by klightspeed** [comment]
I.e. instead of submitting all of the distances on the system you are in, the program should submit them one at a time on the target systems?

**Comment by AnthorNet** [comment]
Normally the main system should be calculated.
The others should be triggered for our background scanner to avoid performance hit when sending the APi response. 
I will take a look at that code.
