### ISSUE TITLE
weird extra lines in 3d and 2d travel map

### ISSUE THREAD

**Issue by Zefod** [EDDiscovery/EDDiscovery#1044]
HI, i noticed this today ; extra lines have appeared in my travel map... any idea what causes it?

![image](https://cloud.githubusercontent.com/assets/17833887/25828675/dd2b1f8c-3451-11e7-9e76-2933aa9f7bc8.png)
![image](https://cloud.githubusercontent.com/assets/17833887/25828690/ecaae5b4-3451-11e7-809f-757a09e8e84d.png)

thanks

**Comment by finwen** [comment]
HAve you been playing with multicrew and flying somewhere else so travelhistory jumps between your position and them crew you joined?  

IF thats the case then we are already working oon a solution for that in 8.0.1

**Comment by Zefod** [comment]
Yeah i've done a few multicrew sessions, that could be it, looking forward to 8.0.1 :)
thanks!

**Comment by finwen** [comment]
Not sure it will make it into 8.0.1 but should be 8.0.2 atleast :)

To give me something for test  please send me some journal files.  Preferable all last month since ED 2.3 release.

Send to robert.l.wahlstrom@gmail.com

**Comment by finwen** [comment]
Probably solved in 8.0.1

**Comment by Zefod** [comment]
the extra lines are still there in 8.0.1 :(
do i need to reprocess the log files?

**Comment by finwen** [comment]
Will do some more test.  and we should hopefully get it fully removed in
8.0.2  It might already been solved in 8.0.2 But i will do some testing
with your data soon.

2017-05-11 16:04 GMT+02:00 Zefod <notifications@github.com>:

**Comment by Zefod** [comment]
Ok, btw i noticed that the extra lines appear on my older logs...
For instance; formidine trip and the second colonia trip look fine.
Looking at older logs; trip to beagle point and my first colonia trip, they
show the extra lines.
if you need more of my logs, let me know :)

**Comment by finwen** [comment]
Ah then the multi crew part is fixed.  The older parts are from before.

HAve you used different commanders before?

2017-05-11 16:53 GMT+02:00 Zefod <notifications@github.com>:

**Comment by Zefod** [comment]
nope it's Just Zefod...
here some extra screenshots from 8.0.1 showing extra lines around the
lagoon nebula:

http://imgur.com/a/vY8pe

what is the meaning of red vs green lines btw?

my EDD jump log goes back to 24-11-2014... looking at the history in the
last screenshot i see some very high jump distances to beagle point... what
happened there?

**Comment by klightspeed** [comment]
Before Elite Dangerous 2.1, the netlogs did not include system coordinates.  Therefore the only systems that will appear on the map are those that you or someone else has trilaterated, or that someone has visited since 2.1 and submitted to EDSM.

Please look at your travel log, filtered by FSDJump entries, and see if you can find the FSDJump entries that coincide with the long lines?

The different colour lines in EDDiscovery are set by the colour you set on those jumps (or the default colour at the time the jumps were made).  The default colour is red, and is set on the settings tab.

**Comment by Zefod** [comment]
I've found a few entries with high jump ranges but are in fact only few
light years apart:

{
  "timestamp": "2016-07-24T20:41:23Z",
  "event": "FSDJump",
  "StarSystem": "Flyae Eaec BM-Z c2-31",
  "StarPos": [
    -3346.21875,
    -293.09375,
    9334.4375
  ],
  "EDDMapColor": -10161009,
  "JumpDist": 2922.7730308006185,
  "EDD_EDSMFirstDiscover": true
}


{
  "timestamp": "2016-07-24T20:42:17Z",
  "event": "FSDJump",
  "StarSystem": "Flyae Eaec NN-A d1-93",
  "StarPos": [
    -3324.65625,
    -288.8125,
    9298.875
  ],
  "EDDMapColor": -10161009,
  "JumpDist": 2923.0463640606577,
  "EDD_EDSMFirstDiscover": true
}

this is how it looks in the history table, filtered by fsd jump... i'm sure
i didn't change the map color on every jump back then ;)

[image: Inline image 2]

**Comment by klightspeed** [comment]
It looks a lot like the time on your computer was out during either the earlier Blua Hypue leg of your trip (when the map colour was red) or the later Flyae Eaec leg of your trip (where your map colour was set to `#64F48F`)

Do you still have the netlogs from those times?

**Comment by Zefod** [comment]
nope those very old ones are gone... i still have them from 01-10-2016....
but there are some anomalies in those too:

in these subsequent EDD records only Kalana and LP 470-30 show up in
attached log file...
i searched other log files prior and after the attached one, Morgor and
Eranin are not found in those either.

{
  "timestamp": "2016-10-01T21:05:37Z",
  "event": "FSDJump",
  "StarSystem": "Kalana",
  "StarPos": [
    131.78125,
    -12.96875,
    60.03125
  ],
  "EDDMapColor": -10161009,
  "JumpDist": 16.911938737915296
}

{
  "timestamp": "2016-10-01T21:19:26Z",
  "event": "FSDJump",
  "StarSystem": "Morgor",
  "StarPos": [
    -15.25,
    39.53125,
    -2.25
  ],
  "EDDMapColor": -10161009,
  "JumpDist": 168.08745514798241
}

{
  "timestamp": "2016-10-01T21:22:44Z",
  "event": "FSDJump",
  "StarSystem": "Eranin",
  "StarPos": [
    -22.84375,
    36.53125,
    -1.1875
  ],
  "EDDMapColor": -10161009,
  "JumpDist": 8.2337078714574279
}

{
  "timestamp": "2016-10-01T20:15:24Z",
  "event": "FSDJump",
  "StarSystem": "LP 470-30",
  "StarPos": [
    -25.125,
    -55.0,
    -57.844
  ],
  "EDDMapColor": -65536,
  "JumpDist": 75.147202248415851
}

**Comment by Zefod** [comment]
[netLog.161001220847.01.txt](https://github.com/EDDiscovery/EDDiscovery/files/995839/netLog.161001220847.01.txt)

**Comment by Zefod** [comment]
sorry attachment troubles :)

**Comment by klightspeed** [comment]
Are those entries the only ones for the mentioned period?

Do you have the netlog before or after this one?  That netlog ends before the supposed Eranin or Morgor jumps.

Were you playing two commanders at the time?  Perhaps the green entries are from one commander, and the red entries are from another, and you merged the logs of those two commanders at some point?

**Comment by Zefod** [comment]
I only play one commander, never merged any logs... i have beta access, but those netlogs are stored in a different location, right?

Anyway, could a different theory be that syncing to and from EDSM has gone wrong?
i found this odd sequence:  

![image](https://cloud.githubusercontent.com/assets/17833887/25996539/20ab7f86-3718-11e7-8ea4-d6be5fc2e7be.png)

notice how there is exactly 2 hours time difference between the green and red sequences of jumps?

**Comment by klightspeed** [comment]
I think this may have been a bug with versions before 5.0, where many things in EDDiscovery were still in local time, and in many places timezones weren't taken into account properly.

At the moment, we don't have an option to filter logs by source or to manage stored log units, but given that all of your EDSM imported logs appear to be green, and appear to be the ones in error, it should be possible to select all of those entries, right-click, and hide them.

**Comment by Zefod** [comment]
Ah ok that solves it :) thanks for all the help!
