### ISSUE TITLE
"Unknown" event: CrewMemberRoleChange

### ISSUE THREAD

**Issue by andybish** [EDDiscovery/EDDiscovery#1048]
Crew Member Role Change event showing as "unknown" in edd. couple of examples:

{ "timestamp":"2017-04-11T18:11:06Z", "event":"CrewMemberRoleChange", "Crew":"[cmdr name]", "Role":"Idle" }
{ "timestamp":"2017-04-11T18:14:56Z", "event":"CrewMemberRoleChange", "Crew":"[cmdr name]", "Role":"FireCon" }
{ "timestamp":"2017-04-11T18:15:49Z", "event":"CrewMemberRoleChange", "Crew":"[cmdr name]", "Role":"Idle" }
{ "timestamp":"2017-04-11T18:15:50Z", "event":"CrewMemberRoleChange", "Crew":"[cmdr name]", "Role":"FighterCon" }

edit: forgot to mention, v8.0.0.0

**Comment by finwen** [comment]
This was unhandled in EDD.  Will add it.

**Comment by finwen** [comment]
Solved in 8.0.1
