### ISSUE TITLE
Where is the Old Data

### ISSUE THREAD

**Issue by Red13x3** [EDDiscovery/EDDiscovery#1056]
Before 2.x when they didn't do the journal logs, I had a lot of expo data using the then current version of EDD.  But since the upgrade to the versions that work with the journal logs, all that old data is gone.

Is there any way to import it? If so, where would that old data reside?

**Comment by klightspeed** [comment]
What version were you using before, and what version did you upgrade to?

You cannot upgrade directly from 4.x or lower to 8.x or higher.  You will need to first upgrade to 5.x-7.x and have that convert the old EDDiscovery.sqlite to the newer EDDUser.sqlite and EDDSystem.sqlite.  If you have already started 8.x, and you have never used 5.x-7.x, then you can remove EDDUser.sqlite and EDDSystem.sqlite, then run 7.x to convert the database.

**Comment by robbyxp1** [comment]
Closing, no further update from user.
