### ISSUE TITLE
Feature request: Display current gamemode in history tab

### ISSUE THREAD

**Issue by andybish** [EDDiscovery/EDDiscovery#1057]
Basically, I'd like to see whether I'm in open, solo, or a private group (and whose) in the info panel of the history tab. It should be possible, by looking up the last load game event and reading its mode and group. (something like ifexists(group) then group, else mode). Could also change based on selection, so it would always show the gamemode you were in at the time of an event?

**Comment by robbyxp1** [comment]
So, its entirely possible, just don't know where to fit it in on the UI. Its already crowded.  But its a good idea.
