### ISSUE TITLE
Obsolete POI categories

### ISSUE THREAD

**Issue by CorbinMoran** [EDDiscovery/EDDiscovery#1058]
Two of the POI categories in EDD has been changed by the Galactic Mapping Project some time ago:

'Stellar Remnant' POI should be renamed 'Stellar Features'. A star icon/image might be suitable for the map.
'Exploration Hazard' POI should be renamed 'Restricted Sectors'. 

Cheers :)

**Comment by phroggster** [comment]
Thanks for letting us know.

In my mind, "restricted sector" implies "permit locked." Not saying that these changes shouldn't be pushed through, just that I don't necessarily agree with the second one.

**Comment by CorbinMoran** [comment]
The restricted sectors are indeed the permit locked sectors.
