### ISSUE TITLE
Asteroid Scan Error Message in Log.

### ISSUE THREAD

**Issue by Datalives** [EDDiscovery/EDDiscovery#1059]
**_Asteroid Scan Error Message in Log of EDDiscovery - Happen twice - advice is to inform devs... scans are going through fine though - and no errors on planets!_**

https://www.edsm.net/en/system/id/872797/name/Phaa+Ain+NL-P+d5-187
EDDN sync thread exiting
Starting EDDN sync thread
Sent Scan event to EDDN (Scan of Phaa Ain NL-P d5-187 B 2 b)
EDDN sync thread exiting
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object Phaa Ain NL-P d5-187 B A Belt Cluster 3 in Phaa Ain NL-P d5-187
Starting EDDN sync thread
Sent Scan event to EDDN (Scan of Phaa Ain NL-P d5-187 B A Belt Cluster 3)
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object Phaa Ain NL-P d5-187 B A Belt Cluster 1 in Phaa Ain NL-P d5-187
Sent Scan event to EDDN (Scan of Phaa Ain NL-P d5-187 B A Belt Cluster 1)
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object Phaa Ain NL-P d5-187 B A Belt Cluster 2 in Phaa Ain NL-P d5-187
Sent Scan event to EDDN (Scan of Phaa Ain NL-P d5-187 B A Belt Cluster 2)
EDDN sync thread exiting
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object Phaa Ain NL-P d5-187 B A Belt Cluster 4 in Phaa Ain NL-P d5-187
Starting EDDN sync thread
Sent Scan event to EDDN (Scan of Phaa Ain NL-P d5-187 B A Belt Cluster 4)
EDDN sync thread exiting
Starting EDDN sync thread
Sent Scan event to EDDN (Scan of Phaa Ain NL-P d5-187 B 1)
EDDN sync thread exiting

https://www.edsm.net/en/system/id/12338216/name/IC+1805+Sector+VM-S+b5-2
Starting EDDN sync thread
Sent FSDJump event to EDDN (Jump to IC 1805 Sector VM-S b5-2)
Sent Scan event to EDDN (Scan of IC 1805 Sector VM-S b5-2 A)
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object IC 1805 Sector VM-S b5-2 A A Belt Cluster 9 in IC 1805 Sector VM-S b5-2
Sent Scan event to EDDN (Scan of IC 1805 Sector VM-S b5-2 A A Belt Cluster 9)
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object IC 1805 Sector VM-S b5-2 A A Belt Cluster 7 in IC 1805 Sector VM-S b5-2
Sent Scan event to EDDN (Scan of IC 1805 Sector VM-S b5-2 A A Belt Cluster 7)
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object IC 1805 Sector VM-S b5-2 A A Belt Cluster 8 in IC 1805 Sector VM-S b5-2
Sent Scan event to EDDN (Scan of IC 1805 Sector VM-S b5-2 A A Belt Cluster 8)
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object IC 1805 Sector VM-S b5-2 A A Belt Cluster 2 in IC 1805 Sector VM-S b5-2
Sent Scan event to EDDN (Scan of IC 1805 Sector VM-S b5-2 A A Belt Cluster 2)
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object IC 1805 Sector VM-S b5-2 A A Belt Cluster 4 in IC 1805 Sector VM-S b5-2
Sent Scan event to EDDN (Scan of IC 1805 Sector VM-S b5-2 A A Belt Cluster 4)
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object IC 1805 Sector VM-S b5-2 A A Belt Cluster 6 in IC 1805 Sector VM-S b5-2
Sent Scan event to EDDN (Scan of IC 1805 Sector VM-S b5-2 A A Belt Cluster 6)
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object IC 1805 Sector VM-S b5-2 A A Belt Cluster 1 in IC 1805 Sector VM-S b5-2
Sent Scan event to EDDN (Scan of IC 1805 Sector VM-S b5-2 A A Belt Cluster 1)
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object IC 1805 Sector VM-S b5-2 A A Belt Cluster 3 in IC 1805 Sector VM-S b5-2
Sent Scan event to EDDN (Scan of IC 1805 Sector VM-S b5-2 A A Belt Cluster 3)
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object IC 1805 Sector VM-S b5-2 A A Belt Cluster 5 in IC 1805 Sector VM-S b5-2
Sent Scan event to EDDN (Scan of IC 1805 Sector VM-S b5-2 A A Belt Cluster 5)

**Comment by jdm12983** [comment]
Having similar issues with a few different systems now. Only happens with asteroid belts ("Belt Clusters").

```
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object Cephei Sector BV-Y b4 A A Belt Cluster 6 in Cephei Sector BV-Y b4
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object Cephei Sector BV-Y b4 A A Belt Cluster 11 in Cephei Sector BV-Y b4
```

Using EDDiscovery version 8.0.5.0.

**Comment by klightspeed** [comment]
For the moment, we probably need to either ignore scans of belt clusters, or group them under the rings of the parent star.  e.g. if the name matches ".* [A-F] Belt Cluster [0-9]*", then either ignore it or add it to its parent star's asteroid clusters.

**Comment by jdm12983** [comment]
Yeah, seeing as they don't even post to sites like EDSM itself (at least not right now) I'm sure it wouldn't hurt to ignore them.

I do like the idea of them being scanned though and recording by EDDsicovery; just for the fact if I go back to a system (or look back at it) I know if there were any belts to go to/look at.
