### ISSUE TITLE
Engineering list doesn't update if history doesn't show any entries

### ISSUE THREAD

**Issue by Thurion** [EDDiscovery/EDDiscovery#1060]
If the history doesn't show a single entry, the engineering list doesn't update.
Easiest way to test:

1. Set history event to none
2. Change filter for engineers (e.g. change from all modules to only armour)

This was tested in version 8.0.0.0

**Comment by Thurion** [comment]
Update: After i started EDD again, I got this [error](http://prntscr.com/f7zlu3). This happens in 8.0.0.0 up to 8.0.2.0

**Comment by robbyxp1** [comment]
Engineering list tracks the availability of materials at the currently selected cursor point in the history.   If there is no selected point, it can't show anything.  its correct behaviour.
