### ISSUE TITLE
Feature Requests: Include atmosopheric data for planets, add XYZ Coords to exported lists

### ISSUE THREAD

**Issue by EtherealVonCereal** [EDDiscovery/EDDiscovery#1062]
For a future build, what are the chances of being able to see atmospheric data for planetary bodies (especially gas giants) added to the database?  Furthermore, it would be a boon to be able to go into an exported list and retrieve XYZ coordinates for a system straight from the sheet, since EDDiscovery already includes that information in the system panel for a particular system's overview.

Thank you in advance 😄

**Comment by robbyxp1** [comment]
Thanks for the suggestions.  The Atmosphere composition is new to 2.3 but will be soon added.

Which excel export are you refererring to? Is it the one on the Export tab, or the ones on the journal/travel history?

**Comment by iainross** [comment]
Atmospheric composition coming with https://github.com/EDDiscovery/EDDiscovery/pull/1074
