### ISSUE TITLE
Remove region borders or make regions more vague

### ISSUE THREAD

**Issue by CorbinMoran** [EDDiscovery/EDDiscovery#1064]
When we (the Galactic Mapping Team) defined the various galactic regions, we never intended their borders to be clear cut and well defined. We wanted regions to be a bit ambigous to add to the mystery of exploration. 

On the EDSM interactive map, region borders are not shown. Instead it is possible to see a popup that shows the vague outline of the region. This allows users of the map to get a sense of the size and shape of the region, but without it being clearly defined. 
An imgur album with the popus are available here: http://imgur.com/a/POi45

On the EDD map, region borders are drawn, and this is an issue that we should discuss how best to handle.

How can we add a functionality in EDD that allows us to keep the vague outline of the regions, without keeping the clearly defined borders?

**Comment by robbyxp1** [comment]
I'm afraid that handling this was complicated, turning the co-ords into triangles that could be painted via opengl.

Making it more vague would be complicated, and also would not show well on the screen against the rest of the stars.  I worked a lot of time to make it display properly, and others contributed to get the drawing right and cope with the boundaries.

So, in all respect, I can't see that this provides any real gain vs the amount of effort that would be required to implement this.

**Comment by CorbinMoran** [comment]
How about disabling region borders and region coloring. But then doing more about placement, size and angle of the region names text? This will bring the 3D map more in line with the way regions are displayed on the 2D map.
