### ISSUE TITLE
Add an Astronomical calculator panel

### ISSUE THREAD

**Issue by robbyxp1** [EDDiscovery/EDDiscovery#1070]
From Jaiotu on the forums:

Any chance of adding a calculator function to EDDiscovery? What I'm looking for is something that can take real-world astronomical data (right ascension, declination, distance) and convert them to in-game X,Y,Z coordinates.

I can do this with the following python script (relies on pyephem) but it would be nice to have something in a nice and easy GUI.

import sys, os
sys.path.append(os.path.dirname(__file__) + "lib64/python2.7/site-packages")

import ephem
import math

def eq2ed(ra,dec,r): # Convert J2000 right ascension, declination, and distance (ly) to ED X,Y,Z
eq = ephem.Equatorial(ra,dec)
gal = ephem.Galactic(eq)
x = r * math.cos(gal.lat) * -math.sin(gal.lon)
y = r * math.sin(gal.lat)
z = r * math.cos(gal.lat) * math.cos(gal.lon)
print('x=%f y=%f z=%f' % (x,y,z))

def ed2eq(x,y,z): # Convert ED X,Y,Z to J2000 right ascension, declination, and distance (ly)
r = math.sqrt(x*x+y*y+z*z)
lat = math.asin(y/r)
lon = math.atan2(-x,z)
gal = ephem.Galactic(lon,lat)
eq = ephem.Equatorial(gal)
print('ra=%s dec=%s dist=%f' % (eq.ra,eq.dec,r))

# [PUT YOUR DATA BELOW HERE]

# Example: get Tycho's star coordinates in ED
r = 8900 # suspected distance to sol in light years
ra = '0:25:22' # right ascension in hours:minutes:seconds
dec = '64:09:0' # declination in degrees:degree_minutes:degree_seconds
eq2ed(ra,dec,r) # call the function to do the conversion

# Example: get Sagittarius A* real world equatorial coordinates based on location in ED
x = 25.21875
y = -20.90625
z = 25899.96875
ed2eq(x,y,z) # call the function to do the conversion

**Comment by klightspeed** [comment]
Beware that virtually all of the stars with a HIP number have had their J2000 coordinates treated as B1950 coordinates.

See https://drive.google.com/open?id=1JBhUHhcI2amWZWA_dXtPpGOZKECl5EQYxubp8BKvUbc for a few example systems.

**Comment by robbyxp1** [comment]
Closing seems inpractable.
