### ISSUE TITLE
Any way to have the voice packs call out whether a system/object has been discovered?

### ISSUE THREAD

**Issue by Kingdud** [EDDiscovery/EDDiscovery#1072]
Is there a way to configure the Voice Packs for EDDiscovery to call out whether or not a targeted object has the 'first discovered by' credit associated with it or not? If so, how?

**Comment by iainross** [comment]
Unfortunately not as that information is not included in the journal.  It might appear one day...

**Comment by Kingdud** [comment]
Darn. :(
