### ISSUE TITLE
There is a bug in the picture conversion system when Sagittarius A* is done

### ISSUE THREAD

**Issue by robbyxp1** [EDDiscovery/EDDiscovery#108]
Star * makes the program barf due to it being a file reservered character.

I'm going to fix it on the branch I'm doing at the moment for route planning updates, its only a few lines of fix..  not sure how to do it properly yet either.

let you know

rob

**Comment by gregmalcolm** [comment]
This duplicates #38 but I don't think anyone has actually worked on this, so thanks!

**Comment by robbyxp1** [comment]
I've got the fix,and it will go in with the route planning fix up

**Comment by mwerle** [comment]
> I've got the fix,and it will go in with the route planning fix up

<pedant> It's better to submit fixes individually; firstly for feature tracking, secondly if a feature is broken, it can be reverted without affecting anything else.

Do you have a personal copy of this fix already up? I'll be getting to SagA tonight..  otherwise I'll need to code my own workaround in the next couple of hourse.

**Comment by robbyxp1** [comment]
Hi,
    Sorry rushed off my feet, but I've created a pull request for it.
    
    Cheers
    
    Rob
    
    On 19/02/2016 11:16, Michael Werle
      wrote:
    
    
      
        I've got the fix,and it will go in with the route planning
          fix up
      
       It's better to submit fixes individually; firstly for feature
        tracking, secondly if a feature is broken, it can be reverted
        without affecting anything else.
      Do you have a personal copy of this fix already up? I'll be
        getting to SagA tonight.. otherwise I'll need to code my own
        workaround in the next couple of hourse.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by robbyxp1** [comment]
Hi Michael,
    
    I know, I was just hoping I could do both together, I'm a bit rushed
    for time this week.
    
    But I've now pushed the single SAGA* fix.
    
    Cheers
    
    Rob
    
    
    
    On 19/02/2016 11:16, Michael Werle
      wrote:
    
    
      
        I've got the fix,and it will go in with the route planning
          fix up
      
       It's better to submit fixes individually; firstly for feature
        tracking, secondly if a feature is broken, it can be reverted
        without affecting anything else.
      Do you have a personal copy of this fix already up? I'll be
        getting to SagA tonight.. otherwise I'll need to code my own
        workaround in the next couple of hourse.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mwerle** [comment]
Hey Rob; no worries! Sorry to have rushed you - at the end of the day it's no big deal, just a hobby after all! But much appreciated!
(No to fix up my local dev branch which is being difficult again so I can compile this in!)
