### ISSUE TITLE
Unhandled Exception after version upgrade

### ISSUE THREAD

**Issue by Ravvin** [EDDiscovery/EDDiscovery#1081]
Hi, after installing the latest EDDiscovery update, I now get the following Unhandled Exception on startup.

[Trace_20170612093106.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/1066824/Trace_20170612093106.0.txt)

I scanned the drive that has the game and log files on it and it said there were no errors.
I'm probably overlooking something obvious, but does anyone have any suggestions?

**Comment by klightspeed** [comment]
This suggests that `%LOCALAPPDATA%\EDDiscovery\EDDSystem.sqlite` is corrupt.  Please try exiting EDDiscovery, renaming or deleting EDDSystem.sqlite, then restarting EDDiscovery to rebuild the systems DB.

**Comment by Ravvin** [comment]
Thanks, that sorted the issue out.
The file was just under 1.4gb in size. Deleted it and it's now 2.4gb.
The program is happily tracking my jumps and discoveries again.

Thanks again.
