### ISSUE TITLE
[minor] typo in menu

### ISSUE THREAD

**Issue by galaxyutii** [EDDiscovery/EDDiscovery#109]
In the `Help` menu, the entry that links to this repo is called `Gitbub` instead of `Github`

**Comment by gregmalcolm** [comment]
Do you have the latest verion os EDD? I thought Finwen fixed this one

**Comment by finwen** [comment]
Should be solved in 2.6.18

**Comment by galaxyutii** [comment]
Yep, it is. It didn't prompt me to update to 2.6.18 so I didn't realize there was an update out. Thank you!
