### ISSUE TITLE
[Feature Request] Add event exclusions to Voice Pack 3

### ISSUE THREAD

**Issue by halitalf** [EDDiscovery/EDDiscovery#1095]
Make it whitelist/blacklist based. Somethings are said in-game, and others cause lag because it's done in rapid succession (Missions, specifically mass planetary scans)

_P.S.: Sorry if this is the wrong place for this._

**Comment by robbyxp1** [comment]
You can do this already.. just go into the editing of the voice action pack and select the condition on each of the entries you don't want to "Always False/Disable"
