### ISSUE TITLE
Feature Request: HTTP / Websocket API

### ISSUE THREAD

**Issue by cmmcleod** [EDDiscovery/EDDiscovery#11]
If this tool could serve data over HTTP then a number of other tools could integrate with it.

Specs / Suggestions
- Run on a default port, but configurable port
- CORS Headers for cross-domain requests
- HTTP api for polling
- Websocket API for push/listening
- Read only API

API
 - Get all data
 - Get last X systems
 - Get current system
 - Subscribe to system data

**Comment by mwerle** [comment]
I'd argue this is a job for EdProxy, and I'd actually really like it if EDDiscovery could be an EdProxy client.
https://forums.frontier.co.uk/showthread.php?t=167688

**Comment by gregmalcolm** [comment]
As EDDiscovery is a windows "thick client" application, definitely sounds like a job for a new or different (web) application. EDSM is actually covering a lot of this kind of ground now that it can import log data: 
http://www.edsm.net/

**Comment by gregmalcolm** [comment]
I'm going to go ahead and close this one out because I'm pretty sure EDD is never going to support web requests. Other tools handle that.
