### ISSUE TITLE
Allow sending distances to other systems if current system has known coordinates

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#110]
I've thought this too, but a forum user put it thusly:

Redfox in [this thread](https://forums.frontier.co.uk/showthread.php?t=138155&p=3587438&viewfull=1#post3587438) said:
"When arriving at a system with known coordinates (e.g. SagA) and wishing to add distances to systems with unknown coordinates - it seems one has to perform an successful trilateration first before being able to add/submit the distances for the systems with unknown coordinates. Would it not make sense to take over the local system's coordinates (if known from the Travel History) when clicking on "Start new"? That way, that redundant trilateration would not be needed."

**Comment by mwerle** [comment]
Implemented locally; requires testing.

**Comment by RedfoxCh** [comment]
...and there I was, thinking my comment had been overlooked ;-)

You guys are great.
