### ISSUE TITLE
Axial tilt is displayed as degrees but the value is radians

### ISSUE THREAD

**Issue by chreden** [EDDiscovery/EDDiscovery#1106]
In 8.0.9.0

For example:
https://www.edsm.net/en/system/bodies/id/13773347/name/Systipeia+HN-A+d14-0/details/idB/5674424/nameB/Systipeia+HN-A+d14-0+A+1

EDD is showing:
Axial tilt: 0.33°

EDSM shows:
Axial Tilt: 18.9 ° (18.85 in game)

This is just a display issue as the underlying value is fine.

**Comment by finwen** [comment]
:) should fix it to next version


2017-06-28 20:14 GMT+02:00 chreden <notifications@github.com>:
