### ISSUE TITLE
Route and Waipoint

### ISSUE THREAD

**Issue by tonkepen100** [EDDiscovery/EDDiscovery#1107]
Hi, first of all say that my English is very bad, so I forgive, and I know I use google, to put this comment.

That said, I mean the ROUTE tab:

The problem I see is that when you mark a destination waipoint, your name comes out as such, see photo .....

![captura1](https://user-images.githubusercontent.com/4571086/27728302-f0f95016-5d81-11e7-8c7c-847ecf1f0675.PNG)

In this case the destination is called New Botany Bay Depot, well if I copy and paste in my game, that destination naturally can not find it. Since the system really is Speamoea SO-G d11-409.

I think the solution would be to put, for example two buttons that go to EDSM, so that we know the real name of the target system. In addition to being able to see its corresponding information.

For example like this

![captura3](https://user-images.githubusercontent.com/4571086/27728327-fd901706-5d81-11e7-88b6-46b996c5e865.PNG)

Another solution would be in the main tab put the same button, next to the selected destination information. Such as .....

![captura4](https://user-images.githubusercontent.com/4571086/27728340-0716daa8-5d82-11e7-9dd4-f5a4aea1023c.PNG)

I do not know if I explain very well, but thanks for your attention

**Comment by robbyxp1** [comment]
EDSM button would be a good idea.

**Comment by tonkepen100** [comment]
Verry thanks, added the For 8.1

**Comment by robbyxp1** [comment]
So, its solved on 8.1, with EDSM buttons on to and from boxes, and a EDSM button on target.

not sure its going to solve your new botany bay issues, edsm does not seem to recognise that name on query..

**Comment by tonkepen100** [comment]
That is not a problem, it was an example that I put, the important thing is the buttons to edsm, so to know the real system.

Thank you very much for your interest, I thank you very much.
