### ISSUE TITLE
ED Discovery not downloading/updating. 

### ISSUE THREAD

**Issue by Timnus** [EDDiscovery/EDDiscovery#1109]
i keep having to search for an manually updating ED Discovery. the UI link has not worked for the last 3 updates. currently running 8090. is there a way you can get it to autodownload after you click on the update now?? better yet get it to do all update process via an option added?

**Comment by robbyxp1** [comment]
I've tried it - and I can't see a problem.  I'm reading the version from the server okay.

8.0.9 is the latest version.

Can you explain more fully whats happening.

**Comment by Timnus** [comment]
i would click on the UI link and nothing would happen. i would have to goto the web an manually find and download it. 
using a BM i already have.  Have a Wonderful Day!!!Timothy Deane

**Comment by klightspeed** [comment]
Are you clicking the "New Release Available!" text at the top of the window?  Does a "EDDiscovery release" window come up when you click this?

If the window does come up, does clicking "Msi Installer" download the MSI installer in your browser?

**Comment by Timnus** [comment]
window did not pop. i just go back to the EdDisc web and re-DL it. run installer and i have current version. i noticed the words were there but nothing clickable. supposed to be a hyperlink button/text area? showing as just a text msg.
 Have a Wonderful Day!!!Timothy Deane

**Comment by klightspeed** [comment]
What if you go into Help -> Check for Updates

Orange delight theme:
![image](https://user-images.githubusercontent.com/147116/28168508-abdf5326-6822-11e7-8c35-9542a745fe84.png)
Click the green area and it comes up with the info dialog
![image](https://user-images.githubusercontent.com/147116/28168608-fdfe2c40-6822-11e7-949b-e885cb0b136e.png)

Default windows theme:
![image](https://user-images.githubusercontent.com/147116/28168556-cd743a7e-6822-11e7-87c3-97d611a7aa62.png)
Click the text and it comes up with the info dialog
![image](https://user-images.githubusercontent.com/147116/28168582-e72a3afe-6822-11e7-9af1-69d85a2def4c.png)

It should also put a line in the log panel:
![image](https://user-images.githubusercontent.com/147116/28168741-69a4280a-6823-11e7-979f-2249ed060e73.png)
Note that this line is not clickable.

If going into Help -> Check for Updates doesn't bring up a dialog, but it does show the "Download new release!" text and the "New EDDiscovery installer available" log line, then you might have a corrupt dotnet install or a corrupt EDDiscovery install.

**Comment by klightspeed** [comment]
Oh, and if you're already at 8.0.9, then no dialog should come up yet, as we haven't released a new stable version yet.

**Comment by Timnus** [comment]
no new dialog at this time. will wait till next release. 

 Have a Wonderful Day!!!Timothy Deane

**Comment by robbyxp1** [comment]
Closed. No issue to solve
