### ISSUE TITLE
Add "Since last docking" to Statistics panel

### ISSUE THREAD

**Issue by RedfoxCh** [EDDiscovery/EDDiscovery#1111]
Picked up in EDD Discord: On the statistics panel we currently have columns for time-slots, e.g. "Last 24h" etc. Could the a column "Since last docking" be added? This would be great to keep track of one's current trip/expedition.

Another option (though very low priority, possibly not even needed at all, so just for your consideration) would be to have a manually configurable "From" date.

Thanks guys, keep up the stellar work.

**Comment by finwen** [comment]
Good idea


2017-07-06 8:58 GMT+02:00 RedfoxCh <notifications@github.com>:

**Comment by robbyxp1** [comment]
So, I've added a Last Dock to the drop down selector for travel/journal.

**Comment by finwen** [comment]
I added to stats panel

**Comment by mwerle** [comment]
There is a bug in that it picks up last docked events from multicrewing.

To be properly useful it should only track last docked for the players own ships.  (In general this may be an issue with other stats).

**Comment by klightspeed** [comment]
Would have to track if the commander is in a crew using the `JoinACrew` and `QuitACrew` / `LoadGame` events, and ignore any `Docked` events while the commander is part of a crew.

**Comment by mwerle** [comment]
I'd store the last docked event somewhere and update it when a new docked event occurs. The update function can then check if the player is currently multicrewing or not.

That way you're not processing the entire log all the time.

Apologies if it already works this way.

**Comment by klightspeed** [comment]
Perhaps add two new properties to HistoryEntry:
  - IsMultiCrew - this would be true if the the entry is in a multi-crew session - it would be set when a `JoinACrew` event is seen, and cleared when a `QuitACrew` or `LoadGame` event is seen.
  - LastDock - this would contain a reference to the last Docked event where `IsMultiCrew` is not set
