### ISSUE TITLE
EDSM Sync not updating credits or ranks

### ISSUE THREAD

**Issue by TalShaf** [EDDiscovery/EDDiscovery#1114]
It seems clicking on the EDSM Sync button doesn't update my credits or ranks on the EDSM website. Only flight logs are updated. Is this intended? 

I'm also using Elite Dangerous Market Connector, which does update ranks and credits, but I'd rather not be using 2 separate programs.

**Comment by andreaspada** [comment]
This is quite confusing to me, too. I'm not sure it's intended this way, or if it's a bug... 
By the matter, I noticed that inara is now able to parse some information from the journal, so maybe an API will be implemented, so we can sync in real time to it, which it will be great!

**Comment by robbyxp1** [comment]
Finwen have better look into this.

**Comment by klightspeed** [comment]
Ranks [HistoryList.cs:1340](https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/HistoryList.cs#L1340) and Credits [HistoryList.cs:1368](https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/HistoryList.cs#L1368) should be sent at the end of a history refresh.  The fact that they aren't suggests that either an exception is being thrown and being swallowed by the surrounding try/catch, or one of the exit conditions is being met (no API key, no commander name, Sync to EDSM disabled, no Rank journal entry, or no Progress journal entry).

**Comment by TalShaf** [comment]
When I click on the EDSM Sync button, the log only says:

EDSM sync begin
EDSM: Sending 4 flightlog entries
EDSM Systems sent 0
EDSM sync Done

**Comment by klightspeed** [comment]
Please check the "Log EDSM requests" box in the settings tab, log into Elite Dangerous, and try syncing to EDSM.  Then please look in `%LOCALAPPDATA%\EDDiscovery\Log\EDD_*.log`, and see if there are any lines containing `https://edsm.net/api-commander-v1/set-ranks` or `https://edsm.net/api-commander-v1/set-credits`

If you do post the log, make sure to mask out the API key in the lines.

**Comment by TalShaf** [comment]
18:58; GET https://www.edsm.net/api-commander-v1/set-ranks?commanderName=Deonon&apiKey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&Combat=2;20&Trade=3;64&Explore=3;38&CQC=0;0&Federation=0;28&Empire=0;0; 
18:58; {"msgnum":100,"msg":"OK"}; 
18:58; GET https://www.edsm.net/api-commander-v1/update-ship?commanderName=Deonon&apiKey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&shipId=1&type=Cobra Mk. III&cargoCapacity=16&cargoQty=0&fuelMainCapacity=16&fuelMainLevel=13.303226&shipIdent=msktnc&shipName=Miskatonic; 
18:58; {"msgnum":100,"msg":"OK"}; 
18:58; GET https://www.edsm.net/api-commander-v1/set-ship-id?commanderName=Deonon&apiKey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&shipId=1; 
18:58; {"msgnum":100,"msg":"OK","inDatabase":true}; 
18:58; GET https://www.edsm.net/api-commander-v1/set-credits?commanderName=Deonon&apiKey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&balance=10061285&loan=0; 
18:58; {"msgnum":100,"msg":"OK"};

**Comment by TalShaf** [comment]
Here is the detailed log. As you can see the credit amount for EDSM and the Companion data doesn't match. The companion data is accurate.

```
22:25; GET https://www.edsm.net/api-commander-v1/set-credits?commanderName=Deonon&apiKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx&balance=10061285&loan=0; 
22:25; {"msgnum":100,"msg":"OK"}; 
22:25; GET https://www.edsm.net/api-v1/systems?startdatetime=2017-07-12+16:41:30&enddatetime=2017-07-12+20:25:34&coords=1&submitted=1&known=1&showId=1; 
22:25; Companion Requesting ; https://companion.orerve.net/profile
22:25; Companion Response ; {"m_HttpResponseHeaders":["Pragma","Cache-Control","Content-Type","Date","Expires","Set-Cookie","Server","Strict-Transport-Security","Vary","X-UA-Compatible","transfer-encoding","Connection"],"m_Uri":"https://companion.orerve.net/profile","m_Certificate":null,"m_Version":{"Major":1,"Minor":1,"Build":-1,"Revision":-1,"MajorRevision":-1,"MinorRevision":-1},"m_StatusCode":200,"m_ContentLength":-1,"m_Verb":"GET","m_StatusDescription":"OK","m_MediaType":null}
22:25; Companion Data is ; {"commander":{"id":3077198,"name":"Deonon","credits":10741399,...........
```

**Comment by klightspeed** [comment]
Does it match the values in the latest LoadGame / Rank / Progress journal event?

**Comment by TalShaf** [comment]
Yes. Those values match.

**Comment by klightspeed** [comment]
Sounds almost as if the journals in the history aren't in order.

**Comment by TalShaf** [comment]
But then EDMC wouldn't work either. But it does.

**Comment by klightspeed** [comment]
As in the journals in EDDiscovery's history aren't in order.  i.e. the assumption that `HistoryList.historylist` is ordered by timestamp is not being met.

**Comment by TalShaf** [comment]
What should I do?


On Jul 13, 2017 01:56, "Ben Peddell" <notifications@github.com> wrote:

As in the journals in EDDiscovery's history aren't in order. i.e. the
assumption that HistoryList.historylist is ordered by timestamp is not
being met.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/EDDiscovery/EDDiscovery/issues/1114#issuecomment-314930607>,
or mute the thread

**Comment by klightspeed** [comment]
We will need to track down where this bug is.

**Comment by klightspeed** [comment]
Please sort your travel history by date descending, filter to LoadGame events, and post the topmost LoadGame event.

**Comment by TalShaf** [comment]
You mean this?

```
{
  "timestamp": "2017-07-12T21:29:15Z",
  "event": "LoadGame",
  "Commander": "Deonon",
  "Ship": "CobraMkIII",
  "ShipID": 1,
  "ShipName": "Miskatonic",
  "ShipIdent": "msktnc",
  "FuelLevel": 16.0,
  "FuelCapacity": 16.0,
  "GameMode": "Solo",
  "Credits": 10741399,
  "Loan": 0
}
```

**Comment by klightspeed** [comment]
Odd.

Do you have any duplicate commanders in EDDiscovery?

Are you able to find the LoadGame that matches the credit balance being sent to EDSM?

**Comment by TalShaf** [comment]
The third to last LoadGame matches the value: 


`Commander:Deonon, Ship:Cobra Mk. III, Name:Miskatonic, Ident:msktnc, Credits:10061285Mode:Solo, Not Landed, Fuel Level:16.0, Capacity:16.0`

AS for duplicate commanders, the drop down menu on the top right hand corner lists two entries: Deonon and something called hidden log. Clicking on hidden log causes a crash, and I am asked to attach the attached log. 

[Trace_20170713155611.0 - Copy.txt](https://github.com/EDDiscovery/EDDiscovery/files/1145435/Trace_20170713155611.0.-.Copy.txt)

**Comment by klightspeed** [comment]
Sending the credits, ranks and ship loadout are currently done at the end of the history refresh and not in the EDSM sync.  Only the credits from the most recent LoadGame event are sent, and not the calculated values from the ledger.

It is odd that in your case it's not seeing LoadGame events more recent than the one you posted.

It would also be good if we can move the loadout etc. sync into the edsm sync procedure.  That could pull the credits from the most recent event that has a credit balance, the ranks from the most recent event that has ranks, and the rank progress from the most recent event that has rank progress, rather than only taking them from specific events.  Those could be passed along in the same way that the material/commodity ledger is passed along.

**Comment by Florelit** [comment]
By the way, I have the same issue.

**Comment by Florelit** [comment]
found one thing on EDSM API FAQ

> Please note that ED Market Connector, starting at version 2.48, uses our new journal API, once you have send information with it, software not compatible with the new API will not be able to send information.
This behaviour is to avoid making a lot of duplicate requests to the server.

**Comment by klightspeed** [comment]
@Florelit it looks like when EDSM has switched to journal mode, it can take a little while before it will update the credits etc, or might not update them until it receives a LoadGame event.

v9.1 will send journal events to EDSM in the same way as EDMC now does.  It will no longer use the older Commander API to update ranks or credits.

**Comment by robbyxp1** [comment]
Sync rewritten.
