### ISSUE TITLE
[8.1.2.0] Voice Pack v4 settings reset each start

### ISSUE THREAD

**Issue by Taomyn** [EDDiscovery/EDDiscovery#1116]
I noticed today that I was still running Voice Pack v3, so I removed it then installed v4. Now every time I start EDDiscovery it shows in the log:

****
Setting voice pack control to default values, use the Add-On menu Voice Pack Configuration to reconfigure
****

And I lose any changes I made to its configuration. At first I thought it was because I was not hitting the OK button as it gets hidden by the window being too small, but I have expanded it and made sure to press it and it still forgets my settings.

**Comment by TalShaf** [comment]
Can confirm. I can get around this by manually editing the Global values in the Edit Addon Action Files menu, but I don't have a complete list of all variables (specifically the fuel reports).

**Comment by Taomyn** [comment]
I've gone back to v3 for now as that at least works, I found that v4 simply didn't work anyway. Had zero reactions to any events within the game.

**Comment by robbyxp1** [comment]
Will be fixed in 8.1.3

**Comment by Taomyn** [comment]
Thanks, looks better now but I can't edit the speech file from the menu, nothing happens but will log a new issue for it
