### ISSUE TITLE
[8.1.3] Menu "Edit speech file", nothing happens

### ISSUE THREAD

**Issue by Taomyn** [EDDiscovery/EDDiscovery#1118]
I can't edit the speech file from the menu, nothing happens.

It was a bit hit'n'miss with 8.1.2 but now with 8.1.3 it's worse.

**Comment by robbyxp1** [comment]
I fixed this in voice pack 4.0.0.1, are you using that version?

rob

**Comment by Taomyn** [comment]
Yes, but it seems to be ok today - I tried numerous times and it would not appear no matter what I did, so maybe the machine rebooting resolved some kind of conflict.
