### ISSUE TITLE
Dicovery and Voice Attack interaction....

### ISSUE THREAD

**Issue by tonkepen100** [EDDiscovery/EDDiscovery#1126]
Hello again here, I am going to propose a question that seems silly, maybe because I do not know how to do it or because it is not so much.

# 1.- DISCOVERY AND VOICE ATTACK INTERACTION

        **A.-** I have voice atack with a voice command, which tells you that inside the game, automatically show me the game main screen, well, VoiceAtack does it correctly, but the problem is that it always searches for the order Name of the program.

       **B.-** The name of the program that opens is ...

![discoveri](https://user-images.githubusercontent.com/4571086/28384320-8fc3a448-6cc4-11e7-98ce-a569c66931ec.PNG)

       The problem is as you can see in the screenshot is that it looks for the full name of the program, and Discovery shows in its title the name plus the version, for which Voice Atack seeks it as such.

      What happens to us when performing a Discovery update ?, because as he does not understand the title does not execute the order, since he wants to open the title of the version that was defined.

      It would be possible that the TITLE of Discovery was simply said name, and the version was reflected in another section ?.

      This will prevent us from having to continuously define Voice, which is what you have to open.

# 2.- CLOSE PROGRAM BUTTON

      **A .-** It also happens that when the program is opened, and we want to minimize it, we inadvertently give the X close, which is a nuisance, especially in the middle of the game.

![cerrar](https://user-images.githubusercontent.com/4571086/28384689-d353d9ca-6cc5-11e7-9703-e10b1b8f3db6.PNG)

           There are applications where you can define that when you give the button close, determine in which state the program will be.

So I in Options would put a check so that when you give the button close, you can define two conditions:

      **A.-** Minimize in Tray
      **B.-** Close in tray

The solution I think would be simple to perform in the tab options, is the most appropriate.

![options](https://user-images.githubusercontent.com/4571086/28384699-ddead046-6cc5-11e7-97ca-085a724fecfa.PNG)

PD :(Jajjaja, as you can see I'm very bad painting, I'll try to learn)

Thank you for your attention, which is always exquisite.

**Comment by phroggster** [comment]
The first point is valid, and something should probably be done to address this. As I don't use VoiceAttack, could you try using "EDDiscovery Version *" as the window title? I wonder if that'll pick it up, regardless of version or (developer-oriented) command-line options that can get added on.

However, I disagree with the second point, even though thousands of apps (often forcibly) offer it. "Close to systray" is just something that defies usability guidelines for little benefit. While yes, this could be done, I don't think it's something that should be done.

**Comment by tonkepen100** [comment]
In principle thank you very much for your quick response.

On point number 1:

Yes, as long as it's the same name, I'll explain ...

If every time we update VoiceAttack sees the name DICOVERY VERSION, it will always detect it as such, and therefore always activate it.

If, on the other hand, he sees that the name DISCOVERY VERSION +++ changes as such, he will not detect it.

SOLUTION: The header name of your program, would have to be equal always, regardless of the subtitle.


On point number 2:

Really as I do not understand English very well I know, or do not understand very well his explanation. You will forgive me, I understand that your reasons have to have to deny this soliloquy.

If with the number 1, you could accept it would be happy, in addition to being able to offer another grain to your wonderful ED: Discovery.

Thank you very much phroggster, I believe you made me happy today

**Comment by phroggster** [comment]
I think you misunderstood. Try setting VoiceAttack to look for a window called "EDDiscovery Version *". This *should* catch any version of EDDiscovery, regardless of version number. In other words:
![this](https://user-images.githubusercontent.com/14035789/28432518-d6e24d46-6d4d-11e7-9e45-b1bb17c88520.png)

**Comment by tonkepen100** [comment]
Ohhhhhhh, Thanksss.

I understood, that happens to those who take paellas on the beach. And we do not know English.

Thank you very much indeed.

**Comment by phroggster** [comment]
No problem. My Spanish is worse than your English! (No hay problema. ¡Mi español es peor que tu inglés!)

Regarding point 2 (Respecto al punto 2):
![untitled-2](https://user-images.githubusercontent.com/14035789/28433217-6d88fd74-6d50-11e7-837a-37236b66ba8b.png)

**Comment by tonkepen100** [comment]
Joderrrrrrrrrr, pues hablas mejor que yo Español.

Thank you very much indeed, you know that you are invited to some paellas in my land, besides some national championship bulls, you deserve it, thank you very much.

Send me a mail from you that you will see that I send you, you deserve to fuck.

Or send me here that I will send you the gift, (ostias); Admin@piro.biz

Mecago en todo con el chaval, esto si es un servicio esmerado.-

**Comment by phroggster** [comment]
No gift is necessary, I'm just glad to get this resolved. As for my Spanish, I frequently have to [cheat](https://translate.google.com). ;-)  Please reopen this issue if you have further questions.

Ningún regalo es necesario, estoy contento de conseguir esto resuelto. En cuanto a mi español, con frecuencia tengo que hacer [trampa](https://translate.google.com). ;-)  Vuelva a abrir este problema si tiene más preguntas.

¡Olé!
