### ISSUE TITLE
Difference between the number of steps between "Routes / Expeditions" and "Route Tracker" / "Trip Panel"

### ISSUE THREAD

**Issue by Teyar** [EDDiscovery/EDDiscovery#1132]
If you save a route under "Routes / Expeditions", an empty row is inserted at the end of the route. This means that a jump too much is indicated in the "Route Tracker" or "Trip Panel" (last jump with 0ly to the target system). This is not really a problem but more a beauty error and something confusing. Of course, you can remove the additional row, but if you save the route again, the additional row is inserted.

Certainly not the most important problem, but perhaps this can be turned off, so the correct number of jumps in the two panels is displayed.

Thanks in advance

**Comment by phroggster** [comment]
I missed this issue when I was working on it, but #1239 should have solved this. Expect it to be fixed in EDDiscovery 8.3.
