### ISSUE TITLE
[Idea] Cargo/Materials - Used/Available/Total

### ISSUE THREAD

**Issue by Uriei** [EDDiscovery/EDDiscovery#1133]
I would like to ask for a little textbox on the Materials and Commodities panels with Current cargo space used / Total Cargo Space.

Something like this:
![image](https://user-images.githubusercontent.com/6078221/28661594-7ed542b0-72b7-11e7-9519-d12e1dbf8630.png)

**Comment by robbyxp1** [comment]
> on its way
