### ISSUE TITLE
Support for tracking PS4 CMDR using PC  

### ISSUE THREAD

**Issue by DELTA-301** [EDDiscovery/EDDiscovery#1134]
I would love to use EDDiscovery on my pc to track the adventures of my PS4 ED CMDR. I notice trade data is mostly up to date between both platforms, so the ED PC and PS4 servers must be updated with almost matching data... I think combining the 2 systems through EDDiscovery would be a match made in the proverbial heavens...

Thanks, CMDR DELTA-301 PC & PS4

**Comment by klightspeed** [comment]
Unfortunately as far as I know there is no endpoint the program can listen to for events from the PS4 or XBox version of Elite Dangerous.  The only possibility would be to query the Companion API every 2 minutes or so (the cache lifetime of the Companion API), so if you jump more frequently than that it would miss jumps.  Additionally, there is some journal data that is not available through Companion API (e.g. what bodies have been scanned, or when you actually jumped).

**Comment by DELTA-301** [comment]
Well, that sucks.... Maybe Frontier will fix that. I hear they want to support 3rd party tools. Fingers crossed.

Thanks for your reply.
