### ISSUE TITLE
Invalid EXE after builiding in Appveyor CI

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#1136]
Not know why, but by many weeks I can't build anymore my commitment in appveyor as the resulted EXE, although the build was successful, is not valid: It do not have the icon applied, and it do not work at all.

How are you compiling the source tree?

**Comment by klightspeed** [comment]
It looks like the csproj was not updated to include all of the new DLLs in the portable build.

Additionally, there seems to be an error during init when starting from scratch.

**Comment by andreaspada** [comment]
Wow... indeed! Thanks and congratulations for the super fast fix! KUDOS

Enviado do meu iPhone

**Comment by robbyxp1** [comment]
Master is in heavy flux note. expect more problems!

**Comment by phroggster** [comment]
Once #1143 gets verified as Unix-safe and merged, this issue should be addressed in a more permanent and future-friendly form.
