### ISSUE TITLE
Cannot copy "Note" cell data from Travel History

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#114]
A recent change has prevented being able to copy "Note" cells from the Travel History. This includes the case when highlighting a range of cells which includes the "Note" column.
All other cells and cell combinations work as expected.

Raised by Spider95 on the forum:
https://forums.frontier.co.uk/showthread.php?t=138155&p=3588497&viewfull=1#post3588497

**Comment by robbyxp1** [comment]
Clicking on Note or distance changes the focus to their editing boxes, to speed up entry. Right click does not have a copy item.  Not sure of this priority.

**Comment by robbyxp1** [comment]
Closed. No change. You can copy areas, just click and drag
