### ISSUE TITLE
Unhandled Exception error 

### ISSUE THREAD

**Issue by cmdrhood** [EDDiscovery/EDDiscovery#1146]
Hi all I need help with this error , not sure this is me doing something wrong or not 

when installed I get this message after a 20 secs 

any ideas 

thanks Jon 

![ed issue](https://user-images.githubusercontent.com/30598544/28782594-82446f6a-7605-11e7-8aee-33a22b3966d8.JPG)

**Comment by klightspeed** [comment]
"Database or disk is full"

Is your disk full?

**Comment by cmdrhood** [comment]
no did read that and checked etc

not so sure about how I check the database though ?

**Comment by cmdrhood** [comment]
Ok sorted "user error" one disk was full !!!!!

thanks guys
