### ISSUE TITLE
Scan issue

### ISSUE THREAD

**Issue by Joghiarus** [EDDiscovery/EDDiscovery#1152]
Reporting scan issue as requested in the log: 

Cannot add scan to system - 
alert the EDDiscovery developers using either discord or Github (see help)
Scan object 33 Tauri BC 8 a d a in 33 Tauri

Kind regards.

**Comment by klightspeed** [comment]
I think we need to add 1 to the maximum depth.  This is a moon of a moon of a moon of a planet orbiting a binary pair of stars, giving a depth of 5.  StarScan.Process() currently only handles a depth of 4.

**Comment by robbyxp1** [comment]
Yep, will fix it, at some point. No ETAs yet
