### ISSUE TITLE
Map Proposal: True Perspective vs. Isometric Perspective

### ISSUE THREAD

**Issue by RedfoxCh** [EDDiscovery/EDDiscovery#116]
Besides being an awesome feature, something in the 3D map's representeation always seemed a little off to me. If I am not mistaken, the current 3D map view is rendered in an isometric perspective, which is not what our (my?) brain would naturally expect from a realistic depiction of a 3D object.

Is it possible to add a 'True Perspective' option when viewing the 3D map?

For reference, I googled this image which shows the difference between the two perspectives nicely: [https://myweb.rollins.edu/jsiry/tp.gif](https://myweb.rollins.edu/jsiry/tp.gif)

**Comment by finwen** [comment]
No idea but its probably just some OpenGL setting

2016-02-21 11:26 GMT+01:00 RedfoxCh <notifications@github.com>:

**Comment by gregmalcolm** [comment]
It's already Perspective. You may get tge illusion that it's not because of certain rendering options.

For example, the camera lense is pretty wide, the points are just rendering as solid colors rather than lit and the culling currently does wierd things when you get close.

**Comment by RedfoxCh** [comment]
Hey Greg, thanks for elaborating. Possibly I'm not using the correct terms. In the 3D map screenshot below I've highlighted two parallel rows of systems, both about 50kly long. In my basic understanding of a perspective view these two rows should gradually converge (visually, towards the vanishing point) the further away they get from the viewer's position. On the current 3D map they are rendered in parallel, all the way.

[http://i.imgur.com/2B53p4r.png](http://i.imgur.com/2B53p4r.png)

I hope this makes sense... and if this is just me, feel free to shelve the issue :-)

**Comment by gregmalcolm** [comment]
Maybe I'm wrong. Well, whether its perspective or other rendering quirks, I
think we can agree the rendering can be improved on

**Comment by klightspeed** [comment]
In 3.0.4, one can now switch between parallel (or orthogonal) projection and perspective projection.

**Comment by RedfoxCh** [comment]
Late to the party, sry - just wated to say the perspective view is fantastic, thanks!!
