### ISSUE TITLE
Map Proposal: Display 'Favourites'

### ISSUE THREAD

**Issue by RedfoxCh** [EDDiscovery/EDDiscovery#117]
In the 3D map systems are highlighted (red) if you've been there AND there are known coordinates - that's great.

In addition, how about being able to compile a personal list of 'favourite' systems that would also be highlighted, maybe in another way (symbol/color/...), even if you have NOT been there. Of course,  only systems with coordinates available in EDSM could be added to the favourites.

Why would I suggest this? I'd like to add my bucket list to the 3D map in order not to accidently bypass one of those POIs when close or even make a detour to check them out. Additionally, this feature could probably be used for a number of other purposes.

**Comment by Red13x3** [comment]
That is a truly brilliant idea!!

+1, please. 

CMDR Red_13

--
Mark
iPhone: 0402 322 901

**Comment by djadjok** [comment]
+1, Count me in
CMDR DJA

**Comment by RedfoxCh** [comment]
If this feature could be combined with a file-based import-feature, I could very well imagine ppl compiling and sharing really cool lists (e.g. planetary nebulae, ELWs, BHs, NSs, ...) and sharing them. And if the import-feature would not only support local files, but also URL-references, you could actually have automatically updating favourites of different kinds, based on community-maintained lists available via URLs. If done right, this would really leverage the existing 3D-map functionality to provide really awesome information, thus further increasing its usefulness for existing users and the appeal for new users.
Now, if I only had the ability to contribute code...

**Comment by Sentynal** [comment]
What would be useful is that the 'favourite' system pops up (in some way) if it is nearby (for a user defined interpretation of nearby)...

**Comment by robbyxp1** [comment]
Bookmarks added. Gal map objects to come.
