### ISSUE TITLE
Suggestion regarding Scan Information

### ISSUE THREAD

**Issue by XeroWonToo** [EDDiscovery/EDDiscovery#1175]
It's a small redundant thing; I've noticed it says both "Terraformable" and "Candidate for Terraforming" when scanning terraformables.

I've got nothing else, this thing is legit.

Thanks again for all your work on this!

**Comment by robbyxp1** [comment]
not sure where you mean..

From EDSM
19 Phi-2 Ceti C 6

Water World, Nitrogen
Earth Masses: 0.2800
Body Radius: 4.13km
Surface Temp: 293K
Surface Pressure: 0.52 Pa
Distance from Arrival Point 8,702.0ls
Orbital Period: 0.0 days
Semi Major Axis: 0.0km
Orbital Inclination: -0.090°
Arg Of Periapsis: 344.250°
Rotation Period: 0.0 days
Candidate for terraforming
Estimated value: 625411

Which panel are you saying? The travel history? The spanel? The scan panel?

Thanks

**Comment by klightspeed** [comment]
The info line contains a summary of the planet details (class, landable, terraformable, atmosphere, gravity, radius).

**Comment by XeroWonToo** [comment]
Fair enough.  I realize now, too, it was kind of a knit-pick thing.  
Seriously though, I really do enjoy using the ap.  

Thanks again for all the hard work you guys put into this.
