### ISSUE TITLE
No sync with EDSM

### ISSUE THREAD

**Issue by Raven144** [EDDiscovery/EDDiscovery#1177]
Hi, i notice today that EDDiscovery couldn't sync with EDSM, i don't know if it's an issue with the program or the fact that the website haven't renew it's security certificate, here the message i get ;

Download of EDSM systems from the server failed (no data returned), will try next time program is run

I've already close and rerun EDDiscovery but it changes nothing.

**Comment by klightspeed** [comment]
Yes, this would be due to the expired certificate.  Downloading systems from EDSM should work again once the certificate is renewed.
