### ISSUE TITLE
EDDiscovery doesn't launch properly

### ISSUE THREAD

**Issue by barroomhero07** [EDDiscovery/EDDiscovery#1178]
I really want to use this handy dandy program, but I can't use it. I've uninstalled and reinstalled many times and it does the same thing every time. This is all that I can use of EDDiscovery. 

![image](https://user-images.githubusercontent.com/30814050/29049432-dd675df0-7ba3-11e7-9899-43e8cbcddf52.png)

**Comment by klightspeed** [comment]
Please try holding shift while launching EDDiscovery - this should fix this sizing error.

**Comment by barroomhero07** [comment]
You're a scholar and a saint. That did it. Thanks!
