### ISSUE TITLE
Cannot reset to default theme - cannot use application

### ISSUE THREAD

**Issue by dthomson39** [EDDiscovery/EDDiscovery#1179]
Hi

I have been using EDDiscovery with the default theme and it has been functioning perfectly - I thought I would switch to another theme but that caused problems in that the text is invisible (white on white) although I can feel about for everything but the settings button - the theme has no scroll bar either so I cannot get to the section dealing with changing the theme.
In one of the future updates would it be useful to have a reset to default theme on one of the dropdown menus so that you can always get back to the default status?
regards

**Comment by robbyxp1** [comment]
The menu Tools has a Edit Theme option
Can you not at least get to that?

**Comment by dthomson39** [comment]
Thanks for the comment but editing the colour scheme doesn't solve my problem. I can't get it back to a manageable layout - there must be some way of getting the app back to its default scheme.

**Comment by robbyxp1** [comment]
So, if its a layout program, launch the program with the shift key held down.  It then won't remember the columns and position layout

**Comment by phroggster** [comment]
Version [8.2.3](https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_8.2.3) introduces a [Safe Mode](https://github.com/EDDiscovery/EDDiscovery/wiki/Safe-Mode) interface that will allow you to reset the theme when things go horribly awry. Please try updating, then holding down shift while you start the app, then clicking *Reset Theme* and *Run* to hopefully get things going.

Please report back on whether or not this update and the *Safe Mode* interface is able to recover things for you.

**Comment by phroggster** [comment]
Closing, no contact, presumed resolved.
