### ISSUE TITLE
Trilateration Enhancement: Keep reference systems between program restarts

### ISSUE THREAD

**Issue by Sheepzz** [EDDiscovery/EDDiscovery#118]
I have added a whole bunch of systems that still need coordinates to the trilateration list and gradually they get "ticked" off. This works really well (thanks guys).

It would be great if the list of systems in the trilateration window persisted between restarts of the program, as currently I cannot close EDDiscovery without losing the list.

Sheepz

**Comment by iainross** [comment]
I've released a change for the next version that allows you to add reference systems to the 'Wanted Systems' grid (off a context menu) and your locally added wanted systems will persist between sessions so you can click on the system in there to add back in to your reference systems when you restart, same as the EDSM wanted systems.

**Comment by Sheepzz** [comment]
Excellent. Thank you, I look forward to playing with the next version.
