### ISSUE TITLE
UNHANDLED UI EXCEPTION / OBS Addon Related?

### ISSUE THREAD

**Issue by jdm12983** [EDDiscovery/EDDiscovery#1181]
Suddenly started getting these random "UNHANDLED UI EXCEPTION" errors popping up with two different computers running EDDiscovery. (trace logs attached)

It's weird because for a while there was no issues; then now there is. However, I no longer get the errors (the seem to appear at launch) if I disable the OBS plugin/addon. Not sure it's OBS Addon only - but certainly related to it.

[Trace_20170808174246.0.log.txt](https://github.com/EDDiscovery/EDDiscovery/files/1209843/Trace_20170808174246.0.log.txt)
[Trace_20170808180221.0.log.txt](https://github.com/EDDiscovery/EDDiscovery/files/1209845/Trace_20170808180221.0.log.txt)
[Trace_20170808180525.0.log.txt](https://github.com/EDDiscovery/EDDiscovery/files/1209844/Trace_20170808180525.0.log.txt)

**Comment by klightspeed** [comment]
This looks like ExpandStringFull needs to handle `line` being null (e.g. due to looking up a non-existent variable).

**Comment by robbyxp1** [comment]
If a ship did not have a name, using the action variable EC_Ship_name would crash as it was null.  Will now be set (along with others) to empty string
