### ISSUE TITLE
"Nearest Stars" panel: Add "Is in History" attribute

### ISSUE THREAD

**Issue by RedfoxCh** [EDDiscovery/EDDiscovery#1186]
When far out many/most/all entries on the "Nearest Stars" panel are my own latest visited systems, thus making it hard/impossible to see, if anyone else has been around that area.
So my suggestion is to add an attribute/culumn which shows, if the listed system is in one's History. A filter for that attribute might also make sense, but is not really necessary. In a luxury-version one could also think about being able to directly call the system's EDSM-page from an entry (or copying the system name to the clipboard when selecting an entry, similar to how this is implemented on the trilateration table).
Obviously, this enhancement has a very low priority.

**Comment by phroggster** [comment]
I marked this "Low Priority" solely to honour your last sentence, but will see what we can do to address this in a timely manner. I do agree that it would be nice to have a filtering mechanism in place.

**Comment by robbyxp1** [comment]
For 8.3
