### ISSUE TITLE
Can't Open 3D Map without Crashing

### ISSUE THREAD

**Issue by zschmeez** [EDDiscovery/EDDiscovery#1188]
Hello! I am a fan of your application. It provides lots of useful information, and it works with multiple accounts. However, I have one issue I have been unable to resolve. Whenever I try to open the 3D map, the program crashes. It works perfectly the rest of the time, but this one feature appears to be broken. I have attached a screenshot of the error message, along with the log file from the crash. Hopefully you can fix this issue, since I find it to be one of the coolest features of the application. Thanks!
[Trace_20170811140709.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/1219124/Trace_20170811140709.0.txt)
![eddiscovery_2017-08-11_14-11-17](https://user-images.githubusercontent.com/18506686/29232522-e2815598-7ea0-11e7-8058-a211e68a04d2.png)

**Comment by phroggster** [comment]
`ChoosePixelFormat()` is an odd place to crash at... Certainly something going on, but I doubt that it's a problem in EDD.

Try rebooting and/or updating your graphics card drivers, and let us know if the 3d map works after that.

**Comment by zschmeez** [comment]
It's been happening for a while now, though several reboots and graphics
driver updates. The only thing I can think of that might cause that is my
strange display setup. I've got 2 monitors running off my R9 280 dedicated
graphics card, and a third monitor running off of Intel Integrated Graphics
on my i5 4670k. This is because the R9 280 is unable to handle 3 separate
timings for monitors, so you can only have 2 at a time.


-Zack

**Comment by phroggster** [comment]
I wonder if OpenTK is going the pixel format for one device context (say, the Intel), then freaking out when it can't share it with the Radeon... Can you let me know if it works without the Intel-attached monitor in use (either disconnected or disabled)?

**Comment by zschmeez** [comment]
Alright, I disabled the third monitor running from Integrated Graphics, and it worked. I guess I can just disable the third display whenever I need the 3D view. Thanks!
![eddiscovery_2017-08-11_16-27-03](https://user-images.githubusercontent.com/18506686/29235245-0c369234-7eb2-11e7-875e-328a230616a0.png)

**Comment by phroggster** [comment]
Do you remember if the issue actually started once the third monitor was added, or have you ever been able to launch it while all three were connected? Also, and this may not be ideal, but if you re-enable that third monitor, try launching the 3d map while EDDiscovery is on various different monitors. It may start on one graphics card / monitor, but not the other.

Meanwhile, I'll dig in and see if there's any way for us to influence things for the better, but I wouldn't get your hopes up too high.

**Comment by zschmeez** [comment]
It works when I open the application on a monitor running from the
dedicated graphics. It only seems to be crashing when I try to open 3D view
while on the Intel monitor. I feel like this is a small enough issue where
you do not need to spend your time troubleshooting it. It's not an
inconvenience for me to have to simply move the window to a different
monitor to use.
Thank you very much for the help. I can't wait to see what you guys can do
next.

-Zack

On Aug 11, 2017 4:36 PM, "Lee" <notifications@github.com> wrote:

Do you remember if the issue actually started once the third monitor was
added, or have you ever been able to launch it while all three were
connected? Also, and this may not be ideal, but if you re-enable that third
monitor, try launching the 3d map while EDDiscovery is on various different
monitors. It may start on one graphics card / monitor, but not the other.

Meanwhile, I'll dig in and see if there's any way for us to influence
things for the better, but I wouldn't get your hopes up too high.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/EDDiscovery/EDDiscovery/issues/1188#issuecomment-321940548>,
or mute the thread

**Comment by phroggster** [comment]
Happy to help, and I'm glad it was something so seemingly trivial. One last question and I'll let you get on your way:

What happens when you open it on the AMD-driven monitor, then drag it to the Intel-driven monitor?

**Comment by zschmeez** [comment]
Strangely enough, it will work if you drag it back and forth. It doesn't
crash if you open 3D view first on the AMD side, close 3D view, move the
window to the Intel side, and click 3D again. It seems to have something to
do with where the 3D view feature was first opened in the session. I guess
this is just one weird quirk that happens for some mysterious reason.

I'm always glad to help, and if you need anything, be sure to let me know.

Thanks,

-Zack

On Aug 11, 2017 4:58 PM, "Lee" <notifications@github.com> wrote:

Happy to help, and I'm glad it was something so seemingly trivial. One last
question and I'll let you get on your way:

What happens when you open it on the AMD-driven monitor, then drag it to
the Intel-driven monitor?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/EDDiscovery/EDDiscovery/issues/1188#issuecomment-321942657>,
or mute the thread

**Comment by klightspeed** [comment]
If I recall correctly, the 3D context is created the first time the 3D map is opened, and is kept around between closing and re-opening the 3D map.  It's possible that the Intel OpenGL driver can't handle something the 3D map is doing - e.g. perhaps it doesn't support the size textures being used (1024x1024 for the grid coord textures), or the number of textures being used (currently 1 texture per system within 2000ly of the current location).

**Comment by zschmeez** [comment]
I only have 256 MB of RAM allocated to the integrated graphics. Could that
have something to do with it?


-Zack

**Comment by phroggster** [comment]
@klightspeed The 3d context description is accurate, but it's got nothing to due with the texture requirements. This is way earlier in the process, when OpenTK is initially trying to establish a graphics context (`OpenTK.GLControl.OnHandleCreated -> OpenTK.WinGLControl.CreateContext`).

@zschmeez  I strongly doubt this has anything to do with the amount of vRAM dedicated to it. We haven't event made it to trying to allocate vRAM or send data over a bus. This is happening when we say "Hey OpenTK. Yeah, can you grab me a GL context so that I can draw cool stuff in 3D?" and OpenTK is responding "No, I'm sorry but something went seriously wrong when I [asked your graphics driver to allocate one](https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/Windows/WinGraphicsMode.cs#L188) with all of the settings at default (despite your graphics driver saying that it *[could](https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/Windows/WinGraphicsMode.cs#L88)* do it, just 100 lines of code previously)."

Can you try grabbing and installing the [Intel Graphics Driver for Windows [15.40]](https://downloadcenter.intel.com/download/26984/Graphics-Intel-Graphics-Driver-for-Windows-15-40-?product=75048)?

**Comment by klightspeed** [comment]
I think I recall the same sort of thing with some older Intel chipsets - the Intel driver didn't support OpenGL 2.0 or something like that, and we had to use a MESA wrapper for a program that used OpenGL.

I notice that it queries what Wgl (Windows OpenGL) supports, without specifying a device.  Sounds like it assumes that all graphics adaptors support the same OpenGL version and extensions.

**Comment by phroggster** [comment]
Sounds reasonable, and yeah, Intel's totally dropped extensions and support from (usually older) products over the years, but certainly not [wglChoosePixelFormatARB](https://www.khronos.org/opengl/wiki/Creating_an_OpenGL_Context_(WGL)#Pixel_Format_Extensions) which is all but universal. Half tempted to wire in a debug OpenTK.dll and go through the hassle of enabling my iGPU to see if I can reproduce.
