### ISSUE TITLE
EGO fail to send event

### ISSUE THREAD

**Issue by kolsurma** [EDDiscovery/EDDiscovery#1194]
At about (edit with correct time) 19:30 UTC the Elite Galaxy Online database seems to have become overloaded which has exposed an issue for the synchronization EDD does to it. When the EDD fails to send an event it logs it and then sends the next in the queue (after the delay), the failed event never returns to the queue.

The solution should be something like the following: 

- On failure to send an event the event should be placed back in the queue and a back-off period should be enacted.
- On multiple subsequent failures the back-off period should increase.

**Comment by finwen** [comment]
EDD does not reties to send a event but it remembers it so next time  you
start EGO sync it will try with it again.

Will maybee ad extra slowdown if we have multiple  fails. Might be a good
idea to get some rest for  EGO. Just no idea on how long to wait :)

2017-08-12 21:15 GMT+02:00 Surma <notifications@github.com>:

**Comment by kolsurma** [comment]
the current 5 second wait is okay if everything's working, on failure perhaps increase by 5 seconds up to... 300 seconds? After a success (or two) it should return to the normal wait period.

All IMO of course :)
