### ISSUE TITLE
Neutron Star Icon wrong when downloaded from EDSM

### ISSUE THREAD

**Issue by EoD** [EDDiscovery/EDDiscovery#1195]
Currently, Neutron stars look like M-class stars.

![image](https://user-images.githubusercontent.com/293499/29250026-5fe5dc20-803b-11e7-8c7e-5379c57e7370.png)

**Comment by klightspeed** [comment]
It looks like you have the B star selected, and the image is the default star image.

The type returned from EDSM is "Neutron Star", while EDDiscovery is expecting "N" (the type from the journal).

**Comment by klightspeed** [comment]
EDSM converts the star types from the incoming journals into friendly names, so we need to do the reverse.

"Herbig Ae/Be Star" => "AeBe"
"Neutron Star" => "N"
"Black Hole" => "H"
"S-type Star" => "S"
"C Star" => "C"
"T Tauri Star" => "TTS"
"Wolf-Rayet Star" => "W"
"MS-type Star" => "MS"
"CN Star" => "CN"
"CJ Star" => "CJ"
"Wolf-Rayet C Star" => "WC"
"Wolf-Rayet N Star" => "WN"
"Wolf-Rayet NC Star" => "WNC"
"Wolf-Rayet O Star" => "WO"

The following types are not round-tripped:
A_BlueWhiteSuperGiant should map to "A (Blue SuperGiant) Star"
F_WhiteSuperGiant should map to "F (White SuperGiant) Star"
M_RedSuperGiant should map to "M (Red SuperGiant) Star"
M_RedGiant should map to "M (Red Giant) Star"
K_OrangeGiant should map to "K (Orange Giant) Star"

**Comment by EoD** [comment]
@klightspeed this does not work in 8.2.5.0, is this already in this release?

**Comment by EoD** [comment]
Well, the issue seems to be fixed in 8.3. Thanks!
