### ISSUE TITLE
Fail to add system to expedition/trilateration table

### ISSUE THREAD

**Issue by kolsurma** [EDDiscovery/EDDiscovery#1196]
Version: 8.2.2.0

When trying to add a system, e.g. Sol, to the expedition / trilateration table the entry is deleted and "Only systems with coordinates or already known to EDSM can be added" is displayed in the trilateration log.

Edit: This was installed on top of older versions, trying it in a clean install now. 
Update: Failure, same message.

**Comment by klightspeed** [comment]
This looks like the autocomplete is clearing the cell when pressing Tab without selecting an entry.

**Comment by kolsurma** [comment]
Even when I select an entry it still clears the cell.

**Comment by klightspeed** [comment]
I think what is actually happening is that ExtendedControls.AutoCompleteDGV.CellEditControl is failing to copy its value to the cell.

In CellValidating, e.FormattedValue is set to the desired value.  However, ExtendedControls.AutoCompleteDGV.CellEditControl.OnTextChanged is never called, and so ExtendedControls.AutoCompleteDGV.CellEditControl.EditingControlValueChanged is never set to true, and the text is not copied to the cell.

Seems almost as though `OnTextChanged` is not called when the `TextChanged` event is handled.
