### ISSUE TITLE
Feature request:  Focus to move to latest added System, Distance from... field. [Enter] updates.

### ISSUE THREAD

**Issue by Red13x3** [EDDiscovery/EDDiscovery#12]
Synopsis: When adding a new system to the Travel History, make the focus (or the selected system) be on the newly added line, and preferably the insert cursor in the "Distance from..." field, ready to accept immediate input when Alt-Tab into it. Allow entry of data then allow the [enter] key to update the field.

Reasoning: I love the feeling that I am "helping out" the community of ED by adding in unknown distances between stars I jump to. That's one of the main reasons I like this program. And so when I am on a mission or delivering materials for my Power, I always have EDD open and ready to enter any unknown distances between those unnamed stars.

In the middle of the jump routine, the new star appears at the top of the Travel History list... But the focus is not on that new system. It remains on the last star you clicked on. When you want to quickly jump between systems, half way through the jump routine, the new system appears in EDD. Perfect! But the focus not being in the "Distance from..." field means you have to use the mouse to madly click the new system, then into that field, enter the data, and click on the Update button. All before the jump routine ends and you're flying into the sun! :)

Which brings me to the second part of this request: When entering data into the "Distance from..." field, please allow the [Enter] key (including the one on the numeric keypad) to do the same task as clicking on the Update button.

Thanks for your consideration.

**Comment by SamMackrill** [comment]
If you do this please make this just an option "Track Current System". Personally I like it to stay where I am looking on the list,

**Comment by Red13x3** [comment]
Yeah, I'd agree with that. Have a checkbox in the Settings tab that enables "Auto focus on new systems" or not.

**Comment by gregmalcolm** [comment]
Sounds reasonable, may look into it.

Although I wonder how much value the "distance to" box actually gives? Most of the bubble systems are already transliterated and there's a low probability a deep space system will get enough visits from enough people to actually transliterate it.

**Comment by Red13x3** [comment]
Is that the purpose of that distance box, to eventually trilaterate any start by "incidentally" getting 4 distances from know stars?

Never thought of it that way. Just figured I was "doing my part" and adding data to the community. I fill that data in pretty religiously when I'm out in the black, and to speed things up, it would be good to have the focus automatically go in there for the newest system. (But
Someone has asked to have that as a checkbox option as they didn't want that functionality)

Mark

--
Mark Jelic
iPhone: 0402 322 901

**Comment by mwerle** [comment]
Eh; I religiously enter the "distance to next system" when jumping. So almost the same workflow I guess. I figure this gives each system a minimum of 2 distances which will make it quicker to eventually trilaterate them.

I opened a near-duplicate request here:
https://github.com/EDDiscovery/EDDiscovery/issues/86

**Comment by Red13x3** [comment]
This can be closed, as the new "Fast Travel" option does exactly what I wanted it to do. Thanks to whomever implemented that! :)
