### ISSUE TITLE
Lots of space needed in "AppData\Local\EDDiscovery"

### ISSUE THREAD

**Issue by philelzebub** [EDDiscovery/EDDiscovery#1200]
Is there any way of stopping EDD from eating up 4GB+ in the "X:\Users\XXXX\AppData\Local\EDDiscovery" location? In my case it's an SSD with limited space so I could do without it, if possible. It's currently taking up 4.45GB. 
I changed the installation location to my regular hard drive but this "AppData\Local\EDDiscovery" data is still present - can it be moved?

**Comment by andreaspada** [comment]
I think you should use the portable version, which store its data in the same folder as EDDiscovery. Mine, which is 4.49 GB, is stored in the EDDiscovery folder. It's also better for backup, IMO.

**Comment by philelzebub** [comment]
I'll certainly give that a shot, ta!

**Comment by robbyxp1** [comment]
Latest version 8.2.3.. hold down shift key when booting. Use the move databases option to move them somewhere else.

**Comment by phroggster** [comment]
As Robby mentioned, [8.2.3](https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_8.2.3) introduces a new [Safe Mode](https://github.com/EDDiscovery/EDDiscovery/wiki/Safe-Mode) interface in the app that will allow you to move your databases out of %LOCALAPPDATA%. While the disk space will still be used, it will allow for you to put it onto a different drive that has some more free space for this kind of thing.

Alternatively, as Andrea mentioned, the portable version will automatically store this stuff along-side wherever the executable is run (well, under a `data` subfolder thereof).

If neither of these approaches is suitable for whatever reason, please reopen this issue. Meanwhile, I'm going to go ahead and close it.
