### ISSUE TITLE
Local Development Requirements

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#1201]
Hi to everyone. I want to start coding in windows - my previous experiences are in Linux and OSX - and, as I use EDDiscovery extensively and I would love to help, I want to start tweaking here and there for some little ideas.
Could some lovely soul give me a clue on the requirements for an EDDiscovery local development setup? I already have Visual Studio Community edition installed. What I need more?

All the best,
Andrea

**Comment by klightspeed** [comment]
As long as you have Visual Studio 2015 or 2017 with git and nuget, you should be good.  All external dependencies are in Nuget packages - no requirement for external installs (except the requirements for Visual Studio itself).

Profiling memory and CPU usage does require a professional edition of Windows (Visual Studio edition doesn't matter).  Also, if you have dotnet 4.7 installed, then memory profiling is only possible with Visual Studio 2017.

**Comment by andreaspada** [comment]
Great! Indeed, Nuget handled all requirements. Thanks you so much!

**Comment by phroggster** [comment]
Your dev environment shouldn't impact anything, and [pull requests](https://github.com/EDDiscovery/EDDiscovery/pulls) are encouraged; just try to keep them on-task and with as minimal changes as possible (i.e. don't re-write the entirety of the database code merely to assign a tool-tip to a button, etc.).

Also something to keep in the back of your mind: EDD is intended for use on Max OS as well as any Windows machine that supports .NET 4.6 (Vista SP2, 7 SP1, 8, 8.1, and 10). Anything that isn't supported over all of those platforms (such as DLLImport or p/invokes) will need to ensure that it isn't introducing problems where such API isn't supported.

**Comment by finwen** [comment]
We still support Visual studio 2015  so you can just go ahead and work. and contribute your ideas.

**Comment by finwen** [comment]
One big tip is to talk to us other developers on our Discord server.    You will find the discord link in EDDiscoverys help menu.

**Comment by andreaspada** [comment]
Great! Many thanks to all, I'm an huge fan of this project, and I can't wait to help in some way. I still do not know if I will have time and knowledge to help in any substantial way, but I'll try.

All the best!

**Comment by phroggster** [comment]
I'm going to go ahead and close this. Feel free to hop on [Discord](https://discordapp.com/invite/0qIqfCQbziTWzsQu) and chat with us if you have any further questions, or feel free to reopen or this issue.
