### ISSUE TITLE
Route/Expedition tab: multiple "unsaved route" msg boxes

### ISSUE THREAD

**Issue by kolsurma** [EDDiscovery/EDDiscovery#1210]
Version 8.2.3.0

When trying to switch routes multiple "Unsaved route" message boxes appear sequentially. 

* If "No" is selected on each box the selected route is NOT loaded.
* If "Yes" is selected on the first message box the correct route is loaded but the data in the previous route is not saved.
* If "No" and then "Yes" then nothing happens, the changed data is not saved and I stay on the current route.

**Comment by phroggster** [comment]
There were a couple of issues that caused this, but they've all been addressed and should be included in the next release.
