### ISSUE TITLE
[BETA] CMDR History/Journal not updating

### ISSUE THREAD

**Issue by AndySpawn** [EDDiscovery/EDDiscovery#1215]
Noticed last night that the History/Journal doesn't update for my [BETA] CMDR in the current Closed Beta 2.4.  For some reason the log files are named "JournalBeta.170818212329.01" this time around; and EDDiscovery won't read them unless I remove the "Beta" part from the filename.

There's also a number of "Unknown" Events in the History/Journal; possibly something related to the new content.  I'm not sure, as I haven't figured out a pattern to them yet. But some do coincide with "Music" in the Journal Log File, while others are the Community Goal, and Outfitting.

**Comment by finwen** [comment]
EDDiscovery 8.2.4 will solve it.
https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_8.2.4

2017-08-21 7:39 GMT+02:00 AndySpawn <notifications@github.com>:

**Comment by AndySpawn** [comment]
Thanks Finwen.  I'll check that out later.
