### ISSUE TITLE
Storage Requirements

### ISSUE THREAD

**Issue by zschmeez** [EDDiscovery/EDDiscovery#1219]
Hello! Me again! I just have a quick question/request...

Would it be possible to move the application data files from the AppData folder? I only have a 120 GB SSD, and EDDiscovery's data files are taking up 6.3 GB of that storage. Would it be possible, in the future, to have an option to select the directory where that data is stored, so I can reclaim that precious space on my SSD?

Thanks!

**Comment by phroggster** [comment]
Hold down shift when you start the application (8.2.3 or better) to launch into what is known as "[Safe Mode](https://github.com/EDDiscovery/EDDiscovery/wiki/Safe-Mode)." From there, the "Move Databases" button will be your friend.
