### ISSUE TITLE
Feature Request: CSV export

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#122]
Dump all the data in the currently-selected travel history to CSV.

Alternatively have a separate filter selection dialog for the CSV export.

**Comment by robbyxp1** [comment]
Good idea, I've thought of this one, and I know its been asked for.

**Comment by robbyxp1** [comment]
Actually, an .cvs import/export would be also be good. 

That way we could back up the exploration list to another file.  I know you can copy the .db but thats a bit esoteric for the average user.

The import would only add if the current database does not have the system/time pair.

But first an export option ;-)

**Comment by Red13x3** [comment]
Yep, I asked for this back in the teens. :)

I'd also like to "import" and add to my personal DB, because before I started using EDD, I recorded every jump in Excel, but they aren't in EDD now, which is annoying. 

--
Mark
iPhone: 0402 322 901

**Comment by Red13x3** [comment]
+1 x infinity!

:)

--
Mark
iPhone: 0402 322 901

**Comment by mwerle** [comment]
Yes I added it based on forum feedback (and because I've wanted it myself).
Started work on an ImportExportHandler subsystem but not sure if I have the time (or the C#'skills) to do so in a timely manner. In general I'm not sure what the Best Practices are for extracting data from another form and in general how to link multiple forms together.  Generally speaking adding these sort of dependencies amongst objects is frowned upon.

The other question is should the data be exported from the TravelHistory (in which case we'd automatically get the filtering that's built into that), or should it come directly from the database?

**Comment by Red13x3** [comment]
It should be the Travel History, imho. 

--
Mark
iPhone: 0402 322 901

**Comment by gregmalcolm** [comment]
Maybe I'll hit this one this week. Been a while since I contributed to EDD directly. Note though: workaround is exporting via Sqlite Database tool

**Comment by gregmalcolm** [comment]
Question: Why would we want a csv dump if the travel historu when you can just copy and paste it into Excel. Do you lose information? Ease of use? I'll admit I need to go back and read up on the various asks

**Comment by gregmalcolm** [comment]
Duplicates #20

**Comment by Red13x3** [comment]
Although this has expanded it by adding import functionality as well, which I think for pedantic people like me, would be great. :)

--
Mark
iPhone: 0402 322 901

**Comment by robbyxp1** [comment]
Well, it should be a graphical button in travel history. I would do the export first, as that's the most useful.
I think it should export all the system data known, not just the stuff in the columns.

So that makes drag and drop not work.

**Comment by mwerle** [comment]
There was a bug report that copy-paste from the grid is broken. Besides that's a fairly unintuitive way of doing it.

Another button? These tabs are getting pretty crowded..  I was doing it via a menu item (File -> Export) and a dialog box..

And yes, the request was for all the data, not just the columns.

**Comment by Red13x3** [comment]
Yes, I agree that copy/paste from the grid is not intuitive.

And agree that it should be “File > Import...” and “File > Export...”  with a dialogue box following either.

But it should be just the user’s data (as in, only the systems they have visited in the Travel History) and could be filtered as to what the user currently has in the view (as in, All, Last 20, etc.).  But it should be ALL the data that is saved in the DB for their travels, not just the columns displayed. Should be All the data available for each record. (Sorry, don’t actually know what is stored for each, but for example, the Prospecting Data that is “Coming Soon TM” should be included.)

RED_13

**Comment by djadjok** [comment]
Just start to wonder if there is a method to import comments (in my case from file generated by slopey'e BPC) when found this feature request, so, +1 to import feature.

**Comment by mwerle** [comment]
@djadjok - could you provide an example file please?

**Comment by djadjok** [comment]
Hmm, it's already some month's passed since the last time I've used BPC - there was an export option in three different file formats: csv (but i reality not "comma separated") + 2 MS excel formats if I remember well. I've heard that the project is revived and newer version available - I'll check this and try to get some examples, but May be the author -  commander Slopey - is a better source of information

**Comment by robbyxp1** [comment]
still on my list

**Comment by finwen** [comment]
Should be solved with EDDiscovery 5.0.2
