### ISSUE TITLE
Request for some indicating of missing bodies on scan panel

### ISSUE THREAD

**Issue by robbyxp1** [EDDiscovery/EDDiscovery#1222]
... or wireframes?

**Comment by EoD** [comment]
The idea is basically to identify missing bodies according to the default naming scheme. 

Several comments about this from discord


> EoD: [...] you have scanned (or downloaded from EDSM) planet 1 and planet 8, there would be wireframes for planets 2 to 7
> EoD: [...] if you would scan a planet "C 7 E" and suddenly 2 sun-, 6 planet- 4 moon-wireframes would pop up.

>Redfox: Regarding the suggested wireframes for unscanned bodies based on the numbering: The current rule seems quite simple and clear - only scanned objects appear, plus wireframes for any unscanned parent-bodies (for visualization purposes). If EDD would (as per example) add wireframes for the bodies 2-6 this would suggest a potentially false completeness, as in reality there might be another 20 bodies beyond those first 7. So my vote would be to keep it as simple and unabiguous as it already is.

**Comment by robbyxp1** [comment]
Closing as there is no consensus
