### ISSUE TITLE
Feature Request: Add a Help -> About box

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#123]
Basic Information:
* Author; release date; release version

Advanced Information:
* Link to Forum thread
* Link to GitHub issue tracker (beta version only?)
* Link to EDSM
* (Any other relevant external links)

**Comment by finwen** [comment]
Good idea.

2016-02-22 13:21 GMT+01:00 Michael Werle <notifications@github.com>:

**Comment by mwerle** [comment]
Looking great! 

But needs to show Release/Trial/Beta status of the current release. 
Maybe we should even make a big yellow or red label on the main interface for non-release builds. Just to really alert people that they're not using a production build.
