### ISSUE TITLE
Ability to move Tabs in Main Window

### ISSUE THREAD

**Issue by Uriei** [EDDiscovery/EDDiscovery#1232]
Simply, I would like to be able to set the order of the tabs in the main window, per example, I would like to have the Grid one as the default one, the first one.
![image](https://user-images.githubusercontent.com/6078221/29741665-d0bbe13e-8a71-11e7-815e-281cc19aacfd.png)

**Comment by iainross** [comment]
It does remember what tab it was closed on and re-open on that one, if that helps.

**Comment by robbyxp1** [comment]
We will rework the major tab system in 9.0 when we move a lot of the current tabs to panels. Then i'll add in the ability to add/remove/reorder the major tabs.

**Comment by robbyxp1** [comment]
Done
