### ISSUE TITLE
Journal Backup

### ISSUE THREAD

**Issue by Timnus** [EDDiscovery/EDDiscovery#1237]
could there be a way to have all the journals created be backed up in a file in case of a failure? one single compacted file on command that can be read back into the program if there is a PC failure.

**Comment by robbyxp1** [comment]
Well, you have two copies.. the original journal files in the elite save folder, and the ones in our DB located in appdata normally.  If you lose the ED one, you can recreate the ED db (without notes admittedly, unless you synced them to EDSM).

We could add a manual backup option of the user DB somewhere..  not sure about duplicating it.

**Comment by andreaspada** [comment]
>  If you lose the ED one, you can recreate the ED db

I didn't know that! How does it works? It's a great feature which I'm pretty sure it's been missed by the large users community...

**Comment by phroggster** [comment]
> If you lose the ED one, you can recreate the ED db.

@andreaspada I think he probably meant:

> If you lose the EDD Journal DB (`%LOCALAPPDATA%\EDDiscovery\EDDUser.sqlite`), it will automatically be re-created from the ED log files (`%USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous\*.log`).

@Timnus Include `%LOCALAPPDATA%\EDDiscovery\EDDUser.sqlite` and `%USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous\*.log` in your backup routine, and you can use whatever backup software you'd like. Here's a command script to do it:
```cmd
@echo off

rem Set the following line appropriately...
set OUTDIR=N:\Backups\EDDiscovery

mkdir "%OUTDIR%"
mkdir "%OUTDIR%\ED Logfiles"

xcopy "%LOCALAPPDATA%\EDDiscovery\EDDUser.sqlite" "%OUTDIR%" /V /C /I /F /G /K /Y
xcopy "%USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous\*.*" "%OUTDIR%\ED Logfiles" /V /C /I /F /G /K /Y
```
