### ISSUE TITLE
Sanitise menus

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#124]
Revamp menus to have 'standard' Windows layout:

File (Load/Save/Export/Exit)
Edit (Cut/Copy/Paste/Delete/...?)
Help (About)

...others as required - reuse what we already have.

**Comment by robbyxp1** [comment]
Actually, maybe the 2D maps should be more easily found as well.. on a tab (with a POP out button)..

**Comment by robbyxp1** [comment]
If you want to do something like this, then you should go the whole hog and remove all the menu items

At the moment, its a mix between tabs to set up stuff (setting tab) and the menu items. 

Really all the settings should be on the settings tab, for example the Options menu (Keep on top, fast travel) should be settings tick boxes.
Help could a button near the ED Discovery icon.. etc
Admin could be under advanced on the settings tab
Tools could be buttons on the appropriate screen.
2D maps could be a tab on its own, with scroll bars and control, with a button to pop it out onto its own screen as of now.  This would integrate it into the GUI more effectively.

Its up to Finwen to decide - this would be a major change and its a policy decision.

I personally always try and write wizards or tab controls like this one without any menus.

**Comment by finwen** [comment]
Yes the meanues  would need some cares  and a some thoughts  in the
longtime on how  we use them and settigns  tab and so on.

WE will find a good solution together.

2016-02-23 18:24 GMT+01:00 robbyxp1 <notifications@github.com>:

**Comment by robbyxp1** [comment]
Yes, maybe we could have a discord conference at s me point to decide.

**Comment by robbyxp1** [comment]
I think we leave leave alone for now - can't see an obv. scheme to use.  We have decided that menus are useful.

**Comment by robbyxp1** [comment]
Retired
