### ISSUE TITLE
Decimal sign issue in Pos

### ISSUE THREAD

**Issue by cmdrmarx** [EDDiscovery/EDDiscovery#1240]
On systems with locales that use "," as the decimal mark, the Pos field of the system information gets broken up as it's the same character as the separator. For example, what would be "12.23, 34.47, 100.42" becomes "12,23, 34,47, 100,42".  It's a minor issue, but it would be good if the decimal mark was converted to "." , which is used by the game anyway.

**Comment by phroggster** [comment]
What locale are you using? Would you be able to dig up something approaching a scholarly, literary, or journalistic style guide that shows the *proper* way to list three coordinates in your locale? I wonder if it's something like:

- `2,35 711,13 17,19` *or*
- `23,29: 31,37: 41,43` *or*
- `6.28, 3.14, 2.71`

**Comment by robbyxp1** [comment]
We try to write number out respecting the locale.

Changed to 

string separ = System.Globalization.CultureInfo.CurrentCulture.NumberFormat.NumberGroupSeparator + " ";

seems to be , for english, space for swedish!
