### ISSUE TITLE
Update scan panel on jump start event, not on arrival event

### ISSUE THREAD

**Issue by EoD** [EDDiscovery/EDDiscovery#1241]
In my understanding, currently the scan panel is only updated (and downloaded from EDSM) when you are already in the system.

It would be really handy if I could already check what I am getting into before actually arriving. A "jump start" event can only very rarely be interrupted, so I assume it should not interfere.

**Comment by klightspeed** [comment]
Note that the Scan panel shows the system of the currently selected entry Travel History tab.

The `Jump Start` event is fired at the start of the 5 second FSD countdown (both when jumping to supercuise and when jumping to hyperspace).
It does not include the coordinates of the system, and so cannot distinguish between duplicate systems.

```
{ "timestamp":"2017-08-28T16:38:41Z", "event":"StartJump", "JumpType":"Hyperspace", "StarSystem":"Col 285 Sector GS-I c10-13", "StarClass":"K" }
```

For non-duplicate systems already in EDSM, the StartJump could be special-cased to be linked to the system that is being jumped to.  For systems not in EDSM, or for systems where the name cannot be resolved to a unique system (e.g. any of the systems in https://www.edsm.net/en/systems/duplicates), the StartJump event would not be able to be linked to any one system.

**Comment by EoD** [comment]
@klightspeed I see. If the EDSM download does not exist, it is not reasonable to update the scan tab anyway during witchspace anyway. In order to be consistent, it might be a good idea to use a "dummy" (empty) scan panel. 
In both cases, this means that the scan panel needs to be updated on arrival as well though.

I am undetermined if the duplicate systems need to be ignored as well. If the above is implemented, you can update the scan tab anyway as soon as you arrive. So it might also be an idea to take the first hit on EDSM?
