### ISSUE TITLE
Habitable Zone estimation wrong for Lagoon Seactor IR-W d1-131

### ISSUE THREAD

**Issue by EoD** [EDDiscovery/EDDiscovery#1243]
Planet `` Lagoon Sector IR-W d1-131 A 5`` is outside the habitable zone approximation, but it's terraformable. As there is only one sun nearby, I am not sure why this is so far off (roughly 20% off).

System:
https://www.edsm.net/en/system/bodies/id/140813/name/Lagoon+Sector+IR-W+d1-131

These are the values from the scan panel:
```
Lagoon Sector IR-W d1-131 A

White Main Sequence star
Age: 1,270 million years
Solar Masses: 1.19
Solar Radius: 1.08 Sols
Surface Temp: 6,505K
Orbital Period: 1,222,086.7 days
Semi Major Axis: 70.70AU
Orbital Eccentricity: 0.193°
Orbital Inclination: 36.753°
Arg Of Periapsis: 104.265°
Absolute Magnitude: 4.15
Axial tilt: 0.00°
Rotation Period: 3.6 days

Habitable Zone Approx. 534-1,065ls (1.07-2.13 AU)
 (This star only, others not considered)
Estimated value: 2931
```

And the screenshots:
![lagoon sector ir-w d1-131 20170902-212755 _sun](https://user-images.githubusercontent.com/293499/29998940-950704cc-9037-11e7-9e1e-cdfde57d9abc.png)
![lagoon sector ir-w d1-131 20170902-212755 _waterworld](https://user-images.githubusercontent.com/293499/29998939-9505d390-9037-11e7-8707-b003cc6e09f8.png)

**Comment by iainross** [comment]
The effect of additional stellar bodies on the habitable zones is bigger than you'd expect (and bigger than science says you should expect too).

This is down to that, most likely - if you assume there will be no CFTs outside of the approximation in EDD then you will miss some.  Especially in multiple star systems.  It's a rough guide and if there are multiple stars then look further outside it than you think you should have to because that's how the game works - if there's only one then planets close to, but outside, the limits could still be CFTs too.

The data you've shown is all internally consistent so it doesn't look to be a bug on our end.

**Comment by EoD** [comment]
@iainross The other star is 150,000ls out and very weak as well. Are you really sure that this is the case?

**Comment by iainross** [comment]
@EoD pretty sure. The effect of secondary stars is a *lot* more than it should be.  If you have the details of the secondary you can try feeding both stars into Jackie's habzone calculator ( https://forums.frontier.co.uk/showthread.php/303159-Jackie-s-Hab-Zone-Calculator-version-2 ) and see if it still comes out wildly wrong.  That should be applying secondaries like ED does (as far as we can tell).

**Comment by EoD** [comment]
@iainross I added the numbers into the generator, but I am not sure what you wanted me to look out for. 

1. If we are we debating the **formula of the habitable zone of Jackie's calculator** to be wrong (as you are using the same formula), then we still have an error of 60ls (5% error):
![image](https://user-images.githubusercontent.com/293499/30002453-48693752-90aa-11e7-8136-331bd3dd0bd5.png)


2. If we are we debating **the formula of the habitable zone of EDD** to be wrong (as you intend to use the same formula), then the testing for one star is more appropriate. Here we have an error of 2ls compared to Jackie's calculator. This seems like an cumulative round error on either side:
![image](https://user-images.githubusercontent.com/293499/30002488-e6e42266-90aa-11e7-9de2-97dc31a214cb.png)


I used the following information as a reference:
* The planet: https://www.edsm.net/en/system/bodies/id/140813/name/Lagoon+Sector+IR-W+d1-131/details/idB/6560336/nameB/Lagoon+Sector+IR-W+d1-131+A+5
* Primary star: https://www.edsm.net/en/system/bodies/id/140813/name/Lagoon+Sector+IR-W+d1-131/details/idB/774344/nameB/Lagoon+Sector+IR-W+d1-131+A
* Secondary star: https://www.edsm.net/en/system/bodies/id/140813/name/Lagoon+Sector+IR-W+d1-131/details/idB/7499580/nameB/Lagoon+Sector+IR-W+d1-131+B

**Comment by iainross** [comment]
That was just to demonstrate how big an impact the second star has - although it looks like that may still be underestimating.

The main point though is that it's an estimation, not a cast iron guarantee and when there are additional stars treat it with even more caution.  CFTs may be found outside the reported zone.

If you find a major discrepancy in a single star proc-gen system then I'll be more interested.
