### ISSUE TITLE
It's there any plan to reduce hardware usage ?

### ISSUE THREAD

**Issue by zsbstephen** [EDDiscovery/EDDiscovery#1244]
First of all please forgive my poor English .
My PC has an Intel Core i5 2500 quad core CPU and 16G RAM . running at Windows 8.1 system . 
When I launched EDDiscovery , the application's CPU usage went up to over 20% , and used over 5G RAM . Memory usage would drop to about 3.5G after synchronized with edsm server , but such hardware usage was above elitedangerous itself , and some application may crash if I run elitedangerous at the same time with system background memory usage over 85% , that really horrible . Now I had no choice but to run EDDiscovery after exiting the game .
It's my honor to have your reply .
![cpu_ram](https://user-images.githubusercontent.com/19226303/30000451-edbd995c-909e-11e7-9a28-937ca715f72b.png)
![eddiscovery](https://user-images.githubusercontent.com/19226303/30000452-f3b848b6-909e-11e7-8113-e83f57cc2ec2.png)

**Comment by klightspeed** [comment]
How many entries are in your travel history?

If the history has less than 50000 entries, it sounds a lot like Windows 8.1 is counting the file cache against the program.

**Comment by iainross** [comment]
On your Commander's settings have you got the 'Sync from EDSM' box checked?  If you don't run ED/EDD on multiple machines then you can leave this unchecked unless you've lost your travel history and local logs so need to rebuild it from EDSM and doing so can see the CPU usage drop quite a lot.

**Comment by zsbstephen** [comment]
@klightspeed  I've got over 110000 entries so far . And thanks for your reply , I noticed that CPU and RAM usage seemed to be proportional to game time . First time I run EDDiscovery only 1G RAM was consumed .
@iainross Thanks for your reply , I leaved this setting as default , and run the sync function every time I launched . Compared to the older version , it seems that the new version won't sync with server every a few minutes automatically  unless I run manually . But I've already got used to do this every time because I want to be able to find out which system I've first discovered and the path I've passed .
Thanks for the effort of the whole team , I'm looking forward to the database optimization in the future .

**Comment by zsbstephen** [comment]
My desktop's configuration
Intel Core i5 2500
ASUS Sabertooth P67
Crucial DDR3 1600 8G*2
MSI Radeon R9 280X 3G Gaming
Sandisk Extreme Pro 480G
Windows 8.1 Enterprise x64 with Update 1 ( hibernation and virtual memory disabled )
AMD Crimson 17.7 VGA driver
Hope this information would help , and thanks for the effort of the whole team . I'm really looking forward to the database optimization in the future .

**Comment by phroggster** [comment]
It appears that you may be using the portable version of EDDiscovery. It may or may not be something, but are you running it from a USB device like a jump drive? Is this device also being used for Windows ReadyBoost?

**Comment by klightspeed** [comment]
I think in order to reduce the memory usage with that many entries, we would need to paginate the travel history and journal history grids, probably to e.g. 10k entries per page.

With my 15k entry history, the total process memory is 200MB, with 80MB on the heap.  The array inside the history list is >85kB, and so ends up on the large object heap.

In your case, that array would be 1MB, and each refresh would put a few more MB on the large object heap (which isn't compacted by DotNet).

**Comment by zsbstephen** [comment]
@phroggster Thx . Yep portable version exactly . But I've stored the folder on the main SSD drive which's parted with GPT , games and all programs were all installed on it . Moreover I'd disable ReadyBoost .
@klightspeed Thx for your comment . I'll keep on upgrading EDDiscovery to the latest version and waiting for your good news .

**Comment by robbyxp1** [comment]
I can't see a way of addressing this in the current roadmap.  Your number of entries is well above anyone else we have ever seen.  You may just have to live with the memory usage for now.

**Comment by iainross** [comment]
It's not that far above - I've got 101k history entries.

If I've got Sync **FROM** EDSM on then I'll typically sit on ~15% CPU as it ends up nearly continuously fetching from EDSM and checking everything is in the list.  

If I only sync **TO** EDSM then I'll generally sit on less than 0.2% CPU for EDD.

I've never managed to get memory usage close to 4GB

**Comment by zsbstephen** [comment]
@robbyxp1 Oh ah emmm ....
@iainross Thx for your remind , but I can't find this option in version 8.2.3.0 .
![default](https://user-images.githubusercontent.com/19226303/30246301-a1e8317e-9628-11e7-81db-88255c77492e.png)

**Comment by klightspeed** [comment]
The options to enable or disable sync from EDSM is in the commander settings in the Settings tab.
