### ISSUE TITLE
Rogue Entries in log

### ISSUE THREAD

**Issue by TheHunstman** [EDDiscovery/EDDiscovery#1245]
[data.txt.txt](https://github.com/EDDiscovery/EDDiscovery/files/1272877/data.txt.txt)

Within my log there are some rogue entries that I certainly didn't do - they are also impossible?

I've attached the extracted data - basically I was at system 2MASS J21515566+6227138 which is 2500Ly from Sol and then the log shows me back in the bubble, docked and jumping between a couple of systems and then I'm back at 2MASS...is this an issue with EDD or something with FD?

**Comment by klightspeed** [comment]
That looks like you went into Training.

Unfortunately, Training uses some real systems, so in 2.3 the only way to determine if you have entered training is if there is a `Location` entry without a corresponding `LoadGame` or `Resurrect` entry.

**Comment by TheHunstman** [comment]
That'll be it...was showing a friend who was thinking of getting the game.  That's damn annoying.  
Thanks though!
