### ISSUE TITLE
Export Value in export

### ISSUE THREAD

**Issue by TheHunstman** [EDDiscovery/EDDiscovery#1246]
When using the export option on the history tab, it includes the estimated value
![image](https://user-images.githubusercontent.com/31588442/30002685-dca9fc88-90a7-11e7-8db0-c56029e7a999.png)

However, when using the actual export function, it doesn't
![image](https://user-images.githubusercontent.com/31588442/30002689-ff8167d2-90a7-11e7-9205-53a6885bf5a4.png)

Any chance of adding the estimated value into the CSV export?

Also, it would be useful to be able to apply a date range to the export?

**Comment by iainross** [comment]
That will definitely happen since I was planning on doing it when I get back from my current trip and before I sell the data (only ~12kly from Sol now and heading back to the bubble).  Also considering adding some more filters on what gets exported (date ranges at least, possibly more).
