### ISSUE TITLE
UI rendering very slow

### ISSUE THREAD

**Issue by EoD** [EDDiscovery/EDDiscovery#1247]
When I use EDD while playing Elite, the UI is very sluggish. Here is a video to demonstrate the issue: https://www.youtube.com/watch?v=7zMT7axjhPs

As well as a quote from Discord:
> Bravada Cadelanne: Looks like it's yielding after each paint operation, and so doesn't paint the next item until the next time slice.

**Comment by robbyxp1** [comment]
Yes, I know about this, and have seen it, and don't have the foggiest what to do with it.  It only happens inside windows/winforms when the UI is heavily loaded.

**Comment by EoD** [comment]
Is there a way to profile the program? It might be able to point out where all the time goes when rendering the UI under load.

**Comment by klightspeed** [comment]
If you have a Pro edition of Windows, you can use CPU profiling in visual studio (any edition).

**Comment by EoD** [comment]
@robbyxp1 Why did you close the issue? It is know ("verified") and not fixed.
