### ISSUE TITLE
Logs. 

### ISSUE THREAD

**Issue by Timnus** [EDDiscovery/EDDiscovery#1249]
Had a total pc failure. tech in support blew my backup. any other way to regain logs?

**Comment by iainross** [comment]
Assuming you were syncing to EDSM you can sync from to get your travel history back.  The rest, unfortunately not if your backup's died too.

**Comment by Timnus** [comment]
the travel histoyr is waht i want. and i was syncing. so if i sync again it comes back??

**Comment by klightspeed** [comment]
Travel history as in the systems you have visited (i.e. FSDJump entries), yes.

**Comment by robbyxp1** [comment]
Okay, ping us if you need more help
