### ISSUE TITLE
UI stopped working after jump

### ISSUE THREAD

**Issue by Obey138** [EDDiscovery/EDDiscovery#1258]
After making a jump, UI stopped working properly (scan data and system information doesn't show up) and crashed

> [...]
> [2017-09-09 11:36:15Z] New entry 09.09.2017 09:36:14 FSDJump
> [2017-09-09 11:36:15Z] Arrived at system: Arietis Sector FL-Y c7 1:th visit.
> [2017-09-09 11:36:15Z] Update sync flag ID 8803 with 1
> [2017-09-09 11:36:16Z] Update sync flag ID 8803 with 3
> [2017-09-09 11:36:18Z] 
> ==== UNHANDLED UI EXCEPTION ====
> System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
>    w EliteDangerousCore.JournalEvents.JournalScan.DisplayStringFromRingClass(String ringClass)
>    w EliteDangerousCore.JournalEvents.JournalScan.RingInformation(Int32 ringno, Double scale, String scaletype)
>    w EliteDangerousCore.JournalEvents.JournalScan.DisplayString(Int32 indent, Boolean includefront)
>    w EDDiscovery.UserControls.UserControlScan.DrawNode(List`1 pc, ScanNode sn, Image notscanned, Point curpos, Size size, Int32& offset, Boolean aligndown, Int32 labelvoff)
>    w EDDiscovery.UserControls.UserControlScan.DrawSystem()
>    w EDDiscovery.UserControls.UserControlScan.Display(HistoryEntry he, HistoryList hl)
>    w EDDiscovery.UserControls.ChangedSelectionHE.Invoke(HistoryEntry he, HistoryList hl)
>    w EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection()
>    w EDDiscovery.UserControls.UserControlTravelGrid.AddNewEntry(HistoryEntry he, HistoryList hl)
>    w System.Action`2.Invoke(T1 arg1, T2 arg2)
>    w EDDiscovery.EDDiscoveryController.NewEntry(JournalEntry je)
>    w EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries)
> ==== cut ====
> [2017-09-09 11:36:19Z] Retrieving logs ending 28.01.2017 09:34:02
> [...]

[Full log](https://github.com/EDDiscovery/EDDiscovery/files/1289686/Trace_20170909104553.0.log.txt)

And stopped working at all, even when restarting

> [2017-09-09 11:41:09Z] Running logfile age check
> [2017-09-09 11:41:09Z] Native library pre-loader is trying to load native SQLite library "D:\EDDiscovery\x64\SQLite.Interop.dll"...
> [2017-09-09 11:41:09Z] SQLite version 3.19.3
> [2017-09-09 11:41:11Z] *** Elite Dangerous Discovery Initializing - Version 8.2.3.0 (Using EDDiscovery), Platform: Win32NT
> [2017-09-09 11:41:11Z] Initializing database
> [2017-09-09 11:41:11Z] Database initialization complete
> [2017-09-09 11:41:15Z] Theme ID 10037
> [2017-09-09 11:41:59Z] Unknown Gal Map object regional
> [2017-09-09 11:41:59Z] Unknown Gal Map object organicPOI
> [2017-09-09 11:41:59Z] Unknown Gal Map object geyserPOI
> [2017-09-09 11:41:59Z] New watch on C:\Users\wojta\Saved Games\Frontier Developments\Elite Dangerous
> [2017-09-09 11:41:59Z] Scanned C:\Users\wojta\Saved Games\Frontier Developments\Elite Dangerous
> [2017-09-09 11:42:00Z] Unknown Gal Map object regional
> [2017-09-09 11:42:00Z] Last message repeated 17 times
> [2017-09-09 11:42:00Z] Unknown Gal Map object organicPOI
> [2017-09-09 11:42:00Z] Last message repeated 7 times
> [2017-09-09 11:42:00Z] Unknown Gal Map object geyserPOI
> [2017-09-09 11:42:00Z] Last message repeated 43 times
> [2017-09-09 11:42:18Z] 
> ==== UNHANDLED UI EXCEPTION ====
> System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
>    w EliteDangerousCore.JournalEvents.JournalScan.DisplayStringFromRingClass(String ringClass)
>    w EliteDangerousCore.JournalEvents.JournalScan.RingInformation(Int32 ringno, Double scale, String scaletype)
>    w EliteDangerousCore.JournalEvents.JournalScan.DisplayString(Int32 indent, Boolean includefront)
>    w EDDiscovery.UserControls.UserControlScan.DrawNode(List`1 pc, ScanNode sn, Image notscanned, Point curpos, Size size, Int32& offset, Boolean aligndown, Int32 labelvoff)
>    w EDDiscovery.UserControls.UserControlScan.DrawSystem()
>    w EDDiscovery.UserControls.UserControlScan.Display(HistoryEntry he, HistoryList hl)
>    w EDDiscovery.UserControls.ChangedSelectionHE.Invoke(HistoryEntry he, HistoryList hl)
>    w EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection()
>    w EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl)
>    w System.Action`1.Invoke(T obj)
>    w EDDiscovery.EDDiscoveryController.RefreshHistoryWorkerCompleted(HistoryList hist)
> ==== cut ====
>

**Comment by klightspeed** [comment]
This should be fixed in 8.3 (by commit c1a81dc)

@robbyxp1 @finwen should we create an 8.2.6 release with this bugfix in it?

**Comment by phroggster** [comment]
Closing as duplicate.

Also, I'm in agreement that a release should be made that includes this fix, but I'm indifferent as to whether it's tagged 8.2.6 or 8.3.0.
