### ISSUE TITLE
UNHANDLED UI EXCEPTION

### ISSUE THREAD

**Issue by Flameon985** [EDDiscovery/EDDiscovery#1259]
Eddiscovery gave an UNHANDLED UI EXCEPTION error while running and gave it again when I restarted it.
[Trace_20170909112145.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/1289698/Trace_20170909112145.0.txt)

**Comment by phroggster** [comment]
Duplicate of #1253. The fix will be included in EDDiscovery 8.3.
