### ISSUE TITLE
Not seeing Modified Embedded Firmware

### ISSUE THREAD

**Issue by kjnpbr** [EDDiscovery/EDDiscovery#1262]
On collecting Modified Embedded Firmware for the first time (new discovery), I noticed by materials count for that component wasn't being updated.

I reloaded the game, and even though it's showing in my Materials journal entry, it's still not showing on my list of Materials on EDDiscovery.

This means that on the engineers screen, my available isn't showing properly for appropriate upgrades, and it's still showing as needed for Modified Embedded Firmware when wanted.

![2017-09-10 1](https://user-images.githubusercontent.com/24323976/30253062-782c7b9a-9675-11e7-8560-3c0f6c372b23.png)

When collecting the Modified Embedded Firmware I noticed that the discovery entry appeared, but no Collected entry appeared.

![2017-09-10 2](https://user-images.githubusercontent.com/24323976/30253069-ba765b1a-9675-11e7-93a2-e6b42678048e.png)

**Comment by phroggster** [comment]
Well, here's something odd:
![30253062-782c7b9a-9675-11e7-8560-3c0f6c372b23](https://user-images.githubusercontent.com/14035789/30253106-1756059c-9644-11e7-8a57-59a37ce65b8e.png)

**Comment by robbyxp1** [comment]
How did you get it? Can you find the journal record where you were rewarded it?  maybe we are not picking up that type of record and adding it to the database.

**Comment by kjnpbr** [comment]
This is the entry from my Journel file.  As you can see there is an event MaterialCollected for 'embeddedfirmware', count 3.

`{ "timestamp":"2017-09-10T20:27:33Z", "event":"DatalinkScan", "Message":"$DATAPOINT_GAMEPLAY_complete;", "Message_Localised":"Alert: All Data Point telemetry links established, Intel package created." }
{ "timestamp":"2017-09-10T20:27:33Z", "event":"DataScanned", "Type":"DataPoint" }
{ "timestamp":"2017-09-10T20:27:33Z", "event":"MaterialCollected", "Category":"Encoded", "Name":"industrialfirmware", "Count":3 }
{ "timestamp":"2017-09-10T20:27:33Z", "event":"MaterialCollected", "Category":"Encoded", "Name":"encryptedfiles", "Count":3 }
{ "timestamp":"2017-09-10T20:27:34Z", "event":"MaterialCollected", "Category":"Encoded", "Name":"scandatabanks", "Count":3 }
{ "timestamp":"2017-09-10T20:27:34Z", "event":"MaterialDiscovered", "Category":"Encoded", "Name":"embeddedfirmware", "DiscoveryNumber":34 }
{ "timestamp":"2017-09-10T20:27:34Z", "event":"MaterialCollected", "Category":"Encoded", "Name":"embeddedfirmware", "Count":3 }`
This is my timestamp when reentering the game.  The EmbeddedFirmware is the last in the list.

`{ "timestamp":"2017-09-10T21:03:24Z", "event":"Materials", "Raw":[ { "Name":"chromium", "Count":33 }, { "Name":"iron", "Count":8 }, { "Name":"phosphorus", "Count":30 }, { "Name":"carbon", "Count":25 }, { "Name":"nickel", "Count":18 }, { "Name":"manganese", "Count":2 }, { "Name":"germanium", "Count":17 }, { "Name":"zinc", "Count":3 }, { "Name":"vanadium", "Count":9 }, { "Name":"cadmium", "Count":23 }, { "Name":"tin", "Count":41 }, { "Name":"antimony", "Count":8 }, { "Name":"mercury", "Count":10 }, { "Name":"niobium", "Count":15 }, { "Name":"molybdenum", "Count":31 }, { "Name":"yttrium", "Count":11 }, { "Name":"zirconium", "Count":21 }, { "Name":"sulphur", "Count":23 }, { "Name":"tungsten", "Count":6 }, { "Name":"selenium", "Count":12 }, { "Name":"arsenic", "Count":10 }, { "Name":"tellurium", "Count":6 }, { "Name":"technetium", "Count":3 } ], "Manufactured":[ { "Name":"shieldemitters", "Count":29 }, { "Name":"wornshieldemitters", "Count":32 }, { "Name":"phasealloys", "Count":21 }, { "Name":"galvanisingalloys", "Count":26 }, { "Name":"protolightalloys", "Count":29 }, { "Name":"heatdispersionplate", "Count":9 }, { "Name":"focuscrystals", "Count":22 }, { "Name":"shieldingsensors", "Count":12 }, { "Name":"refinedfocuscrystals", "Count":31 }, { "Name":"chemicalprocessors", "Count":27 }, { "Name":"fedproprietarycomposites", "Count":6 }, { "Name":"chemicalmanipulators", "Count":14 }, { "Name":"highdensitycomposites", "Count":14 }, { "Name":"precipitatedalloys", "Count":9 }, { "Name":"gridresistors", "Count":12 }, { "Name":"compoundshielding", "Count":24 }, { "Name":"heatconductionwiring", "Count":10 }, { "Name":"conductiveceramics", "Count":7 }, { "Name":"basicconductors", "Count":3 }, { "Name":"chemicaldistillery", "Count":27 }, { "Name":"heatexchangers", "Count":14 }, { "Name":"mechanicalscrap", "Count":11 }, { "Name":"protoheatradiators", "Count":12 }, { "Name":"crystalshards", "Count":4 }, { "Name":"biotechconductors", "Count":7 }, { "Name":"heatresistantceramics", "Count":3 }, { "Name":"heatvanes", "Count":9 }, { "Name":"conductivecomponents", "Count":18 }, { "Name":"configurablecomponents", "Count":3 }, { "Name":"salvagedalloys", "Count":8 }, { "Name":"conductivepolymers", "Count":4 }, { "Name":"polymercapacitors", "Count":7 }, { "Name":"hybridcapacitors", "Count":3 }, { "Name":"mechanicalequipment", "Count":4 }, { "Name":"pharmaceuticalisolators", "Count":9 }, { "Name":"fedcorecomposites", "Count":6 }, { "Name":"improvisedcomponents", "Count":6 } ], "Encoded":[ { "Name":"shieldpatternanalysis", "Count":36 }, { "Name":"scandatabanks", "Count":28 }, { "Name":"emissiondata", "Count":9 }, { "Name":"shieldsoakanalysis", "Count":22 }, { "Name":"bulkscandata", "Count":14 }, { "Name":"shieldcyclerecordings", "Count":12 }, { "Name":"decodedemissiondata", "Count":22 }, { "Name":"encryptedfiles", "Count":15 }, { "Name":"compactemissionsdata", "Count":2 }, { "Name":"encodedscandata", "Count":16 }, { "Name":"disruptedwakeechoes", "Count":20 }, { "Name":"symmetrickeys", "Count":13 }, { "Name":"encryptioncodes", "Count":5 }, { "Name":"hyperspacetrajectories", "Count":2 }, { "Name":"scanarchives", "Count":27 }, { "Name":"encryptionarchives", "Count":16 }, { "Name":"scrambledemissiondata", "Count":6 }, { "Name":"fsdtelemetry", "Count":7 }, { "Name":"legacyfirmware", "Count":12 }, { "Name":"archivedemissiondata", "Count":12 }, { "Name":"classifiedscandata", "Count":8 }, { "Name":"consumerfirmware", "Count":13 }, { "Name":"adaptiveencryptors", "Count":17 }, { "Name":"securityfirmware", "Count":7 }, { "Name":"tg_structuraldata", "Count":3 }, { "Name":"tg_compositiondata", "Count":3 }, { "Name":"unknownwakedata", "Count":3 }, { "Name":"shielddensityreports", "Count":9 }, { "Name":"industrialfirmware", "Count":6 }, { "Name":"embeddedfirmware", "Count":3 } ] }`

**Comment by klightspeed** [comment]
In both of the images in your original post, it looks like you had the material discovery event selected.  Most of the panels will show you either information on the system and/or body related to the selected event, or what the program detects you would have had at that time.

Is there any message in the related trace log in `%LOCALAPPDATA%\EDDiscovery\Log` about that event?

**Comment by kjnpbr** [comment]
My trace file for the time of events above is in the attached ZIP file.

[Trace_20170910153206.0.zip](https://github.com/EDDiscovery/EDDiscovery/files/1294060/Trace_20170910153206.0.zip)

**Comment by klightspeed** [comment]
Odd - it looks like a few events were read out of order:
```
[2017-09-10 21:27:33Z] New entry 10/09/2017 20:27:33 DatalinkScan
[2017-09-10 21:27:33Z] New entry 10/09/2017 20:27:33 DataScanned
[2017-09-10 21:27:34Z] New entry 10/09/2017 20:27:33 MaterialCollected
[2017-09-10 21:27:34Z] New entry 10/09/2017 20:27:34 MaterialCollected
[2017-09-10 21:27:34Z] New entry 10/09/2017 20:27:34 MaterialDiscovered
[2017-09-10 21:27:35Z] New entry 10/09/2017 20:27:33 MaterialCollected
[2017-09-10 21:30:00Z] New entry 10/09/2017 20:30:00 Friends
```

**Comment by kjnpbr** [comment]
OK, so a new collection event for MEF has successfully appeared in my Journal on EDD, and my materials count has increased to 6.  

So, the only thing I can think of is that the discovery event has interfered with the collection event for some reason.

At least I can go and get my rank 5 huge beam lasers now.

**Comment by robbyxp1** [comment]
Are we happy now?

**Comment by kjnpbr** [comment]
I'm happy, but I'm still not sure if there is a bug somewhere in there.  Problem is I cannot replicate the issue now I've discovered this material. Probably best close it, as it seems an obscure issue.

**Comment by robbyxp1** [comment]
Okey dokey
