### ISSUE TITLE
Unhandled Exception on startup

### ISSUE THREAD

**Issue by blackie999** [EDDiscovery/EDDiscovery#1273]
![capture](https://user-images.githubusercontent.com/32020727/30514588-f94630d8-9b0f-11e7-8e13-4b812154d74d.PNG)
[Trace_20170916184110.0.zip](https://github.com/EDDiscovery/EDDiscovery/files/1308535/Trace_20170916184110.0.zip)

**Comment by klightspeed** [comment]
That looks very similar to the OpenTK input error when a joystick with a lot of buttons and/or axes is plugged in.

**Comment by blackie999** [comment]
Have an x52 Pro

**Comment by blackie999** [comment]
Where have the voice synthesis action packs gone? Can’t find them

**Comment by klightspeed** [comment]
The packs should be under Add-ons -> Manage Add-ons

**Comment by blackie999** [comment]
Removed edd, cleaned and files and folders left. redownloaded and reinstalled.
This is the add-ons menu
![addon](https://user-images.githubusercontent.com/32020727/30516133-11a7c826-9b2e-11e7-8088-d6c813384fec.PNG)

**Comment by robbyxp1** [comment]
What version of EDD are you running?  I removed VP3 from the downloads a week ago since it was for a very old version.

**Comment by blackie999** [comment]
Was the latest version. Downloaded it last week I think. Was using voice pack 4. It’s disappeares for the add on menu.

**Comment by robbyxp1** [comment]
VP4 is back.. my fault due to preparing for 8.3

**Comment by blackie999** [comment]
Yay! Will download tonight 😁

**Comment by robbyxp1** [comment]
made the slider reading more robust.. only two sliders allowed

**Comment by robbyxp1** [comment]
Fixed #1276
