### ISSUE TITLE
Unhandled Exception: database is Locked

### ISSUE THREAD

**Issue by Bear67** [EDDiscovery/EDDiscovery#1274]
![screenshot_1](https://user-images.githubusercontent.com/5138687/30524995-c9f7af82-9bc3-11e7-8f46-f30db8428fcd.jpg)

[Trace_20170917150059.0.zip](https://github.com/EDDiscovery/EDDiscovery/files/1309397/Trace_20170917150059.0.zip)

**Comment by robbyxp1** [comment]
Hopefully #1275 has done it

**Comment by phroggster** [comment]
I'm going to close this issue, as it's seemingly resolved in v8.3.0/v8.3.1 via c63f1aa6ca9990572535863ff5ff62ed4e8a1203. If you see this issue again in the future, please re-open this ticket.
