### ISSUE TITLE
Bug: ~~Crash~~ Hang when submitting trilateration with systems with unknown position

### ISSUE THREAD

**Issue by RedfoxCh** [EDDiscovery/EDDiscovery#128]
I've been using the option to enter distances to systems with unknown positions (DSUP) in the trilateration tab - a great addition to EDD, if I may say so.

Unfortunately it seems to crash EDD from time to time. Due to this I've been limiting my entries for DSUP to batches of 5 to not lose too much if that happens. I haven't been able to identify any pattern to the crashes, as I've been able to add 16+ DSUP with no issue, and other times it crashes with 5 DSUP.

Now that it has crashed twice in a row with the same entries I though I'd submit a bug listing the involved systems - possibly helping to identify the cause. Here's a screenshot of the EDD window (sry for the weird resolution): [http://i.imgur.com/YdED6E6.png](http://i.imgur.com/YdED6E6.png)

Steps to reproduce (data as per screenshot):
* Start EDD
* Go to Trialteration Tab
* Click Start New
* Select top 5 suggested reference systems
* Enter those distances
* Click Submit distances (Status shows success)
* Enter a systems with unknown position, followed by entering the distance
* Repeat previous step 4 more times
* Click Submit distances (Status halts at "Submitting systems to EDSM, please wait...")
* Window becomes unresponsive and cannot be closed by "X" or via Taskbar-Right-Click-Close; can only be closed via Task Manager
* Waited for arount 10min, no change

**Comment by mwerle** [comment]
Ok, to confirm, the program doesn't crash, it hangs indefinitely?  (Sorry to be pedantic, but there is a difference).

**Comment by RedfoxCh** [comment]
> it hangs indefinitely

Correct, that is a more accurate description - and no worries, I appreciate the need to be precise.

**Comment by mwerle** [comment]
Another question; after submitting the intial set of distances, do you "Start New" or just add the distances for the unknown systems?
Also, do you submit each "unknown system" in-between adding a new one, or do you enter a bunch of them and then submit?

**Comment by RedfoxCh** [comment]
Sure, gladly; The single steps were precisely those listed in the sequence listed in the OP, but to specifically answer your questions:

> after submitting the intial set of distances, do you "Start New" or just add the distances for the unknown systems?

If by "intial set of distances" you mean the reference systems for the trilateration of the current system, then the answer is: I do not use Start New". I just go ahead and add the unknown systems and their distances below the initial set. "Start New" would clear the list and thus prevent me to add distances to unknown systems.

> do you submit each "unknown system" in-between adding a new one, or do you enter a bunch of them and then submit?

I do "enter a bunch of them and then submit", that's correct. 5 in this case, to be precise.

Additional info, although I'm not sure if it is relevant: The first 'hang' was after I had entered and submitted about 4-5 sets, deleting the submitted unknown systems after submitting them and then entering and submitting the next set. After the 'hang' during the submit of the last set, I killed the application and restarting it. Then I did a new trilateration and tried entering that last set of unknown systems again, resulting in another 'hang'. Same defect twice in a row with the same data constellation? Sounded like a good point to start the investigation, thus this bug report. Hope this is coherent and helpful.

**Comment by finwen** [comment]
It has happends for me too. Some months ago it was more frequent but i
solved one bug with it. But its probably still a way to enter that state
now.

Will see if i can reproduce it.

2016-02-23 21:31 GMT+01:00 RedfoxCh <notifications@github.com>:

**Comment by RedfoxCh** [comment]
I've done dozens of submissions with 20 distances each, no issues anymore.

About a week back I did one with around 40, and EDD froze on me again. No big deal, really, I just thought I'd give an update on the much improved state on my end.

**Comment by RedfoxCh** [comment]
Have been submitting batches of 100 distances for a few days now (with 3.0.5) and have not had any issues. With Anthor's performance improvements on EDSM the typical response time for a batch of 100 distances even went down from about 150sec to about 1-2sec.

**Comment by AnthorNet** [comment]
That is good to know ;)
