### ISSUE TITLE
Enforce single-instance mode

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#129]
Instead of opening a new instance of the app, ensure only a single copy can run at a time. (Sorry, can't think of the proper term for it right now)

Open currently-running copy, pop up a dialog, whatever. Maybe it's just me, but several times now when shutting down the computer I've found a second copy of EDDiscovery running.  I'm actually amazed my DB hasn't blown up!

**Comment by finwen** [comment]
+1

But we need to be sure that the other EDD is alive  and not a half dead or
just a thread that have not shut down and UI is closed.
EDD had a few bugs before then a thread didnt stop at exit and the proces
thas still running in background.  In that case we cant  move the old to
front.

One other way to do it can also be to "kill" the old EDD.

2016-02-24 4:52 GMT+01:00 Michael Werle <notifications@github.com>:
