### ISSUE TITLE
Feature Request: Add "Data Sold $" field.

### ISSUE THREAD

**Issue by Red13x3** [EDDiscovery/EDDiscovery#13]
Synopsis:  1. Add a numeric field to the system records that allow user to enter the amount of money they have earned for a system when handing in cartographic data.

Reasoning: I like to know if I have fully explored as system, along with detailed surface scans or not, and how much money did I make on any particular system.  Needs to be numeric and have it auto formatted to the Windows system number format for thousands, but no decimals.

Optional: A field somewhere, be it on the main screen or not, to show you the total of all those $ amounts. Just because you want to show off. :)

**Comment by gregmalcolm** [comment]
Interesting thought. It makes me want to go sell some data and take a look at what information shows up in the logs.

**Comment by Red13x3** [comment]
I'd also love a checkbox that indicates I was the first to discover the main star in the system, because you then get your name plastered on it. :)

Mark

--
Mark Jelic
iPhone: 0402 322 901

**Comment by robbyxp1** [comment]
Closed. We will address this in the journal 2.2
