### ISSUE TITLE
Wrong sum of Data and Mats

### ISSUE THREAD

**Issue by HomirMunn2** [EDDiscovery/EDDiscovery#1300]
The calculated sum of Data and Mats in the Materials Panel does not correspond with the sums in the game. The amount of Data is too big while the amount of Mats is too low.

**Comment by iainross** [comment]
They look to be nearly backwards but not quite, and my total isn't quite adding up.  I'll have a gander at the weekend if nobody beats me to it.

**Comment by klightspeed** [comment]
Manufactured mats are being added to data instead of materials.

**Comment by robbyxp1** [comment]
public int DataCount { get { return Count(new string[] { MaterialCommodities.MaterialEncodedCategory}); } }
        public int MaterialsCount { get { return Count(new string[] { MaterialCommodities.MaterialRawCategory, MaterialCommodities.MaterialManufacturedCategory }); } }

**Comment by robbyxp1** [comment]
should solve it
