### ISSUE TITLE
Screenshot convert but refuse to appear in application

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#1302]
I'm using EDDiscovery 8.3.1.0

The scresnshots are correctly taken, converted and organized, however they do not display in the app window and the log display the following error:

`Error in executing image conversion, try another screenshot, check output path settings. (Exception Could not find file 'F:\Games\Elite Dangerous\Tools\EDDiscovery\Screenshot_0000.bmp'.)`

ED put the screenshots in d:\Users\"$myuser"\Pictures\Frontier Developments\Elite Dangerous

I organize them in f:\Games\Elite Dangerous\Pictures\Screenshots\"$mycmdr"\...\...

Any clue?

**Comment by klightspeed** [comment]
In your trace log, is there an associated stack trace?

**Comment by phroggster** [comment]
Also, there appears to be three different paths listed. One of these is likely incorrect:
* `F:\Games\Elite Dangerous\Tools\EDDiscovery\`
  * Where ED is reportedly saving the screenshots and EDD is looking for them.
* `D:\Users\$USERNAME\Pictures\Frontier Developments\Elite Dangerous`
  * Where ED is likely saving the screenshots
* `f:\Games\Elite Dangerous\Pictures\Screenshots$cmdr`
  * Where you desire the screenshots to go.

**Comment by phroggster** [comment]
When you said,
> I organize them in f:\Games\Elite Dangerous\Pictures\Screenshots"$mycmdr"......

Is that the output path that EDD is set to save the converted screenshots to?

**Comment by andreaspada** [comment]
Well, certainly the path in the error message is wrong. I neither imagine why it's here... I never used it.

---

> When you said,
> 
>     I organize them in f:\Games\Elite Dangerous\Pictures\Screenshots"$mycmdr"......
> 
> Is that the output path that EDD is set to save the converted screenshots to?

Yes. And it's working. Here it is my setup:

![capture-eddiscovery_screenshot_config](https://user-images.githubusercontent.com/4296635/30940957-8d74b21e-a3b9-11e7-986b-8654e1d6c4d1.PNG)

In the log, I find this traces:

```
[2017-09-27 19:19:20Z] Trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

[2017-09-27 19:19:20Z]    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

[2017-09-27 19:19:20Z]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)

[2017-09-27 19:19:20Z]    at EDDiscovery.ScreenShots.ScreenShotImageConverter.TryGetScreenshot(String filename, String cur_sysname, Int32& cmdrid, JournalScreenshot& ss, String& store_name, Point& finalsize, DateTime& timestamp, Bitmap& bmp, String& readfilename, Action`1 logit, Boolean throwOnError) in C:\projects\eddiscovery\EDDiscovery\ScreenShots\ScreenShotImageConverter.cs:line 314

[2017-09-27 19:19:20Z]    at EDDiscovery.ScreenShots.ScreenShotImageConverter.GetScreenshot(String inputfile, String cur_sysname, Int32& cmdrid, JournalScreenshot& ss, String& store_name, Point& finalsize, DateTime& timestamp, String& readfilename, Action`1 logit) in C:\projects\eddiscovery\EDDiscovery\ScreenShots\ScreenShotImageConverter.cs:line 239

[2017-09-27 19:19:20Z]    at EDDiscovery.ScreenShots.ScreenshotDirectoryWatcher.ProcessScreenshot(String filename, String sysname, JournalScreenshot ss, Int32 cmdrid, ScreenShotImageConverter cp) in C:\projects\eddiscovery\EDDiscovery\ScreenShots\ScreenShotDirectoryWatcher.cs:line 193
[2017-09-27 19:19:20Z] Error in executing image conversion, try another screenshot, check output path settings. (Exception Could not find file 'F:\Games\Elite Dangerous\Tools\EDDiscovery\Screenshot_0000.bmp'.)
```

**Comment by klightspeed** [comment]
Looks like neither `$InputFolder\Screenshot_0000.bmp` nor `$Pictures\Frontier Developments\Elite Dangerous\Screenshot_0000.bmp` are found, so it looks for `Screenshot_0000.bmp` in the program's working directory, and this is where the error comes from.
<https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/ScreenShots/ScreenShotImageConverter.cs#L249>
Since the screenshot is indeed being converted, this suggests the directory watcher is performing the conversion, and the journal entry conversion is then erroring out.

This, combined with the fact that there is no screenshot converted callback, would be the cause of the screenshot not being displayed.

**Comment by andreaspada** [comment]
Well, there's a reason it started to give such problem now? It was working perfectly a couple of days ago...

**Comment by klightspeed** [comment]
Perhaps the game is taking more than 5 seconds to write the image out?

Also, the screenshot display has been separated from the image conversion, and @robbyxp1 removed the screenshot converted callback.

**Comment by phroggster** [comment]
Yeah, it was revised in 854d50ad4af1c0c2e98091449ff75116c0ad03f5 ~6 days ago.

**Comment by andreaspada** [comment]
I'm sorry, I can't see the point... 

Actually, the screenshots are very fast. After the 2.4 update, the game is working much better and smoother than before. 

Any idea how to solve that?

**Comment by phroggster** [comment]
Close the ScreenShotUserControl panel, and wait for a fix.

**Comment by andreaspada** [comment]
Done. KUDOS!

**Comment by andreaspada** [comment]
Just checked. Now it display the screenshot as intended, however not fast like before - it has some seconds delay - and still present the error message.

Trace in log:

```
[2017-09-28 12:54:21Z] Exception watcher: Could not find file 'F:\Games\Elite Dangerous\Tools\EDDiscovery\Screenshot_0000.bmp'.
[2017-09-28 12:54:21Z] Trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

[2017-09-28 12:54:21Z]    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

[2017-09-28 12:54:21Z]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)

[2017-09-28 12:54:21Z]    at EDDiscovery.ScreenShots.ScreenShotImageConverter.TryGetScreenshot(String filename, String cur_sysname, Int32& cmdrid, JournalScreenshot& ss, String& store_name, Point& finalsize, DateTime& timestamp, Bitmap& bmp, String& readfilename, Action`1 logit, Boolean throwOnError) in C:\projects\eddiscovery\EDDiscovery\ScreenShots\ScreenShotImageConverter.cs:line 314

[2017-09-28 12:54:21Z]    at EDDiscovery.ScreenShots.ScreenShotImageConverter.GetScreenshot(String inputfile, String cur_sysname, Int32& cmdrid, JournalScreenshot& ss, String& store_name, Point& finalsize, DateTime& timestamp, String& readfilename, Action`1 logit) in C:\projects\eddiscovery\EDDiscovery\ScreenShots\ScreenShotImageConverter.cs:line 239

[2017-09-28 12:54:21Z]    at EDDiscovery.ScreenShots.ScreenshotDirectoryWatcher.ProcessScreenshot(String filename, String sysname, JournalScreenshot ss, Int32 cmdrid, ScreenShotImageConverter cp) in C:\projects\eddiscovery\EDDiscovery\ScreenShots\ScreenShotDirectoryWatcher.cs:line 202
[2017-09-28 12:54:21Z] Error in executing image conversion, try another screenshot, check output path settings. (Exception Could not find file 'F:\Games\Elite Dangerous\Tools\EDDiscovery\Screenshot_0000.bmp'.)
```

**Comment by phroggster** [comment]
I haven't tried the build from #1308, but I'm not sure which image we should be displaying. The raw BMP would present the highest quality and be the quickest, but some would argue that they want to see the possibly cropped, resized, or otherwise modified, converted output (PNG).

I'm in favour of viewing the converted image, even if it takes longer, if solely as a quick means to verify conversion settings.

**Comment by andreaspada** [comment]
Yes, I understand. Maybe, it should be interesting to have this as a choice, under Screenshots settings.

Anyway, the error message persist...

P.S. If EDDiscovery was written in Python, I could help, but Visual Studio is too weird to me, yet...

**Comment by klightspeed** [comment]
The delay does suggest that the timer is catching the image, and the journal screenshot processing is not.

In the trace log, does it log what filename is actually being converted?

**Comment by andreaspada** [comment]
Last trace log:

> [2017-09-28 13:40:14Z] Exception watcher: Could not find file 'F:\Games\Elite Dangerous\Tools\EDDiscovery\Screenshot_0004.bmp'.
> [2017-09-28 13:40:14Z] Trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
> 
> [2017-09-28 13:40:14Z]    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
> 
> [2017-09-28 13:40:14Z]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
> 
> [2017-09-28 13:40:14Z]    at EDDiscovery.ScreenShots.ScreenShotImageConverter.TryGetScreenshot(String filename, String cur_sysname, Int32& cmdrid, JournalScreenshot& ss, String& store_name, Point& finalsize, DateTime& timestamp, Bitmap& bmp, String& readfilename, Action`1 logit, Boolean throwOnError) in C:\projects\eddiscovery\EDDiscovery\ScreenShots\ScreenShotImageConverter.cs:line 314
> 
> [2017-09-28 13:40:14Z]    at EDDiscovery.ScreenShots.ScreenShotImageConverter.GetScreenshot(String inputfile, String cur_sysname, Int32& cmdrid, JournalScreenshot& ss, String& store_name, Point& finalsize, DateTime& timestamp, String& readfilename, Action`1 logit) in C:\projects\eddiscovery\EDDiscovery\ScreenShots\ScreenShotImageConverter.cs:line 239
> 
> [2017-09-28 13:40:14Z]    at EDDiscovery.ScreenShots.ScreenshotDirectoryWatcher.ProcessScreenshot(String filename, String sysname, JournalScreenshot ss, Int32 cmdrid, ScreenShotImageConverter cp) in C:\projects\eddiscovery\EDDiscovery\ScreenShots\ScreenShotDirectoryWatcher.cs:line 202
> [2017-09-28 13:40:14Z] Error in executing image conversion, try another screenshot, check output path settings. (Exception Could not find file 'F:\Games\Elite Dangerous\Tools\EDDiscovery\Screenshot_0004.bmp'.)
>

**Comment by klightspeed** [comment]
Please try the build at <https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.1759/artifacts> and see how you go.  This should also actually log the filename that it detects in the directory watcher.

**Comment by andreaspada** [comment]
At first, it seems it was solved, but on the second screeenshots continue to present the error message.

Trace:

> 
> [2017-09-28 14:21:46Z] Exception watcher: Could not find file 'F:\Games\Elite Dangerous\Tools\EDDiscovery\Screenshot_0000.bmp'.
> [2017-09-28 14:21:46Z] Trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
> 
> [2017-09-28 14:21:46Z]    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
> 
> [2017-09-28 14:21:46Z]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
> 
> [2017-09-28 14:21:46Z]    at EDDiscovery.ScreenShots.ScreenShotImageConverter.TryGetScreenshot(String filename, String cur_sysname, Int32& cmdrid, JournalScreenshot& ss, String& store_name, Point& finalsize, DateTime& timestamp, Bitmap& bmp, String& readfilename, Action`1 logit, Boolean throwOnError) in C:\projects\eddiscovery\EDDiscovery\ScreenShots\ScreenShotImageConverter.cs:line 314
> 
> [2017-09-28 14:21:46Z]    at EDDiscovery.ScreenShots.ScreenShotImageConverter.GetScreenshot(String inputfile, String cur_sysname, Int32& cmdrid, JournalScreenshot& ss, String& store_name, Point& finalsize, DateTime& timestamp, String& readfilename, Action`1 logit) in C:\projects\eddiscovery\EDDiscovery\ScreenShots\ScreenShotImageConverter.cs:line 239
> 
> [2017-09-28 14:21:46Z]    at EDDiscovery.ScreenShots.ScreenshotDirectoryWatcher.ProcessScreenshot(String filename, String sysname, JournalScreenshot ss, Int32 cmdrid, ScreenShotImageConverter cp) in C:\projects\eddiscovery\EDDiscovery\ScreenShots\ScreenShotDirectoryWatcher.cs:line 202
> [2017-09-28 14:21:46Z] Error in executing image conversion, try another screenshot, check output path settings. (Exception Could not find file 'F:\Games\Elite Dangerous\Tools\EDDiscovery\Screenshot_0000.bmp'.)
>

**Comment by klightspeed** [comment]
With that build, are there any `Journal Screenshot logged` or `Directory watcher picked up screenshot` events in the trace log?

**Comment by andreaspada** [comment]
> [2017-09-28 14:21:17Z] Journal Screenshot logged \ED_Pictures\Screenshot_0000.bmp

and 

> [2017-09-28 14:21:14Z] Directory watcher picked up screenshot d:\Users\andrea\Pictures\Frontier Developments\Elite Dangerous\Screenshot_0000.bmp

**Comment by klightspeed** [comment]
So there's a 3 second delay between the file being written and the journal event being written / read.

I'm not sure what we can do about this without further increasing the directory watcher delay,

**Comment by andreaspada** [comment]
My system continue to display the same error message. And it freezes a lot! Whenever I take a screenshot, the whole app freeze.

Can we return to the previous code, please? It's unusable right now...

**Comment by andreaspada** [comment]
I tried with a totally new setup, in a different folder. Same error...

**Comment by phroggster** [comment]
Which build are you trying? I just tried with what will likely become 8.3.2 from https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.1776/artifacts and screenshots were instant and unremarkable...

**Comment by phroggster** [comment]
Even taking three screenshots in rapid succession from 8ec8ce7e505366d760cb29875e5e521bc62653fb (the 3.2.1.1776 build I linked above) didn't break things, but it did kind of peg one of my CPU cores for a moment as would be expected from converting three BMP files to PNG files... Not sure what you're seeing.
![untitled](https://user-images.githubusercontent.com/14035789/31028006-f956aa24-a511-11e7-9dc8-4b5b94c51f22.png)

**Comment by andreaspada** [comment]
Using last build - 8.3.3.0 - from github, and after I rebuilt the database in its entirety, finally always seems to work. Screenshot finally are working as expected, no more error messages, and duplicate entries seems gone too.
The performance is greatly improved, probably due to the new database. Which gave me the idea that maybe we should have some optimization routines available for maintenance...

**Comment by phroggster** [comment]
That's actually a good idea that needs to be migrated to a new enhancement request. Whether automatically running [vacuum](https://sqlite.org/lang_vacuum.html) on the databases every thirty days or so, or adding an option to the safe mode form, it could be helpful to keep things greased.

Note that [auto_vacuum](https://sqlite.org/pragma.html#pragma_auto_vacuum) is the devil.

**Comment by andreaspada** [comment]
Yep, provably an optional in safe mode will be enough. We don't want devils in our databases! 😜
