### ISSUE TITLE
Route/location error

### ISSUE THREAD

**Issue by Fusion2905** [EDDiscovery/EDDiscovery#1303]
There seems to be an issue with retrieval of the current system name, and consequently route display on 2D/3d maps, as well as on the EDSM travel map are wrong (to put it mildly).

Starting today (27. sep) every couple of jumps EDD seems to think that I've jumped to 60 Tau Draconis (approximately 16.097 ly away) it has happened 3 times so far.

Could it be due to Companion API being temporarily disabled?

I deleted those phantom jumps from EDSM log, so now my route looks ok. If it happens again, I'll report it.

![jumps](https://user-images.githubusercontent.com/32344123/30939803-093a23c8-a3df-11e7-9b90-f774a412f392.png)

**Comment by phroggster** [comment]
Wasn't 60 Tau Draconis one of the "real" training systems being used? I wonder if that issue is occurring again.

**Comment by klightspeed** [comment]
That system apparently often had its location misreported:
https://forums.frontier.co.uk/showthread.php/179063-EDSM-Elite-Dangerous-Star-Map?p=4958362&viewfull=1#post4958362

A trace log of when this occurred and/or journals from this period would hopefully help.

**Comment by Fusion2905** [comment]
Thanks for the replies, guys.

@klightspeed
I'm sorry, I'm not entirely sure I understood you. Did you want me to upload the log and/or the journal for the instances when the error occurred?

**Comment by klightspeed** [comment]
> I'm sorry, I'm not entirely sure I understood you. Did you want me to upload the log and/or the journal for the instances when the error occurred?

Would it please be possible to post the journal entry of an affected jump from journal file, the journal entry of the same jump as stored by EDDiscovery (right-click the journal entry and copy journal entry to clipboard), and trace log lines from around the time of the jump?

**Comment by Fusion2905** [comment]
Unfortunately not at the moment. As I was trying to get my route in order I deleted those specific journal entries.

I am currently not far from the last jump where the glitch happened. I'll retrace my route later today to see if it happens again. If/when it does I'll post the journal entries here.

Thanks for the clarificarion, btw :)

Cheers!

**Comment by Fusion2905** [comment]
I've retraced my steps for the entire session during which the errors I first described happened, but I couldn't reproduce them. 

It's worth mentioning that in both cases I was using EDD v 8.3.1.0.
 
I'm going to upgrade to the new version for my next play session and keep an eye out. If anything happens I'll report it here.

In the meantime, fly safe commanders o7.

**Comment by phroggster** [comment]
Well, if it occurs again for you, please reopen this issue and attach any EDD trace logs and ED journals that contain any information about it. Hopefully this was just some bug that's since been squished, albeit likely by accident.

**Comment by AnthorNet** [comment]
I am currently monitoring this error, and almost found a dirty fix, the main reason still it odd to me!
