### ISSUE TITLE
Journal Last 10 Entries Selection Filter Seemingly Ineffective

### ISSUE THREAD

**Issue by phroggster** [EDDiscovery/EDDiscovery#1319]
From Discord user knausis#4195:
![unknown](https://user-images.githubusercontent.com/14035789/31041976-d1817838-a563-11e7-92c7-3fef5be88acb.png)

> Is that a bug? that it shows more than 10 entries? i remember it showing only 10 entries in older version. now it filter 10 entries and then adds new events instead of replacing them

**Comment by klightspeed** [comment]
So basically AddNewJournalRow needs to remove any rows that no longer match the filter after inserting rows.
