### ISSUE TITLE
edsm sync

### ISSUE THREAD

**Issue by JonathonPenberthy** [EDDiscovery/EDDiscovery#132]
When i press Sync with EDSM it says
"please enter commander name before sending distances/ travel history to EDSM!"
How do I configure it to use my commander name / apikey?

**Comment by gregmalcolm** [comment]
Sorry, don't have EDD in front of me to check, but I think you either enter it into the box on the top right of the main app page or it's in the settings tab. I think... :D

If I'm wrong then maybe the feature for setting it is hiding in the drop down menus. It's somewhere I tell you!

**Comment by RedfoxCh** [comment]
@JonathonPenberthy: My reply to your (?) post on the ED forums, hope it helps:
https://forums.frontier.co.uk/showthread.php?t=138155&p=3634220&viewfull=1#post3634220
