### ISSUE TITLE
EDDi and API Interface

### ISSUE THREAD

**Issue by CmdrAldrin** [EDDiscovery/EDDiscovery#1321]
Hello,

I have a message saying that EDDI Status: Frontier API Connection Lost. I have stepped through trying to re-establish this using the verification code and each time it fails. This problem arose after installing 2.3.1. Any help would be much appreciated.

Cmdr Aldrin

**Comment by klightspeed** [comment]
https://forums.frontier.co.uk/showthread.php/378874-cAPI-asking-user-to-purchase-ED?p=5966220&viewfull=1#post5966220

**Comment by klightspeed** [comment]
Also, this is EDDiscovery.  EDDI is at https://github.com/cmdrmcdonald/EliteDangerousDataProvider

**Comment by robbyxp1** [comment]
Closing as not appropriate to EDD!
