### ISSUE TITLE
Unhandled exception when using panels

### ISSUE THREAD

**Issue by Teyar** [EDDiscovery/EDDiscovery#1323]
I use panels from EDDiscovery im as an overlay in the window mode of Ed. With the new update of today, the following problem occurs (in the example, it concerns the "Shopping list", but has also occurred with "Scan"):
![fehlermeldung 1](https://user-images.githubusercontent.com/30482684/31047544-240f2182-a60d-11e7-8fe1-8a7c06b2077a.png)
The error occurs when I change either in the menu of the Panals something (as "Visible", "On the top" or other) or when I change an entry.

And still the corresponding logfile: 
[Trace_20170930174234.0.log](https://github.com/EDDiscovery/EDDiscovery/files/1346576/Trace_20170930174234.0.log)

Would be nice if the bug could be fixed.
Thank you

**Comment by phroggster** [comment]
```
[2017-09-30 17:44:07Z] 
==== UNHANDLED UI EXCEPTION ====
System.ArgumentOutOfRangeException: Der Wert -25 ist für SplitterDistance ungültig. SplitterDistance muss größer als 0 sein.
Parametername: SplitterDistance
   bei System.Windows.Forms.SplitContainer.set_SplitterDistance(Int32 value)
   bei EDDiscovery.UserControls.UserControlShoppingList.Display()
   bei EDDiscovery.UserControls.UserControlShoppingList.SetTransparency(Boolean on, Color curcol)
   bei EDDiscovery.Forms.UserControlForm.UpdateTransparency()
   bei EDDiscovery.Forms.UserControlForm.CheckMouse(Object sender, EventArgs e)
   bei System.Windows.Forms.Timer.OnTick(EventArgs e)
   bei System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
==== cut ====
```

**Comment by klightspeed** [comment]
Google translate of message:
```
The value -25 is invalid for SplitterDistance. SplitterDistance must be greater than 0.
```

**Comment by iainross** [comment]
8.3.2 is sometimes putting the splitter left of where I want it - in this case obviously left of the left side of the window.  #1322 will probably fix it.  Now I'm paranoid so I'm going to double check.

**Comment by iainross** [comment]
I can still make it happen - I need to work at it - but it's possible.

**Comment by phroggster** [comment]
While you're at it, and rather unrelated to this issue...

It's not a deal breaker, but is it possible to filter the journal events that come in to only do UI updates when `je` is an `
IMaterialCommodityJournalEntry`? As-is, the panel contents dance a little for every new event after a resize, even if the `je` had nothing to do with matcoms.

**Comment by iainross** [comment]
I knew there was something I'd forgotten to do...

**Comment by iainross** [comment]
#1329 / #1330 should make it never happen even if you make the control so narrow it's unusable to try and make it happen...
