### ISSUE TITLE
Minimised Unframed Panel Windows Can't Be Easily Restored/Maximised

### ISSUE THREAD

**Issue by Teyar** [EDDiscovery/EDDiscovery#1327]
This error has existed since one or two updates (at least it was different before).
But I forgot to report it.

If you minimize a panel window without using the "Toggle Show taskbar icon for this window" selection, the window should be minimized to a button (starting at the bottom left of the desktop above the taskbar). If you then click on the button, the window should be restored at the last position.
This is not working at the moment. If you hover the mouse on the button of the minimized panel window, the normal mouse pointer will not appear, but the one that would zoom the button (which, however, does not work).
Currently, you have to restore the panel window with ALT + TAB, which is very cumbersome to use as an overlay in ED.
Below two pictures that illustrate what I mean. However, this long explanation was necessary because the mouse pointer is not displayed in a screen shot.

![fehler 1-1](https://user-images.githubusercontent.com/30482684/31049452-b005d1a6-a633-11e7-806a-b7290c7d8524.png)

![fehler 1-2](https://user-images.githubusercontent.com/30482684/31049453-b746f256-a633-11e7-86a0-f69b549425ac.png)

Please check once.
Thank you

**Comment by phroggster** [comment]
Looks like we need to add the restore and maximize buttons to the minimised window caption when unframed and not showing in taskbar. Add this to my to-do list of no one else gets to it first.

Painting these be hand can be a very painful task (it's considered non-client area). Suggest temporarily re-framing the window to allow upstream to handle it, which still means a bit of work to intercept the minimize and restore/maximize, but WndProc and CreateParams should be all that is needed.

**Comment by phroggster** [comment]
I take part of that back: `WndProc` doesn't get an `WM_SYSCOMMAND`.`SC_MINIMIZE` when assigning `this.FormWindowState = FormWindowState.Minimized;`. Either everything needs to minimize via the `SC_MINIMIZE` route (yuck), or we need to check `FormWindowState` after every resize (also, yuck).

**Comment by Teyar** [comment]
Currently I can't use it because of my previous error message anyway.
Personally, it is enough for me to go back if the error in my previous message is resolved.

So no stress ( :D ).
Thank you

**Comment by robbyxp1** [comment]
Def not working as intended!  Maybe when minimised the simpliest solution is to show in taskbar

**Comment by Teyar** [comment]
Hmm...
I could not use EDDiscovery for a while because computer was defective and the program on the laptop needs too much resources. That's why I can't say exactly when the error occurred the first time. But before 8.3. xx It still works, I'm sure.

**Comment by phroggster** [comment]
8.3 introduced a couple new base classes that we use for pretty much all of the forms. One added a system menu (this was previously done by some individual, and the other was essentially a

**Comment by Teyar** [comment]
It works again (in 8.3.3).

Thanks
