### ISSUE TITLE
Show Landing Pad Location Upon Pad Assignment

### ISSUE THREAD

**Issue by CBXSteve** [EDDiscovery/EDDiscovery#1328]
Some kind of indicator on where to expect your assigned landing pad to be when entering a station would be very nice. Even popping up a non-active bitmap would be quite useful.

**Comment by AndySpawn** [comment]
Your "compass" (to the left of your "radar") in your hud all ready points to your designated landing pad

**Comment by phroggster** [comment]
@AndySpawn Agreed, but then again, popping up something like the following *would* be ***really*** cool:
![small civilian station landing pad organization](https://eddb.io/images/stations/schema_civillian.png "small civilian station landing pad organization")
*Image courtesy of [EDDB.io](https://eddb.io)*

Unfortunately, I don't believe that we get enough station information until after we've already docked, but I may be mistaken.

**Comment by AndySpawn** [comment]
Very true.  As you say though, I'm not sure what reference you guys could use to pull the right image.  Obviously the pad number is there, since EDDI can reference it all ready.  But station type?  I don't know.

**Comment by robbyxp1** [comment]
Nice idea, but.

We don't get enough info from the journal (all you get is basic station type) and thus could not distinguish the layout of platform statiosn, 

and we don't have enough data about all station types to do this,

So unfeasible.
