### ISSUE TITLE
Vacuum Databases Regularly

### ISSUE THREAD

**Issue by phroggster** [EDDiscovery/EDDiscovery#1335]
andreaspada [stated](https://github.com/EDDiscovery/EDDiscovery/issues/1302#issuecomment-333687353):
> ... Maybe we should have some optimization routines available for maintenance...

I [propose](https://github.com/EDDiscovery/EDDiscovery/issues/1302#issuecomment-333704568) [vacuuming](https://sqlite.org/lang_vacuum.html) both databases every thirty days, ~~or on the next startup after a significant thrashing (such as the systemsWithCoordinates.json sync)~~. A DateTime "lastvacuum" DB register alongside a boolean "vacuumneeded" register could track details.

@andreaspada We will need a label to display on the splash form while the operation is in progress. As you proposed the idea, please reply with an idea or three for what we should show for this. Something in line with the other Kerbal-esque messages would be nice, such as "Computing [Drake Equation](https://en.m.wikipedia.org/wiki/Drake_equation)",  "Squaring [Planck Constant](https://en.m.wikipedia.org/wiki/Planck_constant#Value)", or "Evaporating [B–E Condensate](https://en.m.wikipedia.org/wiki/Bose–Einstein_condensate)" come to mind. Space is limited, but ~24 characters should be ok.

**Comment by klightspeed** [comment]
The EDSystems.sqlite database is currently vacuumed at the end of a full sync:
https://github.com/EDDiscovery/EDDiscovery/blob/master/EliteDangerous/DB/SQLiteConnectionSystem.cs#L391

**Comment by phroggster** [comment]
Huh, that didn't show up in my prior search, but sure enough... I do still think that regular maintenance at startup would be a good idea, and the user database still needs an invite to the party.

**Comment by andreaspada** [comment]
Ok, maybe we did not need that, as it seems that vacuum is already happening, but:
@phroggster: What about "**Solving P ≠ NP solution**"? 
Anyway, I loved your suggestion, especially "**Computing Drake Equation**" and "**Squaring Planck Constant**".

**Comment by robbyxp1** [comment]
Don't impact start up performance if it means 20s of the program disappearing!

**Comment by phroggster** [comment]
The SplashForm showing a ~20 second message about non-probabilistic theory every 30 days —unless the edsm json dump was refreshed during those 30 days. Then it's only displayed for ~5 seconds for the user DB.

**Comment by klightspeed** [comment]
Be aware that during the `VACUUM`, the database will be locked, so it will need to be done before anything starts accessing the database.

Switching the full import to creating a new database, and swapping that database out when the full sync completes would probably help fix the occasional "database is locked" errors some people have been reporting.

**Comment by robbyxp1** [comment]
Does not seem an issue now, especially with the code to allow only partial star data to be stored
