### ISSUE TITLE
Transparent Overlay Gridbar Container for UserControl Panels

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#1336]
I found myself using the summary panel twice, with different configurations.
I like to have a trip summary on my top left corner, and a detailed exploration panel on the top right corners. The panel on the right, will display also the scan details; being on the right, it do not cover any information or parameters in galaxy or system map.
I also have a note on the center, which is a placeholder for a panel I'll try to write, which is intended as a memo (mainly to annotate systems I want to explore near the one I am, or important notes which are not intended as EDSM annotations.)

My idea is to try to develop a barpanel grid overlay, which is able to host some panels, activated by a shortcuts - or event - and which display some sticky information, like the summary + trip panel, in an horizontal layout, un-obstructive as possible. The main advantage over current implementation is that we should not need to re-position each panel every time we open the program. And that we should be able to display more information, using less space - we don't need titles for every window...

I'll try to develop it by myself, but if anyone find the idea interesting, and already know how to do it, I'll be happy to just contribute with some ideas. 

![capture-topbar](https://user-images.githubusercontent.com/4296635/31107995-c2dc67dc-a7cc-11e7-9909-bc2b4b0cfa44.PNG)

**Comment by robbyxp1** [comment]
You can open multiple spanels, each with their own configuration
You can open a grid, and place as many panels as you want into it, and move them as a group.
Not sure what this solves.  I don't think we need a new way of containing panels.

**Comment by andreaspada** [comment]
Got it! 
Actually, I have to check for the action pack. Actually, I did not looked at that, yet... could solve my needs.

**Comment by robbyxp1** [comment]
Closing as explained.
