### ISSUE TITLE
After Upgrading to 8.3.2.0 from v7.x.x.x History is not loading

### ISSUE THREAD

**Issue by codevolunt** [EDDiscovery/EDDiscovery#1337]
After Upgrading to 8.3.2.0 from v7.x.x.x History is not loading

I haven't run EDD for a while, and hadn't created a desktop shortcut after the last upgrade deleted it, so did a search from Windows Start button, and ran the ED Discovery that it found.

This turned out to be a version 7, and i am not sure if this pre-dates the last version I successfully used.

Anyway, the star systems loaded and the tables were re-indexed, and everything looked fine. 

Then I ran the 8.3.2.0 installation, and that looked fine too. When the initial screen loads however, the travel history is not populated, and errors are reported, as shown in the attached image.

Please help!
![edd 8 3 2 0 errors](https://user-images.githubusercontent.com/13076132/31119700-b6d60512-a829-11e7-942e-0eee4043a6c5.jpg)

**Comment by andreaspada** [comment]
I suggest to do a clean install - what about the portable version? - and let eddiscovery rebuild its databases.
Very often, it solve major problems.
After that, and after you checked that everything is working, wipe the older version, to avoid conflicts.

**Comment by codevolunt** [comment]
Thanks Andrea, I will ty that. 

By a Clean Install, do you mean uninstall, then install?

Am guessing that the install doesn't overwrite the ED travel data.
 Kind regards
Nigel 

    On Tuesday, 3 October 2017, 13:21, Andrea Spada <notifications@github.com> wrote:
 

 I suggest to do a clean install - what about the portable version? - and let eddiscovery rebuild its databases.
Very often, it solve major problems.
After that, and after you checked that everything is working, wipe the older version, to avoid conflicts.—

**Comment by andreaspada** [comment]
Well, I suggest you to download a portable version, first. Than, let it recreate the db in its folder. After that, check if it solve your problems. Than, you can decide if do a clean reinstall. I use only the portable version, but I'm pretty sure that your data folder is safe, as the installed version saves it in your %USER%\AppData\Local\EDDiscovery folder...

**Comment by robbyxp1** [comment]
Going to protect function more.. maybe because you have a pre-journal load

**Comment by robbyxp1** [comment]
Patches have gone in, should be solved in next 8.3 release (soon)

**Comment by robbyxp1** [comment]
have you tried the latest and is it ok?

**Comment by codevolunt** [comment]
Hi Andrea, so far I have only had time to run the Portable version, which worked fine. 

I will let you know what happens with the local version. 

Kind regards


Nigel
