### ISSUE TITLE
Feature Request: Dark theme for EDD

### ISSUE THREAD

**Issue by Zefod** [EDDiscovery/EDDiscovery#136]
How about a dark with orange text theme to fit with the game; the EDD window is very bright while playing ;) 

Like they did with the marketconnector: 

![edmc](https://cloud.githubusercontent.com/assets/17833887/13753953/734e2b0e-ea15-11e5-8a6d-88231ab7c888.png)

**Comment by maakfischer** [comment]
+1

**Comment by Red13x3** [comment]
+1 to this idea. :)

--
Mark
iPhone: 0402 322 901

**Comment by finwen** [comment]
Just to bad that Microsoft made it so hard to change themes in Windows
forms....    Have not found a good free solution to that yet. And no time
to make my own yet.....

2016-03-15 1:26 GMT+01:00 Mark <notifications@github.com>:

> +1 to this idea. :)
>
> --
> Mark
> iPhone: 0402 322 901
>

**Comment by gregmalcolm** [comment]
It might be possible to make it customizable by binding some form properties to a user app settings file:

https://msdn.microsoft.com/en-us/library/8eyb2ct1(v=vs.110).aspx

**Comment by robbyxp1** [comment]
It looks real hard.  I tried just programming a few colour changes in, but you would need to do it on a control/control basis. And looking at the skin stuff, it seems mostly for WPF.

**Comment by Zefod** [comment]
I know a few things about java, i'm new to c#. A few years back i used recursive functions in java to edit form control properties on the fly... turns out c# can do the same;

http://stackoverflow.com/questions/22935285/change-color-of-all-controls-inside-the-form-in-c-sharp

i added this to EDDiscoveryform.cs after InitializeComponent();

```csharp
menuStrip1.ForeColor = Color.Orange;
menuStrip1.BackColor = Color.Black;

foreach (Control c in this.Controls)
{
     UpdateColorControls(c);
     this.BackColor = Color.Black;
     this.ForeColor = Color.Orange;  
 }

//recursive function to update control appearance
public void UpdateColorControls(Control myControl)
        {
            try
            {
                myControl.BackColor = Color.Black;
                myControl.ForeColor = Color.Orange; 
            }
            catch  { }

            if (myControl is DataGridView)
            {
                DataGridView MyDgv = (DataGridView)myControl;
                MyDgv.ColumnHeadersDefaultCellStyle.BackColor = Color.Black;
                MyDgv.ColumnHeadersDefaultCellStyle.ForeColor = Color.Orange;
            }

            // Any other non-standard controls should be implemented here too...
            foreach (Control subC in myControl.Controls)
            {
                UpdateColorControls(subC);
            }
        }
```

HTH :)

![clipboard01](https://cloud.githubusercontent.com/assets/17833887/13806029/31b07496-eb59-11e5-9498-6d49beafe5fe.png)

**Comment by robbyxp1** [comment]
Looks good, are you wanting to do the work? Or do you want someone else to do it.

**Comment by Zefod** [comment]
:) I'm new to the whole c#, VS2015, github thing; so lots of learning curve for me i guess.... 
I'll try to experiment a bit more, but don't let me hold you up ;)

**Comment by robbyxp1** [comment]
I'll have a play with your code.  I had a go yesterday, but with
    discrete controls.  If we can automate it like you have in one place
    it may make it much more simpler.
    
    Cheers
    
    Rob
    
    
    On 16/03/2016 09:05, Zefod wrote:
    
    
      :) I'm new to the whole c#, VS2015, github thing; so lots of
        learning curve for me i guess.... 
        I'll try to experiment a bit more, but don't let me hold you up
        ;) 
      —
        You are receiving this because you commented.
        Reply to this email directly or view
          it on GitHub

**Comment by gregmalcolm** [comment]
Heh, I actually learned C# by taking what I learned studying up on Java and using it to get by oj a project that got flung at me at work. Turns out java C# is very java like. Have fun! Got the git side of things theres a bit of a learning curve, but its well worth it when you start to get it. A good tutorial/screencast helps. Good luck!

**Comment by finwen** [comment]
Looks like a good stat on a dark theme!

**Comment by robbyxp1** [comment]
I'm on the way with version 1 of this code - maybe not perfect, but will be better. Thanks to Zefod.  Need to put the infrastructure in to handle it.

**Comment by gregmalcolm** [comment]
There was talk of Git's learning curve earlier in the discussion. I put together a wiki page for git problems and how to solve them:

https://github.com/EDDiscovery/EDDiscovery/wiki/Contributing-to-EDDiscovery-Using-Git

I suspect it's full of gramatical errors right now, but it's a wiki, so can fix it up as we go along... :)

**Comment by Zefod** [comment]
Thanks, that's very useful! Way better than the explanation one of my colleagues gave me ;)

**Comment by robbyxp1** [comment]
Note we are working on themes - which covers this idea..

**Comment by robbyxp1** [comment]
Closed. Themes done
