### ISSUE TITLE
Server communication errors cause lost history

### ISSUE THREAD

**Issue by skwerlman** [EDDiscovery/EDDiscovery#1360]
I occasionally get booted from the ED servers when jumping. When I log back in, the jump will have completed.

Whenever this happens, EDDiscovery seems to miss the fact that my system has changed, and never reports this to EDSM, causing that jump to be lost.

![image](https://user-images.githubusercontent.com/6954107/31250984-7ad071de-a9ea-11e7-87c6-3b50d5708897.png)
In the above image, you can see that the jump was initiated (entry 5737), and that I'm in the new system when I log in (entry 5745), but the completed jump is never reported to EDSM.

![image](https://user-images.githubusercontent.com/6954107/31251132-f698b4c0-a9ea-11e7-9846-1b772f4f0873.png)
Rather, EDSM sees the next completed jump and adds the distances, resulting in a ~60ly jump entry which should be 2 30ly jumps.

I think the solution here is to assume that the jump completed when the last log entry before game load is the start of a jump, and the starting system on game load matches the jump target.

**Comment by phroggster** [comment]
We should already know what it says, but just for the sake of completeness and accuracy, can you attach (drag and drop) a journal file to this ticket that shows this occurring? These files are typically located at `%UserProfile%\Saved Games\Frontier Developments\Elite Dangerous\*.log`.

**Comment by phroggster** [comment]
Oh, and under the Admin menu is an option to "Send Unsynced EDDN Events." Clicking on that should transmit the missing FSD jump journal entry.

**Comment by klightspeed** [comment]
`Send Unsynced EDDN Events` will only send bodies.

Unfortunately, only FSDJumps are sent as travel entries to EDSM.  I have argued that we should also send Location events where either the commander has died or the location is different to before loading the game, but certain people have vetoed that.

**Comment by skwerlman** [comment]
Clicking "Send Unsynced EDDN Events" does nothing.

Here are a pair of log files which show this happening: https://gist.github.com/skwerlman/c1f61e50b5031bc841880f779dc36f7f

Note that there's a `StartJump` event in the first log, and a `Location` event showing the new, correct, location in the second log, but there is no `FSDJump` event for that system in either log, which is probably why "Send Unsynced EDDN Events" doesn't work.

**Comment by phroggster** [comment]
My apologies, I thought that was included with "Send Unsynced EDDN Events."

I'm guessing that *certain people* don't want us to be forging data that doesn't exist. Well, I'm off the opinion that "simulated data" is better than no data. Sure would be nice if FDev would just include some form of FSDJump when loading after an instancing or connectivity failure.

**Comment by phroggster** [comment]
It looks like the faked `FSDJump.FuelUsed` field would be near-impossible to accurately simulate, shy of a `FuelScoop` event just prior to `StartJump.` I also think that any FuelUsed inaccuracies in a forged FSDJump are totally worth the benefits gained by faking it.

**Comment by klightspeed** [comment]
FuelUsed etc are not used by the EDSM submission, and the EDDN submission of FSDJump events is only used for faction info (FuelUsed is not sent to EDDN).

**Comment by phroggster** [comment]
The timestamp is the only other thing that we'd be lacking then, no? Maybe use +20s from the StartJump?

**Comment by klightspeed** [comment]
So if you have a Location, look backwards until you find a Resurrect, FSDJump or StartJump event?

If you have a StartJump event for the same system, then either synthesize a FSDJump or use the Location.

If you have a Resurrect, then use the Location.

**Comment by phroggster** [comment]
If our location is `foo`, we're not in a multi-crew, and we've started a jump but it gets hyperdicted by a `"MusicTrack":"MainMenu"`, followed by a `LoadGame` and a `"Location":"bar"`, *then* we counterfeit an `"event":"FSDJump", "StarSystem":"bar", ..."` as accurately as we can in our user database and send it off. I do propose using some sort of "CounterfeitEvent" bool (maybe in the event sync flag, but it can be tricky to query a DB for a bit in a flag, so maybe directly in the event json itself) so that we can later find any of these should the need arise.

**Comment by robbyxp1** [comment]
Well, my 2 cents worth.  I don't think we should create our own fake records to correct frontiers output.  It will inevitably be wrong in some way in the future when they change their behaviour.   

We could look back and see if there was a difference in location between now and previously, but there is no FSD jump or died event (remember that can change location).

I see many perils and very few positives.

**Comment by klightspeed** [comment]
EDSM will reject a duplicate travel entry anyway, so there should be no harm just sending the system timestamp, name and coordinate from the Location record to EDSM (not EDDN), at least so we can be sure EDSM's idea of where the player is matches the game's idea of where the player is.

**Comment by robbyxp1** [comment]
That sounds like a good idea. Nice and simple and contained.

**Comment by iainross** [comment]
@skwerlman as an aside, I raised this with FD and they asked me to turn on some extra logging in game and update them with the output next time it happened.  Obviously it's not happened to me since...

If you're still seeing this with any kind of regularity then please do jump into https://forums.frontier.co.uk/showthread.php/361942-Missing-journal-after-disconnect

**Comment by skwerlman** [comment]
Depending on the day, I might have this happen never, or 3 times in an hour. I'll definitely try to collect the info for that thread.

Thanks guys for getting this figured out! :tada:
