### ISSUE TITLE
Is it possible to have OBS addon to output scan data?

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#1361]
Hi! I'm looking at OBS - to hopefully write a new addon - and I would like to know if is it possible, right now, to have OBS write to my output folder the result of the scan data, as appear on the summary panel. 

If not, can I try to add it?

**Comment by phroggster** [comment]
OBS, the Open Broadcast Software? Is it good enough to just capture a popout panel with the information that you want? If not, it's not too difficult to write an image file out to disk.

> If not, can I try to add it?
Yes, [you certainly can](https://github.com/EDDiscovery/EDDiscovery/blob/master/LICENSE.md). Without seeing any code it's hard to tell you whether it'll actually get merged in here, but as long as the changes can scratch an itch and don't create problems elsewhere, I'm sure it would be appreciated.

**Comment by andreaspada** [comment]
So, I'm not very pleased by the current popup implementation, although it can and certainly works for someone else. I'm actually think in write an overlay add-on to display a selection of text feeds, already created by the EDDiscovery OBS add-on, similar to the way a transparent console with multi tails works on unix. One kind of information I definitely want to be able to display is the scan summary for each scanned bodies. So, I see that, currently, the OBS add-creates lots of files - with ship name, id, type, system, system body, etc... it lack the scan information. So, it's already something we can be able to have? As soon as I can, I'll give the code a look, to see it there's already some way to achieve this, or I'll try to write it.

**Comment by robbyxp1** [comment]
You can modify the OBS pack to write as many files with as much different info as you need to a file.

The action documentation (see the wiki) describes the action language, from that you can grab all the info EDD has about a scan/system using commands.  I did a snapshot of what i thought was useful in the current OBS.

With Action language, you can display an non modal Dialog on screen and control it.  At the moment it can't go transparent but that will come.  I've thought of using Action to create overlays and driving them programatically.

As regards changing the fundamental systems of user controls/popups/grids, I don't want to see another parallel system.  I'm happy with any number of panels being added - mixes of current ones (like the shopping list), new ones created, etc, but the framework is good for the majority of users and we need to avoid having too many ways of doing the same thing.  Its hard enough to document in the wiki as it is and its bad UI practise to do things two ways.  We are moving to panelise everything and regularise the UI interface from the historic one to this panel version.

**Comment by andreaspada** [comment]
Awesome, @robbyxp1 !!!

> You can modify the OBS pack to write as many files with as much different info as you need to a file.

Yep, it seems the more logical and clean way to do this.

> I've thought of using Action to create overlays and driving them programatically.

Is almost exactly what I imagine. I play with just one monitor, and I found having some overlays - or transparent popup - extremely useful. 

> As regards changing the fundamental systems of user controls/popups/grids, I don't want to see another parallel system.

Of course, I never intended - neither have the abilities - to do that. Is why I directed my attention to the OBS Add-On. Extending it a little, it already provide us the meaning to feed an overly - which can be just an add-on, or a third-party extension - so we do not need to mess with the current panels and popup.

> I'm happy with any number of panels being added - mixes of current ones (like the shopping list), new ones created, etc, -

So, can I code and propose an auxiliary "Detailed Scan Summary" panel, which complement the current "SPanel", displaying summaries of scan information in a more flexible way? For example, with a right-text orientation option, as well as some other tweaks? I really found difficult to use the "scan information" output alongside the scan summary. It can be perfectly my fault, but if you do not bother with...

All the best!

**Comment by robbyxp1** [comment]
Yep, but.. 

Remember the spanel is configurable - you can turn on/off info.  

You can turn off all journal event printing by selecting the event filter to none, You can just then have the system info on/off, target line on/off, 

You can turn the scan reports on/off.  If on, The scans will appear when they occur, and the option in the right click allows you to show them forever.

And remember you can have as many scan panels as you want, each remembering its state

So, before you create another panel, why not just put more configuration into the current panel with a right click options under configure scan options to add different output formats. Be much easier than doing a new panel.

If a panel is too similar to one we have, it will be asked to be merged.

rob

**Comment by andreaspada** [comment]
Yes, of course. Much more wise to extend the current implementation. 

Currently I use two instances of SPanel. On the left, I have the System name, with a short summary of its state, faction, etc... and the distance to my target.
On the right, detailed scan information. 

I'll look for some switches and a little organization.

**Comment by robbyxp1** [comment]
Closing as not an issue now.
