### ISSUE TITLE
Error at VoicePackV5::Scan Step 43: Line 870:

### ISSUE THREAD

**Issue by EoD** [EDDiscovery/EDDiscovery#1373]
When scanning asteroid belt cluster, the following error occurs in the Log with EDD 8.3.3:
```
Arrived at system Plaa Aescs BL-C c1-1 Visit No. 1
Error at VoicePackV5::Scan Step 43: Line 870:
Let Expression does not evaluate
```
The same cause as in #1059.

**Comment by robbyxp1** [comment]
Missing gravity, pushing 5.0.2 with more protection against these random scans

**Comment by klightspeed** [comment]
It's an asteroid cluster scan.  Probably should have an `IsPlanet`

**Comment by robbyxp1** [comment]
I've protected more of it from random missing data in 5.0.2
