### ISSUE TITLE
GetBodies(string sysName) wrong API call

### ISSUE THREAD

**Issue by EoD** [EDDiscovery/EDDiscovery#1374]
https://github.com/EDDiscovery/EDDiscovery/blob/08874905c934b0005771543d2d55a19ef0a796e8/EliteDangerous/EDSM/EDSMClass.cs#L708-L713

This API call does yield a 404. For example: https://www.edsm.net/api-v1/bodies?systemName=Colonia

 I guess it should be called ``api-system-v1`` instead of ``api-v1``.

**Comment by klightspeed** [comment]
Fixed in #1375
