### ISSUE TITLE
EDDiscovery error version 8.3.3.0 Help please

### ISSUE THREAD

**Issue by tomknight10** [EDDiscovery/EDDiscovery#1376]
Error Attach, help please
![error_edd](https://user-images.githubusercontent.com/25729521/31324323-e1df1610-ac87-11e7-9766-2e8a850b66e1.jpg)

**Comment by klightspeed** [comment]
That suggests the EDDSystem.sqlite database is corrupt.

Please try removing `%LOCALAPPDATA%\EDDiscovery\EDDSystem.sqlite` and restarting EDDiscovery.

**Comment by tomknight10** [comment]
its works, thank you very much!

**Comment by robbyxp1** [comment]
Fixed
