### ISSUE TITLE
ED Discovery Error re: shopping list?

### ISSUE THREAD

**Issue by VexMatraxis** [EDDiscovery/EDDiscovery#1377]
Hi. I frequently receive this error when any action is performed in game, generating the same error each time. I have no secondary panes/windows active. I have tried safe mode to reset window panes.
![ed discovery shopping error](https://user-images.githubusercontent.com/32651232/31354318-d14c486c-ad2d-11e7-97c3-884cd80c8f42.png)

**Comment by robbyxp1** [comment]
This is fixed on master. @finwen do you want to cherry pick the commit to the branch?

**Comment by robbyxp1** [comment]
Pr1372
