### ISSUE TITLE
Splitterdistance not between Panel1MinSize and Width - Panel2MinSize

### ISSUE THREAD

**Issue by mcange** [EDDiscovery/EDDiscovery#1378]
Hallo,

I couldn't find this exact issue posted before. I hope the screenshot helps because there is not much I could write except it started two days ago.

Have a nice day.

![eddiscovery splitterdistance_bug](https://user-images.githubusercontent.com/32673369/31385505-c679cab8-adc3-11e7-866f-74a090edf11b.PNG)

**Comment by klightspeed** [comment]
This is the same error as in #1301

This was supposed to have been fixed in 8.3.2 or 8.3.3

**Comment by phroggster** [comment]
@mcange Are you still seeing this issue in v8.3.3?

**Comment by mcange** [comment]
@phroggster Yep, using 8.3.3.0 and it's the first time that I had any kind of error message.

**Comment by robbyxp1** [comment]
This is going to be solved in 8.4 by using a different mech.

**Comment by robbyxp1** [comment]
8.4 hopefully fixes the splitter by saving the %, so if you re-open on another tab, then select to it, it should still work.
