### ISSUE TITLE
Possibility to translate into brazilian portuguese

### ISSUE THREAD

**Issue by rafaelpivatto** [EDDiscovery/EDDiscovery#1379]
Hello guys.
After the ED added oficial support to brazilian portuguese, our community are making many 3rd party translation projects.
How can i help to translate to portuguese? the software allows?
Regards. :smiley:

**Comment by andreaspada** [comment]
> ow can i help to translate to portuguese? the software allows?

@rafaelpivatto: Olá, Rafael. Caso seja possível, posso ajudar...

**Comment by rafaelpivatto** [comment]
Olá @andreaspada, toda ajuda será muito bem vinda, sou do grupo Cobra Wing, alguns dos nossos membros ajudaram a traduzir o Elite Dangerous e agora estamos tentando traduzir o máximo possível de programas 3rd party.
Já traduzimos o ED Engineer e estamos em progresso com o ED Market Connector também.
Assim que tiver resposta vamos nos falando, qualquer coisa nos encontre lá no grupo do discord :smiley: 

[]'s

**Comment by klightspeed** [comment]
EDDiscovery does not currently have any i18n string localization support built into it.

Does anybody know of any good cross-platform string localization package for dotnet?

**Comment by andreaspada** [comment]
http://xleon.net/localization/xamarin/pcl/share-locales/i18n/portable/dotnet/2017/02/09/easy-and-cross-platform-localization-for-xamarin-and-dotnet/

**Comment by rafaelpivatto** [comment]
Hello @klightspeed
I don't have advanced knowledge into .Net, currently work in Java and Node.js, but, I'll help whatever it takes.

**Comment by andreaspada** [comment]
At first, we need to translate each existing strings in a format suitable to be translated by an I18N method.

**Comment by robbyxp1** [comment]
You can translate the language string into another language.. I made it so the strings were set up in one place, and could be replaced.

The only problem is that items from elite itself, some of them are localised, some are not. There are a set of tx strings which could be added to to translate those items by replacements. Such as star types etc

**Comment by robbyxp1** [comment]
Closing as not a EDD issue. If you ever do it, use our discord and we can incorporate.
