### ISSUE TITLE
Feature Request: 'Personal' Wanted Systems

### ISSUE THREAD

**Issue by RedfoxCh** [EDDiscovery/EDDiscovery#138]
After seeing how great the 'EDSM Wanted Systems' feature turned out I'd like to suggest a similar feature for a list of 'Personal Wanted Systems', e.g. for reverse trilaterating systems you forgot to do when you were there. Some thoughts:
* Usage is the same as the 'EDSM Wanted Systems', i.e. have another list and click an element to have it added to the and triateration list
* Have the option to add a system to the list either from the travel log or manual entry
* Option to remove systems from the list, or maybe have systems drop out of the list automatically when they get their coordinates (like with the EDSM Wanted Systems)
* This list might be the way to (at a later point) request systems to be pushed to the 'EDSM Wanted List' (after reaching a minimum of maybe 10 distances entred)

Your thoughts?

**Comment by finwen** [comment]
Good idea. should not be to hard to add.

**Comment by finwen** [comment]
Ian Ross made most of this in 3.0.4 (unreleased)

Camulorix  found some smaller issues: 
I can't add systems to my wanted list once i deleted them
example: HL Lupis added to wanted list, removed it from wanted list, can't add again

**Comment by iainross** [comment]
Not sure if I tried re-adding a system I'd deleted...  I'll give it a go this evening and hopefully fix.

**Comment by iainross** [comment]
@RedfoxCh it's not exactly as you've described - they're in the same list (there's a 'Source' column of 'EDSM' or 'Local'), you can only add from the trilateration grid (you're going to put it in there initially anyway...) and I've not implemented an auto-deletion on finding a position, that's manual.

The important thing is that you can save your wanted systems between EDD sessions though.

**Comment by RedfoxCh** [comment]
@iainross Wow, that sounds great, thanks for taking this up. I'm usually not the one going for the pre-release builds, but I'll definitely give this one a try in order to provide feedback. The way you describe it, all core aspects of this enhancement are in place.
*runs off to the releases-page*

**Comment by RedfoxCh** [comment]
Oh, well, @finwen *did* say "unreleased"... I will wait (im)patiently ;-)

**Comment by iainross** [comment]
3.0.4 pre-release is there now...

**Comment by finwen** [comment]
Yes get 3.0.4 here

https://github.com/EDDiscovery/EDDiscovery/releases

2016-04-05 13:17 GMT+02:00 iainross <notifications@github.com>:

**Comment by RedfoxCh** [comment]
I guess this one can firmly be closed, due to the great work from @iainross - thanks! Should the OP close tickets or the dev/admin?

For the improvements/enhancements that are lurking in the back of my mind I'll create a new ticket ;-)
