### ISSUE TITLE
Voiceover problem with neutron stars

### ISSUE THREAD

**Issue by skwerlman** [EDDiscovery/EDDiscovery#1391]
Just now I was at NLTT 44164, and when I supercharged my FSD, EDD played the audio:
```
Frame shift drive charged by January 5th times.
```

The actual audio should have been:
```
Frame shift drive charged by one point five times.
```

Journal entry:
```
{
  "timestamp": "2017-10-11T23:40:37Z",
  "event": "JetConeBoost",
  "BoostValue": 1.5
}
```

**Comment by klightspeed** [comment]
My guess is that the decimal separator in the string being spoken was a period (.), while your locale uses a comma as your decimal separator and a period as your date separator.

Fixing this would require getting the text to speech to support SSML or SABLE.

**Comment by skwerlman** [comment]
My locale (en-US) uses a `.` as a decimal separator.

**Comment by robbyxp1** [comment]
SSML is supported in the current version, see the phoneme replacement system in VP5.

But i'll have a quick look into it.. may be simpler than that.

**Comment by robbyxp1** [comment]
Well, the round.. functions produce always the X.Y format (Invariant culture) 

Strange that this is happening - what speech engine are you using? Is it a microsoft one?

I give the speech engine the speech culture en-gb which for some engines configures it to know X.Y is a number.

**Comment by skwerlman** [comment]
Ye, i'm using whatever the default is. i'll try telling the engine to use en-gb and see if it helps. is there a way to make EDD repeat a voice line so i don't have to go all the way to a neutron star to test?

**Comment by robbyxp1** [comment]
here

https://drive.google.com/file/d/0ByfWjlfIi7UuZWhsUTRvT3BTU0U/view?usp=sharing

is a file. Install it in the c:\users\<your name>\appdata\local\eddiscovery\actions folder

It adds ctrl+F12 to run the program inside of it, which says "Hello there 1.25 2.5"

So on mine, it says 1 point 2 5, 2 point 5.  What does it say on yours?

You can simply text edit it with notepad etc to change what its says.  It uses the default voice set up in the voice configuration dialog.

**Comment by robbyxp1** [comment]
Oh and it can be straight ASCII file, it does not need the BOM marker on it.

**Comment by skwerlman** [comment]
Here's what i hear, along with the incorrect audio from the actual charge event: https://www.youtube.com/watch?v=b6EGVgAlQBo

**Comment by robbyxp1** [comment]
Yep, the joys of the Windows voice engine, i'll give it a play.

**Comment by robbyxp1** [comment]
I've tried again to make it say it as a date.. failed.. 

try

Say "Super charged by <say-as interpret-as='ordinal'>10.29</say-as>"

does that make a different using the SSML markup?

**Comment by skwerlman** [comment]
I was able to get it to read correctly by adding SSML markup around the number: https://youtu.be/uaqfmBFdWEQ

**Comment by robbyxp1** [comment]
Okay.. hmmm. there are lots of places where numbers are written.  I'll annotate that one for now in the next VP

Thanks for your assistance.

**Comment by robbyxp1** [comment]
VP6 marks this as a cardinal
