### ISSUE TITLE
No sync

### ISSUE THREAD

**Issue by FilmExile** [EDDiscovery/EDDiscovery#1393]
Hi there,

Love using EDDI, have done for most of the last year, set up and worked wonderfully. Until the recent update. I have the most up to date version 8.3.3.0, but the API is not syncing with EDSN.

I have rebooted, changed my API key, but its just not syncing.

Funny thing is that it syncs with EGO just fine. It syncs with EDSM Stars no problem...

I do a lot of exploration and having it live sync with EDSM so very handy for navigation.

Can you suggest any possible fixes to get me back on the road.

Thanks

**Comment by iainross** [comment]
Body details don't go direct to EDSM but rather via EDDN.  Have you got EDDN syncing enabled?

**Comment by FilmExile** [comment]
I do now and the log file indicates that its syncing... but... It isn't bring my history down from EDSM, and I can see no update on EDSM.

I have checked the box for send event information to EDDN.

**Comment by AnthorNet** [comment]
What part exactly isn't syncing?

**Comment by FilmExile** [comment]
That's the bit I don't understand, log file says its updated... but update does not appear on EDSM...

Here is a cut and paste from my log file...

Indexing systems table
Checking for new EDSM systems (may take a few moments).
Downloading systems from 12/10/2017 10:05:40 to 12/10/2017 11:05:59
System download complete
EDSM updated 607 systems.
Loading completed, total of 13,989,794 systems
Refresh due to updating systems
Refresh Complete.
Refreshing complete.
Indexing systems table
Checking for new EDSM systems (may take a few moments).
Downloading systems from 12/10/2017 11:05:36 to 12/10/2017 12:10:55
System download complete
EDSM updated 1,146 systems.
Loading completed, total of 13,990,939 systems
Refresh due to updating systems
Refresh Complete.
Refreshing complete.
EDSM sync begin
EDSM: Sending 476 flightlog entries
Refresh Complete.

**Comment by AnthorNet** [comment]
What is CMDR name over EDSM?

**Comment by FilmExile** [comment]
CMDR name is: McNicholl
I use FilmExile as a user name.

**Comment by FilmExile** [comment]
Ian I think I have a confession to make, I think I put the wrong user name in when I updated the software. So this is all my fault and nothing wrong with your work. Looks like everything is syncing now. Sorry for the panic.

Cheers

Angus

**Comment by AnthorNet** [comment]
Good to know then :)

**Comment by iainross** [comment]
These things happen, no real harm done.
