### ISSUE TITLE
Unrecognized rare goods

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDDiscovery/EDDiscovery#1394]
Noticed that some rare goods do not seem to be recognized correctly:

![image](https://user-images.githubusercontent.com/25147462/31522435-0cc0ff32-afae-11e7-8fd2-610b2cedd633.png)

Seems the entries in the commodity list need fixing, or additional aliases.

**Comment by phroggster** [comment]
Some journal files with this information would help validate these choices, but here's what I propose based on your screenshot:

| Current Short Name | Current Description | Proposed Short Name | Proposed Description |
|--------------------------|----------------------------|---------------------|----------------------------|
| azuremilk | Azure Milk | bluemilk | Azure Milk |
| eraninpearlwhiskey | Eranin Pearl Whiskey | eraninpearlwhisky | Eranin Pearl Whisky |
| xihebiomorphiccompanions | Xihe Biomorphic Companions | xihecompanions | Xihe Biomorphic Companions |

**Comment by phroggster** [comment]
From Discord:
>```JSON
>{ "timestamp":"2017-10-03T08:26:00Z", "event":"MarketBuy", "Type":"eraninpearlwhisky", "Count":8, "BuyPrice":1620, "TotalCost":12960 }
>{ "timestamp":"2017-10-03T08:28:04Z", "event":"Cargo", "Inventory":[ { "Name":"bastsnakegin", "Count":15 }, { "Name":"leestianeviljuice", "Count":3 }, { "Name":"eraninpearlwhisky", "Count":8 }, { "Name":"lavianbrandy", "Count":6 }, { "Name":"konggaale", "Count":18 } ] }
>{ "timestamp":"2017-10-02T16:56:42Z", "event":"Cargo", "Inventory":[ { "Name":"bastsnakegin", "Count":15 }, { "Name":"leestianeviljuice", "Count":6 }, { "Name":"eraninpearlwhisky", "Count":8 }, { "Name":"lavianbrandy", "Count":6 }, { "Name":"bluemilk", "Count":6 }, { "Name":"konggaale", "Count":18 }, { "Name":"indibourbon", "Count":4 } ] }
>{ "timestamp":"2017-03-01T00:00:08Z", "event":"MarketBuy", "Type":"xihecompanions", "Count":18, "BuyPrice":2241, "TotalCost":40338 }
```

**Comment by phroggster** [comment]
I think that I've got it such that the old identifiers will be translated over to the new ones. #1407 / #1408 should correct this.

**Comment by phroggster** [comment]
PR's merged in 38309c740fab7a608302b65ea85c1c70056b8ec2 (and ced6dc3379afa3212eba40c9f7dd95c44cf4e2a3 on master). Expect this to be resolved in v8.3.4.
