### ISSUE TITLE
Error message "Exception..."?

### ISSUE THREAD

**Issue by ALTARF94** [EDDiscovery/EDDiscovery#1395]
Program asked me to attach this:
[Trace_20171013115820.0.log](https://github.com/EDDiscovery/EDDiscovery/files/1382107/Trace_20171013115820.0.log)

**Comment by klightspeed** [comment]
You might want to delete `EDDSystem.sqlite` from `%LOCALAPPDATA%\EDDiscovery`, and try again.

**Comment by ALTARF94** [comment]
What will that do?

**Comment by klightspeed** [comment]
`EDDSystem.sqlite` stores the systems downloaded from EDSM and EDDB.

From the trace log, it looks like it's damaged such that some operations that should be quick take a long time, resulting in those "database is locked" errors.

EDDiscovery will rebuild that database after you delete EDDSystem.sqlite and restart EDDiscovery.

**Comment by ALTARF94** [comment]
Ok, thanks. Will do that.
