### ISSUE TITLE
Feature Request: Allow the selection of which System fields are displayed in the Travel History list

### ISSUE THREAD

**Issue by Red13x3** [EDDiscovery/EDDiscovery#14]
Synopsis:  Different users want to see different views of the same data. Allow a user to select (in the Settings tab?) which fields are visible in the Travel History list and preferably in which order they want to.

Reasoning:  Personally, I don't care the exact date/time I visited a system. But knowing what Allegiance it is aligned to, is. And if extra fields are added (like the Data $ field) I would like to see that listed, too.

Allow the user to configure the Travel History list, adding or removing the fields displayed, and ideally enable them to order the fields in any order they wish.

A good way to do this, and one users are already familiar with is done in Windows Explorer, right-clicking on a column title and then clicking checkboxes on and off. Re-ordering is done by dragging columns left/right.  Another suggestion would be to have in the Settings tab, a list of all the fields, and a column indicating the order of the fields. A blank entry means the field is not to be displayed in the list.

**Comment by finwen** [comment]
Good idea, Have done something similar at work. Should not be to hard to do.

**Comment by Red13x3** [comment]
Bump...

Also, is there any particular reason we can't make the Time and System columns thinner than what seems to be enforced? I really don't need to see, for example, more than the date I was there. So I'd like to me the column thinner to hide the time stamp part, but I can't. :(

And for the Note column, when I have a multi-line note, I'd prefer it not actually show lines after the first... Or if we have to, can we at least put a space between the line ending and the start of the next line?

Oh, and what's the purpose of the "Map Color" column? I can't seem to make it do anything on the 3D Map, if that's what it is for, when I change the colour or even type some letter into it..

**Comment by iainross** [comment]
@Red13x3 Map colour should set the colour on the 3D and 2D maps, if you're not drawing lines it should be the colour for the point, if you're drawing lines then when the Map Colour changes the line colour should change from the system where the colour changes until the next new colour.

Not sure why it's not working for you - if you can put your database somewhere I can get at it I'll be happy to have a look.

**Comment by robbyxp1** [comment]
Closed - DGV grid remembers pos and can be smaller
