### ISSUE TITLE
Unhandled exception parsing Unexpected character

### ISSUE THREAD

**Issue by ChianasGeek** [EDDiscovery/EDDiscovery#1412]
Hi,
Latest stable EDD 8.3.3 gives this, this morning (was running fine last night):

[Trace_20171020081724.0.log](https://github.com/EDDiscovery/EDDiscovery/files/1401076/Trace_20171020081724.0.log)

Repeatable, as that was the second run attempt. The following is the first (in case of diff):

[Trace_20171020081555.0.log](https://github.com/EDDiscovery/EDDiscovery/files/1401080/Trace_20171020081555.0.log)

I await input :)

P.S. I will now close ED and re-launch on other Commander (run as diff Windows user, EDD likewise) to see if it happens there, too.

**Comment by AnthorNet** [comment]
EDSM was on maintenance.
Maintenance is over, you just have to wait for the DNS propagation.

**Comment by ChianasGeek** [comment]
Ah, first time I'd ever seen it!
Cheers Anthor B-)

/me goes to make coffee(2);
