### ISSUE TITLE
Editing planet scanning in voicepack

### ISSUE THREAD

**Issue by fintarn** [EDDiscovery/EDDiscovery#1415]
Hey, I have a problem with editing what the voicepack says for planet scanning. I've been trying to both to make changes in these lines, and removing some of them. I want to make it so that some things are not said as it takes too long and isn't really interesting to me.  

> Static say_ScanPlanet $= Scanned %star(EventClass_BodyName,say_ss), %sc(EventClass_TerraformState) %rs(EventClass_PlanetClass,say_ss)
> Static say_ScanPlanetDistance $= , Arrival Delta %round(EventClass_DistanceFromArrivalLS,1,#.0) light seconds
> Static say_ScanPlanetLandable $= , Landable
> Static say_ScanPlanetAtmosphere $= , %sc(EventClass_Atmosphere) atmosphere
> Static say_ScanPlanetNoAtmosphere $= , No Atmosphere
> Static say_ScanPlanetVolcanism $= , %(EventClass_Volcanism)
> Static say_ScanPlanetTidallyLocked $= , Tidally locked
> Static say_ScanPlanetRotation $= , Rotation Period %round(rotation,1,0.#) days
> Static say_ScanPlanetOrbitalPeriod $= , Orbital Period %round(period,1,0.#) days
> Static say_ScanPlanetMass $= , Mass %round(EventClass_nMassEM,3,0.###) earth masses
> Static say_ScanPlanetMoonMass $= , Mass %roundnz(moonmass,2,0.##,4) moon masses
> Static say_ScanPlanetGravity $= , Gravity %roundnz(gravity,1,0.#,4) gee
> Static say_ScanPlanetTemperature $= , Temperature %round(EventClass_nSurfaceTemperature,0,0.#) kelvin
> Static say_ScanPlanetPressure $= , Pressure %roundnz(EventClass_nSurfacePressure,1,0.#,4) Pascal
> Static say_ScanPlanetNoSurfacePressure $= , No surface pressure
> Static say_ScanPlanetMaterials $= ", Materials detected %ExpandVars(EventClass_Materials_,\", \",0,1000,\"nameonly splitcaps\")"
> 

The things i want to remove is: 
- Scan planet distance
- Atmosphere
- Volcanism
- Tidally locked
- Rotation
- Orbital Period
- Temperature
- Pressure
- No surface pressure

So the things I want to keep is essentially: 

- Body name
- Terraforming
- Body class
- Landable
- Mass
- Moon mass
- Gravity
- Materials

The problem is that if I try to remove any of these lines, that I am interested in removing completely, the voice pack will not say anything at all. If I try to change them so that after the = symbol, they are empty I get some error. I don't really know how to solve this and need some help. While I'm at it I wanna request a feature in the "Voice Pack Configuration menu" that can modify these things with checkboxes. I'm sure I'm not the only one that would benefit from such a feature.

Thanks in advance

**Comment by klightspeed** [comment]
Perhaps instead of removing the line, try entering `""` for the value?

To remove the need for those variables, you would need to edit the `Scan` action program.

**Comment by robbyxp1** [comment]
Just set the strings to "" as suggested. that will silence that part of the output.

There is already an expanddefault macro, but its just simpler to set it to empty. At least then you've seen that you've turned that bit off.

The voice configuration dialog also have options to tailor the scan output.

Anything else requires rewiring the scan program, but thats not an easy task! there are lots of variations you have to take care of
