### ISSUE TITLE
Unknown event report, as requested

### ISSUE THREAD

**Issue by ACEinONYX** [EDDiscovery/EDDiscovery#1423]
I've just upgraded to 8.3.3.0, following a (belated) upgrade to 64-bit E:D (no Horizons yet).

Quick Q first:
I noticed that I didn't need to specifically point EDD to the Logs / Journal file locations, manually, (figuring clever automatic "discovery" procedures) but since the old 32-bit (FORC-FDEV-.. etc) folder still exists alongside the 64bit folder, how can I be **sure** EDD will use the "right" folder / file source?
((Ok, it DID pick up the Journal info from my "test run" (undock, re-dock), so.. "duh", but still...))

OK, "Unknown" event report:

In my EDD Journal, "Description" = "Unknown", and "Information" as follows (TWO entries):

Report to EDDiscovery team an unknown event{  "timestamp": "2017-10-28T05:48:33Z",  "event": "",  "Ship": "viper",  "ShipID": 1,  "": "AA8798"}
--

Report to EDDiscovery team an unknown event{  "timestamp": "2017-10-28T06:05:36Z",  "event": "",  "Ship": "viper",  "ShipID": 1,  "": "AA879X"}
--

Specifically, I went into the LIVERY interface, and -- I have the "Ship ID" (6-character, not "Name") plate -- edited what used to be there, first to "AA8798", then later to "AA879X", using the whole 6char space.

So, that's all this "Unknown" event is -- Livery, Ship ID edit / rename.

It may be useful to get OTHERS' FEEDBACK on "Unknown Events" recorded when anyone actually re-NAMES their ship.  I did rename my ship, though when next I go into the game, I may try it myself, and watch EDD for its log/journal response, and let you know.. if nobody else gets here first.  ;)

I did not find a "reported issue" for this (Unknown event / Livery rename), from a perfunctory (ie impatient, non-exhaustive, aka "lazy") search, and _I've just registered here (GitHub) to contribute this feedback to the EDD Team_, so my apologies if I've missed an existing "Open Issue" for this topic.

Still, hope this info is useful.. even if obviously not "critically urgent".  ;)

Cheers,
.A. ONYX o7

**Comment by klightspeed** [comment]
The `event` is set to nothing where it should be `SetUserShipName`, and it looks like both the `UserShipName` and `UserShipId` fields have no name (and so only the `UserShipId` field is picked up).

Would it please be possible to extract the associated events from the actual journal file (in `%USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous`)?

Elite Dangerous seems to write the `SetUserShipName` event correctly here:
```
{ "timestamp":"2017-10-28T17:50:29Z", "event":"SetUserShipName", "Ship":"sidewinder", "ShipID":13, "UserShipName":"Sidewinder", "UserShipId":"XYABCD" }
```

**Comment by ACEinONYX** [comment]
Hi @knightspeed,

As requested, the 2 lines in my journal (plus the associated music track event, since I'd just re-docked) where I'd changed the ShipID twice.  ((The 17min inbetween was blown checking out the different presentations (Black, White, Grey, underlined, over-&-underlined) against the ship's yellow-orange)):

{ "timestamp":"2017-10-28T05:37:40Z", "event":"Music", "MusicTrack":"Starport" }
{ "timestamp":"2017-10-28T05:48:33Z", "event":"", "Ship":"viper", "ShipID":1, "":"CheetahFace", "":"AA8798" }
{ "timestamp":"2017-10-28T06:05:36Z", "event":"", "Ship":"viper", "ShipID":1, "":"CheetahFace", "":"AA879X" }

So, yes, I think I see what you mean; the "SetUserShipName", "UserShipName" and "UserShipId" variable tags are missing in the Journal log, as evinced by the "empty" quote-pairs:
- after "event":
- before :"CheetahFace" - the ship name
(see also: https://www.frontierstore.net/game-extras/elite-dangerous-game-extras/viper-orange-copperhead.html -- or am I the only one who sees it? O_o )
- and before :"AA879*" - the 2 versions of Ship ID I was messing with...

For sake of "completeness", I did a file search for ALL instances of " :"" " and " "": " (ie empty variables) and it seems they were ONLY empty like this for the two times I changed the ShipID.

Also, re "Game Extras" (FrontierStore.net), I ONLY bought the ShipID extra, and NOT YET bought any of the ShipName plates.  And I've yet to buy Horizons...  >_<
Whether or not either is a factor contributing toward the occurrence exhibited here.....  (?)

=-=-=-=-=

OK, re log source, since that (Saved Games) is set by E:D and not(?) typically user-configurable / -modifiable, EDDiscovery intrinsically "knows" where to look, and I no longer need to advise (newer versions of) EDD the location of Journal files like we did with log files for older EDD versions..?
Do i understand correctly?  Thanks -- new to this.  :)

Given that, is it ALSO correct that we STILL need to set "VerboseLogging" with EACH Update?
Thank you!

**Comment by klightspeed** [comment]
`VerboseLogging` has not been required since Elite Dangerous 2.1, when coordinates were added to the netlog, and has definitely not been required since Elite Dangerous started writing journals.

The `Saved Games` directory is set by Windows, and can be changed in File Explorer by using the Location tab in the directory's Properties.

**Comment by robbyxp1** [comment]
I've raised a ticket with Frontier on this.  Closing as we can't do anything in EDD about it, beyond not crashing.
