### ISSUE TITLE
Enhancement request-shell coordinates

### ISSUE THREAD

**Issue by MikeDavison2** [EDDiscovery/EDDiscovery#1427]
Could I raise a request for an upgrade?
In the exploration window it is currently possible to import a sphere of systems around a central system, but at times it would be really useful to be able to import a spherical shell with max & min radii around a central system. And similarly for a cube/cubical shell...I think there are EDSM API calls for these, just needs to be programmed into EDD.

**Comment by robbyxp1** [comment]
Or we can do that via the systems db

**Comment by MikeDavison2** [comment]
Whatever is most convenient!
I'm no programmer, just a grateful user of EDD...

**Comment by andreaspada** [comment]
@MikeDavison2, that's something I thought by a while. I'm thinking that it would be awesome too to have some access - via a console apps? - to the systems db, and do some query to. Star shells, cube/cubical, sphere (we have this already)... 

Ideally, I would love to be able to replace the functionalities of EDTS (https://bitbucket.org/Esvandiary/edts) in EDDiscovery, through an optional - 3rd party? - console app. Or, better yet, through an in-app command line console, manageable as popup or grid element. Who knows...

**Comment by MikeDavison2** [comment]
This spherical (and cubical) shell requirement is cropping up fairly often as we try to explore different puzzles within ED, but most users (including me!) are not programmers so a command line console would not be of much use. I think what is needed is a couple of extra buttons on the EDD Exploration window to supplement the current “Import Sphere” function.

Sent from Mail for Windows 10

**Comment by andreaspada** [comment]
@MikeDavison2 absolutely yes. I was thinking at the command line as a power tool, for quick "in flight" query (as a command line popup, bind to a key...). But it's a project for late...
I support a shell and cube query as extra buttons, of course!

**Comment by robbyxp1** [comment]
System Database is available for use if you know how to write SQL queries in your chosen language/ tool.

**Comment by andreaspada** [comment]
@MikeDavison2, I'm working on a little panel to try to address your request. By now, I'm struggle to have it works, as I need to create two more routines, but the main idea is to have a tabbed popup, similar to the Nearest Stars panel, which let you choose a radius and a max number of stars in the first panel, and the inner and outer radius for a shell. I already have a mockup, I'm working now on the filters code...
![trekker-shell](https://user-images.githubusercontent.com/4296635/34071383-ab2baccc-e25c-11e7-993f-11986a91dd2b.PNG)
![trekker-sphere](https://user-images.githubusercontent.com/4296635/34071384-ab4e14c4-e25c-11e7-9729-44d3ddd22087.PNG)

The second feature is something I always wanted too: we can set the range for accommodate our jump range, for example, so we can easily see how many already explored systems are "at range for the next jump". Something crucial when you want to finish to chart some already explored area, trying to getting rid to jump in an already mapped system...

When ready, and in use, we can add cube and cubical shell, too. Nothing too difficult. And, if other filters are needed, the tabbed approach let us implement as many as needed without significantly alter the panel layout.

@robbyxp1, have you some time to help me figuring out how to modify the CalculateSqDistances routine? 
I altered it to that:

```
public void CalculateSqDistancesInRadius(SortedList<double, ISystem> distlist, double x, double y, double z, double radius, bool removezerodiststar)
        {
            double dist;
            double dx, dy, dz;
            var list = distlist.Values.ToList();
            HashSet<long> listids = new HashSet<long>();
            HashSet<string> listnames = new HashSet<string>(StringComparer.InvariantCultureIgnoreCase);
            foreach (ISystem sys in list)
            {
                listids.Add(sys.id);
                listnames.Add(sys.name);
            }

            foreach (HistoryEntry pos in historylist)
            {
                if (pos.System.HasCoordinate && !listids.Contains(pos.System.id) && !listnames.Contains(pos.System.name))                
                {
                    dx = (pos.System.x - x);
                    dy = (pos.System.y - y);
                    dz = (pos.System.z - z);
                    dist = dx * dx + dy * dy + dz * dz;

                    list.Add(pos.System);

                    if (dist >= 0.1 || !removezerodiststar)
                    {
                        if (dist <= radius)          // if less or equal than radius, add..
                            distlist.Add(dist, pos.System);
                    }
                }
            }
        }
```
I'm calling it in the pane code as it:
```
private void NewStarSphereComputed(ISystem sys, SortedList<double, ISystem> sphere)      // In UI
        {
            // get the radius of the sphere
            double radius = int.Parse(txtRadius.Text);
                        
            System.Diagnostics.Debug.Assert(Application.MessageLoop);       // check!

            discoveryform.history.CalculateSqDistancesInRadius(sphere, sys.x, sys.y, sys.z, radius, true);   // add on any history list systems
            
            FillSphere(sys.name, sphere);
        }
```
It compile successfully, but it do not work as expected. I am missing something obvious?

**Comment by andreaspada** [comment]
@MikeDavison2, I just prepared a PR (#1569) which add a small panel which display systems inside a minimum and maximum range. It's just a beginning of a more comprehensive addon, but by now, you can display shells and sphere from the current or selected system.

**Comment by robbyxp1** [comment]
Done in 9.2. Exploration has a much better import system
