### ISSUE TITLE
Screenshot-Configure-Crop Settings not saved.

### ISSUE THREAD

**Issue by thestyx** [EDDiscovery/EDDiscovery#1430]
The Crop Settings are not saved. i.e. I use 3 monitors and I want to crop just the middle one. For that I set Top: 0, Left: 1920, Width: 1920 and Height: 1080. When I now make a screen shot everything works. When I exit and start the program the Crop settings are back to Top: 1920, Left: 0, Width: 1920 and Height: 1080.  Edit: I forgot the version. The version is 8.3.3.0 on Windows 7

Fly/land safe.
CMDR Steyla

**Comment by robbyxp1** [comment]
Acknowledged, will be fixed in 8.4.2

**Comment by robbyxp1** [comment]
Top and Left gets swapped.

**Comment by phroggster** [comment]
Fixed in [v8.4.2](https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_8.4.2) via 8913882b92f8189709ac2d6771bcaffeb0f60643.
