### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Anthreal** [EDDiscovery/EDDiscovery#1432]
Every time I open it it crashes

**Comment by phroggster** [comment]
Care to provide some information about why or how it is crashing? The "Report Issue" button in the crash dialog, assuming that you're seeing it, will copy these details to your clipboard. Just paste them in to a comment here.

**Comment by Anthreal** [comment]
It just crashes every time at this point
![bandicam 2017-11-03 17-29-02-980](https://user-images.githubusercontent.com/33350915/32387475-7ecc33d4-c0bc-11e7-88a5-dfd02756faac.jpg)

**Comment by phroggster** [comment]
It crashes, and does not display the error window detailing why it crashed? Have you ever been able to open the program before?

"Scanning memory banks" means that it is trying to initialize the databases. Something is wrong either with the databases, or the database engine is missing files or something else.

The trace log should fortunately contain diagnostic information. Please check "%LOCALAPPDATA%\EDDiscovery\Log" and attach the most recent file in that folder. If using the portable version, the log folder should be next to the EDDiscovery.exe file.

**Comment by Anthreal** [comment]
Heres the most recent log, and yes I have been able to open the program before but its always slow on opening
[Trace_20171103172853.0.log](https://github.com/EDDiscovery/EDDiscovery/files/1442010/Trace_20171103172853.0.log)

**Comment by phroggster** [comment]
There's not much in that log file to go on. Do you have any log files that are larger than ~1Kb? If so, could you attach the most recent one?

The lack of error dialog, and the faded dialog screenshot, implies that it might not actually be crashing, and that it's just *really* locked up trying to initialize/upgrade the databases. If you launch Task Manager (<kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>ESC</kbd>), does it show EDDiscovery.exe using more than ~10% of your CPU? Do you get any kind of error dialog, even something that looks similar to the following?
![](http://i.stack.imgur.com/upylr.png)

You can safely delete the "%LOCALAPPDATA%\EDDiscovery\EDDSystem.sqlite" file, and it will be recreated at next startup. However, the "EDDUser.sqlite" file contains all of your settings and may be the one that we're getting stuck on. Go ahead and try deleting that "EDDSystem.sqlite" and restarting EDDiscovery. See if it's any better behaved.

**Comment by Anthreal** [comment]
Yeah after it fades it comes up as not responding and it says wait or shut down the program. And the eddiscovery.exe comes up as less than ~10% but it goes up and down constantly, but it never goes up past 10%
![bandicam 2017-11-03 18-26-39-282](https://user-images.githubusercontent.com/33350915/32389969-762cb9f8-c0c4-11e7-9ea4-b24aff88b49f.jpg)

**Comment by phroggster** [comment]
May or may not be something, but do you have any backup programs that run continuously in the background that may be locking these files? There was an user not too long ago that had "Backup and Sync from Google" interfering with application startup. If you have anything like that running, try exiting it before proceeding.

Then... Go ahead and close EDD down, delete "%LOCALAPPDATA%\EDDiscovery\EDDSystem.sqlite", re-launch EDD and cross your fingers.

**Comment by Anthreal** [comment]
There doesnt seem to be a file called 'EDDSystem.sqlite'

**Comment by phroggster** [comment]
Then the next thing to do is rename "EDDUser.sqlite" to something else ("UserBackup.sqlite"). You're going to lose all of your settings and parsed journals, which is why we're not outright deleting the file, but the journals should be recoverable assuming that the original logs haven't been deleted from your Saved Games folder.

Hopefully once this file has been removed, EDD will start up within 20 seconds or so.

**Comment by Anthreal** [comment]
I managed to get it working but after it loaded nothing happened for a bit and then the log came up and it was completely blank so I closed it again and its taking ages to close now

**Comment by Anthreal** [comment]
Is there any reason as to why everything is blank? Ive used the app before but theres no data?

**Comment by klightspeed** [comment]
Do you have any performance problems with other stuff on the drive on which the EDDiscovery data is stored?  Do you still have the journal files from Elite Dangerous?

**Comment by Anthreal** [comment]
Ah nevermind i didnt see this . I assume after this is completed it wnt be blank anymore
![bandicam 2017-11-03 19-38-09-528](https://user-images.githubusercontent.com/33350915/32392674-7285fe7c-c0ce-11e7-93c5-1efc435e0b8a.jpg)

**Comment by klightspeed** [comment]
Yes, once all of the journals have been processed, it should show the journal history.

**Comment by Anthreal** [comment]
Thanks for the help!

**Comment by phroggster** [comment]
It sounds like you're up a running again. Feel free to reopen this issue if you have problems in the future.

Meanwhile, I've created a task to improve the startup behaviour to aid in debugging efforts, should a similar issue come up in the future.
