### ISSUE TITLE
Add Initialization Enhancements

### ISSUE THREAD

**Issue by phroggster** [EDDiscovery/EDDiscovery#1433]
* Perform database Initializations in a background thread to keep the splash form message pump unblocked.
  * Could run them in parallel if we really want to live dangerously, and we're not disk-I/O-limited, but that voids the next idea:
* Add splash form messages to differentiate between user DB init and systems DB init.
* Switch the database init exception handlers to use the exception form (or remove them entirely) to fall through to the generic loading hard-stop in MainEnginesStart.

**Comment by robbyxp1** [comment]
no action.  It boots up quickly anyway now.
