### ISSUE TITLE
Avast reports Win32:Evo-gen [susp] and deletes 8.4.1 installer .exe

### ISSUE THREAD

**Issue by fnordson** [EDDiscovery/EDDiscovery#1434]
As the title says. 
Just downloaded it. Avast deletes it right away.

**Comment by klightspeed** [comment]
Avast seems over-eager to categorize non-whitelisted programs less than 1MB compiled by Visual Studio as Win32:Evo-gen.

https://answers.microsoft.com/en-us/protect/forum/all/win32evo-gen/c6f488dc-4a11-43fa-b002-576aec09e761#LastReply

**Comment by fnordson** [comment]
Thanks. 
Someone should add this to the release description. 
It's not only Avast: https://www.virustotal.com/de/file/1d1f7df8b9f9d70a611bdf4b445d68d27c11df19d620c631126b0b94714f1fb4/analysis/

**Comment by robbyxp1** [comment]
Klightspeed has produced a clean 8.4.1. closing
