### ISSUE TITLE
UI + datagrid issues after selecting second account name on dropdown 8.4.1.0

### ISSUE THREAD

**Issue by hitchhiker54** [EDDiscovery/EDDiscovery#1436]
After a clean windows reinstall I logged into my second ED account for the first time and selected it's name from EDDiscovery dropbox as I had done previously to add EDSM api etc. I was greeted with errors.

Unhandled UI exception 
### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
>   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
>   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
>   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
>   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
>   at System.IO.Stream.Close()
>   at EliteDangerousCore.CompanionAPI.RijndaelCrypt.Decrypt(String encryptedValue)
>   at EliteDangerousCore.CompanionAPI.CompanionCredentials.get_IsComplete()
>   at EliteDangerousCore.CompanionAPI.CompanionCredentials.CredentialState(String cmdrname, Boolean& disabled)
>   at EDDiscovery.EDDiscoveryForm.Controller_RefreshComplete()
>   at EDDiscovery.EDDiscoveryController.RefreshHistoryWorkerCompleted(HistoryList hist)
>===== END =====
>```

Selecting Settings tab throws up a dialog reporting DataGridView error
https://imgur.com/pK9b4XX

The issue persists after restart. When restarting I see 2 of the above dialogs and 2 of the above exceptions before EDDiscovery has finished loading when settings tab is still active. After clearing these and switching back to History tab restart only now throws 1 Exception dialog.

I am able to carry on as usual with the main commander but setting up the second is not possible.

**Comment by klightspeed** [comment]
That suggests that the Companion API credentials file for that commander is corrupt.

**Comment by hitchhiker54** [comment]
The credentials file would be in c:\...\local\eddiscovery? Checking there, as it's a clean windows install and the second commader has never been set up, that seems unlikely. Indeed the second commander has no credentials file. I only got as far as selecting the name and choosing the settings tab. Unles you mean my main commanders file is corrupted?

**Comment by klightspeed** [comment]
Are there any `credentials*.json` files in `%LOCALAPPDATA%\EDDiscovery`?

The error would appear to be due to the `password` field in the json being corrupt.

Perhaps `rijndaelCrypt.Decrypt()` at https://github.com/EDDiscovery/EDDiscovery/blob/master/EliteDangerous/CompanionAPI/CompanionCredentials.cs#L41 should be in a try/catch which returns null if the password decryption fails.

**Comment by hitchhiker54** [comment]
Just the main commanders one, which has been working correctly. Testing by changing the extension of that file appears to clear the error.

**Comment by robbyxp1** [comment]
I suggest we patch to protect.

**Comment by robbyxp1** [comment]
PR #1588 1588
