### ISSUE TITLE
DirectSoundException when closing EDD

### ISSUE THREAD

**Issue by AtomicFury** [EDDiscovery/EDDiscovery#1437]
### Description
Just downloaded latest build and closed the application.

### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
>   at CSCore.DirectSound.DirectSoundBuffer.Stop()
>   at CSCore.SoundOut.DirectSoundOut.CleanupResources()
>   at CSCore.SoundOut.DirectSoundOut.Dispose(Boolean disposing)
>   at CSCore.SoundOut.DirectSoundOut.Dispose()
>   at AudioExtensions.AudioDriverCSCore.Dispose() in C:\Users\klightspeed\git\EDDiscovery\Audio\AudioDriverCSCore.cs:line 127
>   at EDDiscovery.EDDiscoveryForm.Controller_FinalClose() in C:\Users\klightspeed\git\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 941
>===== END =====
>```

**Comment by phroggster** [comment]
Looks like we need some
```CS
audioqueuespeech.StopAll();
audioqueuewave.StopAll();
```
Inside of `EDDiscoveryForm.Controller_FinalClose` before we dispose of them.

**Comment by phroggster** [comment]
And the HRESULT (0x88780096) translates to DSERR_BUFFERLOST. This means that something tried to lock a buffer or play sound from a buffer that is no longer allocated.

**Comment by robbyxp1** [comment]
will look

**Comment by robbyxp1** [comment]
I reworked this for 9.0, lets see if it occurs again

**Comment by phroggster** [comment]
@AtomicFury Please fill out the anonymous survey located at https://www.surveymonkey.com/r/2RJSWK7 to help us try and nail down a potential cause for this.
