### ISSUE TITLE
Landed stat appears to include 'ship recall'

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1438]
Not sure if it is by design, a bug, or an oversight, but it would seem that the "Landed" count in the statistics/travel panel includes the the ship recalls. 

If I look at the log entry (thanks to EDD's right click copy to journal - awesome BTW), I can see that the recall event calls out the "PlayerControlled" value as "False"
{
  "timestamp": "2017-11-03T21:25:05Z",
  "event": "Touchdown",
  "PlayerControlled": false
}

Therefore, it should be simple enough to only count event:"Touchdown" where PlayerControlled=True.  You could add another stat for the false condition to note how many times the ship is recalled.

In a related matter - When the touchdown occurs when the ship is recalled, the voicepack announces the arrival of the ship at long/lat 0/0.   Would it possible to create a separate entry for the  "PlayerControlled": false condition so it'll say something like 'Ship has arrived and is ready for boarding' or something?

**Comment by robbyxp1** [comment]
Fixed by Iain in 9.0
