### ISSUE TITLE
Themes: Trilateration colour indications no longer present

### ISSUE THREAD

**Issue by gregmalcolm** [EDDiscovery/EDDiscovery#144]
I just noticed while testing 3.0.0beta that we've lost the indication thing in the top right for telling the user how solid the trilatearation thing is. You know, that box that turns red, then yellow then green?

It's a little tricky knowing when to submit to EDSM without it.

/cc @robbyxp1

**Comment by gregmalcolm** [comment]
Also the color indications in the right hand colom of trilateration grid for "Ok" and "Failed" don't give you much color feedback any more either.

**Comment by finwen** [comment]
Yes we should work on improve that feedback.

2016-03-24 5:33 GMT+01:00 Greg Malcolm <notifications@github.com>:

**Comment by gregmalcolm** [comment]
Looks good in 3.0.2

**Comment by mwerle** [comment]
Actually not sure this should be resolved yet. 

Only success is highlighted. The other colour indicators are still missing. 
Also font is no longer larger than test of interface. 


While in general the teeming is awesome, as a very heavy trilaterator I really miss quite a lot of the visual feedback that was in the unthemed version. 

Perhaps some elements should, at least for now, remain unthemed? I appreciate the difficulty of adding another 50 (exagerated) theme options.
