### ISSUE TITLE
Choosing a network path for -Appdata and *dbpath config will result in EDDiscovery trying to open the database from a local path instead

### ISSUE THREAD

**Issue by WraithStar** [EDDiscovery/EDDiscovery#1445]
Apparently, if you specify a network path (e.g. ``\\10.0.0.201\foo\bar``) as an argument for ``Appdata`` or for any ``*dbpath`` option, this will result in the application trying to fetch the database from ``C:\10.0.0.201\foo\bar`` instead, resulting in an ``System.Data.SQLite.SQLiteException (0x80004005)``

**Comment by phroggster** [comment]
Try mapping the share to a drive letter in order to hide the remote nature of it from Sqlite.
