### ISSUE TITLE
Not all jumps/stars get transferred to EDSM

### ISSUE THREAD

**Issue by JerkerPihl** [EDDiscovery/EDDiscovery#1449]
I have star "Drojia NI-I c26-10" that won't appear on EDSM. I have not erased on it EDSM but it seems that it never get transferred from EDD. 
[Journal.171107201705.01.log](https://github.com/EDDiscovery/EDDiscovery/files/1452805/Journal.171107201705.01.log)

**Comment by JerkerPihl** [comment]
This is connected to #1448 since it wouldn't transfer stardata i did a rescan of journalfiles

**Comment by klightspeed** [comment]
What does EDSM say the system after `Drojia JC-K c25-8` is in your travel log?

Is it possible to get the trace log from when that journal would have been read?

**Comment by JerkerPihl** [comment]
It doesn't show up at all in EDSM. It show an extremely long jump to the next star

**Comment by klightspeed** [comment]
Is it possible to get the trace log from when that journal would have been read?

**Comment by JerkerPihl** [comment]
tracelog?

commander name: electro
email : jerker_pihl@hotmail.com

Journal above give you all the data for when visiting the star

**Comment by klightspeed** [comment]
```
{ "timestamp":"2017-11-07T19:18:59Z", "event":"FSDJump", "StarSystem":"Drojia NI-I c26-10", "StarPos":[1741.781,-68.688,3914.688], "SystemAllegiance":"", "SystemEconomy":"$economy_None;", "SystemEconomy_Localised":"None", "SystemGovernment":"$government_None;", "SystemGovernment_Localised":"None", "SystemSecurity":"$GAlAXY_MAP_INFO_state_anarchy;", "SystemSecurity_Localised":"Anarchy", "Population":0, "JumpDist":25.381, "FuelUsed":3.829672, "FuelLevel":27.100328 }
```

It looks like nothing in that journal was sent to EDDN or EDSM, as no events were picked up by ROSS for that system in the past week.

**Comment by AnthorNet** [comment]
Can you try importing it here: https://www.edsm.net/en/settings/logs/import

Just to check if something is wrong on EDSM side.

**Comment by klightspeed** [comment]
Trace logs should be in `%LOCALAPPDATA%/EDDiscovery/Log`

**Comment by JerkerPihl** [comment]
If I drop the journal on the import page om EDSM the star gets added as it should
[Trace_20171107221543.0.log](https://github.com/EDDiscovery/EDDiscovery/files/1453400/Trace_20171107221543.0.log)
[Trace_20171107202038.0.log](https://github.com/EDDiscovery/EDDiscovery/files/1453401/Trace_20171107202038.0.log)
[Trace_20171106203149.0.log](https://github.com/EDDiscovery/EDDiscovery/files/1453402/Trace_20171106203149.0.log)

**Comment by JerkerPihl** [comment]
Sorry about the large trace files but I tried to fix the problem by rereading logfiles (and that created duplicates) :(

**Comment by JerkerPihl** [comment]
Please note that the star has always been visible in the history of EDDisocvery

**Comment by klightspeed** [comment]
It looks like that log was written while EDDiscovery wasn't running.  You would need to click the EDSM Sync button.
![image](https://user-images.githubusercontent.com/147116/32545816-9fb882fe-c4c8-11e7-8b96-acd48172cbb6.png)

**Comment by JerkerPihl** [comment]
@klightspeed : Then why was the the two following stars synced? Since it was in a new journal file?

**Comment by klightspeed** [comment]
EDDiscovery was started at 19:20 UTC.  The jump in question occurred at 19:17 UTC, 3 minutes before EDDiscovery was started.  The following jumps were executed while EDDiscovery was running, and so sent to EDSM and EDDN in real time.

**Comment by JerkerPihl** [comment]
Aaaa.. so sync EDSM stars is not a two way sync?

**Comment by klightspeed** [comment]
The EDSM stars sync is different to the EDSM travel history sync.

The former retrieves systems and coordinates from EDSM, which are then used for auto-completion, resolving systems by name, and for the 3D map.

The latter sends and retrieves travel logs to / from EDSM.

For jumps that occur while EDDiscovery is running, the travel log entry is immediately sent to EDSM.

For jumps that are read at startup, a manual sync is required.

**Comment by JerkerPihl** [comment]
Thank you for clarifying that. 👍  Then this Issue can be closed
