### ISSUE TITLE
3.0.0beta - Close button doesn't respond to clicking

### ISSUE THREAD

**Issue by gregmalcolm** [EDDiscovery/EDDiscovery#145]
Clicking on the cross in the top right doesn't close the app anymore. Sometimes I get an error beep if I try to use the "Close Window" from the windows task bar too if I've run some transliterations first.

Also as a side point, but I've realized that there is no "Exit" option at the bottom of the first menu in the File menu. It's kind of a convention for windows apps that there be one.

**Comment by gregmalcolm** [comment]
I haven't logged at the code, but it crosses my mind it might be a side effect of it taking a long time to close out because of trying to save at the end. Or possibly because my visited list is rather big.

I will really have to fire up Visual Studio and see what's happening here at some point...

**Comment by finwen** [comment]
I think i solved it in 3.0.4   Fixed in #4618415a0efb98e22bbace2d7c23b466215e36f2
