### ISSUE TITLE
Asteroid belts being counted as planets when retrieved from EDSM

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1457]
It seems as though EDD is counting asteroid belts are planets, or at least that's how the voicepack is interpreting it.
eg, I arrived into a system that had the star and two asteroid belts stored on EDSM, so EDD displayed them and as I exited hyperspace, the voicepack announced that the system had one star and two planets.  The system actually has more bodies but of course they aren't scanned so no way for EDD/EDSM to know that, but I don't think the two belts are intended to be counted as planets.

system for example;
https://www.edsm.net/en/system/bodies/id/16902183/name/Spliehm+RQ-L+c21-0

**Comment by robbyxp1** [comment]
Thanks we will look into it.

**Comment by robbyxp1** [comment]
9,2 and VP7 will fix
