### ISSUE TITLE
8.4.1 installer - evaluation license

### ISSUE THREAD

**Issue by draeath** [EDDiscovery/EDDiscovery#1460]
The 8.4.1 installer is [warning that it was created with a trial license, for evaluation purposes only.](https://i.imgur.com/QBYC6u2.png)

This wasn't happening before, so either it's new to the build used for 8.4.1, or something in the build process has gone wonky.

**Comment by robbyxp1** [comment]
We know, we had problems with getting a clean (via virustotal.com) install so Bravada stepped in and produced one with a trial version. Will be fixed on next one. Thanks for reporting.

**Comment by dave-001** [comment]
I'm also seeing the same warning as @draeath has reported above

**Comment by phroggster** [comment]
Closing this, as [8.4.2](https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_8.4.2) is out with no trail license nag text in the installer.

**Comment by draeath** [comment]
I'm still seeing this prompt with the 8.4.2 installer.
