### ISSUE TITLE
Syncing systems takes *ages*...

### ISSUE THREAD

**Issue by nickschurch** [EDDiscovery/EDDiscovery#1463]
I know there is a lot of systems, but it can take upwards of 10m to sync every time its started. There *must* be a better way to do this. Is it downloading and resetting every system every time?

**Comment by nickschurch** [comment]
I take it back, it *used* to take 10-15m, but today and yesterday its taking >2 hrs to sync!

**Comment by robbyxp1** [comment]
No further progress. closing
