### ISSUE TITLE
Window not maximizing

### ISSUE THREAD

**Issue by KiwiKev** [EDDiscovery/EDDiscovery#1465]
App will not come out of Minimised on a win 10
tried uninstalling and re-installing but did not fix

**Comment by iainross** [comment]
Have you tried launching in Safe Mode?
https://github.com/EDDiscovery/EDDiscovery/wiki/Safe-Mode

**Comment by phroggster** [comment]
If safe mode didn't do it, you should be able to double-click the minimised window panel, assuming it's visible. If not, try Alt+Space when the window is selected, then select Move and use your cursor keys to reposition the window. There should also be a Resize option in the menu, and you can perform the same cursor key manipulation after selecting that.

Let us know if you have any luck, ok?

**Comment by KiwiKev** [comment]
Hi 
Sorry for late reply SHIFT while starting worked fine. However i have found other issues which i will start a new post for
