### ISSUE TITLE
Suggestion: Value of currently accepted missions in mission panel

### ISSUE THREAD

**Issue by andybish** [EDDiscovery/EDDiscovery#1466]
The missions panel currently shows a total reward for completed missions within a given range, but there is no similar total for missions that are in progress. The credit reward is given in the MissionAccepted event, so would it be possible to display this in the missions panel, with a total for all active missions?

**Comment by robbyxp1** [comment]
Will look into it, thanks

**Comment by BannorPhil** [comment]
Hello

It would also be *awesome* if you could also add the number of missions currently in progress. I hope you will consider this idea.

Thanks

Philip

**Comment by robbyxp1** [comment]
9.2 added mission total
