### ISSUE TITLE
unhandled UI exception

### ISSUE THREAD

**Issue by b166er** [EDDiscovery/EDDiscovery#1467]
### Description
in Trilateration Tab, just clicked on Start new, then fill out all Distances and then clicked "Submit Distances". The Error Message come after: Submitting system to EDSM, please wait...
after clicked to continue in Messagebox, they do the job: "EDSM submission succeeded, trilateration successful."

### Additional Information
![screenshot](https://user-images.githubusercontent.com/679114/32851601-af654e86-ca35-11e7-8f20-75c96e011b76.png)

### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>   bei EDDiscovery.UserControls.UserControlTrilateration.checkForUnknownSystemsNowKnown()
>   bei EDDiscovery.UserControls.UserControlTrilateration.<>c__DisplayClass39_0.<SubmitToEDSM>b__1()
>   bei System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   bei System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   bei System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>===== END =====
>```

**Comment by klightspeed** [comment]
Suspected cause: systemCell.Tag is null at https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/UserControls/UserControlTrilateration.cs#L920, resulting in NRE on the next line.

**Comment by robbyxp1** [comment]
#1468

**Comment by robbyxp1** [comment]
on master only

**Comment by robbyxp1** [comment]
Closed due to 9.0.0
