### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by stimblus** [EDDiscovery/EDDiscovery#1469]
### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.Collections.ArrayList.get_Item(Int32 index)
>   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
>   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
>   at EDDiscovery.UserControls.UserControlSynthesis.Display()
>   at EDDiscovery.UserControls.ChangedSelectionHE.Invoke(HistoryEntry he, HistoryList hl)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection()
>   at EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl)
>   at EDDiscovery.EDDiscoveryController.RefreshHistoryWorkerCompleted(HistoryList hist)
>===== END =====
>```

**Comment by klightspeed** [comment]
Duplicate of #1435

**Comment by robbyxp1** [comment]
Is this on 8.4? Is it worth doing a new 8.4.x?

**Comment by klightspeed** [comment]
Yes, #1442 was pulled into master before the Branch_Release_8.4 branch was split off.

**Comment by robbyxp1** [comment]
Closing, fixed
