### ISSUE TITLE
Unhandled exception with 3D star map

### ISSUE THREAD

**Issue by zippy8** [EDDiscovery/EDDiscovery#147]
I am out at the edge, with systems few and far between. This is the first time I have seen this error.
-------------------------------------------------------------------------------
Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index.
-------------------------------------------------------------------------
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
   at EDDiscovery.TravelHistoryControl.buttonMap_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
EDDiscovery2
    Assembly Version: 2.7.6.0
    Win32 Version: 2.7.6.0
    CodeBase: file:///C:/Users/Mike%20Emery/AppData/Local/Apps/2.0/0ALADL3P.G2B/K0845W7D.80Q/eddi..tion_0000000000000000_0002.0007_389272a5ff0b4d5b/EDDiscovery2.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
OpenTK
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.1589.5942
    CodeBase: file:///C:/Users/Mike%20Emery/AppData/Local/Apps/2.0/0ALADL3P.G2B/K0845W7D.80Q/eddi..tion_0000000000000000_0002.0007_389272a5ff0b4d5b/OpenTK.DLL
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.99.0
    Win32 Version: 1.0.99.0
    CodeBase: file:///C:/Users/Mike%20Emery/AppData/Local/Apps/2.0/0ALADL3P.G2B/K0845W7D.80Q/eddi..tion_0000000000000000_0002.0007_389272a5ff0b4d5b/System.Data.SQLite.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.1589.5942
    CodeBase: file:///C:/Users/Mike%20Emery/AppData/Local/Apps/2.0/0ALADL3P.G2B/K0845W7D.80Q/eddi..tion_0000000000000000_0002.0007_389272a5ff0b4d5b/OpenTK.GLControl.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
    CodeBase: file:///C:/Users/Mike%20Emery/AppData/Local/Apps/2.0/0ALADL3P.G2B/K0845W7D.80Q/eddi..tion_0000000000000000_0002.0007_389272a5ff0b4d5b/Newtonsoft.Json.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by zippy8** [comment]
Update:
now I am back in explored space the map is working once again BUT when I toggle "draw lines" all of my data isn't displayed.

**Comment by klightspeed** [comment]
When it was throwing the IndexOutOfRangeException, were any of the systems up to the selected system trilaterated?

It looks like the error is due to using `<=` instead of `<` on line 619 of `TravelHistoryControl.cs`

**Comment by zippy8** [comment]
No systems were trilaterated. I was right out at the edge and had been for some time.

Now that I am back in previously logged space I am not getting the crash error but other strangeness persists (see my first reply).

**Comment by klightspeed** [comment]
EDDiscovery cannot show on the map systems for which there is no known location.  The only way to get an accurate location for a system is to trilaterate it.  Ergo, if a system isn't trilaterated, then it cannot be shown on the map.

**Comment by zippy8** [comment]
I appreciate that but it is not really the issue I am experiencing. 

At some point, asking for the 3D map simply caused a crash (as detailed in my first post). Now the crash is no longer happening, I can see the map but toggling the "draw lines" option removes ALL of my visited systems. Screenshots are here (http://imgur.com/a/MSX12).

**Comment by gregmalcolm** [comment]
I can think of 2 possible factors.

1)  (Crash only) You're running out of free memory. Close down your apps, start them up again try again. Better yet reboot.
2) System map filtering is messing things up. I've notice that my map too didn't look right when I turned on lines. Then I realized it was because my Visited Systems list was filtered. Set it to "All" in the dropdown box and your 3D map will likely start behaving.

**Comment by klightspeed** [comment]
@gregmalcolm Point 2 would explain why the last entries in the list would not have been trilaterated if he was using EDDiscovery in the bubble before setting out for the edge.

Repro:
1. Select a "show history" range that has the earliest system in the list having no known location
2. Select an entry in the history list that is between the first known location and the earliest system in the list
3. Click 3D Star Map

This causes an ArgumentOutOfRangeException on line 617 of `TravelHistoryControl.cs` due to `selectedLine` equalling `dataGridViewTravel.Rows.Count`, which in turn is due to `selectedLine <= dataGridViewTravel.Rows.Count` on line 619

Replacing `<=` with `<` on line 619 resolves this crash.

**Comment by zippy8** [comment]
It certainly is affected by the "Show history for the last....." option. 

Set to ALL, it works OK. 24 HOURS generates the unhandled exception, 3 DAYS does not (where was I three days ago ?). Performing a few trilaterations seems to be important in avoiding this too.

**Comment by finwen** [comment]
Should be fixed with klightspeeds fix.,   Will be in 3.0.4
