### ISSUE TITLE
Sound and graphics effected

### ISSUE THREAD

**Issue by KiwiKev** [EDDiscovery/EDDiscovery#1478]
I am running v8.4.1.0
on a imac bootcamp win10 machine
16gb memory 

I have noticed that when running this version if EDDiscovery the sound and graphics jutter and sound cuts out. Also the imac looses connection to the second monitor which is displaying EDDiscovery and a Chrome browser. I have to close EDDiscovery to get access to the 2nd monitor back.

Once closed both issues go away sound and video return to normal.

**Comment by phroggster** [comment]
Try resetting your theme via [Safe Mode](https://github.com/EDDiscovery/EDDiscovery/wiki/Safe-Mode) (hold <kbd>Shift</kbd> when starting EDD, click "Reset Theme"), and try removing any Add-Ons that are loaded ("Add-Ons" > "Manage Add-Ons" in the EDD main window menu). If you can't actually get a usable EDD displaying on your monitor, try deleting the Add-Ons from the `%LOCALAPPDATA%\EDDiscovery\Actions` folder and restarting EDD. You can then add your Add-Ons back, one-by one with an EDD restart in between, to see which one is problematic.

Also, your iMac was built in 2012 or newer, right?

**Comment by KiwiKev** [comment]
Hi Will try the above
just to be clear the whole system is effected not just the edd app, no add-in enabled
sys info below

OS Name	Microsoft Windows 10 Pro
Version	10.0.15063 Build 15063
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	BOOTCAMP10
System Manufacturer	Apple Inc.
System Model	iMac15,1
System Type	x64-based PC
System SKU	Unsupported
Processor	Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz, 3501 Mhz, 4 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Apple Inc. IM151.88Z.0211.B00.1708080656, 8/08/2017
SMBIOS Version	2.4
BIOS Mode	UEFI
BaseBoard Manufacturer	Apple Inc.
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume4
Locale	Australia
Hardware Abstraction Layer	Version = "10.0.15063.502"
User Name	BOOTCAMP10\Kevin Swain
Time Zone	E. Australia Standard Time
Installed Physical Memory (RAM)	24.0 GB
Total Physical Memory	23.9 GB
Available Physical Memory	17.2 GB
Total Virtual Memory	27.4 GB
Available Virtual Memory	18.5 GB
Page File Space	3.50 GB
Page File	C:\pagefile.sys
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not InstantGo, Un-allowed DMA capable bus/device(s) detected, Disabled by policy, TPM is not usable
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	No
Hyper-V - Data Execution Protection	Yes

**Comment by phroggster** [comment]
That all looks appropriate. Not being too familiar with Bootcamp, does your Windows 10 desktop span multiple monitors, with one being a retina display, and the other being a non-retina display?

If you're not needing any of the fancy add-ons, EDDiscovery can work right in Mac OS using [Mono](http://www.mono-project.com/docs/getting-started/install/mac/).

**Comment by klightspeed** [comment]
Please try the following build: https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/8.4.1.2016/artifacts

With that build:
* Extract it to a directory
* Create a shortcut to EDDiscovery.exe
* Modify that shortcut, and in the Target field add the following after a space at the end of field:
  ` -nosound -no3dmap -edsmnull`
* Run that shortcut and see if you have the same problem.

The above build adds options to disable sound, 3D map (using OpenGL), and EDSM interaction (to avoid the large EDSM systems fetch for testing) in EDDiscovery.

**Comment by KiwiKev** [comment]
Hi yes its a mac but running 100% windows
there is a 4k display and a lower res monitor that has edd on it
Not had a problem until this version
