### ISSUE TITLE
Feature request - Notification of a new galactic record

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1479]
On the exceedingly rare occurrence of getting a new record (from EGO) I noticed that the log said something like 'new record' which prompted me to go look in EGO (turned out to be lowest concentration of some material :/).  Anyhow, this was using a dual screen set up.
As I'm now confined to a single screen, I can't see the log anymore.  So....could we have some notification when a new record is found?  Ideally:
1)  The voice could say "A new galactic record has been recorded, well done Commander" or something.  *If* the actual record details can be retrieved, even better
2)  A visual notification - a) if you use the summary panel overlay, then add a line to the body scan display and b) in the scan panel, add an icon - like a star or something.

**Comment by RedfoxCh** [comment]
👍 ;-)

**Comment by robbyxp1** [comment]
We feed into to EGO.. do we get anything back from them?  I'm presuming that is what would be needed.

**Comment by RedfoxCh** [comment]
@robbyxp1 EDD must be getting some info from EGO in response to submissions, as within the EDD log window there's a dedicated message when a record is broken. Something like "New EGO record".

**Comment by iainross** [comment]
When we submit to EGO they respond with a bit of JSON including a boolean "unqiue_record_holder" field that indicates if the submission broke a record.  EGOClass.PostMessage passes the value back out in ref recordSet

**Comment by robbyxp1** [comment]
EGO will be announced by the new VP for the next version
