### ISSUE TITLE
Feature Request "show on EDSM"/"Show on EDDB"

### ISSUE THREAD

**Issue by bjornthv** [EDDiscovery/EDDiscovery#148]
Add "Show on EDSM" and/or "Show on EDDB"  to the right-mouse button context menu on systems in the "Travel history", "Route" and/or "Triliteration".

Having this option will allow people to go directly to the EDDB or EDSM page for that particular system/station/star to edit/update/submit the data that could not be entered via EDDiscovery.

Keep up the good work!

**Comment by gregmalcolm** [comment]
It's crossed my mind that this would be useful too. There is an icon for jumping to EDDB but it's intent isn't too obvious and appears and vanishes. I'd make it stay put but gray out when not needed

**Comment by bjornthv** [comment]
I submit a lot of data to both EDSM and EDDB, and as such, it would help me manage my screens a lot without having like 5 browsers open, EDDiscovery, mEDI's tool and ED:DM Market submitter, etc. This way I can eliminate 1 or 2 screens and focus more on the game instead of screen/app managing.

**Comment by iainross** [comment]
Show on EDSM is now there for Travel History, Trilateration, Wanted Systems, Closest Systems and selected system in the 3D map.  I s'pose I could add it to planned routes as well if you really want it there to.

**Comment by bjornthv** [comment]
I really appreciate it! And I think others will too!

Keep up the good work with this great tool.

**Comment by klightspeed** [comment]
I wonder if EDSM does or can support a route in the request, so a route in the Saved Routes can be shown on EDSM?

**Comment by AnthorNet** [comment]
?

**Comment by robbyxp1** [comment]
Go to EDSM EDDB implemented on main screen and in 3dmaps
