### ISSUE TITLE
Feature Request - Option to redisplay the body scan when dropping from orbital cruise

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1481]
Scenario - we've scanned a couple of bodies and decided to to land to collect some mats.
If you use the scan details in a summary panel overlay like I do, it would be nice to have the option for the scan display to re-appear as you drop from orbit

**Comment by iainross** [comment]
@Disorganise are you happy to close this one off the back of #1519 as well?

**Comment by Disorganise** [comment]
yes.  Your implementation is even better than I had hoped :)
