### ISSUE TITLE
Feature request - embolden the mats in the shopping list I can collect on this body

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1482]
Somewhat related to #1481 - as I drop from orbit, it would be nice if the materials available on *this* body were emboldened in the shopping list overlay.  It's sometimes possible to forget what you're looking for and be forever looking for a mat that doesn't exist because it was on the *other* body.  I know, I know, I should pay more attention - but tools are meant to make life easier right?

**Comment by Disorganise** [comment]
I think this is taken care of on 9.03.  Not BOLD per se, but the particular mats I want to collect that are available on this planet are given their %age and the summary of *all* the mats on this planet are shown below.   It's awesome o7

**Comment by iainross** [comment]
It'll even tell you what planets have the mats you want and at what concentrations while you're flying through the system (including an option to decide whether you want to include available EDSM data in that)
