### ISSUE TITLE
Feature request - Voice over reminding of gravitational conditions as you drop from orbit

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1483]
It would be a nice reminder of what the gravity is for this body as you drop from orbital cruise - whether this simply be a repeated verbatum of the gravity, or some summary included (eg, when gravity is 1 or more "take care, gravity is moderate here", to when gravity is 2+ "reminder, gravity is high here - thruster efficiency is reduced" and when 4+ "Gravity is extreme - be careful out there.  go gentle and slow") <- you get the drift.
For the high gravity conditions, perhaps another reminder (option) when landing gear is deployed

**Comment by robbyxp1** [comment]
So you only get gravity if you have a scan.  No scan, no knowledge.  I don't think its worth it to code this as I can't guarantee the warning.   You can go to a 4.5g world and if you have no scan I can't warn you.

So i think its a non goer.

**Comment by phroggster** [comment]
What about a "gravitational conditions unknown; use caution" (or similar) message if scan data is not available?

**Comment by andreaspada** [comment]
I like it, @phroggster!
