### ISSUE TITLE
Suggestion - For Neutron and WD systems, give advanced verbal warning

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1484]
When we finish the countdown, the voicepack tells us the class of system we're jumping to.  Unfortunately, "Star is N Class" can sound quite similar to "Star is M Class".  Could there be some logic added so if it is a Neutron it says "Star is Neutron Class" instead?   Or...for 'dangerous' stars, a heads up to 'throttle back and prepare for counter measures' or something :)

**Comment by robbyxp1** [comment]
Will warn in 9.0.1 with pack 6.0.1
