### ISSUE TITLE
Win10Pro BSOD KMODE_EXCEPTION_NOT_HANDLED 0x0000001e - Kaspersky klbackupdisk bitlocker fvevol

### ISSUE THREAD

**Issue by dave-001** [EDDiscovery/EDDiscovery#1486]
Since updating to EDDiscovery_8.4.1 on Windows 10 Professional I'm getting a repeated BSOD 0x0000001e (KMODE_EXCEPTION_NOT_HANDLED).

Message in eventvwr is: The computer has rebooted from a bugcheck.  The bugcheck was: 0x0000001e (0xffffffffc0000005, 0xfffff80181e11604, 0x0000000000000000, 0x000000000000002c). A dump was saved in: C:\WINDOWS\Minidump\111917-11000-01.dmp. Report Id: eed2213f-418e-4164-95f8-b017677fbdf1.

This occurs whenever the hourly download/update takes place so it means that I only get about 50 minutes of gameplay in E:D and then suffer a reboot. The same BSOD behaviour also happens when I first start up EDDiscovery each day and it does the larger updates.

Is it possible to go back to EDDiscovery_8.3.03 which was stable for me?

**Comment by klightspeed** [comment]
Are you able to download large files (e.g. https://www.edsm.net/dump/systemsWithCoordinates.json)?

**Comment by dave-001** [comment]
Yes... downloaded using Save As in Edge... 2.19GB

**Comment by dave-001** [comment]
I've got 33639 entries in EDDiscovery - wonder if the database is reaching some kind of limit? EDDSystem.sqlite is just under 4GB - is that still okay? EDDUser.sqlite is ~40MB.
Even with all of that the memory footprint for EDDiscovery is only 214MB.

**Comment by klightspeed** [comment]
If you run BlueScreenView <http://www.nirsoft.net/utils/blue_screen_view.html#DownloadLinks>, does that show what windows kernel module the BSOD is in?

Also, please try the build at <https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/8.4.1.2016/artifacts> and use the `-noaudio` command-line option to disable audio in EDDiscovery and see if you see any crashes.

The entry count in EDDiscovery sounds reasonable, as does the EDDUser.sqlite database size.  The EDDSystem.sqlite size is about right for about 15M systems currently in EDSM.

**Comment by dave-001** [comment]
BlueScreenView reports as: caused by ntoskrnl.exe - caused by address ntoskrnl.exe+ 1640e0
Will download the build you've pointed me to and post back a little later with results...

**Comment by phroggster** [comment]
STATUS_ACCESS_VIOLATION with a null arg0, and a 0x2c arg1?

Do you have write access to "%LocalAppData%\EDDiscovery" as well as "%TEMP%"

**Comment by klightspeed** [comment]
@phroggster not having write access shouldn't cause what is basically an NRE in the windows kernel.

**Comment by dave-001** [comment]
This...

111917-11000-01.dmp	19/11/2017 10:48:00	KMODE_EXCEPTION_NOT_HANDLED	0x0000001e	ffffffff`c0000005	fffff801`81e11604	00000000`00000000	00000000`0000002c	ntoskrnl.exe	ntoskrnl.exe+1640e0					x64	ntoskrnl.exe+1640e0					C:\WINDOWS\Minidump\111917-11000-01.dmp	8	15	16299	361,625	19/11/2017 10:52:54	
Yes, I've got write access - I've been using EDDiscovery since version 7.something :-)

**Comment by dave-001** [comment]
@klightspeed - will that portable version that you've asked me to try from appveyor use my normal database files?

**Comment by klightspeed** [comment]
If you extract the DLLs from that zip file to your EDDiscovery install directory, then yes.

Same if you extract everything from that zip to a directory, then copy `EDDiscovery.exe.config` from your EDDiscovery install directory to that directory.

**Comment by dave-001** [comment]
Thanks - will give it a go now

**Comment by phroggster** [comment]
While you're at it, can you attach the minidump from C:\WINDOWS\Minidump\111917-11000-01.dmp?

**Comment by dave-001** [comment]
Here you go... 
[111917-11000-01.zip](https://github.com/EDDiscovery/EDDiscovery/files/1485515/111917-11000-01.zip)

**Comment by dave-001** [comment]
Just got the same BSOD with the appveyor downloaded version also... is it worth overwriting EDDiscovery.exe.config with the one in the zip file also - I'll have to re-enter my API keys etc. again but if there's a chance that resetting that file might clean things up I'd be willing to give it a go...

**Comment by klightspeed** [comment]
Did you use the `-noaudio` option?

**Comment by dave-001** [comment]
Good point - I launched it from the icon on my desktop... let me give it another go... :)

**Comment by phroggster** [comment]
That's bitlocker crashing, with what looks like Kasperky anti-virus interfering. Try and update your anti-virus and reboot.

![windbg](https://i.imgur.com/DU8Rjbu.png)

**Comment by klightspeed** [comment]
10.0.15063 is 1703

**Comment by phroggster** [comment]
Yes, but 10.0.16299 is what is in use:

![untitled](https://user-images.githubusercontent.com/14035789/32990797-45b9a1ea-ccf5-11e7-849b-4bbe384d91ba.png)

**Comment by phroggster** [comment]
Apparently, klbackupdisk (a module closer to the start of the stack) is your problem. Kaspersky Labs backup disk filter. If updating Kaspersky doesn't fix it, try disabling it's backup features, rebooting, and seeing if this problem is still evident.

**Comment by dave-001** [comment]
@phroggster @klightspeed - thanks for your assistance to date...

I updated to Fall Creators a few weeks ago, had been running EDDiscovery_8.3.03 which was stable for me.

Version of Kaspersky is shown below - it's the latest afaik

![2017-11-19](https://user-images.githubusercontent.com/33800654/32991056-9f84c4fc-cd2c-11e7-8cb2-fa552ad981f9.png)

I'd already excluded EDDiscovery related stuff from being scanned at all by Kaspersky (excluded c:\users\<username>\appdata\local\eddiscovery\)

I've now added (temporarily) EDDiscovery as a Trusted Application within Kaspersky to see if that helps any.

I've not got Kaspersky backup enabled... it recommends that I configure it, but it's not currently configured

![2017-11-19 1](https://user-images.githubusercontent.com/33800654/32991156-0fec2266-cd2e-11e7-8063-098eecc0a81b.png)

I can't see any way of switching off/disabling the Kaspersky backup module from within the product and there doesn't seem to be anything obvious on Google...

**Comment by phroggster** [comment]
Try repairing, or fully [reinstalling](https://kaspersky.com/downloads/thank-you/total-security), Kaspersky, or even engaging their [Support](https://my.kaspersky.com/en/support/helpdesk) channel (particularly with the minidump attachment). Seealso, a [BSOD thread on Kaspersky forums](https://forum.kaspersky.com/index.php?/topic/382679-bsod-klbackupdisksys/&tab=comments#comment-2753352) from Friday that looks identical.

**Comment by klightspeed** [comment]
Similar BSOD with Kaspersky 18 installed:
https://forum.kaspersky.com/index.php?/topic/382679-bsod-klbackupdisksys/&tab=comments#comment-2753352

**Comment by phroggster** [comment]
![ninja](http://gifimage.net/wp-content/uploads/2017/08/ninja-gif-22.gif)

**Comment by dave-001** [comment]
Unfortunately Kaspersky seem to have been made aware of this some time ago and have done nothing to resolve it (yet). There are even posts stating that any fix won't be until the 2019 version of KTS. There are also posts with folk attempting to downgrade KTS to 2017 and getting into a complete mess.
Kaspersky support would need a full 16GB dump sending to them before they'd look at/review my particular issue by the look of things - minidumps don't apparently give them enough information of what I've got running in my computer memory...
@klightspeed and @phroggster - as much as I'd rather not switch off bitlocker, I suspect that the issue would then evaporate... thoughts?

**Comment by phroggster** [comment]
Ahh, I've forgotten how much fun anti-virus providers are to work with.

- [ ] Find a ~2GB stick of RAM
- [ ] Activate "Complete memory dump" mode, and shutdown PC
- [ ] Remove 16GB RAM, insert 2GB RAM, and power on PC.
- [ ] Coax blue screen, wait for it to write it all out to disk, and shutdown PC.
- [ ] Remove 2GB RAM, insert 16GB RAM, power on PC, and reactivate "Small memory dump (256 KB)" mode
- [ ] Move `%SystemRoot%\MEMORY.DMP` to `%USERPROFILE%\Google Drive` (or DropBox/SkyDrive/Resilio/etc), and wait for it to sync with $CloudProvider.
  - [ ] Meanwhile... Change any passwords that may potentially be present in the memory dump...
- [ ] Submit a ticket to Kaspersky, and be sure to invoice them for the 2GB stick of RAM that you had to buy, as well as the 2GB file upload, and the cumulative time wasted by all three of us.

Or... I don't really know. Maybe changing the bitlocker key, or user password, or (faulty?) TPM chip, or ... something ... can reset something in Kaspersky? Maybe just disable it while playing?

**Comment by dave-001** [comment]
LOL @phroggster - you're correct... they are 'fun' to work with.

Anyway, a little good news, adding EDDiscovery as a 'trusted application' within Kaspersky seems to have stopped the BSOD's, or at least I've not had one for a couple of hours. I'll post back to let you know if it continues to behave, and if it does behave I'll try to play around with the settings within 'trusted apps' in Kaspersky to see if I can work out which settings is causing the issue.

**Comment by dave-001** [comment]
A quick update - since adding EDDiscovery as a 'trusted application' within Kaspersky Total Security the issue has disappeared and no more BSOD's. I'll see if I can work out which setting causes things to go awry and post back, but it might not be for a week or ten days.
