### ISSUE TITLE
False double entry when restarted

### ISSUE THREAD

**Issue by SamMackrill** [EDDiscovery/EDDiscovery#149]
Whenever I return to EDDiscovery the next day I have a double entry at my present location.
Here you can see a couple:

![2016-03-27 09_42_02-eddiscovery v2 7 6 0 systems_ 138653](https://cloud.githubusercontent.com/assets/84898/14064599/6ecb2812-f400-11e5-8c52-e53941676188.png)

**Comment by Red13x3** [comment]
Yep, been getting that for a while. 

--
Mark
iPhone: 0402 322 901

**Comment by gregmalcolm** [comment]
Yup

**Comment by mwerle** [comment]
Although it's only temporary -  when you sync with edsm the duplicate disappears.

**Comment by AnthorNet** [comment]
Our API do not accept duplicate

**Comment by mwerle** [comment]
I meant, the duplicate disappears in EDDiscovery; but haven't checked the code yet to see how or why. I've assumed up to now that it does a sanity-check at the time of processing entries for upload.

**Comment by finwen** [comment]
Probably solved it for 3.0.3 now.

Doing some testing
