### ISSUE TITLE
Unhandled exception in statistics panel

### ISSUE THREAD

**Issue by Allitnil2** [EDDiscovery/EDDiscovery#1495]
### Description
Unhandled exception when attempting to access the Travel tab in the Statistics panel (happens in both 8.4.1 and 8.4.2). 

### Additional Information
It was working fine earlier today but now throws up this error every time. Have I been exploring too much? ;)

### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.OverflowException: Arithmetic operation resulted in an overflow.
>   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
>   at EliteDangerousCore.HistoryList.GetScanValue(DateTime start, DateTime to) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 308
>   at EDDiscovery.UserControls.UserControlStats.StatsTravel(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlStats.cs:line 336
>   at EDDiscovery.UserControls.UserControlStats.Stats(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlStats.cs:line 97
>   at EDDiscovery.UserControls.UserControlStatsTime.comboBoxTimeMode_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlStatsTime.cs:line 203
>   at ExtendedControls.ComboBoxCustom._cbsystem_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\Controls\ComboBoxCustom.cs:line 553
>   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
>   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
>   at System.EventHandler.Invoke(Object sender, EventArgs e)
>   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
>   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>   at System.Windows.Forms.Control.CreateControl()
>   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
>   at System.Windows.Forms.TabPage.set_Visible(Boolean value)
>   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
>   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
>   at System.Windows.Forms.TabControl.WmSelChange()
>   at System.Windows.Forms.TabControl.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
That suggests the selected range has a total estimated scan value of more than 2 billion credits.

**Comment by Allitnil2** [comment]
Thought that might be it. My total scan value is certainly over 2 billion now. I expect the scan value for my current trip alone to be over 3 billion by the time I next dock.

**Comment by klightspeed** [comment]
We probably need to change `GetScanValue` to return a `long`, and cast the body estimated values in `Sum` to a `long`
