### ISSUE TITLE
Feature Request: System Screenshots

### ISSUE THREAD

**Issue by Red13x3** [EDDiscovery/EDDiscovery#15]
Synopsis:  An area of the main screen, perhaps under the main Travel History list, that shows the screenshot from a particular (configured) folder, determined by the creation date/time of the file, compared to the selected system's entry time.

Reasoning:  Who doesn't like a screenshot! :)

Method:  Elite has it's own inbuilt screen capture capability which could be used. Or you can have another utility running that works on a different key-bind and save the pictures to a different folder. Or you can take various screenshots, and then manually move them into the configured EDD screenshots folder. Either way, EDD (in the Settings tab) is configured to watch a particular folder for JPG/PNG files.

When a system is selected and a new button called "Screenshot" is clicked, EDD looks in the configured folder for the first image file that is older than the selected system Jump date/time.  When it finds a file, it checks if there is an older/later jump than the currently selected jump. If the time-stamp of the image it has found is equal or greater than this _next_ jump system, then it does not add the reference filename to the record, because it is assumed the screenshot it has found was taken after jumping into the next system and is thus a shot of the next system, not the current one.
(If indeed the screenshot of the current system was taken after jumping into the next system, the user could modify the Creation date using any number of utilities. Or, I suppose we could add a "Manual Shot Selection" button?) Anyway, once a screenshot is selected for a system, the filename is saved to the record and is used to display the screenshot whenever a Jump with the system is selected.

User must be able to size the screenshot portal in height (Or hide it all together), with the width always being the width of the Travel History list. Screenshot to be displayed without distortion (no stretching) within the area allotted by the user.

**Comment by Majkl578** [comment]
Note: Screenshots are logged in the netLog, e.g.:

> {01:23:45} SCREENSHOT: Saved \ED_Pictures\Screenshot_0123.bmp , w:1920, h:1080, pitch:7680, sourceFormat:B8G8R8A8un_In8

**Comment by finwen** [comment]
I have thought about something similar too. It is an area i want to work on after summer.

**Comment by gregmalcolm** [comment]
Would be really nice if screenshots could be sent to EDSM. I may have to ask around to see if they're interesting some PRs... :D

**Comment by Red13x3** [comment]
I don't know if you'd get a lot of support for that, as the data it would need to then hold is potentially huge. 

I'm happy with EDD just referencing my own screenshots. 

Mark

--
Mark Jelic
iPhone: 0402 322 901

**Comment by Red13x3** [comment]
Bump...

Personally, I don't have a use for the "Closest Systems from..." list... I reckon that would be the ideal location for a little screenshot. Could we have to the right of the Label that says "Closest system" a little drop box arrow that opens with the option of "Show Screenshot" and "Show Closest Systems" and whatever else people may want in that corner, instead?

**Comment by bambi72** [comment]
I just came here to post this,so you saved me some typing.

The new beta is great too...

**Comment by robbyxp1** [comment]
Closed. old. screenshots have been reworked
