### ISSUE TITLE
 EDSM sync error submitting system (Training) 304: System is a training mission.

### ISSUE THREAD

**Issue by thestyx** [EDDiscovery/EDDiscovery#1509]
Since today EDD does not sync scanned bodies from a system to EDSM. It syncs only the system. It worked yesterday and the days before without a problem.

it shows the following log entry :   EDSM sync error submitting system (Training) 304: System is a training mission.

Btw, I was not in any training mission for a long time.

**Comment by klightspeed** [comment]
Look for a Location event with system name "Training", and hide it.

As for syncing bodies, you need to have Send to EDDN enabled.

**Comment by thestyx** [comment]
I had sync to EDDN enabled but switched it of because I started to use EDMarketConnector. Today I forgot to start EDmarketConnector. I knew that the error was on my end, I just could not figure it out. 

Sorry about that and thanks for the help.

**Comment by klightspeed** [comment]
You should be able to right-click each of the bodies that didn't get sent and Send unsynced scan to EDDN.
