### ISSUE TITLE
Value wrong against planet types, not sure where the issue lies.

### ISSUE THREAD

**Issue by mearmortal** [EDDiscovery/EDDiscovery#1510]
Hello,
   I wanted to tell someone about this and it's a good place to start.
I've been keeping an eye on the Cartogaphy Data being sold back to the stations etc and I'm finding that quite a few systems are falling short of the value indicated as an estimate in EDDiscovery.
I've accumulated 

twelve samples and the values I'm getting back from the game. There is quite a big difference so I'm wondering if there is a classification problem on object selection. To be fair most of the objects in EDD are accurate to within 1 credit, but these are out by several hundreds of thousands. 
This might be an easy fix I don't know, I hope this helps.
EDD is a wonderful application and I'm finding it very useful to use, so I only want to make it better.
Thanks.
[objects with issues.docx](https://github.com/EDDiscovery/EDDiscovery/files/1519966/objects.with.issues.docx)

**Comment by klightspeed** [comment]
Looks like those are all water worlds with water or ammonia atmospheres.

**Comment by mearmortal** [comment]
Is the calculation done with EDD or is it obtained externally from another source?

**Comment by klightspeed** [comment]
The value is estimated at https://github.com/EDDiscovery/EDDiscovery/blob/master/EliteDangerous/JournalEvents/JournalScan.cs#L946

**Comment by iainross** [comment]
Yes - that is unfortunately a thing :(

For most planets we know the value pretty exactly as a function of body type and mass.  If it's terraformable or earth-like there's an additional terraforming bonus on top of that.  We know the maximum terraforming bonus (which you usually get, and is what EDD assumes) but we also know that around 30% of those planets only get some fraction of the terraforming bonus - usually more than 90% of it but it can be less than 10% in a handful of cases we've observed.  What we don't yet have is a reliable way of determining exactly what fraction any given body is going to get.

There is much discussion and data in this forum thread: https://forums.frontier.co.uk/showthread.php/232000-Exploration-value-formulae

If you're recording data on EDD's predicted values against actual in game values then please do share it all on that thread - hopefully we'll crack it one day...

**Comment by mearmortal** [comment]
Well thats good news, at least it's being looked at. I'll share what I have so far, and the next time I dock I'll have a look at the values again, might be about a month though.

**Comment by mearmortal** [comment]
Well thats good news, at least it's being looked at. I'll share what I have so far, and the next time I dock I'll have a look at the values again, might be about a month though.

**Comment by mearmortal** [comment]
Having read through the code on the link I wanted to know what the variable terraformable was doing, as it had to be something related to that. I worked out the rest.

**Comment by robbyxp1** [comment]
Label set as we can't really fix it at this point
