### ISSUE TITLE
Reset of Sorting upon Journal Update

### ISSUE THREAD

**Issue by RedfoxCh** [EDDiscovery/EDDiscovery#1512]
New Journal-Events will trigger a reset of the sorting of the table on the "Scan" Sub-Tab within the "Statistics" Main-Tab.

No big issue, just a little annoying, as I wanted to look through my scan-stats while travelling in ED on the other screen.

**Comment by robbyxp1** [comment]
We will investigate a fix..

**Comment by robbyxp1** [comment]
Will be Sorted in 9.2
