### ISSUE TITLE
Changing Account causes incorrect Mileage to show

### ISSUE THREAD

**Issue by andrewhubb** [EDDiscovery/EDDiscovery#1513]
I have two accounts I have noticed that when I switch from one that is in the bubble to my exploring one out by Colonia that the distance travelled gets updated with the distance from my bubble account and my exploring account.  So I end up with a 20K light year jump distance. This then gets uploaded to EDSM so I see straight lines on my travel map from the bubble to where I am.

![eddiscoveryissue](https://user-images.githubusercontent.com/17042998/33524171-5c961c12-d84a-11e7-8094-97178468a8a0.png)

I've uploaded the sample screen from the Statistics window.

**Comment by klightspeed** [comment]
Do you have a separate EDSM account for each commander?

**Comment by andrewhubb** [comment]
Hi,
Yes I do,

**Comment by klightspeed** [comment]
What version of EDDiscovery are you using?

**Comment by andrewhubb** [comment]
Having checked. I think I know what the cause is. Its because EDDI was also
set to send information up to EDDN and EDSM using my primary account.
An oversight on my part.
