### ISSUE TITLE
VoicePackV5 error on startup with 8.4.2

### ISSUE THREAD

**Issue by Tachy** [EDDiscovery/EDDiscovery#1516]
1. Start EDDiscovery without Addons
2. Installing VoicePackV5
3. Close EDDiscovery
4. Start EDDiscovery
5. Error in Log attached as screenshot
![error](https://user-images.githubusercontent.com/2771003/33653626-ec5ddd2e-da6d-11e7-9e41-69472c118926.png)

**Comment by phroggster** [comment]
VoicePackV5 is for use with (the as-yet unreleased) EDDiscovery v9.0.0. Switch back to VoicePackV4 for now.

**Comment by Tachy** [comment]
aaahh .. perfect! :)

**Comment by robbyxp1** [comment]
I will investigate next week.

**Comment by robbyxp1** [comment]
Fixed on server. VP5 had an error introduced when atmosphere was corrected
