### ISSUE TITLE
Trip computer Panel reset when changing or checking ship details

### ISSUE THREAD

**Issue by Teyar** [EDDiscovery/EDDiscovery#1517]
When changing the ship details reset the trip computer panel (similar to pressing the Start button on the panel). Even if you only open ship details to check the details and then close the window with Cancel (without having made a change), the panel reset as in "Start".
I can't imagine this to be so.

Please check.

Greetings
Teyar

**Comment by robbyxp1** [comment]
Hi,

I can't see this happening with the latest code.  I open the ship details window and close it, nothing changes. Start marker does not change etc.

**Comment by Teyar** [comment]
Hi,

you're right.
However, I can assure you that the error that was described actually occurred when I reported it.
I'm not writing an error message just to keep you busy.

Whatever's bothered, now it works for me.

I think the ticket can be closed now.
