### ISSUE TITLE
Re-scan all journal files creates duplicate entries

### ISSUE THREAD

**Issue by thestyx** [EDDiscovery/EDDiscovery#1518]
Hi,

I don't know whether this is related to one of the previous posts, and I am not certain whether this is a bug or feature.

When I 'Re-scan all journal files' it does not seam to drop the old tables, it adds the journal files to the old ones. After the process is finished I have duplicate entries. I could confirm that in the statistics where I had before the re-scan in Traveled ly 35,000 ly and after the re-scan 70,000 ly. I could remedy this issue by 'Delete duplicate FSD Jump entries'.

Thanks for this awesome program. Keep up the great work.

o7

CMDR Steyla

**Comment by robbyxp1** [comment]
I will investigate next week

**Comment by robbyxp1** [comment]
Found, PR #1538 will fix this. Thanks for the report. Invaluable!
