### ISSUE TITLE
Enhancement: EGO record triggers voice-output 

### ISSUE THREAD

**Issue by RedfoxCh** [EDDiscovery/EDDiscovery#1520]
When submitting a scan to EGO and getting a record it would be great to have a voice-output announcing just that (in order to to able to take a screenshot for upload to EGO).

**Comment by robbyxp1** [comment]
I'll have to look, after 9.0

**Comment by Disorganise** [comment]
Great minds :)
https://github.com/EDDiscovery/EDDiscovery/issues/1479

**Comment by RedfoxCh** [comment]
👍 :)
Pretty sure I checked the open issues before submitting - must have overlooked #1479.
I'll close this one, as it's a subset of #1479.
