### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by XeroWonToo** [EDDiscovery/EDDiscovery#1522]
### Description
I had loaded it up, and set it up in my usual fashion.  Popped out my journal and put it "on-top" so I could see it while I explored.  It had happened once last night but I didn't do anything different.  I'm not even sure what the issue really is...I'm not very in-the-weeds techno savvy, just following up to help you guys out.  

### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentNullException: Value cannot be null.
>Parameter name: key
>   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
>   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
>   at EliteDangerousCore.StarScan.FindSystem(ISystem sys) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 156
>   at EliteDangerousCore.StarScan.FindSystem(ISystem sys, Boolean useedsm) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 600
>   at EDDiscovery.UserControls.UserControlEstimatedValues.DrawSystem() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlEstimatedValues.cs:line 117
>   at EDDiscovery.UserControls.UserControlEstimatedValues.NewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlEstimatedValues.cs:line 74
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 643
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 625
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 533
>===== END =====
>```

**Comment by klightspeed** [comment]
That suggests that `System.name` in the last history entry is null.

The most likely path I can find where this would happen is if the Systems DB is inconsistent, resulting in one or more systems missing their name.

**Comment by iainross** [comment]
Same issue as #1577
