### ISSUE TITLE
Virus or Potentially Unwanted Software Message with v8.4.2 Installer

### ISSUE THREAD

**Issue by KeithJKT64** [EDDiscovery/EDDiscovery#1523]
Hi, I keep getting this message when I try to run the exe file. I have checked it with AVG and malwarebytes and it says its fine. Hope you can help. 
![capture](https://user-images.githubusercontent.com/34427324/33810930-a820b5c0-de03-11e7-81c4-9b3d0a15bed5.JPG)

**Comment by phroggster** [comment]
Which anti-virus solution(s) are you using?

**Comment by KeithJKT64** [comment]
Hi Lee,

I was using AVG and Malwarebytes.

Keith

**Comment by phroggster** [comment]
AVG and MalwareBytes are both showing clean from the VirusTotal links that I provided above, but their heuristic settings are likely different than yours. Sometimes a reboot, and/or a fresh scanning definition update can clean it up. However, it's not something on our end (to my knowledge).

The other thing to check would be the file hashes, in case something modified it locally. I realize that we don't post the hashes on our releases page (I'll see if we can correct that), but the details tabs on the VirusTotal links above match the file that I downloaded:
![untitled](https://user-images.githubusercontent.com/14035789/33811440-16436df2-ddd9-11e7-9a17-1c759406b726.png)

**Comment by klightspeed** [comment]
Unfortunately one antivirus flags the installer as "Backdoor.MSIL.xnx"
https://www.virustotal.com/#/file/b280904bfa9a69fa405b10bc15d1077d256c73d3f49239b03e1b16bcc3e309ed/detection

Also, at least one antivirus thinks the 32-bit SQLite interop is a trojan:
https://www.virustotal.com/#/file/92eb2b8345113ed1f749b1a41d950f446e64b06f8e8dfbb2b46b7a29d1009426/detection
https://www.virustotal.com/#/file/85a60e3acb69906bd29007dbfa482af17b184780f1960d0ff2b2bfd36a9622a7/detection

**Comment by temotodochi** [comment]
Not a bug. This is a feature of anti-malware programs that never before seen programs (newly compiled, new versions) regularly get blocked. Each program a user runs is checked towards a massive list of known files and their reputation and if it's not found there it's flagged for further study and execution is prevented.
