### ISSUE TITLE
Mistake in English speech file

### ISSUE THREAD

**Issue by Taomyn** [EDDiscovery/EDDiscovery#1535]
Just updated my speech file to v5.0.3.0 and needed to re-apply my tweaks, but it reminded me of a mistake:

![clipboard01](https://user-images.githubusercontent.com/4365929/33955282-497869ca-e03b-11e7-9a77-c5bf9be1bb43.jpg)

In case it's not obvious, there are two "say_txt4" entries.

BTW, no-one says "Salutations" as a parting phrase in English, to me a native speaker it just sounds wrong, it's reserved for formal writing maybe. I always change this to "Farewell".

**Comment by robbyxp1** [comment]
Thanks, will fix

**Comment by robbyxp1** [comment]
Fixed in VP6
