### ISSUE TITLE
No real mistake, but an idea about the route tracker panel

### ISSUE THREAD

**Issue by Teyar** [EDDiscovery/EDDiscovery#1541]
Hi,

mostly you use the route tracker for longer trips with several or even many waypoints. This leads me to two considerations for the Route tracker panel. Both considerations refer to the first line in the Route tracker panel (for better understanding I have added a picture).

![route-tracker](https://user-images.githubusercontent.com/30482684/34003501-b28d173e-e0f5-11e7-9293-48394f2aecff.png)

1. The number of waypoints is determined by the number of entries in the Expedition Planner. Here it should be considered that the starting point (starting system) is not counted as a waypoint. You can correct it yourself by deleting the first entry in the export file, but it would be nice if the route tracker could fix it yourself.

2. I have noticed that the total distance and the entire jumps of a route refer to the final destination (see picture, here is the final destination Colonia and the distance is that from my current position to Colonia). However, this is not the distance of the route from my current position. As it is now presented it is somewhat irritating.

The second line in the route tracker is correct (except for the waypoint, but that results from 1.)

It would be nice if the two considerations could be considered in a later version. Since they are not real mistakes, there is no hurry with it.

Greetings
Teyar

**Comment by robbyxp1** [comment]
9.2 shows path distance, and distance along path, not direct distance to waypoint.
