### ISSUE TITLE
Stuck in "updating journal entries"

### ISSUE THREAD

**Issue by hgwaz** [EDDiscovery/EDDiscovery#1543]
Starting with 8.4 I've been unable to get EDDiscovery to run, it's always stuck in "processing log file updating journal entries", ([see here](https://i.imgur.com/nW3MBNs.png)). I know it takes a bit for it to start, but this is not it. I've tried having it run the whole night but when I woke up in the morning it was still the same. I'll get the "welcome CMDR" message after some time (around 20 min I'd say) from the voicepack, but afterwards nothing happens.

**Comment by klightspeed** [comment]
The screenshot shows you were affected by #1508 

Please close EDDiscovery, then hold Shift while re-launching it and reset the position and layout.

**Comment by hgwaz** [comment]
Yup that did it. Resetting windows and theme made it launchable. Thanks for the help!
