### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by zebernst** [EDDiscovery/EDDiscovery#1546]
### Description
This error happens when EDDiscovery opens, presumably at some point while it's loading. It takes a couple of seconds to pop up, during which I did not interact with the program at all.

### Additional Information
n/a

### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
>   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
>   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
>   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
>   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
>   at System.IO.Stream.Close()
>   at EliteDangerousCore.CompanionAPI.RijndaelCrypt.Decrypt(String encryptedValue) in C:\Code\EDDiscovery\EliteDangerous\CompanionAPI\RijndaelCrypt.cs:line 79
>   at EliteDangerousCore.CompanionAPI.CompanionCredentials.get_IsComplete() in C:\Code\EDDiscovery\EliteDangerous\CompanionAPI\CompanionCredentials.cs:line 56
>   at EliteDangerousCore.CompanionAPI.CompanionCredentials.CredentialState(String cmdrname, Boolean& disabled) in C:\Code\EDDiscovery\EliteDangerous\CompanionAPI\CompanionCredentials.cs:line 118
>   at EDDiscovery.EDDiscoveryForm.Controller_RefreshComplete() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 669
>   at EDDiscovery.EDDiscoveryController.RefreshHistoryWorkerCompleted(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 566
>===== END =====
>```

**Comment by robbyxp1** [comment]
Delete credetials* files in c:\users\<name>\appdata\local\eddiscovery.  Looks like the credential file for the CAPI may be bust.

**Comment by robbyxp1** [comment]
If it fixes it, not sure how it got bust.
