### ISSUE TITLE
Feature Request: Show System in ED Toolbox

### ISSUE THREAD

**Issue by CMDRLucienn** [EDDiscovery/EDDiscovery#155]
The ability to see system data in EDDB and ROSS for modification are very useful buttons; however, the addition of a button to see the information in ED Toolbox for users of that tool would also be incredibly useful.

EDTB displays its data in the browser, by default by broadcasting a webpage on the localhost on port 3001. The URL for a given system follows the pattern:

http://localhost:[PORT]/System/?system_id=[SYSTEMID]

Where the PORT is the port that the user has specified in the settings file for the webpage to broadcast on, and the SystemID is the EDDB ID of the given system (displayed in the EDDB URL for that system).

Users can configure the port which EDTB uses, so it might be worthwhile to provide a setting in the EDDiscovery settings page for the user to define which port they would like the URL button to use. It might also be worthwhile to consider the option for the user to change which IP (localhost by default) the URL button should use, for users of multiple computer setups, or users who host their EDTB database remotely on another address.

**Comment by robbyxp1** [comment]
No further action , closed
