### ISSUE TITLE
More freedom in stars filtering and display

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#1554]
Dear @finwen, @robbyxp1, @klightspeed, I was thinking by a while that it seems we need some more tools to let us display systems and their distance around our current position - or around a defined position - with more fine grained control. I'm working on a prototype for a tabbed panel, similar to the StarDistance one, which let the user define a range to display a sphere, a shell (with inner and outer radius), a cube and a cubical shell. There are already requests for that (#1427) and I found that is something important the program is lacking. 

With all the quests around, both in xeno and astronomical research, having tools to properly display and manipulate systems lists within user defined constrains is something witch hugely improve our gaming experience, IMHO.

I'm proposing a combined effort to have this implemented in a simple, fast, practical yet expandable way. 

The following tools are something I feel we lack, in order of proposed urgency:

1. Display a list of systems in a user defined range, within or not a maximum number of entries
2. Display a list of systems in a user defined shell, within an inner and outer radius, within or not a maximum number of entries
3. and 4. The same, for cubes and cubical shells
5. List of systems filtered by stars class or other relevant characteristics: binary, having landable planets, jumponium class, etc...
6. A 3D and 2D map which display the filtered systems - by the previous systems - in a graphical way. Ideally, the 2D or 3D mini-map should be able to be panelized and/or used as overlays...
7. The 2D map could be a flat view of a plane - x, y or z - centered around a system (current or user defined), which could also be open multiple times for a comprehensive view, or even stacked (coloured by plane)... the possibilities are quite large!

By now, as I'm still learning, and quite an amateur, I would love to have some help in having a working routine which create a list of stars under a specified radius. It should be made in a way that, after the first implementation, could be easily expanded and modified for shells, cubes and cubicals shells and filters (ex. star class). I tried to modify the StarDistance panel somewhat, but it seems beyond my current capabilities...

It seems a great project for the 10.x release. What do you think regard that?

**Comment by robbyxp1** [comment]
We need to create some dB searches to do that, then they can be added to the route planning UCs.  

Look at and play with 
GetSystemDistancesFrom(double x, double y, double z, int maxitems, double maxdist = 200, SQLiteConnectionSystem cn = null)

that features an SQL query to find systems within X distance from x/y/z (sphere)..

**Comment by andreaspada** [comment]
Thanks, @robbyxp1. I saw that GetSystemDistancesFrom is the responsible for the main functioning of the StarDistance panel. I already modified it somewhat, adding the inner (optional, with a default value of 0) and outer radius, so the same routine can be used for a sphere and a shell. I'll try to have a working prototype.

All the best!

**Comment by andreaspada** [comment]
PR #1569 addresses the first and second requirements, even if in a very inelegant way. As soon as they are already filtered, with its coordinates, it doesn't seems too difficult to have a small 2D and 3D map out from the nearest and in-range stars... I'll check for this.

**Comment by andreaspada** [comment]
@robbyxp1, how much difficult you think is ti have a panel similar to this mockup? Basically, with four views (three 2D, one 3D): X and Y plane, Y and Z plane, X and Z plane and an Othogonal view. 
The user should be able to select the maximum range, and probably a maximum systems numbers.
The yellow dot is the current system, the white are mapped, non-visited systems and the azure are mapped, already visited systems...

![mockup_starmap-panel](https://user-images.githubusercontent.com/4296635/34278707-a61c6038-e693-11e7-99d6-8ad8525e8e49.PNG)

**Comment by robbyxp1** [comment]
Closing, as your doing this!
