### ISSUE TITLE
unhandled UI exception with free voice control v1

### ISSUE THREAD

**Issue by Bynorix** [EDDiscovery/EDDiscovery#1558]
the error is happing if Free Voice control v1 is running/starting up. Setup Windows 10. Systemlanguage: German
Report:
There was an unhandled UI exception.

==== BEGIN ====
System.ArgumentException: Es wurde kein Erkennungsmodul mit der erforderlichen ID gefunden.
Parametername: culture
   bei System.Speech.Recognition.SpeechRecognitionEngine..ctor(CultureInfo culture)
   bei AudioExtensions.VoiceRecognitionWindows.Open(CultureInfo ctp) in C:\Code\EDDiscovery\Audio\VoiceRecognitionWindows.cs:Zeile 37.
   bei EDDiscovery.Actions.ActionPerform.ExecuteAction(ActionProgramRun ap) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionsEDDCmds\ActionPerform.cs:Zeile 116.
   bei ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionsCore\ActionRun.cs:Zeile 184.
   bei EDDiscovery.Actions.ActionController.ActionRun(ActionEvent ev, HistoryEntry he, ConditionVariables additionalvars, String flagstart, Boolean now) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:Zeile 524.
   bei EDDiscovery.Actions.ActionController.ManagerAddOns(Boolean manage) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:Zeile 390.
   bei EDDiscovery.EDDiscoveryForm.manageAddOnsToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:Zeile 1428.
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====

**Comment by Bynorix** [comment]
hotfix. Install the language packet for Englisch Great Britian(en-gb)

**Comment by robbyxp1** [comment]
Hi thanks for the report.. the packs are in english, so require that language to support them.

I'll patch it around.

Commit 800092455de4fd7859a524374806bd412f02f4cb fixes it.  It will not produce a warning - i'll update the VP later when its released to do that.
