### ISSUE TITLE
Warning - Frontier Name Acute not recognised by keyboard routines.

### ISSUE THREAD

**Issue by Stefanos42** [EDDiscovery/EDDiscovery#1559]
I did install 9.0.1.0 on WIN 10 and activated Voice control, I get following WARNING

Failed to load files
FreeVoiceControlV1:VoiceInput_Ship_Open:1654 Control binding not recognized

**Comment by robbyxp1** [comment]
This means that the code is not recognising your frontier key name.. probably a bug.

What key do you have that Ship Open orders mapped to?  You can find it either via the binding file (which is in appdata/local/frontier developments/elite dangerous/options/bindings/<mapfile>.binds) or via the ED game configuration menus.

My bet is the code is not dealing with the frontier name and converting it to windows properly.

	<OpenOrders>
		<Primary Device="Keyboard" Key="Key_O" />
		<Secondary Device="{NoDevice}" Key="" />
	</OpenOrders>

**Comment by Stefanos42** [comment]
that what I have 
	<OpenOrders>
		<Primary Device="Keyboard" Key="Key_Acute" />
		<Secondary Device="{NoDevice}" Key="" />
	</OpenOrders>

**Comment by Stefanos42** [comment]
<OpenOrders>
		<Primary Device="Keyboard" Key="Key_Acute" />
		<Secondary Device="{NoDevice}" Key="" />
</OpenOrders>

**Comment by Stefanos42** [comment]
After changing that the error disapear

**Comment by robbyxp1** [comment]
Acute.. thats not being dealt with.. i'll look into it. Thanks

**Comment by robbyxp1** [comment]
Hi again.

I'm trying to find out when Frontier writes Key_Acute to the binding file.  I can't reproduce this at the moment.  

What language/keyboard are you operating? Is it a special keyboard with extra keys, or just a standard 104 keyboard?

Thanks

**Comment by Stefanos42** [comment]
Hi, I have german keyboard using a ASUS Laptop .... WIN10
I dont know what keyboard layout is selected when I use E:D and EDDI
Have to check this at home..

**Comment by Stefanos42** [comment]
Can I help somehow to find t?

 

Von: Rob [mailto:notifications@github.com] 
Gesendet: Freitag, 22. Dezember 2017 09:17
An: EDDiscovery/EDDiscovery
Cc: Stefanos42; Author
Betreff: Re: [EDDiscovery/EDDiscovery] Warning (#1559)

 

Hi again.

I'm trying to find out when Frontier writes Key_Acute to the binding file. I can't reproduce this at the moment.

What language/keyboard are you operating? Is it a special keyboard with extra keys, or just a standard 104 keyboard?

Thanks

**Comment by robbyxp1** [comment]
Hi, Thanks for your help. 

I've put my keylogger program on github, at https://github.com/robbyxp1/KeyLogger/releases/tag/Release_1.0.0.  The source is right there for you to check.  If you don't want to run it its fine.  Or you can build it yourself using visual studio community edition.

When the program runs you can press keys and it shows you the scan codes of the keys you pressed.  Highlight an area and right click to allow it to be copied to the windows clipboard.

Try pressing that key, and tell me what keycode it decodes to in that program.

Example: Top row of my keyboard in English.

07954 KD Oem8            VN Backquote       keycode 223 sc:29 t:00 ---- None
08034 KU Oem8            VN Backquote       keycode 223 sc:29 t:C0 UD-- None
08929 KD D1              VN 1               keycode 49 sc:02 t:00 ---- None
08993 KU D1              VN 1               keycode 49 sc:02 t:C0 UD-- None
09218 KD D2              VN 2               keycode 50 sc:03 t:00 ---- None
09281 KU D2              VN 2               keycode 50 sc:03 t:C0 UD-- None
09489 KD D3              VN 3               keycode 51 sc:04 t:00 ---- None
09569 KU D3              VN 3               keycode 51 sc:04 t:C0 UD-- None
09793 KD D4              VN 4               keycode 52 sc:05 t:00 ---- None
09873 KU D4              VN 4               keycode 52 sc:05 t:C0 UD-- None
00081 KD D5              VN 5               keycode 53 sc:06 t:00 ---- None
00177 KU D5              VN 5               keycode 53 sc:06 t:C0 UD-- None
01073 KD D6              VN 6               keycode 54 sc:07 t:00 ---- None
01185 KU D6              VN 6               keycode 54 sc:07 t:C0 UD-- None
01505 KD D7              VN 7               keycode 55 sc:08 t:00 ---- None
01601 KU D7              VN 7               keycode 55 sc:08 t:C0 UD-- None
01809 KD D8              VN 8               keycode 56 sc:09 t:00 ---- None
01921 KU D8              VN 8               keycode 56 sc:09 t:C0 UD-- None
02113 KD D9              VN 9               keycode 57 sc:0A t:00 ---- None
02225 KU D9              VN 9               keycode 57 sc:0A t:C0 UD-- None
02497 KD D0              VN 0               keycode 48 sc:0B t:00 ---- None
02609 KU D0              VN 0               keycode 48 sc:0B t:C0 UD-- None
02849 KD OemMinus        VN Minus           keycode 189 sc:0C t:00 ---- None
02961 KU OemMinus        VN Minus           keycode 189 sc:0C t:C0 UD-- None
03169 KD Oemplus         VN Plus            keycode 187 sc:0D t:00 ---- None
03297 KU Oemplus         VN Plus            keycode 187 sc:0D t:C0 UD-- None
03537 KD Back            VN Back            keycode 8 sc:0E t:00 ---- None
03617 KU Back            VN Back            keycode 8 sc:0E t:C0 UD-- None

When Deutch selected:

06097 KD Oem5            VN Pipe            keycode 220 sc:29 t:00 ---- None
06177 KU Oem5            VN Pipe            keycode 220 sc:29 t:C0 UD-- None
07953 KD D1              VN 1               keycode 49 sc:02 t:00 ---- None
08033 KU D1              VN 1               keycode 49 sc:02 t:C0 UD-- None
08257 KD D2              VN 2               keycode 50 sc:03 t:00 ---- None
08337 KU D2              VN 2               keycode 50 sc:03 t:C0 UD-- None
08513 KD D3              VN 3               keycode 51 sc:04 t:00 ---- None
08593 KU D3              VN 3               keycode 51 sc:04 t:C0 UD-- None
08801 KD D4              VN 4               keycode 52 sc:05 t:00 ---- None
08881 KU D4              VN 4               keycode 52 sc:05 t:C0 UD-- None
09073 KD D5              VN 5               keycode 53 sc:06 t:00 ---- None
09153 KU D5              VN 5               keycode 53 sc:06 t:C0 UD-- None
09377 KD D6              VN 6               keycode 54 sc:07 t:00 ---- None
09441 KU D6              VN 6               keycode 54 sc:07 t:C0 UD-- None
09697 KD D7              VN 7               keycode 55 sc:08 t:00 ---- None
09777 KU D7              VN 7               keycode 55 sc:08 t:C0 UD-- None
00033 KD D8              VN 8               keycode 56 sc:09 t:00 ---- None
00097 KU D8              VN 8               keycode 56 sc:09 t:C0 UD-- None
00353 KD D9              VN 9               keycode 57 sc:0A t:00 ---- None
00449 KU D9              VN 9               keycode 57 sc:0A t:C0 UD-- None
00705 KD D0              VN 0               keycode 48 sc:0B t:00 ---- None
00801 KU D0              VN 0               keycode 48 sc:0B t:C0 UD-- None
01025 KD OemOpenBrackets VN OpenBrackets    keycode 219 sc:0C t:00 ---- None
01137 KU OemOpenBrackets VN OpenBrackets    keycode 219 sc:0C t:C0 UD-- None
01329 KD Oem6            VN CloseBrackets   keycode 221 sc:0D t:00 ---- None
01409 KU Oem6            VN CloseBrackets   keycode 221 sc:0D t:C0 UD-- None
01602 KD Back            VN Back            keycode 8 sc:0E t:00 ---- None
01681 KU Back            VN Back            keycode 8 sc:0E t:C0 UD-- None

**Comment by robbyxp1** [comment]
Looking at this keyboard https://www.ebay.co.uk/itm/IBM-ThinkPad-T430-Black-Windows-8-German-Layout-Replacement-Laptop-Keyboard/253230904481?hash=item3af5bcf4a1:g:cJ0AAOSwfVhZ9K3E

I see its next to backspace. But I would need to know the scan code that is mapped to.  My guess is Oem6.

**Comment by robbyxp1** [comment]
Actually, i've now managed to reproduce the bindings file with Acute on my machine, so there is no need to do the above.. i'll work on a solution. thanks

**Comment by robbyxp1** [comment]
This has pointed out that it needs a re-write to fix the fact that frontier encodes keys in language dependent manner in their bindings file.. i'll have to re-write

9.1 will have the fix

**Comment by robbyxp1** [comment]
9.0.2 will have it. PR #1587
