### ISSUE TITLE
Scan data panel mouseover

### ISSUE THREAD

**Issue by Zdeto** [EDDiscovery/EDDiscovery#1562]
Hi there!
Up until the latest updates, when I was hovering the mouse over a body in the scan data panel, the informations about them were shown. Now, I have to click on a body in order to display that. And it's a waste of time, click this, click out to close the informations, click again on another body, and so on... please return the mouseover feature! :)
Pretty please! :)

**Comment by iainross** [comment]
We've not taken them away and it's still working for me...

Are the other tooltips working still?

**Comment by andreaspada** [comment]
@Zdeto, they are working as expected for me too. By the way, they are the same of ScanGrid, so it worth to check if they work in the alternative scan panel...

**Comment by Zdeto** [comment]
Hi guys,

Other tooltips are working fine. Only in Scan Data won't work anymore. And yes, I can confirm that they work on Scan Grid, thanks for the tip @andreaspada ;)

**Comment by iainross** [comment]
Do you have it popped out and transaparent?  If it's in 'Fully transparent' mode then you won't get tool tips - maybe you accidentally toggled into a different transparency mode than normal?

**Comment by Zdeto** [comment]
@iainross nope, it's not popped out. It sits normally like the other panels.
![untitled-1](https://user-images.githubusercontent.com/34720764/34268424-4ca5a2a8-e689-11e7-9167-eb893df4a9d2.jpg)

**Comment by robbyxp1** [comment]
I'll check tomorrow. There has been mods to it which might have broke it.

**Comment by robbyxp1** [comment]
Tooltip hover over working for me on the scan grid

**Comment by Zdeto** [comment]
Well... for me it's not working. Maybe I will try a reinstall or I can use the Scan Grid panel as alternate since it's providing me with the information I'm looking for :)

**Comment by robbyxp1** [comment]
Don't reinstall

**Comment by robbyxp1** [comment]
It won't do anything..

[https://i.imgur.com/sgDs5jZ.png](url)

**Comment by robbyxp1** [comment]
this shows a hover over popout on the scan grid

**Comment by robbyxp1** [comment]
Sorry https://imgur.com/sgDs5jZ

**Comment by Zdeto** [comment]
It's ok, @robbyxp1, I trust you. Maybe something else is broken... I think tooltip malfunction happened about the same time I installed Windows 10 Creators Update, and since then, some weird things started to happen to my system.
Anyway, I'm glad I've posted this, because I found the alternate Scan Grid panel that gives me the info I need without clicking on bodies :)

**Comment by andreaspada** [comment]
@zdeto, I’m very happy you liked ScanGrid. It was my very first panel, as a learning project. If you have some request in regard, or some ideas, let me know.

Fly safe!
CMDR Spadino

**Comment by Zdeto** [comment]
@andreaspada great! :) If I came up with some requests or ideas about it, I'll let you know!

Fly safe too, o7!
CMDR Mixxed
