### ISSUE TITLE
[feature request] Voice command macro support Scan targets

### ISSUE THREAD

**Issue by theunkn0wn1** [EDDiscovery/EDDiscovery#1563]
Currently it seems the voice commands only support hitting a key and depressing it quickly after, unless im missing something obvious

My request is this: being able to issue a command such as "scan system" and have it hold down primary fire for 10 seconds so the horn can do its job. 
Basicially, i would like to be able to create a macro thats fired via voice that alllows for something like  the following psudocode:
```
press (mouse1, down)
wait(10000)  #in milliseconds
press (mouse1, up)
say("Done!")
``` 

edit: spelling

**Comment by robbyxp1** [comment]
Windows sadly does not allow me to press a joystick button.  It may allow me to simulate a mouse click. I'll have to investigate.

For now, you could also map primary fire to a key combination (Shift+X etc) and it will use that instead.

**Comment by theunkn0wn1** [comment]
I understand the joystick input limitations, and that was not quite what I was asking for. Sorry for the belated response, was saving a commander somewhere between our Galaxy and Adromeda. 

What I would like it the ability to *hold down*a key for a set period of time. I've already mapped primary fire to my keyboard yet it does not appear possible to trigger the Discovery Scanner from it as it receives a pulse when it expects a hold.

Merry Christmas,
Commander Theunkn0wn1

**Comment by robbyxp1** [comment]
hmmm may have thought of a clever way of doing this..

**Comment by theunkn0wn1** [comment]
Not sure how easy this would be too do at the software level, but my Razer keyboard sends keyDown separately from keyUp if I understand how it functions correctly.

Perhaps a clever way of doing it is to make the button press an async Task where the delay between keyDown and keyUp can be awaited.
If the user does not specify the delay use a default such as 50ms (iirc that's the default on my Razor)

That might require a significant rewrite of how the voice pack handles commands if it's callback/sync based. 

I'll be honest, I haven't had the opportunity to look into your codebase at all

**Comment by theunkn0wn1** [comment]
Woops, wrong button.

**Comment by robbyxp1** [comment]
9.0.3 will support a new "Scan System" command which will hold down the button for 6 seconds..

Had to make a change in the main program which thus requires the update.  9.0.3 will be next week.
