### ISSUE TITLE
Feat/Landable gravity

### ISSUE THREAD

**Issue by rhedrock** [EDDiscovery/EDDiscovery#1572]
Am I totally misreading the scan panel's landable body parenthetical gravity indicator or is the decimal misplaced? 

![image](https://user-images.githubusercontent.com/27317413/34313783-be32010c-e73b-11e7-8253-c858195b3733.png)

**Comment by klightspeed** [comment]
That looks like the conversion for the info box is also required for the
parenthesised value - the value from the journal is in m/s^2.

**Comment by iainross** [comment]
Fixed by #1566
