### ISSUE TITLE
Wrong planetary body G value (multiplied by 10)

### ISSUE THREAD

**Issue by TPRDroid** [EDDiscovery/EDDiscovery#1576]
I'm using version 9.0.1.0 on WIN 10 and after scanning it shows by the planet a gravity value 10 times higher than it should be. The correct value shows in the pop out ( see attached pic). I thought I got lucky finding a 20G planet!

![image](https://user-images.githubusercontent.com/31322660/34360897-09b2fffe-ea5d-11e7-97b9-d335ec3155fa.png)

Otherwise all seems to be working OK. Thanks.

**Comment by iainross** [comment]
9.81 times higher to be precise - the journal gives it in m/s/s and so division by 9.81 to give a multiple of earth standard is required and was forgotten for this caption.  Fix made and queued up for 9.0.2 which we should be able to get out this year...

**Comment by TPRDroid** [comment]
Many thanks for the quick reply Iain. Happy New Year to you!!
Cheers
Andy
