### ISSUE TITLE
[0.9.1] "Voice Recon did not stop" during shutdown

### ISSUE THREAD

**Issue by theunkn0wn1** [EDDiscovery/EDDiscovery#1581]
Issue: When attempting to close EDDiscovery an error box is displayed with the text
```
Voice audio problem
Voice Recon did not stop
```
When I click `OK` the shutdown is aborted.
Severity: Low, next shutdown attempt succeeds
Reproduciblity: Always
Version: 
- EDDiscovery 0.9.1 (Installer)
- Windows 10 x64 (Winver 1607)

Edit spelling

**Comment by robbyxp1** [comment]
This sometimes happens with windows, not much we can do, its been ordered to stop but it wont. Ignore for now.
