### ISSUE TITLE
9.0.1 keeps freezing

### ISSUE THREAD

**Issue by andrewhubb** [EDDiscovery/EDDiscovery#1582]
Since installing, 9.0.1 keeps freezing after running for a while. 
I have to keep using the task manager to kill all the eddiscovery processes and then relaunch. Which as a side note takes much longer to pass the logfiles than previous versions.

I'm running windows 10 64 Bit.

**Comment by mp1963** [comment]
I am experiencing the same thing but I also believe that whatever ED Discovery is doing is causing my ED to lag/slow down/stutter.

**Comment by andrewhubb** [comment]
I thought I was the only one with the freezing problem. I haven't noticed a lag on ED for me though.

**Comment by andreaspada** [comment]
I often experience that too. It's not consistent, however. There are many things happening during running time, so maybe some optimization are needed or, possibly, some fundamental changes in how thing are done.

**Comment by andrewhubb** [comment]
I Rolled back to 8.4.2.0. and deleted the databases now everything is back working without problems.

**Comment by mp1963** [comment]
Today ED would not drop from orbital flight until I closed the unhandled UI exception dialog box on ED Discovery. Am thinking that something is very broken here ?

**Comment by iainross** [comment]
@andrewhubb have you got some trace logs from the 9.0 sessions that were freezing?

@mp1963 have you got the CAPI enabled?  That's the only way we come close to interacting with the game itself (I've not seen reports of CAPI use slowing the game down but it's possible).

**Comment by klightspeed** [comment]
9.0 added voice recognition and sending input.  It's possible that the
method used to send input might have a negative effect on E:D.

**Comment by klightspeed** [comment]
Might also have to check how the config files are opened (should ideally be
read-only with at least read/write sharing), and how long and often they're
opened.

**Comment by SW4NS0N** [comment]
I'm seeing that EDD is hogging a little CPU but it's mostly harddrive i/o. Chugging on the hard drive.

**Comment by SW4NS0N** [comment]
Ok, I know that it takes a little time to sync the systems and info from EDSM, but am I only started playing E:D a couple weeks ago. Am I supposed to be syncing System data from EDSM from 2016? It's syncing System data from every 12 hours a day, every day since 2016. I didn't know if it's supposed to do that but that's whats causing the I/O hogging of my hard drive.

**Comment by SW4NS0N** [comment]
Ok, if we want to use this app, it looks like we need to start the app 20 minutes at least before we start the client. Unavoidable I guess but worth it.

**Comment by iainross** [comment]
@SW4NS0N - if it's the initial download from EDSM that's a one time thing.  If it's trying to sync flight logs you can turn it off in your commander's settings (it's only really useful if you lose your local flight logs or want to sync across multiple machines)

**Comment by klightspeed** [comment]
That syncing every 12 hours from 2016 sounds like the initial systems
download failed.

Perhaps we should look at failing the sync if the bulk download and insert
fails.

**Comment by robbyxp1** [comment]
if you don't install the voice recon pack, you pay zero penalty for the new feature.

**Comment by andrewhubb** [comment]
Since I've done a complete new install by deleting both the program and the database files, everything has been working fine.

@iainross Here are examples of the log files

[](url)
[logs.zip](https://github.com/EDDiscovery/EDDiscovery/files/1601973/logs.zip)

**Comment by robbyxp1** [comment]
Closing as thread finished
