### ISSUE TITLE
[feature request] Sync to INARA

### ISSUE THREAD

**Issue by moulesmariner** [EDDiscovery/EDDiscovery#1585]
Would there be any capacity to sync to INARA?

https://inara.cz/inara-api/

Loving how this project has evolved!

o7

**Comment by robbyxp1** [comment]
Its on the to-do list..

**Comment by jmelfi** [comment]
docs are already in #874

**Comment by iainross** [comment]
@finwen started working on it a while ago.

**Comment by robbyxp1** [comment]
This is well in progress, and i expect a Inara version of the code by early june.

**Comment by moulesmariner** [comment]
Rob,

This I am sure will be welcome news. Thanks for the efforts.
________________________________

**Comment by robbyxp1** [comment]
On master for 10.1
