### ISSUE TITLE
Estimated values appearing before scans

### ISSUE THREAD

**Issue by UnicycleBloke** [EDDiscovery/EDDiscovery#1586]
I jumped to a system deep in the black, and all the estimated values for the objects immediately appeared in EDSM. They were tagged in ED by another commander already, but I had obviously never scanned them myself. Anyone else seen this? I assume it is a bug. My guess is that the other commander is also using EDD or EDSM and that the data for the system was not properly filtered for me. Or, thinking about it, is this a feature?

**Comment by iainross** [comment]
There's an EDSM button on the tool bar for the scan panel you can use it to toggle whether you'll see data from EDSM or only your own scans.

The Estimated Values control, however, would appear to have a hardwired TRUE for the 'UseEDSM' parameter so it will always show you data from EDSM where it exists.

It should probably be a toggle here as well.

**Comment by UnicycleBloke** [comment]
Ah. Thanks. I've jumped to other systems with "discovered by" tags, but not noticed the estimated values appearing. I guess those systems are not in EDSM but only known to ED. I think you are right about making this feature optional.
