### ISSUE TITLE
Map Proposal: Focus on double-clicked system

### ISSUE THREAD

**Issue by klightspeed** [EDDiscovery/EDDiscovery#159]
What are your thoughts on double-clicking on a system to focus on it in the 3d map (as implemented in klightspeed@802b800)

**Comment by finwen** [comment]
No idea yet because i haven't had time to test it yet.

The idea is great.  would be nice to se name of a system on click to?

2016-04-02 8:38 GMT+02:00 Ben Peddell <notifications@github.com>:

**Comment by klightspeed** [comment]
Would you want the clicked system information to show up in the toolbar, in the status bar, or as a tooltip?

**Comment by klightspeed** [comment]
I have created pull request #160 based on this proposal.

**Comment by mwerle** [comment]
Sorry for late reply. Personally I'd vote against tooltip - invariably obscures the bit you're trying to look at.

**Comment by finwen** [comment]
I like your new mechanism allot.  Fun to see the name of the system. 

Maybe later we might show it in a little panel to left or right with more information if (available)  like stations  information about planets  and prospecting information.


BTW Klightspeed whats your in game  ED name?

**Comment by klightspeed** [comment]
My CMDR name is Bravada Cadelanne.

**Comment by mwerle** [comment]
Working great! In general the last couple of 3dMap updates have made the map MUCH more usable.
