### ISSUE TITLE
How do I turn off speach notice about systems or planets info in voice recognition plug-in.

### ISSUE THREAD

**Issue by tbtnsshshin** [EDDiscovery/EDDiscovery#1590]
How do I turn off the function to speak, such as the systems basic information, Fuel scoop etc...?
I just want to recognize and respond to voice commands and behave.
You don't need to read other information to tell us.
I can't find it in the configuration options of voice recognition.

So, If it's not in the option, please add an option to turn it off in configuration options of voice recognition.

**Comment by klightspeed** [comment]
Speech synthesis uses VoicePackV6, while speech recognition uses FreeVoiceControlV1

**Comment by tbtnsshshin** [comment]
Yes, I'm using VoicePack v6 and FreeVoiceControlv1 plug-ins in EDDiscovery 9.0.1.0

**Comment by klightspeed** [comment]
If you don't want speech synthesis, disable SpeechPackV6.

If you only want to disable certain parts of the speech synthesis, then delete or disable the events you don't want to hear.

**Comment by tbtnsshshin** [comment]
oh, I see. Thank you for your comment. 👍
