### ISSUE TITLE
Problem with the Route Tracker

### ISSUE THREAD

**Issue by Adrian2297** [EDDiscovery/EDDiscovery#1591]
**UPDATE**: Seems to be a bug, because as soon as I arrived at WP3 it showed me WP4 as next target and it worked perfectly fine from then on, only at WP6 was this issue reappearing and worked fine again as I arrived at WP7.
I also did a little bit of testing to find out what could be the cause of this problem, but it seems like it doesnt have to do with the way the WPs are arranged on the galaxy map, because I couldnt find anything special about their placement in my route.

**OLD PROBLEM-DESCRIPTION**:
Im having a little problem with the Route Tracker.
I set up an expedition and picked it in the set route option in the Route Tracker.
I then started flying from my starting point to the next waypoint set in the expedition, but
as I arrived nothing happend in the Route Tracker, it just shows me that its 0,00LY to WP2.
Is that a bug, do I have manually change to the next WP and how or do I have to change
something in my settings, so the route tracker changes the target to WP3 automatically?

![route tracker](https://user-images.githubusercontent.com/35138638/34610087-bec2e6c4-f21f-11e7-95e4-1381bcbefa4a.PNG)

**Comment by robbyxp1** [comment]
It needs a good rewrite and retest.. acknowledged.

**Comment by robbyxp1** [comment]
Speculative fix added for 9.0.2 but may not fix it.. let me know.

**Comment by CMDR-Cometborne** [comment]
Ran into the same issue with both 8.x and 9.0.3.  Will re-test with 9.0.4.

One good way to trigger the issue frequently is to use waypoints that just one jump apart.  In my cases, I had calculated routes for travels from/to Colonia using spansh.

**Comment by robbyxp1** [comment]
Still around Mr. Cometborne reports.. i'll have to think of a debug strategy

**Comment by CMDR-Cometborne** [comment]
Protocol of my last session:


WP | system | result |  
-- | -- | -- | --
1 | Eol Prou KK-V b17-18 | n/a |  
2 | Eol Prou SS-T d3-1279 | ok |  
3 | Eol Prou AU-R d4-763 | ok |  
4 | Eol Prou MR-W e1-107 | ok |  
5 | Eol Prou DU-R d4-439 | ok |  
6 | Eoch Pruae SZ-P d5-89 | ok |  
7 | Eoch Pruae KX-U e2-1951 | ok | fuel stop
8 | Eoch Pruae ZF-O d6-608 | stuck |  
9 | Eoch Pruae EM-M d7-1320 | ok |  
10 | Eoch Pruae KS-K d8-2377 | ok |  
11 | Eoch Pruae RD-T e3-109 | ok |  
12 | Eoch Pruae SD-T e3-2977 | ok |  
13 | Eoch Pruae XJ-R e4-1125 | stuck |  
14 | Eoch Pruae YE-H d10-1517 | ok |  
15 | Eoch Pruae ZE-H d10-373 | ok |  
16 | Eoch Pruae ZJ-R e4-1909 | ok |  
17 | Leamue ME-H d10-3022 | ok |  
18 | Leamue VQ-D d12-981 | ok |  
19 | Leamue XQ-D d12-278 | stuck |  
20 | Leamue CW-N e6-5400 | ok | fuel stop
21 | Leamue JY-Z d13-1423 | stuck |  
22 | Leamue DW-N e6-6130 | stuck |  
23 | Kyloarph BP-A d3305 | stuck |  
24 | Kyloarph FK-A d2074 | ok |  
25 | Kyloarph IV-Y d3191 | ok |  
26 | Kyloarph OB-X d1-4065 | ok |  
27 | Kyloarph TH-V d2-4849 | ok |  
28 | Kyloarph JL-Y e1272 | ok |  
29 | Kyloaln IC-V d2-1206 | ok |  
30 | Kyloaln LN-T d3-4165 | stuck |  
31 | Kyloaln UZ-P d5-2152 | ok |  
32 | Kyloaln WZ-P d5-3629 | ok |  
33 | Kyloaln BG-O d6-3665 | ok | fuel stop
34 | Kyloaln RD-T e3-5266 | stuck |  
35 | Kyloaln LS-K d8-4311 | ok |  
36 | Kyloaln NS-K d8-6760 | ok |  
37 | Kyloaln SY-I d9-8049 | stuck |  
38 | Kyloaln UY-I d9-2700 | ok |  
39 | Kyloaln ZE-H d10-8261 | stuck |  
40 | Kyloaln DQ-P e5-3920 | stuck | fuel stop, windows update
41 | Kyloabs UQ-D d12-410 | stuck |  
42 | Kyloabs YL-D d12-3168 | stuck |  
43 | Kyloabs DS-B d13-8001 | stuck |  
44 | Kyloabs CW-N e6-535 | ok |  
45 | Kyloabs KY-Z d13-6412 | ok |  
46 | Schee Flyi CF-A e4873 | stuck | fuel stop
47 | Schee Flyi CF-A e2576 | ok |  
48 | Schee Flyi LQ-Y d7713 | stuck |  
49 | Schee Flyi NQ-Y d1304 | stuck |  
50 | Schee Flyi OQ-Y d7022 | ok |  
51 | Agnairy AQ-Y d212 | stuck |  
52 | Agnairy FW-W d1-5597 | stuck |  
53 | Agnairy DL-Y e6991 | ok |  
54 | Agnairy EL-Y e8069 | ok |  
55 | Agnairy FL-Y e10096 | stuck |  
56 | Agnairy QC-V d2-1686 | stuck |  
57 | Agnairy GL-Y e4143 | stuck |  
58 | Agnairy XI-T d3-1733 | ok |  
59 | Agnairy MR-W e1-8083 | stuck |  
60 | Agnairy AJ-T d3-1185 | stuck |  
61 | Agnairy BJ-T d3-3244 | stuck |  
62 | Agnainks GR-W e1-2683 | ok |  
63 | Agnainks HR-W e1-7971 | ok |  
64 | Agnainks ST-R d4-1161 | stuck | fuel stop
65 | Agnainks AV-P d5-1525 | ok |  
66 | Agnainks DG-O d6-2648 | stuck |  
67 | Agnainks CV-P d5-4672 | stuck |  
68 | Agnainks CA-Q d5-6791 | ok |  
69 | Agnainks KB-O d6-4919 | stuck |  
70 | Agnainks LB-O d6-4474 | stuck |  
71 | Agnainks NB-O d6-3353 | stuck |  
72 | Hypoe Flyi OD-T e3-1460 | stuck |  
73 | Hypoe Flyi EH-M d7-3500 | ok | fuel stop
74 | Hypoe Flyi PD-T e3-6490 | stuck |  
75 | Hypoe Flyi QD-T e3-9885 | ok |  
76 | Hypoe Flyi MN-K d8-4138 | ok |  
77 | Hypoe Flyi RT-I d9-3098 | stuck |  
78 | Hypoe Flyi RY-I d9-402 | stuck |  
79 | Hypoe Flyi UT-I d9-5241 | ok |  

Journals:

[Journal.180202230755.01.log](https://github.com/EDDiscovery/EDDiscovery/files/1693435/Journal.180202230755.01.log)
[Journal.180203092829.01.log](https://github.com/EDDiscovery/EDDiscovery/files/1693436/Journal.180203092829.01.log)
[Journal.180203142549.01.log](https://github.com/EDDiscovery/EDDiscovery/files/1693437/Journal.180203142549.01.log)

**Comment by robbyxp1** [comment]
So i rewrote it, and we will have to see if it performs okay.  it certainly did with all the tests i did.

**Comment by daniel-finger** [comment]
As I have the same Problem, i am very excited about a Bugfix. This is **the** killer Feature for people playing in VR (I imported my Neutron Highway Route to Sagittarius A* and use a Voice command to insert the current Clipboard entry)
Is the a Beta version to try or an ETA to the next version?

**Comment by klightspeed** [comment]
You can try the latest snapshot from <https://ci.appveyor.com/project/eddiscovery/eddiscovery/build/artifacts>
