### ISSUE TITLE
Problem with community goal reporting

### ISSUE THREAD

**Issue by AntumArk** [EDDiscovery/EDDiscovery#1599]
I am experiencing performance issues due to constant updating of community goal which I have participated in but still haven't redeemed rewards. 
![image](https://user-images.githubusercontent.com/23199497/34651366-17630c3c-f3d8-11e7-9088-49db458e3d3b.png)

**Comment by phroggster** [comment]
As I've recently ventured back into the bubble and enrolled in the current two CGs, I've noticed the same. It's not a performance issue (nothing slows down as a result of it; journal DB size increase is reasonable), but the voice pack will sit there (sometimes once, sometimes repeatedly for minutes on end, depending on the triggering event) listing off the same two CGs for just about every other event that occurs.

It's possible to filter out the CG entries from the history view, but the voice pack isn't responsive to this filter. I don't want to delete the voice pack lines, as it's nice to have verbal confirmation when signing up for a CG. However, the repeated CG journal entry/entries for every jump, scan, dock, undock, etc. events *can* be quite tiresome.

Maybe only show/trigger for the first appearance of a particular CG in the journal (when signing up for it), and when cashing in at the end, ignoring every other update event in between?

**Comment by phroggster** [comment]
Here's a couple of journals with the excessive CG events (see event type: CommunityGoal): [Journal.180106050302.01.log](https://github.com/EDDiscovery/EDDiscovery/files/1612119/Journal.180106050302.01.log) and [Journal.180107040237.01.log](https://github.com/EDDiscovery/EDDiscovery/files/1612102/Journal.180107040237.01.log). Note in the first journal at `2018-01-06T11:37:38Z`, there are seven of these events logged within the same second!

Not sure if the CG journal spam is something new (I've been out of the bubble for some time), but, again, every one of these events triggers voice pack and adds a history entry (with only the CG names shown; none of the juicy details).

**Comment by robbyxp1** [comment]
Ok, I see it.. Lets assign it to VP

**Comment by robbyxp1** [comment]
VP 6.0.3 will screen it out, due out v.soon
