### ISSUE TITLE
UI Change: Move "status" panel to bottom of screen.

### ISSUE THREAD

**Issue by Red13x3** [EDDiscovery/EDDiscovery#16]
Synopsis: Move the "Status" box from the top left of the main screen to something a lot less prominent, like the bottom right or right at the bottom, stretched across the full width of the application window.

Reasoning: Yes, it is important... But does it really need to be at the very top and most important (visually) section of the main screen? Surely the user would be quite content with this status bar being at the bottom of the window, if they are really all that interested.

**Comment by Majkl578** [comment]
:+1:

**Comment by finwen** [comment]
I have thought of doing this too. Will test it later.

**Comment by Red13x3** [comment]
Please excuse the super-n00b questions!

I had a fish around and found what looks to be the UI code. I am super particular and would ideally like to change the order of a few things around. (And I'm getting some weird spacing to the bottom and right that only I seem to be getting.)  I've never work in a "collaborative" space like this.

1. What is the etiquette for taking on a section of the work and "owning it" to fix it up?
2. Or, if my changes are too freaky for the rest of the community, what is the process for "splitting off from the norm" and making my own "skin" for the app?
3. If I do this, then how do I ensure my "skin" works with any future updates created to the main functionality?
4. If I find the task too much for me (which is very easy to do!), am I able to get a paid-for developer to work on my behalf? (Like getting someone off Elance.com ?)
5. If I was to advertise on Elance, what language are we programming in, here? (Yes, I'm embarrassed to be even asking this question.)  What  tools/IDE does the programmer need to have to be able to publish changes, compile and test?

**Comment by finwen** [comment]
1. Anyone can fork the code or make a branch and develop whatever they want. 
    Good changes can later be merged back to EDDiscovery repository.

2. Fork in github and then you can do whaterver you want. 

3.  You can merge in updates from main repository but you probably have to solve some conflicts.

4. You are free to do whatever you want with your fork. 

5. Language: C#.  Need some version of git to get source code (I use tortoisegit mostly) . 
     IDE:   Visual studio 2013.   I use professional edition but the free  Visual Studio Community 2013  should work fine too.

**Comment by Red13x3** [comment]
Thanks for answering all those questions, Finwen.

>Moving Status -> I have thought of doing this too. Will test it later.

So can this Issue be "assigned" or marked to you in some way, so that I don't get developers looking to make updates for something you are already working on?

And in the future, for enhancements I would like to do, should I add them to my Fork only, or do I add them to the base trunk and then see if you or any of the community want it, first?

I'm only asking as I don't want to step on any toes, but also want to contribute to the overall project... If my ideas are good ones, of course I am happy for all here to benefit. Just don't want to waste your time or my money for that matter. :)

**Comment by Red13x3** [comment]
Oh, and what's the difference between a "Fork", a "Branch" and a "Pull Request" ?

**Comment by finwen** [comment]
Moved status to bottom.  Solved in 02080242273ccafa330a6925eb5ed4865b8d9bec

**Comment by Red13x3** [comment]
Hey Finwen, when is the next release of the software due, so I can test if this is done?
