### ISSUE TITLE
DirectSoundException when closing EDD

### ISSUE THREAD

**Issue by angrmgmt** [EDDiscovery/EDDiscovery#1603]
### Description
I clicked the 'X' in the top right corner.

### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
>   at CSCore.DirectSound.DirectSoundBuffer.Stop()
>   at CSCore.SoundOut.DirectSoundOut.CleanupResources()
>   at CSCore.SoundOut.DirectSoundOut.Dispose(Boolean disposing)
>   at CSCore.SoundOut.DirectSoundOut.Dispose()
>   at AudioExtensions.AudioDriverCSCore.Dispose() in C:\Code\EDDiscovery\Audio\AudioDriverCSCore.cs:line 127
>   at EDDiscovery.Actions.ActionController.CloseDown() in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:line 570
>   at EDDiscovery.EDDiscoveryForm.Controller_FinalClose() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 907
>===== END =====
>```

**Comment by phroggster** [comment]
What version of EDDiscovery are you running? #1437 is back...

**Comment by robbyxp1** [comment]
It looks older, it does not have line numbers in it @phroggster

**Comment by robbyxp1** [comment]
take that back!

**Comment by robbyxp1** [comment]
FinalClose is in UI thread.. Audio is run from UI thread... this may be a problem with the CSCore..

Lets put a Stop() in before displose at line 127 of CSCore.

**Comment by phroggster** [comment]
The 0x88780096 HResult means that it can't lock a buffer. It shouldn't be trying to lock any buffers unless something else is trying to play, so I think this needs help elsewhere.

I haven't torn into this since the redo, but can we notify the audio queues that we really want to shut down and everything must be stopped with no future items allowed to be added to the queue and only then shut down CSCore? In other words, I'm not sure if it's CSCore that's the problem or the queues are having things added while we've requested CSCore to stop. That, or a system shutdown already requested it to stop for us, or ...

**Comment by angrmgmt** [comment]
I'm running version 9.0.1.0

**Comment by angrmgmt** [comment]
I'm running 9.0.1.0, sorry for misclick on close...

**Comment by robbyxp1** [comment]
This is very hard to find, and is being monitored.  9.0.2 has a little patch to see if it helps.  closing for now

**Comment by angrmgmt** [comment]
Updated to 9.0.2.0, still happens on exit every time.  If it helps, I open EDDiscovery first, and close it last:

EDDiscovery -> VoiceAttack -> ED Crosshair -> ED ToolBox -> Elite Dangerous

Those programs are closed in reverse order when I quit the game.  It's not even interfering with my experience with EDDiscovery (which is awesome, btw), but if you give the option to report... :)

### Exception Details:
>EDDiscovery v9.0.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
>   at CSCore.DirectSound.DirectSoundBuffer.Stop()
>   at CSCore.SoundOut.DirectSoundOut.CleanupResources()
>   at CSCore.SoundOut.DirectSoundOut.Dispose(Boolean disposing)
>   at CSCore.SoundOut.DirectSoundOut.Dispose()
>   at AudioExtensions.AudioDriverCSCore.Dispose() in C:\Code\EDDiscovery\Audio\AudioDriverCSCore.cs:line 130
>   at EDDiscovery.Actions.ActionController.CloseDown() in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:line 571
>   at EDDiscovery.EDDiscoveryForm.Controller_FinalClose() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 907
>===== END =====
>```

**Comment by klightspeed** [comment]
From #1700, this still appears to be happening.

**Comment by phroggster** [comment]
@angrmgmt Please fill out the anonymous survey located at https://www.surveymonkey.com/r/2RJSWK7 to help us try and nail down a potential cause for this.

**Comment by angrmgmt** [comment]
Done.

**Comment by robbyxp1** [comment]
Now trapped in 9.1
