### ISSUE TITLE
Enigma expedition not showing

### ISSUE THREAD

**Issue by Nikouyus** [EDDiscovery/EDDiscovery#1605]
On the expedition tab when i go to pick up an expedition it doesn't appear, all the other expeditions appear but not this one, is it me or it doesn't appear to everyone?

could anyone help me find this out I really want to go on that expedition...

**Comment by klightspeed** [comment]
PR #1596 should be in 9.0.2

**Comment by Nikouyus** [comment]
oh, thank you i didn't know
