### ISSUE TITLE
9.0.2 keeps saying there is an update ...

### ISSUE THREAD

**Issue by mp1963** [EDDiscovery/EDDiscovery#1608]
I have the "There is a new version" message despite running the latest 9.0.2. Am surprised no-one else has not reported this ?

**Comment by robbyxp1** [comment]
That was due to my typo, but it should be solved now? Still getting it. I just ran and it did not warn me.

**Comment by mp1963** [comment]
Ah ok. Haven't run it yet today. Will check shortly but I don't doubt you have sorted it :-)

**Comment by phroggster** [comment]
The initial 9.0.2 release was accidentally marked as 9.02. Since 02 is greater than 0.2, the update checker noticed a "newer" version, even though it was up to date.

The release version number has since been corrected, so this should be resolved as Robby noted above.
