### ISSUE TITLE
3dMap - keyboard controls work even when window does not have focus

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#161]
The 3dMap responds to keyboard controls even when another Window has focus (eg, me typing this bug-report affects the map).

Steps to reproduce:
Open 3dMap
Switch to another program (eg, Notepad)
Type keys which correspond to the 3dMap controls (wasd etc)

**Comment by klightspeed** [comment]
This probably needs the keyboard handling and/or rendering loop to be suspended when the window is deactivated.
