### ISSUE TITLE
EDDiscovery status "Not Responding" frequently

### ISSUE THREAD

**Issue by hairagon** [EDDiscovery/EDDiscovery#1620]
I use the sqlite database for filtering out events for a statistical piece of software I have written. Read only with no locks.
Since installing latest EDD 9.0.2.0 the EDD application often shows "not responding". Taking 9.0% or so CPU, plenty to spare. Occasionally it springs to life, but goes into a coma soon after.

have 103K rows in the sql database, windows 10.
Thoughts on how to alleviate this?

**Comment by phroggster** [comment]
Without knowing what your client app does, best I could say I to check over the [commit log](https://github.com/EDDiscovery/EDDiscovery/compare/Release_9.0.1...Release_9.0.2), see if there's anything that might be interfering. I haven't seen any differences when using SQLiteBrowser in a similar fashion, and the overall feeling is that the EDSM dB transactions in 9.0.2 are quicker.

**Comment by robbyxp1** [comment]
We have not played with the bottom parts of the SQL bits of this really for months, so I can't think why it would be behaving differently.  

The only thing I did was to hold a transaction when an EDSM ID update is being performed on the user db, but the time that takes is small per transaction.

**Comment by robbyxp1** [comment]
Which DB are you using? If its the system one, you could delete it - sometimes the SQL DBs do get screwy.  The user one could also be regenerated as long as you have all the logs..

**Comment by hairagon** [comment]
Ok thanks all for your rapid contributions. My application was not the issue as no locks were taken. A review of the EDDiscovery logs did show that a great deal of time was spend processing logs (?) I only have journals so assumed other items being referred to.
I went into the settings and disabled the EDSM etc. interfaces as at one point I noticed 17 Million records had been accessed. There was a delay of around 10 minutes (at least) every time I changed one of my commander settings, it again doing something with logs or resolving systems.
Since I have no external links now the problem is solved - seems it was these causing the slowdown, possibly explaining why it stopped for 10 minutes, jumped into life for a minute or so, then set about processing external stuff again.
Again thanks for your time.

**Comment by hairagon** [comment]
Rob

Thanks for the response.
I was reading the EDDUser (Table Journal Entries) under the WAL protocol.

 

Problem now solved however by disabling all external connections such as EDSM.

 

Regards

 

CMDR ELF N'SAFETY

Twitch / twitter @hairagon

email: elite@cartmel.me.uk

**Comment by robbyxp1** [comment]
Hmm EDSM primarily hits the system db to populate it.  strange turning that off changed things.
