### ISSUE TITLE
gravity in system view 10 time the real one

### ISSUE THREAD

**Issue by StivlWrith** [EDDiscovery/EDDiscovery#1623]
I just see that there is a little problem with the gravity, but, like i am not good enough in english to explain, i put a picture
The gravity under the body picture is ten times the real one
![gravity](https://user-images.githubusercontent.com/32070483/34904420-b2988e9a-f845-11e7-994c-4570d78e1db9.png)

**Comment by klightspeed** [comment]
Duplicate of #1572

**Comment by phroggster** [comment]
This should have been fixed in [9.0.2](https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_9.0.2). Please update, or let us know if you're already using [9.0.2](https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_9.0.2).
