### ISSUE TITLE
[9.0.3] Unhandled GUI exception

### ISSUE THREAD

**Issue by theunkn0wn1** [EDDiscovery/EDDiscovery#1646]
### Description

I was alt-tabbed into Elite Dangerous at the time of the crash(i think), exact cause is unknown.
I submitted a single distance trilateration and alt-tabbed back into elite. When i alt-tabbed back out i was greeted with the fatal exception.

My appologies if this is not the most helpful issue report, but i genuinely do not have steps to reproduce

### Additional Information

EDD was running with CLI arguments.
```bash
PS I:\Program Files\EDDiscovery\EDDiscovery> .\EDDiscovery.exe -AppFolder I:\EDDiscovery\
```
![image](https://user-images.githubusercontent.com/3110986/35164219-6e9cc5d6-fcfe-11e7-9849-535ef3137b30.png)

### Exception Details:
>EDDiscovery v9.0.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ObjectDisposedException: Cannot access a disposed object.
>Object name: 'CellEditControl'.
>   at System.Windows.Forms.Control.CreateHandle()
>   at System.Windows.Forms.Control.get_Handle()
>   at System.Windows.Forms.Control.PointToScreen(Point p)
>   at ExtendedControls.AutoCompleteTextBox._cbdropdown_DropDown(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\Controls\AutoCompleteTextBox.cs:line 218
>   at System.Windows.Forms.Form.OnActivated(EventArgs e)
>   at System.Windows.Forms.Form.set_Active(Boolean value)
>   at System.Windows.Forms.Form.WmActivate(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by phroggster** [comment]
Odd. Seems like it probably occurred from alt-tabbing while an auto-complete `DataGridView` column was calculating auto-complete values. I'll have to play around for a bit to recreate, but will probably get solved just by monitoring for unplanned disposals of the `CellEditControl`.

**Comment by robbyxp1** [comment]
no response.
