### ISSUE TITLE
Regexp to parse log files needs tweak

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#165]
Mostly a note to self so I don't forget; re pull request #141:

Regexp needs tweaking so last component (the flight mode) is optional.  Otherwise special systems (such as Training) are never matched, also the first time people enter LHS 3447 doesn't end up with the correct time.  It -may- affect other things in future, so best to fix.

This from a perl script I used to re-scan all my log-files:
`{(?<Time>\d{2}:\d{2}:\d{2})\} System:\d+\((?<SystemName>.*?)\) Body:(?<Body>\d+) Pos:( (?<TravelMode>\w+))?`

**Comment by klightspeed** [comment]
Can this be closed?

**Comment by mwerle** [comment]
No

**Comment by mwerle** [comment]
Now it can :)
