### ISSUE TITLE
Show number of displayed records (History and Journal tabs)

### ISSUE THREAD

**Issue by RedfoxCh** [EDDiscovery/EDDiscovery#1653]
While applying filters on the History and Journal tabs it would be quite helpful to see how many records are currently being displayed (e.g. "Displaying 1234 of 24888 records")

**Comment by robbyxp1** [comment]
Good idea, where to put it in the UI?

**Comment by phroggster** [comment]
"Displaying" as in currently visible on-screen, or presently loaded in the `DataGridView` if you were to scroll?

Also, there's also an older bug where *some* ("last *X* entries", maybe others) filters don't get applied to events that show up after the filter is applied. Probably need to get that resolved while working in a solution to this.

**Comment by RedfoxCh** [comment]
"X of Y records", where X are the number of records loaded/available in the grid *with applied filters* and Y the number of records *if no filter were applied*. "Displaying" could be left out entirely.

Displaying the info above the grid and next to the filter buttons would seem fitting. Considering the available horizontal space (on smaller screens/windows) the output might have to be shortened to sth like "1'234'567 records" or "1'234'567#".

**Comment by robbyxp1** [comment]
The tooltips on the filters have been improved to show totals, best we can do with limited UI space.

9.2

**Comment by RedfoxCh** [comment]
Looking fwd to this, thanks!
