### ISSUE TITLE
EDDSystem.sqlite is just too big

### ISSUE THREAD

**Issue by GraXXoR** [EDDiscovery/EDDiscovery#1654]
6GB and climbing....

I need a way to reduce the size of the database by deleting certain entries that I don't need to keep.
Module refits, NPC communications etc.
I don't want to just hide them because that doesn't reduce the size of the database.
I can delete one entry at a time, but I can't seem to delete multiple entries. This is a shame.

I am aware that they might be picked up again if I rescan, but since I have deleted most of the old journal logs, this will not be an issue for me...

I understand that having a bulk delete might be risky, but you could mitigate the risks with a shift right-click to enable the multi-delete or just have a "Are you sure ?" "Are you really sure?" option.

Also, I'm not that cool with writing raw SQL. one unnoticed slip and it could be a while before I realised I've deleted something important.

**Comment by iainross** [comment]
EDDSystem is the star database from EDSM, EDDUser is your journals and what not.

@robbyxp1 is working on a way to reduce the size of EDDSystem by only locally storing the sectors you're interested in.

**Comment by phroggster** [comment]
Meanwhile, you *can* presently hold down <kbd>shift</kbd> while launching the application, then select the "Move Systems DB" to relocate the file to a different drive that has more storage available.

**Comment by robbyxp1** [comment]
Space is dominated by EDDsystems.  EDDuser is normally tiny up to it even if you have lots of entries in your history.  I don't think allowing deletions of records will make any difference.

On my system EDDuser is 31MB, Systems is 4755MB, meanwhile windows is 26GB.

I don't think on a modern computer that EDD sizes is anything out of the ordinary.

Please move the dB to another drive if your current drive is full.  9.1 will offer you the opportunity to reduce EDDsystems by unloading star data or not loading it at all.
