### ISSUE TITLE
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by Listatta** [EDDiscovery/EDDiscovery#1661]
### Description
comparing distance in the rout finder

### Exception Details:
>EDDiscovery v9.0.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   at ExtendedControls.AutoCompleteTextBox._cbdropdown_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\Controls\AutoCompleteTextBox.cs:line 228
>   at ExtendedControls.DropDownCustom._listcontrol_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\Controls\DropDownCustom.cs:line 69
>   at ExtendedControls.ListControlCustom.KeyDownAction(KeyEventArgs e) in C:\Code\EDDiscovery\ExtendedControls\Controls\ListControlCustom.cs:line 408
>   at ExtendedControls.AutoCompleteTextBox.AutoCompleteTextBox_KeyDown(Object sender, KeyEventArgs e) in C:\Code\EDDiscovery\ExtendedControls\Controls\AutoCompleteTextBox.cs:line 258
>   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
>   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
>   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
>   at System.Windows.Forms.Control.WmKeyChar(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.TextBox.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Thanks. I've protected the range in 9.1, no idea how it ever got out of range.
