### ISSUE TITLE
Integrate new az/al to compass screen

### ISSUE THREAD

**Issue by robbyxp1** [EDDiscovery/EDDiscovery#1668]
Shortly i'll push the action system events to master.  At which point the compass screen can subsribe to onUIEvent and get the az/al.

**Comment by robbyxp1** [comment]
Code is on master now, hook to UIPosition report via onNewUI.. in compass panel

**Comment by robbyxp1** [comment]
You can see a hook in Spanel

**Comment by iainross** [comment]
Cool, I'll have a gander this evening.
