### ISSUE TITLE
Statistics panel includes 'recall' as a landed event count

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1670]
Not sure if the previous report should be re-opened or simply start a new issue.  Anyhow, the situation still exists in 9.0.3
Original report;
https://github.com/EDDiscovery/EDDiscovery/issues/1438

Stat showing 5 landings 
https://i.imgur.com/glwrgvv.png

Main screen showing the 5 landings, with 2 of them being NPC controlled as seen by the zero co-ordinates
https://i.imgur.com/2QZrs9U.png

**Comment by iainross** [comment]
Fixed for 9.1
