### ISSUE TITLE
[9.0.4.0] Crash on Elite shutdown

### ISSUE THREAD

**Issue by Tigir** [EDDiscovery/EDDiscovery#1676]
### Exception Details:
>EDDiscovery v9.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: Current cell cannot be set to an invisible cell.
>   at System.Windows.Forms.DataGridView.set_CurrentCell(DataGridViewCell value)
>   at EDDiscovery.UserControls.UserControlStarList.AddNewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlStarList.cs:line 188
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 637
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 619
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 533
>===== END =====
>```

**Comment by robbyxp1** [comment]
Thanks you, found and fixed on 9.1
