### ISSUE TITLE
[9.0.4] Unhandled InvalidOperationException

### ISSUE THREAD

**Issue by Heavensburn** [EDDiscovery/EDDiscovery#1688]
### Description
Attempted to Set a Note from the Star List tab.

Happens with any system. RIght Click, choose Set Note. Nothing happens. ~10 seconds later the Exception window appears.

Screenshot attached.
![2018-02-02 23_20_56-eddiscovery version 9 0 4 0](https://user-images.githubusercontent.com/13399258/35765004-6b873a0c-0870-11e8-9221-3cc48bdb89a3.png)

### Exception Details:
>EDDiscovery v9.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: Current cell cannot be set to an invisible cell.
>   at System.Windows.Forms.DataGridView.set_CurrentCell(DataGridViewCell value)
>   at EDDiscovery.UserControls.UserControlStarList.AddNewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlStarList.cs:line 188
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 637
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 619
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 533
>===== END =====
>```

**Comment by robbyxp1** [comment]
Related to #1676 

The right click note is working on mine.  The crash shown above has already been fixed by 1676. This happened due to a hidden cell due to a search hide and the code was asking to set row[0] .  

Does it still not allow you to note edit?  I can't make mine not note edit.

**Comment by Heavensburn** [comment]
Hi Robby,

I just realized, the "Set Note" didn't popup because I had the row highlighted and clicked on the far-left column. That's perhaps why the "Go to Star on 3D Map" and "View on EDSM" are grayed out: 
![image](https://user-images.githubusercontent.com/13399258/35841556-7ab503e0-0ab1-11e8-8348-a152bd359e02.png)

Clicking on the row in any other column than the far-left column works correctly:
![image](https://user-images.githubusercontent.com/13399258/35841537-66098330-0ab1-11e8-84c9-f078cbb443a9.png)

Perhaps the "Set Note" option should also be grayed out like the "Go to Star on 3D Map" and "View on EDSM" when clicking on the far-left column?
