### ISSUE TITLE
EDSM credit reason unknown

### ISSUE THREAD

**Issue by grozeille** [EDDiscovery/EDDiscovery#1690]
![image](https://user-images.githubusercontent.com/129151/35771242-a5528660-0929-11e8-88ea-42fe039918e6.png)

That's too bad that there's no reason in the balance dashboard of EDSM, we have the event/description in the database (market sell, mission completed, refuel all)

**Comment by klightspeed** [comment]
EDDiscovery 9.1 will submit journal entries to EDSM, so the ledger on EDSM should correctly show the balance reasons.
