### ISSUE TITLE
UI Exception in UCSL due to whereami being null

### ISSUE THREAD

**Issue by Tigir** [EDDiscovery/EDDiscovery#1691]
### Exception Details:
>EDDiscovery v9.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlShoppingList.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlShoppingList.cs:line 245
>   at EDDiscovery.UserControls.UserControlSynthesis.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSynthesis.cs:line 269
>   at EDDiscovery.UserControls.UserControlShoppingList.InitialDisplay() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlShoppingList.cs:line 99
>   at EDDiscovery.Forms.PopOutControl.PopOut(Int32 ix) in C:\Code\EDDiscovery\EDDiscovery\PanelAndPopOuts.cs:line 292
>   at ExtendedControls.DropDownCustom._listcontrol_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\Controls\DropDownCustom.cs:line 67
>   at ExtendedControls.ListControlCustom.lbsys_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\Controls\ListControlCustom.cs:line 427
>   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
>   at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
>   at System.Windows.Forms.ListBox.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
The path i see is whereami = null, not last_he=null.

In normal code, whereami = "", then set from location,docked,starsystem,supercruise exit/entry

the only path i see for this is json itself has null in one of the entries it reads from.. 

Defending in JSONObjectExtension str() to return def if json returns a null

**Comment by robbyxp1** [comment]
Presume this will fix it, please report if it does not.
