### ISSUE TITLE
Invalid name for screenshots, plus sign is missing

### ISSUE THREAD

**Issue by Nishi** [EDDiscovery/EDDiscovery#1698]
I did few screenshots in BD+22 3878.
They were converted by EDDiscovery to PNG and stored in "BD22 3878", losing "+" from correct system name.

**Comment by klightspeed** [comment]
It looks like `StringObjectExtensions.SafeFileString()` is perhaps a little too defensive - it doesn't allow non-alphanumeric characters other than space, dash or underscore.

In reality, Windows doesn't allow the following characters in filenames: `\ / : * ? " < > |`

**Comment by robbyxp1** [comment]
Recoded in 9.1
