### ISSUE TITLE
SQLite Exception

### ISSUE THREAD

**Issue by Udomyr** [EDDiscovery/EDDiscovery#1699]
### Exception Details:
>EDDiscovery v9.0.4.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.Data.SQLite.SQLiteException (0x80004005): unable to open database file
>   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
>   at System.Data.SQLite.SQLiteConnection.Open()
>   at EliteDangerousCore.DB.SQLiteConnectionED`1..ctor(Nullable`1 maindb, Boolean utctimeindicator, Boolean initializing, Boolean shortlived) in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionED.cs:line 147
>   at EliteDangerousCore.DB.SQLiteConnectionUser.<>c.<Initialize>b__4_0() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionUser.cs:line 45
>   at EliteDangerousCore.DB.SQLiteConnectionED`1.InitializeIfNeeded(Action initializer) in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionED.cs:line 87
>   at EDDiscovery.EDDiscoveryController.Initialize(Action`1 msg) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 114
>   at EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:line 137
>===== END =====
>```

**Comment by klightspeed** [comment]
"Unable to open database file" from within `SQLiteConnectionUser` suggests your EDDUser.sqlite database is broken.
