### ISSUE TITLE
Feature Request: A search box for the Systems you have jumped to.

### ISSUE THREAD

**Issue by Red13x3** [EDDiscovery/EDDiscovery#17]
Synopsis:  Almost every modern app these days has a "Search" facility.  We need to be able to Search, at a minimum, in the System name field and the Notes field. 

Reasoning:  You could use the Notes quite extensively... But then trying to find a note about a system or a pristine mining resource or a black hole... Anything... The user should be able to, in this day and age, the ability to filter the List based on the search criteria.

So, lets say the users has thousands of entries, and 3 of them have a note about containing a Black Hole.  The user enters "Hole" (case insensitive) into the Search box and upon hitting the Find button, the list is reduced to just those 3 records.  Clearing the Search box means you also clear any filter in place.

**Comment by finwen** [comment]
solved in  2.3.4  92f3137a6325d8efc1c478e90ad42d08eca00daf

**Comment by Red13x3** [comment]
Thanks Finwen... (Sorry again for the n00b questions)
So, were you already working on this, coincidentally, or was it relatively easy to fix so you just did it?

For the other Enhancements I have requested, I am looking into getting some developers off Elance.com to get them done quickly... How do I mark them as "being worked on" so that you (or anyone) wastes their time also fixing it?
