### ISSUE TITLE
[9.0.4] Enhancement - Rename Tab

### ISSUE THREAD

**Issue by Heavensburn** [EDDiscovery/EDDiscovery#1702]
Posted here after chatting with Robby on Discord. 

![image](https://user-images.githubusercontent.com/13399258/35841717-5252e24a-0ab2-11e8-8f36-22bcb440a190.png)
Add to the Tab right+click popup menu an  "Rename Tab" option, allowing users to change the name of the tab. 

Especially for highly customizable tabs, like Grid, having the ability to uniquely set the tab to the user's preferences would improve user workflow.

**Comment by robbyxp1** [comment]
Good idea.. have to see how to implement it.

**Comment by robbyxp1** [comment]
done
