### ISSUE TITLE
[9.0.4] Enhancement - Expedition -> Set Note 

### ISSUE THREAD

**Issue by Heavensburn** [EDDiscovery/EDDiscovery#1704]
On the Expedition view, the layout shows the system note: 
![image](https://user-images.githubusercontent.com/13399258/35841869-5cdcf9a2-0ab3-11e8-9e91-1dd4ce170642.png)

However, you cannot set the note from this view (you can only set a bookmark). Consider adding to the right+click popup menu "Set Note":
![image](https://user-images.githubusercontent.com/13399258/35841903-9a622fe0-0ab3-11e8-856d-f742185dfb70.png)

**Comment by robbyxp1** [comment]
This is really hard to do, since the expedition does not relate to the user history (its just a collection of star names), so all the code does not work with it which handles notes.  If I just bodged it, the rest of the system would not see the note changed.

Going to have to reject, sorry.
