### ISSUE TITLE
[9.0.4] Enhancement - Scan Data on System -> Move Position of Approx Value

### ISSUE THREAD

**Issue by Heavensburn** [EDDiscovery/EDDiscovery#1705]
Last one. :)

Screen space is expensive and with so many view that require width, I have a sidebar containing System Information, Scan Data on System and Nearest Stars.

However, I find with Scan Data on System, the Approx System Value still scrolls outside the viewable area. If possible, when you choose to Hide the Toolbar, could the Approx Value be moved to the left under the title (instead of disappearing). This is more meta data than a Toolbar option: 
![image](https://user-images.githubusercontent.com/13399258/35842215-93f53f9c-0ab5-11e8-97d4-37a8c9b9f0c8.png)

**Comment by robbyxp1** [comment]
Been fixed.
