### ISSUE TITLE
`3D Map` in route finder crashes

### ISSUE THREAD

**Issue by skwerlman** [EDDiscovery/EDDiscovery#1712]
### Description
After determining a route using the route finder, I clicked `3D Map`. That caused the issue as near I can tell.

### Additional Information
Graphic card: GTX 980
Driver: 390.77

### Exception Details:
>EDDiscovery v9.0.4.0 An unhandled fatal exception has occurred.
>```
>==== BEGIN ====
>System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>   at OpenTK.Platform.SDL2.SDL.GL.CreateContext(IntPtr window)
>   at OpenTK.Platform.SDL2.Sdl2GraphicsContext..ctor(GraphicsMode mode, IWindowInfo win, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
>   at OpenTK.Platform.SDL2.Sdl2Factory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
>   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
>   at OpenTK.Sdl2GLControl.CreateContext(Int32 major, Int32 minor, GraphicsContextFlags flags)
>   at OpenTK.GLControl.OnHandleCreated(EventArgs e)
>   at System.Windows.Forms.Control.WmCreate(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Not reproducable by me. Looks like something up with openGL.  Does it still happen.  It may just be a graphics driver glitch, are you up to date with your drivers?

**Comment by skwerlman** [comment]
I have a GTX 980, and I'm running driver version 390.77. I haven't seen any other issues related to my driver recently.

**Comment by skwerlman** [comment]
Yes, this still occurs.

I have a GTX 980 and driver version 390.77. I haven't had any issues related to my graphics other than this.

**Comment by klightspeed** [comment]
It looks like SDL2 is installed somewhere on your path, and OpenTK is using that.

**Comment by skwerlman** [comment]
How can I locate that install?

Do you need any specific info about SDL2, or do I need to remove it?

**Comment by klightspeed** [comment]
Confirmed exception by dropping the appropriate bitness SDL2.dll from https://www.libsdl.org/download-2.0.php into the executable's directory.

We need to add `Backend = PlatformBackend.PreferNative` to the toolkit options at https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/Program.cs#L38

**Comment by klightspeed** [comment]
Thinking about it, that fix may also fix the 3D map crash I saw ages ago on Linux.
