### ISSUE TITLE
Request: Habitable Region in Scan

### ISSUE THREAD

**Issue by IMBAtvMoley** [EDDiscovery/EDDiscovery#1713]
Is it possible for some setting where the range can be displayed in orbital period (e.g. 42D) instead of ls?

The orbit radius in ls isn't shown in the info screen, but orbital period is shown even before scanning.

The period can be calculated from radius and solar mass,

**Comment by iainross** [comment]
The orbit radius in AU is shown in the scan info as well as ls - and that is also shown on the sysmap before scanning so does that not give you what you want?

**Comment by klightspeed** [comment]
Perhaps switch between ls and AU for the habitable zone?  1 AU is approx. 500ls.
