### ISSUE TITLE
Feature Request - Notify if system is newly discovered in EDSM

### ISSUE THREAD

**Issue by voodoo-curse** [EDDiscovery/EDDiscovery#1716]
ED Market Connector displays a small icon next to the system name if you are the first user to report the system information. While not a perfect indicator that you are the first one to discover a system, it is a fairly reliable as many explorers report to EDSM in one way or another. 

Suggested implementation: Star icon on Scan panel OR System Information panel if EDSM reports a system is newly discovered.

**Comment by iainross** [comment]
We do record that, but it doesn't appear to be easily visible in the UI...

**Comment by Heavensburn** [comment]
What if an icon representing "First" was added to the Scan page? Viewability triggered by the "Show/Hide Body status icons" toggle:
![image](https://user-images.githubusercontent.com/13399258/36188064-5d927e20-10fe-11e8-91c8-30f59ca7e042.png)
Appears to have enough space even on the smallest planet images:
![image](https://user-images.githubusercontent.com/13399258/36188080-76e3e756-10fe-11e8-815f-336ffc41a9a3.png)

**Comment by Heavensburn** [comment]
EDSM doesn't provide a body-level API for firstDiscovery. System-level is offered only when EDDiscovery reboots through the the EDSMLogFetcher on startup (now coming from the https://www.edsm.net/en/api-logs-v1 API).

Related to: https://github.com/EDDiscovery/EDDiscovery/issues/359

**Comment by robbyxp1** [comment]
9.2 will show first discovery flag in name of star in sysinfo

**Comment by voodoo-curse** [comment]
10.0.4.0 implementation is perfect, thank you for your hard work
