### ISSUE TITLE
crash on attempt to close application using red X in upper right corner

### ISSUE THREAD

**Issue by bicarbon8** [EDDiscovery/EDDiscovery#1721]
### Description
attempted to close application while Elite Dangerous launcher was still open, but the Elite Dangerous client was closed. This resulted in a crash

### Exception Details:
>EDDiscovery v9.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
>   at CSCore.DirectSound.DirectSoundBuffer.Stop()
>   at CSCore.SoundOut.DirectSoundOut.CleanupResources()
>   at CSCore.SoundOut.DirectSoundOut.Dispose(Boolean disposing)
>   at CSCore.SoundOut.DirectSoundOut.Dispose()
>   at AudioExtensions.AudioDriverCSCore.Dispose() in C:\Code\EDDiscovery\Audio\AudioDriverCSCore.cs:line 130
>   at EDDiscovery.Actions.ActionController.CloseDown() in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:line 571
>   at EDDiscovery.EDDiscoveryForm.Controller_FinalClose() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 906
>===== END =====
>```

**Comment by robbyxp1** [comment]
Thanks, dup of 1722.

**Comment by phroggster** [comment]
@bicarbon8 Please fill out the anonymous survey located at https://www.surveymonkey.com/r/2RJSWK7 to help us try and nail down a potential cause for this.

**Comment by bicarbon8** [comment]
Survey completed; hope it helps :)
