### ISSUE TITLE
Issue when closing EDDiscovery CSCore issue

### ISSUE THREAD

**Issue by Plasma43** [EDDiscovery/EDDiscovery#1722]
### Description
Selected exit under the tools menu and it brought up an error after about 10 seconds of trying to close.

### Exception Details:
>EDDiscovery v9.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
>   at CSCore.DirectSound.DirectSoundBuffer.Stop()
>   at CSCore.SoundOut.DirectSoundOut.CleanupResources()
>   at CSCore.SoundOut.DirectSoundOut.Dispose(Boolean disposing)
>   at CSCore.SoundOut.DirectSoundOut.Dispose()
>   at AudioExtensions.AudioDriverCSCore.Dispose() in C:\Code\EDDiscovery\Audio\AudioDriverCSCore.cs:line 130
>   at EDDiscovery.Actions.ActionController.CloseDown() in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:line 571
>   at EDDiscovery.EDDiscoveryForm.Controller_FinalClose() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 906
>===== END =====
>```

**Comment by robbyxp1** [comment]
We know about this, and it seems impossible to patch.  I'm thinking its a cscore problem.  It only happens onse in a blue moon.  

Check cscore version

**Comment by robbyxp1** [comment]
Maybe set up a scenario with cscore built in for debugging and making it play a sound while closing

**Comment by phroggster** [comment]
@Plasma43 Please fill out the anonymous survey located at https://www.surveymonkey.com/r/2RJSWK7 to help us try and nail down a potential cause for this.

**Comment by robbyxp1** [comment]
This is occuring with other programs.. https://hydrogenaud.io/index.php/topic,82234.0.html
https://superuser.com/questions/573678/error-creating-directsound-buffer-error-code-88780096

I think its a random bug in the windows layer..  looking at the cscore code it occurs during a Stop.

Stop does:
DirectSoundException.Try(StopNative(), InterfaceName, "Stop");

Stop Native does:

InteropCalls.CalliMethodPtr(UnsafeBasePtr, ((void**)(*(void**)UnsafeBasePtr))[18]);

So its getting a bad result code from windows.  Now it may be that cscore is screwing around with UnsafeBasePtr.. More likely its an error from windows.

I've included CSCore in the project so you can trace into it, set up a repeating harness to open/close the system.. nothing

maybe the audio device was disconnected during use?

**Comment by klightspeed** [comment]
CSCore's DirectSoundOut doesn't catch or test for the BUFFERLOST status, and therefore the `Dispose` errors out.

When this error occurs during shutdown, I think the best course of action is to catch and log it, then let process destruction take care of the dangling WASAPI session (Vista and later emulate DirectSound using WASAPI).

I wonder whether the `WaveOut` or `WasapiOut` implementations would be better behaved?

**Comment by robbyxp1** [comment]
I tried those before settling on DirectSound.. there was a reason.. i'll have to remember.
