### ISSUE TITLE
bug 3d map view v3.0.4.0

### ISSUE THREAD

**Issue by moulesmariner** [EDDiscovery/EDDiscovery#173]
3d map view no longer filters on history when displaying path traveled, its now all or nothing

**Comment by finwen** [comment]
Actually it was a bug. Thanks plan is to have time selection for the 3d
graph inside the graph form soon.
Den 8 apr. 2016 19:22 skrev "moulesmariner" <notifications@github.com>:
>
> 3d map view no longer filters on history when displaying path traveled,
its now all or nothing
