### ISSUE TITLE
Make bookmark user panel

### ISSUE THREAD

**Issue by robbyxp1** [EDDiscovery/EDDiscovery#1733]

**Comment by iainross** [comment]
Already started on that

**Comment by robbyxp1** [comment]
Thoughts.. bookmark form, make a data grid view entry at the bottom to show and edit planetary bookmarks

On the user control bookmark panel, click on edit to go to bookmark form for editing.

I'm going to enhance action language to:
Allow add/remove/edit of bookmarks
download a bookmark file from the github eddiscoverydata repo.. and be able to read that file and update bookmarks (+/- bookmark list)
then we can do a DW3304 action program, which pulls the latest bookmark list from the server and updates/deletes bookmarks accordingly!

**Comment by robbyxp1** [comment]
Change 3dmap to distinguish between system bookmarks and ones with planetary positions.

**Comment by andreaspada** [comment]
Awesome!

**Comment by robbyxp1** [comment]
Done thanks to Iain.
