### ISSUE TITLE
Sorting in Star list by visits results in incorrect ordering

### ISSUE THREAD

**Issue by Pichu0102** [EDDiscovery/EDDiscovery#1741]
If you click to sort the Star list by visits, it has issues with double digit visit counts, as seen in the attached screenshot.
![screenshot 3878](https://user-images.githubusercontent.com/4944941/36449678-75bb9bd4-1659-11e8-8d18-0c318fc7dc2c.png)

**Comment by andreaspada** [comment]
Ok. I'm working on that panel for other things. I'll give it a look.

**Comment by klightspeed** [comment]
That looks like another column that needs `DataGridView.OnSortCompare` to be overridden (or a delegate attached to `DataGridView.SortCompare`) in order to perform a numeric sort - see #1261 for an example.

**Comment by andreaspada** [comment]
@klightspeed, yep! Thanks to pointing to an already solved case.

**Comment by andreaspada** [comment]
Fixed by #1746
