### ISSUE TITLE
Make a new splitter window, like the grid, with configurable number of splits

### ISSUE THREAD

**Issue by robbyxp1** [EDDiscovery/EDDiscovery#1745]
do a drop down menu, with icons, anchored somewhere (in travelgrid top area somehow over the top of it) to select:
1x1,1x2,1x3,1x4,2x1,2x2,2x3,2x4,3x1 etc..

Make the whole stuff configurable..

Of course this replicated grid functionality.

**Comment by andreaspada** [comment]
I suggest to simplify a bit. Make the UserControlHistory just a common UserControl, which reside in a grid. 
However, the Grid should be able to be better managed (auto docking of control to border, auto tiling, etc...)
Also, create a TabContainerControl, to be able to stack UserControls in tabs inside a grid.

**Comment by robbyxp1** [comment]
Maybe.. would have to make the grid much more capable.

My thoughts was a UserControlSplitter, which is like a grid, but with a configurable amount of splits.  Then UserControlhistory can be one of them instead.. but thats a reengineer for another day.

**Comment by andreaspada** [comment]
Exactly that! I was starting fiddling with programmatically creation and deletion of splits, to mimics the way history is now - quite useful, but constrained to a fixed layout... - with much more freedom. Than I stopped, as you said that a major overhauling of the guy was on its way.

To me, it seems that the whole layout could be almost totally user definable, using just a couple of containers - grid and tabs. By now, we can already put a grid inside a grid, as a main tab and as a popup. Having a tab container, would free more screen spaces, yet give a more organized placement - stack similar panel one on top of the other (materials, synthesis... | commodities, market)

So, we can choose a simple planning strategy, to avoid too much work at one time: 

1- let HistoryPanel be as the others UserControls. Let the user choose when and if display it. 
2 - create two simple split containers - horizontal and vertical - and let the user places them whenever they want, as it's now. Each split can receive a panel... we can use them as russian dolls, so a three panels layout could be simply created using an horizontal split panel and a vertical split panel as a panel's child.
______
|   | - |

Than, after a while:
3 - let child elements of grid to be docked to borders when reach a closeup range (say, 5px?). They then behave as splits panel child...
4 - create a combobox which let the user choose a predefined layout
5 - permit users to create user-layouts, which can be community exchanged...
6 - if needed, think on an autotiling behavior,

**Comment by robbyxp1** [comment]
Done
