### ISSUE TITLE
Feature Request - Filter 'Annotated' Journal Entries

### ISSUE THREAD

**Issue by DaddaTheButt** [EDDiscovery/EDDiscovery#1754]
Would like to the ability to just view journal entries that I've annotated (Note not 'blank')

Looked at field filters - a little non-intuitive (as a new user) as expected to see column titles to which conditionals could be applied, there is no Note field, and there is an 'Unknown' field (?)

**Comment by robbyxp1** [comment]
Yep, its a known limitation. I'll have think.

**Comment by DaddaTheButt** [comment]
Feel free to close as a dup of #1505 (provided there's support there for 'not empty' as a criteria)

**Comment by robbyxp1** [comment]
Its done in 9.2, you can filter on Note.
