### ISSUE TITLE
GetEDSCSystems exception

### ISSUE THREAD

**Issue by muthan** [EDDiscovery/EDDiscovery#176]
Got an exeption in the loading console when I start EDDiscovery v2.7.6.0.

Didn't test if it does matter but it looks weird.

Here the output of the loading console:
```
EliteDangerous is not running .
Checking for new EDDiscovery maps
145 new systems from EDSM.
Reading travelhistory Checking for new distances from EDSM. 
Loading completed!
Get systems from EDDB. OK.
Found 1308 new distances.
GetEDSCSystems exception:Unterminated string. Expected delimiter: ". Path '[140343].security', line 1, position 42438656
```

**Comment by klightspeed** [comment]
This sounds like the JSON from EDSM was truncated after 42MB.

**Comment by AnthorNet** [comment]
Updated our container size because access.log are taking more and more space, even with th rotation!
Any way, dump are generated as we speak ;) So it's fixed.

**Comment by muthan** [comment]
seems to be resolved.
