### ISSUE TITLE
Unhandled UI exception. (EDD v9.1.2)

### ISSUE THREAD

**Issue by Gimi1967** [EDDiscovery/EDDiscovery#1761]
### Description
Dropped into Combat Aftermath USS when I saw this. Might have popped up earlier.

### Exception Details:
>EDDiscovery v9.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.StarScan.Process(IBodyNameAndID sc, ISystem sys, Boolean reprocessPrimary) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 423
>   at EliteDangerousCore.StarScan.AddBodyToBestSystem(IBodyNameAndID je, Int32 startindex, List`1 hl, HistoryEntry& he, JournalLocOrJump& jl) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 273
>   at EliteDangerousCore.HistoryList.AddJournalEntry(JournalEntry je, Action`1 logerror) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 811
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 463
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 444
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
>===== END =====
>```

**Comment by Gimi1967** [comment]
Not seen in 9.1.3 so far

**Comment by robbyxp1** [comment]
See #1763
