### ISSUE TITLE
9.1.3 An unhandled UI exception

### ISSUE THREAD

**Issue by rodan65** [EDDiscovery/EDDiscovery#1770]
### Description
<Not sure when event occured as was in VR. Am travelling through galaxy on deep space passenger mission. Basically just jump, system scan, planet / star scan anything exceptional >

### Exception Details:
>EDDiscovery v9.1.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   at EliteDangerousCore.StarScan.ProcessElements(JournalScan sc, ISystem sys, SystemNode sn, String customname, List`1 elements, ScanNodeType starscannodetype, Boolean isbeltcluster) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 736
>   at EliteDangerousCore.StarScan.Process(JournalScan sc, ISystem sys, Boolean reprocessPrimary) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 323
>   at EliteDangerousCore.HistoryList.AddJournalEntry(JournalEntry je, Action`1 logerror) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 797
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 463
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 445
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
>===== END =====
>```

**Comment by robbyxp1** [comment]
Try 9.1.4 it should be solved.
