### ISSUE TITLE
what is is about the eddiscovery installer 

### ISSUE THREAD

**Issue by Shazzsmifff** [EDDiscovery/EDDiscovery#1773]
everytime you release an update and I try to install it I get the same message "Windows cannot access the specified device, file, or path. you may not have the appropriate premissions to access the item".

it's strange how it found the device & path when i downloaded it and it even left me move it to another drive, so it must of found the exe file, and as for premissions it's my computer, I'm the only one that uses it (I've got full access). yet the EDDiscovery setup programe is the only one I have this problem with, I've tried turning of the windows defender, I've tried running it as an administor & it still wont let me run it (it took me hours last time as well, and the time before that )

**Comment by robbyxp1** [comment]
This is not a problem i've seen before. I'm not sure how to help.

**Comment by Nordlaw** [comment]
This happens to me when antivirus (AVG) thinks the file is suspect. It prevents you from executing it even in administrator mode. I report the file and then in a day or so the file gets checked and you can install it.

**Comment by robbyxp1** [comment]
Amusingly, virtustotal passes it past AVG and AVG says ok!

Closing as external problem
