### ISSUE TITLE
Feature Request: System 'history's from EDSM

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1786]
This is probably more for the voicepack, though it could also be shown in the S panel overlays.  I can envision a 'dedicated' S panel on my screen with a 30 sec or so timeout like the body scans.

When we arrive into a system, I think it would be great to know the following:
Cmdr's name that discovered it according to EDSM
When it was discovered - text would actual date, voicepack would be better with something like 3 days/weeks/months/over a year ago.
Name of the most recent visitor
When it was most recently visited (again, voice would be better converting to days/months ago)
Optionally, the ship types....not sure about this TBH.

Why?
I think it will add flavour, particularly when another Cmdr has passed through very recently.  Could lead to friend requests and unexpected meet ups.  The information is there in EDSM, but to be honest, I don't like alt tabbing out and updating to 'this' system....hence wanting EDD to tell me this stuff along with the number of stars and bodies like it does now :)

**Comment by robbyxp1** [comment]
Some of this may be unobtainable.. especially the EDSM stuff.  Don't think they feed us this.

**Comment by robbyxp1** [comment]
We are in negotiation.

**Comment by robbyxp1** [comment]
https://www.edsm.net/api-system-v1/bodies?systemName=Sol

Anthor is kindly supplying data..

**Comment by Disorganise** [comment]
Schweet :)

**Comment by robbyxp1** [comment]
Will be in the next version

**Comment by Disorganise** [comment]
Was this meant to be the 10.x series?  I didn't hear it and BP was pretty busy :)
