### ISSUE TITLE
9.1.4 Lag

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1787]
Pretty sure this is since 9.1.0, but EDD seems to be light for me now.  As in it'll fall behind a jonk or two.
Initially I thought it was the voicepack, but I noticed this morning that the S panel overlays was not updated either.  After the minute or so, it started to try to catch up (S panel updated, voice clipping to catch up).

I can't figure out what is triggering it as I'm on one screen and can't see the log.  I thought it was a star scan but later stars were fine.  In the 30 mins or so I get the play, it lagged 3 or 4 times.  One of those I tried to alt tab to the main window but it was unresponsive so I end tasked.

I did move the DB's from SSD to HDD a day or two before updating to 9.1 so if no one else is seeing this, I'm happy to try moving them back (Captains log had it's DB on the same drive and has no lag so I don't think it's a drive issue TBH)

**Comment by iainross** [comment]
Mine seems to be keeping up OK - but I do have everything on the SSD...

I don't use any voice packs, but the transparent panels I have are updating in a timely fashion.

**Comment by iainross** [comment]
I've seen it a couple of times tonight, jump into a new system and it takes 30-35s before EDD registers the jump.  I've not seen any kind of pattern to it yet - most times it's almost instantaneous.

**Comment by iainross** [comment]
Will hopefully be improved when we do #1825

**Comment by Disorganise** [comment]
*some* of my issues were self inflicted after all.  Turns out I was hitting a queue depth of 2 almost constantly on my disk.  Moved the EDD DB back to the SSD and queue depths dropped to almost zero across the board. Seems the EDD DB io had exceeded the iops capability of the disk :/

But.....
The lag does still exist, just not as pronounced/constant
