### ISSUE TITLE
Trilateration issue

### ISSUE THREAD

**Issue by zebs1** [EDDiscovery/EDDiscovery#1788]
Hi,

Issue: On the trilateration tab, click "Start new", then either "add 20 oldest" or "Add 20 newest", and get an error with the details below:

### Exception Details:
>EDDiscovery v9.1.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentNullException: Value cannot be null.
>Parameter name: source
>   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
>   at EDDiscovery.UserControls.UserControlTrilateration.AddWantedSystem(String sysName) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTrilateration.cs:line 1016
>   at EDDiscovery.UserControls.UserControlTrilateration.AddUnknownFromHistory(Boolean descending) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTrilateration.cs:line 462
>   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by iainross** [comment]
Hoq many systems are shown as Visited Without Coordinates?

**Comment by zebs1** [comment]
1564

**Comment by iainross** [comment]
Damn, was hoping you were going to say zero and I could tell you to leave that button alone ;)

Never seen that (and I use it all the time) - I'll see if I can work out what might cause it.  Is it a new in 9.1.x thing or have you not used it before?

**Comment by klightspeed** [comment]
`GetAllWantedSystems()` returns `null` when there are no wanted systems in the database, while #1672 assumed it always returned a list.

Unfortunately it's a bit of a catch-22, as the error is occurring in the very function that would add a system to the local wanted systems table.

**Comment by robbyxp1** [comment]
List<WantedSystemClass> dbCheck = WantedSystemClass.GetAllWantedSystems();
                if (dbCheck != null && dbCheck.Where(s => s.system == sysName).Any()) // if we have wanted systems in the DB... and its there..
                    return;

**Comment by robbyxp1** [comment]
Pushed to master

**Comment by zebs1** [comment]
Installed 9.1.6, and is now working. Thank you for the quick resolution!
