### ISSUE TITLE
9.1.4.0 Fatal Error on first start-up

### ISSUE THREAD

**Issue by DaftMav** [EDDiscovery/EDDiscovery#1789]
### Description
Installed 9.1.4 (exe version) over previous installation. Crashes on first start-up. Only gets as far to show the starting logo image.

### Exception Details:
>EDDiscovery v9.1.4.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.IO.FileLoadException: Could not load file or assembly 'CSCore, Version=1.2.1.2, Culture=neutral, PublicKeyToken=5a08f2b6f4415dea' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
>File name: 'CSCore, Version=1.2.1.2, Culture=neutral, PublicKeyToken=5a08f2b6f4415dea'
>   at AudioExtensions.AudioDriverCSCore.SetAudioEndpoint(String dev, Boolean usedefault)
>   at EDDiscovery.Actions.ActionController..ctor(EDDiscoveryForm frm, EDDiscoveryController ctrl, Icon ic)
>   at EDDiscovery.EDDiscoveryForm.Init(Action`1 msg)
>   at EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e)
>
>WRN: Assembly binding logging is turned OFF.
>To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
>Note: There is some performance penalty associated with assembly bind failure logging.
>To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
>
>===== END =====
>```

**Comment by klightspeed** [comment]
My guess is that CSCore.dll wasn't updated by the installer.

**Comment by DaftMav** [comment]
I downloaded the zip version, copied those files and now it works. Odd.

**Comment by robbyxp1** [comment]
Its in the installer.. tried again? Tried removed EDD completely and reinstall.
