### ISSUE TITLE
[9.1.5] Shopping list Exception

### ISSUE THREAD

**Issue by Uriei** [EDDiscovery/EDDiscovery#1798]
### Description
Trying to creating a Shopping List tab or opening the one it creates, it throws this every time.

### Additional Information
[Trace_20180301152930.0.log](https://github.com/EDDiscovery/EDDiscovery/files/1771502/Trace_20180301152930.0.log)

### Exception Details:
>EDDiscovery v9.1.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlShoppingList.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlShoppingList.cs:line 247
>   at EDDiscovery.UserControls.UserControlSynthesis.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSynthesis.cs:line 269
>   at EDDiscovery.UserControls.UserControlShoppingList.InitialDisplay() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlShoppingList.cs:line 102
>   at EDDiscovery.MajorTabControl.AddTab(PanelIDs id, Int32 tabindex) in C:\Code\EDDiscovery\EDDiscovery\MajorTabControl.cs:line 146
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
This should be fixed in 9.1.6 (#1792)
