### ISSUE TITLE
[9.1.5] Cannot send beta logs to EDSM

### ISSUE THREAD

**Issue by TalShaf** [EDDiscovery/EDDiscovery#1799]
When I try to sync with EDSM I get "Cannot send beta logs to EDSM". I've deleted my Beta logs and my Beta account no longer appears in the dropdown in EDD. I'm still getting the same message.

![edd](https://user-images.githubusercontent.com/30076917/36850066-09bca9c8-1d66-11e8-8475-67dab802dad2.png)

**Comment by klightspeed** [comment]
This suggests you moved some of your beta history to your main commander at some point.

**Comment by TalShaf** [comment]
How did I do that? And what can I do to fix it?

**Comment by robbyxp1** [comment]
Why don't we just reject the entry instead of dropping out of the loop
