### ISSUE TITLE
Feature Request: A System Setting that controls the method of updates to EDD

### ISSUE THREAD

**Issue by Red13x3** [EDDiscovery/EDDiscovery#18]
Synopsis:  Many programs have the option for configuring how Updates to the program are applied. EDD needs one, too.

Reasoning: Many people are quite nervous about allowing automatic updates, particularly because various instances of even Adobe getting caught with their pants down by releasing a rogue update.

EDD should have a drop-list setting in the Settings tab that controls how updates are managed:

1. Download and Install Automatically
2. Download only, inform availability
3. Inform user of updates only

If an update is available, a red circle with a 1 in it appears on the Settings tab title. In the settings tab, a button to allow downloading and installing of the upgrade as desired.  Updates should be downloaded to the default Downloads folder so they can be virus scanned and saved elsewhere for emergency rebuild, after install.

**Comment by finwen** [comment]
I am working in creating a separate installer.  Will be one step toward this.

The click once installer will update automatically like now  and the other parallell installer will not. But will probably check for a new version and ask for download.
