### ISSUE TITLE
[9.1.5] Missing name in most visited systems graph

### ISSUE THREAD

**Issue by TalShaf** [EDDiscovery/EDDiscovery#1800]
The graph showing my most visited systems is missing one name, as shows in this screenshot:

![visited](https://user-images.githubusercontent.com/30076917/36850177-51ae5f24-1d66-11e8-8c1c-b18b9d81ca1b.JPG)

**Comment by robbyxp1** [comment]
You been battling with Zarak Null?

**Comment by robbyxp1** [comment]
Can't reproduce..

**Comment by TalShaf** [comment]
Deleting my EDDuser.sqlite file and rescanning my logs seems to have fixed this issue.

**Comment by robbyxp1** [comment]
Maybe there were some systems without names? How? no idea.
