### ISSUE TITLE
data point scans misses one material earned

### ISSUE THREAD

**Issue by cosmoderp** [EDDiscovery/EDDiscovery#1802]
I have scanned several data points in my SRV.  Each time it would miss a single entry.  For example, if I got 3 things from the scan the summary would only list 2 and if I only got 2 I would see only a single entry of material acquired.  I tested like 10 times.  always one less.

**Comment by klightspeed** [comment]
If possible, please provide the journal events matching up with these scans so we can investigate.

**Comment by cosmoderp** [comment]
[events.txt](https://github.com/EDDiscovery/EDDiscovery/files/1773879/events.txt)


I took out 5 of these events for you and included a few items before and after.

**Comment by klightspeed** [comment]
Would it please be possible to show us where the entries are missing for those gathered data items?

**Comment by cosmoderp** [comment]
If you mean where I gathered those items it was at davs hope.
If you talking about placement withing the file just let me know to which user I should PM my journal file to in discord.  I am in your discord but mostly lurk.

**Comment by klightspeed** [comment]
Where in the EDDiscovery UI were the entries missing?

**Comment by cosmoderp** [comment]
the main summary one.... that shows all the log entries

**Comment by cosmoderp** [comment]
what more details do you need? I noticed it was labeled awaiting details and I provided you with the details.

**Comment by klightspeed** [comment]
Please take a screenshot showing the issue.

**Comment by cosmoderp** [comment]
never mind.  Seems to have been an ED bug.  Everything works as it should when I loaded up the game this time to test.
