### ISSUE TITLE
No Version No. Suffix on 'Portable.zip' file

### ISSUE THREAD

**Issue by DaddaTheButt** [EDDiscovery/EDDiscovery#1804]
Shown on SHA/MD5 but not applied to actual file.

**Comment by robbyxp1** [comment]
Thats just the way it's going to be for a while. I'm not going to do anything with that bit at the moment.

**Comment by DaddaTheButt** [comment]
That's fine - saw you'd applied <ver> to the .exe and thought you'd want a 'marker' that it could do with being done to the .zip at some point.
