### ISSUE TITLE
Synthesis crash

### ISSUE THREAD

**Issue by AArchAngel** [EDDiscovery/EDDiscovery#1805]
### Description
Set fsd synthesis wanted to 1. Then re filtered list to show materials needed at the top of the list then changed the wanted amount to 5 

### Exception Details:
>EDDiscovery v9.1.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlSynthesis.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSynthesis.cs:line 194
>   at EDDiscovery.UserControls.UserControlSynthesis.dataGridViewModules_CellEndEdit(Object sender, DataGridViewCellEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSynthesis.cs:line 317
>   at System.Windows.Forms.DataGridView.OnCellEndEdit(DataGridViewCellEventArgs e)
>   at System.Windows.Forms.DataGridView.EndEdit(DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave, Boolean keepFocus, Boolean resetCurrentCell, Boolean resetAnchorCell)
>   at System.Windows.Forms.DataGridView.SetCurrentCellAddressCore(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick)
>   at System.Windows.Forms.DataGridView.OnCellMouseDown(HitTestInfo hti, Boolean isShiftDown, Boolean isControlDown)
>   at System.Windows.Forms.DataGridView.OnCellMouseDown(DataGridViewCellMouseEventArgs e)
>   at System.Windows.Forms.DataGridView.OnMouseDown(MouseEventArgs e)
>   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.DataGridView.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Thank you. 9.1.6 will fix it.  Synthesis rows are not supposed to be sortable, you're supposed to click and drag them to order the preference.  Bug fixed.
