### ISSUE TITLE
Journal Entry - Materials Info, Mislabeling

### ISSUE THREAD

**Issue by DaddaTheButt** [EDDiscovery/EDDiscovery#1806]
See below for 'Category' header not ticking over from 'Manufactured:' to 'Encoded:'

(Would also (niggardly) query the consistency with respect to the summary panel showing
  Materials:7 Data:21
-v- Manufactured:5 Encoded:7, I can see the connection but had to look for it.)

Manufactured:5 Encoded:7 
Manufactured:
 Biotech Conductors, 2 items
 Electrochemical Arrays, 1 items
 Grid Resistors, 2 items
 Mechanical Components, 1 items
 Mechanical Equipment, 1 items
Manufactured:
 Irregular Emission Data, 3 items
 Anomalous Bulk Scan Data, 8 items
 Atypical Disrupted Wake Echoes, 2 items
 Divergent Scan Data, 1 items
 Anomalous FSD Telemetry, 1 items
 Classified Scan Databanks, 3 items
 Exceptional Scrambled Emission Data, 3 items

**Comment by robbyxp1** [comment]
Iain has updated the lists for 9.2
