### ISSUE TITLE
Virustotal again reports a trojan for release 9.1.5 ?!

### ISSUE THREAD

**Issue by CrtiUser** [EDDiscovery/EDDiscovery#1807]
Hello,

might be false alert, but also as 9.1.4 was reported as infected with a trojan ...

Anything serious?

EDDiscovery_9.1.5.exe -> 1 / 67 -> Yandex   Trojan.Miner!YfRgtToogUg

**Comment by robbyxp1** [comment]
it does. there is nothing we can do about it.  Its completely random,.

**Comment by klightspeed** [comment]
Sounds like some other random used Advanced Installer to create an installer for such a trojan.
