### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by lucasorsi** [EDDiscovery/EDDiscovery#1812]
I`m having the following error.

how to fix that?

An unhandled fatal exception has occurred.

==== BEGIN ====
System.Data.SQLite.SQLiteException (0x80004005): database disk image is malformed
database disk image is malformed
   em System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   em System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   em System.Data.SQLite.SQLiteDataReader.NextResult()
   em System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   em System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   em System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   em EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteNonQuery() na C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:linha 548
   em EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexesNoLock() na C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:linha 341
   em EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexes() na C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:linha 318
   em EDDiscovery.EDDiscoveryController.BackgroundInit() na C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:linha 564
   em EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() na C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:linha 506
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by klightspeed** [comment]
EDDSystem.sqlite is corrupt.

Please try deleting `%LOCALAPPDATA%\EDDiscovery\EDDSystem.sqlite`, and letting EDDiscovery re-build it.

**Comment by robbyxp1** [comment]
Hold down shift during program launch and there is an option for deleting systems db

**Comment by lucasorsi** [comment]
Ben,
Thank you!!

Delleting this file solve my problem.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>


Lucas Orsi
