### ISSUE TITLE
Route tracker problem still around

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDDiscovery/EDDiscovery#1815]
I am doing another neutron trip, and the route tracker problem described in #1591 is still around in 9.1.6.

![image](https://user-images.githubusercontent.com/25147462/36944616-adc793e8-1fa0-11e8-8ce0-74c38e16e508.png)

**Comment by robbyxp1** [comment]
I think its just a limitation of the algorithm which is used to decide if your in-front or behind your target star.  Does it continue wrong on the next jump?

If you give me the route (a2), and your position where this happened, i may be able to debug it.

**Comment by CMDR-Cometborne** [comment]
Route a2 contains:
Vegni RU-E d12-120
Vegni VF-D d13-95
Vegni UA-C d14-58
Ploea Aoc QS-A d1-19
Ploea Aoc SS-A d1-34
Ploea Aoc TS-A d1-3
Greeroi ME-X d2-6
Greeroi NE-X d2-26
Greeroi SK-V d3-18
Greeroi UK-V d3-12
Greeroi ZQ-T d4-13
Greeroi BR-T d4-9
Greeroi GX-R d5-6
Greeroi HX-R d5-2
Greeroi MD-Q d6-5

The issue happened at the first two waypoints, after that, I abandoned the route

**Comment by robbyxp1** [comment]
need to know what system you were at when it occurred to debug..

**Comment by robbyxp1** [comment]
Any info?

**Comment by robbyxp1** [comment]
Route tracker completely recoded for 9.2, with new 3d interpolation to track.
