### ISSUE TITLE
Bookmark deletion

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDDiscovery/EDDiscovery#1835]
Deleting multiple bookmarks is not possible at the moment.  If you select more than one bookmark, you get the nanny mode box for the first system, and only this system is deleted.  Please make the following changes:

a) allow deletion of multiple bookmarks in one go
b) add an option "do not ask again" to the nanny mode box "do you really want to delete this bookmark"?

**Comment by robbyxp1** [comment]
This is in the latest build.. Nanny box stays, but you can get rid of many for 1 nanny box!
