### ISSUE TITLE
SQLiteException after Save Route

### ISSUE THREAD

**Issue by thestyx** [EDDiscovery/EDDiscovery#1837]
### Description
I deleted one of my routes. Imported a new route from an exported EDSM file. And named the route the same as the one I deleted. After clicking on **Save Route** I got the following error :

### Exception Details:
>EDDiscovery v9.1.7.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.Data.SQLite.SQLiteException (0x80004005): constraint failed
>UNIQUE constraint failed: routes_expeditions.name
>   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
>   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
>   at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteNonQuery() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 548
>   at EliteDangerousCore.DB.SQLiteDBClass.SQLNonQueryText(SQLiteConnectionED cn, DbCommand cmd) in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteDBClass.cs:line 65
>   at EliteDangerousCore.DB.SavedRouteClass.Add(SQLiteConnectionUser cn) in C:\Code\EDDiscovery\EliteDangerous\DB\SavedRouteClass.cs:line 122
>   at EliteDangerousCore.DB.SavedRouteClass.Add() in C:\Code\EDDiscovery\EliteDangerous\DB\SavedRouteClass.cs:line 106
>   at EDDiscovery.UserControls.UserControlExpedition.SaveCurrentRoute() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlExpedition.cs:line 813
>   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by thestyx** [comment]
And the error persists through a restart. I assume that there is now some junk in the DB. If I slightly change the name of the route, i.e. putting a 2 at the end, everything works fine.

**Comment by phroggster** [comment]
We seem to only set the bool that says it's deleted instead of actually removing it from the database. Looks like a call to `SavedRouteClass.Delete()` is in order, at least when the route isn't loaded in from the well-known expeditions json.

**Comment by phroggster** [comment]
Until we get this resolved, what you could do to workaround this is:

* Right-click the combo box (where you would select the route name from).
* Undelete the route in question.
* Load the newly undeleted expedition.
* Give it a new name ("Expedition Name IWantYouToBeDeleted" or something; it's not important).
* Save it with the new name.
* Delete that expedition.

Then it'll no longer match the expedition name that has the correct systems, so you could get rid of the erroneous `2` that you had to add on to it.
