### ISSUE TITLE
Exception in imageWatcher

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#184]
Fresh OS install, fresh install of the game - I don't think I ran it yet.  Install EDD and run at the end of the install. 
message pop up:  Exception in imageWatcher: The directory name C:\Dave\Pictures\Frontier Developments\Elite Dangerous is invalid
Sure enough, directory does not yet exist - so this error will only likely occur if the game hasn't been run yet (or directory was moved) when EDD is first run

**Comment by robbyxp1** [comment]
Solved, in next push

**Comment by robbyxp1** [comment]
Will be solved in the 3dmap grid push
