### ISSUE TITLE
DistanceFromArrivalLS via edsm data?

### ISSUE THREAD

**Issue by PegasusRider** [EDDiscovery/EDDiscovery#1840]
For some systems that seem to be auto-explored in game or given information via navigational beacon EDDiscovery is not showing the above data. It is only showing it for systems I've personally surface scanned.

Which I almost understood until I went to edsm.net and saw that they do actually report that data, at least on their site and at least in some cases. (I checked Tiapalan, one I cannot surface scan, doesn't show the distance data in EDDiscovery, but does show it on edsm.net)

So, my query is:
Why is the data not being displayed if it is available either locally or via edsm?

**Comment by klightspeed** [comment]
`distanceToArrival` wasn't being translated from the EDSM body.

**Comment by PegasusRider** [comment]
That would certainly explain it. Many thanks.
