### ISSUE TITLE
Duplicate Material Names

### ISSUE THREAD

**Issue by MalikDama** [EDDiscovery/EDDiscovery#1844]
Some Materials have duplicate entries (with 0 listed inventory). Anomalous FSD Telemetry has 1 extra, and Focus Crystals has 3 extra entries as examples  (many have 1 or 2 extras). Maybe related to changes in id's from FD or issue generated from a bad version that i had to manual d/l from the site to fix.  Maybe this is something i can fix manually? Just tell me where to go if I can.  :)

**Comment by robbyxp1** [comment]
please provide some examples.. so we can track them down.

**Comment by MalikDama** [comment]
https://imgur.com/bLxRYh9

**Comment by klightspeed** [comment]
So the extra entries have a value of 0.

**Comment by MalikDama** [comment]
yes

**Comment by dlchung** [comment]
I'm seeing this issue on my end now as well. Not sure at what point it started.

[https://imgur.com/a/xa49i](url)
