### ISSUE TITLE
Report to EDDiscovery Team an unknown event.

### ISSUE THREAD

**Issue by incryptx** [EDDiscovery/EDDiscovery#1845]
Hello

I started to receive these in my flight logs from EDDiscovery. They are represented by Stars

I am at Eodgorsts OJ-Z b1-0 and have been flying through this sector for some time.

I started getting lots of them since leaving Pru Ain XF-B b2-0

Any ideas?

**Comment by klightspeed** [comment]
What version of EDDiscovery are you running?  If it's 9.0.x or 8.x, please try upgrading to 9.1.7

If you are already running 9.1.x, please give more information.
