### ISSUE TITLE
Unhandled Journal Event, Report to EDDiscovery team (Wing Mission)

### ISSUE THREAD

**Issue by cybit** [EDDiscovery/EDDiscovery#1848]
Hi,

 I just flew and completed a Wing Mission using EDDiscovery 9.1.4.0 .  I got the following Information in my Log.

Taking on the Mission:
> {
  "timestamp": "2018-03-15T22:53:08Z",
  "event": "CargoDepot",
  "MissionID": 345748781,
  "UpdateType": "WingUpdate",
  "StartMarketID": 0,
  "EndMarketID": 128666762,
  "ItemsCollected": 0,
  "ItemsDelivered": 0,
  "TotalItemsToDeliver": 594,
  "Progress": 0.0
}

Finishing the mission:

> {
  "timestamp": "2018-03-15T22:55:04Z",
  "event": "CargoDepot",
  "MissionID": 345748781,
  "UpdateType": "Deliver",
  "StartMarketID": 0,
  "EndMarketID": 128666762,
  "ItemsCollected": 0,
  "ItemsDelivered": 594,
  "TotalItemsToDeliver": 594,
  "Progress": 0.0
}

There is another entry about the completed mission which was parsed fine.

At a previous mission (where I actually was in a wing) I got the following unhandled messages:

> {
  "timestamp": "2018-03-15T20:27:07Z",
  "event": "CargoDepot",
  "MissionID": 345611770,
  "UpdateType": "WingUpdate",
  "StartMarketID": 128666762,
  "EndMarketID": 3228482304,
  "ItemsCollected": 0,
  "ItemsDelivered": 0,
  "TotalItemsToDeliver": 1424,
  "Progress": 0.0
}

( These got repeated while I was doing somthing else)
After taking up the first batch:

> {
  "timestamp": "2018-03-15T20:40:41Z",
  "event": "CargoDepot",
  "MissionID": 345611770,
  "UpdateType": "Collect",
  "StartMarketID": 128666762,
  "EndMarketID": 3228482304,
  "ItemsCollected": 238,
  "ItemsDelivered": 0,
  "TotalItemsToDeliver": 1424,
  "Progress": 0.167135
}

(This got shown repeatedly as well)
Then after first delivery:

> {
  "timestamp": "2018-03-15T20:51:26Z",
  "event": "CargoDepot",
  "MissionID": 345611770,
  "UpdateType": "Deliver",
  "StartMarketID": 128666762,
  "EndMarketID": 3228482304,
  "ItemsCollected": 238,
  "ItemsDelivered": 238,
  "TotalItemsToDeliver": 1424,
  "Progress": 0.0
}

(Again repeated...)
Wingmate took up the next batch:
> {
  "timestamp": "2018-03-15T21:44:43Z",
  "event": "CargoDepot",
  "MissionID": 345611770,
  "UpdateType": "WingUpdate",
  "StartMarketID": 128666762,
  "EndMarketID": 3228482304,
  "ItemsCollected": 958,
  "ItemsDelivered": 238,
  "TotalItemsToDeliver": 1424,
  "Progress": 0.505618
}

I took up the rest:
>{
  "timestamp": "2018-03-15T21:48:56Z",
  "event": "CargoDepot",
  "MissionID": 345611770,
  "UpdateType": "Collect",
  "StartMarketID": 128666762,
  "EndMarketID": 3228482304,
  "ItemsCollected": 1424,
  "ItemsDelivered": 238,
  "TotalItemsToDeliver": 1424,
  "Progress": 0.832865
}

(Again repeated)
Wingmate delivers one:

> {
  "timestamp": "2018-03-15T21:58:10Z",
  "event": "CargoDepot",
  "MissionID": 345611770,
  "UpdateType": "WingUpdate",
  "StartMarketID": 128666762,
  "EndMarketID": 3228482304,
  "ItemsCollected": 1424,
  "ItemsDelivered": 239,
  "TotalItemsToDeliver": 1424,
  "Progress": 0.832163
}

Wingmate delivers rest:

> {
  "timestamp": "2018-03-15T21:58:18Z",
  "event": "CargoDepot",
  "MissionID": 345611770,
  "UpdateType": "WingUpdate",
  "StartMarketID": 128666762,
  "EndMarketID": 3228482304,
  "ItemsCollected": 1424,
  "ItemsDelivered": 958,
  "TotalItemsToDeliver": 1424,
  "Progress": 0.327247
}

I deliver the rest:

> {
  "timestamp": "2018-03-15T22:04:43Z",
  "event": "CargoDepot",
  "MissionID": 345611770,
  "UpdateType": "Deliver",
  "StartMarketID": 128666762,
  "EndMarketID": 3228482304,
  "ItemsCollected": 1424,
  "ItemsDelivered": 1424,
  "TotalItemsToDeliver": 1424,
  "Progress": 0.0
}

(Shown twice)

**Comment by klightspeed** [comment]
Please upgrade to 9.1.7
