### ISSUE TITLE
Unknown module type StringLights

### ISSUE THREAD

**Issue by oohshiny** [EDDiscovery/EDDiscovery#1849]
Error received when sending ship to Coriolis

"Unknown Module Type
String Lights Coloured:string_lights_coloured"

Journal extract:

    {
      "Slot": "StringLights",
      "Item": "string_lights_coloured",
      "Priority": 1,
      "On": true
    },

**Comment by robbyxp1** [comment]
Put a tentative fix in for 9.1.8

**Comment by robbyxp1** [comment]
Should be fixed.. tested it.
