### ISSUE TITLE
unknow modules name while AFM Repair

### ISSUE THREAD

**Issue by lwt-pressy** [EDDiscovery/EDDiscovery#1852]
I found some  minor issues by module names not recognized in 9.1.8.0.

Here are the log events:
{
  "timestamp": "2018-03-19T20:38:55Z",
  "event": "AfmuRepairs",
  "Module": "$int_sensors_size5_class2_name;",
  "Module_Localised": "$Int_Sensors_Size1_Class1_Name;",
  "FullyRepaired": true,
  "Health": 1.0
}
{
  "timestamp": "2018-03-19T20:38:25Z",
  "event": "AfmuRepairs",
  "Module": "$int_lifesupport_size4_class2_name;",
  "Module_Localised": "$Int_LifeSupport_Size1_Class1_Name;",
  "FullyRepaired": true,
  "Health": 1.0
}
{
  "timestamp": "2018-03-19T20:38:02Z",
  "event": "AfmuRepairs",
  "Module": "$int_engine_size5_class2_name;",
  "Module_Localised": "$Int_Engine_Size2_Class1_Name;",
  "FullyRepaired": true,
  "Health": 1.0
}
{
  "timestamp": "2018-03-19T20:37:45Z",
  "event": "AfmuRepairs",
  "Module": "$int_buggybay_size2_class2_name;",
  "Module_Localised": "$int_buggybay_size2_class1_name;",
  "FullyRepaired": true,
  "Health": 1.0
}
{
  "timestamp": "2018-03-19T20:37:11Z",
  "event": "AfmuRepairs",
  "Module": "$int_fuelscoop_size5_class5_name;",
  "Module_Localised": "$Int_FuelScoop_Size1_Class1_Name;",
  "FullyRepaired": true,
  "Health": 1.0
}
{
  "timestamp": "2018-03-19T20:36:56Z",
  "event": "AfmuRepairs",
  "Module": "$int_hyperdrive_size5_class5_name;",
  "Module_Localised": "$Int_Hyperdrive_Size2_Class1_Name;",
  "FullyRepaired": true,
  "Health": 1.0
}
{
  "timestamp": "2018-03-19T20:36:50Z",
  "event": "AfmuRepairs",
  "Module": "$int_powerdistributor_size4_class5_name;",
  "Module_Localised": "$Int_PowerDistributor_Size1_Class1_Name;",
  "FullyRepaired": true,
  "Health": 1.0
}

**Comment by klightspeed** [comment]
That is odd - those Localised names are not localised, and they are also different to the unlocalised names.

**Comment by robbyxp1** [comment]
I think Howard is going to fix this on the next issue of the code (whenever that is) the non localisation..

**Comment by robbyxp1** [comment]
Its fixed in latest EDD
