### ISSUE TITLE
Two events of type DiscoveryScan with same time stamp, only first shows in History

### ISSUE THREAD

**Issue by vashts6583** [EDDiscovery/EDDiscovery#1853]
Upon landing in a system, I get an event with type "DiscoveryScan" for "discovering" the star, and another event once my ADS fully charges.  Normally, I see both events if they happen in different seconds.  However, if they happen in the same second, I only see the first event.

Please see events below copy/paste from journal and screenshot of History grid, and please let me know if you need more information.

{ "timestamp":"2018-03-20T02:17:24Z", "event":"DiscoveryScan", "SystemAddress":354326415971, "Bodies":1 }
{ "timestamp":"2018-03-20T02:17:24Z", "event":"DiscoveryScan", "SystemAddress":354326415971, "Bodies":13 }

![discoveryscan](https://user-images.githubusercontent.com/15353221/37632453-9df299a6-2bc4-11e8-9794-106230daa5d3.png)

**Comment by klightspeed** [comment]
The first event is when the ADS passively scans the immediate area.  This is where you see "5 New astronomical bodies discovered" in your info panel on the HUD.

The second event is when the ADS does an active scan.  This is where you see "32 New astronomical bodies discovered" in your info panel on the HUD.

**Comment by klightspeed** [comment]
It looks like the deduplication of history entries is erroneously removing the second entry.

**Comment by klightspeed** [comment]
Tracing issue:

Deduplication occurs at
https://github.com/EDDiscovery/EDDiscovery/blob/master/EliteDangerous/EliteDangerous/EDJournalMonitorWatcher.cs#L195, which would have only fired if the two entries were read in separate ticks.
This compares the JSON, and so should not have found a match.

If you used SQLiteBrowser to look at the JournalEntries table in the EDDUser.sqlite database, both entries should be there.

**Comment by vashts6583** [comment]
Only the one entry is in the JournalEntries table for that timestamp

**Comment by klightspeed** [comment]
Are there any messages in the trace log `%LOCALAPPDATA%\EDDiscovery\Log\Trace_*.log` around the time this entry would have been read?

**Comment by vashts6583** [comment]
Just a singe entry for DiscoveryScan:

[2018-03-20 02:17:17Z] New entry 3/20/2018 2:17:17 AM Music
[2018-03-20 02:17:17Z] Update sync flag ID 78230 with 2
[2018-03-20 02:17:17Z] Update journal ID 78230 with edsmid 23354827
[2018-03-20 02:17:17Z] Update sync flag ID 78230 with 3
[2018-03-20 02:17:22Z] New entry 3/20/2018 2:17:24 AM DiscoveryScan
[2018-03-20 02:17:26Z] New entry 3/20/2018 2:17:28 AM Music
[2018-03-20 02:17:38Z] New entry 3/20/2018 2:17:39 AM Scan

**Comment by vashts6583** [comment]
Once I'm done for the evening I'll run a re-scan and see if it pulls in the new entry

**Comment by klightspeed** [comment]
D'oh - inverted json equality test:
https://github.com/EDDiscovery/EDDiscovery/blob/master/EliteDangerous/EliteDangerous/JournalEntry.cs#L974
```
                            if (!AreSameEntry(ent, jent, entjo))
                            {
                                entries.Add(jent);
                            }
```

**Comment by klightspeed** [comment]
A re-scan should pull in the missing entry, even without that fix.
