### ISSUE TITLE
Exception - unknown reason though.

### ISSUE THREAD

**Issue by Acenoid** [EDDiscovery/EDDiscovery#1861]
Not sure what happened just noticed while playing elite. Might have happened much ealier.

### Exception Details:
>EDDiscovery v9.1.8.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>   bei EDDiscovery.UserControls.UserControlShoppingList.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlShoppingList.cs:Zeile 187.
>   bei EDDiscovery.UserControls.UserControlSynthesis.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSynthesis.cs:Zeile 274.
>   bei EDDiscovery.UserControls.UserControlSynthesis.Discoveryform_OnNewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSynthesis.cs:Zeile 157.
>   bei System.Action`2.Invoke(T1 arg1, T2 arg2)
>   bei EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:Zeile 465.
>   bei EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:Zeile 444.
>   bei EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:Zeile 184.
>===== END =====
>```

**Comment by Acenoid** [comment]
happening now constantly. Was doing a skimmer mission most recently and attacked some settlement.
Before that we did some wing trading.
I just checked EDD during the trading to compare markets. There it seemed in the beginning that the most recent market would not show up - probably because I travelled already a bit, before launching the application. Anyways later it seemed to work.

**Comment by klightspeed** [comment]
Seems to suggest the planet you are landed on has only been scanned without a detailed surface scanner, and so the scan has no materials.

**Comment by Acenoid** [comment]
uhm, but this should not cause such an error? I did not even do something in the edd program, just noticed that there is a dialog box in the background.

The planet is in the system 31 Beta Leonis Minoris (at volnov colony)

**Comment by iainross** [comment]
It's a bug in the shopping list panel/tab (sorry, I'm an explorer - never go anywhere without a DSS to the point I forgot you could) so if you've got such a control open then it will keep doing it.

**Comment by Acenoid** [comment]
Ok workaround: close shopping list panel for now then?

**Comment by iainross** [comment]
Yep, there's a fix lined up for the next patch - until that comes out only open the shopping list when you need to check it.
