### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CMDR-Drunkmonkeyy** [EDDiscovery/EDDiscovery#1864]
### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentNullException: Value cannot be null.
>Parameter name: key
>   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
>   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
>   at EliteDangerousCore.StarScan.FindSystem(ISystem sys) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 156
>   at EliteDangerousCore.StarScan.FindSystem(ISystem sys, Boolean useedsm) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 600
>   at EDDiscovery.UserControls.UserControlScan.DrawSystem() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlScan.cs:line 268
>   at EDDiscovery.UserControls.UserControlScan.Display(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlScan.cs:line 140
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 346
>   at EDDiscovery.UserControls.UserControlTravelGrid.AddNewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 247
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 645
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 627
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 533
>===== END =====
>```

**Comment by iainross** [comment]
@CMDR-Drunkmonkeyy what version of EDD are you running?  We fixed this a while ago, which doesn't mean you've not found a new way to get to it, but that's the first thing to check.

(latest is 9.1.8)

**Comment by CMDR-Drunkmonkeyy** [comment]
I am using 9.0.1.0.
Apparently I have other issues aswell seeing how the in-app update check says i have the most recent version.

**Comment by iainross** [comment]
Yeah, the check-for-update function was broken for a while.  Grab the latest and it'll hopefully be sorted.  Let us know how you get on...

**Comment by CMDR-Drunkmonkeyy** [comment]
Grabbed the latest version today. No errors! The problem was most likely my outdated version interacting with the up to date elite. Thanks for reading!
