### ISSUE TITLE
request: exploration tracker

### ISSUE THREAD

**Issue by gatekeeper258** [EDDiscovery/EDDiscovery#1866]
I'm looking for a way to track the estimated amount of money earned while exploring. is this possible?

**Comment by andreaspada** [comment]
Already implemented. 
- Stats Panel / Travel tab / Time: Summary / Last Dock / Scan Value

**Comment by gatekeeper258** [comment]
Omg thank you!!! Eddis can do so much it's confusing learning all the
things it can do. Thank you!!! I'm heading home to check it out now!!!!

**Comment by andreaspada** [comment]
You are welcome! Indeed, EDDiscovery is very capable. There are many things it can do, and which are already implemented in some way. I'm working on a new documentation repo, exactly cause many users aren't able to figure out how to do and how to look for.
I hope to have it usable soon...

All the best!

**Comment by gatekeeper258** [comment]
Are you the creator if eddis????? Wow! Thanks for responding to a mere
mortal cmdr!

**Comment by andreaspada** [comment]
No!!!!! Far from this. I'm just a contributing developer. The creator is @finwen. Current administrator is @robbyxp1, and there are a bunch of outstanding developers working in and contributing to EDDiscovery: currently @iainross , @phroggster and @klightspeed, beside me. I'm, for sure, the very least capable of them, by an huge factor.

As I'm not a professional coder (I'm a musician and luthier), I work on very small projects, for example taking on some side contribution, like the new documentation project. For example, my last code contribution are Plot and LocalMap, ScanGrid being my very first contributed panel. I'm learning to code while trying to implement things I feel need for, and I expect help and guidance from the big guys.

In respect to the Documentation, I certainly will create a FAQ section, and your question will be one of them, for sure! Thanks for being an EDDiscovery user!

See you in the dark!
