### ISSUE TITLE
3D map - unexpected mirroring

### ISSUE THREAD

**Issue by muthan** [EDDiscovery/EDDiscovery#187]
In my case I look at the 3D map so that Sol is right in front of my and Beagle Point Far on the other side. Now I grab the map with my mouse an pull it towards me so that it turns all the way to the other side without letting the map go or that is what I think should happen. But instead that I now have Beagle Point I front of me it is still Sol but the whole map is mirrored upside down.

when I let go the mouse inbetween the behaviour is as expected.

Hopefully it's clear enough what I mean. If not I can provide pictures.

**Comment by klightspeed** [comment]
Is this in the default orthogonal mode, or in perspective mode?

EDDiscovery doesn't limit the pitch axis, so one can turn the map upside-down if one pitches 180 degrees.  Orthogonal mode does not give visual cues as to how close or far away stars are, so pitching 180 degrees will appear to mirror the map upside-down.

**Comment by muthan** [comment]
it is default orthogonal mode

**Comment by RedfoxCh** [comment]
I suggest limiting the navigation in ordee to prevent 'flipping' the Galmap an its head.

Reasoning:
a) I can't think of any use for a 'flipped' view on the Galmap
b) In orhtagonal view this can be quite confusing (especially for new users)
c) That's the way the ED ingame Galmap works

**Comment by Red13x3** [comment]
+1  Totally agree. No need for it to be allowed to be flipped.

**Comment by klightspeed** [comment]
#218 should resolve this in 3.2
