### ISSUE TITLE
Missing materials collected events if a datapoint gives more than one type of data

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDDiscovery/EDDiscovery#1870]
If I scan a datapoint and get more than one type of data, ED Discovery misses one of the journal entries.  For example, my last scan of the beacon at Dav's Hope resulted in the following journal entries:

``{ "timestamp":"2018-03-26T21:54:36Z", "event":"DatalinkScan", "Message":"$DATAPOINT_GAMEPLAY_complete;", "Message_Localised":"Alert: All Data Point telemetry links established, Intel package created." }
{ "timestamp":"2018-03-26T21:54:36Z", "event":"DatalinkVoucher", "Reward":7019, "VictimFaction":"", "PayeeFaction":"Alliance" }
{ "timestamp":"2018-03-26T21:54:36Z", "event":"MaterialCollected", "Category":"Encoded", "Name":"scandatabanks", "Name_Localised":"Classified Scan Databanks", "Count":3 }
{ "timestamp":"2018-03-26T21:54:37Z", "event":"MaterialCollected", "Category":"Encoded", "Name":"consumerfirmware", "Name_Localised":"Modified Consumer Firmware", "Count":3 }
{ "timestamp":"2018-03-26T21:54:37Z", "event":"MaterialCollected", "Category":"Encoded", "Name":"encryptedfiles", "Name_Localised":"Unusual Encrypted Files", "Count":3 }
{ "timestamp":"2018-03-26T21:55:23Z", "event":"ModuleInfo" }``

The history window only shows two of the three materials:
![image](https://user-images.githubusercontent.com/25147462/37935681-bf49ca1e-3152-11e8-8737-5cbc970e0355.png)

**Comment by klightspeed** [comment]
That should be fixed with #1854 or with a journal re-scan.
