### ISSUE TITLE
Use Missions information to account for mission disappearing/killed

### ISSUE THREAD

**Issue by Tigir** [EDDiscovery/EDDiscovery#1872]
Mission list is not updating when killed and active missions are removed.

**Comment by robbyxp1** [comment]
Yes, we should triage the information using the Missions entry. Checking with FD exactly how this entry works.

**Comment by robbyxp1** [comment]
We should also complete all missions on kill

**Comment by robbyxp1** [comment]
Missions entry is not going to help.  I will just clear missions list on Kill.

**Comment by robbyxp1** [comment]
This is done on the tip.
