### ISSUE TITLE
3D map Fatal Error

### ISSUE THREAD

**Issue by Arkhorse** [EDDiscovery/EDDiscovery#1877]
### Description

Attempting to open a 3d map of route to Sagittarius A* (From SOL) 
### Additional Information

Im running the full IOBit/ Advanced system care suite. This is an issue with all new programs. (they cant access their own files) This is resolved by allowing the program to access it. This has already been done. Running as admin does not fix the issue.
### Exception Details:
>EDDiscovery v9.1.8.0 An unhandled fatal exception has occurred.
>```
>==== BEGIN ====
>System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>   at OpenTK.Platform.Windows.Wgl.Arb.ChoosePixelFormat(IntPtr hdc, Int32[] piAttribIList, Single[] pfAttribFList, Int32 nMaxFormats, Int32[] piFormats, Int32& nNumFormats)
>   at OpenTK.Platform.Windows.WinGraphicsMode.ChoosePixelFormatARB(IntPtr device, GraphicsMode desired_mode)
>   at OpenTK.Platform.Windows.WinGraphicsMode.SelectGraphicsMode(ColorFormat color, Int32 depth, Int32 stencil, Int32 samples, ColorFormat accum, Int32 buffers, Boolean stereo)
>   at OpenTK.Platform.Windows.WinGLContext.SetGraphicsModePFD(WinGraphicsMode mode_selector, GraphicsMode mode, WinWindowInfo window)
>   at OpenTK.Platform.Windows.WinGLContext..ctor(GraphicsMode format, WinWindowInfo window, IGraphicsContext sharedContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
>   at OpenTK.Platform.Windows.WinFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
>   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
>   at OpenTK.WinGLControl.CreateContext(Int32 major, Int32 minor, GraphicsContextFlags flags)
>   at OpenTK.GLControl.OnHandleCreated(EventArgs e)
>   at System.Windows.Forms.Control.WmCreate(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
Please check your 3D driver - the error suggests that the default Microsoft 3D OpenGL implementation is in use.

**Comment by Arkhorse** [comment]
Im not even to sure as to what you are talking about. "Check my 3d driver"? Do you mean check which one is in use? I have an AMD, which I am new to. So do please explain what you mean.

**Comment by robbyxp1** [comment]
Are you using the correct AMD driver for your video card..

**Comment by Arkhorse** [comment]
Yes. That was one of the things I checked. Always updated.

**Comment by robbyxp1** [comment]
Hmmm very hard to diagnose.  We are not getting multiple reports of this.  What is the graphics HW in question?

**Comment by Arkhorse** [comment]
It is a Radeon RX 480, 8GB.

**Comment by klightspeed** [comment]
What version of the [Radeon software](https://support.amd.com/en-us/download/desktop?os=Windows%2010%20-%2064) do you have installed?

What info does a tool such as [GL-Z](http://www.geeks3d.com/glz/) or [OpenGL Extensions Viewer](http://realtech-vr.com/admin/glview) give?

**Comment by Arkhorse** [comment]
The version is 18.2.2. 
![gl-z](https://user-images.githubusercontent.com/20694721/38214254-7430b6ee-369a-11e8-9776-5633091b9e12.png)

**Comment by robbyxp1** [comment]
Still got it? We are not having any reports of any problems with it, so it looks like your machine/driver combo

**Comment by Arkhorse** [comment]
Yeah, its still happening.

**Comment by robbyxp1** [comment]
Closing, we can't debug it, and there are no other reports of it happening.
