### ISSUE TITLE
No Installation Instructions

### ISSUE THREAD

**Issue by Trotsky21** [EDDiscovery/EDDiscovery#1880]
There do not appear to be any installation instructions either on the GitHub page for EDDiscovery, or within the files. There does not appear to be an installer in the file base.

**Comment by phroggster** [comment]
Double-click the installer, downloaded as an EXE file from the [releases](https://github.com/EDDiscovery/EDDiscovery/releases) page. It's built using different called "Advanced Installer" from the [Installer](https://github.com/EDDiscovery/EDDiscovery/tree/master/Installer) source folder.

Not sure what more you'd like to be documented, or are you just looking for the link to the installer (on the releases page)?

**Comment by Trotsky21** [comment]
Managed to install it. It logged 3100+ events and then stopped working. Nothing updates now.

**Comment by Trotsky21** [comment]
I attempted to install from the "portable" .zip version. This was probably incorrect. I deleted the install and reinstalled using the .exe installer, which was very smooth. After re-entering data in settings for the CMDR and the API key for EDSN, both EDD and EDSN updated to the present.

**Comment by klightspeed** [comment]
The portable zip is meant for a portable install, where the data sits in the same directory as the executable.
