### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by Imathil** [EDDiscovery/EDDiscovery#1883]
### Description
Traversing planetary surface, had compass open in a pop-out window. Had just landed on the planet when the error happened.

### Exception Details:
>EDDiscovery v9.1.8.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentNullException: Value cannot be null.
>Parameter name: source
>   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
>   at EDDiscovery.UserControls.UserControlCompass.PopulateBookmarkCombo()
>   at EDDiscovery.UserControls.UserControlCompass.OnNewEntry(HistoryEntry he, HistoryList hl)
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je)
>   at EDDiscovery.EDDiscoveryController.PlayJournalList()
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries)
>===== END =====
>```

**Comment by klightspeed** [comment]
This should be fixed by #1882
