### ISSUE TITLE
How to reset Add-on's ???

### ISSUE THREAD

**Issue by Lambeau-D** [EDDiscovery/EDDiscovery#1887]
I activated some add-ons and now the program crashes on start-up.
The free Voice Control starts and then I get a " EDDiscovery has stoped working" error.
Is there a way to reset these settings?
Uninstall and reinstalling DOES NOT work.

**Comment by klightspeed** [comment]
Please try deleting the files from `%LOCALAPPDATA%\EDDiscovery\Actions` - this will uninstall any installed action packs.

Getting a "Stopped working" window suggests that an exception occurred in a native thread - i.e. completely outside our control.

**Comment by robbyxp1** [comment]
Have you set a default microphone in the sound control panel...

**Comment by Lambeau-D** [comment]
Yup, did that.



Deleted the files in the appdata and reinstalled.
Problem solved.

 

Van: Rob [mailto:notifications@github.com] 
Verzonden: Sunday, April 1, 2018 15:25
Aan: EDDiscovery/EDDiscovery <EDDiscovery@noreply.github.com>
CC: Lambeau-D <andrew.christiaens@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [EDDiscovery/EDDiscovery] How to reset Add-on's ??? (#1887)

 

Have you set a default microphone in the sound control panel...

**Comment by Lambeau-D** [comment]
Deleted the files in the appdata and reinstalled.
Problem solved.

 

Van: Ben Peddell [mailto:notifications@github.com] 
Verzonden: Sunday, April 1, 2018 06:42
Aan: EDDiscovery/EDDiscovery <EDDiscovery@noreply.github.com>
CC: Lambeau-D <andrew.christiaens@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [EDDiscovery/EDDiscovery] How to reset Add-on's ??? (#1887)

 

Please try deleting the files from %LOCALAPPDATA%\EDDiscovery\Actions - this will uninstall any installed action packs.

Getting a "Stopped working" window suggests that an exception occurred in a native thread - i.e. completely outside our control.

**Comment by Lambeau-D** [comment]
Forgot to mention this:

There is something wrong with the ship detection.



I fly a Python, and EDDiscovery submit data to EDSM that I fly a Viper MkIV.

 

Van: Rob [mailto:notifications@github.com] 
Verzonden: Sunday, April 1, 2018 15:25
Aan: EDDiscovery/EDDiscovery <EDDiscovery@noreply.github.com>
CC: Lambeau-D <andrew.christiaens@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [EDDiscovery/EDDiscovery] How to reset Add-on's ??? (#1887)

 

Have you set a default microphone in the sound control panel...

**Comment by klightspeed** [comment]
The incorrect ship sounds like the journal event switching to that ship was not picked up by EDSM.  Try either clicking the EDSM button (to the right of the 3d map button near the top of the window) or uploading your journals to EDSM using its journal import.
