### ISSUE TITLE
3D map home system setting problem

### ISSUE THREAD

**Issue by bazza14** [EDDiscovery/EDDiscovery#1893]
Hi,
It is very tedious setting the home system as the input field only allows the inputting of a single character. For example if I want to enter Coalsack I input 'c' in the field and the drop down shows a list of systems beginning with 'c' which is what I would expect. If i now try to refine the list by entering the 'o' instead of the 'o' being appended to the 'c' and the displayed list showing systems beginning with 'co' the 'o' overwrites the 'c' and the drop down shows a list of systems beginning with 'o'.

**Comment by klightspeed** [comment]
What version?

**Comment by bazza14** [comment]
Hi,
Currently it's 9.1.8 but I've had the issue with all previous versions
(there have been about 5 updates since I started using it). I also
omitted to mention that it will often insert the text text Sol into the
input field after you press the second letter, but the drop down list
shows the list of systems beginning with the second letter. BTW thanks
for the programme, it is really helpful.

**Comment by iainross** [comment]
It's fixed in 9.1.9 so an upgrade should sort you out.

**Comment by bazza14** [comment]
Upgraded, pleased to confirm it is working as expected. Many thanks.
