### ISSUE TITLE
Statistics Panel, Scan Tab shows Belt Clusters as "Unknown"

### ISSUE THREAD

**Issue by vashts6583** [EDDiscovery/EDDiscovery#1897]
I have 16 entries listed as Unknown on Jan 5, 2018.  I have 16 entries of Scan for Belt Cluster, and there are no entries in the Scan tab for "Belt Cluster".  I feel like Belt Cluster should have its own row in the Scan tab, since they are scannable objects.

![belt cluster](https://user-images.githubusercontent.com/15353221/38288943-9f5da810-37a1-11e8-80f8-8d505f99627a.png)

**Comment by klightspeed** [comment]
Belt Cluster scans are put under the belt.  However, if the star has not been scanned, then that belt won't show up.

**Comment by iainross** [comment]
We could change the label for the Planet Scan counts in the stats control to 
   obj == EDPlanet.Unknown ? "Belt Cluster" : obj.ToString().Replace("_", " ")
?

Definitely shouldn't try adding them to the Scan control.

**Comment by robbyxp1** [comment]
Done on tip
