### ISSUE TITLE
Body's space delimited - bug 9.1.9

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1898]
Not sure what happened here
[img]https://i.imgur.com/ZVsoXk9.png[/img]

if it won't break things I'm fine, but it needs to be cleaned up, please advise how to do that

**Comment by klightspeed** [comment]
That looks like one of the systems where some other program that submits to EDSM assigned bodies to the wrong system.

**Comment by Disorganise** [comment]
Interesting.  I looked at EDSM and found
https://www.edsm.net/en/system/id/23541269/name/Praea+Eup+KH-M+d7-0  has just the one body.  First discovered by Cmdr MARDUK_ESP, whose timeline seems to match the 'fake' bodies ON-K, ST-I and WZ-G
https://www.edsm.net/en/user/flight-logs/id/31095/cmdr/MARDUK_ESP/index/p/63

Which each have only the star registered
https://www.edsm.net/en/system/id/23544124/name/Praea+Eup+ON-K+d8-0
https://www.edsm.net/en/system/id/23544125/name/Praea+Eup+ST-I+d9-0
https://www.edsm.net/en/system/id/23544126/name/Praea+Eup+WZ-G+d10-0

**Comment by klightspeed** [comment]
That system has one body because I cleaned it up.
