### ISSUE TITLE
Bug: rounding error in distance calculations

### ISSUE THREAD

**Issue by RockSlice** [EDDiscovery/EDDiscovery#19]
Occasionally, the calculated distance to a reference star is off from game-reported distance by .01

This may be due to a slight difference in rounding methods between EDDiscovery and ED.

![eddiscovery](https://cloud.githubusercontent.com/assets/13170221/8504266/86430032-219c-11e5-81ec-9398cd402264.jpg)
![screenshot_0006](https://cloud.githubusercontent.com/assets/13170221/8504271/8a575c72-219c-11e5-8ace-a282c545b14b.jpg)

**Comment by Majkl578** [comment]
Yes, this may happen, I've seen this as well. Not sure yet if it's caused by floating point error during calculation or or just rounding error, will have to investigate.
Can you try with JS algo if that one is fine?

**Comment by RockSlice** [comment]
JS had the same results.  Forgot to mention that.

**Comment by RockSlice** [comment]
This may be related to the issues discussed at https://forums.frontier.co.uk/showthread.php?t=43362&page=119&p=1174014&viewfull=1#post1174014

**Comment by gregmalcolm** [comment]
Is this still a thing?

**Comment by finwen** [comment]
I think its still a thing.. rare but i should fix it someday.

2016-03-02 16:19 GMT+01:00 Greg Malcolm <notifications@github.com>:

**Comment by finwen** [comment]
Obsolete now with coordinates from ED 2.1
