### ISSUE TITLE
Materials tab - Duplicate entry names

### ISSUE THREAD

**Issue by dlchung** [EDDiscovery/EDDiscovery#1900]
I currently have duplicate materials listed in my Materials Tab. One of them displays the correct quantity of materials, while the remaining show 0. It also shows for materials where I have 0.

[https://imgur.com/a/xa49i](url)

**Comment by dlchung** [comment]
No it is currently unchecked.

**Comment by dlchung** [comment]
While checked, I am seeing duplicates on non-zero materials

https://imgur.com/a/7bakW

**Comment by robbyxp1** [comment]
One thing to do.. scroll down slowly on your travel history, with the materials window open.  As you scroll down, the material list will change to reflect the items at that point in time.

So if you could tell us the journal entries where both of these items come into your possession, and also dump out the journal record of those entries (right click, copy journal entry to clipboard) and paste them in it would give us an idea of which journal record was adding the item to the DB and its internal fd name.

thanks

**Comment by robbyxp1** [comment]
In here i mean, paste the Journal records in a reply

**Comment by dlchung** [comment]
It looks like the non-zero duplicates are no longer showing up. I can't seem to replicate the issue either.

Still seeing duplicates for zero'd items when "Remove zero items" is unchecked.

**Comment by robbyxp1** [comment]
I've asked on discord for someone to contribute their whole journal history (the whole file) to us where this happens.  If you would like to consider zipping up the whole saved games\ frontier developements \ elite dangersous folder and posting it to us (via discord or another method) thats the only way i feel we can debug it.

**Comment by Gimi1967** [comment]
Saw this and just checked my ED Discovery. What do you know, I have duplicates and even triplicates including non Zero :0
![mat tab](https://user-images.githubusercontent.com/1433251/39269242-a664b3dc-48d2-11e8-919d-65c5337202f3.PNG)

Journals Zipped and ready to go. (Only 3.2MB). Will go on Discord...

**Comment by robbyxp1** [comment]
I think i have a provisional fix, but your journals would prob confirm it, so i'd still like to check. many thanks

**Comment by robbyxp1** [comment]
Now closed, thanks for the help!
