### ISSUE TITLE
Close cleanly when the ED Launcher closes option

### ISSUE THREAD

**Issue by Pichu0102** [EDDiscovery/EDDiscovery#1905]
A suggestion: Have an option to cleanly exit when the ED Launcher is closed. Currently have a process manager set up to auto close the launcher when exiting ED, which then closes EDMC and EDDiscovery. EDDiscovery doesn't save any changes in this way as the process is simply killed. It would be nice if it would safely save and close on its own.

**Comment by klightspeed** [comment]
Does the process manager not support sending WM_CLOSE to the main window of a process it manages?

**Comment by robbyxp1** [comment]
This is up to your external manager to ask ED to close down cleanly.  I don't think sitting their monitoring another process is a good use of resources by ED.
