### ISSUE TITLE
Discrepancy between exploration values and Universal Cartographics values of 400,000CR

### ISSUE THREAD

**Issue by Imathil** [EDDiscovery/EDDiscovery#1910]
System is HIP 31451 - approx scan value is listed at 1,025,622CR in EDDiscovery. 
Full scanned system (except for belts)
Universal Cartographics list turn in value at 621,053CR
Comparing values between the two most are within one credit which I would expect
HIP 31451 3 in EDD is listed as Terraformable, Volcanism, Thick Argon Ricvh Atmosphere, Value 729,088
HIP 31451 in Cartographics is listed value as 324,491
System map shows it as Terraformable

Not sure where the values for exploration come from? Is this a E:D, an EDSM or EDDiscovery problem or just an outlier?

**Comment by iainross** [comment]
Unfortunately the values for terraforming candidates are not full understood.  All bodies have a UC value which is a known function of their mass and a constant that varies by planet type.  If it's terraformable there is a bonus added, which is a similar function of mass and body type then multiplied by a number between 0 and 1 - we don't know exactly what controls the value of that last multiplier yet, EDD currently just assumes 1 (as this is mostly what you get).

See https://forums.frontier.co.uk/showthread.php/232000-Exploration-value-formulae for more detail on the calculations and ongoing efforts to work out what drives the proportion of the bonus you get on a CFT, rest assured if we ever nail it down reliably then I will promptly update the EDD calculation to reflect it.  Until then there's not a lot we can do.
