### ISSUE TITLE
EDD Enhancement: Running Approx value total while exploring

### ISSUE THREAD

**Issue by Aznok** [EDDiscovery/EDDiscovery#1916]
I think it might be nice to have a running total of the approx value for the systems when your out exploring. Just keep adding on the total of current system when you jump to the next system, in a separate box, perhaps at the top of the History tab next to the cursor to top box or something. Have it reset to 0 when you turn in your discoveries. Would be cool to know, Hey, I've made around 100 mil so for...I think it's time to turn in. Just a thought, since you have no idea how much you have accumulated until you turn in anyway.

**Comment by iainross** [comment]
You can see an estimated value of what you've scanned in assorted time periods (including since last dock) on the statistics panel (which you can include in the history tab, I do...)
