### ISSUE TITLE
Unknown events history tab

### ISSUE THREAD

**Issue by Abulion** [EDDiscovery/EDDiscovery#1918]
I have recently re-started to play the game, i find many "unknown events Report to  EDDIscovery Team" in my timeline.

Regards

**Comment by robbyxp1** [comment]
Make sure you are running 9.1.9.

**Comment by Abulion** [comment]
Thanks I had the previous version (the 7.04 or something similar) I checked for updates and it did not find anyone... 

😀 

Now I have installed the latest version, and no unknown events... 

Regards, again.

I think I can close the issue...

(It was mine... 😆 )
