### ISSUE TITLE
Unhandled UI exception on route finder tab

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDDiscovery/EDDiscovery#1922]
### Description
After calculating a route and clicking into one of the empty field of the "straight line distance" line:

### Additional Information
![image](https://user-images.githubusercontent.com/25147462/39428518-edd98efa-4c87-11e8-9e14-adcc9b261a0b.png)

### Exception Details:
>EDDiscovery v9.1.9.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentNullException: Value cannot be null.
>Parameter name: text
>   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
>   at EDDiscovery.UserControls.UserControlRoute.dataGridViewRoute_CellClick(Object sender, DataGridViewCellEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlRoute.cs:line 667
>   at System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
>   at System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Ahh will fix. silly me.

**Comment by robbyxp1** [comment]
Fixed
