### ISSUE TITLE
Unknown module type - Alliance Chieftain

### ISSUE THREAD

**Issue by imathrowback** [EDDiscovery/EDDiscovery#1923]
Version: 9.1.9.0

Attempting to send my ship, an [Alliance Chieftain](http://elite-dangerous.wikia.com/wiki/Alliance_Chieftain), to Corolis from Loadout tab and error message box appears:

> Unknown module Type
> Alliance Chieftain Armor Grade 1:typex_Armour_grade1
This is probably a new or powerplay module
Report to EDD Team by Github giving the full text above.

The armor is "1C LIGHTWEIGHT ALLOY", the default armor.

All the other ships I have, export to Corolis fine.

Workaround: Use alternate program such as [EDMarketConnector](https://github.com/Marginal/EDMarketConnector)

**Comment by robbyxp1** [comment]
Fixed in the next version already. And your work around is not really applicable to EDD, is it ;-)
