### ISSUE TITLE
Unhandled Journal events - report to ED Discovery team. 

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#1929]
{
  "timestamp": "2018-05-06T10:15:10Z",
  "event": "Status",
  "Flags": 16777304,
  "Pips": [
    4,
    4,
    4
  ],
  "FireGroup": 1,
  "GuiFocus": 6
}

**Comment by robbyxp1** [comment]
This one should not appear in the journal record.  Did it appear in the travel history?

**Comment by Tromador** [comment]
I am unfamiliar with how ED stores data, point me where to look and I will check for you.

**Comment by robbyxp1** [comment]
Does it appear on the main travel history page, where it shows all the events seen by the program, such as FSD jumps, docking etc.

**Comment by Tromador** [comment]
You mean the history tab, right? If so, yes, that is where it appeared.

**Comment by klightspeed** [comment]
Is it possible to get the journal and trace log (or excerpts thereof) for when that event was logged?  Journals are in `shell:SavedGames\Frontier Developments\Elite Dangerous`, and trace logs are in `%LOCALAPPDATA%\EDDiscovery\Log`

**Comment by robbyxp1** [comment]
Okay, i'm going to close this.  let us know if it reappears..
