### ISSUE TITLE
Exceptions in Compass trying to bookmark

### ISSUE THREAD

**Issue by ArthurGideon** [EDDiscovery/EDDiscovery#1931]
### Exception Details:
>EDDiscovery v9.1.9.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'SelectedIndex'.
>Parameter name: SelectedIndex
>   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
>   at ExtendedControls.ComboBoxCustom.OnKeyDown(KeyEventArgs e) in C:\Code\EDDiscovery\ExtendedControls\Controls\ComboBoxCustom.cs:line 427
>   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
>   at System.Windows.Forms.Control.WmKeyChar(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```
![screenshot 2018-05-08 07 19 56](https://user-images.githubusercontent.com/39077740/39739554-cd70bdb8-5291-11e8-8eb1-060422e597d4.png)

**Comment by robbyxp1** [comment]
Protecting against this on tip.
