### ISSUE TITLE
Opening 2D plot generates an "unhandled UI exception"error then a crash

### ISSUE THREAD

**Issue by Imathil** [EDDiscovery/EDDiscovery#1935]
### Description
Tried to open a 2D plot in a separate window. Got the Unhandled UI exception error message (info copied below) then clicked on to continue and EDDiscovery crashed.

### Exception Details:
>EDDiscovery v10.0.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'OxyPlot.WindowsForms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=245eacd6b5d2d338' or one of its dependencies. The system cannot find the file specified.
>   at EDDiscovery.UserControls.UserControlPlot.InitializeComponent()
>   at EDDiscovery.UserControls.UserControlPlot..ctor() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlPlot.cs:line 50
>   --- End of inner exception stack trace ---
>   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
>   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
>   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
>   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
>   at System.Activator.CreateInstance(Type type, Object[] args)
>   at EDDiscovery.Forms.PanelInformation.Create(PanelIDs p) in C:\Code\EDDiscovery\EDDiscovery\PanelAndPopOuts.cs:line 213
>   at EDDiscovery.Forms.PopOutControl.PopOut(PanelIDs selected) in C:\Code\EDDiscovery\EDDiscovery\PanelAndPopOuts.cs:line 296
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by spadino** [comment]
Ops! Got look into it today later!

**Comment by klightspeed** [comment]
Looks like those 2 DLLs might not have been included in the installer.

**Comment by spadino** [comment]
Yep, @klightspeed! I can't reproduce that crash in my system. 
@Imathil, could you check on your system with the portable version? I'm sure it come with all the needed libraries. I thoroughly and extensive checked and rechecked the panel functioning, using it by some weeks before the 10.0 release, and I hadn't had any issue with...

**Comment by spadino** [comment]
It seems so. ;)

**Comment by robbyxp1** [comment]
Yep, my conclusion.. going to do a new version today to fix another bug, i will include!
