### ISSUE TITLE
Route tracker and Trip computer in version 10.0

### ISSUE THREAD

**Issue by Teyar** [EDDiscovery/EDDiscovery#1936]
**1. Route Tracker** (see picture)

![routetracker](https://user-images.githubusercontent.com/30482684/39845242-034e19c6-53f5-11e8-9b0f-d0da01acbac1.png)

In my example, the residual distance is not correct. In the afternoon (version 9.1) It was still about 24,000 ly, which is also the correct residual distance. Now with the new version it is about 5,000 ly more. Where do they come from?

What does the reference to ship information refer to?
 On Ship/Loadout? There I can only set the tank warning.
Or the Trip Computer? There the setting for the ship details does not work, as was still done in 9.1.

**2. Trip Computer**

As mentioned above there are no settings to the ship details or it does not work (right click with the mouse does not show any effect). As a result, there is no information about jump range, remaining jumps as well as the total range. A tank warning, as it can be set in Ship/Loadout, is actually superfluous.
Is that supposed to be?

The Start button on the Trip Computer does not work, the Trip Computer cannot be reset.

It would be nice if you could check it out.

Thank you very much
Teyar

**Comment by robbyxp1** [comment]
Residual distance is now correctly the trip distance.. the distance along the path.  Previously it was the straight line distance as the crow flys, which did not make sense. We had a ticket to fix this.

Second part is a bug - will fix and release v.soon

thanks for the report.

**Comment by robbyxp1** [comment]
And 2. the trip computer uses the same method as the route tracker to work out jump distances.  It should be fixed.
