### ISSUE TITLE
error prompt when opening 3d map

### ISSUE THREAD

**Issue by Jsamsonite** [EDDiscovery/EDDiscovery#1939]
### Exception Details:
>EDDiscovery v10.0.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.EDDiscoveryForm.show3DMapsToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 851
>   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
That sounds like you don't have a history grid on your History tab.

**Comment by robbyxp1** [comment]
Qs. to Jsamsonite.  

1.The primary tab page, the one with travel history on, was the tab page there with a travel history showing when you hit the 3dmap button?

2. Did you hit the 3dmap button really quick after program start?

**Comment by robbyxp1** [comment]
Also, is the problem persistent? Does it always happen.  You can reset the tabs by holding down shift during launch and selected the tab reset option.

**Comment by robbyxp1** [comment]
Closing - no response
