### ISSUE TITLE
A few little things

### ISSUE THREAD

**Issue by Teyar** [EDDiscovery/EDDiscovery#1942]
Hello,

**1. Trip Computer**

1.1. Start button does not work properly
 After pressing the Start button, the start point is inserted in the journal, but the trip computer is not reset (picture 1 and 2)
![tripcomputer 1](https://user-images.githubusercontent.com/30482684/39961901-c748333c-5640-11e8-8df5-f542cbcc2910.png)
![tripcomputer 2](https://user-images.githubusercontent.com/30482684/39961906-cc4b6d36-5640-11e8-8002-ab160867107b.png)

1.2. Jump Range
![tripcomputer 3](https://user-images.githubusercontent.com/30482684/39961907-d6f69da0-5640-11e8-93eb-28628bd56113.png)

I found a discrepancy between the actual jump range and the one shown in the Trip computer (picture 3).
Even if I describe it here, it does not seem to be a mistake in the trip computer, but affects ships and their lodouts...
There is a record that I have installed weapons and a cloud scanner. However, this has not been the case for more than 4 months. I do not know whether this is a general mistake or only concerns me. What I noticed, however, is when I call the ship configuration via EDSM, it is displayed correctly. EDSM gets the data on EDDiscovery, right? So how can it be that different data is available?
It is not a big mistake, but it is still a bad indication in the trip computer. So far it has not bothered because it could be corrected via the ship detail setting in the trip computer. Since this is no longer possible, my question is: Can this be corrected? It would be nice if the trip computer would show a correct jump range.

**2. Route Tracker (see also picture 3)**

The remaining jumps refer to the final destination of the route, right? Shouldn't they also be a row higher? In my example it reads as if I would need to the waypoint for about 3,300 ly 662 jumps. This can, of course, be possible in regions with poor stars, but certainly does not apply in this example (the last sentence remark was a joke)

**3. Finally, a few (optical) suggestions for improvements for future versions**
These would be especially helpful if you work with overlay like me.

3.1. Trip computer
-One way to hide the two buttons (EDSM and start) (similar to the system information). They are rather obstructive in the overlay.
-a label for first detected systems also in the trip computer. This custom only consist of an asterisk (*) and can be attached to the identification number of the visit in the respective system. In the example above, it could look like this: "Preia Flyuae ZX-y C2-35 [1 *] | 13 Mu... " or without a star, if you were not the first.

3.2. Route Tracker
-A way to hide the coordinates of the current waypoint, similar to the "show jumps to go" option.

**Comment by robbyxp1** [comment]
Thanks for the reports.

1. Start/Stop insertion - I'll check.  I though it did a history reload which meant the TC would be updated.  May be missing a call in the TC

1.2 What is the loadout/modules panel saying about what is on your ship?  Is it wrong vs the items actually on your ship? Thats what the mass is based on.  Can you report.

(Maybe its missed a journal record with you removing something. Looking at the code, journal Loadout only supplements the ship information list, it does not wipe it (and that's because it does not contain every field)..  maybe I need a rethink..)

2. The 3301.5 @ 662 looks wrong.. and is wrong in the code.  Its just giving distance to waypoint, but it has computed the jumps on 24k ly.  will fix.

3.1 Agree will add a right click to hide EDSM..
I'll look into first discovered and how easy it is to add..

3.2 I can add a right click

Thanks for your detailed report!

Rob

**Comment by Teyar** [comment]
Thanks for the quick reply

To 1.2 I have put myself upside down (need a new glasses xd)

The whole thing is even more convoluted. First of all, the panel to which it is:
![loadout](https://user-images.githubusercontent.com/30482684/39965521-f36cedae-569a-11e8-81f9-bfb73dd49cbe.png)

I have marked the modules that affect it. I have actually no longer installed these modules.

Now it becomes interesting. My actual jump range is 35,10ly, as seen from the picture. The trip computer gives me a wider range, 36,7ly. If I call up the Coriolis website via the Panel ships/loadout, then I will see a jump range of 34,85ly. I think that this would have to be in the trip computer, provided that the values shown in the Panel ships/Loadout are based.
All very strange. What's funny is that the trip computer displays a higher jump range than it actually has, even though my mass is larger than actually in the journal.
Still to supplement, I have not yet upgraded through engineers.

**Comment by robbyxp1** [comment]
The mass is actually based on corolis data for each module.  See the Mass number in the list. Which one is wrong? Hull/Modules? 

Can you post me your corolis loadout (as a link)..

So, somehow, the EDD did not recognise the entries where you removed the pulse lasers (or its a bug), so..

Does the journal record in travel history show the ModuleSell/Module Store event where you removed the pulses?  If its not there, then EDD never saw the removal.  If it is there, then why did EDD not remove them (bug?)

I don't know if you would be willing to share the complete logs (in a zip) either on discord or some other method, if you could, I'm finding thats the quickest way of diagnosing these cases. All in confidence.

Cheers

**Comment by Teyar** [comment]
Okay, here's the link to Coriolis:
https://coriolis.edcd.io/import?data=H4sIAAAAAAAEANWYTVPbMBCG753pf2By5uCP2Am9hQQIHWgZzMDRs9hKookieWSZ4jL890o2pgai1AqiQA75kKXVM292V6999%2FXLzk6Pwgr1vu30RhQSRlPo7VbDK5YWBOXyyp36LUdGfMUK%2FnfgcVJ7SA7iVA643tDp7%2Flhf7d15flWcR0yPuKQIrfXnsqonCh4gdqDGceMY1Gq%2BM3wff3l%2FmFebwx8zqYgksW%2FSRueU3UReLV0H8oJY%2FwlzAxIrqPxdDQTlABxu5NU8%2BOD24wwjnh8QLBAdnSpInsfhsT%2FCCQHdI4pGjPSKa8bnodVRS7YCucgMKPxTw50bonqkMuNogWeiQnHN8ig4MK%2B6w3WFdwxFfG0zBBPVcQ4wr9RGI8J5HlgxOxomQtELoAujWD9wNHBNvEq1KBG9e3Ie4JnKCqyjHFhJm2wp6NthWwDe3a0PQVM65zLjYCd4drmq4DrcG%2FAekaAIgG8HGUZZ5AsokJVa2fscOD5rjaF6%2BhPQ1vJiTP2C%2FEJzgXH14VgJodc2PccTwv8LG5bcUuVV22hhDHLZqe%2FGTpTEStcfxtcrdLnkIKhvIE2jSNEc8bzCnNoNY9l%2B83GLFlmuIOsL2xNs9KKYgrleOJ0x%2FghP%2BXfJ2R9V0vjCSuuCTpRFX%2B1sFYzdXADb%2FMfudRWWynWuAzHfQukrcR6IyTChIyoKmdg0J7la6htHOrQjhLGsjqs1TaneF2nCtw34fWD0NW2D4GItP37LC1lj07YDeJllACl0mWO0hugCUrtqe36FX0HC966gQr6WtMxkU0G0%2FmYrbJCSOJIgOw9fA3xpjuXjYI7Xm0VTQQfSMl1yOcoA6w8%2FGYDuj1v%2F5PxBrUhMOTVnodPePU2Y3ve0JT33Vx%2BhTvYAtcLtRUn2zgi6RGS%2FQEaM%2BfbtR2Kemjc5Qaet6ftcvvFfF7uQ1lH1eJunxR75l053JDEE3n%2FgAlKo4LPIEFNQ77AtLSUGisgZCo7ZcYwFR3O5PYDreFanaeZtM2FFPAEcsl6iG9RGlf72BL6CbPZGfJezOof21LmwF1bhAp5ikBEmC5PoKDJQiVGwTkS5vnRjdvwuLbF%2FXrBjQ5BL%2FC04GPCirSpQlXpjt2D5QpBxqjpQ7iHVU8ewp3bsmtnIAX8zq674zQr4sd7wFPZxgjBiRePF5ytbNp2%2F%2FO4nEuU54hcMpx0eAjUQFXTzyBZxpeo2uBV0qkP%2BXb%2FB9RxhnzuGAAA&bn=Pan-Thau-Ra

What about logs? The journal entries under saved games? If so, then I have attached it as a zip file. If anything else is meant, please write again.

Journal entries: 
[Elite Dangerous.zip](https://github.com/EDDiscovery/EDDiscovery/files/1998289/Elite.Dangerous.zip)

**Comment by Teyar** [comment]
The journal entries only go back to Nov 2017, but I have only expanded the modules afterwards.

**Comment by klightspeed** [comment]
The 36.7ly suggests that the extra fuel tank is assumed to be empty.

**Comment by Teyar** [comment]
I don't understand.
Is this a new feature of the trip computer from version 10? Because before version 10 he still has the correct jump range displayed.

**Comment by klightspeed** [comment]
It looks like `ShipInformationList.Loadout` doesn't remove any modules not in the `Loadout` event.

It looks like the jump range in the trip panel is the jump range when your tank is half full.  Perhaps it should show current / average / max jump ranges, rather than just the average jump range.

**Comment by klightspeed** [comment]
The actual problem with the hardpoint removal not being recognised was that the events from before `LoadGame` were being held too long, resulting in the `Loadout` event from the start of the session overwriting any loadout changes during the session.

**Comment by klightspeed** [comment]
#1943 should fix the incorrect loadout issue.
#1944 should show last / average / max jump ranges based on the most recent fuel event and the current cargo and modules.

**Comment by robbyxp1** [comment]
Your issue 1.1 is intentional - the stop flag history entry position still has the travel distance data in there from the previous journal .  On the next entry, it will reset to zero.

Issue 1.2 Klightspeed has fixed

Issue 2 I've fixed in a upcoming PR

3.1 Trip computer is now fully configurable!

3.2 Route tracker shows total jumps, jumps to waypoint, and you can turn on/off the jumps, deviations and co-ords

Think we are all done with this ticket.
