### ISSUE TITLE
10.0.2 Install Loop

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1952]
Probably not an EDD thing and is coincidental since I blue-screened immediately before downloading 10.0.2, but...
I'm in a loop where installing yields a 'are you sure you want to cancel' - if I say no, it goes back to the the 'next' button to start the install and then back to the 'are you sure you want to cancel'.  clicking yes quits.

![img](https://i.imgur.com/LXKOCbx.png)

also tried 10.0.1 again, it gives me repair or remove options.....but again goes into this cancel loop.  So I seem to be be stuck :(

**Comment by Disorganise** [comment]
I managed to remove via control panel, but reinstall does the same loop.  I *have* been able to install 9.1.9, but any attempt to install 10.x results in the loop

**Comment by robbyxp1** [comment]
Can you remove it via the control panel program and features?

**Comment by robbyxp1** [comment]
Very strange.

You could

1. try blowing away all the files in program files
2. Try installing the portable version.. but you would need to move your appdata \ eddiscovery folder to the appdata folder under where you stored the portable install.

i'll think.

**Comment by klightspeed** [comment]
More specifically, the files in the EDDiscovery directory in program files.

**Comment by robbyxp1** [comment]
Yep! I did not mean all of your programs ;-)

**Comment by Disorganise** [comment]
Uninstalled 9.1.9 again.  Renamed the install folder (under Z:\apps as opposed to C:\Program Files) but the install loop persists.  Couldn't find anything useful in the registry either.

Have grabbed the portable version and copied over the appdata directory - it 'remembered' my overlays etc (and more importantly, my trip), so all good there.  I guess this means I don;t need the installed version at all now, but I do want to try and fix the loop.  Will keep digging.  If you can think of anything....

**Comment by klightspeed** [comment]
Do you have UAC disabled, or otherwise set not to allow elevation?  I was able to reproduce this by clicking No on the UAC elevation prompt.

**Comment by Disorganise** [comment]
UAC - still on default.  But you're onto something.  I upped it to 'always' and still did not even get anything.  in comparison, after choosing the directory, clicking the install button with 9.1.9 generates the UAC window. 
So....for some reason 10.x is not giving UAC a kick

**Comment by Disorganise** [comment]
phooey.....I tried right clicking, run as admin for the installer.  Got UAC prompt, approved, but still get the 'are you sure you want to cancel' message.

**Comment by klightspeed** [comment]
What OS version does `winver` say you're on?

**Comment by robbyxp1** [comment]
We have a bug report from the installer https://www.advancedinstaller.com/forums/viewtopic.php?t=34111

**Comment by Disorganise** [comment]
Microsoft Windows [Version 10.0.17134.48]

**Comment by Disorganise** [comment]
So, I've 'fixed' it - but it is very very odd.
I did some poking to see if I could get a log file.  Missed it and saw I could extract the contents, so did that.  Realised I couldn't see the extracted files cos I fumbled the folder, so created a sub-folder and tried again.  The found the msi wouldn't launch without the bootstrapper, and finally spotted the /exelog command.  Ran it and.....
Got hit up for UAC and install was a success.  Long story shortened, I did several repeats :)
If I run from my downloads directory - no UAC, and no install.  It has ALWAYS been run from here and I still have installers there from as far back as 3.0.5.
Running from the sub-directory - get UAC message and successful install (and uninstall).

Log pasted below in case you're interested (though it merely says I cancelled the installed)

====== Starting logging of "Z:\Downloads\EDDiscovery_10.0.2.exe" ====
OS Version: 10.0.17134 SP0 (workstation) [x64]

2018-05-16 22-53-29-Full command line:EDDiscovery_10.0.2.exe  /exelog Z:\Downloads\EDDiscovery\install.log
2018-05-16 22-53-29-Command line to pass to MSI:
2018-05-16 22-53-29-Extraction path set to:\\?\C:\Users\Dave\AppData\Roaming\EDDiscovery\EDDiscovery 10.0.2\install\
2018-05-16 22-53-29-Extraction path set to:\\?\C:\Users\Dave\AppData\Roaming\EDDiscovery\EDDiscovery\prerequisites\
2018-05-16 22-53-29-Language used for UI:0-English (Australia)
2018-05-16 22-53-29-Maintenance mode:false
2018-05-16 22-53-29-Wrong OS or Os language for:.NET Framework 4.6
2018-05-16 22-53-57-Code returned to Windows by setup:1602
2018-05-16 22-53-57-=====================End of Log=====================


====== Starting logging of "Z:\Downloads\EDDiscovery\EDDiscovery_10.0.2.exe" ====
OS Version: 10.0.17134 SP0 (workstation) [x64]

2018-05-16 22-55-01-Full command line:EDDiscovery_10.0.2.exe  /exelog Z:\Downloads\EDDiscovery\install.log
2018-05-16 22-55-01-Command line to pass to MSI:
2018-05-16 22-55-02-Extraction path set to:\\?\C:\Users\Dave\AppData\Roaming\EDDiscovery\EDDiscovery 10.0.2\install\
2018-05-16 22-55-02-Extraction path set to:\\?\C:\Users\Dave\AppData\Roaming\EDDiscovery\EDDiscovery\prerequisites\
2018-05-16 22-55-02-Language used for UI:0-English (Australia)
2018-05-16 22-55-02-Maintenance mode:false
2018-05-16 22-55-02-Wrong OS or Os language for:.NET Framework 4.6
2018-05-16 22-55-27-Code returned to Windows by setup:0
2018-05-16 22-55-27-=====================End of Log=====================

**Comment by klightspeed** [comment]
Do you have any DLLs in the Downloads directory?

I wonder if Windows 10 1803 now has an option to deny UAC to unknown executables?

**Comment by Disorganise** [comment]
No DLLs.  Plenty of exe's and msi's.  9.x still installs from there, it's only 10.x.  I also ran graphic card driver update from there last night.   This is really weird and unfortunately I know of no other logs to look at to figure out what is going wrong.  If it's just me, I guess we move on.
I got one thing I didn't try yet, and that's disabling AV (bitdefender) - it's not complaining any though so I don't think it's a factor, but I will try it over weekend.

**Comment by Disorganise** [comment]
Turns out to be Bitdefender.   After disabling the shield, the installer prompts for UAC and then installs/uninstalls/repairs as expected
![img](https://i.imgur.com/fhltFXg.png)

*only* for the 10.x installers.  Did you change a certificate or something?  I'll contact BitDefender also

**Comment by Disorganise** [comment]
Belay that.  Was trying to reproduce for Bitdefnder ticket and ran into the issue with BD disabled....now I'm confused....maybe I ran it from the subfolder without realising

**Comment by klightspeed** [comment]
Advanced Installer was used to make both the 9.1.x and 10.0.x installers.

We did add a new third-party library (OxyPlot), though you would think the AV would flag that if that were the problem.

As usual, using VirusTotal, JiangMin flags the installer (some random probably used Advanced Installer to create a bitcoin miner trojan), and Baidu flags the SQLite library (some random probably used that library in a trojan).  Other than those false positives, all of the other antivirus vendors return a clean result.

**Comment by robbyxp1** [comment]
Closing as this is now old.. hopefully its sorted.
