### ISSUE TITLE
EDSM requesting of Bodies is handled poorly.

### ISSUE THREAD

**Issue by Sakedo** [EDDiscovery/EDDiscovery#1955]
Conclusion before the story:
Requests to EDSM frequently times out because of high server load and EDD handles these timeouts very poorly.

Story: 
I have no bodies information in my database besides the few systems in my local journal.  I first noticed this issue when installing ED Discovery on my desktop machine after having successfully used it on my laptop, and now it's happening on my laptop as well.

Starting from a fresh database and pruning AppData/Local:
EDSM pull is successful.  EDDB also syncs successfully.  The journals are present and scanned - I see history.  I have bodies only for the few systems that I've scanned over my course of exploration.

I have the full system list in EDD.  I can plan routes, etc.

EDSMClass::GetBodiesList() has no valid data.  The first early-exit block --

if (DictEDSMBodies!=null &&  DictEDSMBodies.ContainsKey(edsmid))  // Cache EDSM bidies during run of EDD.
                    return DictEDSMBodies[edsmid];

returns DictEDSMBodies[edsmid]; -- which is itself NULL.

GetBodiesList() is not called from code that I can tell without getting through that block of code, and the .json import from EDSM contains no body information.  

... 

Doing a little of my own debugging and removing that early exit, I see calls to GetBodies failing because of a EDSM timeout, which is set to 5 seconds.  I can make the call manually to EDSM and it does succeed, but it's quite sluggish.

If I change this value from 5 seconds to 20, my calls succeed and I have body data. But only if I run with that block commented out because those systems will never attempt to get body information again that I can see.

**Comment by AnthorNet** [comment]
Aloa?

**Comment by robbyxp1** [comment]
Anthor is on the case, and will fix up a tiny issue which was causing random hold ups.  Thanks for the report.
