### ISSUE TITLE
EDDiscovery bug (10.0.2)

### ISSUE THREAD

**Issue by spitap** [EDDiscovery/EDDiscovery#1959]
Every time I start the software i get this log result :
Check Systems exception: disk I/O error
disk I/O error
Trace:    à System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   à System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   à System.Data.SQLite.SQLiteDataReader.NextResult()
   à System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   à System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   à EliteDangerousCore.DB.SQLiteDataReaderED`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLiteTransactionED`1 txn, SQLiteTxnLockED`1 txnlock) dans C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:ligne 339
   à EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteDbDataReader(CommandBehavior behavior) dans C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:ligne 509
   à EliteDangerousCore.EDSM.SystemClassEDSM.DoParseEDSMUpdateSystemsReader(JsonTextReader jr, Boolean[] grididallowed, DateTime& maxdate, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache, Boolean useTempSystems) dans C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:ligne 440
   à EliteDangerousCore.EDSM.SystemClassEDSM.ParseEDSMUpdateSystemsStream(TextReader sr, Boolean[] grididallow, DateTime& date, Boolean removenonedsmids, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache, Boolean useTempSystems) dans C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:ligne 265
   à EliteDangerousCore.EDSM.SystemClassEDSM.ParseEDSMUpdateSystemsString(String json, Boolean[] grididallow, DateTime& date, Boolean removenonedsmids, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache) dans C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:ligne 254
   à EliteDangerousCore.EDSM.SystemClassEDSM.PerformEDSMUpdateSync(Boolean[] grididallow, Func`1 PendingClose, Action`2 ReportProgress, Action`1 LogLine, Action`1 LogLineHighlight) dans C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:ligne 744
   à EDDiscovery.EDDiscoveryController.DoPerformSync() dans C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:ligne 696

**Comment by klightspeed** [comment]
Disk I/O error - that suggests that the filesystem needs to be checked.

**Comment by robbyxp1** [comment]
External issue - check file system - come back if its re-occuring after you did this
