### ISSUE TITLE
10.0.2 Trip reset in stats panel by itself

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1960]
For some reason my stats panel decided to reset my trip to starting 'now'.  Fortunately, the the trip computer and main panel are still correct.  Have NOT tried closing and re-opening pending your advice in case there's logs or something you need to check out what happened.

(As an aside....how does one set the beginning of trip?  if this goes pear shape I want to be able to set the trip start back to the beginning of DECE)

Trip Comp
![img](https://i.imgur.com/v3SlRkX.png)

Main panel (1 jump later)
![img](https://i.imgur.com/tTj06HS.png)

Stats panel
![img](https://i.imgur.com/Hm49UE5.png)

**Comment by klightspeed** [comment]
Do you have a start marker 15 jumps back?

**Comment by Disorganise** [comment]
At work now so can't check.   I didn't (intentionally) create one though.

**Comment by klightspeed** [comment]
Looking at it, the "Trip" in the stats panel is the segment since the last start marker, while the statistics in the trip panel and system info are for the entire trip - i.e. since the first start marker or last stop-start pair, whichever is most recent.

**Comment by Disorganise** [comment]
The last time I updated the destination was when I set it to sublustrius beacon.... Monday ish.... So somewhere between 26 and 105 jumps ago. 
So how/why does EDD auto create a trip start?   I *have* flipped between EDD installed and portable versions because of an installer problem, both pointing to same DB (only run one at a time) 
Is there an event written when I  select a new route in Gal Map?   I wasn't aware of such a thing but that could explain (I decided to return to head towards ishams reach this morning, so a new plot).   I'm not using any EDD plotting though (never worked out how)

**Comment by robbyxp1** [comment]
It never autocreates a start/stop marker - its always a manual process

there is a right click option in the travel history to jump to the next start/stop marker - see where they are.

**Comment by klightspeed** [comment]
There was a bug in the trip panel that didn't add a stop marker when start was clicked.

You can select the entry with the start marker, right-click, and click `Set start/stop point for travel calculations`

**Comment by Disorganise** [comment]
yay, that resolved it 👍 
![img](https://i.imgur.com/dPGilUL.png)
