### ISSUE TITLE
feature request - Material collection statistics 

### ISSUE THREAD

**Issue by torbach** [EDDiscovery/EDDiscovery#1963]
Would it be possible to click a material and have it display where/how the object was obtained?

I want a breakdown of what vessels or poi's return data. 

E.g.  
"OPEN SYMMETRIC KEYS" 
- 23.6% gathered from "SATELLITES"
- 15.54% gathered from "DATA POINT" (surface)

Click > "SATELLITES" 
- 20% chance for "OPEN SYMMETRIC KEYS"
- 4% "CLASSIFIED SCAN FRAGMENT" 
etc...

**Comment by klightspeed** [comment]
Ship:
`ShipTargeted` -> `MaterialCollected (Category=Encoded)`

Data point:
`DatalinkScan` -> `MaterialCollected (Category=Encoded)`

Data point / Satellite / ground:
`DataScanned` -> `MaterialCollected (Category=Encoded)`

Note that `ShipTargeted` was not logged before 2.4.

For manufactured items in unknown signal sources, the best available is:
`USSDrop` -> `MaterialCollected (Category=Manufactured)`

When on the ground, there is no indication as to what type of site you're raiding (unless it's a major outpost in which case you get `ApproachSettlement` from several hundred km) or what type of material node you're shooting.

**Comment by robbyxp1** [comment]
We don't store that in material commodities at the moment..  
 
we should also be aware of the memory implications of adding stats to each material type... since it gets cloned on change.. it may be okay.  You could have a set of stat against each material.

**Comment by torbach** [comment]
I'm unfamiliar with what's behind the doors; from what I see `EDDN Integration` sends log info so players benefit each other by creating a galactic average on material drops -- How idiot-proof? e.g. can a player upload fake data or remove info and then re-link integration to hide it?

***
although my example was Encoded I envisioned players would contribute each of the 3 (Manufacture/Encoded/Raw) material drop % 
***

This is an idealized vision suggestion


```
**Abnormal Compact Emissions Data** (grade 5) (group 1) - [your lifetime collected 82]
Known sources : (Ship scans), (Mission reward), 

(Ship scan ; System Authority Vessel) 
- 51% Python; (top 3 sources rank - Elite 56%, Deadly 32%, Dangerous 13%)
- 42% Anaconda (top 3 sources rank - Elite 55%, Deadly 34%, Dangerous 10%)
- 7% Viper MkIII (top 3 sources rank - Elite 66%, Deadly 32%, Dangerous 1%)

(Mission reward)
- 100% Deciat (faction; 100% Independent Deciat Green Party)


**Imperial Shielding** (grade 5 ) ( group 7 ) - [your lifetime collected 178]
Known sources : (USS), (Mission reward), (Combat Aftermath)

(USS)
- 99.9% USS; (High Grade - Imperial space 100% )

(Mission reward)
- 0%;  (_you have not performed any missions for this material_)

(Combat Aftermath)
- <1% ; (top 3 locations - Deciat 100%)
```



(although EDDB handles body drop % i figured once a system was in place there's not much reason to NOT log raw drops from prospecting, missions, mining, or automatic mining stations.)


But from what @klightspeed has posted -- The data might not provide this level of specificity

**Comment by robbyxp1** [comment]
As we don't have a method to comprehensively do this, I think its a no-goer for all the effort involved. Sorry
