### ISSUE TITLE
Support for White Dwarf (DAZ) Star type

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#1965]
On visiting system LHS 1547, EDSM correctly lists LHS 1547 A as a White Dwarf (DAZ) Star, whilst EDDiscovery simply lists unknown star.

**Comment by klightspeed** [comment]
Did you scan it?

**Comment by Tromador** [comment]
What difference would that make? EDDiscovery pulled all the rest of the system data down from EDSM as normal, only that one star showed an anomalous output.
