### ISSUE TITLE
Voice lag - several minutes

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1967]
I've noticed that the voice readout can get quite far behind.  By example, today we assembled for the DECE/BPE mass jump out at the BP tourist beacon - the chat was being spammed with beluga chat.
At some point, the voice pack gave up - I only noticed because after we moved locations and jumped out, the voice pack kicked back in with all the beluga chat.  I did 70 jumps and it was still babbling :)

But I've noticed it also with just regular jumping, it will be a jump or two behind.  Some of it is probably the new speech (like weapons out, hard point retracted each time you honk) slowing it down, but without being a programmer, I suspect there may also be a threading issue.

**Comment by Disorganise** [comment]
Watched resource monitor - no disk queues and only occassional micro second spike to 100% cpu..  main panel lags maybe a second or two behind which is probably normal to allow log written and read.  but voice is still a jump or more behind - it only takes 2 or 3 jumps for it to get that far behinds

**Comment by robbyxp1** [comment]
I'm going to introduce max lag for voice messages to address this in 10.1

**Comment by robbyxp1** [comment]
And there is an issue for that. So closing.
