### ISSUE TITLE
Feature Request:  Integrate E.D.I.S.O.N

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1968]
If you haven't tried it...try it :)
Thread here;
https://forums.frontier.co.uk/showthread.php/372326-E-D-I-S-O-N-Orbital-and-surface-navigation-Waypoints/page5 

I realise you have a compass already, but to be honest, it's either broken or I'm using it wrong cos it seems to want to take me somewhere other than where I'm trying to go.  Edison is a voice over and visual overlay and it works really well....except you have to enter the planet radius manually.

It would be really cool if *either* EDD could call Edison with parameters such as radius and co-ordinates so we use EDD bookmarks (required Edison to expose an API....already asked :))  *or* integrate their work somehow (if they're willing).  (Option 3..plaigarise)

**Comment by Disorganise** [comment]
I trialled it in conjunction with Captains Log at two of the BC's during my catch up to DECE.  I assume the arrow thing was meant to be telling me left or right and the line (iirc) the destination.   For some reason EDD and CL disagreed and I found CL got me to the posted co-ords and EDD was still implying I was over 1Mm away.  
I'll have another go at the next BC and make note of what I'm doing - more than happy to learn 'the right way'.

**Comment by klightspeed** [comment]
That sounds like the latitude and longitude might have been swapped.

**Comment by spadino** [comment]
@Disorganise, I've used our compass many times, and it works really well. I agree with @klightspeed: maybe you swapped the latitude with the longitude? Each tool pull the coordinates by the very same method, which s fro the journal, so they cannot be in disagreement. Give it a better look!

Now, E.D.I.S.O.N. is a very well made tool; if you like it and do not bother in having more than one tool working at the same time, you can just continue to use it, no? ;)

**Comment by robbyxp1** [comment]
If there is anything we can improve with our compass, I'm happy to do it. Iain did a sterling job on it.

I cant see integrating another tool a good idea.
