### ISSUE TITLE
Resizing is slow

### ISSUE THREAD

**Issue by imathrowback** [EDDiscovery/EDDiscovery#1969]
For whatever reason, the components in the main window are terribly slow at redrawing/painting so that 
 when resizing the main window the entire window can  freeze for short periods.

To mitigate this, I suggest adding something like this:

`this.ResizeBegin += (s, ee) => { this.SuspendLayout(); };`
`this.ResizeEnd += (s, ee) => { this.ResumeLayout(true); };`

somewhere into the main form (maybe EDDiscoveryForm_Load? ) so the window can be resized without having pauses. 

That should suspend paints while resizing, then as soon as the resizing is stopped, the form will refresh based on the final size.

**Comment by spadino** [comment]
Hi, @imathrowback. You can also fork the repo and, after you applied your code, ask for a PR. All efforts are welcome, I suppose...

**Comment by spadino** [comment]
There’s a contributing guide, already: https://github.com/EDDiscovery/EDDiscovery/wiki/Contributing-to-EDDiscovery-Using-Git

I started contributing

**Comment by robbyxp1** [comment]
Closing - this is not a widely reported issue.
