### ISSUE TITLE
Screenshot conversion - make/check it catches up

### ISSUE THREAD

**Issue by gobba** [EDDiscovery/EDDiscovery#1971]
Hey,
I have it set to scan my screenshotfolder and to convert them and save to another folder as jpg.

When i start the program it says its scanning the folder for bmp. But nothing more happens. There are tons of screenshots in that folder. They are big though around 14mb/screenshot.

I tried browsing to different folder and then back again. But still dont find any screenshots.

Scanning for bmp screenshots in D:\OneDrive\Pictures\Frontier Developments
Scanning for bmp screenshots in D:\OneDrive\Pictures\Frontier Developments\Elite Dangerous

Is there a debug switch or more detailed log that i can look in and see whats happening?

**Comment by gobba** [comment]
Also, nothing at all shows up in the screenshot tab.

**Comment by gobba** [comment]
Oh, now i moved all the SS outside the folder, and then moved them back in. Then it started converting!

**Comment by gobba** [comment]
Its when its to many screenshots it wont process. It stopped after it had converted like 100 of them. The wouldnt do any more, if i move them away and batch move them inside the folder again it will process them

**Comment by robbyxp1** [comment]
So, we don't post processes screenshots. Only process screenshots while we are running.and finding new journal events...

**Comment by gobba** [comment]
Aha, well it did process all the screenshots in the folder as long as there werent to many in it, when the game wasnt running, and it tagged them with the "current system" though. And it didnt process any new screenshots when there was to many in that folder aswell when the game was running. 

Maybe for postprocessing, if you like me forget to start the app when playing sometimes, which can fill that folder, so next time I start it its going to process them. Thats how it is now, so for a feature request, make postprocessing compare the created date of the screenshot with the journals so it can tag it with the correct system name. =)

**Comment by klightspeed** [comment]
Probably would need to have a `HistoryRefresh` handler which would cache the filename, timestamp and system from the `Screenshot` journal events, and use those to process any unprocessed screenshots.

**Comment by robbyxp1** [comment]
I've thought about it, but it used to be very difficult .. now maybe with the screenshot journal entry we can tie in the files.. 

But it would have to be a manual thing via an Admin menu option, don't want to slow down the load constantly checking and remembering if we screenshotted an entry.

**Comment by gobba** [comment]
Well, another approach is to check the created date of the screenshot in the folder, and reference that to where the cmdr was in the journals/database/edsm. Wouldnt that be easier? Its only when youve forgotten to start eddiscovery that there will be old screenshots in that folder, when its started next time. Isnt that way easier, that way you dont need to log screenshot events.

**Comment by klightspeed** [comment]
It is the game that logs screenshot events, which helps with matching screenshots to the system the commander was in when the screenshot was taken.

**Comment by robbyxp1** [comment]
On the backburner

**Comment by robbyxp1** [comment]
Moving to project future ideas, closing now
