### ISSUE TITLE
Materials requirements for Efficient Beam Laser modification are incorrect

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#1973]
See my screenshot. Heat Dispersion Plate is not required for the Efficient Weapon Grade 2 modification, in fact it's Heat Conduction Wiring and the Dispersion Plate is for Grade 3. The knock on effect is that all the requirements for higher grades are also listed incorrectly.

![laser](https://user-images.githubusercontent.com/38956076/40497048-26101aac-5f73-11e8-85c7-91f4bb89e70d.png)

The requirements are correctly listed at https://inara.cz/galaxy-blueprint/170/

**Comment by klightspeed** [comment]
Looking at the source history, it looks like most of the older recipes in EDDiscovery were not updated for 3.0.

We will need to gather the recipes and update <https://github.com/EDDiscovery/EDDiscovery/blob/master/EliteDangerous/EliteDangerous/MaterialRecipes.cs> with the updated recipes.

**Comment by Tromador** [comment]
Seeing as I opened the can of worms and this is grunt work (ie within my skillset) I will volunteer to go through it and submit a PR in due course.

**Comment by spadino** [comment]
Thanks!

**Comment by robbyxp1** [comment]
Hmm corolis has this encoded in their data.. we may be able to write a corolis to our format converter, much as we do with ShipModuleData

that may be the best way to do it.. a converted in netlogentry

**Comment by robbyxp1** [comment]
Before you go to all that effort, discuss with me.  If you've done most of it, well take the results, but if not, an converter will be better long run

**Comment by robbyxp1** [comment]
I'm writing the converter from coriolis now, so I would hold fire.

**Comment by Tromador** [comment]
I have done A-H but quite happy to hold up whilst you look at an alternative.
Don't mind doing it if it needs done, but it's pretty tedious.

**Comment by robbyxp1** [comment]
I've got a method to suck the data from the corolis automatically, its better in the long run its done programatically than manually.

thanks for your help

**Comment by AnthorNet** [comment]
I'll send you a spreadsheet we use to convert into our classes.

**Comment by Tromador** [comment]
As far as I can tell from spot checking blueprints in game, Inara is correct.

I will maintain a holding pattern until you have seen what Anthor has up his jumper, but if you do need me to continue with the manual rewrite, don't hesitate to ask.

**Comment by robbyxp1** [comment]
Thanks for your help.

i have an automated method of taking the frontier data provided to us and turning it into the engineers list.

I'm going to close this now, and do another small point update this week with the corrected tables.
