### ISSUE TITLE
Minor mistake in Wiki contributing guide.

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#1974]
After you say 
Clone your forked repo from Git Bash. Create an upstream remote to the main remote repo

I'm pretty sure you mean for the following example command line to read

$ git clone http....

not just

$ clone http....

Confused me for a minute or two...

Edit: 

And then before adding the upstream a 

$ cd EDDiscovery 

is required.

**Comment by klightspeed** [comment]
I have fixed those items on that page.
