### ISSUE TITLE
Enhancement - Correct name of Aisling promotional materials

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#1977]
Per the following journal entry:

![eddis](https://user-images.githubusercontent.com/38956076/40896574-9d284474-67ad-11e8-9111-d8f52993335f.png)

{"timestamp":"2018-06-04T03:01:26Z","event":"PowerplayDeliver","Power":"Aisling Duval","Type":"$aislingpromotionalmaterials_name;","Type_Localised":"Aisling Programme Materials","Count":150}

EDDiscovery seems to convert a lot of the $sometag that appears in the journal and expand that to the full names in the history (e.g. $ShipName_Police_Empire is shown as Internal Security Service). 

Can $aislingpromotionalmaterials_name also be converted, so to read "Aisling Programme Materials" as per attached screenshot. Alternatively, it might be more correct to display the Type_Localised field in the information, rather than the Type

![aisling](https://user-images.githubusercontent.com/38956076/40896489-35c606c2-67ad-11e8-9f95-398e099f9e16.png)

**Comment by robbyxp1** [comment]
Thanks for the report. Will be fixed in 10.1
