### ISSUE TITLE
Feature Request: Import EDSM route information

### ISSUE THREAD

**Issue by CmdrZach** [EDDiscovery/EDDiscovery#198]
EDSM now allows route information to be stored and displayed. It would be nice to be able to import this data in the ROUTES tab on EDD, set a colour for it and view on the 3d/2d maps. 

Ideally select multiple routes with multiple colours.

[http://www.edsm.net/galactic-routes](http://www.edsm.net/galactic-routes)

**Comment by RedfoxCh** [comment]
I like this! I suppose by 'import' (sounds like doing this once) you mean 'load' (as in always getting the latest info from EDSM as the master data owner, e.g. at the beginning of every the EDD session).

Having an option to toggle the lines between the waypoints/systems (on|off) would be great, too.

**Comment by klightspeed** [comment]
Unfortunately, the routes in http://www.edsm.net/galactic-routes are not currently exposed in http://www.edsm.net/galactic-mapping/json, and http://www.edsm.net/galactic-routes/json does not exist.

@AnthorNet are there any plans to expose public and/or private routes via an API?

**Comment by AnthorNet** [comment]
It is planned to add a copy key so you can paste it in EDD, then we will provide an API to request that key.

**Comment by RedfoxCh** [comment]
@AnthorNet Would you mind sharing the reasoning behind chosing that approach? Being naive, I would have expected a drop-down (or sth like that) in EDD, showing all available routes, from where the desired route can be selected. Much like the "Select Maps" feature on the 3D map.

**Comment by AnthorNet** [comment]
Cause I do not use EDD, so I'm not always aware of how things work.

Providing a key fishery an API seems to me the easiest way for other software and EDD to grab specific routes from EDSM, surely a listing of public routes could be made available too.

**Comment by klightspeed** [comment]
@RedfoxCh I think @finwen is curating the maps - they are separate to EDSM.
EDDiscovery isn't part of EDSM - to EDSM it is a third-party application that uses the APIs that EDSM provides.

In #202, I have implemented a saved route / expedition page.
We could have a json file or something similar to hold the common routes such as those in the EDDiscovery maps.
For the routes on EDSM, it shouldn't be too hard to copy the list of systems into the saved route / expedition page.
I am looking to link the expedition start/end times from the saved expeditions to the map and travel log filters.

**Comment by RedfoxCh** [comment]
Hmmm... I guess I must be a little slow then. A simple way to do this IMHO would seem to be for EDSM to expose a) the list of available routes and b) the list of systems (incl. attributes) per specific route.

The only downside I see is the additional need for authorisation of a CMDR's non-public routes, which of course would need to take into accound the requesting CMDR.

I'll leave my 2c at that - honestly, no need to drag me along when you've already got a viable solution worked out :-)

**Comment by robbyxp1** [comment]
Any action on this or close?
