### ISSUE TITLE
Cargo count not updated with missions

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1985]
My cargo count got out of sync, even suggesting I had 6/4 at one point :)

I think what's happening is that whilst the count increases when you collect stuff like black boxes, it's not being decremented when you turn them over for missions as opposed to selling in the market (where it decrements correctly)

Example - I just did a 2 black box run mission;
![img](https://i.imgur.com/VtZ8f81.png)

![img](https://i.imgur.com/Gb2wxPr.png)

**Comment by klightspeed** [comment]
Would it please be possible to get the journal events associated with the turn-in of the mission?

**Comment by Disorganise** [comment]
{"timestamp":"2018-06-10T00:36:48Z","event":"MissionCompleted","Faction":"LTT 198 Order","Name":"MISSION_Salvage_Illegal_name","MissionID":389404166,"Commodity":"$USSCargoBlackBox_Name;","Commodity_Localised":"Black Box","Count":2,"DestinationSystem":"LTT 9795","Reward":36287,"FactionEffects":[{"Faction":"LTT 198 Order","Effects":[{"Effect":"$MISSIONUTIL_Interaction_Summary_boom_up;","Effect_Localised":"$#MinorFaction; are experiencing increased growth that could lead to an economic boom","Trend":"UpGood"}],"Influence":[{"SystemAddress":11666070513065,"Trend":"UpGood"}],"Reputation":"UpGood"},{"Faction":"Order of LTT 9795","Effects":[],"Influence":[{"SystemAddress":3107509441242,"Trend":"DownBad"}],"Reputation":"DownBad"}]}

**Comment by Disorganise** [comment]
another example
{ "timestamp":"2018-06-09T07:56:10Z", "event":"MissionCompleted", "Faction":"LTT 198 Order", "Name":"Chain_HelpFinishTheOrder_name", "MissionID":389106314, "Commodity":"$Superconductors_Name;", "Commodity_Localised":"Superconductors", "Count":2, "DestinationSystem":"Arngi", "DestinationStation":"Otto Vision", "Reward":91895, "FactionEffects":[ { "Faction":"Friends of Arngi", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_boom_up;", "Effect_Localised":"$#MinorFaction; are experiencing increased growth that could lead to an economic boom", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":13865093768617, "Trend":"UpGood" } ], "Reputation":"UpGood" }, { "Faction":"LTT 198 Order", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_boom_up;", "Effect_Localised":"$#MinorFaction; are experiencing increased growth that could lead to an economic boom", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":11666070513065, "Trend":"UpGood" } ], "Reputation":"UpGood" } ] }
