### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by RalphVargr** [EDDiscovery/EDDiscovery#1987]
### Exception Details:
>EDDiscovery v10.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlSpanel.DrawHistoryEntry(HistoryEntry he, Int32 rowpos, Int32 rowheight, Point3D tpos, Color textcolour, Color backcolour) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 344
>   at EDDiscovery.UserControls.UserControlSpanel.Display(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 318
>   at EDDiscovery.UserControls.UserControlSpanel.NewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 549
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 460
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 439
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
>===== END =====
>```

**Comment by klightspeed** [comment]
That suggests that `JournalEntry.EventSummaryName` isn't being filled.  It looks like this occurs when FSD jumps are synced from EDSM.  #1992 and #1993 should fix this.
