### ISSUE TITLE
interdictor vs interdictor_localised

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#1989]
Here's another event which seems to need to use the "_localised" data. Similar to #1977 

{"timestamp":"2018-06-12T15:23:39Z","event":"Interdicted","Submitted":true,"Interdictor":"$ShipName_Military_Empire;","Interdictor_Localised":"Imperial Navy Vessel","IsPlayer":false,"Faction":"Black Ram"}

**Comment by robbyxp1** [comment]
Fixed thanks on tip
