### ISSUE TITLE
Feature Request: Ability to pull private comments from EDSM back into EDD

### ISSUE THREAD

**Issue by CmdrZach** [EDDiscovery/EDDiscovery#199]
that it all.

**Comment by klightspeed** [comment]
At the moment, EDDiscovery doesn't link notes to any commander, while EDSM private comments are linked to a commander.

Should notes be linked to a particular commander?  If not, what should happen if more than one of the user's commanders have a private comment on the system, or EDSM has a private comment on a system where EDDiscovery already has a note?  Should the most recent private comment take precedence, regardless of source?

**Comment by CmdrZach** [comment]
Maybe select on import which commander to import them to? Also, they will be stored on EDSM under a commander name, so default to that? Or only allow import to the correct commander name or just whatever local commander is selected when import comments is chosen?

All I know is I enter comments in EDD as me, it exports them to EDSM on my commander name, and I would like to get them back: After  a rebuild and losing my comments, and now a corrupt database and losing all my new comments......

**Comment by klightspeed** [comment]
Resolved in PR 200
