### ISSUE TITLE
How to not update a info all planet?

### ISSUE THREAD

**Issue by KingRider** [EDDiscovery/EDDiscovery#1990]
i need update a planet discovery and all, not working update

Example a system Daibais

eddb list:
https://eddb.io/system/bodies/3968

screenshot:
https://i.imgur.com/X3Cm8Vv.png

**Comment by klightspeed** [comment]
In pre-discovered systems, you need to scan the nav beacon.

**Comment by KingRider** [comment]
But a new planet discovery not exist nav beacon more 5kk yl 😥😥

**Comment by klightspeed** [comment]
Systems that have stations should always have a nav beacon orbiting the arrival star.

**Comment by KingRider** [comment]
thanks! work a fine.
