### ISSUE TITLE
Unhandled UI Exception+Inara send problems

### ISSUE THREAD

**Issue by NecroBones** [EDDiscovery/EDDiscovery#1994]
Right after starting up with 10.1, and adding Inara info, and then clicked the button to send historic Inara data:

### Exception Details:
>EDDiscovery v10.1.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.Inara.InaraSync.HistoricList(HistoryList history) in C:\Code\EDDiscovery\EliteDangerous\Inara\InaraSync.cs:line 114
>   at EliteDangerousCore.Inara.InaraSync.HistoricData(Action`1 logger, HistoryList history, EDCommander cmdr) in C:\Code\EDDiscovery\EliteDangerous\Inara\InaraSync.cs:line 57
>   at EDDiscovery.EDDiscoveryForm.sendHistoricDataToInaraToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 1187
>   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
You have no ships stored.. okay i'll protect against that.  At least its in the historic upload.

**Comment by robbyxp1** [comment]
Does it always happen? did it happen during loading?

**Comment by NecroBones** [comment]
This is happening whenever I try to sync the historical data. As long as I don't click that, everything seems to be happy.

**Comment by NecroBones** [comment]
Also, no stored ships? I have every ship in the game, just not at the base I last docked at.

**Comment by robbyxp1** [comment]
It's a strange bug. In the panel ships and loadouts, does it list all your ships?

The item it's excepting on should always be available.

**Comment by robbyxp1** [comment]
If you have ships listed..

**Comment by NecroBones** [comment]
Yeah, something strange is going on with the ships+loadout panel. I don't usually look at it. It seems to be showing my current ship OK, but the selection drop-down shows some as a number only (no ship name), and selecting one, I got:

There was an unhandled UI exception.

==== BEGIN ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteDangerousCore.ShipModuleData.GetShipProperties(String fdshipname) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\ShipModuleData.cs:line 49
   at EliteDangerousCore.ShipInformation.HullMass() in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\ShipInformation.cs:line 200
   at EDDiscovery.UserControls.UserControlModules.DisplayShip(ShipInformation si) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlModules.cs:line 191
   at EDDiscovery.UserControls.UserControlModules.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlModules.cs:line 179
   at EDDiscovery.UserControls.UserControlModules.comboBoxHistoryWindow_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlModules.cs:line 326
   at ExtendedControls.ComboBoxCustom._cbsystem_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\Controls\ComboBoxCustom.cs:line 569
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at ExtendedControls.ComboBoxCustom._customdropdown_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\Controls\ComboBoxCustom.cs:line 544
   at ExtendedControls.DropDownCustom._listcontrol_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\Controls\DropDownCustom.cs:line 67
   at ExtendedControls.ListControlCustom.OnMouseClick(MouseEventArgs e) in C:\Code\EDDiscovery\ExtendedControls\Controls\ListControlCustom.cs:line 309
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====

**Comment by NecroBones** [comment]
All of my ships appear OK toward the end of the list, but at the top, they're just numbers, and I think they're probably ships I've since sold or something.
![shiplist](https://user-images.githubusercontent.com/10134364/41435264-414e3d10-6fec-11e8-92b8-f20ee160d4e6.jpg)

**Comment by NecroBones** [comment]
Actually I think they're all SRVs that I've since lost due to selling the hangar modules.

**Comment by Disorganise** [comment]
I get this too.  Signed up for Inara just now :)  Set up EDD and it sent 3 events.  Went to send history and got the same crash at line 114

I also have 'blank' items in the ship list:
![img](https://i.imgur.com/5SoGQc9.png)

**Comment by robbyxp1** [comment]
Anyone want to zip up ALL of their journal .log files and send them to me, its the quickest way to work out how these empty entries got into the logs..

**Comment by klightspeed** [comment]
Exception on line 49 suggests `fdshipname` is null.

`ModuleBuy`, `ModuleSell`, `ModuleSwap`, `ModuleStore`, `ModuleRetrieve`, `MassModuleStore` will create an empty ship if the ship hasn't been seen.  This could also explain the missing ship names.

`ShipInformation` is only created in `ShallowClone` and `EnsureShip`.  In both cases, ShipFD is available (it's used in the ship information list key), but is not passed to the constructor.

It looks like we should also completely ignore the ship details when the `LoadGame` event has the player starting in the SRV or fighter.

**Comment by robbyxp1** [comment]
Yep, we have a fix in for the ModuleBuy stuff.. coming up today in 10.1.1.  I've reproduced the empty entry problem.

**Comment by Disorganise** [comment]
do you still need the journals?  (just saw the message)

**Comment by NecroBones** [comment]
In case they're still needed, my journals are here: https://edastro.com/tmp/journals-20180615.zip

**Comment by robbyxp1** [comment]
Yep you can delete them now many thanks

**Comment by robbyxp1** [comment]
Your log pointed out a frontier localisation error which i picked over Necrobones. Thanks

**Comment by Disorganise** [comment]
Just updated to 10.1.1 portable.
Hit the send history to Inara and the main log window spat out the following (there's no unhandled error so perhaps this should be a different issue ticket - let me know and I'll repost)

INARA Send Error: Error to request setCommanderShipLoadout {
  "eventName": "setCommanderShipLoadout",
  "eventTimestamp": "2018-06-15T21:47:10.303292Z",
  "eventData": {
    "shipType": "Type6",
    "shipGameID": 18,
    "shipLoadout": [
      {
        "slotName": "Slot07_Size2",
        "itemName": "Int_dockingcomputer_standard"
      },
      {
        "slotName": "Slot06_Size2",
        "itemName": "Int_cargorack_size2_class1"
      },
      {
        "slotName": "Slot03_Size4",
        "itemName": "Int_shieldgenerator_size4_class5"
      },
      {
        "slotName": "Slot04_Size4",
        "itemName": "Int_cargorack_size4_class1"
      },
      {
        "slotName": "Slot02_Size5",
        "itemName": "Int_cargorack_size5_class1"
      },
      {
        "slotName": "Slot01_Size5",
        "itemName": "Int_cargorack_size5_class1"
      },
      {
        "slotName": "PowerPlant",
        "itemName": "Int_powerplant_size3_class5"
      },
      {
        "slotName": "MainEngines",
        "itemName": "Int_engine_size4_class5"
      },
      {
        "slotName": "LifeSupport",
        "itemName": "Int_lifesupport_size2_class2"
      },
      {
        "slotName": "PowerDistributor",
        "itemName": "Int_powerdistributor_size3_class5"
      },
      {
        "slotName": "Radar",
        "itemName": "Int_sensors_size2_class2"
      },
      {
        "slotName": "PaintJob",
        "itemName": "paintjob_type6_blackfriday_01"
      },
      {
        "slotName": "Decal1",
        "itemName": "decal_distantworlds"
      },
      {
        "slotName": "SmallHardpoint1",
        "itemName": "Hpt_beamlaser_turret_small"
      },
      {
        "slotName": "TinyHardpoint1",
        "itemName": "Hpt_cloudscanner_size0_class1"
      }
    ]
  }
} with Unable to erase the ship loadout.
Error to request setCommanderShip {
  "eventName": "setCommanderShip",
  "eventTimestamp": "2018-06-15T21:47:10.303292Z",
  "eventData": {
    "shipType": "Type6",
    "shipGameID": 18,
    "isCurrentShip": false,
    "starsystemName": "Nang Di",
    "stationName": "Ziegler Orbital"
  }
} with Unable to erase the ship loadout.
Error to request setCommanderShipLoadout {
  "eventName": "setCommanderShipLoadout",
  "eventTimestamp": "2018-06-15T21:47:10.303292Z",
  "eventData": {
    "shipType": "Asp",
    "shipGameID": 19,
    "shipLoadout": [
      {
        "slotName": "PowerDistributor",
        "itemName": "Int_PowerDistributor_Size3_Class5",
        "itemValue": 158331,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 0
      },
      {
        "slotName": "Radar",
        "itemName": "Int_Sensors_Size5_Class2",
        "itemValue": 79444,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 0
      },
      {
        "slotName": "Slot07_Size2",
        "itemName": "Int_StellarBodyDiscoveryScanner_Advanced",
        "itemValue": 1545000,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 1
      },
      {
        "slotName": "Slot03_Size3",
        "itemName": "Int_ShieldGenerator_Size3_Class5",
        "itemValue": 507912,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 0
      },
      {
        "slotName": "Slot05_Size3",
        "itemName": "Int_DetailedSurfaceScanner_Tiny",
        "itemValue": 250000,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 1
      },
      {
        "slotName": "Decal1",
        "itemName": "Decal_DistantWorlds",
        "itemValue": 0,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 1
      },
      {
        "slotName": "PowerPlant",
        "itemName": "Int_Powerplant_Size4_Class5",
        "itemValue": 1610080,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 1
      },
      {
        "slotName": "Slot06_Size2",
        "itemName": "Int_DockingComputer_Standard",
        "itemValue": 4500,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 3
      },
      {
        "slotName": "LifeSupport",
        "itemName": "Int_LifeSupport_Size4_Class2",
        "itemValue": 28373,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 0
      },
      {
        "slotName": "WeaponColour",
        "itemName": "WeaponCustomisation_Purple",
        "itemValue": 0,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 1
      },
      {
        "slotName": "FrameShiftDrive",
        "itemName": "Int_Hyperdrive_Size5_Class5",
        "itemValue": 5103953,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 0
      },
      {
        "slotName": "Slot02_Size5",
        "itemName": "Int_FuelScoop_Size5_Class5",
        "itemValue": 8846852,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 0
      },
      {
        "slotName": "MainEngines",
        "itemName": "Int_Engine_Size5_Class5",
        "itemValue": 5103953,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 0
      },
      {
        "slotName": "Decal2",
        "itemName": "Decal_Explorer_Elite",
        "itemValue": 0,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 1
      },
      {
        "slotName": "PaintJob",
        "itemName": "PaintJob_Asp_Metallic_Gold",
        "itemValue": 0,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 1
      },
      {
        "slotName": "Slot01_Size6",
        "itemName": "Int_CargoRack_Size6_Class1",
        "itemValue": 353527,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 1
      },
      {
        "slotName": "Slot04_Size3",
        "itemName": "Int_CargoRack_Size3_Class1",
        "itemValue": 10299,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 1
      },
      {
        "slotName": "TinyHardpoint2",
        "itemName": "Hpt_PlasmaPointDefence_Turret_Tiny",
        "itemValue": 18083,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 0,
        "itemAmmoClip": 12,
        "itemAmmoHopper": 10000
      },
      {
        "slotName": "TinyHardpoint3",
        "itemName": "Hpt_PlasmaPointDefence_Turret_Tiny",
        "itemValue": 18083,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 0,
        "itemAmmoClip": 12,
        "itemAmmoHopper": 10000
      },
      {
        "slotName": "MediumHardpoint1",
        "itemName": "Hpt_PulseLaser_Gimbal_Medium",
        "itemValue": 34515,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 0,
        "itemAmmoClip": 1,
        "itemAmmoHopper": 1
      },
      {
        "slotName": "TinyHardpoint1",
        "itemName": "Hpt_CrimeScanner_Size0_Class1",
        "itemValue": 13206,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 0
      },
      {
        "slotName": "Armour",
        "itemName": "Asp_Armour_Grade1",
        "itemValue": 0,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 1
      },
      {
        "slotName": "CargoHatch",
        "itemName": "ModularCargoBayDoor",
        "itemValue": 0,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 1
      },
      {
        "slotName": "FuelTank",
        "itemName": "Int_FuelTank_Size5_Class3",
        "itemValue": 97754,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 1
      },
      {
        "slotName": "PlanetaryApproachSuite",
        "itemName": "Int_PlanetApproachSuite",
        "itemValue": 500,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 1
      },
      {
        "slotName": "ShipCockpit",
        "itemName": "Asp_Cockpit",
        "itemValue": 0,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 1
      },
      {
        "slotName": "TinyHardpoint4",
        "itemName": "Hpt_ShieldBooster_Size0_Class5",
        "itemValue": 273975,
        "itemHealth": 100,
        "isOn": true,
        "itemPriority": 0
      }
    ]
  }
} with Unable to erase the ship loadout.
Error to request setCommanderShip {
  "eventName": "setCommanderShip",
  "eventTimestamp": "2018-06-15T21:47:10.303292Z",
  "eventData": {
    "shipType": "Asp",
    "shipGameID": 19,
    "isCurrentShip": false,
    "starsystemName": "Shinrarta Dezhra",
    "stationName": "Jameson Memorial"
  }
} with Unable to erase the ship loadout.

**Comment by Disorganise** [comment]
Inara did receive my ships though :)   well, 16/19 anyways (EDSM has 15.  and they're different.  EDSM has my adder, inara does not)

**Comment by klightspeed** [comment]
Does Inara have the ships where it logged `Unable to erase the ship loadout`?

**Comment by Disorganise** [comment]
No.  Ship IDs 18&19, T6 at Nang Di and Asp at Shinrarta Dezhra are not in Inara

**Comment by klightspeed** [comment]
With the ships above, with 10.1.0 were there SRVs in slots 18 and 19?  I wonder if Inara is choking on those SRVs, and refusing to replace them with the proper ships?

**Comment by Disorganise** [comment]
Doesn't look like it.  19 is the Asp, 18 is there twice, having been sold once:
![img](https://i.imgur.com/WZq1SDN.png)

The adder shows above 10.1.0 and below in 10.1.1 as slot 27 in the right location
![img](https://i.imgur.com/91U3vTu.png)

**Comment by klightspeed** [comment]
If you look for `inara.cz` in the latest `*.hlog` file in the `Log` directory in the EDDiscovery data directory (`Data` for the portable install, or `%LocalAppData%\EDDiscovery` for the installed version), it should log the POST request containing the ships and loadouts sent to Inara.  Is there a `setCommanderShip` and `setCommanderShipLoadout` for `"shipGameID": 27`?

**Comment by Disorganise** [comment]
Search for "shipGameID": 27 in the HLOG is negative

**Comment by klightspeed** [comment]
If the other ships do show up in the .hlog file, then that suggests the ship is being filtered out.

When submitted using `Send Historic Data To Inara`, ships are filtered out if they have a subvehicle set, or they are sold or destroyed, or they are a SRV or fighter.

If you select the Adder, does it show something like `Adder (27) in SRV`?

**Comment by klightspeed** [comment]
It looks like Elite Dangerous sometimes failed to write `SRVDock` or `SRVDestroyed` events.  I have one such thing where I touched down and launched my SRV, then a few minutes later had a disconnect, then shortly after loading back in had my SRV destroyed.  We should reset the subvehicle when a `SupercruiseEntry` event is logged.

```
{ "timestamp":"2016-10-30T17:04:11Z", "event":"ApproachSettlement", "Name":"Hoffman Oasis" }
{ "timestamp":"2016-10-30T17:04:25Z", "event":"SupercruiseExit", "StarSystem":"Kenyamuna", "Body":"Kenyamuna 2 a", "BodyType":"Planet" }
{ "timestamp":"2016-10-30T17:05:30Z", "event":"Touchdown", "Latitude":40.365307, "Longitude":-149.846954 }
{ "timestamp":"2016-10-30T17:09:25Z", "event":"LoadGame", "Commander":"Traumatophobiac", "Ship":"Hauler", "ShipID":2, "StartLanded":true, "GameMode":"Solo", "Credits":868590, "Loan":0 }
{ "timestamp":"2016-10-30T17:09:25Z", "event":"Rank", "Combat":0, "Trade":2, "Explore":3, "Empire":0, "Federation":0, "CQC":0 }
{ "timestamp":"2016-10-30T17:09:25Z", "event":"Progress", "Combat":0, "Trade":16, "Explore":51, "Empire":0, "Federation":2, "CQC":0 }
{ "timestamp":"2016-10-30T17:09:29Z", "event":"ApproachSettlement", "Name":"Hoffman Oasis" }
{ "timestamp":"2016-10-30T17:10:07Z", "event":"Location", "Docked":false, "StarSystem":"Kenyamuna", "StarPos":[24.250,57.688,-145.594], "Allegiance":"Federation", "Economy":"$economy_Military;", "Economy_Localised":"Military", "Government":"$government_Confederacy;", "Government_Localised":"Confederacy", "Security":"$SYSTEM_SECURITY_low;", "Security_Localised":"Low Security", "Body":"Kenyamuna 2 a", "BodyType":"Planet", "Faction":"Coalition of Kenyamuna" }
{ "timestamp":"2016-10-30T17:10:07Z", "event":"Touchdown", "Latitude":40.365307, "Longitude":-149.846954 }
{ "timestamp":"2016-10-30T17:10:27Z", "event":"LaunchSRV", "Loadout":"starter", "PlayerControlled":true }
{ "timestamp":"2016-10-30T17:14:24Z", "event":"HullDamage", "Health":0.617051 }
{ "timestamp":"2016-10-30T17:14:50Z", "event":"LoadGame", "Commander":"Traumatophobiac", "Ship":"TestBuggy", "ShipID":3, "StartLanded":true, "GameMode":"Solo", "Credits":868590, "Loan":0 }
{ "timestamp":"2016-10-30T17:14:50Z", "event":"Rank", "Combat":0, "Trade":2, "Explore":3, "Empire":0, "Federation":0, "CQC":0 }
{ "timestamp":"2016-10-30T17:14:50Z", "event":"Progress", "Combat":0, "Trade":16, "Explore":51, "Empire":0, "Federation":2, "CQC":0 }
{ "timestamp":"2016-10-30T17:14:53Z", "event":"ApproachSettlement", "Name":"Hoffman Oasis" }
{ "timestamp":"2016-10-30T17:15:16Z", "event":"Location", "Docked":false, "StarSystem":"Kenyamuna", "StarPos":[24.250,57.688,-145.594], "Allegiance":"Federation", "Economy":"$economy_Military;", "Economy_Localised":"Military", "Government":"$government_Confederacy;", "Government_Localised":"Confederacy", "Security":"$SYSTEM_SECURITY_low;", "Security_Localised":"Low Security", "Body":"Kenyamuna 2 a", "BodyType":"Planet", "Faction":"Coalition of Kenyamuna" }
{ "timestamp":"2016-10-30T17:15:44Z", "event":"HullDamage", "Health":0.595873 }
{ "timestamp":"2016-10-30T17:17:26Z", "event":"HullDamage", "Health":0.382701 }
{ "timestamp":"2016-10-30T17:18:58Z", "event":"DatalinkScan", "Message":"$DATAPOINT_GAMEPLAY_complete;", "Message_Localised":"Alert: All Data Point telemetry links established, Intel package created." }
{ "timestamp":"2016-10-30T17:18:58Z", "event":"DataScanned", "Type":"DataPoint" }
{ "timestamp":"2016-10-30T17:23:22Z", "event":"HullDamage", "Health":0.193747 }
{ "timestamp":"2016-10-30T17:24:07Z", "event":"ApproachSettlement", "Name":"Hoffman Oasis" }
{ "timestamp":"2016-10-30T17:24:32Z", "event":"Location", "Docked":false, "StarSystem":"Kenyamuna", "StarPos":[24.250,57.688,-145.594], "Allegiance":"Federation", "Economy":"$economy_Military;", "Economy_Localised":"Military", "Government":"$government_Confederacy;", "Government_Localised":"Confederacy", "Security":"$SYSTEM_SECURITY_low;", "Security_Localised":"Low Security", "Body":"Kenyamuna 2 a", "BodyType":"Planet", "Faction":"Coalition of Kenyamuna" }
{ "timestamp":"2016-10-30T17:25:28Z", "event":"SupercruiseEntry", "StarSystem":"Kenyamuna" }
```

**Comment by Disorganise** [comment]
> If you select the Adder, does it show something like Adder (27) in SRV?

yes:
![img](https://i.imgur.com/Lw3QZBN.png)

**Comment by mydevpeeps** [comment]
#### Description

I got a new error today while filtering my journal my the search term "mission".

### Additional Information


### Exception Details:
>EDDiscovery v10.1.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlJournalGrid.CreateHistoryRow(HistoryEntry item, String search) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlJournalGrid.cs:line 260
>   at EDDiscovery.UserControls.UserControlJournalGrid.Display(HistoryList hl, Boolean disablesorting) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlJournalGrid.cs:line 162
>   at EDDiscovery.UserControls.UserControlJournalGrid.Searchtimer_Tick(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlJournalGrid.cs:line 311
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>````

**Comment by robbyxp1** [comment]
Closed
