### ISSUE TITLE
EDDiscovery v10.1.0.0 There was an unhandled UI exception

### ISSUE THREAD

**Issue by mydevpeeps** [EDDiscovery/EDDiscovery#1997]
* This was happening with v10.0.0.3 & v10.0.0.4 as well. It pops up about 20 times a day.

### Exception Details:
>EDDiscovery v10.1.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlSpanel.DrawHistoryEntry(HistoryEntry he, Int32 rowpos, Int32 rowheight, Point3D tpos, Color textcolour, Color backcolour) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 349
>   at EDDiscovery.UserControls.UserControlSpanel.Display(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 318
>   at EDDiscovery.UserControls.UserControlSpanel.NewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 549
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 454
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 433
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
>===== END =====
>```

**Comment by mydevpeeps** [comment]
Also, I see this in my Log when it happens:
"Companion API get failed: Object reference not set to an instance of an object."

**Comment by mydevpeeps** [comment]
Based on what others in similar threads have stated, I went ahead and closed my SHIP/LOADOUT tab because I don't usually have that open, and this started happening around the same time I started using it. I will let you know if it helps or not.

**Comment by robbyxp1** [comment]
This is probably related to #1991 bug.  10.1.1 will have that bug fixed.

**Comment by mydevpeeps** [comment]
Could be. I haven't' had the error pop up since i closed the ship loadout tab. Do you need any files from me?

**Comment by robbyxp1** [comment]
Closed, open another ticket if it comes back.
