### ISSUE TITLE
EDDiscovery v10.1.0.0- Inara Sync Issue

### ISSUE THREAD

**Issue by Nemaroth** [EDDiscovery/EDDiscovery#1999]
### Description
Send Inara Historic Data from the menu.

### Exception Details:
>EDDiscovery v10.1.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.Inara.InaraSync.HistoricList(HistoryList history) in C:\Code\EDDiscovery\EliteDangerous\Inara\InaraSync.cs:line 114
>   at EliteDangerousCore.Inara.InaraSync.HistoricData(Action`1 logger, HistoryList history, EDCommander cmdr) in C:\Code\EDDiscovery\EliteDangerous\Inara\InaraSync.cs:line 57
>   at EDDiscovery.EDDiscoveryForm.sendHistoricDataToInaraToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 1187
>   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
It looks like this is the same exception as in the original post of #1994

**Comment by klightspeed** [comment]
This should be fixed in 10.1.1
