### ISSUE TITLE
Feature Request: Export to CSV

### ISSUE THREAD

**Issue by Red13x3** [EDDiscovery/EDDiscovery#20]
Synopsis: In the Tools Menu, have an option to "Export to CSV" that exports all data saved relating to the Systems in the Travel History list.

Reasoning: I am soooo close to giving up running Excel while I play Elite... BUT... I'm worried that all this data I'm saving in EDD and not in Excel... That I have no backup at all!  Please, provide some way to export all the Travel History data out to an Excel compatible CSV file (or Tab delimited) file.  Please include the following fields:

Time
System
Notes
Visits
Allegiance

And if the extra fields I have suggested get added, like the Sold Data $ and any other fields the user might add if that functionality is added...

**Comment by gregmalcolm** [comment]
Sounds useful, but in the interim theres a workaround: 

* Install SQLite Browser, 
* Locate and load the db file (for me it's in `C:/users/<user>/AppData/Local/EDDiscovery/EDDiscovery.sqlite`)
* Export the `VisitedSystems` and `SystemNotes` tables

**Comment by robbyxp1** [comment]
Closed for 122
