### ISSUE TITLE
EDDiscovery v10.1.0.0 - Periodic Inara Update Issue during CG

### ISSUE THREAD

**Issue by Nemaroth** [EDDiscovery/EDDiscovery#2000]
INARA Send Error: Error to request setCommanderCommunityGoalProgress {
  "eventName": "setCommanderCommunityGoalProgress",
  "eventTimestamp": "2018-06-15T17:32:51Z",
  "eventData": {
    "communitygoalGameID": 505,
    "contribution": 701,
    "percentileBand": 0,
    "percentileBandReward": 1000000
  }
} with Some properties like percentileBand, etc. are missing.

This shows up in the log window. It looks like whenever I enter a new system or dock at a station.

**Comment by klightspeed** [comment]
I wonder if Inara is using `eventData["percentileBand"] == null` in PHP?  That would treat community goals that have not passed the first percentile band as invalid.

**Comment by robbyxp1** [comment]
On Monday I'll point Artie towards this..

**Comment by Nemaroth** [comment]
Thought I would add I'm still seeing this even after the CG has been going on a few days.

INARA Send Error: Error to request setCommanderCommunityGoalProgress {
  "eventName": "setCommanderCommunityGoalProgress",
  "eventTimestamp": "2018-06-17T14:59:04Z",
  "eventData": {
    "communitygoalGameID": 505,
    "contribution": 1472,
    "percentileBand": 0,
    "percentileBandReward": 3800000
  }
} with Some properties like percentileBand, etc. are missing.

**Comment by klightspeed** [comment]
Would it please be possible to get the associated `CommunityGoal` journal event?

**Comment by Nemaroth** [comment]
{"timestamp":"2018-06-17T18:30:53Z","event":"CommunityGoal","CurrentGoals":[{"CGID":505,"Title":"Refugee Centre Initiative","SystemName":"Niflhel","MarketName":"Biruni Port","Expiry":"2018-06-21T15:00:00Z","IsComplete":false,"CurrentTotal":2735383,"PlayerContribution":20224,"NumContributors":1537,"TopTier":{"Name":"Tier 8","Bonus":""},"TopRankSize":10,"PlayerInTopRank":true,"TierReached":"Tier 3","PlayerPercentileBand":0,"Bonus":3800000}]}

**Comment by Nemaroth** [comment]
INARA Send Error: Error to request setCommanderCommunityGoalProgress {
  "eventName": "setCommanderCommunityGoalProgress",
  "eventTimestamp": "2018-06-17T18:30:53Z",
  "eventData": {
    "communitygoalGameID": 505,
    "contribution": 1537,
    "percentileBand": 0,
    "percentileBandReward": 3800000
  }
} with Some properties like percentileBand, etc. are missing.
