### ISSUE TITLE
Add option to send historic jumps, docks and missions to Inara

### ISSUE THREAD

**Issue by klightspeed** [EDDiscovery/EDDiscovery#2001]
It has been suggested on Discord to add the option to send historic jumps, docks and missions to Inara.

**Comment by robbyxp1** [comment]
I talked extensively with Artie on what he wanted to be sent..
This is what he wants.. I can ask if we can send historic jumps but it prob won't work at the moment as he will prob reject them due to timestamp

**Comment by robbyxp1** [comment]
Artie will need to add a historic jump API as he rejects stuff in the past..

**Comment by robbyxp1** [comment]
Word back is that its not currently supportable, and we can't do it.  If it changes we can re-open the issue.
Cheers
