### ISSUE TITLE
Unhandled Journal Event

### ISSUE THREAD

**Issue by Wizlon** [EDDiscovery/EDDiscovery#2002]
{
  "timestamp": "2018-06-16T19:18:30Z",
  "event": "PayBounties",
  "Amount": 200,
  "Faction": "$faction_Empire;",
  "Faction_Localised": "Empire",
  "ShipID": 5,
  "BrokerPercentage": 25.0
}

**Comment by klightspeed** [comment]
Please try upgrading to the latest version - 10.1.1 -> https://github.com/EDDiscovery/EDDiscovery/releases/latest
