### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by rootsrat** [EDDiscovery/EDDiscovery#2003]
### Exception Details:
>EDDiscovery v10.1.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentException: Only TrueType fonts are supported. This is not a TrueType font.
>   at System.Drawing.Font.FromLogFont(Object lf, IntPtr hdc)
>   at System.Windows.Forms.FontDialog.UpdateFont(LOGFONT lf)
>   at System.Windows.Forms.FontDialog.RunDialog(IntPtr hWndOwner)
>   at System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
>   at ExtendedControls.ThemeStandardEditor.textBox_Font_MouseClick(Object sender, MouseEventArgs e) in C:\Code\EDDiscovery\ExtendedControls\Themes\ThemeStandardEditor.cs:line 198
>   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
>   at System.Windows.Forms.TextBoxBase.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
It looks like this occurs when you select a non-truetype font in the font selection dialog, then try to edit that font.
https://social.msdn.microsoft.com/Forums/vstudio/en-US/e50a3dc2-a9d9-4eea-aae6-39bc7c18b04e/font-dialog-problem-how-can-i-determine-if-font-is-truetype-font?forum=vbgeneral

It looks like this is a Microsoft bug we have to work around.

**Comment by rootsrat** [comment]
No worries, this is when I tried to manually select Euro Caps font for the application.
