### ISSUE TITLE
Show all

### ISSUE THREAD

**Issue by logarou** [EDDiscovery/EDDiscovery#201]
Hi ( excuse me for my bad english :) 
I can see "hide system" in the option but where is show all 
i'have take a mistake !!

thank you
Logarou

**Comment by finwen** [comment]
If you Go to commander you can select Hidden log.   That will show you all
hidden systems

2016-04-30 7:17 GMT+02:00 logarou <notifications@github.com>:

**Comment by robbyxp1** [comment]
Closed
