### ISSUE TITLE
Unhandled UI exception when opening scan grid.

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#2010]
### Description
Opening "scan grid" caused this. Happened in 10.1.0.0 - upgraded to 10.1.1.0 and reproduced. (Obviously, this will have included restarting the program).
This was at system: Col 285 Sector YZ-P d5-119

Was able to "continue", but error repeated for each and every journal entry until scan grid window was closed. Jumped to another system and was able to open the scan grid window without problem - the next 3 systems were unusual in that EDSM had no data[1], but scanned nav beacon and data appeared in scan grid and uploaded to EDSM correctly. 4th system I hit had EDSM data to display and worked as expected.

As everything appeared to be working correctly, I closed and restarted again and had no reoccurrence.

[1] Pre-scanned inhabited systems, I guess nobody had pinged the nav beacon to upload data prior to my visit.

### Exception Details:
>EDDiscovery v10.1.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.FormatException: Input string was not in a correct format.
>   at System.Text.StringBuilder.FormatError()
>   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
>   at System.Text.StringBuilder.AppendFormat(String format, Object[] args)
>   at EliteDangerousCore.JournalEvents.JournalScan.DisplayString(Int32 indent, Boolean includefront, MaterialCommoditiesList historicmatlist, MaterialCommoditiesList currentmatlist) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalScan.cs:line 551
>   at EDDiscovery.UserControls.UserControlScanGrid.DrawSystem() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlScanGrid.cs:line 107
>   at EDDiscovery.UserControls.UserControlScanGrid.Display(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlScanGrid.cs:line 100
>   at EDDiscovery.Forms.UserControlForm.UserControlForm_Shown(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\Forms\UserControlForm.cs:line 281
>   at System.Windows.Forms.Form.OnShown(EventArgs e)
>   at EDDiscovery.Forms.DraggableFormPos.OnShown(EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\Forms\DraggableFormPos.cs:line 160
>   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>===== END =====
>```

**Comment by klightspeed** [comment]
`AppendFormat` was used incorrectly.
