### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by b166er** [EDDiscovery/EDDiscovery#2016]
### Description
add "Summary Panel" as new Tab

### Exception Details:
>EDDiscovery v10.1.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>   bei EDDiscovery.UserControls.UserControlSpanel.DrawHistoryEntry(HistoryEntry he, Int32 rowpos, Int32 rowheight, Point3D tpos, Color textcolour, Color backcolour) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:Zeile 349.
>   bei EDDiscovery.UserControls.UserControlSpanel.Display(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:Zeile 318.
>   bei EDDiscovery.MajorTabControl.AddTab(PanelIDs id, Int32 tabindex) in C:\Code\EDDiscovery\EDDiscovery\MajorTabControl.cs:Zeile 155.
>   bei System.Windows.Forms.Control.OnClick(EventArgs e)
>   bei System.Windows.Forms.Button.OnClick(EventArgs e)
>   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   bei System.Windows.Forms.Control.WndProc(Message& m)
>   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   bei System.Windows.Forms.Button.WndProc(Message& m)
>   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Sam as #1991 please make sure your on 10.1.1 thanks

**Comment by klightspeed** [comment]
`JournalEntry.AddEDDCommodityPrices` does not set `EventSummaryName`

**Comment by klightspeed** [comment]
Please let us know if this still happens with 10.1.2 when it comes out.
