### ISSUE TITLE
send error

### ISSUE THREAD

**Issue by spatula007** [EDDiscovery/EDDiscovery#2020]
hey there, im getting an issue when i plugged in the INARA api:

INARA Send Error: Error to request setCommanderTravelLocation {
  "eventName": "setCommanderTravelLocation",
  "eventTimestamp": "2018-06-18T03:19:41Z",
  "eventData": {
    "starsystemName": "Colonia",
    "stationName": "Dove Enigma",
    "marketID": 128844088
  }
} with No starsystem name provided.

When I tried to upload the history as well, I got a long string that I saw posted in another thread. I'm not sure how to fix, pls advise!

**Comment by robbyxp1** [comment]
Checking

**Comment by robbyxp1** [comment]
Inara confirms problem on their side, its fixed. Thanks for the report.
