### ISSUE TITLE
Missions - Panel Refresh Resets Column Sort

### ISSUE THREAD

**Issue by mydevpeeps** [EDDiscovery/EDDiscovery#2023]
Sort Missions tab by end date, descending. Automatic Panel Refresh triggers, sort order goes back to default (what ever that is). I can leave on the sort filter for materials and other tabs and they stay in place.

**Comment by robbyxp1** [comment]
Will fix. thanks

**Comment by robbyxp1** [comment]
Fixed on 10.2
