### ISSUE TITLE
Unhandled UI exception when opening settings window.

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#2026]
### Description
Was attempting to open up the settings into a new window.

### Additional Information
Already had "default" window and scan grid open as a window. Was at Wredguia TH-U C16-7

### Exception Details:
>EDDiscovery v10.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at ExtendedControls.PictureBoxHotspot.AddTextAutoSize(Point topleft, Size max, String label, Font fnt, Color c, Color backcolour, Single backscale, Object tag, String tiptext) in C:\Code\EDDiscovery\ExtendedControls\Controls\PictureBoxHotspot.cs:line 184
>   at EDDiscovery.UserControls.UserControlSpanel.AddColText(Int32 coli, Int32 nextcol, Int32 rowpos, Int32 rowh, String text, Color textcolour, Color backcolour, String tooltip, Image opt, String imagetooltip) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 485
>   at EDDiscovery.UserControls.UserControlSpanel.Display(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 283
>   at EDDiscovery.UserControls.UserControlSpanel.HideScanData(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 777
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
`scanhide.Tick` is subscribed to in `UserControlSpanel.Init()`, but not unsubscribed to in `UserControlSpanel.Closing()`
