### ISSUE TITLE
Trojan:Win32/Gatrid.E!cl

### ISSUE THREAD

**Issue by Sentynal** [EDDiscovery/EDDiscovery#203]
since 3.1.1 windows defender has been quarantining the installer. The earlier one was clean.

https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fGatrid.E!cl&threatid=2147709345&enterprise=0

"Alert level: Severe
This threat can perform a number of actions of a malicious hacker's choice on your PC.
First published: Feb 22, 2016 
Latest published: Mar 21, 2016"

**Comment by finwen** [comment]
Probably a false positive,. 

Neither  mcaffe aor Kapesrky has found anything on build computer.

**Comment by Sentynal** [comment]
yeah I just ran it through the Virustotal website and only hit 1 positive out of 56. (which I just found) https://www.virustotal.com/en/file/e629348c237d9fbfcd54bab007d09b33ba7de149845b02cf2a8a97b8853e6238/analysis/1462247816/
