### ISSUE TITLE
10.1.2 Salvage Mission Cargo being counted (incorrectly) when accepting the mission

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#2030]
When accepting a salvage mission, the cargo to collect is being added to the cargo count in EDD.  eg, mission below is to collect 2 black boxes.  Upon acceptance, cargo says 2 in EDD (0 in inventory).  when collecting, EDD will say 4 (phantom 2 plus the 2 collected) and when turning in the mission the count goes back to 2 (4-2).
Restarting EDD resets the cargo count.

{"timestamp":"2018-06-24T00:55:16Z","event":"MissionAccepted","Faction":"Iah Lanitei Empire League","Name":"MISSION_Salvage_Refinery","LocalisedName":"Black Box salvage contract for refinery","Commodity":"$USSCargoBlackBox_Name;","Commodity_Localised":"Black Box","Count":2,"DestinationSystem":"Amphisatsu","DestinationStation":"Osterbrock Terminal","Expiry":"2018-06-27T21:13:48Z","Wing":false,"Influence":"Med","Reputation":"Med","Reward":419933,"MissionID":393739034}

**Comment by klightspeed** [comment]
So what is the difference between that journal entry and the one where you were given items to take to another station (#2005)?  If there is no discernable difference, then I'll have to revert #2006.

**Comment by Disorganise** [comment]
There seems to be a few variations.  How many in total, I don't know.  What I found so far:

**Delivery** - So cargo should be added on acceptance, and removed when completed (or die)
"Name":"Mission_Delivery"
"Name":"Mission_Delivery_Boom"
"Name":"Chain_HelpFinishTheOrder"
"Name":"Mission_Delivery_War"


**Retrieval** - So cargo should not be added on acceptance, but should be removed when MissionCompleted (assuming the CollectCargo event adds the cargo)
"Name":"Mission_Collect_Industrial"
"Name":"MISSION_Collect_RankEmp"
"Name":"MISSION_Salvage_Refinery"
"Name":"Mission_Salvage_RankEmp"
"Name":"Mission_Salvage"
"Name":"MISSION_Salvage_Illegal"

Example entries for above
{ "timestamp":"2018-06-17T01:35:00Z", "event":"MissionAccepted", "Faction":"LTT 198 Order", "Name":"Mission_Collect_Industrial", "LocalisedName":"Industry needs 2 units of Polymers", "Commodity":"$Polymers_Name;", "Commodity_Localised":"Polymers", "Count":2, "DestinationSystem":"Kigandan", "DestinationStation":"Vinogradov Port", "Expiry":"2018-06-18T18:19:14Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":10000, "MissionID":391596158 }
{ "timestamp":"2018-06-17T01:35:59Z", "event":"MissionAccepted", "Faction":"Kigandan Silver Brothers", "Name":"Mission_Delivery", "LocalisedName":"Deliver 4 units of Basic Medicines", "Commodity":"$BasicMedicines_Name;", "Commodity_Localised":"Basic Medicines", "Count":4, "TargetFaction":"Brothers of CPO 24", "DestinationSystem":"CPO 24", "DestinationStation":"Heng Terminal", "Expiry":"2018-06-18T01:30:54Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":64814, "MissionID":391596329 }

{ "timestamp":"2018-06-17T00:51:50Z", "event":"MissionAccepted", "Faction":"LTT 198 Order", "Name":"MISSION_Salvage_Refinery", "LocalisedName":"Black Box salvage contract for refinery", "Commodity":"$USSCargoBlackBox_Name;", "Commodity_Localised":"Black Box", "Count":3, "DestinationSystem":"Aninohanu", "DestinationStation":"Bardeen Hangar", "Expiry":"2018-06-22T01:09:57Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":532474, "MissionID":391587001 }

{ "timestamp":"2018-06-23T23:44:19Z", "event":"MissionAccepted", "Faction":"Cordenet Group", "Name":"Mission_Delivery_Boom", "LocalisedName":"Boom time delivery of 6 units of Indium", "Commodity":"$Indium_Name;", "Commodity_Localised":"Indium", "Count":6, "TargetFaction":"Cordenet Group", "DestinationSystem":"Iah Lanitei", "DestinationStation":"Dassault Gateway", "Expiry":"2018-06-24T23:42:29Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":73996, "MissionID":393722855 }

{ "timestamp":"2018-06-24T01:01:37Z", "event":"CollectCargo", "Type":"USSCargoBlackBox", "Type_Localised":"Black Box", "Stolen":false }

{ "timestamp":"2018-06-24T01:24:59Z", "event":"MissionCompleted", "Faction":"Iah Lanitei Empire League", "Name":"MISSION_Salvage_Refinery_name", "MissionID":393739006, "Commodity":"$USSCargoBlackBox_Name;", "Commodity_Localised":"Black Box", "Count":2, "DestinationSystem":"Grabi", "DestinationStation":"Jones Mine", "Reward":417521, "FactionEffects":[ { "Faction":"Iah Lanitei Empire League", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_boom_up;", "Effect_Localised":"$#MinorFaction; are experiencing increased growth that could lead to an economic boom", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":6131300635346, "Trend":"UpGood" }, { "SystemAddress":5856422728402, "Trend":"DownBad" } ], "Reputation":"None" } ] }
{ "timestamp":"2018-06-24T01:25:13Z", "event":"MissionCompleted", "Faction":"Iah Lanitei Empire League", "Name":"MISSION_Salvage_Refinery_name", "MissionID":393739034, "Commodity":"$USSCargoBlackBox_Name;", "Commodity_Localised":"Black Box", "Count":2, "DestinationSystem":"Amphisatsu", "DestinationStation":"Osterbrock Terminal", "Reward":419933, "FactionEffects":[ { "Faction":"Iah Lanitei Empire League", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_boom_up;", "Effect_Localised":"$#MinorFaction; are experiencing increased growth that could lead to an economic boom", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":6131300635346, "Trend":"UpGood" } ], "Reputation":"UpGood" }, { "Faction":"Cordenet Group", "Effects":[  ], "Influence":[ { "SystemAddress":2870782797233, "Trend":"DownBad" } ], "Reputation":"DownBad" } ] }

{ "timestamp":"2018-06-23T14:32:55Z", "event":"MissionAccepted", "Faction":"Cordenet Group", "Name":"Mission_Salvage_RankEmp", "LocalisedName":"Commercial Samples Imperial Navy salvage mission", "Commodity":"$ComercialSamples_Name;", "Commodity_Localised":"Commercial Samples", "Count":2, "DestinationSystem":"Beta Reticuli", "Expiry":"2018-06-27T04:12:51Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":232647, "MissionID":393544283 }

{ "timestamp":"2018-06-20T20:31:45Z", "event":"MissionAccepted", "Faction":"LTT 198 Patrons of Law", "Name":"Mission_Salvage", "LocalisedName":"Black Box salvage operation", "Commodity":"$USSCargoBlackBox_Name;", "Commodity_Localised":"Black Box", "Count":3, "DestinationSystem":"EGM 559", "DestinationStation":"Burke Dock", "Expiry":"2018-06-27T20:30:56Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":692899, "MissionID":392757799 }

{ "timestamp":"2018-06-16T08:24:37Z", "event":"MissionAccepted", "Faction":"LTT 198 Order", "Name":"Chain_HelpFinishTheOrder", "LocalisedName":"Deliver 2 units of Insulating Membrane", "Commodity":"$InsulatingMembrane_Name;", "Commodity_Localised":"Insulating Membrane", "Count":2, "DestinationSystem":"Kappa Phoenicis", "DestinationStation":"Low Gateway", "Expiry":"2018-06-17T08:20:04Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":130330, "MissionID":391306491 }

{ "timestamp":"2018-06-10T00:11:08Z", "event":"MissionAccepted", "Faction":"LTT 198 Order", "Name":"MISSION_Salvage_Illegal", "LocalisedName":"Illegal Black Box salvage operation", "Commodity":"$USSCargoBlackBox_Name;", "Commodity_Localised":"Black Box", "Count":2, "DestinationSystem":"LTT 9795", "Expiry":"2018-06-10T13:49:27Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":36287, "MissionID":389404166 }

{ "timestamp":"2018-06-09T12:04:50Z", "event":"MissionAccepted", "Faction":"GR 316 Silver Universal Group", "Name":"MISSION_Collect_RankEmp", "LocalisedName":"Source 3 units of Clothing for the Imperial Navy", "Commodity":"$Clothing_Name;", "Commodity_Localised":"Clothing", "Count":3, "DestinationSystem":"Neits", "DestinationStation":"Crown Port", "Expiry":"2018-06-10T19:42:52Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":10000, "MissionID":389170791 }

{ "timestamp":"2018-06-08T22:42:38Z", "event":"MissionAccepted", "Faction":"Neo Galactic Adventure Force", "Name":"Mission_Delivery_War", "LocalisedName":"Deliver war supplies of 2 units of Non-Lethal Weapons", "Commodity":"$NonLethalWeapons_Name;", "Commodity_Localised":"Non-Lethal Weapons", "Count":2, "TargetFaction":"Movement for Lorden Resistance", "DestinationSystem":"Lorden", "DestinationStation":"Roentgen Horizons", "Expiry":"2018-06-09T22:38:40Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":31018, "MissionID":389001104 }

**Comment by robbyxp1** [comment]
Fixed in 10.1.3
