### ISSUE TITLE
Missions: Courier/Combat Missions Not Active on Death

### ISSUE THREAD

**Issue by mydevpeeps** [EDDiscovery/EDDiscovery#2037]
Funny back story.. I was leaving a port and going too fast in my Anaconda and literally blew up a ship by running into it. And then was obliterated by the port lol.  So, I died.

When we come back from death, we keep our non-passenger missions.   However, in EDDiscovery all of the missions are gone:
![image](https://user-images.githubusercontent.com/25742242/41983055-fefd23f4-79fa-11e8-9ef4-e0ad477283a9.png)

Attempted Workarounds:
- Tried to re-scan all journal files and that does not cause them to return. 
- Tried to "run actions" on the history entry for the 2 active, and that also did not bring them back.

In the Missions tab of EDDiscovery, they show as completed (DIED):
![image](https://user-images.githubusercontent.com/25742242/41981555-2ff96bec-79f7-11e8-9c46-e541622b6e8c.png)

Yet, they are not actually gone (in the game):
![image](https://user-images.githubusercontent.com/25742242/41982702-1dd522c8-79fa-11e8-8ede-3c2a7406714c.png)

On my death, You can see in the history tab I have 7 failed PAX but it still shows 2 "active":
![image](https://user-images.githubusercontent.com/25742242/41983233-783f51f6-79fb-11e8-8355-441b8dc5aaa5.png)

Here is the history export of the MISSIONS Event:
`{"timestamp":"2018-06-27T14:24:14Z","event":"Missions","Active":[{"MissionID":394860617,"Name":"Mission_Courier_Lockdown_name","PassengerMission":false,"Expires":77698},{"MissionID":394869806,"Name":"Mission_Courier_name","PassengerMission":false,"Expires":80840}],"Failed":[{"MissionID":394875830,"Name":"Mission_PassengerBulk_REFUGEE_LEAVING_name","PassengerMission":true,"Expires":0},{"MissionID":394875861,"Name":"Mission_PassengerBulk_REFUGEE_LEAVING_name","PassengerMission":true,"Expires":0},{"MissionID":394862940,"Name":"Mission_PassengerBulk_BUSINESS_LEAVING_name","PassengerMission":true,"Expires":0},{"MissionID":394874301,"Name":"Mission_PassengerBulk_SECURITY_ARRIVING_name","PassengerMission":true,"Expires":0},{"MissionID":394863835,"Name":"Mission_PassengerBulk_PROTESTOR_ARRIVING_name","PassengerMission":true,"Expires":0},{"MissionID":394871001,"Name":"Mission_PassengerBulk_POLITICIAN_ARRIVING_name","PassengerMission":true,"Expires":0},{"MissionID":394863878,"Name":"Mission_PassengerBulk_AIDWORKER_ARRIVING_name","PassengerMission":true,"Expires":0}],"Complete":[]}`

Attaching Journal Log:
[Journal.180627074952.01.log](https://github.com/EDDiscovery/EDDiscovery/files/2141850/Journal.180627074952.01.log)

**Comment by klightspeed** [comment]
Sounds like we need exceptions to the "fail mission on death" rule.
Also, I'm not sure if we're currently taking missions from the `Missions` event.

**Comment by robbyxp1** [comment]
We are not using the Missions event.. i had a lot of conversations with Howard over that journal entry, and its useless as the missions come and go and are not guaranteed always to be there... so you can't use it to triage our own mission list. So I ignored it for the main line code.

How can their be passenger missions after death?

**Comment by robbyxp1** [comment]
We should, in Missions, look thru the active list, and resurrect any missions that are in the active list and NOT timed out.  So the missions all die, but the next Missions can make a mission live again..

**Comment by mydevpeeps** [comment]
These are not Passenger Missions. Those are gone. These are Data missions (or Courier as the title states).  In the XML for the Passenger missions there is "PassengerWanted:false". This string does not exist in other types of missions. Is there a way to tell if a missions is a non-Passenger mission?

`{"timestamp":"2018-06-28T19:21:42Z","event":"MissionAccepted","Faction":"Rhea Travel Interstellar","Name":"Mission_PassengerVIP_CEO_BOOM","LocalisedName":"Transport Aaryn Shields","Commodity":"$SyntheticMeat_Name;","Commodity_Localised":"Synthetic Meat","Count":2,"DestinationSystem":"LQ Hydrae","DestinationStation":"Wohler Horizons","Expiry":"2018-06-28T20:40:56Z","Wing":false,"Influence":"Med","Reputation":"Med","Reward":859360,"PassengerCount":6,"PassengerVIPs":true,"PassengerWanted":false,"PassengerType":"Business","MissionID":395190280}`

Additionally, the game just updated to 3.1 and I had 20 of this type of mission in my queue, and the game update wiped them out. So, now I have these 20 missions stuck in my mission tab.

![image](https://user-images.githubusercontent.com/25742242/42059278-dbbf44f2-7af0-11e8-9e7d-a098df52a20a.png)

Need a way to reset the tab when odd stuff happens, or force an action on that missions event to set it back to normal. Thanks.

**Comment by mydevpeeps** [comment]
Well now today they are all gone from my Missions Tab. Glad to see them disappear (i guess they went pass the expire time). At least there is some reprieve to the situation when it does get wiggy. Thanks much for all that you guys do!

**Comment by mydevpeeps** [comment]
Notice from ED about missions stuck.....

![image](https://user-images.githubusercontent.com/25742242/42105570-c6419dc4-7b9e-11e8-9d94-61e8fc11e29e.png)

**Comment by mydevpeeps** [comment]
Just noticed, same thing happens on Assassinate missions.. they are still there and yet gone from EDDiscovery.

**Comment by robbyxp1** [comment]
All missions get wiped on death.  we will look and fix it in 10.2

**Comment by mydevpeeps** [comment]
No worries, I'm just adding more info as I discover it. For example, I just noticed this in a Mission Description which I never saw before:

![image](https://user-images.githubusercontent.com/25742242/42394785-59bfe076-8129-11e8-9f7a-b6ae720a231e.png)
