### ISSUE TITLE
was working fine for a few days then all the sudden it started crashing on load and i cant use it

### ISSUE THREAD

**Issue by chumboat** [EDDiscovery/EDDiscovery#2038]
### Exception Details:
>EDDiscovery v10.1.3.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.IndexOutOfRangeException: Index was outside the bounds of the array.
>   at BaseUtils.EnhancedSendKeysParser.ParseKeys(Queue`1 events, String s, Int32 defdelay, Int32 defshiftdelay, Int32 defupdelay, IAdditionalKeyParser additionalkeyparser) in C:\Code\eddiscovery2\EDDiscovery\BaseUtils\Keys\EnhancedSendKeys.cs:line 98
>   at EDDiscovery.Actions.ActionKeyED.VerifyBinding(String userdata, BindingsFile bf) in C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\Actions\ActionsEDDCmds\ActionKeyED.cs:line 121
>   at EDDiscovery.Actions.ActionController.AdditionalChecks(String& errlist) in C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\Actions\ActionController.cs:line 161
>   at EDDiscovery.Actions.ActionController.ReLoad(Boolean completereload) in C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\Actions\ActionController.cs:line 146
>   at EDDiscovery.EDDiscoveryForm.Init(Action`1 msg) in C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 261
>   at EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e) in C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:line 145
>===== END =====
>```

**Comment by robbyxp1** [comment]
Actually I don't think removing the pack will work.  Please attach the binding file to this github ticket asap and i'll rush out a fix.

**Comment by robbyxp1** [comment]
take that back, it probably will.

**Comment by chumboat** [comment]
ok once I get home I will do all these things.  does this mean I wont be able to use the voice pack from this point then? that makes me sad/
hey also big thanks for the quick response that's dope man

**Comment by chumboat** [comment]
[Custom.3.0.zip](https://github.com/EDDiscovery/EDDiscovery/files/2146311/Custom.3.0.zip)

**Comment by chumboat** [comment]
yeah man removing the action files did the thing. it loads now. thanks! I'm both happy to have it back and sad about the voice thing. let me know if that fix gets implemented and ill gladly test it for you

**Comment by robbyxp1** [comment]
Its messing up reading this custom file.. i'll debug it in a mo, thanks

**Comment by robbyxp1** [comment]
Its not crashing my program. hmmm.  Hard to debug. Does it still crash if you reinstall the free voice control?  You can remove just that .act file to solve it again.

**Comment by klightspeed** [comment]
`EnhancedSendKeysParser.ParseKeys` will throw an `Index out of range` exception on a malformed key string - e.g. a truncated `[d1,d2,d3]` sequence, or delay specification without anything else.

Have you created any custom voice commands?

**Comment by chumboat** [comment]
I will reinstall the voice pack again. 
I don't think I did. I did mess with it a little trying to figure out to get the "scan" command to actually do my discovery scanner so maybe that was it.
I will report back in a bit.

**Comment by chumboat** [comment]
yeah man its working great. though to be honest I still cant figure out how to get the scan system command to actually scan when it says it will. maybe im just not smart lol

**Comment by klightspeed** [comment]
At the moment, EDDiscovery can only send keyboard keys.

There is no dedicated binding in Elite Dangerous for the discovery scanner, so it needs to be on a fire group.

If it's on secondary fire, and you have bound secondary fire to a key, then you should be able to use:
```
Key "[10,10,10000]{SecondaryFire}"
```

**Comment by chumboat** [comment]
dope man, I shall give it a try!

**Comment by chumboat** [comment]
ok so maybe im slow. I don't know how you are entering those values to make it long press.
