### ISSUE TITLE
Visited systems not always shows correctly in StarDistance panel

### ISSUE THREAD

**Issue by spadino** [EDDiscovery/EDDiscovery#2040]
Very often, visited systems aren't correctly marked as visited in StarDistance panel after logoff the game and start a new session.

![nearest](https://user-images.githubusercontent.com/4296635/42037027-9db9e85c-7abd-11e8-83ac-8b2707a66cb1.PNG)
![history](https://user-images.githubusercontent.com/4296635/42037041-adf372a6-7abd-11e8-991a-6d4c5ffc9f79.PNG)

**Comment by spadino** [comment]
You never had this issue?

**Comment by robbyxp1** [comment]
Experimental fix on master/10.1.x being pushed. reopen if it reoccurs
