### ISSUE TITLE
Technology brokers: Shopping List showing wrong amount of needed materials, ship cargo updating incorrectly on unlock

### ISSUE THREAD

**Issue by goscickiw** [EDDiscovery/EDDiscovery#2051]
So I wanted to unlock the Corrosion Resistant Cargo Rack. According to Shopping List, I needed 28 Meta-Alloys, 12 Neofabric Insulation and 30 Radiation Baffle. I have collected all this and unlocked the cargo rack.  Later, I saw that I have still 12 Meta-Alloys and 8 Radiation Baffle left over. I sold the Radiation Baffle and kept the Meta-Alloys, I might need them later. Then I went on Inara and saw that the correct amounts were 16 Meta-Alloys and 22 Radiation Baffle.

Also on Inara, I saw that the stuff i needed for the technology broker unlock was all marked blue, as if I still had it. In the Inara CMDR's Log - Cargo and Crafting - Cargo section, it said that my cargo was 28 Meta-Alloys, 22 Radiation Baffle and 12 Neofabric Insulation (It should be only 12 Meta-Alloys with no other cargo). I waited for a couple of hours but it didn't update.

In EDDiscovery Commodities section, it shows that I have 28 Meta-Alloys, 30 Radiation Baffle (Not 22 like on Inara) and 12 Neofabric Insulation. Again, it should be only 12 Meta-Alloys with no other cargo.

Interestingly, on EDSM it shows my cargo correctly, but only in the Dashboard - Inventory section. In My Fleet section, on the ship, it shows 0 cargo.

**Comment by AnthorNet** [comment]
Concerning EDSM if dashboard and cargo are right it might just be a case where I forget something to show the cargo.

I know last week I removed the progress bar for non active ships so something I might look to fix ;)

**Comment by robbyxp1** [comment]
Data will be updated in the next release.  Not sure about the other issues..

**Comment by robbyxp1** [comment]
So, with this one, its impossible to debug without a full dump (every log files) from your journal history, why it is showing an incorrect amount.  EDD goes thru the history and accumulates the totals to work out what your carrying.  Also at start up the totals are checked and adjusted by the journal record written at that time.

So, if you want m to look, drop in a zip of all log files from the journal folder in here or send me a link to dropbox etc- you can do that via discord.

**Comment by goscickiw** [comment]
[Logs.zip](https://github.com/EDDiscovery/EDDiscovery/files/2163085/Logs.zip)
Now it doesn't show the previous cargo, but it does show (on Inara, EDSM and in EDDiscovery Commodities section) that I still have 55 limpets that I have already got rid of.

**Comment by robbyxp1** [comment]
Thanks for the logs - we are miscounting drones.  Will be fixed in 10.1.5.

**Comment by robbyxp1** [comment]
The died in the eagle problem..  found the answer will fix also,

**Comment by robbyxp1** [comment]
Thanks for the logs - invaluable ;-)
