### ISSUE TITLE
Atmosphere on scan grid- EDSM data vs Direct scan

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#2052]
EDSM data shows the atmosphere as a field of the form 
Atmosphere: Some Random Gases
![edsm](https://user-images.githubusercontent.com/38956076/42251118-46fd0412-7f2d-11e8-8a90-97d9c94c53f0.png)
And accordingly, when displaying that data via the scan grid it just says "some random gases".
![before](https://user-images.githubusercontent.com/38956076/42251139-662e3356-7f2d-11e8-835e-7b9f8ae3aac8.png)
But then when you scan it directly it changes to add the word "atmosphere", to become "some random gases atmosphere"
![after](https://user-images.githubusercontent.com/38956076/42251159-821fe078-7f2d-11e8-9829-404bb4414d28.png)

This really quite irrelevant change has the annoying knock on effect of redrawing the entire scan grid and resetting it to the top of the page. For large systems which need a scrollbar, this gets to be a real pain as one constantly has to scroll the window back down if one wants to see where one was in the list, or keep up with the information about that part of the system.

I see where it comes from. The EDSM data does not include the word "atmosphere", whilst the ED API information does and a direct scan overwrites, updates and clarifies any EDSM information. 

I just wonder if it can be mitigated for this scenario, where no additional information is gained, but rather it often has the negative effect of repeatedly having to rescroll the scan grid window to the part of the system in which one is presently interested.

**Comment by robbyxp1** [comment]
I'll fix it up for 10.1.4 today. thanks for the report.

**Comment by robbyxp1** [comment]
closing done
