### ISSUE TITLE
Query window/ Search box

### ISSUE THREAD

**Issue by robbyxp1** [EDDiscovery/EDDiscovery#2054]
For materials/stations/etc.

Shows a list of matching items which you can right click to jump to.

**Comment by robbyxp1** [comment]
Query items such as materials
stations
systems within range of x visited
generally, a panel with a multiple of conditions which has a result list

**Comment by spadino** [comment]
I would love to have a REPL console, powered by a very flexible and easy scripting language (https://github.com/polterguy/lizzie) which can provide all sort of queries. Actually, not terribly difficult at all... I already worked on some ideas of the sort, but I was too new to C# at the time.
Lizzie provide easy means to point to internal method via "symbolic delegates", so we can use the already implemented ActionLanguage and SqlQueries methods from it.

> generally, a panel with a multiple of conditions which has a result list

Having a REPL console - external, or as an UeerControl - we can easily create a shared user scripts common base and a GUI from where run those scripts and which present the result. An user could select only those scripts from the add-on panel and they will be presented in the panel menu.
But a panel with a multiple conditions also will work great, of course, but it could be difficult and not so fast to use. A scripting language provide all the means and more.

Power users will prefer the console - which could be used as the Quake console - or my already in-the-work message-tokens idea (sending a request from the in-game chat) - while GUI users could access all those scripts from the GUI panel.

What about?

**Comment by robbyxp1** [comment]
That would be a power user thing ;-)

for the rest of us mortals, some flexible controls to select the query, extenable, would be good

**Comment by spadino** [comment]
Sure! ;)

**Comment by robbyxp1** [comment]
EDSM Star Finder - > General query box.. 

List of queries at the top in icon form. Click on one and it has a UC underneath it with query specific parameters.  EDSM Star Finder is on of those.

Other ones are: 

Enhance EDSM Star Finder to do your visited stars within range X
Enhance EDSM Star Finder to allow a pop out star scan panel showing graphic of planets (how easy.. maybe split out star scan code/display to sep UC first or control first.)
Show where you docked in system..
Show how many scans.

**Comment by robbyxp1** [comment]
10.4 has this
