### ISSUE TITLE
crash on exit

### ISSUE THREAD

**Issue by AndrewdAzotus** [EDDiscovery/EDDiscovery#2055]
### Exception Details:
>EDDiscovery v10.1.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
>Parameter name: value
>   at System.Windows.Forms.DataGridView.set_FirstDisplayedScrollingRowIndex(Int32 value)
>   at EDDiscovery.UserControls.UserControlScanGrid.DrawSystem() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlScanGrid.cs:line 252
>   at EDDiscovery.UserControls.UserControlScanGrid.NewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlScanGrid.cs:line 92
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 455
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 434
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
>===== END =====
>```

**Comment by robbyxp1** [comment]
I see it, i'll fix it thanks

**Comment by robbyxp1** [comment]
10.1.5 fixes it hopefully
