### ISSUE TITLE
Installer Issue: Upgrade While Directory Open - Resets Path & Access Denied

### ISSUE THREAD

**Issue by mydevpeeps** [EDDiscovery/EDDiscovery#2057]
_Preface_: 
I know, I know. Stupid. I went to that directory to make a shortcut to my desktop while the installer was running. _Little did I know that the installer was going to wipe the entire directory and replace its contents completely._  The good new is, after re-running the installer (even though it put my files in the default directory) none of my settings were lost (since they are stored elsewhere).

_Issue_: 
Upgrading with the old non-default installation target directory open causes an insufficient privileges error after wiping the files in the non-customer target directory. After this access is denied to that target directory until re-running the installer. Re-running the installer causes it to set the target path to the windows default directory instead of the old non-default installation target directory.

_Windows Event Log_: 
```
Log Name:      Application
Source:        MsiInstaller
Date:          7/5/2018 6:20:09 AM
Event ID:      11303
Task Category: None
Level:         Error
Keywords:      Classic
User:          systemname\username
Computer:      computername.domain.com
Description:
Product: EDDiscovery -- Error 1303. The installer has insufficient privileges to access this directory: D:\Program Files\EDDiscovery\EDDiscovery.  The installation cannot continue.  Log on as administrator or contact your system administrator.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MsiInstaller" />
    <EventID Qualifiers="0">11303</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-07-05T10:20:09.354874000Z" />
    <EventRecordID>25843</EventRecordID>
    <Channel>Application</Channel>
    <Computer>computername.domain.com</Computer>
    <Security UserID="S-n-n-nn-nnnnnnnnnn-nnnnnnnnnn-nnnnnnnnnn-nnnn" />
  </System>
  <EventData>
    <Data>Product: EDDiscovery -- Error 1303. The installer has insufficient privileges to access this directory: D:\Program Files\EDDiscovery\EDDiscovery.  The installation cannot continue.  Log on as administrator or contact your system administrator.</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>
    </Data>
    <Binary>7B30364431444642362D333638382D343542332D384630432D4538423141373639463545467D</Binary>
  </EventData>
</Event>
```

_WorkAround_: 
Re-run the installer as Administrator (right-click) instead of relying on UAC to handle it.

_NOTE_: 
I understand if you want to just close this out and call it what it is, stupid for having the directory open. If you can do something about it great. If not, at least it's documented for someone that might encounter it in the future. Thanks for your time. 

_Additional Info_:
I am not sure if this is normal or not given my understanding of exit codes/errorlevel in windows (it's been a while), but it seems that the installer had no idea there was a failure and reported an exit code of 0 back to MSI:
```
Product: EDDiscovery -- Error 1303. The installer has insufficient privileges to access this directory: D:\Program Files\EDDiscovery\EDDiscovery.  The installation cannot continue.  Log on as administrator or contact your system administrator.
Ending a Windows Installer transaction: C:\Users\localadmin\AppData\Roaming\EDDiscovery\EDDiscovery 10.1.4\install\EDDiscovery.x64.msi. Client Process Id: 31480.
Product: EDDiscovery -- Installation failed.
Windows Installer installed the product. Product Name: EDDiscovery. Product Version: 10.1.4. Product Language: 1033. Manufacturer: EDDiscovery. Installation success or error status: 0.
```

**Comment by robbyxp1** [comment]
So, i'm not sure what we can do - we use the advanced installer, and it wraps the EDD code in a install msi exe created by it.  

Obv. we can't fix a problem inside the advanced installer software or change what error codes it pumps out..

I run as a normal user and always get the "Enter your admin password" box when running the installer.
