### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by nonam3z** [EDDiscovery/EDDiscovery#2058]
### Description
Doing nothing, just exploring stars. EDD minimized.

### Additional Information
None.

### Exception Details:
>EDDiscovery v10.1.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Заданный аргумент находится вне диапазона допустимых значений.
>Имя параметра: value
>   в System.Windows.Forms.DataGridView.set_FirstDisplayedScrollingRowIndex(Int32 value)
>   в EDDiscovery.UserControls.UserControlScanGrid.DrawSystem() в C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlScanGrid.cs:строка 252
>   в EDDiscovery.UserControls.UserControlScanGrid.NewEntry(HistoryEntry he, HistoryList hl) в C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlScanGrid.cs:строка 92
>   в System.Action`2.Invoke(T1 arg1, T2 arg2)
>   в EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) в C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:строка 455
>   в EDDiscovery.EDDiscoveryController.PlayJournalList() в C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:строка 434
>   в EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) в C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:строка 184
>===== END =====
>```

**Comment by robbyxp1** [comment]
Known, duplicate, fixing in 10.1.5 in a moment.

thanks
