### ISSUE TITLE
EDDiscovery 10.1.4.0 - Application Hang

### ISSUE THREAD

**Issue by mydevpeeps** [EDDiscovery/EDDiscovery#2059]
_Reporting for Commander N2CUA_

Actions Attempted:
- Rebooted
- Restarted EDDiscovery

Screenshots:
![image](https://user-images.githubusercontent.com/25742242/42328794-2db44374-803d-11e8-9630-d9ae6f6dfa93.png)

![image](https://user-images.githubusercontent.com/25742242/42328735-111f8458-803d-11e8-980f-a389e56b315f.png)

Event Viewer Details:
```Log Name:      Application
Source:        Application Hang
Date:          7/5/2018 10:08:35 AM
Event ID:      1002
Task Category: (101)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Win10-17G
Description:
The program EDDiscovery.exe version 10.1.4.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 25ac
 Start Time: 01d41469036e86b3
 Termination Time: 4294967295
 Application Path: C:\Program Files\EDDiscovery\EDDiscovery\EDDiscovery.exe
 Report Id: 7ed1fbe5-9f61-43ad-90bb-6db336cd0cfe
 Faulting package full name: 
 Faulting package-relative application ID: 

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" />
    <EventID Qualifiers="0">1002</EventID>
    <Level>2</Level>
    <Task>101</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-07-05T14:08:35.213356700Z" />
    <EventRecordID>3960</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Win10-17G</Computer>
    <Security />
  </System>
  <EventData>
    <Data>EDDiscovery.exe</Data>
    <Data>10.1.4.0</Data>
    <Data>25ac</Data>
    <Data>01d41469036e86b3</Data>
    <Data>4294967295</Data>
    <Data>C:\Program Files\EDDiscovery\EDDiscovery\EDDiscovery.exe</Data>
    <Data>7ed1fbe5-9f61-43ad-90bb-6db336cd0cfe</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Binary>54006F00700020006C006500760065006C002000770069006E0064006F0077002000690073002000690064006C00650000000000</Binary>
  </EventData>
</Event>```

Installation History from Event Viewer:
```
Log Name:      Application
Source:        MsiInstaller
Date:          7/5/2018 9:33:12 AM
Event ID:      11707
Task Category: None
Level:         Information
Keywords:      Classic
User:          WIN10-17G\Randy
Computer:      Win10-17G
Description:
Product: EDDiscovery -- Installation completed successfully.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MsiInstaller" />
    <EventID Qualifiers="0">11707</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-07-05T13:33:12.671127800Z" />
    <EventRecordID>3890</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Win10-17G</Computer>
    <Security UserID="S-1-5-21-3390767787-733260333-1679756328-1002" />
  </System>
  <EventData>
    <Data>Product: EDDiscovery -- Installation completed successfully.</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>(NULL)</Data>
    <Data>
    </Data>
    <Binary>7B30364431444642362D333638382D343542332D384630432D4538423141373639463545467D</Binary>
  </EventData>
</Event>
```

```
Log Name:      Application
Source:        MsiInstaller
Date:          7/5/2018 9:33:12 AM
Event ID:      1033
Task Category: None
Level:         Information
Keywords:      Classic
User:          WIN10-17G\Username
Computer:      Win10-17G
Description:
Windows Installer installed the product. Product Name: EDDiscovery. Product Version: 10.1.4. Product Language: 1033. Manufacturer: EDDiscovery. Installation success or error status: 0.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MsiInstaller" />
    <EventID Qualifiers="0">1033</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-07-05T13:33:12.672127800Z" />
    <EventRecordID>3891</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Win10-17G</Computer>
    <Security UserID="S-1-5-21-3390767787-733260333-1679756328-1002" />
  </System>
  <EventData>
    <Data>EDDiscovery</Data>
    <Data>10.1.4</Data>
    <Data>1033</Data>
    <Data>0</Data>
    <Data>EDDiscovery</Data>
    <Data>(NULL)</Data>
    <Data>
    </Data>
    <Binary>7B30364431444642362D333638382D343542332D384630432D4538423141373639463545467D3030303064633863663238626132383061666363326530346464366564343034366238663030303030393034</Binary>
  </EventData>
</Event>
```

Windows Error Reporting:
```
Log Name:      Application
Source:        Windows Error Reporting
Date:          7/5/2018 9:38:50 AM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      Win10-17G
Description:
Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: EDDiscovery.exe
P2: 10.1.4.0
P3: 5b3ca241
P4: a1ad
P5: 67246336
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\Critical_EDDiscovery.exe_5347a24bc18591d1596bb90fe3a66b0e6ea35e0_feb022ab_09996bc3

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3b158ebc-f3cd-46b5-9412-03a8e4476cd3
Report Status: 4
Hashed bucket: 
Cab Guid: 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-07-05T13:38:50.164430200Z" />
    <EventRecordID>3893</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Win10-17G</Computer>
    <Security />
  </System>
  <EventData>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>AppHangB1</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>EDDiscovery.exe</Data>
    <Data>10.1.4.0</Data>
    <Data>5b3ca241</Data>
    <Data>a1ad</Data>
    <Data>67246336</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>C:\ProgramData\Microsoft\Windows\WER\ReportQueue\Critical_EDDiscovery.exe_5347a24bc18591d1596bb90fe3a66b0e6ea35e0_feb022ab_09996bc3</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>3b158ebc-f3cd-46b5-9412-03a8e4476cd3</Data>
    <Data>4</Data>
    <Data>
    </Data>
    <Data>0</Data>
  </EventData>
</Event>
```

Windows Error Reporting Details:
```
Version=1
EventType=AppHangB1
EventTime=131752733150120145
ReportType=1
Consent=1
ReportIdentifier=bd70b6c8-de53-489d-b739-b8946d332654
IntegratorReportIdentifier=7ed1fbe5-9f61-43ad-90bb-6db336cd0cfe
Wow64Host=34404
NsAppName=EDDiscovery.exe
OriginalFilename=EDDiscovery.exe
AppSessionGuid=000025ac-0001-000b-b386-6e036914d401
TargetAppId=W:00060c77662c8f3cd5397194def4a528062100000000!0000ff1178f811151be3aee91fd04daef326ef8ca22a!EDDiscovery.exe
TargetAppVer=2018//07//04:10:32:33!0!EDDiscovery.exe
BootId=4294967295
TargetAsId=341
UserImpactVector=269484304
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=EDDiscovery.exe
Sig[1].Name=Application Version
Sig[1].Value=10.1.4.0
Sig[2].Name=Application Timestamp
Sig[2].Value=5b3ca241
Sig[3].Name=Hang Signature
Sig[3].Value=a1ad
Sig[4].Name=Hang Type
Sig[4].Value=67246336
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.17134.2.0.0.768.101
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Hang Signature 1
DynamicSig[22].Value=a1ad98ff8515b9c42a10931d3e32daca
DynamicSig[23].Name=Additional Hang Signature 2
DynamicSig[23].Value=5a76
DynamicSig[24].Name=Additional Hang Signature 3
DynamicSig[24].Value=5a76845d01aa939f8ca55dfbc5be5816
DynamicSig[25].Name=Additional Hang Signature 4
DynamicSig[25].Value=a1ad
DynamicSig[26].Name=Additional Hang Signature 5
DynamicSig[26].Value=a1ad98ff8515b9c42a10931d3e32daca
DynamicSig[27].Name=Additional Hang Signature 6
DynamicSig[27].Value=5a76
DynamicSig[28].Name=Additional Hang Signature 7
DynamicSig[28].Value=5a76845d01aa939f8ca55dfbc5be5816
UI[3]=EDDiscovery is not responding
UI[4]=If you close the program, you might lose information.
UI[5]=Close the program
UI[6]=Close the program
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=17134
OsInfo[3].Key=ubr
OsInfo[3].Value=112
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=244
OsInfo[8].Key=sku
OsInfo[8].Value=101
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=768
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=67584
OsInfo[15].Key=osinsty
OsInfo[15].Value=1
OsInfo[16].Key=iever
OsInfo[16].Value=11.112.17134.0-11.0.70
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=8143
OsInfo[19].Key=svolsz
OsInfo[19].Value=930
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=180410
OsInfo[22].Key=bldtm
OsInfo[22].Value=1804
OsInfo[23].Key=bldbrch
OsInfo[23].Value=rs4_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.17134.112.amd64fre.rs4_release.180410-1804
OsInfo[30].Key=buildflightid
OsInfo[30].Value=F8EE1E09-5379-44DF-B86D-E49E70CBE43B.1
OsInfo[31].Key=edition
OsInfo[31].Value=Core
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[33].Value=RS:1679
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
FriendlyEventName=Stopped responding and was closed
ConsentKey=AppHangXProcB1
AppName=EDDiscovery
AppPath=C:\Program Files\EDDiscovery\EDDiscovery\EDDiscovery.exe
ReportDescription=A problem caused this program to stop interacting with Windows.
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=2143C2B4C274CD5B8F1CB90AC709061B
MetadataHash=898395116
```

**Comment by robbyxp1** [comment]
Try safe mode.. reset options, rebuild system db, etc.

**Comment by klightspeed** [comment]
If it persists, please submit the most recent EDDiscovery trace log.

**Comment by mydevpeeps** [comment]
Safe Mode? Reset Options? Rebuild System DB? What are you going on about LOL. Is there a HOW-TO somewhere for all of that?

**Comment by klightspeed** [comment]
Holding shift while starting EDDiscovery will bring up a "safe mode" dialog, where you can perform maintenance / troubleshooting actions such as resetting options or rebuilding the systems DB.

See [Safe Mode](https://github.com/EDDiscovery/EDDiscovery/wiki/Safe-Mode), linked to from the [Troubleshooting](https://github.com/EDDiscovery/EDDiscovery/wiki#troubleshooting) section of the wiki.

**Comment by mydevpeeps** [comment]
User followed your above instructions and was able to launch with 10.1.5.0. Thanks.
