### ISSUE TITLE
Engineering - Experimental missing

### ISSUE THREAD

**Issue by lwt-pressy** [EDDiscovery/EDDiscovery#2061]
No experimental effects are in the list with all filters set to all. If I select only level "experimental" the list is empty.

**Comment by robbyxp1** [comment]
We don't support the experimental effects.  I think its an error, so i'll remove that tick box. thanks for the report.

**Comment by iainross** [comment]
We used to - did they get lost when you moved to pulling the recipes from t'internet?

**Comment by strangealien** [comment]
I just wanted to ask experimental effects to be added...
Could you please consider this? The 'experimental' tick box is misleading, but please do not remove it, make it functional.
Thank you.

**Comment by klightspeed** [comment]
I suspect the source document that is used to generate the engineering recipe list doesn't include experimental effects <https://inara.cz/galaxy-experimentaleffects/>

**Comment by strangealien** [comment]
The link to Inara - all the experimental effects are listed, and if you click on any effect, it opens and shows the materials needed.
https://inara.cz/galaxy-experimentaleffects/
