### ISSUE TITLE
Shopping list ends up repeat use of displaynumber of other legit tabs

### ISSUE THREAD

**Issue by robbyxp1** [EDDiscovery/EDDiscovery#2064]
Somehow, shopping list with its embedded UCs need to give unique numbers to those UC.. or unique IDs maybe..

**Comment by robbyxp1** [comment]
Make it use the same displaynumber but change the name by having the engineeringgrid name config

**Comment by iainross** [comment]
I thought that would happen eventually, never should've believed your claim I didn't need to protect against it :p
