### ISSUE TITLE
Frontier Journal error causing voicepack to read out incorrect percentages

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#2066]
I noted that the voicepack told me that I had completed 0 of 40 units and my progress was 0%.  In fact I had delivered 24 of the 40 units that the mission required.  So I pulled out the journals (pasted below).

I think that for "Name":"Mission_Collect", the ED journal updates the "ItemsDelivered":24  entry.  It also fails to update the "Progress":0.0 so I've logged that as a bug with FD
https://forums.frontier.co.uk/showthread.php/437619-Mission-Collect-not-updating-progress-in-the-journal?p=6847460#post6847460
Edit:  recreated bug report on FD as the original seems to have disappeared
https://forums.frontier.co.uk/showthread.php/439017-Mission-Collect-not-updating-progress-in-the-journal?p=6866758#post6866758

{"timestamp":"2018-07-06T09:56:22Z","event":"MissionAccepted","Faction":"Iah Lanitei Empire League","Name":"Mission_Collect","LocalisedName":"Source and return 40 units of Imperial Slaves","Commodity":"$ImperialSlaves_Name;","Commodity_Localised":"Imperial Slaves","Count":40,"DestinationSystem":"Apadipinook","DestinationStation":"Deslandres Installation","Expiry":"2018-07-07T09:53:20Z","Wing":false,"Influence":"Med","Reputation":"Med","Reward":4034086,"MissionID":398127656}

{"timestamp":"2018-07-06T10:12:23Z","event":"CargoDepot","MissionID":398127656,"UpdateType":"Deliver","CargoType":"ImperialSlaves","CargoType_Localised":"Imperial Slaves","Count":24,"StartMarketID":0,"EndMarketID":3223744256,"ItemsCollected":0,"ItemsDelivered":24,"TotalItemsToDeliver":40,"Progress":0.0}

{"timestamp":"2018-07-06T10:35:59Z","event":"CargoDepot","MissionID":398127656,"UpdateType":"Deliver","CargoType":"ImperialSlaves","CargoType_Localised":"Imperial Slaves","Count":16,"StartMarketID":0,"EndMarketID":3223744256,"ItemsCollected":0,"ItemsDelivered":40,"TotalItemsToDeliver":40,"Progress":0.0}

{"timestamp":"2018-07-06T10:37:06Z","event":"MissionCompleted","Faction":"Iah Lanitei Empire League","Name":"Mission_Collect_name","MissionID":398127656,"Commodity":"$ImperialSlaves_Name;","Commodity_Localised":"Imperial Slaves","Count":40,"DestinationSystem":"Apadipinook","DestinationStation":"Deslandres Installation","Reward":4034086,"FactionEffects":[{"Faction":"Iah Lanitei Empire League","Effects":[{"Effect":"$MISSIONUTIL_Interaction_Summary_boom_up;","Effect_Localised":"$#MinorFaction; are experiencing increased growth that could lead to an economic boom","Trend":"UpGood"}],"Influence":[{"SystemAddress":5069537617321,"Trend":"UpGood"}],"Reputation":"UpGood"}]}

In contrast, the "Name":"Mission_DeliveryWing_Boom" updates the "ItemsCollected":104 entry and correctly updates the progress.   I *think* EDD gets that correct as I didn't notice an error except the 0% on delivery.  It did do the maths on total less delivered though :)

{"timestamp":"2018-07-06T12:15:20Z","event":"MissionAccepted","Faction":"LFT 37 Blue Natural Corp.","Name":"Mission_DeliveryWing_Boom","LocalisedName":"Boom time delivery of 2760 units of Coffee","Commodity":"$Coffee_Name;","Commodity_Localised":"Coffee","Count":2760,"TargetFaction":"Nemet Defence Force","DestinationSystem":"Nemet","DestinationStation":"Hirase Horizons","Expiry":"2018-07-07T12:13:33Z","Wing":true,"Influence":"Med","Reputation":"Med","Reward":3949561,"MissionID":398152639}

{"timestamp":"2018-07-06T14:16:41Z","event":"CargoDepot","MissionID":398152639,"UpdateType":"Collect","CargoType":"Coffee","Count":104,"StartMarketID":3224132352,"EndMarketID":3224129280,"ItemsCollected":104,"ItemsDelivered":0,"TotalItemsToDeliver":2760,"Progress":0.037681}

{"timestamp":"2018-07-07T00:17:04Z","event":"CargoDepot","MissionID":398152639,"UpdateType":"Deliver","CargoType":"Coffee","Count":104,"StartMarketID":3224132352,"EndMarketID":3224129280,"ItemsCollected":104,"ItemsDelivered":104,"TotalItemsToDeliver":2760,"Progress":0.0}

**Comment by robbyxp1** [comment]
And Vp8 says:

Static say_CargoDepot $= "%ifequal(EventClass_UpdateEnum,\"Collect\",\"{Collected %(EventClass_Count) of %(EventClass_FriendlyCargoType), leaving \")"
Static say_CargoDepot $+= "%ifequal(EventClass_UpdateEnum,\"Deliver\",\"{Delivered %(EventClass_Count) of %(EventClass_FriendlyCargoType), leaving \")"
Static say_CargoDepot $+= "%ifequal(EventClass_UpdateEnum,\"WingUpdate\",\"Wing update on cargo mission \")"
Static say_CargoDepot $+= "%(EventClass_ItemsToGo) items left, %round(EventClass_ProgressPercent,1,\"0.#\") percent."

last line just vocalises the progress percent directly.  I suppose we could calculate it to work around the bug..

**Comment by Disorganise** [comment]
I've never worked out where the variable get set.  But I suspect %(EventClass_Count) get set to "ItemsCollected" regardless of whether it is a collect or deliver.
Thus {Delivered %(EventClass_Count) of %(EventClass_FriendlyCargoType), leaving ")"  becomes "Delivered 0 of Imperial Slaves, leaving 40.   When it should have been "Delivered 24 of Imperial Slaves"  (I ned to double check but I think the remaining was the full amount rather than subtracted, but for collect missions it is correct)

The percentage thing is a journal error.  The collect/deliver thing is looking at the wrong variable (I think)

**Comment by robbyxp1** [comment]
Code does:

            MissionId = evt["MissionID"].Int();
            UpdateType = evt["UpdateType"].Str();        // must be FD name
            System.Enum.TryParse<UpdateTypeEnum>(UpdateType, out UpdateTypeEnum u);
            UpdateEnum = u;
            CargoType = evt["CargoType"].Str();     // item counts
            FriendlyCargoType = JournalFieldNaming.RMat(CargoType);
            Count = evt["Count"].Int(0);
            StartMarketID = evt["StartMarketID"].Long();
            EndMarketID = evt["EndMarketID"].Long();
            ItemsCollected = evt["ItemsCollected"].Int();
            ItemsDelivered = evt["ItemsCollected"].Int();
            TotalItemsToDeliver = evt["TotalItemsToDeliver"].Int();
            ItemsToGo = TotalItemsToDeliver - ItemsDelivered;
            ProgressPercent = evt["Progress"].Double()*100;
            MarketID = evt["MarketID"].LongNull();

EventClass_Count  gets set to Journal entry "Count". Looking at the journal entries Count appears correct in them.  hmmm.

Put into 10.2 on master:

            if (ProgressPercent < 0.0001)
                ProgressPercent = ((double)System.Math.Max(ItemsCollected, ItemsDelivered) / (double)TotalItemsToDeliver) * 100;

So its the maximum of collected/delivered, which seems to be what they are aiming at with the progress.

**Comment by Disorganise** [comment]
Hi, thanks.
I think this:
ItemsDelivered = evt["ItemsCollected"].Int();

should be:
ItemsDelivered = evt["ItemsDelivered"].Int();

that's what I was trying to say before - EDD points to collected regardless whether it is a deliver or collect event, hence it saying zero of x.

FD have deleted the report again - seems they don't want to know about journal issues.  If we're not supposed to log them in the bug report section, it'd be nice if they'd just say so rather than delete the post :/

**Comment by AnthorNet** [comment]
I wouldn't worry about your bug report, I just saw it in the private forum, so it's not deleted.

**Comment by robbyxp1** [comment]
Thanks - well spotted. Fixed on master for 10.2
