### ISSUE TITLE
Norton finds Heuristic Virus in EDDiscover Update

### ISSUE THREAD

**Issue by Jibsman** [EDDiscovery/EDDiscovery#2067]
![eddiscovery_virus](https://user-images.githubusercontent.com/31598994/42488752-f79b9972-83bb-11e8-894c-8bdcf5e7013d.jpg)

**Comment by robbyxp1** [comment]
Its just Norton being paranoid.  The problem will go away as more people use it and Norton sees more of it.

We get false positives all the time from these tools.  Jiangmin (whatever that is) always says its bad. Basically, virus scanners are not very reliable!

![image](https://user-images.githubusercontent.com/6573992/42494078-2d2f4bf2-83ed-11e8-91f5-34de44adf832.png)
