### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by spacematador** [EDDiscovery/EDDiscovery#2068]
### Exception Details:
>EDDiscovery v10.1.5.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.Runtime.InteropServices.COMException (0x80040154): Falha ao obter class factory de COM do componente com CLSID {D9F6EE60-58C9-458B-88E1-2F908FD7F87C} devido ao seguinte erro: 80040154 Classe não registada (Excepção de HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
>   em System.Speech.Internal.ObjectTokens.RegistryDataKey..ctor(String fullPath, IntPtr regHandle)
>   em System.Speech.Internal.ObjectTokens.RegistryDataKey.Open(String registryPath, Boolean fCreateIfNotExist)
>   em System.Speech.Internal.ObjectTokens.SAPICategories.DefaultDeviceOut()
>   em System.Speech.Internal.Synthesis.VoiceSynthesis..ctor(WeakReference speechSynthesizer)
>   em System.Speech.Synthesis.SpeechSynthesizer.get_VoiceSynthesizer()
>   em System.Speech.Synthesis.SpeechSynthesizer.SetOutputToNull()
>   em System.Speech.Synthesis.SpeechSynthesizer.SetOutputStream(Stream stream, SpeechAudioFormatInfo formatInfo, Boolean headerInfo, Boolean closeStreamOnExit)
>   em AudioExtensions.WindowsSpeechEngine..ctor() em C:\Code\eddiscovery2\EDDiscovery\Audio\SpeechSythesizerWindows.cs:line 33
>   em EDDiscovery.Actions.ActionController..ctor(EDDiscoveryForm frm, EDDiscoveryController ctrl, Icon ic) em C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\Actions\ActionController.cs:line 81
>   em EDDiscovery.EDDiscoveryForm.Init(Action`1 msg) em C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 260
>   em EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e) em C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:line 145
>===== END =====
>```

**Comment by robbyxp1** [comment]
This is something to do with your windows subsystem, when it tried to turn on the voice synthesiser.

Was it working before? Is this the first time? Do you have a default sound device selected (go into the sound control panel and make sure something is selected)..

**Comment by spacematador** [comment]
Yes, it's the first time.
Yes, I have a default sound device.

**Comment by klightspeed** [comment]
I'm guessing that "version" has the text to speech API removed?

**Comment by robbyxp1** [comment]
Yep, that explains it.  Your windows does not have the correct COM component for SAPI to work.

Please close the ticket if your happy with the answer.

**Comment by spacematador** [comment]
I think so: Removed: Speech Recognition

**Comment by spacematador** [comment]
Thank you for your help

**Comment by klightspeed** [comment]
Perhaps we should use the Dummy speech provider if the initialization of the Windows speech provider fails?

**Comment by spacematador** [comment]
Dummy speech? 
if the original does not work I think it is impossible a secondary program of the same function...

**Comment by robbyxp1** [comment]
I don't think so.  This lite version is a non official supported version of windows.  We support standard windows only.

**Comment by spacematador** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=13045
Rob sorry to bother but if I install Windows Speech Recognition Macros will probably solve the problem?

**Comment by robbyxp1** [comment]
I don't know exactly, but i doubt that the package comes with the missing DLLs

Your missing the COM DLL modules which implement speech.  Maybe you could get them from another windows install and register them?

**Comment by klightspeed** [comment]
It'd be the Speech API runtime.  Version 5.1 (the version shipped with Windows XP) is at https://www.microsoft.com/en-us/download/details.aspx?id=10121

**Comment by spacematador** [comment]
Still giving error klightspeed =/

**Comment by klightspeed** [comment]
I'm guessing the SAPI 5.1 redistributable is 32-bit only.  As later versions are integrated into the OS, I don't think there are any runtimes available for download for them.

Maybe copying `C:\Windows\System32\Speech` from another working Windows 10 machine, then registering sapi.dll and MSTTSEngine.dll might work:
```
regsvr32 C:\Windows\System32\Speech\Common\sapi.dll
regsvr32 C:\Windows\System32\Speech\Engines\MSTTSEngine.dll
```

**Comment by spacematador** [comment]
ok, i will speak to a friend to give me a copy of these dll´s and see if that works

**Comment by klightspeed** [comment]
If that doesn't work, you might have to use the `-nosound` option (or put `NoSound` into an `options.txt` file with the program) to disable speech.

**Comment by spacematador** [comment]
the "options.txt" i need to create right?
