### ISSUE TITLE
Inara not showing updated exploration rank.

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#2071]
From information sent by EDDiscovery Inara knows where I am and how much money I have, completely up to date - but doesn't seem to have been sent (or ignored the message) of my recent promotion.

I know there is a short delay on sending messages, so as not to flood, but cash transactions post promotion have been received and processed, so that can't be it.

{"timestamp":"2018-07-14T10:04:02Z","event":"Promotion","Explore":8}

**Comment by Tromador** [comment]
Update: 

After relogging, Inara worked it out (presumably from the Rank event on login) - but the Promotion event was still not correctly transmitted one way or another.

**Comment by robbyxp1** [comment]
Not processing Promotion in Inarasync.cs,.. should be..

eventstosend.Add(InaraClass.setCommanderRankPilot( from entry name, (int)from entry value, 0, rank.EventTimeUTC));

0 as the progress thru the next rank should be zero at time of promotion..

**Comment by robbyxp1** [comment]
Fixed in 10.2
