### ISSUE TITLE
Not runing

### ISSUE THREAD

**Issue by lucasorsi** [EDDiscovery/EDDiscovery#2072]
Hello,

While opening EDDiscovery, I`m having the folowing error.
How do I solve that?

An unhandled fatal exception has occurred.

==== BEGIN ====
System.Data.SQLite.SQLiteException (0x80004005): database disk image is malformed
database disk image is malformed
   em System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   em System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   em System.Data.SQLite.SQLiteDataReader.NextResult()
   em System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   em System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   em System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   em EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteNonQuery() na C:\Code\eddiscovery2\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:linha 548
   em EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexesNoLock() na C:\Code\eddiscovery2\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:linha 341
   em EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexes() na C:\Code\eddiscovery2\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:linha 318
   em EDDiscovery.EDDiscoveryController.BackgroundInit() na C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:linha 552
   em EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() na C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:linha 495
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by klightspeed** [comment]
> database disk image is malformed

This means that either the database is corrupt or you have filesystem errors.

The stack trace points to this being the system database, which you can reset by holding the shift button while starting EDDiscovery, then clicking `Delete/Rebuild System DB` and clicking `Run`

**Comment by robbyxp1** [comment]
Closing as no more comment received.
