### ISSUE TITLE
Voicepack reading out "multiple final separator"

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#2073]
Not sure if this is a bug in the journal or how EDD reads it.  But accepting passenger missions results in in the VP reading out "multiple final separator" - it then seems to hang for a little bit (spinny wheel if you hover mouse) but it does come back.

{"timestamp":"2018-07-15T07:08:13Z","event":"MissionAccepted","Faction":"Synteini Imperial Society","Name":"Mission_Sightseeing","LocalisedName":"Lenard Zamora seeks sightseeing adventure","Commodity":"$Clothing_Name;","Commodity_Localised":"Clothing","Count":3,"DestinationSystem":"LTT 9164$MISSIONUTIL_MULTIPLE_FINAL_SEPARATOR;Tchernobog","Expiry":"2018-07-15T20:58:36Z","Wing":false,"Influence":"Med","Reputation":"Med","Reward":2334700,"PassengerCount":4,"PassengerVIPs":true,"PassengerWanted":false,"PassengerType":"Tourist","MissionID":401277072}

**Comment by robbyxp1** [comment]
Fixed on master, thanks for the report!  Will be fixed in 10.2
