### ISSUE TITLE
Voicepack pronounciation

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#2074]
Minor thing, but voice pack gets some words a bit strange.

Most obvious is manoeuvres which sounds more like 'main' 'ow' 'vers' :)

**Comment by klightspeed** [comment]
I think you can blame Microsoft for that - EDDiscovery sends text to the Microsoft TTS, and except for some cases like system or body names, does not explicitly provide pronunciation for the words.

Does your selected Speech language match your language? (In windows 10: Settings -> Time & Language -> Speech)

**Comment by Disorganise** [comment]
aha!  my 2nd profile was set to US.  Maybe that's it.  Have set it to 'strayan now, will see how it goes

**Comment by Disorganise** [comment]
nope :(  Had the brain wave that hitting silent running will trigger the 'evasive manoeuvres' message - which it did.  still main owvers.  Oh well.  wasn't sure if there was an adjustment file or something.  no worries :)

**Comment by klightspeed** [comment]
It's a misspelling in the act file - it's `maneouvers` when it should be `maneuvers` (en-US) `manoeuvres` (en-GB / en-AU)
