### ISSUE TITLE
Voicepack - Star is dangerous warning, missing for white dwarf

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#2075]
When jumping to a neutron, the voicepack says 'warning, star is dangerous, throttle down now'.  My alt is in the bubble and has come across a few white dwarfs and that warning is not announced - I think it should apply to whitedwarfs as well as neutrons (and maybe also for blackholes if it doesn't already)

**Comment by robbyxp1** [comment]
Voice pack 9 for 10.2 will have this, thanks
