### ISSUE TITLE
Enhancement: Roads to Riches

### ISSUE THREAD

**Issue by mydevpeeps** [EDDiscovery/EDDiscovery#2080]
### Roads to Riches
**Summary**

There are a few decent Roads to Riches websites out there for Exploring:
[https://www.spansh.co.uk/riches](https://www.spansh.co.uk/riches)
[http://edtools.ddns.net/expl.php](http://edtools.ddns.net/expl.php)
[https://www.alpha-orbital.com/pathfinder](https://www.alpha-orbital.com/pathfinder) *(honorable mention)*

They are very useful, but they all really lack some key features to making this great for more than one-off use.  Exploring is a solid way to make money fast and get an Elite Rank quickly to utilize Jameson Memorial (~$400M CR turned in). They are also in websites, and we all want to just use EDD for everything!

**Website Shortcomings**
They each have various features that make them useful. Here are the shortcomings:
-  Tracking systems already "scanned".
-  Excluding already "scanned" systems in new search results.
-  Making a two-way trip results in a lot of similar systems in the list.
-  Unable to choose systems which only have scoopable stars (mitigated on the galaxy map in-game at the moment). This would be useful for those wanting to start exploring early on in a ship with small range (both total and per jump) or they get out into the middle of nowhere without a fuel scoop.
-  Remove already visited systems from the top of the list as the route is followed, so that the next system is always on the top of the list.
- Some don't show monetary scan values (per system and/or in total).
- Unable to select by planetary body type

This made me realize that EDDiscovery already has my "scan history" and how valuable this information would be in determining an explorer route.  

### Currently Available Information
**History Tab**
I started mitigating this annoyance with EDDiscovery by filtering my history on "scan of", exported to a CSV, and then stripped out into a text editor to search before going to the galaxy map.  That then later evolved into just using the Galaxy Map to determine if I had the scan data already (white system info circle on the target system on the map gives this away).  

**Travel History Tab**
I am able to leverage the "Travel History" tab and a "Scan" filter to get a list of every system I have scanned so far, and it is pretty responsive given there are almost 3000 entries in there for me.  However, this still involves extra steps for me to paste the system into this filtered list if I don't want to paste it into the galaxy map to find out if I have already been there.

**Exploration Tab**
Allows for import/export of a route via JSON text. Very cool. If only the websites out there had an export option to JSON. Even so, this tab has no idea which systems I have already visited, and no field selection options (such as already scanned, visited, etc). It does have a note column so I supposed it could be possible to figure it out that way, but this data would still need to come from somewhere.

**Route Tracker**
This tab comes to the closest to this kind of system, one system at at time, but is very minimal and limited for this kind of use. It is very nice that it gives you one system at a time as to avoid any visual stress trying to constantly scan for the next system in the list, but for exploration it lacks any details that might be useful without viewing another tab (such as Estimated Values). This seems to be meant for very long trips (ie., 22k ly).

**Route Finder**
Can find routes from A to B. No exploration options are available. Same can be accomplished in the game galaxy map. 

**Estimated Values**
This is probably the tab used most by explorers or those traveling from A to B to see if anything in a system is worth scanning before moving on.  However, it also has no reference to any scan history.

### Possible Choices for Roads to Riches
**Route Finder**
This has the best mechanism already built in to the application to leverage a route-finding system. Could add a column here for an already scanned system. Could set a metric for Roads to Riches and account for already scanned systems. However, it lacks individual system body entries (system level, not planetary body level entries). Would need to use in combination with Estimated Values tab in order to be feasible.

**New Tab: Roads to Riches**
I believe the best option is for a new module/tab which combines the Route Finder with Estimated Values, with options similar to the existing web-based planners, plus some additional features. See below for more details.

**_Features_**
- Planetary Body Type Search (drop-down)
- Minimum Estimated Scan Value (input box)
- Maximum distance to arrival (input box)
- Remember position on EDDiscovery shutdown/startup (could leverage already scanned bodies option)
- Include/Exclude already scanned bodies (checkbox)
- Show/Hide visited systems in this trip (checkbox)
- Start System (input box with auto populate)
- Target System (input box with auto populate)
- Circle Mode (no Target System entered)
- Via (input box with auto populate) to add way points along the way _[nextgen]_
- Radius (how far away from the path the plotter will deviate to find systems. if in circle mode, ie no target system, this would be a circle in which the systems would be selected from the start system).
- Max distance from start system (input box)
- Max systems in route (input box)
- Include/Exclude populated systems (checkbox)
- Max deviation from route (if target system entered)
- Include/Exclude Neutron stars (checkbox)
- Route only though star-types that can be scooped (checkbox)
- Single Jump Range of ship (input box)
- Total Jump Range of ship (input box)
- Reverse Route (button) - flips the start/target systems around and re-routes
- Auto select start system (button) "History"
- Import from file (JSON/TXT/CSV) w/examples
- Export to file (JSON/TXT/CSV)
- Galaxy Site Button(s) for system currently in (EDSM, EDDB, etc.) in case some data is missing.
- Look in Ship/Loadout to determine if Detail Surface Scanner and Advanced Discovery Scanner are fitted, and if not give a warning indicating these should be fitted to the ship before embarking.
- Remember settings on exit (checkbox or always enabled)

**_Output Form_**
Scan_Num | System_Name | Name | Star_Type | Target_Type | Distance |  Value|  Jumps | Visited
_TOTALS AT BOTTOM FOR_: #, Value, Jumps

### Enhancement Ideas to Assist in Exploration
***History Tab***
None. This should be obvious why,

**Travel History Tab**
Since you can filter by "Scan" event type here, there is no benefit here for this purpose since it doesn't integrate with a route.

**Exploration Tab**
None.

**Route Tracker**
None.

**Estimated Values**
This could be an interesting place to perhaps put a * next to, or a new column for, an already scanned planetary body since a lot of explorers use this tab whilst flying around from A to B looking to make a few coins along the way.

**Comment by klightspeed** [comment]
Be aware that filtering based on body type for systems you have not scanned would require either querying a lot of systems from EDSM (limit 720 per hour), or downloading the bodies dump (currently 19GB).  Filtering by primary star class is only possible for systems where the primary star has been scanned, and would require using EDSM's cube systems API, which is limited to a cube 400x400x400ly.

**Comment by robbyxp1** [comment]
Some points, as Klightspeed said. 

We can't bombard EDSM with queries for data. 

The star dump given by EDSM does not have stellar information in it.

I'm not sure how we could do a route finder in these circumstances.

**Comment by mydevpeeps** [comment]
There must be a way these other websites are doing it. Do you think they downloaded the 20GB database locally and are querying it that way? I can put in a route that is 5000LY and it will kick me back a list.

**Comment by robbyxp1** [comment]
Yep, they must be holding the DB locally on their server and serving it.  They are def. not transferring that size of file to your machine.

**Comment by mydevpeeps** [comment]
A snippet from one of the sites:
The data used by this program comes from [eddb.io](https://eddb.io/).

The list of unpopulated high-value systems can be found [here](https://drive.google.com/file/d/0B-_p8JFokEecZEhPN2J2LTloQWM/view) (1.4MB).
The structure is mostly pretty clear. The following abbreviations were used: "sid" means system id (in eddb), "bid" means body id (in eddb), "dls" means distance in light seconds from jump point, "tp" means planet type, with the following possible values: 26=ELW, 30=HMC, 36=WW.
You can also download the list of populated high-value systems separately [here](http://edtools.ddns.net/expl_pop.json).

So, It looks like they parsed a subset of planet info and are just leveraging that for the searching, maybe?

**Comment by robbyxp1** [comment]
We can grab data from EDSM and store locally in the install a file of interesting systems.. 

I'm not getting into sucking down any more large DBs from EDSM/EDDB - we already download a lot of data.

The list will slowly become out of date but that should not be too bad for this purpose.

So we could enhance the route finder with some options. 

Its a long term thing though, we have to do 10.2 first.

**Comment by robbyxp1** [comment]
And its low because other sites already do this functionality.. and I'm not sure how feasible it is at the moment.

**Comment by robbyxp1** [comment]
Closing, no appetite to do this.  And estimate values is in flux due to 3.3 changes
