### ISSUE TITLE
Voicepack adding an 'm' to "a" body names

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#2087]
This has been there a while - I noticed it back in Octoberish but thought it might have been a quirk of the system.  But many systems later I still hear it.  So it's either my PC, or maybe some odd  left over fragment being spoken aloud maybe?

It *appears* that moons "a" become "a" "m"  (or n...not quite sure actually)
So example.  Byoo Aec IP-N c20-0 2 a is read out as;
Scanned Byoo Aec IP-N c20-0 "2a" "m"

I shot a quick vid of it;
https://youtu.be/bZ-LZf8u8Rc

**Comment by klightspeed** [comment]
Looks like the Microsoft TTS interpreting `2 a` as a time (`2 AM`)

**Comment by robbyxp1** [comment]
Have to see what to do about this... the star names are processed to come out better, may be able to tell TTS not to do this

**Comment by robbyxp1** [comment]
Going to comma out the star names so she pauses.. 10.2

**Comment by Disorganise** [comment]
Good idea :D

⁣Sent from BlueMail ​
