### ISSUE TITLE
Unhandled UI exception (modification during enumeration)

### ISSUE THREAD

**Issue by ohrn** [EDDiscovery/EDDiscovery#2097]
### Description
Exception happned once on start up.

### Exception Details:
>EDDiscovery v10.1.6.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
>   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
>   at EliteDangerousCore.EDSM.GalacticMapping.Find(String name, Boolean contains, Boolean disregardenable) in C:\Code\EDDiscovery\EliteDangerous\EDSM\GalacticMapping.cs:line 133
>   at EliteDangerousCore.HistoryList.FindSystem(String name, GalacticMapping glist) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 652
>   at EDDiscovery.UserControls.UserControlRoute.IsValid() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlRoute.cs:line 199
>   at EDDiscovery.UserControls.UserControlRoute.UpdateTo(Boolean updatename) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlRoute.cs:line 529
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Cheers
