### ISSUE TITLE
3D Star Map: Bug?

### ISSUE THREAD

**Issue by Red13x3** [EDDiscovery/EDDiscovery#21]
What's happened to the 3D star Map?  It is now in colour which is cute, but maybe there should be an option to show the different colours for faction or just stick to b&w with red showing the systems you have visited.

![2015-07-11_001933](https://cloud.githubusercontent.com/assets/13119623/8620540/7f9aa600-2763-11e5-9fa5-7791b9cc77bf.png)

But also, there seems to be a very big reduction in the number of stars shown, as visited by other commanders. Last week, it used to show several trips of commanders travelling around the rim of the galaxy, and another fairly funny "graffitti on our galaxy"... All of these are gone. Is the data still there?

Last point, if you will use blue stars for the empire, I'd suggest making them a little brighter, as they tend to get washed out by the red and green dots.

**Comment by finwen** [comment]
Ops its my testplot by goverment i think.  I forgot to change it back to
old plotting.

2015-07-10 16:27 GMT+02:00 Mark <notifications@github.com>:

**Comment by Red13x3** [comment]
I actually really liked the colouring! :)

Is there a way you could have a "Toggle" on the map that changes it from colour to black & white? The problem is that the Allegiance colors (Red, Blue, Yellow, Green) means that your own travels need to be in white.  Actually... This toggle could also change the map to show:

In B/W:  All known stars in DB in White and the stars you have traveled to in Red. (As it does now)
In Color: Only stars with an Allegiance are shown in their respective colors, and with your travels (only) be shown in White. No other stars shown.

Ooh! And just thought of another idea!  You have in the Travel History a list of all the stars you've traveled to, right?  Could you put on the 3D map a button called "Current System" which centers the map (and the rotation axis') on the last system in your Travel History?

Oh! And then you could also have "Prev" and "Next" buttons that move the center down / up your travel list! (Just thought of that, too! :)

Man, I'm full of ideas, tonight! :)

Should I start a new Issue for these ideas?
