### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Jokonnoh** [EDDiscovery/EDDiscovery#2100]
### Exception Details:
>EDDiscovery v10.1.6.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
>   in EliteDangerousCore.EDSM.EDSMJournalSync.SendEDSMEvents(Action`1 log, IEnumerable`1 helist, Boolean manual) in C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMJournalSync.cs:riga 197
>   in EDDiscovery.EDDiscoveryForm.Controller_NewEntrySecond(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:riga 709
>   in EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:riga 455
>   in EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:riga 433
>   in EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:riga 184
>===== END =====
>```

**Comment by klightspeed** [comment]
Did you delete the commander while it was active?

**Comment by Jokonnoh** [comment]
Probably. I had another CMDR but it wasn't supposed to be active. I deleted it but I'm not sure I did it while that error occurred. Anyway, i have to reset Eddiscovery because i can't sync anymore.

**Comment by robbyxp1** [comment]
Do we want to do anything? Hmmm

**Comment by Jokonnoh** [comment]
After a complete uninstall and a brand new clean install, EDDiscovery seems working. I haven't tryied more than a couple of systems (no much time to play Elite), but it appear to sync data now. I haven't posted the error log for my sync issues, just for help you in case of program's strange behaviours. If the error is just related to CMDR deletion we can close this thread. I'll still continue monitoring the program to check sync related issues. Thank you. Fly safe.
