### ISSUE TITLE
Unhandled UI Exception (When adding Ship Yards to new tab)

### ISSUE THREAD

**Issue by Jinxtrr** [EDDiscovery/EDDiscovery#2102]
### Description
Added a Ships/Loadout tab, then went to add a Ship Yards tab and it threw that error in the title. EDD crashed after closing error.

Screenshot of last 2 added tabs with error --> https://imgur.com/a/V6Vedxn <--

### Exception Details:
>EDDiscovery v10.1.6.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlShipYards.DisplayYard(ShipYard yard) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlShipYards.cs:line 190
>   at EDDiscovery.UserControls.UserControlShipYards.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlShipYards.cs:line 155
>   at EDDiscovery.MajorTabControl.AddTab(PanelIDs id, Int32 tabindex) in C:\Code\EDDiscovery\EDDiscovery\MajorTabControl.cs:line 155
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
`yard.Ships` is used without checking that it isn't null.  `yard.Ships` being null suggests that `ShipYard.json` was overwritten before the most recent `ShipYard` event was read.
