### ISSUE TITLE
Crash upon launching EDDiscovery_10.1.6, tab related.

### ISSUE THREAD

**Issue by eyeonus** [EDDiscovery/EDDiscovery#2109]
New install, not upgrade, no artifacts from previous versions.
Screenshot of error message:
![image](https://user-images.githubusercontent.com/1733600/43680908-ac13a020-9802-11e8-9619-9d9089b55816.png)

**Comment by eyeonus** [comment]
Starting in Safe Mode and performing the steps listed in the error message did not fix the problem.

Win10 64-bit, if that matters.

**Comment by eyeonus** [comment]
Also:
"This is **an** abnormal condition - please **report**problem ...."

**Comment by robbyxp1** [comment]
Did you hit the reset tabs, and then run the program?  It only takes effect if you run the program after pressing the fix button.

**Comment by eyeonus** [comment]
Yes: "Starting in Safe Mode and performing the steps listed in the error message did not fix the problem."

**Comment by klightspeed** [comment]
So the following doesn't work?
* Hold shift while launching to bring up the safe mode dialog
* Click "Reset Tabs, Remove PopOuts"
* Click "Run"

**Comment by eyeonus** [comment]
I get exactly the same result as I did when I ran it the first time. Which isn't surprising, since this was a new install with no old data to cause a corruption.
![image](https://user-images.githubusercontent.com/1733600/43885447-232dc200-9b76-11e8-9817-ce8a71eebbe1.png)

**Comment by spadino** [comment]
I suggest you to try the portable version, to see if something went wrong during the installation. It's the first time I see that behavior, especially on a fresh install. You can also rename %LOCALAPPDATA%\EDDiscovery to %LOCALAPPDATA%\EDDbad and let the program recreate it.

**Comment by eyeonus** [comment]
Yup. Portable version seems to be working fine. Now that I think about it, I'm willing to bet it has something to do with installing EDDiscovery onto a different drive than C:.

Gods I hate Windows. The Registry is a stupid idea. AppData is a stupid idea, MetroUI is a stupid idea, RibbonUI is a stupid idea.....(ramble ramble ramble)

**Comment by eyeonus** [comment]
Get a second hard drive, install to that one.
