### ISSUE TITLE
Can't bind 'PrintScreen' for 'onKeyPress' in Action Files

### ISSUE THREAD

**Issue by vonEdfa** [EDDiscovery/EDDiscovery#2110]
I've noticed that while PrintScreen is available in the drop down list for onKeyPress events EDD doesn't seem to be able to register when that button is pressed.

My goal was to create a custom log of when I've taken screenshots through EDFX and this seems to be the only thing stopping me from getting my little action file add-on working.

Any ideas?

**Comment by robbyxp1** [comment]
I'll check

**Comment by robbyxp1** [comment]
So, Printscreen actually takes a print screen of your whole desktop when you hit it, i don't think that would be a good idea.  

Windows intercept the keystroke so the program does not get the code..

I'm going to remove Print screen from the options list in 10.2

**Comment by robbyxp1** [comment]
Sorry about that!
