### ISSUE TITLE
Mapping issue

### ISSUE THREAD

**Issue by Tuktanuk** [EDDiscovery/EDDiscovery#2112]
You have  10 Bodies listed not including the Star in Col 285 Sector NP-C b14-3. There are only 2 Bodies that actually exist. 
![image](https://user-images.githubusercontent.com/4446795/43735591-00278118-9989-11e8-9169-ae8344828fa0.png)

**Comment by klightspeed** [comment]
Did you have an Advanced Discovery Scanner equipped when you scanned that system?

When you have the EDSM button selected, EDDiscovery retrieves body data from EDSM.  See https://www.edsm.net/en/system/bodies/id/139480/name/Col+285+Sector+NP-C+b14-3

**Comment by Tuktanuk** [comment]
yes, I did have the Advanced scanner

**Comment by klightspeed** [comment]
That would suggest that those planets were an E:D 2.4 anomaly.

**Comment by Tuktanuk** [comment]
I would think so. It's not very often I find mistakes or incorrect data. I
just wanted to let someone know. I actually also found a similar issue
using Road to riches tool.

**Comment by klightspeed** [comment]
When was that taken?
![image](https://user-images.githubusercontent.com/147116/43804133-4e00fab2-9ade-11e8-9d0d-2891bed667af.png)

**Comment by Tuktanuk** [comment]
Looks like Today just a few minutes ago. I honestly don't get it. I was in my exploration ship which has all the scanners and I honk on every system. Why it didn't show up for me is quite odd indeed. I promise I was not meaning to waste anyone's time. I legit thought there was an anomaly.

**Comment by klightspeed** [comment]
When abouts did you scan the system?  In E:D 3.0.3, there was a missing mass bug that removed some planets.

**Comment by Tuktanuk** [comment]
it was Yesterday when I scanned.

**Comment by klightspeed** [comment]
Not sure why your ADS didn't pick up the other 8 planets, unless it was an Intermediate Discovery Scanner in disguise.

In any case, I have now refreshed the planets on EDSM and EDDB.
