### ISSUE TITLE
OBS Plugin

### ISSUE THREAD

**Issue by r04dw4rri0r** [EDDiscovery/EDDiscovery#2117]
Im having issues with EDDiscovery updating the text files OBS creates. It only updates the files whenever I restart the program. It also doesn't update overall wealth/current credits.

**Comment by Ianchandler1990** [comment]
I found that if you edit the obs plugin to the same as this top four to be marked as Always action true it will update the files with each entry to EDD.
![eddiscovery_150014348y090818](https://user-images.githubusercontent.com/18488300/43903795-20784ef8-9be5-11e8-90b4-353fcaaf2275.png)

**Comment by Ianchandler1990** [comment]
overall wealth/current credits is something that plugin wont save but could be added by the owner.

**Comment by robbyxp1** [comment]
I'll check its functionality.

I can add a credit output easily enough

**Comment by Ianchandler1990** [comment]
Rob, I will note it used to work great without the change I posted. didn't use it much so don't know when it stopped working.

**Comment by r04dw4rri0r** [comment]
Thank you everyone for the replies. I will try that fix tonight.

**Comment by robbyxp1** [comment]
I've patched the current OBS to work with 10+ versions of EDD - update via Add Ons

10.2 will have credit output as well..
