### ISSUE TITLE
If a bookmark's system cannot be found, default to the bookmark's position in the editor

### ISSUE THREAD

**Issue by JBHemloque** [EDDiscovery/EDDiscovery#2120]
I saw this as an aftermath of debugging another issue (2118): If a bookmark's system cannot be found in the DB, it will not set the position in the bookmark editor dialog. Then, when we try to update the bookmark, an exception is thrown because we can't parse empty strings into doubles.

**Comment by robbyxp1** [comment]
Thanks!
