### ISSUE TITLE
Ships/Loadout URL for coriolis is incorrect

### ISSUE THREAD

**Issue by KevFerguson** [EDDiscovery/EDDiscovery#2122]
Clicking on the "Send to Coriolis" button in Ships/Loadout takes the user to the deprecated **coriolis.edcd.io** site but should instead be using **coriolis.io**.

**Comment by robbyxp1** [comment]
Thanks for reporting - first I knew.  Will change to it in 10.2

**Comment by robbyxp1** [comment]
Fixed in 10.2
