### ISSUE TITLE
Event type SearchAndRescue does not decrement cargo count

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#2124]
When handing in items to the contact for search and rescue, it looks like the cargo is not removed from EDD.  Example journals;

{"timestamp":"2018-08-16T20:34:13Z","event":"SearchAndRescue","MarketID":128793137,"Name":"usscargoblackbox","Name_Localised":"Black Box","Count":1,"Reward":18842}

{"timestamp":"2018-08-16T20:34:15Z","event":"SearchAndRescue","MarketID":128793137,"Name":"wreckagecomponents","Name_Localised":"Wreckage Components","Count":4,"Reward":30424}

{"timestamp":"2018-08-16T20:34:17Z","event":"SearchAndRescue","MarketID":128793137,"Name":"occupiedcryopod","Name_Localised":"Occupied Escape Pod","Count":14,"Reward":416696}

{"timestamp":"2018-08-16T20:34:19Z","event":"SearchAndRescue","MarketID":128793137,"Name":"damagedescapepod","Name_Localised":"Damaged Escape Pod","Count":5,"Reward":63635}

**Comment by robbyxp1** [comment]
Fixed and tested on 10.2
