### ISSUE TITLE
Windows resizing

### ISSUE THREAD

**Issue by tclancey** [EDDiscovery/EDDiscovery#2125]
Can we please please please have some resize handles at the corners?

**Comment by klightspeed** [comment]
Is this the main window or the popout windows?

The main window can be resized using its edges, and there is also a resize handle on the bottom right.

**Comment by robbyxp1** [comment]
There are.. on the main screen and on each pop up.  Which ones do you mean?

**Comment by robbyxp1** [comment]
Closing, no response.
