### ISSUE TITLE
Star scanning Exception

### ISSUE THREAD

**Issue by nhaslam** [EDDiscovery/EDDiscovery#2127]
### Description
Scanned a star, main star at 64 Orionis. 

### Additional Information
Have had this a few times over multiple versions. only just created a GitHub account though.

### Exception Details:
>EDDiscovery v9.1.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   at EliteDangerousCore.StarScan.ProcessElements(JournalScan sc, ISystem sys, SystemNode sn, String customname, List`1 elements, ScanNodeType starscannodetype, Boolean isbeltcluster) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 736
>   at EliteDangerousCore.StarScan.Process(JournalScan sc, ISystem sys, Boolean reprocessPrimary) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 323
>   at EliteDangerousCore.HistoryList.AddJournalEntry(JournalEntry je, Action`1 logerror) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 797
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 463
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 445
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
>===== END =====
>```

**Comment by nhaslam** [comment]
### Description
When scanning 64 Orionis B (Class A (Blue-White) )

### Additional Information


### Exception Details:
>EDDiscovery v9.1.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   at EliteDangerousCore.StarScan.ProcessElements(JournalScan sc, ISystem sys, SystemNode sn, String customname, List`1 elements, ScanNodeType starscannodetype, Boolean isbeltcluster) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 736
>   at EliteDangerousCore.StarScan.Process(JournalScan sc, ISystem sys, Boolean reprocessPrimary) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 323
>   at EliteDangerousCore.HistoryList.AddJournalEntry(JournalEntry je, Action`1 logerror) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 797
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 463
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 445
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
>===== END =====
>```

**Comment by klightspeed** [comment]
Please upgrade to the latest version - see https://github.com/EDDiscovery/EDDiscovery/releases

**Comment by nhaslam** [comment]
![image](https://user-images.githubusercontent.com/1252118/44303239-5769a100-a333-11e8-820d-5909d3a06f93.png)
Hadn't realised there was a new version, will do...
