### ISSUE TITLE
Enhancement: Green System indicator

### ISSUE THREAD

**Issue by tivec** [EDDiscovery/EDDiscovery#2131]
A green system is one that contains all the materials to make jumponium/FSD injection synthesis. They require having all the following materials:

Arsenic, Cadmium, Carbon, Germanium, Niobium, Polonium, Vanadium, Yttrium

Per today, this is achievable by creating a shopping list set to an arbitrary number (say, 500) of each FSD injection. This would look something like this: 
![image](https://user-images.githubusercontent.com/717574/44574714-77152500-a78a-11e8-82da-475ed1e2a410.png)

While this works, and is definitely not a bad way of checking, it is quite cluttered. My suggestion is to put this in the Scan window like this:
![image](https://user-images.githubusercontent.com/717574/44574816-c3f8fb80-a78a-11e8-9c7f-ccc90714e5ea.png)

The same could also go in the Scan Grid, where the approximate total scan value is also shown.

I do not know if the EDSM data contains the information straight out of the box, but it looks like this if I look the system up on EDSM:
![image](https://user-images.githubusercontent.com/717574/44574878-e854d800-a78a-11e8-9631-25b1c0e81e46.png)

For explorers, I believe this would be a very useful addition. If you are visiting already explored systems, you would get a quick indication if it has the materials, and once you start scanning undiscovered systems, it would light up once you scan and find the last material required.

As a further addition, this could also be something you can find in your journal, or even as a column in the "nearest stars" window.

**Comment by spadino** [comment]
Very good suggestion. Actually, is something I implemented while working on scan grid, than abandoned it. I will look again on that possibility, now that I’m slightly more confident with csharp

**Comment by spadino** [comment]
I'm refactoring ScanGrid to include new features, and I'll provide such functionality too.

**Comment by robbyxp1** [comment]
Close as well?

**Comment by spadino** [comment]
Can be closed. I’ll push the related PR for next release
