### ISSUE TITLE
Enhancement: Make it possible to pop out windows from the + button

### ISSUE THREAD

**Issue by tivec** [EDDiscovery/EDDiscovery#2132]
Right now we have the ability to create a new tab in the main window by right clicking any tab (or the +) and choosing "Insert tab with panel". My suggestion is to add a secondary option - "Open Panel as pop out", just below that option:
![image](https://user-images.githubusercontent.com/717574/44575133-9496be80-a78b-11e8-9ef8-ba1b87487aba.png)

**Comment by robbyxp1** [comment]
Okay

**Comment by robbyxp1** [comment]
Done
