### ISSUE TITLE
System.OutOfMemory

### ISSUE THREAD

**Issue by Amalgamator** [EDDiscovery/EDDiscovery#2142]
### Description
I launched EDDiscovery while Firefox, steam, notepad and mspaint were open. I have 16gigs on this machine. When trying to reproduce, EDDiscovery launched normally.

### Exception Details:
>EDDiscovery v10.1.6.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>   at EDDiscovery.FormMap.InitializeComponent()
>   at EDDiscovery.FormMap..ctor() in C:\Code\EDDiscovery\EDDiscovery\3DMap\FormMap.cs:line 317
>   at EDDiscovery._3DMap.MapManager..ctor(EDDiscoveryForm frm) in C:\Code\EDDiscovery\EDDiscovery\3DMap\MapManager.cs:line 35
>   at EDDiscovery.EDDiscoveryForm.Init(Action`1 msg) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 252
>   at EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:line 145
>===== END =====
>```

**Comment by klightspeed** [comment]
This suggests that your memory was already fully consumed, and Windows had to increase the size of the pagefile, during which time the program's request for memory failed.

**Comment by robbyxp1** [comment]
Closing.. no user response
