### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by geofwlkr** [EDDiscovery/EDDiscovery#2144]
### Description

Tried to open settings as a new tab after updating to v10.2.1.0
### Exception Details:
>EDDiscovery v10.2.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlSettings.checkBoxKeepOnTop_CheckedChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSettings.cs:line 494
>   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
>   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
>   at System.Windows.Forms.CheckBox.set_Checked(Boolean value)
>   at EDDiscovery.UserControls.UserControlSettings.Init() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSettings.cs:line 66
>   at EDDiscovery.MajorTabControl.CreateTab(PanelIDs ptype, String name, Int32 dn, Int32 posindex, Boolean dotheme) in C:\Code\EDDiscovery\EDDiscovery\MajorTabControl.cs:line 246
>   at EDDiscovery.MajorTabControl.AddTab(PanelIDs id, Int32 tabindex) in C:\Code\EDDiscovery\EDDiscovery\MajorTabControl.cs:line 148
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Thanks for the report. It will be patched in 10.2.2.  I'm guessing it does not happen very often, as that bit of code has been in the system for months.
