### ISSUE TITLE
Renamed tab resets after same tab type is added

### ISSUE THREAD

**Issue by mydevpeeps** [EDDiscovery/EDDiscovery#2150]
Steps to reproduce:
1. Add  Journal Tab.
2. Rename Journal Tab to "Mining".
3. Add Journal Tab.

Result:
Mining tab is renamed Journal, and the new Journal tab is named Journal(1).

**Comment by robbyxp1** [comment]
Thanks. Will do a new version next week when I get back

**Comment by robbyxp1** [comment]
So, I can't reproduce it.. with 10.2.2. 

Is it still happening?

**Comment by mydevpeeps** [comment]
happened to me in 10.2.1 actually. I'll try to reproduce it tomorrow on 10.2.1, and then upgrade to 10.2.2 and try it again.

**Comment by mydevpeeps** [comment]
I can't get it to reproduce on 10.2.1 now. just close for now. thanks.
