### ISSUE TITLE
Feature suggestion - bookmark filters and custom keybind profile manager

### ISSUE THREAD

**Issue by goscickiw** [EDDiscovery/EDDiscovery#2151]
It would be useful to be able to filter bookmarks by a group or tag assigned to them. For example, if I want to see only Guardian and Thargoid-related bookmarks, i could mark the "Guardian" and Thargoid" option in the filter There also could be different types of tags, so I could also mark a "Base" option, so then I would only see Thargoid and Guardian bases instead of also wrecks and barnacles.

Also, it would be nice to have a manager for the custom XML keybind groups stored in `AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings` that could be used to automatically create them (based on the main "Custom" file), rename them and delete them. Right now, there is no option in game to create custom keybind profiles other than the main "Custom" one, so it has to be done manually in the folder, by copying the "Custom" file, renaming it and changing the name of the profile in the file. This could be done automatically by a simple program.
Maybe it could also edit the custom profiles. The edit feature would have to be made compatible with all of the different HOTAS devices, but it isn't needed as much, since the copied custom profiles can be later edited in game.

**Comment by robbyxp1** [comment]
We can add a search feature to bookmarks..

We could add a new panel - keybindings, showing your key bindings (we know them already) and allowing you to copy the keybindings file. 

I'm not sure I want to do a keybinding editor though - you can do that in game already.

**Comment by robbyxp1** [comment]
Moving idea  to project.
