### ISSUE TITLE
import/export bookmarks

### ISSUE THREAD

**Issue by karlsnyder1967** [EDDiscovery/EDDiscovery#2152]
Could you add the ability to import/export bookmarks? What I'm thinking is the ability to use Excell (or others) to grab POI lists from Canonn or others (just don't want to type it out). Which is why I had requested the ability to bookmark just a planet without any coords'. Plus gives the ability to perform a backup.

**Comment by robbyxp1** [comment]
Good idea..  to the bookmark panel

**Comment by robbyxp1** [comment]
Done for 10.4 import and export
