### ISSUE TITLE
Stats panel 'by ship' sort is by alphabetic rather than numeric

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#2153]
Just noticed the 'by ship' tab under the statistics column.  Awesome :)
but....when I click the jumps, or travelled ly columns, they sort as if the numbers were letters, rather than as values.  eg, 0, 1003, 135, 17....

probably screenshot will help:
![img](https://i.imgur.com/JQieCGj.png)

**Comment by robbyxp1** [comment]
will fix thanks

**Comment by robbyxp1** [comment]
Fixed
