### ISSUE TITLE
Collect and deliver missions not updating cargo properly

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#2155]
Sorry....this old chestnut again :(

I picked up a bunch of delivery missions that will exceed my cargo capacity.  Initially it looked like no cargo was being registered at all, even though I just collected 6 - and I was gonna log that.  But I was having issues with timing the snip to get the pop up.  *then* I see that I allegedly now have 3 times the cargo to my capacity - so I 'm guessing EDD was doing background stuff and 'frozen' for a bit - that doesn't matter - it still means the cargo isn't right.

I think it's assuming accepting the mission is accepting the cargo, rather than just relying on the "ItemsCollected":6, "ItemsDelivered":0, "TotalItemsToDeliver":6,

The last time my alt did missions was 12th Aug.  3.2 was 28th Aug.  So I'm assuming the either the journal or the game changed.  FWIW, I *think* the game changed - it seems you now accept the mission but get no cargo until you go through the collect part.  I'm guessing this is to allow you to take missions with the 'wrong' ship, go swap ship, and come collect the cargo and then go deliver.

![image](https://user-images.githubusercontent.com/18409322/45907877-25b98d80-be3d-11e8-87dd-85247b09b80b.png)
 
Journal;
{ "timestamp":"2018-09-21T21:45:02Z", "event":"MissionAccepted", "Faction":"Federation Unite!", "Name":"Mission_Delivery_Boom", "LocalisedName":"Boom time delivery of 108 units of Liquor", "Commodity":"$Liquor_Name;", "Commodity_Localised":"Liquor", "Count":108, "TargetFaction":"RSR", "DestinationSystem":"Ceos", "DestinationStation":"Brunel Hub", "Expiry":"2018-09-22T21:44:42Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":928902, "MissionID":420731034 }
{ "timestamp":"2018-09-21T21:45:18Z", "event":"MissionAccepted", "Faction":"Federation Unite!", "Name":"Mission_Courier_Boom", "LocalisedName":"Boom data delivery", "TargetFaction":"RSR", "DestinationSystem":"Ceos", "DestinationStation":"New Dawn Station", "Expiry":"2018-09-22T21:44:42Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":73198, "MissionID":420731093 }
{ "timestamp":"2018-09-21T21:46:30Z", "event":"MissionAccepted", "Faction":"Overlord Armada", "Name":"Mission_Courier_Boom", "LocalisedName":"Boom data delivery", "TargetFaction":"Sirius Corporation", "DestinationSystem":"Ceos", "DestinationStation":"Babbage Gateway", "Expiry":"2018-09-22T21:44:42Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":23114, "MissionID":420731361 }
{ "timestamp":"2018-09-21T21:46:54Z", "event":"MissionAccepted", "Faction":"Deep Space Clan", "Name":"Mission_Courier_Boom", "LocalisedName":"Boom data delivery", "TargetFaction":"Sirius Corporation", "DestinationSystem":"Ceos", "DestinationStation":"New Dawn Station", "Expiry":"2018-09-22T21:44:42Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":22288, "MissionID":420731459 }
{ "timestamp":"2018-09-21T21:46:57Z", "event":"MissionAccepted", "Faction":"Deep Space Clan", "Name":"Mission_Delivery_Boom", "LocalisedName":"Boom time delivery of 6 units of Domestic Appliances", "Commodity":"$DomesticAppliances_Name;", "Commodity_Localised":"Domestic Appliances", "Count":6, "TargetFaction":"Deep Space Clan", "DestinationSystem":"Ceos", "DestinationStation":"Babbage Gateway", "Expiry":"2018-09-22T21:44:42Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":74130, "MissionID":420731470 }
{ "timestamp":"2018-09-21T21:47:02Z", "event":"MissionAccepted", "Faction":"Deep Space Clan", "Name":"Mission_Courier_Boom", "LocalisedName":"Boom data delivery", "TargetFaction":"Sirius Corporation", "DestinationSystem":"Ceos", "DestinationStation":"New Dawn Station", "Expiry":"2018-09-22T21:44:42Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":17022, "MissionID":420731497 }
{ "timestamp":"2018-09-21T21:47:08Z", "event":"MissionAccepted", "Faction":"Deep Space Clan", "Name":"Mission_Delivery_Boom", "LocalisedName":"Boom time delivery of 30 units of Clothing", "Commodity":"$Clothing_Name;", "Commodity_Localised":"Clothing", "Count":30, "TargetFaction":"Deep Space Clan", "DestinationSystem":"Ceos", "DestinationStation":"Brunel Hub", "Expiry":"2018-09-22T21:44:42Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":301906, "MissionID":420731530 }
{ "timestamp":"2018-09-21T21:47:19Z", "event":"MissionAccepted", "Faction":"Deep Space Clan", "Name":"Mission_Courier_Boom", "LocalisedName":"Boom data delivery", "TargetFaction":"Deep Space Clan", "DestinationSystem":"Ceos", "DestinationStation":"Brunel Hub", "Expiry":"2018-09-22T21:44:42Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":15193, "MissionID":420731570 }
{ "timestamp":"2018-09-21T21:47:33Z", "event":"MissionAccepted", "Faction":"Liberate Ceos", "Name":"Mission_Courier_Boom", "LocalisedName":"Boom data delivery", "TargetFaction":"Federation Unite!", "DestinationSystem":"Ceos", "DestinationStation":"New Dawn Station", "Expiry":"2018-09-22T21:44:42Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":27555, "MissionID":420731613 }
{ "timestamp":"2018-09-21T21:47:37Z", "event":"MissionAccepted", "Faction":"Liberate Ceos", "Name":"Mission_Delivery_Boom", "LocalisedName":"Boom time delivery of 6 units of Clothing", "Commodity":"$Clothing_Name;", "Commodity_Localised":"Clothing", "Count":6, "TargetFaction":"Liberate Ceos", "DestinationSystem":"Ceos", "DestinationStation":"New Dawn Station", "Expiry":"2018-09-22T21:44:42Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "Reward":73410, "MissionID":420731626 }
{ "timestamp":"2018-09-21T21:47:57Z", "event":"CargoDepot", "MissionID":420731626, "UpdateType":"Collect", "CargoType":"Clothing", "Count":6, "StartMarketID":128857674, "EndMarketID":128669069, "ItemsCollected":6, "ItemsDelivered":0, "TotalItemsToDeliver":6, "Progress":1.000000 }

**Comment by klightspeed** [comment]
So I'm guessing since 3.2 they've made it so we don't have to special-case delivery missions?
