### ISSUE TITLE
Make Scan Panel and System info update on StartJump etc

### ISSUE THREAD

**Issue by EoD** [EDDiscovery/EDDiscovery#2158]
Scan panel does not update on "Charging FSD" (i.e. "StartJump") event anymore. The feature was introduced with #1242 .

Having a quick look at the history, it seems that c0649308bb905f2d9192630a15acc8ba69f435c7 did major changes to: https://github.com/EDDiscovery/EDDiscovery/blob/9dbbdaed6204f6d4bc972c01d9fd5599b6719a13/EliteDangerous/HistoryList/HistoryEntry.cs#L139
Could this be the issue?

**Comment by robbyxp1** [comment]
Yes, its working as designed.

Please don't re-engineer this ticket yet.  Changing its behaviour will be for a future release

**Comment by EoD** [comment]
@robbyxp1 I partially understand your reasoning. When the ticket originally was created the "StartJump" (i.e. "Charging FSD") event could not be stopped and except for Hyperdiction, I am also unaware there is a way?

**Comment by klightspeed** [comment]
Perhaps controls that are interested in what the next system is (e.g. system info, scan) could process the `StartJump` and `FSDJump` events through OnNewEvent, and have an option to set their displayed system accordingly?

So upon receiving a `StartJump` event to another system (or even a `FSDTarget` when not already overridden), the displayed system would be temporarily overridden to that destination system until either a `FSDJump` or `Location` event is received or the current journal entry is changed in the main travel history control.

You wouldn't want `FSDTarget` to change the displayed system when already in hyperspace, as `FSDTarget` is generated when the next system in the route is targeted, which occurs after entering the new system but before `FSDJump` is generated (which occurs when you enter the system instance).
