### ISSUE TITLE
Synchronization with EDSM. Redundancy of locally stored data.

### ISSUE THREAD

**Issue by raven03** [EDDiscovery/EDDiscovery#2160]
Hello.

I am the user of your application. I apologize, I do not speak English well, so I use machine translation (Google).

Synchronization with EDSM creates a huge database on the local disk, more than 10 GB. Information on tens of millions of star systems, in my opinion, will not be claimed by the majority of users in the volume in which it is stored locally. But if you turn off the synchronization, then some of the features of the application become unavailable.

In addition, when the application is launched for the first time after installation, it starts the full synchronization of the database without a user request. This causes the application to hang, it stops responding and the task manager prompts you to close it.

I'd like to suggest adding a synchronization option, with which only users visited the system would be synchronized.

**Comment by iainross** [comment]
You can use the 'Galaxy Select' button next to the checkbox for enabling/disabling the download to limit the areas that are included if you're not interested in the whole galaxy.

An installation option to say whether you start with the whole galaxy or none of it enabled for download might be a nice idea though.

**Comment by robbyxp1** [comment]
Closing - we already have a method of controlling data base size.  We may introduce a first-run 'what galaxy portion do you want option'..
