### ISSUE TITLE
Run "replacing system tables and re-indexing" run on a non-UI thread

### ISSUE THREAD

**Issue by DerekFoulk** [EDDiscovery/EDDiscovery#2165]
My installation froze completely and started making my game geek out while this process ran. I assume there is a reason this hasn't been done yet, but I'll suggest it anyways... This process should not disrupt the UI thread. I suggest that the re-indexing/replacing tables be performed on a thread separate from the UI.

If it's not too big of a task, I may be able to assist with this. Is there a reason for that it doesn't already?

Thanks for the app!
-Derek

**Comment by klightspeed** [comment]
Systems DB re-indexing does run on a non-UI thread.  Anything trying to access the systems DB during that time will stall (perhaps it should just return a no data result).

The only way this would affect the game is due to the high disk I/O during re-indexing.

**Comment by robbyxp1** [comment]
So it does already.  Closing
