### ISSUE TITLE
10.2.3.0 Fatal Error : An unhandled fatal exception has occurred.

### ISSUE THREAD

**Issue by zsbstephen** [EDDiscovery/EDDiscovery#2166]
OS : Windows 8.1 Enterprise Update 1 x64 zh-cn
Microsoft .Net Framework version : 4.7.1

![0101](https://user-images.githubusercontent.com/19226303/46207032-79a20600-c358-11e8-829e-b0119f611d8b.png)

An unhandled fatal exception has occurred.

==== BEGIN ====
System.AccessViolationException: 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
   在 System.Net.UnsafeNclNativeMethods.OSSOCK.WSAConnect(IntPtr socketHandle, Byte[] socketAddress, Int32 socketAddressSize, IntPtr inBuffer, IntPtr outBuffer, IntPtr sQOS, IntPtr gQOS)
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   在 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   在 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   在 System.Net.Connection.CompleteStartConnection(Boolean async, HttpWebRequest httpWebRequest)
   在 System.Net.Connection.CompleteStartRequest(Boolean onSubmitThread, HttpWebRequest request, TriState needReConnect)
   在 System.Net.Connection.SubmitRequest(HttpWebRequest request, Boolean forcedsubmit)
   在 System.Net.ServicePoint.SubmitRequest(HttpWebRequest request, String connName)
   在 System.Net.HttpWebRequest.SubmitRequest(ServicePoint servicePoint)
   在 System.Net.HttpWebRequest.GetResponse()
   在 BaseUtils.HttpCom.Request(String method, String postData, String action, NameValueCollection headers, Boolean handleException, Int32 timeout) 位置 C:\Code\EDDiscovery\BaseUtils\HTTP\HttpCom.cs:行号 109
   在 BaseUtils.HttpCom.RequestGet(String action, NameValueCollection headers, Boolean handleException, Int32 timeout) 位置 C:\Code\EDDiscovery\BaseUtils\HTTP\HttpCom.cs:行号 58
   在 EliteDangerousCore.EDSM.EDSMClass.GetLogs(Nullable`1 starttimeutc, Nullable`1 endtimeutc, List`1& log, DateTime& logstarttime, DateTime& logendtime) 位置 C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMClass.cs:行号 416
   在 EliteDangerousCore.EDSM.EDSMLogFetcher.FetcherThreadProc() 位置 C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMLogFetcher.cs:行号 112
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by klightspeed** [comment]
Do other programs that use the internet have problems on your computer?

Do you have an antivirus or some other software that might hook winsocks?

Are you able to access https://www.edsm.net/

**Comment by zsbstephen** [comment]
Thx for the reply .
Yep connect to github and edsm might be not that well in China because of the Great Firewall , but actualy I was using shadowsock proxy all the time , and I managed to apply this proxy tunnel to eddiscovery and ed either ~
You might come up with a critical point , I was using proxifier as a transfer tunnel to hook package of eddiscovery , so that it could connect to the server through shadowsocks .

**Comment by robbyxp1** [comment]
I'm surprised it was not caught - line 153 in httpcom should catch it.

**Comment by klightspeed** [comment]
It's a process corrupt exception, which is not handled unless the exception handler explicitly handles process corrupt exceptions.
