### ISSUE TITLE
Inconsistent EDSM data confuses scan panel

### ISSUE THREAD

**Issue by EoD** [EDDiscovery/EDDiscovery#2170]
The system "Eol Prou TD-S d4-60" has been renamed to "Earth Expenditionary Fleet" and EDSM still contains both data: 
https://www.edsm.net/en/system/bodies/id/11075885/name/Earth+Expeditionary+Fleet

If you download EDSM data in your scan panel it looks like this:
![image](https://user-images.githubusercontent.com/293499/46412799-ce120080-c71f-11e8-861e-4d1f960465d0.png)

**Comment by AnthorNet** [comment]
Hello,

Just need to ask EDSM to remove them! It's now done ;)

**Comment by EoD** [comment]
@AnthorNet I thought that maybe EDD wants to implement a protection against such things, so I opened this issue here as well
