### ISSUE TITLE
Synthesising Limpets does not update cargo

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#2173]
It looks like the synthesis of limpets does not update the cargo list
Journal entry:
{
  "timestamp": "2018-10-07T05:03:01Z",
  "event": "Synthesis",
  "Name": "Limpet Basic",
  "Materials": [
    {
      "Name": "iron",
      "Count": 10
    },
    {
      "Name": "nickel",
      "Count": 10
    }
  ]
}

What EDD shows
![image](https://user-images.githubusercontent.com/18409322/46578394-ed27cf80-ca4a-11e8-9758-a14f8a1ce3f1.png)

What inventory shows (after launching 2 of the limpets)
![image](https://user-images.githubusercontent.com/18409322/46578396-fe70dc00-ca4a-11e8-9712-ec177afcfcfc.png)

**Comment by robbyxp1** [comment]
Fixed for 10.3
