### ISSUE TITLE
NullReferenceException when selecting empty route in route tracker

### ISSUE THREAD

**Issue by tweigt** [EDDiscovery/EDDiscovery#2174]
### Description
To reproduce:

1. Go to Expedition panel
2. Click New Route
3. Enter Route Name
4. Check that system list is empty
5. Click Save Route
6. Go to Route Tracker panel
7. Right click, in context menu click Set route, choose route with name from 3.

Appended exception occurs.

### Additional Information

Tell me what you need?

### Exception Details:
>EDDiscovery v10.2.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>   bei EliteDangerousCore.DB.SavedRouteClass.P3D(ISystem s) in C:\Code\EDDiscovery\EliteDangerous\DB\SavedRouteClass.cs:Zeile 369.
>   bei EliteDangerousCore.DB.SavedRouteClass.ClosestTo(ISystem currentsystem) in C:\Code\EDDiscovery\EliteDangerous\DB\SavedRouteClass.cs:Zeile 374.
>   bei EliteDangerousCore.DB.SavedRouteClass.TestHarness() in C:\Code\EDDiscovery\EliteDangerous\DB\SavedRouteClass.cs:Zeile 525.
>   bei EDDiscovery.UserControls.UserControlRouteTracker.setRouteToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlRouteTracker.cs:Zeile 274.
>   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   bei System.Windows.Forms.Control.WndProc(Message& m)
>   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Solved
