### ISSUE TITLE
fatal exception when opening

### ISSUE THREAD

**Issue by Subivan1** [EDDiscovery/EDDiscovery#2180]
A copy of diagnostic information follows.
I have recently had to reinstall windows 10 on a 2012 Imac Bootcamp disk. Everything is now updated and I have reinstalled EDDiscovery. the tool falls over at various times, on opening, on adding to settings etc.

here's the dump
### Exception Details:
>EDDiscovery v10.2.3.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.Data.SQLite.SQLiteException (0x80004005): unable to open database file
>   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
>   at System.Data.SQLite.SQLiteConnection.Open()
>   at EliteDangerousCore.DB.SQLiteConnectionED`1..ctor(Nullable`1 maindb, Boolean utctimeindicator, Boolean initializing, Boolean shortlived) in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionED.cs:line 147
>   at EliteDangerousCore.DB.SQLiteConnectionUser.<>c.<Initialize>b__4_0() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionUser.cs:line 45
>   at EliteDangerousCore.DB.SQLiteConnectionED`1.InitializeIfNeeded(Action initializer) in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionED.cs:line 87
>   at EDDiscovery.EDDiscoveryController.InitializeDatabases() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 383
>   at EDDiscovery.EDDiscoveryController.Initialize(Action`1 msg) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 145
>   at EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:line 137
>===== END =====
>```

Any ideas what I can do? or what I have done wrong?
Cheers

**Comment by klightspeed** [comment]
That error says it is unable to open the EDDUser.sqlite database.

Is `%LOCALAPPDATA%\EDDiscovery\EDDUser.sqlite` accessible?

**Comment by Subivan1** [comment]
I see that, but, I don’t know why. I have since installed an old versions eddiscovery, and everything works fine. I upgrade to the latest version and I get a crash on first 8ntall.

**Comment by klightspeed** [comment]
Would it please be possible to get the version number of the version that worked, and the version number of the version that doesn't work?  Also, if possible, would it please be possible to get the tracelog (from `%LOCALAPPDATA%\EDDiscovery\Log`) for a failed run?

**Comment by Subivan1** [comment]
Thanks very much for the help, hopefully you can find out where I am gong wrong.
Here's the answers to your questions.

Working Version 8.1.3.0
failing version is 10.2.3
I have uploaded 5  log files, first three are from different attempts to install the 10.2.3 version. Final one is the latest one showing the successful use of 8.1.3.

[Trace_2018-10-17-09-52-59.0.log]
(https://github.com/EDDiscovery/EDDiscovery/files/2497966/Trace_2018-10-17-09-52-59.0.log)

[Trace_2018-10-17-17-22-39.0.log]
(https://github.com/EDDiscovery/EDDiscovery/files/2497965/Trace_2018-10-17-09-52-59.0.log)

[Trace_2018-10-19-09-40-12.0.log](https://github.com/EDDiscovery/EDDiscovery/files/2497960/Trace_2018-10-19-09-40-12.0.log)
[Trace_2018-10-19-16-10-37.0.log](https://github.com/EDDiscovery/EDDiscovery/files/2497961/Trace_2018-10-19-16-10-37.0.log)
[Trace_20181019161152.0.log](https://github.com/EDDiscovery/EDDiscovery/files/2497962/Trace_20181019161152.0.log)

**Comment by klightspeed** [comment]
The first 4 logs look like you are running the portable version from `I:\downloads\EDDiscovery`

The first two logs suggest an error while loading the tabs.

The third log suggests that you ran out of disk space after performing a minimal the EDSM systems sync.

The fourth log is odd, as it looks like creating EDDUser.sqlite had failed, and so opening it then failed.

The fifth log looks like you're running the installed 8.1.3 version.

Note that the portable version stores its data in the directory it's run from, while the installed version stores its data in `%LOCALAPPDATA%\EDDiscovery`

**Comment by Subivan1** [comment]
I didn't intentionally install the portable version, I believe I took the exe file option from https://github.com/EDDiscovery/EDDiscovery/releases.  
I have five logs like the first one where it falls over at the tab loading stage
I saw that it suggests I ran out of disk space, but the usb drive I am using has hundreds of gig free so there is space even if it doesn't recognise it, All off my other logs are like the 4th one. 
I will have a clean up and another go and see what happens.

**Comment by Subivan1** [comment]
All's well that ends well as they say. I have just deleted every trace of EDDiscovery from every disk and downloaded the latest version. it is currently scanning my journal files and everything appears to be working OK. Thanks to everybody who looked at the logs.

**Comment by klightspeed** [comment]
Was the USB disk formatted FAT32?  The maximum file size on FAT32 is 4GB, while a fully synced systems DB is about 8GB.

**Comment by Subivan1** [comment]
Good spot, I had forgotten the size restriction. I have reinstalled now on a correctly formatted disk, and all seems well.
