### ISSUE TITLE
my journal don't apear in History tab

### ISSUE THREAD

**Issue by Potatossauro** [EDDiscovery/EDDiscovery#2181]
it does not give an error but it does not appear my history my Jurnal does not synchronize already tried as admin but not worked

**Comment by klightspeed** [comment]
In File Explorer, if you browse to `shell:SavedGames\Frontier Developments\Elite Dangerous`, are there any `Journal.*.log` files?

In the commander dropdown in the EDDiscovery UI, do you have any commanders?

**Comment by Potatossauro** [comment]
> 
> 
> In File Explorer, if you browse to `shell:SavedGames\Frontier Developments\Elite Dangerous`, are there any `Journal.*.log` files?
> 
> In the commander dropdown in the EDDiscovery UI, do you have any commanders?

yes have but she only read the new journal files my old files (August) don't appear

**Comment by Potatossauro** [comment]
I copied the files and formatted the computer then pasted it into the folder.
I don't exclude any Commander

**Comment by klightspeed** [comment]
I'm guessing you copied at the very least EDDUser.sqlite into `%LOCALAPPDATA%\EDDiscovery`?

If not, do you have the journal files from your saved games directory from before you re-formatted your computer?

**Comment by Potatossauro** [comment]
i did't copy EDDUser.sqlite but i have journal files

**Comment by klightspeed** [comment]
In that case, making sure the journals are in `shell:SavedGames\Frontier Productions\Elite Dangerous`, please try moving the new `EDDUser.sqlite` out of the way, and restarting EDDiscovery.

**Comment by Potatossauro** [comment]
works, thx
