### ISSUE TITLE
Add the option to display ammonia world zone in scan panel

### ISSUE THREAD

**Issue by EoD** [EDDiscovery/EDDiscovery#2184]
Similar to the habitable zone, it would be great to have ammonia world zone as well. Similar to what EMC already provides via this plugin: http://edcodex.info/?m=tools&entry=432

![image](https://user-images.githubusercontent.com/293499/47316551-ae4b6980-d647-11e8-8459-8a767ec699e9.png)

@spadino has been working on this already in the past.

**Comment by spadino** [comment]
Yep, already planned. Along with some tweaks to overlays panels...

**Comment by spadino** [comment]
#2198 Will provide the starting point. By now, only Summary Panel is capable of show the new zones, but Scan and ScanGrid will follow very soon...

**Comment by spadino** [comment]
Yep!
