### ISSUE TITLE
Put au as a distance measurement for goldilocks zones

### ISSUE THREAD

**Issue by spinnelein** [EDDiscovery/EDDiscovery#2186]
EDDiscovery shows the habitable zone for a star in ls under Scan. In the game, stars other than the approach star are shown in light seconds from approach rather than distance from the star they're orbiting. 

You can see the orbital distance in the system view, but it's displayed in AU. 

Please display the goldilocks zone for stars other than A as AU rather than ls

**Comment by iainross** [comment]
The detailed scan info shows both

**Comment by spinnelein** [comment]
Oh, thanks!
