### ISSUE TITLE
Trying to launch using mono on linux - Fails to load WindowsSpeechEngine

### ISSUE THREAD

**Issue by cpw** [EDDiscovery/EDDiscovery#2187]
### Description

Trying to launch the portable zip on Linux using mono.

### Exception Details:
>EDDiscovery v10.2.3.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.TypeLoadException: Could not load type 'AudioExtensions.WindowsSpeechEngine' from assembly 'Audio, Version=1.1.6842.18753, Culture=neutral, PublicKeyToken=null'.
>  at EDDiscovery.EDDiscoveryForm.Init (System.Action`1[T] msg) [0x003af] in <5d7e6aa53a0645bfa61510ed8eed54d0>:0 
>  at (wrapper remoting-invoke-with-check) EDDiscovery.EDDiscoveryForm:Init (System.Action`1<string>)
>  at EDDiscovery.EDDApplicationContext.MainEngineStart (System.Object sender, System.EventArgs e) [0x000cd] in <5d7e6aa53a0645bfa61510ed8eed54d0>:0 
>===== END =====
>```

**Comment by klightspeed** [comment]
That sounds like the compiler is inlining the ActionController constructor, and hoisting the resolution of the type `AudioExtensions.WindowsSpeechEngine`.

**Comment by cpw** [comment]
If I disable "Audio.dll" and "Audio.pdb" then it gets to a different spot and crashes.

### Exception Details:
>EDDiscovery v10.2.3.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.TypeLoadException: Could not load type 'EDDiscovery.Actions.ActionController' from assembly 'EDDiscovery, Version=10.2.3.0, Culture=neutral, PublicKeyToken=null'.
>  at (wrapper remoting-invoke-with-check) EDDiscovery.EDDiscoveryForm:Init (System.Action`1<string>)
>  at EDDiscovery.EDDApplicationContext.MainEngineStart (System.Object sender, System.EventArgs e) [0x000cd] in <5d7e6aa53a0645bfa61510ed8eed54d0>:0 
>===== END =====
>```

**Comment by cpw** [comment]
Unfortunately, it looks like this isn't buildable on a vanilla Linux setup, so I can't really debug.

**Comment by klightspeed** [comment]
If you have msbuild and nuget installed (which should be pulled in by e.g. monodevelop), you should be able to compile EDDiscovery from source:

```
git clone https://github.com/EDDiscovery/EDDiscovery.git
cd EDDiscovery
nuget restore
msbuild
```

**Comment by cpw** [comment]
msbuild doesn't exist in debian sadly. It looks like monodevelop was killed a while ago. A typical fate for IDEs - they move too fast for debian to keep up. https://tracker.debian.org/pkg/monodevelop
Ah well. I may dig around and see if I can find a more up to date version.

**Comment by klightspeed** [comment]
xbuild should work for mono 4.8 and lower.

**Comment by cpw** [comment]
Yeah, I found the "official" distribution of mono. Trying...

**Comment by cpw** [comment]
Yeah, this doesn't generate a runnable build sadly. The executable in "bin/Release" is complaining about sqlite errors.

### Exception Details:
>EDDiscovery v10.2.3.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object
>  at EliteDangerousCore.DB.SQLiteConnectionED`1[TConn]..ctor (System.Nullable`1[T] maindb, System.Boolean utctimeindicator, System.Boolean initializing, System.Boolean shortlived) [0x00117] in <dacf61150ad147f1aa43e9518c28bcc4>:0 
>  at EliteDangerousCore.DB.SQLiteConnectionUser..ctor (System.Boolean initializing, System.Boolean utc, EliteDangerousCore.DB.EDDbAccessMode mode) [0x00007] in <dacf61150ad147f1aa43e9518c28bcc4>:0 
>  at EliteDangerousCore.DB.SQLiteConnectionUser+<>c.<Initialize>b__4_0 () [0x00000] in <dacf61150ad147f1aa43e9518c28bcc4>:0 
>  at EliteDangerousCore.DB.SQLiteConnectionED`1[TConn].InitializeIfNeeded (System.Action initializer) [0x00025] in <dacf61150ad147f1aa43e9518c28bcc4>:0 
>  at EliteDangerousCore.DB.SQLiteConnectionUser.Initialize () [0x00009] in <dacf61150ad147f1aa43e9518c28bcc4>:0 
>  at EDDiscovery.EDDiscoveryController.InitializeDatabases () [0x00000] in <7a19774636564f5e9410ef56410cab7a>:0 
>  at EDDiscovery.EDDiscoveryController.Initialize (System.Action`1[T] msg) [0x000ac] in <7a19774636564f5e9410ef56410cab7a>:0 
>  at EDDiscovery.EDDApplicationContext.MainEngineStart (System.Object sender, System.EventArgs e) [0x0005b] in <7a19774636564f5e9410ef56410cab7a>:0 
>===== END =====
>```


So, after much fiddling about - it turns out your "find the SQLite library" doesn't quite work right either and it was failing to load SQLite correctly in the local build. I don't know why. I forced the mono sqlite library and it is now working fine in a local build (with, I guess, voice commands disabled).

**Comment by robbyxp1** [comment]
solved
