### ISSUE TITLE
Trilateration Window Width Issue

### ISSUE THREAD

**Issue by fnordson** [EDDiscovery/EDDiscovery#219]
Would you please make it possible to change the width in the trilateration window?
I have to make the whole window narrower so it fits next to ED. 

_Attached screenshot in case of misunderstanding._

![edd](https://cloud.githubusercontent.com/assets/5624605/15092764/9c8fa474-1473-11e6-8014-1da2945fdb53.jpg)

**Comment by finwen** [comment]
Solved in 3.2.0

**Comment by fnordson** [comment]
Thank you :)
