### ISSUE TITLE
Feature Request: Toggle color/b&w 3D Star Map

### ISSUE THREAD

**Issue by Red13x3** [EDDiscovery/EDDiscovery#22]
IN 2.3.4 there was a "bug" that didn't display all the known stars, just the systems that are pledged to a faction.

I actually really liked the colouring! :)

Is there a way you could have a "Toggle" on the map that changes it from colour to black & white, or from "All Stars / Your Stars" ? The problem is that the Allegiance colors (Red, Blue, Yellow, Green) means that your own travels need to be in white.  This toggle could also change the map to show:

In B/W: All known stars in DB in White and the stars you have traveled to in Red. (As it does now)
In Color: Only stars with an Allegiance are shown in their respective colors, and with your travels (only) be shown in White. No other stars shown.

Ooh! And just thought of another idea! You have in the Travel History a list of all the stars you've traveled to, right? Could you put on the 3D map a button called "Current System" which centers the map (and the rotation axis') on the last system in your Travel History?

Oh! And then you could also have "Prev" and "Next" buttons that move the map center down / up your travel list! (Just thought of that, too! :)

Man, I'm full of ideas, tonight! :)

**Comment by gregmalcolm** [comment]
Looks like the main ask has been addressed now now. There's a filter for turning "white stars" off.

**Comment by Red13x3** [comment]
Yeah, good enough. :)

Mark

--
Mark Jelic
iPhone: 0402 322 901
