### ISSUE TITLE
Bug: Game chrashes when submit Data

### ISSUE THREAD

**Issue by muthan** [EDDiscovery/EDDiscovery#220]
In the last couple of weeks I had often the problem that the game freezes sometimes when I hit submit with calculating coordinates. When this accoures I have always the EDDs own trilat check passed but didn't calculated the "Distance Wrong"-Check yet. So the last row I entered only has my own input in it and not the calculated ones. I also don't get to the point were I get the reply from EDSM.

As additional info, this always accures after a longer session like 1+hr. I also have the feeling that over time EDD geht a bit slower and slower until I restart it. Like some kind of memory handling problem.

Don't know if that accures in 3.1.2 last I had this was with 3.1.1.

**Comment by RedfoxCh** [comment]
Might be related to #128

**Comment by robbyxp1** [comment]
Closing no further input
