### ISSUE TITLE
Voice Pack SMML Error for Events in Chi Persei Sector

### ISSUE THREAD

**Issue by Madproforg** [EDDiscovery/EDDiscovery#2201]
When ever jumping to a system or scanning a planet the voice pack just says out error in SMML markup.
This is only happening for entries in the "Chi Persei Sector"

Extracted a line from the journal where this happens

{ "timestamp":"2018-10-30T20:33:28Z", "event":"StartJump", "JumpType":"Hyperspace", "StarSystem":"Chi Persei Sector UE-Q d5-11", "SystemAddress":387293529939, "StarClass":"A" }

**Comment by robbyxp1** [comment]
Thanks will fix

**Comment by robbyxp1** [comment]
Will be fixed in VP10, for 10.3
