### ISSUE TITLE
Beta 3.3

### ISSUE THREAD

**Issue by bazza14** [EDDiscovery/EDDiscovery#2205]
EDD is not reading the 3.3 beta logs.

**Comment by klightspeed** [comment]
EDDiscovery should put beta logs under `[BETA] CommanderName`

**Comment by bazza14** [comment]
I don't know in what way. It's simply not reading them. I had no issues with the last beta in Feb this year. I have a Beta commander showing in EDD settings and I've set the location of the Journal to the location of the journal.

**Comment by bazza14** [comment]
Perhaps this is the problem.
Beta log
{ "timestamp":"2018-11-08T07:42:31Z", "event":"Commander", "FID":"F1321420", "Name":"Zaphod Beeblebrox IV" }

Normal log
{ "timestamp":"2018-11-08T00:43:47Z", "event":"Commander", "Name":"Zaphod Beeblebrox IV" }

I didn't have that FID field in the Feb beta

**Comment by bazza14** [comment]
Win 10

**Comment by bazza14** [comment]
Weird, tested it today and there were the Beta logs. Closing this.
