### ISSUE TITLE
About the FileHandle of BaseUtils.

### ISSUE THREAD

**Issue by qubeGH** [EDDiscovery/EDDiscovery#2209]
It is a sentence translated from Japanese to English.　sorry that it is hard to read.

Is there a problem with adding [FileShare.ReadWrite] to the attribute of file open?

sample:
BaseUtils.FileHandle
> 
        public bool Open(string f, FileMode fm, FileAccess ac,  out string errmsg)
        {
            try
            {
              //  FileStream file = File.Open(f, fm,  ac);  //change here
                  FileStream file = File.Open(f, fm,  ac, FileShare.ReadWrite);

                if (ac == FileAccess.Read)
                    reader = new StreamReader(file);
                else
                    writer = new StreamWriter(file);

                errmsg = "";
                return true;
            }
            catch (Exception ex)
            {
                errmsg = ex.Message;
                return false;
            }
        }

open a file with Filestream from another application, ActionLanguage will not be able to write the file.

**Comment by klightspeed** [comment]
Probably want `ac == FileAccess.Read ? FileShare.ReadWrite : FileShare.Read`
