### ISSUE TITLE
Some Engineering/Shopping List enhancement suggestions

### ISSUE THREAD

**Issue by goscickiw** [EDDiscovery/EDDiscovery#2212]
1. Experimental Effects are not yet available in the Shopping List, and it would be quite useful to have needed materials/data listed for them as well.

2. A smaller, display-only version of the Shopping List without the tables, showing only the list of needed materials/data, with the ability to link to an existing big Shopping List to get the data. Then, for example, I could put it in a splitter in the main History tab so I don't have to switch tabs to se how much more materials/data I need (I have EDDiscovery on second monitor). I would only have to do so if I want to change something in the tables.

3. Auto-subtract from Wanted (if non-zero) on Engineer Craft or Synthesis event, auto-uncheck from Tech Broker Unlocks (if checked) on Technology Broker event.

~~4. An option to disable/enable displaying planets in system containing the needed raw material in the list.~~ It's already there, I just didn't notice it.

**Comment by robbyxp1** [comment]
Thanks. We have a backlog of stuff to do, and we are at the moment trying to track the journal changes for 3.3.  Not sure when this will be looked at.

**Comment by iainross** [comment]
(4) should already be there in the context menu for the list.

**Comment by goscickiw** [comment]
> (4) should already be there in the context menu for the list.

I didn't notice that before. Thank you.

**Comment by robbyxp1** [comment]
Moved to project ideas.

**Comment by RobinEd** [comment]
second for experimental materials :) Great job guys!
