### ISSUE TITLE
Installer replaced symlink %APPDATA%\EDDiscovery silently

### ISSUE THREAD

**Issue by draeath** [EDDiscovery/EDDiscovery#2232]
Seems the installer is naive when it checks for `C:\Users\{username}\AppData\Local\EDDiscovery`.

If this exists as a symbolic link (`mklink /D`) - done to perhaps relocate data somewhere more appropriate (safe-mode database move *only* moves the sqlite files, not the jsons or other content) - the installer just wipes it out and recreates the directory.

Ideally the installer should not do this.

Fortunately, it only replaces the link, and the data is not lost - but the user must remember to go back and move the new contents over and replace the link.

**Comment by klightspeed** [comment]
It is odd that this only just started occurring when the creation of `%LOCALAPPDATA%\EDDiscovery\Actions` was added in the v6.1.0 installer.

It appears that the reason `%LOCALAPPDATA%\EDDiscovery\Actions` was created no longer exists - in v7.0 the `KeypressesV1.act` file was removed from the installer and instead provided using the Addons installer.  The directory creation should probably be removed from `Installer/EDDiscovery.aip`
