### ISSUE TITLE
When updating database notification into top bar

### ISSUE THREAD

**Issue by juhaeske** [EDDiscovery/EDDiscovery#2234]
Suggestion:
When updating database : Notification box into top of application window. 
Location example next to "Edit Add-Ons" blinking "Updating" notification.
Attached image.

Just to make clear indication that database is under update sequence or arranging data.
Now notification is in lower frame of the program window and might not be noticed.
Closing the application might take really long time due to ongoing data transfer or so.
Also to avoid unwanted data corruption in case of forced shutdown.

![ed discovery](https://user-images.githubusercontent.com/21039267/49281108-60225500-f494-11e8-8189-1dc1d53380a2.PNG)

**Comment by robbyxp1** [comment]
Have to have a think about this

**Comment by robbyxp1** [comment]
I've done it in another way.. when its doing the database update asking for close gives you a warning dialog to ask if you really want to close down during an update.

Thanks for the idea ;-)
