### ISSUE TITLE
Reporting as asked to.

### ISSUE THREAD

**Issue by EthanYvormes** [EDDiscovery/EDDiscovery#2235]
### Exception Details:
>EDDiscovery v10.3.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: No room is available to display rows.
>   at System.Windows.Forms.DataGridView.set_FirstDisplayedScrollingRowIndex(Int32 value)
>   at ExtendedControls.DataViewScrollerPanel.SetFirstDisplayed(Int32 count) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\DataViewScrollerPanel.cs:line 165
>   at System.Windows.Forms.Control.OnMouseWheel(MouseEventArgs e)
>   at System.Windows.Forms.DataGridView.OnMouseWheel(MouseEventArgs e)
>   at System.Windows.Forms.Control.WmMouseWheel(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
That suggests that the panel containing that the grid you were trying to scroll was made too small.

**Comment by robbyxp1** [comment]
Any idea what caused this? Which window you were using..

if it persists, hold down shift during launching the program and use the reset windows positions option

**Comment by robbyxp1** [comment]
Presume fixed. Please re-open if you need more help.
