### ISSUE TITLE
NPC Crew statistics are blank

### ISSUE THREAD

**Issue by goscickiw** [EDDiscovery/EDDiscovery#2238]
I noticed that the NPC crew statistics in the Statistics panel are all 0 (I have NPC crew):
![2](https://user-images.githubusercontent.com/39399945/49685267-20d1b500-fae1-11e8-807b-3cf77f147426.png)

In the Statistics event in History, they're just blank:
![1](https://user-images.githubusercontent.com/39399945/49685268-24653c00-fae1-11e8-8498-ca0653af39d1.png)

However, they look fine in EDSM and Inara:
![3](https://user-images.githubusercontent.com/39399945/49685335-65118500-fae2-11e8-99f2-d1e3806891af.PNG)
![4](https://user-images.githubusercontent.com/39399945/49685338-68a50c00-fae2-11e8-84ca-3b17a106dc53.PNG)

I am using EDD version 10.3 with ED 3.2.

Journal files: [Journal.zip](https://github.com/EDDiscovery/EDDiscovery/files/2659628/Journal.zip)

**Comment by robbyxp1** [comment]
Have a look for the last statistics journal entry
i'm betting that frontier has not filled in the data.. mine for instance has Crew info as empty..

 "Crew": {},
  "Multicrew": {
    "Multicrew_Time_Total": 0,
    "Multicrew_Gunner_Time_Total": 0,
    "Multicrew_Fighter_Time_Total": 0,
    "Multicrew_Credits_Total": 0,
    "Multicrew_Fines_Total": 0
  },

Right click on the last statistics entry and do "Copy journal entry to Clipboard/log" to see the raw frontier data.

**Comment by goscickiw** [comment]
In my case, after copying to log, the "Crew" part looks like this:
```
  "Crew": {
    "NpcCrew_TotalWages": 7680479,
    "NpcCrew_Hired": 1
  },
```
This matches the data visible in EDSM and Inara.

**Comment by klightspeed** [comment]
`Crew` is never set in `JournalStatistics` - looks like an oversight.
