### ISSUE TITLE
Inara Send Error - Unknown engineer name (and EDDN sync exceptions)

### ISSUE THREAD

**Issue by goscickiw** [EDDiscovery/EDDiscovery#2246]
I'm getting this error in EDD log when it attempts Inara sync:
```
INARA Send Error: Error to request setCommanderRankEngineer {
  "eventName": "setCommanderRankEngineer",
  "eventTimestamp": "2018-12-12T17:15:42Z",
  "eventData": {
    "engineerName": null,
    "rankValue": 1
  }
} with Unknown engineer name.
```
I'm using EDD 10.3.1 with ED 3.3 now.
Journal files: [Journal.zip](https://github.com/EDDiscovery/EDDiscovery/files/2672857/Journal.zip)

Edit: Also, I'm getting EDDN sync exceptions:
`EDDN sync Exception Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.`
The Polish part probably comes from OS language. It means "Object reference not set to an instance of an object".

**Comment by robbyxp1** [comment]
we have put more debug output into EDDN system for todays release..  should help us find this.
