### ISSUE TITLE
Wrong total (amount + bonus) on Sell Exploration Data

### ISSUE THREAD

**Issue by EnterTheNameHere** [EDDiscovery/EDDiscovery#2257]
I've sold eploration data at Universal Cartographics, but there seems to be an issue with the total amount. Here is the information from EDDiscovery:
https://imgur.com/tLHWoOr

Here is entry from Codex:
https://imgur.com/PisLc15

And here is Copy journal entry to clipboard/Log
```
{
  "timestamp": "2018-12-15T07:26:49Z",
  "event": "SellExplorationData",
  "Systems": [
    "58 Geminorum"
  ],
  "Discovered": [
    "58 Geminorum BC 1",
    "58 Geminorum BC 9",
    "58 Geminorum A 2",
    "58 Geminorum BC 6",
    "58 Geminorum A 9",
    "58 Geminorum A 5",
    "58 Geminorum BC 7",
    "58 Geminorum BC 5",
    "58 Geminorum A 8",
    "58 Geminorum BC 8",
    "58 Geminorum BC 4",
    "58 Geminorum A 10 A Ring",
    "58 Geminorum A 3",
    "58 Geminorum BC 3",
    "58 Geminorum A 4",
    "58 Geminorum A 7",
    "58 Geminorum A 1",
    "58 Geminorum A 6"
  ],
  "BaseValue": 9858271,
  "Bonus": 9450644,
  "TotalEarnings": 10058271
}
```

**Comment by EnterTheNameHere** [comment]
As you can see, the total amount EDDiscovery thinks is sum of BaseValue + Bonus, but Total Earnings are not the sum. The wrong amount is then reported to INARA etc.

**Comment by klightspeed** [comment]
EDDiscovery uses `BaseValue + Bonus` when `TotalEarnings` is lower due to a bug in E:D 3.0.2 (where TotalEarnings was much lower).

**Comment by klightspeed** [comment]
Just how many earthlikes or water worlds did that system have?  And the `Discovered` says you should have earned a bonus.  Yet the difference between `BaseValue` and `TotalEarnings` is 0, suggesting either `BaseValue` is bogus or you got no first discovery bonus.

Looks like we need to alter the test to only try to correct the error if the event was from before e.g. April 2018.

**Comment by EnterTheNameHere** [comment]
58 Geminorum is:
2 high metal content terraforming candidate I discovered and mapped first (according to in game system map)
10 high metal content (non candidate) I discovered and mapped first
1 high metal content being terraformed (not me)
1 water world terraforming candidate (not me)
5 icy body I discovered and mapped first


HR 2711 is:
1 high metal content terraforming candidate I discovered and mapped first
1 high metal content terraforming candidate not discovered by me or mapped by me first
1 high metal content (only) mapped by me first
1 water world being terraformed (not me)
4 high metal content (not candidate, not me)
2 rocky bodies mapped by me first
1 gas giant with water based life mapped by me first
1 class III giant (not me)
1 metal rich body (not me)
+ 2 class F stars


These are populated systems in local bubble, not far away; I just probe all of them and sometime land if there is geological signal to scan it. It seems weird that I "rediscover" these, if they are already populated systems though.

**Comment by klightspeed** [comment]
This should be fixed in the next release (by #2258)

**Comment by EnterTheNameHere** [comment]
It was a good question anyway, so I checked it out, because it looks like really excessive bonus and in-game it's not really well explained what bonus amount you are getting for what.

Thank you for quick fix and really, really thank you and all developers for EDDiscovery, it should come with the game itself!

**Comment by robbyxp1** [comment]
So its fixed, but until we understand the new exploration payouts the whole estimation is wobbly.
