### ISSUE TITLE
Overlay for showing which bodies you have mapped in a system

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#2262]
Finding out whether you already mapped a body or not is quite clunky.  You have to exit FSS and go to System map to see the text.

So...
Could we add two things to EDD?

1) In the scan map that shows all the bodies with the name, gravity and materials, could we have an icon or colour change to indicate the body is mapped?

2) Since not everyone has the luxury of a 2nd screen to run EDD, could we have an overlay also to show same.  I'm thinking a list of bodies such as
A1
A2
A4a
A4b
and so on
which is populated as you scan (thus showing what is 'missing'), and an asterix to indicate it is mapped.
Alternatively, for those not wanting a big list, perhaps a toggle to NOT list all bodies, but only the ones that are mapped.

I think this is probably the driving journal entry.  
{
  "timestamp": "2018-12-16T00:00:55Z",
  "event": "SAAScanComplete",
  "BodyName": "Greae Phoea SZ-E d12-1903 4 a",
  "BodyID": 24,
  "ProbesUsed": 2,
  "EfficiencyTarget": 4
}

**Comment by robbyxp1** [comment]
Good idea.  We are going to add this.

**Comment by robbyxp1** [comment]
1. is done

2. is more work and will be later.

**Comment by robbyxp1** [comment]
Moving to project list.
