### ISSUE TITLE
Latest version continuously pulls systems data

### ISSUE THREAD

**Issue by Frerduro** [EDDiscovery/EDDiscovery#2265]
In the latest version it seems to be pulling systems data every second instead of every hour
![image](https://user-images.githubusercontent.com/35627247/50138579-e5a75280-0253-11e9-8cb9-abd2c9506981.png)

**Comment by klightspeed** [comment]
It looks like EDSM was probably returning a 200 OK instead of a 503 service unavailable, and the defence added in e7c4189 did not abort the sync when an error occurred processing the data from EDSM.
