### ISSUE TITLE
[10.3.2.0] Crashes

### ISSUE THREAD

**Issue by EagleMountainDK** [EDDiscovery/EDDiscovery#2268]
Hi

Just upgraded to the latest release and starting version 10.3.2.0 crashes EDDiscovery with the following error:
### Exception Details:
>EDDiscovery v10.3.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlScanGrid.DrawSystem(HistoryEntry he, Boolean force) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlScanGrid.cs:line 251
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 482
>   at EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl, Boolean disablesorting) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 242
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshComplete(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 843
>===== END =====
>```

Cheers
Mark

**Comment by robbyxp1** [comment]
Investigating

**Comment by robbyxp1** [comment]
In the meanwhile, turn off the scan grid.. may only be one system which causes it

**Comment by EagleMountainDK** [comment]
My pilot is in Deciat if I can help you in any way. Removing the tap make the error go away. And adding it again gives the error :)

**Comment by robbyxp1** [comment]
Thanks

**Comment by robbyxp1** [comment]
with the tab closed, i'd select another system on the history .. then open the tab.  right click on the grid and turn off show structures. that might solve it for now.

**Comment by klightspeed** [comment]
Did you drop out at an asteroid cluster without scanning it?

**Comment by EagleMountainDK** [comment]
Hmmmm not sure what you mean exactly? At my current location or sometime before?
