### ISSUE TITLE
EDD Crash 10.3.2.0

### ISSUE THREAD

**Issue by eplossl** [EDDiscovery/EDDiscovery#2269]
I'm not sure if this is possibly related to bug #2268, but my EDD has now crashed showing an unhandled fatal exception has occurred.  The following is the debug information that it made available:

### Description
Unfortunately, I'm not sure exactly what it was doing at the time of the crash, if mostly because I'm not sure when it crashed.  I was last playing two nights ago and it seemed to be working fine, although there did seem to be some latency for stuff getting updated to Inara.  Either way, I happened to minimize other windows today and noticed the crash.

### Additional Information
Nothing I can give at the moment.  Let me know if you need anything specific, please.

### Exception Details:
>EDDiscovery v10.3.2.0 An unhandled fatal exception has occurred.
>```
>==== BEGIN ====
>System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>   --- End of inner exception stack trace ---
>   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>   at System.Delegate.DynamicInvokeImpl(Object[] args)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.Form.WndProc(Message& m)
>   at ExtendedControls.SmartSysMenuForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\SmartSysMenuForm.cs:line 224
>   at ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\DraggableForm.cs:line 124
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
>   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
>   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
>   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
>   at EDDiscovery.Program.Main() in C:\Code\EDDiscovery\EDDiscovery\Program.cs:line 47
>===== END =====
>```

**Comment by robbyxp1** [comment]
Let us know if it happens again.  There is no part of our program in the trace, its all windows stuff.  Will have to have a think.

**Comment by robbyxp1** [comment]
Hmmm that one is hard to find.  lets see how reproducible it it.

**Comment by klightspeed** [comment]
This smells like a graphics driver issue with the 3D map.  Alternatively, it could be a third-party Windows UI extension.

AccessViolationException generally means that native code dereferenced a null or invalid memory pointer.  AccessViolationExceptions can't usually be caught as they usually indicate the process state is corrupt - this is why it was a fatal exception rather than a UI exception, even though it occurred in the UI thread.

**Comment by robbyxp1** [comment]
Closing, reopen if anything occurs like this
