### ISSUE TITLE
'Show 2D maps' as a menupoint still necessary?

### ISSUE THREAD

**Issue by muthan** [EDDiscovery/EDDiscovery#227]
Just a thought.

Under Tools there is still the `Show 2D maps` button. Is it still needed with the `2D Map` button on the `Travel history`? Or should it at least be constistent with the 3D map buttons?

**Comment by robbyxp1** [comment]
3d map button is now there, as is the 2d map button.  We are now consistent. Useful if your not viewing the main travel grid.
