### ISSUE TITLE
Inara reporting unknown commanders

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#2273]
I don't always pay attention to the start log so this may have been there before - it also be normal so no worries if it is.
Started EDD 10.3.2.0 and got the following in the log after the rank and progress events;

INARA Reports: Inara reports commander Rewision is not known to it
Inara reports commander Duckfather is not known to it
Inara reports commander Chankk Saotome is not known to it

These Commanders I were on-line when I entered the game and they're in my friends list.  So were two others according to the information panel;

Online:5
Rewision, Online
Gramps, Online
Duckfather, Online
Maia Posidana, Online
Chankk Saotome, Online

**Comment by robbyxp1** [comment]
Normal.. These commanders are not in Inara.  Its just saying that it does not have a commander of that name in Inara to add to your friend list.
