### ISSUE TITLE
Not all scanned bodies are marked as scanned in EDSM, wrong Total Fired NPC crew count

### ISSUE THREAD

**Issue by goscickiw** [EDDiscovery/EDDiscovery#2276]
Some of the celestial bodies that I scanned (just FSS, not mapped) are displayed as not yet scanned in EDSM, even the ones that I discovered and sent first.
Other data about them seems to be sent properly.
The "Send unsynced scan to EDDN" option for these bodies is disabled.

For example, in this system, I scanned all the bodies:
![11](https://user-images.githubusercontent.com/39399945/50289547-786d0a80-0469-11e9-81f0-0e7a2dda4b02.png)

Some of them are like this (correct):
![12](https://user-images.githubusercontent.com/39399945/50289783-1234b780-046a-11e9-94db-fe258ab98f3f.PNG)

And some are like this.
![13](https://user-images.githubusercontent.com/39399945/50289799-1d87e300-046a-11e9-99b7-fcae43cddf76.PNG)

And the main star (auto scanned - this is not a problem only with autoscan though - some stars have correct scanned status, some don't, just as it is with other FSS scanned bodies):
![14](https://user-images.githubusercontent.com/39399945/50289809-24165a80-046a-11e9-9f9c-8e9e9124be51.PNG)
A star probably shouldn't have a mapped status, but that's an EDSM issue.

Also involving scans, in one system (Delphi) EDD didn't register the first main star autoscan - showed "Main Star" wireframe instead. I fixed it by scanning the nav beacon, but in unpopulated systems it may be a problem.

Also, the Total Fired counter in NPC Crew statistics shows 1 where it should be 0:
![16](https://user-images.githubusercontent.com/39399945/50290646-9ee07500-046c-11e9-9973-d48a5bcb5e6d.PNG)

In the History entry it looks fine:
![17](https://user-images.githubusercontent.com/39399945/50290682-b7e92600-046c-11e9-87d0-28075f6018c9.png)

After copying to log:
```
  "Crew": {
    "NpcCrew_TotalWages": 11823279,
    "NpcCrew_Hired": 1
  },
```

Journal files: [Journal.zip](https://github.com/EDDiscovery/EDDiscovery/files/2699174/Journal.zip)

**Comment by AnthorNet** [comment]
Did you untick the delay EDDN options from EDSM too in your settings?

**Comment by goscickiw** [comment]
If you mean the "Delay scanned celestial bodies until docked?" option from Public Profile settings in EDSM, then I have it on, but I have already docked and sold the exploration data.

By the "Send unsynced scan to EDDN" option, I meant the one in the context menu for a History entry - it's grayed out.

I have "Send Event Information to EDDN" enabled in commander settings.

**Comment by AnthorNet** [comment]
If it is tick On in EDSM, you will have to wait for our background scanner to process them, can take some time

**Comment by goscickiw** [comment]
I suspected it may be because of EDDN being overloaded from the massive influx of scans after 3.3. I'll wait and see how these systems look like after some time.
