### ISSUE TITLE
Installer: Some files that need to be updated are currently in use / firefox

### ISSUE THREAD

**Issue by lwt-pressy** [EDDiscovery/EDDiscovery#2280]
While installing I get the warning "Installer: Some files that need to be updated are currently in use". As relevant application Firefox is named. So I wander which files this could be, based on security issue this overlapping gives me a bad taste.

Version: 10.3.3

![unbenannt](https://user-images.githubusercontent.com/13365281/50354790-e807f600-054c-11e9-92bf-303bacce2d11.PNG)

**Comment by klightspeed** [comment]
The only shared file I can think of is the Eurocaps font.

If you use Process Explorer, does Firefox have `C:\Windows\Fonts\EUROCAPS.TTF` open?

**Comment by lwt-pressy** [comment]
These are the open fonts (no eurocaps) for firefox:
File	C:\Windows\Fonts\segoeui.ttf
File	C:\Windows\Fonts\segoeuib.ttf
File	C:\Windows\Fonts\segoeuii.ttf
File	C:\Windows\Fonts\segoeuil.ttf
File	C:\Windows\Fonts\segoeuisl.ttf
File	C:\Windows\Fonts\segoeuiz.ttf
File	C:\Windows\Fonts\seguibl.ttf
File	C:\Windows\Fonts\seguibli.ttf
File	C:\Windows\Fonts\seguiemj.ttf
File	C:\Windows\Fonts\seguili.ttf
File	C:\Windows\Fonts\seguisb.ttf
File	C:\Windows\Fonts\seguisbi.ttf
File	C:\Windows\Fonts\seguisli.ttf
File	C:\Windows\Fonts\StaticCache.dat
File	C:\Windows\Fonts\tahoma.ttf
File	C:\Windows\Fonts\times.ttf

PS: interesseting tool btw.

**Comment by robbyxp1** [comment]
I've seen this too.  As Klightspeed says, its probably the font.  Nothing else could be shared.

We will try and massage around it. 

thanks

**Comment by robbyxp1** [comment]
In progress for 10.4

**Comment by robbyxp1** [comment]
10.4 will have the TTF shipped in the exe folder, but not installed by the installer, and not picked up by the local font load.  And i'll tell the user where to install manually the font.  Until we solve the font selection issue i think thats the best we can do.
