### ISSUE TITLE
Unhandled Journal Event

### ISSUE THREAD

**Issue by MrSharku** [EDDiscovery/EDDiscovery#2286]
Since the Chapter 4 Update 12/12/18 when I do a scan the Description says: SAA Scan Complete.
In the Information it says: Unhandled Journal Event, Report to EDDiscovery Team.
I had same message the 1st 2 times FSS Discovery Scan but then it worked fine.

**Comment by klightspeed** [comment]
What version are you using?

**Comment by MrSharku** [comment]
9.1.4.0
I just checked and no new updates.

**Comment by klightspeed** [comment]
Latest version is 10.3.3
Not seeing updates is a known issue with 9.1.x
Latest version is always at https://github.com/EDDiscovery/EDDiscovery/releases/latest

**Comment by MrSharku** [comment]
Thanks. Updating now. :]
