### ISSUE TITLE
Parsing distance input in trilateration gridview

### ISSUE THREAD

**Issue by robertliska** [EDDiscovery/EDDiscovery#229]
**Low priority**
Methods for validation and conversion of distance inputs tries to help by replacing "." to "," for people which have comma as decimal separator. Though if you have "," (comma) as decimal separator only for currency values (and numbers decimal separator is "." (dot)) you are unable to enter decimal places at all. 

I would suggest to replace `CurrencyDecimalSeparator` with `NumberDecimalSeparator`since `double.TryParse` use obviously the latter one. 

Related part of code:
`if (Application.CurrentCulture.NumberFormat.CurrencyDecimalSeparator.Equals(","))  // To make it easier for  regions that uses , as deciaml separator. .   allow them to use . also
                        value = value.Replace(".", ",");
`

**Comment by klightspeed** [comment]
This appears to have been fixed in PR 233
