### ISSUE TITLE
unhandled UI exception

### ISSUE THREAD

**Issue by Jantik** [EDDiscovery/EDDiscovery#2290]
### Exception Details:
>EDDiscovery v10.3.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: Nullable object must have a value.
>   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>   at EDDiscovery.UserControls.UserControlScanGrid.DrawSystem(HistoryEntry he, Boolean force) in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScanGrid.cs:line 189
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 489
>   at EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl, Boolean disablesorting) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 246
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshComplete(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 843
>===== END =====
>```

**Comment by klightspeed** [comment]
Would it please be possible to get the scan journal entries for the system where this occurs?

Looking, one possibility is that the `Atmosphere` is not null and not `None`, but no `SurfacePressure` is present.
