### ISSUE TITLE
[Bug] Duplicates in Visited Star list.

### ISSUE THREAD

**Issue by Lethann** [EDDiscovery/EDDiscovery#2297]
Similar to #1579 maybe? 

When I open up my Visited Stars tab it has all systems duplicated down to the exact second timestamp. And this isn't just from my current session, this is all time. 

![edd duplicate visited bug](https://user-images.githubusercontent.com/25929754/50606095-13161200-0e8a-11e9-903c-31af9f12656a.JPG)

Here is an exported excel workbook of the entire log as well:

[visitedstarstest.xlsx](https://github.com/EDDiscovery/EDDiscovery/files/2721645/visitedstarstest.xlsx)

**Comment by robbyxp1** [comment]
Found. Fixed. Thanks
