### ISSUE TITLE
edsm/eddm control

### ISSUE THREAD

**Issue by Shazzsmifff** [EDDiscovery/EDDiscovery#2299]
the esdm/eddm control, any chance of it showing how much space each download option will take up, and how much it needs to down

**Comment by robbyxp1** [comment]
We have no idea.. no idea how much each sector will take, and how quickly the data grows.  Thats up to the commanders who submit info to EDSM/EDDB, and it does not report size before you download.

**Comment by AnthorNet** [comment]
There is a . length file along each dump if needed ;)

**Comment by robbyxp1** [comment]
Not going to work for the purposes the user wants.

**Comment by klightspeed** [comment]
EDDiscovery uses its own grid system (not aligned to any sector boundaries) to pick what areas to store in its database.  To have the desired reduction in download size, we would need to process and store the split daily systems dump.  While I can do this on EDGalaxyData, I don't know if others would accept it.
