### ISSUE TITLE
10.3.4 Not sending events to EDSM

### ISSUE THREAD

**Issue by Evanruoss** [EDDiscovery/EDDiscovery#2312]
Just updated the client to 10.3.4 yesterrday and noticed it didn't send log events to EDSM or Inara.

Did some research and found the verboselogging fix, but those articles were all several years old, and upon locating the appconfig file, it appears the Network section has changed a bit since then.

Do I still need to add that line in AppConfig.xml or am I having a whole different issue?  Sort of figured verboselogging is old, since EDD 10.3.3 was able to send my logs no problem.

**Comment by robbyxp1** [comment]
In Settings, go to your commander, Edit it.

Check your API key vs the EDSM API key, and check that the EDSM commander name matches the EDSM name you use.  Check you have it enabled..

Same with Inara.

**Comment by robbyxp1** [comment]
Presume okay.
