### ISSUE TITLE
Changing the keybinds in KeyPressesV5

### ISSUE THREAD

**Issue by DR-JFZoidberg** [EDDiscovery/EDDiscovery#2313]
Is there any documentation on changing the key binds to different functions? I am trying to bind a key to a custom grid tab named ''at a glance.'' Under the last field to the right, I tried replacing the preset tabs with the names of my own tab setup. None of the binds that I changed work. Any advice?

**Comment by robbyxp1** [comment]
This area has been left behind by the expansion of tabs.. i'll have a look tomorrow and see if its easy to add a new command to 10.4 so you can select tabs by name.

10.3 won't support it.

**Comment by robbyxp1** [comment]
Hmm try a command ProgramWindow "name"
That should switch to the tab.

**Comment by robbyxp1** [comment]
Sorry ProgramWindow tab "name"
