### ISSUE TITLE
Sending invalid parameters for Engineer ranks to Inara.

### ISSUE THREAD

**Issue by Moleculor** [EDDiscovery/EDDiscovery#2314]
EDD is sending a rankValue parameter to Inara for Engineers that are not unlocked.

This marks the engineer as unlocked on Inara's website, despite them not being unlocked.

rankValue should not be sent for engineers that are not unlocked.

For example, it's sending this for me:

{
      "eventName": "setCommanderRankEngineer",
      "eventTimestamp": "2019-01-10T20:04:10Z",
      "eventData": {
        "engineerName": "Etienne Dorn",
        "rankStage": "Invited",
        "rankValue": 1
      }

And that marks the Engineer as unlocked, due to the "rankValue": 1.

According to their API documentation (https://inara.cz/inara-api-docs/#event-9): Note: 'rankStage' and 'rankValue' properties aren't required, but there should be at least one property set. When the 'rankValue' is set, engineer will be in a stage 'Unlocked', doesn't matter what was set.

**Comment by robbyxp1** [comment]
I'll talk to Artie.

**Comment by robbyxp1** [comment]
10.4 will have this fixed,.. Not expected for another week or so.

**Comment by robbyxp1** [comment]
static public JToken setCommanderRankEngineer(string name, string progress, int value, DateTime dt)

fix it so value can be null...

**Comment by robbyxp1** [comment]
Fixed 10.4
