### ISSUE TITLE
EDDI won't launch (EDDiscovery is not responding)

### ISSUE THREAD

**Issue by Shmexysmguy** [EDDiscovery/EDDiscovery#2318]
When I try and launch EDDiscovery, the loading window pops up and it goes through the various messages, then stops at the "repairing canopy" one every time. I noticed this a few days ago, and restarting my computer and reinstalling EDDI hasn't fixed anything. I've tried older versions, back to 10.3.2 when 3.3 support was added, the same issue persisted. I used it post 3.3, and I don't know of any updates or changes that would've broken things, so I'm at a loss for what's going on.

**Comment by klightspeed** [comment]
When you look at what windows the program has open, is there a message box?

"Repairing Canopy" is printed when themes are being loaded and tabs are being restored.

Please try holding shift while starting EDDiscovery, and resetting your tabs.

**Comment by klightspeed** [comment]
Note also that EDDI and EDDiscovery are totally different programs.

**Comment by klightspeed** [comment]
Is there a trace log in `%LOCALAPPDATA%\EDDiscovery\Log`?  What is the last event logged in that file?

**Comment by Shmexysmguy** [comment]
[Trace_2019-01-13-15-39-58.0.log](https://github.com/EDDiscovery/EDDiscovery/files/2753701/Trace_2019-01-13-15-39-58.0.log)
This is the latest trace log

**Comment by klightspeed** [comment]
That last line suggests that the program was exited during "Replacing old systems table with new systems table and re-indexing - please wait"

You can try removing EDDSystem.sqlite and having the program rebuild it.

**Comment by Shmexysmguy** [comment]
That did the trick, thanks! Launches normally now, and also somehow saved all my tabs and theme and stuff despite all the resets and reinstalls. Thank you again!

**Comment by robbyxp1** [comment]
SQLLite code sometimes barfs and breaks the database.. Glad it fixed it.
