### ISSUE TITLE
Feature Request - Remove Sold Ships

### ISSUE THREAD

**Issue by nmyron** [EDDiscovery/EDDiscovery#2319]
There is currently no functionality to enable the removal of ships marked (Sold) - I noticed upon loading up EDDiscovery for the first time today that some ships I've marked as "sold" in Inara previously are appearing in my "Ships/Loadout" panel as (Sold) still. It would be great to have an option to purge these from the list. I cannot see them in Inara, and no longer own the hull in question, however I have no way to remove it from my inventory in EDDiscovery.

Thanks!

**Comment by robbyxp1** [comment]
I can add a means to mask them in the ship loadout display.   They are already sorted to the bottom of the list I think.

They need to be accumulated during travel history load, so don't remove them there.

**Comment by robbyxp1** [comment]
Moved to projects
