### ISSUE TITLE
Feature Request: Manage add-ons window loading activity indicator

### ISSUE THREAD

**Issue by wherget** [EDDiscovery/EDDiscovery#2323]
In unfavorable network conditions, the Manage Add-Ons Window can take some time to display the list of available Add-Ons. This may confuse users (such as happened to me) into thinking there are none available, closing the window before the load operation has a chance to complete.

I would like to propose there to be some sort of indicator (a simple text of "Loading Add-On list..." centered on the listing area would probably suffice) that a background operation is taking progress when the window is initially opened.

What do you think?

**Comment by robbyxp1** [comment]
I've added a spinning disk.. good idea.
