### ISSUE TITLE
ED Discovery 10.3.4 Always lagging, freezing, crashing

### ISSUE THREAD

**Issue by Arcadia117** [EDDiscovery/EDDiscovery#2324]

**Comment by Arcadia117** [comment]
Sorry. Basicly when a switch tab its gonna freeze and i'll have to crash it. and I have 6 files in the log folder 
![capture](https://user-images.githubusercontent.com/46700074/51159250-41b2c600-1856-11e9-9dd1-36b8440ab757.PNG)

**Comment by robbyxp1** [comment]
No more interaction.
