### ISSUE TITLE
Distant Worlds 2 Scouting Reporter

### ISSUE THREAD

**Issue by SirTyler** [EDDiscovery/EDDiscovery#2328]
I've created an add-on to help with submitting reports for the DW2 expeditions. Is it possible to have it added as a add-on in the repository?
https://github.com/SirTyler/Scouting-Report

**Comment by klightspeed** [comment]
Please create a pull request to https://github.com/EDDiscovery/EDDiscoveryData, adding the act file in `ActionFiles/V1`

**Comment by SirTyler** [comment]
The pull request is up.

**Comment by robbyxp1** [comment]
I see it, hang on
