### ISSUE TITLE
'Unhandled UI exception'

### ISSUE THREAD

**Issue by Kriellya** [EDDiscovery/EDDiscovery#2331]
### Description
Using a popped out split panel, something goes wrong and then the entire panel can't be interacted with. The rest of EDD seems to work fine, including new split panels. Rebooting does not help, will error as soon as that panel is loaded.

### Exception Details:
>EDDiscovery v10.3.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlCompass.SetTransparency(Boolean on, Color curbackcol) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlCompass.cs:line 99
>   at EDDiscovery.UserControls.UserControlContainerSplitter.<>c__DisplayClass38_0.<SetTransparency>b__0(SplitterPanel p, Control c) in C:\Code\EDDiscovery\EDDiscovery\UserControls\GridsSplitters\UserControlContainerSplitter.cs:line 494
>   at ControlHelpersStaticFunc.RunActionOnSplitterTree(SplitContainer sc, Action`2 action) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\WinForms\ControlHelpers.cs:line 396
>   at ControlHelpersStaticFunc.RunActionOnSplitterTree(SplitContainer sc, Action`2 action) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\WinForms\ControlHelpers.cs:line 396
>   at EDDiscovery.UserControls.UserControlContainerSplitter.SetTransparency(Boolean on, Color curcol) in C:\Code\EDDiscovery\EDDiscovery\UserControls\GridsSplitters\UserControlContainerSplitter.cs:line 489
>   at EDDiscovery.Forms.UserControlForm.UpdateTransparency() in C:\Code\EDDiscovery\EDDiscovery\Forms\UserControlForm.cs:line 203
>   at EDDiscovery.Forms.UserControlForm.UserControlForm_Shown(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\Forms\UserControlForm.cs:line 267
>   at System.Windows.Forms.Form.OnShown(EventArgs e)
>   at EDDiscovery.Forms.DraggableFormPos.OnShown(EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\Forms\DraggableFormPos.cs:line 159
>   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>===== END =====
>```

**Comment by robbyxp1** [comment]
First, you can clear the UI settings - hold down shift during start up and select one of the clear UI options - such as tabs.

Secondly, you have a compass in a splitter... not done that. What else is in the splitter?

**Comment by kerntoni** [comment]
I got something similar:

### Description


### Additional Information


### Exception Details:
>EDDiscovery v10.3.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 209
>   at EDDiscovery.Actions.ActionController.ActionRun(ActionEvent ev, HistoryEntry he, ConditionVariables additionalvars, String flagstart, Boolean now) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:line 533
>   at EDDiscovery.EDDiscoveryForm.<>c__DisplayClass91_0.<Init>b__7() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 270
>   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>===== END =====
>```

**Comment by Kriellya** [comment]
Clearing the UI settings temporarily fixes it, but it comes back a few reboots (or hours) after I set the splitter back up.

I have a Compass, Route Tracker, Trip Computer, Estimated Values, and Scan in the splitter. (I don't like having overlays on top of E:D for a bunch of reasons :P )

**Comment by robbyxp1** [comment]
Will have to try and repo.

**Comment by klightspeed** [comment]
@kerntoni your issue is completely different to the OP - please create a new issue.

**Comment by klightspeed** [comment]
It looks like `SetTransparency` is being called before `EDDiscoveryForm.theme` has been set.

**Comment by klightspeed** [comment]
Correction: SetTransparency is being called before `Init(EDDiscoveryForm, int)` is called.  It looks like `UserControlForm` needs to call `SetTransparency` after `Init`, not during `Shown`.
