### ISSUE TITLE
Setting to ignore belt clusters with voice pack

### ISSUE THREAD

**Issue by BlepBlep** [EDDiscovery/EDDiscovery#2332]
Jumping to a system and having the voice spam about the 6 belt clusters immediately discovered can get very annoying, and takes like 3 minutes to get through it all, before actually catching up with what's happening. It'd be nice if there was a setting for the addon to ignore specifically belt clusters to reduce spam.

**Comment by BlepBlep** [comment]
tyvm <3

**Comment by robbyxp1** [comment]
10.0.1.0 does it
