### ISSUE TITLE
Ability to "sort" travel history in to subsets

### ISSUE THREAD

**Issue by Greek64** [EDDiscovery/EDDiscovery#2333]
Currently EDDiscovery works with your whole travel/journal history (kind of like EDSM).

I look for the ability to sort my jump history into subsets (lets call them trips), so that I do not see the entire jump history of me all the time (I find it irrelevant to know what I did in the bubble).

Let's say I did a 5k Ly trip to unlock Prof. Palin. I want to select the start and end of this trip from my history and save it as "Palin Trip" and have the ability to only display this trip in the 2D and 3D maps.

Even better would be the ability to do that on the fly, i.e. say all jumps from now on should be sorted in a specified subset.

**Comment by robbyxp1** [comment]
I'll add it to the project roadmap.  I would not hold your breath, thats a big lot of work.
