### ISSUE TITLE
EDSM Sync Button on Toolbar ignores configured Settings

### ISSUE THREAD

**Issue by Greek64** [EDDiscovery/EDDiscovery#2334]
If I press the `EDSM Sync` Button on the Toolbar it uploads data to EDSM, even if I specifically configured EDDiscovery to only fetch data from EDSM.

Even if the Tooltip Text suggests that it does a TO and FROM Synchronization, I still expect it to respect my configured settings.

**Comment by klightspeed** [comment]
EDDiscovery will not automatically send your logs to EDSM when sync to is not enabled.

The EDSM button currently only sends any unsynced events to EDSM.

It does not do anything for fetching logs from EDSM, as that is done in the background when sync from is enabled.  To force the sync from to start over, use Admin -> Synchronize with EDSM -> Fetch Logs Again.

So you're basically wanting the EDSM button to be a no-op when you have disabled sync to EDSM?

**Comment by Greek64** [comment]
The Tooltip text of the Button says `Synchronize with EDSM, To and From`.
If as you say the Button is only to force a sync *TO* EDSM, and a *FROM* synchronization can only happen automatically in the background, then my issue makes no sense and the Tooltip text should be updated to reflect the actual function of the button.

Also note that the functionality of the Button is also incorrectly stated in the [wiki](https://github.com/EDDiscovery/EDDiscovery/wiki)
>EDSM Sync: if you've configured EDSM sync in Settings then this causes EDDiscovery to check for EDSM information and up and download it

**Comment by robbyxp1** [comment]
Fixed
