### ISSUE TITLE
Ability to add Columns on 'Visited Stars' Panel

### ISSUE THREAD

**Issue by Greek64** [EDDiscovery/EDDiscovery#2337]
Currently, the `Visited Stars` Panel only has the Columns *Time, System, Visits, Information*, where as more columns exist in the `Exploration` Panel (*Dist, X, Y, Z, Scans, Pri Star, Note*).

Currently the only way (that I found) to see a Note that you made on a system in the `Visited Stars` Panel (through right click->Set Note), is to either try to take another Note on the same System and see the Note in the pop-up or adding the System in the `Exploration` Panel.

Having the ability to select which columns to display on the `Visited Stars` Panel (and any similar Panel) would be the best approach.
If not possible, at least add the *Note* column to the `Visited Stars` Panel.

**Comment by robbyxp1** [comment]
Moved to projects
