### ISSUE TITLE
UNKNOWN JOURNAL ENTRIES - 10.4 will address the few new ones added in 3.3.2

### ISSUE THREAD

**Issue by robbyxp1** [EDDiscovery/EDDiscovery#2338]
Out soon

**Comment by Slegnor** [comment]
I guess this thread covers this but I got this message twice just now, unfortunately I was AFK cruising at 30kms in supercruise so no idea what triggered it:

{
  "timestamp": "2019-01-17T20:34:19Z",
  "event": "ReservoirReplenished",
  "FuelMain": 22.537966,
  "FuelReservoir": 1.07
}

{
  "timestamp": "2019-01-17T21:01:00Z",
  "event": "ReservoirReplenished",
  "FuelMain": 21.467966,
  "FuelReservoir": 1.07
}

**Comment by robbyxp1** [comment]
Your tank depleting..

**Comment by Marenthyu** [comment]
Can confirm, also just got it.

{
  "timestamp": "2019-01-17T21:35:53Z",
  "event": "ReservoirReplenished",
  "FuelMain": 25.680861,
  "FuelReservoir": 0.63
}

**Comment by pioto** [comment]
In case you need an example of the `SquadronStartup` event:

```json
{
  "timestamp": "2019-01-18T00:16:13Z",
  "event": "SquadronStartup",
  "SquadronName": "FLEETCOMM",
  "CurrentRank": 4
}
```

**Comment by robbyxp1** [comment]
10.4.1 out!
