### ISSUE TITLE
unhandled UI exception

### ISSUE THREAD

**Issue by sutex** [EDDiscovery/EDDiscovery#2339]
### Description
Open up the Free voice control edit and editing 

### Exception Details:
>EDDiscovery v10.3.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 209
>   at ActionLanguage.ActionRun.Tick_Tick(Object sender, EventArgs e) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 235
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====

### Description
Open up the Free voice control edit and editing 

### Exception Details:
>EDDiscovery v10.3.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 209
>   at ActionLanguage.ActionRun.Tick_Tick(Object sender, EventArgs e) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 235
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

### Description
Open up the Free voice control edit and editing 

### Exception Details:
>EDDiscovery v10.3.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 209
>   at ActionLanguage.ActionRun.Tick_Tick(Object sender, EventArgs e) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 235
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

>```

### Description
Open up the Free voice control edit and editing 

### Exception Details:
>EDDiscovery v10.3.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 209
>   at ActionLanguage.ActionDialogBase.Cd_Trigger(String lname, String controlname, Object tag) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCoreCmds\ActionUserInteraction.cs:line 438
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```### Description
Open up the Free voice control edit and editing 

### Exception Details:
>EDDiscovery v10.3.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 209
>   at ActionLanguage.ActionRun.Tick_Tick(Object sender, EventArgs e) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 235
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
I think i've got it. A nice long standing bug. Thank you

**Comment by ered2000** [comment]
### Description


### Additional Information


### Exception Details:
>EDDiscovery v10.3.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
>   в ActionLanguage.ActionRun.DoExecute() в C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:строка 209
>   в EDDiscovery.Actions.ActionController.ActionRun(ActionEvent ev, HistoryEntry he, ConditionVariables additionalvars, String flagstart, Boolean now) в C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:строка 533
>   в EDDiscovery.EDDiscoveryForm.Controller_NewEntrySecond(HistoryEntry he, HistoryList hl) в C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:строка 702
>   в EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) в C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:строка 455
>   в EDDiscovery.EDDiscoveryController.PlayJournalList() в C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:строка 433
>   в EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) в C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:строка 184
>===== END =====
>```

**Comment by robbyxp1** [comment]
10.4 fixes
