### ISSUE TITLE
Not picking E:D activity

### ISSUE THREAD

**Issue by Majkl578** [EDDiscovery/EDDiscovery#2342]
For some unknown reason EDDiscovery stopped reading my E:D activity. Last picked entry is from a month ago.
Verified that E:D is correctly creating `Journal.*.log` files in `C:\Users\<name>\Saved Games\Frontier Developments\Elite Dangerous`.

Here is the latest trace log: https://gist.github.com/Majkl578/42db0edb5eb632887ebb61be657bb30a

Tried 10.3.1, 10.3.3 and 10.3.4 preview - neither works.

Let me know how to debug this one or what other info is needed.

**Comment by klightspeed** [comment]
You have your journal directory set to C:\Users\Majkl\Documents\edjournal

**Comment by Majkl578** [comment]
Heheh, so "Journal" should point to the E:D's saved games... This is not explained anywhere and I didn't set the wrong path myself.
