### ISSUE TITLE
Feature request - Mapped column in Estimated Vaules grid

### ISSUE THREAD

**Issue by Kingdud** [EDDiscovery/EDDiscovery#2345]
The Estimated Values 'pane' is very useful and compact. That said, given the 3.3 exploration changes, I'd really love if I could tweak two things about it:

1. Add a third column to the window which is a simple checkbox / x that will tells me if I have already mapped a given planet or not. If you'd like to re-use the green-globe asset from the Scans pane, that's fine too. Just some way for me to visually see, in that list, which systems I have mapped and which ones I haven't.
2. A way to sort the list in a 2-depth manner. IE: Primary sort by what is/isn't scanned yet, and secondary sort by system value (that way the 20 icy bodies stay at the bottom, and the higher value stuff comes to the top).

I don't know how hard either of those are, but I can say #1 is the one I want *far* more than #2. I'm hoping this is a simple change, but I don't know that for a fact.

**Comment by robbyxp1** [comment]
We will look. Moving to projects.
