### ISSUE TITLE
Unhandled UI in stats panel

### ISSUE THREAD

**Issue by Allitnil2** [EDDiscovery/EDDiscovery#2346]
### Description
Opened stats panel

### Additional Information
Works OK with my alt CMDR and beta CMDRs which have a lot fewer scans.

### Exception Details:
>EDDiscovery v10.4.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.OverflowException: Arithmetic operation resulted in an overflow.
>   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
>   at EliteDangerousCore.HistoryList.GetScanValue(DateTime start, DateTime to) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 359
>   at EDDiscovery.UserControls.UserControlStats.StatsTravel(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlStats.cs:line 447
>   at EDDiscovery.UserControls.UserControlStats.Stats(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlStats.cs:line 127
>   at EDDiscovery.UserControls.UserControlStats.InitialDisplay() in C:\Code\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlStats.cs:line 81
>   at EDDiscovery.Forms.UserControlForm.UserControlForm_Shown(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\Forms\UserControlForm.cs:line 283
>   at System.Windows.Forms.Form.OnShown(EventArgs e)
>   at EDDiscovery.Forms.DraggableFormPos.OnShown(EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\Forms\DraggableFormPos.cs:line 155
>   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>===== END =====
>```

**Comment by robbyxp1** [comment]
Okay, going to try a patch.. 10.4.1 soon

**Comment by robbyxp1** [comment]
should be fixed
