### ISSUE TITLE
System Scan estimated value not shown

### ISSUE THREAD

**Issue by Sentor77** [EDDiscovery/EDDiscovery#2347]
The estimated scan values are not shown in the scan panel since version 10.4.1.0

**Comment by iainross** [comment]
Assuming you mean the total system value then I see where it got lost so I'll put it back.

**Comment by Sentor77** [comment]
Hi, thx for the fast response. 
Yes, the total system value is missin on the scan panel ;)

**Comment by iainross** [comment]
I did the scan value change for 3.3 earlier this week which made me paranoid I'd broken it - nothing like that 'crap, what did I do' feeling to make me jump all over an issue :D

**Comment by robbyxp1** [comment]
Yep, it was a nice bit of re-plumbing!
