### ISSUE TITLE
Planet info is not working in voice

### ISSUE THREAD

**Issue by MartindForlon** [EDDiscovery/EDDiscovery#2349]
![vpc](https://user-images.githubusercontent.com/22664864/51412697-b9416780-1b6c-11e9-97ff-370b4e205f80.jpg)
Using latest ED Discovery (10.4.1.0) and voice with info for scanned planets not work (silence). In attached screenshot is setting which I use now. Except planets other information works (in voice). In previous versions planets info worked.

**Comment by robbyxp1** [comment]
Found and will be fixed in next version today
