### ISSUE TITLE
WARNING: EDMaterializer credentials are missing!

### ISSUE THREAD

**Issue by MasterElwood** [EDDiscovery/EDDiscovery#235]
Updated to new version 3.1.2.0 today - now i get a "WARNING: EDMaterializer credentials are missing!" 

What is this - and how can i fix it?

Thanx in A.

**Comment by finwen** [comment]
Its a warning for a future module. So you can ignore it.  

It is removed in next release

**Comment by gregmalcolm** [comment]
That should have gone away with the last release, right? I moved the error
to the prospecting save button in a previous  PR.
