### ISSUE TITLE
Addon Pack - possible to edit Journal Information from an event script?

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#2351]
Hi,
I've had a quick look through the ActionPack stuff, but I don't think what I want to do is possible.

The question I have is whether there's a way for an ActionPack Script to modify a value in the Journal.  

The concrete use-case I have (the idea comes from DrKaii's Cmdr Log tool) is that if I send a particularly-formatted string to local chat that the string is appended to the "Note" field of the current system.

**Comment by robbyxp1** [comment]
I'll have a look..

**Comment by robbyxp1** [comment]
Not at the moment, but its easy to add to update a note on an event.  Then we can write a simple pack which intercepts ReceiveText, looks for local and the text marker, and creates a note with the rest of the text on the current event... or last type of event.

good idea! Do it in the next few days

**Comment by robbyxp1** [comment]
Actually easy, will be in 10.4.2

Event THPOS
Event FROM %(EC_JID) NOTE "Hello"

Adds to current cursor position..

I'll write a simple pack to do this.

**Comment by robbyxp1** [comment]
I'll make the prefix configurable.

**Comment by mwerle** [comment]
Ok, cheers; I was most of the way there to writing a Pack, but after seeing "Note" wasn't in the variables (easy enough to add) my next sticking point was how to then update it. Wasn't sure if simply assigning to it would do the trick.

Btw, it should be in the "SendText" event, not "ReceiveText" ;)

**Comment by mwerle** [comment]
Oh I see, you needed to create a new command to do it rather than being able to assign values to the variable.

**Comment by robbyxp1** [comment]
Yeah, i realised that ;-)

Yep We needed a new command, it will be in the next version, coming right now. 
EVENT THPOS gets the current event under the cursor of the travel history, and writes EC_JID with the number
EVENT FROM %(EV_JID) NOTE writes the note

I would also put in the pack the ability to configure the prefix - if you look at something like the the InputBox at the bottom of voicepack you can see how to use it..

And you can link it to an Add-on menu item as per voicepack.

**Comment by mwerle** [comment]
Thanks for the awesomely quick feature!

**Issue**: it overwrites the current note, it doesn't append to it.  So I added a "Note" system value to access in the script and then concatenate the new note with the old one in the script, but that doesn't seem to work (Even after "EVENT THPOS" and using "EC_Note").

ActionVars.cs:88
                vars[prefix + "Note"] = s.SystemNote.ToNullSafeString();

**Comment by robbyxp1** [comment]
Added EC_Note - it was missing.. note on current HE entry.

I'm doing a release tomorrow so you'll have it then, or if you can build it, right now.

We can use discord to easier chat btw, see our forum entry for the invite.

**Comment by mwerle** [comment]
Ok, finally got it working.  Turns out wasn't really necessary to make an options dialog (Can just use the "Globals" section) and there was no "InputBox2 in the Voice Pack (at least not the versions I have), but finally got it working and left it in as example code.

Will do some testing and then make a pull request on EDDiscoveryData, or is there another preferred way to share?

**Comment by mwerle** [comment]
https://github.com/EDDiscovery/EDDiscoveryData/pull/8 - feedback welcome
