### ISSUE TITLE
Request: Ability to import/export preferences (Filters/Tabs/etc)

### ISSUE THREAD

**Issue by Slegnor** [EDDiscovery/EDDiscovery#2356]
I wanted to move my EDDiscovery from my PC to a laptop and realised that there was no way to preserve my current settings, unless I'm missing it?

Would be useful to be able to import/export preferences (Filters/Tabs/ etc) between machines, especially filters for chat etc

**Comment by klightspeed** [comment]
All settings, journal history, bookmarks, etc is in EDDUser.sqlite, which should be able to be copied between machines.  This is in the EDDiscovery data directory (`%LOCALAPPDATA%\EDDiscovery` if using the installed version, `Data` in the extracted directory for the portable version).

**Comment by Slegnor** [comment]
Ah excellent, thank you
