### ISSUE TITLE
UI exception

### ISSUE THREAD

**Issue by hornetgr** [EDDiscovery/EDDiscovery#2360]
### Exception Details:
>EDDiscovery v10.4.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Δεν έχει οριστεί αναφορά αντικειμένου σε μια παρουσία αντικειμένου.
>   σε EDDiscovery.UserControls.UserControlScan.BuildScanValue(SystemNode system) στο C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:γραμμή 194
>   σε EDDiscovery.UserControls.UserControlScan.DrawSystem() στο C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:γραμμή 181
>   σε EDDiscovery.UserControls.UserControlScan.NewEntry(HistoryEntry he, HistoryList hl) στο C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:γραμμή 135
>   σε System.Action`2.Invoke(T1 arg1, T2 arg2)
>   σε EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) στο C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:γραμμή 453
>   σε EDDiscovery.EDDiscoveryController.PlayJournalList() στο C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:γραμμή 432
>   σε EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) στο C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:γραμμή 184
>===== END =====
>```

**Comment by robbyxp1** [comment]
Update to 10.4.3 thanks
