### ISSUE TITLE
Action documentation errors

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#2363]
Sorry, would edit and create a pull request, but it's in docx and when I used LibreOffice it complained about breaking formatting.

Anyway, these are the ones I remember now:

S2.5.3:
EscapeChars / ReplaceEscapeChars - the actual functions don't have the 's'; ie, EscapeChar / ReplaceEscapeChar

S2.4.4.1
No entry for "Label" control

S2.4.4.2
The DialogControl example references %(Value) to retrieve dialog data, which is incorrect.  It should be %(DialogResult)

**Comment by klightspeed** [comment]
Perhaps we should look at converting it to e.g. asciidoc

**Comment by robbyxp1** [comment]
No I want to edit it in word.. but I normally do a google doc one which is linked to the wiki.  I'll export another one and do it from the wiki.

**Comment by robbyxp1** [comment]
You don't need anything for label because there are no control parameters. I've made that clearer.

thanks
