### ISSUE TITLE
First Discovered DSS Prices

### ISSUE THREAD

**Issue by jpotelle** [EDDiscovery/EDDiscovery#2366]
Please add a check box or button on modules that calculate body scan prices to indicate this is a First Discovered (FD) item, which is worth far more. Fore simplicity, assume the whole system has never been discovered. Calculate prices accordingly. Or add a 2nd price (per body? whole system?). Where price #1 is not FD and price #2 is FD.
Thanks for considering!

**Comment by robbyxp1** [comment]
Okay will consider.  No ETA yet on when this will come.

**Comment by robbyxp1** [comment]
Moved to projects.
