### ISSUE TITLE
Error: Unhandled UI Exception - NullReferenceException

### ISSUE THREAD

**Issue by AndrielChaoti** [EDDiscovery/EDDiscovery#2370]
### Description
I was doing a first-time run of the application and this error did it's error thing.

### Exception Details:
>EDDiscovery v10.4.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at System.Windows.Forms.ToolStripProgressBar.set_Value(Int32 value)
>   at EDDiscovery.UserControls.UserControlScanGrid.ResetDefaults() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScanGrid.cs:line 173
>   at EDDiscovery.UserControls.UserControlScanGrid.Display(HistoryEntry he, HistoryList hl, Boolean selectedEntry) in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScanGrid.cs:line 152
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl, Boolean selectedEntry)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 485
>   at EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl, Boolean disablesorting) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 245
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshComplete(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 843
>===== END =====
>```

**Comment by klightspeed** [comment]
https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/ToolStripProgressBar.cs,246

I don't know how this exception is even possible, when the progress bar is set in the constructor.

**Comment by AndrielChaoti** [comment]
I believe it's related to the progress bar that shows up in the "Scan Grid" panel's progress bar.

**Comment by klightspeed** [comment]
What were you doing when the error occurred?

What steps are necessary to reproduce it?

**Comment by AndrielChaoti** [comment]
I was configuring UI panels to try and get an "Exploration data" tab that I could use for... well, what the name of the tab says. It was a splitter tab with a scan widget, a scan grid widget, a estimated body value widget and a system info widget. I was also switching between tabs a lot and downloading the EDDB/EDSM system data for colonia/bubble at the time, IIRC.

**Comment by klightspeed** [comment]
This should be fixed by 49373a4
