### ISSUE TITLE
Writing Logs to other than Elite's Journal Directory

### ISSUE THREAD

**Issue by incryptx** [EDDiscovery/EDDiscovery#2377]
Is there a path set that I can change so EDDiscovery's files do not end up in Elite's Journal Directory?

I found one path in "Settings" for the location of the Elite Journals, and it seems once set, EDDiscovery feels free to dump it's own log files there. I would like to have a setting which I can set to a directory specifically for EDDiscovery log files. EDMarketConnector has it's own. Elite Journals has its own, cant' this program?

**Comment by klightspeed** [comment]
EDDiscovery by default stores its data in either `%LOCALAPPDATA%\EDDiscovery` (for the installed version) or the `Data` directory in the portable install directory.  It does _not_ write files to the journal directory.

**Comment by robbyxp1** [comment]
No response.
