### ISSUE TITLE
Parsing Joystick shows inaccurate settings.

### ISSUE THREAD

**Issue by incryptx** [EDDiscovery/EDDiscovery#2378]
List Joystick and Binding Information. What file are you parsing for this information?

I have a joystick binding created by VoiceAttack and placed in the "C:\Users\Username\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings" directory, called "HCS SaitekX55.3.0.binds" and the information shown in "List Joystick and Binding Information" does not match what the joystick is using in the game.

You should parse whatever file is located at "C:\Users\Username\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings" for accurate joystick bindings.

**Comment by incryptx** [comment]
Although I do list what I see, this app is awesome overall and gives good information on the game. I am impressed overall. I'm only trying to make this app better for all users.

As I stated, I do develop software for a living.

**Comment by klightspeed** [comment]
The bindings file is loaded at https://github.com/EDDiscovery/EDDiscovery/blob/master/EliteDangerous/EliteDangerous/BindingsFile.cs#L230

Probably should have an option to select which bindings file is in use, rather than just selecting the first bindings file.

**Comment by robbyxp1** [comment]
We select the one referenced for StartPreset.start - that is the one we read.

What is yours pointing to?  

The naming of the joystick by Windows is variable and may not match the name the joystick is called.

Are you telling me the binding read are wrong?

**Comment by robbyxp1** [comment]
Mine is set to "Custom" and it loads the latest binds file, the one called custom.* and has the latest date.

**Comment by robbyxp1** [comment]
No response.
