### ISSUE TITLE
Expedition : System not found On EDSM

### ISSUE THREAD

**Issue by Arcadia117** [EDDiscovery/EDDiscovery#2381]
Im trying to create a new expedition but when i select the starting system, it's telling me that it is unknown to EDSM... The system is Pallaeni.. same happened for Shapley 1, the view, Cycladia , etc..

**Comment by robbyxp1** [comment]
Have you downloaded the EDSM System database - is settings galaxy select (bottom right) set to off, or have you just downloaded a small subsection of the galaxy.  Because if you have, it won't know about them.

**Comment by robbyxp1** [comment]
Try the 3dmap as well - does it show stars?

**Comment by klightspeed** [comment]
Perhaps we should modify the schema to include extra data (coordinates, EDSM ID, SystemAddress) on route and system bookmark entries, and when directly entering the system and it isn't found locally then look it up via an EDSM API call?

**Comment by klightspeed** [comment]
#2386 should improve the situation (it uses the system cache, which includes any EDSM systems that have been fetched through it in the current session as well as any systems you have visited).

**Comment by Arcadia117** [comment]
Robbyxp1 The Enable Star data download case is checked. is that what you mean ?

**Comment by robbyxp1** [comment]
Going to move to projects : Expand route_systems to have x/y/z, and allow a lookup from EDSM on system name to find co-ords, or manual entry.
