### ISSUE TITLE
Settings tab does not reflect active settings properly

### ISSUE THREAD

**Issue by kinaflex** [EDDiscovery/EDDiscovery#2382]
After starting the application, settings that are checked appear as unchecked; meanwhile, EDD still seems to know what the settings actually are and uses them. The user can check those boxes again and they will remain checked until the next time the application starts. The specific settings are all settings related to saving screenshots and to EDSM/EDDB download control.

**Comment by robbyxp1** [comment]
See the other ticket - its the same issue of SQLUserDB somehow not being read.
