### ISSUE TITLE
[Enhancement] Add Unscanned bodies count to Scan Data Pannels

### ISSUE THREAD

**Issue by AndrielChaoti** [EDDiscovery/EDDiscovery#2387]
It is possible that when the player uses the Discovery Scanner in a system that EDDiscovery can then populate the scan screens with a counter displaying "unexplored" bodies in the system.

The journal events that records a discovery scan says how many bodies the system has, which should mean you can at least list a counter or a bar or something to show how many bodies are still unscanned in the system you are in.

An example event, perhaps BodyCount can be implemented into the scan panels in some way. I personally would just have it as a "Total: 3" in the scan data grid view.
```json
{
  "timestamp": "2019-01-23T14:46:30Z",
  "event": "FSSDiscoveryScan",
  "Progress": 1.0,
  "BodyCount": 3,
  "NonBodyCount": 0
}
```

**Comment by robbyxp1** [comment]
Thanks. Moved to projects
