### ISSUE TITLE
ChatConsole requested commands

### ISSUE THREAD

**Issue by spadino** [EDDiscovery/EDDiscovery#2388]
#  Command proposal for ChatConsole, an interactive in-game chat bridge

### Current in-game chat tokens, as per Elite: Dangerous 3.3.02

- /l - local space
- /sy - current system
- /w - wing
- /mc - multicrew
- /s - squadron
- /sl - squadron leaders
- /r, /reply - replies to recent direct messages
- /d [name], /direct, /to - send a message to [name]
- /t, /target - direct message to target
- /clear
- /help

### Suggested commands/tokens/behavior for custom interactive actions

Users will be able to define their preferred tokens, of course. Here are some proposals, which fit well with Frontier scheme. 
There could be "tokens themes", which users could exchange and include in main repo...

**NOTE**
This command deal with system note. Already implemented.
- /n, append a note at current system.
- /nr, replace current system note with a new one.
- /nc, clear current system note.

**TARGET**
Set/Unset target.
- /t ?[name], set target to [system], or current system if no argument's given
- /tc, clear target.

**BOOKMARK**
Set/Unset bookmarks
- /b ?[name], bookmark current system, or [system], if given.
- /bc ?[name], clear bookmark for current system, or [system], if given.

**FLAG**
Set/Unset start and end flags for the trip computer.
- /fs ?[name], set start flag to [system], or current system if no argument's given.
- /fe ?[name], set start flag to [system], or current system if no argument's given.
- /fu, unset flag at current system, if present.

**CAPTAINLOG**
- /cl ?[tag], create a new entry in the captain's log, at current system and date. If a tag is given, it create or link an existing tag to this entry.
- /clr, replace last entry in the captain's log.
- /clc, clear last entry of the captain's log.
- /cld, delete last entry of the captain's log
- /clq 
    - t:[tag], query the captain's log for entries with [tag], and print or say the result.
    - s:[name], query the captain's log for entries at [system]. and print or say the result.

**COMMAND**
An extensible collection of specialty commands, which could be helpful to be run from the in-game chat.
- /> [?], execute given command (user extensible).

The command token must be followed by a defined argument. Some ideas:
    - r:[ly], print or say a list of known systems in range.
    - rc:[ly] [?...], as above, but filtering for main star class/es.
    - rv:[ly], as above, but for visited.
    - ru:[ly], as above, but for unvisited.
    - a:[name], run named [scripts] at current history position.
    - s, stop all running scripts.
    - ...

**Comment by robbyxp1** [comment]
Okay, all good ideas.

COMMAND.. 
Run a script can already be done via PERFORM.. GENERATEEVENT
Star lists : Extend STAR command to STAR [PREFIX NAME] "Starname" LISTWITHIN 10 [CLASSES] 
etc

BOOKMARKS exist already
Agree CAPTIANSLOG ADD/REMOVE/UPDATE needs doing - will do when i push the CL update
Agree TARGET SET/UNSET 
Agree EVENT NOTE already done.

**Comment by robbyxp1** [comment]
Note this should have been a project entry - i'm going to keep issues for bugs rather than enhancement ideas.

**Comment by mwerle** [comment]
I'd suggest not to use "/" as the EDD command prefix, use something else such as ":" by default.

Otherwise if a future release of ED adds more commands they might clash.

**Comment by spadino** [comment]
@mwerle, I prefer to let the user choose it''s preferred prefix. There are many keyboard layout out there, so neither the "/" or ":" may be handy for some users... those tokens MUST be user definable, to me.

If, for some reason, they will clash in the future (something quite possible) we can deal with the need to change them globally recursively writing to the journal, to change each matching entry to the new prefix. A maintenance script could be prepared and included in the maintenance panel. But yes, I see your point. I thought in regard, too... I, as a personal point of view, prefer a closely matching syntax. We can offer two optional tokens theme maps, which the user choose from at install or after that: a "frontier map" and a "{put a cool name here} map". The script then source them at the point it needs to, and replace inner variables with proper tokens... just a thought.

**Comment by robbyxp1** [comment]
•	Event [PREFXIX name] FROM jid STARTMARKER: Set start marker, clear stop[13]
•	Event [PREFXIX name] FROM jid STOPMARKER : Set stop marker, clear start[13]
•	Event [PREFXIX name] FROM jid CLEARSTARTSTOPMARKER : Clear both flags [13]

New vars
•	Prefix + StartMarker – 1 if the start marker is present on this entry, 0 otherwise [13]
•	Prefix + StopMarker – 1 if the stop marker is present on this entry, 0 otherwise [13]

**Comment by robbyxp1** [comment]
Added GMO Command
Added TARGET command to set to bookmark/notemark/gmo

**Comment by robbyxp1** [comment]
Added COMMANDERS
Added STAR <name> NEAREST <parameters>
Reports on nearest stars to the name.

**Comment by robbyxp1** [comment]
Closing this one now - you now need to write it!
