### ISSUE TITLE
Feature Request:  Add a "scratchpad"

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#2396]
It would be great to have a scratchpad window (ie, popup panel) into which I can paste arbitrary text; doesn't even need to be saved. Bonus points for rendering some kind of markup (bold, font size, etc) but not necessary.

**Use case:**
These days I fly a lot in VR, it would be great to be able to pin some notes into my VR space (Oculus Dash, works great for EDD windows) which is in the same style as my other pinned windows.

Yes, I can pin <insert arbitrary other window> but they usually have borders, GUI, etc etc.

**Comment by mwerle** [comment]
Alternatively, implement the ActionLanguage TODO list item to create transparent/borderless "popup" windows 

(which is needed for another users' request anyway - someone wants a simple popup showing the current planet's G-force; not sure why they don't use the in-game display : https://forums.frontier.co.uk/showthread.php/474141-ED-Discovery-Scanned-planet-G-value-display-question)

**Comment by mwerle** [comment]
Ok, so for my purposes, I've managed to create something which works for me for now, since I don't actually need it to be "On Top".

However, there's an ActionLanguage bug: you cannot specify the TextBox height because the size is specified -before- multiline is set.

To fix, the size must be set afterwards.

A hack was to just reset the size if multiline is set but there's probably a neater refactor.  I'd make one and create a pull request, but I'm really not sure how all these git sub modules work. Do I have to check out a different repo to make changes?
 
Append the following to ConfigurableForm.cs:481 
```
                    if (tb.Multiline) {
                        tb.Size = ent.size;
                    }
```

**Comment by mwerle** [comment]
Ok, correction, it doesn't work :(

The NonModalDialog created by ActionLanguage can't be "pulled" into VR using Oculus Dash (I guess I should have tested that before all the malarking about; didn't expect it to be an issue though). 

How does it differ from the "popout panels"?

So modified Feature Request:  Allow ActionLanguage to create a "popout panel" style window please.

**Comment by robbyxp1** [comment]
That is very difficult, the popout panel User Control with transparency would be difficult to do using a modal action dialog from the script.

I popped out a non modal and can move it around the screen by dragging it (in both normal windows and borderless mode)... why does it not work for you?

**Comment by robbyxp1** [comment]
Okay, fixed the multiline thing on my new working copy - not master yet. Thanks

**Comment by spadino** [comment]
I like the idea of a scratchpad. I always thought that it's a needed feature for explorers - actually, I made a suggestion years ago for one... 
I came to the conclusion that I can use the next-to-be-released CmdDiary panel, showing an entry tagged as "scratch", which can be used as a scratchpad. Does it seems a good compromise to you?

**Comment by mwerle** [comment]
> I popped out a non modal and can move it around the screen by dragging it (in both normal windows and borderless mode)... why does it not work for you?

In Windows it works and looks great.  But in Oculus Dash it doesn't.  That's why I asked what the underlying difference is between the ActionLanguage NonModalDialog and the EDD-created popout panel windows.

Oculus Dash allows you to "pull" individual windows into VR space.  In the case of EDD popout panels, that works great.  In the case of the ActionLanguage NonModalDialog, it won't let me pull that individual window; it pulls the entire desktop if I try.

**Comment by spadino** [comment]
Good idea for the Codex entries. Not sure if is it viable, but definitely worth a deep look. Thanks! ;)

**Comment by mwerle** [comment]
I've created #2401 to avoid derailing this thread further.

**Comment by robbyxp1** [comment]
Closed - I can't debug this, I can't see any reason why a form, which the window is from action , does not act like a pop out window, which is also a form...
