### ISSUE TITLE
10.4.4.0 Application freeze right when opening..

### ISSUE THREAD

**Issue by Arcadia117** [EDDiscovery/EDDiscovery#2398]
When I try to open ED Discovery 10.4.4.0, it keeps freezing.. Can't select anything.. Help please :(

**Comment by klightspeed** [comment]
Please try removing `EDDSystem.sqlite` from you EDDiscovery data directory (`%LOCALAPPDATA%\EDDiscovery` or `Data` if portable), and let us know if that helps.  Note that if you close the program while it is rebuilding the system index, then the issue will likely return.

**Comment by Arcadia117** [comment]
Got it ! it worked !! still have issue with EDSM... typing Omega Sector VE-Q b5-15 in expedition tab and it say this system is not known

**Comment by klightspeed** [comment]
The expedition panel currently still requires a functional system DB.  We plan to add an option to directly query the EDSM API for a system not in the systems DB.

**Comment by Arcadia117** [comment]
What is a system DB ?

**Comment by iainross** [comment]
It's what's in the EDDSystem.sqlite file.

**Comment by Arcadia117** [comment]
ok so by removing EDDSystem.sqlite, then restarting the App, it will create a functional EDDSystem.sqlite (system DB). with that EDD should be able to find Omega Sector VE-Q b5-15 (Omega Mining Operation) correct ?

**Comment by robbyxp1** [comment]
yep
