### ISSUE TITLE
System info and Nearest stars not updating

### ISSUE THREAD

**Issue by bazza14** [EDDiscovery/EDDiscovery#2399]
As per the title the system info and nearest stars panels no longer update. I have to close and reopen EDD to get them to update.

**Comment by bazza14** [comment]
Thanks, that was it. I had unticked it to stop it jumping to the top
when I was trying read something in the history. It was quite some time
after that that I noticed the system info not updating so didn't
connect the two events.

**Comment by robbyxp1** [comment]
np
