### ISSUE TITLE
Feature Request : Codex

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#2401]
A new tab/mode to hunt down Codex entries in your current region of space.
(Not sure if region can be autodetected prior to first "Codex" event; might need manual selection.  Also might need to petition FDev to add a "Codex State" journal event on startup which would list all "reported" and "confirmed" Codex entries for the Cmdr thus avoiding spoilers (I've accidentally seen a more comprehensive list prepared by someone, I'm guessing it was datamined))

Basic premise is to show a list/table of all possible Codex entries (Biologicals and Geologicals) that can be found. This list should also be filterable (perhaps some Cmdrs are only interested in a subset).

For each entry, optionally list the known Systems / Planets that they can be found on and any traits.
(Optional because user might want a smaller popout panel)

Optional: Entries should be groupable/sortable by types and sub-types and/or names. Allow group/sub-group to be collapsed.

When the Cmdr scans an item (Codex event in the Journal), that item is tagged as "found".  Default filter would hide "found" items, but User can disable that filter and "show all".

Cmdr can also mark an item as "found" manually.

**Comment by spadino** [comment]
EDSM already have some work on that: https://www.edsm.net/en_GB/codex

**Comment by robbyxp1** [comment]
Moved to projects.
