### ISSUE TITLE
Incorrect jump range calculation in “System Information” panel

### ISSUE THREAD

**Issue by kaimi** [EDDiscovery/EDDiscovery#2402]
So both my Beluga and my ExplorEagle show up as way less range than they actually have; the difference seems to be pretty close to their fitted FSD boosters.

![image](https://user-images.githubusercontent.com/910302/51914148-7424fd00-23d8-11e9-9b02-927ee6bbf14d.png)

![image](https://user-images.githubusercontent.com/910302/51914189-8bfc8100-23d8-11e9-8a34-8a7016249af9.png)

**Comment by bdeferme** [comment]
Same issue here, very close to the FSD booster range.

**Comment by robbyxp1** [comment]
FSD Boosters are not in the calculation at the moment.

**Comment by robbyxp1** [comment]
In code base, thank you

**Comment by kaimi** [comment]
Thanks for the quick fix :)
