### ISSUE TITLE
Fire groups reported incorrectly with voice pack

### ISSUE THREAD

**Issue by DHK79** [EDDiscovery/EDDiscovery#2403]
The voice pack is adding 1 to every fire group (.i.e it never calls out fire group 1).

**Comment by robbyxp1** [comment]
I'll have a look on monday..

**Comment by DHK79** [comment]
Thanks Rob,

 

One possible suggestion is to also change them to ABC rather than 123, to match the change FD did to naming fire groups (not that I personally really care).

 

Doug

**Comment by robbyxp1** [comment]
I think they changed their number scheme when they did this..

**Comment by robbyxp1** [comment]
Fixed, update from server. Thanks for the report.
