### ISSUE TITLE
Unhandled journal events

### ISSUE THREAD

**Issue by jtcsrtx** [EDDiscovery/EDDiscovery#2407]

**Comment by klightspeed** [comment]
Please upgrade to the latest version: https://github.com/EDDiscovery/EDDiscovery/releases/latest

**Comment by klightspeed** [comment]
And yes, it is a known issue that 9.1.x cannot properly detect updates - this was fixed by a later update.

**Comment by jtcsrtx** [comment]
Update completed.  Thank you!!!
