### ISSUE TITLE
Exception when clicking Sync with EDSM -> Fetch Logs Again

### ISSUE THREAD

**Issue by irman** [EDDiscovery/EDDiscovery#2413]
### Description
Clicked Sync with EDSM -> Fetch Logs Again

### Exception Details:
>EDDiscovery v10.4.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.EDSM.EDSMLogFetcher.KeyName(String& latest, String& oldest) in C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMLogFetcher.cs:line 260
>   at EliteDangerousCore.EDSM.EDSMLogFetcher.ResetFetch() in C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMLogFetcher.cs:line 72
>   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
This suggests you have "Sync From EDSM" disabled for your current commander.
