### ISSUE TITLE
VoicePack v10 - sayCodexEntry - no voice and error in log

### ISSUE THREAD

**Issue by Slegnor** [EDDiscovery/EDDiscovery#2416]
Hope I haven't missed this reported elsewhere, did search but couldn't find anything

Having say_CodexEntry enabled results in no voice and the following in the log:

At Step 7 in VoicePackV10::GenericResponse:1762: Set
Error: Function phrase: Parameter 1: Function indirect: Indirect Variable 'say_CodexEntry' not found

**Comment by robbyxp1** [comment]
VP10 appears to work - can you check you have that one..

**Comment by Slegnor** [comment]
Yes I'm running pack 10, only version I have ever installed

**Comment by robbyxp1** [comment]
Update to version 10.0.2.0 as it looks like your running the original VP10 - as I said mine is working..

**Comment by Slegnor** [comment]
I have updated to10.0.2.0 and will see how it goes, thanks

Is it right that when it updates it resets everything?  I disabled all but
4 actions and all 210 are re-enabled again now its been updated?

**Comment by robbyxp1** [comment]
Yep, since the enable/disable is kept in the action file..

To help you, V11 will have the events grouped, and will have a nice Select Action Button which allows you to enable/disable whole groups
![capture](https://user-images.githubusercontent.com/6573992/52467683-47ae7500-2b7e-11e9-97e7-5a9976296988.PNG)

**Comment by Slegnor** [comment]
Update: Definitely running 10.4.4.0 and voicepack 10.0.2.0 and still getting this message:

At Step 7 in VoicePackV10::GenericResponse:1762: Set
Error: Function phrase: Parameter 1: Function indirect: Indirect Variable 'say_CodexEntry' not found

![image](https://user-images.githubusercontent.com/11891577/52522004-ba4f4b80-2c77-11e9-8e95-cc08b5836fa0.png)

![image](https://user-images.githubusercontent.com/11891577/52522016-d7841a00-2c77-11e9-842b-346bdbd4dbcd.png)

![image](https://user-images.githubusercontent.com/11891577/52522029-fa163300-2c77-11e9-9e50-14f9e8959221.png)

**Comment by Slegnor** [comment]
Just spotted the UISrvUnderShip error at the top there, should I report it separately?

**Comment by robbyxp1** [comment]
No keep it under one roof.

**Comment by Slegnor** [comment]
Ok, I'm wondering if there may be something inherently wrong my end,  as I turned on a few to check if anything works and most arent working

Error: Function phrase: Parameter 1: Function indirect: Indirect Variable 'say_UISrvTurret' not found
At Step 23 in VoicePackV10::GenericResponseUI:28: Set
Error: Function phrase: Parameter 1: Function indirect: Indirect Variable 'say_CollectCargo' not found
At Step 7 in VoicePackV10::GenericResponse:9: Set
Error: Function phrase: Parameter 1: Function indirect: Indirect Variable 'say_UILights' not found
At Step 23 in VoicePackV10::GenericResponseUI:28: Set

**Comment by Slegnor** [comment]
Ok  found part of the issue, noticed that in my Add-ons menu I was missing:
Stop currently running action file
Voice Synthesis Configuration
Voice Pack Configuration
Edit Speech File

No idea why it hadn't loaded/activated on startup, restart of EDDiscovery seems to have fixed that aspect.

Now the above aren't erroring anymore but some are still not speaking:
say_UISrvUnderShip, says nothing for example but when it was erroring, the error was appearing when under the boarding point

**Comment by robbyxp1** [comment]
Very strange..   I was playing it last night and under ship was working.

In your appdata folder (if you did a normal install) is local/eddiscovery/actions.  Here is where the scripts are stored. You could delete them all and reinstall.

**Comment by Slegnor** [comment]
A couple of days testing now and all seems good, I think everything was linked to the missing bits of the plugin on load
