### ISSUE TITLE
Info Request - Backup

### ISSUE THREAD

**Issue by lwt-pressy** [EDDiscovery/EDDiscovery#2420]
when i do a backup of ${env:LOCALAPPDATA}\EDDiscovery can i savely exclude the files EDDSystem.sqlite and edsmsystems.json from it. Will they be automaticly downloaded after I start it after an restore?

**Comment by klightspeed** [comment]
Yes, edsmsystems.json will be downloaded from https://www.edsm.net/dump/systemsWithCoordinates.json, and EDDSystem.sqlite will be built as that file is being downloaded.

**Comment by lwt-pressy** [comment]
thx for the feedback
