### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by CmdJackson** [EDDiscovery/EDDiscovery#2421]
### Description
Fresh Download to a new Computer.  Attempted to start EDDiscovery with Elite Dangerous.  Got the error message shortly after starting EDDiscovery.

### Exception Details:
>EDDiscovery v10.4.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
>NOT NULL constraint failed: Bookmarks.x
>   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
>   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
>   at SQLLiteExtensions.SQLExtCommand`1.ExecuteNonQuery() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:line 131
>   at SQLiteCommandExtensions.SQLNonQueryText(SQLExtConnection cn, DbCommand cmd) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLExtensions.cs:line 73
>   at EliteDangerousCore.DB.BookmarkClass.Add(SQLiteConnectionUser cn) in C:\Code\EDDiscovery\EliteDangerous\DB\BookmarkClass.cs:line 244
>   at EliteDangerousCore.DB.BookmarkClass.Add() in C:\Code\EDDiscovery\EliteDangerous\DB\BookmarkClass.cs:line 225
>   at EliteDangerousCore.DB.GlobalBookMarkList.AddOrUpdateBookmark(BookmarkClass bk, Boolean isstar, String name, Double x, Double y, Double z, DateTime tme, String notes, PlanetMarks planetMarks) in C:\Code\EDDiscovery\EliteDangerous\DB\BookmarkClass.cs:line 454
>   at EDDiscovery.Actions.ActionBookmarks.ExecuteAction(ActionProgramRun ap) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionsEDDCmds\ActionBookmarks.cs:line 188
>   at ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 217
>   at ActionLanguage.ActionRun.Tick_Tick(Object sender, EventArgs e) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 239
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
Do you have the Distant Worlds 2 plugin?  This suggests that the bookmark didn't have any coordinates.

**Comment by robbyxp1** [comment]
Just started from fresh db put dw pack on ..  no crash.

**Comment by CmdJackson** [comment]
Yes, I downloaded the Distant Worlds 2 pack shortly after downloading EDDiscovery.  (Now that I think about it, only started to crash.

After disabling the DW2 plugin, I haven’t experienced another crash.
