### ISSUE TITLE
Suggestion: Show number of surface locations on Scan panel

### ISSUE THREAD

**Issue by Slegnor** [EDDiscovery/EDDiscovery#2422]
Suggestion: Show number of surface locations on Scan panel

After a FSS of a body, you get the number of surface locations but they aren't shown anywhere else in the game, with a large system it is a pain to remember which you might want to map and land at.

Is it possible to display the  number of surface locations on the Scans page like you do with the volcanism/terraformable icons next to bodies?

**Comment by iainross** [comment]
Unfortunately that's not something the game tells us.  If it ever does we'll add it to the UI but for now it's not possible.
