### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by Andromedadragon** [EDDiscovery/EDDiscovery#2424]
### Description

Just entered a system FLOATL Go-G D11-9 and this message appeared. I closed out of EDDiscovery and opened it up again and the message returned

### Exception Details:
>EDDiscovery v10.4.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: Nullable object must have a value.
>   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>   at EDDiscovery.UserControls.UserControlScanGrid.DrawSystem(HistoryEntry he, Boolean force) in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScanGrid.cs:line 197
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl, Boolean selectedEntry)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 493
>   at EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl, Boolean disablesorting) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 249
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshComplete(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 845
>===== END =====
>```
[Journal.190215121622.01.log](https://github.com/EDDiscovery/EDDiscovery/files/2870574/Journal.190215121622.01.log)

**Comment by klightspeed** [comment]
The orbital parameters of `Floalt GO-G d11-9 2 a` on EDSM are null.
