### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by Mancoon-Crest** [EDDiscovery/EDDiscovery#2426]

**Comment by Mancoon-Crest** [comment]
### Description


### Additional Information


### Exception Details:
>EDDiscovery v10.4.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: Das Objekt mit Nullwert muss einen Wert haben.
>   bei System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>   bei EDDiscovery.UserControls.UserControlScanGrid.DrawSystem(HistoryEntry he, Boolean force) in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScanGrid.cs:Zeile 197.
>   bei EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:Zeile 493.
>   bei EDDiscovery.UserControls.UserControlTravelGrid.AddNewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:Zeile 389.
>   bei System.Action`2.Invoke(T1 arg1, T2 arg2)
>   bei EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:Zeile 454.
>   bei EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:Zeile 433.
>   bei EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:Zeile 184.
>===== END =====
>```

**Comment by silvermistshadow** [comment]
Another here.

### Description
No idea. Just using it.

### Additional Information
No idea what even happened. It doesn't seem to have affected anything. Or is that effect? I forget.

### Exception Details:
>EDDiscovery v10.4.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: Nullable object must have a value.
>   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>   at EDDiscovery.UserControls.UserControlScanGrid.DrawSystem(HistoryEntry he, Boolean force) in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScanGrid.cs:line 197
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl, Boolean selectedEntry)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 493
>   at EDDiscovery.UserControls.UserControlTravelGrid.AddNewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 389
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 454
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 433
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
>===== END =====
>```

**Comment by marcin212** [comment]
### Description


### Additional Information


### Exception Details:
>EDDiscovery v10.4.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: Obiekt dopuszczający wartość pustą musi mieć wartość.
>   w System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>   w EDDiscovery.UserControls.UserControlScanGrid.DrawSystem(HistoryEntry he, Boolean force) w C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScanGrid.cs:wiersz 197
>   w EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl, Boolean selectedEntry)
>   w EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() w C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:wiersz 493
>   w EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl, Boolean disablesorting) w C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:wiersz 249
>   w System.Action`1.Invoke(T obj)
>   w EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshComplete(HistoryList hist) w C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:wiersz 845
>===== END =====
>```

**Comment by klightspeed** [comment]
These are all duplicates of #2424

**Comment by robbyxp1** [comment]
Will be fixed in next version.
