### ISSUE TITLE
Make the 50k limit configurable

### ISSUE THREAD

**Issue by Buzzwhig** [EDDiscovery/EDDiscovery#2427]
This isn't an issue, but I didn't know how else to contact the folks working on this project. Is there a way to go into a file to adjust the 50k value set for the <$> icon in the scan tab?

EDDiscovery is a life saver, thanks for all the hard work!

thanks!

**Comment by klightspeed** [comment]
The 50k value is currently hard-coded in https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/UserControls/Helpers/ScanDisplay.cs#L327

**Comment by robbyxp1** [comment]
I'll look to see if there is a UI way of doing this..

**Comment by Buzzwhig** [comment]
Ok, good to know, thanks for the replies.

**Comment by robbyxp1** [comment]
On tip now, will be in 10.5
