### ISSUE TITLE
Uninstall Doesn't Remove Local AppData Files

### ISSUE THREAD

**Issue by Stevoni** [EDDiscovery/EDDiscovery#2428]
When uninstalling, there's not a prompt to remove all the local cache files so the application continues to take up an extra 4 GB in the AppData\Local folder.

Please consider adding the option to the (un)installer.

**Comment by klightspeed** [comment]
I think there is precedence to tell the user that the uninstaller does not remove user data or settings, and to provide information on how to do that.

https://support.mozilla.org/en-US/kb/uninstall-firefox-from-your-computer#w_remove-user-data-and-settings_2

I can't think of any MSI-based installers that offer removing user data or settings as an option.

## Remove user data and settings
The uninstaller does not remove any user data such as history or downloaded star data. If you wish to completely remove this data, you must manually delete the EDDiscovery folder containing your user profile:

* Click the Start button or press the Windows key  Windows Key to open the Start Menu.
* Type %LOCALAPPDATA% (when you start typing, a Windows search will start) and press enter to open the hidden Local folder.
* Delete the EDDiscovery folder.

**Comment by robbyxp1** [comment]
And there is no option available in the installer we use to do this.  I'm afraid we can't support this idea at this point. thanks
