### ISSUE TITLE
Add a hint about slow syncing with edsm when running from HDD

### ISSUE THREAD

**Issue by daniel-finger** [EDDiscovery/EDDiscovery#2429]
I was running EDD from a HDD and syncing was awfull slow due to slow sqlite.
After copying it to my SSD and running from there syncing was only a matter of a minute instead of half an hour syncing all Data after being offline about 4 Days.

In my opinion this would only affect those people using the portable Version running of a HDD. I assume no one uses a HDD as system disk anymore. 

Maybe this is worth mentioning on the troubleshooting page.

**Comment by robbyxp1** [comment]
Ta. Done this.
