### ISSUE TITLE
Idea: Biological Life Indicator for Scanned Planets

### ISSUE THREAD

**Issue by macrossmerrell** [EDDiscovery/EDDiscovery#2433]
If the GUI could denote Biological Life along with Geological Sites on scanned planets, it would make it so explorers do not need to write down which planets it biological locations.

I don't know if the game exposes that information like it does geological / volcanism, but I thought it would be worth sharing the idea.

Thanks!

**Comment by klightspeed** [comment]
The presence of surface POIs is not exposed in the journal.
