### ISSUE TITLE
Voice Control issue

### ISSUE THREAD

**Issue by mysakm** [EDDiscovery/EDDiscovery#2435]
After turning on Voice control the app is constantly frozen. No error, no sign except the fact Voice assistant doesn't tell me I did something, but the app is just frozen... :/

**Comment by robbyxp1** [comment]
To remove the feature, hold down shift, run the app, use the delete action files option.

I've no idea why it does not work on your PC.  Check your sound settings.

**Comment by mysakm** [comment]
Ok, thanks. Going to do it.
