### ISSUE TITLE
Feature request: configurable alerts on stellar body properties

### ISSUE THREAD

**Issue by petercoxphoto** [EDDiscovery/EDDiscovery#2438]
Would be great to be able to configure voice alerts based on planetary attributes, such as surface gravity, radius, etc. 

While exploring, I'm always on the lookout for exceptionally small worlds, high-g landables, etc. It's not terribly efficient to check those attributes on each body scanned in the FSS, especially with the current bug where you have to zoom out and back in again to get the properties pane to display.

Also, I'm not sure if this information is sent to the client before being displayed to the user, but alerting on geological and biological signals before the several second delay that is currently present is finished would be hugely useful as well.

**Comment by robbyxp1** [comment]
I've moved this idea to projects - There is no report of geological/biological signals from ED at the moment.

The voice pack has many different configs already. Each one costs time and effort to test.  I'm not sure this is practical but i'll keep it in the project list.
