### ISSUE TITLE
Hangs (V1.3 and V1.4) during import from EDSM

### ISSUE THREAD

**Issue by Clampitts** [EDDiscovery/EDDiscovery#244]
Worked great - now having a couple of issues

I have it installed on 2 Mac.  On my main game machine I have it set to read my log files and also have the API key set.  The App hangs when parsing the EDSM files / Log files (it appears)
<img width="1075" alt="screen shot 2016-05-27 at 07 19 48" src="https://cloud.githubusercontent.com/assets/19603917/15600092/bbe918e8-23df-11e6-9f40-1f80e80bcaa7.png">
<img width="1115" alt="screen shot 2016-05-27 at 07 15 28" src="https://cloud.githubusercontent.com/assets/19603917/15600093/bbe93c4c-23df-11e6-8795-396ff4d518eb.png">

The second installation does not have log file pasring set up as it's not on my Gaming iMac, just the API key.  But this does not read EDSM entries before 26/1/16 - even though I have EDSM Flight logs back to Aug 2015.  Of note, the files from 26/1/16 (that it is reading) wereuploaded to EDSM before ED 2.1.  The files from Aug to Jan were uploaded to ED after / during ED 2.1 rollout.  The screen grab below is from non-gaming Mac (without API), parses ok, doesn't have log file installation, but doesn't read all of EDSM flight logs
<img width="1077" alt="screen shot 2016-05-27 at 07 55 08" src="https://cloud.githubusercontent.com/assets/19603917/15600255/c4165728-23e0-11e6-8339-8d595f31f2ad.png">

**Comment by klightspeed** [comment]
Please re-submit this against the https://github.com/EDDiscovery/EDDiscovery-Mac repository.  This repository is for the DotNet version of EDDiscovery.

**Comment by Clampitts** [comment]
Done....
