### ISSUE TITLE
Elite dangerouse voice pack EDDiscovery crash 

### ISSUE THREAD

**Issue by Kunndo** [EDDiscovery/EDDiscovery#2446]
EDDiscovery voice pack crasz the app olways at landing ship on eny dock 

### Exception Details:
>EDDiscovery v10.5.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Wartość 'count' musi być nieujemna.
>Nazwa parametru: count
>   w System.String.CtorCharCount(Char c, Int32 count)
>   w BaseUtils.FunctionsBasic.Hnum(String& output) w C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\FunctionsBasic.cs:wiersz 690
>   w BaseUtils.Functions.ExpandStringFull(String line, String& result, Int32 recdepth) w C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\Functions.cs:wiersz 242
>   w BaseUtils.FunctionsBasic.Indirect(String& output) w C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\FunctionsBasic.cs:wiersz 228
>   w BaseUtils.Functions.ExpandStringFull(String line, String& result, Int32 recdepth) w C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\Functions.cs:wiersz 242
>   w BaseUtils.FunctionHandlers.ProcessParameter(String t, Boolean isstr, Int32 recdepth) w C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\FunctionHandlers.cs:wiersz 97
>   w BaseUtils.Functions.ExpandStringFull(String line, String& result, Int32 recdepth) w C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\Functions.cs:wiersz 219
>   w ActionLanguage.ActionSetLetBase.ExecuteAction(ActionProgramRun ap, Boolean setit, Boolean globalit, Boolean persistentit, Boolean staticit) w C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCoreCmds\ActionSet.cs:wiersz 98
>   w ActionLanguage.ActionSet.ExecuteAction(ActionProgramRun ap) w C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCoreCmds\ActionSet.cs:wiersz 155
>   w ActionLanguage.ActionRun.DoExecute() w C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:wiersz 217
>   w EDDiscovery.Actions.ActionController.ActionRun(ActionEvent ev, HistoryEntry he, Variables additionalvars, String flagstart, Boolean now) w C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:wiersz 536
>   w EDDiscovery.EDDiscoveryForm.Controller_NewEntrySecond(HistoryEntry he, HistoryList hl) w C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:wiersz 665
>   w EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) w C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:wiersz 455
>   w EDDiscovery.EDDiscoveryController.PlayJournalList() w C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:wiersz 434
>   w EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) w C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:wiersz 184
>===== END =====
>```

**Comment by klightspeed** [comment]
Makes me wonder if the value was NaN

**Comment by robbyxp1** [comment]
Can you tell me what was being said when it crashed.  Just docking should not have crashed it since the function it crashed in does not get called during Docked event.  What was the last event that was received?  You should be able to tell after you reload EDD and see the history.  Was it something to do with buying/sellling etc.
