### ISSUE TITLE
>EDDiscovery v10.5.0.0 There was an unhandled UI exception.

### ISSUE THREAD

**Issue by shinjiyamazaki** [EDDiscovery/EDDiscovery#2448]
### Exception Details:
>EDDiscovery v10.5.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.OverflowException: Die arithmetische Operation hat einen Überlauf verursacht.
>   bei System.Linq.Enumerable.Sum(IEnumerable`1 source)
>   bei EliteDangerousCore.HistoryList.GetScanValue(DateTime start, DateTime to) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:Zeile 357.
>   bei EDDiscovery.UserControls.UserControlStats.StatsTravel(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlStats.cs:Zeile 447.
>   bei EDDiscovery.UserControls.UserControlStats.Stats(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlStats.cs:Zeile 127.
>   bei EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl, Boolean selectedEntry)
>   bei EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:Zeile 546.
>   bei EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl, Boolean disablesorting) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:Zeile 287.
>   bei System.Action`1.Invoke(T obj)
>   bei EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshComplete(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:Zeile 854.
>===== END =====
>```

**Comment by klightspeed** [comment]
Let me guess - integer overflow (more than 2 billion)?
