### ISSUE TITLE
No Longer Autoupdating?

### ISSUE THREAD

**Issue by Red13x3** [EDDiscovery/EDDiscovery#245]
<img width="517" alt="capture" src="https://cloud.githubusercontent.com/assets/13119623/15625378/bc10db0e-24e7-11e6-8a4e-59f3591a423f.PNG">
Back a few major version ago, when I started EDD and there was a new version available, it would inform me of that and from memory it would just update it without me getting a chance to say no thanks. Obviously that wasn't ideal.

But now, since version 2.7 or there abouts... It never seems to do the update check and I have to manually cut and paste the info from the status panel to download the latest version.

Did that functionality get nerfed on purpose or is it just my machine?

Oh, and when I try to install the latest version 3.2.4, Windows 10 is getting in the way... See the screenshot. But it didn't for 3.1.2...

**Comment by klightspeed** [comment]
The SmartScreen prompt is essentially equivalent to the old Windows XP / Windows 7 "Do you want to run this file from an unknown source".  This means that the executable doesn't have a good reputation (yet) with the Microsoft SmartScreen database - likely due to it only being 12 hours old.

**Comment by Red13x3** [comment]
Yes, I used the ClickOnce installer, I guess, way back when.
So the standalone installer will never auto-update?

**Comment by finwen** [comment]
WIll make a new click once installer.  But had some 64 bit problems that i
need some time to solve and test.


2016-05-30 10:34 GMT+02:00 Mark <notifications@github.com>:

**Comment by robbyxp1** [comment]
Closed. no futher input
