### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by MartindForlon** [EDDiscovery/EDDiscovery#2452]
Hi, just to let you know, this happens with latest "pre-relase version" shortly after was EDDiscovery started:

### Description
Did exactly almost nothing, just started EDDiscovery and started the game, looked at system map and then noticed crash message.

### Additional Information
Screenshot with active tabs: https://www.swat-portal.com/CFDB/ED/EDiscovery_bug01.jpg

### Exception Details:
>EDDiscovery v10.5.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Parametr count musí být nezáporný.
>Název parametru: count
>   v System.String.CtorCharCount(Char c, Int32 count)
>   v BaseUtils.FunctionsBasic.Hnum(String& output) v C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\FunctionsBasic.cs:řádek 702
>   v BaseUtils.Functions.ExpandStringFull(String line, String& result, Int32 recdepth) v C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\Functions.cs:řádek 242
>   v BaseUtils.FunctionsBasic.Indirect(String& output) v C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\FunctionsBasic.cs:řádek 228
>   v BaseUtils.Functions.ExpandStringFull(String line, String& result, Int32 recdepth) v C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\Functions.cs:řádek 242
>   v BaseUtils.FunctionHandlers.ProcessParameter(String t, Boolean isstr, Int32 recdepth) v C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\FunctionHandlers.cs:řádek 97
>   v BaseUtils.Functions.ExpandStringFull(String line, String& result, Int32 recdepth) v C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\Functions.cs:řádek 219
>   v ActionLanguage.ActionSetLetBase.ExecuteAction(ActionProgramRun ap, Boolean setit, Boolean globalit, Boolean persistentit, Boolean staticit) v C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCoreCmds\ActionSet.cs:řádek 98
>   v ActionLanguage.ActionSet.ExecuteAction(ActionProgramRun ap) v C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCoreCmds\ActionSet.cs:řádek 155
>   v ActionLanguage.ActionRun.DoExecute() v C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:řádek 217
>   v EDDiscovery.Actions.ActionController.ActionRun(ActionEvent ev, HistoryEntry he, Variables additionalvars, String flagstart, Boolean now) v C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:řádek 552
>   v EDDiscovery.EDDiscoveryForm.Controller_NewEntrySecond(HistoryEntry he, HistoryList hl) v C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:řádek 665
>   v EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) v C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:řádek 447
>   v EDDiscovery.EDDiscoveryController.PlayJournalList() v C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:řádek 434
>   v EliteDangerousCore.EDJournalClass.ScanTickDone(Tuple`2 entries) v C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:řádek 186
>===== END =====
>```

**Comment by MartindForlon** [comment]
As result when I decide to continue is not working Voice pack (last version activated)

**Comment by robbyxp1** [comment]
Got it, fix coming up thanks

**Comment by robbyxp1** [comment]
Try 10.5.2
