### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by BannorPhil** [EDDiscovery/EDDiscovery#2453]
### Exception Details:
>EDDiscovery v10.5.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: 'count' must be non-negative.
>Parameter name: count
>   at System.String.CtorCharCount(Char c, Int32 count)
>   at BaseUtils.FunctionsBasic.Hnum(String& output) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\FunctionsBasic.cs:line 702
>   at BaseUtils.Functions.ExpandStringFull(String line, String& result, Int32 recdepth) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\Functions.cs:line 242
>   at BaseUtils.FunctionHandlers.ExpandMacroStr(String& output, Int32 parano) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\FunctionHandlers.cs:line 254
>   at BaseUtils.FunctionsBasic.Ifnotempty(String& output) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\FunctionsBasic.cs:line 519
>   at BaseUtils.Functions.ExpandStringFull(String line, String& result, Int32 recdepth) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\Functions.cs:line 242
>   at BaseUtils.FunctionsBasic.Indirect(String& output) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\FunctionsBasic.cs:line 228
>   at BaseUtils.Functions.ExpandStringFull(String line, String& result, Int32 recdepth) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\Functions.cs:line 242
>   at BaseUtils.FunctionHandlers.ProcessParameter(String t, Boolean isstr, Int32 recdepth) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\FunctionHandlers.cs:line 97
>   at BaseUtils.Functions.ExpandStringFull(String line, String& result, Int32 recdepth) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\Functions.cs:line 219
>   at ActionLanguage.ActionSetLetBase.ExecuteAction(ActionProgramRun ap, Boolean setit, Boolean globalit, Boolean persistentit, Boolean staticit) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCoreCmds\ActionSet.cs:line 98
>   at ActionLanguage.ActionSet.ExecuteAction(ActionProgramRun ap) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCoreCmds\ActionSet.cs:line 155
>   at ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 217
>   at EDDiscovery.Actions.ActionController.ActionRun(ActionEvent ev, HistoryEntry he, Variables additionalvars, String flagstart, Boolean now) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:line 552
>   at EDDiscovery.EDDiscoveryForm.Controller_NewEntrySecond(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 665
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 447
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 434
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(Tuple`2 entries) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 186
>===== END =====
>```

**Comment by LesserHellspawn** [comment]
Same Problem in the release version:

### Description


### Additional Information


### Exception Details:
>EDDiscovery v10.5.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: "count" muss nicht-negativ sein.
>Parametername: count
>   bei System.String.CtorCharCount(Char c, Int32 count)
>   bei BaseUtils.FunctionsBasic.Hnum(String& output) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\FunctionsBasic.cs:Zeile 702.
>   bei BaseUtils.Functions.ExpandStringFull(String line, String& result, Int32 recdepth) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\Functions.cs:Zeile 242.
>   bei BaseUtils.FunctionsBasic.Indirect(String& output) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\FunctionsBasic.cs:Zeile 228.
>   bei BaseUtils.Functions.ExpandStringFull(String line, String& result, Int32 recdepth) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\Functions.cs:Zeile 242.
>   bei BaseUtils.FunctionHandlers.ProcessParameter(String t, Boolean isstr, Int32 recdepth) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\FunctionHandlers.cs:Zeile 97.
>   bei BaseUtils.Functions.ExpandStringFull(String line, String& result, Int32 recdepth) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\Functions\Functions.cs:Zeile 219.
>   bei ActionLanguage.ActionSetLetBase.ExecuteAction(ActionProgramRun ap, Boolean setit, Boolean globalit, Boolean persistentit, Boolean staticit) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCoreCmds\ActionSet.cs:Zeile 98.
>   bei ActionLanguage.ActionSet.ExecuteAction(ActionProgramRun ap) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCoreCmds\ActionSet.cs:Zeile 155.
>   bei ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:Zeile 217.
>   bei EDDiscovery.Actions.ActionController.ActionRun(ActionEvent ev, HistoryEntry he, Variables additionalvars, String flagstart, Boolean now) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:Zeile 552.
>   bei EDDiscovery.EDDiscoveryForm.Controller_NewEntrySecond(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:Zeile 665.
>   bei EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:Zeile 447.
>   bei EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:Zeile 434.
>   bei EliteDangerousCore.EDJournalClass.ScanTickDone(Tuple`2 entries) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:Zeile 186.
>===== END =====
>```

**Comment by robbyxp1** [comment]
Got it, fix coming up thanks

**Comment by robbyxp1** [comment]
try 10.5.2 ;-)
