### ISSUE TITLE
Jump range

### ISSUE THREAD

**Issue by CmdrDeluvian** [EDDiscovery/EDDiscovery#2454]
Jump range is stuck on one value and does not update.. I hoped it'd be representation of the current ship jump range based on loaded fuel etc. Am I doing something wrong? The value does not change and is not what the current ship jump range is reported in the Ship menu

**Comment by robbyxp1** [comment]
I'll check, thanks

**Comment by robbyxp1** [comment]
At the moment its calculating on maximum fuel, not current fuel. I'll see if what happens if it does.

**Comment by CmdrDeluvian** [comment]
Oh,, I did not think it needed to be calculated. What was on my mind, numeric value of the current jump range refreshed after every jump based on the fuel consumed.. It could be just read from the journal but as you made the fuel so nicely dynamically updating, probably the jump range makes sense to be done in that very same fashion.. Good luck, looking forward to it :)

**Comment by robbyxp1** [comment]
So, it should actually be the current jump range.  previously we did not have enough data to calculate it real time.. now we do.  You'll notice the fuel level does decrease all the time on that panel.  its a miss not to use that to also calc jump range.  i'll fix

**Comment by CmdrDeluvian** [comment]
Thanks a lot

**Comment by robbyxp1** [comment]
Fixed in 10.5.3 out today.
