### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by brallinoth** [EDDiscovery/EDDiscovery#2456]
When I attempt to install I get the following message for EDDiscovery.10.5.2 exe "Windows cannot access the specified device, path, or file.  You may not have the appropriate permissions to access the item. I get the same message when I attempt to run it in Administrator mode. Never have I had this issue when upgrading this.

**Comment by klightspeed** [comment]
I'm guessing this is when you try to launch the installer?

It's possible that your antivirus is blocking it due to it being fairly new (Smartscreen also blocks it because it isn't in Microsoft's whitelist).

**Comment by brallinoth** [comment]
![Capture](https://user-images.githubusercontent.com/48651261/54572787-8e825c80-49bf-11e9-8721-76305e1489ba.PNG)
Nope

**Comment by klightspeed** [comment]
What version of Windows are you running, and what architecture are you running on?

If I recall correctly, Starter versions of Windows will only run Windows Store apps.

The EDDiscovery installer is for the x86 / x64 architecture, and won't run on the ARM architecture.

**Comment by brallinoth** [comment]
![System](https://user-images.githubusercontent.com/48651261/54574095-5e3dbc80-49c5-11e9-9197-19f90c720eeb.PNG)

**Comment by klightspeed** [comment]
Perhaps try downloading the installer again?  I'm wondering if the installer was corrupted during download (I checked it myself and the installer works correctly after going through the smartscreen dance).

**Comment by brallinoth** [comment]
I shall try again

**Comment by brallinoth** [comment]
That worked, thanks
