### ISSUE TITLE
 Cannot add scan to system

### ISSUE THREAD

**Issue by Andromedadragon** [EDDiscovery/EDDiscovery#2457]
I'm getting the message, cannot add scan to system with the current system name and object that was just scanned by FSS. I included the log file that Elite created
[Journal.190320175311.01.log](https://github.com/EDDiscovery/EDDiscovery/files/2990298/Journal.190320175311.01.log)

**Comment by robbyxp1** [comment]
Thanks - will try that and see if i can reproduce

**Comment by klightspeed** [comment]
What version of EDDiscovery are you using?  Does the trace log (in `%LOCALAPPDATA%\EDDiscovery\Log` or `Data\Log` for the portable version) indicate which body it is unable to process, or is it occurring with all bodies?  Does the trace log indicate any errors processing the `FSDJump`?

**Comment by Andromedadragon** [comment]
I'm using 10.5.2.0

It was all bodies in the one system.

I included the log files that were in the EDDiscovery file. Please note that I did try to recreate the database thinking that it might have corrupted since I hadn't used in a few days  or the system didn't shutdown correctly. I dropped in the respective log files from around that time period. I wish that I included the time and date in my original, so that I could include only the specific ones.
[Trace_2019-03-20-17-58-25.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3011077/Trace_2019-03-20-17-58-25.0.log)
[Trace_2019-03-20-17-59-27.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3011078/Trace_2019-03-20-17-59-27.0.log)
[Trace_2019-03-20-18-01-07.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3011079/Trace_2019-03-20-18-01-07.0.log)
[Trace_2019-03-20-18-05-42.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3011080/Trace_2019-03-20-18-05-42.0.log)
[Trace_2019-03-20-18-16-37.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3011081/Trace_2019-03-20-18-16-37.0.log)
[Trace_2019-03-20-17-54-19.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3011082/Trace_2019-03-20-17-54-19.0.log)

**Comment by Andromedadragon** [comment]
I had it occur again. I've added the files below.
[Journal.190411124338.01.log](https://github.com/EDDiscovery/EDDiscovery/files/3069735/Journal.190411124338.01.log)
[Trace_2019-04-11-12-41-32.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3069738/Trace_2019-04-11-12-41-32.0.log)

**Comment by Andromedadragon** [comment]
It worked okay for a system or two, but now throwing the messages about not being able to add scanned data from the system. Logs are below.
[Journal.190411124338.01.log](https://github.com/EDDiscovery/EDDiscovery/files/3069855/Journal.190411124338.01.log)
[Trace_2019-04-11-12-41-32.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3069857/Trace_2019-04-11-12-41-32.0.log)

**Comment by Andromedadragon** [comment]
Here's another system where it doesn't want to accept the scanned bodies with the message "Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)"
[Journal.190411124338.01.log](https://github.com/EDDiscovery/EDDiscovery/files/3070294/Journal.190411124338.01.log)
[Trace_2019-04-11-13-23-17.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3070300/Trace_2019-04-11-13-23-17.0.log)

**Comment by klightspeed** [comment]
```
[2019-04-11T16:50:00.864Z] Net tick exception : An unexpected network error occurred.
[2019-04-11T16:50:00.864Z] 
[2019-04-11T16:50:00.888Z]    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
[2019-04-11T16:50:00.888Z]    at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
[2019-04-11T16:50:00.888Z]    at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
[2019-04-11T16:50:00.888Z]    at EliteDangerousCore.TravelLogUnitLogReader.ReadLine[T](T& line, Func`2 processor, Stream stream, Boolean ownstream) in C:\Code\EDDiscovery\EliteDangerous\DB\TravelLogUnitLogReader.cs:line 135
[2019-04-11T16:50:00.888Z]    at EliteDangerousCore.EDJournalReader.ReadJournal(List`1& jent, List`1& uievents, Boolean historyrefreshparsing, Boolean resetOnError) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalReader.cs:line 218
[2019-04-11T16:50:00.888Z]    at EliteDangerousCore.JournalMonitorWatcher.ScanReader(EDJournalReader nfi, List`1 entries, List`1 uientries) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalMonitorWatcher.cs:line 224
[2019-04-11T16:50:00.888Z]    at EliteDangerousCore.JournalMonitorWatcher.ScanForNewEntries() in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalMonitorWatcher.cs:line 117
```

Are you accessing the journal over a file share?

```
[2019-04-11T16:50:01.035Z] Bad journal line:
[2019-04-11T16:50:01.035Z] <3383 null bytes>-04-11T16:49:52Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Plio Chruia GM-T d4-4 A A Belt Cluster 5", "BodyID":8, "Parents":[ {"Ring":3}, {"Star":1}, {"Null":0} ], "DistanceFromArrivalLS":7.005903 }
```

It looks like the handling of journal file errors needs to be looked at again.  Though it's quite possible that Windows file caching is doing us a disservice here (the nulls lead up to the start of a cluster in the journal file).

**Comment by robbyxp1** [comment]
Unless there is an obv clean solution, trying to get EDD to cover up for a network problem is not really the way to go with our code.  if the access to the file system is unstable, i don't think we should be in the buisness of trying to cover it up.

rob

**Comment by Andromedadragon** [comment]
I'm using it over a network share to read the journal files from the PC. I had the program on a laptop so that I could have the program near my while gaming. I'll move the application to the PC running Elite to see if that corrects the issue in the long term. I guess for now that it is a network protocol issue that my issue isn't valid or something that can be corrected.

**Comment by robbyxp1** [comment]
We can see if we can recover more gracefully from an IO error.  it does check the file constantly to pick up changes.  If your using Wifi, from the laptop, it may be too much for the link.

**Comment by klightspeed** [comment]
The I/O error itself wasn't the issue.  It looks like after the I/O error the OS cached bad data up to the end of the cluster.  I'm not sure how we would tell the OS to cut that out, and do an uncached read in that case.

**Comment by robbyxp1** [comment]
You would have thought the CRC on the data would have caught that one.. 

If so, not much we can do.
