### ISSUE TITLE
Feature request: Add ring density figure.

### ISSUE THREAD

**Issue by MKhrome** [EDDiscovery/EDDiscovery#2459]
In the information for rings, is it possible to add a ring density number?

A simple formula would suffice, like:

A/((3.14159265359*(C^2))-(3.14159265359*(B^2)))

Where A is the mass in MT, C is the outer radius in KM and B is the inner radius in KM. 

This may be an extremely obscure thing, but i hope it's easy enough to add. It's mostly an aid to find filming locations for me, when you're looking for specific types of rings :)

**Comment by spadino** [comment]
Hi! It seems very easy easy to do. I will give a look next days. Thanks for the idea

**Comment by robbyxp1** [comment]
Moved to project ideas, as its not being executed.
