### ISSUE TITLE
Travel History window empty

### ISSUE THREAD

**Issue by amdraper** [EDDiscovery/EDDiscovery#246]
I have my logs directory correctly set, when I open it with tools->show logfiles then it shows a directory with several logfiles in it.  Unfortunately there is nothing in the Travel History window.

(I tried to attach one of the logfiles but github does not like it, even with a .txt extension)

**Comment by iainross** [comment]
There's a drop down of time frames to show above the history - you've not got that set to too short a time frame so it's filtering out everything, have you?

**Comment by amdraper** [comment]
The dropdown is set to "Week" which should show something.  I tried setting it to "All" and to various other values but this did not change the contents of the history window.
I think the issue may be with capture rather than display.  Yesterday I took a screenshot and it was renamed "Unknown System (20160607-225049)"

**Comment by iainross** [comment]
You are on 3.2.3+ (anything earlier won't parse 1.6/2.1 logs properly)?

**Comment by amdraper** [comment]
No, I am on 3.0.5.0.  I will update, hopefully that will fix the issue.

**Comment by amdraper** [comment]
I downloaded 3.2.5.0 from https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_3.2.5
It looks much nicer but still no history I'm afraid.
I checked Tools->Show logfiles again, it still opens the correct directory.

**Comment by iainross** [comment]
Try hitting the refresh button?

If that doesn't work it will be ignoring those logs because it has already (however unsuccessfully) processed them.  You could either delete the database (Users\%user%\AppData\Local\EDDiscovery\EDDiscovery.sqlite) and restart the app to create a new one and reprocess the log files, or upload the files into EDSM through the webpage and sync from EDD.

**Comment by amdraper** [comment]
Yes that worked.  I now have all the logs since the 2.1 update.
Amazing application, just what I had been wanting for months.  It's just a shame I didn't know about it before I went to Sag A*
Thanks very much for your help.
