### ISSUE TITLE
Voicepack11 last EDD mixes spanish and english

### ISSUE THREAD

**Issue by XaRz** [EDDiscovery/EDDiscovery#2461]
I have the EDDiscovery language in Auto, and  I've installed VoiscePAck11 addon. I see texts of EDDiscovery in Spanish at same time the VoicePack mixes Spanish and English.

Knowing this I changed eddiscovery to default english and restarted (several times) Edd keeps showing texts in Spanish and mixing the VoicePack with english and Spanish in a aberration of Spanglish.

It seems that Eddiscover don't update the language after changing from Auto to English default.

Any help would be apreciated.  :)

**Comment by klightspeed** [comment]
What parts are in Spanish?  Is your Elite Dangerous language set to Spanish?  Is your system language set to Spanish?

I don't think the voice pack currently has languages other than English.

**Comment by XaRz** [comment]
Hi, 
My ED is in english but my system language is spanish. In the speech the bizarre sentences seems like the numbers are some in spanish the word thousand instead of "mil".
Things like that. I'll try to capture the audio in a video.

**Comment by robbyxp1** [comment]
Is it the NPCs which are talking in spanish?

I think if you have spanish voices installed in windows 10 you'll hear them as the voice pack currently picks a voice for a NPC at random from the installed voices.

I may have to make it select english only. 

I have a french sounding voice, but she does say the phrase in an heavily accented english!

**Comment by XaRz** [comment]
I mean the voice that that tells de log when I'm exploring. There is no NPC there, isn't it?

But I suspect that you are true, I think that it picks the audio from windows 10. Is there  a setting for selecting english voices in win10 or I may change all system language to english?

**Comment by robbyxp1** [comment]
You can select the voice it uses as the prime voice using the ADD On menu, voice menus.  One of them selects the primary voice.

**Comment by robbyxp1** [comment]
Presumed fixed by user.
