### ISSUE TITLE
Options for 'Scan' to show Total System Value in Panel or to be Embedded in a new Tab

### ISSUE THREAD

**Issue by macrossmerrell** [EDDiscovery/EDDiscovery#2462]
I know the Total System Value was removed from inside the Scan window for a variety of issues.  

- Having the value removed has caused issues for VR users that pin the Scan window into their VR Elite Dangerous environment.  Oculus hides the top window bar (where System Name and Total System Value are displayed. 

- This change also eliminated the ability to see the Total System Value for anyone that uses 'Scan' as a tab in EDDiscovery. Would love to have the option to display the system value inside the Scan window for VR Users and those that use the 'Scan' window as a tab in EDDiscovery.

Current work arounds:  Pin the entire EDDiscovery in the VR environment (takes up a lot of space), don't use 'Scan' in a tab.

Suggested idea:

- Allow users to create a tab where 'Scan' (or other) window can be inserted as it is on the 'History' tab.  This would allow the program to be resized to fit in VR environment with a custom Tab selected that has Scan (or other) window embedded  (showing the Total System Value).

Thank you for your consideration and for making such a great product that enriches Elite Dangerous!

**Comment by robbyxp1** [comment]
I'll have another look at the UI for this and come up with a solution..

**Comment by macrossmerrell** [comment]
You sir, are awesomesauce :)  

Thanks for letting me be a whiner!

**Comment by robbyxp1** [comment]
Fixed in 10.5.3. Out today prob.
