### ISSUE TITLE
Crash after minimizing after starting EDDiscovery

### ISSUE THREAD

**Issue by RoscoP** [EDDiscovery/EDDiscovery#2463]
### Description
Just started EDDiscovery, started on surveyer tab.  As soon as it opened, a moment later the tab filled out I minimized the window it crashed

### Exception Details:
>EDDiscovery v10.5.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentException: Parameter is not valid.
>   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
>   at BaseUtils.BitMapHelpers.DrawTextIntoAutoSizedBitmap(String text, Size maxsize, Font dp, Color c, Color b, Single backscale, StringFormat frmt) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\WinForms\BitMapHelpers.cs:line 98
>   at EDDiscovery.UserControls.UserControlSurveyor.DrawToScreen(WantedBodies body, Int32 bodiesCount) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSurveyor.cs:line 374
>   at EDDiscovery.UserControls.UserControlSurveyor.SelectBodiesToDisplay(List`1 wanted_nodes) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSurveyor.cs:line 319
>   at EDDiscovery.UserControls.UserControlSurveyor.DrawSystem(HistoryEntry he) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSurveyor.cs:line 277
>   at System.Windows.Forms.Control.OnResize(EventArgs e)
>   at System.Windows.Forms.UserControl.OnResize(EventArgs e)
>   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
>   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
>   at System.Windows.Forms.Control.UpdateBounds()
>   at System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.UserControl.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Thanks for the report

**Comment by klightspeed** [comment]
Would seem to suggest that the width of the surveyor picture box was 0 or negative.

**Comment by robbyxp1** [comment]
Fixed in 10.5.3. Thanks for the report.
