### ISSUE TITLE
Tab content not displayed correctly on low-height screen resolutions

### ISSUE THREAD

**Issue by KDERazorback** [EDDiscovery/EDDiscovery#2464]
### Description
The app failed to display the contents of the DataGridView control of the "Nearest Stars" panel on display resolution that has a very low vertical size (1366x768)
Since the screen vertical resolution is so low, the app tries to fit everything on the screen despite not having enough space, this leaves the DataGridView control with just enough space to fit its column headers only.
When you try to click on the control or to scroll it using the mouse wheel, an exception pops up.

### Additional Information
DPI Resolution is set to 100% by default on windows. This was never changed.
Screen resolution: 1366x768 (Default resolution on most plasma TVs and a lot of hi-inches TVs too, like mine).
Increasing TV/Screen resolution on windows solves the issue, but THIS specific issue should not be a restriction for the app and should be considered for the design as well.

### Suggestion
Wrap the contents of the main tab control inside a scroll-able container, so that IF the vertical resolution of the screen isn't enough for displaying all controls properly, a general vertical scrollbar appears on the side.

### Side note
A similar issue happens on the settings tab. The GroupBox titled "Move System DB/Reset UI etc" cannot be displayed correctly because it's trimmed vertically. Currently, I'm not able to know if there's any other GroupBox further down, because the app fails to display the rest of the content below that.

### Exception Details (redacted since the default system language is not en-US):
>EDDiscovery v10.5.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: No room is available to display rows..
>   at System.Windows.Forms.DataGridView.set_FirstDisplayedScrollingRowIndex(Int32 value)
>   at ExtendedControls.ExtPanelDataGridViewScroll.MoveDGVToRow(Int32 rowindex) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\PanelDataGridViewScroll.cs:line 299
>   at ExtendedControls.ExtPanelDataGridViewScroll.Wheel(Object sender, MouseEventArgs e) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\PanelDataGridViewScroll.cs:line 282
>   at System.Windows.Forms.Control.OnMouseWheel(MouseEventArgs e)
>   at System.Windows.Forms.DataGridView.OnMouseWheel(MouseEventArgs e)
>   at System.Windows.Forms.Control.WmMouseWheel(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

![History](https://user-images.githubusercontent.com/13314069/55364594-7706a180-549e-11e9-9462-7b9206b92834.png)

![Settings Tab](https://user-images.githubusercontent.com/13314069/55364593-7706a180-549e-11e9-9d02-b5cb7b921a67.png)

**Comment by robbyxp1** [comment]
The panels can be resize, hover your mouse over the area between the panels and a resizer will appear.  

![image](https://user-images.githubusercontent.com/6573992/55458561-2cdc0800-55e5-11e9-9429-6b036dc2cc05.png)

**Comment by robbyxp1** [comment]
Where the white line is, is a divider. 

The settings panel i'll look at

**Comment by robbyxp1** [comment]
Fixed settings window. 
thanks for the detailed report!
Closing
