### ISSUE TITLE
EDDN Market Event Inconsistent

### ISSUE THREAD

**Issue by RamblinEngineer** [EDDiscovery/EDDiscovery#2465]
When I first dock at a station and open the market UI in game, EDDiscovery will update EDDN with the current stock. After buying out stock on certain items, I used to be able to close the market UI in Elite, and reopen it, which would update the market quantity to EDDN again to update that said item is no longer in stock. In the last couple weeks, EDDiscovery will not send that 2nd market update upon reopening the UI.

**Comment by robbyxp1** [comment]
Will check

**Comment by robbyxp1** [comment]
The Market event from ED is only accepted into EDD if it is different from the previous one.  This is to stop spamming EDD when the user continuously goes into/out of the market screen.

I've just tested it with a difference, and it correctly accepts a new market event (and thus it would be sent to EDDN)

So i can't see a problem as of now.
