### ISSUE TITLE
ED Events ownly shown since 14th Jan

### ISSUE THREAD

**Issue by TonyFlury** [EDDiscovery/EDDiscovery#2466]
I have played ED since 19 December 2018, and I have the journal log files from then - this appears to be game version 3.3.0.402, I did not purchase horizons installed at this point.

Even though I have EDDiscovery set to show all events, it only shows events in the History Tab back to 14th January, This date does not appear to align with anything specific - for instance : 
 - I purchased/installed horizons on the 18th Jan
 - on 14th Jan, the version was 3.3.1.501 - this was installed on 18 December 2018
 - The Earliest history event number that is loaded is 59959 which doesn't seem like a logical boundary.

Am I doing something wrong ?

This is just a matter of interest, rather than a major issue, but it would be nice to have the full history loaded.

**Comment by robbyxp1** [comment]
have you got any filters on your travel history on.

To check, open up the journal tab (click on + on the tab line and select journal).  Is that filtered?

**Comment by TonyFlury** [comment]
No - On both the history and the Journal tabs the time is set to All

**Comment by klightspeed** [comment]
In the settings tab, do you have "Only read Essential Entries" set to e.g. >90 days?  90 days back from 03 Apr is 09 Jan.

When you reported this issue, had you only just installed EDDiscovery, or had you installed it earlier?

**Comment by TonyFlury** [comment]
No - I have 'Only read Essential Entries' Disabled - I had only just install EDDiscovery - but I have log files back to when i first started playing.

**Comment by robbyxp1** [comment]
You could zip up all the journal files in the saved folder and send them privately to me on discord (see the EDD thread for the invite on the forums/exploration)

**Comment by TonyFlury** [comment]
Will do - give me a day or so.

**Comment by TonyFlury** [comment]
The discord invite (https://discord.gg/CS3eK) is showing as invalid
So here are the zipped files (all 410 of them) 
[Journal.181223101706.01.zip](https://github.com/EDDiscovery/EDDiscovery/files/3133349/Journal.181223101706.01.zip)

**Comment by klightspeed** [comment]
Try https://discordapp.com/invite/0qIqfCQbziTWzsQu - that is the URL in the `Help` -> `Discord` menu item.

**Comment by TonyFlury** [comment]
File is too big to send on discord (without upgrading) - have attached to the comment above.

**Comment by robbyxp1** [comment]
Is this still happening?

**Comment by robbyxp1** [comment]
Closing, reopen if required.
