### ISSUE TITLE
Scan panel: Select Image Size

### ISSUE THREAD

**Issue by KyleHamar** [EDDiscovery/EDDiscovery#2468]
In scan panel, clicking on select image size icon spawns a popup to pick the size. That popup appears on primary monitor even though EDDiscovery is running on alternate monitor. This happens in full screen and also windowed. 

Expected behavior: Clicking on image size icon should spawn the size selector windows nearby the mouse position and on the monitor that is in focus.

**Comment by robbyxp1** [comment]
Thanks. What version are you using?

Just tested it on the tip code with my 3 monitors and it functions correctly.

**Comment by KyleHamar** [comment]
I updated to 10.5.4.0 today and tried again. The image size box appears correctly if I place EDD window on my main monitor. That popup with image size will only appear on my main monitor, even if I drag EDD to my alternate monitor.

**Comment by robbyxp1** [comment]
hmmm. how to test this.  What OS are you using? Is there anything about your monitor setup different to the normal side by side.. etc.

**Comment by KyleHamar** [comment]
Windows 10. Two monitors, Nvidia Geforce GTX 980. Very standard setup.

**Comment by KyleHamar** [comment]
Ok, tested with two other computers. One shows the bug and one does not.

**Comment by robbyxp1** [comment]
Closing, no way to reproduce at the moment. will keep it in mind.
