### ISSUE TITLE
Ver 10.5.3.0 unhandled UI exception

### ISSUE THREAD

**Issue by IliasSarpedon** [EDDiscovery/EDDiscovery#2469]
after updating and starting the new version, i received this message. Parts of information e.g. Missions are missing...

There was an unhandled UI exception.
==== BEGIN ====
System.FormatException: Der Index, basierend auf 0 (null), muss größer als oder gleich Null sein, und kleiner als die Größe der Argumentenliste.
   bei System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei System.Text.StringBuilder.AppendFormat(String format, Object[] args)
   bei EliteDangerousCore.JournalEvents.JournalScan.DisplayString(Int32 indent, Boolean includefront, MaterialCommoditiesList historicmatlist, MaterialCommoditiesList currentmatlist) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalScan.cs:Zeile 622.
   bei EDDiscovery.UserControls.ScanDisplayControl.DrawNode(List`1 pc, ScanNode sn, MaterialCommoditiesList curmats, HistoryList hl, Image notscanned, Point curpos, Size size, Int32& offset, Boolean aligndown, Int32 labelvoff, Boolean toplevel) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplay.cs:Zeile 288.
   bei EDDiscovery.UserControls.ScanDisplayControl.DrawSystem(SystemNode last_sn, MaterialCommoditiesList curmats, HistoryList hl, String opttext) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplay.cs:Zeile 104.
   bei EDDiscovery.UserControls.UserControlScan.DrawSystem() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:Zeile 195.
   bei EDDiscovery.UserControls.UserControlScan.Display(HistoryEntry he, HistoryList hl, Boolean selectedEntry) in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:Zeile 160.
   bei EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl, Boolean selectedEntry)
   bei EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:Zeile 546.
   bei EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl, Boolean disablesorting) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:Zeile 287.
   bei System.Action`1.Invoke(T obj)
   bei EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshComplete(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:Zeile 848.
===== END =====

**Comment by robbyxp1** [comment]
Found, fixing in 10.5.4 in a few mos
