### ISSUE TITLE
Vipre Advanced Security blocking 10.5.4 install - reports as malware

### ISSUE THREAD

**Issue by rhedrock** [EDDiscovery/EDDiscovery#2471]
Vipre hasn't blocked previous versions. Blocks version 10.5.4 and reports it as 'general malware'.

**Comment by klightspeed** [comment]
Does it block the files in the portable zip file?

**Comment by robbyxp1** [comment]
I passed the exe thru total virus.  These virus scanners guess a lot.

![image](https://user-images.githubusercontent.com/6573992/55670817-c3782580-5880-11e9-8592-4b456f6cc53b.png)

**Comment by rhedrock** [comment]
Yes, Vipre blocks the executable in the extracted portable zip file as well.

![image](https://user-images.githubusercontent.com/27317413/55683150-7ccf0d80-590a-11e9-8d4a-98883805cb85.png)

**Comment by klightspeed** [comment]
I wonder what it is flagging as malicious behaviour?

**Comment by robbyxp1** [comment]
Not much we can do about these virus thingies.

**Comment by klightspeed** [comment]
Probably a bad choice of words.  To be clear, there isn't a lot we can do
about random antivirus programs flagging new programs as suspicious.

**Comment by robbyxp1** [comment]
Haha. That's what i meant.  These virus scanners using heuristics are non predictable in their flagging of executables.
