### ISSUE TITLE
There was an unhandled UI exception

### ISSUE THREAD

**Issue by brallinoth** [EDDiscovery/EDDiscovery#2472]
This came up when I started the program.  After a fresh install because all it was doing was freezing up on me when I started it up.
### Exception Details:
>EDDiscovery v10.1.6.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.IndexOutOfRangeException: Index was outside the bounds of the array.
>   at EDDiscovery.UserControls.UserControlSysInfo.UpdateViewOnSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSysInfo.cs:line 500
>   at EDDiscovery.UserControls.UserControlSysInfo.Display(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSysInfo.cs:line 162
>   at EDDiscovery.UserControls.UserControlContainerSplitter.<LoadLayout>b__12_0(SplitterPanel p, Control c) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlContainerSplitter.cs:line 129
>   at ControlHelpersStaticFunc.RunActionOnSplitterTree(SplitContainer sc, Action`2 action) in C:\Code\EDDiscovery\BaseUtils\WinForms\ControlHelpers.cs:line 390
>   at EDDiscovery.UserControls.UserControlContainerSplitter.LoadLayout() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlContainerSplitter.cs:line 131
>   at EDDiscovery.MajorTabControl.LoadTabs() in C:\Code\EDDiscovery\EDDiscovery\MajorTabControl.cs:line 113
>   at EDDiscovery.EDDiscoveryForm.EDDiscoveryForm_Load(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 318
>   at System.Windows.Forms.Form.OnLoad(EventArgs e)
>   at System.Windows.Forms.Form.OnCreateControl()
>   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>   at System.Windows.Forms.Control.CreateControl()
>   at System.Windows.Forms.Control.WmShowWindow(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.Form.WmShowWindow(Message& m)
>   at ExtendedControls.SmartSysMenuForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\Forms\SmartSysMenuForm.cs:line 224
>   at ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\Forms\DraggableForm.cs:line 124
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
Please try upgrading to the latest version.

**Comment by brallinoth** [comment]
Okay that worked, though I downloaded the right one, it still freezes up and does nothing

**Comment by klightspeed** [comment]
If it freezes during "Repairing Canopy", please try removing EDDSystem.sqlite from that EDDiscovery data directory (`%LOCALAPPDATA%\EDDiscovery` for the installed version or `Data` for the portable version)

**Comment by klightspeed** [comment]
Does the entire program freeze, or is it just the history panel that shows the busy cursor and doesn't update?  If it's the latter, it should update once it has fully loaded.

**Comment by brallinoth** [comment]
It freezes once it updates, updates with every opening of my current position, so it is reading the logs and updating, but it doesn't continue a current update on my progress. Until I shut it down and restart it. Would having two different commanders playing on both systems cause an issue. (I was thinking of copying the logs from the lap top and pasting them into the desk top)

**Comment by robbyxp1** [comment]
You did have "Cursor to top" on the history window (up green arrow on main history page)..

**Comment by brallinoth** [comment]
Yes, but the entire window is frozen, can't even change commanders name,
once I open it. It does read the logs that I have added but afterwards, it
doesn't do anything. Since I have two commanders and use two computers for
both of them I did try copying the journal entries from the laptop to the
desktop and that does work for me, just a nuisance,

**Comment by klightspeed** [comment]
Does it work if you disable EDSM star data download in the settings tab?

**Comment by brallinoth** [comment]
Once it updates the journals it freezes and I have to force close it. I
Tried downloading it  again also

**Comment by klightspeed** [comment]
What if you hold shift while starting, then click Delete / Rebuild System DB, and click Run, then disable the EDSM star data download?

**Comment by brallinoth** [comment]
Thank you. Seems to be working now.
