### ISSUE TITLE
Scan - body status icon spacing

### ISSUE THREAD

**Issue by goscickiw** [EDDiscovery/EDDiscovery#2477]
The body status icon spacing in Scan panel can be confusing sometimes. For example, in the picture below the icons for planet 3 look like they are for planet 2:
![iconspacing](https://user-images.githubusercontent.com/39399945/56457246-06a1c080-6378-11e9-87f2-03462ffd17a1.png)
Also, visible in the picture (on moon A of planet 1), when using smaller icon sizes (48 and below), the [+] icon indicating the presence of materials overlaps the body, and stays the same size no matter which icon size I choose.

**Comment by robbyxp1** [comment]
Will look at it, ta

**Comment by robbyxp1** [comment]
Fixing in 10.6
