### ISSUE TITLE
Can not access last option on drop down menu.

### ISSUE THREAD

**Issue by Jax15132** [EDDiscovery/EDDiscovery#2478]
Had a problem with a drop down menu, the menu drops beneath the task bar and unable to click on the last option.  What I was trying to do was set up a materials list and while using the filter options and scrolling to the bottom of the list looking for Zirconium the last option available was Zinc.  Actually thought Zirconium was missing from the list, after selecting the “All” option from the top of the list and seen that Zirconium was actually added to the list figured out that the drop down menu was actually falling underneath the task bar, had to hide the task bar to reach the final option “Zirconium”.
 After going through the settings found an option to “Keep on Top” which did force this drop down list above the task bar but it also hides every other window I have open including the game, so not relay a viable option.
  Maybe you could add just a bit of real estate at the bottom of the drop down to push the final entry up above the task bar.
 Thanks.
Quick edit: can set task bar to auto hide (I don't prefer that behavior my self), click and drag to the side to move it quickly is a good work around for now and can be done quickly.

**Comment by robbyxp1** [comment]
Added a margin for the main drop downs.

thanks for the report.
