### ISSUE TITLE
UI exception with build info to Coriolis

### ISSUE THREAD

**Issue by dooferorg** [EDDiscovery/EDDiscovery#2482]
Got a UI exception opening a ship build to coriolis

`### Description

### Exception Details:
>EDDiscovery v10.5.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.ShipInformation.ToJsonCoriolisEngineering(ShipModule module) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\ShipInformation.cs:line 662
>   at EliteDangerousCore.ShipInformation.ToJSONCoriolis(String& errstring) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\ShipInformation.cs:line 639
>   at EDDiscovery.UserControls.UserControlModules.buttonExtCoriolis_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlModules.cs:line 369
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>````

**Comment by robbyxp1** [comment]
Found and will be fixed in 10.6 out v.soon thank you
