### ISSUE TITLE
Feature Request: Postgresql support

### ISSUE THREAD

**Issue by temotodochi** [EDDiscovery/EDDiscovery#2483]
Hi, as you might know windows 10 has native support for postgresql (installable feature) and it works quite a bit faster than sqlite considering tens of millions of star systems and related data. 

Would it be possible to support localhost postgresql some time in the future?

**Comment by robbyxp1** [comment]
I have no plans to remove SQLite from this program at this point.

SQLite works fast enough for now for most of EDD use cases. 

So no, thats really not in the future plans to remove SQLLite from this at this point. 

Its all a balance of possibilities, and i see more payoff with some ideas i have to improve the program than spend time doing that.

Thanks for the idea.

**Comment by klightspeed** [comment]
EDDiscovery/BaseUtilities#9 adds preliminary support for overriding the connection string and provider.
