### ISSUE TITLE
Problem exporting ship to Coriolis after patch

### ISSUE THREAD

**Issue by strangealien** [EDDiscovery/EDDiscovery#2484]
EDDiscovery has a problem since the patch exporting my ship to Coriolis. The Journal entry (reported by EDDiscovery) mentions Optional Slots, numbered from slot 1 to slot 8, on a DBX. The DBX has now 8 optional internal slots, sizes 4, 4, 3, 3, 2, 2, 1, 1.
I currently have a shield size 4 and a fuel Scoop size 4 in the first two slots.
Slot 3 (size 3) is empty, Slot 4 (size 3) has an AFMU.
Slot 5 and slot 6 (both size 2) have a vehicle hangar each.
The new slots 7 and 8, both size 1 have a DC and a DSS.
The empty slot is either exported wrong or Coriolis does it wrong. But Coriolis can export and import this build without errors. But exporting the ship from EDDiscovery leaves out the empty slot 3, it shifts everything up one slot, which is wrong.
All the other equipment is exported correct.

**Comment by robbyxp1** [comment]
Can you export for me the loadout journal entry of your ship and paste it in here.

Right click on the loadout journal entry and click "Copy to clipboard/log" and paste it in here.

Then i can try your export to coriolis and see whats up!

Thanks

**Comment by strangealien** [comment]
Hello,

and thank you for the reply. Here is my journal entry 'loadout', from EDDiscovery:
{
  "timestamp": "2019-04-27T13:39:59Z",
  "event": "Loadout",
  "Ship": "DiamondBackXL",
  "ShipID": 1,
  "ShipName": "Vasco da Gama",
  "ShipIdent": "JP-09D",
  "HullValue": 1392539,
  "ModulesValue": 12004267,
  "HullHealth": 1.0,
  "UnladenMass": 346.940002,
  "CargoCapacity": 0,
  "MaxJumpRange": 56.374001,
  "FuelCapacity": {
    "Main": 32.0,
    "Reserve": 0.52
  },
  "Rebuy": 669840,
  "Modules": [
    {
      "Slot": "LargeHardpoint1",
      "Item": "hpt_multicannon_gimbal_large",
      "On": true,
      "Priority": 1,
      "AmmoInClip": 90,
      "AmmoInHopper": 2100,
      "Health": 1.0,
      "Value": 462749
    },
    {
      "Slot": "MediumHardpoint1",
      "Item": "hpt_pulselaser_gimbal_medium",
      "On": true,
      "Priority": 1,
      "Health": 1.0,
      "Value": 30090
    },
    {
      "Slot": "MediumHardpoint2",
      "Item": "hpt_pulselaser_gimbal_medium",
      "On": true,
      "Priority": 1,
      "Health": 1.0,
      "Value": 28320
    },
    {
      "Slot": "TinyHardpoint1",
      "Item": "hpt_plasmapointdefence_turret_tiny",
      "On": true,
      "Priority": 0,
      "AmmoInClip": 12,
      "AmmoInHopper": 9496,
      "Health": 1.0,
      "Value": 18083
    },
    {
      "Slot": "TinyHardpoint2",
      "Item": "hpt_chafflauncher_tiny",
      "On": true,
      "Priority": 0,
      "AmmoInClip": 1,
      "AmmoInHopper": 10,
      "Health": 1.0,
      "Value": 7225
    },
    {
      "Slot": "TinyHardpoint3",
      "Item": "hpt_heatsinklauncher_turret_tiny",
      "On": true,
      "Priority": 0,
      "AmmoInClip": 1,
      "AmmoInHopper": 2,
      "Health": 1.0,
      "Value": 3500
    },
    {
      "Slot": "TinyHardpoint4",
      "Item": "hpt_plasmapointdefence_turret_tiny",
      "On": true,
      "Priority": 0,
      "AmmoInClip": 8,
      "AmmoInHopper": 9736,
      "Health": 1.0,
      "Value": 18083
    },
    {
      "Slot": "Armour",
      "Item": "diamondbackxl_armour_grade1",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "PowerPlant",
      "Item": "int_powerplant_size4_class5",
      "On": true,
      "Priority": 1,
      "Health": 1.0,
      "Value": 1225049,
      "Engineering": {
        "Engineer": "Felicity Farseer",
        "EngineerID": 300100,
        "BlueprintID": 128673770,
        "BlueprintName": "PowerPlant_Stealth",
        "Level": 1,
        "Quality": 1.0,
        "ExperimentalEffect": "special_powerplant_lightweight",
        "ExperimentalEffect_Localised": "Stripped Down",
        "Modifiers": [
          {
            "Label": "Mass",
            "Value": 4.68,
            "OriginalValue": 5.0,
            "LessIsGood": 1
          },
          {
            "Label": "PowerCapacity",
            "Value": 15.132001,
            "OriginalValue": 15.6,
            "LessIsGood": 0
          },
          {
            "Label": "HeatEfficiency",
            "Value": 0.3,
            "OriginalValue": 0.4,
            "LessIsGood": 1
          }
        ]
      }
    },
    {
      "Slot": "MainEngines",
      "Item": "int_engine_size4_class5",
      "On": true,
      "Priority": 0,
      "Health": 1.0,
      "Value": 1569828,
      "Engineering": {
        "Engineer": "Felicity Farseer",
        "EngineerID": 300100,
        "BlueprintID": 128673665,
        "BlueprintName": "Engine_Tuned",
        "Level": 1,
        "Quality": 0.941,
        "Modifiers": [
          {
            "Label": "EngineOptimalMass",
            "Value": 411.600037,
            "OriginalValue": 420.0,
            "LessIsGood": 0
          },
          {
            "Label": "EngineOptPerformance",
            "Value": 108.000015,
            "OriginalValue": 100.0,
            "LessIsGood": 0
          },
          {
            "Label": "EngineHeatRate",
            "Value": 1.04767,
            "OriginalValue": 1.3,
            "LessIsGood": 1
          }
        ]
      }
    },
    {
      "Slot": "FrameShiftDrive",
      "Item": "int_hyperdrive_size5_class5",
      "On": true,
      "Priority": 0,
      "Health": 1.0,
      "Value": 4338361,
      "Engineering": {
        "Engineer": "Elvira Martuuk",
        "EngineerID": 300160,
        "BlueprintID": 128673694,
        "BlueprintName": "FSD_LongRange",
        "Level": 5,
        "Quality": 0.989,
        "ExperimentalEffect": "special_fsd_heavy",
        "ExperimentalEffect_Localised": "Mass Manager",
        "Modifiers": [
          {
            "Label": "Mass",
            "Value": 26.0,
            "OriginalValue": 20.0,
            "LessIsGood": 1
          },
          {
            "Label": "Integrity",
            "Value": 93.840004,
            "OriginalValue": 120.0,
            "LessIsGood": 0
          },
          {
            "Label": "PowerDraw",
            "Value": 0.69,
            "OriginalValue": 0.6,
            "LessIsGood": 1
          },
          {
            "Label": "FSDOptimalMass",
            "Value": 1691.398682,
            "OriginalValue": 1050.0,
            "LessIsGood": 0
          }
        ]
      }
    },
    {
      "Slot": "LifeSupport",
      "Item": "int_lifesupport_size3_class2",
      "On": true,
      "Priority": 0,
      "Health": 1.0,
      "Value": 8614
    },
    {
      "Slot": "PowerDistributor",
      "Item": "int_powerdistributor_size4_class2",
      "On": true,
      "Priority": 0,
      "Health": 1.0,
      "Value": 24118
    },
    {
      "Slot": "Radar",
      "Item": "int_sensors_size3_class2",
      "On": true,
      "Priority": 0,
      "Health": 1.0,
      "Value": 8614
    },
    {
      "Slot": "FuelTank",
      "Item": "int_fueltank_size5_class3",
      "On": true,
      "Priority": 1,
      "Health": 1.0,
      "Value": 83090
    },
    {
      "Slot": "Decal1",
      "Item": "decal_explorer_elite",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "Decal2",
      "Item": "decal_explorer_elite",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "Decal3",
      "Item": "decal_explorer_elite",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "Slot01_Size4",
      "Item": "int_shieldgenerator_size4_class5",
      "On": true,
      "Priority": 0,
      "Health": 1.0,
      "Value": 1368568,
      "Engineering": {
        "Engineer": "Elvira Martuuk",
        "EngineerID": 300160,
        "BlueprintID": 128673826,
        "BlueprintName": "ShieldGenerator_Optimised",
        "Level": 2,
        "Quality": 1.0,
        "ExperimentalEffect": "special_shield_lightweight",
        "ExperimentalEffect_Localised": "Stripped Down",
        "Modifiers": [
          {
            "Label": "Mass",
            "Value": 6.66,
            "OriginalValue": 10.0,
            "LessIsGood": 1
          },
          {
            "Label": "Integrity",
            "Value": 86.399994,
            "OriginalValue": 96.0,
            "LessIsGood": 0
          },
          {
            "Label": "PowerDraw",
            "Value": 2.31,
            "OriginalValue": 3.08,
            "LessIsGood": 1
          },
          {
            "Label": "ShieldGenOptimalMass",
            "Value": 276.450012,
            "OriginalValue": 285.0,
            "LessIsGood": 0
          },
          {
            "Label": "ShieldGenStrength",
            "Value": 127.199997,
            "OriginalValue": 120.000008,
            "LessIsGood": 0
          }
        ]
      }
    },
    {
      "Slot": "Slot02_Size4",
      "Item": "int_fuelscoop_size4_class5",
      "On": true,
      "Priority": 2,
      "Health": 1.0,
      "Value": 2433010
    },
    {
      "Slot": "Slot04_Size3",
      "Item": "int_repairer_size3_class2",
      "On": false,
      "Priority": 2,
      "Health": 1.0,
      "Value": 82620
    },
    {
      "Slot": "Slot05_Size2",
      "Item": "int_buggybay_size2_class2",
      "On": true,
      "Priority": 2,
      "Health": 1.0,
      "Value": 18360
    },
    {
      "Slot": "Slot06_Size2",
      "Item": "int_buggybay_size2_class2",
      "On": true,
      "Priority": 2,
      "Health": 1.0,
      "Value": 21060
    },
    {
      "Slot": "PlanetaryApproachSuite",
      "Item": "int_planetapproachsuite",
      "On": true,
      "Priority": 1,
      "Health": 1.0,
      "Value": 425
    },
    {
      "Slot": "VesselVoice",
      "Item": "voicepack_verity",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "Slot07_Size1",
      "Item": "int_dockingcomputer_standard",
      "On": true,
      "Priority": 0,
      "Health": 1.0,
      "Value": 4500
    },
    {
      "Slot": "Slot08_Size1",
      "Item": "int_detailedsurfacescanner_tiny",
      "On": true,
      "Priority": 0,
      "Health": 1.0,
      "Value": 250000
    },
    {
      "Slot": "ShipCockpit",
      "Item": "diamondbackxl_cockpit",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "CargoHatch",
      "Item": "modularcargobaydoor",
      "On": true,
      "Priority": 3,
      "Health": 1.0
    }
  ]
}

**Comment by robbyxp1** [comment]
![image](https://user-images.githubusercontent.com/6573992/56851613-0752cd80-6909-11e9-9bdf-d6be611bc6e4.png)

Your ship is in..

here is the export to coriolis of the slots

  {
      "Item": "Int_fuelscoop_size4_class5",
      "Slot": "Slot02_Size4",
      "On": true,
      "Priority": 2
    },
    {
      "Item": "Int_repairer_size3_class2",
      "Slot": "Slot04_Size3",
      "On": false,
      "Priority": 2
    },
    {
      "Item": "Int_buggybay_size2_class2",
      "Slot": "Slot05_Size2",
      "On": true,
      "Priority": 2
    },
    {
      "Item": "Int_buggybay_size2_class2",
      "Slot": "Slot06_Size2",
      "On": true,
      "Priority": 2
    },
    {
      "Item": "Int_dockingcomputer_standard",
      "Slot": "Slot07_Size1",
      "On": true,
      "Priority": 0
    },
    {
      "Item": "Int_detailedsurfacescanner_tiny",
      "Slot": "Slot08_Size1",
      "On": true,
      "Priority": 0
  
It looks good, i'll ask the Coriolis people for comments

**Comment by robbyxp1** [comment]
I've reported the issue to the Coriolis people and we will see what happens.  Thanks for the effort of reporting it!

Rob

**Comment by robbyxp1** [comment]
I'm presuming they will fix it.
