### ISSUE TITLE
Market Data not updating

### ISSUE THREAD

**Issue by FalcoGer** [EDDiscovery/EDDiscovery#2486]
The information on the 'Market Data' panel are not updating, even after docking. I had the program running for some time, and it still only shows a single market with price data from the 01.01.2019. I didn't fly for some time but just this month I have docked at several stations with markets and nothing is changing.
Perhaps the market data is no longer dumped into the journal, but instead you need to use the new web API to fetch it like EDMC does?

**Comment by robbyxp1** [comment]
Yes its still being exported to the journal I believe.

Silly question, you have the left select to "Travel History Entry Last'...

I'll check tomorrow with my second account.

**Comment by FalcoGer** [comment]
There are only two entries in the drop down list. Travel History and Diaguandri from 5 months back.
Shipyards didn't update either, but Outfitting did for some reason at Eravate/Ackerman when I docked at it 4 days ago. But not when I docked 2 days ago.

Say do I actually have to open the market screen for things to update?

**Comment by robbyxp1** [comment]
The API is not currently planned, this is its only use case, and its a lot of work to make sure it works. 

Maybe in the future, but not yet

glad you had it sorted.
