### ISSUE TITLE
[Feature Request] EDD to save custom tab between sessions

### ISSUE THREAD

**Issue by TonyFlury** [EDDiscovery/EDDiscovery#2489]
I have created a tab that allows me (after a fashion) to keep track of bodies I have scanned that have surface deposits.

It would be great if EDD could keep track of that tab - and have an option to save it so that it opens when EDD restarts.

Note : Even when the custom tab is the one selected on shutdown; EDD doesn't restore the custom tab.

I have noted that the tab I created is based on the splitter template - and if I select that splitter for a new tab it does restore my custom tab; so presumably it is recording the last used layout.

**Comment by robbyxp1** [comment]
Hi,

Sound good.  Slightly confused though.  Where did you create the tab?  Is it an addition to the EDD code base? 

New panels are created (see the UserControlNotePanel.cs for a simple one), conform to the panel rules, have a entry in PanelAndPopOuts, have an icon in EDIcons, and then they operate basically in isolation to each other.  They can be inserted into the main tab line, into a splitter or grid holder. 

So I'm not sure what you've exactly done as of now.

**Comment by TonyFlury** [comment]
I haven't altered the code in anyway. I simply added a new Tab by clicking the + on the GUI, and then chose the gird planner. I then used the GUI to add panels to the grid.

**Comment by robbyxp1** [comment]
It should restart to the last major tab selected when you close the program.

The grid should remember the panels and positions of them, and the z-order of them.

I've just checked it and it does.

**Comment by TonyFlury** [comment]
ok - what I has was very weird then - it didn't do that on at least two previous sessions.
Closing....
