### ISSUE TITLE
Travel history not updating

### ISSUE THREAD

**Issue by ChrisJ66** [EDDiscovery/EDDiscovery#249]
Running Horizons on Win10 x64 and noticed tonight that I am about 3-4 weeks behind on the travel history. Verbose logging had got turned off with the last update but have reinstated - 

<Network
	  Port="0"
      upnpenabled="1"
	  LogFile="netLog"
	  DatestampLog="1"
	  VerboseLogging="1"	  
	  >
	</Network>

**Comment by mwerle** [comment]
Which version of EDDiscovery are you running?  As of ED2.1, the logfile format has changed so you need a newer version of EDD (at least 3.2.3). Also, verbose logging is no longer necessary.

**Comment by ChrisJ66** [comment]
I’m running 3.2.4 as of last night but still not updating the travel history. Have tried uninstalling/reinstalling but still no difference

**Comment by mwerle** [comment]
You're pointing your "Elite Dangerous netlog location" at the correct directory? You don't have multiple installs of Elite? (Eg, Steam, or Beta)? Are you using multiple Commanders?

**Comment by ChrisJ66** [comment]
Definitely correct netlog location, have browsed to and can see logs from yesterday

Only 1 copy of Elite plus Horizons, no beta and not via steam. Does show me option of 32/64bit and then Horizons on start but that is normal I belive

Only 1 commander but I did accidentally start to add another in the settings page early on in using the app, can confirm that the original commander is the active one (with the arrow). Not found a way to delete the rogue one though!

 

May be worth doing a complete uninstall but just unnstalling from add/remove programs doesn’t seem to completely remove everything as when I then reinstalled it didn’t ask for any settings and still had the additional blank commander. Does it need cleaning up in registry to fully remove or deleting of particular folders?

**Comment by klightspeed** [comment]
If you open with Notepad one of the recent `netLog.yymmddhhmss.nn.log` files where you have been jumping between systems in the last few weeks, and do a search for `} System:`, what is one of the lines that is found?

To reset the config for EDDiscovery, one can browse to `%LOCALAPPDATA%\EDDiscovery` and rename `EDDiscovery.sqlite` to `EDDiscovery.sqlite.old` (or completely remove that file if you have already synced everything to EDSM).

**Comment by ChrisJ66** [comment]
Here's the first instance of } System that comes up  -
} System:"Outordy ZT-O b20-0" StarPos:(-3279.281,140.438,-1903.031)ly Body:9 RelPos:(-435.43,-1842.57,3761.6)km NormalFlight
I tried the config reset and that seems to have fixed the issue, it now manages to read my flight logs over the last few weeks. I've also "found" what I'm supposed to do with it by reigstering on the website, inserting the API key and uploading my travel history - now it makes more sense :-)
