### ISSUE TITLE
[Feature Request] A new in-built permanent for finding materiels

### ISSUE THREAD

**Issue by TonyFlury** [EDDiscovery/EDDiscovery#2491]
Using the data of which objects have been scanned, would it be possible to have a dedicated tab just for finding where particular surface material deposits might be.

EDD has the information - as it is able to pull together the system map with the icons; it is just not available in a searchable form.

I don't want to be able to see data on objects I haven't scanned - so it doesn't require jumping off to the ED API to fetch a galaxy worth of data.

**Comment by klightspeed** [comment]
The only information available is what materials are present on each scanned planet.  No information is available on where on the planet those materials are likely to be found.

I think the shopping list has what planets have the materials you want.

**Comment by robbyxp1** [comment]
Look at the search panel, click on materials button (second icon) and you can search all your scans/material collected events for a particular material.

As stated, we can't guess what is there.

thanks for the feedback.

**Comment by TonyFlury** [comment]
ok - how about this : 
1) You do know what has been collected and where
2) You do know which  planets have been scanned
3) You do know the composition of the planets (since you display that info).

I don't know if you know how many locations (geolgical etc exist on each planet).

Could you do a combined search which will list both : 
1) Sites where the material has actually been collected
2) Planets which have the material in  their make up, have been scanned, and have volcanism (since this are the ones which that have the geological locations).

Category 2 is an informed guess - given the information that EDD has, and could be differentiated by a different Icon - effectively it is a synthetic event just for this search.
