### ISSUE TITLE
Crashing at launch v10.5.4.0 Fatal Error

### ISSUE THREAD

**Issue by EDVillers** [EDDiscovery/EDDiscovery#2493]
### Exception Details:
>EDDiscovery v10.5.4.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
>File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
>   at EDDiscovery.EDDTheme.LoadThemes()
>   at EDDiscovery.EDDiscoveryForm.Init(Action`1 msg) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 190
>   at EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:line 146
>
>WRN: Assembly binding logging is turned OFF.
>To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
>Note: There is some performance penalty associated with assembly bind failure logging.
>To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
>
>===== END =====
>```

**Comment by klightspeed** [comment]
How did you install EDDiscovery?  This looks like DLLs from different versions were mixed.

**Comment by mjericho1228** [comment]
I downloaded the exe, ran it. then once installed and set up initially i closed and restarted it and it started crashing

**Comment by robbyxp1** [comment]
No user response. closed
