### ISSUE TITLE
Denoting Biological POIs

### ISSUE THREAD

**Issue by metalsynkk** [EDDiscovery/EDDiscovery#2496]
So there was a rather short thread regarding this (https://github.com/EDDiscovery/EDDiscovery/issues/2433), however my question is whether EDD can pull just the number of POIs from the FSS scan. All I know is that when you scan a planet in FFS mode and it doesn't give [None] in the locations section, you just need to wait 5-20 seconds and it will reveal how many geo/bio/xeno locations there are. Is it not possible to pull just this number and denote that in the 'Scan' section of EDD. similar to how the volcanism icon is displayed?

**Comment by klightspeed** [comment]
The presence of biological POIs is not written to the journal.  The Volcanism symbol is from the `Volcanism` attribute of the `Scan` event.
