### ISSUE TITLE
EDDiscovery v10.6.0.0 Surveyor Panel NRE.

### ISSUE THREAD

**Issue by rastitkac** [EDDiscovery/EDDiscovery#2497]
### Description
I started the application.

### Additional Information
E:D was not launched yet, not even the launcher.
Steam system tray agent was running.
Except main application window, I exited the previous time with the splitter panel open.
Splitter panel has visited stars, estimated values and surveyor panels.
Main application window has history, system information, trip computer, visited stars and estimated values panels.

### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlSurveyor.Display(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSurveyor.cs:line 91
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshComplete(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 848
>===== END =====
>```

**Comment by robbyxp1** [comment]
I'll look. the dear old surveyor panel..

**Comment by CMDR-Cometborne** [comment]
Similar issue:

### Description


### Additional Information


### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
>database is locked
>   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at SQLLiteExtensions.SQLExtDataReader`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLExtTransaction`1 txn, SQLExtTransactionLock`1 txnlock) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLReader.cs:line 38
>   at SQLLiteExtensions.SQLExtCommand`1.ExecuteDbDataReader(CommandBehavior behavior) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:line 92
>   at EliteDangerousCore.DB.SystemClassDB.GetEdsmIdsFromName(String name, SQLiteConnectionSystem cn, Boolean uselike) in C:\Code\EDDiscovery\EliteDangerous\DB\SystemClassDB.cs:line 276
>   at EliteDangerousCore.DB.SystemClassDB.GetSystemsByName(String name, SQLiteConnectionSystem cn, Boolean uselike) in C:\Code\EDDiscovery\EliteDangerous\DB\SystemClassDB.cs:line 301
>   at EliteDangerousCore.SystemCache.FindSystem(ISystem find, SQLiteConnectionSystem conn) in C:\Code\EDDiscovery\EliteDangerous\DB\SystemCache.cs:line 79
>   at EliteDangerousCore.HistoryList.FillEDSM(HistoryEntry syspos) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 575
>   at EDDiscovery.UserControls.UserControlSysInfo.Display(HistoryEntry he, HistoryList hl, Boolean selectedEntry) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSysInfo.cs:line 197
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl, Boolean selectedEntry)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 546
>   at EDDiscovery.UserControls.UserControlTravelGrid.<>c__DisplayClass48_0.<HistoryChanged>b__0() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 345
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
@CMDR-Cometborne please create a separate issue, as your error is different to the OP.

**Comment by robbyxp1** [comment]
Protected, thanks for the report.
