### ISSUE TITLE
Exporting material % of scanned bodies into CSV

### ISSUE THREAD

**Issue by soundasleep** [EDDiscovery/EDDiscovery#2498]
In a previous version of EDDiscovery I vaguely remember I was able to export my visited systems history into CSV, and for each scanned body, it included a separate column for each material (e.g. Iron %, Sulphur %, etc).

In the latest EDDiscovery, when exporting my Journal/History to CSV, I can only get a "Detailed Info" which includes the materials, but not in a separate column - it's all one big multi-line string. I can't export visited systems into a column-per-material format. I tried filtering the view to only Scans but that didn't help.

Am I missing something? Did something change?

**Comment by klightspeed** [comment]
It's the Excel Export button on the Scan panel.

**Comment by soundasleep** [comment]
There it is! Thank you! :)
