### ISSUE TITLE
Typo in License Terms.

### ISSUE THREAD

**Issue by Danman1354** [EDDiscovery/EDDiscovery#2502]
Is says INARA where it's supposed to say ELITEGALAXYONLINE.COM, plus it says ELITE**R**GALAXYONLINE.COM, with an extra "R", in both instances.

"6. UPLOADING OF PLAYER DATA TO ELITE**R**GALAXYONLINE.COM. EDD offers the option to send player data to your **INARA** account.  If you enter the EGO API key into your commander details, you accept that EDD will transfer your player scan data, sourced from the journal records generated by Frontiers Elite Dangerous program, to ELITE**R**GALAXYONLINE.COM"

**Comment by robbyxp1** [comment]
Thanks, i've corrected it. Just can't get the staff now adays!

Now if only EGO would start working again..

**Comment by Danman1354** [comment]
Glad i could help. finally made an account just for this.

**Comment by robbyxp1** [comment]
Thanks for reporting.
