### ISSUE TITLE
10.6.0.0 Surveyor panel leaves gaps when items are surveyed mid-list

### ISSUE THREAD

**Issue by floatingatoll** [EDDiscovery/EDDiscovery#2505]
When surveying a large system with a bunch of interesting features, the "Hide already mapped bodies" feature does hide scanned features, but doesn't move up the entries to fill the hidden gap. Unchecking that options shows the hidden entries with an "o " in the front of them. Rechecking it hides them but still leaves the gap.

![surveyor-bug](https://user-images.githubusercontent.com/92684/58398287-2184e600-8044-11e9-8dbc-0b06037d7fa9.png)

**Comment by robbyxp1** [comment]
I've fixed this on the master, for 11.0, unfort. that's not coming out for a while.  Thanks for the report.
