### ISSUE TITLE
Sync events to EDDN

### ISSUE THREAD

**Issue by Redbird123** [EDDiscovery/EDDiscovery#2506]
Starting on April 26th Ed Discovery no longer sends events to EDDN. It has worked flawlessly in the past.   I have sync events with EDDN checked in ED Discovery.  I did a manual sync of events and then jumped 25 systems.  I ran ED Discovery and it synced with EDSM but not with EDDN.  I recently upgraded to  Ed Discovery version 10.6 but this occurred with this new version and the previous version.

**Comment by robbyxp1** [comment]
We will have a think.
