### ISSUE TITLE
10.6.0.0 Crashes on Custom Expedition

### ISSUE THREAD

**Issue by SilverHawk7** [EDDiscovery/EDDiscovery#2507]
### Description
> Trying to select custom expedition dates on 3D map.  "Custom" option at the bottom of the menu generates the below exception.

### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Value of '12/31/9999 11:59:59 PM' is not valid for 'Value'. 'Value' should be between 'MinDate' and 'MaxDate'.
>Parameter name: Value
>   at System.Windows.Forms.DateTimePicker.set_Value(DateTime value)
>   at EDDiscovery.FormMap.dropdownFilterHistory_Custom_Click(Object sender, EventArgs e, ToolStripButton sel) in C:\Code\EDDiscovery\EDDiscovery\3DMap\FormMap.cs:line 1132
>   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```
-----

**Comment by robbyxp1** [comment]
Fixed in 11.0 with a complete rework of the time/date selector. 

In the meantime, i'm afraid its out of service.

11.0 is late june.

thanks for the report.
