### ISSUE TITLE
EDDiscovery is running very slowly and is frequently freezing. 

### ISSUE THREAD

**Issue by Jaredcrue** [EDDiscovery/EDDiscovery#2508]
Version 10.6.0.0

EDDiscovery is running very slowly and is frequently freezing. 
No add ons are enabled.

I have a pretty decent system, EDDiscovery's issue doesn't impact performance with other programs (eg. Elite Dangerous.)

It might be due to having 700 journal files in the Journal folder.

**Comment by robbyxp1** [comment]
Is it doing anything with the systems database, downloading systems etc? Is it saying anything in the status line at the bottom or in the log?  Are you running on a HDD?

**Comment by Jaredcrue** [comment]
It's slow even while at idle. 
Yes, it's running on a hard drive.  

I'm going to move some of the older journal files to a separate folder to see what happens.

**Comment by Jaredcrue** [comment]
The journal files are on my ssd.
Moving files didn't help.

**Comment by iainross** [comment]
It's the location of the databases that matters more than the location of the journals.  If you used the installer and haven't moved them these will be in your Appdata folder.  You can launch EDD while holding Shift to get an option to move them, or try limiting how much is in memory with the 'Only Read Essential Entries' drop down on the settings tab.

**Comment by Jaredcrue** [comment]
ok, I changed the "Only Read Essential Entries" dropdown to ">7 days old"
Still runs about the same after restart,  I don't think it will freeze now.

**Comment by robbyxp1** [comment]
Closing, SSD is the best place to put your databases if your travels are very extensive ;-)

**Comment by Jaredcrue** [comment]
Thanks for the help.  :)

**Comment by dudeisbrendan03** [comment]
> Closing, SSD is the best place to put your databases if your travels are very extensive ;-)

SSD, same problem
