### ISSUE TITLE
Change User Profile / Commander on startup

### ISSUE THREAD

**Issue by lwt-pressy** [EDDiscovery/EDDiscovery#2510]
For DW2 a got myself a second account. To start E:D accoprdingly i set up a powersahell script which swaps profles and start all my needed tools. Is there a way to change to commander by a start parameter or an API call? If not it would be a nice feature to add.

**Comment by robbyxp1** [comment]
I'll add a command line option - good idea

**Comment by lwt-pressy** [comment]
thx, btw. a very nice tool. I probably couldn't play E:D without it anymore :)

**Comment by robbyxp1** [comment]
I've put -cmdr/-commander and -profile into the main code base.. 11.0 will have it.

**Comment by spadino** [comment]
Bravo!
