### ISSUE TITLE
unhandled UI exception when shopping list popout minimized and set to transparent/inert

### ISSUE THREAD

**Issue by Tomparkes93** [EDDiscovery/EDDiscovery#2512]
### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: SplitterDistance must be between Panel1MinSize and Width - Panel2MinSize.
>   at System.Windows.Forms.SplitContainer.set_SplitterDistance(Int32 value)
>   at System.Windows.Forms.SplitContainer.ApplyPanel1MinSize(Int32 value)
>   at System.Windows.Forms.SplitContainer.set_Panel1MinSize(Int32 value)
>   at EDDiscovery.UserControls.UserControlShoppingList.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\EngineeringSynthesis\UserControlShoppingList.cs:line 317
>   at EDDiscovery.UserControls.UserControlSynthesis.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\EngineeringSynthesis\UserControlSynthesis.cs:line 304
>   at EDDiscovery.UserControls.UserControlSynthesis.Discoveryform_OnNewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\EngineeringSynthesis\UserControlSynthesis.cs:line 183
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 447
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 434
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(Tuple`2 entries) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 186
>===== END =====
>```

**Comment by robbyxp1** [comment]
Thanks. Will be protected against in 11.0
