### ISSUE TITLE
Layout get messed when restart or change profile

### ISSUE THREAD

**Issue by spadino** [EDDiscovery/EDDiscovery#2513]
I noticed that when I restart EDD or the profile changes it can be messed, with a split half collapsed. Any one noticed the same? Already recreated user.db...

_Sent from my moto e5 plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by robbyxp1** [comment]
Any more detail - it seems to remember panel pos here.

**Comment by spadino** [comment]
It should be as that:

![image](https://user-images.githubusercontent.com/4296635/58964678-acbd5480-8785-11e9-9ed8-ca83c7c005c5.png)

**Comment by robbyxp1** [comment]
Its not doing it here .. have to think

**Comment by spadino** [comment]
Yeah, it's pretty strange. However, it's in 10.6. I didn't checked with the current master branch. I'll have a look today later...

**Comment by robbyxp1** [comment]
Any further details?

**Comment by spadino** [comment]
New build solved that. ;)

**Comment by robbyxp1** [comment]
Closed
