### ISSUE TITLE
CSV export not showing mapped values

### ISSUE THREAD

**Issue by Tomparkes93** [EDDiscovery/EDDiscovery#2514]
The CSV export triggered from a SCAN tab does not include full values for mapped planets. it only shows the estimated value for the planet as if it was not mapped. 
included is an image showing the difference between the CSV reported values, and EDDiscoveries values: https://cdn.discordapp.com/attachments/357165142430973952/585830910809735168/unknown.png

**Comment by klightspeed** [comment]
EDDiscovery fetches the events directly from the database rather than using the history list, and so the normal history processing doesn't occur.

#2515 should fix this discrepancy.
