### ISSUE TITLE
Captains Log Entry crashing if body or system is manually cleared to empty

### ISSUE THREAD

**Issue by jungfaha** [EDDiscovery/EDDiscovery#2516]
### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
>NOT NULL constraint failed: CaptainsLog.BodyName
>   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
>   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
>   at SQLLiteExtensions.SQLExtCommand`1.ExecuteNonQuery() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:line 131
>   at EliteDangerousCore.DB.CaptainsLogClass.Update(SQLiteConnectionUser cn) in C:\Code\EDDiscovery\EliteDangerous\DB\CaptainsLogClass.cs:line 122
>   at EliteDangerousCore.DB.CaptainsLogClass.Update() in C:\Code\EDDiscovery\EliteDangerous\DB\CaptainsLogClass.cs:line 104
>   at EliteDangerousCore.DB.GlobalCaptainsLogList.AddOrUpdate(CaptainsLogClass bk, Int32 commander, String systemname, String bodyname, DateTime timeutc, String notes, String tags, String parameters) in C:\Code\EDDiscovery\EliteDangerous\DB\CaptainsLogClass.cs:line 249
>   at EDDiscovery.UserControls.CaptainsLogEntries.StoreRow(DataGridViewRow rw) in C:\Code\EDDiscovery\EDDiscovery\UserControls\LogsBookmarks\CaptainsLogEntries.cs:line 323
>   at EDDiscovery.UserControls.CaptainsLogEntries.dataGridView_CellEndEdit(Object sender, DataGridViewCellEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\LogsBookmarks\CaptainsLogEntries.cs:line 272
>   at System.Windows.Forms.DataGridView.OnCellEndEdit(DataGridViewCellEventArgs e)
>   at System.Windows.Forms.DataGridView.EndEdit(DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave, Boolean keepFocus, Boolean resetCurrentCell, Boolean resetAnchorCell)
>   at System.Windows.Forms.DataGridView.SetCurrentCellAddressCore(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick)
>   at System.Windows.Forms.DataGridView.OnCellMouseDown(HitTestInfo hti, Boolean isShiftDown, Boolean isControlDown)
>   at System.Windows.Forms.DataGridView.OnCellMouseDown(DataGridViewCellMouseEventArgs e)
>   at System.Windows.Forms.DataGridView.OnMouseDown(MouseEventArgs e)
>   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.DataGridView.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
The stack trace suggests that you tried to set a body captains log entry on something that wasn't a body.

**Comment by robbyxp1** [comment]
Body cell was empty.. it needs protecting. will do.

**Comment by robbyxp1** [comment]
Fixed in 11.0 out at end of month.  In the meantime, it will only happen if you manually delete the body or star name.

thanks for the report.
