### ISSUE TITLE
Small guardian gauss missing from export

### ISSUE THREAD

**Issue by wentbackward** [EDDiscovery/EDDiscovery#2518]
Hello!
Was exporting an AX build today using the export to Coriolis in the Ship/Loadout tab. This module is missing, text and screenshot as requested in-app

Guardian Gauss Cannon Fixed Small:Hpt_guardian_gausscannon_fixed_small

![image](https://user-images.githubusercontent.com/1219178/59145823-b19b3600-8a1b-11e9-9ee5-5b0fd9add70e.png)

o7 and thanks for a great tool!

**Comment by robbyxp1** [comment]
Hi, Are you using the latest version 10.6.0. It appears to be in the 10.6.0 code base.

thanks

rob

**Comment by wentbackward** [comment]
Hi Rob ... yes 10.6.0.0, checked for updates and it says no updates founds
Regards
Paul

**Comment by wentbackward** [comment]
I had a look at the code as well, it's definitely in the 10.6 branch release. Can't see anything wrong. In the screenshot I provided, Hpt is capitalised, but presumably it's not that.

**Comment by robbyxp1** [comment]
So, its in there, in the 10.6 branch.

The case is irrelevant - because frontier was a bit random on their casing I made everything lower case.

{ "hpt_guardian_gausscannon_fixed_small", new ShipModule(0, 2, 1.91F, "Ammo:80/1, Damage:22, Range:3000m, Reload:1s, ThermL:15","Guardian Gauss Cannon Fixed Small", "Guardian")},
{ "hpt_guardian_gausscannon_fixed_medium", new ShipModule(128833687, 4, 2.61F, "Ammo:80/1, Damage:70, Range:3000m, Reload:1s, ThermL:25","Guardian Gauss Cannon Fixed Medium", "Guardian")},

In the loadout message, produced when you add/change/start up, it should list this.  If you can give the the loadout JSON (right click on loadout and use journal copy to clipboard option) I can import it into a test account i have and can debug it ;-)

rob

**Comment by wentbackward** [comment]
`{
  "timestamp": "2019-06-10T13:32:34Z",
  "event": "Loadout",
  "Ship": "typex",
  "ShipID": 41,
  "ShipName": "FLUFFY TOFFEE",
  "ShipIdent": "FLUF-T",
  "HullValue": 18611476,
  "ModulesValue": 37604196,
  "HullHealth": 1.0,
  "UnladenMass": 618.581604,
  "CargoCapacity": 32,
  "MaxJumpRange": 31.514673,
  "FuelCapacity": {
    "Main": 16.0,
    "Reserve": 0.77
  },
  "Rebuy": 2810787,
  "Modules": [
    {
      "Slot": "ShipCockpit",
      "Item": "typex_cockpit",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "LargeHardpoint1",
      "Item": "hpt_guardian_gausscannon_fixed_medium",
      "On": true,
      "Priority": 2,
      "AmmoInClip": 1,
      "AmmoInHopper": 80,
      "Health": 1.0
    },
    {
      "Slot": "LargeHardpoint2",
      "Item": "hpt_guardian_gausscannon_fixed_medium",
      "On": true,
      "Priority": 2,
      "AmmoInClip": 1,
      "AmmoInHopper": 80,
      "Health": 1.0
    },
    {
      "Slot": "MediumHardpoint1",
      "Item": "hpt_flakmortar_fixed_medium",
      "On": true,
      "Priority": 2,
      "AmmoInClip": 1,
      "AmmoInHopper": 32,
      "Health": 1.0
    },
    {
      "Slot": "SmallHardpoint1",
      "Item": "hpt_guardian_gausscannon_fixed_small",
      "On": true,
      "Priority": 2,
      "AmmoInClip": 1,
      "AmmoInHopper": 80,
      "Health": 1.0
    },
    {
      "Slot": "SmallHardpoint2",
      "Item": "hpt_guardian_gausscannon_fixed_small",
      "On": true,
      "Priority": 2,
      "AmmoInClip": 1,
      "AmmoInHopper": 80,
      "Health": 1.0
    },
    {
      "Slot": "SmallHardpoint3",
      "Item": "hpt_beamlaser_gimbal_small",
      "On": true,
      "Priority": 0,
      "Health": 1.0,
      "Engineering": {
        "Engineer": "Broo Tarquin",
        "EngineerID": 300030,
        "BlueprintID": 128673339,
        "BlueprintName": "Weapon_LongRange",
        "Level": 5,
        "Quality": 1.0,
        "ExperimentalEffect": "special_thermal_vent",
        "ExperimentalEffect_Localised": "Thermal Vent",
        "Modifiers": [
          {
            "Label": "Mass",
            "Value": 2.6,
            "OriginalValue": 2.0,
            "LessIsGood": 1
          },
          {
            "Label": "PowerDraw",
            "Value": 0.69,
            "OriginalValue": 0.6,
            "LessIsGood": 1
          },
          {
            "Label": "MaximumRange",
            "Value": 6000.0,
            "OriginalValue": 3000.0,
            "LessIsGood": 0
          },
          {
            "Label": "DamageFalloffRange",
            "Value": 6000.0,
            "OriginalValue": 600.0,
            "LessIsGood": 0
          }
        ]
      }
    },
    {
      "Slot": "TinyHardpoint1",
      "Item": "hpt_heatsinklauncher_turret_tiny",
      "On": true,
      "Priority": 1,
      "AmmoInClip": 1,
      "AmmoInHopper": 3,
      "Health": 1.0,
      "Engineering": {
        "Engineer": "Ram Tah",
        "EngineerID": 300110,
        "BlueprintID": 128731666,
        "BlueprintName": "Misc_HeatSinkCapacity",
        "Level": 1,
        "Quality": 1.0,
        "Modifiers": [
          {
            "Label": "Mass",
            "Value": 2.6,
            "OriginalValue": 1.3,
            "LessIsGood": 1
          },
          {
            "Label": "AmmoMaximum",
            "Value": 3.0,
            "OriginalValue": 2.0,
            "LessIsGood": 0
          },
          {
            "Label": "ReloadTime",
            "Value": 15.0,
            "OriginalValue": 10.0,
            "LessIsGood": 1
          }
        ]
      }
    },
    {
      "Slot": "TinyHardpoint2",
      "Item": "hpt_heatsinklauncher_turret_tiny",
      "On": true,
      "Priority": 1,
      "AmmoInClip": 1,
      "AmmoInHopper": 3,
      "Health": 1.0,
      "Engineering": {
        "Engineer": "Ram Tah",
        "EngineerID": 300110,
        "BlueprintID": 128731666,
        "BlueprintName": "Misc_HeatSinkCapacity",
        "Level": 1,
        "Quality": 1.0,
        "Modifiers": [
          {
            "Label": "Mass",
            "Value": 2.6,
            "OriginalValue": 1.3,
            "LessIsGood": 1
          },
          {
            "Label": "AmmoMaximum",
            "Value": 3.0,
            "OriginalValue": 2.0,
            "LessIsGood": 0
          },
          {
            "Label": "ReloadTime",
            "Value": 15.0,
            "OriginalValue": 10.0,
            "LessIsGood": 1
          }
        ]
      }
    },
    {
      "Slot": "TinyHardpoint3",
      "Item": "hpt_heatsinklauncher_turret_tiny",
      "On": true,
      "Priority": 1,
      "AmmoInClip": 1,
      "AmmoInHopper": 3,
      "Health": 1.0,
      "Engineering": {
        "Engineer": "Ram Tah",
        "EngineerID": 300110,
        "BlueprintID": 128731666,
        "BlueprintName": "Misc_HeatSinkCapacity",
        "Level": 1,
        "Quality": 1.0,
        "Modifiers": [
          {
            "Label": "Mass",
            "Value": 2.6,
            "OriginalValue": 1.3,
            "LessIsGood": 1
          },
          {
            "Label": "AmmoMaximum",
            "Value": 3.0,
            "OriginalValue": 2.0,
            "LessIsGood": 0
          },
          {
            "Label": "ReloadTime",
            "Value": 15.0,
            "OriginalValue": 10.0,
            "LessIsGood": 1
          }
        ]
      }
    },
    {
      "Slot": "TinyHardpoint4",
      "Item": "hpt_heatsinklauncher_turret_tiny",
      "On": true,
      "Priority": 1,
      "AmmoInClip": 1,
      "AmmoInHopper": 3,
      "Health": 1.0,
      "Engineering": {
        "Engineer": "Ram Tah",
        "EngineerID": 300110,
        "BlueprintID": 128731666,
        "BlueprintName": "Misc_HeatSinkCapacity",
        "Level": 1,
        "Quality": 1.0,
        "Modifiers": [
          {
            "Label": "Mass",
            "Value": 2.6,
            "OriginalValue": 1.3,
            "LessIsGood": 1
          },
          {
            "Label": "AmmoMaximum",
            "Value": 3.0,
            "OriginalValue": 2.0,
            "LessIsGood": 0
          },
          {
            "Label": "ReloadTime",
            "Value": 15.0,
            "OriginalValue": 10.0,
            "LessIsGood": 1
          }
        ]
      }
    },
    {
      "Slot": "CargoHatch",
      "Item": "modularcargobaydoor",
      "On": false,
      "Priority": 3,
      "Health": 1.0
    },
    {
      "Slot": "PaintJob",
      "Item": "paintjob_typex_military_tactical_white",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "Armour",
      "Item": "typex_armour_grade1",
      "On": true,
      "Priority": 1,
      "Health": 1.0,
      "Engineering": {
        "Engineer": "Selene Jean",
        "EngineerID": 300210,
        "BlueprintID": 128673644,
        "BlueprintName": "Armour_HeavyDuty",
        "Level": 5,
        "Quality": 1.0,
        "ExperimentalEffect": "special_armour_chunky",
        "ExperimentalEffect_Localised": "Deep Plating",
        "Modifiers": [
          {
            "Label": "DefenceModifierHealthMultiplier",
            "Value": 156.608002,
            "OriginalValue": 79.999992,
            "LessIsGood": 0
          },
          {
            "Label": "KineticResistance",
            "Value": -17.419994,
            "OriginalValue": -20.000004,
            "LessIsGood": 0
          },
          {
            "Label": "ThermicResistance",
            "Value": 2.150005,
            "OriginalValue": 0.0,
            "LessIsGood": 0
          },
          {
            "Label": "ExplosiveResistance",
            "Value": -36.989986,
            "OriginalValue": -39.999996,
            "LessIsGood": 0
          }
        ]
      }
    },
    {
      "Slot": "PowerPlant",
      "Item": "int_powerplant_size6_class5",
      "On": true,
      "Priority": 1,
      "Health": 1.0,
      "Engineering": {
        "Engineer": "Hera Tani",
        "EngineerID": 300090,
        "BlueprintID": 128673764,
        "BlueprintName": "PowerPlant_Armoured",
        "Level": 5,
        "Quality": 1.0,
        "ExperimentalEffect": "special_powerplant_cooled",
        "ExperimentalEffect_Localised": "Thermal Spread",
        "Modifiers": [
          {
            "Label": "Mass",
            "Value": 24.0,
            "OriginalValue": 20.0,
            "LessIsGood": 1
          },
          {
            "Label": "Integrity",
            "Value": 272.800018,
            "OriginalValue": 124.0,
            "LessIsGood": 0
          },
          {
            "Label": "PowerCapacity",
            "Value": 28.224001,
            "OriginalValue": 25.200001,
            "LessIsGood": 0
          },
          {
            "Label": "HeatEfficiency",
            "Value": 0.3168,
            "OriginalValue": 0.4,
            "LessIsGood": 1
          }
        ]
      }
    },
    {
      "Slot": "MainEngines",
      "Item": "int_engine_size6_class5",
      "On": true,
      "Priority": 0,
      "Health": 1.0,
      "Engineering": {
        "Engineer": "Professor Palin",
        "EngineerID": 300220,
        "BlueprintID": 128673659,
        "BlueprintName": "Engine_Dirty",
        "Level": 5,
        "Quality": 0.94,
        "ExperimentalEffect": "special_engine_overloaded",
        "ExperimentalEffect_Localised": "Drag Drives",
        "Modifiers": [
          {
            "Label": "Integrity",
            "Value": 105.400002,
            "OriginalValue": 124.0,
            "LessIsGood": 0
          },
          {
            "Label": "PowerDraw",
            "Value": 8.4672,
            "OriginalValue": 7.56,
            "LessIsGood": 1
          },
          {
            "Label": "EngineOptimalMass",
            "Value": 1260.0,
            "OriginalValue": 1440.0,
            "LessIsGood": 0
          },
          {
            "Label": "EngineOptPerformance",
            "Value": 145.163193,
            "OriginalValue": 100.0,
            "LessIsGood": 0
          },
          {
            "Label": "EngineHeatRate",
            "Value": 2.288,
            "OriginalValue": 1.3,
            "LessIsGood": 1
          }
        ]
      }
    },
    {
      "Slot": "FrameShiftDrive",
      "Item": "int_hyperdrive_size5_class5",
      "On": true,
      "Priority": 1,
      "Health": 1.0,
      "Engineering": {
        "Engineer": "Felicity Farseer",
        "EngineerID": 300100,
        "BlueprintID": 128673694,
        "BlueprintName": "FSD_LongRange",
        "Level": 5,
        "Quality": 0.842,
        "ExperimentalEffect": "special_fsd_heavy",
        "ExperimentalEffect_Localised": "Mass Manager",
        "Modifiers": [
          {
            "Label": "Mass",
            "Value": 26.0,
            "OriginalValue": 20.0,
            "LessIsGood": 1
          },
          {
            "Label": "Integrity",
            "Value": 93.840004,
            "OriginalValue": 120.0,
            "LessIsGood": 0
          },
          {
            "Label": "PowerDraw",
            "Value": 0.69,
            "OriginalValue": 0.6,
            "LessIsGood": 1
          },
          {
            "Label": "FSDOptimalMass",
            "Value": 1675.346191,
            "OriginalValue": 1050.0,
            "LessIsGood": 0
          }
        ]
      }
    },
    {
      "Slot": "LifeSupport",
      "Item": "int_lifesupport_size5_class2",
      "On": true,
      "Priority": 0,
      "Health": 1.0,
      "Engineering": {
        "Engineer": "Lori Jameson",
        "EngineerID": 300230,
        "BlueprintID": 128731494,
        "BlueprintName": "Misc_LightWeight",
        "Level": 4,
        "Quality": 0.773,
        "Modifiers": [
          {
            "Label": "Mass",
            "Value": 2.1816,
            "OriginalValue": 8.0,
            "LessIsGood": 1
          },
          {
            "Label": "Integrity",
            "Value": 51.600002,
            "OriginalValue": 86.0,
            "LessIsGood": 0
          }
        ]
      }
    },
    {
      "Slot": "PowerDistributor",
      "Item": "int_powerdistributor_size6_class5",
      "On": true,
      "Priority": 0,
      "Health": 1.0,
      "Engineering": {
        "Engineer": "The Dweller",
        "EngineerID": 300180,
        "BlueprintID": 128673739,
        "BlueprintName": "PowerDistributor_HighFrequency",
        "Level": 5,
        "Quality": 0.8156,
        "ExperimentalEffect": "special_powerdistributor_fast",
        "ExperimentalEffect_Localised": "Super Conduits",
        "Modifiers": [
          {
            "Label": "WeaponsCapacity",
            "Value": 45.599998,
            "OriginalValue": 50.0,
            "LessIsGood": 0
          },
          {
            "Label": "WeaponsRecharge",
            "Value": 7.751827,
            "OriginalValue": 5.2,
            "LessIsGood": 0
          },
          {
            "Label": "EnginesCapacity",
            "Value": 31.92,
            "OriginalValue": 35.0,
            "LessIsGood": 0
          },
          {
            "Label": "EnginesRecharge",
            "Value": 4.770355,
            "OriginalValue": 3.2,
            "LessIsGood": 0
          },
          {
            "Label": "SystemsCapacity",
            "Value": 31.92,
            "OriginalValue": 35.0,
            "LessIsGood": 0
          },
          {
            "Label": "SystemsRecharge",
            "Value": 4.770355,
            "OriginalValue": 3.2,
            "LessIsGood": 0
          }
        ]
      }
    },
    {
      "Slot": "Radar",
      "Item": "int_sensors_size4_class2",
      "On": true,
      "Priority": 1,
      "Health": 1.0,
      "Engineering": {
        "Engineer": "Juri Ishmaak",
        "EngineerID": 300250,
        "BlueprintID": 128740136,
        "BlueprintName": "Sensor_LongRange",
        "Level": 5,
        "Quality": 0.9427,
        "Modifiers": [
          {
            "Label": "Mass",
            "Value": 8.0,
            "OriginalValue": 4.0,
            "LessIsGood": 1
          },
          {
            "Label": "SensorTargetScanAngle",
            "Value": 21.0,
            "OriginalValue": 30.0,
            "LessIsGood": 0
          },
          {
            "Label": "Range",
            "Value": 8776.65625,
            "OriginalValue": 5040.0,
            "LessIsGood": 0
          }
        ]
      }
    },
    {
      "Slot": "FuelTank",
      "Item": "int_fueltank_size4_class3",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "Slot01_Size6",
      "Item": "int_cargorack_size5_class1",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "Slot02_Size5",
      "Item": "int_dronecontrol_repair_size5_class2",
      "On": true,
      "Priority": 0,
      "Health": 1.0
    },
    {
      "Slot": "Slot03_Size4",
      "Item": "int_guardianmodulereinforcement_size4_class2",
      "On": true,
      "Priority": 0,
      "Health": 1.0
    },
    {
      "Slot": "Slot04_Size2",
      "Item": "int_guardianhullreinforcement_size2_class2",
      "On": true,
      "Priority": 0,
      "Health": 1.0
    },
    {
      "Slot": "Slot05_Size2",
      "Item": "int_repairer_size2_class5",
      "On": true,
      "Priority": 4,
      "Health": 1.0
    },
    {
      "Slot": "Slot06_Size1",
      "Item": "int_guardianhullreinforcement_size1_class2",
      "On": true,
      "Priority": 0,
      "Health": 1.0
    },
    {
      "Slot": "Military01",
      "Item": "int_guardianhullreinforcement_size4_class2",
      "On": true,
      "Priority": 0,
      "Health": 1.0
    },
    {
      "Slot": "Military02",
      "Item": "int_hullreinforcement_size4_class2",
      "On": true,
      "Priority": 1,
      "Health": 1.0,
      "Engineering": {
        "Engineer": "Selene Jean",
        "EngineerID": 300210,
        "BlueprintID": 128673719,
        "BlueprintName": "HullReinforcement_HeavyDuty",
        "Level": 5,
        "Quality": 1.0,
        "ExperimentalEffect": "special_hullreinforcement_chunky",
        "ExperimentalEffect_Localised": "Deep Plating",
        "Modifiers": [
          {
            "Label": "Mass",
            "Value": 11.2,
            "OriginalValue": 8.0,
            "LessIsGood": 1
          },
          {
            "Label": "DefenceModifierHealthAddition",
            "Value": 624.360046,
            "OriginalValue": 330.0,
            "LessIsGood": 0
          },
          {
            "Label": "KineticResistance",
            "Value": 15.033997,
            "OriginalValue": 1.999998,
            "LessIsGood": 0
          },
          {
            "Label": "ThermicResistance",
            "Value": 15.033997,
            "OriginalValue": 1.999998,
            "LessIsGood": 0
          },
          {
            "Label": "ExplosiveResistance",
            "Value": 15.033997,
            "OriginalValue": 1.999998,
            "LessIsGood": 0
          }
        ]
      }
    },
    {
      "Slot": "Military03",
      "Item": "int_hullreinforcement_size4_class2",
      "On": true,
      "Priority": 1,
      "Health": 1.0,
      "Engineering": {
        "Engineer": "Selene Jean",
        "EngineerID": 300210,
        "BlueprintID": 128673719,
        "BlueprintName": "HullReinforcement_HeavyDuty",
        "Level": 5,
        "Quality": 1.0,
        "ExperimentalEffect": "special_hullreinforcement_chunky",
        "ExperimentalEffect_Localised": "Deep Plating",
        "Modifiers": [
          {
            "Label": "Mass",
            "Value": 11.2,
            "OriginalValue": 8.0,
            "LessIsGood": 1
          },
          {
            "Label": "DefenceModifierHealthAddition",
            "Value": 624.360046,
            "OriginalValue": 330.0,
            "LessIsGood": 0
          },
          {
            "Label": "KineticResistance",
            "Value": 15.033997,
            "OriginalValue": 1.999998,
            "LessIsGood": 0
          },
          {
            "Label": "ThermicResistance",
            "Value": 15.033997,
            "OriginalValue": 1.999998,
            "LessIsGood": 0
          },
          {
            "Label": "ExplosiveResistance",
            "Value": 15.033997,
            "OriginalValue": 1.999998,
            "LessIsGood": 0
          }
        ]
      }
    },
    {
      "Slot": "PlanetaryApproachSuite",
      "Item": "int_planetapproachsuite",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "Bobble05",
      "Item": "bobble_textcaret",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "Bobble06",
      "Item": "bobble_textcaret",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "WeaponColour",
      "Item": "weaponcustomisation_red",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "EngineColour",
      "Item": "enginecustomisation_red",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    },
    {
      "Slot": "VesselVoice",
      "Item": "voicepack_verity",
      "On": true,
      "Priority": 1,
      "Health": 1.0
    }
  ]
}`

**Comment by wentbackward** [comment]
Pasted the journal entry, hope that's ok .. also another thing I tried the export to coriolis ... same error ... tried on edshipyard and it didn't give an error!

**Comment by robbyxp1** [comment]
Found at last - been v.busy. Thanks for the report. 11.0 will have it fixed.
