### ISSUE TITLE
Unhandled Fatal Error on startup v10.5.4

### ISSUE THREAD

**Issue by TonyFlury** [EDDiscovery/EDDiscovery#2519]
I have just got an Unhandled fatal exception when starting EDD 10.5.4: 
### Description
Starting EDD either in normal mode, or using the rebuild data bases option in Safe Mode.

### Exception Details:
>EDDiscovery v10.5.4.0 An unhandled fatal exception has occurred.
>```
>==== BEGIN ====
>System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
>   at Newtonsoft.Json.JsonTextReader..ctor(TextReader reader)
>   at EliteDangerousCore.EDCommander.Load(Boolean write, SQLiteConnectionUser conn) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDCommander.cs:line 328
>   at EDDiscovery.EDDConfig.Update(Boolean write, SQLiteConnectionUser conn) in C:\Code\EDDiscovery\EDDiscovery\EDDConfig.cs:line 414
>   at EDDiscovery.EDDiscoveryController.Initialize(Action`1 msg) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 151
>   at EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:line 137
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
>   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
>   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
>   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
>   at EDDiscovery.Program.Main() in C:\Code\EDDiscovery\EDDiscovery\Program.cs:line 47
>===== END =====
>```

**Comment by klightspeed** [comment]
That is a very odd exception to get at that point - completely external to the flow of the program.  Basically an uncaught native exception in pure managed code.

Does the latest version (v10.6.0) give the same exception?

**Comment by robbyxp1** [comment]
Isn't that the part that's reading the CommandersPaths.Json file?  Maybe its corrupted. Its not protected from bad JSON.

Remind me why this is in there (the idea is very old).. Can we remove this bit of code now?  We provide configuration of journal directories in other way now.

**Comment by klightspeed** [comment]
The exception is occurring during the construction of the `JsonTextReader` instance that is used to read the json.
https://github.com/EDDiscovery/EDDiscovery/blob/8a41f956cd41c50b6d951e8a06c0221c7e80aba2/EliteDangerous/EliteDangerous/EDCommander.cs#L328-L331

I think this is the first time the program creates a `JsonTextReader`, suggesting that the NGen'd code for the library is somehow corrupt, or the copy of the Newtonsoft.Json dll that is being used is calling native C++ code that isn't in the Json.NET source.
https://github.com/JamesNK/Newtonsoft.Json/blob/c4af75c8e91ca0d75aa6c335e8c106780c4f7712/Src/Newtonsoft.Json/JsonTextReader.cs#L83-L96

**Comment by robbyxp1** [comment]
Closing due to age.
