### ISSUE TITLE
Database corruption in 10.6.0.0

### ISSUE THREAD

**Issue by xenophonf** [EDDiscovery/EDDiscovery#2525]
### Description
I play on two computers.  In order to keep them in sync, I use Syncthing to replicate the `Saved Games` and `%LocalAppData%\EDDiscovery` folders.  For the EDDiscovery folder, I configured Syncthing to exclude `EDDSystem.sqlite` because of its size.  Recently, on one of the computers, EDDiscovery has begun reporting the error "Processing EDSM systems download failed, will try next time program is run" in the log window on the lower right.  Restarting EDDiscovery results in the same error.  I tried fixing it by clicking the option to "Fetch star data again".  At some point during that process, I began getting this exception.  I am unable to start EDDiscovery because it throws the exception immediately

### Additional Information
Deleting `EDDSystem.sqlite` seemed to fix this problem, but I don't know what caused it in the first place.

### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Corrupt (11), message = System.Data.SQLite.SQLiteException (0x800007EF): database disk image is malformed
>database disk image is malformed
>   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
>   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at SQLLiteExtensions.SQLExtDataReader`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLExtTransaction`1 txn, SQLExtTransactionLock`1 txnlock) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLReader.cs:line 38
>   at SQLLiteExtensions.SQLExtCommand`1.ExecuteDbDataReader(CommandBehavior behavior) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:line 92
>   at EliteDangerousCore.DB.SystemClassDB.GetEdsmIdsFromName(String name, SQLiteConnectionSystem cn, Boolean uselike) in C:\Code\EDDiscovery\EliteDangerous\DB\SystemClassDB.cs:line 276
>   at EliteDangerousCore.DB.SystemClassDB.GetSystemsByName(String name, SQLiteConnectionSystem cn, Boolean uselike) in C:\Code\EDDiscovery\EliteDangerous\DB\SystemClassDB.cs:line 301
>   at EliteDangerousCore.SystemCache.FindSystem(ISystem find, SQLiteConnectionSystem conn) in C:\Code\EDDiscovery\EliteDangerous\DB\SystemCache.cs:line 79
>   at EliteDangerousCore.HistoryList.FillEDSM(HistoryEntry syspos) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 575
>   at EDDiscovery.UserControls.UserControlSysInfo.Display(HistoryEntry he, HistoryList hl, Boolean selectedEntry) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSysInfo.cs:line 197
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl, Boolean selectedEntry)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 546
>   at EDDiscovery.UserControls.UserControlTravelGrid.AddNewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 442
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 447
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 434
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(Tuple`2 entries) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 186
>===== END =====
>```

**Comment by klightspeed** [comment]
Please try deleting EDDSystem.sqlite - it will be rebuild on the next run.

**Comment by xenophonf** [comment]
Thank you.  Deleting the database fixed my problem.

**Comment by septagram** [comment]
Happened twice to me recently. Last time directly after an update today, version 12.0.2.0. Would be really cool if it could delete the DB automatically, without the need for googling.

**Comment by septagram** [comment]
And now it happened again, literally a few hours later.

**Comment by Eahlstan** [comment]
Well listen. This is a free project and everyone here has jo problem with helping people and fixing bugs. But if you don't provide any info and keep talking like you do the chance that anyone will look into this isn't big.
So please open a new issue, describe exactly what you did and please be more polite.
