### ISSUE TITLE
Disabling or Set to Manual EDSM Syncing

### ISSUE THREAD

**Issue by bWildcard** [EDDiscovery/EDDiscovery#2529]
So this is getting abit annoying Everytime I open ED Discovery it has to sit there for upwards of 10minutes while I just Chews up my internet bandwidth while syncing to EDSM 
![image](https://user-images.githubusercontent.com/43270488/60762100-c91b0e00-a01d-11e9-847b-7266d4629b2a.png)

There needs to be an opiton to either turn this off, Stop It, disable it on startup, or set it to manual update only. 

Its not even updating anything so whats the point of this thing doing this every time EDDiscovery starts?

**Comment by klightspeed** [comment]
Settings tab, disable EDSM star download.

**Comment by robbyxp1** [comment]
Closing as answered, thanks.
