### ISSUE TITLE
stuck on replacing old systems table with new systems table and re-indexing

### ISSUE THREAD

**Issue by Daelmaron** [EDDiscovery/EDDiscovery#2532]
My EDDiscovery has been stuck on the step where the banner at the bottom says "Replacing old systems table with new systems table and re-indexing - please wait" for the last 8 hours and it has made no progress and the entire program is locked down and not responding to any input

**Comment by klightspeed** [comment]
Are you running it on a slow HDD?
Is the program accessing the disk?  If not, it sounds like there was a deadlock.

**Comment by Daelmaron** [comment]
running it on a prebuilt gaming laptop, the HDD isn't slow, though I've only got the one and according to task manager its accessing properly.

**Comment by klightspeed** [comment]
Indexing the systems database seeks a lot, and is likely to perform poorly on a HDD (rather than an SSD).

My only suggestion would be to terminate EDDiscovery, delete EDDSystems.sqlite, then restart it, and select the option to not download any systems.

**Comment by robbyxp1** [comment]
Closing, as q. answered
