### ISSUE TITLE
Missing Horizons Flag when sending Shipyard and Outfitting data to EDDN

### ISSUE THREAD

**Issue by aaaabcv** [EDDiscovery/EDDiscovery#2533]
Although Optional, schemas for outfitting and shipyard data in EDDN have a horizons boolean flag indicating whether the data has come from a player having horizons season pass or not. 
A client interpreting EDDN data can thus know if certain modules and ships being unavailable due to the market or due to the player not having access to these modules or ships.
It would be good to send this information to give message consumers that information.

**Comment by klightspeed** [comment]
Basically take the `Horizons` flag from the most recent `LoadGame` event, and add it to the `https://eddn.edcd.io/schemas/commodity/3` message when processing the `Market` event?

**Comment by aaaabcv** [comment]
Yes, that's one possibility. The horizons flag is also present in the shipyard.json and outfitting.json files if the appropriate menus in game are accessed.

**Comment by robbyxp1** [comment]
Fixed for 11.0
