### ISSUE TITLE
Move Database Option Should Move the ENITRE Application Data Folder

### ISSUE THREAD

**Issue by mikeloeven** [EDDiscovery/EDDiscovery#2535]
I figured move databases would move all the large files to another drive however it only moved a few small database files while the app data folder continued to balloon in size with what I assume was map data. Please set the move database option to move the entire app data folder or provide an additional option specify an alternate location for the app data folder. Right now I am offloading it to another drive using a junction which is a sub optimal way to do it because while it does move the data off of C: it still uses disk bandwidth as it needs to first query the junction on C: before being redirected to the second drive resulting in the system drive still getting hit with the high IOPS

**Comment by mikeloeven** [comment]
Okay Looks like i was mistaken the bulk of data is being written to the database files however there are several json files remaining in appdata not entirely sure what these do but i suspect its a temp storage for raw data downloaded via the various API's which can reach several gigs in size

**Comment by klightspeed** [comment]
You can use one of the following methods:
* Add `AppFolder path/to/desired/directory` to an options.txt file in the program directory
* Add `-AppFolder path/to/desired/directory` to the commandline in the program shortcut

**Comment by robbyxp1** [comment]
Hopefully your using 10.6, which cleans up most of those really large json files.

You can also use the portable version of EDD which stored the data in a subfolder underneath the place you installed it in.

Thanks
