### ISSUE TITLE
Feature Request:  System faction reputation logging/search

### ISSUE THREAD

**Issue by radioactiv** [EDDiscovery/EDDiscovery#2536]
It would be useful for selecting missions if a CMDR could look up their reputation with the faction in the target system.  Example: If one knew a faction is hostile in a given system, they may not pick a cargo delivery to that system.

**Comment by robbyxp1** [comment]
So, are you talking about looking up say the reputation from a system you have already visited.  We get reputation information per faction on each FSDJump.  So we could present a search on that..

Obv. that is historical data, and may not be the most up to date view Elite has on your reputation..
