### ISSUE TITLE
issue report

### ISSUE THREAD

**Issue by mrquimp** [EDDiscovery/EDDiscovery#2537]
### Description
got this error while setting tabs

### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: No room is available to display rows.
>   at System.Windows.Forms.DataGridView.set_FirstDisplayedScrollingRowIndex(Int32 value)
>   at ExtendedControls.ExtPanelDataGridViewScroll.MoveDGVToRow(Int32 rowindex) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\PanelDataGridViewScroll.cs:line 299
>   at ExtendedControls.ExtPanelDataGridViewScroll.Wheel(Object sender, MouseEventArgs e) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\PanelDataGridViewScroll.cs:line 282
>   at System.Windows.Forms.Control.OnMouseWheel(MouseEventArgs e)
>   at System.Windows.Forms.DataGridView.OnMouseWheel(MouseEventArgs e)
>   at System.Windows.Forms.Control.WmMouseWheel(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Thanks.. will try to reproduce.

**Comment by robbyxp1** [comment]
Found, patched for 11.0. Thanks
