### ISSUE TITLE
History not loading

### ISSUE THREAD

**Issue by RunnerTK** [EDDiscovery/EDDiscovery#2539]
Maybe I´m too dumb but I have Problems with the history…
I´ve installed EDDiscovery 10.6.0.0 a couple of days before and everything worked fine, but the next day I hit the "Refresh the History" button and Nothing happend, then I´ve uninstalled EDDiscovery, installed it again and it worked again, but the very next day the refresh button stopped working again. 
API, Cmdr names and the path to the log are correct

**Comment by klightspeed** [comment]
Please make sure the journal directory points at the journal directory (default `%USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous`) and not at the netlog directory.

**Comment by RunnerTK** [comment]
Thanks a lot, it seems to work now!
