### ISSUE TITLE
Log events do not appear to be sent to edsm unless the manual sync button is pressed?

### ISSUE THREAD

**Issue by mikeloeven** [EDDiscovery/EDDiscovery#2540]
EDSM is showing data very far out of date with EDDiscovery it seems as though its only syncing log data when i manually click the send unsynced events to EDSM button I would prefer to have this done automatically however I cannot locate any options to determine if and how often automatic syncing can occur.

**Comment by klightspeed** [comment]
Is `Sync to EDSM` checked in the commander settings (settings tab, click commander, edit)

**Comment by robbyxp1** [comment]
Closing, no reply
