### ISSUE TITLE
[Feature Request] Filter in scan panel

### ISSUE THREAD

**Issue by sdfg2** [EDDiscovery/EDDiscovery#2541]
I love EDD so so much.  It makes things much much easier for a hardcore explorer like me.

I have one request though - can we get a filtering mechanism in the scan panel?  That way I could have a pop-out with just important bodies (unscanned high value targets, or bodies with materials that I'm looking for).

**Comment by robbyxp1** [comment]
Thats a lot of UI to do, i'll have a think how to do something like that.

**Comment by spadino** [comment]
You can use surveyor popup by now. It allow you to show only valuables bodies, and it is quite unobstrusive. It's the way it was intended to be used, when I coded that...

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by sdfg2** [comment]
Ah!  I didn't realise you could filter the surveyor.  I guess the Scan panel is more a summary, and surveyor/shopping list etc actually uses that data.

Could you add the system name and estimated value of the scan data to the surveyor header like it is in the scan header?  At the moment I've got a scan pop out shrunk down just to show that information heh.  

Also as a complete aside, is there a way to get the total estimates scan value for data collected since last dock?  EDSM has a field for that, but it's nothing like what it should be.

**Comment by robbyxp1** [comment]
The stats panel can give that data.  

I think i could easily add a drop down check box filter on the scan panel to say 'don't show planet type X'..  I'll have a think.

**Comment by sdfg2** [comment]
What's the stats panel?

The filters on the surveyor are very useful, maybe combine surveyor/scan panel together and offer a text or graphic representation or something?
