### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Uhlersoth1** [EDDiscovery/EDDiscovery#2542]
Was happily mapping in the black, mapped a planet, EDD shows it's not mapped, click onto EDD and I get a fatal exception. Now won't launch. Appears to be a SQL error/corrupt?

Code below..

### Exception Details:
>EDDiscovery v10.6.0.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>code = CantOpen (14), message = System.Data.SQLite.SQLiteException (0x800007FF): unable to open database file
>   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
>   at System.Data.SQLite.SQLiteConnection.Open()
>   at SQLLiteExtensions.SQLExtConnectionWithLock`1..ctor(String dbfile, Boolean utctimeindicator, Action initializercallback, AccessMode mode) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnectionLock.cs:line 81
>   at EliteDangerousCore.DB.SQLiteConnectionUser.<>c.<Initialize>b__4_0() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionUser.cs:line 46
>   at SQLLiteExtensions.SQLExtConnectionWithLock`1.InitializeIfNeeded(Action initializer) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnectionLock.cs:line 189
>   at EDDiscovery.EDDiscoveryController.InitializeDatabases() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 383
>   at EDDiscovery.EDDiscoveryController.Initialize(Action`1 msg) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 139
>   at EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:line 137
>===== END =====
>```

**Comment by klightspeed** [comment]
Would it please be possible to get the trace log from when the initial error occurred?

**Comment by Uhlersoth1** [comment]
Im sure it would if I had any idea where it is found...
It seems to be back up and working again now, after a couple of hours which was odd.

Let me know where the file is and it is all yours (or what it is called and I'll go look for it)


-----Original Message-----

**Comment by klightspeed** [comment]
Would you happen to have moved the database to e.g. Google Drive or OneDrive, and that happened to be offline when the error occurred?

The trace logs are in `%LOCALAPPDATA%\EDDiscovery\Log`

**Comment by Uhlersoth1** [comment]
Nope, I don't use cloud storage for anything.
Please find attached all log files from 17th July.

I had to add a .txt suffix to the hlog file as otherwise useless AOL wouldn't send it.
Kind regards.

-----Original Message-----

**Comment by klightspeed** [comment]
It looks like Github doesn't process email attachments properly.

Please visit the issues page and add the trace log (not the hlog).

**Comment by Uhlersoth1** [comment]
[Trace_2019-07-17-17-29-55.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3413318/Trace_2019-07-17-17-29-55.0.log)
[Trace_2019-07-17-18-03-48.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3413319/Trace_2019-07-17-18-03-48.0.log)
[Trace_2019-07-17-19-45-34.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3413320/Trace_2019-07-17-19-45-34.0.log)
[Trace_2019-07-17-17-29-36.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3413321/Trace_2019-07-17-17-29-36.0.log)

**Comment by Uhlersoth1** [comment]
I believe the two timed at 17.29 are the original crash and attempt to restart. The 18.03 is after a reboot of the game etc and the 1945 is either after a computer restart or is the successful launch of ED.

**Comment by klightspeed** [comment]
```
[2019-07-17T16:29:37.043Z] SQLite error (14): os_win.c:44845: (3) winOpen(E:\ED Discovery\EDDUser.sqlite) - The system cannot find the path specified.
```

This suggests that the drive disappeared.

**Comment by Uhlersoth1** [comment]
Well, indeed. I did read that, however it would be a neat trick as the drive is ever present in the machine.
Maybe it just dropped off for a nap for some reason.
Glad it's not a bug.
Thanks.


-----Original Message-----
