### ISSUE TITLE
scan issue

### ISSUE THREAD

**Issue by mrquimp** [EDDiscovery/EDDiscovery#2543]
### Description
searchinf for scan in transparent pop up window

### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.ScanDisplayControl.CreateMaterialNodes(List`1 pc, JournalScan sn, MaterialCommoditiesList curmats, HistoryList hl, Point matpos, Size matsize) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplay.cs:line 476
>   at EDDiscovery.UserControls.ScanDisplayControl.DrawNode(List`1 pc, ScanNode sn, MaterialCommoditiesList curmats, HistoryList hl, Image notscanned, Point curpos, Size size, Int32& offset, Boolean aligndown, Int32 labelvoff, Boolean toplevel) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplay.cs:line 397
>   at EDDiscovery.UserControls.ScanDisplayControl.CreatePlanetTree(List`1 pc, ScanNode planetnode, MaterialCommoditiesList curmats, HistoryList hl, Point curpos) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplay.cs:line 219
>   at EDDiscovery.UserControls.ScanDisplayControl.DrawSystem(SystemNode last_sn, MaterialCommoditiesList curmats, HistoryList hl, String opttext) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplay.cs:line 163
>   at EDDiscovery.UserControls.UserControlScan.DrawSystem() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:line 194
>   at EDDiscovery.UserControls.UserControlScan.extCheckBoxStar_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:line 235
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by mrquimp** [comment]
First time I clicked to filter out maxed cap. materials and got that error.
After restart. Error when I search for same scan log again. 
### Description


### Additional Information


### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.ScanDisplayControl.CreateMaterialNodes(List`1 pc, JournalScan sn, MaterialCommoditiesList curmats, HistoryList hl, Point matpos, Size matsize) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplay.cs:line 476
>   at EDDiscovery.UserControls.ScanDisplayControl.DrawNode(List`1 pc, ScanNode sn, MaterialCommoditiesList curmats, HistoryList hl, Image notscanned, Point curpos, Size size, Int32& offset, Boolean aligndown, Int32 labelvoff, Boolean toplevel) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplay.cs:line 397
>   at EDDiscovery.UserControls.ScanDisplayControl.CreatePlanetTree(List`1 pc, ScanNode planetnode, MaterialCommoditiesList curmats, HistoryList hl, Point curpos) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplay.cs:line 219
>   at EDDiscovery.UserControls.ScanDisplayControl.DrawSystem(SystemNode last_sn, MaterialCommoditiesList curmats, HistoryList hl, String opttext) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplay.cs:line 163
>   at EDDiscovery.UserControls.UserControlScan.DrawSystem() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:line 194
>   at EDDiscovery.UserControls.UserControlScan.extCheckBoxStar_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:line 235
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
ack. will investigate.

**Comment by robbyxp1** [comment]
Speculative fix to more fully protected the test in EDDForm.  

Thanks.
