### ISSUE TITLE
Settings panel needs refinements

### ISSUE THREAD

**Issue by spadino** [EDDiscovery/EDDiscovery#2544]
As per screenshot, settings user control need better dynamic flow of controls, to be able to better fit different window size. I currently have a second monitor, vertically oriented, with a resolution of 1360x768, where I place EDDiscovery and, while almost everything fit well, the settings panel do not fit at all. Of course, I can open Settings as a popup, which allow me to use the previously hidden controls, but it should be clever enough to adapt itself. ;)

![image](https://user-images.githubusercontent.com/4296635/61501130-64a86900-a9a4-11e9-96ee-a03b763b0889.png)

You can see that there's a lot of wasted space at the bottom...

**Comment by robbyxp1** [comment]
Noted, I'll have a look, its being reworked now. closing not to clutter the list.
