### ISSUE TITLE
[Feature Request] - switch tabs on event

### ISSUE THREAD

**Issue by spadino** [EDDiscovery/EDDiscovery#2545]
I would like to have something like the profile switching, but instead of switch the profile, focus a different tab. Not sure if it can be already accomplished, probably yes, but it's quite hidden somewhere.

**Comment by robbyxp1** [comment]
Focus another tab? while your playing? Not sure what you mean.  You mean take focus off of the ED? Thats not a good idea.

**Comment by klightspeed** [comment]
I'm guessing spadino means switching the active tab.

**Comment by robbyxp1** [comment]
Ahhh,

So, the programming language can switch tabs, and it can react to events, so you could do it that way.

**Comment by spadino** [comment]
Indeed, Ben got it right. Yeah, I was almost sure that ActionLanguage already was able to do that. I'll give it a look...  😉

**Comment by robbyxp1** [comment]
Yep, its ProgramWindow Tab <tabname> to go to a particular tab.  Just make an event with a condition and run that bit of code..

EVENT ShipTargeted, SwitchToCombat, "", Condition AlwaysTrue

PROGRAM SwitchToCombat
ProgramWindow Tab "Combat Panel"
END PROGRAM

etc.

Closing as answered
