### ISSUE TITLE
New Events auto move panel to top while scrolling

### ISSUE THREAD

**Issue by bWildcard** [EDDiscovery/EDDiscovery#2546]
This is quite frustrating, ive been using this program more and more as trying to find the name of that ship to report after being instantly one shotted. How ever while scrolling through the Events list trying to find a single entry for Target Events, any new event that happens and is logged forces the panel to resort and auto scroll back to the top of the List! 

Can this please be fixed or an option be added to stop auto scrolling on new entry event?

**Comment by klightspeed** [comment]
On the history panel, is the up arrow (Automatically move the cursor to the latest entry when it arrives) selected?

**Comment by robbyxp1** [comment]
Unselect the up-arrow and it won't autoupdate on new journal events.  Does that work?

**Comment by robbyxp1** [comment]
No response, closing.
