### ISSUE TITLE
[Feature Request] Manually add exploration data from context menu

### ISSUE THREAD

**Issue by spadino** [EDDiscovery/EDDiscovery#2548]
Just returned to civilized area from almost two years of trip, and I remembered that previously discovered systems cannot be scanned. So, exploration data give that "no scan data available". Which suggest me that a context menu in both scan and scangrid panels can help in insert scan data manually to help populate legacy and already populated systems. 

So, a context menu item which open a manual exploration data insert form seems pretty useful in some situations... ;)

**Comment by klightspeed** [comment]
That would require either inserting fake Scan events in the journal table, or persisting the data somewhere.

**Comment by spadino** [comment]
Yes, indeed. I'm considering two directions which could be followed:

- a CustomEntries.db, with a table for scan datas.
- a custom "fake" journal entry, living in a Data/Custom folder, to be read and processed AFTER the standard journal dir.

Both will permits easy implementation, non polluting real data.

Thoughts?

**Comment by robbyxp1** [comment]
I don't think people will use this.. putting in scan data manually.

Moved to project ideas.
