### ISSUE TITLE
[UI Fix] - Logo stick over tabs when toolbar collapsed

### ISSUE THREAD

**Issue by spadino** [EDDiscovery/EDDiscovery#2553]
Whenever the toolbar is collapsed, the logo stick over the tab. Maybe worth consider some improvements on the idea...

![image](https://user-images.githubusercontent.com/4296635/62480548-823c4780-b786-11e9-9f25-e572898d6ed9.png)

**Comment by robbyxp1** [comment]
Reworked, done
