### ISSUE TITLE
Question: What does WAYPOINT mean in Route Finder?

### ISSUE THREAD

**Issue by ChuckBryan** [EDDiscovery/EDDiscovery#2557]
When using Route Finder, what does "WAYPOINT" mean when it appears in the System Column.

For example, mapping between Eorm Aim DY-O b33-0 and Eorm Aim HI-Z b27-0 creates an entry called "WAYPOINT" at row 3?

**Comment by iainross** [comment]
It means there's not a good known system to map you to so you need to scroll the galmap to those rough coordinates and pick a system.

**Comment by ChuckBryan** [comment]
Thank you!
