### ISSUE TITLE
Error when using the statistic tab

### ISSUE THREAD

**Issue by Menvynion** [EDDiscovery/EDDiscovery#2559]
### Description
When opening the first tab of the statistics tab

### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>   à EDDiscovery.UserControls.UserControlStats.StatsGeneral(HistoryEntry he, HistoryList hl) dans C:\Code\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlStats.cs:ligne 184
>   à EDDiscovery.UserControls.UserControlStats.Stats(HistoryEntry he, HistoryList hl) dans C:\Code\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlStats.cs:ligne 121
>   à System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
>   à System.Windows.Forms.TabControl.WmSelChange()
>   à System.Windows.Forms.TabControl.WndProc(Message& m)
>   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
This suggests you have no history.
