### ISSUE TITLE
11.0.0.0 GetAllEDSMSystems exception

### ISSUE THREAD

**Issue by dave-001** [EDDiscovery/EDDiscovery#2563]
Hello,

When I launch EDSM after upgrading to 11.0.0.0 I get the following:

Checking for new EDDiscovery maps
Scanning for bmp screenshots in C:\Users\xxxxxxxx\OneDrive\Pictures\Frontier Developments\Elite Dangerous
Checking for new Expedition data
*** Web server is disabled ***
Checking for new Exploration data
Profile Default Loaded
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
Full synchronisation to the EDSM databases required.
This will take a while, please be patient.
Please continue running ED Discovery until refresh is complete.
**GetAllEDSMSystems exception:Could not find a part of the path 'c:\code\edsm\Jsonprocess.lst'.**
History refresh complete.
Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 03/06/2019 17:12:16 to 03/06/2019 20:12:16
Download of EDSM systems from the server failed (NotFound), will try next time program is run
EDDB update complete with 4 systems
Refresh due to updating EDSM or EDDB data
History refresh complete.

The database compression/housekeeping doesn't take place.

I've uninstalled/reinstalled EDDiscovery and the issue persists after reinstalling.

Thoughts/advice appreciated!

Thanks in advance.
Dave.

**Comment by robbyxp1** [comment]
11.1 coming up !

**Comment by robbyxp1** [comment]
Download 11.0.1 and that bit of debug is turned off.

Thanks for the report.
