### ISSUE TITLE
An unhandled fatal exception has occurred.

### ISSUE THREAD

**Issue by 1RGhost** [EDDiscovery/EDDiscovery#2565]
An unhandled fatal exception has occurred.

==== BEGIN ====
code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   ved System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   ved System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   ved System.Data.SQLite.SQLiteDataReader.NextResult()
   ved System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   ved System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   ved SQLLiteExtensions.SQLExtDataReader`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLExtTransaction`1 txn, SQLExtTransactionLock`1 txnlock) i C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLReader.cs:linje 38
   ved SQLLiteExtensions.SQLExtCommand`1.ExecuteDbDataReader(CommandBehavior behavior) i C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:linje 94
   ved EliteDangerousCore.DB.SystemsDB.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical, SQLiteConnectionSystem cn, Action`1 LookedUp) i C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDBGetByDistance.cs:linje 91
   ved EliteDangerousCore.DB.SystemCache.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical, SQLiteConnectionSystem cn) i C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemCache.cs:linje 167
   ved EliteDangerousCore.StarDistanceComputer.BackgroundStardistWorkerThread() i C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarDistanceComputer.cs:linje 101
   ved System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ved System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ved System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   ved System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by klightspeed** [comment]
This looks like the same underlying cause as #2561 - SQLite multithreading being borked.

**Comment by robbyxp1** [comment]
Will be fixed in 11.1
