### ISSUE TITLE
Deleted EDDSystems.sqlite EDD  gets stuck trying to fetch new data.

### ISSUE THREAD

**Issue by 1RGhost** [EDDiscovery/EDDiscovery#2568]
After a crash the database never got updated to the new format and I deleted EDDSystems.sqlite.

EDD asked me to select which part of the galaxy map to download and i chose extended bubble,

Now EDD gets stuck downloading new data.

**Comment by klightspeed** [comment]
The EDSM systemsWithCoordinates.json dump is currently corrupt.  Please try disabling EDSM systems sync for the moment.
