### ISSUE TITLE
Random UnKnown Jumps are being created

### ISSUE THREAD

**Issue by recrudesce** [EDDiscovery/EDDiscovery#2569]
Since 11, every time I open EDD I get massive sections of my travels modified with UnKnown systems.

![image](https://user-images.githubusercontent.com/6450799/64428310-5543c300-d0ab-11e9-90de-954059510b40.png)

As you can see, every jump I performed through this route has a line going straight back to my current position.

Every other jump it's reading from the journals, there's also an UnKnown added

![image](https://user-images.githubusercontent.com/6450799/64428400-89b77f00-d0ab-11e9-844f-4a4e8ca1ba7d.png)

If I go into the SQLite database they are shown as follows:

```json
{
  "timestamp": "2019-09-03T21:51:43Z",
  "event": "FSDJump",
  "StarSystem": "UnKnown",
  "StarPos": [
    76.78125,
    -44.5,
    5.84375
  ],
  "EDDMapColor": -65536,
  "EDD_EDSMFirstDiscover": false
}
```

The co-ordinates of this UnKnown system are the co-ordinates of my current location, but it puts one between each of the jumps I performed to get to my current stop.

If I delete them, and then load EDD again, the problem goes away.  If I then do some jumps, close EDD, and then re-open it, the problem comes back but for the most recent "route".

**Comment by recrudesce** [comment]
See https://forums.frontier.co.uk/threads/eddiscovery-exploration-tool-for-pc-users-journal-3dmap-voice.462396/page-9#post-7986727 for confirmation this issue is not restricted to just my install.

**Comment by klightspeed** [comment]
It looks like instead of returning null, `FindSystem` is returning the system that was passed in when it can't find it in the systems database.
