### ISSUE TITLE
High Memory usage with 3.2.5

### ISSUE THREAD

**Issue by jgoode** [EDDiscovery/EDDiscovery#257]
I am getting 2.5 Gb of memory usage after having not played for a while. Is the memory usage normal?

**Comment by klightspeed** [comment]
@Robby has been working on something to reduce this memory usage.

**Comment by MNarath** [comment]
You are lucky I have a memory usage of 4-5 Gb and I can't use eddiscovery anymore because of that

**Comment by finwen** [comment]
We will release a beta of the new version with reduced memory usage soon

Den 15 juli 2016 15:14 skrev "MNarath" <notifications@github.com>:
>
> You are lucky I have a memory usage of 4-5 Gb and I can't use eddiscovery
anymore because of that

**Comment by MNarath** [comment]
Thank you for the answer I hope that the problem will be solved with this

**Comment by finwen** [comment]
https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_4.0.0

Test this

**Comment by finwen** [comment]
Solved with 4.0.x
