### ISSUE TITLE
Crash (seems like DB migration issue)

### ISSUE THREAD

**Issue by aaaabcv** [EDDiscovery/EDDiscovery#2572]
### Description
I Installed Version 11.1.0.1 (the current one) right on top of 10.6.0.0 After starting I get the crash report.
Please let me know if you need any further information or files from my installation.

According to the log it appears that there is a missing column in the database.

### Exception Details:
>EDDiscovery v11.0.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
>**no such column: s.edsmid**
>   bei System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   bei System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   bei System.Data.SQLite.SQLiteDataReader.NextResult()
>   bei System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   bei System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   bei SQLLiteExtensions.SQLExtDataReader`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLExtTransaction`1 txn, SQLExtTransactionLock`1 txnlock) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLReader.cs:Zeile 38.
>   bei SQLLiteExtensions.SQLExtCommand`1.ExecuteDbDataReader(CommandBehavior behavior) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:Zeile 94.
>   bei EliteDangerousCore.DB.SystemsDB.FindStar(Int64 edsmid, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDBGetStars.cs:Zeile 107.
>   bei EliteDangerousCore.DB.SystemCache.FindSystem(ISystem find, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemCache.cs:Zeile 85.
>   bei EliteDangerousCore.HistoryList.FillEDSM(HistoryEntry syspos) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:Zeile 575.
>   bei EDDiscovery.UserControls.UserControlSysInfo.Display(HistoryEntry he, HistoryList hl, Boolean selectedEntry) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSysInfo.cs:Zeile 197.
>   bei EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl, Boolean selectedEntry)
>   bei EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:Zeile 544.
>   bei EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl, Boolean disablesorting) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:Zeile 281.
>   bei System.Action`1.Invoke(T obj)
>   bei EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshCompleteonUI(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:Zeile 183.
>===== END =====
>```

**Comment by klightspeed** [comment]
Please try deleting EDDSystem.sqlite from `%LOCALAPPDATA%\EDDiscovery`

**Comment by aaaabcv** [comment]
Additional information: I had EDSM syncronization turned off. I turned it on again and it stared downloading from EDSM and after completing some stuff it seems that this error message does not appear anymore

**Comment by aaaabcv** [comment]
Thx @klightspeed, I was about trying that when I recognized that it has healed itself during EDSM (re-)download I had disabled since some versions as I enabled it again now. At least it appears like that.

**Comment by klightspeed** [comment]
It sounds like the DB schema isn't upgraded when EDSM system download is disabled, and the logic performing system searches needs to check the DB schema version and abort if the schema version is too low.

**Comment by robbyxp1** [comment]
hmmm.. it should run to upgrade even if its turned off, so that's a error by me.

I suggest that we tell them to turn it back on temporarily for now, and later we can clean it up.

**Comment by robbyxp1** [comment]
11.0.2 always tries to upgrade the db, irrespective of the state of that download switch.  So I think its fixed mostly.

I don't think its worth doing a pro-active check.. this is a temporary thing during the upgrade period.
