### ISSUE TITLE
Bad System scan parsing leading to incorrect System display

### ISSUE THREAD

**Issue by maddavo** [EDDiscovery/EDDiscovery#2574]
Screenshot of problem in 11.0.1.0 ...
https://i.imgur.com/DZk4LdN.png

**Comment by maddavo** [comment]
... hopefully this is also not leading to bad info being sent to EDSM... I haven't checked that.

**Comment by klightspeed** [comment]
This should be fixed by #2570, which will be in 11.0.2

**Comment by Envisitor** [comment]
All right, sorry for the duplicate.
