### ISSUE TITLE
Crash - unhandled UI exception

### ISSUE THREAD

**Issue by Zymurgy65** [EDDiscovery/EDDiscovery#2575]
Crash occured when starting to explore the UI

There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
>no such column: s.edsmid
>   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at SQLLiteExtensions.SQLExtDataReader`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLExtTransaction`1 txn, SQLExtTransactionLock`1 txnlock) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLReader.cs:line 38
>   at SQLLiteExtensions.SQLExtCommand`1.ExecuteDbDataReader(CommandBehavior behavior) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:line 94
>   at EliteDangerousCore.DB.SystemsDB.FindStar(String name, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDBGetStars.cs:line 50
>   at EliteDangerousCore.DB.SystemCache.FindSystem(ISystem find, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemCache.cs:line 92
>   at EliteDangerousCore.HistoryList.FillEDSM(HistoryEntry syspos) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 575
>   at EDDiscovery.UserControls.UserControlSysInfo.Display(HistoryEntry he, HistoryList hl, Boolean selectedEntry) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSysInfo.cs:line 197
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl, Boolean selectedEntry)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 544
>   at EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl, Boolean disablesorting) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 281
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshCompleteonUI(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 183
>===== END =====
>```

**Comment by recrudesce** [comment]
Same issue as #2572 
Worth reading that @Zymurgy65 as there's a "fix" detailed in it.

**Comment by robbyxp1** [comment]
closing as dup, thanks
