### ISSUE TITLE
Systemmap-view not working correctly

### ISSUE THREAD

**Issue by Envisitor** [EDDiscovery/EDDiscovery#2576]
I post this issue for a friend.
Sometimes the systemmap-view is not working correctly for him.
The systemmap shows up 4 red bodies in grid-design and instead of the body's name the system name is split into 4 parts and these are used as body-names. The link below will show up a screenshot of this issue. Also sometimes EDD seems to "forget" in which system the commander currently is in.

[https://media.discordapp.net/attachments/589457852263956499/620303556196696114/unknown.png](url)

**Comment by klightspeed** [comment]
This should be fixed in 11.0.2 (PR #2570)

In the meantime, disabling sync from EDSM in your commander settings should prevent any more `UnKnown` FSDJumps from being created.

**Comment by Envisitor** [comment]
All right, sorry for the duplicate.
