### ISSUE TITLE
Display scaling not working properly on Windows 7

### ISSUE THREAD

**Issue by klightspeed** [EDDiscovery/EDDiscovery#2579]
Tom#7765 reported on the eddiscovery channel on the EDCD discord that display scaling isn't working correctly on Windows 7 with 150% scaling on a 4k monitor.

> [11:47 PM] Tom: also the latest vertion is quite blurey
> [11:47 PM] Tom: im running a 4K display and win 7
> [11:48 PM] Bravada Cadelanne: That sounds like you have a scaling factor other than 100%, and the high DPI changes in EDDiscovery aren't working properly.
> [11:49 PM] Tom: i do have system scaling at 150% otherwise i cant actualy read anything
> [11:53 PM] Tom: i have tryed it with the Disable display scaling on high DPI settings compatabilaty option and that does make the text more clear but also make the images bigger and more blury and makes all the text boxes and buttons look bloated
> [11:53 PM] Tom: ![](https://cdn.discordapp.com/attachments/419456725075099648/619893005767409712/2019-09-07_21.53.01.png)
> [11:58 PM] Bravada Cadelanne: It sounds like we need to do more work on the high DPI support - it sounds like the buttons, text boxes, and image boxes are taking the system DPI setting and scaling themselves, while the text itself is applying post-draw scaling rather than scaling the font size.
> [12:01 AM] Tom: with high DPI settings on it looks less 'puffy' but evrything (text, icons, buttons etc) is blury and without high DPI it looks 'puffy' but the text is clear but buttons and icons are bigger and this make them more blury

**Comment by robbyxp1** [comment]
Thanks for the report. My comments are, first, I don't have windows 7 anymore to test it on.
Second windows 7 is EOL in January.

Is this a windows 7 thing or is it affecting windows 10?

**Comment by robbyxp1** [comment]
Closing, no possibility to debug this at this time.
