### ISSUE TITLE
EDSM Tab operation question

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#2580]
Is the new EDSM tab supposed to update to the current system after each jump?  That was my assumption, but it seems instead to go the current system when I activate the tab, and then on hyperjump, it goes to the EDSM homepage. 
If this is expected, that's fine - but what then does it add over and above the long standing EDSM button on the main window?
FWIW - I liked the idea of having the 2D map update in near-real time as a visualisation of where you are - even better with the trip computer start and target locations shown.  I thought maybe the EDSM tab would provide some of this...the blob of where you are now - can be useful to know when you're nearing the edge of a sparse zone.

**Comment by robbyxp1** [comment]
It follows the line in history selected.  In the history, have the button "Cursor to latest entry" selected.   then as you jump, EDSM panel will query EDSM about the next system.

https://github.com/EDDiscovery/EDDiscovery/wiki/Using-the-History-Grid-Panel
