### ISSUE TITLE
11.0.3.0 Fatal Error

### ISSUE THREAD

**Issue by RedfoxCh** [EDDiscovery/EDDiscovery#2582]
During first run of 10.0.3.0 after updating from ~10.x

Status bar on the bottom of the main window shows "Removing old system tables"

`An unhandled fatal exception has occurred.

==== BEGIN ====
code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   bei System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   bei System.Data.SQLite.SQLiteDataReader.NextResult()
   bei System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   bei System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   bei System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   bei SQLLiteExtensions.SQLExtCommand`1.ExecuteNonQuery() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:Zeile 133.
   bei SQLLiteExtensions.SQLExtConnection.ExecuteNonQuery(String query) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnection.cs:Zeile 237.
   bei SQLLiteExtensions.SQLExtConnection.ExecuteNonQueries(String[] queries) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnection.cs:Zeile 230.
   bei EliteDangerousCore.DB.SQLiteConnectionSystem.UpgradeSystemTableFrom102TypeDB(Func`1 cancelRequested, Action`1 reportProgress, Boolean fullsyncrequested) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SQLiteConnectionSystem.cs:Zeile 216.
   bei EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerMain.cs:Zeile 312.
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
===== END =====`

**Comment by RedfoxCh** [comment]
EDD seems to be working fine after crashing.

EDDSystem.sqlite size is 12 GB
edsmsystems.json size is 4.85 GB

**Comment by robbyxp1** [comment]
Bravada has a nice fix coming along to fix these lock issues, and will be in 11.1
