### ISSUE TITLE
Cannot Change Star Map Color - Keeps Changing Back To Red

### ISSUE THREAD

**Issue by idahosurge** [EDDiscovery/EDDiscovery#2585]
Every since I updated to 11.0.1.0 on September 8th the star map color keeps defaulting to red. Just updated to 11.0.3.0 and it is the same thing.

I highlight line 1 then right click; then in the popup box left click star map color. In the popup box change the color to green and click okay. Go back and check it and the color is red again.

It seems to me there use to be an option under the settings tab to change this. If it is still there I can not find it anyplace.

It is annoying to have to go in everyday and select all entries for that day and change them to green. I definitely never had to do this prior to upgrading to 11.0.1.0 after I changed the map color to a new color.

**Comment by klightspeed** [comment]
The default map colour in the commander settings dialog (from editing the commander in the settings tab) sets the default colour for new entries.

**Comment by idahosurge** [comment]
Thanks Ben!
