### ISSUE TITLE
System DB upgrade / How long does it take?

### ISSUE THREAD

**Issue by CrtiUser** [EDDiscovery/EDDiscovery#2586]
Hello,

I'm using a low end notebook and just migrated to EDD 11.x.

As announced the DB is bein upgraded ... no it's running for about 24 hours.
The number "processed" in the status line is slowly increasing.

Is there a way to determine how long it will take to be finished?

Greetings
CritiUser :-)

**Comment by klightspeed** [comment]
The number in the status bar is the total number of systems processed.  There are currently about 40 million systems in the EDSM system dump.

Note that the update will be slow if performed on a HDD or SSHD (entirely limited by seek speed).

**Comment by CrtiUser** [comment]
Thanks for the info. 
The upgrade just made it to the 40 millions :-)  and is now shrinking the DB.
