### ISSUE TITLE
Database update unable to complete

### ISSUE THREAD

**Issue by mp1963** [EDDiscovery/EDDiscovery#2588]
Please will you consider adding the option to NOT upgrade the database. For those of us who only are able to play ED for a short while at a time the database will NEVER be upgraded because we quite the game/ED Discovery before it has managed to complete the task. Thank you.

**Comment by robbyxp1** [comment]
Can't do that sorry. the rest of the code needs an updated database.

For a quicker upgrade, try pressing shift and run EDD. 

![image](https://user-images.githubusercontent.com/6573992/65376004-f8433200-dc92-11e9-9127-84644379a970.png)

Use delete/rebuild system DB, and it will then reload all the data from EDSM.  This will prob be quicker.
