### ISSUE TITLE
Material Collection not updating on scan tab

### ISSUE THREAD

**Issue by mearmortal** [EDDiscovery/EDDiscovery#2597]
Hello, I recently upgraded from 10.6.0 to 11.0.3.0 and I've just starting to collect materials after about 40lys of travel. I can see from the journal view that the materials are being registered in EDD, but the scan window with 'show only required materials' selected, does not reflect the additional material. The white popout window stays the same value, and if I max out the material, the hex icon is supposed to be removed but it doesn't. Now I've collected several times and it never updated. I've restarted and it's corrected the materials on loading, but still fails to update on further collections. I tried again today and it's still the same. I'm looking at a re-install next. This used to work fine on the previous version. Is there anything I can do? Thanks in advance.

**Comment by mearmortal** [comment]
One other thing, I've installed in in another location and loading with the command line option:
-Appfolder "D:\Elite Dangerous\EDDiscovery"

**Comment by klightspeed** [comment]
It looks like when that option was added, they forgot to add the events that update material counts to the events that update the scan display.

**Comment by mearmortal** [comment]
So how does this get fixed?

**Comment by klightspeed** [comment]
It should be fixed in the next version.  Alternatively, try the build at <https://ci.appveyor.com/project/EDDiscovery/eddiscovery/builds/27642615/artifacts> - this contains the fix that should fix this issue.

**Comment by mearmortal** [comment]
Thanks for the quick response, much appreciated

**Comment by robbyxp1** [comment]
In 11.0.4 coming v.soon
