### ISSUE TITLE
Backup / import  data

### ISSUE THREAD

**Issue by finwen** [EDDiscovery/EDDiscovery#26]
From  Matt Kowalsky 

First, I would really hate to loose the data that I have gathered so far. Accidents happen and I could loose the netlog files or the sqlite data files. Is there a way to backup the data (and restore it of course)?
Of course, we could simply backup the sqlite datafiles in appdata/Local/EDDiscovery but it would be better to have a menu option to do the backup/export and restore/import

**Comment by Red13x3** [comment]
+1 this idea.
I would also like to add that I used a spreadsheet before finding EDD and so I would love to add those stars as ones I have traveled to into my personal DB.

**Comment by robbyxp1** [comment]
We have export to excel now.
