### ISSUE TITLE
Download of EDSM systems from the server failed (NotFound), will try next time program is run

### ISSUE THREAD

**Issue by lemmy04** [EDDiscovery/EDDiscovery#2602]
After i start EDD I eventually get this message on the log view:

Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 06.09.2019 05:55:33 to 06.09.2019 08:55:33
Download of EDSM systems from the server failed (NotFound), will try next time program is run

I'm running EDD 11.0.4.0

**Comment by robbyxp1** [comment]
This happens sometimes with EDSM due to the server being overloaded or in maintenance.

please try again.

**Comment by lemmy04** [comment]
I've been retrying this several times per day now, is there any log that I can check? maybe EDSM changed something and all EDD gets is an error 404?

**Comment by klightspeed** [comment]
Do you have any sort of application-layer firewall or proxy between you and EDSM?

What does <https://www.edsm.net/api-v1/systems?startdatetime=2019-09-06+05:55:33&enddatetime=2019-09-06+08:55:33&coords=1&submitted=1&known=1&showId=1> give you?  It should give you some json containing systems and coordinates starting with:
```
[{"name":"Oochoxt MG-Y a96-0","id":43684298,"id64":5506684700472,"coords":{"x":1297.9375,"y":-43.6875,"z":-1314.84375},"coordsLocked":false,"date":"2019-09-06 05:55:33","submitted":[]},
```

**Comment by lemmy04** [comment]
bingo.
my firewall was in the way (technically: firewalld inserts the allow rule for state established,related *after* the source rules for the drop zone).
