### ISSUE TITLE
Redundant/Unnecessary Downloads

### ISSUE THREAD

**Issue by jehrek** [EDDiscovery/EDDiscovery#2603]
Hello, 

Installed 11.0.4 yesterday, and on run it began to output the below in the log:

```
Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 4/3/2010 12:00:00 PM to 4/5/2010 12:00:00 PM
Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 4/4/2010 12:00:00 AM to 4/6/2010 12:00:00 AM
Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 4/4/2010 12:00:00 PM to 4/6/2010 12:00:00 PM
Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 4/5/2010 12:00:00 AM to 4/7/2010 12:00:00 AM
Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 4/5/2010 12:00:00 PM to 4/7/2010 12:00:00 PM
Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 4/6/2010 12:00:00 AM to 4/8/2010 12:00:00 AM
Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 4/6/2010 12:00:00 PM to 4/8/2010 12:00:00 PM
Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 4/7/2010 12:00:00 AM to 4/9/2010 12:00:00 AM
```

Two things I've noticed

1) Redundant downloads (one would assume the 4/3 to 4/5 download would include 4/4)
2) These downloads began with UTC 1/1/2000 to 1/3/2000 . As the game and EDSM were not in existence until the end of 2014, why is it downloading so much data which shouldn't exist?

I've attached both trace logs I have.

[Trace_2019-09-27-12-40-38.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3665488/Trace_2019-09-27-12-40-38.0.log)
[Trace_2019-09-27-15-58-08.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3665489/Trace_2019-09-27-15-58-08.0.log)

**Comment by robbyxp1** [comment]
Delete the system DB (hold Shift, run EDD, select the option to remove the system DB) and start again.  Something when a little screwy.

**Comment by klightspeed** [comment]
Also delete edsmsystems.json if it exists - fetching starting from 2000 suggests that this file is either empty or invalid.

**Comment by jehrek** [comment]
Removing both json and dB and reloading worked, it seems to have loaded fine. Thanks for the assistance
