### ISSUE TITLE
There was an unhandled UI exception while exporting route to CSV

### ISSUE THREAD

**Issue by EoD** [EDDiscovery/EDDiscovery#2609]
### Description
Trying to export a route to CSV (and open "in Excel") from the Route Finder tab

### Additional Information
![ed_bug1](https://user-images.githubusercontent.com/293499/65841331-57531780-e321-11e9-99d3-924cd5b3a233.PNG)

### Exception Details:
>EDDiscovery v11.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ComponentModel.Win32Exception (0x80004005): Application not found
>   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
>   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>   at EDDiscovery.UserControls.UserControlRoute.buttonExtExcel_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlRoute.cs:line 671
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
That looks like you didn't uncheck Open with Excel when you exported to CSV.  Do you have Excel installed?

**Comment by EoD** [comment]
@klightspeed ok, I found the option, but the path was slightly different `Control Panel` -> `Apps` -> `Default Apps` -> `Choose default applications by file type`.
This is the screenshot:
![image](https://user-images.githubusercontent.com/293499/65904684-3a6d2180-e3bf-11e9-80b0-4c3b0af61dc9.png)

After selecting an app there (it was "blank" for some reason), the crash didn't occur anymore.

**Comment by robbyxp1** [comment]
Yes, it can, i'll address.

**Comment by robbyxp1** [comment]
Fixed on tip
