### ISSUE TITLE
Unhandled exception when opening filter dropdown 2nd time

### ISSUE THREAD

**Issue by mpfj** [EDDiscovery/EDDiscovery#2610]
### Description
Opened filter dropdown ... showed okay
Closed it with the [X] and then re-opened ... error message

### Exception Details:
>EDDiscovery v11.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ObjectDisposedException: Cannot access a disposed object.
>Object name: 'FilterSelector'.
>   at System.Windows.Forms.Control.CreateHandle()
>   at System.Windows.Forms.Form.CreateHandle()
>   at System.Windows.Forms.Control.get_Handle()
>   at System.Windows.Forms.Form.Show(IWin32Window owner)
>   at EDDiscovery.UserControls.FilterSelector.Filter(Control ctr, Form parent) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\Filter.cs:line 99
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Which panel were you using Please?

The main travel history, or another one?

**Comment by mpfj** [comment]
Yes, the main travel history.

**Comment by mpfj** [comment]
Okay, so if you click the Filter icon to close the dropdown, everything works fine :)

But if you click the [X] to close the dropdown, you get the unhandled exception every time you try to re-open the filter dropdown.

I guess the [X] is freeing up something it shouldn't.

**Comment by klightspeed** [comment]
It looks like the dropdown is not borderless in the default windows theme.

**Comment by robbyxp1** [comment]
Fixed for 11.0.5  Thanks for the report.
