### ISSUE TITLE
Route Finder goes into endless loop with some specific values

### ISSUE THREAD

**Issue by EoD** [EDDiscovery/EDDiscovery#2611]
I can reproducibly kill EDD by entering these values into the route finder:
![image](https://user-images.githubusercontent.com/293499/66005713-8f3a9600-e4ac-11e9-9ec7-517009213157.png)

From `Stroa Eohn KC-B d1-0`
Max jump `105` ly.

It is independent of the target system as well as the Metric being used.

**Comment by EoD** [comment]
I found a couple more cases where it goes into a loop, mostly if I use values >100ly as max jump range.

**Comment by klightspeed** [comment]
That looks like it isn't excluding the previous system(s) from candidates for the next waypoint, and possibly isn't checking that forward progress is being made toward the destination.

**Comment by robbyxp1** [comment]
got it, will fix, thanks

**Comment by robbyxp1** [comment]
Fixed, 11.0.5

**Comment by EoD** [comment]
Thanks, I can confirm it's fixed with 68f2c0bd7356d6e1bf197a65773f7dbbed36f422
