### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by rurwin** [EDDiscovery/EDDiscovery#2613]
EDDiscovery running in the background on second monitor.
Went through maybe 50 jumps, some scanning. Clicked to bring it to the front.
### Exception Details:
>EDDiscovery v11.0.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.HistoryList.AddJournalEntry(JournalEntry je, Action`1 logerror) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 894
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 82
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 72
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(Tuple`2 entries) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 185
>===== END =====

![image](https://user-images.githubusercontent.com/1812668/66166702-f03ea700-e62f-11e9-8667-b9e958ec2d8c.png)

**Comment by klightspeed** [comment]
Please try updating to 11.0.5 - this issue was fixed in #2592
