### ISSUE TITLE
UI exception during database delete (via remove sectors from ESM)

### ISSUE THREAD

**Issue by strangealien** [EDDiscovery/EDDiscovery#2619]
Hello,
since the tool is now very slow and sluggish with every ESM database operation I decided to delete all the ESM data (~5000 ly around Sol) and maybe download them anew later. Maybe something happened during database upgrade?

The tool became extremely sluggish and slow, after start the ESM update took ages (and there are now less reports so it is not obvious when this is ready). So if you happen to use the 3D map during this, the entire tool hangs, you cannot close the map and not use the tool for 30 secs to a minute. Populating the 3D map with the downloaded sectors when first opened took ages too and again the tool is very slow to react and tends to hang for minutes until this is ready. All this is accompanied by heavy disk activity (I do not use my SSD for EDD data).

During the database delete (all sectors) this bug happened: 

### Description
Nothing - I waited, while EDD removed all my ESM data I had downloaded.

### Exception Details:
>EDDiscovery v11.0.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
>database is locked
>   bei System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   bei System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   bei System.Data.SQLite.SQLiteDataReader.NextResult()
>   bei System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   bei System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   bei SQLLiteExtensions.SQLExtDataReader`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLExtTransaction`1 txn, SQLExtTransactionLock`1 txnlock) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLReader.cs:Zeile 38.
>   bei SQLLiteExtensions.SQLExtCommand`1.ExecuteDbDataReader(CommandBehavior behavior) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:Zeile 94.
>   bei EliteDangerousCore.DB.SystemsDB.FindStar(String name, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDBGetStars.cs:Zeile 50.
>   bei EliteDangerousCore.DB.SystemCache.FindSystem(ISystem find, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemCache.cs:Zeile 97.
>   bei EliteDangerousCore.EDCommander.get_HomeSystemIOrSol() in C:\Code\EDDiscovery\EliteDangerous\DB\EDCommander.cs:Zeile 516.
>   bei EDDiscovery.UserControls.UserControlSysInfo.Display(HistoryEntry he, HistoryList hl, Boolean selectedEntry) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSysInfo.cs:Zeile 207.
>   bei EDDiscovery.UserControls.UserControlSysInfo.Discoveryform_OnNewUIEvent(UIEvent obj) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSysInfo.cs:Zeile 165.
>   bei System.Action`1.Invoke(T obj)
>   bei EliteDangerousCore.EDJournalClass.UIEventPost(ConcurrentQueue`1 events) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:Zeile 335.
>===== END =====
>```

**Comment by klightspeed** [comment]
The `database is locked` error should be fixed in 11.1

We'll have to look at the delete operation and see if it can be paginated, so as to limit the amount of time each delete command runs for and so limit the amount of time accesses to the systems database have to wait.
