### ISSUE TITLE
Exception on option "Send unsynced EGO scans"

### ISSUE THREAD

**Issue by sanjay-nambiar** [EDDiscovery/EDDiscovery#2620]
Getting an exception every time I use **Admin -> Send unsynced EGO scans**

_EGO sync Exception String cannot be of zero length.
Parameter name: oldValue_

EDDiscovery version 11.0.5.0
I got the same exception with the previous couple of versions as well.

**Comment by robbyxp1** [comment]
Turn off EGO sync in your commanders settings, the site EGO is not working.

I'll stop this from happening later.

thanks

**Comment by robbyxp1** [comment]
EGO is disabled in 11.1 and the exception is removed. Thanks for the report.
