### ISSUE TITLE
System not found, despite system exists on EDSM!

### ISSUE THREAD

**Issue by strangealien** [EDDiscovery/EDDiscovery#2623]
Hello,

the **Wregoe VK-E c12-0**  system is in EDSM and can be found there, but using it in EDD 11.0.5 is impossible? Typing/copying the name into the route finder or using it as a target is not possible, error message:
Unknown system, system is without co-ordinates or galaxy object not found

I tried it with bubble data (it is not in the bubble) and completely without data downloaded. Seems to be a communication problem with EDSM. Lots of other systems without data downloaded work fine.

**Comment by klightspeed** [comment]
I don't think EDDiscovery currently requests the system directly from EDSM before rejecting it - it only uses the local system store supplemented by your visited systems.  For those interactive lookups, we probably need to request the system directly from EDSM and cache it if it's not in the local system store.

Note that the route finder won't work if it has no data in the local system store for the area you are routing through.

**Comment by strangealien** [comment]
Just downloaded 'extended bubble' data, and now it can be found. Before that I had only 'bubble' data, and it was rejected - BUT: I found a lot of systems outside the bubble and outside the data downloaded. In this case the route finder used 'WAYPOINTS', which it always uses if it cannot find systems.
So it works somehow even if no data are found: The target system seems to be requested from EDSM, the systems along the route (which are unknown) are not requested, and this is fine, because it would be hard to do. But the target system with a system name should be looked up and requested if it exists in EDSMs data base.

**Comment by robbyxp1** [comment]
The route finder works on the downloaded data, as designed. Using EDSM directly would result in too many requests to EDSM for it to handle.

The EDSM button could be recoded to check EDSM.. I'll think about it.

So closing as its working as currently designed.
