### ISSUE TITLE
percentage of scanned bodies in exploration tab

### ISSUE THREAD

**Issue by wolfnether** [EDDiscovery/EDDiscovery#2627]
it's possible to have the percentage of scanned bodies in the exploration tab ?

**Comment by robbyxp1** [comment]
I'll have a think about that, if we can really calculate it (Frontier may not give enough info to do that).

**Comment by klightspeed** [comment]
The `FSSDiscoveryScan` event has `BodyCount` and `Progress`.  `BodyCount` is copied to `SystemNode.TotalBodies`.

It should be possible to take `SystemNode.Bodies.Where(b => b.type == ScanNodeType.star || b.type == ScanNodeType.planet).Count()` as the number of known bodies, and `SystemNode.TotalBodies` as the total number of bodies.

**Comment by robbyxp1** [comment]
I'm thinking of asteroid clusters.. do they properly sum?

**Comment by robbyxp1** [comment]
the exploration tab has had a much needed bit of tlc:

![image](https://user-images.githubusercontent.com/6573992/68086885-344be400-fe48-11e9-947c-a148a995bcd2.png)

This uses the scan node to find data about a system. It also knows about a system not just thru EDSM but also thru your history.

Added totals to surveyor, starlist panels as well.

closing.
