### ISSUE TITLE
An error has occurred. (C2-12686-3)

### ISSUE THREAD

**Issue by dededrei** [EDDiscovery/EDDiscovery#2629]
I've been having this issue since I install henkaku latest version.. this message appears after I copy h-encore (13mb) from PC - PS Vita through application manager.. after I exit out, I can see a white bubble name h-encore.. how do I fix this?
PS Vita model: PCH 2006
System software: 3.68

**Comment by klightspeed** [comment]
I don't see any relation between EDDiscovery and Henkaku.

Please try re-posting your issue to https://github.com/henkaku/henkaku/issues
