### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by NeilMcArmstrong** [EDDiscovery/EDDiscovery#2630]
I was Just traveling around an Scan Plantes in ED. i dont know when exactly the Error Ocured,  EDDiscovery alway runs in the Background.

### Exception Details:
>EDDiscovery v11.0.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
>no such table: Sectors
>   bei System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   bei System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   bei System.Data.SQLite.SQLiteDataReader.NextResult()
>   bei System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   bei System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   bei SQLLiteExtensions.SQLExtDataReader`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLExtTransaction`1 txn, SQLExtTransactionLock`1 txnlock) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLReader.cs:Zeile 38.
>   bei SQLLiteExtensions.SQLExtCommand`1.ExecuteDbDataReader(CommandBehavior behavior) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:Zeile 94.
>   bei EliteDangerousCore.DB.SystemsDB.FindStar(String name, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDBGetStars.cs:Zeile 72.
>   bei EliteDangerousCore.DB.SystemCache.FindSystem(ISystem find, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemCache.cs:Zeile 97.
>   bei EDDiscovery.Actions.ActionScan.ExecuteAction(ActionProgramRun ap) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionsEDDCmds\ActionScanStar.cs:Zeile 75.
>   bei ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:Zeile 217.
>   bei EDDiscovery.Actions.ActionController.ActionRun(ActionEvent ev, HistoryEntry he, Variables additionalvars, String flagstart, Boolean now) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:Zeile 552.
>   bei EDDiscovery.Actions.ActionTimer.Timer_Tick(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionsEDDCmds\ActionTimer.cs:Zeile 140.
>   bei System.Windows.Forms.Timer.OnTick(EventArgs e)
>   bei System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Looks like a broken system db

Hold down shift, run EDD, delete the system db, and let it rebuild it after you select how much star data you want to load in.

Make sure you have a decent internet connection if you do the lot.
