### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by Abulion** [EDDiscovery/EDDiscovery#2636]
### Exception Details:
>EDDiscovery v11.1.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.IndexOutOfRangeException: Indice oltre i limiti della matrice.
>   in EliteDangerousCore.DB.GridId.Id(Double x, Double z) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemGridID.cs:riga 59
>   in EDDiscovery.StarGrids.IsDisplayChanged(Single xp, Single zp) in C:\Code\EDDiscovery\EDDiscovery\3DMap\StarGrid.cs:riga 476
>   in EDDiscovery.FormMap.SystemTick(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\3DMap\FormMap.cs:riga 628
>   in System.EventHandler.Invoke(Object sender, EventArgs e)
>   in System.Windows.Forms.Timer.OnTick(EventArgs e)
>   in System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

This is just happened to me.

Plus i have noticed that is slower than the previous version...

Sometimes it get "lost" populating the hystory grid, and I am a system ahead...

**Comment by robbyxp1** [comment]
Slower in what way? The 3dmap?

I'll look into the crash.

**Comment by robbyxp1** [comment]
The crash is due to floating point precision, its pretty unlikely to happen, i'll fix it in the next version.

**Comment by robbyxp1** [comment]
11.1.2 when it is released will have this fix. thanks for the report.
