### ISSUE TITLE
Tool blocks after start, cannot be used for minutes!

### ISSUE THREAD

**Issue by strangealien** [EDDiscovery/EDDiscovery#2637]
Hello,
there is something very wrong with the database access: If I start EDD, it first reads my history, then fills the grid and reports history update complete. Next it seems to try to update EDSM systems. This always happened, but now it is really awful. (Database upgrade happened days ago, I always updated to the last version!)

EDD hangs and cannot even be minimized, it is completely unresponsive for minutes. It trashes the hard disk, first with reads around 1 MByte/sec, for minutes, next it starts to download from EDSM, and writes around 1Mbyte/sec, also for minutes. If one did not use EDD for several days this takes around 10-20 minutes. 
The updates from EDSM always blocked a bit and took a while, but older EDD versions remained responsive and you could use the tool, only the 3D map and the route finder tended to hang in this phase. Now you can hardy use the tool, and in the reading phase you cannot even switch it to background (minimize it) in Windows!
I have only 'extended bubble' downloaded, I just upgraded from 11.1.1.0, and had other 11.1.x versions before that. The database upgrade should be long done by now. I last deleted all the EDSM systems and re-downloaded them with 11.1.1.0, and my database has 490 MByte. 
The system is Windows 7 64 SP2, Core i7 6850k, 32 GB, fully patched.

Could it be, that somehow it always tries to optimize the database despite it being already optimized? Because it seems to read (and analyze?) the entire database and then tries to update it from EDSM, which can take quite a time since it does it in 'sips'. During update (also reported by EDD) the tools becomes somewhat more responsive, but in the 'reading phase' the tool just hangs and also shows the 'busy cursor'. 
When i started it today, after a pause of 3 days, it became unresponsive after telling me about the update. It hung for over 10 minutes (permanently reading something from the disk, 1MByte/sec, according to the Windows Resource Monitor), so that I had to task kill it, because it was unresponsive and could not even be minimized. After this I updated and it happened again, but this time only for around 2 minutes, where it was completely unresponsive.
Any ideas?

**Comment by strangealien** [comment]
Additional information: The disk/partition for my database remains entirely accessible the whole time, and CPU load is very low during the 'reading phase'. I can access, manipulate and copy files on the same disk/partition with the database, so it is not the disk. The disk can do 30MByte/sec with small files and up to 100 MByte/sec with large files. Only the reading thread in EDD seems to block the EDD GUI and the rest of EDD, while it runs.

**Comment by robbyxp1** [comment]
I'm not totally sure what is going on here.  The obv thing is that the system db is borked, probably the indexes.  If it was my computer i'd delete the system db and let it rebuild it (hold down shift and run EDD to do this).

The actual operations on the db it does is exactly the same as 11.0, the difference being the scheduling of them is all in one thread thus preventing any multitasking issues.

**Comment by Abulion** [comment]
Well, it seems that I have a similar problem...

The tool become irresponsive and took a 14% of cpu usage... 

I have arrived now at Ratraii and the tool it's blocked on Asura... slowly populating the history grid...

**Comment by Abulion** [comment]
I have tried to rebuild the database...

And now the Eddiscovery it's taking a 0.3 ish of cpu time...

**Comment by robbyxp1** [comment]
Closing
