### ISSUE TITLE
EDSM Data failure

### ISSUE THREAD

**Issue by Ischtaratu** [EDDiscovery/EDDiscovery#2641]
In some core systems (e.g. Khun, Sol, Sirius ...) EDDiscovery apparently has difficulties displaying the correct scan data (from EDSM). Instead only a 'Main Star' and the symbol for not scanned stars (red sphere) is displayed.

What is the problem? The data from EDSM should be available.

I use EDDiscovery to display the system data directly in the game. It is not nice to get an "unknown star system" displayed if you have already been there 1000 times. 

Enclosed 2 screenshots for clarification:

http://kaldarin.net/temp/Screen1.jpg
http://kaldarin.net/temp/Screen2.jpg

I hope you understand what I mean.

**Comment by robbyxp1** [comment]
You show one screenshot with Khun data, the other without..  So I'm a bit confused..

**Comment by klightspeed** [comment]
That looks like you have 2 scan panels - one in the history tab, and the other in its own tab.

I suspect the one in its own tab has show EDSM bodies turned off.

If you hover over the double-line at the top of the scan tab, to expand the toolbar, I think you'll find that the EDSM button is not highlighted (checked).  When the EDSM button is not checked, the scan panel will exclude any bodies for which you don't have scan events.

**Comment by Ischtaratu** [comment]
Thank you! Now I understand the system behind it.
So it's not a mistake in itself.

What I don't understand yet is why I still don't get scan data in systems like Khun, even though I scanned them. In Sol the complete system is displayed after a simple scan. Khun remains empty.

**Comment by klightspeed** [comment]
Odd - do you have scan events in your journal for the bodies you scanned?

For populated systems, you can scan the nav beacon to get the scans for all of the bodies in the system.

**Comment by Ischtaratu** [comment]
EDD use the Logs form the Game-Client ... maybe data errorß ... but why only this starsystem ... it make no sense ...

**Comment by klightspeed** [comment]
If you type `Khun` into the history panel search box, do any scans for `Khun` show up?

**Comment by Ischtaratu** [comment]
Yes, the entry exists in the log.
The identical problem also exists in Shinrarta. After the Honk and VSS scan I do not get any scan data of the stars and planets displayed.
Only if I switch on the EDSM option in EDD, I get the correct data.

Bug or feature ? I think it is due to the game client that it does not output the data.

**Comment by klightspeed** [comment]
Have you tried scanning the nav beacon?  Honking and using FSS scan for pre-discovered systems won't write the bodies to the journal - for that, you need to scan the nav beacon.

**Comment by Ischtaratu** [comment]
Scan the nav beacon .... <facepalm> ... oh ... yes, thats it. 
But one last question:
Which bastard came up with this crap? Didn't FD have a better idea what to do with their small piping probes? How good that I am as an explorer so rarely in the bubble xD

Thanks you for your patience. You made my day!

/closed

**Comment by klightspeed** [comment]
From what I can tell, scanning a nav beacon has always revealed all bodies in the system.  I think Frontier added scanning the nav beacon writing all scans to the journal in 2.4 as a way of getting scans for bodies in populated systems that had already been scanned, and so could not be re-scanned.  Pre-discovered systems have all of their bodies pre-scanned, and so the bodies cannot be manually scanned.

**Comment by Ischtaratu** [comment]
Yes .... but outside the bubble, you scan the system once ... and they are always in your journal ... and there is no difference you have made the first scan or not.

**Comment by klightspeed** [comment]
Pre-discovered systems (such as Sol, Khun, Sirius, etc) are systems where you start out with the body data for the system, and so can __never__ scan the bodies manually (except by mapping them), and so the only way to get the body data written to the journal is to scan the nav beacon.

Elite Dangerous does not allow you to re-scan bodies once they have been scanned.  For bodies you scanned before 3.0, you do have the option to map the bodies and get their scans that way.

**Comment by klightspeed** [comment]
Pre-discovered systems (such as Sol, Khun, Sirius, etc) are systems where you start out with the body data for the system, and so can __never__ scan the bodies manually (except by mapping them), and so the only way to get the body data written to the journal is to scan the nav beacon or map the bodies.

Elite Dangerous does not allow you to re-scan bodies once they have been scanned.  For bodies you scanned before 3.0, you do have the option to map the bodies and get their scans that way.
