### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by bcrotty** [EDDiscovery/EDDiscovery#2642]
I'm trying scan bio & geo sites for codex entries and keep a record of which ones I've scanned.

When I enter notes in the System Information notes field, they do appear on the Notes tab, but they disappear from the System Information notes field (same as #704), so anytime I want to add a site, I have to retype the whole thing from scratch.

I tried typing notes directly in EDSM as a private comment, but that never shows up in EDDiscovery.

Am I doing something wrong? Is there a better way to do what I'm trying to do?

Also, I can't find the Add Note from #869.

**Comment by klightspeed** [comment]
The right-click context menu option is called `Set Note`.

The note in the system information tab is the note from the currently selected journal entry, not the note for the system.

Note that EDSM system comments are only applied to the FSDJump event, as EDSM comments only apply to the system.  EDSM comments are currently only fetched if you have enabled Sync From EDSM on the commander.  Perhaps we should separate comment sync from travel history sync at some point, and perhaps also separate system notes from journal entry notes in the UI.

**Comment by bcrotty** [comment]
Where can you find the Set Note option? It hasn't been on any of the right-click context menus that I've found.

I have sync from EDSM turned on. Would I only see the EDSM comment when I'm jumping into the system?

**Comment by klightspeed** [comment]
Right-click on an entry in the history tab:
![image](https://user-images.githubusercontent.com/147116/67400983-cdc9f900-f5f1-11e9-9074-cf860ab8cdd5.png)

If EDSM comments are synced from EDSM, they should appear on the FSDJump entry associated with that system in the history tab.
