### ISSUE TITLE
Estimated Scan Values Transparency Support

### ISSUE THREAD

**Issue by bcrotty** [EDDiscovery/EDDiscovery#2644]
May we please have transparency support for the Estimated Scan Values panel? I use it as an overlay to track bodies I should map.

**Comment by robbyxp1** [comment]
At the moment its based on a data grid, which can't be made transparent.  It would have to be recoded.

I'll put it on the list. Don't expect it to be soon - we are in a holding pattern at the moment.

**Comment by ASemenov1977** [comment]
Maybe you can add max possible scan value to Surveyor? Like it realized in EDSM dashboard.

**Comment by robbyxp1** [comment]
Surveyor now has values.
