### ISSUE TITLE
Add excel output to ships/loadout

### ISSUE THREAD

**Issue by robbyxp1** [EDDiscovery/EDDiscovery#2650]
Put out info about all ships.
Maybe one overall csv and a csv per ship..

**Comment by Loki419420** [comment]
{
  "$schema": "https://coriolis.io/schemas/ship-loadout/4.json#",
  "name": "The Killer",
  "ship": "Federal Corvette",
  "references": [
    {
      "name": "Coriolis.io",
      "url": "https://coriolis.io/outfit/federal_corvette?code=A4putpFklodzsuf5yGyG0u1a1a2d2d030j0402030303033hfh06--6l1K2L2Lf46l3x2i.Iw18ZVA%3D.Aw18ZVA%3D.H4sIAAAAAAAAA2P4x8LAwPCXFUj86QcS3AXOPgyCO7gZGFR%2Bn2Jg4F1pxsjwn%2FGfHVxRPZDgEPr7%2Fz%2F%2FAz0GBjH9a8wMQutu%2Ff%2F%2Fn%2BmfOFxRKZDg59FmYBDKYmdgUK548%2F%2B%2FqBhQTARkmUTue6By5n9ScOXlIOVvW7kYhJ4ATRL5cOP%2FfwkQwQgUZxD%2B7MrIoAxi%2Fef%2FxwXTw28AtENohhVQVPGfLEgUZDSPzbf%2F%2F4WOcAItWcDPwCDVIQyUV%2F4XC9MlJKDOwGAKFv3PAAEA8dzJYAEBAAA%3D&bn=The%20Killer",
      "code": "A4putpFklodzsuf5yGyG0u1a1a2d2d030j0402030303033hfh06--6l1K2L2Lf46l3x2i.Iw18ZVA=.Aw18ZVA=.H4sIAAAAAAAAA2P4x8LAwPCXFUj86QcS3AXOPgyCO7gZGFR+n2Jg4F1pxsjwn/GfHVxRPZDgEPr7/z//Az0GBjH9a8wMQutu/f//n+mfOFxRKZDg59FmYBDKYmdgUK548/+/qBhQTARkmUTue6By5n9ScOXlIOVvW7kYhJ4ATRL5cOP/fwkQwQgUZxD+7MrIoAxi/ef/xwXTw28AtENohhVQVPGfLEgUZDSPzbf//4WOcAItWcDPwCDVIQyUV/4XC9MlJKDOwGAKFv3PAAEA8dzJYAEBAAA=",
      "shipId": "federal_corvette"
    }
  ],
  "components": {
    "standard": {
      "bulkheads": "Reactive Surface Composite",
      "cargoHatch": {
        "enabled": true,
        "priority": 1
      },
      "powerPlant": {
        "class": 8,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "modifications": {
          "eff": -750,
          "integrity": 12000,
          "pgen": 251439,
          "mass": -9554
        },
        "blueprint": {
          "fdname": "PowerPlant_Armoured",
          "grades": {
            "1": {
              "components": {
                "Worn Shield Emitters": 1
              },
              "features": {
                "eff": [
                  0,
                  -0.04
                ],
                "integrity": [
                  0,
                  0.4
                ],
                "pgen": [
                  0,
                  0.04
                ],
                "mass": [
                  0.04,
                  0.04
                ]
              },
              "uuid": "14be2e0d-417b-4cde-834f-b7e8ca14bb85"
            },
            "2": {
              "components": {
                "Carbon": 1,
                "Shield Emitters": 1
              },
              "features": {
                "eff": [
                  -0.04,
                  -0.06
                ],
                "integrity": [
                  0.3,
                  0.6
                ],
                "pgen": [
                  0,
                  0.06
                ],
                "mass": [
                  0.08,
                  0.08
                ]
              },
              "uuid": "14ade730-2a1d-4f48-a619-46be865819ec"
            },
            "3": {
              "components": {
                "Carbon": 1,
                "High Density Composites": 1,
                "Shield Emitters": 1
              },
              "features": {
                "eff": [
                  -0.06,
                  -0.08
                ],
                "integrity": [
                  0.6,
                  0.8
                ],
                "pgen": [
                  0.06,
                  0.08
                ],
                "mass": [
                  0.12,
                  0.12
                ]
              },
              "uuid": "aa9a05c9-f142-40db-b0bf-8f6ca29efba8"
            },
            "4": {
              "components": {
                "Proprietary Composites": 1,
                "Shielding Sensors": 1,
                "Vanadium": 1
              },
              "features": {
                "eff": [
                  -0.08,
                  -0.1
                ],
                "integrity": [
                  0.5,
                  1
                ],
                "pgen": [
                  0.08,
                  0.1
                ],
                "mass": [
                  0.16,
                  0.16
                ]
              },
              "uuid": "bfb0ccc8-389e-4df0-9acd-4df91680c5a3"
            },
            "5": {
              "components": {
                "Compound Shielding": 1,
                "Core Dynamics Composites": 1,
                "Tungsten": 1
              },
              "features": {
                "eff": [
                  -0.1,
                  -0.12
                ],
                "integrity": [
                  1,
                  1.2
                ],
                "pgen": [
                  0.1,
                  0.12
                ],
                "mass": [
                  0.2,
                  0.2
                ]
              },
              "uuid": "5156badb-c1eb-49f4-923d-b9e6f862799f"
            }
          },
          "id": 62,
          "modulename": [
            "Power plant"
          ],
          "name": "Armoured",
          "grade": 5,
          "special": {
            "name": "Stripped Down",
            "id": 127,
            "edname": "special_powerplant_lightweight",
            "uuid": "11b258eb-36d1-4cbc-be04-7fc426ef3121"
          }
        }
      },
      "thrusters": {
        "class": 7,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "modifications": {
          "integrity": 11020,
          "mass": 1898,
          "thermload": -5000,
          "optmul": 22,
          "optmass": 4,
          "power": -4243
        },
        "blueprint": {
          "fdname": "Engine_Reinforced",
          "grades": {
            "1": {
              "components": {
                "Carbon": 1
              },
              "features": {
                "integrity": [
                  0,
                  0.3
                ],
                "mass": [
                  0.05,
                  0.05
                ],
                "thermload": [
                  -0.1,
                  -0.1
                ]
              },
              "uuid": "21503395-f165-4340-91c7-07d062895eae"
            },
            "2": {
              "components": {
                "Heat Conduction Wiring": 1,
                "Vanadium": 1
              },
              "features": {
                "integrity": [
                  0.3,
                  0.5
                ],
                "mass": [
                  0.1,
                  0.1
                ],
                "thermload": [
                  -0.1,
                  -0.2
                ]
              },
              "uuid": "452e2359-5804-4de1-94bf-d16c9d512cc4"
            },
            "3": {
              "components": {
                "Heat Conduction Wiring": 1,
                "Shielding Sensors": 1,
                "Vanadium": 1
              },
              "features": {
                "integrity": [
                  0.5,
                  0.7
                ],
                "mass": [
                  0.15,
                  0.15
                ],
                "thermload": [
                  -0.2,
                  -0.3
                ]
              },
              "uuid": "ae1a71bb-e025-4268-aa7f-fd4063945beb"
            },
            "4": {
              "components": {
                "Compound Shielding": 1,
                "Heat Dispersion Plate": 1,
                "High Density Composites": 1
              },
              "features": {
                "integrity": [
                  0.7,
                  0.9
                ],
                "mass": [
                  0.2,
                  0.2
                ],
                "thermload": [
                  -0.3,
                  -0.4
                ]
              },
              "uuid": "4bc0b925-dd64-41da-a653-f15acf108f23"
            },
            "5": {
              "components": {
                "Heat Exchangers": 1,
                "Imperial Shielding": 1,
                "Proprietary Composites": 1
              },
              "features": {
                "integrity": [
                  0.9,
                  1.1
                ],
                "mass": [
                  0.25,
                  0.25
                ],
                "thermload": [
                  -0.4,
                  -0.5
                ]
              },
              "uuid": "88aef454-76f6-48a3-a66c-958e50c92e7c"
            }
          },
          "id": 23,
          "modulename": [
            "Thrusters",
            "Engines"
          ],
          "name": "Reinforced",
          "grade": 5,
          "special": {
            "name": "Double Braced",
            "id": 117,
            "edname": "special_engine_toughened",
            "uuid": "41b04d96-0817-479b-92e5-2114de444170"
          }
        }
      },
      "frameShiftDrive": {
        "class": 6,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "modifications": {
          "integrity": 689645,
          "mass": -9500,
          "optmass": -10000,
          "power": -10000,
          "boot": 0,
          "maxfuel": 83443,
          "thermload": 0
        },
        "blueprint": {
          "fdname": "FSD_LongRange",
          "grades": {
            "1": {
              "components": {
                "Atypical Disrupted Wake Echoes": 1
              },
              "features": {
                "integrity": [
                  -0.03,
                  -0.03
                ],
                "mass": [
                  0.1,
                  0.1
                ],
                "optmass": [
                  0,
                  0.15
                ],
                "power": [
                  0.03,
                  0.03
                ]
              },
              "uuid": "bb67b1a2-7a5b-47bc-8ed8-e949b5e3fb16"
            },
            "2": {
              "components": {
                "Atypical Disrupted Wake Echoes": 1,
                "Chemical Processors": 1
              },
              "features": {
                "integrity": [
                  -0.06,
                  -0.06
                ],
                "mass": [
                  0.15,
                  0.15
                ],
                "optmass": [
                  0.15,
                  0.25
                ],
                "power": [
                  0.06,
                  0.06
                ]
              },
              "uuid": "74045351-f348-45f5-8798-487211f19520"
            },
            "3": {
              "components": {
                "Chemical Processors": 1,
                "Phosphorus": 1,
                "Strange Wake Solutions": 1
              },
              "features": {
                "integrity": [
                  -0.09,
                  -0.09
                ],
                "mass": [
                  0.2,
                  0.2
                ],
                "optmass": [
                  0.25,
                  0.35
                ],
                "power": [
                  0.09,
                  0.09
                ]
              },
              "uuid": "cf196bb9-55a1-457f-893b-84ff2afd4db9"
            },
            "4": {
              "components": {
                "Chemical Distillery": 1,
                "Eccentric Hyperspace Trajectories": 1,
                "Manganese": 1
              },
              "features": {
                "integrity": [
                  -0.12,
                  -0.12
                ],
                "mass": [
                  0.25,
                  0.25
                ],
                "optmass": [
                  0.35,
                  0.45
                ],
                "power": [
                  0.12,
                  0.12
                ]
              },
              "uuid": "ecf49fec-32fd-4930-949d-a341bf0fd00c"
            },
            "5": {
              "components": {
                "Arsenic": 1,
                "Chemical Manipulators": 1,
                "Datamined Wake Exceptions": 1
              },
              "features": {
                "integrity": [
                  -0.15,
                  -0.15
                ],
                "mass": [
                  0.3,
                  0.3
                ],
                "optmass": [
                  0.45,
                  0.55
                ],
                "power": [
                  0.15,
                  0.15
                ]
              },
              "uuid": "dddd4fd3-bc9a-4c5b-8606-853c63d0f554"
            }
          },
          "id": 26,
          "modulename": [
            "Frame shift drive",
            "FSD"
          ],
          "name": "Increased range",
          "grade": 5,
          "special": {
            "name": "Deep Charge",
            "id": 119,
            "edname": "special_fsd_fuelcapacity",
            "uuid": "56f1e58d-2044-4a31-8b54-ad0f99dfd64e"
          }
        }
      },
      "lifeSupport": {
        "class": 5,
        "rating": "E",
        "enabled": true,
        "priority": 1
      },
      "powerDistributor": {
        "class": 8,
        "rating": "A",
        "enabled": true,
        "priority": 1
      },
      "sensors": {
        "class": 8,
        "rating": "A",
        "enabled": true,
        "priority": 1
      },
      "fuelTank": {
        "class": 5,
        "rating": "C",
        "enabled": true,
        "priority": 1
      }
    },
    "hardpoints": [
      {
        "class": 3,
        "rating": "C",
        "enabled": true,
        "priority": 1,
        "group": "Shock Cannon",
        "mount": "Fixed"
      },
      {
        "class": 3,
        "rating": "C",
        "enabled": true,
        "priority": 1,
        "group": "Shock Cannon",
        "mount": "Fixed"
      },
      {
        "class": 3,
        "rating": "C",
        "enabled": true,
        "priority": 1,
        "group": "Beam Laser",
        "mount": "Fixed"
      },
      {
        "class": 2,
        "rating": "E",
        "enabled": true,
        "priority": 1,
        "group": "Pulse Laser",
        "mount": "Fixed"
      },
      {
        "class": 2,
        "rating": "E",
        "enabled": true,
        "priority": 1,
        "group": "Pulse Laser",
        "mount": "Fixed"
      },
      {
        "class": 1,
        "rating": "B",
        "enabled": true,
        "priority": 1,
        "group": "Missile Rack",
        "mount": "Fixed",
        "missile": "D"
      },
      {
        "class": 1,
        "rating": "B",
        "enabled": true,
        "priority": 1,
        "group": "Missile Rack",
        "mount": "Fixed",
        "missile": "D"
      }
    ],
    "utility": [
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Point Defence",
        "name": "Point Defence",
        "modifications": {
          "integrity": 30000,
          "mass": 15000
        },
        "blueprint": {
          "fdname": "Misc_Reinforced",
          "grades": {
            "1": {
              "components": {
                "Nickel": 1
              },
              "features": {
                "integrity": [
                  0,
                  0.6
                ],
                "mass": [
                  0.3,
                  0.3
                ]
              },
              "uuid": "9b714883-e0e7-46b5-a2bb-5367f2cc9b3f"
            },
            "2": {
              "components": {
                "Nickel": 1,
                "Shield Emitters": 1
              },
              "features": {
                "integrity": [
                  0.6,
                  1.2
                ],
                "mass": [
                  0.6,
                  0.6
                ]
              },
              "uuid": "9de3e096-fbfa-4694-a2e4-919494d39ee1"
            },
            "3": {
              "components": {
                "Nickel": 1,
                "Shield Emitters": 1,
                "Tungsten": 1
              },
              "features": {
                "integrity": [
                  1.2,
                  1.8
                ],
                "mass": [
                  0.9,
                  0.9
                ]
              },
              "uuid": "4a5d7441-2543-4405-8587-9b969fffd3f2"
            },
            "4": {
              "components": {
                "Molybdenum": 1,
                "Tungsten": 1,
                "Zinc": 1
              },
              "features": {
                "integrity": [
                  1.8,
                  2.4
                ],
                "mass": [
                  1.2,
                  1.2
                ]
              },
              "uuid": "f4b41ce9-d3a8-4362-9821-0d45f2b975bc"
            },
            "5": {
              "components": {
                "High Density Composites": 1,
                "Molybdenum": 1,
                "Technetium": 1
              },
              "features": {
                "integrity": [
                  2.4,
                  3
                ],
                "mass": [
                  1.5,
                  1.5
                ]
              },
              "uuid": "d5d06450-a1cf-4dd2-b8f0-12d0142ad773"
            }
          },
          "id": 10,
          "modulename": [
            "Chaff launcher",
            "Electronic counter measures",
            "ECM",
            "Wake scanner",
            "Frame shift wake scanner",
            "Heat sink launcher",
            "Kill warrant scanner",
            "KWS",
            "Cargo scanner",
            "Manifest scanner",
            "Point defence"
          ],
          "name": "Reinforced",
          "grade": 5
        }
      },
      {
        "class": 0,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Kill Warrant Scanner"
      },
      {
        "class": 0,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Shield Booster"
      },
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Heat Sink Launcher",
        "name": "Heat Sink Launcher"
      },
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Point Defence",
        "name": "Point Defence"
      },
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Point Defence",
        "name": "Point Defence"
      },
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Point Defence",
        "name": "Point Defence"
      },
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Point Defence",
        "name": "Point Defence"
      }
    ],
    "internal": [
      {
        "class": 7,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Fuel Scoop"
      },
      {
        "class": 7,
        "rating": "D",
        "enabled": true,
        "priority": 1,
        "group": "Fighter Hangar"
      },
      {
        "class": 7,
        "rating": "E",
        "enabled": true,
        "priority": 1,
        "group": "Cargo Rack"
      },
      null,
      null,
      {
        "class": 4,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Frame Shift Drive Interdictor"
      },
      {
        "class": 5,
        "rating": "D",
        "enabled": true,
        "priority": 1,
        "group": "Guardian Shield Reinforcement Packages"
      },
      {
        "class": "5",
        "rating": "D",
        "enabled": true,
        "priority": 1,
        "group": "Guardian Module Reinforcement Package"
      },
      {
        "class": "5",
        "rating": "D",
        "enabled": true,
        "priority": 1,
        "group": "Guardian Module Reinforcement Package"
      },
      {
        "class": 4,
        "rating": "C",
        "enabled": true,
        "priority": 1,
        "group": "Fuel Tank"
      },
      {
        "class": 4,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Frame Shift Drive Interdictor",
        "modifications": {
          "facinglimit": -2500,
          "mass": 2500,
          "power": 4000,
          "ranget": 5000
        },
        "blueprint": {
          "fdname": "FSDinterdictor_LongRange",
          "grades": {
            "1": {
              "components": {
                "Unusual Encrypted Files": 1
              },
              "features": {
                "facinglimit": [
                  -0.01,
                  -0.01
                ],
                "mass": [
                  0.1,
                  0.1
                ],
                "power": [
                  0.1,
                  0.1
                ],
                "ranget": [
                  0,
                  0.2
                ]
              },
              "uuid": "ecec8b3e-891f-4b79-8c07-7836e62424f8"
            },
            "2": {
              "components": {
                "Atypical Disrupted Wake Echoes": 1,
                "Tagged Encryption Codes": 1
              },
              "features": {
                "facinglimit": [
                  -0.15,
                  -0.15
                ],
                "mass": [
                  0.15,
                  0.15
                ],
                "power": [
                  0.2,
                  0.2
                ],
                "ranget": [
                  0.2,
                  0.3
                ]
              },
              "uuid": "08d02c88-e63f-4d29-86b9-eea6a20b17a1"
            },
            "3": {
              "components": {
                "Anomalous Bulk Scan Data": 1,
                "Anomalous FSD Telemetry": 1,
                "Open Symmetric Keys": 1
              },
              "features": {
                "facinglimit": [
                  -0.2,
                  -0.2
                ],
                "mass": [
                  0.2,
                  0.2
                ],
                "power": [
                  0.3,
                  0.3
                ],
                "ranget": [
                  0.3,
                  0.4
                ]
              },
              "uuid": "a2d4bed7-4326-4776-a17b-6ee746f4c9be"
            },
            "4": {
              "components": {
                "Unidentified Scan Archives": 1,
                "Strange Wake Solutions": 1,
                "Atypical Encryption Archives": 1
              },
              "features": {
                "facinglimit": [
                  -0.25,
                  -0.25
                ],
                "mass": [
                  0.25,
                  0.25
                ],
                "power": [
                  0.4,
                  0.4
                ],
                "ranget": [
                  0.4,
                  0.5
                ]
              },
              "uuid": "aaabe016-883e-4ec6-a0f0-dd519b4f0ca5"
            }
          },
          "id": 29,
          "modulename": [
            "Frame shift drive interdictor",
            "FSDI"
          ],
          "name": "Long range",
          "grade": 4
        }
      },
      {
        "class": 1,
        "rating": "E",
        "enabled": true,
        "priority": 1,
        "group": "Docking Computer",
        "name": "Advanced Docking Computer"
      },
      {
        "class": 1,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Surface Scanner",
        "name": "Detailed Surface Scanner",
        "modifications": {
          "mass": 10000,
          "proberadius": 5000
        },
        "blueprint": {
          "fdname": "Sensor_Expanded",
          "grades": {
            "1": {
              "components": {
                "Phosphorus": 1
              },
              "features": {
                "mass": [
                  0.2,
                  0.2
                ],
                "proberadius": [
                  0,
                  0.1
                ]
              },
              "uuid": "d2f404d2-a8b9-4dfb-ae3c-43f0208123cb"
            },
            "2": {
              "components": {
                "Flawed Focus Crystals": 1,
                "Phosphorus": 1
              },
              "features": {
                "mass": [
                  0.4,
                  0.4
                ],
                "proberadius": [
                  0.1,
                  0.2
                ]
              },
              "uuid": "2a077c82-5671-4c22-b3cb-caff4979c644"
            },
            "3": {
              "components": {
                "Flawed Focus Crystals": 1,
                "Open Symmetric Keys": 1,
                "Phosphorus": 1
              },
              "features": {
                "mass": [
                  0.6,
                  0.6
                ],
                "proberadius": [
                  0.2,
                  0.3
                ]
              },
              "uuid": "081990f9-99d3-435a-9428-ad26471576de"
            },
            "4": {
              "components": {
                "Atypical Encryption Archives": 1,
                "Focus Crystals": 1,
                "Manganese": 1
              },
              "features": {
                "mass": [
                  0.8,
                  0.8
                ],
                "proberadius": [
                  0.3,
                  0.4
                ]
              },
              "uuid": "aa10c84d-1409-48d5-ac02-d0a100d27555"
            },
            "5": {
              "components": {
                "Adaptive Encryptors Capture": 1,
                "Arsenic": 1,
                "Refined Focus Crystals": 1
              },
              "features": {
                "mass": [
                  1,
                  1
                ],
                "proberadius": [
                  0.4,
                  0.5
                ]
              },
              "uuid": "ea7dfe28-95d0-4939-bcf2-282dbed7d80f\n"
            }
          },
          "id": 93,
          "modulename": [
            "Detailed surface scanner",
            "DSS"
          ],
          "name": "Expanded Probe Scanning Radius",
          "grade": 5
        }
      }
    ]
  },
  "stats": {
    "class": 3,
    "hullCost": 182589570,
    "speed": 200,
    "boost": 260,
    "boostEnergy": 27,
    "baseShieldStrength": 555,
    "baseArmour": 370,
    "hardness": 70,
    "hullMass": 900,
    "masslock": 24,
    "heatCapacity": 333,
    "pipSpeed": 0.13,
    "fighterHangars": 1,
    "pitch": 28,
    "roll": 75,
    "yaw": 8,
    "crew": 3,
    "moduleCostMultiplier": 1,
    "fuelCapacity": 48,
    "cargoCapacity": 128,
    "passengerCapacity": 0,
    "ladenMass": 1752.24,
    "armour": 11246.17,
    "shield": 0,
    "shieldCells": 0,
    "totalCost": 1055777319,
    "unladenMass": 1576.24,
    "totalDpe": 475.07,
    "totalAbsDpe": 0,
    "totalExplDpe": 416.67,
    "totalKinDpe": 39.35,
    "totalThermDpe": 19.05,
    "totalDps": 461.92,
    "totalAbsDps": 0,
    "totalExplDps": 50,
    "totalKinDps": 362,
    "totalThermDps": 49.92,
    "totalSDps": 164.22,
    "totalAbsSDps": 0,
    "totalExplSDps": 38.1,
    "totalKinSDps": 76.21,
    "totalThermSDps": 49.92,
    "totalEps": 27.19,
    "totalHps": 68.66,
    "shieldExplRes": 0,
    "shieldKinRes": 0,
    "shieldThermRes": 0,
    "hullExplRes": 250.15,
    "hullKinRes": 0.43,
    "hullThermRes": 2.4,
    "powerAvailable": 941.18,
    "powerRetracted": 18.01,
    "powerDeployed": 26.61,
    "unladenRange": 0,
    "fullTankRange": 0,
    "ladenRange": 0,
    "unladenFastestRange": 0,
    "ladenFastestRange": 0,
    "maxJumpCount": 1,
    "modulearmour": 770,
    "moduleprotection": 0.84,
    "hullCausRes": 0,
    "topSpeed": 212.87,
    "topBoost": 276.73,
    "topPitch": 29.8,
    "topRoll": 79.83,
    "topYaw": 8.51
  }
}

**Comment by robbyxp1** [comment]
Done. Basic output for now
