### ISSUE TITLE
Tool start stresses HDD to 100% and is taking ~15min to be responsive

### ISSUE THREAD

**Issue by Vorkosik** [EDDiscovery/EDDiscovery#2654]
Hello,
and first: thank you for this great tool!
Sadly, I have a small issue, analog to issue no. #2637 my instance of EDDiscovery pushes the disc activity to 100% (db storage partition "I:\") for ca. 15min before anything related to the program becomes responsive. I already rebuild the database two times, but unfortunately that did not help. Before the rewrite (version 10.x ?) this problem was not existing and for the upgrade I also rebuild the database as recommended.
Maybe there is something that I can test to help identify the problem?

Anyways, I really appreciate all the work that went into EDD and wish you ongoing success with its development!

**System:**
Windows 10, Ryzen 1700X CPU, 16 GB RAM
Currently using EDDiscovery version 11.1.2.0

**Comment by robbyxp1** [comment]
Try rebuilding the system db indexes - use the admin tool.  Thats the only thing I can think of trying.

If that does not work, does it work if you delete (or just rename) the eddsystem.sqlite file (in your appdata/local/eddiscovery folder) and then selected 'None' as the systems to be stored when it asks you next time you run..

**Comment by Vorkosik** [comment]
I think the system db index rebuild did the trick for the responsiveness! :)
Disk activity is still ramping up to ca. 98%, put the EDDiscovery window is now usable again from the start!

**Comment by Vorkosik** [comment]
Yesterday the index rebuild did help to recover responsiveness, but today it is back to being unresponsive after start (until some time later) -.-
I'm now trying your other method (deleting/renaming the eddsystem.sqlite file).

**Comment by klightspeed** [comment]
Loading systems from EDSM does a lot of seeks, and will perform poorly on a HDD or SSHD.

If you don't want to load EDSM systems, then uncheck the `Enable Star Data Download` checkbox on the Settings tab.

**Comment by robbyxp1** [comment]
Closing now, if you have any specific problems please open another ticket.
