### ISSUE TITLE
Fatal error upon app start

### ISSUE THREAD

**Issue by ruicabanita** [EDDiscovery/EDDiscovery#2655]
### Description

was just in ED in supercruise, nothing special
### Exception Details:
>EDDiscovery v10.6.0.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>code = CantOpen (14), message = System.Data.SQLite.SQLiteException (0x800007FF): unable to open database file
>   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
>   at System.Data.SQLite.SQLiteConnection.Open()
>   at SQLLiteExtensions.SQLExtConnectionWithLock`1..ctor(String dbfile, Boolean utctimeindicator, Action initializercallback, AccessMode mode) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnectionLock.cs:line 81
>   at EliteDangerousCore.DB.SQLiteConnectionUser.<>c.<Initialize>b__4_0() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionUser.cs:line 46
>   at SQLLiteExtensions.SQLExtConnectionWithLock`1.InitializeIfNeeded(Action initializer) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnectionLock.cs:line 189
>   at EDDiscovery.EDDiscoveryController.InitializeDatabases() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 383
>   at EDDiscovery.EDDiscoveryController.Initialize(Action`1 msg) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 139
>   at EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:line 137
>===== END =====
>```

**Comment by klightspeed** [comment]
Is the user database redirected to another drive?  If so, is that drive connected?

`CantOpen` usually means that the directory the database file is in isn't writable or doesn't exist.

**Comment by ruicabanita** [comment]
That C:\Code\EDDiscovery it seems to be pointing at, doesn't exist. Tried EDD's safe mode but no luck there either, it said that I had to start EDD once to create the DB.

In the end, I uninstalled, cleaned the registry and every folder I could find related to EDD and made a fresh install, which fixed the issue.

**Comment by klightspeed** [comment]
`C:\Code\EDDiscovery` is the path on the developer's computer where the program was built.

My guess is that either the permissions on the EDDiscovery directory were wrong, or the DB had been redirected to a location that no longer exists.
