### ISSUE TITLE
unhandled UI exception

### ISSUE THREAD

**Issue by Hellrider88** [EDDiscovery/EDDiscovery#2658]
### Exception Details:
>EDDiscovery v11.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>SQLLiteExtensions.SQLProcessingThreadException: SQL logic error
>no such column: s.edsmid ---> System.Data.SQLite.SQLiteException: SQL logic error
>no such column: s.edsmid
>   w System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   w System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   w System.Data.SQLite.SQLiteDataReader.NextResult()
>   w System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   w System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   w EliteDangerousCore.DB.SystemsDB.FindStar(String name, SQLiteConnectionSystem cn) w C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDBGetStars.cs:wiersz 47
>   w EliteDangerousCore.DB.SystemCache.FindSystem(ISystem find, SystemsDatabaseConnection cn) w C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemCache.cs:wiersz 110
>   w SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() w C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:wiersz 66
>   --- Koniec śladu stosu wyjątków wewnętrznych ---
>   w SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() w C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:wiersz 89
>   w SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) w C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:wiersz 158
>   w SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase[T](Func`2 func, Int32 warnthreshold) w C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:wiersz 177
>   w EDDiscovery.UserControls.UserControlExpedition.dataGridViewRouteSystems_CellValidating(Object sender, DataGridViewCellValidatingEventArgs e) w C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlExpedition.cs:wiersz 1008
>   w System.Windows.Forms.DataGridView.OnCellValidating(DataGridViewCellValidatingEventArgs e)
>   w System.Windows.Forms.DataGridView.OnCellValidating(DataGridViewCell& dataGridViewCell, Int32 columnIndex, Int32 rowIndex, DataGridViewDataErrorContexts context)
>   w System.Windows.Forms.DataGridView.CommitEdit(DataGridViewCell& dataGridViewCurrentCell, DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave)
>   w System.Windows.Forms.DataGridView.CommitEdit(DataGridViewDataErrorContexts context, Boolean forCurrentCellChange, Boolean forCurrentRowChange)
>   w System.Windows.Forms.DataGridView.OnCellMouseDown(HitTestInfo hti, Boolean isShiftDown, Boolean isControlDown)
>   w System.Windows.Forms.DataGridView.OnCellMouseDown(DataGridViewCellMouseEventArgs e)
>   w System.Windows.Forms.DataGridView.OnMouseDown(MouseEventArgs e)
>   w System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
>   w System.Windows.Forms.Control.WndProc(Message& m)
>   w System.Windows.Forms.DataGridView.WndProc(Message& m)
>   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
My analysis was this occurred during a system db rebuild, or your system db is corrupted.

If it works okay now, its during the former.  If not, rebuild your system db using safe mode to delete the db (see settings page) and let it rebuild.

I've added additional protection for the system db rebuild.

thanks for the report.
