### ISSUE TITLE
Feature request: add fullscreen toggle on web server pages

### ISSUE THREAD

**Issue by tecnosegugio** [EDDiscovery/EDDiscovery#2661]
On a tablet every cm of screen space is useful and the address bar of the browser it's a big waste of space.
It would be a very nice feature if we can toggle a "fullscreen" view on pages served from the embedeed  web server in EDdiscovery. 
Fullscreen on a browser MUST follow an user action, it can't be enabled at page load time, so we need a button that start a javascript like this: https://gist.github.com/demonixis/5188326

**Comment by robbyxp1** [comment]
okay, i'll give it a look.
