### ISSUE TITLE
Incorrect assumption of combat rank on interdiction

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#2668]
![edd](https://user-images.githubusercontent.com/38956076/70818508-ccd06f00-1dcb-11ea-8fab-b677745e25e6.png)

In the first entry of the screenshot, the NPC rank is given as harmless. This is incorrect and an assumption without evidence, as the log entry shows:

``
{
  "timestamp": "2019-12-13T17:01:34Z",
  "event": "Interdicted",
  "Submitted": true,
  "Interdictor": "Wendy Purelight",
  "IsPlayer": false,
  "Faction": "Aristocrats of Dharawal"
}
``

The second entry correctly shows the NPC rank. In this case it does appear in the log.

``
{
  "timestamp": "2019-12-13T17:01:36Z",
  "event": "ShipTargeted",
  "TargetLocked": true,
  "Ship": "typex",
  "Ship_Localised": "Alliance Chieftain",
  "ScanStage": 3,
  "PilotName": "$npc_name_decorate:#name=Wendy Purelight;",
  "PilotName_Localised": "Wendy Purelight",
  "PilotRank": "Master",
  "ShieldHealth": 100.0,
  "HullHealth": 100.0,
  "Faction": "Aristocrats of Dharawal",
  "LegalStatus": "Wanted",
  "Bounty": 128467
}
``

As interdictions (apparently) don't show the rank in the log entry, the assumed harmless probably should also not be showing in the information field of the history tab.

**Comment by klightspeed** [comment]
What version are you using?

This should have been fixed in #2143 (included in 10.2.1)

Combat rank should be getting set to `Unknown` if not set.

**Comment by Tromador** [comment]
Version 11.1.2.0
