### ISSUE TITLE
Make the matching better in System Class between VSC and Db

### ISSUE THREAD

**Issue by robbyxp1** [EDDiscovery/EDDiscovery#267]
FillVisitedSystems... 

search for name
if select returns more than 1
    pick the entry which has the best x/y/z to the VSC x/y/z
    if VSC does not have a x/y/z or x/y/z does not match
         mark as ambiguous in memory
    show on screen somehow its ambiguous

**Comment by robbyxp1** [comment]
VisitedSystem: FillVisitedSystems

VisitedSystems has a in memory only entry - alt_name (or something like that)

search for name
    if 1 name match
        if VSC has x/y/z
            if VSC x/y/z != db x/y/z
                search for star at x/y/z
                    if match
                    {
                        vsc.alt_name = "(" vsc.cur_name ")"
                        vcs.cur_name = eddb.name
                        update database
                    }
            else
                star found
        else
            star found


    if >1 name match
        if VSC has x/y/z
            search for best x/y/z

            if match x/y/z
                vsc.alt_name = "(" vsc.cur_name ")"
                vcs.cur_name = eddb.name
                update database
            else
                vsc.alt_name = "(Not Found)"

        else
            vcs.alt_name = "(Ambiguous)"


Right Click - Rename
    allow a rename

Right Click - find alternates
    if VSC has x/y/z
        present list of stars at x/y/z and allow a rename

**Comment by klightspeed** [comment]
If the VisitedSystem is newer than the db entry, shouldn't the vsc name override the db name?

**Comment by robbyxp1** [comment]
good point. Can't decide.  here is a better logic but without an auto rename.

VisitedSystem: FillVisitedSystems

VisitedSystems has a new in memory only entry - alt_name - tells you the results.. user decides what to do.

in memory since we want to do this every time in case the db has more stars..

search for name
    if 0 match
        if VSC has x/y/z
                search for star at x/y/z
                    if match
                    {
                        vsc.alt_name = "EDSM(" db name ")"
                    }

    if 1 name match
        if VSC has x/y/z
            if VSC x/y/z != db x/y/z
                search for star at x/y/z
                    if match
                        vsc.alt_name = "EDSM(" db name ")"

                    no star match (so the dummy is created at the right position)
            else
                star found
        else
            star found


    if >1 name match
        if VSC has x/y/z
            search for best x/y/z

            if match x/y/z
                vsc.alt_name = "EDSM(" db name ")"

            no star match (so the dummy is created at the right position)

        else
            vcs.alt_name = "(Ambiguous)"


Right Click - Rename
    allow a rename

Right Click - find alternates
    if VSC has x/y/z
        present list of stars at x/y/z and allow a rename

**Comment by robbyxp1** [comment]
think it needs more thoughts

**Comment by robbyxp1** [comment]
Another thought.. with a new field

VisitedSystem: FillVisitedSystems

VisitedSystems has a new entry - assigned_id_edsm
and an in memory indicate, namestatus

if vsc.assigned_id_edsm
    look up id_edsm (new index)
    if names differ
            namestatus = "Assigned EDSM system not the same"            (due to a rename, use find alternatives to fix)
            no star match
    if VSC has x/y/z
        if db does not match x/y/z                                      (due to a move.. VSC is the cannocial source)
            namestatus = "Assigned EDSM system not at correct x/y/z"    (use find alternatives to fix)
            no star match
        else
            star found
    else
        star found - use assigned_edsm_id as the star position.
else
    search for name

    if 0 match
        if VSC has x/y/z
            search for star at x/y/z
            if db match
                  vsc.alt_name = "EDSM(" db name ")"                   (use find alternatives to change the name - name change)
            no star match

    if 1 name match
        if VSC has x/y/z
            if VSC x/y/z != db x/y/z
                search for star at x/y/z
                    if match
                        vsc.alt_name = "Position differ to " db name ")"     (EDSM entry not at VSC, either leave alone or find alternatives)

                    no star match
            else
                star found
        else
            star found


    if >1 name match
        if VSC has x/y/z
            search for best x/y/z

            if match x/y/z
                vsc.alt_name = "Best match " db name ""                 (use find alternatives to set assigned_idsm_id)
        else
            vcs.alt_name = "(Ambiguous)"


Right Click - Rename
    allow a rename

Right Click - find alternates
    if VSC has x/y/z
        present list of stars at x/y/z
        on selection, set assigned_edsm_id to selected star.
        set vsc name to selected star

**Comment by robbyxp1** [comment]
`VisitedSystem: FillVisitedSystems

VisitedSystems has a new entry - assigned_id_edsm
and an in memory indicate, namestatus

if vsc.assigned_id_edsm
    look up id_edsm (new index)
    if names differ
            namestatus = "Assigned EDSM system not the same"            (due to a rename, use find alternatives to fix)
            no star match
    if VSC has x/y/z
        if db does not match x/y/z                                      (due to a move.. VSC is the cannocial source)
            namestatus = "Assigned EDSM system not at correct x/y/z"    (use find alternatives to fix)
            no star match
        else
            star found
    else
        star found - use assigned_edsm_id as the star position.
else
    search for name

    if 0 match
        if VSC has x/y/z
            search for star at x/y/z
            if db match
                  vsc.alt_name = "EDSM(" db name ")"                   (use find alternatives to change the name - name change)
            no star match

    if 1 name match
        if VSC has x/y/z
            if VSC x/y/z != db x/y/z
                search for star at x/y/z
                    if match
                        vsc.alt_name = "Position differ to " db name ")"     (EDSM entry not at VSC, either leave alone or find alternatives)

                    no star match
            else
                star found
        else
            star found


    if >1 name match
        if VSC has x/y/z
            search for best x/y/z

            if match x/y/z
                vsc.alt_name = "Best match " db name ""                 (use find alternatives to set assigned_idsm_id)
        else
            vcs.alt_name = "(Ambiguous)"


Right Click - Rename
    allow a rename

Right Click - find alternates
    if VSC has x/y/z
        present list of stars at x/y/z
        on selection, set assigned_edsm_id to selected star.
        set vsc name to selected star
`

**Comment by robbyxp1** [comment]
```
VisitedSystem: FillVisitedSystems

VisitedSystems has a new entry - assigned_id_edsm
and an in memory indicate, namestatus

if vsc.assigned_id_edsm
    look up id_edsm (new index)
    if names differ
            namestatus = "Assigned EDSM system not the same"            (due to a rename, use find alternatives to fix)
            no star match
    if VSC has x/y/z
        if db does not match x/y/z                                      (due to a move.. VSC is the cannocial source)
            namestatus = "Assigned EDSM system not at correct x/y/z"    (use find alternatives to fix)
            no star match
        else
            star found
    else
        star found - use assigned_edsm_id as the star position.
else
    search for name

    if 0 match
        if VSC has x/y/z
            search for star at x/y/z
            if db match
                  vsc.alt_name = "EDSM(" db name ")"                   (use find alternatives to change the name - name change)
            no star match

    if 1 name match
        if VSC has x/y/z
            if VSC x/y/z != db x/y/z
                search for star at x/y/z
                    if match
                        vsc.alt_name = "Position differ to " db name ")"     (EDSM entry not at VSC, either leave alone or find alternatives)

                    no star match
            else
                star found
        else
            star found


    if >1 name match
        if VSC has x/y/z
            search for best x/y/z

            if match x/y/z
                vsc.alt_name = "Best match " db name ""                 (use find alternatives to set assigned_idsm_id)
        else
            vcs.alt_name = "(Ambiguous)"


Right Click - Rename
    allow a rename

Right Click - find alternates
    if VSC has x/y/z
        present list of stars at x/y/z
        on selection, set assigned_edsm_id to selected star.
        set vsc name to selected star

```

**Comment by robbyxp1** [comment]
Implemented by Ben.
