### ISSUE TITLE
ARX on EDDiscovery

### ISSUE THREAD

**Issue by Jibsman** [EDDiscovery/EDDiscovery#2671]
Can you see your ARX balance on EDDiscovery? I couldn't find anything in Help. If not, will it be added some time in the future?
Cheers and thanks for a great product!
Happy Daze

**Comment by klightspeed** [comment]
The ARX balance is not written to the journal and not exposed through the Companion API, so it is not possible for EDDiscovery to display it.

**Comment by robbyxp1** [comment]
Thanks but we can't help.
