### ISSUE TITLE
can't filter history

### ISSUE THREAD

**Issue by aldobro19** [EDDiscovery/EDDiscovery#2678]
### Description
Clicking the history filter.

### Exception Details:
>EDDiscovery v11.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: Form that is already visible cannot be displayed as a modal dialog box. Set the form's visible property to false before calling Show.
>   at System.Windows.Forms.Form.Show(IWin32Window owner)
>   at EDDiscovery.UserControls.FilterSelector.Filter(Control ctr, Form parent) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\Filter.cs:line 99
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by aldobro19** [comment]
Seems to be when getting data from EDSM? Works after a restart. 🤷‍♂

**Comment by aldobro19** [comment]
Just make a better UI already.

**Comment by klightspeed** [comment]
That sounds like the filter window is being opened multiple times.  My guess is that it was being shown but not activated, and so OnDeactivate wasn't hiding it.
