### ISSUE TITLE
cant open 3D Map 

### ISSUE THREAD

**Issue by NYC00kie** [EDDiscovery/EDDiscovery#2679]
### Description
 I clicked the Button for the 3D Map

### Exception Details:
EDDiscovery v11.1.2.0 There was an unhandled UI exception.
>==== BEGIN ====
>SQLLiteExtensions.SQLProcessingThreadException: SQL logic error
>no such column: s.edsmid ---> System.Data.SQLite.SQLiteException: SQL logic error
>no such column: s.edsmid
>   bei System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   bei System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   bei System.Data.SQLite.SQLiteDataReader.NextResult()
>   bei System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   bei System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   bei EliteDangerousCore.DB.SystemsDB.FindStar(String name, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDBGetStars.cs:Zeile 47.
>   bei EliteDangerousCore.DB.SystemCache.FindSystem(ISystem find, SystemsDatabaseConnection cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemCache.cs:Zeile 110.
>   bei SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:Zeile 66.
>   --- Ende der internen Ausnahmestapelüberwachung ---
>   bei SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:Zeile 89.
>   bei SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:Zeile 158.
>   bei SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase[T](Func`2 func, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:Zeile 177.
>   bei EDDiscovery.FormMap.FindSystem(String name) in C:\Code\EDDiscovery\EDDiscovery\3DMap\FormMap.cs:Zeile 2166.
>   bei EDDiscovery.FormMap.Prepare(ISystem historysel, String homesys, ISystem centersys, Single zoom, List`1 visited) in C:\Code\EDDiscovery\EDDiscovery\3DMap\FormMap.cs:Zeile 135.
>   bei EDDiscovery.EDDiscoveryForm.Open3DMap(HistoryEntry he) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:Zeile 1107.
>   bei System.Windows.Forms.Control.OnClick(EventArgs e)
>   bei System.Windows.Forms.Button.OnClick(EventArgs e)
>   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   bei System.Windows.Forms.Control.WndProc(Message& m)
>   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   bei System.Windows.Forms.Button.WndProc(Message& m)
>   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Please hold down shift, run EDD, safe mode will open, and delete the system db. It's got itself corrupted, maybe during updating from previous versions.

Let it rebuild and it will be ok.
