### ISSUE TITLE
Web server doesn't start (possibly for Windows usernames with spaces in it)

### ISSUE THREAD

**Issue by Devil-Boy** [EDDiscovery/EDDiscovery#2681]
I attempted to start the web server using the instructions here:
https://github.com/EDDiscovery/EDDiscovery/wiki/Web-Server#turning-on-web-server

After checking the box, I hit "yes" and granted Administrator privileges.
However, after Powershell finished, I received "Did not start - click OK to configure windows" and the checkbox remained unchecked (leaving the "Test" button unclickable.

I checked the Windows firewall and saw the expected firewall rule was in there.

I dug in the code a bit and found in UserControlSettings.cs that two separate PowerShell commands are run: one that sets the firewall rule and one for urlacls.

I found that manually running the second in PowerShell (as administrator) resolved the problem for me:
`netsh http add urlacl url = http://*:6502/ user="Devil Boy"`

I honestly can't tell what the command EDDiscovery attempts is, but I suspect that this may have occured because my Windows username has a space in it.

Please let me now if I can provide any further information.

**Comment by klightspeed** [comment]
PR 2682 should fix this.

Since you have now set up the URL ACL and firewall rule, you can click No when it asks you if you want it to set up the firewall rule.
