### ISSUE TITLE
unhandled UI exception

### ISSUE THREAD

**Issue by batkung** [EDDiscovery/EDDiscovery#2684]
### Exception Details:
>EDDiscovery v11.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.StarScan.FindSystemNode(ISystem sys) in C:\Code\EDDiscovery\EliteDangerous\ScarScan\StarScanHelpers.cs:line 149
>   at EliteDangerousCore.StarScan.FindSystem(ISystem sys, Boolean edsmweblookup, Boolean byname) in C:\Code\EDDiscovery\EliteDangerous\ScarScan\StarScan.cs:line 264
>   at EDDiscovery.UserControls.UserControlSurveyor.DrawSystem(ISystem sys, String tt) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSurveyor.cs:line 222
>   at EDDiscovery.UserControls.UserControlSurveyor.Discoveryform_OnNewUIEvent(UIEvent uievent) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSurveyor.cs:line 175
>   at System.Action`1.Invoke(T obj)
>   at EliteDangerousCore.EDJournalClass.UIEventPost(ConcurrentQueue`1 events) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 335
>===== END =====
>```

**Comment by batkung** [comment]
seems this happens every time I have the surveyor window popped out and EDD tries to write to it, if I have another window popped out then the info in that window is updated and displayed correctly.

**Comment by robbyxp1** [comment]
I've found it, thanks for the report, hopefully the new version will be out in the next day or so.

**Comment by robbyxp1** [comment]
Try 11.1.3 ;-)
