### ISSUE TITLE
EDSM Full Sync is failing - 11.1.4 fixes it. Full Sync from EDSM uses invalid URL

### ISSUE THREAD

**Issue by imathrowback** [EDDiscovery/EDDiscovery#2686]
The default full system url for the property `EliteConfigInstance.InstanceConfig.EDSMFullSystemsURL` uses [this URL](https://www.edsm.net/dump/systemsWithCoordinates.json) which is not valid (it returns 404)

The [correct url](https://www.edsm.net/dump/systemsWithCoordinates.json.gz) appears to be GZIP as shown on [the nightly dump page](https://www.edsm.net/en/nightly-dumps)

The property should be updated and the function `EliteDangerousCore.DB.SystemsDB.ParseEDSMJSONFile` should be updated to wrap it's stream reading in a `GZipStream` class to decompress it on the fly (so it isn't decompressed on disk first)

PS: It would also be nice to get a progress reading of this as well as it could take a while

**Comment by klightspeed** [comment]
The sync was changed from uncompressed to gzip compressed without any warning a few days ago.

**Comment by imathrowback** [comment]
I created a pull request #2687 for my own purposes.

It only fixes the URL now, but it might be worth coding something a bit more flexible in the future.

**Comment by robbyxp1** [comment]
Even grabbing the url from say github dynamically would not have helped if the encoding changes..  I think we will just incorporate your change. thanks

**Comment by robbyxp1** [comment]
Update in thanks

**Comment by robbyxp1** [comment]
Update to 11.1.4 to fix this.
