### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AtariSenpai** [EDDiscovery/EDDiscovery#2688]
### Exception Details:
>EDDiscovery v11.1.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
>no such column: s.edsmid
>   в System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   в System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   в System.Data.SQLite.SQLiteDataReader.NextResult()
>   в System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   в System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   в EliteDangerousCore.DB.SystemsDB.FindStar(String name, SQLiteConnectionSystem cn) в C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDBGetStars.cs:строка 47
>   в EliteDangerousCore.DB.SystemCache.FindSystem(ISystem find, SystemsDatabaseConnection cn) в C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemCache.cs:строка 110
>   в SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() в C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:строка 66
>===== END =====
>```

**Comment by robbyxp1** [comment]
If it still happens on running it again, 

Delete the system db using safe mode (see settings) and rebuild the system db.
