### ISSUE TITLE
v11.1.3.0 Fatal Error

### ISSUE THREAD

**Issue by HannaHunter** [EDDiscovery/EDDiscovery#2689]
`An unhandled fatal exception has occurred.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: database disk image is malformed
database disk image is malformed ---> System.Data.SQLite.SQLiteException: database disk image is malformed
database disk image is malformed
   à System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   à System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   à System.Data.SQLite.SQLiteDataReader.NextResult()
   à System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   à System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   à System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   à SQLLiteExtensions.SQLExtConnection.ExecuteNonQuery(String query) dans C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnection.cs:ligne 237
   à SQLLiteExtensions.SQLExtConnection.ExecuteNonQueries(String[] queries) dans C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnection.cs:ligne 230
   à SQLLiteExtensions.SQLProcessingThread`1.<>c__DisplayClass15_0.<ExecuteWithDatabase>b__0() dans C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:ligne 172
   à SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() dans C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:ligne 66
   --- Fin de la trace de la pile d'exception interne ---
   à SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() dans C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:ligne 89
   à SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) dans C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:ligne 158
   à SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase(Action`1 action, Int32 warnthreshold) dans C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:ligne 173
   à EliteDangerousCore.DB.SystemsDatabase.UpgradeSystemTableFrom102TypeDB(Func`1 cancelRequested, Action`1 reportProgress, Boolean fullsyncrequested) dans C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDatabase.cs:ligne 186
   à EDDiscovery.EDDiscoveryController.DoPerformSync() dans C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerSync.cs:ligne 107
   à EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() dans C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerMain.cs:ligne 310
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()
===== END =====`

**Comment by HannaHunter** [comment]
Deleting EDDSystem.sqlite seemed to fix this problem

**Comment by robbyxp1** [comment]
sometime SQLLite just messes up.. even though we reworked the whole db.
