### ISSUE TITLE
unhandled UI exception - awaiting details

### ISSUE THREAD

**Issue by qthermal** [EDDiscovery/EDDiscovery#2692]
### Description
Toggling between windows. EDDiscovery was minimized.

### Exception Details:
>EDDiscovery v11.1.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at ExtendedControls.ExtPictureBox.AddTextAutoSize(Point topleft, Size max, String label, Font fnt, Color c, Color backcolour, Single backscale, Object tag, String tiptext, StringFormat frmt) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\PictureBox.cs:line 188
>   at EDDiscovery.UserControls.UserControlTrippanel.DisplayState(HistoryEntry he, HistoryEntry lastfsd) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlTrippanel.cs:line 159
>   at EDDiscovery.UserControls.UserControlTrippanel.Display(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlTrippanel.cs:line 120
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshCompleteonUI(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 192
>===== END =====
>```

**Comment by klightspeed** [comment]
This suggests a use after dispose, which suggests that event handlers aren't being unsubscribed in UserControlTrippanel when the panel is closed.

**Comment by robbyxp1** [comment]
Closing, no user response.

**Comment by qthermal** [comment]
How does one prevent it?

**Comment by klightspeed** [comment]
Is the trip panel in a popout, or a tab, or a grid, or something else?

**Comment by qthermal** [comment]
That may have been it. I’ll check it out the next time I use it. I have been having a lot of trouble with the program immediately upon opening, it says “refreshing display…” or something of that sort and then it just hangs for about an hour or more.  After that, it then finally begins to work. 
Thanks for your reply, btw.
