### ISSUE TITLE
Error popup at start

### ISSUE THREAD

**Issue by riccardilorenzo** [EDDiscovery/EDDiscovery#2699]
### Description
I've opened EDDiscovery just after update, but it keeps reporting me this same error after multiple openings of the software.

### Additional Information
//

### Exception Details:
>EDDiscovery v11.1.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
>no such column: s.edsmid
>   in System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   in System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   in System.Data.SQLite.SQLiteDataReader.NextResult()
>   in System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   in System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   in EliteDangerousCore.DB.SystemsDB.FindStar(String name, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDBGetStars.cs:riga 69
>   in EliteDangerousCore.DB.SystemCache.FindSystem(ISystem find, SystemsDatabaseConnection cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemCache.cs:riga 110
>   in SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:riga 66
>===== END =====
>```

**Comment by robbyxp1** [comment]
Reset the UI panels and popups - hold down shift and reset the panels/pop outs option.  One of them is accesssing the database before its been upgraded. Its a known problem and will be solved in the next version.

**Comment by robbyxp1** [comment]
This has been fixed..
