### ISSUE TITLE
Search system DB and enter note for a system

### ISSUE THREAD

**Issue by finwen** [EDDiscovery/EDDiscovery#27]
From  Matt Kowalsky

I would very much like to be able to search the database for a System and enter a note without having to actually fly there. Manually manipulating the sqlite db (or entering the system name in the netlog file manually and let eddiscovery think I've flown there) is possible but it's error prone and not very user friendly.

**Comment by Red13x3** [comment]
+1 this idea
I'd like to see a "All Systems" tab that is searchable and then you can add your own notes that when you arrive in that system, the note appears as normal in your Travel History view. A good use for that would be say entering a note for all the systems that have rares. When you arrive in that system, the note reminds you to go to a station and get the rare.

**Comment by gregmalcolm** [comment]
Looks like this has been implemented. Close?

**Comment by Red13x3** [comment]
Yes, close. 

--
Mark Jelic
iPhone: 0402 322 901
