### ISSUE TITLE
VoicePackV12::SellExplorationData: Variable 'EventClass_Systems_Length' does not exist

### ISSUE THREAD

**Issue by sengel** [EDDiscovery/EDDiscovery#2700]
EDDiscovery 11.1.4.0, VoicepackV12 12.2.0.0

## Description
I think this is either a corner case in EDDiscovery or a "bug" in the journal entries of ED.

I sold cartographics data which contained an already scanned system (Xi-2 Lupi) which gave me 0 credits (I just scanned a ring for mining). In addition I got a "discovery" for this ring. This journal entry for the discovery contained empty lists for "Systems" and "Discovered" (see below).

The journal contains 8 entries of SellExplorationData which in turn lead to 8 Exceptions. It seems that the first 0 credit entry for Xi-2 Lupi caused an error which propagated into processing of the following SellExplorationData entries (or the empty lists for "discovered"?).

The items in the history tab of EDDiscovery are displayed correctly, i.e. descriptions / information are like this

"Sell Exploration Data" / "Amount:0 cr, Bonus:0 cr, Total:0 crScanned:Xi-2 Lupi Discovered:Xi-2 Lupi A 2 A Ring"
"Sell Exploration Data" / "Amount:13,798 cr, Bonus:0 cr, Total:13,798 cr"
...

## Exception Details
```
Error: Function phrase: Parameter 1: Function expand: Variable 'EventClass_Systems_Length' does not exist
At Step 1 in VoicePackV12::SellExplorationData:1275: Set
```

## Journal entries
{ "timestamp":"2020-01-10T00:02:24Z", "event":"SellExplorationData", "Systems":[ "Xi-2 Lupi" ], "Discovered":[ "Xi-2 Lupi A 2 A Ring" ], "BaseValue":0, "Bonus":0, "TotalEarnings":0 }
{ "timestamp":"2020-01-10T00:02:34Z", "event":"SellExplorationData", "Systems":[  ], "Discovered":[  ], "BaseValue":13798, "Bonus":0, "TotalEarnings":13798 }
{ "timestamp":"2020-01-10T00:02:38Z", "event":"SellExplorationData", "Systems":[ "Scorpii Sector GB-X b1-0" ], "Discovered":[  ], "BaseValue":11204, "Bonus":0, "TotalEarnings":11204 }
{ "timestamp":"2020-01-10T00:02:41Z", "event":"SellExplorationData", "Systems":[  ], "Discovered":[  ], "BaseValue":7368, "Bonus":0, "TotalEarnings":7368 }
{ "timestamp":"2020-01-10T00:02:45Z", "event":"SellExplorationData", "Systems":[ "Scorpii Sector KH-V b2-3" ], "Discovered":[  ], "BaseValue":78835, "Bonus":0, "TotalEarnings":78835 }
{ "timestamp":"2020-01-10T00:02:48Z", "event":"SellExplorationData", "Systems":[ "Scorpii Sector MS-T b3-6" ], "Discovered":[  ], "BaseValue":7806, "Bonus":0, "TotalEarnings":7806 }
{ "timestamp":"2020-01-10T00:02:51Z", "event":"SellExplorationData", "Systems":[ "Scorpii Sector QY-R b4-7" ], "Discovered":[  ], "BaseValue":6016, "Bonus":0, "TotalEarnings":6016 }
{ "timestamp":"2020-01-10T00:02:54Z", "event":"SellExplorationData", "Systems":[ "Scorpii Sector MS-T b3-8" ], "Discovered":[  ], "BaseValue":2808, "Bonus":0, "TotalEarnings":2808 }

**Comment by robbyxp1** [comment]
voice pack bug, will fix thanks

**Comment by robbyxp1** [comment]
12.3 fixes this, thanks for the report.
