### ISSUE TITLE
VoicePackV12::MultiSellExplorationData: Variable 'EventClass_Systems_Length' does not exist

### ISSUE THREAD

**Issue by sengel** [EDDiscovery/EDDiscovery#2701]
Thanks for the quick fix of issue #2700. Keep up the good work :-)

## Description
Today I tried MultiSell and got no voice output but found an exception instead. This one looks like the same kind as #2700, but now for MultiSellExplorationData.

## Exception Details
```
Error: Function phrase: Parameter 1: Function expand: Variable 'EventClass_Systems_Length' does not exist
At Step 1 in VoicePackV12::MultiSellExplorationData:1291: Set
```

## Journal entries
{ "timestamp":"2020-01-10T22:50:14Z", "event":"MultiSellExplorationData", "Discovered":[ { "SystemName":"", "NumBodies":2 }, { "SystemName":"", "NumBodies":1 }, { "SystemName":"", "NumBodies":5 }, { "SystemName":"", "NumBodies":1 } ], "BaseValue":53409, "Bonus":0, "TotalEarnings":53409 }

**Comment by robbyxp1** [comment]
Fixed, same issue. I could have sworn I fixed that before.  Just can't get the staff.

12.3.1 should fix it.
