### ISSUE TITLE
Only send unsynced EDDN events since given or recent time.

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#2702]
When one creates (or for any reason recreates) a new EDDiscovery DB, then it makes the assumption that all scans found in player log are unsynced with EDDN (in EDDUser.sqlite main.JournalEntries.Synced = 0), regardless of how old those entries are.

This may well not be the best way to proceed.

- Scenario
 ##
I am returning to Elite after a 6 month hiatus, I reinstall EDDiscovery which reads all my logs back to the beginning, some years of play, including DW2 expedition. 

I forget to start up EDDiscovery during a play session, or have some technical issue, or some circumstance means that some new scans are not uploaded to EDDN.

I ask EDDiscovery to "Send unsynced EDDN events" from the admin menu.

EDDiscovery goes back to the start of my logs and begins uploading everything I scanned ever. Years of logs, including 6 months of DW2, when in fact it's just a few missing scans that need sending.
- End Scenario

I can workaround by manually setting main.JournalEntries.Synced = 3 for all appropriate events, with a single easy line of SQL, but that's not ideal for less clueful users.

Can I suggest either by default saying that any scan events imported with timestamp prior to the time of DB creation are assumed synced
OR
There are options to either mark all events as synced
OR
A date range is required  for sending unsynced EDDN events.

This will stop (potentially) hours of EDDiscovery sending events to EDDN and the need for EDDN to process old, out of date and what could have once been valid but is now garbage data.

Even if my scenario is an extreme case, I'm sure there are other users with a lesser version of this.

**Comment by robbyxp1** [comment]
EDDiscoveryForm.cs line 708 has

        if (EDDNClass.IsEDDNMessage(he.EntryType,he.EventTimeUTC) && he.AgeOfEntry() < TimeSpan.FromDays(1.0) && EDCommander.Current.SyncToEddn == true)
            {
                EDDNSync.SendEDDNEvents(LogLine, he);
            }

It should not be sending stuff older than 1 day..

**Comment by robbyxp1** [comment]
Thats for live entries, in Send Unsynced, 

        private void sendUnsuncedEDDNEventsToolStripMenuItem_Click(object sender, EventArgs e)
        {
            List<HistoryEntry> hlsyncunsyncedlist = Controller.history.FilterByScanNotEDDNSynced;        // first entry is oldest

            EDDNSync.SendEDDNEvents(LogLine, hlsyncunsyncedlist);
        }

that just sends all of them without checking date.

By solution is to remove the option to send old EDDN events from the menu system

**Comment by robbyxp1** [comment]
Edit - it does check them as too old in 

                        if (age.Days >= 1 && he.EntryType != EliteDangerousCore.JournalTypeEnum.Scan)
                        {
                            System.Diagnostics.Debug.WriteLine("EDDN: Ignoring entry due to age");
                        }

**Comment by Tromador** [comment]
My observed behaviour is it uploads everything since forever.

**Comment by Tromador** [comment]
Removing the menu option would likely not be a terrible option. The potential for loss of data trss

**Comment by klightspeed** [comment]
If one wants to send those old events, one can use EDSM's journal uploader.

**Comment by Tromador** [comment]
Given C# is largely out of my skill set and so I've not read all the source code, but the following 

``
if (age.Days >= 1 && he.EntryType != EliteDangerousCore.JournalTypeEnum.Scan)
``

says to me
if ("at least one day old" AND NOT "a scan")

should "!=" actually read "==" ??

**Comment by klightspeed** [comment]
> ```
> if (age.Days >= 1 && he.EntryType != EliteDangerousCore.JournalTypeEnum.Scan)
> ```
>
> says to me
> if ("at least one day old" AND NOT "a scan")
> {ignore entry}

That is correct - FSDJump and Docked events are considered to be stale after about a day, while Scan events were not considered to be stale.

We are considering removing the Send Unsynced EDDN Scans menu option, and directing users to use the EDSM journal uploader if they want to send old scans via EDDN.

**Comment by Tromador** [comment]
> That is correct - FSDJump and Docked events are considered to be stale after about a day, while Scan events were not considered to be stale.

Hence it sending all my scans since forever. Right. 
 
> We are considering removing the Send Unsynced EDDN Scans menu option, and directing users to use the EDSM journal uploader if they want to send old scans via EDDN.

If someone has a bulk upload, then upload via EDSM is a much better option, though I'm unsure how valuable a lot of possibly very old data is going to be. I suppose someone could have been exploring in the wider galaxy (where FDEV don't manually rename or alter systems) and never uploaded data for whatever reason, in which case EDSM is definitely the way to go.

As I said before, a few hours of my (or any individual's) missing data isn't likely a massive deal in the grand scheme of EDDN, but it could be important to the explorer, maybe making some interesting discovery. 
For this case, the convenience of a quick menu item on an app you already have open makes it worth considering keeping, especially given all the upload code is there and working.  Another conditional to check scan age doesn't seem like a huge deal, with an appropriate reword of the menu item to indicate the time limit.

**Comment by robbyxp1** [comment]
I'm going to leave it all alone for now since i want to do a release this week. We can have a ponder over this in good time

**Comment by klightspeed** [comment]
Perhaps present a menu giving an option for how many days back to upload (with empty or 0 meaning all time)?

**Comment by robbyxp1** [comment]
Going to retire this one.
