### ISSUE TITLE
Bodies scanned by "autoscan" not shown in the graphical overview of celestial bodies

### ISSUE THREAD

**Issue by DeepstarOne** [EDDiscovery/EDDiscovery#2703]
Hi,
I've started to play Elite Dangerous again after nearly a year off. With the (at least for me) "new" planetary scanning I observed, that some celestial bodies scanned by "austoscan" are not shown in the graphical overview of celestial bodies at the bottom oft he window. I think only moons are affected by this. The data of the objects can still be got via the text entries in the history. I've marked the corresponding entries for one example system  with yellow in the comment column in the attached screen shots.
Is this behavior intentional?
Best regards

![EDD_missing_moons_1](https://user-images.githubusercontent.com/25210660/72220318-ce6a8f80-354f-11ea-9da4-05467e86500f.png)

![EDD_missing_moons_2](https://user-images.githubusercontent.com/25210660/72220321-d32f4380-354f-11ea-9793-9412562ddbf4.png)

**Comment by robbyxp1** [comment]
I have an Autoscan of a 3a (moon) body

473: { "timestamp":"2019-12-18T17:23:56Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"G 89-32 3 a", "BodyID":35, "Parents":[ {"Planet":34}, {"Star":0} ], "StarSystem":"G 89-32", "SystemAddress":20462163797409, "DistanceFromArrivalLS":1809.903198, "TidalLock":true, "TerraformState":"", "PlanetClass":"Icy body", "Atmosphere":"", "AtmosphereType":"None", "Volcanism":"major water geysers volcanism", "MassEM":0.002769, "Radius":1234133.125000, "SurfaceGravity":0.724586, "SurfaceTemperature":35.470211, "SurfacePressure":0.000000, "Landable":true, "Materials":[ { "Name":"sulphur", "Percent":26.975786 }, { "Name":"carbon", "Percent":22.683844 }, { "Name":"phosphorus", "Percent":14.522585 }, { "Name":"iron", "Percent":12.189399 }, { "Name":"nickel", "Percent":9.219550 }, { "Name":"chromium", "Percent":5.481977 }, { "Name":"selenium", "Percent":4.221939 }, { "Name":"vanadium", "Percent":2.993292 }, { "Name":"tin", "Percent":0.727590 }, { "Name":"tungsten", "Percent":0.669320 }, { "Name":"polonium", "Percent":0.314705 } ], "Composition":{ "Ice":0.818298, "Rock":0.165388, "Metal":0.016314 }, "SemiMajorAxis":149597984.000000, "Eccentricity":0.000973, "OrbitalInclination":0.034568, "Periapsis":2.063424, "OrbitalPeriod":116629.328125, "RotationPeriod":116636.695313, "AxialTilt":0.819521, "WasDiscovered":true, "WasMapped":true }
A 

![image](https://user-images.githubusercontent.com/6573992/72221295-205fe500-3551-11ea-875c-2a59c0cd969d.png)

Which is showing. Another one is. Not sure what is happening.

**Comment by DeepstarOne** [comment]
Hi,
issue can be closed. I was my fault, I accidentally clicked on "show/hide moons" without noticing. Sorry! ;-)
Best regards
