### ISSUE TITLE
VoicepackV12: german planned?

### ISSUE THREAD

**Issue by RamonaTigier** [EDDiscovery/EDDiscovery#2710]
I'd like to help with a german Voicepack. 
Can I help with coding or translating?

What I've done so far with "Edit speech file":

`PROGRAM SetUpLanguageEnglish

Static jkm_install $= You have installed Elite Dangerous Discovery, Joystick, Keyboard, Mouse Pack 2, English version

Rem naming convention jkm_Bindingname or jmk_N_Bindingname or jmp_H_Bindingname.  Use N = normal space only, H = hyperspace only

Static jkm_N_ShipSpotLightToggle $= Toggle ship lights
Static jkm_N_ToggleDriveAssist $= Toggle drive assist
Static jkm_N_AutoBreakBuggyButton $= Toggle SRV brake
Static jkm_N_ToggleBuggyTurretButton $= Toggle SRV turret

Rem no power, cause it just goes crazy.. instead just plop them under a single POWER entry
// Static jkm_IncreaseEnginesPower_Buggy $= "Increase power to Engines"
// Static jkm_IncreaseWeaponsPower_Buggy $= "Increase power to Weapons"
// Static jkm_IncreaseSystemsPower_Buggy $= "Increase power to Systems"
// Static jkm_ResetPowerDistribution_Buggy = "Reset SRV power system"
// Static jkm_IncreaseEnginesPower $= "Increase power to Engines"
// Static jkm_IncreaseWeaponsPower $= "Increase power to Weapons"
// Static jkm_IncreaseSystemsPower $= "Increase power to Systems"
// Static jkm_ResetPowerDistribution $= "Reset ship power distribution"
Static jkm_powerbindings $= IncreaseEnginesPower_Buggy,IncreaseSystemsPower_Buggy,IncreaseWeaponsPower_Buggy,ResetPowerDistribution_Buggy,IncreaseEnginesPower,IncreaseWeaponsPower,IncreaseSystemsPower,ResetPowerDistribution
Static jkm_Power = Adjusting power;Changing power allocation

// Static jkm_ToggleFlightAssist $= ""
Static jkm_N_LandingGearToggle $= Fahrwerk umschalten
Static jkm_N_ToggleButtonUpInput $= Stielle Fahrt umschalten
Static jkm_N_ToggleCargoScoop $= Frachtschaufel umschalten
Static jkm_TargetNextRouteSystem $= Ausgewählte bestehende Route
Static jkm_OrbitLinesToggle $= Umlaufbahnlinien umschalten
Static jkm_GalaxyMapOpen $= Galaxiekarte umschalten
Static jkm_SystemMapOpen $= Systemübersicht umschalten

Static jkm_SetSpeedMinus100 $= Voll achtern
Static jkm_SetSpeedMinus75 $= 75 Prozent achtern
Static jkm_SetSpeedMinus50 $= 50 Prozent achtern
Static jkm_SetSpeedMinus25 $= 25 Prozent achtern
Static jkm_SetSpeedZero $= Maschinen aus
Static jkm_SetSpeed25 $= 25 Prozent voraus;Langsame Fahrt voraus Kapitän
Static jkm_SetSpeed50 $= 50 Prozent voraus;Halbe Fahrt voraus Kapitän
Static jkm_SetSpeed75 $= 75 Prozent voraus;Schnelle Fahrt voraus Kapitän
Static jkm_SetSpeed100 $= Voll voraus;Volle Fahrt
Static jkm_N_UseBoostJuice $= Verstärkung
Static jkm_EngineColourToggle $= Strahlfarbe umschalten

Static jkm_DeployHardpointToggle $= Waffen umschalten
Static jkm_CycleFireGroupPrevious $= Feuergruppe zurück
Static jkm_CycleFireGroupNext $= Nächste Feuergruppe
Static jkm_CycleNextSubsystem $= Nächstes Zielsubsystem
Static jkm_CyclePreviousSubsystem $= Vorheriges Zielsubsystem
Static jkm_CycleNextTarget $= Nächstes Ziel
Static jkm_CyclePreviousTarget $= Vorheriges Ziel
Static jkm_SelectTarget $= Ziel auswählen
Static jkm_CycleNextHostileTarget $= Nächster Feindseeliger
Static jkm_CyclePreviousHostileTarget $= Vorheriger Feindseeliger
Static jkm_SelectHighestThreat $= Höchste Bedrohung
Static jkm_WeaponColourToggle $= Waffenfarbe umschalten

Static jkm_DeployHeatSink $= Feuere Kühlkörper
Static jkm_N_UseShieldCell $= Schildzelle entladen
Static jkm_N_FireChaffLauncher $= Feuere Düppel
Static jkm_N_ChargeECM $= Lade ECM

Static jkm_TargetWingman0 $= Selektiere Flügelmann 1
Static jkm_TargetWingman1 $= Selektiere Flügelmann 2
Static jkm_TargetWingman2 $= Selektiere Flügelmann 3
Static jkm_SelectTargetsTarget $= Selektiere Flügelmann Ziel
Static jkm_WingNavLock $= Flügelmann-Navigationssperre umschalten

Static jkm_MicrophoneMute $= Mikrofon stumm schalten

Static jkm_FocusLeftPanel $= Navigationsfenster umschalten
Static jkm_FocusRightPanel $= Systemfenster umschalten
Static jkm_FocusRadarPanel $= Rollenfenster umschalten
Static jkm_QuickCommsPanel $= Schnellkommunikations Bedienfeld
Static jkm_FocusCommsPanel $= Kommunikations Bedienfeld
Static jkm_UIFocus $= Bedienfeld umschalten
Static jkm_HeadLookToggle $= Kopfsicht umschalten
Static jkm_FriendsMenu $= Freund Menü umschalten
Static jkm_PhotoCameraToggle $= Kamera Modus umschalten

Static jkm_N_OrderRequestDock $= Jäger andocken anfordern
Static jkm_N_OrderDefensiveBehaviour $= Defensiver Modus
Static jkm_N_OrderAggressiveBehaviour $= Aggressiver Modus
Static jkm_N_OrderFocusTarget $= Ausgewähltes Ziel angreifen
Static jkm_N_OrderHoldFire $= Nicht schießen
Static jkm_N_OrderHoldPosition $= Position halten
Static jkm_N_OrderFollow $= Mir folgen
Static jkm_N_OpenOrders $= Befehle öffnen

Static jkm_UI $= UI_Select,UI_Up,UI_Down,UI_Left,UI_Right,CyclePreviousPanel,CycleNextPanel

Static jkmSpeechCulture = de-de

END PROGRAM`

**Comment by robbyxp1** [comment]
So, the answer is, if someone contributes a translated voice pack, i'll host it on Github for download.  

But as we have seen with the translation of the main program, its very hard to sustain the translations.  People come and go and the translation does not always get kept up to date as elite evolves.

So the answer is, there is no plans for the development team to do any work translating the voice packs, but if users submit a translated pack we will host it for others to download

cheers rob

**Comment by RamonaTigier** [comment]
> but if users submit a translated pack we will host it for others to download
> 
> cheers rob

Dear rob, 
where can I find the pack, I tried to find it in your structure but wasn't able to find? :) 
I'd love to submit a translated one and as I'll play ED and using EDDiscovery willed to update it regularly.

**Comment by RamonaTigier** [comment]
Dear rob, 

one small question. 

As testing my GermanVoicePack I didn't found a "Static say" that says "Toggle Navigations Panel", but VoicePack is saying/reading "Wechsle zu Navigationsfenster". 

Are there variables that are not in VoicePackV12.act?

Or better how can I reach/change them? 

Many thanks!


Cheers!

P.S.: Please find attached my GermanVoicePackV12.act - it is at 30% but maybe I have overseen something? Renamed to txt to be able to upload.
[GermanVoicePackV12.act.txt](https://github.com/EDDiscovery/EDDiscovery/files/4124168/GermanVoicePackV12.act.txt)

**Comment by RamonaTigier** [comment]
Okay, there is still a SetUpLanguageEnglish.atf at C:\Users\magic\AppData\Local\Temp

The statics have:
jkm_*

Can I insert them into GermanVoicePackV12.act as well??

**Comment by robbyxp1** [comment]
The joystick/keyboard/mouse action pack is separate to the voice packs.  The voice packs deal with journal information, the JKM with user UI interaction.  They use different methods to pick up events.

Of course you could combine the VP and JKM into a new german one. I kept them separate for the reasons some people may not want their UI interaction reported.

**Comment by robbyxp1** [comment]
Closing, if you have a pack, please submit.
