### ISSUE TITLE
EDD not recognizing new commander properly

### ISSUE THREAD

**Issue by cristi-neagu** [EDDiscovery/EDDiscovery#2713]
Hello,

After a very long break i decided to come back to ED. Because i couldn't remember much and everything was confusing and spread out all over the galaxy, i decided to erase my old save and make a new one. I also decided to give my character the same name as before. As a result, EDD thinks the old logs are from the same character even though it recognizes the "Clear Save Game" and "New Commander" events.
I tried moving the old logs to another commander (right click menu), but i cannot define a new commander, as far as i can tell.

Any solution for this?

Thank you.

**Comment by klightspeed** [comment]
In the settings panel, under the commanders list, click Add, and give the commander a name.  Then you should be able to move the old history to that commander.

**Comment by cristi-neagu** [comment]
That was an easy fix. Thanks!
