### ISSUE TITLE
Issue with copy pasting route rows

### ISSUE THREAD

**Issue by cristi-neagu** [EDDiscovery/EDDiscovery#2714]
Hello,

EDD doesn't seem to be able to recognize rows copied from its own route window. If you select multiple waypoints in the route editor and then paste them in either the route or expedition windows (both with right click - paste and with right click - insert copied rows), the waypoints aren't copied over properly. Instead of inserting only the name of the waypoint, EDD inserts a formatted line of the route table. This doesn't seem right.

Thank you.

**Comment by klightspeed** [comment]
Select the system cells using the keyboard, right-click, copy.

We'll have to look at making shift-select using the mouse select the cells instead of the clicked row.

**Comment by cristi-neagu** [comment]
That works for now. Thanks!
