### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by fonstec** [EDDiscovery/EDDiscovery#2715]
### Description
Restart failed after update.

### Additional Information
Tried hold shift+start and restart PC - no change.
Popups -
![EDD 2020-02-05 github error](https://user-images.githubusercontent.com/23567353/73840763-d2b56000-4810-11ea-91bd-5fbdfce86cf4.png)
![EDD 2020-02-05 github error popup2](https://user-images.githubusercontent.com/23567353/73840831-01cbd180-4811-11ea-8c68-64b2cdebce94.PNG)

### Exception Details:
>EDDiscovery v11.2.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlSettings.PeriodicCheck(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Settings\UserControlSettings.cs:line 600
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
It sounds like EDDiscovery didn't properly exit.

Press Ctrl+Alt+Delete, and bring up the task manager, then kill any `EDDiscovery` processes.  Then try re-installing EDDiscovery.

**Comment by fonstec** [comment]
Ctrl+Alt+Delete showed nothing running.
I have now uninstalled the previous version, restart and installed new version and all is well.
There seems to be a problem with updating processes, clean install - no problem.

Thanks for your assistance.
