### ISSUE TITLE
Error: Function phrase: Parameter 1: Function indirect: Function ifgt:

### ISSUE THREAD

**Issue by MartindForlon** [EDDiscovery/EDDiscovery#2717]
Greetings,

getting next error message in program log which is added after each jump to the next system:

Error: Function phrase: Parameter 1: Function indirect: Function ifgt: Function ifeq: Parameter 1: Variable 'EventShip_FuelCapacity' value '32,0' is not a number
At Step 7 in VoicePackV12::GenericResponse:1837: Set

like: 

History refresh complete.
Arrived at system Arietis Sector OY-R b4-5 Visit No. 1
Error: Function phrase: Parameter 1: Function indirect: Function ifgt: Function ifeq: Parameter 1: Variable 'EventShip_FuelCapacity' value '32,0' is not a number
At Step 7 in VoicePackV12::GenericResponse:1837: Set
Arrived at system Arietis Sector LS-T b3-1 Visit No. 1
Error: Function phrase: Parameter 1: Function indirect: Function ifgt: Function ifeq: Parameter 1: Variable 'EventShip_FuelCapacity' value '32,0' is not a number
At Step 7 in VoicePackV12::GenericResponse:1837: Set
Arrived at system Paestae Visit No. 1
Error: Function phrase: Parameter 1: Function indirect: Function ifgt: Function ifeq: Parameter 1: Variable 'EventShip_FuelCapacity' value '32,0' is not a number
At Step 7 in VoicePackV12::GenericResponse:1837: Set

**Comment by robbyxp1** [comment]
Got it, your running under a locale with ',' as the decimal separator

It will only stop that event running for now, i'll update EDD soon to fix it

thanks for the report.

rob

**Comment by robbyxp1** [comment]
tommorrow will bring a version which fixes it.
