### ISSUE TITLE
Surveyor not updating new system

### ISSUE THREAD

**Issue by Ahlos** [EDDiscovery/EDDiscovery#2718]
When i start the EDDiscovery 11.2.3.0 it loads the current system, the surveyor. But when i jump to a new system, evrything else updates, but not the surveyor..

I just more or less installed this new update 11.2.3.0, and the problem started after that.

**Comment by robbyxp1** [comment]
So, the surveyor follows the cursor position of the main travel grid. Click on the entry in the travel grid and the 

Have you got the "Automatically move the cursor" switched on in the travel grid (its the big green up arrow).  If not, it won't change when you jump.

**Comment by robbyxp1** [comment]
No response back, closing
