### ISSUE TITLE
Huge lag and freeze

### ISSUE THREAD

**Issue by BBBenj** [EDDiscovery/EDDiscovery#2719]
Hi!
Just updated from 11.2.1 to 11.2.3. If it used to work fine, now I have huuuuuuge lags and it freezes most of the time. At this point, it's totally useless.

Therefore, I uninstalled it, restarded my computer, cleaned my registry, restarted again, reinstalled from scratch. And... Nothing change.

I restarted once again, started EDDiscovery with shift key, cleaned all my datas... And still the same.

I'm a long time huge fan of your application, so I'm sad it doesn't work as desired.

Config: AMD 1600x, 16Gb, RTX 2070 and NVMe Samsung 970... I think it's good enough!

Can you have a look at the source of this problem, please?

Best regards,

Benjamin aka Kalifornia Belem

**Comment by klightspeed** [comment]
Does the build at <https://ci.appveyor.com/project/EDDiscovery/eddiscovery/builds/30694484/artifacts> improve this?

If you look at your latest trace log in `%LOCALAPPDATA%\EDDiscovery\Log`, and search for `Job delayed for` or `Database connection held for`, do you find any log entries?

**Comment by BBBenj** [comment]
Hi! 
I gave 11 files from February 12th to 15th with "job delayed for" inside, mostly once in each file. And none for "Database connection held for". 

I'll try the build you be me and I'll keep you informed. 

Thanks a lot. 

Benjamin

⁣Télécharger TypeApp pour Android ​


-------- Message original --------
De: Ben Peddell <notifications@github.com>
Envoyé: Sat Feb 15 19:18:45 GMT+01:00 2020
À: EDDiscovery/EDDiscovery <eddiscovery@noreply.github.com>
Cc: Benjamin <benjamin.larue@numericable.fr>, Author <author@noreply.github.com>
Sujet: Re: [EDDiscovery/EDDiscovery] Huge lag and freeze (#2719)

Does the build at <https://ci.appveyor.com/project/EDDiscovery/eddiscovery/builds/30694484/artifacts> improve this?

If you look at your latest trace log in `%LOCALAPPDATA%\EDDiscovery\Log`, and search for `Job delayed for` or `Database connection held for`, do you find any log entries?

**Comment by klightspeed** [comment]
Having "Job delayed for" but no "Database connection held for" sounds like it's the systems DB update that is slowing it down.  You can try disabling star data download in the settings panel.

**Comment by robbyxp1** [comment]
No more user feedback, closed.

**Comment by BBBenj** [comment]
Nooo! I'm still trying to know what went wrong. I think I have a clue. It's about the mission board. From what I tested, everything seems to work normally, but when I use the mission tab, it lags a lot, including the portable version you gave me.

You may have a look at this feature, I think.
