### ISSUE TITLE
Sorting under Materials Panel causes unhandled UI exception

### ISSUE THREAD

**Issue by SisuSnacks** [EDDiscovery/EDDiscovery#2726]
Under the Materials panel, about every 2-3 times I sort by one of the columns, I get a UI error.  I can hit continue and will keep working, then same thing again after a couple column sorts.  It does not matter which columns, I went ahead and randomly clicked them for a while to see if it kept happening.  You can still use it, just have to hit the continue button is all.  Can't see anything else on the user end of the experience.  Here is the diagnostic info.  Thanks for working on such an incredible piece of software and have a good one!

### Exception Details:
>EDDiscovery v11.2.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.Collections.ArrayList.get_Item(Int32 index)
>   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
>   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
>   at EDDiscovery.UserControls.UserControlMaterialCommodities.dataGridViewMC_CellDoubleClick(Object sender, DataGridViewCellEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlMaterialCommodities.cs:line 259
>   at System.Windows.Forms.DataGridView.OnCellDoubleClick(DataGridViewCellEventArgs e)
>   at System.Windows.Forms.DataGridView.OnDoubleClick(EventArgs e)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
That stack trace suggests that the grid thinks it's being double-clicked.
