### ISSUE TITLE
Exception on 29 Feb 3306

### ISSUE THREAD

**Issue by Ejsstiil** [EDDiscovery/EDDiscovery#2730]
### Description
App crash

### Exception Details:
>EDDiscovery v11.2.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
>   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
>   at EDDiscovery.EDDConfig.ConvertTimeToSelectedFromUTC(DateTime t) in C:\Code\EDDiscovery\EDDiscovery\EDDConfig.cs:line 154
>   at EliteDangerousCore.JournalEvents.JournalMissionAccepted.MissionBasicInfo() in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalMissions.cs:line 208
>   at EliteDangerousCore.JournalEvents.JournalMissionAccepted.FillInformation(String& info, String& detailed) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalMissions.cs:line 192
>   at EDDiscovery.UserControls.UserControlTravelGrid.CreateHistoryRow(HistoryEntry item, String search) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 446
>   at EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl, Boolean disablesorting) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 259
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshCompleteonUI(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 192
>===== END =====
>```

I believe that this has something to do with 29 Feb date trouble

**Comment by klightspeed** [comment]
Yeah - that weird leap year in 3302 and 3306, and the lack of a leap year in 3300 and 3304.

Perhaps it should subtract 86 (or 1286) years if the year is greater than or equal to 3300?
