### ISSUE TITLE
Statistics - Travel - Summary: Last Dock column showing no values

### ISSUE THREAD

**Issue by McCriddle** [EDDiscovery/EDDiscovery#2732]
i'm on an expedition right now and at some point EDDiscovery stopped showing statistic values for the travel since last dock.

**Comment by klightspeed** [comment]
If the last dock event is being filtered out by the filter in the settings panel, then the statistics panel is unable to determine when you last docked.

**Comment by McCriddle** [comment]
Thanks a lot.
I had the memory set to ">7 days old" and "Jumps and Scans"

Choosing another timeframe solved the issue
