### ISSUE TITLE
Incorrectly displayed volcanism

### ISSUE THREAD

**Issue by SigurdCole** [EDDiscovery/EDDiscovery#2743]
Scanning Prue Prao FC-P c21-0, both the 3 and 5a planets showed Metallic Magma volcanism in EDDiscovery, but in E:D they had iron magma volcanism.

EDSM also shows metallic magma volcanism, so may be mis-reported as well. Can supply screenshot if needed.

**Comment by klightspeed** [comment]
The Volcanism in the journal is "metallic magma volcanism".

```json
{
  "BodyID": 32,
  "BodyName": "Prue Prao FC-P c21-0 5 a",
  "PlanetClass": "Rocky body",
  "StarSystem": "Prue Prao FC-P c21-0",
  "Volcanism": "metallic magma volcanism",
  "event": "Scan",
  "timestamp": "2020-03-09T14:40:23Z"
}
```

```json
{
  "BodyID": 7,
  "BodyName": "Prue Prao FC-P c21-0 3",
  "PlanetClass": "High metal content body",
  "StarSystem": "Prue Prao FC-P c21-0",
  "Volcanism": "minor metallic magma volcanism",
  "event": "Scan",
  "timestamp": "2020-03-09T14:45:46Z"
}
```

**Comment by robbyxp1** [comment]
So its showing what the journal says, so there i nothing to fix. thanks for the report.
