### ISSUE TITLE
Error: There was an unhandled UI exception / search route -> view scan display

### ISSUE THREAD

**Issue by compubuster** [EDDiscovery/EDDiscovery#2744]
### Exception Details:
>EDDiscovery v11.2.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.
>Parametername: index
>   bei System.Collections.ArrayList.get_Item(Int32 index)
>   bei System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
>   bei System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
>   bei EDDiscovery.UserControls.UserControlRoute.showScanToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlRoute.cs:Zeile 798.
>   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   bei System.Windows.Forms.Control.WndProc(Message& m)
>   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
You probably clicked on the header line, and its not screened out.

I'll fix.

**Comment by robbyxp1** [comment]
Fixed, thats for the report. will be in 11.3 soon
