### ISSUE TITLE
Documentation for IGAU integration // Wiki

### ISSUE THREAD

**Issue by alterNERDtive** [EDDiscovery/EDDiscovery#2746]
by Astro74205#7457 on EDCD Discord

Updated the Wiki with documentation for IGAU integration. Deleted the EGO stuff in the process. [See discussion in \#eddiscovery on EDCD Discord](https://discord.gg/etSnxm) and harass Astro/Urania Minora if you don’t like anything.

Bit fiddly to handle since Github has no pull requests for the Wiki, but I think you’ll manage.

https://github.com/alterNERDtive/EDDiscovery-wiki/compare/igau-integration

**Comment by robbyxp1** [comment]
Okay, i'll clean it all up v.soon, thanks

**Comment by robbyxp1** [comment]
Done,Thanks
