### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by Jaxinc** [EDDiscovery/EDDiscovery#2750]
### Exception Details:
>EDDiscovery v11.3.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.Inara.InaraSync.NewEntryList(HistoryList history, HistoryEntry he) in C:\Code\EDDiscovery\EliteDangerous\Inara\InaraSync.cs:line 236
>   at EliteDangerousCore.Inara.InaraSync.NewEvent(Action`1 logger, HistoryList history, HistoryEntry he) in C:\Code\EDDiscovery\EliteDangerous\Inara\InaraSync.cs:line 66
>   at EDDiscovery.EDDiscoveryForm.Controller_NewEntrySecond(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 705
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 85
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 72
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(Tuple`2 entries) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 185
>===== END =====
>```

**Comment by klightspeed** [comment]
That would suggest that either an event that wasn't a FSDJump was passed through, or the ship information was not set.

**Comment by Jaxinc** [comment]
> 
> 
> That would suggest that either an event that wasn't a FSDJump was passed through, or the ship information was not set.

How would I resolve this? It doesn't seem to prevent it from sending data to Inara or anything, but it's just popping it up continuously.

**Comment by robbyxp1** [comment]
Both of which above is v.strange.

Describe when it pops up - when a new journal entry is received from Elite during play?  Every time, or on a particular one?

Is there any other reports of problems?  Ship information should always be set on each entry.

At the moment, i'm lost to know why its happening.

**Comment by klightspeed** [comment]
Would it please be possible to get the trace log (`Trace_2020-03-*.log` from `%LOCALAPPDATA%\EDDiscovery\log`) and possibly the journal file (`Journal.2003*.log` from `shell:SavedGames\Frontier Developments\Elite Dangerous`) from when this occurred?

**Comment by Jaxinc** [comment]
[Trace_2020-03-13-19-24-05.0.log](https://github.com/EDDiscovery/EDDiscovery/files/4362188/Trace_2020-03-13-19-24-05.0.log)
[Journal.200319184140.01.log](https://github.com/EDDiscovery/EDDiscovery/files/4362225/Journal.200319184140.01.log)

There you are.


> 
> 
> Both of which above is v.strange.
> 
> Describe when it pops up - when a new journal entry is received from Elite during play? Every time, or on a particular one?
> 
> Is there any other reports of problems? Ship information should always be set on each entry.
> 
> At the moment, i'm lost to know why its happening.

I am unsure /when/ it pops up given it does not get focus, so I don't realize the screen has appeared until I close ED. It however occurs every time I play ED on this one system, on my other system I do not have this problem. Both systems are running W10 Pro x64.

**Comment by klightspeed** [comment]
```
[2020-03-15T05:41:17.843Z] Update cmdr id ID -1 with -1
```

You moved all history to the hidden commander.  This included the start of the session, so there was no information EDDiscovery could use to determine what ship the current commander was flying.  As a result, ShipInformation was null.

I was originally writing:

> One thing I notice is quite a few DNS resolution errors
> ```
> [2020-03-14T01:16:17.845Z] WebException : The remote name could not be resolved: 'www.edsm.net'
> ```
> 
> Error:
> ```
> [2020-03-15T05:43:44.806Z] 105579504+1 Refresh history complete
> [2020-03-15T05:44:56.365Z] New entry 3/15/2020 5:44:56 AM StartJump
> [2020-03-15T05:45:14.469Z] New entry 3/15/2020 5:45:14 AM FSDJump
> [2020-03-15T05:45:14.483Z] Arrived at system: Praea Euq GL-X d1-27 1:th visit.
> [2020-03-15T05:45:14.490Z] Adding FSDJump event to EDSM journal sync (Jump to Praea Euq GL-X d1-27)
> [2020-03-15T05:45:14.714Z] HTTPPOST TO https://www.edsm.net/api-journal-v1 ThreadEDSM Journal Sync
> [2020-03-15T05:45:14.718Z] 
> [2020-03-15T05:45:14.718Z] ==== UNHANDLED UI EXCEPTION ====
> [2020-03-15T05:45:14.718Z] System.NullReferenceException: Object reference not set to an instance of an object.
> [2020-03-15T05:45:14.718Z]    at EliteDangerousCore.Inara.InaraSync.NewEntryList(HistoryList history, HistoryEntry he) in C:\Code\EDDiscovery\EliteDangerous\Inara\InaraSync.cs:line 236
> [2020-03-15T05:45:14.718Z]    at EliteDangerousCore.Inara.InaraSync.NewEvent(Action`1 logger, HistoryList history, HistoryEntry he) in C:\Code\EDDiscovery\EliteDangerous\Inara\InaraSync.cs:line 66
> [2020-03-15T05:45:14.718Z]    at EDDiscovery.EDDiscoveryForm.Controller_NewEntrySecond(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 705
> [2020-03-15T05:45:14.718Z]    at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 85
> [2020-03-15T05:45:14.718Z]    at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 72
> [2020-03-15T05:45:14.718Z]    at EliteDangerousCore.EDJournalClass.ScanTickDone(Tuple`2 entries) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 185
> [2020-03-15T05:45:14.718Z] ==== cut ====
> ```
> 
> I notice you also have fetch from EDSM enabled.  I wonder if there's some interplay between the jump history fetched from EDSM and the ship information that is causing the ship information not to be set?
> 
> The journal is from a few days later.  The journal in question would be something like `Journal.200315004039.01.log.
> 
> The only way I can see that ShipInformation would be null (meaning EDDiscovery was unable to determine your current ship) is if you logged in in a fighter or SRV, __or if you moved all history to the hidden commander__.  It looks like your other commander did log out in a SRV, but that should not have affected Chatin naidoo.

Also, as a security precaution, you may want to reset the API key on Chatin naidoo.  The trace log you posted did not have the API key masked out.

**Comment by robbyxp1** [comment]
Fixed
