### ISSUE TITLE
Version 11.3 installer hangs on Windows 8.1

### ISSUE THREAD

**Issue by jrmain** [EDDiscovery/EDDiscovery#2751]
The installer runs and initially seems fine, but when it starts actually doing stuff it hangs. The installer just says "Configuring EDDiscovery - Installing EDDiscovery..."

I have to kill two EDDiscovery installer processes, then kill the Windows Installer process to get back to normal.

I've tried this a few times with the same results each time.

Windows 8.1 64-bit. Installed previous versions numerous times without any issues.

**Comment by klightspeed** [comment]
This sounds similar to <https://www.advancedinstaller.com/forums/viewtopic.php?t=34746> (the installer currently uses Advanced Installer)

**Comment by robbyxp1** [comment]
I'm afraid we won't be fixing it, because windows 8.1 is no longer supported by microsoft.

Try using the portable version, the zip. Download it to a folder and run it there.  That does not use an installer.

Thanks

**Comment by jrmain** [comment]
Thanks. I've already switched to the portable version. I should have done that ages ago.

For the record, Windows 8.1 is still supported by Microsoft, and will be until January 10, 2023. See https://support.microsoft.com/en-ca/help/13853/windows-lifecycle-fact-sheet

There's also no reason to assume that Windows 8.1 is the problem. I have no issues with any other installers. It's possible that the problem is in the 'Advanced Installer' software you used to create the EDD installer.
