### ISSUE TITLE
Materials Panel Filter - Doesn't Apply until Close/ReOpen

### ISSUE THREAD

**Issue by DaddaTheButt** [EDDiscovery/EDDiscovery#2752]
When setting a filter condition with the Materials Panel the filters don't seem to be  apllied when clicking off the filter list. Closing/ReOpening Panel shows correctly filtered set [v11.3.0p].

**Comment by robbyxp1** [comment]
Will investigate, thanks.

**Comment by robbyxp1** [comment]
Found. Thanks
