### ISSUE TITLE
Feature Request - Transparent Materials Panel

### ISSUE THREAD

**Issue by DaddaTheButt** [EDDiscovery/EDDiscovery#2753]
Currently running around Brain Tree Fields collecting Synthesis Materials. Have a 'target' of quantities reqd. Would be nice to support with a transparent overlay of counts (currently running 'on top' but, obviously, obscuring portion of srv's field of view).

**Comment by iainross** [comment]
If you use the shopping list to set your targets you can make that transparent.

**Comment by DaddaTheButt** [comment]
Thx for the response Iain.
Looked at that - was promising but took more real estate and, although have 'clear'ed both lists it's still giving me a crap ton of 'Needed Mats:' which is coming from I know not where :/
As an alternative I compiled a table of 'needed mats' (SRV Premium, 5 of each) for x-compare against EDD Mat Panel.

**Comment by robbyxp1** [comment]
Possible, i'll add it to the wish list.  The wait may be long.

**Comment by iainross** [comment]
Real estate shouldn't be an issue - the two grids are only visible when it's opaque.  When transparent it only shows the left hand text so needed mats (plus a couple of optional things you can turn on and off via the context menu like planets in system with the needed mats or what's on your current planet when landed).

Not sure how you got extra needed mats for things not in your shopping list.  Did you clear both lists with the 'Clear' buttons or by entering zeroes in the wanted column?  The latter approach could miss some if you have any filters on the list hiding non-zeroes.

**Comment by DaddaTheButt** [comment]
Iain, Oooo - so close! Wasn't aware of windows 'morphing' when transparent. Will raise seperate issue for extraneous 'Needed Mats:'

**Comment by DaddaTheButt** [comment]
Robby - No Rush, definitely a Feature Request ;) I find the transparency feature hugely useful as I'm typically on the other side of the room (armchair, PC+Xbox Elite Controller) so can set up then retire to comfortable flight. Would effort be worth investing into implementing Transparency as a general PopOut function (as opposed to selected (potentially expanding list of) Panels)?

**Comment by robbyxp1** [comment]
Grids can't at the moment be made transparent, so only certain panels can do that.  Thats just the way the system works and we will have to live with it.  So the main ones based on grids can't be transparent.

Thanks for your suggestion, but I'm not going to reengineer this at this time.

**Comment by DaddaTheButt** [comment]
Ahhhh, that explains the 'morphing' for shopping list then :)
All fine and understandable.
Impressed with how clean the issue list is here but is there 'Transparent Grids' Feature Request logged 'somewhere' and is that 'available' (along with others) for pre-check to reduce recurrence? Maybe something on the Documentation Project? (I'll check that seperately).
