### ISSUE TITLE
Shopping List - 'Needed Mats' still present on PopOut after 2xClear

### ISSUE THREAD

**Issue by DaddaTheButt** [EDDiscovery/EDDiscovery#2755]
First Foray into 'Shopping'
Initially on Tab - 'Clear'ed both Synthesis and Upgrades but Needed Mats: still listing many items. Following day (incl relog) these did go away. However...
On PopOut - Extraneous 'Needed Mats:' still appear, even after 2xClear and ReLog (see attached ScreenShot)
![ShoppingList](https://user-images.githubusercontent.com/36791039/77247339-10871000-6c28-11ea-87d7-d851964fb0f5.png)
Happy to chat on Discord (DaddaTheButt) if helpful.

**Comment by robbyxp1** [comment]
I'll look.

**Comment by robbyxp1** [comment]
Actually, there is no error. You have two panels open. One in a tab and a popout.

Each one is independent of each other.  Each has its own settings. Changing one will not effect the other.

All panels hold their own configuration.

i'll let you read this and I will close this tomorrow if you don't comment further.

**Comment by DaddaTheButt** [comment]
I opened both purposefully to demonstrate the issue. I have 2xClear'd the PopOut but still shows the extraneous mats that used to be on the tab (which you can see is now clear after yesterday's 2xClear but only 'eventually').

**Comment by DaddaTheButt** [comment]
Could be a 'semantic' issue of clear-v-wanted-v-default filters.
Bit of investigative fiddling - I've never stated anything as 'wanted' and pressed 'Clear' in both groups and was expecting (and I think 'New User Expectation' is the key here) Needed Mats: to be empty but, however, do have quite an extensive list.
Turning ALL filters to 'None' clears that list.
Turning ON 'Special Effects/AngledPlating' adds '5 Compact Composites' to list.
Neither TechBrokerUnlocks nor SpecialEffects are in the grid so presumably:
  a) Do not have a 'Wanted' value and hence
  b) Are not 'Clear'ed by the onscreen button
Implication therefore that 'Wanted', in respect to Unlocks/Effects, is a boolean driven by filter state.
If this is the case then intuitive use could possibly be 'improved', in terms of a default state of 'Wanted'=Nothing, by an initial state of Unlocks/Effects 'NONE' and also setting these to 'NONE' as a result of a 'Clear' (thus satisfying the general response to extraneous Needed Mats: of 'have you pressed 'Clear'?).
I presume this does not apply to the 'Upgrade' grade as I don't think there any 'boolean' Wanted's.
Couldn't see any user documentation around this - happy to help with the Documentation Project if provide details of where get involved.

(NB: There's an issue I observed whilst fiddling somewhere with Filter State being (none)applied immediately (where opening Unlock/SpecialEffects drop-down IMMEDIATELY updates Needed Mats: ) but I can't determine a consistent replication sequence)

**Comment by robbyxp1** [comment]
I'll have to investigate this later in the week... thanks for the report.

**Comment by robbyxp1** [comment]
Found, the filter was borked when i stopped it autoupdating on every entry.

fix coming along today. thanks for the report.
