### ISSUE TITLE
Voice pack information incorrect

### ISSUE THREAD

**Issue by tarbault** [EDDiscovery/EDDiscovery#2758]
Hi,
I love this software and the help it provides when exploring !

One problem so far: Whatever system I jump to , the voice says " total of one star and six planets in this system"... regardless of the real count.

**Comment by robbyxp1** [comment]
I'll check. Thanks

**Comment by tarbault** [comment]
maybe a false alert: happens only for some systems (seems those for which there is no data available ?)
Feel free to forget about it .
Thanks

**Comment by robbyxp1** [comment]
ok
