### ISSUE TITLE
Translation of the voicepack, atf translation OK but how to proceed with variables contents ?

### ISSUE THREAD

**Issue by codje** [EDDiscovery/EDDiscovery#2759]
Hello,

First, very good software, thanks for that!

I use also the voicepack addon as it adds nice information to play with.

I have started a french translation of the atf file and managed to rephrase almost everything.
It plays well with microsoft french voice.
However the issue remaining as you can imagine is the text not directly put into the atf, I mean the contents of the different variables. In the log, sometimes it's in french, sometimes it's in english.

For example, a type of star will be in English and the TTS voice will struggle saying it.
Is there a way to translate all these variables as well ?

I contact you as advised in the wiki but probably putting it as an issue is maybe not the way to go.. Sorry if that's the case

Thanks.

**Comment by robbyxp1** [comment]
Yes, some of the stuff fed to us from Elite is not translated.

if you look at the code around say_tx_* variables, they list subsitutes to replace text with..  

    Static say_tx_power1 = Archon Delaine;<phoneme alphabet='ipa' ph='ˈɑːkɒn'>Archon</phoneme> <phoneme alphabet='ipa' ph='dəˈleɪn'>Delaine</phoneme>

the first part is the text to search for, the seocnd is the replacement text, a ; separates them.

I would set up another list, under a different prefix name (call it say_rep*, for some of the things you want translated.  Then you need to sprinkle in       Set speech = "%replacevar(speech,\"say_rep\")" to do the replacement.  Most of the speech goes through Program speak, so you could place it in there to pick up some more substitutions..

**Comment by robbyxp1** [comment]
You can join our discord if you want to speak more interactively with us.
