### ISSUE TITLE
Is EDDiscovery able to show me all scanned and mapped data ( Credits ) I will get on next station ?

### ISSUE THREAD

**Issue by delaware1999** [EDDiscovery/EDDiscovery#2764]
I am asking my self and I cant find it in the EDDiscovery..

This app is tracking really everything..

When I go on a exploration tour i get 20.000.000 Credits for example when I visit the next station.

But how can I see, and where can I see, in game or in EDDiscovery before I enter a station how much credits I did collect allready ??

This is a very importand function I think ? 
Does EDDiscovery support that fuction and if not why not ?

**Comment by klightspeed** [comment]
In the Travel tab of the Statistics panel, the Scan value has an estimate of the total value of your scans, with the Last Dock being the estimated value since you last docked.

**Comment by delaware1999** [comment]
Where can I find this " Travel Tab " ? or the " Statistics Panel " ?

**Comment by delaware1999** [comment]
Í did find it.. But the " Mapped " value is  not correct. I did scan  more the 3.000.000 credits and it only shows me  4 credits

**Comment by klightspeed** [comment]
Mapped is the number of bodies you have mapped, not the value of the bodies you have mapped.

**Comment by delaware1999** [comment]
Ok I understand.. But where is the complete value of all scanned stuff I did scan..

Why does this greak mega app this not show somewhere ?`This is again a very importand function..

**Comment by klightspeed** [comment]
The game does not provide an exact value, and EDDiscovery can only estimate the value based on actual scans (it can't estimate the value of systems you have only honked).

**Comment by delaware1999** [comment]
ok.. Thats really bad.. When I use the site https://www.spansh.co.uk/riches/ it works perfectly.. This site tells me how much I will get when I will mapp the planeds. And on the end of the story this is 90% correct when I give in a station the scanned and mapped data I get the credits show on **https://www.spansh.co.uk/riches/**

Why does not EDDiscovery use the same mapped value ?

**Comment by klightspeed** [comment]
Please give an example of a planet where EDDiscovery has given a wildly inaccurate value versus Road to riches.  You can see the estimated value of bodies by selecting them in the Scan panel, which should include a mapping bonus if you have mapped the body.

**Comment by delaware1999** [comment]
No I dont ment that it gives wrong data.. It gives you only the collected credits from the date..

For Example . It shows me only how many mapped planets I did find from 13.04.2020 - 13.04.2020  and the normal scanns. Not how much credits I get for the mapped planets. 

But I want a summary of what I get for all when I enter a station and give it to them
This must be possible or is it not allowed for you guys to show it from frontier by their rules and laws ?

Your perfect app EDDiscovery shows us nearly everything. But why not all exploration data on one single place directly on the main screen " History " on some corner.. There is enough space left to do that in the " History " Panel.

**Comment by klightspeed** [comment]
You can e.g. change the nearest stars panel on the history tab to the Statistics panel by mousing over the upper-left of the panel, then clicking on the panels icon, and selecting Statistics Information from the dropdown.

You can also add a new panel to the tab by e.g. right-clicking on the divider below the history panel, and clicking Split Bottom Panel, then mouse-over the Stop icon, click the Panels icon, and select Statistics Information from the dropdown.

In the Time dropdown, you can select Custom, then select a custom start and end date.

Note that the panels can only operate off information loaded into memory.  If you have selected only load 7 days from the settings panel, then the panels will only show data for the last 7 days.

**Comment by iainross** [comment]
In the statistics panel, on the Travel tab, change the `Time` drop down to `Summary`.  You should now have the statistics summarised across various time frames, one of which is `Last Dock`.  The second row from the bottom will show you `Scan Value`.  That is the number you are looking for, I think, the estimated UC value you have accumulated from scans and mapping since you last landed in a station.

For the statistic tab to be accurate the settings tab must have `Entries to read` set to `Disabled - All` *or* if you have set it to a lower timeframe then the `Essential Entries` drop down must be set to one of the top two entries.

**Comment by robbyxp1** [comment]
Closing
