### ISSUE TITLE
Can I trigger a profile with a ship-name? or type of weapon/loadout?

### ISSUE THREAD

**Issue by six-shooter** [EDDiscovery/EDDiscovery#2766]
I want to get my eddiscovery to switch to a mining-profile based on the mining-equipment on board, or the ship-name/ID. Is this possible?

**Comment by robbyxp1** [comment]
I'm going to look into this tomorrow.

**Comment by six-shooter** [comment]
Thanks mate!

**Comment by robbyxp1** [comment]
So i've answered you question by updating the wiki 

https://github.com/EDDiscovery/EDDiscovery/wiki/Profiles

This shows an example of setting up a condition to detect if the shipyard new/swap occurs, which means you've jumped into another ship.

This is about as detailed as I can get. If want more, you need to understand more of the action programming system, which is described in a document and text file, which you can find in the Using Actions part of the wiki.  Here you can find the variables associated with each event, and construct an expression to trigger on them.

thanks for the question.
