### ISSUE TITLE
Exported estimated values don't match the internal estimated values

### ISSUE THREAD

**Issue by Qumfur** [EDDiscovery/EDDiscovery#2767]
This is a weird bug I stumbled upon in the last few weeks.

I'm a heavy user of the export function of the exploration data. I like to analyse my explored systems.
I also track the estimated values. This is more or less useless because EDSM and EDDiscovery itself also track those, but I noticed the exported values don't match the internal numbers. 
So I waited to turn my data in to look which one is correct. 
That happened yesterday and to no surprise the internal numbers were more or less correct. 

So I went digging for the problem:
[Here](https://imgur.com/a/uKjHsWT) is an example of a random system I pulled up.
The bottom picture is the estimated values tab from EDDiscovery. The top one is directly exported and imported into an excel spreadsheet (The duplicated entries from mapping are already sorted out).
As you can see the values for the star and the bodies 1, 2 and 3 are the same. Those are the ones I scanned _and_ mapped. 
The bodies 4, 5, 6 and 7 on the other hand are not matching. I scanned but did _not_ map them.

What I **think** went wrong here is that it somehow assumes that all planets are scanned _and_ mapped in the exported data. If that would be the case, the values roughly match the expected values.

What seems like only a small difference added up pretty signifficantly: In the end the difference was almost 200 million credits or roughly 30%.

**Comment by robbyxp1** [comment]
I'll look, thanks

**Comment by robbyxp1** [comment]
My theory is this.

The excel comes from your scan results only.  The Journal Scan reports if a body has been mapped/discovered and therefore the computation can take that into account and produce a figure based on that

The panel looks at your scan data, and does an EDSM lookup.  EDSM does not know if a body is scanned in the same was as Elite does.

This is probably the discrepency.

I'll add in a turn off EDSM lookup on that panel and we can see if the values then are the same.

**Comment by Qumfur** [comment]
I don't think I understand what you are saying here. 

[Example](https://imgur.com/9fNwvXn)
What I did was pressing this button (Blue circle) and importing the resulting .csv-file into my spreadsheet.
My Problem is, that the red incircled value is not the same as in the spreadsheet. 
But the value in this panel is **correct**. The value in the spreadsheet is **not** correct.
First I thought the problem is in the spreadsheet but that's not the case. 
The problem is in the exported data. 
I don't know how the .csv-file is created but it seems like it somehow assumes that all planets are scanned **and** mapped.
The panel itself correctly recognises the planets I did _not_ map.
The exported data does not.

**Comment by robbyxp1** [comment]
The excel just looks at scan results in the DB - it does not use EDSM.
The scan result has a wasdiscovered/wasmapped flag (since last year) which can tell us how to compute the figure.  I've checked and its using the function which takes into account this.
Therefore the excel results should be the right ones.

The panel also looks up EDSM, which does not report wasmapped/wasdiscovered therefore we always present the lowest price.

Your saying the excel is wrong? Is that based on what you actually sold it for? 

I'll double check with some of mine and see if i can see any discrepancies.

**Comment by Qumfur** [comment]
Yes that is based on what it actually sold for. Sadly I can't show you an example from a single system now.

Overall on the last trip I got: 620.530.673 Cr
The excel predicted : 818.645.710 Cr
The panel predicted about: 615.000.000 Cr

My theory were the difference comes from has nothing todo wether someone discovered/mapped it before. The wasmapped/wasdiscovered and EDSM has nothing to do with it. The excel somehow assumes I, the player, physically went to each and every planet and mapped every single planet.
That is not true.
The panel knows that.

**Comment by robbyxp1** [comment]
will keep on digging.
