### ISSUE TITLE
Engineering Recipes for DSS

### ISSUE THREAD

**Issue by DaddaTheButt** [EDDiscovery/EDDiscovery#2768]
Engineering(/ShoppingList et.al) still showing pre 3.3 recipes for Surface Scanner.

Fast/Long/Wide as opposed to Expanded Radius

**Comment by robbyxp1** [comment]
Okay, i'll double check those against inara. Thanks

**Comment by robbyxp1** [comment]
Cheers, removed the extra ones, now just showing

![image](https://user-images.githubusercontent.com/6573992/79634339-bc594800-8161-11ea-93ef-e47a9e6274f7.png)

**Comment by DaddaTheButt** [comment]
Most Excellent - Thank You Sir
