### ISSUE TITLE
Grid line number column resizeable

### ISSUE THREAD

**Issue by philcart** [EDDiscovery/EDDiscovery#2771]
EDDiscovery v11.3.1.0
EDSM Theme

The first column of numbered grids (History, Journal, Exploration, etc...) is resizable and the row numbers can be cut off.
![image](https://user-images.githubusercontent.com/4084083/80023210-8a106780-8520-11ea-96c3-26f2adab38f0.png)

Ideally the row number column should be fixed.

**Comment by robbyxp1** [comment]
I'll keep this in mind, but its probably not as easy as it looks with variable size Fonts. Thanks for the suggestion.

**Comment by philcart** [comment]
I did have a little wander through the C# code with my hack developer eyes. Couldn't see where the numbering came from. Is it a property of the DataGridView control itself?

**Comment by klightspeed** [comment]
The row numbers are drawn in a RowPostPaint event handler.

Perhaps in an OnPaint override measure the needed width, then in a Layout handler resize the row headers if needed?

**Comment by robbyxp1** [comment]
This whole area needs very very careful treading over, as we have found out in the past trying to save the grid sizes.  

The header column size could autosize to the largest number, but i don't want to take away the ability of a user to say i don't care about the numbers, and maximise the space.

I'll have to have a ponder.  One way is to autosize the font to the available size.  Another way is to provide yet another switch to allow it to autosize.

**Comment by robbyxp1** [comment]
And you don't need to do it in the layout - you can calculate in the display function what the maximum value you are going to print, then measure it in the font, then set the header column size appropriately.

**Comment by klightspeed** [comment]
Maybe allow for e.g. 6em by default for travel history / journals, and 3em by default for everything else?

**Comment by robbyxp1** [comment]
I've made a note of this idea.
