### ISSUE TITLE
Feature Request - Screenshot conversion - Multiple Outputs

### ISSUE THREAD

**Issue by jeremymarx** [EDDiscovery/EDDiscovery#2773]
I'd love to see the screenshot conversion have an option to output more than one converted image file. The second would typically be useful for social sharing, such as on screenshot forums like on reddit, discords, twitter, etc.

For example, I have 8k screenshots that EDD is converting to PNG. While keeping the "original" hi-res PNG, I'd also like a "Full HD" 1080 that I can share.

**Comment by robbyxp1** [comment]
Will investigate - mostly its the UI aspects which will have to be considered.

**Comment by robbyxp1** [comment]
Coming to next version. Thanks for the idea.
