### ISSUE TITLE
Failed mission are not removed

### ISSUE THREAD

**Issue by xzenor** [EDDiscovery/EDDiscovery#2774]
In the missions screen the missions that failed just stay there as active missions until the End Date.
You can't do anything with them anymore, they're no longer available in the game but you can't get rid of them.

**Comment by klightspeed** [comment]
Is there a `Mission Failed` or `Mission Abandoned` event associated with the mission failure?

Perhaps EDDiscovery should treat any missions that are not in the `Missions` event as having been failed or abandoned?

**Comment by xzenor** [comment]
I have to admit. there's an event for accepting the mission and then nothing.
there's no way to find out that the mission even ended in case of a "Contract Terminated" nor  for "Mission failed" through the journal logs.

**Comment by robbyxp1** [comment]
There should be an abandoned event or failed - if not there is something up with the Elite Dangerous journal writer.  If we can isolate that i'll report it to FDEV.  If you have a log showing this we can send it to FDEV.

I think the current system is logical - it stays there until either date expiry or abandon/complete/failed is seen.

There was a reason I did not use Mission to terminate.

**Comment by xzenor** [comment]
I'm not sure how but for some reason the failed missions no longer showed in game..
They did now.. once I properly abandoned them, the missions we also removed from the list of active missions in EDDiscovery.
So I guess this was an issue with the game (or the person playing it) and not with EDDiscovery.
