### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by bazza14** [EDDiscovery/EDDiscovery#2779]
Hi, Reporting this because it told me to. It may be because I'm trying to downgrade to 10.6 from 11.4.1
### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
>no such table: SystemNames
>   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at SQLLiteExtensions.SQLExtDataReader`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLExtTransaction`1 txn, SQLExtTransactionLock`1 txnlock) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLReader.cs:line 38
>   at SQLLiteExtensions.SQLExtCommand`1.ExecuteDbDataReader(CommandBehavior behavior) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:line 92
>   at EliteDangerousCore.DB.SystemClassDB.GetEdsmIdsFromName(String name, SQLiteConnectionSystem cn, Boolean uselike) in C:\Code\EDDiscovery\EliteDangerous\DB\SystemClassDB.cs:line 276
>   at EliteDangerousCore.DB.SystemClassDB.GetSystemsByName(String name, SQLiteConnectionSystem cn, Boolean uselike) in C:\Code\EDDiscovery\EliteDangerous\DB\SystemClassDB.cs:line 301
>   at EliteDangerousCore.SystemCache.FindSystem(ISystem find, SQLiteConnectionSystem conn) in C:\Code\EDDiscovery\EliteDangerous\DB\SystemCache.cs:line 79
>   at EliteDangerousCore.HistoryList.FindSystem(String name, GalacticMapping glist) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 715
>   at EDDiscovery.UserControls.UserControlRoute.UpdateTo(Boolean updatename) in C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlRoute.cs:line 474
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
This is a known bug in 10.6.0.0.  

We are now on 11.4.1 so your one year behind. 

I suggest updating the program.  The update past 11 will require a rebuild of the system DB so you will need to be patient.

Thanks for the report.

**Comment by robbyxp1** [comment]
If you want to solve it with 10.6.0.0, use safe mode (hold down shift then run) and delete the system DB, then let it rebuild.
