### ISSUE TITLE
French Traduction

### ISSUE THREAD

**Issue by Actarus37** [EDDiscovery/EDDiscovery#2784]
Hello,
I have been using EDDiscovery since I started in Elite Dangerous and first of all congratulate you for this wonderful tool!

What brings me here is that I am French and I noticed that there was no French translation. I therefore offer you my services to translate your work, it would be with pleasure that I would put my little stone to this building.
Hoping to read you soon.

Regards and Fly Safe !

CMDR ACTA

**Comment by robbyxp1** [comment]
Hello,

Glad you like it.

The translations are held in .tlf and .tlp files in the github repo.

There is an example-ex ones which guide you to what to translate - you can start by just doing the major panels, it does not all have to be done. 

A guide is here
https://github.com/EDDiscovery/EDDiscovery/wiki/Translations

Once you get the concept, its really simple.  If you look at your install folder, you'll see the translation files for the current languages in there and can get an idea.

I need to update them to the latest before anyone works on them again - thats on my todo list.

**Comment by robbyxp1** [comment]
Our discord is a better place to talk to us btw, there is a channel for translations:

https://discord.gg/sJENEc

I'll close this, let me know if your doing anything with this via the discord.
