### ISSUE TITLE
Unhandled UI exception using the material trader

### ISSUE THREAD

**Issue by xenophonf** [EDDiscovery/EDDiscovery#2787]
### Description
I was trying to clear my previous trade (for arsenic) and select a new element (for manganese).

### Additional Information
I'm not sure which logs to attach, so I'm grabbing the most recent of everything.
[Elite Dangerous.zip](https://github.com/EDDiscovery/EDDiscovery/files/4562354/Elite.Dangerous.zip)

### Exception Details:
>EDDiscovery v11.4.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlMaterialTrader.extPictureTrades_ClickElement(Object sender, MouseEventArgs eventargs, ImageElement i, Object tag) in C:\Code\EDDiscovery\EDDiscovery\UserControls\EngineeringSynthesis\UserControlMaterialTrader.cs:line 458
>   at ExtendedControls.ExtPictureBox.OnMouseClick(MouseEventArgs e) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\PictureBox.cs:line 435
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Thanks, will check.
