### ISSUE TITLE
materials filtering

### ISSUE THREAD

**Issue by batkung** [EDDiscovery/EDDiscovery#2789]
would it be possible to have materials filtering split into subfilters?..that way you can filter by material type (Raw/Encoded/Manufactured or the individual materials) and then have another filter that will filter the results of the first filter by the rarity? in effect giving you :-
 (Raw OR Encoded OR Manufactured OR Individual Material..) AND (Rare OR Very Rare OR Common etc)

**Comment by robbyxp1** [comment]
So, the answer is of course it would be, but its unlikely to be coded right now, as there are lots of other stuff on the boil for the moment.

I'll keep it in mind when we touch this panel again.

thanks for the idea.
