### ISSUE TITLE
EDDiscovery Hangs for a while, then will recover 30s-30m later

### ISSUE THREAD

**Issue by cgc007** [EDDiscovery/EDDiscovery#2795]
I upgraded from 11.3.1 to 11.4.1. This error occurs in 11.4.1 but not in 11.3.1.

I've noticed that the voice pack reads things to me in a less timely manner now, which is how I discovered that EDD was hanging in the first place.

I haven't pinned down why it stops responding, but it ceases to take user input for periods of time, and then finally catches up and reads all the voice journal events and performs all UI interactions that were done with it sequentially.

As I narrow it down more, I'll flesh this out more, but I wanted you to be aware of it.

**Comment by robbyxp1** [comment]
We have identified more issues with some grids when they are not in the foreground - mission grid for instance.

Try going back to basics and having only the history + settings tabs open, and see if it does it then.

rob

**Comment by robbyxp1** [comment]
Try the new one. thanks
