### ISSUE TITLE
BUG Market Data

### ISSUE THREAD

**Issue by bazza14** [EDDiscovery/EDDiscovery#2805]
When carrying the relevant commodity. VO and LTD cargo show on a separate additional line such that you have 2 entries for these commodities, one showing the market data and 0 cargo and one showing no market data and the correct cargo.

**Comment by robbyxp1** [comment]
Not getting what you mean exactly. Have you got a screenshot of it?

**Comment by bazza14** [comment]
See attached. Alexandrite which is buyable shows correctly but VO and
LTD have 2 entries each.
