### ISSUE TITLE
Bug System Info, Set Target

### ISSUE THREAD

**Issue by bazza14** [EDDiscovery/EDDiscovery#2809]
Unable to set target. typing the system name works but it does not give a distance and clicking the EDSM button pops up a 'System unknown to EDSM' message

**Comment by klightspeed** [comment]
If you search for the system on EDSM, is it found?

Getting `System unknown to EDSM` means that the program queried EDSM and EDSM returned nothing.

**Comment by bazza14** [comment]
I have tried well known systems such as Achenar, Rhea and Colonia. The
fact that it does not pull up the distance and EDSM returns unknown
suggests that the input is not being read correctly. Does setting a
target require an internet connection? I ask because I'm on cellular
network which sometimes has low data rates and high latency.

**Comment by klightspeed** [comment]
Getting the distance to the system needs a local copy of the systems database, and getting the EDSM link needs to be able to connect to EDSM if that database is not present.

**Comment by bazza14** [comment]
OK I've checked in the journal for Achenar and I have confirmed that it is present so it should be giving me the distance. Also the fail message when clicking the EDSM button is almost instantaneous, far to fast to have tried and failed to connect to EDSM. FWIW the 'Open' EDSM button near the top of the panel works as expected.

**Comment by robbyxp1** [comment]
You did not tell us if you've downloaded the system database.

The algorithm checks the system db for the star, failing that, it checks your history, and also checked the list of EDSM Galactive points of interest.  If it finds a star in these locations, the EDSM button will go to the page of the star on EDSM.  Failing to find one will instantly give a can't find warning without connecting to EDSM.

Achenar is a G POI object so should be found.

I've simulated this without having a system DB and achenar is found, barnard star (which is not a POI) is not, as expected.

Any more info?

**Comment by bazza14** [comment]
I have the system DB downloaded and it updates every time I launch EDDis. As I feel we may be wandering off at a tangent I'd like to stress that the bug is about not being able to set a target, the not getting a distance is a symptom. I type the target system into the box, as each letter is entered the drop down of systems gets shorter until one sees the system in the list then one clicks on that system thereby entering that name into the box and then nothing else happens. No distance to the target displayed, Trip Computer reports no target set.

**Comment by klightspeed** [comment]
Are you pressing enter?

**Comment by bazza14** [comment]
No I didn't press enter. I made the assumption that clicking the system name completed the transaction.
