### ISSUE TITLE
Program unresponsive when viewing Scan tab for system jumps

### ISSUE THREAD

**Issue by SkoidUK** [EDDiscovery/EDDiscovery#2811]
I fly with the standard History tab (last 7 days) and the Scan tab open. If I'm on the Scan tab and jump to another system (while out in the black), it becomes unresponsive for a long time; I cannot switch to another tab and no system details (apart from the name) appear despite having done a honk. For me the programs springs back to life after around 1.5 minutes - the discovered bodies appear and I can switch tabs again (e.g. History). This behaviour is not replicated if I'm on the History tab while jumping; everything updates as expected and the program remains responsive.

**Comment by iainross** [comment]
What version are you running?

**Comment by SkoidUK** [comment]
Sorry, I guess that would help! :) 11.4.4

**Comment by robbyxp1** [comment]
Do you have the EDSM button turned on? If so, its doing a web access and will halt until the access succeeds.

**Comment by robbyxp1** [comment]
![image](https://user-images.githubusercontent.com/6573992/82153883-26990180-9862-11ea-8175-321d2948df51.png)
Make sure the EDSM button is off and see if it makes a difference.

**Comment by robbyxp1** [comment]
Closing, no reply

**Comment by SkoidUK** [comment]
Sorry for not getting back on this. I have not had the chance to check this out yet. From the questions asked it makes sense that this is what has happened. Am I right in thinking that the settings on each tab are independent, so that the scan area of the History tab and the Scan tab can be altered to different settings? If so, that would make sense for the behaviour I am seeing. Either way, EDDiscovery is the one tool I use while flying (with the odd visit to the EDSM, EDDB and Inara websites) and I love it. Cheers, Simon

**Comment by robbyxp1** [comment]
Thanks. If you have EDSM clicked, it will do a web access, and the panel its on will freeze for a short while. If EDSM or the internet is having a bad day, that can be a while.  Sometimes I see this freezing the whole program (which its not designed to do) and I'm investigating why that is. Thanks for the report.
