### ISSUE TITLE
Theme change didnt work

### ISSUE THREAD

**Issue by andrewcurd** [EDDiscovery/EDDiscovery#2812]
### Exception Details:
>EDDiscovery v11.4.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: No room is available to display rows.
>   at System.Windows.Forms.DataGridView.set_FirstDisplayedScrollingRowIndex(Int32 value)
>   at DataGridViewControlHelpersStaticFunc.MoveToSelection(DataGridView dgv, Dictionary`2 index, Tuple`2& pos, Boolean force, Int32 column) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\WinForms\DataGridViewHelpers.cs:line 320
>   at EDDiscovery.UserControls.UserControlStarList.<>c__DisplayClass31_0.<HistoryChanged>b__0() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlStarList.cs:line 219
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Did it work when you restarted?

**Comment by robbyxp1** [comment]
I will protect against this happening again - updated code
