### ISSUE TITLE
Geological Scouting Report Error: output file path not set.  Disable then re-enable the pack to select the path

### ISSUE THREAD

**Issue by ABELSS** [EDDiscovery/EDDiscovery#2813]
Hi All,

Thanks for the great work!

On startup of ED Discovery i get below log with in bold the error. How to get rid of it?
I can only find back that geological items are to be decided if it is going to be implemented.

**log extract on startup**
Checking for new EDDiscovery maps
Checking for new Expedition data
Checking for new Exploration data
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
Voice Recognition Pack running.
JKM Pack installed, running on EDD Version 11.4.5.0
Scanning for bmp screenshots in C:\Users\ABELSS\Pictures\Frontier Developments\Elite Dangerous
*** Web server is disabled ***
Profile Default Loaded
Match of FD Device SaitekX55Joystick to Saitek Pro Flight X-55 Rhino Stick
Match of FD Device SaitekX55Throttle to Saitek Pro Flight X-55 Rhino Throttle
Match of FD Device Keyboard to Keyboard
Match of FD Device Mouse to Mouse

**Geological Scouting Report Error: output file path not set.  Disable then re-enable the pack to select the path**

Sound Blaster pack installed

**Comment by robbyxp1** [comment]
Go into Add-Ons and edit addons.  Turn off the geo pack and quit the menu
Go back in again and turn it on. It should pop up a dialog asking for a path to write the files to.

**Comment by ABELSS** [comment]
Thanks. It did solve the issue. Had first overlooked that package.
