### ISSUE TITLE
Sending to INARA Does not work on Window 7

### ISSUE THREAD

**Issue by daveokeeffe** [EDDiscovery/EDDiscovery#2817]
Hi,

After a month or two hiatus from ED I returned and found that ED Discovery is no longer able to update INARA.  The only error message I can see in the Log window is"

INARA Reports: No Response

From digging around on Discord and on INARA I found some talk of Windows 7 support being left behind because it doesn't support certain ssl ciphers.  See [more here](https://inara.cz/board/7049/333379/?page=24).

Is there anything that can be done about this on ED Discovery's side?  I tried adding `-forcetls12` parameter in the ED Discovery app shortcut, but that didn't help sadly.

EDMC still works ok, so I'm crossing my fingers that a fix can be added here?

**Comment by klightspeed** [comment]
EDMC runs on Python, which bundles its own SSL implementation.

Chrome also uses its own SSL implementation.

EDDiscovery runs on dotnet, which uses the system SSL implementation.

A workaround might be to try running EDDiscovery under Mono for Windows.

I don't know if it would be worth using Bouncy Castle to support Inara on Windows 7 and Windows 8.1

**Comment by robbyxp1** [comment]
If windows 7 was still officially supported by Microsoft, then it would be fixed. But its not anymore, and there is nothing we can do reasonably to fix it.  So I'm afraid when Inara changed its policies it made windows 7 maching unusable for EDD for the Inara upload.

**Comment by klightspeed** [comment]
The same issue would affect Windows 8.1 users - Windows 8.1 exits support in 2023.  I guess not many people don't use Windows 8.1, as we haven't seen any complaints from any Windows 8.1 users.

**Comment by robbyxp1** [comment]
So, closing this as we can't fix it without a major reengineering of the internet layers of EDD, which we are not prepared to do as these O.S are very old now and are superseded by 10.

**Comment by daveokeeffe** [comment]
Thanks for looking into it guys, I really appreciate it.  I agree that adding your own ssl implementation for a deprecated OS is a bit much.

**Comment by Ejsstiil** [comment]
Thats a big grief as I am using W7 x64... Tried to update SSL stack inside windows but without luck. Is there any DOT NET drop-in replacement of SSL from third party? Aka drop libssl.dll or ssleay32.dll etc??

**Comment by robbyxp1** [comment]
Hi, we have talked about this a lot, and we have not found any way around it.  So as I said above, without a reengineer, which is not going to happen, its not supported.

sorry

**Comment by klightspeed** [comment]
Does mono work?  https://www.mono-project.com/docs/getting-started/install/windows/

**Comment by Ejsstiil** [comment]
Downloaded (x64), installed but still "No response". How to launch EDD under mono?

**Comment by Ejsstiil** [comment]
Tried but it always hangs on startup during "Checking databases" :(

**Comment by klightspeed** [comment]
After adding some debugging:
```
[2020-07-11T09:55:17.206Z] Native library pre-loader is trying to load native SQLite library "D:\Users\klightspeed\git\EDDiscovery\EDDiscovery\bin\Debug\x64\SQLite.Interop.dll"...
[2020-07-11T09:55:17.209Z] Unable to load System.Data.SQLite: System.DllNotFoundException: SQLite.Interop.dll assembly:<unknown assembly> type:<unknown type> member:(null)
```

Using Process Monitor, it looks like `SQLite.Interop.dll` references `kernel32.dll`, and for reasons unknown mono tries and fails to load this from the directory the executable is in, and doesn't try either using the version that is in memory, or loading it from the system32 directory.

```
[2020-07-11T09:55:17.262Z] DB Factory does not work: System.TypeInitializationException: The type initializer for 'Mono.Data.Sqlite.UnsafeNativeMethods' threw an exception. ---> System.DllNotFoundException: sqlite3 assembly:<unknown assembly> type:<unknown type> member:(null)
```

It looks like mono doesn't include sqlite3.dll

Even after extracting the pre-compiled windows x64 sqlite3.dll to the application directory, it doesn't work properly.

So much for "have you tried running it under mono" - it looks like it'd take some work to fix the issues it's having running under Mono, and trying to get Inara communication running under Windows 7 / Windows 8 would also take some work.

**Comment by Ejsstiil** [comment]
Been unwillingly forced to win 10 thanks to Oculus Rift S. :((( So this one is no problem to me anymore. Maybe if there are no others you don't have to waste time...

**Comment by robbyxp1** [comment]
Closing again, as no more people have complained recently!

**Comment by Harag9** [comment]
@robbyxp1 I understand the reason for closing this for Windows 7. I have just downloaded this and created an Inara account (quite new to this) and I get the same "No Response" message - I'm on Windows 8.1 however and that support doesn't end until 2023.

However if you still can't fix this for 8.1 Can I run EDMC (which seems to connect fine as far as I can tell) at the same time as EDD , just have EDMC update inara.

However, really like the look of EDD, looks like it does a lot of extra stuff too!

**Comment by robbyxp1** [comment]
Yes, you can use the normal EDMC to do this. Just make sure EDD does also send to EDDN, by using commanders settings.

**Comment by Harag9** [comment]
@robbyxp1 Thanks for confirming that, I've gone through the configs of them and set them up. was just about to uninstall EDMC but I'll keep that on and run both.
