### ISSUE TITLE
Documentation on GMO EXISTS command has a typo

### ISSUE THREAD

**Issue by tloimu** [EDDiscovery/EDDiscovery#2823]
"Action" document version V17 has a typo on EXISTS command. It says **EXIST**. Found from source code that one needs to use **EXISTS** instead - unlike with Bookmarks function.

Also, the GMO command could use some further explanation on its usage specifically how and what kind of searches can be made.

**Comment by robbyxp1** [comment]
Thanks for the report. I've looked thru the document vs all the "Exists" in the code base and found only one, direxists, which is wrong.

Can you tell me exactly what you mean? Ie. The source code location.

**Comment by robbyxp1** [comment]
Ok on second reading got it, thanks for the report.
