### ISSUE TITLE
Journal Event FSDTarget does not get triggered

### ISSUE THREAD

**Issue by tloimu** [EDDiscovery/EDDiscovery#2824]
When player journal gets "FSDTarget"-event, it does not trigger EDD Journal Event "FSDTarget" in actions/plugins. Also, these events are not shown in EDD events log UI either. However, EDD UIEvent named "UIFSDTarget" does get triggered here at least in actions/plugins.

I have a feeling that the EDD UI's lack of showing the FSD Target events roots from this issue as well.

Similarly, at least Journal Event "Music" is never triggered, but UIEvent "UIMusic" is.

So, are the Journal Events getting deprecated or is this unintentional?

**Comment by robbyxp1** [comment]
The FSDTarget journal event is turned into a UI event by design.  Not showing the FSDTarget in the journal history is also by design, because it just floods the history log.  It was turned off for that reason.

Thanks

**Comment by tloimu** [comment]
Roger that.

To avoid confusion for programmers, it might then be useful to remove these turned-off journal events from the EDD's Add-On Editor's where you can use the GUI to "write code" and select an event from a popup menu to choose what triggers a piece of program. Or have them actually produce code that has the UI-prefix in them.

**Comment by robbyxp1** [comment]
I'll think about that
