### ISSUE TITLE
Can't install 11.5.0 - install directory left behind.

### ISSUE THREAD

**Issue by dsnt02518** [EDDiscovery/EDDiscovery#2831]
Having uninstalled version 11.4.5 and rebooted, the installer still complains that a previous version has been detected and refuses to install.

Running on Windows 10.

Deleting the (now empty) C:\Program Files\EDDiscovery and it's empty EDDiscovery folder inside rectified the problem, but thought you'd want to know.

**Comment by ntorgov** [comment]
Same issue

**Comment by robbyxp1** [comment]
Yes, I know about this.. For some reason the uninstall is leaving the folder behind.

thanks for the report.
