### ISSUE TITLE
Can't read logs after use of Fleet Carriers

### ISSUE THREAD

**Issue by Nozdu** [EDDiscovery/EDDiscovery#2833]
Hello,

I have a problem since last update in 11.5.0.0
First start of EDDiscovery was OK and crashed after some Fleet Carrier operations. I didn’t read or capture the error message in the infobox.
When I start it again, all modules are empty with no data

![eddiscovery-bug](https://user-images.githubusercontent.com/57685065/84205498-807d9780-aaad-11ea-8b4e-4bac43ae5e4d.png)

Here is the text in the Log Window
```
Scanning for bmp screenshots in C:\Users\Nozdus\Pictures\Frontier Developments\Elite Dangerous
Checking for new EDDiscovery maps
Checking for new Expedition data
Checking for new Exploration data
Web server enabled
Profile Default Loaded
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
History Refresh Error: System.InvalidCastException: Impossible d'effectuer un cast d'un objet de type 'EliteDangerousCore.JournalEvents.JournalCarrierJump' en type 'EliteDangerousCore.JournalEvents.JournalFSDJump'.
   à EliteDangerousCore.HistoryTravelStatus.Update(HistoryTravelStatus previous, HistoryEntry heprev, HistoryEntry hecur) dans C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryTravel.cs:ligne 88
   à EliteDangerousCore.HistoryEntry.FromJournalEntry(JournalEntry je, HistoryEntry prev, Boolean checkdbforunknownsystem, Boolean& journalupdate) dans C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryEntry.cs:ligne 227
   à EliteDangerousCore.HistoryList.LoadHistory(EDJournalClass journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Int32 fullhistoryloaddaylimit, String essentialitems) dans C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:ligne 1010
   à EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) dans C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:ligne 154
History refresh complete.
```

I tried "Refresh History" => It show me Cmdr name of my 2 accounts but nothing happen when I select my main account "Nozdus".
I have uninstalled and delete previous version of EDDiscovery before installing the new one.
My installation is in C:\Program Files\EDDiscovery and I have no C:\Code directory

Tell me if you need more informations

**Comment by HughBourbaki** [comment]
I am also having this problem, but I cannot understand how to implement the fix that you have described above.

**Comment by klightspeed** [comment]
If you extract the files from the build at <https://ci.appveyor.com/project/EDDiscovery/eddiscovery/builds/33424176/artifacts>, and copy the `EDDiscovery.exe.config` file from `C:\Program Files\EDDiscovery\EDDiscovery` over the one in the extracted directory, then try running `EDDiscovery.exe` from that directory, does it fix your error?

**Comment by HughBourbaki** [comment]
That fixed it, thank you.

**Comment by Nozdu** [comment]
Klightspeed, yes, using your portable version with my EDDiscovery.exe.config seems to work.
Thank you.
