### ISSUE TITLE
11.50 unhandled fatal exception has occurred

### ISSUE THREAD

**Issue by jellowiggler** [EDDiscovery/EDDiscovery#2835]
### Description

Loading up EDDiscovery before loading the game as I normally do. I haven't patched to the carrier update yet either.

### Exception Details:
>EDDiscovery v11.5.0.0 An unhandled fatal exception has occurred.
>```
>==== BEGIN ====
>System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>   at EliteDangerousCore.JournalEvents.JournalDocked.FillInformation(String& info, String& detailed) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalDocking.cs:line 118
>   at EDDiscovery.UserControls.UserControlTravelGrid.CreateHistoryRow(HistoryEntry item, String search) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 443
>   at EDDiscovery.UserControls.UserControlTravelGrid.<>c__DisplayClass48_1.<HistoryChanged>b__1() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 296
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
>   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
>   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
>   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
>   at EDDiscovery.Program.Main() in C:\Code\EDDiscovery\EDDiscovery\Program.cs:line 48
>===== END =====
>```

**Comment by jellowiggler** [comment]
I cannot repeat the error now.  Not sure what's up.  If it happens again I'll be back.

**Comment by klightspeed** [comment]
An AccessViolationException (segfault) in managed code usually means that either an unmanaged DLL is messing with stuff, that your overclock is not stable, or that your memory is flaky.
