### ISSUE TITLE
Trilateration get unhandled UI Exception

### ISSUE THREAD

**Issue by Fenrrirr** [EDDiscovery/EDDiscovery#2841]
When i try to open Trilateration and click Start New, ED gives a popup with unhandled UI Exception:
I have tested to unisntall and install the newest version, but the exception comes again.

### Exception Details:
>EDDiscovery v11.5.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
>   en EDDiscovery.UserControls.UserControlTrilateration.<>c.<Set>b__47_0(HistoryEntry j) en C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlTrilateration.cs:línea 776
>   en System.Linq.Enumerable.WhereListIterator`1.MoveNext()
>   en System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
>   en EDDiscovery.UserControls.UserControlTrilateration.Set(ISystem system) en C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlTrilateration.cs:línea 776
>   en EDDiscovery.UserControls.UserControlTrilateration.buttonStartNew_Click(Object sender, EventArgs e) en C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlTrilateration.cs:línea 123
>   en System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   en System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
>   en System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   en System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   en System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   en System.Windows.Forms.Control.WndProc(Message& m)
>   en System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Should be fixed in .2, out today.
