### ISSUE TITLE
There was an unhandled UI exception

### ISSUE THREAD

**Issue by ultrasnail** [EDDiscovery/EDDiscovery#2842]
### Exception Details:
>EDDiscovery v11.5.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentException: Parameter is not valid.
>   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
>   at BaseUtils.BitMapHelpers.DrawTextIntoAutoSizedBitmap(String text, Size maxsize, Font dp, Color c, Color b, Single backscale, StringFormat frmt) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\WinForms\BitMapHelpers.cs:line 113
>   at ExtendedControls.ExtPictureBox.ImageElement.TextAutosize(Point topleft, Size max, String text, Font dp, Color c, Color backcolour, Single backscale, Object t, String tt, StringFormat frmt) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\PictureBox.cs:line 73
>   at ExtendedControls.ExtPictureBox.AddTextAutoSize(Point topleft, Size max, String label, Font fnt, Color c, Color backcolour, Single backscale, Object tag, String tiptext, StringFormat frmt) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\PictureBox.cs:line 204
>   at EDDiscovery.UserControls.UserControlMissionOverlay.Display(HistoryEntry he) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlMissionOverlay.cs:line 200
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 85
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 73
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(Tuple`2 entries) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 185
>===== END =====
>```

**Comment by robbyxp1** [comment]
Got it, your window was so small height got to zero.

Will protect, thanks.

**Comment by robbyxp1** [comment]
Fixed in .2, out today
