### ISSUE TITLE
Markets do not appear to update on empty Fleet Carrier markets

### ISSUE THREAD

**Issue by Vrenshrrg** [EDDiscovery/EDDiscovery#2844]
In trying to verify the prices at various Fleet Carriers, it appears as though once a market does not buy or sell anything, EDDiscovery does not record a market update to send to Inara and other sites.

The Fleet Carrier in question was The Singularitas II (Y27-X2H) in Menguru at approximately 14:00 GMT on the 11th of June, the day of this report. It showed up as buying Tritium on Inara, however upon arrival the market did not display any commodities to be bought or sold.

This information was subsequently not recorded by EDDiscovery (Version 11.5.2.0) and not sent to Inara.

Testing on a different Fleet Carrier which *does* buy various commodities properly updated the market.

I am happy to provide further information if necessary.

Proper market update:
![grafik](https://user-images.githubusercontent.com/66787315/84398281-0e699780-ac00-11ea-8dcf-225e993ce51d.png)
![grafik](https://user-images.githubusercontent.com/66787315/84398340-1cb7b380-ac00-11ea-9c0f-e62dc8844b45.png)

Missing market update (despite opening the commodities market):
![grafik](https://user-images.githubusercontent.com/66787315/84398403-335e0a80-ac00-11ea-8156-2cee7282fd4a.png)

**Comment by robbyxp1** [comment]
This is a known issue.

Its a frontier thing, its not sending a market event to us, and we are therefore not sending a market event to inara.

Not much we can do about it, except tell Frontier.

Thanks for the report.

**Comment by Vrenshrrg** [comment]
Understood, thanks for the quick answer.

Closing this issue.
