### ISSUE TITLE
Alert msg: "Cannot add scan to system - alert the EDDiscovery developers" Duplicate body?

### ISSUE THREAD

**Issue by JWSmythe** [EDDiscovery/EDDiscovery#2845]
I have an error in EDDiscovery.:

```
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object Col 285 Sector CV-Y d57 AB 2 in LTT 4428
```
The log is attached.

Let me know if you need any further information.

[EDDIscovery-error-20200610-cannot-add-scan-to-system.txt](https://github.com/EDDiscovery/EDDiscovery/files/4766000/EDDIscovery-error-20200610-cannot-add-scan-to-system.txt)

**Comment by klightspeed** [comment]
11.4.1 does not support Fleet Carriers.  Please update.

**Comment by JWSmythe** [comment]
Ok.  Updated and now it's happy.  Thank you.
