### ISSUE TITLE
Unhandled journal event -- carrier rename

### ISSUE THREAD

**Issue by 274below** [EDDiscovery/EDDiscovery#2846]
```
{
  "timestamp": "2020-06-11T17:54:23Z",
  "event": "CarrierNameChange",
  "CarrierID": 3701243648,
  "Name": "JEFF",
  "Callsign": "V84-Q5J"
}
```

**Comment by robbyxp1** [comment]
And what version are you running of EDD?

**Comment by 274below** [comment]
11.5.2.0.

**Comment by robbyxp1** [comment]
Oohh, its Frontier!

11.15	CarrierNameChanged
This is logged when a carrier’s name is changed
•	CarrierID
•	Callsign
•	Name

In the journal manual, i'll correct their mistake in our program. Thanks for the report.

**Comment by robbyxp1** [comment]
Need fixing on master and 11.5.x - keep open for now.

**Comment by robbyxp1** [comment]
Fixed on both. next version.
