### ISSUE TITLE
Shopping List - Top Grid Empty

### ISSUE THREAD

**Issue by bazza14** [EDDiscovery/EDDiscovery#2847]
The top grid does not populate for either Tech Broker or Special Effects like Synthesis does although it does add mats to the shopping list.
Further observation - this Tab makes the Engineering Tab redundant

**Comment by robbyxp1** [comment]
I'll check.

And no it does not, i like the engineering tab ;-)

**Comment by robbyxp1** [comment]
So, the top grid won't populate for these, since the top grid is used solely for ordering up the standard synthesis recipes.

Only the shopping list will be changed by enabling one of these recipes.

So No problems I can find.
