### ISSUE TITLE
History Log record

### ISSUE THREAD

**Issue by Jonas14s** [EDDiscovery/EDDiscovery#2848]
![Annotation 2020-06-12 185212](https://user-images.githubusercontent.com/66823727/84484250-db95d100-acdd-11ea-91bf-3b01dee2f18a.png)
Fuel level and capacity are same but it didn't in real. Real cargo capacity is 794 so i think something went wrong. Or you just mean max fuel capacity. If last is what you mean then just im stupid. Sorry

**Comment by klightspeed** [comment]
Fuel level is the current fuel level.
(Fuel) Capacity is the total capacity of your fuel tanks.

**Comment by robbyxp1** [comment]
Closing as explained./
