### ISSUE TITLE
11.5.xxx versions cause VoicePack action pack edits to fail to load

### ISSUE THREAD

**Issue by psybreeze** [EDDiscovery/EDDiscovery#2849]
Using VoicePack 14 version, and any of the new 11.5.xxx versions, even if one just edits an action to "never action" and saves the file, next time EDDiscovery loads it, it will not be able to complete the load and will throw the error "Condition operator Condition is not recognized". Tested by me and Maze905 on Discord. 

edit:
As the EDDiscovery ideas link is the same as for the issues, I'll list this here too.

The reason I edit the VoicePack files is to enable UINightVision and UIFlightAssist voicing of these actions. For some reason, these are not enabled in the actions and in the speech file, but the functions are there in the app. When I add these to new version of the VoicePack, there are no problems so I don't know why these are not included by default, but if these don't cause any problems unknown to me, maybe consider adding these to the main VoicePacks?

The actions needed for these are self explanatory, and here is the speech file lines that can be copy-pasted for ease of inclusion.
Static say_UIFlightAssist $= "%iftrue(EventClass_Assist,"Flight assist disabled;Flight assist switched off","Flight assist on;Flight assist enabled")"
Static say_UINightVision $= "%iftrue(EventClass_State,"Nightvision enabled commander;Turning nightvision on","Nightvision off commander;Turning nightvision off")"

Thanks if you look into this also :)

**Comment by robbyxp1** [comment]
got it, will fix.

I did not turn on the UIFlightAssist and I thought for some people, they toggle it all the time and it would irritate.  The night vision is good though.

**Comment by robbyxp1** [comment]
Its fixed, will be out in next version, maybe this weekend. thanks

**Comment by tecnosegugio** [comment]
Sorry but this bug still exists on my installation (WIn 10, EDD v11.5.3.0, Voicepack v14.0.0.0).
I've just enabled the voicepack and disabled all events in the action files editor using the selectors on the right.
At reboot the voicepack doesn't start.
Is there some additional info you need? How can I provide them to you?

**Comment by tecnosegugio** [comment]
Addendum: the issue happens only when I disable ALL options in the voice action pack.
In this way the voicepack related items in the "add ons" menu does not appears giving the idea the action pack is not installed anymore. 
Anyway, I can uninstall and reinstall the VoiceAction pack, without disabling ALL options, and the voice action pack is back in action. ;-)
