### ISSUE TITLE
EDD Stops reading journal after carrier jump

### ISSUE THREAD

**Issue by peakzero** [EDDiscovery/EDDiscovery#2850]
After riding a carrier, EDD consistently stops displaying any journal entries after the jump. Hitting history refresh seems to cause it to loop with "refresh history" in log repeatedly. Trying to exit the program after doing this causes it to sit idle displaying "closing, please wait" at the bottom. After force closing in task manager and re-launching it works fine again.

using version 11.5.2.0

**Comment by robbyxp1** [comment]
Hi,
I've done two carrier jumps without incident.  So no idea whats going on at the moment..

**Comment by peakzero** [comment]
I'm not sure if its relevant but I was not the owner of the carrier, I hitched a ride on another person's carrier from the new LTD3 site to the sell location, and then from the sell location back to the LTD3 site, and it happened the exact same way both times.

Is there anything I can provide to help diagnose possibly?

**Comment by peakzero** [comment]
Sorry for another update, but I tried it again with a different carrier and it worked fine. Here is the raw journal from the failed carrier
{
  "timestamp": "2020-06-12T12:32:19Z",
  "event": "CarrierJump",
  "Docked": true,
  "StationName": "W84-P9Z",
  "StationType": "FleetCarrier",
  "MarketID": 3700802048,
  "StationFaction": {
    "Name": "FleetCarrier"
  },
  "StationGovernment": "$government_Carrier;",
  "StationGovernment_Localised": "Private Ownership ",
  "StationServices": [
    "dock",
    "autodock",
    "commodities",
    "contacts",
    "crewlounge",
    "rearm",
    "refuel",
    "repair",
    "engineer",
    "flightcontroller",
    "stationoperations",
    "stationMenu",
    "carriermanagement",
    "carrierfuel"
  ],
  "StationEconomy": "$economy_Carrier;",
  "StationEconomy_Localised": "Private Enterprise",
  "StationEconomies": [
    {
      "Name": "$economy_Carrier;",
      "Name_Localised": "Private Enterprise",
      "Proportion": 1.0
    }
  ],
  "StarSystem": "Unktock",
  "SystemAddress": 16063580349833,
  "StarPos": [
    -41.34375,
    -14.59375,
    -68.625
  ],
  "SystemAllegiance": "Independent",
  "SystemEconomy": "$economy_Industrial;",
  "SystemEconomy_Localised": "Industrial",
  "SystemSecondEconomy": "$economy_None;",
  "SystemSecondEconomy_Localised": "None",
  "SystemGovernment": "$government_Patronage;",
  "SystemGovernment_Localised": "Patronage",
  "SystemSecurity": "$SYSTEM_SECURITY_low;",
  "SystemSecurity_Localised": "Low Security",
  "Population": 5047804,
  "Body": "Unktock",
  "BodyID": 0,
  "BodyType": "Star",
  "Factions": [
    {
      "Name": "Unktock Free",
      "FactionState": "None",
      "Government": "Democracy",
      "Influence": 0.009311,
      "Allegiance": "Federation",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0
    },
    {
      "Name": "PLX 695 Silver Public Industry",
      "FactionState": "Retreat",
      "Government": "Corporate",
      "Influence": 0.009311,
      "Allegiance": "Federation",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0,
      "ActiveStates": [
        {
          "State": "Retreat"
        }
      ]
    },
    {
      "Name": "Bureau of Unktock Front",
      "FactionState": "None",
      "Government": "Dictatorship",
      "Influence": 0.009311,
      "Allegiance": "Independent",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0
    },
    {
      "Name": "Unktock Galactic & Co",
      "FactionState": "None",
      "Government": "Corporate",
      "Influence": 0.009311,
      "Allegiance": "Federation",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0
    },
    {
      "Name": "Mafia of Unktock",
      "FactionState": "InfrastructureFailure",
      "Government": "Anarchy",
      "Influence": 0.009311,
      "Allegiance": "Independent",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0,
      "ActiveStates": [
        {
          "State": "InfrastructureFailure"
        }
      ]
    },
    {
      "Name": "Quebecois Patriots",
      "FactionState": "Expansion",
      "Government": "Patronage",
      "Influence": 0.900372,
      "Allegiance": "Independent",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0,
      "ActiveStates": [
        {
          "State": "Investment"
        },
        {
          "State": "CivilLiberty"
        },
        {
          "State": "PirateAttack"
        },
        {
          "State": "Expansion"
        }
      ]
    },
    {
      "Name": "160 S.O.A.R.",
      "FactionState": "None",
      "Government": "Democracy",
      "Influence": 0.053073,
      "Allegiance": "Alliance",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0
    }
  ],
  "SystemFaction": {
    "Name": "Quebecois Patriots",
    "FactionState": "Expansion"
  },
  "EDDMapColor": -65536
}


and the successful carrier



{
  "timestamp": "2020-06-12T23:38:20Z",
  "event": "CarrierJump",
  "Docked": true,
  "StationName": "G14-P2L",
  "StationType": "FleetCarrier",
  "MarketID": 3700171264,
  "StationFaction": {
    "Name": "FleetCarrier"
  },
  "StationGovernment": "$government_Carrier;",
  "StationGovernment_Localised": "Private Ownership ",
  "StationServices": [
    "dock",
    "autodock",
    "commodities",
    "contacts",
    "outfitting",
    "crewlounge",
    "rearm",
    "refuel",
    "repair",
    "shipyard",
    "engineer",
    "flightcontroller",
    "stationoperations",
    "stationMenu",
    "carriermanagement",
    "carrierfuel",
    "voucherredemption"
  ],
  "StationEconomy": "$economy_Carrier;",
  "StationEconomy_Localised": "Private Enterprise",
  "StationEconomies": [
    {
      "Name": "$economy_Carrier;",
      "Name_Localised": "Private Enterprise",
      "Proportion": 1.0
    }
  ],
  "StarSystem": "Unktock",
  "SystemAddress": 16063580349833,
  "StarPos": [
    -41.34375,
    -14.59375,
    -68.625
  ],
  "SystemAllegiance": "Independent",
  "SystemEconomy": "$economy_Industrial;",
  "SystemEconomy_Localised": "Industrial",
  "SystemSecondEconomy": "$economy_None;",
  "SystemSecondEconomy_Localised": "None",
  "SystemGovernment": "$government_Patronage;",
  "SystemGovernment_Localised": "Patronage",
  "SystemSecurity": "$SYSTEM_SECURITY_low;",
  "SystemSecurity_Localised": "Low Security",
  "Population": 5047804,
  "Body": "Unktock 1 b",
  "BodyID": 8,
  "BodyType": "Planet",
  "Factions": [
    {
      "Name": "Unktock Free",
      "FactionState": "None",
      "Government": "Democracy",
      "Influence": 0.009311,
      "Allegiance": "Federation",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0
    },
    {
      "Name": "PLX 695 Silver Public Industry",
      "FactionState": "Retreat",
      "Government": "Corporate",
      "Influence": 0.009311,
      "Allegiance": "Federation",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0,
      "ActiveStates": [
        {
          "State": "Retreat"
        }
      ]
    },
    {
      "Name": "Bureau of Unktock Front",
      "FactionState": "None",
      "Government": "Dictatorship",
      "Influence": 0.009311,
      "Allegiance": "Independent",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0
    },
    {
      "Name": "Unktock Galactic & Co",
      "FactionState": "None",
      "Government": "Corporate",
      "Influence": 0.009311,
      "Allegiance": "Federation",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0
    },
    {
      "Name": "Mafia of Unktock",
      "FactionState": "InfrastructureFailure",
      "Government": "Anarchy",
      "Influence": 0.009311,
      "Allegiance": "Independent",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0,
      "ActiveStates": [
        {
          "State": "InfrastructureFailure"
        }
      ]
    },
    {
      "Name": "Quebecois Patriots",
      "FactionState": "Expansion",
      "Government": "Patronage",
      "Influence": 0.900372,
      "Allegiance": "Independent",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 30.0,
      "ActiveStates": [
        {
          "State": "Investment"
        },
        {
          "State": "CivilLiberty"
        },
        {
          "State": "PirateAttack"
        },
        {
          "State": "Expansion"
        }
      ]
    },
    {
      "Name": "160 S.O.A.R.",
      "FactionState": "None",
      "Government": "Democracy",
      "Influence": 0.053073,
      "Allegiance": "Alliance",
      "Happiness": "$Faction_HappinessBand2;",
      "Happiness_Localised": "Happy",
      "MyReputation": 0.0
    }
  ],
  "SystemFaction": {
    "Name": "Quebecois Patriots",
    "FactionState": "Expansion"
  },
  "EDDMapColor": -65536
}



I'm not sure why it happened with one and not the other, maybe it was a fluke. Apologies if I wasted time.

**Comment by klightspeed** [comment]
Is there anything in the `Trace*.log` in `%LOCALAPPDATA%\EDDiscovery\Log` from when this occurred?

**Comment by robbyxp1** [comment]
I too was riding along..

**Comment by peakzero** [comment]
Here is a pastebin of the part of my first trace log leading up to the first jump that had an issue 
https://pastebin.com/i88BtJmF

and here is the log leading up to the jump back that also had an issue
https://pastebin.com/EYATfzJN

For posterity, here is a slice from my trace log for the jump that worked successfully
https://pastebin.com/vEjR6VBg

**Comment by klightspeed** [comment]
```
Unable to read extra info from C:\Users\minchar\Saved Games\Frontier Developments\Elite Dangerous\NavRoute.json: The process cannot access the file 'C:\Users\minchar\Saved Games\Frontier Developments\Elite Dangerous\NavRoute.json' because it is being used by another process.
```

It looks like Elite Dangerous might be locking `NavRoute.json`, and that you might be getting bitten by the `NavRoute` spamming bug in the game (where the `NavRoute` is written essentially every frame to the journal).

**Comment by klightspeed** [comment]
#2851 should work around the NavRoute spamming bug by not reading `NavRoute.json` if the most recent `NavRoute` event was less than 2 seconds before this one.

**Comment by robbyxp1** [comment]
Presuming this was it..
