### ISSUE TITLE
Feature request: Hotspot filters for scan search panel

### ISSUE THREAD

**Issue by oltsukoo** [EDDiscovery/EDDiscovery#2859]
Could you implement a filter for the scans search panel that lets us search for bodies based on whether they have hotspots, what type they are and how many there are? This information is already available in the main Scan window but the search panel just doesn't seem to use it (the "signals" section is missing from the "information" tab in the search results).

This would make visiting already discovered hotspots much easier as there would be no need to keep a ton of bookmarks just so we can remember where certain hotspots are. Just search for the type and number of hotspots you need and you'd get a list of the nearest ones.

**Comment by robbyxp1** [comment]
Good idea.

**Comment by robbyxp1** [comment]
![image](https://user-images.githubusercontent.com/6573992/86937123-c6725d80-c136-11ea-8f4c-5939e3576380.png)

Added to search: Material commodity to search SAASignalsDiscoveryed entries.

**Comment by robbyxp1** [comment]
11.6, thanks for the idea.
