### ISSUE TITLE
received error notice, but don't see any issues currently 

### ISSUE THREAD

**Issue by billstewart** [EDDiscovery/EDDiscovery#2860]
### Exception Details:
>EDDiscovery v11.5.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.Collections.ArrayList.get_Item(Int32 index)
>   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
>   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
>   at EDDiscovery.UserControls.UserControlModules.Discoveryform_OnNewUIEvent(UIEvent obj) in C:\Code\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlModules.cs:line 123
>   at System.Action`1.Invoke(T obj)
>   at EliteDangerousCore.EDJournalClass.UIEventPost(ConcurrentQueue`1 events) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 335
>===== END =====
>```

**Comment by klightspeed** [comment]
Looks like a mis-patch in 974cf24381eec46d8f8be31bc64f0928837d7be6
