### ISSUE TITLE
Unhandled UI Exception (possibly related to browser)

### ISSUE THREAD

**Issue by adeemij** [EDDiscovery/EDDiscovery#2862]
### Description
I'm not sure what triggered this, so I can't provide reproduction steps; however, all I did was open EDD.  Since the error indicates an ad script (apparently), perhaps it is related to the new EDSM tab?  

This error occurs periodically even after electing not to continue running scripts.

### Additional Information
![edd_bug1](https://user-images.githubusercontent.com/26843599/85421558-691cc080-b529-11ea-84ef-48ea213453fc.png)
![edd_bug2](https://user-images.githubusercontent.com/26843599/85421563-6ae68400-b529-11ea-8ec3-6d1bdaedc9a1.png)

### Exception Details:
>EDDiscovery v11.5.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.Runtime.InteropServices.COMException (0x800700AA): The requested resource is in use. (Exception from HRESULT: 0x800700AA)
>   at System.Windows.Forms.UnsafeNativeMethods.IWebBrowser2.Navigate2(Object& URL, Object& flags, Object& targetFrameName, Object& postData, Object& headers)
>   at System.Windows.Forms.WebBrowser.PerformNavigate2(Object& URL, Object& flags, Object& targetFrameName, Object& postData, Object& headers)
>   at System.Windows.Forms.WebBrowser.Navigate(String urlString)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>===== END =====
>```

**Comment by klightspeed** [comment]
We might have to just ignore UI exceptions in `System.Windows.Forms.UnsafeNativeMethods.IWebBrowser2.Navigate2`, as they are beyond our control.  Also might have to suppress script errors.

**Comment by John-Bosch** [comment]
I have been getting the same. I am using the new Chromium based Edge browser as default if that helps. Sometimes I get just the script error popping up sporadically every minute or so, some times when I click to activate the window I get both the script error and the exception.

**Comment by AnthorNet** [comment]
Is this something I can fix on my side?

**Comment by klightspeed** [comment]
It sounds like a combination of the ad script trying to update the advertisement (which loads in an iframe), doing something that is incompatible with the implementation used by the `System.Windows.Forms.WebBrowser` control on the system, and EDDiscovery not allowing the loading of any page other than EDSM (including within any iframe - the `WebBrowser.Navigating` event does not distinguish between a top-level page load and an `iframe` page load).

**Comment by dolfandringa** [comment]
I am getting the same issue quite often too.

**Comment by robbyxp1** [comment]
Do we need to do another 11.5.x to cover this up.

**Comment by robbyxp1** [comment]
Anthor has disable the ad he was testing, so this won't occur for now. Further versions will cover this up.
