### ISSUE TITLE
Feature Request: transfer Fleet Carrier Infos like Docking access, Allow notorious and Service tariff to Inara

### ISSUE THREAD

**Issue by lwt-pressy** [EDDiscovery/EDDiscovery#2865]
On Inara I see this Info for a lot of Carriers. For mine EDD does not seem to transfer the info. Would be nice when it could be added.

**Comment by klightspeed** [comment]
We'll have to check what INARA endpoint accepts the data from the `CarrierStats` journal event in the carrier owner's journal, or whether INARA instead gets that through the carrier owner registering on INARA for CAPI access to the `/fleetcarrier` CAPI endpoint.

**Comment by lwt-pressy** [comment]
Thanks for pointing me to the right direction. My auto update through frontier was disabled to 30 day timeout. Probably longer since most data come through EDD which didn't make me realize it. Btw EDD is a very cool tool, I never fly without it.

**Comment by robbyxp1** [comment]
I've asked Artie if he's going to put in a CarrierStats endpoint - which obv means a lot of new Inara UI.  

Thanks for pointing this out, closing as its not an EDD problem, yet.
