### ISSUE TITLE
Database is locked while deleting the downloaded EDSM data

### ISSUE THREAD

**Issue by ChuangSheep** [EDDiscovery/EDDiscovery#2866]
Error message was shown while I was deleting the EDSM data. During that time, I was also doing the exploration, so it might because of this. 

Full error Message:
![2020-07-03_12-02-22](https://user-images.githubusercontent.com/44814054/86458357-6b4efe00-bd25-11ea-9cd1-39910a7ff4ed.png)

**Comment by robbyxp1** [comment]
Does it reoccur if you rerun?

**Comment by ChuangSheep** [comment]
At the first time, similar error has occured and I closed EDDiscovery, restarted my computer.  The error in the picture was shown as I reran it the second time, when I clicked the *route finder* tab. 

I uninstalled the programm, cleared the data in C, and reinstalled it. Now it seems to work properly.

**Comment by klightspeed** [comment]
> Error message was shown while I was deleting the EDSM data

You weren't trying to delete or edit the EDDSystems.sqlite file while EDDiscovery was still running, were you?

**Comment by ChuangSheep** [comment]
> > Error message was shown while I was deleting the EDSM data
> 
> You weren't trying to delete or edit the EDDSystems.sqlite file while EDDiscovery was still running, were you?

No, what I was doing is: EDDiscovery -> Setting -> EDSM/EDDB Control -> Select galaxy sectors -> (choose some grids) -> "You have removed sectors. This will require the DB to be cleaned of entries, which will take time
Confirm you wish to do this?" -> OK -> Play game while EDDiscovery trying to delete the data (deleting sector 1 , 2 , 3, ... was shown) -> Error message was shown when it was deleting about sector 110.

**Comment by robbyxp1** [comment]
Sometimes this happens, its hard to track down. If it keeps on repeating please open another ticket.
