### ISSUE TITLE
EDDiscovery not seeing scanned bodies.

### ISSUE THREAD

**Issue by HEELcaT666** [EDDiscovery/EDDiscovery#2867]
I have a very similar issue to #2431, where EDDiscovery is not showing the scan data of the system I'm in if I turn off EDSM data. 

Example is Jackson's Lighthouse, where I have everything explored in game, but the data is missing from EDDiscovery, even after refreshing the logs. 

I was able to fix this issue in other systems where there was a nav beacon, but this system doesnt have one.

I have had similar issues in other systems, ones where I have purchased Universal Cartographics data. Is this just an error in reading data for those systems?

**Comment by klightspeed** [comment]
> I have had similar issues in other systems, ones where I have purchased Universal Cartographics data. Is this just an error in reading data for those systems?

Purchasing cartographics data for a system does not generate the `Scan` events in the journal for the bodies for which you purchased the cartographic data.  Without the `Scan` events, EDDiscovery doesn't have any information on the bodies to show you.

**Comment by HEELcaT666** [comment]
So, apart from using EDSM data, there is no way for EDDiscovery to see those bodies?

**Comment by klightspeed** [comment]
Correct - without the `Scan` event in the journal, EDSM is the only place EDDiscovery can get the body data from.

**Comment by HEELcaT666** [comment]
Alright, thank you for explaining! Seems like an E:D problem, not an EDDiscovery problem. I will close issue as nothing can be done.
