### ISSUE TITLE
EDMC plugins and Window Control

### ISSUE THREAD

**Issue by DawnTreader** [EDDiscovery/EDDiscovery#2871]
Hello

I have a fleet carrier, I am part of the Apollo's Chariot Cooperative and there is a plugin for EDMC we use to send FC data to the https://fleetcarrier.space/my_carrier page and the discord servers, channels my carrier is listed in. I was wondering if you knew about the  Fleet Carrier Management System (FCMS) tool and if you can or have any plans to add it to ED Discovery? I currently have it running under EDMC but I have turned off all features but this one plugin because I like and use EDD. It would be nice if the  Fleet Carrier Management System (FCMS) could be implemented as a plugin in EDD, save users from having to have 2 tools doing the same thing.

The other thing I am wondering, is it possible to start the program minimized? I have tried a bat file with START /MIN "Start EDD" "C:\Program Files\EDDiscovery\EDDiscovery.exe" and START "Start EDD" "C:\Program Files\EDDiscovery\EDDiscovery.exe" /MIN, neither way worked. I also tried START "Start EDD" "C:\Program Files\EDDiscovery\EDDiscovery.exe" --new-window/MIN and no variation on any of these seemed to work. It would be nice if there was a way to make the program dive to the system tray when starting.

**Comment by robbyxp1** [comment]
So, good news, I'm about to launch EDD-EDMC, which will allow EDMC plugins to run in conjunction with EDD.  Coming within a week hopefully.

Secondly, for the window, that will have to be new code, i'll write it in the list of things to do.

thanks.

**Comment by robbyxp1** [comment]
The start minimised is a hard thing to do UI wise, programs don't ever start minimised, and you don't normally close them that way.

I'll have to ponder long and hard if its possible to UI.

**Comment by klightspeed** [comment]
![image](https://user-images.githubusercontent.com/147116/86623991-e9e9bb00-c005-11ea-84d0-762ec5d8f41b.png)
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.windowstyle?view=netframework-4.8

It sounds like because the main EDDiscovery window is not the first one that opens, it is ignoring the `Process.GetCurrentProcess().StartInfo.WindowStyle`

**Comment by robbyxp1** [comment]
The was my assumption..

**Comment by DawnTreader** [comment]
Not trying to be a jerk, and please understand that I am greatful that you are even responding to my "issue", but I have a lot of programs that start minimized. Microsoft Teams is one. In the settings there is a check box to put it in the background at startup. Another I can set a "minimize on startup on" are Discord and EA's Origin.

I understand it might be harder than I think, but there has got to be a way.

AND, I have tried choosing that in the options of the shortcut, it doesn't work either.

**Comment by robbyxp1** [comment]
We will look into it, I've added it to the list of stuff to do.  That's all I can promise now.

**Comment by DawnTreader** [comment]
Thanks even for just doing that. 😄
