### ISSUE TITLE
Opening the 3D map causes app hang

### ISSUE THREAD

**Issue by Crocodoc84** [EDDiscovery/EDDiscovery#2888]
Installed EDD at 19th of July for the first time, and everything worked fine. 
Since a few days (3 or 4), opening the 3D map will cause the app to hang indefinitely. The map window pops up, toolbar is ok, map area is empty (transparent), then turns solid black, then nothing. 
I already reinstalled, updated video drivers, started as admin to no avail. Application was in idle at map start, no communication/ data download. System is only SSD equipped. 
Win10 64 home latest updates.

Beschreibung
Aufgrund eines Problems kann dieses Programm nicht mehr mit Windows kommunizieren.
Pfad der fehlerhaften Anwendung:	C:\Program Files\EDDiscovery\EDDiscovery.exe

Problemsignatur
Problemereignisame:	AppHangB1
Anwendungsname:	EDDiscovery.exe
Anwendungsversion:	11.6.1.0
Anwendungszeitstempel:	5f119e9b
Absturzsignatur:	4752
Absturztyp:	134217728
Betriebsystemversion:	10.0.18363.2.0.0.256.48
Gebietsschema-ID:	1031
Zusätzliche Absturzsignatur 1:	47528f46dcfa425c77335f9fa95e6106
Zusätzliche Absturzsignatur 2:	63df
Zusätzliche Absturzsignatur 3:	63dff216d2c7c0677e8a3a7182725029
Zusätzliche Absturzsignatur 4:	4752
Zusätzliche Absturzsignatur 5:	47528f46dcfa425c77335f9fa95e6106
Zusätzliche Absturzsignatur 6:	63df
Zusätzliche Absturzsignatur 7:	63dff216d2c7c0677e8a3a7182725029

**Comment by robbyxp1** [comment]
First, leave EDD for a while then open it, does it work then?  
The system db may be upset.  At the expense of another DB download, you can run safe mode (from settings panel) and delete the system db and let it rebuild.

**Comment by Crocodoc84** [comment]
1. no, I tried that, as I read this in another issue report.. but doesnt help.
2. Will try the db reset after my current session and will report back.

Thanks for the prompt reply! 👍

**Comment by Crocodoc84** [comment]
Ok, did as you said. Deleted/ Rebuilt the system DB, waited for everything to be installed properly. Didn't cure the issue. I then tried each of the other steps in the safe mode menu, which also did not solve the issue. 
De-/ Reinstall did not solve it as well. Only thing I didn't try so far is to deinstall and manually delete all the user data in user\local. Maybe worth a try?

**Comment by klightspeed** [comment]
Try disabling `Enable Star Data Download` in the `EDSM/EDDB Control` group in the settings panel, then restarting EDDiscovery, and wait until `Star Data download is disabled. Use Settings panel to reenable` is logged in the log panel before opening the 3D map.

**Comment by Crocodoc84** [comment]
Did it.. issue remains. Thx for your help guys, I appreciate it ;)

**Comment by Crocodoc84** [comment]
Ok I found something. 
I use a multi monitor setup, with the main monitor for the game and useful other stuff like EDD on the second one. For my current exploration tour I downloaded and tested EDD on my main monitor, and it worked fine. For the actual tour I moved it to the second screen. While the main program runs just fine, the 3D map will not open (as described). 
Now when I select "only mainscreen" via Win-P, everything is forced on the mainscreen, and the 3D map opens properly. I then extended the desktop again, dragging both the main program and the map over to the second screen. Map works fine there now, but once I try to reopen it after closing, application hangs again.
If via Win-P and extending again only the main program is dragged to the second screen and the map remains on the main (so the map will always popup on the main), map works as expected. 
So it has some issue with being opened on the secondary screen.

**Comment by klightspeed** [comment]
Do the two screens run on different cards?  Does the map work if it is dragged from the main display to the secondary display?  Do other 3D programs (including webgl sites such as <https://get.webgl.org/> or <https://webglreport.com/?v=2>) work if started on the secondary display?

**Comment by Crocodoc84** [comment]
Nope, both run on the same card (1070). If it's started on the main, you can drag it over to the secondary without any problem. It just doesn't start up on the secondary.
Sites you posted, as well as other software works, as far as I can tell (Google Earth for example).

**Comment by robbyxp1** [comment]
Closing, no more info.
