### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mearmortal** [EDDiscovery/EDDiscovery#2896]
Great app BTW, been using it for a while now, and it's scan page is the most useful for me.

I'm using the app with the 'On Top' option ticked and with Opacity set to the lowest setting and although it's nearly perfect, it still dulls out the game image on my second screen, and the application colours are a little dull too, but that's the setting. Is is possible for you to configure a transparent option.
I'm not sure if it's going to help but EDMC does have that option already, and works well.
Let me know if it's something that can be achieved. Thank you.

**Comment by klightspeed** [comment]
Popout panels do have a transparent option - this makes their background transparent.  If you want multiple panels in a popout window, you can pop out a splitter panel, and split that up how you want and put the panels you want in it.

**Comment by mearmortal** [comment]
Hello, didn't know that I will take a look at that this evening thank you




Sent from Samsung Mobile on O2


Get Outlook for Android







On Sat, Aug 1, 2020 at 6:58 AM +0100, "Ben Peddell" <notifications@github.com> wrote:















Popout panels do have a transparent option - this makes their background transparent.  If you want multiple panels in a popout window, you can pop out a splitter panel, and split that up how you want and put the panels you want in it.

**Comment by mearmortal** [comment]
I'll move this to discord for more general questions now. Thanks.
