### ISSUE TITLE
[3D map] Limit the display of systems within X ly from the slected system

### ISSUE THREAD

**Issue by Evander3** [EDDiscovery/EDDiscovery#2898]
Displaying all systems in DB can be resources intensive and sometimes I only want to see the surrounding systems (to estimate in which directions to explore).

Would it be possible to add a feature to display only the surrounding systems around the currently slected system; like a toggle to activate/deactivate it and a text input to indicate how many ly in radius to display ?

**Comment by robbyxp1** [comment]
Thanks for the idea, but no more development is going to take place on the 3dmap, i have a new one which will operating in a completely different manner in development for roll out when I get the time.

The number of stars is now overwhelming the current 3dmap I acknowledge.  But its not worth doing any more to it now.

thanks.
