### ISSUE TITLE
There was an unhandled UI exception

### ISSUE THREAD

**Issue by Basti7734** [EDDiscovery/EDDiscovery#2899]
This Error pops up when i change the Theme. But the Theme change anyways so i have no idea what the issiue is. 
P.S. sorry for my bad English

### Exception Details:
>EDDiscovery v11.6.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>   bei ExtendedControls.ToolStripComboBoxCustom.get_SelectedItem() in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\ToolStrips\ToolStripComboBoxCustom.cs:Zeile 69.
>   bei EDDiscovery.UserControls.UserControl2DMap.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControl2DMap.cs:Zeile 111.
>   bei System.Action`1.Invoke(T obj)
>   bei EDDiscovery.EDDiscoveryForm.ApplyTheme(Boolean panelrefreshaswell) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:Zeile 712.
>   bei EDDiscovery.UserControls.UserControlSettings.comboBoxTheme_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Settings\UserControlSettings.cs:Zeile 305.
>   bei ExtendedControls.ExtComboBox._cbsystem_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\ComboBox.cs:Zeile 375.
>   bei System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
>   bei System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
>   bei ExtendedControls.ExtComboBox.customdropdown_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\ComboBox.cs:Zeile 350.
>   bei ExtendedControls.ExtListBoxForm.listcontrol_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\ListBoxForm.cs:Zeile 111.
>   bei ExtendedControls.ExtListBox.OnMouseClick(MouseEventArgs e) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\ListBox.cs:Zeile 364.
>   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   bei System.Windows.Forms.Control.WndProc(Message& m)
>   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
thanks, will look at it.

**Comment by klightspeed** [comment]
The 2D map isn't unsubscribing from `OnHistoryChange` when it closes.
