### ISSUE TITLE
There was an unhandled UI Exception

### ISSUE THREAD

**Issue by MaverickBlue** [EDDiscovery/EDDiscovery#2901]
### Exception Details:
>EDDiscovery v11.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   at System.Collections.Generic.List`1.get_Item(Int32 index)
>   at Newtonsoft.Json.Linq.JObject.WriteTo(JsonWriter writer, JsonConverter[] converters)
>   at Newtonsoft.Json.Linq.JToken.ToString(Formatting formatting, JsonConverter[] converters)
>   at EliteDangerousCore.DLL.EDDDLLCallerHE.CreateFromHistoryEntry(HistoryEntry he, Boolean storedflag) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\DLL\EDDDLLHistoryEntry.cs:line 34
>   at EDDiscovery.EDDiscoveryForm.Controller_NewEntrySecond(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 824
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 85
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 73
>   at EliteDangerousCore.EDJournalUIScanner.ScanTickDone(Tuple`2 entries) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDScanner.cs:line 181
>===== END =====
>```

**Comment by klightspeed** [comment]
Please update to 11.6.2

**Comment by MaverickBlue** [comment]
Ah, I didn't notice there was an update, altho now that you mention it I do see it across the title bar. It never really popped anything up to grab my attention. A nice to have feature might be some settings to pick from that pop a notification window on top, or frequency of update checks.
