### ISSUE TITLE
v11.6.2.0 combining history events from different commanders

### ISSUE THREAD

**Issue by markm1701** [EDDiscovery/EDDiscovery#2902]
in version 11.6.2.0 i have 2 commanders configured, one is running from local pc where ED Discovery is installed, the other is read across my network from my other pc.  

at first everything ran fine with events from both commanders being tracked against the actual commander, 

all of sudden, events seem to being combined to the commander i'm running on the same PC as EDDiscovery on

So far the only solution i have is to delete the local user database and re-initialize it

**Comment by klightspeed** [comment]
Just to make sure, you're not doing anything silly like using `Move all history to current commander` from the Admin menu?

**Comment by markm1701** [comment]
If that option had been selected in an earlier version when i only had one commander to import legacy command entries, could that be being remembered and updating my entries from my second commander ?

**Comment by klightspeed** [comment]
No, `Move all history to current commander` is a command (not an option) that will at that point in time move all history from all commanders to the current commander.

**Comment by robbyxp1** [comment]
Closing
