### ISSUE TITLE
No idea what caused this to pop up!

### ISSUE THREAD

**Issue by Meridianstream** [EDDiscovery/EDDiscovery#2903]
### Exception Details:
>EDDiscovery v11.6.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.ScanDisplayUserControl.DrawSystem(SystemNode scannode, MaterialCommoditiesList curmats, HistoryList hl, String opttext, String[] filter) in C:\Code\EDDiscovery\EDDiscovery\UserControls\HelpersScanDisplayUC\ScanDisplayUserControl.cs:line 243
>   at EDDiscovery.UserControls.UserControlScan.<DrawSystem>d__23.MoveNext() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:line 229
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by robbyxp1** [comment]
Fixed, thanks. Will be in the next release.
