### ISSUE TITLE
Surveyor Tab is not refreshing

### ISSUE THREAD

**Issue by Inkognyto** [EDDiscovery/EDDiscovery#2905]
Started happening in the last two weeks.

FSS scan happens - no update from previous.

I don't know what forces a refresh but it is not happening.

I almost exclusively use the Surveyor tab tell me what to scan when exploring. the fact I have to close and restart EDDiscovery for this to work has made me stop using it altogether.

If I keep going and ignore it after like 20-30 scans it may work for a few then stop again.

**Comment by klightspeed** [comment]
When the surveyor tab stops updating, does anything else update?  It should update every time you switch between UI panels or modes in the game, and when the selected entry in the associated history panel is changed (whether manually, or when move to latest is enabled and a new entry is read).

**Comment by Inkognyto** [comment]
I found the culprit from what I can tell.

Addon - Scout Report.

I had installed this around the time it stopped updating, it was writing a log I never used. 

Since I've removed it, I haven't hard the issue.  I did this sometime yesterday, and it's been fine since, and on my trip back in to the bubble (last 4k ly updated fine after).

If you want to research if that addon was having issues you can otherwise close this.

**Comment by klightspeed** [comment]
If that addon is <https://github.com/EDDiscovery/EDDiscoveryData/blob/master/ActionFiles/V1/Scout%20Report.act>, it says:
> This writes files about system information and scanned body for easier reporting for the DW2 Geological Reports.

I don't see how that would interact with the surveyor panel.

The note that when the surveyor tab wouldn't update it's coupled with an estimated values tab sounds almost like some interaction with the async code trying to fetch bodies from EDSM.

**Comment by robbyxp1** [comment]
Closing, no more data.
