### ISSUE TITLE
2D Map Options Missing

### ISSUE THREAD

**Issue by nov912** [EDDiscovery/EDDiscovery#2906]
In previous versions an option to access a 2D map was available from both the toolbar and the tools menu.  This option no longer appears to be available (has disappeared completely in both locations) and I don't see another option to access the 2D map.  Documentation here still references the map so just wanted to identify whether this was intentional or not, thanks!

**Comment by klightspeed** [comment]
The 2D map is now a panel, which can be created through the + Tab.

**Comment by nov912** [comment]
Issue solved, thanks much!
