### ISSUE TITLE
Best way to log Notable Stellar Phenomena?

### ISSUE THREAD

**Issue by GaryMack** [EDDiscovery/EDDiscovery#2908]
Hi,
What's the best way to log 'Notable Stellar Phenomena' NSP and can they then be exported to CSV, or other route planners?
Would like to create a 3D map of a nebula, with NSP's and also a route planner for people to plan visits.
Currently people are scanning with FSS and entering the data in a Google Sheet. Was hoping there is a better way and thought of you :)

Thanks,
Gary

**Comment by robbyxp1** [comment]
Captains log can hold entries and export to excel.  Thats the main note taking system in ED.

Or you can export all the Codex entries you have by filtering for them in the history panel and exporting to excel.

Other than that, thats all we currently offer.

**Comment by GaryMack** [comment]
Ok, thanks chap
