### ISSUE TITLE
"Entries to Read" setting typographical error

### ISSUE THREAD

**Issue by Anticept** [EDDiscovery/EDDiscovery#2909]
The "Entries to Read" setting is using the greater than (>) sign, but uses less than (<) logic. I suspect it was meant to use the less than symbol.

![image](https://user-images.githubusercontent.com/521038/91112188-6422dd00-e650-11ea-9e2a-9ae0ff7785b6.png)

![image](https://user-images.githubusercontent.com/521038/91112287-ad732c80-e650-11ea-8010-3b7e187d81b9.png)

**Comment by robbyxp1** [comment]
It means, and I know its hard to read, but "entries to read", > 30 days old, is limited to essential entries in the box below...

thanks for the report.

**Comment by Anticept** [comment]
I see. It's a bit convoluted and probably should have a little help tool-tip to explain that.
