### ISSUE TITLE
EDDiscovery v11.7.0.0 Fatal Error

### ISSUE THREAD

**Issue by gathooed** [EDDiscovery/EDDiscovery#2917]
During "Send unsynced Journals to EDSM"

Sync is still running

Win 10
Processor: Intel Core i7 9700KF
Memory: 32 GB / DDR4
HD: SSD
________________________________________________________________________________________________________________________
An unhandled fatal exception has occurred.

==== BEGIN ====
System.NotSupportedException: Das angegebene Pfadformat wird nicht unterstützt.
   bei System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   bei System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   bei System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   bei EliteDangerousCore.DB.TravelLogUnit..ctor(String s) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\DB\TravelLogUnit.cs:Zeile 49.
   bei EliteDangerousCore.EDSM.EDSMLogFetcher.Process(List`1 edsmlogs, DateTime logstarttime, DateTime logendtime) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\EDSM\EDSMLogFetcher.cs:Zeile 252.
   bei EliteDangerousCore.EDSM.EDSMLogFetcher.FetcherThreadProc() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\EDSM\EDSMLogFetcher.cs:Zeile 155.
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by gathooed** [comment]
An Additional after restarting the UI and changing to "Options" (Einstellungen)

**Comment by klightspeed** [comment]
https://github.com/EDDiscovery/EliteDangerousCore/blob/46631b23b5b268d33d9e8ced3302a2a05e6ca41a/EliteDangerous/DB/TravelLogUnit.cs#L48 assumes that the name passed in is a path, which is not true for EDSM syncs.

**Comment by robbyxp1** [comment]
Ok i'll check.
