### ISSUE TITLE
Trouble with initial history display after startup, duplicate history entries, release 11.7.0 and 11.7.1

### ISSUE THREAD

**Issue by DexSK** [EDDiscovery/EDDiscovery#2918]
after updating to v11.7 the history display after starting up doesn't show up, I have to click buttons at random for it to be displayed, and when it does, all entries are duplicated and they stay that way, new entries get duplicated too.
![image](https://user-images.githubusercontent.com/71542727/93660919-fe115600-fa53-11ea-85f6-bcfdb1d65986.png)

**Comment by DexSK** [comment]
![image](https://user-images.githubusercontent.com/71542727/93660908-ee920d00-fa53-11ea-9833-f8bdd9a38f89.png)

**Comment by robbyxp1** [comment]
I would remove/rename the user DB and let it rescan your journals.

See https://github.com/EDDiscovery/EDDiscovery/issues/2914

**Comment by DexSK** [comment]
Clean install solved it, it's an annoyance nonetheless.
+1

**Comment by robbyxp1** [comment]
Yes, and I've reproduced it.  Will fix v.soon.

**Comment by DexSK** [comment]
Hello Robby, unfortunately this is still ongoing, see screenshot:
![image](https://user-images.githubusercontent.com/71542727/94293570-bfe9ca00-ff5e-11ea-8911-02c3ccf338ef.png)

**Comment by robbyxp1** [comment]
Okay, will investigate.

**Comment by robbyxp1** [comment]
Are you just playing normally, or did you do any journal rescans etc.

**Comment by robbyxp1** [comment]
Sorry, also, when your playing, does it duplicate?  or it it just when you reload EDD you end up with duplicates?

**Comment by DexSK** [comment]
Didn't change anything, I don't generally have it open, just running in the system tray so can't exactly say when it started, noticed it after the last update when it started up after install, the history took some time to load and then the entries were duplicated again

**Comment by robbyxp1** [comment]
can you send a picture of your settings screen, so i can check the commander settings. thanks

**Comment by DexSK** [comment]
![image](https://user-images.githubusercontent.com/71542727/94337596-eefa4d00-ffeb-11ea-87e5-699a1f7e47a8.png)

**Comment by robbyxp1** [comment]
So I see your reading from d:\docs.. EDD always scans the c:\users\<user>\saved games\frontier developments\elite dangerous files for journal updates, and thats where Elite writes it.  Why are you scanning the d:\docs folder?  If it sees the journal in both locations, you'll end up with duplicate entries.

Is this location a backup of the journal files? If so, please don't let EDD scan it - set the location to blank again in the commander settings.

**Comment by DexSK** [comment]
I've got most of the profile data folders redirected out of the system drive (documents, saved games, music, pictures, etc), that's why, for easy backup when reinstalling the system. the location shown there ist where the location of the saved games folder is :)

**Comment by DexSK** [comment]
Now I started the game up again, new entries single only no duplicates

**Comment by klightspeed** [comment]
If you have redirected (or are using a directory symlink or junction point to redirect) Saved Games to `D:\Docs\My Games` (i.e. entering `shell:SavedGames` takes you to `D:\Docs\My Games`), then manually specifying the commander journal path should not be necessary, as EDDiscovery by default includes `shell:SavedGames\Frontier Developments\Elite Dangerous` in the directories it scans for journals.  Having two different paths pointing to the same files, and directing EDDiscovery to read both paths, will result in duplicates.

**Comment by DexSK** [comment]
Right, at the initial setup I somehow missed that ED is smart enough that it doesn't need pointing at anything :) ok, case closed.

**Comment by robbyxp1** [comment]
Cheers.
