### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by antoneeeee** [EDDiscovery/EDDiscovery#2919]
11.7.2 - windows cannot access specified path drive or file, may not have appropriate permissions blah blah blah - this is trying to install the latest version - even trying to run as administrator

**Comment by robbyxp1** [comment]
Hi, 
I've just installed it successfully. 

There are a lot of reasons it could be doing this - antivirus, previous installations, etc.

I would make sure EDD is fully uninstalled and not present in program files in any way

Then try installing it, maybe disabling the antivirus if you have one...

**Comment by antoneeeee** [comment]
ok sorted problem after 3 attempts - older version uninstalled, avast switched completely off - computer restarted - re downloaded in chrome not explorer and then run as admin finally installed - thanks
