### ISSUE TITLE
Quotes in System Names Interfere with EDSM Trilateration

### ISSUE THREAD

**Issue by PhoenixBlue0** [EDDiscovery/EDDiscovery#2920]
Starting in version 11.7.x, populating the trilateration tab with systems from EDSM would put quotation marks around the system names. This doesn't interfere with galaxy map entry, because Elite's galaxy map interface ignores quotation marks. However, the quotation marks interfere with the "export to EDSM" process, resulting in an error message. Reverting to EDDiscovery 11.6.2 or manually removing the quotation marks work as temporary workarounds for this issue.

**Comment by klightspeed** [comment]
This should be fixed in 11.7.3
