### ISSUE TITLE
unhandled UI exception

### ISSUE THREAD

**Issue by AJayzer** [EDDiscovery/EDDiscovery#2921]
### Description

error on program load. Seems to run fine so far.

### Exception Details:
>EDDiscovery v11.7.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlEngineering.InitialDisplay() in C:\Code\EDDiscovery\EDDiscovery\UserControls\EngineeringSynthesis\UserControlEngineering.cs:line 179
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshCompleteonUI(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 192
>===== END =====
>```

**Comment by robbyxp1** [comment]
Have you been able to reproduce it consistently?

**Comment by robbyxp1** [comment]
Closing, no response.
