### ISSUE TITLE
3D map crashes when opening on a different monitor

### ISSUE THREAD

**Issue by FormBurden** [EDDiscovery/EDDiscovery#2922]
Pretty much the title. I have a three monitor setup and I usually have misc programs such as this on my left monitor. Anyway, the program crashes if trying to open the 3D map on a different monitor. But on the main monitor, it will not crash and actually open.

Also, when re-sizing the 3D window, if you mess around to much of re-sizing the entire program crashes. 

Program: latest build

**Comment by klightspeed** [comment]
Are the monitors on the same graphics card, or on different graphics cards?

**Comment by FormBurden** [comment]
They are on the same graphics card. Idk if it matters, but it's a GTX 2080 Super.

**Comment by klightspeed** [comment]
What type of crash is it?

Is it an Unhandled Exception, with a dialog that has an option to report the error on Github?
Is it a This program is not responding, where you close it?
Or does it crash in such a way that there is no option to report the crash?

In any case, is it possible to get the trace log (`Trace_*.log`) associated with the crashed session from `%LOCALAPPDATA%\EDDiscovery\Log`?

If it is the latter hard crash, I don't know what we can do about it, as in that case it is crashing in code outside our control (e.g. the GPU's OpenGL driver).

**Comment by FormBurden** [comment]
It's pretty much the third option, nothing, just freezes real quick and crashes, no dialogue of any kind.

Here's the most recent log when I caused it to crash.
[Trace_2020-09-27-23-08-11.0.log](https://github.com/EDDiscovery/EDDiscovery/files/5290025/Trace_2020-09-27-23-08-11.0.log)


Sorry, build: 11.7.3.0

Anything from the 3D map crash that you could have me do that you can think of?

**Comment by robbyxp1** [comment]
Did you open it immediately after program start, or waiting until the EDSM update finished?

**Comment by klightspeed** [comment]
If it was an application hang, then there should be an `Application Hang` error event in the Application log in event viewer with something like the following:
```
The program EDDiscovery.exe version 11.7.3.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
```

If it was an application crash, it should be an `Application Error` event with something like:
```
Faulting application name: EDDiscovery.exe, version: 11.7.3.0, time stamp: 0x5f6a0b90
```

If it's a .NET crash that was somehow not caught by the unhandled exception handler, then it might be preceded by a `.NET Runtime` error with something like:
```
Application: EDDiscovery.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
```

Note that an application hang when opening the 3D map can occur if it is still initializing the systems DB, as while it is doing that the systems DB is in single-threaded mode.

**Comment by FormBurden** [comment]
Hi again, sorry for the few days of not replying. Yes, it stated it was an Application Hang in Event Viewer. The workaround that would work is just opening in main window and dragging, but whenever I quit the program even if I quit in main monitor, when I re-open the program and open the 3D map, it wants to open on the other monitor, so the same thing happens. So I end up having to use the safe mode to reset the windows and restart.

**Comment by robbyxp1** [comment]
I'm afraid there is not much we can do, this is a not a general problem ,else we would be seeing lots of reports. Its probably some graphics driver issue.

Closing
