### ISSUE TITLE
Improve `DockingGranted` event for VoicePack

### ISSUE THREAD

**Issue by Californ1a** [EDDiscovery/EDDiscovery#2923]
I'm just recently switching over from EDDI, mostly for the neat overlays, and one of the first things that immediately stood out to me is the lack of docking pad location info given upon docking granted. With EDDI, the voiceover says something like "Landing pad 2 is at 6 o'clock near, as you enter with the green lights on your right" so you immediately know the clock direction to rotate toward, and if it's at the near or far end of the station. It's mainly just for the starport-type stations (Coriolis, Orbis, Ocellus, Asteroid) that have a full circle of landing pads; planetary and orbitals don't give any extra location info.

**Comment by robbyxp1** [comment]
Okay, i'll have a look at this idea.

**Comment by robbyxp1** [comment]
Such a good idea i've coded it, download VP15! thanks
