### ISSUE TITLE
Voicepack SSML in speech file

### ISSUE THREAD

**Issue by gordenwunderlich** [EDDiscovery/EDDiscovery#2926]
When inputting an SSML command (break) into the speech file it gets quoted automatically.

**Comment by robbyxp1** [comment]
You need to explain a bit more ;-)

**Comment by gordenwunderlich** [comment]
ok. When i use the edit speech file function and enter the break SSML command <break time="3s"/>, which should be supported by all voices. it gets quoted automatically when closing the file. So it becomes "<break time=\"3s\"/>". which will not work as intended. This is strange because there are already commands like this in the file, for Example <say-as interpret-as='cardinal'> in line 198.

**Comment by robbyxp1** [comment]
I'll have a look tomorrow.

**Comment by robbyxp1** [comment]
I've not been able to reproduce this accurately. All i can say is that the quoting of the strings need to be consistent, if you put a " in there, the whole line needs to be quoted and either you use the quote escape \" in the break bit around the 3s, or you can use single quotes around '3s'

**Comment by gordenwunderlich** [comment]
Ok, so single quotes at least won't get changed when i save the file, but the voice still reads out "break/". Is this because the default Microsoft voice does not support the break command? Because the say-as works as i expect it to.

**Comment by robbyxp1** [comment]
So, looking at the code, break was not supported. So I've added it. this works

Static say_FuelScoop $= "fred <break time='1s'/> <say-as interpret-as='address'>150th CT NE, Redmond, WA</say-as> and <prosody volume='+50%'> jim much lounder</prosody> finish"

If you can compile the tip code, this will work, else i will be doing another version shortly, either today or tomorrow.

Note I find SSML support in each voice very patchy, some of my voices do not. My Ivona voice does nothing for the say-as and the prosody above, but the Microsoft David one does.

cheers

**Comment by robbyxp1** [comment]
`Static say_FuelScoop $= "fred <break time='1s'/> <say-as interpret-as='address'>150th CT NE, Redmond, WA</say-as> and <prosody volume='+50%'> jim much lounder</prosody> finish"
`

**Comment by robbyxp1** [comment]
See above for the correct line, the markup spoilt the one above.

**Comment by gordenwunderlich** [comment]
Alright, thanks for the help. I will try it out once the new version comes.

**Comment by robbyxp1** [comment]
11.7.5 is now out, give it a try ;-)
