### ISSUE TITLE
The "Jump" field can't be moved.

### ISSUE THREAD

**Issue by AndrielChaoti** [EDDiscovery/EDDiscovery#2928]
The field labelled "jump" in the system information panel can't be moved, nor can any other fields be on the same line as it, despite it appearing as a 1 column wide item.

**Comment by AndrielChaoti** [comment]
Actually, it's just *really finnicky* to get something to go on the same line as it, but i am still unable to get the Jump field to move.

**Comment by klightspeed** [comment]
How are you moving fields around?

**Comment by AndrielChaoti** [comment]
By holding control and clicking and dragging the field by it's "label" component. I can't seem ot get this to work for the Jump field, but any other field seems to not be bothered by it.

**Comment by robbyxp1** [comment]
Well spotted, will be fixed in next version.
