### ISSUE TITLE
Web server will not start

### ISSUE THREAD

**Issue by packet1** [EDDiscovery/EDDiscovery#2931]
I have tried to enable the webserver but no longer have success.  I had it running once.   I enabled the option but it complains it cannot start.  I deleted the auto created FW rule and ran netsh http delete urlacl url=http://*:6502/ and tried to enable it again but it still will not start.

![image](https://user-images.githubusercontent.com/70610088/95523876-730de680-0995-11eb-8149-4944e8d61173.png)
![image](https://user-images.githubusercontent.com/70610088/95523928-9b95e080-0995-11eb-9884-8d8e82f40caf.png)

**Comment by packet1** [comment]
I think I figured out a possible explanation and at the very least the web server is running again.  The reserved URL adds the user as HOSTNAME\username.   In my case, my system is joined to a domain.  It really should add the user as DOMAIN\username.   After I deleted the URL reservation added it with DOMAIN\username the web server started.   BTW, debug logs are virtually non-existent here.

**Comment by robbyxp1** [comment]
I'm afraid windows does not tell you why it won't start, i.e the reason, only the fact it got rejected.  I would have printed that out if I had it.  Glad you got it going.
