### ISSUE TITLE
Star Type In Estimated Values Tool

### ISSUE THREAD

**Issue by Hotklou2404** [EDDiscovery/EDDiscovery#2933]
In the Estimated Values tool there is a Body Type column. Here is shown what type of body a planet is (icy body, earth-like, water world, etc.), but stars are left blank. I suggest that in the Body Type column it shows what type star it is (blue-white star, brown dwarf star, neutron star, black hole, red supergiant star, etc.).

**Comment by robbyxp1** [comment]
In next version, thanks for noting that.

**Comment by Hotklou2404** [comment]
Love it! Thank you guys so much! <3
