### ISSUE TITLE
[11.7.4.0] Image conversion fails to work

### ISSUE THREAD

**Issue by LuckyLuigi** [EDDiscovery/EDDiscovery#2934]
I previously had problems that image conversion would stop working if a folder was present in the target directory for the converted files. Now the target folder is empty and it was working again until today.

source folder C:\Users\lgong\Pictures\Frontier Developments\Elite Dangerous

It finds the files but the conversion fails

Error in executing image conversion, try another screenshot, check output path settings. (Exception Access to the path 'C:\Users\lgong\Desktop\CONVERTED\Xothuia MK-E d12-640 (20201015-214951).png' is denied.)
Error in executing image conversion, try another screenshot, check output path settings. (Exception Access to the path 'C:\Users\lgong\Desktop\CONVERTED\Xothuia MK-E d12-640 (20201015-214951).png' is denied.)

This is actually a new target folder,  the previous one was C:\Users\lgong\Pictures\Converted TODO
I made this one to see if it would help.
Running as Administrator has no effect
I was converting from bmp to png, resizing to 1080 * 1024, and deleting the original
I turned of resizing but it makes no difference

Full config:

Scan for bmp
Orgininal Image Delete
Store in <target folder>
Save as png
In Sub folder None
Filename format Sysname (YYYMMDD-HHMMSS)
Mark HiRes Files checked
Clipboard No Copy
Crop/Resize options off

Everything else EDDiscovery does seems to work fine. Great program and this is my favourite feature.
Any tips would be great

**Comment by klightspeed** [comment]
Check the permissions on that directory.

**Comment by robbyxp1** [comment]
See if you can create a file  in that folder, to double check.

**Comment by LuckyLuigi** [comment]
I have figured out what the problem is.
It is Avast Ransomware Shield that blocks the file creation.
You can turn it off by adding an exception for the EDDiscovery exe in Avast Ransomeware Shield.
Making exceptions for the directories where you read, write, or where the EDDiscovery exe is located will not work, it has to be the exe file specifically for which the exception is made.
If have tested it with 11.7.5.0 as well and the problem is resolved.
