### ISSUE TITLE
Duplicating systems on Display

### ISSUE THREAD

**Issue by Harag9** [EDDiscovery/EDDiscovery#2935]
Being new to the product, I'm just playing around and on the "Map 3D Local Systems" panel I have seen the selected system duplicate several time.

1. Set the min to 0
2, Set the max to 30
3. Set the slider to anything, e.g. 250,

Screen refreshed, all is ok.

Now enter a new number in the MAX box

4. Set the max to 25

Screen redraws, but I'm now seeing MULTIPLE red systems, all with the same name

To fix this, I simply have to alter the slider. Right Clicking and selecting any of the context options (even reset) doesn't solve it.

**Comment by robbyxp1** [comment]
This panel will soon be withdrawn, in favour of newer 3dpanels.

If there is a quick fix, i'll incorporate.

**Comment by Harag9** [comment]
Hi, Thanks for letting me know. First time I used the panel and new to the software so not sure on the history.  Happy for you to not fix it and just remove the panel.

**Comment by robbyxp1** [comment]
Closing, as I said, i'm planning on this and plot to disappear.
