### ISSUE TITLE
EDD web-server's favicon.ico does not display correctly

### ISSUE THREAD

**Issue by kn-yami** [EDDiscovery/EDDiscovery#2938]
The web-server serves this file with some of its bytes replaced by `0xef 0xbf 0xbd` sequence. Since the original file (`eddwebsite.zip\favicon.ico`) does not have this problem I suspect that at some point it is interpreted as text and whatever does this replaces "invalid" bytes with `U+FFFD REPLACEMENT CHARACTER` encoded in UTF-8.

**Comment by robbyxp1** [comment]
i will look into it, thanks

**Comment by robbyxp1** [comment]
Found, thanks for the report.
