### ISSUE TITLE
Moving or resizing windows give UI exception

### ISSUE THREAD

**Issue by MardanteSoliest** [EDDiscovery/EDDiscovery#2939]
### Description
Moving or rescaling windows give a UI exception

### Additional Information
![image](https://user-images.githubusercontent.com/73404769/97092403-1cb2d000-1644-11eb-87a8-77220fa3dfca.png)

### Exception Details:
>EDDiscovery v11.7.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.OverflowException: Arithmetic operation resulted in an overflow.
>   at ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\DraggableForm.cs:line 169
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
What OS are you using?

Does it error out when you initially attempt to resize the window, or after the window has been resized?

**Comment by MardanteSoliest** [comment]
Win 10 Pro, i7 7700k, GTX 1080ti, 32Gb ram, DX12.

It errors out when clicking. Before moving or resizing.

**Comment by robbyxp1** [comment]
Hi. This is a regular install of EDD, not a self compiled version I'm presuming?

Hold down shift key and run EDD, and use the safe mode form to reset theme, window position, tabs one by one and see if you can solve it that way.

**Comment by robbyxp1** [comment]
This has got us stumped, mainly because the error line is not accurate enough to work out what is happening. Is it still happening?

**Comment by MardanteSoliest** [comment]
It is the one downloaded as exe installer.

In safe mode I used all tabs to reset it all. Also uninstalled and installed the 11.7.5.0, the problem still is there.
I will try some other drivers.

Thank you for your comitment of this tool ;) much apriciated.

**Comment by robbyxp1** [comment]
I'll keep this in mind, but i can't reporduce. I've tried modifying my screen layout to see if I can cause it, but I cant.

Closing but will remember and see if i can get it to go wrong.

**Comment by MardanteSoliest** [comment]
running the app as Admin resolves the issue

**Comment by klightspeed** [comment]
That seems to suggest that something is hooking windows events and giving garbage data for e.g. the WM_NCHITTEST (Non-Client Hit Test) message, and running the program as administrator prevents the hook from succeeding.

**Comment by klightspeed** [comment]
<https://referencesource.microsoft.com/#mscorlib/system/intptr.cs,192>
Explicitly casting an IntPtr to int (as occurs in <https://github.com/EDDiscovery/ExtendedControls/blob/b30bee864f24c11f8de7f30dbcd24190f15969c2/ExtendedControls/Forms/DraggableForm.cs#L240>) will throw an OverflowException if the IntPtr falls outside the the range 0 to int.MaxVal - e.g. if the Y coordinate is negative.
