### ISSUE TITLE
EDSM Panel not working

### ISSUE THREAD

**Issue by mearmortal** [EDDiscovery/EDDiscovery#2940]
Hello,
    Just noticed in the last 5 minutes while browsing the journal, was looking to check out a system on EDSM by rightclicking a description field with the likes of 'Jump to HIP 36866' the link opens up ok but I get '404 Are you lost in space?' back from EDSM. Cool, but would be nice if it went there. I believe it use to, but I can't tell you when it stopped working. I'm using v11.7.5.0

Thanks

**Comment by robbyxp1** [comment]
Enquiring with EDSM, they have changed something

**Comment by robbyxp1** [comment]
Anthor has acknowledged that the API is not working, and he will be looking into it.  No idea how long to fix.

**Comment by mearmortal** [comment]
Hey it's fine, I'm just glad to have found something real. Thanks for your efforts, o7

**Comment by robbyxp1** [comment]
Anthor has supposedly fixed the API, thanks for the report.

**Comment by nmyron** [comment]
Just wanted to comment that I found out tonight that while the EDSM tab will load your current system, if you click the "Show System" button, and input another system to get data on it, that seems to still result in the same 404 error.

For example, I am currently in Anlave. I click Show System, input WISE J004945, which is auto-filled (so EDDiscovery does have EDSM data for this system I believe in it's current data store) when I click Ok, I am routed to the 404 Lost in Space message. I can then manually browse to the system by loading the EDSM home page and inputting the name manually. I figure maybe some other API hooks are still broken on the EDSM side?

**Comment by AnthorNet** [comment]
I haven't changed anything on that URL so it's kinda strange.
Anyone could copy me the called link?

**Comment by robbyxp1** [comment]
Ok, i think its an EDD bug, i will address and fix.

**Comment by robbyxp1** [comment]
Fixed on tip, new version coming in a few days.

**Comment by nmyron** [comment]
I wanted to ask, but didn't want to tack on a new issue request without checking first. 

It appears that the EDSM pane is essentially a web renderer. It appears to render EDSM as if I opened it in my browser direct to the system I'm in. Effectively that means that EDD knows how to render websites in tabs/panes.

Is it possible to create a feature through which I could define pages to load? Basically something through which I could tell this snap in to load inara.cz, or spansh.co.uk, etc? My thoughts being that a lot of commanders use this utility, and also open another browser window to load these other sites. But I feel like, if one could load spansh and inara in a tab inside EDD, one wouldn't need that second browser window. Should I open a new issue to request this type of behavior? Do you feel it to be a worthwhile addition to the tool?

**Comment by klightspeed** [comment]
@nmyron please create a new issue regardless.
It is a dotnet [WebBrowser](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser?view=netframework-4.6.2), so under the default Windows WebBrowser implementation (which uses the Trident renderer), it would only work if the site supports Internet Explorer.  If I recall correctly, Microsoft will be turning off JScript support on IE, at which point those sites would no longer function in the WebBrowser component.
