### ISSUE TITLE
high priority voice + timer doesn't interrupt low priority voice

### ISSUE THREAD

**Issue by gordenwunderlich** [EDDiscovery/EDDiscovery#2941]
While modifying the voice pack i came upon this problem.
When there are items in the speech queue, e.g. a lot of Scans, and i start a timer which should start a high priority speech, the queue does not get interrupted, but finishes all queued low priority commands.
I have tried starting a high priority voice command as i create the timer, which works as intended, interrupting the lower priortity speeches, but using the timer doesn't work.

**Comment by robbyxp1** [comment]
no quite clear how the two could be interacting between them.  The timer system is independent of the speech system.  

You need to give me a script which causes the problem.

thanks

**Comment by gordenwunderlich** [comment]
[VoicePackV15.txt](https://github.com/EDDiscovery/EDDiscovery/files/5469373/VoicePackV15.txt)
Here is my file (Github doesn't support .act so it's a .txt).
The important parts would be the delayed response triggered from the startjump Event. The empty speech with high priority does interrupt Scan Events while the speech from the onTimer Event, which should start after 4.5 seconds, does not.
I looked into it a bit and the speech has high priority when the speak function is called but it somehow doesn't interrupt the normal priority one. So the only thing i can think of is that the timer somehow gets messed up.

**Comment by robbyxp1** [comment]
Most odd, it works here. Here is a test file, the program Test1 starts saying "Hello There" at normal priority, i pause the script for 500ms, then do your break time with high priority, then say something else.

it works - only "Hello" is voiced, the break overrides it, and then she says "And Welcome".

just put the script in the Actions folder and rename it, and rerun EDD, hit shift+F4

[T1.txt](https://github.com/EDDiscovery/EDDiscovery/files/5471181/T1.txt)

let me know if it does the same on your computer

rob

**Comment by gordenwunderlich** [comment]
Yeah that works, but my Problem looks more like this:
[T1.txt](https://github.com/EDDiscovery/EDDiscovery/files/5471336/T1.txt)
since the Scan Event is fired multiple times.
If you press shift+F4 3-4 times and then try to interrupt it with shift+F5 it won't come out.

**Comment by robbyxp1** [comment]
ok will debug when i get a mo.

**Comment by robbyxp1** [comment]
a mo was a long time.. ;-)

So I used your script, hit F4 five time, waiting for two "hello theres", hit F5, it interrupts the speech with the "and welcome", then continues with the rest of the hello there's

This is correct.

The code works like this.. 

If a speech is submitted with a priority higher than the current speech playing, then it gets inserted at the front of the queue.  

A higher priority entry, does not stop the current speech, or remove further speech, it just gets inserted in front of them, 

The only caviate is that if the queue front consists of lots of Low priority speech, and a higher one comes in, then they are all removed from the queue up to the next normal/high in the queue.

There is not a abandon queue operation as of now.  Maybe there should be an "Insert next and clear queue" order.

Rob

**Comment by robbyxp1** [comment]
Actually, looking at the code it does stop the current one, but does not clear the queue..

**Comment by robbyxp1** [comment]
I've added another option!

Priority if present sets the priority, Normal is the default, or you can use Low, High or HighClear[18], or the value can be set by the global SpeechPriority[7] when defined. 

Speech marked with a higher priority than the current top of the queue is inserted at the front of the queue, to be played next.  All entries marked low priority are removed from the front of the queue in this situation.  The current speech is stopped immediately if it’s Low or Normal priority, else it’s played out.  High Clear inserts the speech at the start of the queue, and clears the queue afterwards of all speech.

For 11.8, coming very soon.

**Comment by gordenwunderlich** [comment]
I would have expected it to say "and welcome" and then continue with the the rest, but if i hit F4 five times and immediatly press F5, it will never even say the "and welcome". I tested it a bit now and if the queue contains at least 3 "hello there" and i hit F5, it wont say "and welcome".

**Comment by robbyxp1** [comment]
strange, mine does

**Comment by robbyxp1** [comment]
Ahh i know why
you've got QueueLimit in there at 5s, that means don't bother with it if there is more than 5s of speech queued

**Comment by gordenwunderlich** [comment]
Yeah i just thought about that too. But should that really happen if the 5s queue is of a lower priority?

**Comment by robbyxp1** [comment]
Its a bit dumb, it just sums up the pending list...
