### ISSUE TITLE
%Tickcount producing negative values

### ISSUE THREAD

**Issue by gordenwunderlich** [EDDiscovery/EDDiscovery#2942]
Not sure if this is how it works but i think this is causing problems in the Maxrepeat step of the GenericResponseUI in the Voice Pack.
looking at these values
last = 0 cur = -2127520687 delta = -2127520687  MaxRepeat = 15000
since last is only uptated if something is said, it will never say anything as lasttime will stay at 0 and the result will be negative.
Can't really say tho what caused this sudden change.

**Comment by robbyxp1** [comment]
You must have left your computer on for a long time! I.E >24 days.
I'll change it to a uint, which will wrap every 49 days or so.

thanks
