### ISSUE TITLE
Material/commodity search sorting is broken for date, location and distance

### ISSUE THREAD

**Issue by oltsukoo** [EDDiscovery/EDDiscovery#2944]
The Date, Location and Current Distance columns aren't sorting entries correctly. EDDiscovery version 11.7.5.0, Windows 10 2004, build 19041.508.

The Date column seems to be assuming the system time format is M-D-Y even when it's not (I use D-M-Y) and that breaks the sorting:

![dates](https://user-images.githubusercontent.com/12410080/98471742-118ca200-21f7-11eb-9899-0df1854537de.png)

The Location and Current Distance columns are also not working correctly for some reason. Also, to switch the Location sorting direction, I need to click the column header twice. I searched older issues and the distance thing looks like it might be a new occurrence of https://github.com/EDDiscovery/EDDiscovery/issues/2625?

![locations](https://user-images.githubusercontent.com/12410080/98471794-6b8d6780-21f7-11eb-9847-878594875f50.png)

![distances](https://user-images.githubusercontent.com/12410080/98471798-6fb98500-21f7-11eb-8308-03df28e5e88f.png)

Log file doesn't seem to show any errors or anything:

[Trace_2020-11-08-19-24-08.0.log](https://github.com/EDDiscovery/EDDiscovery/files/5506834/Trace_2020-11-08-19-24-08.0.log)

**Comment by robbyxp1** [comment]
I'll fix. thanks for the report.
