### ISSUE TITLE
Feature Request: Mission Overlay Panel / Or Massacre Stacking Mission Overlay

### ISSUE THREAD

**Issue by CapWacky** [EDDiscovery/EDDiscovery#2945]
Hi,

I'd like to request a feature for tracking concurrent massacre missions as a tab / module for EDDiscovery, many of us stack wing massacre missions so that multiple missions can be completed at once killing the same faction of pirates. Most of it is dependent on whether or not the Elite API / Journal would let you extract or otherwise publish an event when you make progress on a Massacre Mission either by getting progress on the mission itself or by recording the faction of a target when it is killed by the player.

Simple Short Term Addition: Add Massacre Mission Progress to the Mission Overlay Panel.
Essentially adding an option to see how many kills you have completed on each Massacre Mission. So if you have a mission to kill 50 Pirates from a Particular Faction you would be able to see how many pirates you have actually killed..

Ideal Feature: New Panel for Massacre Mission Stacker showing kill and mission counts. Effectively the goal is to replace spreadsheets for tracking concurrent Mas and have EDDiscovery build this data layout automatically based on the player's mission board. First stab at making what the data output/tab 

Target Faction Name: X Missions from Y Factions, X of Y Kills
Individual: ~X of Y 1.23m, Wing: ~X of Y 1.23m Credits
Faction1 (Player Reputation) A of B Missions Current X of Y Kills, Pending - X Missions: A, B, C Kills
Faction2 (Player Reputation) A of B Missions Current X of Y Kills, Pending - X Missions: A, B, C Kills
Faction3 (Player Reputation) A of B Missions Current X of Y Kills, Pending - X Missions: A, B, C Kills
Faction4 (Player Reputation) A of B Missions Current X of Y Kills, Pending - X Missions: A, B, C Kills

Mission Turn in's for Massacre Missions
System1:
-Station1 (M Pad): X of Y Missions (timestamp since last landed)
-City1 (L Pad): X of Y Missions (timestamp since last landed)
System2:
-Station1 (M Pad): X of Y Missions (timestamp since last landed)
-City1 (L Pad): X of Y Missions (timestamp since last landed)

**Comment by robbyxp1** [comment]
We don't get that info.  We don't get updates on missions, only events MissionAccepted, ..Completed, ..Abandoned.

The only update we get for missions is cargo depot missions.

We also don't get faction info for a PVP kill, so we don't know what faction it is.

I don't think the journal is good enough for what you want..

**Comment by CapWacky** [comment]
Hrm. It looks like it per the combat tab; E.G. Bounty entries in the combat tab show victim faction when a bounty is issued. This could be used to track mission progress artificially for the full "Massacre Mission Progress" Tab.

So for example you pick up a series of Massacre Missions for the same NPC Target Faction from 3 different mission giver factions killing the same target pirate faction the Albardhas Syndicate.

Faction 1: 3 Massacre Missions, 151 total pirate kills. Target Faction: Albardhas Syndicate
Faction1 Mission1: Massacre 20 Albardhas Syndicate Pirates, start time 11/10 00:00 UTC
Faction1 Mission2: Massacre 50 Albardhas Syndicate Pirates, start time 11/10 00:10 UTC
Faction1 Mission3: Massacre 81 Albardhas Syndicate Pirates, start time 11/10 00:15 UTC

Faction 2: 4 Massacre Missions, 123 total pirate kills. Target Faction: Albardhas Syndicate
Faction2 Mission1: Massacre 45 Albardhas Syndicate Pirates, start time 11/10 00:00 UTC
Faction2 Mission2: Massacre 18 Albardhas Syndicate Pirates, start time 11/10 00:12 UTC
Faction2 Mission3: Massacre 35 Albardhas Syndicate Pirates, start time 11/10 00:20 UTC
Faction2 Mission4: Massacre 25 Albardhas Syndicate Pirates, start time 11/10 00:20 UTC

Faction 3: 2 Massacre Missions, 153 total Pirate Kills. Target Faction: Albardhas Syndicate
Faction3 Mission1: Massacre 72 Albardhas Syndicate Pirates, start time 11/10 00:00 UTC
Faction3 Mission2: Massacre 81 Albardhas Syndicate Pirates, start time 11/10 00:12 UTC

Totals:
Massacre Missions where Target Faction = Albardhas Syndicate: 9
Concurrent Pirate Kills = 153 (e.g. the largest total of all the Massacre Missions for a single faction)

You then establish a variable for each faction kill count. Call it FactionX_Massacre_Progress, one for each faction given for the oldest mission.

When Bounty is issued; If Bounty Victim Faction = Tracked Target Faction from Massacre Mission set then advance each FactionX_Massacre_Progress Variable by 1.

If an event is received for one of the Missions Expiring, being Completed or Abandoned then update the appropriate FactionX_Massacre_Progress to 0 and start applying progress to the next oldest massacre mission for the issuing faction and recalculate the Concurrent Pirate Kills stat accordingly.

**Comment by robbyxp1** [comment]
I'll keep the idea in mind, and put it on the project list.  But I've limited time for coding at the moment, and need to complete some other stuff, so don't hold out any expectations of a quick result.

Moving to projects and closing.

**Comment by CapWacky** [comment]
ok seems fair and reasonable. In the meantime I will poke around the github to see how this could be made as an addon until there is time and interest to do this as a project.
