### ISSUE TITLE
Route Planner now working as expected

### ISSUE THREAD

**Issue by BraINstinct0** [EDDiscovery/EDDiscovery#2955]
![image](https://user-images.githubusercontent.com/29201475/100491327-fcf05980-3165-11eb-8a07-283d6b9eec66.png)
The WAYPOINTs should be systems, not placeholder systems

**Comment by robbyxp1** [comment]
Its working as designed.  You probably don't have the EDSM Data loaded into EDD, so it does not know about any nearby systems, thus its just giving you waypoints.  In settings, galaxy data, download the EDSM data (4.6gb) and try again.

**Comment by BraINstinct0** [comment]
![image](https://user-images.githubusercontent.com/29201475/100515770-ce07d100-31c1-11eb-8d5c-24796f8f85fe.png)
Confirmed. Thanks for the quick feedback, though it *might* seem too large.
maybe some compression-send-decompression might help?
i.e. upload compressed every week, just pull the diff everytime

**Comment by klightspeed** [comment]
When the database has been updated within the last 2 weeks, then the program will use the EDSM API to download any updated systems.
