### ISSUE TITLE
Backup your EDDiscovery data

### ISSUE THREAD

**Issue by Cowski4444** [EDDiscovery/EDDiscovery#2958]
Hi there!!
Loving your program.  I run it along side E:D every time I play.  I feel I'm missing something if it isn't running on one of my other monitors while I'm playing.
I have data dating back to 2016 with the game.  It's fun checking things out as I progressed.  And with that said, I'd hate to lose all this data if something were to happen to EDD or E:D.
My suggestion is an option to backup the data within EDD.  I looked and didn't find one unless I missed it.  
Everything else you have is absolutely perfect.  Thanks for this program and your continuing work on it.

**Comment by robbyxp1** [comment]
Its real easy to back it up.. go to %localappdata%\eddiscovery.  Backup EDDuser.sqlite.  That holds all the journals records, bookmarks, user settings etc.

I'll put in a backup option to the safe mode. Adding to project ideas and closing ticket.

**Comment by robbyxp1** [comment]
Going to be in the next release, good idea, thanks
