### ISSUE TITLE
Request: UI Readability Enhancement - Shading for alternate table rows

### ISSUE THREAD

**Issue by CircuitGuy** [EDDiscovery/EDDiscovery#2959]
Is it possible to add shading to the table rows?

Example of what I'm hoping for (CSS, probably N/A here, but you get the idea): https://www.geeksforgeeks.org/how-to-set-alternate-table-row-color-using-css/

Problem:
Looking at any of the larger tables, I'm absolutely unable to follow a row without highlighting it. For example, hop over to the materials tab while full screen on a wide monitor.

Solution:
Alternate table row shading would be a significant UI readability improvement, helping to guide the eyes across a row.

**Comment by robbyxp1** [comment]
I'll have a look into it, but that means a change in the theme system as we would need to add a new colours to the theme table, alter all the themes, etc.  Doable.

I'm going to add this to the project ideas and close the ticket down.

**Comment by robbyxp1** [comment]
You'll be glad to know i've done it, its a good idea.  in 11.9.3, coming soon

**Comment by CircuitGuy** [comment]
> You'll be glad to know i've done it, its a good idea. in 11.9.3, coming soon

Wow! Thanks. Also, you're a freaking machine. That was ridiculously fast.

**Comment by CircuitGuy** [comment]
Haven't seen / figured out this feature yet. Wasn't in 11.9.3 or 11.10.1.0
