### ISSUE TITLE
Estimated Values tab re-sorts itself upon planet mapping

### ISSUE THREAD

**Issue by phlnx** [EDDiscovery/EDDiscovery#2960]
1. I opened a new tab with the Estimated Values feature.
2. I traveled to a system (for the record, Synuefe UD-R C21-35).
2. I clicked on the column Body Name so that it would be sorted in the orrery order and not in the previous order which was by the "Est Value" column.
3. I mapped a planet that I hadn't mapped before (and coincidentally that wasn't been mapped by anyone), for the record, Synuefe UD-R c21-35 5.
4. Upon returning to EDDiscovery, the body table was sorted back to the "Est Value" column.

If this is the intended feature, then please ignore and close.

Thank you for your attention.

**Comment by robbyxp1** [comment]
I'll fix this, it should remember the sort. Thanks for the report.
