### ISSUE TITLE
Fatal error after upgrading

### ISSUE THREAD

**Issue by ficostam** [EDDiscovery/EDDiscovery#2961]
I have updated EDD from v. 11.2 to 11.9.3
I can't start the application anymore, the following is the first of a series of errors until a fatal one that will close the app.

### Exception Details:
>EDDiscovery v11.9.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.DivideByZeroException: Tentativo di divisione per zero.
>   in System.Windows.Forms.DataGridViewCell.MeasureTextPreferredSize(Graphics graphics, String text, Font font, Single maxRatio, TextFormatFlags flags)
>   in System.Windows.Forms.DataGridViewColumnHeaderCell.GetPreferredSize(Graphics graphics, DataGridViewCellStyle cellStyle, Int32 rowIndex, Size constraintSize)
>   in System.Windows.Forms.DataGridViewCell.GetPreferredSize(Int32 rowIndex)
>   in System.Windows.Forms.DataGridView.AutoResizeColumnHeadersHeight(Boolean fixedRowHeadersWidth, Boolean fixedColumnsWidth)
>   in System.Windows.Forms.DataGridView.OnGlobalAutoSize()
>   in System.Windows.Forms.DataGridView.OnHandleCreated(EventArgs e)
>   in System.Windows.Forms.Control.WmCreate(Message& m)
>   in System.Windows.Forms.Control.WndProc(Message& m)
>   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

here is the fatal error:

### Exception Details:
>EDDiscovery v11.9.3.0 An unhandled fatal exception has occurred.
>```
>==== BEGIN ====
>System.Reflection.TargetInvocationException: Eccezione generata dalla destinazione di una chiamata. ---> System.AccessViolationException: Tentativo di lettura o scrittura della memoria protetta. Spesso questa condizione indica che altre parti della memoria sono danneggiate.
>   in System.Windows.Forms.UnsafeNativeMethods.ITextRange.ScrollIntoView(Int32 value)
>   in System.Windows.Forms.TextBoxBase.ScrollToCaret()
>   in ExtendedControls.ExtRichTextBox.AppendText(String s, Color c) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\RichTextBox.cs:riga 111
>   in EDDiscovery.UserControls.UserControlLog.AppendText(String s, Color c) in C:\Code\EDDiscovery\EDDiscovery\UserControls\LogsBookmarks\UserControlLog.cs:riga 57
>   in EDDiscovery.EDDiscoveryController.<>c__DisplayClass118_0.<LogLineColor>b__0() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerMain.cs:riga 401
>   --- Fine della traccia dello stack dell'eccezione interna ---
>   in System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>   in System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>   in System.Delegate.DynamicInvokeImpl(Object[] args)
>   in System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
>   in System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   in System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   in System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>   in System.Windows.Forms.Control.WndProc(Message& m)
>   in System.Windows.Forms.Form.WndProc(Message& m)
>   in ExtendedControls.SmartSysMenuForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\SmartSysMenuForm.cs:riga 221
>   in ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\DraggableForm.cs:riga 169
>   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>   in System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
>   in System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
>   in System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
>   in System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
>   in System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
>   in ExtendedControls.MessageBoxTheme.Show(IWin32Window window, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, Icon windowicon) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\MessageBoxTheme.cs:riga 33
>   in EDDiscovery.EDDiscoveryForm.EDDiscoveryForm_Shown(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:riga 417
>   in System.Windows.Forms.Form.OnShown(EventArgs e)
>   in System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   in System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   in System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>   in System.Windows.Forms.Control.WndProc(Message& m)
>   in System.Windows.Forms.Form.WndProc(Message& m)
>   in ExtendedControls.SmartSysMenuForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\SmartSysMenuForm.cs:riga 221
>   in ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\DraggableForm.cs:riga 169
>   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>   in System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
>   in System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
>   in System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
>   in System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
>   in EDDiscovery.Program.Main() in C:\Code\EDDiscovery\EDDiscovery\Program.cs:riga 45
>===== END =====
>```

The directory C:\Code does not exist. EDD is installed in C:\Program Files\EDDiscovery

**Comment by klightspeed** [comment]
Please try resetting the layout by holding shift while starting and using the safe mode dialog to reset tabs and positions.

Both errors imply that your layout is broken.

**Comment by ficostam** [comment]
I gathered it was a config problem and looked in the apps folder for files but couldn't find anything useful.
Thank you very much for your instructions though, they worked like a treat! I didn't know of safe mode, nice one. Well done to you and the rest of the team!
