### ISSUE TITLE
Rider factions

### ISSUE THREAD

**Issue by PeterMayerHamburg** [EDDiscovery/EDDiscovery#2962]
Include the percentage call in the list.
Otherwise the overview is very interesting.

Times have shortened the log file and moved it to another folder ( To backup the data and later pack with zip ) . The overview of the missions has gone to zero, only the information on Commodites Sold and Bought is still visible. It seems that ED Discovery is always accessing this log folder when viewing it.

**Comment by robbyxp1** [comment]
Not clear what you mean, sorry.  What is 'percentage call'?  Do you mean the faction panel?

The second part I'm not clear about either.

**Comment by robbyxp1** [comment]
No response, closing.
