### ISSUE TITLE
Map 2D Local Systems - Current System (Red Dot) is hidden behind Visited System Icon (Blue Dot)

### ISSUE THREAD

**Issue by TheSaltySailor** [EDDiscovery/EDDiscovery#2963]
When using the Map 2D Local Systems panel, the red dot icon that indicates the current system is being obscured by a blue dot icon.  It is difficult to readily identify where the current system is in order leverage this panel.

![EDDiscovery_2D map_zoomed_in](https://user-images.githubusercontent.com/76213506/102620232-b4e0a900-410b-11eb-87bc-31d4a641405a.png)
![EDDiscovery_2D map_zoomed_out](https://user-images.githubusercontent.com/76213506/102620241-b6aa6c80-410b-11eb-89d7-3ba94431e530.png)

**Comment by robbyxp1** [comment]
That panel is going to be removed soon, in favour of a new 3dmap.  I'll have a look but its on the depreciated list and if its hard to fix, it will have to remain the same.

thanks
rob

**Comment by TheSaltySailor** [comment]
No worries Rob.  I'm new to the tool and poking through the various panels learning what they do.  Thank you very much for the feedback and for your work with this application.

**Comment by robbyxp1** [comment]
CLosing, will keep it in mind.
