### ISSUE TITLE
Voice pack might have died.

### ISSUE THREAD

**Issue by WayneFrancis** [EDDiscovery/EDDiscovery#2965]
### Description
Scanning a system with FSS

### Exception Details:
>EDDiscovery v11.2.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
>   at CSCore.DirectSound.DirectSoundBuffer.Stop()
>   at CSCore.SoundOut.DirectSoundOut.CleanupResources()
>   at CSCore.SoundOut.DirectSoundOut.Initialize(IWaveSource source)
>   at AudioExtensions.AudioDriverCSCore.Start(AudioData o, Int32 vol) in C:\Code\EDDiscovery\BaseUtilities\Audio\AudioDriverCSCore.cs:line 166
>   at AudioExtensions.AudioQueue.Queue(AudioSample newdata) in C:\Code\EDDiscovery\BaseUtilities\Audio\AudioQueue.cs:line 185
>   at ActionLanguage.ActionSay.ExecuteAction(ActionProgramRun ap) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCoreCmds\ActionSay.cs:line 307
>   at ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 217
>   at EDDiscovery.Actions.ActionController.ActionRun(ActionEvent ev, HistoryEntry he, Variables additionalvars, String flagstart, Boolean now) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:line 544
>   at EDDiscovery.EDDiscoveryForm.Controller_NewEntrySecond(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 676
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 85
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 73
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(Tuple`2 entries) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 185
>===== END =====
>```

**Comment by klightspeed** [comment]
See #1722 - This error is one of those errors that occurs infrequently, and when it occurs there isn't much that can be done to recover from it other than restarting the program.

Also, 11.2 is almost a year old, and does not support Carriers.  The current release <https://github.com/EDDiscovery/EDDiscovery/releases/latest> is 11.9.3

**Comment by robbyxp1** [comment]
Thanks for the report, closing. Just ignore it.
