### ISSUE TITLE
Mining Overlay does not update

### ISSUE THREAD

**Issue by NKDavis** [EDDiscovery/EDDiscovery#2968]
I am running version 11.9.3.0 
I also have E:D Market Connector 4.1.5 running.

When I try to use the Mining overlay it does not update.

Is this a bug, or is the fault with my set up?

**Comment by robbyxp1** [comment]
it looks at your mining session pointed to by the travel history grid current entry (normally at the top), at the refined/prospected entries. Do you have those in the history?

**Comment by robbyxp1** [comment]
No response, closing.
