### ISSUE TITLE
EDDiscovery for the hearing impaired

### ISSUE THREAD

**Issue by JamesRabe** [EDDiscovery/EDDiscovery#2969]
Is there an option or module that will allow EDD to be used by the deaf?
Perhaps instead of speaking it has a pop-up text display?

**Comment by robbyxp1** [comment]
The only option at the moment to see what the speech is is to do this, go the Add-Ons, Edit Addons, click on "Globals" at the bottom, and add this entry (scroll down to see the + sign on the bottom left)

![image](https://user-images.githubusercontent.com/6573992/102777793-38f39480-4389-11eb-9e1f-b6657eb7f7cb.png)

this will print the speech to the EDD log window.

Your probably thinking of a pop out translucent window which the speech appears in?  That could be done later in the future.

**Comment by robbyxp1** [comment]
Adding to ideas

**Comment by robbyxp1** [comment]
Note this will be in Voicepack 16/EDD 11.10

**Comment by robbyxp1** [comment]
11.10.1 is launched with this feature!

**Comment by JamesRabe** [comment]
Is there anything that can be done to make the text box more readable in game?  Is it a Windows thing that the text becomes readable only if you hover the mouse over the box, or place a white background behind the window (such as using an empty *.txt file?  I have found that if I hover my mouse over the box I can read it in game but it is hard to play that way.  For example, clicking a mouse button to fire my weapons while the cursor is over the text box causes windows to focus EDD instead of the game, effectively alt-tabbing me out of the game.  And of course, focusing an *.txt file to make it readable also alt-tabs me out of the game.
