### ISSUE TITLE
Unhandled exception when double clicking on border between "Distance" and "Information" column headers in "Scan Data on system in a grid" panel within "Grid" tab

### ISSUE THREAD

**Issue by mmseng** [EDDiscovery/EDDiscovery#2975]
### Description
Hi, I seem to have found a repeatable bug causing an unhandled exception error and crash to happen.

I don't currently have the resources to thoroughly test the re-createability of this (i.e. with a fresh install). But in my current setup, I have a "Grid" tab with several panels. One of the panels is the "Scan data on system in a grid" panel. Within this panel, whenever I double-click on the border between the "Distance" and "Information" column headers (i.e. in order to auto-resize the "Distance" column), and unhandled UI exception is thrown. I haven't seen this behavior with any other table.

I should note that selecting "Continue" in the exception dialog allows the program to continue working normally, and I can repeat the exception again with or without closing and reopening the app.

The exception info dump is pasted below, and I've attached a screenshot.

### Environment:
Win10 Pro 20H2 x64
EDDiscovery v11.9.3.0

### Exception Details:

![eddiscovery-unhandled-exception](https://user-images.githubusercontent.com/8218085/102900354-c7235580-4431-11eb-869d-a945dc9c2a11.png)

>EDDiscovery v11.9.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.Collections.ArrayList.get_Item(Int32 index)
>   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
>   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
>   at EDDiscovery.UserControls.UserControlScanGrid.dataGridViewScangrid_CellDoubleClick(Object sender, DataGridViewCellEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScanGrid.cs:line 638
>   at System.Windows.Forms.DataGridView.OnCellDoubleClick(DataGridViewCellEventArgs e)
>   at System.Windows.Forms.DataGridView.OnDoubleClick(EventArgs e)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Gotcha, good find! Fixed, and will be in the next version..

Thanks for reporting this.

Rob
