### ISSUE TITLE
"Ship yards" panel table sorts "Price" column alphabetically, instead of numerically

### ISSUE THREAD

**Issue by mmseng** [EDDiscovery/EDDiscovery#2976]
See title, screenshot below:

Expected behavior: table sorts price numerically. Additionally, it would be easier to read (and perhaps would make more sense from a code/sorting standpoint), if "cr" were omitted from the values, perhaps being added to the column header, i.e. "Price (cr)". Lastly, the trailing 0 in the tenths place could be omitted.

I would hazard a guess that this is all probably just precipitated by the values being read in as a string, rather than interpreted as an integer.

![eddiscovery-shipyards-sorting](https://user-images.githubusercontent.com/8218085/102942972-679e6780-447c-11eb-8e95-42bc7a809c16.png)

Regards,

**Comment by robbyxp1** [comment]
See it, fixed. Thanks.
