### ISSUE TITLE
Errant malformed commodity is listed in "Search" panel

### ISSUE THREAD

**Issue by mmseng** [EDDiscovery/EDDiscovery#2977]
### Description:
When looking at the "Materials Commodities" tab within the "Search" panel, the first commodity listed is `$ Aislingmediamaterials Name ; (Commodity, Unknown)`. Perhaps this is the result of corrupt data downloaded by my client, or maybe the bad entry is being pulled straight from EDDN. Or maybe it's just an erroneous manipulation of good data before being displayed in the dropdown.

Screenshots:

![eddiscovery-material-search-oddity](https://user-images.githubusercontent.com/8218085/102943898-f8764280-447e-11eb-9dcb-613d077067c8.png)

![eddiscovery-material-search-oddity2](https://user-images.githubusercontent.com/8218085/102943904-fb713300-447e-11eb-8382-36fde26a3731.png)

**Comment by klightspeed** [comment]
It's a commodity it doesn't know about, so it doesn't know the name of it, so it tries to format its symbolic name `$aislingmediamaterials_name`

From Inara <https://inara.cz/galaxy-commodity/10172/>:
> **Aisling Media Materials**
> Used by Aisling's supporters to prepare systems by delivering to the desired system. They are of no value to anyone but her followers. This Item will be out of date at the end of the powerplay week.

**Comment by robbyxp1** [comment]
Frontier has not advised us of this material.

**Comment by robbyxp1** [comment]
Wrong, we do know about:            AddCommodity("Aisling Media Materials", ItemType.PowerPlay, "AislingMediaMaterials");

Whats up with that _name thing? I wonder which journal entry had that in.

**Comment by mmseng** [comment]
I searched through all my journals with Notepad++ and here are the only two lines that returned from searching "aislingmedia", both in a journal from 2017-07-08:

`{ "timestamp":"2017-07-08T09:26:45Z", "event":"PowerplayCollect", "Power":"Aisling Duval", "Type":"$aislingmediamaterials_name;", "Type_Localised":"Aisling Media Materials", "Count":10 }`

and 

`{ "timestamp":"2017-07-08T10:07:05Z", "event":"EjectCargo", "Type":"aislingmediamaterials", "Count":10, "Abandoned":false }`

I don't know how EDD functions so is this where it pulls the list of materials from? I kind of figured that would have been a list from EDDN. If it's just pulling an aggregated list from journals, while I have no real experience with journal syntax, it kind of looks like it's just an issue with the data not being kosher in this particular journal.

I can provide the full journal if anyone wants, but it doesn't seem relevant.

**Comment by robbyxp1** [comment]
You read my mind, I was going to ask you to find this. Thanks

So its powerplay collect which is doing this.  I will patch over it and correct for the $ _name part.

The materials are hard coded in EDD from information provided to us by Frontier.

Thanks

**Comment by robbyxp1** [comment]
patched.
