### ISSUE TITLE
Hide Column

### ISSUE THREAD

**Issue by Aebrahim-uct** [EDDiscovery/EDDiscovery#2978]
Hey there
Wanted to just ask about the possibility of maybe adding the hide column feature to all panels that use a grid to display data?
I currently am using Statistics and Estimated Values in a Splitter view to see an overview of my current exploration value and a hide column option within those/all panels would help me just de-clutter unnecessary/unwanted info.
Thanks and loving the work you guys have done :)

**Comment by robbyxp1** [comment]
Hi,

Estimated values I already noticed I did not put the hider on it - it now has it, next release.

Stats I'll have a look into.

I've made a note to do this.

Thanks.

Closing.
