### ISSUE TITLE
UI Frozen up

### ISSUE THREAD

**Issue by Dover8** [EDDiscovery/EDDiscovery#2979]
### Exception Details:
>EDDiscovery v11.9.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: No row can be added to a DataGridView control that does not have columns. Columns must be added first.
>   at System.Windows.Forms.DataGridViewRowCollection.AddInternal(Boolean newRow, Object[] values)
>   at EDDiscovery.UserControls.UserControlEstimatedValues.<DrawSystem>d__11.MoveNext() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlEstimatedValues.cs:line 112
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by robbyxp1** [comment]
Hi,

Is this repeatable, or a one off?

**Comment by robbyxp1** [comment]
Closing, no more info

**Comment by Dover8** [comment]
I managed to lock it up a few times, but not sure there were set reproducible steps.

**Comment by klightspeed** [comment]
If you look at the log (`%LOCALAPPDATA%\EDDiscovery\Log\Trace*.log`) around the time that it locked up, were there any errors?

**Comment by Dover8** [comment]
Yes, the one I mentioned when opening the bug. Here is the full log from the time. 
[Trace_2020-12-27-15-51-08.0.log](https://github.com/EDDiscovery/EDDiscovery/files/5932103/Trace_2020-12-27-15-51-08.0.log)

**Comment by klightspeed** [comment]
> [2020-12-27T16:03:01.794Z] HTTPGET TO https://www.edsm.net/api-v1/systems
...
> [2020-12-27T16:03:41.179Z] New entry 27/12/2020 16:03:40 ReservoirReplenished
> [2020-12-27T16:05:42.327Z] SystemsDatabaseConnection Job delayed for 121140ms
> [2020-12-27T16:06:00.161Z] HTTPGET TO https://www.edsm.net/api-v1/systems

Taking about 3 minutes to add 3 hours of systems from EDSM (about 10000 systems) suggests that it's on slow storage.  You might be best to disable EDSM star data download.

**Comment by Oldwargoat39** [comment]
I have that problem as well. No interaction with UI but it still runs

**Comment by Dover8** [comment]
> Taking about 3 minutes to add 3 hours of systems from EDSM (about 10000 systems) suggests that it's on slow storage. You might be best to disable EDSM star data download.

Database is stored on an SSD.

**Comment by robbyxp1** [comment]
Try the rebuild system index in 11.10.x in the admin menu. see if rebuilding it helps.
