### ISSUE TITLE
French traduct or bug : TERROFORMABLE

### ISSUE THREAD

**Issue by Dextramorphane** [EDDiscovery/EDDiscovery#2980]
Hello
I see in French the word TERROFORMABLE for planets
The correct word is TERRAFORMABLE 
Thank you 
![sdfdsfdsfsd](https://user-images.githubusercontent.com/75636751/103443559-c1fbad00-4c60-11eb-9e80-812fa3af70ee.jpg)

**Comment by robbyxp1** [comment]
Ok, will fix.

**Comment by robbyxp1** [comment]
fixed
