### ISSUE TITLE
Love the tool! A couple of requests for explorer usage

### ISSUE THREAD

**Issue by fredjk-gh** [EDDiscovery/EDDiscovery#2985]
Hi there. I started playing ED a couple weeks ago and found EDDiscovery about a week ago (version 11.9.3.0). It has a lot of great features. Your documentation/wiki have been tremendously helpful.

I've been using EDD to capture as I am exploring. I have a route plotted in-game between two waypoints (~1000 Ly between waypoints, overall, some 6K Ly 1-way trip) and am navigating that in game. I use EDD to determine what bodies to scan (DSS) and keeping track of which I have scanned. Furthermore, I'm tracking every system I visit to a route in the Expedition and keeping a captains log.

I've modified the history grid to have the the following panels:

<pre>
+-------------------------------+------------------+
| Event history (filtered)      | System info      |
+-------------------------------+------------------+
| System map                    | Estimated values |
+-------------------------------+------------------+
| Expedition                    | Nearest stars    |
+-------------------------------+------------------+
</pre>

General workflow:
1) Jump into a system, honk, FSS.
2.1) Look at map/estimated values to see if there is anything I wish to DSS and do that. Use map to keep track of what I've done.
2.2) Check map and do whatever other exploring, planetary landing, material gathering, etc. I wish to do. Chase down any in-game phenomena, etc.
3) Add a note to the system for anything of interest (ie. if it was previously considered undiscovered so I may be tagged, features of the system, etc). I am not syncing these notes to eddn as they are relative to my journey.
4) Add the system to my route.
5) Repeat...

At the end of the session, add an entry to the captains log.

Things I'd love to see improved:
1) Overall performance. It's pretty sluggish on my quite reasonable gaming desktop w/ 32 GiB of memory and a 6 core/12 thread CPU and an M.2 disk. I've limited the history grid to 6 hours of entries to keep it usable.
2) Expedition panel: Remember last-opened route. Allow the various input fields [Route Name, Reverse, Start/End date] to be collapsible to reduce the space they take up. (Keep the button panel always there, although, why isn't "Reverse" on button panel?) I don't mind the stats staying visible if they're on 1 line.
2.1) Auto-save route when a system is added. I discovered it doesn't auto-save after shutting it down the first time and having all my day's progress lost. Thankfully, I was able to recover by going back through that day's history. Was a surprise, got no warning I had "unsaved" data when closing.
2.2) I currently have 284 entries in my expedition... Saving it is getting slow (can't scroll the expedition list for several seconds after hitting save).
2.3) Keep the list scrolled to the bottom (or auto scroll to newly added item).
3) Adding a system to expedition panel takes a lot of clicks (right-click the history event of interest, select "Add to..." -> "Expedition Panel"). Can you add a "Save to expedition" button for this on the System Info panel?
4) Adding notes: Typing notes in the System Info panel or in the history grid is *super* slow and glitchy. The cursor position in the System info panel jumps around when there's a background data refresh. The fastest, most reliable way of doing it is through the "Set note" right-click menu option. Perhaps both the history grid "Note" field and the System Info "Note" field could be changed to open the dialog too (similar to the Captains Log grid)?
5) Estimated Values panel: Can estimated values in the grid be summed up and displayed beside the EDSM button (and updated as new information becomes available)? Perhaps this total estimated value could also be displayed on the System info panel?
6) Expedition: Also add the total estimated system value also to the route in the expedition so I can also have a cumulative estimated value of my journey! I'd love to know the approx value of the cartographic data I'm carrying with me!

Super long-term bonus idea: Add the ability to use an external mysql/maria database.

Feel free to split this up as you please... If there is some functionality I've requested that's already there but I've not found yet, point me to it!

Thanks again for a great app!

**Comment by robbyxp1** [comment]
Thats a lot of suggestions! 

Performance is what it is - the data grid views take a lot of memory/time to populate and thus you should limit them.  Make sure your on an SDD for the EDD databases.

Most of what your asking for is a lot of work.

2.1 is difficult, there is no mech at the moment for panels to prevent shutdown
2.3 may be doable
3 means a new button or more on the system info panel 
4. thats the way it works, if a new entry comes in and you've got the go to last entry button clicked, it will save it and go to the top.  Not sure how i can change that behaviour.  I could do double click on note field opens the dialog
5. No, not enough space.  i'll consider if estimated values can be computed in a system info field - this is normally done in panels and so i'll have to check performance.
6. This again is difficult - its not part of the panel to work out totals.

We are sticking with the inbuilt SQL database, i'm not going to test yet another database system.

Moving to the project backlog.

thanks

Rob
