### ISSUE TITLE
Screenshots not converting

### ISSUE THREAD

**Issue by clementsX** [EDDiscovery/EDDiscovery#2986]
Hello, 

I have been trying to get this to work for several days now and it just won’t finish the loop. I have quadruple checked the directories for both locations and they are correct. 

What happens! 

I hit the F10 key for screen shot, the screenshot is captured, it creates the sun folder in the “save to” directory but does not convert the actual screen shot. Any help would be greatly appreciated! 

- I have ran program as admin
- Disabled all F10 keys in GeForce Experience
- Tried both the Steam and Frontier screenshot directories 
- Restarted the Program 
- Restarted the PC

**Comment by robbyxp1** [comment]
heres my screenshot configuration dialog, which is for Elite directly (not steam)

![image](https://user-images.githubusercontent.com/6573992/104569856-221f2580-5649-11eb-8bf7-0904d83aca96.png)

and its enabled.  is yours anything like that?  Remember ED needs to be running at the time the screenshot is taken.

**Comment by clementsX** [comment]
> heres my screenshot configuration dialog, which is for Elite directly (not steam)
> 
> ![image](https://user-images.githubusercontent.com/6573992/104569856-221f2580-5649-11eb-8bf7-0904d83aca96.png)
> 
> and its enabled. is yours anything like that? Remember ED needs to be running at the time the screenshot is taken.

Thank you for the reply, yes mine look exactly like this. On the settings page it is enabled. And yes the game is running while taking the screenshots; as stated above the screenshot is created in the main folder, than in the conversion file a sub folder is created but no conversion happens!

**Comment by robbyxp1** [comment]
Sorry, see a mistype, EDD is running when the screenshot is taken?

**Comment by clementsX** [comment]
> Sorry, see a mistype, EDD is running when the screenshot is taken?

Yes, EDD is running. I have had it running normal and as an admin. I leave it up on the 2nd monitor so I can see things from in game that I am looking at in the moment. 

The only difference I see from your screenshot and mine without being at my PC is I have mine set to do the sub folders.

**Comment by clementsX** [comment]
![screenshot ed discovery](https://user-images.githubusercontent.com/77316557/104681358-61805d00-56af-11eb-843b-0e8f62ebc85e.PNG)

Here is a screenshot of my screen shot conversion settings. Please assist!

**Comment by clementsX** [comment]
I was able to make some progress on this issue. I disabled the Geforce experience in game overlay. Now the screenshot event is showing in the action log but it is throwing this error. 

Error in executing image conversion, try another screenshot, check output path settings. (Exception Access to the path 'C:\Users\%name%\Pictures\Frontier Developments\Elite Dangerous\2021\Evangelis (20210115-054946).jpg' is denied.)

With this new error, I have tried in both non administrator and administrator mode. 

Any suggestions?

**Comment by klightspeed** [comment]
Access Denied can mean that anti-malware (often Anti-Ransomware) is blocking the program from accessing the files.

**Comment by clementsX** [comment]
Thank you for the info. I am running Avast, I will look and see if it is blocking anything from Elite Dangerous and report back!

**Comment by clementsX** [comment]
Thank you all for your help! Problem fixed! How I did it in the event someone else runs into this in the future! 

Disabled GeForce Experience In-game Overlay

Added ED Discovery to my anti-virus exceptions

Thank you again, Happy hunting!

**Comment by robbyxp1** [comment]
Another anti-virus problem, I think they cause more problems than they solve!

Thanks for the report. Happy flying commander.
