### ISSUE TITLE
EDDiscovery can't export to Coriolis via Firefox browser.

### ISSUE THREAD

**Issue by TonyFlury** [EDDiscovery/EDDiscovery#2987]
I use EDDiscovery application on Windows 10, and Firefox 84.02 as my default browser.

From the Ship Loadout tab I press the 'Send to Coriolis' button and get the following error in the browser window :

>     Jameson, we have a problem..
>     TypeError: can't redefine non-configurable property "userAgent"
> 
>     If you are attempting to import a ship from EDDI or EDMC and are seeing a 'Z_BUF_ERROR' it means that the URL has not been provided correctly. This is a common problem when using Microsoft Internet Explorer or Microsoft Edge, and you should use another browser instead.
> 
>     Please note that this site uses Google Analytics to track performance and usage. If you are blocking cookies, for example using Ghostery, please disable blocking for this site and try again.
> 
>     Create an issue on Github if this keeps happening. Add these details:
>     Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
>     Path: /import?data=H4sIAAAAAAAEAO1aTXPbNhD9Lzw7HALgp29OnNRu7Sa1POmhk%2BFAJCShJgkOSDlVM%2F3vXYBSRJOgSEk%2B5BAfkhFBPS6wb3ffLvXNYs%2BsqK1L607QVKxr68KarXgJF36TlNfx%2FdPtLVy7F%2Bk6Y5V1%2Bdc367ZmOaw%2F6fX8ifP4SuZiLeOlpClDCiETCrK5DJ8%2FFtZlLdfswvokuZC83liX6MJ6Xyx5wZjkxdK6%2FGa9zdashA%2F17TUs49APiE%2Fci%2F3132nOvsPGV%2BkzLRKWAv4dbCKzLr0L6481zTS8Y0e%2Bq%2B3mC85kY%2Fkdnav7rGu2YPDV3eINo1m9ul9nNS8z%2BAyInyk81LoMAEb9YdiD5GAtzXYr0feVO1ZVt9UvQqTW5YJmFfvvYv%2Bo32CHNU8eWMWrWtm7B3%2BDbQf%2BUA%2F7DXb0iuOOgD%2BumMzN4Mht7At76IA9Avv%2BnzITFX9mRqtR1Bjn9%2B0m20PxTQ%2F48p96xpY8ueITlQmVSzGnm1QIuefNO3X1htbJaoA7uIV0W9TxalMymUqwOK74v8yLk4xWlbtH%2FCCBOsDrRX2t7hqAdSZRMjJQ8sPsOr4TxfKBFks2SMggGiLkPZi7P2IX2Z7ZdwR3naf20PYdHAdb6u3sqYCx7SqP9VmMXHeUDZ%2FEVyavJf26R3RsL%2FAMxPIO2wan9LGseU6zl%2FtFxHNtF2E36HMqDDyzhS%2FopEiwWLMMuPrUpgBpUQCWH2F5KB110DK%2BYNW6LIWsNaDbALay2x3cMWvumEhTpsml4fwGztvD3VNeNOyrzqKnF%2FTp2XwtvuZS82LLTtJiJ1KHPIWbxFd3dpzk9nLKFFoibIekyRZdWuKTaBnayHdDQ0INbM8%2FbF9zQgPsbKKuHzoTMukO9hOTCyHzTo7GpsNEzlRcqFv1A63biHZoCHKbGDb%2F5ULleaBSDvWfZu8XC5YoHlYlSzjNdmTN%2BHJVf2XqX6sdcTcl1H5VMRNaFKKIlzyfw7dylvJ13mK1%2FnxDZVoK4CM6h9qeY8i8fzJawuM%2FPjOZrKBuHNID3qAeoDldMvDRjCWiSPfnCYWYEBSZMie2feSR0BvxVAPdQrSDEGMD5W1%2FrNpfQy2WfL6uRS8dozAypGPkHia9lg80U8qvDeabsPBhKEXDj4sPXLa2GtjECfyIGMLRjzBxwpH9XuW5eJfxcgb5soUaGGImGg%2BZxhGPoBTae%2B1DDSCNhQuHyC5STuUmlmJdpNUrRAs%2BL1rIcdHiTisHh2IFha6PTOn81FjxsfvqkdKP5ZMjBRvMGw0VM61DExeHaD1GRgo7jzMwFnqZrkwqMwodCS1LKWiyqtZc148tAT81i3JztV2fbdenSKZSVeR0f%2FRa6AQ93dQU7v1t55A8MPWH3QfEN1C93tGSJrwtf7xpfDcpF4%2FYSrhEBnKicDQTNUFYtSzaftnz7DBCKAr6AgtNRX1gTWC3FJvtQivc7yVcG01SGQZDQQSGjt%2FfPQ4mKheDmdjGKMB9MyEJjEDONhWQ8HXN3GKebeZYpPZiZkGruh%2Bz6i4VuHU7pkgnplTwDrUik6YtgR8ORJOGjt8KAadyfMkwhZDjgm%2Fgr68OEBknuzbK4HBi435figc6yBaeUtLgG55wViSbdor3TBne1OdO8nTjw0SIDI6x6%2BWKFZWQVbs%2FbKXNB5rS03Nl4DqIRH3vzvQz4z95yq6KZdaaXUzsDs3TAVONHSmxjSWPKtrqGciknTnb7%2FumVomMy77dRGaX9HDTWnZzYTjUdL0YM7RGnolInkpe7%2F2jpqbvvl%2BcUi%2BrFWdZumQFk3RXLrd%2BJ00e2IPDfw6KlWTwz6mXoZED2o5fvtvxwHgBzergaPU4NkD56TfkpFt7emzY2TSrJXSi9ardj4MC9FBkaCwmtAFvpXhixQODY3%2FZOgd2n7Tjtfw9HNpyA2pYI7ZjIDQljpEpxIFhsRvZkXmGd3DoOm1Y%2FAYUsILoC4%2FJo%2BiDM2MvNOVl70R128RNvNJT%2B34W1asJy7L5bhjYH7bpeMKH42kctz9n1rhE43oTcRdqtMLknG7amKiD6R6FuVpnmdxFsTpFDY0baNyBDjX0UK%2FZTlrPgicMau5T%2FMyTuj2x%2FwxOZNlntT4BZ6AbzrZKazdfVR9%2FjMlRSI7uhgm2kecaZDc0CBGBv7EXR91mGPQSJiA9DcozPKMfJsQ4yccjo%2FyBhphE%2FVwPV0dK%2FysMer50py1zRnNgO5OT2HX6pCUgkRMaiuqWXTtRWb%2BGsELQexgnh4ePd3hiQ0DeBqb3TJD1sS4qpxILmsvQkPFtLzyBVwQKnGcoIIHtm2TEWP2om2fE%2BsX3ebwhP3nzkzeaN408mOsOuZHyTk91PPJi8zoFLTC9hG4089utCY0Oa152m6uaRwbLmqFjd7GNifGltDsuk42k7DsGjc1OOz%2FcaHZs%2BuGG8c3aVC17QIYjD5SyoQiPNx6HfqtxMuhB1X0k7DTZvWN4sloXT5vzw%2BCsdxxBZHjHMRoG7osw8JEfHBMGZKhVOjUMXNMrjh8%2BDpCNHN90DOdFwhmwh2PhWOBXiYYSmJ9TzfO08Vhcr6VkdVxDDAxExKCm6IBD07JYZHRdJHCehwDdqZ1o%2Bwc0bm%2FGrJtFTzeLQ4jdCZdCrBIhSg1JzG24ryGn7FpBSmhAudzmlgHEYDJiyhLwZSJA6dUxU%2F5uDd2u1eJQmUZHoUzprsdRhnbURoHTKeq%2FxTxuzSqf%2BVyqufOGZZn42nproO79VcynerNK4X71uiLZjSuReaQQaQcMKhzo1v4HHRpF%2BXgqAAA%3D&bn=WASP
>     Error: Unknown
>     Details:
> 
>     scriptUrl: https://coriolis.io/import?data=H4sIAAAAAAAEAO1aTXPbNhD9Lzw7HALgp29OnNRu7Sa1POmhk%2BFAJCShJgkOSDlVM%2F3vXYBSRJOgSEk%2B5BAfkhFBPS6wb3ffLvXNYs%2BsqK1L607QVKxr68KarXgJF36TlNfx%2FdPtLVy7F%2Bk6Y5V1%2Bdc367ZmOaw%2F6fX8ifP4SuZiLeOlpClDCiETCrK5DJ8%2FFtZlLdfswvokuZC83liX6MJ6Xyx5wZjkxdK6%2FGa9zdashA%2F17TUs49APiE%2Fci%2F3132nOvsPGV%2BkzLRKWAv4dbCKzLr0L6481zTS8Y0e%2Bq%2B3mC85kY%2Fkdnav7rGu2YPDV3eINo1m9ul9nNS8z%2BAyInyk81LoMAEb9YdiD5GAtzXYr0feVO1ZVt9UvQqTW5YJmFfvvYv%2Bo32CHNU8eWMWrWtm7B3%2BDbQf%2BUA%2F7DXb0iuOOgD%2BumMzN4Mht7At76IA9Avv%2BnzITFX9mRqtR1Bjn9%2B0m20PxTQ%2F48p96xpY8ueITlQmVSzGnm1QIuefNO3X1htbJaoA7uIV0W9TxalMymUqwOK74v8yLk4xWlbtH%2FCCBOsDrRX2t7hqAdSZRMjJQ8sPsOr4TxfKBFks2SMggGiLkPZi7P2IX2Z7ZdwR3naf20PYdHAdb6u3sqYCx7SqP9VmMXHeUDZ%2FEVyavJf26R3RsL%2FAMxPIO2wan9LGseU6zl%2FtFxHNtF2E36HMqDDyzhS%2FopEiwWLMMuPrUpgBpUQCWH2F5KB110DK%2BYNW6LIWsNaDbALay2x3cMWvumEhTpsml4fwGztvD3VNeNOyrzqKnF%2FTp2XwtvuZS82LLTtJiJ1KHPIWbxFd3dpzk9nLKFFoibIekyRZdWuKTaBnayHdDQ0INbM8%2FbF9zQgPsbKKuHzoTMukO9hOTCyHzTo7GpsNEzlRcqFv1A63biHZoCHKbGDb%2F5ULleaBSDvWfZu8XC5YoHlYlSzjNdmTN%2BHJVf2XqX6sdcTcl1H5VMRNaFKKIlzyfw7dylvJ13mK1%2FnxDZVoK4CM6h9qeY8i8fzJawuM%2FPjOZrKBuHNID3qAeoDldMvDRjCWiSPfnCYWYEBSZMie2feSR0BvxVAPdQrSDEGMD5W1%2FrNpfQy2WfL6uRS8dozAypGPkHia9lg80U8qvDeabsPBhKEXDj4sPXLa2GtjECfyIGMLRjzBxwpH9XuW5eJfxcgb5soUaGGImGg%2BZxhGPoBTae%2B1DDSCNhQuHyC5STuUmlmJdpNUrRAs%2BL1rIcdHiTisHh2IFha6PTOn81FjxsfvqkdKP5ZMjBRvMGw0VM61DExeHaD1GRgo7jzMwFnqZrkwqMwodCS1LKWiyqtZc148tAT81i3JztV2fbdenSKZSVeR0f%2FRa6AQ93dQU7v1t55A8MPWH3QfEN1C93tGSJrwtf7xpfDcpF4%2FYSrhEBnKicDQTNUFYtSzaftnz7DBCKAr6AgtNRX1gTWC3FJvtQivc7yVcG01SGQZDQQSGjt%2FfPQ4mKheDmdjGKMB9MyEJjEDONhWQ8HXN3GKebeZYpPZiZkGruh%2Bz6i4VuHU7pkgnplTwDrUik6YtgR8ORJOGjt8KAadyfMkwhZDjgm%2Fgr68OEBknuzbK4HBi435figc6yBaeUtLgG55wViSbdor3TBne1OdO8nTjw0SIDI6x6%2BWKFZWQVbs%2FbKXNB5rS03Nl4DqIRH3vzvQz4z95yq6KZdaaXUzsDs3TAVONHSmxjSWPKtrqGciknTnb7%2FumVomMy77dRGaX9HDTWnZzYTjUdL0YM7RGnolInkpe7%2F2jpqbvvl%2BcUi%2BrFWdZumQFk3RXLrd%2BJ00e2IPDfw6KlWTwz6mXoZED2o5fvtvxwHgBzergaPU4NkD56TfkpFt7emzY2TSrJXSi9ardj4MC9FBkaCwmtAFvpXhixQODY3%2FZOgd2n7Tjtfw9HNpyA2pYI7ZjIDQljpEpxIFhsRvZkXmGd3DoOm1Y%2FAYUsILoC4%2FJo%2BiDM2MvNOVl70R128RNvNJT%2B34W1asJy7L5bhjYH7bpeMKH42kctz9n1rhE43oTcRdqtMLknG7amKiD6R6FuVpnmdxFsTpFDY0baNyBDjX0UK%2FZTlrPgicMau5T%2FMyTuj2x%2FwxOZNlntT4BZ6AbzrZKazdfVR9%2FjMlRSI7uhgm2kecaZDc0CBGBv7EXR91mGPQSJiA9DcozPKMfJsQ4yccjo%2FyBhphE%2FVwPV0dK%2FysMer50py1zRnNgO5OT2HX6pCUgkRMaiuqWXTtRWb%2BGsELQexgnh4ePd3hiQ0DeBqb3TJD1sS4qpxILmsvQkPFtLzyBVwQKnGcoIIHtm2TEWP2om2fE%2BsX3ebwhP3nzkzeaN408mOsOuZHyTk91PPJi8zoFLTC9hG4089utCY0Oa152m6uaRwbLmqFjd7GNifGltDsuk42k7DsGjc1OOz%2FcaHZs%2BuGG8c3aVC17QIYjD5SyoQiPNx6HfqtxMuhB1X0k7DTZvWN4sloXT5vzw%2BCsdxxBZHjHMRoG7osw8JEfHBMGZKhVOjUMXNMrjh8%2BDpCNHN90DOdFwhmwh2PhWOBXiYYSmJ9TzfO08Vhcr6VkdVxDDAxExKCm6IBD07JYZHRdJHCehwDdqZ1o%2Bwc0bm%2FGrJtFTzeLQ4jdCZdCrBIhSg1JzG24ryGn7FpBSmhAudzmlgHEYDJiyhLwZSJA6dUxU%2F5uDd2u1eJQmUZHoUzprsdRhnbURoHTKeq%2FxTxuzSqf%2BVyqufOGZZn42nproO79VcynerNK4X71uiLZjSuReaQQaQcMKhzo1v4HHRpF%2BXgqAAA%3D&bn=WASP
>     line: 1
>     col: 130
>     error: {}

I have reported this to Coriolis team too - issue #633 on Coriolis git Hub

**Comment by robbyxp1** [comment]
Just tried on my EDD, it works, into firefox.

**Comment by robbyxp1** [comment]
Any other info you can provide to help?

**Comment by TonyFlury** [comment]
What more do you need ?

I can copy and past the same URL into the Chrome Browser, so it seems to only be broken with Firefox.

I can assure you it fails consistely trying to export from EDDiscovery to Coriolis on Firefox - why yours works and mine doesn't is a mystery to me - but then I don't really understand what the error actually means -
BTW exports to EDSY work ok using firefox.

**Comment by klightspeed** [comment]
Are you using a plugin to override the user-agent in Firefox?  The error suggests that something is trying to change the user-agent.
Alternatively, searching around, there are some threads out there that point to Firefox profile corruption.

**Comment by robbyxp1** [comment]
Try running firefox in safe mode (hold down shift, click on firefox icon) and see if it then works.  if so, its a plugin or a firefox setting, in which case try resetting it. got to about:support (type it in the address bar)

**Comment by robbyxp1** [comment]
No update from user, presumed solved. No other reports from other users of problems. closing
