### ISSUE TITLE
Error sending EDSM events BadGateway

### ISSUE THREAD

**Issue by ciberloky** [EDDiscovery/EDDiscovery#2990]
since a few days, it gives this error
Error sending EDSM events BadGateway
Error sending EDSM events BadGateway
Sending 6038 journal event(s) to EDSM
Error sending EDSM events BadGateway
Sending 6038 journal event(s) to EDSM
Error sending EDSM events BadGateway
Sending 6038 journal event(s) to EDSM

**Comment by ciberloky** [comment]
answered in discord

**Comment by klightspeed** [comment]
EDSM's migration to a new server did not go to plan, and they will be rolling back to the state immediately before the migration when they move to a second new server.
