### ISSUE TITLE
2 voice packs working at same time at startup and are linked together

### ISSUE THREAD

**Issue by Oldwargoat39** [EDDiscovery/EDDiscovery#2991]
I have installed EDD but the voice pack plays both Spanish and English. I tried to disable the Spanish pack but it still plays and I even selected default as the Language and it still plays.

**Comment by robbyxp1** [comment]
Remove the packs via the Add-On menu and install the English one again.

**Comment by robbyxp1** [comment]
Or you can go into %localappfolder%/EDDiscovery/Actions and delete the pack you don't want.

**Comment by Oldwargoat39** [comment]
thank you,  was trying to find where it was. and fixed

**Comment by robbyxp1** [comment]
Thats good!
