### ISSUE TITLE
TargetShip Event only fires when deselecting ship.

### ISSUE THREAD

**Issue by kylewill0725** [EDDiscovery/EDDiscovery#2993]
I created a basic script to test the UIEvent TargetShip but it only fires when target_locked is false. There is no condition enabled on the event.  
Version: 11.9.3.0

**Comment by robbyxp1** [comment]
else if (newentry.EventTypeID == JournalTypeEnum.ShipTargeted)
            {
                var jst = newentry as JournalEvents.JournalShipTargeted;
                if (jst.TargetLocked == false)
                {
                    uievents.Add(new UIEvents.UIShipTargeted(jst, jst.EventTimeUTC, false));
                    return;
                }
            }

That appears so.  I think the logic is, that normally you want to see the target events in the normal journal log, but the untarget events are not of interest to keep in the journal log so they become UI events.

UI events are transitional - Journal events end up in the log.

If you also subscribe to

EVENT ShipTargeted, ShipTargeted, "", Condition AlwaysTrue

You'll see the other target events.

Cheers Rob

**Comment by robbyxp1** [comment]
closing, hopefully this helps

**Comment by kylewill0725** [comment]
Sorry, thought I replied yesterday. This was perfect thank you.
