### ISSUE TITLE
Crash when loading DLL Action program

### ISSUE THREAD

**Issue by earthfishy** [EDDiscovery/EDDiscovery#2995]
### Description
I'm using an external DLL with v 11.9.3, and whenever I try to create an Action program using their defined commands and dll file, I get this error returned by Windows: 

### Additional Information

![Screenshot_403](https://user-images.githubusercontent.com/62408547/107891215-fb3c6380-6f14-11eb-91de-d24886726f45.png)

![Screenshot_404](https://user-images.githubusercontent.com/62408547/107891216-fbd4fa00-6f14-11eb-9f8f-681a69a5e862.png)

### Exception Details:
>EDDiscovery v11.9.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidCastException: Unable to cast object of type 'EDDiscovery.Actions.ActionDLLCall' to type 'ActionLanguage.ActionCall'.
>   at ActionLanguage.ActionProgramEditForm.Prog_Clicked(Object sender, EventArgs e) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionEditing\ActionProgramEditForm.cs:line 417
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

The dll file in question is for an x52 Pro plugin - listed here: [https://github.com/wulkanat/EDDX52](https://github.com/wulkanat/EDDX52)

I appreciate this is an old plugin & may not work with a newer version of Action Language. I have also reported it to them & they have suggested it might be caused by EDD - they're unsure as to what the error message is describing.

If you need any more info, please ask!

Thanks :)

**Comment by earthfishy** [comment]
Update: This works perfectly fine using EDD v10.1.3, which was the version this plugin was initially released for.

**Comment by robbyxp1** [comment]
Thanks! Bug in the editor.  Ignore the > button for now, except if its a Call.

Thanks for the report.

**Comment by robbyxp1** [comment]
It should not effect the running of the program, just avoid the > button till the next release.
