### ISSUE TITLE
Trilateration window bug.

### ISSUE THREAD

**Issue by Fenlander216** [EDDiscovery/EDDiscovery#2996]
### Exception Details:
>EDDiscovery v11.9.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.Collections.ArrayList.get_Item(Int32 index)
>   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
>   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
>   at EDDiscovery.UserControls.UserControlTrilateration.<>c__DisplayClass24_0.<dataGridViewDistances_CellEndEdit>b__1() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlTrilateration.cs:line 253
>   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>===== END =====
>```

**Comment by robbyxp1** [comment]
Thanks. I will protect against that.
