### ISSUE TITLE
Chemical colours

### ISSUE THREAD

**Issue by Diguelo** [EDDiscovery/EDDiscovery#2998]
Can we have a method to change the colours of the chemical elements display please, the Green is far to dark and a method to change text colours other than themes would be awesome.

**Comment by robbyxp1** [comment]
Please explain further.. chemical display? What is that? what theme are you using, etc.

**Comment by Diguelo** [comment]
Sorry should have explained. For those of us with OLD eyes, certain colours on the screen become smeared, mainly the dark green and black text I find hard to read. A small routine to add either text colours or to change the Periodic table notation colours used in this program would be a bonus. Or an ability to  List the elements available on each planet if the chemical representations are gif/jpg images.  The whole interface is very well laid out and the themes do help in some cases, but having tried all of them I cant find one that fully fits. 

 

I have a policy I use in some programs I have made in the past that seems to be a good method. Colours used RGB, generally I add up the R amount 0 – 256 with G and B this gives me a number between 0 & 795. If the number is less than 265 I use white text over it, 266 – 530 use either black or white and black text up to 795.  Generally this gives a better reading quality. This is of course just my suggestion and I am able to do it for my copy of the program, but I thought it might be an idea to address to complete the aesthetics.

 

Your program is wonderful, helping my searches immensely and saving me game time with letting me know where I have been.

 

Diguelo

**Comment by robbyxp1** [comment]
I'm presuming your having trouble with the green/black material icons here

![image](https://user-images.githubusercontent.com/6573992/108630208-94123800-745b-11eb-9b3b-1f9e6fb5a898.png)


They could be recoloured easily to white.

**Comment by robbyxp1** [comment]
Which i have done.

![image](https://user-images.githubusercontent.com/6573992/108630461-db4cf880-745c-11eb-96e9-88fdb4474c93.png)

**Comment by robbyxp1** [comment]
Also , those icons are dynamically made up inside the code, and I really avoid adding more complexity (more colours) to the theming system as much as possible..  so its just easier to add code to check the back brightness and pick the fore accordingly.

**Comment by Diguelo** [comment]
Hi Rob,

 

Glad to see you got the gist of what I was saying. Yes the white lettering does enable easier reading. This wasn’t a critise at your work, just something that may be easier for us optically challenged to read easier.

 

To be honest I think your complimentary programs for ED and EDH are excellent and add to the whole experience of playing the sim. Im actually thinking of a third monitor so I can have discovery, EDSM and sim open and visible all the time.

 

Ill have a good read of the code out of sheer interest. 

 

One awesome program would be a flasher that says “THIS SERVERS GOING OFFLINE I XX MINUITES” server just cut out half way through a jump so I don’t know if my account is dead. Thanks for the changes if you are adopting them, or just add a check box in settings to activate3 easy reading.

 

Diguelo

**Comment by robbyxp1** [comment]
No problem.  thanks for the heads up
