### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by Tampliera** [EDDiscovery/EDDiscovery#2999]
### Exception Details:
>EDDiscovery v11.9.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
>   в EDDiscovery.UserControls.UserControlExpedition.UpdateSystemRows() в C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlExpedition.cs:строка 180
>   в EDDiscovery.UserControls.UserControlExpedition.dataGridViewRouteSystems_CellValidated(Object sender, DataGridViewCellEventArgs e) в C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlExpedition.cs:строка 1034
>   в System.Windows.Forms.DataGridView.OnCellValidated(DataGridViewCellEventArgs e)
>   в System.Windows.Forms.DataGridView.OnCellValidated(DataGridViewCell& dataGridViewCell, Int32 columnIndex, Int32 rowIndex)
>   в System.Windows.Forms.DataGridView.CommitEdit(DataGridViewCell& dataGridViewCurrentCell, DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave)
>   в System.Windows.Forms.DataGridView.CommitEdit(DataGridViewDataErrorContexts context, Boolean forCurrentCellChange, Boolean forCurrentRowChange)
>   в System.Windows.Forms.DataGridView.OnCellMouseDown(HitTestInfo hti, Boolean isShiftDown, Boolean isControlDown)
>   в System.Windows.Forms.DataGridView.OnCellMouseDown(DataGridViewCellMouseEventArgs e)
>   в System.Windows.Forms.DataGridView.OnMouseDown(MouseEventArgs e)
>   в System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
>   в System.Windows.Forms.Control.WndProc(Message& m)
>   в System.Windows.Forms.DataGridView.WndProc(Message& m)
>   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Found it, thanks.  Fixed in next version, out v.soon
