### ISSUE TITLE
EDSM import (Extended Bubble) taking days to finish

### ISSUE THREAD

**Issue by pdario** [EDDiscovery/EDDiscovery#3000]
Hello!

Each day I start EDDiscovery to let it load EDSM data for extended bubble; now (after about 7hr today) it is at 4.850.000 and counting...
How much am I supposed to wait? Is this regular?
![image](https://user-images.githubusercontent.com/5813131/109025408-fe76e280-76be-11eb-9e00-8911a2894402.png)

**Comment by robbyxp1** [comment]
If your storing it on an HDD, then it will. Are you using an HDD. The database is too big for that type of device now.

**Comment by klightspeed** [comment]
This suggests that the database is on slow storage (e.g. a slow laptop HDD).

Interrupting the build by closing the program will result needing to restart the build from scratch the next time the program is started.

I am currently trialing creating a pre-built database for those with a slow HDD.  The latest build for the Extended Bubble selection is at <https://edgalaxydata.space/eddiscovery/EDDSystem-ExtendedBubble.sqlite> and is 520MB in size and has about 7M systems.  If you want to use this, rename it to `EDDSystem.sqlite` after downloading, and copy it to `%LOCALAPPDATA%\EDDiscovery`.  You will probably also want to disable Star Data Download in the settings tab.

**Comment by pdario** [comment]
I'm using an external HDD, indeed!
I didn't know it starts from scratch every time!

Doesn't it work on new updates only? Do I need to disable Download?

**Comment by robbyxp1** [comment]
Disable star download, on the setting screen.  That will stop it doing the update.

The star database needs an SDD to work now, its over 50 million stars.  

Closing as we have identified the problem.

**Comment by pdario** [comment]
To be honest, on a different PC I put the DB on an HDD and it worked.

**Comment by klightspeed** [comment]
External HDDs are often optimized for sequential access at the expense of random access, and have a higher latency as compared to internal HDDs.
