### ISSUE TITLE
Unhandled UI Exception on EDDiscovery 11.10.1.0 (Windows 10 x64 - Build 20H2)

### ISSUE THREAD

**Issue by jpalsgaardanglin** [EDDiscovery/EDDiscovery#3003]
### Description
Issue occurs on launch of the new release
Note: No issues on the prior release.

### Additional Information
(see attached ZIP journal logs)
I can provide my SQLite file from AppData folder if needed but it is huge.
[Elite Dangerous.zip](https://github.com/EDDiscovery/EDDiscovery/files/6056891/Elite.Dangerous.zip)

### Exception Details:
>EDDiscovery v11.10.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
>   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
>   at System.Collections.Generic.List`1.GetRange(Int32 index, Int32 count)
>   at EDDiscovery.UserControls.TravelHistoryFilter.FilterLatestFirst(List`1 list) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\TravelHistoryFilter.cs:line 148
>   at EDDiscovery.UserControls.UserControlStarList.Display(Boolean disablesorting) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlStarList.cs:line 269
>   at EDDiscovery.UserControls.UserControlStarList.InitialDisplay() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlStarList.cs:line 135
>   at EDDiscovery.MajorTabControl.LoadTabs() in C:\Code\EDDiscovery\EDDiscovery\MajorTabControl.cs:line 106
>   at EDDiscovery.EDDiscoveryForm.EDDiscoveryForm_Load(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 340
>   at System.Windows.Forms.Form.OnLoad(EventArgs e)
>   at System.Windows.Forms.Form.OnCreateControl()
>   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>   at System.Windows.Forms.Control.CreateControl()
>   at System.Windows.Forms.Control.WmShowWindow(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.Form.WmShowWindow(Message& m)
>   at ExtendedControls.SmartSysMenuForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\SmartSysMenuForm.cs:line 221
>   at ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\DraggableForm.cs:line 169
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
Probably need to clamp `MaximumNumberOfItems` to the total number of items in the list.

**Comment by robbyxp1** [comment]
that has been in there a long time

**Comment by robbyxp1** [comment]
11.10.2 is available
