### ISSUE TITLE
Web Browser Tool Prevents Logins

### ISSUE THREAD

**Issue by dylan-k** [EDDiscovery/EDDiscovery#3006]
The built-in browser for sites like Spansh doesn't always permit a login there. In that example, an attempt to login fails and says "Could not connect to the reCAPTCHA service. Please check your internet connection and reload to get a reCAPTCHA challenge." -- probably because the reCAPTCHA site is blocked here.

**Comment by robbyxp1** [comment]
This is by design. Its not supposed to be a general browser, but a method of getting the current system page on the relevant sites to pop up automatically. This is for security reasons. You need to use chrome or firefox to get the full functionality.

**Comment by robbyxp1** [comment]
Okay, changed my mind, to allow through just the sites needed to log in with spansh. EDSM login works too.

**Comment by dylan-k** [comment]
That's great, and it's very good to have it be so specific, and not a general browser. Love the app!
