### ISSUE TITLE
Route generation in an area

### ISSUE THREAD

**Issue by DawnTreader** [EDDiscovery/EDDiscovery#3007]
I clicked the submit feedback so I hope this is the kind of thing I can write here.

On the last CG where there were a bunch of items that they wanted delivered, I was trying to find a way to using the delivery system as center, create a loop or route that would take me to each system so I could fill up my hold with as much as possible before turning it all in. I know there is a route finder and an expedition creator but is it possible to create a system for creating a list of systems that are around a central "starter" or "end" system in a "spherical" map that follows you so you know where you have been and what systems you haven't within the sphere? kind of like a mini galaxy map that you could have overlaid on your screen.

Going to see if I can diagram it or something...

**Comment by robbyxp1** [comment]
I'd look at what Spansh website offers, he does all kinds of routing.
