### ISSUE TITLE
Grid panel loads wrong DB contents

### ISSUE THREAD

**Issue by Eahlstan** [EDDiscovery/EDDiscovery#3008]
If you open a grid panel and place 2 surveyor tabs in it there are two surveyor tab IDs created in the 'Register' table.
![Screenshot 2021-03-02 140046](https://user-images.githubusercontent.com/59618179/109652171-b6910900-7b5f-11eb-83e4-1c8fcf1e0af3.JPG)

If you close EDDiscovery and open it again only the settings of the first surveyor ID are read and applied to both surveyor panels.
The splitter panel works fine using two surveyor panels.

**Comment by robbyxp1** [comment]
Found, thanks for the report. Fixed in .3, prob some time this week.
