### ISSUE TITLE
VoicePack announcing wrong amount of stars and planets when jumping into unexplored systems

### ISSUE THREAD

**Issue by Californ1a** [EDDiscovery/EDDiscovery#3009]
With the edsm "short summary" option enabled in voice pack config, it seems that VoicePack gets the star and planet count directly from edsm and says that amount instead of waiting for your autoscan and then comparing the amounts and using the scanned amounts if it's more than edsm has. Ideally, there would be an option in the voice pack config to wait for manual fss discovery scan and then say the star and planet count only if you do the fss discovery scan, or even wait until "all bodies found". The small edit I've made locally is to change it to say "x stars and y planets *known* in this system" instead of "Total of x stars and y planets in this system" so it's more clear it's edsm data rather than my scan data.

**Comment by robbyxp1** [comment]
Done, thanks
