### ISSUE TITLE
Feature Request: 3D map as ED3D Galaxy Map Plugin

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#301]
There's any chance to render the 3D map with the ED3D Galaxy Map plugin? It's really beautiful and appealing, and also very, very fast and stable. I feel that it could be a great addition, maybe not as the main 3D map, which have special features, but for fast visualization of routes and traveled system.

**Comment by klightspeed** [comment]
Not entirely sure how we'd do this - it's designed to be a plugin for webapps, and EDDiscovery is a desktop application.  One way might be to use a HttpListener, serve up the javascript / html / css / json files, and direct the browser to the port on which the HttpListener is listening.

**Comment by andreaspada** [comment]
> Note that the test at http://en.ed-board.net/3Dedsm_test/ is only 53k stars, and there are now 1.1 million stars.

Maybe is why it's seem so fast... ;)

Well, anyway, it seems that your proposed solution could work well, even if we think it as an additional feature, not a replacement for the already developed 3d map. 
Not sure if I can help in something, but I'll check this.

Cheers

**Comment by klightspeed** [comment]
I guess this would also allow stuff like #155 to be done.

**Comment by robbyxp1** [comment]
Very low priority though.

**Comment by robbyxp1** [comment]
Not going to implement as the project you refer to is dead
