### ISSUE TITLE
Estimated values - add first discovery and first mapping multipliers

### ISSUE THREAD

**Issue by Californ1a** [EDDiscovery/EDDiscovery#3010]
EDSM dashboard shows planets more than about 800k value as you fss scan the system (% is how many planets you've scanned in that system):
![](https://i.imgur.com/gncIT6M.png)
The two checkmarks on the side are adding on the first discovery multiplier and the first mapping multiplier.

In the estimated values EDD panel, it doesn't add these multipliers:
![](https://i.imgur.com/oTIKnBI.png)

It only shows the base estimated value (from [this planet's edsm page](https://www.edsm.net/en/system/bodies/id/63393378/name/Flyiedge+FH-O+b51-4/details/idB/294226919/nameB/Flyiedge+FH-O+b51-4+2)):
![](https://i.imgur.com/GzeDfHq.png)
(though after mapping it, the estimated value changes to the one with the multipliers)

Maybe add one more column with these added if edsm doesn't already have it discovered and mapped. Or since you're already able to hide columns, add 3 more columns (hidden by default) - 1 with first discovery added, 1 with first mapping added, and 1 with both added. It would also be nice to highlight planets over a certain value, and add a comma delimiter so it's easier to read the values.

**Comment by Californ1a** [comment]
It seems planets that already have been discovered and mapped also show different estimated discovery values on edsm compared to edd's estimated values. For example, on edsm:
![](https://i.imgur.com/yDc8n4y.png)
And in edd:
![](https://i.imgur.com/Di6NX4x.png)
And after mapping one of them, edd shows a value much closer to edsm's (and actually higher than edsm sometimes):
![](https://i.imgur.com/1Ywc7L3.png)

**Comment by Californ1a** [comment]
EDD's estimate seems to be *very* far off until after you've already mapped it, which makes the estimate not very useful for figuring out which planets to go do a detailed scan on, whereas esdm's estimate on the dashboard is much closer to the actual value even before mapping it. If possible, I think the value shown after mapping is what should be shown before mapping, so you get an estimated mapping value to be able to determine if the planet is worth going over to do a detailed scan on it or not.

**Comment by robbyxp1** [comment]
Its the standard algorithm, i've checked it.

I'll move this to project items, but i'm not going to change anything about this system or display right now.  I have other items on my plate

thanks for the input.

**Comment by robbyxp1** [comment]
Closing, recorded in project items

**Comment by Californ1a** [comment]
The estimated values panel seems like the right place to put it, but alternatively, an entirely separate panel specifically for "bodies to map" that works similarly to [EDSM's dashboard](https://www.edsm.net/en/dashboard) where it will only show the % of system scanned and any bodies worth mapping (hide bodies under a set value) with their estimated mapping value (+first mapping if it isn't already noted as mapped in EDSM). Right now I keep both the estimated values panel and EDSM's dashboard open, but I could get rid of needing to keep that whole webpage open if there was a panel that provided the same info.

**Comment by robbyxp1** [comment]
I've worked with EDSM and the figures now align. EstimatedValues will be getting more columns
