### ISSUE TITLE
Thargoid wreckage components are treated as wreckage components

### ISSUE THREAD

**Issue by Eahlstan** [EDDiscovery/EDDiscovery#3011]
TWCs are materials, WCs are commodities.

`{ "Name":"tg_wreckagecomponents", "Name_Localised":"Restos de accidentes", "Count":27 }`

**Comment by klightspeed** [comment]
https://github.com/EDDiscovery/EliteDangerousCore/blob/5b608ed3cfc8f74d411f28bdfb0b0ece1e2ed833/EliteDangerous/MaterialsCommodities/MaterialCommodityData.cs#L547

```cs
            AddManu("Wreckage Components", ItemType.Standard, MaterialGroupType.NA, "WRC", "TG_WreckageComponents");
```

It should already be classified as manufactured materials.

**Comment by Eahlstan** [comment]
Well it's not. I got this journal from another player and let my EDD read it. It's definitely treated as the wrong thing. I DMed Robby the journal, I'll DM it to you too :)

**Comment by klightspeed** [comment]
https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/UserControls/CurrentState/UserControlMaterialCommodities.cs#L189

```cs
                    MaterialCommodities m = mcl.List.Find(x => x.Details.Name == mcd.Name);     // and we see if we actually have some at this time
```

It's comparing the name, and not the FDName.

```cs
            AddManu("Wreckage Components", ItemType.Standard, MaterialGroupType.NA, "WRC", "TG_WreckageComponents");
```

```cs
            AddCommodity("Wreckage Components", sv, "WreckageComponents");
```
