### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by CAHAI** [EDDiscovery/EDDiscovery#3013]
### Description
this appeared when I began using the bookmark feature - since then the history/mission doesn't update without ADMIN menu interaction (most times)

### Additional Information
>EDDiscovery v11.10.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentException: Height must be greater than 0px.
>   at System.Windows.Forms.DataVisualization.Charting.ChartPicture.InspectChartDimensions(Int32 width, Int32 height)
>   at System.Windows.Forms.DataVisualization.Charting.ChartPicture.set_Height(Int32 value)
>   at System.Windows.Forms.DataVisualization.Charting.Chart.OnResize(EventArgs e)
>   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
>   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
>   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
>   at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
>   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(Rectangle bounds, BoundsSpecified specified)
>   at System.Windows.Forms.Layout.DefaultLayout.xLayoutDockedControl(IArrangedElement element, Rectangle newElementBounds, Boolean measureOnly, Size& preferredSize, Rectangle& remainingBounds)
>   at System.Windows.Forms.Layout.DefaultLayout.LayoutDockedControls(IArrangedElement container, Boolean measureOnly)
>   at System.Windows.Forms.Layout.DefaultLayout.xLayout(IArrangedElement container, Boolean measureOnly, Size& preferredSize)
>   at System.Windows.Forms.Layout.DefaultLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
>   at System.Windows.Forms.Layout.LayoutEngine.Layout(Object container, LayoutEventArgs layoutEventArgs)
>   at System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
>   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
>   at System.Windows.Forms.Control.ControlCollection.SetChildIndexInternal(Control child, Int32 newIndex)
>   at EDDiscovery.UserControls.UserControlMiningOverlay.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlMiningOverlay.cs:line 512
>   at EDDiscovery.UserControls.UserControlMiningOverlay.Display(HistoryEntry he) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlMiningOverlay.cs:line 165
>===== END =====
>```

**Comment by robbyxp1** [comment]
Try resetting the UI.

https://github.com/EDDiscovery/EDDiscovery/wiki/Safe-Mode

try one of those first three options one by one, then run the program and see if it disappears

**Comment by robbyxp1** [comment]
Closing, presumed solved.
