### ISSUE TITLE
3D local systems map - red dot replication

### ISSUE THREAD

**Issue by clif9710** [EDDiscovery/EDDiscovery#3014]
When I use the 3D local systems map and make any changes to the inner and outer shell, the red dot that indicates the centered system replicates itself to the left and does this repeatedly with each change I make so that I end up with a series of red dots extending to the left of the correct one at center, each one when moused over indicating the same information for what should be the single red dot at center. This has been reproduced by another user.

**Comment by robbyxp1** [comment]
This functionality is deprecated, and going to be removed as soon as the new 3d map is done.

I'm not going to rework this in any way.  Priority for my time needs to be given to features which have a long term future.
