### ISSUE TITLE
3D map issues with fleet carrier docking

### ISSUE THREAD

**Issue by asd1o1** [EDDiscovery/EDDiscovery#3015]
Last summer, I hitched a ride on the DSSA Pilgrim's Harbour on its maiden voyage, at least up till Colonia. Previously, the 3D map showed all my dockings with the carrier in the right systems, along the highway to Colonia. Recently, I had to re-scan all journal files, and my 3D star map now shows all those dockings at the current location of the carrier in Hieronymous Delta.
![Capture](https://user-images.githubusercontent.com/19939445/111398739-43b87f80-8681-11eb-878f-7b389f55af63.JPG)

**Comment by robbyxp1** [comment]
EDD does not know where the carrier currently is.   It has no information on that.  It only knows about your journal data.

Without having access to all the journals, this is impossible to know why its drawing it that way.

**Comment by asd1o1** [comment]
[Journals.zip](https://github.com/EDDiscovery/EDDiscovery/files/6154811/Journals.zip)

Will this be sufficient?

**Comment by robbyxp1** [comment]
Thanks. I'll have a look later.

**Comment by robbyxp1** [comment]
This is my display, with your commander Danielle

![image](https://user-images.githubusercontent.com/6573992/111448611-7fe1f380-8706-11eb-8598-6468288e09f5.png)

This is with 11.10.3, the last released version.

So i'm not sure where that jump is coming from.

**Comment by robbyxp1** [comment]
What system is it that its pointing at incorrectly?

**Comment by asd1o1** [comment]
Bya Chria QY-Y d1-2, the current system the DSSA Pilgrim's Harbour is in.

**Comment by robbyxp1** [comment]
Well, its very strange. Your journals do not mention that system at all. If you search them, Bya Chria is not in them.

I'm stumped as to how your local machine got that.  Can you see the relevant system in your history (search on "Bya Chria" in your history panel)

**Comment by klightspeed** [comment]
Just throwing this out there: do you have Sync From EDSM enabled in the commander settings?

**Comment by asd1o1** [comment]
Haven't had the chance to check my history yet, but I do.

**Comment by asd1o1** [comment]
Bya Chria QY-Y d1-2 is in my jump history...
![Capture](https://user-images.githubusercontent.com/19939445/111521504-72346a00-8716-11eb-8056-69c749a4d98c.JPG)

**Comment by klightspeed** [comment]
Empty information suggests it did not come from your journal.

**Comment by asd1o1** [comment]
I assume so. I have since deleted the jumps from EDSM so it's fixed there. Is there a quick way to remove all EDSM data from EDDiscovery and only have my journals (preferably while keeping my config)?

**Comment by klightspeed** [comment]
Filter by event type: FSD Jump
Filter out by field:
- Event: FSDJump
- Field: JumpDist
- Condition: Is Not Empty

This should display only the entries that have come from EDSM (or from the netlog if you've been playing since before 2017)

You should then be able to select the unwanted entries and hide them.

**Comment by asd1o1** [comment]
Thank you! Everything is good now.
