### ISSUE TITLE
app crashed last night, wont reload

### ISSUE THREAD

**Issue by Dionysymbiant** [EDDiscovery/EDDiscovery#3016]
### Description

was farming pirates in Na Chem system at the nav beacon
### Exception Details:
>EDDiscovery v11.10.2.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   at EDDiscovery.EDDTheme.RestoreSettings() in C:\Code\EDDiscovery\EDDiscovery\Themeing\Theme.cs:line 65
>   at EDDiscovery.EDDiscoveryForm.Init(Action`1 msg) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 189
>   at EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:line 192
>===== END =====
>```

**Comment by robbyxp1** [comment]
Run in safe mode https://github.com/EDDiscovery/EDDiscovery/wiki/Safe-Mode

try resetting the theme.

**Comment by robbyxp1** [comment]
feedback given.
