### ISSUE TITLE
Unhandled Taxi events from Odyssey Alpha

### ISSUE THREAD

**Issue by TonyFlury** [EDDiscovery/EDDiscovery#3025]
The following events are listed as unhandled in the Journal : 

Unhandled Journal event, Report to EDDiscovery team. {"timestamp":"2021-03-31T22:00:17Z","event":"BookTaxi","Cost":100,"DestinationSystem":"Adityan","DestinationLocation":"Konscak Penal colony"}

Unhandled Journal event, Report to EDDiscovery team. {"timestamp":"2021-03-31T19:14:46Z","event":"CancelTaxi","Refund":100}
--

Unhandled Journal event, Report to EDDiscovery team. {"timestamp":"2021-03-31T22:01:06Z","event":"Embark","SRV":false,"Taxi":true,"Multicrew":false}

Unhandled Journal event, Report to EDDiscovery team. {"timestamp":"2021-03-31T22:08:27Z","event":"Disembark","SRV":false,"Taxi":true,"Multicrew":false}
--

I am running 11.10.3.0,

**Comment by TonyFlury** [comment]
There is also probably a 'MissedTaxi' event - but I can't find an example as yet.

**Comment by klightspeed** [comment]
Given that no journal documentation exists yet for Odyssey, all developers are flying blind, and can only go on their own journals and those shared by other developers in the Odyssey alpha.

**Comment by robbyxp1** [comment]
As before,closing.

**Comment by TonyFlury** [comment]
So why bother notifying the developer - I did what was asked - ah well.

**Comment by robbyxp1** [comment]
Thank you for the report. We are awaiting the official journal from Frontier before implementing, as I said in the one of the other tickets that you opened.  We can't implement until we know the details.
