### ISSUE TITLE
Unhandled 'Buy Weapon' event fom Odyssey Alpha

### ISSUE THREAD

**Issue by TonyFlury** [EDDiscovery/EDDiscovery#3029]
EDD 11.10.3.0 reports the following events as unhandled:

Unhandled Journal event, Report to EDDiscovery team. {"timestamp":"2021-03-31T10:24:47Z","event":"BuyWeapon","Name":"Wpn_M_Launcher_Rocket_SAuto","Name_Localised":"Karma L-6","Price":175000}
--

Unhandled Journal event, Report to EDDiscovery team. {"timestamp":"2021-03-31T10:30:33Z","event":"CreateSuitLoadout","LoadoutID":4293000003,"LoadoutName":"Rocket Launcher with Kinetic Side Arm","Modules":[{"SlotName":"PrimaryWeapon1","ModuleName":"wpn_m_launcher_rocket_sauto","ModuleName_Localised":"Karma L-6"},{"SlotName":"SecondaryWeapon","ModuleName":"wpn_s_pistol_kinetic_sauto","ModuleName_Localised":"Karma P-15"}]}
--

Unhandled Journal event, Report to EDDiscovery team. {"timestamp":"2021-03-31T10:31:46Z","event":"SwitchSuitLoadout","LoadoutID":4293000003,"LoadoutName":"Rocket Launcher with Kinetic Side Arm"}
--

There are also (presumably) 'SellWeapon' and 'DeleteSuitLoadout' and possibly 'ModifySuitLoadout' events.

**Comment by robbyxp1** [comment]
Thanks, but we have not had the journal from Frontier yet officially released, so we are not implementing odyssey at this point in time.
