### ISSUE TITLE
Faction panel and mission panel differ

### ISSUE THREAD

**Issue by Eahlstan** [EDDiscovery/EDDiscovery#3032]
Feeding the attached log to EDDiscovery makes the faction panel say that there are 3 active missions. The mission panel correctly states two active missions.
The faction panel doesn't seem to update on the MissionAbandoned event (and I can't confirm this but Jugom says on the MissionFailed event too).

[Journal.210403125512.01.log](https://github.com/EDDiscovery/EDDiscovery/files/6253352/Journal.210403125512.01.log)

**Comment by robbyxp1** [comment]
It will update when the mission list is different, see the code.

which one in the log is causing trouble, there are a lot of missions  in there

**Comment by Eahlstan** [comment]
{ "timestamp":"2021-04-03T19:07:34Z", "event":"MissionAbandoned", "Name":"Mission_Massacre_Skimmer_Expansion_name", "MissionID":746671016 }

That one is correctly marked as abandoned in the mission panel, yet the number of active missions is 3 on the faction panel and 2 on the mission panel.
