### ISSUE TITLE
Non existing bodies from EDSM data

### ISSUE THREAD

**Issue by Scyntrus** [EDDiscovery/EDDiscovery#3035]
I came across this system that listed some non existent bodies from EDSM data.
https://imgur.com/a/lAuKrZ3

The system is BD+33 4395.
I looks like the system name was incorrectly interpreted as bodies.
The estimated values page had a body called .BD+33 4395 BD 33 4395 A 1'.

**Comment by klightspeed** [comment]
`decodeURI('BD+33 4395 A 1') == 'BD 33 4395 A 1'`
It looks like those 3 bodies (`A`, `A 1`, and `B`) were submitted on 10 Aug 2020

**Comment by Scyntrus** [comment]
A, A1, and B are supposed to exist. 'BD 33 4395 A, 'BD 33 4395 A 1', and 'BD 33 4395 B should not.

**Comment by klightspeed** [comment]
Death star deployed - duplicate bodies have been zapped.

**Comment by robbyxp1** [comment]
closing
