### ISSUE TITLE
There was an unhandled UI exception

### ISSUE THREAD

**Issue by b166er** [EDDiscovery/EDDiscovery#3036]
### Description
i was farming Pirates in Arque - Ressource Low.

### Exception Details:
EDDiscovery v11.10.3.0 Error
```
There was an unhandled UI exception.
==== BEGIN ====
System.ArgumentException: Ungültiger Parameter.
   bei System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   bei ExtendedControls.ExtPictureBox.Render(Boolean resizecontrol, Nullable`1 minsize, Nullable`1 margin) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Controls\PictureBox.cs:Zeile 313.
   bei EDDiscovery.UserControls.UserControlSpanel.<Display>d__33.MoveNext() in C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSpanel.cs:Zeile 390.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
===== END =====
```

**Comment by Eahlstan** [comment]
Are you using the german translation?
If yes please try if that happens if you set EDDiscovery to english too.

**Comment by robbyxp1** [comment]
more likely the         Bitmap newrender = new Bitmap(size.Width, size.Height);   // size bitmap to contents

failed, but i can't see why width/height can ever be less than 1 each.

**Comment by robbyxp1** [comment]
It this repeatable? Does it always do it?

**Comment by Eahlstan** [comment]
Just saw that there are some translations used a few lines above line 390 in spanel.cs and you know my translation paranoia :D

**Comment by b166er** [comment]
> Are you using the german translation?
> If yes please try if that happens if you set EDDiscovery to english too.

no, i use Default (English) in EDDiscovery, but yes, my Windows is German. 
maybe it happens because i just started two Elite Dangerous Windows (one from Steam, the other from Epic), but both Games crashed after one hour.


> It this repeatable? Does it always do it?

This was the first time that this happened to me, I have not yet been able to reproduce this error.

**Comment by b166er** [comment]
### Description
tarted two ED-gameclients, after 2 hours playing, again same exception

### Additional Information

### Exception Details:
>EDDiscovery v11.10.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentException: Ungültiger Parameter.
>   bei System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
>   bei ExtendedControls.ExtPictureBox.Render(Boolean resizecontrol, Nullable`1 minsize, Nullable`1 margin) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Controls\PictureBox.cs:Zeile 313.
>   bei EDDiscovery.UserControls.UserControlSpanel.<Display>d__33.MoveNext() in C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSpanel.cs:Zeile 390.
>--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
>   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by Eahlstan** [comment]
Was there any specific action you did in game or out of game when that happened?

**Comment by klightspeed** [comment]
`System.Drawing` uses GdiPlus, which probably uses GPU resources on Windows.

In the Wine and ReactOS versions of the function the `Bitmap` constructor calls (`GdipCreateBitmapFromScan0`), the only way I can see that `InvalidParameter` can be returned is if the width or height are less than or equal to zero.

However, according to <https://social.msdn.microsoft.com/Forums/vstudio/en-US/6f4d1c8f-a9fd-4696-8b89-541b5692f5f6/bitmap-creation-argumentexception-raised-instead-of-out-of-memory?forum=netfxbcl>, `InvalidParameter` can also be returned if GdiPlus runs out of resources.  This could mean that there are a large number of panels that use a picture box to draw their contents (like the scan panel, spanel, etc), and either bitmaps are being leaked or GdiPlus itself has a memory leak.

The fact that the game clients also crashed suggests that the resources are from a shared pool.

Perchance, if you run `winver`, does the version show as `Version 20H2 (OS Build 19042.867)` or `Version 2004 (OS Build 19041.867)`?  See <https://stackoverflow.com/questions/66872343/gdi-memory-leak-when-printing-png24-images-with-gdiplus>, <https://support.microsoft.com/en-us/topic/march-15-2021-kb5001567-os-builds-19041-868-and-19042-868-out-of-band-6e0844a2-7551-4b2d-9c4b-4274a5949bf3>, and <https://support.microsoft.com/en-us/topic/march-18-2021-kb5001649-os-builds-19041-870-and-19042-870-out-of-band-ebbe0617-3a63-467a-aaaa-2a4c68a6de33>

**Comment by b166er** [comment]
> Was there any specific action you did in game or out of game when that happened?

just killing pirates in Low-Res-Site. after two hours one game client are starting to react slowly, my RAM was increased dramatically (one client 6GB, other 1,5GB, EDDiscovery had 1,3GB), then I saw the exception from EDDiscovery, after seconds, the first game client crashed, in next minute the other game client crashed too.

**Comment by robbyxp1** [comment]
I think I shall close this, as its not debuggable.. it sounds like a system wide problem and others are not reporting it.

thanks for the report.
