### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by CMDRmiko0001** [EDDiscovery/EDDiscovery#3037]
### Description
When clicking on "! Faction rewards and trading Tally!" the error occurs. 
After deinstallation of EDDiscovery, registry cleanup, and installing from freshly downloaded 11.10.03 the same error occurs on startup of EDDiscovery.

### Exception Details:
>EDDiscovery v11.10.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Der addierte oder subtrahierte Wert ergibt eine nicht darstellbare DateTime.
>Parametername: months
>   bei System.DateTime.AddMonths(Int32 months)
>   bei EDDiscovery.EDDConfig.ConvertTimeToUTCFromSelected(DateTime t) in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDConfig.cs:Zeile 193.
>   bei EDDiscovery.UserControls.UserControlFactions.Display() in C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlFactions.cs:Zeile 294.
>   bei ExtendedControls.ExtDateTimePicker.Checkbox_CheckedChanged(Object sender, EventArgs e) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Controls\DateTimePicker.cs:Zeile 502.
>   bei System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
>   bei System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
>   bei System.Windows.Forms.CheckBox.set_Checked(Boolean value)
>   bei EDDiscovery.UserControls.UserControlFactions.Init() in C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlFactions.cs:Zeile 204.
>   bei EDDiscovery.PopOutControl.PopOut(PanelIDs selected) in C:\Code\Examples\EDDiscovery\EDDiscovery\PanelAndPopOuts.cs:Zeile 441.
>   bei ExtendedControls.ExtListBoxForm.listcontrol_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Forms\ListBoxForm.cs:Zeile 113.
>   bei ExtendedControls.ExtListBox.OnMouseClick(MouseEventArgs e) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Controls\ListBox.cs:Zeile 366.
>   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   bei System.Windows.Forms.Control.WndProc(Message& m)
>   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
To clear the crash, please hold shift while launching EDDiscovery, and reset Tabs.  Note that when the display time is set to game time, most if not all dates should be entered in game time.

Analysis:

Loading and saving of Faction filter dates do not match up.

https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/UserControls/CurrentState/UserControlFactions.cs#L242-L245
```cs
            PutSetting("StartDate", EDDiscoveryForm.EDDConfig.ConvertTimeToUTCFromSelected(startDateTime.Value));
            PutSetting("StartDateChecked", startDateTime.Checked);
            PutSetting("EndDate", EDDiscoveryForm.EDDConfig.ConvertTimeToUTCFromSelected(endDateTime.Value));
            PutSetting("EndDateChecked", endDateTime.Checked);
```

https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/UserControls/CurrentState/UserControlFactions.cs#L199-L202
```cs
            startDateTime.Value = GetSetting("StartDate", DateTime.UtcNow);
            startDateTime.Checked = GetSetting("StartDateChecked", false);
            endDateTime.Value = GetSetting("EndDate", DateTime.UtcNow);
            endDateTime.Checked = GetSetting("EndDateChecked", false);
            VerifyDates();
```

The date time picker Value Changed event handlers don't check whether the control is still being initialized, so `Display()` is called before `VerifyDates()` is called.
https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/UserControls/CurrentState/UserControlFactions.cs#L470-L478
```cs
        private void startDateTime_ValueChanged(object sender, EventArgs e)
        {
            Display();
        }

        private void endDateTime_ValueChanged(object sender, EventArgs e)
        {
            Display();
        }
```

The date time pickers are also not updated when the display time type is changed.

As a result, when the time display is set to game time while the start date picker have e.g. 10 Apr 2021, and then EDDiscovery is closed and re-opened, 1286 years is subtracted (resulting in 10 Apr 0735) and that is saved to the database.  Then when EDDiscovery is re-opened, the start date picker is set to 10 Apr 0735, and the checkbox is checked, which calls `Display()`, which subtracts 1286 years from that date, resulting in 10 Apr -551, which cannot be displayed (DateTime only handles AD dates).

**Comment by CMDRmiko0001** [comment]
Thank you, that cleared the problem ;)

**Comment by robbyxp1** [comment]
Darn

**Comment by robbyxp1** [comment]
i'll fix it later this weekend, i think its time for 12.0
