### ISSUE TITLE
New install of EDDiscovery flagged as virus

### ISSUE THREAD

**Issue by Cojo96** [EDDiscovery/EDDiscovery#3038]
In trying to install EDDiscovery, the file is being disallowed for "Trojan:Win32/Zpevdo.B" virus. Never had this issue installing EDDiscovery before, after nearly a year of using it.

**Comment by Eahlstan** [comment]
Are you sure it was EDDiscovery and not EDD-EDMC?
There was a faulty definition of Windows Defender today that got already fixed.
Please try the steps mentioned in the screenshot below and see if that fixes your problem.
If not please state which file you downloaded so I can submit another report to Microsoft.
(If you use another anti virus you could contact the manufacturer yourself and report a false positive.)

![Screenshot 2021-04-10 175141](https://user-images.githubusercontent.com/59618179/114276388-b02b6200-9a26-11eb-9542-f023a20f713d.JPG)

**Comment by Cojo96** [comment]
I apologize, it was EDD-EDMC, and the faulty Windows Defender definition. Thank you for clearing that up for me! Solved with the steps you gave me.
