### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by jerky5** [EDDiscovery/EDDiscovery#3039]
### Description

Choosing a date on the diary to see if I can figure out why my local time is wrong in the Captain's Log

### Exception Details:
>EDDiscovery v11.10.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at ExtendedControls.ExtDateTimePicker.Calendar_LostFocus(Object sender, EventArgs e) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Controls\DateTimePicker.cs:line 472
>   at System.Windows.Forms.Control.OnLostFocus(EventArgs e)
>   at System.Windows.Forms.Control.WmKillFocus(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.MonthCalendar.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
calendar.Visible = false;
            this.FindForm().Controls.Remove(calendar);
            Invalidate();

Reproducable - click on calendar, then click on entries, calandar is stranded.

**Comment by robbyxp1** [comment]
Fixed on tip, will be in 12.0. thanks for the report.
