### ISSUE TITLE
Engineered FSD v1

### ISSUE THREAD

**Issue by daniloraisi** [EDDiscovery/EDDiscovery#3041]
Under the Shopping List, Tech Broker Unlocks, we cannot select Human Engineered FSD v1.

**Comment by Eahlstan** [comment]
True that. But to be fair that's a fairly new thing and has to be added manually.

@Robby it's

Frame Shift Drive (Engineered V1)
26 Tellurium
26 Electrochemical Arrays
28 Chemical Processors
18 Datamined Wake Exceptions

**Comment by daniloraisi** [comment]
@Eahlstan and @robby, I created a Pull Request to EDDiscoveryCore with the Human FSD v1.

https://github.com/EDDiscovery/EliteDangerousCore/pull/36

**Comment by robbyxp1** [comment]
incorporated, thanks
