### ISSUE TITLE
Unhandled Exception error when hiding multiple entries

### ISSUE THREAD

**Issue by Ozric42** [EDDiscovery/EDDiscovery#3042]
### Description
When highlighting multiple entries and trying to hide them the program throws an exception error.  It only happens if you select more than one to hide, and it does hide the bottom one of the selection even though it throws the error.

### Exception Details:
>EDDiscovery v11.10.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.Collections.ArrayList.get_Item(Int32 index)
>   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
>   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
>   at ExtendedControls.ExtPanelDataGridViewScrollOutlining.UpdateOutlines() in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Controls\PanelDataGridViewScrollOutlining.cs:line 236
>   at ExtendedControls.ExtPanelDataGridViewScrollOutlining.RowRemoved(Int32 row, Int32 count) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Controls\PanelDataGridViewScrollOutlining.cs:line 384
>   at System.Windows.Forms.DataGridView.OnRowsRemoved(DataGridViewRowsRemovedEventArgs e)
>   at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged_PostNotification(CollectionChangeAction cca, Int32 rowIndex, Int32 rowCount, DataGridViewRow dataGridViewRow, Boolean changeIsDeletion, Boolean changeIsInsertion, Boolean recreateNewRow, Point newCurrentCell)
>   at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged(CollectionChangeEventArgs e, Int32 rowIndex, Int32 rowCount, Boolean changeIsDeletion, Boolean changeIsInsertion, Boolean recreateNewRow, Point newCurrentCell)
>   at System.Windows.Forms.DataGridViewRowCollection.RemoveAtInternal(Int32 index, Boolean force)
>   at EDDiscovery.UserControls.UserControlTravelGrid.hideSystemToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 984
>   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Gotcha, with outlining on..

**Comment by robbyxp1** [comment]
its just a little broke
