### ISSUE TITLE
Regex Sort

### ISSUE THREAD

**Issue by FrankXLT** [EDDiscovery/EDDiscovery#3043]
I know it is important to be able to leave body and system names unmodified for coping, however I was wondering if when sorting alphanumerically you can use some sort of regex such that the following list:

- Hypio Phreia BA-F c28-0 1
- Hypio Phreia BA-F c28-0 10 a
- Hypio Phreia BA-F c28-0 11
- ...
- Hypio Phreia BA-F c28-0 2
- Hypio Phreia BA-F c28-0 3

...

Sorts as:

- Hypio Phreia BA-F c28-0 1
- Hypio Phreia BA-F c28-0 2
- Hypio Phreia BA-F c28-0 3
- ...
- Hypio Phreia BA-F c28-0 10 a
- ...
- Hypio Phreia BA-F c28-0 11
- 

Thanks!

**Comment by Eahlstan** [comment]
![Screenshot 2021-04-16 012851](https://user-images.githubusercontent.com/59618179/114950360-224edd00-9e53-11eb-8d68-1ca6ba17e1fc.JPG)
That's no easy thing to do, maybe it will be done if one of those guys is really really bored in the future :)

**Comment by FrankXLT** [comment]
Understood.  What about showing and sorting on the names that add a 01, 02, 03, however when you double click the field to get the name it shows the unmodified one?  Just a thought.

**Comment by FrankXLT** [comment]
> Understood. What about showing and sorting on the names that add a 01, 02, 03, however when you double click the field to get the name it shows the unmodified one? Just a thought.

Or another thought.  Always display it with the 01, 02, 03, etc, and put a copy system name icon next to each name that copies the unmodified one.

**Comment by robbyxp1** [comment]
Its an idea, but its not going to be implemented for the forseeable future - we have alpha to code for.  I've added this to the list of ideas.

thanks for the idea.
