### ISSUE TITLE
UI Exception while loading

### ISSUE THREAD

**Issue by gbuxton** [EDDiscovery/EDDiscovery#3045]
The following is from the information sent to the clipboard when I chose to report the issue from the exception dialog.
My comments on the crash itself are in the Additional Information, as well as information that may help to find the cause of the crash based on a test I did. 
[EDDiscovery_crash_report_20210415.txt](https://github.com/EDDiscovery/EDDiscovery/files/6322576/EDDiscovery_crash_report_20210415.txt)

**Comment by robbyxp1** [comment]
This is prob one of those random windows UI things - the error is deep within windows framework, and will probably not reproduce.

Is it working okay now?

**Comment by gbuxton** [comment]
Today, April 18, I had the same problem.  I had reverted back to the latest EUROCAPS.TTF as mentioned in my previous report.  In two attempts to start, the same error appears.  I swapped to the earlier version of the EUROCAPS.TTF and it started as intended.
The application window, size, position, and monitor that it is displayed on have not changed, at least across the previous version and into the latest 11.10.3.0 update.  I rarely move it now that I have found the "best place" for it in my use.
I will do some more font date swaps and start-close cycles as I get time today or over the next few days, to see if I can re-create the problem consistently enough to say whether I think that it is the eurocaps that may be the problem.  Right now, swapping back to the "new" file EDD starts and closes (four times) fine.  Windows 10 v. 20H2 if I didn't mention that before.
A new thought I will also look for, when a new (or not played for some time) game starts now and then it will set resolution to less than my main monitor 2160p (4k).  That causes other windows whether minimized or displayed to move around, mostly to my second monitor which is 1080p.  I have not seen any effects that I recall as far as the third monitor (also 1080p) and typically EDD would not be running when those games are since it is not needed for that game.  Perhaps that shift causes Windows to "do something" that affects the way it handles the GUI elements involved in the crash when I start EDD sometime after that type of occurrence.  I would have to check after such an occurrence, so in that I don't know when that might come up again.
For certain, that situation does cause all of the windows that got moved to monitor 2 to resize in a way that they for the most part do not revert to the size they are on monitor 1 (the 4k) and I have to stop and restart some of the applications in order to get them back "the way they ought to be."
If you are willing to give it a couple of weeks or so, until I trip into the resolution change thing, I'm happy to try to give a useful report that would either confirm Windows quirkiness or something that could be tweaked in EDD to fix or at least tolerate the Windows quirks.

**Comment by klightspeed** [comment]
This seems to be the same issue as the OP had in <https://github.com/EDDiscovery/EDDiscovery/issues/2832> - the OP on that issue never got back to us about whether the hash on the font file matched - note that the font has not been changed in our repository since 2016 (though it has moved around), when it was first added to the installer.

**Comment by robbyxp1** [comment]
Its an interaction with windows, which is outside of the remit for us to fix.  Try another theme and see if it works.  thanks for the report.
