### ISSUE TITLE
found a system which is not correctly displayed

### ISSUE THREAD

**Issue by DeepstarOne** [EDDiscovery/EDDiscovery#3047]
Hi,
I've found a system, which is not correctly displayed in EDDiscovery (see attached images and relevant part of log-file). The icy asteroid field is missing. In the scan grid it is listed correctly. 

![Pho Aoscs GY-G c24-1_EDDiscovery](https://user-images.githubusercontent.com/25210660/115042988-4bfc1880-9ed4-11eb-9686-38f02d9a5f5a.png)
![Pho Aoscs_GY-G c24-1_Elite_1](https://user-images.githubusercontent.com/25210660/115043009-528a9000-9ed4-11eb-933a-19d5404f9d0a.png)
![Pho Aoscs_GY-G c24-1_Elite_2](https://user-images.githubusercontent.com/25210660/115043227-91204a80-9ed4-11eb-88e3-ca7350df90de.png)
![Pho Aoscs_GY-G c24-1_Elite_5](https://user-images.githubusercontent.com/25210660/115045527-e0677a80-9ed6-11eb-8c60-d9f6dfa61ae9.png)
[Pho Aoscs_GY-G c24-1_Log_Elite.zip](https://github.com/EDDiscovery/EDDiscovery/files/6326037/Pho.Aoscs_GY-G.c24-1_Log_Elite.zip)

**Comment by klightspeed** [comment]
Barycentres are not scannable, so their rings are not detected.  As a result, the inner and outer radii of the belt (which are used to place the belt in the scan panel) are unknown.

**Comment by robbyxp1** [comment]
We have pointed that out to Frontier, no change.  thanks for the report.
