### ISSUE TITLE
EDDiscovery 4.1.1.0 Hangs when "Updating from EDSM, received 65438 systems, updated 20886"

### ISSUE THREAD

**Issue by BlueDrache** [EDDiscovery/EDDiscovery#305]
I've already updated everything once, and it keeps doing this when I restart the program.  It gets to a certain point and then just hangs.

**Comment by klightspeed** [comment]
We need to add better feedback when importing the 1.3M systems (and counting) from EDSM.

**Comment by BlueDrache** [comment]
That's not it at all, it flat out hangs.  On separate occasions, I've left it alone for 15 minutes to finish and it never moves from that point.  My computer slows to a crawl.  When I close/kill the EDD process, my computer returns to normal.

**Comment by klightspeed** [comment]
What version did you upgrade from?

Also, do you have `Use distances` checked in the settings?

The point at which you say it's stalling suggests that it is occurring while importing EDSM systems.

If you upgraded from 3.x, EDDiscovery needed to re-sync all of the systems in order to populate the EDSM ID.

Please post a screenshot of at least the message area of the window.

**Comment by DeltaW7** [comment]
I have the same problem

Also there is no " use distances" option in the settings, the only option mentioning distances is "get distance pairs from edsm" (mine is not checked
below is the screenshot after 20 mins

And the question is why does it need to re-sync all of the systems every time you open the program

![clipboard01](https://cloud.githubusercontent.com/assets/17954905/17306005/e9adcdaa-582d-11e6-9053-24db9c7ee96f.jpg)

**Comment by BlueDrache** [comment]
4.1.1.0 has really screwed the pooch on this one, IMO.  I can't run anything ... and now my personal database that I've collected for over a year is gone.  Good job.

**Comment by klightspeed** [comment]
Please try going back to 3.2.5 until such time as we have the long startup issue sorted out.

**Comment by klightspeed** [comment]
This should be resolved in the next release.

**Comment by robbyxp1** [comment]
Closed, old issue
