### ISSUE TITLE
Error in German Translation with Captains Log Panel causing Crash

### ISSUE THREAD

**Issue by ectol** [EDDiscovery/EDDiscovery#3050]
### Exception Details:
>EDDiscovery v12.0.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
>   bei EDDiscovery.UserControls.CaptainsLogDiary.LoadLayout() in C:\Code\EDDiscovery\EDDiscovery\UserControls\LogsBookmarks\CaptainsLogDiary.cs:Zeile 58.
>   bei EDDiscovery.UserControls.UserControlCaptainsLog.<Init>b__5_1(TabStrip tab, Control ctrl, Int32 si) in C:\Code\EDDiscovery\EDDiscovery\UserControls\LogsBookmarks\UserControlCaptainsLog.cs:Zeile 56.
>   bei ExtendedControls.TabStrip.PostCreate() in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\TabStrip.cs:Zeile 198.
>   bei ExtendedControls.TabStrip.ChangePanel(Int32 i) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\TabStrip.cs:Zeile 130.
>   bei EDDiscovery.MajorTabControl.LoadTabs() in C:\Code\EDDiscovery\EDDiscovery\MajorTabControl.cs:Zeile 106.
>   bei EDDiscovery.EDDiscoveryForm.EDDiscoveryForm_Load(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:Zeile 344.
>   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
>   bei System.Windows.Forms.Form.OnCreateControl()
>   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>   bei System.Windows.Forms.Control.CreateControl()
>   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
>   bei System.Windows.Forms.Control.WndProc(Message& m)
>   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
>   bei ExtendedControls.SmartSysMenuForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\SmartSysMenuForm.cs:Zeile 221.
>   bei ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\DraggableForm.cs:Zeile 169.
>   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Is this repeating? It may just be a bad start..

**Comment by robbyxp1** [comment]
Have you selected a language to use which is not english?

**Comment by robbyxp1** [comment]
Your probably using German

**Comment by Eahlstan** [comment]
I'm really sorry it's my fault I skipped pressing shift and entered , instead of ;

**Comment by robbyxp1** [comment]
Please just temp stop using German or don't use captains log diary until we fix it - in 12.0.1 which will probably be out by thursday.  Thanks for the report.

**Comment by Eahlstan** [comment]
You can download a fixed version of the faulty file here: https://drive.google.com/file/d/1kX1_BArFqDMS17exiup9DjWJpd7gFGN4/view?usp=sharing

Replace your existing one with that to fix it.

**Comment by robbyxp1** [comment]
Fix 12.0.1
