### ISSUE TITLE
EDDiscovery lacks on its primary word "Discovery"

### ISSUE THREAD

**Issue by the-insulter** [EDDiscovery/EDDiscovery#3053]
and that's sadly, because for the new Quest to find the sister Generation ship is is absolutely of no use, though I like it for some of the tools you implemented.

Although there is no tools to do that, I hoped EDD would make that, but am sadly disappointed.

The tools needs to:
1. Search all Stars named Taurus and their class
2. Filter option to only show the G classes
3. List them
4. make a route from your start point
5. Check off which you have been visited
6. save from the last point to continue

I think you have all the tools and code there in this nice program, but they are not sorted like the way which an explorer needs it.

Can you make that tool?

In ED there is only the option to show the class but no other filtering and checking off system.

Regards

**Comment by robbyxp1** [comment]
The answer is no, I can't.  We don't have that info available. Use EDSM/Spansh etc.
