### ISSUE TITLE
Suggestion for 3D-Map (Bookmark-import from Excel)

### ISSUE THREAD

**Issue by kochmich** [EDDiscovery/EDDiscovery#3054]
Dear Sir.
You are doing an amazing job! Thank you for your fantastic software.
I have a suggestion about the 3-D map that I believe would delight many fellow Explorers:

It would be great if I could import my own bookmarks from an Excel spreadsheet into the 3D map. I have a database of different forms of life and sights with hundreds and thousands of xyz coordinates. I would like to import these and also share them with colleagues. It would be great if you could e.g. exchange interesting locations or collections of lists you created yourself in this way.
The imported bookmarks should only contain:
x / y / z description (and symbol number for the display)
It would be good if several bookmark lists were parallel available in the 3D map.

With this expansion in the 3D map, the research community would have a powerful upgrade.

Thank you for your efforts and I wish you a good day,
with best Regards

CMDR Dr. James Thaddeus Latenoid

**Comment by robbyxp1** [comment]
Thanks.   i'll add it to the list of projects ideas.  Note the current 3dmap is depreciated, a new one is going to replace it.
