### ISSUE TITLE
unhandled UI exception

### ISSUE THREAD

**Issue by Shinji-Yamazaki** [EDDiscovery/EDDiscovery#3056]
There was an unhandled UI exception.

==== BEGIN ====
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei EDDiscovery.UserControls.CaptainsLogDiary.LoadLayout() in C:\Code\EDDiscovery\EDDiscovery\UserControls\LogsBookmarks\CaptainsLogDiary.cs:Zeile 58.
   bei EDDiscovery.UserControls.UserControlCaptainsLog.<Init>b__5_1(TabStrip tab, Control ctrl, Int32 si) in C:\Code\EDDiscovery\EDDiscovery\UserControls\LogsBookmarks\UserControlCaptainsLog.cs:Zeile 56.
   bei ExtendedControls.TabStrip.PostCreate() in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\TabStrip.cs:Zeile 198.
   bei ExtendedControls.TabStrip.ChangePanel(Int32 i) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\TabStrip.cs:Zeile 130.
   bei EDDiscovery.MajorTabControl.LoadTabs() in C:\Code\EDDiscovery\EDDiscovery\MajorTabControl.cs:Zeile 106.
   bei EDDiscovery.EDDiscoveryForm.EDDiscoveryForm_Load(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:Zeile 344.
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei ExtendedControls.SmartSysMenuForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\SmartSysMenuForm.cs:Zeile 221.
   bei ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\DraggableForm.cs:Zeile 169.
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====

**Comment by Eahlstan** [comment]
https://github.com/EDDiscovery/EDDiscovery/issues/3050

Please see that issue.

**Comment by robbyxp1** [comment]
Closing, leave the other one open until next release.
