### ISSUE TITLE
IE is causing Edge to open. Use the system default browser instead.

### ISSUE THREAD

**Issue by DawnTreader** [EDDiscovery/EDDiscovery#3057]
I clicked the spot in the intro video to view the video on youtube and it tried opening IE, windows caught it and opened edge. I use and have set as default Chrome and despise IE and Edge. IE is a very old browser and very insecure. Edge is pure garbage. Please make the intro video use the system default set browser.

**Comment by robbyxp1** [comment]
Can't.  Not possible to do this at the moment. We are aware of the issue but the embedded web player is fixed and not configurable.

**Comment by klightspeed** [comment]
The only way we would be able to do this is to put a link under the Youtube panel in the about window.  The Youtube panel uses the WebBrowser control, which uses the Internet Explorer renderer.

@robbyxp1 it appears you want to have the Youtube panel load html, not do a simple Navigate, when embedding a Youtube video.  See <https://stackoverflow.com/questions/49047715/c-sharp-embed-youtube-videos-in-your-winforms> and <https://www.c-sharpcorner.com/blogs/play-youtube-videos-in-desktop-application-using-c-sharp>
