### ISSUE TITLE
The screenshot converter can be set to an endless conversion.

### ISSUE THREAD

**Issue by Eahlstan** [EDDiscovery/EDDiscovery#3060]
If you set it to scan for file extension 'a' and save it as file extension 'a' in the same folder the converter picks up every converted image as a new one.
Solution: Make it impossible to set scan and save extension as the same, or make it impossible to save the converted image to the same folder as the original.

//This issue was brought to you by a direct command of Robby
![Screenshot 2021-04-28 230128](https://user-images.githubusercontent.com/59618179/116473064-04cc3b00-a877-11eb-8ce6-583a56a8f95f.JPG)

**Comment by robbyxp1** [comment]
Fixed so user can't set up this situation in the configuration form in 12.0.2, thanks
