### ISSUE TITLE
Feature Request: manual  defined filters as preset in History TAB

### ISSUE THREAD

**Issue by Ischtaratu** [EDDiscovery/EDDiscovery#3061]
On the history page it is possible to filter the entries. There are predefined categories (travel, trade, exploration, etc.) as well as individually selectable criteria (e.g. hyperspace jump, purchase and so on).

Is it possible to define additional manual filter criteria as presets to select them faster, similar to the predefined categories, instead of having to work through the complete list each time?

I use different ships for various activities and with Odyssey more will be added. A few additional filter sets could really help to keep the overview.

Nothing against the predefined sets, but for me personally this is still too much (unnecessary) information. Less is more.

**Comment by Eahlstan** [comment]
Wouldn't it be easier to set up profile triggers that activate when changing ships to get what you want?

https://github.com/EDDiscovery/EDDiscovery/wiki/Profiles

**Comment by Ischtaratu** [comment]
yes, sure ... but can i aktivate a trigger manualy too ?

**Comment by Eahlstan** [comment]
You can manually change the profile whenever you want to. It's the drop down menu next to the drop down menu containing your commanders.

**Comment by robbyxp1** [comment]
Thats a lot of new UI, which i'm not going to consider to do.  We have a backlog of stuff to do, Odyssey being the largest. And I've not had others asking for it.

**Comment by robbyxp1** [comment]
I will add the idea to the project list, but i doubt it will be implemented soon. thanks
