### ISSUE TITLE
All translations cause splitter/grid problems

### ISSUE THREAD

**Issue by Eahlstan** [EDDiscovery/EDDiscovery#3062]
If any translation is used the drop down menu in the splitter and grid panels insert the wrong panels.
Also if you use any translation a UI exception pops up if you try to add the 2D map in a splitter or grid panel - but not if you open the 2D map as a seperate panel.

The first problem is linked to the sorting used on the PopOutInfo section in the .tlf files, if this section is completely deleted the drop down menu inserts exactly what it should (although the menu itself is now no longer translated).

The second problem causes:

>EDDiscovery v12.0.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.FormatException: No se puede reconocer la cadena como valor DateTime válido.
>   en System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
>   en System.Windows.Forms.DateTimePicker.set_Text(String value)
>   en BaseUtils.Translator.Translate(Control ctrl, String subname, Control[] ignorelist, Boolean debugit) en C:\Code\Examples\EDDiscovery\BaseUtilities\BaseUtilities\Translator\Translator.cs:línea 386
>   en BaseUtils.Translator.Translate(Control ctrl, String subname, Control[] ignorelist, Boolean debugit) en C:\Code\Examples\EDDiscovery\BaseUtilities\BaseUtilities\Translator\Translator.cs:línea 399
>   en BaseUtils.Translator.Translate(Control ctrl, String subname, Control[] ignorelist, Boolean debugit) en C:\Code\Examples\EDDiscovery\BaseUtilities\BaseUtilities\Translator\Translator.cs:línea 399
>   en BaseUtils.Translator.Translate(Control ctrl, String subname, Control[] ignorelist, Boolean debugit) en C:\Code\Examples\EDDiscovery\BaseUtilities\BaseUtilities\Translator\Translator.cs:línea 399
>   en BaseUtils.Translator.Translate(Control ctrl, String subname, Control[] ignorelist, Boolean debugit) en C:\Code\Examples\EDDiscovery\BaseUtilities\BaseUtilities\Translator\Translator.cs:línea 399
>   en BaseUtils.Translator.Translate(Control ctrl, Control[] ignorelist) en C:\Code\Examples\EDDiscovery\BaseUtilities\BaseUtilities\Translator\Translator.cs:línea 364
>   en EDDiscovery.UserControls.UserControl2DMap.Init() en C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControl2DMap.cs:línea 95
>   en EDDiscovery.UserControls.UserControlContainerGrid.CreateInitPanel(UserControlCommonBase uccb) en C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\GridsSplitters\UserControlContainerGrid.cs:línea 219
>   en EDDiscovery.UserControls.UserControlContainerGrid.<>c__DisplayClass27_0.<buttonExtPopOut_Click>b__0(Object s, EventArgs ea) en C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\GridsSplitters\UserControlContainerGrid.cs:línea 349
>   en ExtendedControls.ExtListBoxForm.listcontrol_SelectedIndexChanged(Object sender, EventArgs e) en C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Forms\ListBoxForm.cs:línea 113
>   en ExtendedControls.ExtListBox.OnMouseClick(MouseEventArgs e) en C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Controls\ListBox.cs:línea 366
>   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   en System.Windows.Forms.Control.WndProc(Message& m)
>   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====

**Comment by robbyxp1** [comment]
Okay, will investigate.  rob

**Comment by robbyxp1** [comment]
Found them, thanks. next version today.
