### ISSUE TITLE
[feedback] youtube video on new release is cool but on autoplay mode is not

### ISSUE THREAD

**Issue by lx-dev-pm** [EDDiscovery/EDDiscovery#3064]
Simple feedback from a user.

It's nice to create a video for a new release.

But leaving it on "autoplay" can be very annoying (especially if the window is being the game or something else).

**Comment by robbyxp1** [comment]
I'm trying to make sure people know the videos exist and that they at least look at them.  The number of questions I get we get which would be solved by the user looking at a video or the wiki means that promoting them is a must.

They should stop if you hit return/close the window.  We have had reports of them not doing that, and are looking into it.

They won't play on second run.

thanks

**Comment by robbyxp1** [comment]
I think i'll change the logic to make it a little less aggressive, not popping up on a 0.0.X change.

**Comment by lx-dev-pm** [comment]
yeah...

Again, I think the video is a very good idea, if you let the user choose to play it him-self.

**Comment by imathrowback** [comment]
Not that anyone cares, but I strongly disagree @robbyxp1 

No problem with the video being there. But autoplay is a terrible idea. This should be a toggle option to never play **automatically** again regardless of "new features" and by default should be disabled.

- https://websitestrategies.com.au/why-having-videos-autoplay-on-your-website-is-a-bad-idea/
- http://www.punkchip.com/autoplay-is-bad-for-all-users/
- https://www.advisorwebsites.com/blog/blog/general/hate-videos-autoplay
- https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-dis-audio.html

And I could keep listing items until I run out of space in this box.
