### ISSUE TITLE
EDSM/EDDB/Inara inaccessible

### ISSUE THREAD

**Issue by sdfg2** [EDDiscovery/EDDiscovery#3066]
Viewing EDSM, EDDB or Inara gives 

`Content was blocked because it was not signed by a valid security certificate.`

Spansh works correctly, and EDSM, EDDB and Inara work in a normal browser.

**Comment by klightspeed** [comment]
Is the time on your computer correct?

All 4 sites use sha256rsa certificates from LetsEncrypt, and the only difference is their expiry date - the Spansh certificate was renewed 1 day ago and has an expiry date of 01 August 2021, while the others have certificates that were renewed between 1 and 7 weeks ago and have expiry dates between 14 June and 24 July.

**Comment by sdfg2** [comment]
If the time on my computer was incorrect, it wouldn't work in a normal browser.  That's why I deliberately put that information in there.

**Comment by klightspeed** [comment]
Do the sites load in Internet Explorer?

Do you have some sort of internet security suite that does a man-in-the-middle on your https traffic?

**Comment by sdfg2** [comment]
Again, none of this is relevant because it works in a normal browser on the same machine using the same pathways to the servers.

**Comment by klightspeed** [comment]
If you look at the certificate, on EDSM, EDDB, and/or Inara, what do they say their issuer is?
What OS are you running on?

**Comment by robbyxp1** [comment]
I'm afraid your alone in reporting this, so its something up with your machine. If you give us more fuller information, we will try and help you debug it.  Otherwise i'll just close down the ticket.

So again, does the sites load in Internet explorer (not your chosen browser). Since EDD uses that, it may be that internet explorer has logged that the site has an invalid certificate, and you may need to reset IE by adding inara etc to its trusted site list.

**Comment by robbyxp1** [comment]
Closing, no response.

**Comment by sdfg2** [comment]
EDSM issuer: edsm.net
Inara issuer: www.inara.cz
EDDB issuer: eddb.io

Windows 10, latest update.

All of them work in Internet Explorer.

**Comment by klightspeed** [comment]
> EDSM issuer: edsm.net
> Inara issuer: [www.inara.cz](http://www.inara.cz)
> EDDB issuer: eddb.io

So you're saying they're self-signed certificates?

**Comment by sdfg2** [comment]
> > EDSM issuer: edsm.net
> > Inara issuer: [www.inara.cz](http://www.inara.cz)
> > EDDB issuer: eddb.io
> 
> So you're saying they're self-signed certificates?

No, I hadn't had my first cup of tea of the day before writing that, sorry!

They are all Let's Encrypt certificates so they are issued BY R3 TO the domains.  (You'd think with a networking degree even before coffee I'd have noticed that lol)

**Comment by klightspeed** [comment]
Would it please be possible to get a screenshot of the error you are getting?

**Comment by sdfg2** [comment]
> Would it please be possible to get a screenshot of the error you are getting?

![image](https://user-images.githubusercontent.com/5736478/117442734-11aff500-af2f-11eb-93de-2471c4e8d0d4.png)

**Comment by klightspeed** [comment]
If you right-click in the white area, is Properties included in the right-click menu?  If so, please click Properties, then click on Certificates.

**Comment by klightspeed** [comment]
Please try using Wireshark to capture the TLS connection between EDDiscovery and EDSM (using capture filter `ip host edsm.net and tcp port 443`), or EDDB or Inara (replacing `edsm.net` with `eddb.io` or `inara.cz`)

In the TLS session there should be a frame with `Certificate` info, which Wireshark should automatically reassemble in the packet details panel.

A good certificate should look like:
![image](https://user-images.githubusercontent.com/147116/117449714-a17f8e80-af83-11eb-970a-a0e7f35861a2.png)

A bad certificate might look like:
![image](https://user-images.githubusercontent.com/147116/117449788-b6f4b880-af83-11eb-9055-42b002868bd0.png)

**Comment by sdfg2** [comment]
Yup, certificate is fine.  I also checked the certificate for the EDSM star update, perfectly fine certificate. (Checked separately as I imagine they use different means)

**Comment by klightspeed** [comment]
One thing Spansh does that EDSM, EDDB, and Inara do not do is that it includes the OCSP result.

Seeing that, I was able to replicate it by denying __all__ outgoing tcp port 80 connections (i.e. http), so that the Internet Explorer component could not fetch any certificate revocation lists.

Do you have an firewall that blocks or messes with outgoing HTTP connections?

**Comment by sdfg2** [comment]
Yes I have a firewall, no it doesn't touch port 80 outgoing.

**Comment by klightspeed** [comment]
Internet Explorer uses its own certificate status server when it is unable to contact the OCSP / CRL servers listed in the certificate, and Chrome (and presumably Edge) unconditionally use their own certificate status servers and do not directly query the OCSP or CRL servers.

ieframe.dll (used by the WebBrowser control) has no fallback mechanism when OCSP and CRL queries fail, and by default will not continue with the TLS handshake if it is unable to query the OCSP or CRL servers.

Does `%USERPROFILE%\AppData\LocalLow\Microsoft\CryptnetUrlCache\Content\96462A1867D57AF0D537331DC8253E9F` exist?  If not, this is a sure sign that OCSP queries are failing (this is the cache file for the OCSP query for the current EDSM certificate)

**Comment by sdfg2** [comment]
Loads of files in there, but not that one specifically.

**Comment by klightspeed** [comment]
>> Does %USERPROFILE%\AppData\LocalLow\Microsoft\CryptnetUrlCache\Content\96462A1867D57AF0D537331DC8253E9F exist? If not, this is a sure sign that OCSP queries are failing (this is the cache file for the OCSP query for the current EDSM certificate)
> Loads of files in there, but not that one specifically.

If you want to fix this, you are going to need to put on your troubleshooting hat and figure out _why_ that is the case.  Use the tools available to you (e.g. Process Monitor and Wireshark).

**Comment by robbyxp1** [comment]
So, this is not a problem with EDD. So i'm going to close this.  You can continue discussing this if you want to.
