### ISSUE TITLE
UI Exception

### ISSUE THREAD

**Issue by SuperDuperTed** [EDDiscovery/EDDiscovery#3067]
### Exception Details:
>EDDiscovery v12.0.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.EDSM.EDSMJournalSync.GetListToSend(List`1 helist) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\EDSM\EDSMJournalSync.cs:line 53
>   at EDDiscovery.EDDiscoveryForm.EDSMSend() in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryFormHelpers.cs:line 107
>   at EDDiscovery.EDDiscoveryForm.Controller_RefreshComplete() in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryFormJournalEvents.cs:line 75
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshCompleteonUI(HistoryList hist) in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 259
>===== END =====
>```

**Comment by Eahlstan** [comment]
A little more information of what you did when this occured would be extremely usefull...

**Comment by klightspeed** [comment]
The exception seems to suggest that the history entry's commander is null, which could happen if the history is from the `Hidden` commander or from a commander that was just deleted.

This suggests:
- The hidden commander was active
- While the history was being read from the files or loaded from the database, the commander was changed
or
- A commander you didn't want any more was active
- While the history was being read from the files or loaded from the database, the commander was deleted
