### ISSUE TITLE
3dMap window does not use the theme

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#307]
Would be nice for the 3dMap window to use the same theme as the main program window.

**Comment by robbyxp1** [comment]
I don't want to do this..  Very little of the window shows, only the toolbar.  There is no real point themeing that.

**Comment by robbyxp1** [comment]
Close, not going to theme it, not worth it for just the toolbar, and the themeing of the toolbar is not perfect
