### ISSUE TITLE
UI exception

### ISSUE THREAD

**Issue by GhostPLKR** [EDDiscovery/EDDiscovery#3072]
### Exception Details:
>EDDiscovery v12.0.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.TypeInitializationException: Inicjator typów zgłosił wyjątek dla typu 'EliteDangerousCore.Recipes'. ---> System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
>   w System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
>   w EliteDangerousCore.MaterialCommodityData.SetCache() w C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\MaterialsCommodities\MaterialCommodityData.cs:wiersz 264
>   w EliteDangerousCore.MaterialCommodityData.FillTable() w C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\MaterialsCommodities\MaterialCommodityData.cs:wiersz 380
>   w EliteDangerousCore.MaterialCommodityData.GetByShortName(String shortname) w C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\MaterialsCommodities\MaterialCommodityData.cs:wiersz 130
>   w EliteDangerousCore.Recipes.Recipe..ctor(String n, String ingredientsstring) w C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\MaterialsCommodities\MaterialRecipesData.cs:wiersz 44
>   w EliteDangerousCore.Recipes.SynthesisRecipe..ctor(String n, String l, String indg) w C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\MaterialsCommodities\MaterialRecipesData.cs:wiersz 81
>   w EliteDangerousCore.Recipes..cctor() w C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\MaterialsCommodities\MaterialRecipesData.cs:wiersz 171
>   --- Koniec śladu stosu wyjątków wewnętrznych ---
>   w EliteDangerousCore.Recipes.UsedInEngineeringByFDName(String fdname, String join) w C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\MaterialsCommodities\MaterialRecipesData.cs:wiersz 142
>   w EliteDangerousCore.Recipes.UsedInRecipesByFDName(String fdname, String join) w C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\MaterialsCommodities\MaterialRecipesData.cs:wiersz 122
>   w EDDiscovery.UserControls.UserControlMaterialCommodities.Display(MaterialCommoditiesList mcl) w C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlMaterialCommodities.cs:wiersz 192
>   w EDDiscovery.MajorTabControl.AddTab(PanelIDs id, Int32 tabindex) w C:\Code\Examples\EDDiscovery\EDDiscovery\MajorTabControl.cs:wiersz 169
>   w System.Windows.Forms.Control.OnClick(EventArgs e)
>   w System.Windows.Forms.Button.OnClick(EventArgs e)
>   w System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   w System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   w System.Windows.Forms.Control.WndProc(Message& m)
>   w System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   w System.Windows.Forms.Button.WndProc(Message& m)
>   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
Either this is a race condition (where multiple threads were trying to fill the table simultaneously), or your dotnet install is broken.

Probably need to make sure in `MaterialCommodityData.EnsurePresent` that the table has been filled, and take a lock while filling the table.
