### ISSUE TITLE
Faction panel uses wrong name

### ISSUE THREAD

**Issue by Eahlstan** [EDDiscovery/EDDiscovery#3074]
![faction](https://user-images.githubusercontent.com/59618179/118568625-875e6100-b778-11eb-93b2-f3b76730d63b.png)

Those come from

{ "timestamp":"2021-05-17T21:13:29Z", "event":"FactionKillBond", "Reward":15000000, "AwardingFaction":"$faction_PilotsFederation;", "AwardingFaction_Localised":"Federación de Pilotos", "VictimFaction":"$faction_Thargoid;", "VictimFaction_Localised":"Thargoides" }

Should be an easy fix as all the other fixes that changed the displayed name from "XY" to "XY_localised".

(Bug found by Jugom.)

**Comment by robbyxp1** [comment]
Not as easy as you think!

**Comment by Eahlstan** [comment]
Damn :(
