### ISSUE TITLE
Difference in field names between history grid and filterable field dalog. 

### ISSUE THREAD

**Issue by TonyFlury** [EDDiscovery/EDDiscovery#3077]
I have created a Special tab for setup which lists the hotspots I have found.
The Tab uses a History view, and is filtered for SAA Signals Found Event : On it's own this will show planetary surface signals too, so I wanted to signal out those fields that are not relevant to Rings.

I have built an advanced filter but in doing so I have noted that the names of the on-screen fields do not match the names of the filterable fields.

On screen the history view shows a `Description` field - when trying to build a filter though the relevant column is 'BodyName'.

I understand that 'Description' is a generic name since the history view shows data from multiple events, but it would be useful if the filter dialog could indicate which on screen field the 'even field is related to - as you can see from the screen snip the filter out fields window gives no indication of which on screen field is being filtered.

![image](https://user-images.githubusercontent.com/15114356/118664032-0d19f500-b7e9-11eb-8bac-1457b07a9b9d.png)

**Comment by robbyxp1** [comment]
Those are the names used in the SAASignalsFound event.  They can't be changed as they map to Frontier journal records, and must be kept for backwards compatibility with the action packs.

The description field is not a one to one mapping between it and any field listed here.  Each event can fill up the description field as it likes.

So I fail to see any change I can make.

**Comment by TonyFlury** [comment]
I understand the reaons for the inconsistency, but clearly the application has a dictionary or similar internally which for each signal type defines which journal field maps to which history grid field.

Is there nothing that can be added to the filterable fields dialog which identifies which history grid field the journal field maps to ? Or even a link to a help page which shows the mappng ?
