### ISSUE TITLE
Webserver and fullscreen mode

### ISSUE THREAD

**Issue by ehcelino** [EDDiscovery/EDDiscovery#3078]
Greetings,
I've been using the webserver with my samsung tablet for a while, and I noticed that when you change tabs it goes out of fullscreen mode. I've tested it in a few different browsers, to no avail. Yesterday I found a workaround: there's a very good piece of software called WallPanel, to be used with web dashboards. It opens an "always full" browser screen, and works perfectly with EDDiscovery web server. It can be found here: https://thanksmister.com/wallpanel-android. Users running Android 4.4.4 will want to use the legacy version, and also specify as browser engine the option "Crosswalk Project".
Good luck commanders,
ehcelino

**Comment by robbyxp1** [comment]
Thanks for the info. I'll have a look at any issues.
