### ISSUE TITLE
Customization of web server

### ISSUE THREAD

**Issue by ehcelino** [EDDiscovery/EDDiscovery#3079]
I am finding the web server very useful, but I won't mind some customization options, and maybe text instead of icons (I keep forgetting what they do....). I do a lot of exploration, so a "scan" tab would be very welcome.
Thank you for a great piece of software!

ehcelino

**Comment by robbyxp1** [comment]
Thats already in the project backlog.  Its going to be a while, due to the amount of work for Odyssey.

Thanks for the suggestion.
