### ISSUE TITLE
Unreplaced ; on the mission panel

### ISSUE THREAD

**Issue by Eahlstan** [EDDiscovery/EDDiscovery#3081]
![Screenshot 2021-05-19 001429](https://user-images.githubusercontent.com/59618179/118730062-40837080-b837-11eb-95db-9acca6bc3c62.JPG)

This is on the english verion, the spanish things come from the journal (therefore most likely no translation issue).

> Influence:++, Reputation:++, Type:Mission Util Faction Tag Basilisk ;, Target Faction:Operation Ida, Target Type:Basilisco Thargoide

I'll send you the journal which contains the necessary events on Discord.

**Comment by robbyxp1** [comment]
Fixed, thanks
