### ISSUE TITLE
Odyessey Broke My EDD

### ISSUE THREAD

**Issue by robbyxp1** [EDDiscovery/EDDiscovery#3082]
We know the changes frontier did to the odyssey build has broken things:

* Bindings (therefore affecting free voice control) They changed the bindings file

**Comment by robbyxp1** [comment]
For now, make sure you have custom on all your odyssey control sections.

**Comment by robbyxp1** [comment]
CAPI is broken from the frontier end

EDDN sending won't always work.

We are awaiting stability on frontier end and a new version will be out soon.

**Comment by robbyxp1** [comment]
CAPI seems to be working now

**Comment by Harag9** [comment]
Robby, I'm sure you know about this and on the case, but just wanted to report it "just in case"...

Now with Odyssey out,  My history journal is now being filled with a load of "unhandled" entries. 

![image](https://user-images.githubusercontent.com/20284741/119222550-d72c8780-baec-11eb-9c36-47b132254f7a.png)

When I load up EDD I get these errors in my log file, again I assume Odyssey.

![image](https://user-images.githubusercontent.com/20284741/119222656-4904d100-baed-11eb-87d4-f4e9f2c34587.png)

Cheers.

**Comment by robbyxp1** [comment]
We have most of those coded.. awaiting Frontiers final fixed journal.

They will appear right when 12.1 is released. 

No point releasing now, EDD will play the space game okay.

**Comment by Harag9** [comment]
Excellent, thought you might be aware of it. Still works ok as you say for now. Looking forward to the 12.1 release (as and when it's ready) :)

**Comment by robbyxp1** [comment]
Frontier are still fixing up the journal, holding off and adding more odyssey features like an improved web view.
