### ISSUE TITLE
Failed sending Shipyard event to EDDN (Shipyard)

### ISSUE THREAD

**Issue by KnightArch** [EDDiscovery/EDDiscovery#3083]
Maybe some change in the journals broke the format file that EDDN accepts the shipyard info on Odyssey and we are no longer able to update station's shipyards. How could I help to address this issue with more data?

![image](https://user-images.githubusercontent.com/8745760/119007999-209f9a00-b968-11eb-88bb-f278ffd87f33.png)

**Comment by KnightArch** [comment]
I can confirm that on Horizons the shipyard info is sent normally, it's just the changes in the Odyssey version of the journals.

**Comment by klightspeed** [comment]
EDDN Market, Shipyard, and Outfitting events require the `odyssey` flag.

**Comment by KnightArch** [comment]
I'm not sure what's happening, Market and Outfitting is being sent fine every time I try but shipyard sometimes fail and sometimes is sent normally, I can't say why is failing in some occasions for the same station. Is there some sort of log I can grab and send to you to try to understand what is happening? There are plenty of stations in the EDDN data which is wrong, showing stuff which never was in that station, just copy-like from "Jameson Memorial" and I'm trying to update as soon as I can these stations to fix the data.

**Comment by robbyxp1** [comment]
The whole systems are up in the air at the moment, with the Odyssey change.  It will be debugged and a new version will appear soon.

Thanks for the report.

**Comment by KnightArch** [comment]
Why to close the ticket if the problem is not solved? That was weird and rude. Thank you anyway, I think...
