### ISSUE TITLE
"Merge" Options Always Greyed-Out on Splitter

### ISSUE THREAD

**Issue by dylan-k** [EDDiscovery/EDDiscovery#3085]
I'm in a bit of a jam. I've opened too many panels within the splitter. Now, no matter what I try, I can't seem to close any of them. There's no close button, which is confusing. When I right click on the space between the panels, the "merge" options are greyed out. If I close the tab and open the "splitter" again in a new tab, it's inherited the mistakes I've made and there seems to be no way to reset the tab to its defaults. Am I doing something wrong or is there a glitch somewhere?

**Comment by klightspeed** [comment]
Hold shift while starting and click Reset Tabs?

**Comment by robbyxp1** [comment]
You can only merge a split. If its showing its greyed out, its not a split. try another dividing line.

**Comment by dylan-k** [comment]
> You can only merge a split. If its showing its greyed out, its not a split. try another dividing line.

But it is a split I'm pretty sure, but the option is greyed out. That's the issue I'm having. Maybe I don't understand though. Is there a difference between a split and some other kind of dividing line? I've tried them all. Greyed out everywhere.

**Comment by dylan-k** [comment]
> Hold shift while starting and click Reset Tabs?

That was somewhat helpful, as it did reset some things (that I'll now need to spend a lot of time redoing unfortunately). but nevertheless I'm still having the trouble. Here's the steps to it:

1. add a new "splitter" tab
2. do "split left panel" or "split right panel"
3. after that, I should be able to do "merge" but no matter what split divider I right click on, the option is always greyed out. There seems to be no other way to close/delete the newly created frame.

I'm on version `12.0.2.0`

**Comment by Eahlstan** [comment]
Can reproduce:

![Screenshot 2021-05-21 235445](https://user-images.githubusercontent.com/59618179/119201855-f5b06580-ba8f-11eb-8b6e-f7f176f12885.JPG)

**Comment by klightspeed** [comment]
> Can reproduce:
> 
> ![Screenshot 2021-05-21 235445](https://user-images.githubusercontent.com/59618179/119201855-f5b06580-ba8f-11eb-8b6e-f7f176f12885.JPG)

If I recall correctly, the `Merge` options are only enabled when right-clicking on a divider where the related side is already split.  i.e. if in the above image, the top panel is split, then `Split Top Panel` should be greyed out and `Merge Top Panel` should be selectable.

i.e. you want to right-click the divider 1 level up from the pair of panels you want to merge, not the divider between the panels you want to merge.

Perhaps a `Merge top and bottom / left and right panels` option should be added to the context menu?

**Comment by Eahlstan** [comment]
Oh. Now I get it. It's not entirely intuitive.
If I have a horizontal split and split the top panel the logical way to merge would be to right click on the border of the two upper panels. But I have to right click on the border between the lower panel and the two upper panels.

(Although I'm 100% sure that I right clicked every border, maybe the restart did something to it or I just was too tired.)

**Comment by robbyxp1** [comment]
Its just the way it works. The splitter system was a mind warp, don't want to get into that right now
