### ISSUE TITLE
the summary panel overlay does not show up on my system

### ISSUE THREAD

**Issue by feiercrack** [EDDiscovery/EDDiscovery#3086]
as said: the summary panel overlay does not show up on my system

Windows 10 Pro, x64 21H1 19043.985  34" 100Hz + 24" 60Hz 3nd Monitors

current EDDiscovery 12.0.2  and Elite Dangerous Odyssey Frontier Edition

**Comment by Eahlstan** [comment]
Your panel position might be off screen. Please check if the summary panel is listed in the task manager like this:

![Screenshot 2021-05-21 231855](https://user-images.githubusercontent.com/59618179/119199235-03172100-ba8b-11eb-9ef3-e70cd91503ec.JPG)

If it's shown in the task manager the it's in fact present but not visible. In that case go to the settings tab and click 'restart in safe mode'. On the safe mode menu click the second entry from above (reset window positions) and then restart EDD.

If this doesn't bring the overlay back on your screen you would have to go to the safe mode again and click on the third entry from above (Reset Tabs, Remove PopOuts) but be aware that this completely resets everything you personalized.

If the summary overlay doesn't show up in the task manager please click on the button that should make a summary pop-out again, close EDD and upload the latest log file made in EDDs logs folder (default position %localappdata%/EDDiscovery ).

**Comment by robbyxp1** [comment]
There is also in menu tools | Popouts methods to turn off transparency and show in taskbar.

Once you've got your panel in the taskbar shown, click it, and use windows key + up/down/left/right to move it.

**Comment by feiercrack** [comment]
oh, wait.. there are buttons? which button exactly do you mean?
Never heard of that before..
Could u please make an tutorial on how t configure that correctly, please?
I just found the button, and i AM overwhelmed!
Wow, THIS is the best overlay i've ever saw!
Amazing, so many options!
Thanks!

**Comment by feiercrack** [comment]
but: ii can see the transparent window now, overlayed to Elite
If i click then inside the game too lay, it vanishes.
Is this normal?
from EDMC EDR i know that the overlay stays, even if i am inside the game. Any solution?
Then, can we adjust the letters of the tab? On my 34" those are too tiny.
And, can we change the colo
![1](https://user-images.githubusercontent.com/47046040/119261334-3666c680-bbd7-11eb-8462-70b986655dec.png)
![2](https://user-images.githubusercontent.com/47046040/119261335-36ff5d00-bbd7-11eb-81a7-705e002d937d.jpg)

rs of the overlay t make them fit to my ED Profiler generated Colors?

**Comment by Eahlstan** [comment]
There's an entire wiki here describing almost everything (also Robby made some videos for people who don't like to read).
I hardly recommend that you start using the Wiki as this would solve most of your questions.
E.g.: https://github.com/EDDiscovery/EDDiscovery/wiki/Using-Panels
