### ISSUE TITLE
Odyssey Unhandled Events - We Know

### ISSUE THREAD

**Issue by b-00-ka** [EDDiscovery/EDDiscovery#3088]
Got few types of unhandled events after Odyessey.
(Local language is Russia)

> **ShipLockerMaterials**
> `{"timestamp":"2021-05-24T14:10:15Z","event":"ShipLockerMaterials","Items":[{"Name":"largecapacitypowerregulator","Name_Localised":"Ðåãóëÿòîð ìîùíîñòè","OwnerID":4188900,"MissionID":769953027,"Count":1},{"Name":"largecapacitypowerregulator","Name_Localised":"Ðåãóëÿòîð ìîùíîñòè","OwnerID":4188900,"MissionID":769953832,"Count":1},{"Name":"largecapacitypowerregulator","Name_Localised":"Ðåãóëÿòîð ìîùíîñòè","OwnerID":4188900,"MissionID":769960653,"Count":1},{"Name":"largecapacitypowerregulator","Name_Localised":"Ðåãóëÿòîð ìîùíîñòè","OwnerID":4188900,"MissionID":770946187,"Count":1},{"Name":"largecapacitypowerregulator","Name_Localised":"Ðåãóëÿòîð ìîùíîñòè","OwnerID":4188900,"MissionID":770979342,"Count":1},{"Name":"largecapacitypowerregulator","Name_Localised":"Ðåãóëÿòîð ìîùíîñòè","OwnerID":4188900,"MissionID":771018988,"Count":1},{"Name":"healthmonitor","Name_Localised":"Ìîíèòîð çäîðîâüÿ","OwnerID":0,"Count":34},{"Name":"healthmonitor","Name_Localised":"Ìîíèòîð çäîðîâüÿ","OwnerID":4188900,"Count":2},{"Name":"healthmonitor","Name_Localised":"Ìîíèòîð çäîðîâüÿ","OwnerID":2952975139,"Count":2},{"Name":"insight","OwnerID":0,"Count":9},{"Name":"insightdatabank","Name_Localised":"Áàíê äàííûõ Insight","OwnerID":0,"Count":8},{"Name":"personalcomputer","Name_Localised":"Ïåðñîíàëüíûé êîìïüþòåð","OwnerID":0,"Count":11},{"Name":"infinity","OwnerID":0,"Count":10},{"Name":"personaldocuments","Name_Localised":"Ëè÷íûå äîêóìåíòû","OwnerID":0,"Count":8},{"Name":"universaltranslator","Name_Localised":"Óíèâåðñàëüíûé ïåðåâîä÷èê","OwnerID":0,"Count":10},{"Name":"chemicalsample","Name_Localised":"Õèìè÷åñêèé îáðàçåö","OwnerID":0,"Count":4},{"Name":"gmeds","Name_Localised":"G-ïðåïàðàòû","OwnerID":0,"Count":6},{"Name":"inertiacanister","Name_Localised":"Èíåðòíûé êîíòåéíåð","OwnerID":0,"Count":4},{"Name":"inertiacanister","Name_Localised":"Èíåðòíûé êîíòåéíåð","OwnerID":2952974481,"Count":1},{"Name":"inertiacanister","Name_Localised":"Èíåðòíûé êîíòåéíåð","OwnerID":2952974491,"Count":1},{"Name":"compactlibrary","Name_Localised":"Êîìïàêòíàÿ áèáëèîòåêà","OwnerID":0,"Count":2},{"Name":"nutritionalconcentrate","Name_Localised":"Ïèòàòåëüíûé êîíöåíòðàò","OwnerID":0,"Count":2},{"Name":"compressionliquefiedgas","Name_Localised":"Ñæèæåííûé ãàç","OwnerID":0,"Count":8},{"Name":"compressionliquefiedgas","Name_Localised":"Ñæèæåííûé ãàç","OwnerID":2952974481,"Count":1},{"Name":"californium","Name_Localised":"Êàëèôîðíèé","OwnerID":0,"Count":3},{"Name":"californium","Name_Localised":"Êàëèôîðíèé","OwnerID":2952974611,"Count":1},{"Name":"buildingschematic","Name_Localised":"×åðòåæ çäàíèÿ","OwnerID":0,"Count":6},{"Name":"insightentertainmentsuite","Name_Localised":"Ðàçâëåêàòåëüíîå óñòðîéñòâî Insight","OwnerID":0,"Count":3},{"Name":"degradedpowerregulator","Name_Localised":"Íåðàáî÷èé ðåãóëÿòîð ìîùíîñòè","OwnerID":0,"Count":18},{"Name":"weaponschematic","Name_Localised":"×åðòåæ îðóæèÿ","OwnerID":0,"Count":26},{"Name":"weaponschematic","Name_Localised":"×åðòåæ îðóæèÿ","OwnerID":2952976079,"Count":1},{"Name":"surveillanceequipment","Name_Localised":"Îáîðóäîâàíèå äëÿ íàáëþäåíèÿ","OwnerID":0,"Count":2},{"Name":"push","Name_Localised":"Ðûâîê","OwnerID":2952975155,"Count":1},{"Name":"push","Name_Localised":"Ðûâîê","OwnerID":0,"Count":12},{"Name":"biochemicalagent","Name_Localised":"Áèîõèìè÷åñêèé àãåíò","OwnerID":2952974481,"Count":4},{"Name":"biochemicalagent","Name_Localised":"Áèîõèìè÷åñêèé àãåíò","OwnerID":0,"Count":26},{"Name":"geneticrepairmeds","Name_Localised":"Ãåííî-ðåïàðàòèâíûå ïðåïàðàòû","OwnerID":2952974491,"Count":1},{"Name":"pyrolyticcatalyst","Name_Localised":"Ïèðîëèòè÷åñêèé êàòàëèçàòîð","OwnerID":2952974491,"Count":1},{"Name":"pyrolyticcatalyst","Name_Localised":"Ïèðîëèòè÷åñêèé êàòàëèçàòîð","OwnerID":2952974481,"Count":2},{"Name":"inorganiccontaminant","Name_Localised":"Íåîðãàíè÷åñêèé êîíòàìèíàíò","OwnerID":2952974481,"Count":2},{"Name":"suitschematic","Name_Localised":"Ýñêèç êîìáèíåçîíà","OwnerID":4188900,"Count":1},{"Name":"hush","Name_Localised":"Òñ-ñ","OwnerID":0,"Count":15},{"Name":"lazarus","Name_Localised":"Ëàçàðü","OwnerID":0,"Count":16},{"Name":"syntheticpathogen","Name_Localised":"Ñèíòåòè÷åñêèé ïàòîãåí","OwnerID":0,"Count":17}],"Components":[{"Name":"circuitswitch","Name_Localised":"Ïåðåêëþ÷àòåëü öåïè","OwnerID":0,"Count":13},{"Name":"encryptedmemorychip","Name_Localised":"Çàøèôðîâàííàÿ ïëàòà ïàìÿòè","OwnerID":0,"Count":4},{"Name":"memorychip","Name_Localised":"Ïëàòà ïàìÿòè","OwnerID":0,"Count":6},{"Name":"metalcoil","Name_Localised":"Ìåòàëëè÷åñêàÿ êàòóøêà","OwnerID":0,"Count":69},{"Name":"opticallens","Name_Localised":"Îïòè÷åñêèå ëèíçû","OwnerID":0,"Count":45},{"Name":"ionbattery","Name_Localised":"Èîííàÿ áàòàðåÿ","OwnerID":0,"Count":16},{"Name":"graphene","Name_Localised":"Ãðàôåí","OwnerID":0,"Count":46},{"Name":"electricalfuse","Name_Localised":"Ïðåäîõðàíèòåëü","OwnerID":0,"Count":7},{"Name":"electricalwiring","Name_Localised":"Ýëåêòðîïðîâîäêà","OwnerID":0,"Count":16},{"Name":"microtransformer","Name_Localised":"Ìèêðîòðàíñôîðìàòîð","OwnerID":0,"Count":8},{"Name":"opticalfibre","Name_Localised":"Îïòîâîëîêíî","OwnerID":0,"Count":30},{"Name":"scrambler","Name_Localised":"Øèôðàòîð","OwnerID":0,"Count":7},{"Name":"transmitter","Name_Localised":"Ïåðåäàò÷èê","OwnerID":0,"Count":5},{"Name":"electromagnet","Name_Localised":"Ýëåêòðîìàãíèò","OwnerID":0,"Count":20},{"Name":"microelectrode","Name_Localised":"Ìèêðîýëåêòðîä","OwnerID":0,"Count":12},{"Name":"weaponcomponent","Name_Localised":"Êîìïîíåíò îðóæèÿ","OwnerID":0,"Count":6},{"Name":"circuitboard","Name_Localised":"Ýëåêòðîïëàòà","OwnerID":0,"Count":11},{"Name":"microhydraulics","Name_Localised":"Ìèêðîãèäðàâëèêà","OwnerID":0,"Count":3},{"Name":"viscoelasticpolymer","Name_Localised":"Âÿçêîýëàñòè÷íûé ïîëèìåð","OwnerID":0,"Count":2},{"Name":"tungstencarbide","Name_Localised":"Êàðáèä âîëüôðàìà","OwnerID":0,"Count":7},{"Name":"microthrusters","Name_Localised":"Ìàíåâðîâûå ìèêðîäâèãàòåëè","OwnerID":0,"Count":2},{"Name":"microsupercapacitor","Name_Localised":"Ìèêðîñóïåðêîíäåíñàòîðû","OwnerID":0,"Count":16},{"Name":"oxygenicbacteria","Name_Localised":"Êèñëîðîäíûå áàêòåðèè","OwnerID":0,"Count":1},{"Name":"carbonfibreplating","Name_Localised":"Óãëåâîëîêîííàÿ áðîíÿ","OwnerID":0,"Count":2},{"Name":"titaniumplating","Name_Localised":"Òèòàíîâàÿ áðîíÿ","OwnerID":0,"Count":3},{"Name":"motor","Name_Localised":"Ìîòîð","OwnerID":0,"Count":10}],"Consumables":[{"Name":"healthpack","Name_Localised":"Àïòå÷êà","OwnerID":0,"Count":99},{"Name":"energycell","Name_Localised":"Ýíåðãîÿ÷åéêà","OwnerID":0,"Count":100},{"Name":"amm_grenade_emp","Name_Localised":"Ðàçðóøèòåëü ùèòîâ","OwnerID":0,"Count":100},{"Name":"amm_grenade_frag","Name_Localised":"Îñêîëî÷íàÿ ãðàíàòà","OwnerID":0,"Count":100},{"Name":"amm_grenade_shield","Name_Localised":"Ïðîåêòîð ùèòà","OwnerID":0,"Count":100},{"Name":"bypass","Name_Localised":"Âçëîìùèê","OwnerID":0,"Count":97}],"Data":[{"Name":"ballisticsdata","Name_Localised":"Áàëëèñòè÷åñêèå äàííûå","OwnerID":0,"Count":1},{"Name":"classicentertainment","Name_Localised":"Êëàññè÷åñêèå ðàçâëå÷åíèÿ","OwnerID":0,"Count":2},{"Name":"cocktailrecipes","Name_Localised":"Ðåöåïòû êîêòåéëåé","OwnerID":0,"Count":1},{"Name":"dutyrota","Name_Localised":"Ãðàôèê äåæóðñòâ","OwnerID":0,"Count":5},{"Name":"employeeexpenses","Name_Localised":"Ðàñõîäû ðàáîòíèêîâ","OwnerID":0,"Count":1},{"Name":"residentialdirectory","Name_Localised":"Àäðåñíàÿ êíèãà","OwnerID":0,"Count":1},{"Name":"salesrecords","Name_Localised":"Îò÷åòû î ïðîäàæàõ","OwnerID":0,"Count":1},{"Name":"securityexpenses","Name_Localised":"Ðàñõîäû íà îõðàíó","OwnerID":0,"Count":2},{"Name":"criminalrecords","Name_Localised":"Äîñüå","OwnerID":0,"Count":1},{"Name":"tacticalplans","Name_Localised":"Òàêòè÷åñêèå ïëàíû","OwnerID":4188900,"Count":1},{"Name":"tacticalplans","Name_Localised":"Òàêòè÷åñêèå ïëàíû","OwnerID":0,"Count":1},{"Name":"internalcorrespondence","Name_Localised":"Âíóòðåííÿÿ êîððåñïîíäåíöèÿ","OwnerID":0,"Count":1},{"Name":"accidentlogs","Name_Localised":"Æóðíàë ïðîèñøåñòâèé","OwnerID":0,"Count":2},{"Name":"campaignplans","Name_Localised":"Ïëàí êàìïàíèè","OwnerID":0,"Count":3},{"Name":"digitaldesigns","Name_Localised":"Äèçàéíåðñêèé ïðîåêò","OwnerID":0,"Count":2},{"Name":"digitaldesigns","Name_Localised":"Äèçàéíåðñêèé ïðîåêò","OwnerID":4188900,"Count":1},{"Name":"influenceprojections","Name_Localised":"Ïðîãíîç âëèÿíèÿ","OwnerID":0,"Count":1},{"Name":"visitorregister","Name_Localised":"Ðååñòð ïîñåòèòåëåé","OwnerID":0,"Count":1},{"Name":"factionassociates","Name_Localised":"Ïàðòíåðû ôðàêöèè","OwnerID":0,"Count":1},{"Name":"chemicalexperimentdata","Name_Localised":"Äàííûå î õèìè÷åñêèõ ýêñïåðèìåíòàõ","OwnerID":0,"Count":1},{"Name":"culinaryrecipes","Name_Localised":"Êóëèíàðíûå ðåöåïòû","OwnerID":0,"Count":1},{"Name":"patienthistory","Name_Localised":"Èñòîðèÿ áîëåçíè","OwnerID":0,"Count":1},{"Name":"personallogs","Name_Localised":"Ëè÷íûå äíåâíèêè","OwnerID":0,"Count":2},{"Name":"productionschedule","Name_Localised":"Ïðîèçâîäñòâåííûé ãðàôèê","OwnerID":0,"Count":1},{"Name":"vaccinationrecords","Name_Localised":"Æóðíàëû âàêöèíàöèè","OwnerID":0,"Count":1},{"Name":"payrollinformation","Name_Localised":"Ïëàòåæíàÿ âåäîìîñòü","OwnerID":0,"Count":1},{"Name":"nocdata","Name_Localised":"Äàííûå ïî òàéíûì àãåíòàì","OwnerID":4188900,"Count":1},{"Name":"airqualityreports","Name_Localised":"Îò÷åòû î êà÷åñòâå âîçäóõà","OwnerID":4188900,"Count":5},{"Name":"audiologs","Name_Localised":"Àóäèîçàïèñè","OwnerID":4188900,"Count":1},{"Name":"productionreports","Name_Localised":"Îò÷åòû î ïðîèçâîäñòâå","OwnerID":4188900,"Count":2},{"Name":"productionreports","Name_Localised":"Îò÷åòû î ïðîèçâîäñòâå","OwnerID":0,"Count":1},{"Name":"combattrainingmaterial","Name_Localised":"Ó÷åáíûå ìàòåðèàëû ïî áîåâîé ïîäãîòîâêå","OwnerID":4188900,"Count":2},{"Name":"manufacturinginstructions","Name_Localised":"Ïðîèçâîäñòâåííûå èíñòðóêöèè","OwnerID":0,"Count":10},{"Name":"radioactivitydata","Name_Localised":"Èíôîðìàöèÿ î ðàäèîàêòèâíîñòè","OwnerID":0,"Count":10},{"Name":"operationalmanual","Name_Localised":"Ðóêîâîäñòâî ïî ýêñïëóàòàöèè","OwnerID":0,"Count":8},{"Name":"stellaractivitylogs","Name_Localised":"Æóðíàëû çâåçäíîé àêòèâíîñòè","OwnerID":0,"Count":9},{"Name":"topographicalsurveys","Name_Localised":"Òîïîãðàôè÷åñêèå èññëåäîâàíèÿ","OwnerID":0,"Count":6},{"Name":"atmosphericdata","Name_Localised":"Àòìîñôåðíûå äàííûå","OwnerID":0,"Count":5},{"Name":"mineralsurvey","Name_Localised":"Ðåçóëüòàòû ãåîëîãè÷åñêîé ðàçâåäêè","OwnerID":0,"Count":5},{"Name":"unionmembership","Name_Localised":"Ñïèñîê ÷ëåíîâ ñîþçà","OwnerID":0,"Count":2},{"Name":"extractionyielddata","Name_Localised":"Äàííûå îá îáúåìå äîáû÷è","OwnerID":0,"Count":1},{"Name":"literaryfiction","Name_Localised":"Õóäîæåñòâåííàÿ ëèòåðàòóðà","OwnerID":0,"Count":1},{"Name":"meetingminutes","Name_Localised":"Ïðîòîêîëû çàñåäàíèé","OwnerID":0,"Count":1},{"Name":"opinionpolls","Name_Localised":"Îïðîñû îáùåñòâåííîãî ìíåíèÿ","OwnerID":0,"Count":1},{"Name":"propaganda","Name_Localised":"Ïðîïàãàíäà","OwnerID":0,"Count":1},{"Name":"purchaserequests","Name_Localised":"Çàïðîñû íà ïîêóïêó","OwnerID":0,"Count":1}]}`

> **TransferMicroResources**
> `{"timestamp":"2021-05-24T13:06:02Z","event":"TransferMicroResources","Transfers":[{"Name":"healthpack","Name_Localised":"Àïòå÷êà","Category":"Consumable","Count":1,"Direction":"ToShipLocker"},{"Name":"energycell","Name_Localised":"Ýíåðãîÿ÷åéêà","Category":"Consumable","Count":2,"Direction":"ToShipLocker"},{"Name":"amm_grenade_emp","Name_Localised":"Ðàçðóøèòåëü ùèòîâ","Category":"Consumable","Count":1,"Direction":"ToShipLocker"},{"Name":"amm_grenade_frag","Name_Localised":"Îñêîëî÷íàÿ ãðàíàòà","Category":"Consumable","Count":2,"Direction":"ToShipLocker"},{"Name":"amm_grenade_shield","Name_Localised":"Ïðîåêòîð ùèòà","Category":"Consumable","Count":1,"Direction":"ToShipLocker"},{"Name":"circuitboard","Name_Localised":"Ýëåêòðîïëàòà","Category":"Component","Count":1,"Direction":"ToShipLocker"},{"Name":"circuitswitch","Name_Localised":"Ïåðåêëþ÷àòåëü öåïè","Category":"Component","Count":2,"Direction":"ToShipLocker"},{"Name":"opticalfibre","Name_Localised":"Îïòîâîëîêíî","Category":"Component","Count":1,"Direction":"ToShipLocker"},{"Name":"weaponschematic","Name_Localised":"×åðòåæ îðóæèÿ","Category":"Item","Count":4,"Direction":"ToShipLocker"}]}`

> **BackPackMaterials**
> `{"timestamp":"2021-05-20T17:40:19Z","event":"BackPackMaterials","Items":[],"Components":[],"Consumables":[],"Data":[]}`

> **SuitLoadout**
> `{"timestamp":"2021-05-24T14:09:10Z","event":"SuitLoadout","SuitID":1700273508218568,"SuitName":"utilitysuit_class2","SuitName_Localised":"$UtilitySuit_Class1_Name;","LoadoutID":4293000001,"LoadoutName":"Engy","Modules":[{"SlotName":"PrimaryWeapon1","SuitModuleID":1700274198907078,"ModuleName":"wpn_m_sniper_plasma_charged","ModuleName_Localised":"Manticore Executioner"},{"SlotName":"SecondaryWeapon","SuitModuleID":1700274290886623,"ModuleName":"wpn_s_pistol_laser_sauto","ModuleName_Localised":"TK Zenith"}]}`

> **CollectItems**
> `{"timestamp":"2021-05-24T13:02:14Z","event":"CollectItems","Name":"energycell","Name_Localised":"Ýíåðãîÿ÷åéêà","Type":"Consumable","OwnerID":0,"Count":1,"Stolen":false}
`> 

> **Disembark**
>` {"timestamp":"2021-05-24T14:09:02Z","event":"Disembark","SRV":false,"Taxi":true,"Multicrew":false,"StarSystem":"Orishis","SystemAddress":5068464399785,"Body":"Orishis 4","BodyID":8,"OnStation":false,"OnPlanet":true}`
> 

> **Embark**
> `{"timestamp":"2021-05-24T14:03:07Z","event":"Embark","SRV":false,"Taxi":true,"Multicrew":false,"StarSystem":"Orishis","SystemAddress":5068464399785,"Body":"Orishis 4 a","BodyID":9,"OnStation":false,"OnPlanet":true}`

> **SellOrganicData**
>` {"timestamp":"2021-05-24T13:58:11Z","event":"SellOrganicData","MarketID":3537673216,"BioData":[{"Genus":"$Codex_Ent_Bacterial_Genus_Name;","Genus_Localised":"Áàêòåðèè","Species":"$Codex_Ent_Bacterial_05_Name;","Species_Localised":"Áàêòåðèÿ Vesicula","Value":56100,"Bonus":0},{"Genus":"$Codex_Ent_Electricae_Genus_Name;","Genus_Localised":"Ýëåêòðèêè","Species":"$Codex_Ent_Electricae_01_Name;","Species_Localised":"Ýëåêòðèêà Pluma","Value":339100,"Bonus":0},{"Genus":"$Codex_Ent_Fonticulus_Genus_Name;","Genus_Localised":"Ôîíòèêóëû","Species":"$Codex_Ent_Fonticulus_02_Name;","Species_Localised":"Ôîíòèêóëà Campestris","Value":63600,"Bonus":0}]}`

> **UpgradeWeapon**
> `{"timestamp":"2021-05-24T13:57:18Z","event":"UpgradeWeapon","Name":"wpn_s_pistol_laser_sauto","Name_Localised":"TK Zenith","Class":2,"SuitModuleID":1700274290886623,"Cost":180000}`

> **BookTaxi**
> `{"timestamp":"2021-05-24T13:44:35Z","event":"BookTaxi","Cost":100,"DestinationSystem":"Orishis","DestinationLocation":"Chasles Base"}`

> **BackpackChange**
> `{"timestamp":"2021-05-24T13:02:12Z","event":"BackpackChange","Removed":[{"Name":"energycell","Name_Localised":"Ýíåðãîÿ÷åéêà","OwnerID":0,"Count":1,"Type":"Consumable"}]}`

**Comment by robbyxp1** [comment]
Thanks for the report.  I know about the events, and they are coded on the tip code. It will be released when the journal from frontier is stablised - its still being worked on by their engineers.
