### ISSUE TITLE
Some thoughts on the Surveyor

### ISSUE THREAD

**Issue by SirTedDanson** [EDDiscovery/EDDiscovery#3094]
Been using EDD for a long time, this program is amazing thank you so much for your hard work. Seriously, Great work :) 

I just have a few thoughts about the Surveyor I wanted to share. I really wish I could filter out non-landable bodies with volcanism. These really get in the way visually when using the Surveyor to find bodies with geological features, i.e. landable planets with volcanism.

The only bodies I really want to appear in the Surveyor are planets that have features or locations.  I don't know if it is possible to do that through. That would be game changing for me.

Otherwise I think just adding something like an additional filtering option would be extremely useful:

-Display IF body has volcanism AND is landable
-Display IF body has atmosphere AND is landable

**Comment by Eahlstan** [comment]
All (or most) features and locations are only written to the journal after DSSing the body. All bodies that have non-DSS signals can already be shown if you select "has signal" in the body features menu.

**Comment by SirTedDanson** [comment]
Oh ok I thought that is how it might work. 

What about more filtering? Landable planets with volcanism or an atmosphere are the bodies with features (mostly). 

As an explorer I really would just like to be able to filter out non-landable bodies with volcanism (has volcanism + is landable), and with the Odyssey update it would be great to have an additional parameter (has atmosphere + is landable).

**Comment by robbyxp1** [comment]
You've been wanting a challenge @Eahlstan !

**Comment by Eahlstan** [comment]
> You've been wanting a challenge @Eahlstan !

My last challenge hasn't been confirmed yet, so I'm not touching the very same file until I know if I did something wrong :D

**Comment by Eahlstan** [comment]
Well, let's see if Robby approves #3101 

![Screenshot 2021-06-08 015126](https://user-images.githubusercontent.com/59618179/121102542-21f11380-c7fe-11eb-8cfe-c7562f539534.JPG)

**Comment by robbyxp1** [comment]
closed

**Comment by SirTedDanson** [comment]
Gosh you guys are awesome. When do you think that feature will be live :)

**Comment by Eahlstan** [comment]
> Gosh you guys are awesome. When do you think that feature will be live :)

Well, you could join the Discord, take a look at the pins in the insider channel and download the latest beta where most of these chances are already implemented (I just changed the surveyor again to show the exact atmosphere instead just "has atmosphere" and that's not in there).
As Frontier is still changing their journal output no date can be given on a full release as this depends completely on the things Frontier does - can't code EDD if there's nothing to base it on.

**Comment by SirTedDanson** [comment]
Gotchya, for sure will do! Thanks for all the help. o7
