### ISSUE TITLE
Cant log in to EDDB or FCAPI. 

### ISSUE THREAD

**Issue by dcheva** [EDDiscovery/EDDiscovery#3095]
![image](https://user-images.githubusercontent.com/47900415/120828813-a4ab7180-c565-11eb-87ce-0dadf6ea4a7f.png)
can not log in via frontier via steam.
--- server returned 302 !!!internal error. why and for what? when logging in. Logging in EEDB directly and steam directli are okey. sessions are both alive in chrome. but... ?
for first.
cant find EDDB option.
for second.
can you try to revert your changes back?

**Comment by klightspeed** [comment]
> can not log in via frontier via steam.
> --- server returned 302 !!!internal error. why and for what? when logging in. Logging in EEDB directly and steam directli are okey. sessions are both alive in chrome. but... ?

Please provide a screenshot of this error.

> for first.
> cant find EDDB option.

There is no direct sync to EDDB.  Rather, EDDB receives its data via EDDN.

> for second.
> can you try to revert your changes back?

Which changes?  If it's the Inara login, does 11.10.3 work?  Though 11.10.3 does not have cAPI support.

Note that cAPI support was added primarily to enable Console commanders to be able to use EDDiscovery.

**Comment by robbyxp1** [comment]
no response. closing
