### ISSUE TITLE
Linux build issues

### ISSUE THREAD

**Issue by RononDex** [EDDiscovery/EDDiscovery#3096]
The linux build is failing with errors message
 ```
"/home/cobra/packages/eddiscovery/src/eddiscovery-11.10.3/EDDiscovery.sln" (default target) (1) ->
"/home/cobra/packages/eddiscovery/src/eddiscovery-11.10.3/EDDiscovery/EDDiscovery.csproj.metaproj" (default target) (2) ->
"/home/cobra/packages/eddiscovery/src/eddiscovery-11.10.3/BaseUtilities/Audio/Audio.csproj" (default target) (3) ->
"/home/cobra/packages/eddiscovery/src/eddiscovery-11.10.3/BaseUtilities/BaseUtilities/BaseUtils.csproj" (default target) (4:2) ->
(ResolveAssemblyReferences target) -> 
  /usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2198,5): error MSB3248: Parameter "AssemblyFiles" has invalid value "/usr/lib/mono/4.6-api/mscorlib.dll". Could not load file or assembly 'System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. [/home/cobra/packages/eddiscovery/src/eddiscovery-11.10.3/BaseUtilities/BaseUtilities/BaseUtils.csproj]
```

I did try with AUR package and manual build (on Arch Linux)

**Comment by Eahlstan** [comment]
Are you using the latest released source code ( https://github.com/EDDiscovery/EDDiscovery/archive/refs/tags/Release_12.0.2.tar.gz )?

[/home/cobra/packages/eddiscovery/src/eddiscovery-11.10.3/BaseUtilities/BaseUtilities/BaseUtils.csproj] indicates that you're using an old code, as old versions aren't fixed any longer bugs that aren't in the newest release won't be fixed ever.

**Comment by klightspeed** [comment]
`/usr/lib/mono/4.6-api/` is because EDDiscovery and its DLLs are compiled targeting dotnet 4.6

Looking at <https://archlinux.org/packages/extra/x86_64/mono/files/>, `/usr/lib/mono/4.6-api/mscorlib.dll` is included in the package.

Looking at <https://ci.appveyor.com/project/EDDiscovery/eddiscovery/builds/39453304/job/uusntds9n7waxsub>, the build is currently succeeding with Mono 6.8 using the command:
```
msbuild /p:Configuration=Release EDDiscovery.sln /p:DefineConstants=NO_SYSTEM_SPEECH
```

**Comment by RononDex** [comment]
Thanks, you were able to point me in the right direction.
It turns out that the "official" mono package in Arch Linux is outdated.
To get mono4.8 I had to get mono-git from AUR and compile mono myself.

After that EDDiscovery works just fine.

By the way, are there any plans to migrate to .net core soonish?

**Comment by RononDex** [comment]
At the moment, when I click on "Tools" in the top menu though, I keep getting a NullReferenceException:

![image](https://user-images.githubusercontent.com/2249071/120920777-d2f19400-c6c0-11eb-9f3d-780db69a2eed.png)

**Comment by robbyxp1** [comment]
.net core does not have everything we need to run EDD on windows. Hopefully soon it will.

**Comment by Eahlstan** [comment]
11.10.3 is an old version, have you tried if this error is in the current version too?

https://github.com/EDDiscovery/EDDiscovery/archive/refs/tags/Release_12.0.2.tar.gz

**Comment by RononDex** [comment]
just installed 12.0.2 and it crashes when hitting "OK" in the Greetings / Disclaimer screen

![image](https://user-images.githubusercontent.com/2249071/120921251-19e08900-c6c3-11eb-96ed-8384062ad817.png)

**Comment by RononDex** [comment]
Also hitting Tool-->Exit throws another exception:

![image](https://user-images.githubusercontent.com/2249071/120921292-4eecdb80-c6c3-11eb-862f-ba1b4c960d9e.png)

**Comment by RononDex** [comment]
Also getting lots of these messages in the console
![image](https://user-images.githubusercontent.com/2249071/120921346-88254b80-c6c3-11eb-9d4f-342fe4e3952c.png)

**Comment by klightspeed** [comment]
I think the NRE in the about box is because the web browser is compiled out when MONO is set, yet there are probably some things that assume it's present.

The `UnauthorizedAccessException` suggests that you have pointed the journal directory at `/home/cobra/Games/origin` or something similar, and the journal scan is trying to find journal files in all subdirectories (including symlinks) in that directory.  `Z:` is usually symlinked to `/`

**Comment by klightspeed** [comment]
> By the way, are there any plans to migrate to .net core soonish?

.net core only supports System.Windows.Forms on Windows (i.e. netcoreapp31-windows or net50-windows).  It does not support it at all on Linux or MacOS.  It would need a complete rewrite of the GUI code to use a cross-platform GUI library (such as GTK#).

**Comment by RononDex** [comment]
> The UnauthorizedAccessException suggests that you have pointed the journal directory at /home/cobra/Games/origin or ...

My jounral directory is set to `/home/cobra/.local/share/Steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/Saved Games/Frontier Developments/Elite Dangerous/`

**Comment by klightspeed** [comment]
Looking at <https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/EDDiscoveryControllerHistory.cs#L182>, if `-DefaultJournalFolder` is not specified on the command-line or in `options.txt`, then the current working directory will be used on Linux (as there is no native client for Elite Dangerous, so there is no default journal directory).

Are you running EDDiscovery directly from your home directory (or running it using an absolute path with the current working directory being your home directory)?

**Comment by RononDex** [comment]
I am running it using command "eddiscovery" (which works because it is in my PATH) in the home directory. However, I have the journal folder set in the settings

**Comment by klightspeed** [comment]
In your `eddiscovery` script, you might want to `cd` to your EDDiscovery directory.

**Comment by RononDex** [comment]
Also when I try to rescan journal files I get these messages 
![image](https://user-images.githubusercontent.com/2249071/120929716-6d1a0200-c6ea-11eb-8ef3-ec4b55f12968.png)

With a crash to desktop

**Comment by klightspeed** [comment]
> Also when I try to rescan journal files I get these messages
> ![image](https://user-images.githubusercontent.com/2249071/120929716-6d1a0200-c6ea-11eb-8ef3-ec4b55f12968.png)
> 
> With a crash to desktop

That `ObjectDisposedException` suggests that something is trying to access the systems database after it has stopped.  The only place it is stopped is during the `finally` in the `Main` procedure, at which point the main GUI thread has exited, and the GUI will have been torn down.

It seems that the error that actually caused the CTD has scrolled off your console (which looks like it's weirdly using a proportional font - either that, or the window that has that log is running on its own thread separate from the main GUI thread).

**Comment by RononDex** [comment]
Here is more from the log, it still seems to originate from the "Permissions denied" issue

![image](https://user-images.githubusercontent.com/2249071/120939549-d44eab00-c718-11eb-92d2-ff3112850c7a.png)

After `cd` into the journal directory, it shows some basic info, but crashes again on rescan:
![image](https://user-images.githubusercontent.com/2249071/120939628-37d8d880-c719-11eb-8460-cdbfe94615d2.png)

**Comment by klightspeed** [comment]
> Here is more from the log, it still seems to originate from the "Permissions denied" issue
> 
> ![image](https://user-images.githubusercontent.com/2249071/120939549-d44eab00-c718-11eb-92d2-ff3112850c7a.png)

Do you have the trace log (should be `Trace*.log` in `~/.local/share/EDDiscovery/Log`) from that?  The `Cannot access a disposed object` errors look like they occur whenever trying to access the Systems database, suggesting that `StopRequested` is being set.  The only place `StopRequested` should be getting set is in `SQLProcessingThread[T].Stop()`, which is only called in the `finally` when the main loop exits.

The permission denied issue is just because it's trying to enumerate the files in `.`, which includes a symlink to `/`.

Are you running it from source, or using the portable install?

If you are running it from source, what commit did you build from, and what command did you use to build it?

Here, running from the master branch (commit 35dadaf), compiled using `msbuild /p:Configuration=Debug EDDiscovery.sln '/p:DefineConstants="NO_SYSTEM_SPEECH;MONO;DEBUG;TRACE"'`, and running using mono 6.12.0.122, it is running mostly successfully.  I am running Gentoo here, so:
```
$ mono --version
Mono JIT compiler version 6.12.0.122 (tarball Mon Jun  7 19:55:04 AEST 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

Some issues I have noted are:
* The commander dialog has the bottom cut off when running under icewm (I recall this being reported, but cannot find it) - I'm not sure how we would fix this, as the layout engine seems to treat `DockStyle.Fill` as filling the entire window, and trying to use `Anchor` just makes it worse.
* Trying to close the about dialog results in a `NullReferenceException` due to trying to stop a non-existent web browser (should be fixed with #3099)

**Comment by RononDex** [comment]
[Trace_2021-06-06-22-45-46.0.log](https://github.com/EDDiscovery/EDDiscovery/files/6608947/Trace_2021-06-06-22-45-46.0.log)
This is the trace log, I can not find any message related to "disposed" inside it though.

I used the git commit that was tagged with v12.0.2, meaning this one: https://github.com/EDDiscovery/EDDiscovery/commit/3a51e2a2459c64aed0b6efdea204452051376a48

I was able to fix the commander button issue by increasing window size in my wm (i3wm).

Thanks a lot for your time trying to solve this issue :+1: 

My mono version:
```
❯ mono -V
Mono JIT compiler version 6.13.0 (main/a271b719293 Sun Jun  6 09:47:42 AM UTC 2021)
Copyright (C) Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Comment by klightspeed** [comment]
> [Trace_2021-06-06-22-45-46.0.log](https://github.com/EDDiscovery/EDDiscovery/files/6608947/Trace_2021-06-06-22-45-46.0.log)

That log coincides with your first error:

> At the moment, when I click on "Tools" in the top menu though, I keep getting a NullReferenceException:
> 
> ![image](https://user-images.githubusercontent.com/2249071/120920777-d2f19400-c6c0-11eb-9f3d-780db69a2eed.png)

```
[2021-06-06T20:46:44.087Z] 4884Stop UserDatabaseConnection SQL Thread UserDB
[2021-06-06T20:46:44.088Z] 4884Stopped UserDatabaseConnection SQL UserDB
[2021-06-06T20:46:44.088Z] 4884Stop SystemsDatabaseConnection SQL Thread SystemDB
[2021-06-06T20:46:44.088Z] 4884Stopped SystemsDatabaseConnection SQL SystemDB
[2021-06-06T20:46:44.089Z] 
[2021-06-06T20:46:44.089Z] ==== UNHANDLED EXCEPTION ====
[2021-06-06T20:46:44.089Z] System.NullReferenceException: Object reference not set to an instance of an object
[2021-06-06T20:46:44.089Z]   at System.Windows.Forms.Application.RunLoop (System.Boolean Modal, System.Windows.Forms.ApplicationContext context) [0x00344] in <3cd0d72857b74b79b647936a17a4cec9>:0 
[2021-06-06T20:46:44.089Z]   at System.Windows.Forms.Application.Run (System.Windows.Forms.ApplicationContext context) [0x00011] in <3cd0d72857b74b79b647936a17a4cec9>:0 
[2021-06-06T20:46:44.089Z]   at EDDiscovery.Program.Main () [0x00034] in <376328e2616740d5b903f1f0b9ec53a2>:0 
[2021-06-06T20:46:44.089Z] ==== cut ====
```

That's an error somewhere in <https://github.com/mono/mono/blob/main/mcs/class/System.Windows.Forms/System.Windows.Forms/Application.cs#L765>

**Comment by RononDex** [comment]
If I could get it to run with `dotnet run` for example I could debug it and see whats going wrong.

However, I don't seem able to get it started from source on Linux. I tried using `xbuild <sln file>` and `dotnet run` and  `mono ...

It always fails with error message that it can not find basic types:
![image](https://user-images.githubusercontent.com/2249071/121090971-a2594980-c7e9-11eb-8d0e-9bb61d8429f4.png)

**Comment by klightspeed** [comment]
> If I could get it to run with `dotnet run` for example I could debug it and see whats going wrong.
> 
> However, I don't seem able to get it started from source on Linux. I tried using `xbuild <sln file>` and `dotnet run` and `mono ...
> 
> It always fails with error message that it can not find basic types:
> ![image](https://user-images.githubusercontent.com/2249071/121090971-a2594980-c7e9-11eb-8d0e-9bb61d8429f4.png)

`dotnet run` will not work, as the `System.Windows.Forms` libraries will be missing.

The errors suggest that you did not `nuget restore`

You need [nuget](https://archlinux.org/packages/extra/any/nuget/) and [mono-msbuild](https://archlinux.org/packages/community/x86_64/mono-msbuild/) installed in order to build EDDiscovery.

```sh
git clone https://github.com/EDDiscovery/EDDiscovery.git
cd EDDiscovery
git submodule update --init
nuget restore
msbuild /p:Configuration=Debug EDDiscovery.sln '/p:DefineConstants="NO_SYSTEM_SPEECH;MONO;DEBUG;TRACE"'
```

**Comment by robbyxp1** [comment]
the command sequence on the wiki page for linux worked for me to install everything.

**Comment by RononDex** [comment]
I have been trying to debug it, however, I cant seem able to pinpoint the exact piece of code that causes it.

I can see some very basic stack trace though. Pressing on the stack trace entry does not show any related code though:

![image](https://user-images.githubusercontent.com/2249071/121347655-b99e5100-c927-11eb-83ca-03f211e65088.png)

**Comment by klightspeed** [comment]
That looks like it's back to your original error.

With that line 910, it looks like the error is in <https://github.com/mono/mono/blob/main/mcs/class/System.Windows.Forms/System.Windows.Forms/Application.cs#L910>
```cs
if (keyboard_capture != null) {
    Control c2 = Control.FromHandle (msg.hwnd);
    var contextMenuStrip = keyboard_capture.GetTopLevelToolStrip () as ContextMenuStrip;

    // The target is not a winforms control (an embedded control, perhaps), so
    // release everything
    if (c2 == null) {
        ToolStripManager.FireAppClicked ();
        goto default;
    }

    // Skip clicks on owner windows, eg. expanded ComboBox
    if (Control.IsChild (keyboard_capture.Handle, msg.hwnd)) {
        goto default;
    }

    // Close any active toolstrips drop-downs if we click outside of them,
    // but also don't close them all if we click outside of the top-most
    // one, but into its owner.
    Point c2_point = c2.PointToScreen (new Point (
        (int)(short)(m.LParam.ToInt32() & 0xffff),
        (int)(short)(m.LParam.ToInt32() >> 16)));
    while (keyboard_capture != null && !keyboard_capture.ClientRectangle.Contains (keyboard_capture.PointToClient (c2_point))) {
        keyboard_capture.Dismiss ();
    }

    var iter_OwnerItem = (c2 as ToolStripDropDown)?.OwnerItem;
    while (iter_OwnerItem != null && iter_OwnerItem.Owner != contextMenuStrip) {
        iter_OwnerItem = iter_OwnerItem.OwnerItem;
    }
    var contextMenuStripIsOwnerOf_c2 = (iter_OwnerItem != null);
    
    if (c2 != contextMenuStrip && !contextMenuStripIsOwnerOf_c2)
        contextMenuStrip.Dismiss (); // <----
}
```

Basically the left button is pressed, and it assumes that a context menu needs to be dismissed, but no context menu has keyboard focus.

This looks like a bug in mono, where something is null when it is assumed to not be null.

**Comment by RononDex** [comment]
Could it be related to my window manager? Isn't the Window manager the part that handles window focus etc (fires all the UI events) on linux?
I am using i3-gaps, maybe it is reproducible that way

**Comment by klightspeed** [comment]
It looks like it is a bug that was introduced in mono/mono#20953, which explains why I'm not running into it (I'm not running mono directly from the main branch)

**Comment by klightspeed** [comment]
And it looks like the fix for it is in mono/mono#21014

**Comment by RononDex** [comment]
Ah that might be it, nice find!
That PR has been open for almost 2 months now. I hope they will get around to fix it, or I need to find mono packaged in a different way to install a version before that bug was introduced

**Comment by RononDex** [comment]
I have recompiled and installed mono from source, however, I am still getting the same error

**Comment by klightspeed** [comment]
What commit did you build mono from?

**Comment by RononDex** [comment]
The package has the name mono-git-6.12.0.145.r1308.9570aef3394-1-x86_64.pkg.tar.zst, meaning the commit was probably 9570aef3394

**Comment by klightspeed** [comment]
mono/mono@9570aef3394 is the current tip of the mono main branch.

You might want to try applying <https://github.com/mono/mono/pull/21014.patch>

```sh
cd /path/to/src/mono
wget 'https://github.com/mono/mono/pull/21014.patch'
patch -p1 <21014.patch
```

Then do the standard `make` and `make install` - it should be quicker than a full compile, as it should only be `System.Windows.Forms.dll` that should need to be rebuilt.

**Comment by RononDex** [comment]
Ah I see, I mistakinkly thought that it was already merged into the main branch.

I will try the patch when I get time the next few days

**Comment by robbyxp1** [comment]
I can't see anything to update EDD, so closing, but you can keep on discussing it obv.
