### ISSUE TITLE
Scan Panel: FSS/Mapping "high value target" icon logic

### ISSUE THREAD

**Issue by therealfakemoot** [EDDiscovery/EDDiscovery#3098]
The Scan panel currently has a "value threshold" for bodies in the present system, and will display a $ symbol next to planets with a *current scanned value* above the set value threshold. It might be nicer if this icon's visibility was controlled by the estimated mapping value, possibly factoring in whether the planets are known to be discovered.

**Comment by Eahlstan** [comment]
Should be done with the update of PR #3090

**Comment by robbyxp1** [comment]
done
