### ISSUE TITLE
EDSM sync missing some systems

### ISSUE THREAD

**Issue by repaxan** [EDDiscovery/EDDiscovery#31]
![img](https://i.sli.mg/hKUjLH.png)

**Comment by AnthorNet** [comment]
Hi,
Without more informations, I can't really help you.

HAve you tried hitting again the EDSM sync ?

**Comment by repaxan** [comment]
Yes, that is after pressing the sync button. It says "edsm: sending 0 flightlog entries"

**Comment by AnthorNet** [comment]
Hmm I'm sure Finwen will have an idea ;)
In the meantime you could add them manually in the database.

**Comment by finwen** [comment]
Not sure why but i will look into it in a few days.

To make it easier for me to  find the problem.  Send  EDDiscovery.sqlite
 database to me.    You will find it at  %localappdata%/EDDiscovery

Send it to robert.l.wahlstrom@gmail.com



2015-11-12 21:40 GMT+01:00 AnthorNet <notifications@github.com>:

**Comment by gregmalcolm** [comment]
I think sometimes it happens when you arrive at a known point, quit the game and come back in again and EDSM sends a replica point. Easily done I guess if the difference are subtle.

**Comment by Red13x3** [comment]
I think it would be good to be able to judiciously add or remove entries in your local DB. But if they are manually added, it would mark the line in some fashion like yellow background or an asterix near the line number, or such.

And if you delete a line (with confirmations!) then it would delete the verbose log file created by Elite. (I seem to get duplicates in my list if I restart the game out in the black.)

Mark

--
Mark Jelic
iPhone: 0402 322 901

**Comment by robbyxp1** [comment]
EDSM Sync completely rewritten. Closed.
