### ISSUE TITLE
DB update counter not updating

### ISSUE THREAD

**Issue by Eahlstan** [EDDiscovery/EDDiscovery#3102]
The initial download of the EDSM dump works fine, the import itself works alos, but the count doesn't increase.
Right now the size of the EDDSystem.sqlite is 769112 kB and still increasing, but
![Screenshot 2021-06-10 014428](https://user-images.githubusercontent.com/59618179/121443241-68c14380-c98d-11eb-89ec-4263ac982fbd.JPG)
 It's most likely caused by this change: https://github.com/EDDiscovery/EliteDangerousCore/commit/d73bb2cb640a580835c2625a49dde9f492557b07#diff-4df419dd810424298f88cc0723b3615d82c7a95a969ac267938106c1884ca2b9

I changed that back, compiled it and it's correctly updating the counter again. I won't submit that change as I don't know why it was changed.

**Comment by Seag011** [comment]
I have the same problem with counter update. Also tried this and counter starts work fine
![image](https://user-images.githubusercontent.com/34947358/121445259-c8255080-c999-11eb-9ef9-89f7838afee8.png)

**Comment by robbyxp1** [comment]
it says how many has been downloaded per get.. as it should do.  thus i changed it.  it says "updated" not "total updates".

**Comment by klightspeed** [comment]
> it says how many has been downloaded per get.. as it should do. thus i changed it. it says "updated" not "total updates".

Perhaps instead of changing the count displayed from the total updates to the number updated in that step, you should have changed the text from "updated" to "total updates"

**Comment by Seag011** [comment]
Is it possible to add "total updates" progress to see progress, as many people don't understand what's happening? Often update counter has the same value during whole update process and it doesn't shows user anything.

**Comment by Eahlstan** [comment]
> it says how many has been downloaded per get.. as it should do. thus i changed it. it says "updated" not "total updates".

Hm. Before that change that message was useful to see that it was working and a everlasting '10000' was an indicator of a broken DB - which isn't rare as we could see on Discord in the past.
Now it constantly shows '10000' until the last update which is less than 10000 and there's no visible sign that it's actually doing something and there's now no indicator that it's not doing something too.
Honestly I don't see how the current non-counter is better than the previous counter.

**Comment by Eahlstan** [comment]
How about

`reportProgress?.Invoke("EDSM Star database updated with" + recordstostore + " updated " + updates + " so far.");`

![Screenshot 2021-06-10 123356](https://user-images.githubusercontent.com/59618179/121510743-401a6780-c9e8-11eb-9795-bfd525bc6836.JPG)

**Comment by robbyxp1** [comment]
i'll reopen and we can reconsider later..

**Comment by robbyxp1** [comment]
technically, and i've seen this, it is working as i intended. it says the no of updates, but we can add the total as well.

**Comment by Eahlstan** [comment]
> technically, and i've seen this, it is working as i intended. it says the no of updates, but we can add the total as well.

I can't stress enough how much this would be useful.
