### ISSUE TITLE
Can not update to the latest version

### ISSUE THREAD

**Issue by DoctorShpongle** [EDDiscovery/EDDiscovery#3103]
When I try and update, the update appears to run smoothly, however when I run EDDiscovery, I get an error that says failed to download the full EDSM system file, it tells me to try again later, when I run it again it reverts back to version 12. I have attempted this multiple times and have even re-downloaded it. Is there a way to fix this, or do I need to wait for another update?

**Comment by klightspeed** [comment]
The `failed to download the full EDSM system file` suggests that either you don't have enough disk space on the drive the EDDiscovery data is stored on (default `%LOCALAPPDATA%\EDDiscovery`) (the systems dump is 2.2GB, and the database that is generated from it is about 5GB), or the systems dump download was interrupted.

If you don't need full systems database, then you can disable EDSM system data download on the settings tab.

The current version of EDDiscovery is 12.0.3

**Comment by robbyxp1** [comment]
no response
