### ISSUE TITLE
Cant Log Into Frontier CAPI

### ISSUE THREAD

**Issue by crunk007** [EDDiscovery/EDDiscovery#3104]
A browser window keeps popping up for Frontier Authentication login. I login but it still says im logged out of Frontier CAPI in settings. I try again and doesn't work. Browser window keeps popping up from time to time even after i gave up and left it alone. 

This is what it says in the log

DLLs loaded: EDMCHarness
Profile Default Loaded
Frontier bindings did not load
History refresh complete.
CAPI Awaiting Callback
CAPI Require Log in
Sent 3 events to INARA
CAPI Authorization Failed

**Comment by robbyxp1** [comment]
Its the frontier servers.. try again later.

**Comment by robbyxp1** [comment]
closing
