### ISSUE TITLE
About Window Doesn't Stop Videos When Closed

### ISSUE THREAD

**Issue by milonti** [EDDiscovery/EDDiscovery#3108]
When opening the About window from the Help drop down menu, the youtube video embedded into one of the sections begins playing. If I don't pause that video before I close the window it will keep playing audio in the background with no way to get to it again to stop it. Opening up the About window again opens a new instance of the video.

This also might mean that the About window is not properly closing/destroying/reusing itself but I have much less insight into that.

**Comment by robbyxp1** [comment]
Its a known problem, which we have attempted fixes to. It does not happen on all systems, which makes it harder to debug.

Thanks for the report, i'll have another go at it.
