### ISSUE TITLE
Odyssey Screen shot events ?

### ISSUE THREAD

**Issue by TonyFlury** [EDDiscovery/EDDiscovery#3111]
Does Odyssey generate screenshot events when the player is onfoot - they seem to be missing from EDD.

**Comment by Eahlstan** [comment]
If you want to know something about a specific journal event please consult the official manual: https://elite-journal.readthedocs.io/en/latest/

If you're unsure if an event is written try to trigger it in game and then take a look at your journals located in shell:SavedGames\Frontier Developments\Elite Dangerous or look at the journal panel in EDDiscovery.

**Comment by robbyxp1** [comment]
I tested it on foot in station and they appeared.

**Comment by robbyxp1** [comment]
confirmed on planet, no issue, closing
