### ISSUE TITLE
unknown Journal

### ISSUE THREAD

**Issue by DubbyDu** [EDDiscovery/EDDiscovery#3113]
{"timestamp":"2021-06-13T23:29:12Z","event":"ShipLocker","Items":[],"Components":[],"Consumables":[{"Name":"healthpack","Name_Localised":"Medikit","OwnerID":0,"Count":100},{"Name":"energycell","Name_Localised":"Energiezelle","OwnerID":0,"Count":100},{"Name":"amm_grenade_emp","Name_Localised":"Schildunterbrecher","OwnerID":0,"Count":100},{"Name":"amm_grenade_frag","Name_Localised":"Splittergranate","OwnerID":0,"Count":100},{"Name":"amm_grenade_shield","Name_Localised":"Schildgenerator","OwnerID":0,"Count":100}],"Data":[]}

**Comment by robbyxp1** [comment]
We know, thanks, the next version out soon will cope with it.
