### ISSUE TITLE
Reminder: Server hickups sending multiple SAASignalfound events cause the scan panel to list every single one of them

### ISSUE THREAD

**Issue by Eahlstan** [EDDiscovery/EDDiscovery#3117]
![EDDiscovery](https://user-images.githubusercontent.com/59618179/122656930-55696180-d15f-11eb-87cb-5dc3f1a908e9.png)

**Comment by robbyxp1** [comment]
Line 98 of StarScanSAASignalsFound does not check for repeated signals, fix.

**Comment by robbyxp1** [comment]
Closed and fixed.
