### ISSUE TITLE
Joystick Bindings

### ISSUE THREAD

**Issue by incryptx** [EDDiscovery/EDDiscovery#3118]
When installing "FreeVoicePack", it never finds the Frontier bindings even though it's a commonly known path.

It shows:

Check:

Bindings:

Devices:
X56 H.O.T.A.S. Throttle:715eba10-3a20-11eb-8002-444553540000:a2210738-0000-0000-0000-504944564944:a221,738:36,0,2
X56 H.O.T.A.S. Stick:7160b5e0-3a20-11eb-8004-444553540000:22210738-0000-0000-0000-504944564944:2221,738:17,1,0
Keyboard:6f1d2b61-d5a0-11cf-bfc7-444553540000:6f1d2b61-d5a0-11cf-bfc7-444553540000
Mouse:6f1d2b60-d5a0-11cf-bfc7-444553540000:6f1d2b60-d5a0-11cf-bfc7-444553540000

But, never any "bindings".

**Comment by robbyxp1** [comment]
Its due to Odyssey changes Frontier made in startpreset.start.  The next version will cope with it.

To solve it, you would need to change startpreset.start back to a single line with 'Custom' in it.

**Comment by robbyxp1** [comment]
startpreset can be found in the frontier binding location 
C:\Users\<user>\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings

Odyssey will work with the single line version.

**Comment by robbyxp1** [comment]
Did a 12.0.3 patch which will work better. thanks

**Comment by incryptx** [comment]
Unfortunately, no.

 

This is because you “hard coded” for “custom.3.0.binds” file name and I use HCS Voicepacks, so my binds are called “HCS SaitekX56.3.0.binds”

 

As well, the hard coded binds name will not work for the majority of your audience because most use controllers which are not named “custom”.

 

To solve this, a window for the “path”, which includes the “file name” of the binding to be loaded, would be helpful and work.

 

I installed and uninstalled EDD and the Frontier CAPI  does authenticate, but the LOGIN button just opens EDD over and over again, with three or four instances running,

 

My EDDI CAPI is broken and will not work. I have EDDI installed and it’s CAPI will authenticate and run without opening many instances of EDDI.

**Comment by robbyxp1** [comment]
We did not code for custom binds file name thank you very much, as you'll see if you look at the code.

We coded for the filename starting with a line in startpreset and picking the latest by date of that name. So if you've called it Fred, it would pick the latest fred one.

So, since you're the only one telling me its broken, i'll presume its working for the majority of users.

**Comment by incryptx** [comment]
I don’t mean to be rude, but the first line in startpreset has not changed. The only thing that changed in startpreset was the addition of three additional lines. If EDD read the first line before Odyssey, then it should be able to read the first line in startpreset after Odyssey. Nothing changed here. The additional lines in startpreset should not affect EDD, provided you did not hard code for a filename.

**Comment by incryptx** [comment]
After a clean uninstalling and reinstalling of 12.03, this works now.

 

Loaded Bindings C:\Users\Me\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\HCS SaitekX56.4.0.binds

 

There seems to be “multiple instances” of EDD running in the “Task Manager” and EDD does not properly shut down now. I have to kill at least two running EDD instances.

 

From: Support ***@***.***> 
Sent: Monday, June 21, 2021 10:32 AM
To: 'EDDiscovery/EDDiscovery' ***@***.***>; 'EDDiscovery/EDDiscovery' ***@***.***>
Cc: 'Incryptx' ***@***.***>; 'Author' ***@***.***>
Subject: RE: [EDDiscovery/EDDiscovery] Joystick Bindings (#3118)

 

Unfortunately, no.

 

This is because you “hard coded” for “custom.3.0.binds” file name and I use HCS Voicepacks, so my binds are called “HCS SaitekX56.3.0.binds”

 

As well, the hard coded binds name will not work for the majority of your audience because most use controllers which are not named “custom”.

 

To solve this, a window for the “path”, which includes the “file name” of the binding to be loaded, would be helpful and work.

 

I installed and uninstalled EDD and the Frontier CAPI  does authenticate, but the LOGIN button just opens EDD over and over again, with three or four instances running,

 

My EDDI CAPI is broken and will not work. I have EDDI installed and it’s CAPI will authenticate and run without opening many instances of EDDI.

**Comment by klightspeed** [comment]
> There seems to be “multiple instances” of EDD running in the “Task Manager” and EDD does not properly shut down now. I have to kill at least two running EDD instances.

Do you have any DLL addons installed?  Not completely exiting, yet releasing the mutex so other instances don't give the `EDDiscovery is already running. Launch anyway?` warning (or `Whoo there, Bessie. Your sure?` if you're using French, Spanish, or Example) suggests that one or more non-background threads are started.
