### ISSUE TITLE
DSS showing as SAA

### ISSUE THREAD

**Issue by GreytalonCBR** [EDDiscovery/EDDiscovery#3121]
The timeline event list shows "SAA Scan of <Insert planet here>" instead of "DSS scan of <Insert planet here>

**Comment by klightspeed** [comment]
From the journal doc <http://hosting.zaonce.net/community/journal/v31/Journal_Manual_v31.pdf>:
> ### 6.13 SAAScanComplete
>
> When written: after using the “Surface Area Analysis” scanner
>
> Parameters:
> * SystemAddress
> * BodyName
> * BodyID
> * ~~Discoverers: (array of names)~~
> * ~~Mappers: (array of names)~~
> * ProbesUsed: (int)
> * EfficiencyTarget: (int)
>
> Example:
> ```json
> { "timestamp":"2018-10-05T15:06:12Z", "event":"SAAScanComplete", "BodyName":"Eranin 5",
>   "BodyID":5, "ProbesUsed":6, "EfficiencyTarget":9 } 
> ```

**Comment by robbyxp1** [comment]
I'm keeping with the journal naming of the event.

**Comment by GreytalonCBR** [comment]
Thanks for getting back to me. And apologies, I didn’t realise it was actually the Journal event name.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
