### ISSUE TITLE
Request: Filter route finder by scoopable stars

### ISSUE THREAD

**Issue by DRA6N** [EDDiscovery/EDDiscovery#3133]
It would be _super_ handy to be able to filter a route by scoopable stars rather than a simple route. This would help us fuel rats out a LOT, and it would be the only router (besides the game) that does this!

**Comment by klightspeed** [comment]
Please suggest this either in the #Spansh channel on the EDCD discord server, or in the Spansh neutron router thread <https://forums.frontier.co.uk/showthread.php/308674-Neutron-Highway-long-range-route-planner/> to be added to <https://spansh.co.uk/exact-plotter>.

The EDDiscovery route plotter is designed for plotting waypoints where you would use the in-game route plotter to plot between those waypoints.  It is not designed for plotting single jumps.

Note also that the EDSM systems dump does not include star data, so even if EDDiscovery did keep star data with its system data, it would only have that star data with systems you have already visited (unless either a separate star data dump were created, or you were happy to extract the 43GB Spansh galaxy dump).

**Comment by DRA6N** [comment]
Hey, if storing 43GB of data on my system is what it takes haha.

Thanks.

**Comment by DRA6N** [comment]
> Please suggest this either in the #Spansh channel on the EDCD discord server, or in the Spansh neutron router thread <https://forums.frontier.co.uk/showthread.php/308674-Neutron-Highway-long-range-route-planner/> to be added to <https://spansh.co.uk/exact-plotter>.
> 
> The EDDiscovery route plotter is designed for plotting waypoints where you would use the in-game route plotter to plot between those waypoints.  It is not designed for plotting single jumps.
> 
> Note also that the EDSM systems dump does not include star data, so even if EDDiscovery did keep star data with its system data, it would only have that star data with systems you have already visited (unless either a separate star data dump were created, or you were happy to extract the 43GB Spansh galaxy dump).

Do you have a link to the EDCD discord?

**Comment by robbyxp1** [comment]
https://discord.gg/zQjjutY

thanks
