### ISSUE TITLE
Error when launching - v12.1.1.0

### ISSUE THREAD

**Issue by neorazor** [EDDiscovery/EDDiscovery#3135]
Greetings! 

First and foremost, many thanks for a wonderful tool!

When launching EDDiscovery 12.1.1.0, I'm presented with Translation file disappeared - check your debugger - translationfolder settings. (see attached image) This issue started after v 12.1.0.0 was upgraded to 12.1.1.0. 

Note clicking Ok allows the app to load and work normally.

Let me know what other information I can provide.

Thank you!

![image](https://user-images.githubusercontent.com/7603327/125625903-8404fca3-57eb-4a12-b7ac-d4f7e66eb6a6.png)

**Comment by Eahlstan** [comment]
This has been fixed shortly (™) after the initial release.
The release has been updated, but no new version number has been made. If you redownload the last release and install it this problem should be gone.

**Comment by neorazor** [comment]
Thank you, redownloaded, installed and confirmed no more error.
