### ISSUE TITLE
Enhancement - Biology Count & Pop Out

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#3136]
I've taken to looking for life out in the black.  One thing that is hard to keep track of is the bodies with biological signals in a system, and when on the surface, the number of life-forms scanned to the codex versus total.

Some thoughts:
I don't know if the FSS scan log lists biology or not, but if it does, perhaps it could be added to the scan map?
Looking at the current planet, I can see EDD knows it has 8 Biological signals when I mapped it.  And each and codex entry is logged to.  Using the codex entry, we should be able to show 2/8 scanned, 3/8 scanned and so on.  Whether this would work better as a separate pop out (maybe with the details of the life found), or integrated into the existing summary panel somehow, I don't know.

Be nice to push FD to add a biology (and geology) tag to the FSS scans to0 (if not already present), so a dedicated planetary explorer panel could be developed.

**Comment by robbyxp1** [comment]
i'll have a look at how scanorganic can be integrated into the system. thanks.

**Comment by robbyxp1** [comment]
moved to project cards
