### ISSUE TITLE
unhandled ui exception

### ISSUE THREAD

**Issue by toqueville** [EDDiscovery/EDDiscovery#3143]
### Description

I loaded up eddiscovery before starting the game. I loaded into space near a planet I hadn't scanned yet.  I then low waked and then scanned a planet. Restarting EDDiscovery didn't fail again.
### Exception Details:
>EDDiscovery v12.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.JournalEvents.JournalScan.SurveyorInfoLine(ISystem sys, Boolean hassignals, Boolean showvolcanism, Boolean showvalues, Boolean shortinfo, Boolean showGravity, Boolean showAtmos, Boolean showRings, Int32 lowRadiusLimit, Int32 largeRadiusLimit, Double eccentricityLimit) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalScanInfo.cs:line 885
>   at EDDiscovery.UserControls.UserControlSurveyor.<DrawSystem>d__21.MoveNext() in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSurveyor.cs:line 340
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by robbyxp1** [comment]
Thanks, I can't see the error for now, i'll keep this in mind.

**Comment by klightspeed** [comment]
It looks like it's using `last_sys` where it should be using `sys`
