### ISSUE TITLE
Popout forms call SetWindowLong on Linux

### ISSUE THREAD

**Issue by klightspeed** [EDDiscovery/EDDiscovery#3145]
`focarion` on Discord reported:

> whenever i try to use the surveyor tab i'm getting a blank page and a error:

### Exception Details:
>EDDiscovery v12.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.EntryPointNotFoundException: SetWindowLong assembly:<unknown assembly> type:<unknown type> member:(null)
>  at (wrapper managed-to-native) BaseUtils.Win32.UnsafeNativeMethods.SetWindowLong(intptr,BaseUtils.Win32.UnsafeNativeMethods/GWL,int)
>  at BaseUtils.Win32.UnsafeNativeMethods.ChangeWindowLong (System.IntPtr hWnd, BaseUtils.Win32.UnsafeNativeMethods+GWL nIndex, System.Int32 mask, System.Int32 set) [0x0000e] in <5c9e50859dcc44c18eece6a8d64c9cec>:0 
>  at EDDiscovery.UserControls.UserControlForm.UpdateTransparency () [0x00165] in <4b29a109b9804377a47a0ed810119bd6>:0 
>  at EDDiscovery.UserControls.UserControlForm.SetTopMost (System.Boolean t) [0x0002a] in <4b29a109b9804377a47a0ed810119bd6>:0 
>  at EDDiscovery.UserControls.UserControlForm.UserControlForm_Shown (System.Object sender, System.EventArgs e) [0x0005f] in <4b29a109b9804377a47a0ed810119bd6>:0 
>  at System.Windows.Forms.Form.OnShown (System.EventArgs e) [0x00019] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>  at EDDiscovery.Forms.DraggableFormPos.OnShown (System.EventArgs e) [0x00009] in <4b29a109b9804377a47a0ed810119bd6>:0 
>  at System.Windows.Forms.Form.SetVisibleCore (System.Boolean value) [0x0013d] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>  at System.Windows.Forms.Control.set_Visible (System.Boolean value) [0x00009] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>  at System.Windows.Forms.Control.Show () [0x00000] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control.Show()
>  at EDDiscovery.PopOutControl.PopOut (EDDiscovery.PanelInformation+PanelIDs selected) [0x0012c] in <4b29a109b9804377a47a0ed810119bd6>:0 
>  at EDDiscovery.UserControls.UserControlPanelSelector.ButtonPress (System.Object o, System.Int32 i) [0x00064] in <4b29a109b9804377a47a0ed810119bd6>:0 
>  at ExtendedControls.CompositeButton+<>c__DisplayClass8_0.<QuickInit>b__0 (System.Object o, System.EventArgs e) [0x00020] in <daedbd09434e4f76982d3e682db2e90b>:0 
>  at System.Windows.Forms.Control.OnClick (System.EventArgs e) [0x00019] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>  at System.Windows.Forms.Button.OnClick (System.EventArgs e) [0x00011] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>  at System.Windows.Forms.ButtonBase.OnMouseUp (System.Windows.Forms.MouseEventArgs mevent) [0x00069] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>  at System.Windows.Forms.Button.OnMouseUp (System.Windows.Forms.MouseEventArgs mevent) [0x00000] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>  at ExtendedControls.ExtButton.OnMouseUp (System.Windows.Forms.MouseEventArgs mevent) [0x00016] in <daedbd09434e4f76982d3e682db2e90b>:0 
>  at System.Windows.Forms.Control.WmLButtonUp (System.Windows.Forms.Message& m) [0x00078] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x001b4] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>  at System.Windows.Forms.ButtonBase.WndProc (System.Windows.Forms.Message& m) [0x00037] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>  at System.Windows.Forms.Button.WndProc (System.Windows.Forms.Message& m) [0x00000] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00085] in <3fb877620f4346078c0ed47fd8d21e37>:0 
>===== END =====
>```

**Comment by robbyxp1** [comment]
Mono, full of little bugs

Unfort it looks like no-one is maintaining it when i looked at their github
