### ISSUE TITLE
EDD Enhancement Request - Automatic Carrier Jump Timer

### ISSUE THREAD

**Issue by Thecat8413** [EDDiscovery/EDDiscovery#3148]
As it looks like EDD is able to see Carrier Jump Requests, would it be possible to add a small automatic timer that pings you when the carrier is available to be jumped again? I've been using EDD's Expedition and Route Tracker Functions to help automate a fairly long trip and this would help significantly with keeping on pace. 

Either way, thank you for creating such a great tool.

**Comment by robbyxp1** [comment]
Added to project list.
