### ISSUE TITLE
Obelisk Data amounts/tiers wrong

### ISSUE THREAD

**Issue by tmzasz** [EDDiscovery/EDDiscovery#3151]
The Obelisk data ingame has all totals maxing at 150 but in EDD they have higher max amounts as well as the tier's of the data are wrong. Attaching screenshots
![ingame](https://user-images.githubusercontent.com/7916657/127788558-757550b9-d8aa-44ec-8d53-9d6d0d8fd4f7.png)
![EDD](https://user-images.githubusercontent.com/7916657/127788561-d05f540f-5f35-48f9-8a94-0f27ed03face.png)

**Comment by robbyxp1** [comment]
I'll have to find out why they were classified incorrectly. thanks for the report.

**Comment by robbyxp1** [comment]
fixed, thanks
