### ISSUE TITLE
Broken Codex Strings in 12.1.xxx

### ISSUE THREAD

**Issue by Elite-IGAU** [EDDiscovery/EDDiscovery#3154]
Robby, 

I noticed from the jump from 12.0.xxx to 12.1.xxxx that codex strings sent to IGAU are no longer stripped of extra characters like "$" and ";", nor are they shifted to lower case.  See attached. 

![1](https://user-images.githubusercontent.com/56673950/128566524-a780cd89-fb49-42f4-a108-b82eded847b9.png)
![2](https://user-images.githubusercontent.com/56673950/128566537-91d23b28-c952-4d11-8bcd-6e761f1aa32d.png)

**Comment by Eahlstan** [comment]
Does this happen all the time?

My current log shows me:

`2021-08-06T19:20:17.684Z: POST https://ddss70885k.execute-api.us-west-1.amazonaws.com/Prod: {"timestamp":"2021-08-06T19:20:48Z","EntryID":"2370208","Name":"codex_ent_fonticulus_02_l","Name_Localised":"Fonticulua Campestris - Mauve","System":"Blia Chria GS-N b48-0","SystemAddress":"338900253089","App_Name":"EDDiscovery","App_Version":"12.1.3.0"`

`2021-08-05T12:43:48.335Z: POST https://ddss70885k.execute-api.us-west-1.amazonaws.com/Prod: {"timestamp":"2021-08-05T12:44:16Z","EntryID":"2420703","Name":"codex_ent_stratum_07_m","Name_Localised":"Stratum Tectonicas - Green","System":"Blia Chria VO-B b41-1","SystemAddress":"2529065072993","App_Name":"EDDiscovery","App_Version":"12.1.3.0"}`

**Comment by Elite-IGAU** [comment]
@Eahlstan :

`
codex_ent_fonticulus_02_l | Fonticulua Campestris - Mauve | Blia Chria GS-N b48-0
codex_ent_stratum_07_m | Stratum Tectonicas - Green | Blia Chria VO-B b41-1
`

Were those genetic sampler scans, FSS data, or composition scans?

**Comment by Eahlstan** [comment]
Yeah, I think I already found what's causing it, one second.

**Comment by Eahlstan** [comment]
Should be fixed with this:

https://github.com/EDDiscovery/EliteDangerousCore/pull/63

Thanks for your report.

**Comment by Eahlstan** [comment]
`2021-08-06T21:05:56.815Z: POST https://ddss70885k.execute-api.us-west-1.amazonaws.com/Prod: {"timestamp":"2021-08-06T21:06:28Z","EntryID":"-","Name":"codex_ent_fonticulus_04","Name_Localised":"Fonticulua Lapida","System":"Blia Chria KO-G c24-5","SystemAddress":"1416164883666","App_Name":"EDDiscovery","App_Version":"12.1.3.0"}`

Seems fine now, that's a ScanOrganic event.

**Comment by robbyxp1** [comment]
The older codex strips the $, the newer scanorganic did not. Now does.

Will be rolled into the next update, whenever that is.
