### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by Uggers** [EDDiscovery/EDDiscovery#3157]
I am running version 12.1.4.0

When I start EDDiscovery, it is unresponsive.
It does however let me open the program and view the window that its frozen on, but it is entirely unresponsive.

It appears to be processing something, maybe the EDSM Star Database update or perhaps my recent log. I can't really tell. I know its doing something 
About 50% of the time it will work again, although it ranges from 10-30 minutes to not at all (after 2-3 hours)

Let me know if any more info is required. But previous versions worked fine

**Comment by Uggers** [comment]
Not sure if it matters but my EDDSystem.sqlite is around 5.4gb

**Comment by robbyxp1** [comment]
This is a problem with your installation, as we are not getting any other reports of this.

Are you running on an HDD? if so, the EDSM DB is too big for that now.

**Comment by Uggers** [comment]
Yes I am, it wasn't a problem previously but I guess something has changed.

My SSD space is limited which is why this was sitting on a WD Black. I'll have to see if I can make some space

**Comment by Eahlstan** [comment]
The logs inside EDDs log folder would still be nice to see, just is n case there's something interesting in there.

**Comment by Uggers** [comment]
Of course; Logs attached.

[Trace_2021-08-24-13-29-43.0.log](https://github.com/EDDiscovery/EDDiscovery/files/7039445/Trace_2021-08-24-13-29-43.0.log)

**Comment by robbyxp1** [comment]
Either its just the speed the HDD works at, or its a damaged DB.

My suggestion is to run the system DB on an SDD.  Remember you don't have to download the whole galaxy, you can initially say No to what to download, then go to the systems panel and set up a custom download of the sectors of the galaxy you actually are interested in.

**Comment by robbyxp1** [comment]
You could try moving the current large DB to an SDD before you delete it, and see if it works better.  Use safe mode and you can move it to another place while keeping the exe in the same place.

**Comment by Uggers** [comment]
many thanks, i'll try a few of the suggestions and see if it improves

Happy for you to close this ticket out,

 If those options don't work I'll fully move it to an SSD to see if that improves, if not i'll do a reinstall, and failing that I'll reach out

**Comment by robbyxp1** [comment]
thanks- remember you can just copy EDDUser.SQLITE to your new install location appdata folder to keep all your settings
