### ISSUE TITLE
Buy to Storage not registering in ledger.

### ISSUE THREAD

**Issue by halbrooktech** [EDDiscovery/EDDiscovery#3158]
With Update 6, we got the option to buy to storage directly.  When doing so, EDD does not register the purchase in the ledger.  

The journal does have "Module Buy and Store" but the information is {"timestamp":"2021-08-24T23:07:45Z","event":"ModuleBuyAndStore","BuyItem":"$int_hullreinforcement_size1_class1_name;","BuyItem_Localised":"Hull Reinforcement","MarketID":3223343616,"BuyPrice":4144,"Ship":"diamondbackxl","ShipID":36} 

Which looks like it's not processing the buy to storage.

**Comment by klightspeed** [comment]
That looks like a new event, which would not yet be handled by EDDiscovery.

**Comment by robbyxp1** [comment]
Noted. Thanks

**Comment by robbyxp1** [comment]
Fixed on tip
