### ISSUE TITLE
Release_12.1.4: Not all actions available from Webserver in "Status" and "Grid" view are executed ingame

### ISSUE THREAD

**Issue by projectb-temp** [EDDiscovery/EDDiscovery#3159]
Hi there and thank you for the nice companion tool you've created.

I'm running Release_12.1.4 in portable mode on a Windows 10 machine running the Steam version of ED:Horizons.
EDD itself and the EDD webserver is running smoothly and I'm accessing it from a Android tablet to get various information. Also the response of actions I do ingame are reflected fine within EDD and the webpage.

But: Not all action buttons on the Status and Grid pages seem to trigger actions within the game.
Positive example: Pressing the "Lights" button on the webpage does alternate the light modes ingame.
Negative examples: Pressing "Night Vision", "Show System Map" or "Show Galaxy Map" on the webpage does not trigger any actions ingame, regardless of the state of flying I'm in (docked, SC, normal flying).

I don't think I re-mapped any of the key settings or added any new secondary keys regarding those actions.

How can I get the not working action buttons to actually trigger things ingame?

Thank's a lot for your assistance.

Best regards

**Comment by robbyxp1** [comment]
I'll have to check. Please bear with me.

**Comment by Eahlstan** [comment]
It works fine on my side.
Please add the Free Voice Control add-on, after this there's a new option in the "Help" menu called "List Elite Bindings".
This enables you to see if the control scheme EDD picks up is the same you use in game.

**Comment by projectb-temp** [comment]
Thanks for your reply.
I'll have to check the add-on and will report my findings. Due to absence this might take some days.

**Comment by robbyxp1** [comment]
I have checked it out in all modes (flight, srv, onfoot) and pressing galaxy button (for example, and other) on mine ends up sending a key stroke to elite.

Remember that the galaxy/star map buttons have unique control settings in the control list for on-foot and srv.

At the moment, there is nothing i can see wrong.

**Comment by robbyxp1** [comment]
You need to map the galaxy/planet etc settings in on-foot, and srv, and not leave them empty.

**Comment by robbyxp1** [comment]
Closing unless something else comes up.

**Comment by projectb-temp** [comment]
> ... Please add the Free Voice Control add-on, after this there's a new option in the "Help" menu called "List Elite Bindings".
> This enables you to see if the control scheme EDD picks up is the same you use in game.

Thank you for pointing me in the right direction. I really had some controls screwed up here. Everything works fine now. The issue can be marked as closed/solved.
