### ISSUE TITLE
Enhancement request: Add a limpet life-time panel (and to webserver)

### ISSUE THREAD

**Issue by projectb-temp** [EDDiscovery/EDDiscovery#3160]
Hi there,

when mining a lot it sometimes is quite handy to know the remaining life-time of any of your currently active limpets.

So I hereby kindly ask you if it's possible to add such a "limpet life-time" feature to the panels and the webserver.

Thank you a lot for your response.

Best regards

**Comment by robbyxp1** [comment]
I'll add it to the project list.  But as I'm the only one doing stuff at the moment and I have my plate full it won't be soon.

Thanks

**Comment by projectb-temp** [comment]
Thank you for addressing my request!

Take your time and don't put yourself under pressure by it. If it's done, it's done.
