### ISSUE TITLE
HTML embedded render engine

### ISSUE THREAD

**Issue by Ejsstiil** [EDDiscovery/EDDiscovery#3161]
Not an issue, just a feature request. I noticed some issues when using a panel with Inara.cz inside - some their web buttons are not working and I bet that is because EDDiscovery uses the IE engine. We all know IE's "compatibility". If it would be possible to let user choose a different HTML engine for web panels (Chrome, Fox). And to have a tiny, RW address bar next to button "Track" ;)

**Comment by robbyxp1** [comment]
No, its not, and that's because of a limitation with c# web services.  I've had a deep look into it and its impossible to move away at this time from IE.

Remember the purpose of this is to auto track the current system on Inara etc, more than it being just a general web browser.
