### ISSUE TITLE
VoicePack 17: Error in saving "Voice Pack Configuration"

### ISSUE THREAD

**Issue by tecnosegugio** [EDDiscovery/EDDiscovery#3162]
Saving in the "Voice Pack Configuration" window I read this error in the log window:
```
Error: Variable 'EventClass_EventTypeStr' does not exist
At Step 6 in VoicePackV17::GenericResponse:2099: Set
```
and the configuration window become unresponsive.

* EDDiscovery 12.1.4.0
* VoicePack17 17.0.0.0
* Windows 10 pro
* Elite Dangerous Odyssey

**Comment by robbyxp1** [comment]
Is this a modified pack?  line 2099 is not inside GenericResponse program.

**Comment by robbyxp1** [comment]
Please copy in the voice pack file, which you can find in %LOCALAPPDATA%\eddiscovery\actions here, you can just drop it onto the comment field.

**Comment by robbyxp1** [comment]
And you were using the voice pack configuration menu, when the error occurred?  

An error in a voice pack, due to a incorrect program line, won't stop the next event happening and working. So i'm very confused about what happened.  

Also, if your in the voice pack configuration menu, and it froze, that means you could not hit okay or cancel?

**Comment by tecnosegugio** [comment]
Sorry for late answer but I can use Windows only on evening.

Attached you can find the .act file, I presume this is the file you asked for.
[VoicePackV17.zip](https://github.com/EDDiscovery/EDDiscovery/files/7145165/VoicePackV17.zip)

I got the error message when I cilck on:
Menu -> Add-Ons -> Voice Pack COnfiguration

After the error, if I click on "OK" or "Cancel" button nothing happens. 
Even clicking on the X on upper-right corner of the config window doesn't close the configuration window.
I can only close the whole program clicking, for instance, on the X at upper-right corner of the program window.

**Comment by tecnosegugio** [comment]
Addendum: tonight I've sen that my log is flooded by errors like:

```
Error: Function phrase: Parameter 1: Function indirect: Indirect Variable 'say_Position' not found
At Step 7 in VoicePackV17::GenericResponse:2101: Set
Error: Function phrase: Parameter 1: Function indirect: Indirect Variable 'say_Position' not found
At Step 7 in VoicePackV17::GenericResponse:2101: Set
Error: Function phrase: Parameter 1: Function indirect: Indirect Variable 'say_OverallStatus' not found
At Step 7 in VoicePackV17::GenericResponse:2101: Set
Error: Function phrase: Parameter 1: Function indirect: Indirect Variable 'say_OverallStatus' not found
At Step 7 in VoicePackV17::GenericResponse:2101: Set
Error: Variable 'EventClass_EventTypeStr' does not exist
At Step 6 in VoicePackV17::GenericResponse:2099: Set
```

I begin to think that I have configuration files damaged. :-/

**Comment by Eahlstan** [comment]
On Line 238 you changed
`EVENT DropShipDeploy, GenericResponse, "", Condition AlwaysTrue`
to
`EVENT All, GenericResponse, "", Condition AlwaysTrue`

That "All" messes up everything.

Somehow GitHub currently throws an error when I try to upload a file here, but I fixed it for you and uploaded it to [my drive](https://drive.google.com/file/d/1JQmDuOTgyIbm40n3pQ7YDTgy1y9UKMGM/view?usp=sharing). This should keep all your changes, please try it.

**Comment by tecnosegugio** [comment]
I never edited that file, maybe it become corrupted after some incorrect operation.

Now I've edited the file as you told me and errors disappeared.
Thank you.

I'll keep an eye on that file to see if become corrupted again.

**Comment by Eahlstan** [comment]
Using the "Edit Add-On" thing edits the file.
So you might have changed `DropShipDeploy` to `All` there.

**Comment by robbyxp1** [comment]
Glad it got sorted. closing
