### ISSUE TITLE
Exception during monitor watch file found

### ISSUE THREAD

**Issue by BanditSan** [EDDiscovery/EDDiscovery#3163]
Can you please explain wtf EDDiscovery is doing here?
```
[2021-09-14T10:52:17.142Z] Exception during monitor watch file found System.UnauthorizedAccessException: Access to the path '~/.local/share/Steam/steamapps/common/Proton 5.0/dist/share/default_pfx/dosdevices/z:/lost+found' is denied. ---> System.IO.IOException: Permission denied
```
```
[2021-09-14T10:38:46.326Z] Exception during monitor watch file found System.UnauthorizedAccessException: Access to the path '~/.local/share/teamviewer11/dosdevices/z:/lost+found' is denied. ---> System.IO.IOException: Permission denied
```
What kinda files are you trying to watch in these locations?

**Comment by Eahlstan** [comment]
I'm not very familiar with Linux, but I think that has been answered in another [issue](https://github.com/EDDiscovery/EDDiscovery/issues/3096#issuecomment-855385434). Maybe the answers there can help you, if not we have to wait for klightspeed :)

**Comment by klightspeed** [comment]
If you are running EDDiscovery via a `.desktop` file or via a script in your path, and are not specifying a working directory, then the default working directory is your home directory.  EDDiscovery will search the working directory recursively for journal files.  As the `Z:` Wine drive is a symlink to `/`, and the Mono implementation of `Directory.EnumerateFiles` follows symlinks when recursively searching, and does not ignore directories it can't access, this results in the access denied on `lost+found`.

**Comment by BanditSan** [comment]
So you don't need to be familiar with linux at all to ask the question. Why this app trying to look for something in
teamviewer settings folder:
```
Access to the path '~/.local/share/teamviewer11/dosdevices/z:/lost+found' is denied. ---> System.IO.IOException: Permission denied
```
in navicat folder:
```
Access to the path '~/.navicat/dosdevices/z:/lost+found' is denied. ---> System.IO.IOException: Permission denied```
And yes these specific folder require root permissions to access, but question is why it's looking there? How it's related to elite journal logs?

**Comment by klightspeed** [comment]
Where are you running EDDiscovery from?
How are you running it?
What is the CWD when you are running EDDiscovery?
What do you have your journal directory set to in your commander settings in EDDiscovery?
Are you specifying the `-DefaultJournalFolder` option?

**Comment by BanditSan** [comment]
> If you are running EDDiscovery via a `.desktop` file or via a script in your path, and are not specifying a working directory, then the default working directory is your home directory. EDDiscovery will search the working directory recursively for journal files. As the `Z:` Wine drive is a symlink to `/`, and the Mono implementation of `Directory.EnumerateFiles` follows symlinks when recursively searching, and does not ignore directories it can't access, this results in the access denied on `lost+found`.

1. Doing recursive search by default? That is a lot of pointless IO to disk. 
2. Where is option to disable that?
3. Why it's still doing recursive search when i already have specified journal location? Again pointless disk IO

**Comment by robbyxp1** [comment]
I think klightspeed has answered your questions, its most probably searching folders in the default places it searches them for, for the journal .log files, and your set up is wrong at the moment to find them.

Your not giving us any information back to try and work out what its doing.

**Comment by BanditSan** [comment]
> Where are you running EDDiscovery from?
> How are you running it?

start script:
```bash
$ cat /usr/bin/eddiscovery 
#!/bin/sh
exec mono /usr/lib/eddiscovery/EDDiscovery.exe "$@"
```

> What is the CWD when you are running EDDiscovery?

CWD is always by default user home directory

> What do you have your journal directory set to in your commander settings in EDDiscovery?

directory where elites journal is located
```
~/.virtualenvs/EliteDangerous/wine/drive_c/users/$USER/Saved Games/Frontier Developments/Elite Dangerous
```

> Are you specifying the `-DefaultJournalFolder` option?
No

**Comment by robbyxp1** [comment]
Also the link posted about by Eahlstan is valid, you must set your -defaultJournalLocation.

**Comment by BanditSan** [comment]
> Also the link posted about by Eahlstan is valid, you must set your -defaultJournalLocation.

Wait so what is the point of this?
![screenshot_20210914-150607_691x77](https://user-images.githubusercontent.com/6743235/133254798-71ff6f15-dd25-42b0-8b0f-fd6dede3e004.png)
This is not default location?

**Comment by klightspeed** [comment]
> > Where are you running EDDiscovery from?
> > How are you running it?
> 
> start script:
> 
> ```shell
> $ cat /usr/bin/eddiscovery 
> #!/bin/sh
> exec mono /usr/lib/eddiscovery/EDDiscovery.exe "$@"
> ```

To avoid the error, you must either change your working directory away from `$HOME` (e.g. `$HOME/.local/share/EDDiscovery`), or specify a `-DefaultJournalDirectory`

e.g.
```sh
#!/bin/sh
mkdir -p "${$XDG_DATA_HOME:-$HOME/.local/share}/EDDiscovery"
cd "${$XDG_DATA_HOME:-$HOME/.local/share}/EDDiscovery}"
exec mono /usr/lib/eddiscovery/EDDiscovery.exe "$@"
```

**Comment by klightspeed** [comment]
> > Also the link posted about by Eahlstan is valid, you must set your -defaultJournalLocation.
> 
> Wait so what is the point of this?
> ![screenshot_20210914-150607_691x77](https://user-images.githubusercontent.com/6743235/133254798-71ff6f15-dd25-42b0-8b0f-fd6dede3e004.png)
> This is not default location?

The commander journal directory specifies another directory to search, in addition to the default journal directory.

As there is no native Linux Elite Dangerous client, EDDiscovery uses the current working directory as the default journal directory unless overridden by `-DefaultJournalDirectory`

**Comment by BanditSan** [comment]
> > > Also the link posted about by Eahlstan is valid, you must set your -defaultJournalLocation.
> > 
> > 
> > Wait so what is the point of this?
> > ![screenshot_20210914-150607_691x77](https://user-images.githubusercontent.com/6743235/133254798-71ff6f15-dd25-42b0-8b0f-fd6dede3e004.png)
> > This is not default location?
> 
> The commander journal directory specifies another directory to search, in addition to the default journal directory.
> 
> As there is no native Linux Elite Dangerous client, EDDiscovery uses the current working directory as the default journal directory unless overridden by `-DefaultJournalDirectory`

What addition journal directory you can set then default elite's journal? From where?

**Comment by klightspeed** [comment]
> > The commander journal directory specifies another directory to search, in addition to the default journal directory.
> > As there is no native Linux Elite Dangerous client, EDDiscovery uses the current working directory as the default journal directory unless overridden by `-DefaultJournalDirectory`
> 
> What addition journal directory you can set then default elite's journal? From where?

If you have each commander in a separate wine prefix, then you can point that commander's Journal Location to the `Saved Games` in that wine prefix.  Also, if you are sharing journals from another computer, you can point the appropriate commander's Journal Location at the directory that share is mounted on.

**Comment by BanditSan** [comment]
So user sets only one commander. Why that journal location cannot be equal DefaultJournalDirectory?
Even if user sets more then one commander why first one cannot be default?
If that is somehow issue this app on first start creates "${XDG_DATA_HOME:-$HOME/.local/share}/EDDiscovery" directory. Why this cannot be `-DefaultJournalDirectory` default value?

What you are doing by recursive home search is generating unnecessary disk IO and creating security hole by scanning files not owned by this application.

**Comment by robbyxp1** [comment]
I think this ticket is over now, and we have explained what was happening. 

Closing.

**Comment by klightspeed** [comment]
> So user sets only one commander. Why that journal location cannot be equal DefaultJournalDirectory?
> Even if user sets more then one commander why first one cannot be default?

How do you suggest that EDDiscovery automatically determine which wine prefix you have installed Elite Dangerous into out of the four wine prefixes you have listed here?  What if you're not even running Elite Dangerous on the computer you are running EDDiscovery on, but are instead sharing the journal directory from another computer?

> If that is somehow issue this app on first start creates "${XDG_DATA_HOME:-$HOME/.local/share}/EDDiscovery" directory. Why this cannot be `-DefaultJournalDirectory` default value?

An option that has been floated is to not have a default journal directory on platforms (such as Linux or *BSD) that have no native EDDiscovery client.

Note: In case you are wondering where `${XDG_DATA_HOME:-$HOME/.local/share}` came from, see <https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html>:
> $XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

**Comment by BanditSan** [comment]
> How do you suggest that EDDiscovery automatically determine which wine prefix you have installed Elite Dangerous into out of the four wine prefixes you have listed here? What if you're not even running Elite Dangerous on the computer you are running EDDiscovery on, but are instead sharing the journal directory from another computer?

Simple. On first start asks user to set first commanders journal location if cannot determine by itself. But NOT recursively  scans $HOME by default without noticing user.
You do understand that $HOME can be from few GB to multiple TB in size and  have multiple mount point which also can be multiple TB in size. And your trying to search $HOME recursively by default.

**Comment by robbyxp1** [comment]
So, we will keep this in mind.  There is nothing much else to say.
