### ISSUE TITLE
There was an unhandled UI exception

### ISSUE THREAD

**Issue by Tampliera** [EDDiscovery/EDDiscovery#3167]
### Exception Details:
>EDDiscovery v12.1.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
>   в EDDiscovery.UserControls.UserControlExpedition.toolStripButtonImportNavRoute_Click(Object sender, EventArgs e) в C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlExpedition.cs:строка 473
>   в System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   в System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
>   в System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   в System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   в System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   в System.Windows.Forms.Control.WndProc(Message& m)
>   в System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by Eahlstan** [comment]
Could you upload the journal file from the session that caused this?

Default location shell:SavedGames\Frontier Developments\Elite Dangerous

**Comment by robbyxp1** [comment]
This is fixed on the tip and on Branch12_1 - happens if the last navroute entry was blank.

Thanks for the report.

Will be in the next 12.1.X release.

Closing due to it being fixed.
