### ISSUE TITLE
Linux installation problems - 'System.IO.Compression 4.3.0' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.7.0'. 

### ISSUE THREAD

**Issue by matt32106** [EDDiscovery/EDDiscovery#3169]
Hello there,
I am following the [installation instructions for Linux from the wiki](https://github.com/EDDiscovery/EDDiscovery/wiki/Linux-and-EDD) (Ubuntu 20.04 LTS here) 

When I run nuget restore I get this error:
```
ippo@hippo-camp:~/EDDiscovery$ nuget restore
Installing 'System.Data.SQLite.Core 1.0.113.6'.
Installing 'SharpDX.DirectInput 4.2.0'.
Installing 'OpenTK.GLControl 3.0.1'.
Installing 'OpenTK 3.0.1'.
Installing 'OpenTK 3.3.2'.
Installing 'System.Data.SQLite.Linq 1.0.113.0'.
Installing 'OpenTK.GLControl 3.1.0'.
Installing 'Stub.System.Data.SQLite.Core.NetFramework 1.0.113.3'.
Installing 'CSCore 1.2.1.2'.
Installing 'SharpDX 4.2.0'.
Successfully installed 'SharpDX 4.2.0'.
Successfully installed 'OpenTK.GLControl 3.0.1'.
Successfully installed 'CSCore 1.2.1.2'.
Successfully installed 'OpenTK.GLControl 3.1.0'.
Successfully installed 'System.Data.SQLite.Linq 1.0.113.0'.
Successfully installed 'SharpDX.DirectInput 4.2.0'.
Successfully installed 'OpenTK 3.0.1'.
Successfully installed 'OpenTK 3.3.2'.
Successfully installed 'Stub.System.Data.SQLite.Core.NetFramework 1.0.113.3'.
The 'System.IO.Compression 4.3.0' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.7.0'.
The 'System.IO.Compression.ZipFile 4.3.0' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.7.0'.
'System.Data.SQLite.Core' already has a dependency defined for 'Stub.System.Data.SQLite.Core.NetStandard'.
```
I can't find a way of installing a newer version of nuget.
Any idea?

**Comment by Eahlstan** [comment]
Does it work with a version greater than 2 or are there compatibility issues?

https://www.nuget.org/downloads

**Comment by matt32106** [comment]
I would try if I knew how to install it.

**Comment by Eahlstan** [comment]
I have no Linux, but did you try this?

https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#nugetexe-cli

**Comment by matt32106** [comment]
The latest version does not work but replacing /usr/lib/nuget/NuGet.exe by NuGet Version: 3.3.0.212 was enough to make nuget restore work without error.
But now I have no monobuild file... new issue.

**Comment by klightspeed** [comment]
`dotnet build` is not compatible with mono, and `dotnet-sdk` is not required to build EDDiscovery.

Instructions on how to install the mono repository (from which you can install updated versions of `nuget`, `msbuild`, and `mono-devel`) are at https://www.mono-project.com/download/stable/#download-lin-ubuntu

**Comment by matt32106** [comment]
In my case, the nuget version that gets installed  with the Instructions you suggest is 2.8.7+md510+dhx1-1. This leads to the error in the title when running `nuget restore`

**Comment by matt32106** [comment]
Ok, I made a sanity check and did `sudo apt purge` all involved packages and reinstalled everything from scratch. Now the build process works with quite a few warnings but no error.
