### ISSUE TITLE
No OK buttons on commander setttings in Ubuntu installation

### ISSUE THREAD

**Issue by brightlego** [EDDiscovery/EDDiscovery#3170]
Yesterday, I installed EDDiscovery on Ubuntu, following the given instructions, and now there are no OK or Cancel buttons on the change commander settings.

I also was unable to find 'EDDiscovery/bin/Release', but I did find a 'EDDiscovery.exe' in the debug folder.

**Comment by robbyxp1** [comment]
Its a formatting problem in the controls with Mono under linux. Its known about and on the list to fix.

**Comment by robbyxp1** [comment]
More accurately patch over the poor mono implementation.

**Comment by brightlego** [comment]
Ok. Do you have any ideas about how to work around it?

**Comment by klightspeed** [comment]
The `OK` button is next in the tab sequence after the `Sync to Inara` checkbox, so the easiest way would be to click in the `Inara API Key` text box, press tab twice, then press space.

**Comment by brightlego** [comment]
Thank you. That worked

**Comment by robbyxp1** [comment]
Try the latest master branch, it now patched over it and you should see the ok button.

thanks

**Comment by brightlego** [comment]
I've updated and the problem is fixed.
