### ISSUE TITLE
[Linux][Problem] Can't move the window 

### ISSUE THREAD

**Issue by matt32106** [EDDiscovery/EDDiscovery#3172]
The app displays correctly and I can use the window content, however I can't move the window at all. I tried all the clicks and ctrl shft alt combinations I could think of but the window won't move. Is this a mono 'feature' or what?
I am using Ubuntu 20.04
usr/bin/mono --version
Mono JIT compiler version 6.12.0.122
EDD is 12.1.4

**Comment by klightspeed** [comment]
Given that in your other issues you appear to be using a theme, it seems likely that either Mono is ignoring the result of the `WM_NCHIT` message, or is not able to properly communicate window movement back to your window manager.

Please try editing the theme in the Settings panel, checking `Window Frame`, and clicking `OK`

**Comment by robbyxp1** [comment]
Theme is going to be turned off in mono, its on my next to do this.  Thanks for the report.

**Comment by matt32106** [comment]
I confirm, setting Window Frame to Ok solves the issue.
