### ISSUE TITLE
[linux] Missing UI elements?

### ISSUE THREAD

**Issue by matt32106** [EDDiscovery/EDDiscovery#3174]
The screenshot here shows some missing UI elements in the 4th 5th & 6th columns:
https://i.imgur.com/c8PymLw.png

**Comment by klightspeed** [comment]
Mono's `DataGridViewImageCell` ignores `DefaultCellStyle.NullValue`, and always uses its `image-missing.png` when the cell value is null.

**Comment by robbyxp1** [comment]
fixed
