### ISSUE TITLE
The overall assets value now inlcudes fleet carrier asset

### ISSUE THREAD

**Issue by Soibur** [EDDiscovery/EDDiscovery#3177]
Since odyssey update 7 the fleet carrier asset is also calculated within the statistic site. Therefore, there are deviations on profiles of inara.cz (I just saw it is displayed correctly in EDDiscovery under "Wealth" but the wrong value transferred to inara.)

**Comment by robbyxp1** [comment]
And.. is there anything wrong with EDDiscovery?

**Comment by robbyxp1** [comment]
We just transfer the statistics journal item to Inara.  If Inara is displaying it wrong, please take that up with Inara.

**Comment by Soibur** [comment]
ok I will try my luck, if inara get the data from frontier it is also the right value, thanks

**Comment by klightspeed** [comment]
`Wealth` in the EDDiscovery statistics is taken directly from the `Bank_Account.Current_Wealth` in the the `Statistics` event.  That statistics event is also sent to Inara as-is.

Inara likely needs to update their Wealth calculation to take into account that the `Bank_Account.Current_Wealth` now includes fleet carrier assets, where they previously had to presumably use the Companion API to get the carrier statistics (if you connected Inara to the cAPI).

**Comment by robbyxp1** [comment]
I've told Artie on the Inara discord.  

Closing, not an EDD issue.
