### ISSUE TITLE
Support for fleetcarrier.space

### ISSUE THREAD

**Issue by n0la** [EDDiscovery/EDDiscovery#3178]
https://fleetcarrier.space is a new web app that helps with managing and tracking fleet carriers. It also has a webhook possibility, where you can post information and updates regarding your fleet carrier (movement, events, market changes) to discord. But of course to be up to date it needs info from the player journal.

Would it be possible to support fleetcarrier.space alongside other API pages like Inara?

The market connector has a plugin for fleetcarrier.space:

https://github.com/anthonylangsworth/FCMS/

**Comment by robbyxp1** [comment]
I asked if he wanted to do a plug in, and he declined. 

I can't see the utility of putting a web page browser in unless it would automatically track the current system, as the point of the current browser plug ins it that they automatically take you to the page of the system your in.. 

It looks like fleetcarrier.space is not using a URI encoded string to pick the system up. He's using a POST.

I don't have any time to code this, so I'm afraid its a no from me.

Thanks for the idea.

**Comment by klightspeed** [comment]
This looks like a potential misunderstanding - it sounds like what is wanted is something to submit data to FCMS, not a control to display FCMS

FCMS is interested in `CarrierJumpRequest` and `CarrierJumpCancelled` events, and authenticates using Commander Name / Email Address / API Key.

**Comment by robbyxp1** [comment]
Closing.
