### ISSUE TITLE
Crash when i try to import Nav Tab (big travel with 240 jumps)

### ISSUE THREAD

**Issue by Arkyrua** [EDDiscovery/EDDiscovery#3179]
### Exception Details:
>EDDiscovery v12.1.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>   à EDDiscovery.UserControls.UserControlExpedition.toolStripButtonImportNavRoute_Click(Object sender, EventArgs e) dans C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlExpedition.cs:ligne 473
>   à System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   à System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
>   à System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   à System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   à System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   à System.Windows.Forms.Control.WndProc(Message& m)
>   à System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
Would it please be possible to get a copy of the `NavRoute` event you are trying to import?

**Comment by robbyxp1** [comment]
Known issue, fixed on 12.1 and tip, i'll do another version of 12.x today.

Thanks for the report.
