### ISSUE TITLE
4.1.0 issue on startup

### ISSUE THREAD

**Issue by Gwydify** [EDDiscovery/EDDiscovery#318]
4.1.0 suddenly seems to have developed an issue retrieving data from EDSM, or at least that's what it appears to be.  Application is started up and, after a few minutes, two popups appear:

```
Exception : Value cannot be null.
Parameter name: s at System.IO.StringReader..ctor(String s)
```

And:

```
at EDDiscovery.DB.SystemClass.ParseEDSMUpdateSystemsString(String json, String& date, Boolean removenonedsmids, EDDiscoveryForm discoveryform)
at EDDiscovery2.EDSM.EDSMClass.GetNewSystems(EDDiscoveryForm discoveryform)
at EDDiscovery.TravelHistoryControl.TriggerEDSMRefresh()
at EDDiscovery.TravelHistoryControl.button_RefreshHistory_Click(Object sender, EventArgs e)
```

After these the application will just hang with no further progress being made, it doesn't appear to succeed at actually updating from EDSM:

Checking for new EDDiscovery maps
Checking for new EDSM systems (may take a few moments).
Map check complete.

Refreshing results in the same thing.
I've unchecked the two data to/from EDSM checkboxes and the Get distance pairs from EDSM with the same result.  Upgraded to 4.1.1, again with the same result.

Unclear if it's related to issue #305

**Comment by klightspeed** [comment]
This is a known issue, which should be resolved in the next release.

**Comment by jgoode** [comment]
Looks like this is fixed in the next version. Still testing

**Comment by robbyxp1** [comment]
Closed, old version
