### ISSUE TITLE
Updated to newest portable Version

### ISSUE THREAD

**Issue by Poet68** [EDDiscovery/EDDiscovery#3180]
### Exception Details:
>EDDiscovery v12.1.5.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.IO.FileLoadException: Die Datei oder Assembly "OpenTK, Version=3.0.1.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
>Dateiname: "OpenTK, Version=3.0.1.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4"
>   bei EDDiscovery.FormMap..ctor()
>   bei EDDiscovery._3DMap.MapManager..ctor(EDDiscoveryForm frm) in C:\Code\Examples\EDDiscovery\EDDiscovery\3DMap\MapManager.cs:Zeile 31.
>   bei EDDiscovery.EDDiscoveryForm.Init(Action`1 msg) in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:Zeile 186.
>   bei EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e) in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:Zeile 187.
>
>WRN: Protokollierung der Assemblybindung ist AUS.
>Sie können die Protokollierung der Assemblybindungsfehler aktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) auf 1 festlegen.
>Hinweis: Die Protokollierung der Assemblybindungsfehler führt zu einer gewissen Leistungseinbuße.
>Sie können dieses Feature deaktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] entfernen.
>
>===== END =====
>```

**Comment by klightspeed** [comment]
Please try the portable build at <https://ci.appveyor.com/project/EDDiscovery/eddiscovery/builds/41027195/job/fm2ge47i5q672sqj/artifacts> (or copy the contents of <https://raw.githubusercontent.com/EDDiscovery/EDDiscovery/v12.1_portable_asmbind/EDDiscovery/App.Portable.config> into EDDiscovery.exe.config)

**Comment by Poet68** [comment]
@klightspeed thanks, the portable build works
