### ISSUE TITLE
unhandled ui exception when opening the 3d map

### ISSUE THREAD

**Issue by straef** [EDDiscovery/EDDiscovery#3183]
### Description
opening the 3d map

### Exception Details:
>EDDiscovery v12.1.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.IO.FileLoadException: Could not load file or assembly 'OpenTK.GLControl, Version=3.0.1.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
>File name: 'OpenTK.GLControl, Version=3.0.1.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4'
>   at OpenTKUtils.GL1.LineDataCollection.Dispose()
>   at OpenTKUtils.GL1.LineDataCollection.Add(LineData primative) in C:\Code\Examples\EDDiscovery\BaseUtilities\OpenTKUtils\DataSets\Data3DLineData.cs:line 128
>   at EDDiscovery._3DMap.DatasetBuilder.AddCoarseGridLines() in C:\Code\Examples\EDDiscovery\EDDiscovery\3DMap\DatasetBuilder.cs:line 628
>   at EDDiscovery.FormMap.GenerateDataSets() in C:\Code\Examples\EDDiscovery\EDDiscovery\3DMap\FormMap.cs:line 940
>   at EDDiscovery.FormMap.OnLoad(EventArgs e) in C:\Code\Examples\EDDiscovery\EDDiscovery\3DMap\FormMap.cs:line 366
>   at System.Windows.Forms.Form.OnCreateControl()
>   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>   at System.Windows.Forms.Control.CreateControl()
>   at System.Windows.Forms.Control.WmShowWindow(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.Form.WmShowWindow(Message& m)
>   at ExtendedControls.SmartSysMenuForm.WndProc(Message& m) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Forms\SmartSysMenuForm.cs:line 221
>   at ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Forms\DraggableForm.cs:line 169
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>
>WRN: Assembly binding logging is turned OFF.
>To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
>Note: There is some performance penalty associated with assembly bind failure logging.
>To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
>
>===== END =====
>```

**Comment by robbyxp1** [comment]
Please download the updated portable version. thanks for the report.
