### ISSUE TITLE
Ledger Issue

### ISSUE THREAD

**Issue by redzacke** [EDDiscovery/EDDiscovery#3185]
Dear developers,

EDDiscovery is a great tool! Maybe you could fix the problem that the earnings from shared missions are also shown on the ledger tab. Currently I have a difference of about 300 million credits between EDD and the ingame value.

Good luck and good will to continue with it :-)

o7 Cmdr phoenixXx

**Comment by robbyxp1** [comment]
Also, is it missing the MissionCompleted record when you complete a shared mission? Is this Odyssey (which has a known bug of not writing missioncompleted at times).

**Comment by redzacke** [comment]
maybe I should have told you that I use the portable version ;-) I will now
install the fixed version :-))🤗 Since the database should be rebuilt anyway

Am Do., 14. Okt. 2021 um 21:46 Uhr schrieb Eahlstan <
***@***.***>:

**Comment by redzacke** [comment]
And here again the two files I had previously attached via the Gmail application, which obviously went wrong

![eddiscovery](https://user-images.githubusercontent.com/26506496/137389493-916bd3b5-507e-4b9e-8235-a573c0a03b8d.png)
[Journal.211012153238.01.log](https://github.com/EDDiscovery/EDDiscovery/files/7349160/Journal.211012153238.01.log)

**Comment by Eahlstan** [comment]
Hm, yeah well. As Robby said this could be due to missing informations in the journal file. We would need your journal file from a session when you did such missions to check that.
The journals should be in shell:SavedGames\Frontier Developments\Elite Dangerous
Does the ledger correct the value now if you restart Elite?

**Comment by Eahlstan** [comment]
Sorry didn't see it. Totally my fault :(

**Comment by redzacke** [comment]
the shared missions had a reward of about 30 million CR

**Comment by Eahlstan** [comment]
There are 5 completed wing missions in my ledger screenshot though...

**Comment by Eahlstan** [comment]
Yeah, as I said: Some times the balance is in there, some times it isn't. That's not a good basis to use it.

**Comment by klightspeed** [comment]
> that's my content:
> 
> { "timestamp":"2021-10-15T09:18:18Z", "event":"Status", "Flags":151060741, "Flags2":0, "Pips":[2,8,2], "FireGroup":0, "GuiFocus":5, "Fuel":{ "FuelMain":32.000000, "FuelReservoir":0.770000 }, "Cargo":0.000000, "LegalState":"Clean", "Balance":4214545366, "Destination":{ "System":2870514820521, "Body":37, "Name":"Hamilton Gateway" } }

Only in Odyssey (not Horizons), only while logged into the game, and only for the currently active client (good luck if you run multiple clients under the same Windows account).

**Comment by Eahlstan** [comment]
And the most important reason why this is a no go: The status file doesn't mention which commander it belongs to. So if I play with commander A and switch to commander B in EDDiscovery commander Bs balance would be updated with the balance from the status file made by commander A.
