### ISSUE TITLE
Progress journal entry missing Odyssey ranks

### ISSUE THREAD

**Issue by lolPants** [EDDiscovery/EDDiscovery#3186]
The progress journal entry is missing the new Odyssey ranks, Mercenary and Exobiologist.

```
{"timestamp":"2021-10-13T16:55:53Z","event":"Progress","Combat":7,"Trade":78,"Explore":22,"Soldier":17,"Exobiologist":14,"Empire":65,"Federation":40,"CQC":14}
```
> ^ Example journal JSON

![image](https://user-images.githubusercontent.com/2358182/137186029-2ac708e7-93ef-4124-a2fa-5d5101a78289.png)
> ^ Current EDDiscovery entry text

**Comment by robbyxp1** [comment]
Noted in projects, closing.
