### ISSUE TITLE
Fix import of CVS files in explortation and expedition (+ others check)

### ISSUE THREAD

**Issue by Eahlstan** [EDDiscovery/EDDiscovery#3188]
If you have an expedition containing systems with a bookmark note that has more than one line abd you want to export that expedition as a csv the bookmark note doesn't get stripped off the line breaks.
It should look something like test1.csv, but it actually looks like test2.csv
And of course reimporting that file creates a wrong expedition.
[test1.csv](https://github.com/EDDiscovery/EDDiscovery/files/7360572/test1.csv)
[test2.csv](https://github.com/EDDiscovery/EDDiscovery/files/7360573/test2.csv)

**Comment by robbyxp1** [comment]
Mine import the same for both

The CSV looks right

Is this a comma thing, its Comma Separated Values, not semicolon..

**Comment by robbyxp1** [comment]
move to project.
