### ISSUE TITLE
An unhandled fatal exception has occurred.

### ISSUE THREAD

**Issue by Fito-wolf** [EDDiscovery/EDDiscovery#3189]
An unhandled fatal exception has occurred.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: database is locked
database is locked ---> System.Data.SQLite.SQLiteException: database is locked
database is locked
   en System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   en System.Data.SQLite.SQLiteDataReader.NextResult()
   en System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   en System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   en System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   en System.Data.SQLite.SQLiteTransaction.Commit()
   en EliteDangerousCore.JournalMonitorWatcher.<>c__DisplayClass17_0.<ScanReader>b__0(UserDatabaseConnection cn) en C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDJournalMonitorWatcher.cs:línea 208
   en SQLLiteExtensions.SQLProcessingThread`1.<>c__DisplayClass26_0.<ExecuteWithDatabase>b__0() en C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:línea 263
   en SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() en C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:línea 66
   --- Fin del seguimiento de la pila de la excepción interna ---
   en SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() en C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:línea 89
   en SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) en C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:línea 247
   en SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase(Action`1 action, Int32 warnthreshold) en C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:línea 264
   en EliteDangerousCore.JournalMonitorWatcher.ScanForNewEntries() en C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDJournalMonitorWatcher.cs:línea 120
   en EliteDangerousCore.EDJournalUIScanner.ScanTickWorker(Func`1 stopRequested) en C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Scanner\EDScanner.cs:línea 106
   en EliteDangerousCore.EDJournalUIScanner.ScanThreadProc() en C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Scanner\EDScanner.cs:línea 0
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
No response
