### ISSUE TITLE
Life hazard on entry

### ISSUE THREAD

**Issue by MaXxProsTe** [EDDiscovery/EDDiscovery#3199]
I'd like you to add into the GALmap a "flag" to warn voyagers (in advance) about entering "**Exarg KA-A c0**" because entry point is just in the middle of the suns and you will- almost immediatelly get at least 123% of heat "pressure". Someone with less precise equipped ship for DSexp and someone less experienced or prone to rashness, would end in dissaster, because I did got scared about my Expdata :-D
![ED 100](https://user-images.githubusercontent.com/93586922/139835676-da0a1b82-9c58-4ead-8cc3-9ac0308e2427.jpg)

**Comment by klightspeed** [comment]
You might want to submit that to the Galactic Mapping Project <https://forums.frontier.co.uk/threads/the-galactic-mapping-project-historical-archive-of-exploration.116450/page-279#post-9582749> - EDDiscovery gets its POIs from an API on EDSM, which contains the data presented on EDSM's galactic map.

**Comment by robbyxp1** [comment]
Thanks for the info, as said, we take POIs from EDSM.  Thats the curated list we use.

closing thanks
