### ISSUE TITLE
Crash after unhandled exception

### ISSUE THREAD

**Issue by Ratterkresch** [EDDiscovery/EDDiscovery#3200]
An unhandled fatal exception has occurred.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: database disk image is malformed
database disk image is malformed ---> System.Data.SQLite.SQLiteException: database disk image is malformed
database disk image is malformed
   bei System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   bei System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   bei System.Data.SQLite.SQLiteDataReader.Read()
   bei EliteDangerousCore.DB.SystemsDB.GetSystemVector[V](Int32 gridid, V[]& vertices1, UInt32[]& colours1, Int32 percentage, Func`4 tovect, SQLiteConnectionSystem cn) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByGrid.cs:Zeile 78.
   bei EliteDangerousCore.DB.SystemsDB.<>c__DisplayClass30_0`1.<GetSystemVector>b__0(SystemsDatabaseConnection db) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByGrid.cs:Zeile 36.
   bei SQLLiteExtensions.SQLProcessingThread`1.<>c__DisplayClass26_0.<ExecuteWithDatabase>b__0() in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:Zeile 263.
   bei SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:Zeile 66.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:Zeile 89.
   bei SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:Zeile 247.
   bei SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase(Action`1 action, Int32 warnthreshold) in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:Zeile 264.
   bei EliteDangerousCore.DB.SystemsDB.GetSystemVector[V](Int32 gridid, V[]& vertices1, UInt32[]& colours1, Int32 percentage, Func`4 tovect) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByGrid.cs:Zeile 38.
   bei EDDiscovery.StarGrid.FillFromDB() in C:\Code\Examples\EDDiscovery\EDDiscovery\3DMap\StarGrid.cs:Zeile 88.
   bei EDDiscovery.StarGrids.ComputeThread() in C:\Code\Examples\EDDiscovery\EDDiscovery\3DMap\StarGrid.cs:Zeile 580.
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by Eahlstan** [comment]
Seems like your systems DB is gone.
You could try to repair it using external SQLite tools, or just delete it by either going to your appfolder (default %loacalappdata%\EDDiscovery ) and deleting EDDSystem.sqlite or by holding shift while clicking on the icon that starts EDD and selecting "delete/rebuild system DB" in the safe mode menu.

**Comment by robbyxp1** [comment]
Please delete and rebuild the DB.

Thanks
