### ISSUE TITLE
Error in EDDiscovery v12.1.5.0 

### ISSUE THREAD

**Issue by M4DV1K** [EDDiscovery/EDDiscovery#3202]
### Description

Hi. 
Have a problem when close the EDDiscovery. When i push buttom "Close", it asking me "Program update data from EDDB and EDSM. Press "Ok" for exit now or "Decline" for waitinf until updating will not finish". 
I press "Yes" and on next window write Error
P.S. I can reinstall program into Enlish version if it's necessary.

### Additional Information

[https://flic.kr/p/2mJufeX](url)

### Exception Details:
>EDDiscovery v12.1.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "System.Speech, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" либо одну из их зависимостей. Не удается найти указанный файл.
>Имя файла: 'System.Speech, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
>   в AudioExtensions.VoiceRecognitionWindows.Close()
>   в EDDiscovery.EDDiscoveryForm.Controller_FinalClose() в C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:строка 854
>
>Предупреждение: регистрация привязки сборок выключена.
>Чтобы включить регистрацию ошибок привязки сборок, установите значение параметра реестра [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) в 1.
>Примечание. Регистрация ошибок привязки сборок может привести к некоторому снижению производительности.
>Чтобы отключить эту функцию, удалите параметр реестра [HKLM\Software\Microsoft\Fusion!EnableLog].
>
>===== END =====
>```

**Comment by robbyxp1** [comment]
Its saying that it can't load the DLL System.Speech.

This means there is something wrong with your windows installation.  One thing you could try is to reinstall .net 4.8 from microsoft website.

Note. EDD is for windows 10/11 only.

**Comment by M4DV1K** [comment]
Thank's a lot for assistant. 
It's realy problem with my 8.1 Windows. I try to install .net 4.8 but it's error in instalation. Very interesting for me. 
Any how, thank's and sorry for disturbing.
