### ISSUE TITLE
Update the INARA plugin so that it is possible to sort columns displayed on INARA page

### ISSUE THREAD

**Issue by BZSm1ith** [EDDiscovery/EDDiscovery#3203]
Not sure how easy it would be.   

But when using INARA on a browser.  It is possible to sort data columns (fo example, when viewing minor faction details, you can sort by  System name, economy etc)

However, this is not possible with the INARA plugin on EDDiscovery

**Comment by robbyxp1** [comment]
The panel is just a web page, so it might not be working due to incompatibilites between the web browser and Inara. Not much i can do. Sorry.
