### ISSUE TITLE
Not sending correct asset information to Inara

### ISSUE THREAD

**Issue by Pichu0102** [EDDiscovery/EDDiscovery#3206]
EDDiscovery isn't sending the correct credits information to Inara, leading to it getting confused about how many credits you have if you also have Inara's Frontier data import option enabled. Example below.

![screenshot 5724](https://user-images.githubusercontent.com/4944941/143769593-308814e3-03d9-4821-9753-09d27ed6f749.png)

**Comment by robbyxp1** [comment]
We know, Artie knows, I thought he had fixed this at his end, i will review it.

thanks

**Comment by Eahlstan** [comment]
Just to be sure: Is the amount of credits shown in EDD after you start Elite correct?

**Comment by robbyxp1** [comment]
see 12.1.6
