### ISSUE TITLE
Better Shopping List

### ISSUE THREAD

**Issue by wisquimas** [EDDiscovery/EDDiscovery#3209]
In the shooping list i need to update my recipes. I want to put the human module: DETAILED SURFACE SCANNER (ENGINEERED V1)

I think if you do an importation, exportation system in csv it would be great.

**Comment by Eahlstan** [comment]
I took a look at the list, the DSS was indeed missing. I added it in, so it will be fixed in the next release. Thanks for mentioning it.
Did you notice anything else missing?

As for the import/export thing: I can't say anything on this, that's Robbys territory.

**Comment by robbyxp1** [comment]
Thanks for the head up about the missing recipes

The idea of exporting the table i'll add to the project list.
