### ISSUE TITLE
EDDiscovery 12.1.7 (Portable) crashes 

### ISSUE THREAD

**Issue by ManweS** [EDDiscovery/EDDiscovery#3211]
I run the portable version of EDD at the same time as EDO,  EDD crashes, becomes unresponsive, and has to be closed using Windows Task Manager.
This problem has persisted over several update versions of EDD.

**Comment by robbyxp1** [comment]
We will need more details about this to do anything. Please give us the logs which you can find in the data folder of the portable install.  Inside the data/log folder.

**Comment by ManweS** [comment]
Hello Rob,

Thank you for your quick response.

I have attached the Log subdirectory as a zip.

Regards,
Manwe

**Comment by Eahlstan** [comment]
Seems like this didn't work, there's no zip file anywhere.

**Comment by ManweS** [comment]
I've attached it again to this reply.
It is named "Log.zip"

**Comment by Eahlstan** [comment]
Still not here.
Might not work if you're replying by email.

**Comment by ManweS** [comment]
Yes I have been replying to emails.
This is directly in github
[Log.zip](https://github.com/EDDiscovery/EDDiscovery/files/7745388/Log.zip)
.

**Comment by Eahlstan** [comment]
Ok, I got it. Now please delete it as you included the whole directory which includes the .hlog files which contain all your API keys.

**Comment by Eahlstan** [comment]
Are you using a HDD or a SSD?
Your DB is extremely slow.

**Comment by ManweS** [comment]
I'm using an external SSD.
I've been using this system for quite some time, nearly two years.  It has only started with this error in the last couple of months.

**Comment by Eahlstan** [comment]
One thing you can try is
Admin menu -> Rebuild System DB Indexes

You could also use a tool like AS SSD to see if something is wrong with your setup by testing the latency of your external SSD.

If your SSD is fine and the index rebuild didn't help your DB is most likely damaged beyond repair. In that case either rename or delete EDDUser.sqlite to start from scratch.

**Comment by ManweS** [comment]
Thank you.  I'll try those options.

**Comment by ManweS** [comment]
Rebuild System DB Indexes didn't work.
AS SSD test showed the SSD ok.
The final brutal option of deleting EDDUser.sqlite and starting from scratch appears to have worked.
Is there anything I can do to prevent this problem from reoccurring?
Again, thank you for your prompt attention.

**Comment by Eahlstan** [comment]
Never close EDD by force.
Never disconnect your SSD while EDD is running.
Never disconnect your SSD without safely removing it first. (Like it's described [here](https://www.seagate.com/gb/en/support/kb/how-to-safely-disconnect-an-external-drive-from-your-computer-192211en/).)

IT surely can be randomly damaged, but those things greatly reduce the risk.

**Comment by Eahlstan** [comment]
> Rebuild System DB Indexes didn't work. AS SSD test showed the SSD ok. The final brutal option of deleting EDDUser.sqlite and starting from scratch appears to have worked. Is there anything I can do to prevent this problem from reoccurring? Again, thank you for your prompt attention.

I'm sorry. I misinformed you. I should have said "Rebuild User DB index".
Although I doubt that i would have helped I'm really sorry about that.

**Comment by ManweS** [comment]
I do follow the protocols relating to the SSD.
Closing EDD by force.  Does this include the window close button in the top right hand corner?
I vaguely understand the need to close databases carefully.
What would be the recommended method of shutting down?
Re the indexing name mistake, not a problem  :-)

**Comment by robbyxp1** [comment]
Sometimes the DBs can get corrupted. 

As long as you use the X to close, it will close down properly. Corruption can occur if its in the middle of a DB write and the program is terminated.  Normally the DB copes with it, but sometimes it does not, at random.

Closing this as it seems solved, even if by brute force.

thanks
