### ISSUE TITLE
Probe diagram to show where to shoot DSS probes at

### ISSUE THREAD

**Issue by RPeterson0487** [EDDiscovery/EDDiscovery#3212]
I was thinking about this while I was playing with the compass feature, and then again while I was DSSing a planet.  Would it be possible (as far as programming goes) to create an overlay where you could set / draw the size of the planet you are facing, and the efficiency target of said planet.  Then, the overlay (in my mind, drawn to match the planet diameter, somehow)  would show where to shoot the probes to the most efficient pattern for scanning.  I'm picturing a version of this chart.
![image0-3](https://user-images.githubusercontent.com/69528095/147042720-023177c4-1002-4a6d-9d03-64a3de13b5d0.jpg)
I'm sure it can't be done easily, but thought it would be a neat idea.  If I was better at programming, I'd take a shot at it for fun, but I still have a lot to learn, there.

(Feel free, of course, to close and / or delete this)

**Comment by robbyxp1** [comment]
Thats a neat idea, but a lot of work. I'll move it to the projects section.
