### ISSUE TITLE
RES SITES SHOWING

### ISSUE THREAD

**Issue by delaware1999** [EDDiscovery/EDDiscovery#3213]
Hello I am playing a lot of massacre missions lately with my Type 10 AFK build.
I am using this sites : https://edtools.cc/pve  and https://edtools.cc/res  to find res sites and massacre mission givers.

Why don´t you install into your EDDiscovery a extra " tab " that saves all visited RES Sites and creates a good list to find them easier.
If other player finds a RES LOW HIGH .... Site it should be also save in some kind of Data Base into EDDiscovery so that me and all other players can see it when we would use EDDiscovery with the RES showing Tab..

This is only a suggestion because there are no good tools to find massacre mission givers and the Res Sites...

Hope you can install such a thing.. Sorry for bad english, this is not my mother language...

**Comment by robbyxp1** [comment]
Thanks
I'll add it to the project backlog.  Note its long!

**Comment by robbyxp1** [comment]
Closing, now in project list

**Comment by robbyxp1** [comment]
We don't get enough information from elite on resource extraction sites. We don't get their location. I don't think this is possible but i'll keep it in mind.

**Comment by delaware1999** [comment]
Yes I understand that Elite is not giving you enough informations. But it is already enough if a database would containt the following information : System name - How many res sites and which ones ( low / high etc )  
More is not needed.. And this information is Elite not giving ? They show it on the left panel..

**Comment by Eahlstan** [comment]
Open a new history tab, show only FSS Signal Discovered events, search for "Resource", export it.

![Screenshot 2021-12-25 130542](https://user-images.githubusercontent.com/59618179/147384529-2cb80af4-5a77-4b46-9499-01c0ebd28f5a.JPG)

Delete all unneeded columns and you'll end up with something like this.
![Screenshot 2021-12-25 130601](https://user-images.githubusercontent.com/59618179/147384581-79122b7e-7607-49db-a279-3e5868148c5b.JPG)

That's the best you can do with EDD, given that this is a extremely rare use case it's just not worth the time and resources to code something for it in EDD itself, sorry.

**Comment by delaware1999** [comment]
Ok great this works for me.. I can get the list in a excel Data file.
This is too much work.. Why cant you programm in the next month something that shows this in a new TAB ? 
The data is there.. it must only me used correctly..  I dont know much about coding and if this is possible.. But its only a suggestion for something very new and very helpfull..

Thanx for your support.
