### ISSUE TITLE
[Scan Tab] Show EDSM Total Body Count, if available

### ISSUE THREAD

**Issue by MinerMax555** [EDDiscovery/EDDiscovery#3214]
When I'm in a system, after I honked it, EDD shows me how many bodies there are in total. When using the scan tab to show me the EDSM data of a system I have not visited yet, this information is not present, even though the EDSM website (and API and dump as well) does contain this information (for most systems).

I'm currently trying to complete the scan data of the H- and G-Systems of sectors, and seeing if these scans are already complete in EDSM (both in the Scan Tab and ideally also in the Exploration Tab) would be a great addition to plan my exploration runs better.

**Comment by robbyxp1** [comment]
Thanks. I've made a note in projects, and we will try and fix something
