### ISSUE TITLE
Missing "ok" button when creating or editing a new profile

### ISSUE THREAD

**Issue by tvienneau404** [EDDiscovery/EDDiscovery#3217]
As the title states.

Built from AUR package on Manjaro.

**Comment by robbyxp1** [comment]
More information would be good.

So its linux.
Commander editing form ?
Which branch? 12.1?

We know the OK button is missing due to an error in Mono implementation of winforms.  I'm trying to remind myself if we patched that over on master.  

Master will not build on linux at the moment, its under development.

**Comment by robbyxp1** [comment]
Addition on master for patching over the mono issue.

Applied to EliteDangerousCore CommanderForm.cs

     protected override void OnShown(EventArgs e)
+        {
+            base.OnShown(e);
+            if (Environment.OSVersion.Platform != PlatformID.Win32NT)
+            {
+                extPanelScroll.Dock = System.Windows.Forms.DockStyle.None;
+                panelOK.Dock = System.Windows.Forms.DockStyle.None;
+                int bh = 50;
+                int vsplit = ClientRectangle.Height-bh;
+                int width = ClientRectangle.Width;
+                extPanelScroll.Bounds = new System.Drawing.Rectangle(0,0,width,vsplit);
+                panelOK.Bounds = new System.Drawing.Rectangle(0,vsplit,width,bh);
+
+            }
+        }

**Comment by tvienneau404** [comment]
> More information would be good.
> 
> So its linux. Commander editing form ? Which branch? 12.1?
> 
> We know the OK button is missing due to an error in Mono implementation of winforms. I'm trying to remind myself if we patched that over on master.
> 
> Master will not build on linux at the moment, its under development.

Yes, the commander editing form
Branch 12.1

12.1.3 to be exact

**Comment by robbyxp1** [comment]
I have applied the patch to Branch_12_1, and it works in Debian.

I'd checkout that branch and see if it fixes your issue.

Thats all i can offer you.

**Comment by robbyxp1** [comment]
closing.
