### ISSUE TITLE
Notepad Idea

### ISSUE THREAD

**Issue by Cowski4444** [EDDiscovery/EDDiscovery#3219]
I keep a notebook dedicated to Elite with me.  I jot random things down when I'm playing.  Random thoughts of what I will do when I get docked again, where to explore, etc.  Sometimes I'll quit a game with plans to get back in in a few hours or the next day.  Sometimes it can be a few days or even a  week or so before I get back in.  It would be cool if I could put notes in of what I was doing last and what I was thinking when I quit the game.  
It would be great if EDDiscovery had a built in notepad.  Nothing fancy, a simple notepad.  But if you could make it a feature-rich text editor, that would be icing on the cake.
Thanks!

**Comment by Eahlstan** [comment]
https://github.com/EDDiscovery/EDDiscovery/wiki/Using-the-Captains-Log-Panel

**Comment by robbyxp1** [comment]
Answer given!
