### ISSUE TITLE
Ideas for Note in System Info tab

### ISSUE THREAD

**Issue by UnknownGuardianTV** [EDDiscovery/EDDiscovery#3220]
Thought of sharing an idea to relieve confusion and/or clutter for Note in System Info [Just one of them, not all of them]:
- Add new separate box for "EDSM Note" if sync from EDSM is enabled
- Add few empty lines or dash to separate EDSM-sync note from original note in same note box [Like adding one ENTER]
- Highlight sync-from-EDSM note

Reason: Some notes I made was overcrowded of two same messages: original message and EDSM-sync message.

Other idea is adding an option to sync note to all different-time-visitings of same systems, so i can track what system have. That would save time from searching first-note of same system.

**Comment by robbyxp1** [comment]
Thanks, added to worklist.
