### ISSUE TITLE
Bookmark: planetary body show just a list of number

### ISSUE THREAD

**Issue by tecnosegugio** [EDDiscovery/EDDiscovery#3223]
In the Bookmark tab, the list of "Planetary Bodies" in the "Surface bookmarks in system" show just a list of number and not the whole name of the bodies. 

Example: I'm in BAIJUNGU system and I want to add a bookmark on the surface of BAIJUNGU B 1 body, so I click on the icon "New bookmark" and enter BAIJUNGU in the first field of the form. 
Then in the "Surface bookmarks in system" section I would like to enter the body name selecting from the list of bodies but what I see  is a list like:
A
1
A
2
3
... etc

What I was expecting is a list like:
BAIJUNGU A
BAIJUNGU A 1
BAIJUNGU A 1 A
BAIJUNGU A 2
BAIJUNGU A 3
... etc

and I remember this was the way it was working many weeks ago.
Could this behaviour turned back as it was before?

P.S.: thank you for this little jewel of software. ;-)

**Comment by Eahlstan** [comment]
Additional note:

The list repeats itself.

https://www.edsm.net/en/system/bodies/id/71694355/name/Phroea+Flyuae+RF-M+d8-104

![Screenshot 2022-01-17 225340](https://user-images.githubusercontent.com/59618179/149840887-9212e7d1-7703-4709-b0e5-d0916615a16f.JPG)

**Comment by robbyxp1** [comment]
The repeat is wrong, the fact it removes the prefix is right. Your in the system, there is no need to repeat the main body name.

Added to backlog.

**Comment by tecnosegugio** [comment]
Il giorno mar, 18/01/2022 alle 01.48 -0800, Rob ha scritto:
> The repeat is wrong, the fact it removes the prefix is right. Your in the
> system, there is no need to repeat the main body name.

OK but at least write the complete body name except the system name.
The first moon of the first planet should be :

1 A

and not only 

A


-- 
-=) Pierpaolo AKA il Tecnosegugio (=-

**Comment by robbyxp1** [comment]
Yep. i'll look into it soon

**Comment by robbyxp1** [comment]
Fixed on master, new version out in the next few weeks.
