### ISSUE TITLE
Feature Request - Compass - Name of Target

### ISSUE THREAD

**Issue by RenaeMacLeod** [EDDiscovery/EDDiscovery#3224]
When using the compass in game it would be great to have the name of the target shown, perhaps just below the arrow that marks the direction...

|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
            12.2 km    ^    Name

**Comment by klightspeed** [comment]
As in add a Target Name text box, which is populated when you select a bookmark, then display that name on the compass?

**Comment by RenaeMacLeod** [comment]
Yes, perfect. I was thinking of a body with multiple bookmarks.

I hadn't considered the text field. I tried manually putting lat/lon in the fields but it wasn't working for me. I presume it works for others. I didn't test much to find out why it wasn't working, as I was on a mission. I plan to properly test this and the other issues I was seeing and post other items in here with more info if/when I find anything else that would be helpful.

**Comment by robbyxp1** [comment]
Closing.

**Comment by klightspeed** [comment]
> Closing.

I believe this was a feature request.
