### ISSUE TITLE
[False Positive] Trojan in last version od EDDiscovery

### ISSUE THREAD

**Issue by Marval89** [EDDiscovery/EDDiscovery#3228]
When trying to download last version my antyvirus software says that there is:

TrojanDownloader:MSIL/Tnega!MSR

**Comment by klightspeed** [comment]
False positive in Windows Defender's cloud-based scanning.

Does https://eddiscovery.space/EDDiscovery.Portable.12.1.7.zip trigger the same warning - that's exactly the same file, just hosted on a different server.

**Comment by robbyxp1** [comment]
AV Software are just what they are. Nothing much we can do about them .  As you can see virustotal was happy with it at the time.

Closing as there is not much to be done about this.

**Comment by philcart** [comment]
> False positive in Windows Defender's cloud-based scanning.
> 
> Does https://eddiscovery.space/EDDiscovery.Portable.12.1.7.zip trigger the same warning - that's exactly the same file, just hosted on a different server.

Just providing some feedback on this. The above link didn't trigger the virus warning while the in-game link did.

**Comment by Eahlstan** [comment]
The miracles of stupid heuristics 🤮

**Comment by klightspeed** [comment]
> in-game

I presume you're calling EDDiscovery a game?
