### ISSUE TITLE
EDDSystem.sqlite is just too big

### ISSUE THREAD

**Issue by mouarfff** [EDDiscovery/EDDiscovery#3231]
Same issue has some ppl some years ago...
We need to have possibility to change this from appdata to another place easely please
(better : having the choice for a profile location
(this game is crazy hard enough s :D )

thx for the work !

**Comment by klightspeed** [comment]
Moving databases: Hold shift while starting EDDiscovery, click Move Databases, and select a new location

Changing profile location: either add an `-AppFolder` option to the shortcut with the path to the new profile directory, or create an `options.txt` in the EDDiscovery program directory with containing the line `AppFolder` with the new profile directory

**Comment by robbyxp1** [comment]
Or read the wiki! https://github.com/EDDiscovery/EDDiscovery/wiki/Move-databases

Closing, not an issue. Thanks.

**Comment by mouarfff** [comment]
It's an issue because it's difficult to find this
if it was easy, i didn't ask you here

**Comment by Eahlstan** [comment]
You're looking for a setting, the logical way is to go to the settings panel.
It's literally written there how to move the DBs...
![Screenshot 2022-02-25 185244](https://user-images.githubusercontent.com/59618179/155763459-b67a5b4f-87e4-4965-a053-01f55f51e87a.JPG)
That's not difficult at all.

**Comment by mouarfff** [comment]
"That's not difficult at all."
Lol
this game is difficult, we have thousand web site and colmplicated app, time wasted to undertsand these ...
after lost bdd, waste hours, to understand. see what the app often freeze
I don't play a game

you should make this option directly in parameters and AFTER, ask for restart in safe mode.

**Comment by robbyxp1** [comment]
Right. Being rude is not an option here. We are all doing this for free. We do it because we like to help other people. We have given you assistance, the only thing you needed to do is to say thank you.

Any more comments and your banned from this github. Please don't comment again.
