### ISSUE TITLE
CAPI not signing in

### ISSUE THREAD

**Issue by SciPhi1980** [EDDiscovery/EDDiscovery#3235]
I'm not sure if its EDD or Frontiers site with the issue, but EDD is not letting me sign into CAPI. It just hangs. 
 Other API have authenticated correctly, just not EDD.

**Comment by robbyxp1** [comment]
Delete all files in %LOCALAPPDATA$\EDDiscovery\CAPI  (for a standard install) and try again.

**Comment by Eahlstan** [comment]
Also: We had people whose browsers somehow acted up on delivering the needed file to EDD, so try changing your default browser.

**Comment by SciPhi1980** [comment]
All that was suggested failed last night, but after a restart it seems to be working, so it was more than likely my computer. Thank you for your help.

**Comment by robbyxp1** [comment]
NP.
