### ISSUE TITLE
TrojanDownloader:MSIL/Tnega.ARP!MTB

### ISSUE THREAD

**Issue by TehnoMag** [EDDiscovery/EDDiscovery#3240]
containerfile: EDDiscovery.Portable.12.1.7.zip
file: EDDiscovery.Portable.12.1.7.zip->EDDiscovery.exe

**Comment by robbyxp1** [comment]
Antiviruses are a mind of their own.  Nothing we can do about it. You can see the virustotal view of the file.

thanks for the report.

**Comment by TehnoMag** [comment]
Heh, indeed. MS Defender detect the Trojan only on Downloading. After unpacking everything is normal.
