### ISSUE TITLE
ED crash

### ISSUE THREAD

**Issue by azanian** [EDDiscovery/EDDiscovery#3242]
### Exception Details:
>EDDiscovery v12.1.7.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentNullException: Value cannot be null.
>Parameter name: key
>   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
>   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
>   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
>   at EliteDangerousCore.Inara.InaraSync.NewEntryList(HistoryEntry he, Dictionary`2 mcmr) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\InaraSync.cs:line 599
>   at EliteDangerousCore.Inara.InaraSync.NewEvent(Action`1 logger, HistoryList hl, HistoryEntry he) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\InaraSync.cs:line 69
>   at EDDiscovery.EDDiscoveryForm.Controller_NewEntrySecond(HistoryEntry he, HistoryList hl) in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryFormJournalEvents.cs:line 116
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 114
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 74
>   at EliteDangerousCore.EDJournalUIScanner.IssueEvents(Tuple`2 entries) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Scanner\EDScanner.cs:line 146
>===== END =====
>```

**Comment by klightspeed** [comment]
Would it please be possible to get the lines from the journal from around when that occurred?

**Comment by robbyxp1** [comment]
Fails at
                        var mr = mcmr.Values.Where(x => x.Details.IsMicroResources).ToList();

mcmr must be null.  

    public static bool NewEvent(Action<string> logger, HistoryList hl, HistoryEntry he)
        {
            var mcmr = hl.MaterialCommoditiesMicroResources.GetDict(he.MaterialCommodity);
            List<JToken> events = NewEntryList(he, mcmr);
            if (events.Count > 0)
                Submit(events, logger, he.Commander, false);
            return true;
        }

mcmr is got from hl/me, now GetDict, uses .Get on a generational dictionary, which always returns a dictionary.

so v.confused.  can't see a path for mcmr to be null.

**Comment by klightspeed** [comment]
> 

The line number is misleading - the error comes from `Dictionary.TryGetValue` with a null key, not a null dictionary.

**Comment by robbyxp1** [comment]
thanks

**Comment by robbyxp1** [comment]
So, if Name was missing from the journal entry for Buy, then Resource.Name would be null.

Same with buy.

The easiest way is to make sure Name is never null in JournalMicroResources.Normalise.  Put in a 'Missing Microresource Journal Error' substitute.

**Comment by robbyxp1** [comment]
I find no missing Names in my or Ealhstans journals. Its most puzzling where this is coming from. If we had the journal logs that would be good.

**Comment by robbyxp1** [comment]
Frontier has introduced a new format of Buymicroresources, which is causing this if you buy from a fleet carrier.

Next version will fix it. In the meanwhile, just restart EDD and it will happily continue.
