### ISSUE TITLE
Shopping list does not count micro resources in storage

### ISSUE THREAD

**Issue by Bredo70** [EDDiscovery/EDDiscovery#3243]
Materials tab and Engineering tab both count the correct number of micro resources in storage, but the "Needed Mats:" list in Shopping list tab, still lists every micro resource as needed even though more than enough is in storage.

**Comment by Eahlstan** [comment]
Could you please provide screenshots?

**Comment by Bredo70** [comment]
Example showing weapon upgrade

Materials tab: Micro resources gives the correct number in storage
![image](https://user-images.githubusercontent.com/44196261/160300505-6aa3e5f5-89e7-4d0a-9c1f-b159ce367812.png)

Engineering tab: 1 upgrade wanted, available resources listed correctly
![image](https://user-images.githubusercontent.com/44196261/160300527-51d490c9-fd47-4921-94d0-4b0423fabdba.png)

Shopping list tab: Needed mats lists 1 Weapon Schematic even though I have 18 in storage
![image](https://user-images.githubusercontent.com/44196261/160300542-59680c36-87cf-40ff-930a-a155450647b6.png)

**Comment by Eahlstan** [comment]
You might have some things as wanted that you're not aware of?
Could you please press both "Clear" buttons on the shopping list to set everything to zero and tell me if that resolved the issue?

**Comment by Bredo70** [comment]
This is what I've tried before submitting a request:
- Pressed "Clear" multiple times
- Rebuilding DB indexes
- Restarting ED while EDDiscovery was running
- Restarting EDDiscovery while ED was running
- Restarting my PC

Still the same strange issue.

**Comment by Eahlstan** [comment]
Mind to upload your latest journal file?
(I don't haver micro resources :D )

**Comment by Bredo70** [comment]
I have several from today (as I have restarted a couple of times); If you need, I'll zip my entire folder, but here is one:

[Journal.2022-03-27T221235.01.log](https://github.com/EDDiscovery/EDDiscovery/files/8358531/Journal.2022-03-27T221235.01.log)

And just to be clear, this is a minor annoyance. EDDiscovery is absolutely fantastic. I can't imaging playing without it :-)

**Comment by Eahlstan** [comment]
Could confirm the issue, thanks for the report.

**Comment by robbyxp1** [comment]
Thanks for the report, its now fixed on the tip. New 15 test version out later in the week.
