### ISSUE TITLE
Missing selection for visited star list to filter out codex entries

### ISSUE THREAD

**Issue by Dextramorphane** [EDDiscovery/EDDiscovery#3245]
Version 12.1.0
![version 12 1 0](https://user-images.githubusercontent.com/75636751/161641573-31f75ef1-65a7-4fdf-b3f7-8cee74ca0f21.jpg)

Version 12.1.7 filters NO
![Version 12 1 7 NO1](https://user-images.githubusercontent.com/75636751/161641537-e6b46bb9-e868-4dcc-a33d-b3e47338cbf6.jpg)
![Version 12 1 7NO2](https://user-images.githubusercontent.com/75636751/161641617-e2a85469-a576-4358-8ade-5d7ea639988a.jpg)

Version 12.1.7 Stars and valuable filters
![Version 12 1 7Stars and valuable1](https://user-images.githubusercontent.com/75636751/161641679-58bd47af-af56-46f3-976a-31f1dca7b594.jpg)
![Version 12 1 7Stars and valuable2](https://user-images.githubusercontent.com/75636751/161641706-01edbacd-25d8-4339-aab9-c2c6400b06ad.jpg)

Hello
This is a screen of the 12.1.0 version. Il like it beacause the Star List is very simple. I can see only what i want : stars and valuable planets
In the new 12.1.7 version of EDDiscovery the filters don't work and I have a lot of informations that I don't want and I can't easily see the valuable planets
So I keep using 12.1.0 version
I hope this will be fix in the next version
Thank you for your job, this programm is very usefull !!

**Comment by Eahlstan** [comment]
Thanks for the report.

@robbyxp1 This is due the new UI not adding the panel ID (?) to the DB name when storing it.

1 and 2 are my VisitedStars panels, 3 is the value that gets saved to the DB.
![Screenshot 2022-04-05 012450](https://user-images.githubusercontent.com/59618179/161648512-3ce7c5d6-dc6d-46ba-8574-8be4ea1cc0db.JPG)

**Comment by robbyxp1** [comment]
Fixed on tip, thanks
