### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by Leerensucher** [EDDiscovery/EDDiscovery#3248]
### Exception Details:
>EDDiscovery v12.1.7.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>   bei EDDiscovery.UserControls.UserControlMiningOverlay.Display(HistoryEntry he) in C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlMiningOverlay.cs:Zeile 142.
>   --- Ende der internen Ausnahmestapelüberwachung ---
>   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>   bei System.Delegate.DynamicInvokeImpl(Object[] args)
>   bei EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:Zeile 550.
>   bei System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
>   bei System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
>   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   bei System.Windows.Forms.Control.WndProc(Message& m)
>   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by Eahlstan** [comment]
Please upload the journal of the session that caused this.

shell:SavedGames\Frontier Developments\Elite Dangerous

**Comment by klightspeed** [comment]
https://github.com/EDDiscovery/EDDiscovery/blob/Branch_12_1/EDDiscovery/UserControls/Overlays/UserControlMiningOverlay.cs#L142
This should already be fixed in 15.0
