### ISSUE TITLE
EDDN data missing vital feild on carrier market event

### ISSUE THREAD

**Issue by tmzasz** [EDDiscovery/EDDiscovery#3253]
"economies": [
      {
        "name": "Carrier",
        "proportion": 1
      }
    ],
This block seems to be missing when a Market Event is sent to EDDN from a carrier market event

Json sent to the upload endpoint

`{"header":{"uploaderID":"Tmzasz","softwareName":"EDDiscovery","softwareVersion":"15.0.0.7"},"$schemaRef":"https://eddn.edcd.io/schemas/commodity/3","message":{"systemName":"Paemara","stationName":"H8N-4VJ","marketId":3706118656,"timestamp":"2022-04-23T03:05:26Z","commodities":[{"name":"bertrandite","meanPrice":0,"buyPrice":41517,"stock":125,"stockBracket":2,"sellPrice":0,"demand":0,"demandBracket":0,"statusFlags":["Producer"]}],"odyssey":false,"horizons":true}}`

**Comment by tmzasz** [comment]
upon search i found this in [EliteDangerousCore](https://github.com/EDDiscovery/EliteDangerousCore/tree/625f50de8352747d873f427e172dc4aec3a9a586)/[EliteDangerous](https://github.com/EDDiscovery/EliteDangerousCore/tree/625f50de8352747d873f427e172dc4aec3a9a586/EliteDangerous)/[EDDN](https://github.com/EDDiscovery/EliteDangerousCore/tree/625f50de8352747d873f427e172dc4aec3a9a586/EliteDangerous/EDDN)/EDDNClass.cs
ln 368

`
private void RemoveStationEconomyKeys` and it seems to be responsible for the missing data being gone

**Comment by robbyxp1** [comment]
I'll check with EDDN, but the code has been like that a long time, so there must have been a reason.

**Comment by klightspeed** [comment]
`RemoveStationEconomyKeys` is called from the `Docked` journal event, and removes the `_Localised` keys.

`economies` does not exist in the `Market.json` file, so will not be sent to EDDN when a player looks at the commodity market.  It could theoretically be synthesised from the `StationCommodities` property in the `Docked` event, and copied into the `commodity/3` message.

**Comment by robbyxp1** [comment]
Market sends EDDNCommodityMessage which sends only the properties in that function, which does not include economies.

Market event itself does not have economies.

I do not have economies to send, this code has been like this, and i'm not going to reengineer at this point.





This schema has been updated recently,
