### ISSUE TITLE
Exception when Managing Add Ons inManagerAddOns

### ISSUE THREAD

**Issue by thenamesjay03** [EDDiscovery/EDDiscovery#3255]
### Description
I just added the OBS pack

### Additional Information
Im on windows 11

### Exception Details:
>EDDiscovery v15.0.0.7 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.Actions.ActionController.ManagerAddOns(Boolean manage) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:line 393
>   at EDDiscovery.EDDiscoveryForm.buttonExtManageAddOns_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 1199
>   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by Eahlstan** [comment]
Was this before or after you specified a directory to write to?
If it was after: Which directory did you choose?

**Comment by thenamesjay03** [comment]
When I press the install button that error poped up it never asked me to specify a directory to write to

**Comment by robbyxp1** [comment]
one of these excepting..

                    actionrunasync.TerminateAll();
                    AudioQueueSpeech.StopAll();
                    AudioQueueWave.StopAll();


they should all be okay
i'll ? them just for luck.

**Comment by Eahlstan** [comment]
Could you please try the newest release and tell us if it works now?

**Comment by thenamesjay03** [comment]
Sure im just on my way home from collage but I can try when I get home

**Comment by robbyxp1** [comment]
My guess, it was something up with your audio, which meant the driver did not start up and it was null....

**Comment by thenamesjay03** [comment]
![16511641485348751064811377136581](https://user-images.githubusercontent.com/83084519/165802640-07e5491c-7f87-4311-9862-f3b8f1c93f7d.jpg)
Got the obs function all set up now thanks for you help

**Comment by robbyxp1** [comment]
good. thanks for the report
