### ISSUE TITLE
Fresh installation of Edd wont start

### ISSUE THREAD

**Issue by Kimunachan** [EDDiscovery/EDDiscovery#3256]
### Exception Details:
>EDDiscovery v15.0.0.7 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Users\jonas\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings" konnte nicht gefunden werden.
>   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>   bei System.IO.FileSystemEnumerableIterator`1.CommonInit()
>   bei System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
>   bei System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
>   bei EliteDangerousCore.BindingsFile.LoadBindingsFile(String path, Boolean odyssey) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Bindings\BindingsFile.cs:Zeile 286.
>   bei EDDiscovery.Actions.ActionController.ReLoad(Boolean completereload) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:Zeile 151.
>   bei EDDiscovery.EDDiscoveryForm.EDDiscoveryForm_Shown(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:Zeile 520.
>   bei System.Windows.Forms.Form.OnShown(EventArgs e)
>   bei System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   bei System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   bei System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>===== END =====
>```
Thats the error what i get 

How to reproduce: 
Relative fresh installation of Ed Odysee and Edd version 15.0.0.7

edit:
Running on Insider build of Win 11

**Comment by Eahlstan** [comment]
Already started Elite once?

What happens if you try to navigate to C:\Users\jonas\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings ?

**Comment by Kimunachan** [comment]
Was activly playing Elite at that time

The Folder doesnt exist

**Comment by Eahlstan** [comment]
To which folder does the Windows explorer redirect you when you enter %localappdata% in the address bar?

**Comment by Kimunachan** [comment]
I land here C:\Users\jonas\AppData\Local

the only folder which doesnt exist ist the Bindings one

**Comment by Eahlstan** [comment]
Hm.
Did you create custom bindings in Elite? It may be that Elite only creates that folder if you do that.
Please try that first, if the folder doesn't get created create it yourself, beside some add-ons (free voice control) and the grid panel of the web server EDD runs fine without having the actual bindings.

**Comment by Kimunachan** [comment]
I created the Folder myself and it works now

No i didnt install it over another user

**Comment by Eahlstan** [comment]
But did you create custom bindings in Elite? (I'm curious.)

**Comment by Kimunachan** [comment]
No i didnt i use the normal bindings the game defaults to

**Comment by Eahlstan** [comment]
That's a hint that I'm right with "only created when needed". Thank you.
Robby just added a fail check to the newest release, so even if this folder doesn't exist it shouldn't crash the app in the future.
