### ISSUE TITLE
Error opening the new 3D map

### ISSUE THREAD

**Issue by tecnosegugio** [EDDiscovery/EDDiscovery#3257]
### Description
Just upgraded EDDIscovery at 15.0.1 version and this is the error that come out when I try to add a new tab with the new 3D map

### Additional Information
I've tried to:
* resetting user/system DB indexes
* restarting with a clean user/systems DB and rebuilding them from scratch
with no changes: still get the error.

System Info:
RAM 32GB, CPU Intel I7, GPU Nvidia GTX970M
Windows 10 Pro, DirectX 12

### Exception Details:
>EDDiscovery v15.0.1.0 An unhandled fatal exception has occurred.
>```
>==== BEGIN ====
>System.AccessViolationException: Tentativo di lettura o scrittura della memoria protetta. Spesso questa condizione indica che altre parti della memoria sono danneggiate.
>   in OpenTK.Graphics.OpenGL4.GL.CreateBuffers(Int32 n, Int32& buffers) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Graphics\OpenGL4\GL4.cs:riga 14790
>   in GLOFC.GL4.GLBuffer..ctor(Boolean std430)
>   in EDDiscovery.UserControls.Map3D.Map.Start(GLWinFormControl glwfc, GalacticMapping edsmmapping, GalacticMapping eliteregions, UserControlCommonBase parent, Parts parts) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\Map.cs:riga 156
>   in EDDiscovery.UserControls.UserControl3DMap.LoadLayout() in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\UserControl3DMap.cs:riga 53
>   in EDDiscovery.MajorTabControl.AddTab(PanelIDs id, Int32 tabindex) in C:\Code\EDDiscovery\EDDiscovery\MajorTabControl.cs:riga 168
>   in System.Windows.Forms.Control.OnClick(EventArgs e)
>   in System.Windows.Forms.Button.OnClick(EventArgs e)
>   in System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   in System.Windows.Forms.Control.WndProc(Message& m)
>   in System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   in System.Windows.Forms.Button.WndProc(Message& m)
>   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>   in System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
>   in System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
>   in System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
>   in System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
>   in EDDiscovery.Program.Main() in C:\Code\EDDiscovery\EDDiscovery\Program.cs:riga 45
>===== END =====
>```

**Comment by robbyxp1** [comment]
That is an memory error deep in openGL. No idea why this is there.

**Comment by Eahlstan** [comment]
Did you update all your drivers?

**Comment by tecnosegugio** [comment]
> Did you update all your drivers?

There was an Nvidia driver update. I've done it but th error still exists.

**Comment by Eahlstan** [comment]
Could you please download FurMark (it uses OpenGL too) and see if there's something strange with it?

**Comment by klightspeed** [comment]
This is a Mobile GPU, which means it's probably paired with the Intel iGPU.  I wonder if the program is being assigned to the Intel iGPU, and if that iGPU (or its driver) does not support OpenGL 4.5?

**Comment by robbyxp1** [comment]
You may want to try:

https://www.howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10/

to assign the gtx to eddiscovery

**Comment by robbyxp1** [comment]
And to see what GPU EDDiscovery is using - see the task manager part of that website

**Comment by tecnosegugio** [comment]
> Could you please download FurMark (it uses OpenGL too) and see if there's something strange with it?

Done and I've seen no problem. 
Below the log of FurMark:
----------------------------------------------------------------------
<->[NORMAL]#00000001#Fri Apr 29 19:44:35 2022#FurMark 1.29.0.0 is starting up...
<->[NORMAL]#00000002#Fri Apr 29 19:44:35 2022#FurMark folder: C:\Program Files (x86)\Geeks3D\Benchmarks\FurMark\
<->[NORMAL]#00000003#Fri Apr 29 19:44:35 2022#Log file: C:\Program Files (x86)\Geeks3D\Benchmarks\FurMark\FurMark_0001.txt
<->[NORMAL]#00000004#Fri Apr 29 19:44:35 2022#CPU/System info:
<->[NORMAL]#00000005#Fri Apr 29 19:44:35 2022#- CPU: Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
<->[NORMAL]#00000006#Fri Apr 29 19:44:36 2022#- CPU speed: 2494 MHz
<->[NORMAL]#00000007#Fri Apr 29 19:44:36 2022#- System memory: 32687 MB
<->[NORMAL]#00000008#Fri Apr 29 19:44:36 2022#- OS: Windows 10 64-bit build 19044
<->[NORMAL]#00000009#Fri Apr 29 19:44:36 2022#Detecting GPUs...
<->[NORMAL]#00000010#Fri Apr 29 19:44:36 2022#Found 2 GPUs.
<->[NORMAL]#00000011#Fri Apr 29 19:44:36 2022#- GPU 1:  NVIDIA GeForce GTX 970M
<->[NORMAL]#00000012#Fri Apr 29 19:44:36 2022#  - Cores: 1280
<->[NORMAL]#00000013#Fri Apr 29 19:44:36 2022#  - Memory size: 3071MB
<->[NORMAL]#00000014#Fri Apr 29 19:44:36 2022#  - Memory type: GDDR5
<->[NORMAL]#00000015#Fri Apr 29 19:44:36 2022#  - TDP: 100W
<->[NORMAL]#00000016#Fri Apr 29 19:44:36 2022#  - Bus ID: 1
<->[NORMAL]#00000017#Fri Apr 29 19:44:36 2022#  - Bios: 84.04.22.00.07
<->[NORMAL]#00000018#Fri Apr 29 19:44:36 2022#  - Graphics driver: R512.59
<->[NORMAL]#00000019#Fri Apr 29 19:44:36 2022#  - GPU temperature: 47.0°C
<->[NORMAL]#00000020#Fri Apr 29 19:44:36 2022#  - True clocks - GPU clock: 1037MHz - Memory clock: 2505MHz - GPU voltage: 0.987V
<->[NORMAL]#00000021#Fri Apr 29 19:44:36 2022#  - GPU base clock: 924MHz - GPU boost clock: 1038MHz
<->[NORMAL]#00000022#Fri Apr 29 19:44:36 2022#  - Fan speed: -1%
<->[NORMAL]#00000023#Fri Apr 29 19:44:36 2022#- GPU 2:  Intel(R) HD Graphics 4600
<->[NORMAL]#00000024#Fri Apr 29 19:44:36 2022#  - Cores: 20
<->[NORMAL]#00000025#Fri Apr 29 19:44:36 2022#  - Memory size: 1024MB
<->[NORMAL]#00000026#Fri Apr 29 19:44:36 2022#  - Memory type: 
<->[NORMAL]#00000027#Fri Apr 29 19:44:36 2022#  - TDP: 45W
<->[NORMAL]#00000028#Fri Apr 29 19:44:36 2022#  - Bus ID: -1
<->[NORMAL]#00000029#Fri Apr 29 19:44:36 2022#  - Bios: Intel Video BIOS
<->[NORMAL]#00000030#Fri Apr 29 19:44:36 2022#  - Graphics driver: 20.19.15.5171
<->[NORMAL]#00000031#Fri Apr 29 19:44:36 2022#no multi-GPU support (2 physical GPUs)
<->[NORMAL]#00000032#Fri Apr 29 19:44:36 2022#GPU monitoring thread started up ok.
<->[NORMAL]#00000033#Fri Apr 29 19:44:36 2022#oZone3D Engine is starting up - kernel build: [v3.4.3 - Nov 12 2021 @ 18:24:44] - codename: Kantalium
<->[NORMAL]#00000034#Fri Apr 29 19:44:36 2022#oZone3D initialization in progress...
<->[NORMAL]#00000035#Fri Apr 29 19:44:36 2022#oZone3D - OpenGL renderer creation ok.
<->[NORMAL]#00000036#Fri Apr 29 19:44:37 2022#o3RendererOpenGL INFO: OpenGL version: 4.6.0 NVIDIA 512.59
<->[NORMAL]#00000037#Fri Apr 29 19:44:37 2022#o3RendererOpenGL INFO: OpenGL Shading Language (GLSL) version: 4.60 NVIDIA
<->[NORMAL]#00000038#Fri Apr 29 19:44:37 2022#oZone3D initialization ok.
<->[NORMAL]#00000039#Fri Apr 29 19:44:37 2022#Checking for new version...
<->[NORMAL]#00000040#Fri Apr 29 19:44:37 2022#Your version of FurMark is up to date
----------------------------------------------------------------------

**Comment by tecnosegugio** [comment]
> This is a Mobile GPU, which means it's probably paired with the Intel iGPU. I wonder if the program is being assigned to the Intel iGPU, and if that iGPU (or its driver) does not support OpenGL 4.5?

Yes, There is an Intel  HD Graphics 4600 AND an Nvdia GeForce GTX 970M.

**Comment by tecnosegugio** [comment]
> You may want to try:
> https://www.howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10/
> to assign the gtx to eddiscovery

I've followed the instructions and now the 3Dmap works without errors!
Thank you tp everybody!

**Comment by Eahlstan** [comment]
Great to hear that it was a GPU mixup :)

**Comment by Silarn** [comment]
Might be nice to gracefully handle this error if an incompatible GPU is used.

**Comment by klightspeed** [comment]
> Might be nice to gracefully handle this error if an incompatible GPU is used.

`System.AccessViolationException` cannot be caught, and so cannot be handled gracefully.

I think Robby is re-architecting it to:
* Explicitly request OpenGL 4.6 (it currently requests the default, which for nVidia drivers is a 4.6 compatibility context, but for other drivers can be anything)
* Check if the context is actually an OpenGL 4.6 context, and fail gracefully if it is not.

**Comment by robbyxp1** [comment]
I am, its a bigger task than i thought. But a later version will be asking for 4.6.
