### ISSUE TITLE
Warnings/Unknown Frontier Keys?

### ISSUE THREAD

**Issue by incryptx** [EDDiscovery/EDDiscovery#3260]
On version v12.1.7, everything worked perfectly. After installing the latest version v15.0.1, I get the following errors.

-------------------------------------------------------------------------------------------------------------------------------
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Landing_GearToggle:692 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Landing_GearUp:704 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Landing_GearDown:716 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Chaff:728 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Shield_Cell:740 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Lights_On:752 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Lights_Off:764 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Lights_Toggle:776 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Heat_Sink:788 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Deploy_Cargo_Scoop:800 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Retract_Cargo_Scoop:812 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Charge_ECM:836 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Toggle_Weapons_Colour:848 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Toggle_Engine_Colour:860 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Toggle_Flight_Assist:872 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Flight_Assist_On:884 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Flight_Assist_Off:896 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Boost:908 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Drop:944 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Supercruise:956 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Select_Target:980 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Minus100:992 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Minus75:1004 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Minus50:1016 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Minus25:1028 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Stop:1040 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_25:1052 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_50:1064 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_75:1076 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_100:1088 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_NightVision:1100 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Rotational_Correction_Toggle:1112 No keyboard binding for DisableRotationCorrectToggle
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Next_Target:1124 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Previous_target:1136 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Highest_Threat:1148 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Next_Hostile:1160 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Previous_Hostile:1172 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Next_Subsystem:1244 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Previous_Subsystem:1256 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Resume_Route:1268 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Next_Fire_Group_Ship:1280 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Previous_Fire_Group_Ship:1292 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Deploy_Weapons:1304 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Retract_Weapons:1316 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Silent_Running:1328 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Increase_Radar_Range:1340 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Decrease_Radar_Range:1352 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Long_Range_Scan:1364 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Short_Range_Scan:1376 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Medium_Range_Scan:1388 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Head_Look:1532 No keyboard binding for HeadLookToggle
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Friends_Menu_Ship:1556 No keyboard binding for FriendsMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Next_Panel_Ship:1568 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Previous_Panel_Ship:1580 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Head_Look_Reset:1592 No keyboard binding for HeadLookReset
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Head_Look_Up:1604 No keyboard binding for HeadLookPitchUp
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Head_Look_Down:1616 No keyboard binding for HeadLookPitchDown
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Head_Look_Left:1628 No keyboard binding for HeadLookYawLeft
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Head_Look_Right:1640 No keyboard binding for HeadLookYawRight
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Head_Look_FullLeft:1652 No keyboard binding for HeadLookYawLeft
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Head_Look_FullRight:1664 No keyboard binding for HeadLookYawRight
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Head_Look_FullUp:1676 No keyboard binding for HeadLookPitchUp
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Recall_Ship:1688 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Dismiss_Ship:1700 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Toggle_Drive_Assist:1712 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Drive_Assist_On:1724 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Drive_Assist_Off:1736 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_LaunchNPCFighter:1748 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_LaunchInFighter:1760 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_SwitchFighterInFighter:1772 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_SwitchFighterInShip:1784 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Fighter_Open:1923 No keyboard binding for OpenOrders
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Ship_Open:2007 No keyboard binding for OpenOrders
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Escape_Ship:2163 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_CameraOnFoot:2229 No keyboard binding for PhotoCameraToggle_Humanoid
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Camera_PreviousCam:2264 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Camera_NextCam:2276 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Camera_IncrZoom:2480 No keyboard binding for FreeCamZoomIn
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Camera_DecrZoom:2492 No keyboard binding for FreeCamZoomOut
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Camera_IncrBlur:2504 No keyboard binding for FStopInc
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Camera_DecrBlur:2516 No keyboard binding for FStopDec
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Toggle_Handbrake:2528 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Toggle_Headlights:2540 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Toggle_Turret:2552 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_SelectTargetSRV:2564 Invalid key !LShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_EmbarkSRV:2576 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Close_Panel_Buggy:2636 No keyboard binding for UIFocus_Buggy
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Next_Fire_Group_Buggy:2720 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Previous_Fire_Group_Buggy:2732 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Increase_Engine_Power_Buggy:2744 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Increase_Weapons_Power_Buggy:2756 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Increase_Systems_Power_Buggy:2768 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Reset_Power_Buggy:2780 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Weapons_WS_Buggy:2792 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Weapons_SpeedAttack_Buggy:2804 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Weapons_MaxWeapons_Buggy:2816 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Weapons_MaxShields_Buggy:2828 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Weapons_MaxEngines_Buggy:2840 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Weapons_Balanced_Buggy:2852 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Weapons_AttackMode_Buggy:2864 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Weapons_FastAttack_Buggy:2876 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_RequestDocking_Ship:2888 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_PreviousGrenade:3092 No keyboard binding for HumanoidSelectPreviousGrenadeTypeButton
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Switch:3116 No keyboard binding for HumanoidSwitchWeapon
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_SelectUtility:3152 No keyboard binding for HumanoidSelectUtilityWeaponButton
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_NextWeapon:3164 No keyboard binding for HumanoidSelectNextWeaponButton
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_PreviousWeapon:3176 No keyboard binding for HumanoidSelectPreviousWeaponButton
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Open_Galaxy_Map_Humanoid:3344 No keyboard binding for GalaxyMapOpen_Humanoid
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Close_Galaxy_Map_Humanoid:3356 No keyboard binding for GalaxyMapOpen_Humanoid
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Open_System_Map_Humanoid:3368 No keyboard binding for SystemMapOpen_Humanoid
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Close_System_Map_Humanoid:3380 No keyboard binding for SystemMapOpen_Humanoid
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_FocusComms_Humanoid:3404 No keyboard binding for FocusCommsPanel_Humanoid
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_InsightPanel_RecallShip_Humanoid:3440 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_InsightPanel_DismissShip_Humanoid:3452 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_InsightPanel_Taxi_Humanoid:3464 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_InsightPanel_CancelTaxi_Humanoid:3476 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_InsightPanel_Navigation_Humanoid:3488 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_InsightPanel_Contacts_Humanoid:3500 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_InsightPanel_Transactions_Humanoid:3512 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_InsightPanel_Backpack_Humanoid:3524 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_InsightPanel_Commander_Humanoid:3536 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_InsightPanel_Codex_Humanoid:3548 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_InsightPanel_Powerplay_Humanoid:3560 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_InsightPanel_Squadrons_Humanoid:3572 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_InsightPanel_Engineer_Humanoid:3584 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_InsightPanel_Galnet_Humanoid:3596 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_EmotePoint:3620 No keyboard binding for HumanoidEmoteSlot1
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_EmoteWave:3632 No keyboard binding for HumanoidEmoteSlot2
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_EmoteAgree:3644 No keyboard binding for HumanoidEmoteSlot3
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_EmoteDisagree:3656 No keyboard binding for HumanoidEmoteSlot4
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_EmoteGo:3668 No keyboard binding for HumanoidEmoteSlot5
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_EmoteStop:3680 No keyboard binding for HumanoidEmoteSlot6
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_EmoteApplaud:3692 No keyboard binding for HumanoidEmoteSlot7
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_EmoteSalute:3704 No keyboard binding for HumanoidEmoteSlot8
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_EnterLift_Humanoid:3716 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_DisembarkLanded:3728 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_DisembarkLandedSRV:3740 Invalid key !RShiftKey
Key Mapping Warning: FreeVoiceControlV4:MoveStarPortServices:3774 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:MoveStarPortServices:3779 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_StarPortServices:3791 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_LaunchDocked:3802 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_DisembarkDocked:3814 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_RefuelDocked:3825 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_RepairDocked:3836 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_RestockDocked:3847 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_ReturnToSurfaceDocked:3858 Invalid key !RMenu
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Embark_Humanoid:3881 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Manage_Inventory_Humanoid:3893 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Resupply_Inventory_Humanoid:3905 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:VoiceInput_ScanSystem:3921 Invalid key !RControlKey
Key Mapping Warning: FreeVoiceControlV4:ScanSystemTimer:3933 Invalid key !RControlKey
CAPI Installed
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
Voice Pack installed, running on EDD Version 15.0.1.0
Scanning for bmp screenshots in E:\Pictures\Frontier Developments\Elite Dangerous
Web server enabled
DLLs loaded: EDDCanonn
Profile Default Loaded
Loaded Bindings C:\Users\bill\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\Custom.4.0.binds
Bindings Errors
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Unknown Frontier Key Key_Apps in key layout US
Error: Function phrase: Parameter 1: Function expand: Function ifzero: Parameter 1: Parameter 'LAST_OnFoot' is not an number or a variable name
History refresh complete.
Voice Recognition Pack running.
CAPI Refresh Succeeded
CAPI User Logged in
Sent 3 events to INARA

---------------------------------------------------------------------------------------------------------------------
I have uninstalled v12, deleted all directories, reinstalled v15, reconfigured it, and still the errors persist. I uninstalled v15 and reinstalled v12 and all errors are gone. I have no idea as to what causes these errors, but v15 is useless to me, no offense.

**Comment by incryptx** [comment]
By comparison, this is my v12 log.

CAPI Installed
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
Scanning for bmp screenshots in E:\Pictures\Frontier Developments\Elite Dangerous
Web server enabled
DLLs loaded: EDDCanonn
Profile Default Loaded
Loaded Bindings C:\Users\bill\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\Custom.4.0.binds
Voice Recognition Pack running.
New EDDiscovery installer available: EDDiscovery Release 15.0.1 New 3dmap, Organics panel, updated UI
History refresh complete.
CAPI Refresh Succeeded
CAPI User Logged in
Sent 3 events to INARA

**Comment by robbyxp1** [comment]
They are not errors, they are warnings. The rest of the program outside of free voice control will be working.

Its a combination of your locale and the frontier bindings file. If you tell me your keyboard locale, and send the bindings file, i can see if i can reproduce.

What other packs are you running?

**Comment by robbyxp1** [comment]
And you need to be running a custom bindings control set, even if you just changed one item in it.  Otherwise EDD does not know how the mapping is set.

**Comment by Eahlstan** [comment]
Side note:

Some days ago another user sent me a log that contained many

`[2022-04-29T15:12:08.344Z] Unknown Frontier Key Key_Apps in key layout US`

**Comment by robbyxp1** [comment]
Have you edited the voice pack yourself in any way?

**Comment by robbyxp1** [comment]
The lines such as "Key Mapping Warning: FreeVoiceControlV4:VoiceInput_Head_Look:1532 No keyboard binding for HeadLookToggle" are just warning you that you don't have a key mapped for that Elite binding, hence EDD can't press the key.

The Key_Apps i can solve by adding more frontier names -> VKEY translations

**Comment by incryptx** [comment]
1) No edits to voicepacks at all.
2) I run "custom" binds in Elite, v3.0 for ED and v4.0 for EDO, which has not changed when upgrading EDD from v12. to v15.
3) No changes were made to Elite or EDD v12. I upgraded by uninstalling v12, then installing V15. The warnings persisted. I then uninstalled v15, deleting all directories and reinstalled v15. The warnings persisted. I then uninstalled v15 and reinstalled v12. The warnings went away and now it loads clean.

Logs from EDD v12.
----------------------------------------------------------------
CAPI Installed
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
Scanning for bmp screenshots in E:\Pictures\Frontier Developments\Elite Dangerous
Web server enabled
DLLs loaded: EDDCanonn
Profile Default Loaded
Loaded Bindings C:\Users\bill\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\Custom.4.0.binds
Voice Recognition Pack running.
New EDDiscovery installer available: EDDiscovery Release 15.0.1 New 3dmap, Organics panel, updated UI
Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 5/2/2022 3:19:43 AM to 5/2/2022 9:19:43 AM
History refresh complete.
CAPI Refresh Succeeded
CAPI User Logged in
Downloading systems from UTC 5/2/2022 9:19:17 AM to 5/2/2022 3:19:17 PM
EDSM systems update complete with 865 systems
Sent 3 events to INARA
-------------------------------------------------------------------------------
EDD V12 works just fine. I don't understand why EDD v15 now has problems with my binds, which have not changed.

**Comment by Eahlstan** [comment]
Please upload all files found in %localappdata%\Frontier Developments\Elite Dangerous\Options\Bindings

**Comment by incryptx** [comment]
[Bindings.zip](https://github.com/EDDiscovery/EDDiscovery/files/8605389/Bindings.zip)

**Comment by Eahlstan** [comment]
> [Bindings.zip](https://github.com/EDDiscovery/EDDiscovery/files/8605389/Bindings.zip)
> 
> I doubt my binds caused this or they would not work in Elite or EDD v12.

It's better to have your files to be able to test it.

I could reproduce the issue using your binding files and FVCv4.

**Comment by Eahlstan** [comment]
> [Actions.zip](https://github.com/EDDiscovery/EDDiscovery/files/8605402/Actions.zip) [Bindings.zip](https://github.com/EDDiscovery/EDDiscovery/files/8605389/Bindings.zip)
> 
> I doubt my binds caused this or they would not work in Elite or EDD v12.

On a side note: I had a talk with Robby and he said that v15 simply outputs errors that were there in v12 but not visible. Could you try if FVC works like in v15 even though v15 prints those errors?

**Comment by robbyxp1** [comment]
The conclusion is, your keystroke sequences are too complex for the current code to handle, and the ones it can't handle are producing the warnings.

I've made a project card to fix it in the future (ie. not right now but hopefully soon).

12 vs 15 makes no difference, they both won't be able to handle them.  

Some sequences will work, others will not.

Thanks for the report.

**Comment by incryptx** [comment]
Thanks for this info.

So, if I understand this correctly, both V12 and V15, specifically the FVCv4/v3 add-on, will generate these warnings due to two modifiers in my binds. V15 will show these warnings and V12 will not.

Which means to me, that V12, before the upgrade to v15, never worked due to my two additional binding modifiers and I never knew it because the warnings were hidden? and only exposed in V15?

To make matters clear for everyone, the bindings I use were generated by VoiceAttack for use with the HCS Voicepacks, which will explain the presence of the additional modifiers. As well, those who use VoiceAttack and HCS Voicepacks don't use EDD for in-game voice activation as the two would conflict and cause problems. The reason I have EDD installed, and I assume this is true for those not using EDD for it's intended purpose, is to read the journals as well as some additional information provided by EDD. 

In other words, the user needs to make a decision to use EDD as the primary voice activation software for Elite gaming, or use VA/HCS, but not both. It would be almost impossible to use EDD's FVCv4/v3 add-in properly, without warnings, due to the modifications made to the users bindings by VA/HCS, even if the user wanted to switch between the two, without having an additional set of bindings specifically tuned to EDD FVCv4/v3 requirements.

I'm also thinking that more users than not, and I may be wrong here, primarily use EDD for reading journals and for the additional information it provides as well as route planning/expedition features and not so much it's voice control system. I have always used EDD for it's informational value. So to fix this for me, and to use EDD the way I want to, I just don't need to load the FVCv4/v3 add-in. 

As a suggestion, it might be good code to check for the presence of VA/HCS, or it's altered bindings (the presence of additional modifiers), when attempting to load the FVCv4/v3 add-in and if present, give a warning of conflict, or just not load the add-in at all. I don't think it is good code to hide or expose warnings which are the result of the miss-use of EDD's primary design function, i.e. bindings created by other voice software.

In any event, thank you for your excellent investigation into this issue.

Please close the issue and mark it "by design".

**Comment by robbyxp1** [comment]
Its not by design, its going to be solved. In fact, solved very soon.  We are not going to check for third party software.
