### ISSUE TITLE
Bookmark CSV import not working

### ISSUE THREAD

**Issue by tecnosegugio** [EDDiscovery/EDDiscovery#3261]
### Description
Was trying to import a CSV file generated from EDDiscovery Bookmark panel of a friend (same version of EDD 15.0.1) but nothing is imported. 
Curiously EDD ask me twice to open the file.

This is the CSV file: [GUN-1ca.csv](https://github.com/EDDiscovery/EDDiscovery/files/8644955/GUN-1ca.csv)

### Additional Information
System Info:
RAM 32GB, CPU Intel I7, GPU Nvidia GTX970M
Windows 10 Pro, DirectX 12

**Comment by klightspeed** [comment]
The CSV exported by your friend looks like it was generated using a locale that uses a comma as the decimal point and semicolon as the field separator.

Unfortunately EDDiscovery exports numbers in the user's locale, but tries to import numbers using an invariant locale, so merely setting the CSV separator to be semicolon in the import form won't work - you'd have to open the file in a text editor and replace the commas in the numbers with periods.

**Comment by tecnosegugio** [comment]
I see. 
So I tried to edit the CSV file as you told me.
I've built two versions:
File with comma as separator: [GUN-1ca-comma.csv](https://github.com/EDDiscovery/EDDiscovery/files/8645544/GUN-1ca-comma.csv)
File with semicolon as separator: [GUN-1ca-semicolon.csv](https://github.com/EDDiscovery/EDDiscovery/files/8645546/GUN-1ca-semicolon.csv)

Both file are loaded correctly but the screen is not updated after the import.
I have to make a fake search to see my bookmarks on the screen.

Anyway, the problem is solved.
Thank you!

**Comment by robbyxp1** [comment]
It should be using the import dialog, maybe its one i missed..

**Comment by Eahlstan** [comment]
It's really strange on my side.
I click import. It opens a file selection screen.
![Screenshot 2022-05-07 194325](https://user-images.githubusercontent.com/59618179/167265736-3c2e2751-24b3-478d-a206-43b7dddb8e02.JPG)
I select the file and another selection screen comes up.
![Screenshot 2022-05-07 194433](https://user-images.githubusercontent.com/59618179/167265762-364dae43-8cae-4895-ab62-9bb2ceaed87d.JPG)
I select the file again and it gets imported without any problems.

**Comment by robbyxp1** [comment]
So, no action, it works?

**Comment by robbyxp1** [comment]
We have fixed the repeated opening of the file dialog on import, as noted. will be in 15.0.2

**Comment by robbyxp1** [comment]
Closing
