### ISSUE TITLE
[request] Exported coordinates with only 2 digits

### ISSUE THREAD

**Issue by tecnosegugio** [EDDiscovery/EDDiscovery#3262]
A CSV file exported from the Bookmark page have all surface coordinates with only 2 decimal digits.
This precision is not enough if I want to mark a precise place on the surface for SRV or when on foot.

Can we have a CSV file with 4 decimal digits, please?

Thank you

**Comment by robbyxp1** [comment]
Done on tip, will be in 15.0.2
