### ISSUE TITLE
Galaxy objects too small

### ISSUE THREAD

**Issue by TribbleTrouble** [EDDiscovery/EDDiscovery#3263]
The galaxy objects on the new 3D map are far too small. I use the galaxy map to determine whether there are interesting POI or fleet carriers along my expedition route. I can only see the galaxy objects if I zoom into the map. Often I have to remove my historical route as they obscure objects. I need to be able to see objects 500ly to 1500ly away. Other people may have different uses for the galaxy objects. Perhaps what is needed is a setup option to change the size of the objects.

**Comment by robbyxp1** [comment]
The size has been selected to balance map crowding vs visibility. They scale when you zoom out to a limit.

I'll consider if new UI can be added for this. Moving to projects.
