### ISSUE TITLE
Mono path issue with Bindings file

### ISSUE THREAD

**Issue by cotste** [EDDiscovery/EDDiscovery#3264]
There is a hardcoded path in EDDiscovery/Actions/ActionController.cs for the bindings location. Everything builds properly but the app crashes on launch looking for ~/.local/share/Frontier Developements\Elite Dangerous\Options\Bindings.

I also had to symlink my steam install to ~/.local/share, I have no idea if there is a way to pull the steam/proton path with the GetFolderPath function.

I can submit a pull request but I'm not familiar with your processes, let me know if you want one. I made the following change and it seems to be working great building from 15.0.1

`frontierbindings.LoadBindingsFile(System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), @"Frontier Developments\Elite Dangerous\Options\Bindings"),true);`
          

`frontierbindings.LoadBindingsFile(System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Frontier Developments", "Elite Dangerous", "Options", "Bindings"),true);`

**Comment by Eahlstan** [comment]
I can't say anything about your code change, but the reason EDD tries to look for the files in .local/share is that your XDG_DATA_HOME is not set (or actually set to .local/share ), so even if your changes do work around this the underlying issue is your unset variable.

http://docs.go-mono.com/index.aspx?link=T%3aSystem.Environment%2bSpecialFolder
https://superuser.com/questions/365847/where-should-the-xdg-config-home-variable-be-defined

**Comment by klightspeed** [comment]
There are doubtless other windows-centric backslashed paths that should be replaced with `Path.Combine` over the path components.

As for overriding the directory it looks in for the bindings (which probably won't be usable when running under Mono), perhaps an option could be added to EDDOptions to override where to look for the bindings file?

**Comment by robbyxp1** [comment]
Does SendKeys even work on Mono? If it does not, all is pointless.

**Comment by klightspeed** [comment]
> Does SendKeys even work on Mono? If it does not, all is pointless.

`BindingsFile.LoadBindings` is called by `ActionController.ReLoad`, which is called by `EDDiscoveryForm.EDDiscoveryForm_Shown`, so fixing the _crash_ is not pointless.

@cotste what is the exact error and stack trace you are seeing when it is crashing?

**Comment by robbyxp1** [comment]
Oh its crashing, missed that.

**Comment by robbyxp1** [comment]
I will more protected BindingsFile.cs, and move to that combine path stuff. 

In 15.0.2, closing.
