### ISSUE TITLE
Opening the 3D map causes an immediate crash to error dialog

### ISSUE THREAD

**Issue by BilliousOz** [EDDiscovery/EDDiscovery#3267]
### Description
Opening the 3D map causes an immediate crash to error dialog

### Exception Details:
>EDDiscovery v15.0.4.0 An unhandled fatal exception has occurred.
>```
>==== BEGIN ====
>System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>   at OpenTK.Graphics.OpenGL4.GL.DrawElementsInstancedBaseVertexBaseInstance(PrimitiveType mode, Int32 count, DrawElementsType type, IntPtr indices, Int32 instancecount, Int32 basevertex, Int32 baseinstance) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Graphics\OpenGL4\GL4.cs:line 17747
>   at GLOFC.GL4.GLRenderableItem.Render()
>   at GLOFC.GL4.Controls.GLControlDisplay.Render(GLRenderState currentstate, UInt64 ts)
>   at System.Action`1.Invoke(T obj)
>   at GLOFC.WinForm.GLWinFormControl.GlControl_Paint(Object sender, PaintEventArgs e)
>   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
>   at OpenTK.GLControl.OnPaint(PaintEventArgs e) in I:\work\github\opentk\src\OpenTK.GLControl\GLControl.cs:line 287
>   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
>   at System.Windows.Forms.Control.WmPaint(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.UserControl.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by Eahlstan** [comment]
Please share your hard- and software configuration.

**Comment by BilliousOz** [comment]
![image](https://user-images.githubusercontent.com/3821287/169621416-ba1922e4-f93a-4a2f-bb8f-509b3e2ece3a.png)
Running Windows 10.

**Comment by robbyxp1** [comment]
The trace does not give enough data to know why the memory is corrupted. 

Only if the buffer was not bound to element target .DrawElementsInstancedBaseVertexBaseInstance would I expect an access error. The controldisplay does bind the buffer to element index target.

Other Nvidia cards the code does works.

To debug it, we would need someone to compile and run the test harness at https://github.com/Foundation-Classes-For-OpenTK/OFC and see if a particular test caused a similar crash, and then isolate down the actions which caused it, on the 1650.

**Comment by robbyxp1** [comment]
Or run a test build of EDD with more error checking on.

**Comment by BilliousOz** [comment]
I'll see what I can do and will get back to you.

**Comment by Eahlstan** [comment]
> I'll see what I can do and will get back to you.

There's now a debug version available on the download page. It's a zip file containing a special portable version.

https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_15.0.4

**Comment by BilliousOz** [comment]
Thanks, here's the output, using the debug version.


>==== BEGIN ====
>System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>   at OpenTK.Graphics.OpenGL4.GL.DrawElementsInstancedBaseVertexBaseInstance(PrimitiveType mode, Int32 count, DrawElementsType type, IntPtr indices, Int32 instancecount, Int32 basevertex, Int32 baseinstance) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Graphics\OpenGL4\GL4.cs:line 17747
>   at GLOFC.GL4.GLRenderableItem.Render() in C:\Code\OFC\OFC\GL4\Renderers\RenderableItem.cs:line 169
>   at GLOFC.GL4.Controls.GLControlDisplay.Render(GLRenderState currentstate, UInt64 ts) in C:\Code\OFC\OFC\GL4\Controls\Base\ControlDisplay.cs:line 194
>   at GLOFC.GL4.Controls.GLControlDisplay.Gc_Paint(UInt64 ts) in C:\Code\OFC\OFC\GL4\Controls\Base\ControlDisplay.cs:line 456
>   at System.Action`1.Invoke(T obj)
>   at GLOFC.WinForm.GLWinFormControl.GlControl_Paint(Object sender, PaintEventArgs e) in C:\Code\OFC\OFC\GLWinFormControl.cs:line 384
>   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
>   at OpenTK.GLControl.OnPaint(PaintEventArgs e) in I:\work\github\opentk\src\OpenTK.GLControl\GLControl.cs:line 287
>   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
>   at System.Windows.Forms.Control.WmPaint(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.UserControl.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by Eahlstan** [comment]
Could to please ensure that EDD uses your GPU, not your APU to render?

https://www.howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10/

**Comment by BilliousOz** [comment]
> Could to please ensure that EDD uses your GPU, not your APU to render?
> 
> https://www.howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10/

That did the trick, thanks! I should have thought of that.
