### ISSUE TITLE
Bookmarks are not visible in 2D Map

### ISSUE THREAD

**Issue by Pisodeuorrior** [EDDiscovery/EDDiscovery#3268]
Personal bookmarks are not visible when setting the 3D map in orthogonal view.

Even in 3D view they're really difficult to spot, it would be nice if they were independent from camera orientation, and anyway much bigger.

Compared to the previous map versions, setting up a route based on bookmarks is now very laborious.

**Comment by robbyxp1** [comment]
Unfort if you make them larger, you end up seeing them not the galaxy when zoomed out. Its a balance, you don't want the galaxy dominated by them. I picked a balance point. I may try to make it selectable later.

I'll look into the orthographic view - they need rotating differently.

**Comment by robbyxp1** [comment]
Moved to project cards.
