### ISSUE TITLE
Error right-clickign on stars in 3D map

### ISSUE THREAD

**Issue by Pisodeuorrior** [EDDiscovery/EDDiscovery#3272]
### Description

I was attempting to bookmark a star in the 3D map by right clicking on it.

Right clicking always returns an error.

In order to reproduce it: 

- open the 3D map (pop out or tabbed makes no difference).
- right click anywhere in the map

Most times it would return an error, sometimes it would just hard crash.

### Exception Details:
>EDDiscovery v15.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   at GLOFC.GL4.Buffers.GLSetOfObjectsWithLabels.FindBlock(GLShaderPipeline findshader, GLRenderState glstate, Point pos, Size size)
>   at EDDiscovery.UserControls.Map3D.GalaxyStars.Find(Point loc, GLRenderState rs, Size viewportsize, Single& z) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\GalaxyStars.cs:line 356
>   at EDDiscovery.UserControls.Map3D.Map.FindObjectOnMap(Point loc) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\Map.cs:line 1117
>   at EDDiscovery.UserControls.Map3D.Map.MouseClickOnMap(GLBaseControl s, GLMouseEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\Map.cs:line 1297
>   at GLOFC.GL4.Controls.GLBaseControl.Gc_MouseClick(GLWindowControl sender, GLMouseEventArgs e)
>   at GLOFC.WinForm.GLWinFormControl.Gc_MouseClick(Object sender, MouseEventArgs e)
>   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.UserControl.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
@Pisodeuorrior does the right click work on an object at all?

As regards the bookmark, thats easy, i forgot to regen them.

**Comment by robbyxp1** [comment]
And what graphics card are you using? is it a laptop? has it got a APU and a discrete graphics card?

**Comment by robbyxp1** [comment]
Just did the same, everything off except EDSM stars, and I can't make it crash !

Nvidia here. 

I can stop it going wrong, but have no idea why its reporting an incorrect index. And I don't know if it would right click correctly afterwards.  I'll continue digging
