### ISSUE TITLE
[Suggestion] Some extra info in the Ledger Tab.

### ISSUE THREAD

**Issue by Jugom** [EDDiscovery/EDDiscovery#3273]
Just thought it would be nice to have. Those obsessed with cr./h will probably appreciate it too. 
The picture should be self explanatory. Just an extra cell displaying the profits in a selected period of time. 

![image](https://user-images.githubusercontent.com/74990247/170994832-38926c5b-0b37-4e62-bf4b-bafd6a9a12a9.png)

**Comment by robbyxp1** [comment]
Noted in worklist. Thanks
