### ISSUE TITLE
Incorrect first discovered

### ISSUE THREAD

**Issue by Californ1a** [EDDiscovery/EDDiscovery#3278]
I've seen this appear a few times, finally decided to just grab a screenshot and drop an issue.

[This system](https://www.edsm.net/en/system/id/12556916/name/Synuefe+JS-J+c25-5) has already been discovered, however, EDDiscovery is reporting "first discovered" for me even though it knows bodies in the system have already been discovered:

![](https://i.imgur.com/GEesduz.png)

If bodies in the system are already discovered, then the system itself has also already been discovered and the FD star should be removed from the system info, summary, etc. panels.

**Comment by robbyxp1** [comment]
The icon does not show this. It shows if its the first time EDSM has seen the system.  Its nothing to do with the first discovery flag introduced much later into the journals.

See https://github.com/EDDiscovery/EDDiscovery/wiki/Using-the-System-Information-Panel

Obv the system you went to has been visited by a commander who never uses EDSM.

Working as designed.

**Comment by Eahlstan** [comment]
The response of EDSM stopped assigning the needed flag when the system is up there. It still sends it when the system is new.
We might have to check that with Anthor.

**Comment by Eahlstan** [comment]
There either was a misunderstanding about what EDSM does or a bug in EDSM - hard to say after 4 years.
EDSM has changed the respond it sends, so from now on this icon should correctly work as a "First one to submit this system to EDSM" indicator.

Thanks for your report.
And thanks Anthor for changing the code of EDSM.

**Comment by Californ1a** [comment]
> so from now on this icon should correctly work as a "First one to submit this system to EDSM" indicator.

Yes, that's what I thought it was supposed to be, not Frontier's in-game first discovered, though EDSM shows it's already discovered (I wouldn't get the star/FD credit on EDSM) hence my confusion.

**Comment by Eahlstan** [comment]
Please see if the change EDSM made today fixed that problem. It shouldn't have happened even without these changes, we quite don't know how you made this error happen.
But if it's gone now we don't need to dig deeper :)

**Comment by Californ1a** [comment]
I hopped back out to that system to check and that seems to have fixed it, the star isn't there anymore.

![](https://i.imgur.com/yNh31jm.png)

I'll keep an eye out for it to happen again in any other systems, but for now it seems fixed.

**Comment by robbyxp1** [comment]
Okay, thanks for the update. We ended up fixing up EDSM a little!

**Comment by Californ1a** [comment]
> No it should not.  
> This star should only show when the system is not on EDSM at the time you jump to it. Logically this can only be true at your first jump to it. On your second visit it's already on EDSM from your first visit so EDSM doesn't report it back as new.

Ah, interesting. I'd think it would show the FD star if you have FD on EDSM, regardless of if it's your first visit to that system or not. It not showing on future visits would lead me to mistakenly think I didn't have FD on that system if I'm looking for that info even if I do. EDSM flight logs show the FD star on the system every time you visit it:

![](https://i.imgur.com/OvEpbxP.png)

![](https://i.imgur.com/QJMJCsK.png)
