### ISSUE TITLE
Wiki Page "Using the Nearest Stars Panel" has a broken link to "Using the History Grid Panel"

### ISSUE THREAD

**Issue by designerzim** [EDDiscovery/EDDiscovery#3279]
The first line on https://github.com/EDDiscovery/EDDiscovery/wiki/Using-the-Nearest-Stars-Panel

> The Nearest stars panel shows the list of stars closest to the system selected by the [history grid](Using the History Grid) cursor, and the number of times you visited them.

Incorrectly displays `[history grid](Using the History Grid)` rather than a link: [history grid](https://github.com/EDDiscovery/EDDiscovery/wiki/Using-the-History-Grid-Panel)

It's unclear how the Wiki formatting needs to be since I can't see the source on these wiki pages, but it's possibly as simple as missing the word **Panel**. The target page url and page title reference "Using the History Grid _Panel_" (emphasis added)

**Comment by Eahlstan** [comment]
Fixed, thank you.
