### ISSUE TITLE
[Linux] 15.0.4 On Ubuntu running KDE Plasma

### ISSUE THREAD

**Issue by combivanCoder** [EDDiscovery/EDDiscovery#3280]
On first run (after being asked to select how much EDSM data to download, and opting for "Bubble"), and on every subsequent open the following exception is thrown:

```
### Description
Running the application

### Additional Information
Tried using the release artefacts, also tried building from source but fails with:
./monobuild: line 6: msbuild: command not found

### Exception Details:
>EDDiscovery v15.0.4.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.EntryPointNotFoundException: DdeInitializeW assembly:<unknown assembly> type:<unknown type> member:(null)
>  at (wrapper managed-to-native) BaseUtils.DDE.DDEServer+NativeMethods.DdeInitializeW(uint&,BaseUtils.DDE.DDEServer/DdeDelegate,uint,uint)
>  at BaseUtils.DDE.DDEServer.Start (System.String ddeapplicationname) [0x00012] in <b3f34e60c92a4cb89ecfece17436d5b0>:0 
>  at EDDiscovery.EDDiscoveryController.PostInit_Shown () [0x00048] in <c0376c8afee84da78a8ea48f807eacdc>:0 
>  at EDDiscovery.EDDiscoveryForm.EDDiscoveryForm_Shown (System.Object sender, System.EventArgs e) [0x0008f] in <c0376c8afee84da78a8ea48f807eacdc>:0 
>  at System.Windows.Forms.Form.OnShown (System.EventArgs e) [0x0001c] in <a3daa9b84fd241a497578a25f68bc3c7>:0 
>  at EDDiscovery.Forms.DraggableFormPos.OnShown (System.EventArgs e) [0x00007] in <c0376c8afee84da78a8ea48f807eacdc>:0 
>  at System.Windows.Forms.Form.SetVisibleCore (System.Boolean value) [0x00183] in <a3daa9b84fd241a497578a25f68bc3c7>:0 
>  at System.Windows.Forms.Control.set_Visible (System.Boolean value) [0x0000c] in <a3daa9b84fd241a497578a25f68bc3c7>:0 
>  at System.Windows.Forms.Control.Show () [0x00000] in <a3daa9b84fd241a497578a25f68bc3c7>:0 
>  at EDDiscovery.EDDApplicationContext.SwitchContext (System.Windows.Forms.Form newForm) [0x00022] in <c0376c8afee84da78a8ea48f807eacdc>:0 
>  at EDDiscovery.EDDApplicationContext.InitialiseEDD (System.Object sender, System.EventArgs e) [0x002d3] in <c0376c8afee84da78a8ea48f807eacdc>:0 
>===== END =====
>```
```
Application unresponsive.

Also noticed the following in the console during execution:
`/home/rex/.gtkrc-2.0:19: error: unexpected character '\357', expected keyword - e.g. 'style'`

Mono version: Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-2 Wed Feb 26 23:23:50 UTC 2020)
OS Version: 22.04.4

**Comment by robbyxp1** [comment]
I'll have to crack open the linux VB and see what it does.

**Comment by klightspeed** [comment]
The DDE server should probably only be initialized for the CAPI client when `Environment.OSVersion.Platform == PlatformID.Win32NT`

**Comment by robbyxp1** [comment]
Agreed.  No time in last few days to investigate.

**Comment by robbyxp1** [comment]
I also want to see what happens on my installation because it did not fail last time I ran.

**Comment by klightspeed** [comment]
> I also want to see what happens on my installation because it did not fail last time I ran.

It probably wouldn't error if run from source because CAPI would not be enabled, and so that code path would not be hit.

**Comment by combivanCoder** [comment]
I did try a run from source also, but the build failed with:

```Tried using the release artefacts, also tried building from source but fails with:
./monobuild: line 6: msbuild: command not found```

**Comment by combivanCoder** [comment]
To clarify: I did not use dotnet, I simply followed the Linux instructions on your wiki (which focused on `mono-complete`).
The error posted was from the command instructed on your wiki.

Can you confirm that additional steps are needed beyond your wiki please?

**Comment by robbyxp1** [comment]
I just built and ran EDD from source on Debian 10, with the instructions given in the wiki.

Mono JIT compiler version 6.12.0.122 (tarball Mon Feb 22 17:42:49 UTC 2021)

the CAPI needs to be disabled in the mono build I agree.

**Comment by robbyxp1** [comment]
I've turned off CAPI/DDE on non win32, as suggested, on the dev branch.

**Comment by klightspeed** [comment]
`mono-complete` depends on `msbuild`, while `mono-devel` only recommends it.  It sounds like @robbyxp1 said yes to the `recommends`, while @combivanCoder said no.

**Comment by robbyxp1** [comment]
I went full fat.

**Comment by combivanCoder** [comment]
> `mono-complete` depends on `msbuild`, while `mono-devel` only recommends it. It sounds like @robbyxp1 said yes to the `recommends`, while @combivanCoder said no.

No reference to msbuild as a dependency in the Ubuntu apt response to an `apt install mono-complete`

**Comment by klightspeed** [comment]
Odd - `mono-complete` in <https://download.mono-project.com/repo/ubuntu/dists/stable-focal/main/binary-amd64/Packages> has:

Depends: mono-runtime (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-runtime-sgen (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-llvm-support (= 6.12.0.182-0xamarin1+ubuntu2004b1), libmono-2.0-1 (= 6.12.0.182-0xamarin1+ubuntu2004b1), libmono-profiler (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-utils (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-devel (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-mcs (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-roslyn (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-csharp-shell (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-4.0-gac (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-4.0-service (= 6.12.0.182-0xamarin1+ubuntu2004b1), monodoc-base (= 6.12.0.182-0xamarin1+ubuntu2004b1), monodoc-manual (= 6.12.0.182-0xamarin1+ubuntu2004b1), libmono-cil-dev (= 6.12.0.182-0xamarin1+ubuntu2004b1), referenceassemblies-pcl, ___msbuild___, ca-certificates-mono (= 6.12.0.182-0xamarin1+ubuntu2004b1)

What does `apt list msbuild` show?

**Comment by combivanCoder** [comment]
> No, i'm not going to do a fresh install! Takes too long.
> 
> The instructions as given work on Debian. Thats as far as I'm going to test it.

Are you using stable or testing though? Most distributions like Ubuntu use testing as a base for LTS, and unstable for non-LTS, rather than the older (more reliable) stable channel for Debian. May be worth using testing as a middle ground, not sure what MX and Mint use.

**Comment by combivanCoder** [comment]
> Odd - `mono-complete` in https://download.mono-project.com/repo/ubuntu/dists/stable-focal/main/binary-amd64/Packages has:
> 
> Depends: mono-runtime (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-runtime-sgen (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-llvm-support (= 6.12.0.182-0xamarin1+ubuntu2004b1), libmono-2.0-1 (= 6.12.0.182-0xamarin1+ubuntu2004b1), libmono-profiler (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-utils (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-devel (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-mcs (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-roslyn (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-csharp-shell (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-4.0-gac (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-4.0-service (= 6.12.0.182-0xamarin1+ubuntu2004b1), monodoc-base (= 6.12.0.182-0xamarin1+ubuntu2004b1), monodoc-manual (= 6.12.0.182-0xamarin1+ubuntu2004b1), libmono-cil-dev (= 6.12.0.182-0xamarin1+ubuntu2004b1), referenceassemblies-pcl, _**msbuild**_, ca-certificates-mono (= 6.12.0.182-0xamarin1+ubuntu2004b1)

Agreed. It *should* be implied by `apt`

> What does `apt list msbuild` show?

Well this is bizarre:
`Listing... Done`

That cannot be right. Just checked on a clean Ubuntu 22.04 install and exactly the same situation (once the appropriate source has been added of course).

Given the variance of distributions based on Debian I honestly think the docs need adjustment to:
`apt install mono-complete msbuild`

Did this and something unjammed.... despite the `apt list msbuild` output noted previously got a successful package install.

Does not build from release artefact zip-ed code ({Audio,ExtendedControls,ActionLanguage,DirectInput,EDDiscovery}.csproj not found), does build from latest repo code though.

Runs fine... but no ability to hook into Frontier CAPI...

**Comment by klightspeed** [comment]
> > Odd - `mono-complete` in https://download.mono-project.com/repo/ubuntu/dists/stable-focal/main/binary-amd64/Packages has:
> > Depends: mono-runtime (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-runtime-sgen (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-llvm-support (= 6.12.0.182-0xamarin1+ubuntu2004b1), libmono-2.0-1 (= 6.12.0.182-0xamarin1+ubuntu2004b1), libmono-profiler (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-utils (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-devel (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-mcs (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-roslyn (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-csharp-shell (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-4.0-gac (= 6.12.0.182-0xamarin1+ubuntu2004b1), mono-4.0-service (= 6.12.0.182-0xamarin1+ubuntu2004b1), monodoc-base (= 6.12.0.182-0xamarin1+ubuntu2004b1), monodoc-manual (= 6.12.0.182-0xamarin1+ubuntu2004b1), libmono-cil-dev (= 6.12.0.182-0xamarin1+ubuntu2004b1), referenceassemblies-pcl, _**msbuild**_, ca-certificates-mono (= 6.12.0.182-0xamarin1+ubuntu2004b1)
> 
> Agreed. It _should_ be implied by `apt`
> 
> > What does `apt list msbuild` show?
> 
> Well this is bizarre: `Listing... Done`

I wonder if `msbuild` was missing from the Packages file at some point in the past, and `apt update` hadn't picked up the updated Packages?

> 
> That cannot be right. Just checked on a clean Ubuntu 22.04 install and exactly the same situation (once the appropriate source has been added of course).
> 
> Given the variance of distributions based on Debian I honestly think the docs need adjustment to: `apt install mono-complete msbuild`
> 
> Did this and something unjammed.... despite the `apt list msbuild` output noted previously got a successful package install.
> 
> Does not build from release artefact zip-ed code ({Audio,ExtendedControls,ActionLanguage,DirectInput,EDDiscovery}.csproj not found), does build from latest repo code though.

The zip file would not include submodules.

> 
> Runs fine... but no ability to hook into Frontier CAPI...

Enabling CAPI would require re-instating the old `HttpListener` based OAuth flow.

There are also a number of panels that use features that are not available under Mono, and stuff like speech recognition, text to speech, hotkeys, etc. are not available under Mono.

**Comment by combivanCoder** [comment]
> I wonder if `msbuild` was missing from the Packages file at some point in the past, and `apt update` hadn't picked up the updated Packages?

This is entirely plausible.

> The zip file would not include submodules.

Understood, thought that may be as intended.

> Enabling CAPI would require re-instating the old `HttpListener` based OAuth flow.

I'll have a look through the codebase although pressed for time with some sqdn services & discord bot development. EDD is a fantastic tool and was delighted to see there's a nix build / support for it. Got a med sized sqdn of console cmdrs that would benefit and booting into Windows just for one tool is a bit of a pain; our PC cmdrs have no issues obviously. EDD also appears to be the only tool which considers console cmdrs.

> There are also a number of panels that use features that are not available under Mono, and stuff like speech recognition, text to speech, hotkeys, etc. are not available under Mono.

Yeh I totally get that. No Windows namespaces makes that a bit tricky ;) Expectations were set appropriately on the wiki btw.
