### ISSUE TITLE
3D Map crashes

### ISSUE THREAD

**Issue by TrabucJL** [EDDiscovery/EDDiscovery#3282]
### Description
When I add the 3d map in a folder the program crashes and needs to relaunch.

### Additional Information
![image](https://user-images.githubusercontent.com/107922184/174771197-c0c1e481-007b-46dd-a65e-e56847890394.png)

### Exception Details:
>EDDiscovery v15.0.4.0 An unhandled fatal exception has occurred.
>```
>==== BEGIN ====
>System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>   at OpenTK.Graphics.OpenGL4.GL.DrawElementsInstancedBaseVertexBaseInstance(PrimitiveType mode, Int32 count, DrawElementsType type, IntPtr indices, Int32 instancecount, Int32 basevertex, Int32 baseinstance) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Graphics\OpenGL4\GL4.cs:line 17747
>   at GLOFC.GL4.GLRenderableItem.Render()
>   at GLOFC.GL4.Controls.GLControlDisplay.Render(GLRenderState currentstate, UInt64 ts)
>   at System.Action`1.Invoke(T obj)
>   at GLOFC.WinForm.GLWinFormControl.GlControl_Paint(Object sender, PaintEventArgs e)
>   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
>   at OpenTK.GLControl.OnPaint(PaintEventArgs e) in I:\work\github\opentk\src\OpenTK.GLControl\GLControl.cs:line 287
>   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
>   at System.Windows.Forms.Control.WmPaint(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.UserControl.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
This is due to your laptops graphics card drivers for the chip you are using. Some opengl implementations are buggy and don't meet the spec.

See #3271 for a remedy if you have a dual GPU adaptor.

**Comment by robbyxp1** [comment]
Closing, please us 3271 if you require more assistance.
