### ISSUE TITLE
Keep track of biological scans in surveyor

### ISSUE THREAD

**Issue by uxlapogi** [EDDiscovery/EDDiscovery#3289]
Hi,

I'd like to be able to see in one glance if I have already scanned the biologicals on a planet. I'd like to request either a (hopefully small) new option for the expedition planner or the surveyor.

**Expedition planner**
This does track my scanning progress for biologicals, but here I only have the option to show all planets in a system or none, also removing the ones I want to see. The filter for signals only works if I have all planets displayed which clutters the table, also showing planets I am not interested in.
If possible I'd like to be able to filter out planets, similar to the system scan panel:
A. Maybe 'Has signals' could override 'show all planets' and show planets with signals (this would also display those with geological signals, but you can't have everything i guess :/)
B. Or an additional option for always displaying geo or bio signals.

**Surveyor**
As an alternative, if the above option of the expedition planner could be added to the surveyor panel to also track progress of biological scans (e.g. Has biological signals. Has been scanned for organics.), that would be awesome. :D

Love your tool btw. :)

o7,
Ux

**Comment by uxlapogi** [comment]
The organics panel only keeps a record of scans without giving a completion status for a given system. I currently only use it in case I haven't completed a scan on a body from a previous session.
The combination of surveyor requires me to doublecheck and compare the names of each body in surveyor and organics panel, which is not ideal.
So yes, it works somewhat, and it's what I am using at the moment but it is cumbersome and requires extra steps to compare multiple inputs which can be prone to error.

**Comment by robbyxp1** [comment]
I'm going to add a organic symbol to the surveyor (and other places where that code is used, expedition, star list) to show you've done an organic scan, and if you completed them all..

thanks for the idea!
