### ISSUE TITLE
Feature query

### ISSUE THREAD

**Issue by mearmortal** [EDDiscovery/EDDiscovery#3293]
I've mentioned this on discord but I think it may have gotten lost in the ether.
I'm out exploring and would like a view created for a particular purpose if possible.
I'd like to be able to see a list of bodies with Geo and Bio quantities< I'd like to see those with Geo quantities to also show volcanism if there is one, and none if not.
I understand these will only appear in a detailed scan, FSS body signals or SSA signals entries.

As my purpose is to update my own codex entries and collect Bio data, I don't see an appropriate view in EDD for the collection.
Organic Scans works great after you've found them, and estimated values only show applicable credit gains. I use both to keep track of my totals, and estimated values works great for determining what is worth scanning and what is not.

let me know your thoughts.

Thank you.

**Comment by Eahlstan** [comment]
It's simple: If a body has geological signals it has volcanism. Or do you want to see the specific type of volcanism?

> As my purpose is to update my own codex entries and collect Bio data, I don't see an appropriate view in EDD for the collection.
> Organic Scans works great after you've found them, and estimated values only show applicable credit gains. I use both to keep track of my totals, and estimated values works great for determining what is worth scanning and what is not.

I don't get that. What is it that you want to have that's missing?

**Comment by mearmortal** [comment]
Hi there So seeing volcanism goes towards identifying if you've found something different or not in system, and whether you'll get a reward for scanning it. Plenty of times I've already discovered it on another body and therefore no further reward.

As for the other item, I'd like to see No. of bio/Geo instances as part of the detailed scan, but in estimated values it won't show it but it would be ideal to have it there or somewhere else of your choosing

Thanks for the response

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Eahlstan** [comment]
Good news, in the next release the number of signals detected will be shown on all panels that show signals (if we didn't miss any).
Estimated values is meant to show scanning values of bodies. We're not going to bloat that panel up by showing more than those values, it's just not what this panel is.
Did you try if you can customize the Surveyor panel to show the things you want to? (In the next release you will be able to define and save your very own searches and use them on the Surveyor.) 
![Screenshot 2022-07-27 201841](https://user-images.githubusercontent.com/59618179/181344281-884536cb-be75-4fce-870f-94efa483902a.png)

**Comment by mearmortal** [comment]
Thanks for that, will take a look at the surveyor panel shortly

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by robbyxp1** [comment]
I think this is answered
