### ISSUE TITLE
crashed when clicking on start date dropdown on organic scans tab

### ISSUE THREAD

**Issue by rocknrollbetty** [EDDiscovery/EDDiscovery#3296]
crashed when clicking on start date dropdown on organic scans tab

currently set to 14 december 0002.  cant change it due to crash

**Comment by rocknrollbetty** [comment]
does it every time :) let me know if you ned more info.

### Description


### Additional Information


### Exception Details:
>EDDiscovery v15.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Value of '14/12/0002' is not valid for 'SelectionEnd'. 'SelectionEnd' must be greater than or equal to MinDate.
>Parameter name: SelectionEnd
>   at System.Windows.Forms.MonthCalendar.set_SelectionEnd(DateTime value)
>   at ExtendedControls.CalendarForm.set_Value(DateTime value) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\CalendarForm.cs:line 36
>   at ExtendedControls.ExtDateTimePicker.Calendaricon_MouseClick(Object sender, MouseEventArgs e) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\DateTimePicker.cs:line 428
>   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
Probably need to clamp the `CalendarForm.Value` between `Calendar.MinDate` and `Calendar.MaxDate`.
The minimum date supported by `MonthCalendar` and `DateTimePicker` is 01 Jan 1753.

**Comment by klightspeed** [comment]
In the meantime you should be able to click the year and enter a valid value, then try picking the date again using the calendar icon.

**Comment by robbyxp1** [comment]
Can clamp the date in GetSettings.. that would be generic

**Comment by robbyxp1** [comment]
I've no idea how it got to that date.

**Comment by klightspeed** [comment]
Click the year, type 2, click the calendar icon, crash

**Comment by robbyxp1** [comment]
gotcha.

**Comment by robbyxp1** [comment]
i'll fix

**Comment by robbyxp1** [comment]
fixed i hope. thanks for the report.

**Comment by rocknrollbetty** [comment]
> In the meantime you should be able to click the year and enter a valid value, then try picking the date again using the calendar icon.

thanks. corrected duff date as above (no crash), but the scans shown & credit total does not seem to be updating to reflect the date range. I've tried closing and re-starting, but no change.

![Screen Shot 08-06-22 at 02 24 PM](https://user-images.githubusercontent.com/46960073/183250918-320ba9f3-c398-4ed0-b1c2-9fc87b1ae2aa.PNG)

**Comment by Eahlstan** [comment]
To reflect the date range you have to check the check box next to the start and/or end date.

**Comment by rocknrollbetty** [comment]
so you do!!!  thanks very much. missed that.
