### ISSUE TITLE
Issue attempting to restart in Safe Mode. 

### ISSUE THREAD

**Issue by Rahkan** [EDDiscovery/EDDiscovery#3298]
### Exception Details:
>EDDiscovery v15.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.Threading.ThreadAbortException: Thread was being aborted.
>   at System.Threading.Thread.AbortInternal()
>   at System.Threading.Thread.Abort()
>   at EDDiscovery.UserControls.UserControlSettings.buttonExtSafeMode_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Settings\UserControlSettings.cs:line 719
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

When I hit 'Continue' in an attempt to ignore the error. It hits me with

An unhandled fatal exception has occurred.

==== BEGIN ====
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====

This is after waiting about 5-7m after initial launch of the program so it downloads all it's database stuff. 
It took me 5 attempts to be able to reboot the program into safe mode. I then was able to move the database like I intended (Small C drive.)

**Comment by klightspeed** [comment]
https://github.com/EDDiscovery/EDDiscovery/blob/22a0eb45d9af67d91e2774200e5cb027a356d816/EDDiscovery/UserControls/Settings/UserControlSettings.cs#L707-L717

That suggests that you clicked the "Restart in safe mode" twice, suggesting that the first `Application.Exit()` didn't work.

**Comment by robbyxp1** [comment]
I can't repo, but i'll keep it in mind for the future. thanks for the report.
