### ISSUE TITLE
Class II Gas Giants missing from Surveyor

### ISSUE THREAD

**Issue by mearmortal** [EDDiscovery/EDDiscovery#3303]
I'm out there exploring, and I'm trying to select bodies worth scanning, now I have a popout panel open for Estimated Values, and I also have one for the Surveyor panel.
Now under the Surveyor panel, I've selected the one's I want based on Ammonia Worlds through to Terraformable, Biological and other signals. But what I can't include on it's own is Class II's, as you know, mapping Class II's gives a lot more credits than the other classes, normally in access of 200K more. Is there anyway Class II's can be added.

Also, the Surveyor Panel has the Text Alignment feature but the Organic Scans as yet does not, can this be added please. This applies to the popout window, where the table is hidden and the scanned Bio's are listed as they are found.

Thanks.

**Comment by Eahlstan** [comment]
As of version 15.1.1 you are free to define everything you're looking for in the [search](https://github.com/EDDiscovery/EDDiscovery/wiki/Using-the-Search-Scans-Panel) panel, save those searches and use them by selecting them in the "[magnifying glass](https://www.youtube.com/watch?v=3aApsza_y8w)" menu of the Surveyor.

As for the text alignment I will see if it's possible to add that to the overlay part of the Organics panel.

Thank you,

**Comment by robbyxp1** [comment]
![image](https://user-images.githubusercontent.com/6573992/185932628-966b01d1-bbfb-4e5b-bc15-adcaedc2e6dc.png)

**Comment by robbyxp1** [comment]
etc
![image](https://user-images.githubusercontent.com/6573992/185932736-83855a6e-f57f-4396-9b7f-2c7ecfd50185.png)

**Comment by robbyxp1** [comment]
Closing as answered
