### ISSUE TITLE
EDDN - UTF encoding on outfitting/2 sometimes ?

### ISSUE THREAD

**Issue by Athanasius** [EDDiscovery/EDDiscovery#3304]
This is only showing up from one source, a few times a day the past couple of days:
```
2022-08-21 13:10:41,103 - ERROR - Gateway:241: Failed Validation "[<ValidationError: "u'\\u0131nt_dockingcomputer_standard' does not match '(^Hpt_|^hpt_|^Int_|^int_|_Armour_|_armour_)'">]" (28331, "EDDiscovery", "15.1.1.0", "https://eddn.edcd.io/schemas/outfitting/2", "-") from <ip>
```
That `\\u0131` is apparently ['LATIN SMALL LETTER DOTLESS I' (U+0131)](https://www.fileformat.info/info/unicode/char/0131/index.htm).

It's entirely possible this is a Frontier issue.

**Comment by robbyxp1** [comment]
["modules"] = new JArray(journal.YardInfo.Items.Select(m => JournalFieldNaming.NormaliseFDItemName(m.FDName)))

        static public string NormaliseFDItemName(string s)      // has to deal with $int and $hpt.. This takes the FD name and keeps it, but turns it into the form
        {                                                       // used by Coriolis/Frontier API
            //string x = s;
            if (s.StartsWith("$int_"))
                s = s.Replace("$int_", "Int_");
            if (s.StartsWith("int_"))
                s = s.Replace("int_", "Int_");
            if (s.StartsWith("$hpt_"))
                s = s.Replace("$hpt_", "Hpt_");
            if (s.StartsWith("hpt_"))
                s = s.Replace("hpt_", "Hpt_");
            if (s.Contains("_armour_"))
                s = s.Replace("_armour_", "_Armour_");      // normalise to Armour upper cas.. its a bit over the place with case..
            if (s.EndsWith("_name;", StringComparison.InvariantCultureIgnoreCase))
            {
                //System.Diagnostics.Debug.WriteLine("Correct " + s);
                s = s.Substring(0, s.Length - 6);
            }
            if (s.StartsWith("$"))                          // seen instances of $python_armour..
                s = s.Substring(1);

            return s;
        }

            YardInfo = new Outfitting(evt["StationName"].Str(), evt["StarSystem"].Str(), EventTimeUTC, evt["Items"]?.ToObjectQ<Outfitting.OutfittingItem[]>());

etc.

I see no path to introduce this character..

**Comment by klightspeed** [comment]
`"I".ToLower()` with a Turkish locale will result in that character.

This occurs in https://github.com/EDDiscovery/EDDiscovery/blob/b67d55130d90c795047f52d3ddabbe3730d4b078/EDDiscovery/EDDiscoveryControllerNewEntry.cs#L257

**Comment by robbyxp1** [comment]
Well, that ToLower() is in a lot of places
No point fixing it just there

**Comment by robbyxp1** [comment]
We have a ToLowerInvariant, i'll have to look thru and find usages of tolower()

**Comment by robbyxp1** [comment]
I've ToLowerInvariant everything.. hopefully this will fix it. thanks for the report. Will be in 15.1.2 coming this week.
