### ISSUE TITLE
ArgumentOutOfRangeException on Expedition Route Deletion

### ISSUE THREAD

**Issue by louisrousseau** [EDDiscovery/EDDiscovery#3308]
### Description
Tried to delete an expedition.

### Exception Details:
>EDDiscovery v15.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: L'index était hors limites. Il ne doit pas être négatif et doit être inférieur à la taille de la collection.
>Nom du paramètre : index
>   à System.Collections.ArrayList.get_Item(Int32 index)
>   à System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
>   à System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
>   à EDDiscovery.UserControls.UserControlExpedition.<UpdateSystemRows>d__27.MoveNext() dans C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlExpedition.cs:ligne 330
>--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by klightspeed** [comment]
That would seem to suggest that the table hadn't properly updated its row count when it tries to update the table after deleting the row.

**Comment by klightspeed** [comment]
Correction - it might be a race, where the row was deleted while it was querying EDSM for the row(s) that were deleted.

**Comment by robbyxp1** [comment]
Its probably as you said, it was during the await, the table got cleared, the await finished, nothing to update, bang.

**Comment by robbyxp1** [comment]
Best to turn off some buttons during row update

**Comment by klightspeed** [comment]
Perhaps abort the update if the row count has changed after returning from the EDSM query?

**Comment by robbyxp1** [comment]
Could do. My first thought was to disable the relevant buttons, but that might be simpler..  Let it percolate for a bit.

**Comment by robbyxp1** [comment]
Fixed in 15.1.3
