### ISSUE TITLE
[Request] Anti Xeno Statistics

### ISSUE THREAD

**Issue by Jugom** [EDDiscovery/EDDiscovery#3311]
Create a Thargoid related tab in the Statistics panel that keeps track of how many scouts and cyclops/basilisk/medusa/hydra interceptors you have killed so far.

as a side note, not sure if it is possible to also keep track of hyperdictions (including timestamps and system name)

**Comment by Eahlstan** [comment]
I'm against a Thargoid related tab. If such a thing is made it should cover all combat to fit the Statistics panel.

**Comment by Jugom** [comment]
what would be the rest of "all combat"? isn't that already covered in the _in game_ tab?

**Comment by Eahlstan** [comment]
Oh sweet child. Don't you think if it's possible to separate Thargoids it's also possible to separate the ships and ranks from other kills? I don't know about on foot kills, but there can be surely made something out of them too.

**Comment by Jugom** [comment]
I just assumed the in game tab would remain untouched as it compiles the info we see in the player codex in game.

**Comment by robbyxp1** [comment]
Noted. Please don't hold your breath, I have a large backlog.

**Comment by Eahlstan** [comment]
> I just assumed the in game tab would remain untouched as it compiles the info we see in the player codex in game.

Yeah. But you want a tiny fraction of the field of "combat" to be extracted. I say: If another subpanel gets added, why focus just on a fraction of that section when it's likely that more stats can be displayed?
