### ISSUE TITLE
Issue opening 3D map

### ISSUE THREAD

**Issue by RPeterson0487** [EDDiscovery/EDDiscovery#3312]
Hello,
I have been unable to open the 3D map on Windows 10 on an Asus G74SX with 16GB of RAM, Intel i7-2630QM 2GHZ, GTX560m.  As requested, I am including the reports and some screenshots.  Please let me know what else I can provide.  Thank you!

--Zeta Squirrel
![Screenshot 2022-09-05 113421](https://user-images.githubusercontent.com/69528095/188493848-99b7067a-08ba-4c7f-97b9-9f740ae19344.jpg)
[3d Map Unhandled Exception.txt](https://github.com/EDDiscovery/EDDiscovery/files/9491406/3d.Map.Unhandled.Exception.txt)
[OpenGL Details.txt](https://github.com/EDDiscovery/EDDiscovery/files/9491407/OpenGL.Details.txt)
![OpenGL Extension Viewer 6](https://user-images.githubusercontent.com/69528095/188493899-a228fd9f-cded-4294-a698-416002336d82.png)

**Comment by klightspeed** [comment]
If you expand `ARB 2015`, what features are unsupported I wonder?

**Comment by robbyxp1** [comment]
With that chip, its a wonder anything will work. 

Max memory is 1536MB according to https://www.notebookcheck.net/NVIDIA-GeForce-GTX-560M.48313.0.html.  

I think we may not be able to do anything.

**Comment by RPeterson0487** [comment]
![image](https://user-images.githubusercontent.com/69528095/188515272-4b15e2a1-a913-4ace-98c3-0cb8f6293924.png)

**Comment by Eahlstan** [comment]
So comparing the XML containing all features of that user with the one made by me shows that ARB_bindless_texture is present on my system, but missing on that users system.
