### ISSUE TITLE
The "History" of each of my CMDR is the same for all my accounts

### ISSUE THREAD

**Issue by heatherg23** [EDDiscovery/EDDiscovery#3314]
The "History" listed for all my accounts is the history of my main account only. It's always had it's own history, depending on the account I'm in,  and not sure why it's happening now. I've updated to the latest version which didn't solve the issue.

I changed the name for 2 of my accounts so my old CMDR names are still listed and used to have a history of *those* commanders only. Is there anything I can do to fix it?

**Comment by robbyxp1** [comment]
Changing versions won't alter a thing, as nothing in these systems have been touched for a long time.

One way you could try and solve it and see what happens is to run EDDISCOVERY.EXE -appfolder t1

That will create a new appfolder t1 in appdata\local and rescan the journals on your PC. See what it shows when it does this.

**Comment by robbyxp1** [comment]
As in, are your different commanders history properly segregated now? Do they have the right names etc? 

For the experiment, you don't need to download the EDSM data again - say no.

**Comment by robbyxp1** [comment]
You can delete t1 afterwards without affecting your main data in appdata\local\EDDiscovery.

**Comment by heatherg23** [comment]
I was able to get the history to be correct for the 2 commanders I have. I discovered that section where you select your commander somehow became unpinned.
