### ISSUE TITLE
edd crash on journal update

### ISSUE THREAD

**Issue by mrknify** [EDDiscovery/EDDiscovery#3315]
### Description

Just did a jump -- I use edd with console version of game.
### Exception Details:
>EDDiscovery v15.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>OpenTK.Graphics.GraphicsContextException: Failed to make context 131072 current. Error: 0
>   at OpenTK.Platform.Windows.WinGLContext.MakeCurrent(IWindowInfo window) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Platform\Windows\WinGLContext.cs:line 279
>   at EDDiscovery.UserControls.UserControl3DMap.SystemTick(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\UserControl3DMap.cs:line 106
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Thats a graphics error..  What is your graphics system.  We have lots of problems with some openGL implementations not meeting specification.

**Comment by klightspeed** [comment]
This seems to be the same as #3276, where it occurred after resuming from sleep.

**Comment by robbyxp1** [comment]
We are presuming its a sleeping issue. Closing unless new information appears.
