### ISSUE TITLE
Toggle title visibility for this window when transparent nonfunctional

### ISSUE THREAD

**Issue by Uma410** [EDDiscovery/EDDiscovery#3316]
The toggle title visibility for this window when transparent doesn't work on pop out windows. On either of the two settings the title is hidden when it the window is transparent.

**Comment by Eahlstan** [comment]
Define "this window".

**Comment by robbyxp1** [comment]
Yep, we need more information, such as which panel you were using, what exactly the steps are..

**Comment by Eahlstan** [comment]
That's not the title bar, that's part of the Surveyor panel content.
If you're not seeing the setting icons
![Screenshot 2022-09-12 184358](https://user-images.githubusercontent.com/59618179/189710273-500d6f02-9bae-46a8-a0f6-a92542d14514.png)
everything that should be hidden in transparent mode is hidden.
The order of the things in your screenshots makes me wonder if you're running an old version though.

**Comment by robbyxp1** [comment]
Closing, no more data.
