### ISSUE TITLE
Crash on filtering events

### ISSUE THREAD

**Issue by Herkfixer** [EDDiscovery/EDDiscovery#3317]
### Description

Click on "None" for filters and crsahed.
### Exception Details:
>EDDiscovery v15.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.Collections.ArrayList.get_Item(Int32 index)
>   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
>   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
>   at EDDiscovery.UserControls.UserControlTravelGrid.<>c__DisplayClass37_0.<HistoryChanged>b__0() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 350
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Have outlining on, and then go to None.

![image](https://user-images.githubusercontent.com/6573992/189516060-5fd0631c-5c6c-4dfd-97ef-bd6fed4720bc.png)


Reproduced.. i'll look into from wed on.  Pretty easy fix.

thanks for the report.

**Comment by robbyxp1** [comment]
Ok, found time, fixed on master and Dev. Thanks

**Comment by Herkfixer** [comment]
Wow, you work fast. Thanks.
