### ISSUE TITLE
unhandled UI exception

### ISSUE THREAD

**Issue by MaxeoN** [EDDiscovery/EDDiscovery#3318]
### Exception Details:
>EDDiscovery v15.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentNullException: Значение не может быть неопределенным.
>Имя параметра: ptr
>   в System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
>   в EliteDangerousCore.DLL.EDDDLLCaller.Shown() в C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\DLL\EDDDLLCaller.cs:строка 187
>   в EliteDangerousCore.DLL.EDDDLLManager.Shown() в C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\DLL\EDDDLLManager.cs:строка 152
>   в EDDiscovery.EDDiscoveryForm.EDDiscoveryForm_Shown(Object sender, EventArgs e) в C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:строка 823
>   в System.Windows.Forms.Form.OnShown(EventArgs e)
>   в System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   в System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   в System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>===== END =====
>```

**Comment by Eahlstan** [comment]
What did you do when this happened?
Does it happen all the time?

**Comment by klightspeed** [comment]
`pShown` is being compared to `null`, when it should be compared to `IntPtr.Zero`

**Comment by Eahlstan** [comment]
> https://github.com/EDDiscovery/EliteDangerousCore/blob/989d036406a6eb1de57f8a09e2f570da21ff72ac/EliteDangerous/DLL/EDDDLLCaller.cs#L185
> 
> `pShown` is being compared to `null`, when it should be compared to `IntPtr.Zero`

Great to know.
I still wonder how to trigger it, I've spent countless minutes on it in the past and never had a crash.

**Comment by klightspeed** [comment]
> > https://github.com/EDDiscovery/EliteDangerousCore/blob/989d036406a6eb1de57f8a09e2f570da21ff72ac/EliteDangerous/DLL/EDDDLLCaller.cs#L185
> > `pShown` is being compared to `null`, when it should be compared to `IntPtr.Zero`
> 
> Great to know. I still wonder how to trigger it, I've spent countless minutes on it in the past and never had a crash.

It needs a native / C++ DLL addon

**Comment by MaxeoN** [comment]
that happens every time the program starts

**Comment by klightspeed** [comment]
> 

Any native / C++ DLL that does not implement `EDDMainFormShown` is going to have the issue, due to `pShown` being compared to `null` instead of `IntPtr.Zero`

**Comment by Eahlstan** [comment]
> > Then you could try to add back on DLL after the other until you know which one causes this problem.
> 
> Any native / C++ DLL that does not implement `EDDMainFormShown` is going to have the issue, due to `pShown` being compared to `null` instead of `IntPtr.Zero`

Yep. Just trying to help him get it running until a patch is deployed. I have some DLLs loaded myself without problems so it's possible that most of the DLLs of that user will work with the current version.

**Comment by MaxeoN** [comment]
Thanks for help. Found dll that coused the problem. I use logitech X52 pro with EDD. X52 needs two dll to work properly. 
DirectOutput.dll and [EDDX52](https://github.com/Theaninova/EDDX52/releases/tag/v1.1-alpha)
Previous versions worked fine with it. Actually v15.1.2.0 works too if i click a continue button in an error window.
As far as i really need this functionality, please add support of that DLL in future releses.

**Comment by MaxeoN** [comment]
That plugin works fine with all previous versions
https://github.com/Theaninova/EDDX52/issues/5#issuecomment-780150671

**Comment by klightspeed** [comment]
The bug was introduced in EDDiscovery/EliteDangerousCore@bdf68134a08abb8be598b4677d8c3fdf6a74b48e (included in 15.1.0), and should be fixed in 15.1.3
