### ISSUE TITLE
Unhandled exception on load

### ISSUE THREAD

**Issue by Randomgazz** [EDDiscovery/EDDiscovery#3322]
### Description
Unhandled exception on load. History tab selected from last load. ED launcher being loaded at same time.

### Exception Details:
>EDDiscovery v15.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.JournalEvents.JournalEngineerProgress.<>c__DisplayClass9_0.<ApplyProgress>b__0(ProgressInformation x) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalEngineer.cs:line 302
>   at System.Array.FindIndex[T](T[] array, Int32 startIndex, Int32 count, Predicate`1 match)
>   at System.Array.FindIndex[T](T[] array, Predicate`1 match)
>   at EliteDangerousCore.JournalEvents.JournalEngineerProgress.ApplyProgress(String[] engineers) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalEngineer.cs:line 300
>   at EDDiscovery.UserControls.UserControlEngineering.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\EngineeringSynthesis\UserControlEngineering.cs:line 297
>   at EDDiscovery.UserControls.UserControlEngineering.UCTGChanged(HistoryEntry he, HistoryList hl, Boolean selectedEntry) in C:\Code\EDDiscovery\EDDiscovery\UserControls\EngineeringSynthesis\UserControlEngineering.cs:line 198
>===== END =====
>```

**Comment by Randomgazz** [comment]
### Description
Updated to 15.1.3.0, similar occurred.

### Exception Details:
>EDDiscovery v15.1.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.JournalEvents.JournalEngineerProgress.<>c__DisplayClass9_0.<ApplyProgress>b__0(ProgressInformation x) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalEngineer.cs:line 302
>   at System.Array.FindIndex[T](T[] array, Int32 startIndex, Int32 count, Predicate`1 match)
>   at System.Array.FindIndex[T](T[] array, Predicate`1 match)
>   at EliteDangerousCore.JournalEvents.JournalEngineerProgress.ApplyProgress(String[] engineers) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalEngineer.cs:line 300
>   at EDDiscovery.UserControls.UserControlEngineering.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\EngineeringSynthesis\UserControlEngineering.cs:line 297
>   at EDDiscovery.UserControls.UserControlEngineering.UCTGChanged(HistoryEntry he, HistoryList hl, Boolean selectedEntry) in C:\Code\EDDiscovery\EDDiscovery\UserControls\EngineeringSynthesis\UserControlEngineering.cs:line 198
>===== END =====
>```

**Comment by Randomgazz** [comment]
Reload with Engineer tab closed and no exception.

**Comment by Eahlstan** [comment]
@robbyxp1 We got a second bad EngineerProgress event, it might be wise to release a 15.1.4 with the fix - now that it seems like this wasn't a one time error of Frontier.

**Comment by Eahlstan** [comment]
Fixed by https://github.com/EDDiscovery/EliteDangerousCore/commit/e5da7b6519a71509197bea6f8d09325cc650336a

**Comment by Eahlstan** [comment]
Thanks for your report, we had another user reporting the same thing 2 days ago. This is due to Frontier writing malformed data to the journal files. We already protected against it in the code and will release a protected version soon.
In the meantime please keep your Engineers panel closed (as you already noticed yourself).

**Comment by robbyxp1** [comment]
Ack

**Comment by robbyxp1** [comment]
Fixed in https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_15.1.4
