### ISSUE TITLE
Feature request: import material list from EDSY into shopping list

### ISSUE THREAD

**Issue by uxlapogi** [EDDiscovery/EDDiscovery#3323]
Hi,

when I use the EDSY retrofit report under ANALYSIS I get a handy list of all materials needed to upgrade from my current build to my target build.
If possible I'd like to be able to import this into the shopping list.

Thanks!

EDIT: Here's an example list as generated by EDSY:

---Checklist:

Build Module Act Details
Lazy Mule 0I Heat Sink Launcher Buy 0,0% discount
Lazy Mule 4A Power Plant Eng Low Emissions G1 x1
Lazy Mule 4A Power Plant Eng Low Emissions G2 x1.5
Lazy Mule 4A Power Plant Eng Low Emissions G3 x2.5
Lazy Mule 4A Power Plant Eng Low Emissions G4 x4
Lazy Mule 4A Power Plant Exp Stripped Down
Lazy Mule 6A Frame Shift Drive Eng Increased Range G5 x7
Lazy Mule 5D Power Distributor Eng Charge Enhanced G1 x1
Lazy Mule 5D Power Distributor Eng Charge Enhanced G2 x1.5
Lazy Mule 5D Power Distributor Eng Charge Enhanced G3 x2.5
Lazy Mule 4D Sensors Eng Light Weight G1 x1
Lazy Mule 4D Sensors Eng Light Weight G2 x1.5
Lazy Mule 4D Sensors Eng Light Weight G3 x2.5

---Materials list:

Item Type Lvl Qty
Credits 3.500
Arsenic Raw G2 7
Chemical Distillery Mfc G3 3
Chemical Manipulators Mfc G4 7
Chemical Processors Mfc G2 2
Conductive Ceramics Mfc G3 3
Datamined Wake Exceptions Enc G5 7
Germanium Raw G2 4
Grid Resistors Mfc G1 8
Heat Exchangers Mfc G3 3
Heat Vanes Mfc G4 4
Iron Raw G1 5
Irregular Emission Data Enc G2 4
Manganese Raw G2 4
Modified Consumer Firmware Enc G2 3
Phosphorus Raw G1 1
Proto Light Alloys Mfc G4 1
Salvaged Alloys Mfc G1 4
Specialised Legacy Firmware Enc G1 3
Unexpected Emission Data Enc G3 4
Vanadium Raw G2 3

**Comment by robbyxp1** [comment]
The shopping list does not work this way, it takes your engineering vs your current material state and produces a list this way around.

This would be another panel, a wanted materials panel.  Maybe an extension of the materials panel..

will add it to the backlog.

**Comment by Eahlstan** [comment]
Just a thought:

Beside the strange "Engineer your Sensors 2.5 times" requirement, the first part entered into EDD would produce the list of the second part. So if EDSY fixes the impossible amounts it should be possible to use the list in the current shopping list panel.

**Comment by robbyxp1** [comment]
For those looking for this, see the resources panel.  It allows a list of materials to be imported.
