### ISSUE TITLE
Surveyor - status icons not updating 

### ISSUE THREAD

**Issue by uxlapogi** [EDDiscovery/EDDiscovery#3325]
Hi,

As the title says, once I have mapped a planet and completed all biological samples, the status icons only update after I click on some of the buttons in surveyor, e.g. open the display settings.
Then the status immediately updates.

**Comment by Eahlstan** [comment]
Is the "organics completed" thing the only one affected?

**Comment by Eahlstan** [comment]
Bug confirmed.

**Comment by uxlapogi** [comment]
I think for me Surveyor as a whole does not update.
I was travelling through systems with 'Set High Value Limit' set to 500k and it never triggered although I had planets exceeding the threshold.
I can send you any logs you need if you tell me which ones would help.

Attached the screenshots of my recent history panel.
![EDD_history_2022-09-26 040257](https://user-images.githubusercontent.com/5829697/192179924-2fbb257c-34c6-4154-81da-068881c725cd.jpg)

**Comment by klightspeed** [comment]
If the main travel history panel is not set to automatically move the cursor to the latest entry, then the surveyor panel is not going to update without manual intervention, as it relies on the `OnTravelSelectionChanged` event for most updating, and handles only the `NavRoute` journal entry in the `OnNewEntry` event.

**Comment by Eahlstan** [comment]
Looking at your screenshot you filtered out most events. Please show all events as this filtered view might be the reason. (Also: high value limit on the Surveyor? Sure you're talking about the correct panel?)

**Comment by uxlapogi** [comment]
> If the main travel history panel is not set to automatically move the cursor to the latest entry, then the surveyor panel is not going to update without manual intervention, as it relies on the `OnTravelSelectionChanged` event for most updating, and handles only the `NavRoute` journal entry in the `OnNewEntry` event.
> Looking at your screenshot you filtered out most events. Please show all events as this filtered view might be the reason. (Also: high value limit on the Surveyor? Sure you're talking about the correct panel?)

I wasn't aware that the filter in the history affects the Surveyor and I could swear I had this filtered during my 5k LY expedition a couple weeks ago and Surveyor worked fine. Is this a recent change or has this been this way for a long time?
Anyway, I'll test with no filters on the history events.

(Also, yes, wrong panel, I filtered by earthlike and biosignals in Surveyor.)

**Comment by Eahlstan** [comment]
All panels follow the history cursor of the main history panel, it's always been that way. So if you filter for only event X and then 100 other newer events happen the cursor stays on the last X event and the other panels (most likely) won't update until a new event X.
So out of curiosity: Which panel were you talking about?

**Comment by uxlapogi** [comment]
Scan, I must've confused my two splitters :E
Also, I just confirmed, everything works as intended in Surveyor with no filters set on the history panel.
Apologies for taking your time.
