### ISSUE TITLE
There was an unhandled UI exception after waking PC from sleep mode.

### ISSUE THREAD

**Issue by bandophahita** [EDDiscovery/EDDiscovery#3330]
### Description
Woke PC from sleep mode while app was running and noticed the app produced the exception window.  

### Exception Details:
>EDDiscovery v15.1.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>OpenTK.Graphics.GraphicsContextException: Failed to make context 131072 current. Error: 0
>   at OpenTK.Platform.Windows.WinGLContext.MakeCurrent(IWindowInfo window) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Platform\Windows\WinGLContext.cs:line 279
>   at EDDiscovery.UserControls.UserControl3DMap.SystemTick(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\UserControl3DMap.cs:line 106
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

 _Bravo including the github template in the clipboard. It's the little things :)_

**Comment by Eahlstan** [comment]
We had this once in the past.
Sending the PC into sleep mode while the map is opened seems to be a bad idea. Please close the map before you let your PC sleep.

**Comment by bandophahita** [comment]
I don't usually have the map open.  I'll test it again tonight to be sure.

**Comment by Eahlstan** [comment]
The map is the only thing that uses OpenGL and as you can see in your error message the 3DMap was involved. So the likelihood that your map wasn't open is close to zero.
Further testing is always a good thing though.

**Comment by bandophahita** [comment]
Can't look at it now, but is the map something that always opens in another window, or is it possible to remain embedded?

**Comment by Eahlstan** [comment]
Like any panel you can either pop it out or use it as just another tab.

**Comment by bandophahita** [comment]
That was it; it was in a tab.  I closed that tab and after waking from sleep the error didn't occur.

**Comment by Eahlstan** [comment]
Great.

I'm closing this issue as this is not an EDD bug.

**Comment by robbyxp1** [comment]
Therotically it could be trapped and shut down the 3dmap more gracefully, if it could be repo
