### ISSUE TITLE
Sub Directories in log file directory.

### ISSUE THREAD

**Issue by smajeh** [EDDiscovery/EDDiscovery#3331]
I discovered that ED Discovery reads any sub directories under the standard log file directory.  This is probably by design.  For me it caused duplicate entries in ED Discovery because I used a subdirectory under the standard log directory for testing python programs that read log files.  I solved my issue by moving the test directory to a new location.

**Comment by Eahlstan** [comment]
And by log file you mean journal file?

**Comment by smajeh** [comment]
Yes the journal files. with an extension of log

**Comment by robbyxp1** [comment]
It has always searched all subfolders of the given watched folder, from day 0! We will consider this behaviour

**Comment by robbyxp1** [comment]
The next version, 15.2, will have an option in the commanders settings to look into subfolders or not.

thanks
