### ISSUE TITLE
Field filters don't seem to filter

### ISSUE THREAD

**Issue by aCandidMind** [EDDiscovery/EDDiscovery#3332]
Awesome software BTW thanks a lot!

I can setup the filters so there's indication it didn't accept my filters and when clicking OK the journal actually refreshes, but no matter what I tried it never actually removed rows.

Tried ReceiveText and filtering on channel with all sorts of operators and the same with MarketSell filtering on Commodity. 
![](https://cdn.discordapp.com/attachments/359066257699373058/1035856695626309682/unknown.png)

**Comment by klightspeed** [comment]
This is known, and should be fixed in the next version.

**Comment by robbyxp1** [comment]
Thanks for the report. Its fixed on the dev code as Klightspeed says. The new version will be out soon.

**Comment by aCandidMind** [comment]
You people rock!
