### ISSUE TITLE
Crash while shrinking the Star Database

### ISSUE THREAD

**Issue by charlesmcevoy** [EDDiscovery/EDDiscovery#3336]
### Description
Shrinking the Star database from All to Bubble+Colonia

### Exception Details:
>EDDiscovery v12.1.7.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>SQLLiteExtensions.SQLProcessingThreadException: disk I/O error
>disk I/O error ---> System.Data.SQLite.SQLiteException: disk I/O error
>disk I/O error
>   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
>   at SQLLiteExtensions.SQLExtRegister.PutSetting(String key, String sqlname, Object value) in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLRegister.cs:line 141
>   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 66
>   --- End of inner exception stack trace ---
>   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 89
>   at SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 247
>   at SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase[T](Func`2 func, Int32 warnthreshold) in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 0
>   at SQLLiteExtensions.SQLProcessingThread`1.WithReadWrite[T](Func`1 action) in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 391
>   at EDDiscovery.UserControls.UserControlSettings.buttonExtEDSMConfigureArea_Click(Object sender, EventArgs e) in C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\Settings\UserControlSettings.cs:line 582
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
I/O error could be due to the database journal not being writable (e.g. if the disk is full).  You might need to delete the EDDSystem.sqlite database file before trying to rebuild it using the new system selection.

**Comment by robbyxp1** [comment]
Closing. Please don't open another issue on this. If you need support, use this issue.
