### ISSUE TITLE
Hide window title

### ISSUE THREAD

**Issue by KingGLEB** [EDDiscovery/EDDiscovery#3341]
If in window "Scan" selected transparent window then the window title is hidden. The window title is shown only when the "opaque window" option is selected. Worked as it should in version 15.0.4, broke in version 15.1.1.

**Comment by Eahlstan** [comment]
Can confirm, ShowTitle doesn't work on panels like Scan and Combat.
Might be due to the changes here https://github.com/EDDiscovery/EDDiscovery/commit/fbdefcf60b339cc6854f2873193545d2a3f95026

**Comment by robbyxp1** [comment]
Hi, Thanks for the report. Your right, its bugged. Will be fixed in 16.0, due out just after update 14.
