### ISSUE TITLE
INARA Reports: Rejected Send: There is a newer app version required (16.0+).

### ISSUE THREAD

**Issue by fred4fish** [EDDiscovery/EDDiscovery#3346]
Seeing this while running EDDiscovery and playing Elite.  My version of EDD is 15.1.4.0

**Comment by Eahlstan** [comment]
As said in your other issue: Simply update EDDiscovery.

**Comment by fred4fish** [comment]
> Seeing this while running EDDiscovery and playing Elite. My version of EDD is 15.1.4.0



> As said in your other issue: Simply update EDDiscovery.
> 
> https://github.com/EDDiscovery/EDDiscovery/releases

Thanks.  I did not know where to find version 16.  Check for up date came up with no updates.

**Comment by fred4fish** [comment]
> > Seeing this while running EDDiscovery and playing Elite. My version of EDD is 15.1.4.0
> 
> > As said in your other issue: Simply update EDDiscovery.
> > https://github.com/EDDiscovery/EDDiscovery/releases
> 
> Thanks. I did not know where to find version 16. Check for up date came up with no updates.

OK.  I updated to version 16 and now I'm getting 'Error sending EDSM events Game/Build version too old'.

**Comment by fred4fish** [comment]
> EDSM currently only accepts events from Live (i.e. not `Legacy Horizons` / `Legacy Elite Dangerous`).

I am running Live.

**Comment by Eahlstan** [comment]
I already received another report of this. I'll investigate when that user sends me the required things tomorrow.

**Comment by poeticbulldozer** [comment]
For what it's worth, I am also unable to upload to EDDB for the same reason "Game/Build version too old" and am willing to send you any data that might assist, if you are tackling the problem tonight or tomorrow. If I can help, just say the word!

**Comment by quinnell** [comment]
Same error: Error sending EDSM events Game/Build version too old
v16. Elite Dangerous Odyssey. (live)

**Comment by klightspeed** [comment]
Is this when sending events as you play, or sending unsent events?

**Comment by poeticbulldozer** [comment]
Both. Gives the same response whether attempting to update live, or trying again once the app is closed and re-opened.

**Comment by robbyxp1** [comment]
I will investigate.

**Comment by robbyxp1** [comment]
EDSM is accepting live data. He may have enabled it since you tested this.

Expect upsets from Inara/EDSM for a few days while we sort this Star Trek universe out.

thanks for the report.
