### ISSUE TITLE
Exception on changing the column selector in Statistics panel

### ISSUE THREAD

**Issue by keritaf** [EDDiscovery/EDDiscovery#3347]
### Description

Release: 16.0

Steps to reproduce:
1. Open Statistics panel
2. Go to Travel OR Scan OR Combat tab (error happens in all of them)
3. Switch the column selector combobox from "Summary" to "Week"

### Additional Information
- Screen capture: https://www.youtube.com/watch?v=69j29sOl2ug
- Logs: [Trace_2022-11-30-15-32-29.0.log](https://github.com/EDDiscovery/EDDiscovery/files/10124194/Trace_2022-11-30-15-32-29.0.log)

### Exception Details:
>EDDiscovery v16.0.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
>   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
>   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, Int32 millisecond, DateTimeKind kind)
>   at ObjectExtensionsDates.EndOfWeek(DateTime tme) in C:\Code\Dev\EDDiscovery\BaseUtilities\BaseUtilities\Dates\DateObjectExtensions.cs:line 221
>   at EDDiscovery.UserControls.UserControlStats.SetUpDaysMonthsYear(DateTime endtimenowutc, DataGridView gridview, TimeModeType timemode, String dbname) in C:\Code\Dev\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlStatistics.cs:line 1557
>   at EDDiscovery.UserControls.UserControlStats.<StatsTravel>d__50.MoveNext() in C:\Code\Dev\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlStatistics.cs:line 713
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by Eahlstan** [comment]
Can confirm. Thanks for the report.

**Comment by robbyxp1** [comment]
Found and fixed, in 16.0.1 v.soon. thanks for this.
