### ISSUE TITLE
3d Map Crash

### ISSUE THREAD

**Issue by lkalabric** [EDDiscovery/EDDiscovery#3351]
### Exception Details:
>EDDiscovery v15.1.4.0 An unhandled fatal exception has occurred.
>```
>==== BEGIN ====
>System.AccessViolationException: Tentativa de leitura ou gravação em memória protegida. Normalmente, isso é uma indicação de que outra memória está danificada.
>   em OpenTK.Graphics.OpenGL4.GL.DrawElementsInstancedBaseVertexBaseInstance(PrimitiveType mode, Int32 count, DrawElementsType type, IntPtr indices, Int32 instancecount, Int32 basevertex, Int32 baseinstance) na C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Graphics\OpenGL4\GL4.cs:linha 17747
>   em GLOFC.GL4.GLRenderableItem.Render()
>   em GLOFC.GL4.Controls.GLControlDisplay.Render(GLRenderState currentstate, UInt64 ts)
>   em System.Action`1.Invoke(T obj)
>   em GLOFC.WinForm.GLWinFormControl.GlControl_Paint(Object sender, PaintEventArgs e)
>   em System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
>   em OpenTK.GLControl.OnPaint(PaintEventArgs e) na I:\work\github\opentk\src\OpenTK.GLControl\GLControl.cs:linha 287
>   em System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
>   em System.Windows.Forms.Control.WmPaint(Message& m)
>   em System.Windows.Forms.Control.WndProc(Message& m)
>   em System.Windows.Forms.UserControl.WndProc(Message& m)
>   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
Please refer the pinned issue #3271

> On some laptops with both APUs and GPUs, it appears to pick the APU for EDD by default.
>
> So to fix it, see https://www.howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10/ to tell windows to use the GPU for EDD.

**Comment by robbyxp1** [comment]
Closing
