### ISSUE TITLE
Game crashing when loading CMDR database

### ISSUE THREAD

**Issue by Moses8uno** [EDDiscovery/EDDiscovery#3352]
### Description
When opening the game since receiving update 16.0.2.0, while creating CMDR database, I get the below error.

### Exception Details:
>EDDiscovery v16.0.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
>no such table: Sectors
>   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at EliteDangerousCore.DB.SystemsDB.FindStar(String name, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetStars.cs:line 47
>   at EliteDangerousCore.DB.SystemCache.FindSystemInCacheDB(ISystem find, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 139
>   at SQLLiteExtensions.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 355
>===== END =====
>```

**Comment by robbyxp1** [comment]
System DB is broken
Hold down shift during launch. Use the remove the system DB option.  Restart.

**Comment by Moses8uno** [comment]
Rob,

That fixed the issue, thank you so much!

 Moses
