### ISSUE TITLE
Lost all user data, preferences and notes in updating to v16

### ISSUE THREAD

**Issue by proxneo** [EDDiscovery/EDDiscovery#3353]
Hi. First off, my complements on the program. It is great.

In my experience with software over the years, I try to defer updates if something works. I have never updated from my initial download of EDD version 12.0.2. Until I was forced to update to 16 with the recent ED update 14 to keep EDD compatible.

Unfortunately, this update has resulted in a loss of all my user data. I can customise things like they were and re-entering API's is not a problem, but losing all notes is. Searching for note-entries on specific keywords I used does not give any results, other than words in the "information" column. I kept track of all discoveries and special systems/bodies in my notes... Is there a way to still recover them?

Thank you in advance.

Kind regards

**Comment by Eahlstan** [comment]
https://forums.frontier.co.uk/threads/update-14-note-eddiscovery-exploration-tool-for-pc-and-console-users-journal-3dmap-voice.462396/post-9826861

**Comment by proxneo** [comment]
Thank you. I searched in the closed tickets, just not via Google / the forums. Sorry.
I will try those suggestions.

**Comment by proxneo** [comment]
Replaced the new sqlite and other files with the old stuff from appdata. Notes show up now. Thanks!
