### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by MutantKeyboard82** [EDDiscovery/EDDiscovery#3354]
### Description
Simply opening the software.

### Exception Details:
>EDDiscovery v16.0.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
>no such table: Sectors
>   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at EliteDangerousCore.DB.SystemsDB.GetSystemListBySqDistancesFrom(Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical, SQLiteConnectionSystem cn, Action`2 callback) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByDistance.cs:line 78
>   at EliteDangerousCore.DB.SystemsDB.GetSystemByPosition(Double x, Double y, Double z, SQLiteConnectionSystem cn, Double maxdist) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByDistance.cs:line 108
>   at EliteDangerousCore.DB.SystemCache.<>c__DisplayClass11_1.<FindNearestSystemTo>b__3(SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 350
>   at SQLLiteExtensions.SQLAdvProcessingThread`1.<>c__DisplayClass19_0.<DBRead>b__0() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 47
>   at SQLLiteExtensions.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 355
>===== END =====
>```

**Comment by Eahlstan** [comment]
See https://github.com/EDDiscovery/EDDiscovery/issues/3352 or https://github.com/EDDiscovery/EDDiscovery/issues/3277#issuecomment-1154352044
