### ISSUE TITLE
Layout of Statistics panel

### ISSUE THREAD

**Issue by Grramps** [EDDiscovery/EDDiscovery#3355]
Version 16.0.3  Open Statistics panel - set a start and to date - select the scan tab - select the Summary tab. Type and date column are displayed however the 'ALL' column has gone missing in this new version. It would be nice to have it back if possible.

Example picture shows earlier Version 15.1.4.0   
![EDD 15-1-4](https://user-images.githubusercontent.com/119940515/206183358-06d88498-fa3d-4117-9063-3d1172ca66cb.JPG)

**Comment by robbyxp1** [comment]
![image](https://user-images.githubusercontent.com/6573992/206184937-66775eca-a3d4-45d4-ba9a-96e82a32d5eb.png)

Right click on the headers (type etc) and make sure the column is not turned off

**Comment by Grramps** [comment]
Thank you for your quick help kind sir, I see it's a U.I.E. problem (User Interface Error) now solved
