### ISSUE TITLE
Manual Login Frontier CAPI

### ISSUE THREAD

**Issue by digi4care** [EDDiscovery/EDDiscovery#3356]
Hi,

I am running ED on a linux box and also your EDDiscovery app. But the Frontier Login CAPI isn't working. Most of the times it wont start the IE browser. And if you can login it does have problem with the callback. It would be awesome if we can manualy do this login part

**Comment by robbyxp1** [comment]
EDD Linux does not support Capi.  Not possible. the code is windows only. Sorry!

**Comment by robbyxp1** [comment]
And you can't do it manually, it relies on doing a callback from the browser, you have to install a handler into the OS to pick up the callback.
