### ISSUE TITLE
INARA Error Message after starting EDDiscovery

### ISSUE THREAD

**Issue by centurio** [EDDiscovery/EDDiscovery#3357]
Hi,
here is the copy of my Log. INARA seems to have a problem. Hope you can help. Appeared today in version 16.0.3.0

CAPI Installed
Notizen, Lesezeichen sowie GMP-Daten geladen.
Lese die Reisehistorie.
Scanne nach bmp Screenshots in C:\Users\Centurio\Pictures\Frontier Developments\Elite Dangerous
Webserver aktiviert
Profil Default geladen
Loaded Bindings C:\Users\Centurio\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\Custom.4.0.binds
Aktualiserung der Historie abgeschlossen.
CAPI Refresh Succeeded
CAPI User Logged in to Live using Grimsal
INARA Reports: Exception QuickJSON.JToken+JsonException: Eine Ausnahme vom Typ "QuickJSON.JToken+JsonException" wurde ausgelöst.
   bei QuickJSON.JToken.ParseError(IStringParserQuick parser, String text, ParseOptions flags, String& error)
   bei QuickJSON.JToken.Parse(String text, ParseOptions flags)
   bei QuickJSON.JObject.ParseThrowCommaEOL(String text)
   bei EliteDangerousCore.Inara.InaraClass.Send(List`1 events, List`1& datalist) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\Inara.cs:Zeile 93.

Sent NavRoute event to EDDN (Nav-Route)
In System Zunu PS-B d661 angekommen. Besuch Nr. 1
Sent FSDJump event to EDDN (Springe zu Zunu PS-B d661)
Sent Scan event to EDDN (Automatischer Scan von Zunu PS-B d661)
INARA Reports: Exception QuickJSON.JToken+JsonException: Eine Ausnahme vom Typ "QuickJSON.JToken+JsonException" wurde ausgelöst.
   bei QuickJSON.JToken.ParseError(IStringParserQuick parser, String text, ParseOptions flags, String& error)
   bei QuickJSON.JToken.Parse(String text, ParseOptions flags)
   bei QuickJSON.JObject.ParseThrowCommaEOL(String text)
   bei EliteDangerousCore.Inara.InaraClass.Send(List`1 events, List`1& datalist) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\Inara.cs:Zeile 93.

Sent FSSDiscoveryScan event to EDDN (VSS Erkundungsscan)
Sent Scan event to EDDN (Detailscan von 1)
Sent FSSAllBodiesFound event to EDDN (VSS alle Körper gefunden)
In System Zunu WZ-Z b3-81 angekommen. Besuch Nr. 1
Sent FSDJump event to EDDN (Springe zu Zunu WZ-Z b3-81)
Sent Scan event to EDDN (Automatischer Scan von A Belt Cluster 5)
INARA Reports: Exception QuickJSON.JToken+JsonException: Eine Ausnahme vom Typ "QuickJSON.JToken+JsonException" wurde ausgelöst.
   bei QuickJSON.JToken.ParseError(IStringParserQuick parser, String text, ParseOptions flags, String& error)
   bei QuickJSON.JToken.Parse(String text, ParseOptions flags)
   bei QuickJSON.JObject.ParseThrowCommaEOL(String text)
   bei EliteDangerousCore.Inara.InaraClass.Send(List`1 events, List`1& datalist) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\Inara.cs:Zeile 93.

Sent Scan event to EDDN (Automatischer Scan von A Belt Cluster 6)
Sent Scan event to EDDN (Automatischer Scan von A Belt Cluster 3)
Sent Scan event to EDDN (Automatischer Scan von Zunu WZ-Z b3-81)
Sent Scan event to EDDN (Automatischer Scan von A Belt Cluster 2)
Sent Scan event to EDDN (Automatischer Scan von A Belt Cluster 7)
Sent Scan event to EDDN (Automatischer Scan von A Belt Cluster 1)
Sent Scan event to EDDN (Automatischer Scan von A Belt Cluster 4)
Sent FSSDiscoveryScan event to EDDN (VSS Erkundungsscan)
Sent Scan event to EDDN (Detailscan von 4)
Sent Scan event to EDDN (Detailscan von 4 c)
Sent Scan event to EDDN (Detailscan von 4 d)
Sent Scan event to EDDN (Detailscan von 4 b)
Sent Scan event to EDDN (Detailscan von 4 f)
Sent Scan event to EDDN (Detailscan von 4 a)
Sent Scan event to EDDN (Detailscan von 4 e)
Sent Scan event to EDDN (Detailscan von 3)
Sent Scan event to EDDN (Detailscan von 2)
Sent Scan event to EDDN (Detailscan von 2 a)
Sent Scan event to EDDN (Detailscan von 2 b)
Sent Scan event to EDDN (Detailscan von 2 c)
INARA Reports: Exception QuickJSON.JToken+JsonException: Eine Ausnahme vom Typ "QuickJSON.JToken+JsonException" wurde ausgelöst.
   bei QuickJSON.JToken.ParseError(IStringParserQuick parser, String text, ParseOptions flags, String& error)
   bei QuickJSON.JToken.Parse(String text, ParseOptions flags)
   bei QuickJSON.JObject.ParseThrowCommaEOL(String text)
   bei EliteDangerousCore.Inara.InaraClass.Send(List`1 events, List`1& datalist) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\Inara.cs:Zeile 93.

Sent Scan event to EDDN (Detailscan von 1)
Sent FSSAllBodiesFound event to EDDN (VSS alle Körper gefunden)
In System Zunu WK-Y b4-31 angekommen. Besuch Nr. 1
Sent FSDJump event to EDDN (Springe zu Zunu WK-Y b4-31)
INARA Reports: Exception QuickJSON.JToken+JsonException: Eine Ausnahme vom Typ "QuickJSON.JToken+JsonException" wurde ausgelöst.
   bei QuickJSON.JToken.ParseError(IStringParserQuick parser, String text, ParseOptions flags, String& error)
   bei QuickJSON.JToken.Parse(String text, ParseOptions flags)
   bei QuickJSON.JObject.ParseThrowCommaEOL(String text)
   bei EliteDangerousCore.Inara.InaraClass.Send(List`1 events, List`1& datalist) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\Inara.cs:Zeile 93.

Sent Scan event to EDDN (Automatischer Scan von Zunu WK-Y b4-31)
Sent Scan event to EDDN (Automatischer Scan von A Belt Cluster 1)
Sent Scan event to EDDN (Automatischer Scan von A Belt Cluster 3)
Sent Scan event to EDDN (Automatischer Scan von A Belt Cluster 2)
Sent FSSDiscoveryScan event to EDDN (VSS Erkundungsscan)
Sent Scan event to EDDN (Detailscan von 5)
Sent Scan event to EDDN (Detailscan von 3)
Sent Scan event to EDDN (Detailscan von 1)
Sent Scan event to EDDN (Detailscan von 7)
Sent Scan event to EDDN (Detailscan von 7 a)
Sent Scan event to EDDN (Detailscan von 7 b)
Sent Scan event to EDDN (Detailscan von 6)
Sent Scan event to EDDN (Detailscan von 8)
Sent Scan event to EDDN (Detailscan von 4)
Sent Scan event to EDDN (Detailscan von 2)
Sent FSSAllBodiesFound event to EDDN (VSS alle Körper gefunden)
In System Zunu WV-W b5-80 angekommen. Besuch Nr. 1
Sent FSDJump event to EDDN (Springe zu Zunu WV-W b5-80)
Sent Scan event to EDDN (Automatischer Scan von A)
INARA Reports: Exception QuickJSON.JToken+JsonException: Eine Ausnahme vom Typ "QuickJSON.JToken+JsonException" wurde ausgelöst.
   bei QuickJSON.JToken.ParseError(IStringParserQuick parser, String text, ParseOptions flags, String& error)
   bei QuickJSON.JToken.Parse(String text, ParseOptions flags)
   bei QuickJSON.JObject.ParseThrowCommaEOL(String text)
   bei EliteDangerousCore.Inara.InaraClass.Send(List`1 events, List`1& datalist) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\Inara.cs:Zeile 93.

Sent FSSDiscoveryScan event to EDDN (VSS Erkundungsscan)
Sent Scan event to EDDN (Automatischer Scan von C)
Sent Scan event to EDDN (Automatischer Scan von D)
Sent Scan event to EDDN (Automatischer Scan von B)
Sent Scan event to EDDN (Detailscan von ABC 3)
Sent Scan event to EDDN (Detailscan von ABC 2)
Sent Scan event to EDDN (Detailscan von D 5)
Sent Scan event to EDDN (Detailscan von D 2)
Sent Scan event to EDDN (Detailscan von D 3)
Sent Scan event to EDDN (Detailscan von D 4)
Sent Scan event to EDDN (Detailscan von D 1)
Sent Scan event to EDDN (Detailscan von D 6)
Sent Scan event to EDDN (Detailscan von ABC 5)
Sent Scan event to EDDN (Detailscan von ABC 5 a)
Sent Scan event to EDDN (Detailscan von ABC 5 b)
Sent Scan event to EDDN (Detailscan von ABC 5 c)
INARA Reports: Exception QuickJSON.JToken+JsonException: Eine Ausnahme vom Typ "QuickJSON.JToken+JsonException" wurde ausgelöst.
   bei QuickJSON.JToken.ParseError(IStringParserQuick parser, String text, ParseOptions flags, String& error)
   bei QuickJSON.JToken.Parse(String text, ParseOptions flags)
   bei QuickJSON.JObject.ParseThrowCommaEOL(String text)
   bei EliteDangerousCore.Inara.InaraClass.Send(List`1 events, List`1& datalist) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\Inara.cs:Zeile 93.

Sent Scan event to EDDN (Detailscan von ABC 5 d)
Sent Scan event to EDDN (Detailscan von ABC 5 e)
Sent Scan event to EDDN (Detailscan von ABC 1)
Sent Scan event to EDDN (Detailscan von ABC 4)
Sent Scan event to EDDN (Detailscan von ABC 4 b)
Sent Scan event to EDDN (Detailscan von ABC 4 c)
Sent Scan event to EDDN (Detailscan von ABC 4 e)
Sent Scan event to EDDN (Detailscan von ABC 4 a)
Sent Scan event to EDDN (Detailscan von ABC 4 d)
Sent Scan event to EDDN (Detailscan von ABC 4 f)
Sent Scan event to EDDN (Detailscan von ABC 4 g)
INARA Reports: Exception QuickJSON.JToken+JsonException: Eine Ausnahme vom Typ "QuickJSON.JToken+JsonException" wurde ausgelöst.
   bei QuickJSON.JToken.ParseError(IStringParserQuick parser, String text, ParseOptions flags, String& error)
   bei QuickJSON.JToken.Parse(String text, ParseOptions flags)
   bei QuickJSON.JObject.ParseThrowCommaEOL(String text)
   bei EliteDangerousCore.Inara.InaraClass.Send(List`1 events, List`1& datalist) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\Inara.cs:Zeile 93.

Sent Scan event to EDDN (Detailscan von ABC 7)
Sent Scan event to EDDN (Detailscan von ABC 7 b)
Sent Scan event to EDDN (Detailscan von ABC 7 a)
Sent Scan event to EDDN (Detailscan von ABC 7 d)
Sent Scan event to EDDN (Detailscan von ABC 7 c)
Sent Scan event to EDDN (Detailscan von ABC 7 e)
Sent Scan event to EDDN (Detailscan von ABC 7 f)
Sent Scan event to EDDN (Detailscan von ABC 7 g)
Sent Scan event to EDDN (Detailscan von ABC 6 f)
Sent Scan event to EDDN (Detailscan von ABC 6 e)
Sent Scan event to EDDN (Detailscan von ABC 6 b)
Sent Scan event to EDDN (Detailscan von ABC 6 c)
Sent Scan event to EDDN (Detailscan von ABC 6 a)
Sent Scan event to EDDN (Detailscan von ABC 6 d)
Sent Scan event to EDDN (Detailscan von ABC 6)
Sent FSSAllBodiesFound event to EDDN (VSS alle Körper gefunden)
In System Zunu RY-Z d2078 angekommen. Besuch Nr. 1
Sent FSDJump event to EDDN (Springe zu Zunu RY-Z d2078)
INARA Reports: Exception QuickJSON.JToken+JsonException: Eine Ausnahme vom Typ "QuickJSON.JToken+JsonException" wurde ausgelöst.
   bei QuickJSON.JToken.ParseError(IStringParserQuick parser, String text, ParseOptions flags, String& error)
   bei QuickJSON.JToken.Parse(String text, ParseOptions flags)
   bei QuickJSON.JObject.ParseThrowCommaEOL(String text)
   bei EliteDangerousCore.Inara.InaraClass.Send(List`1 events, List`1& datalist) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\Inara.cs:Zeile 93.

Sent Scan event to EDDN (Automatischer Scan von A)
Sent FSSDiscoveryScan event to EDDN (VSS Erkundungsscan)
Sent Scan event to EDDN (Automatischer Scan von B)
Sent Scan event to EDDN (Automatischer Scan von C)
Sent Scan event to EDDN (Detailscan von A 1)
Sent Scan event to EDDN (Detailscan von A 5)
Sent Scan event to EDDN (Detailscan von A 7)
Sent Scan event to EDDN (Detailscan von A 2 a)
Sent Scan event to EDDN (Detailscan von A 2)
Sent Scan event to EDDN (Detailscan von A 3)
Sent Scan event to EDDN (Detailscan von A 6)
Sent Scan event to EDDN (Detailscan von A 4)
Sent FSSAllBodiesFound event to EDDN (VSS alle Körper gefunden)
Sent Scan event to EDDN (Detailscan von A 5)
In System Zunu MT-W c3-94 angekommen. Besuch Nr. 1
Sent FSDJump event to EDDN (Springe zu Zunu MT-W c3-94)
Sent Scan event to EDDN (Automatischer Scan von Zunu MT-W c3-94)
INARA Reports: Exception QuickJSON.JToken+JsonException: Eine Ausnahme vom Typ "QuickJSON.JToken+JsonException" wurde ausgelöst.
   bei QuickJSON.JToken.ParseError(IStringParserQuick parser, String text, ParseOptions flags, String& error)
   bei QuickJSON.JToken.Parse(String text, ParseOptions flags)
   bei QuickJSON.JObject.ParseThrowCommaEOL(String text)
   bei EliteDangerousCore.Inara.InaraClass.Send(List`1 events, List`1& datalist) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\Inara.cs:Zeile 93.

Sent FSSDiscoveryScan event to EDDN (VSS Erkundungsscan)
Sent Scan event to EDDN (Detailscan von 1)
Sent Scan event to EDDN (Detailscan von 7)
Sent Scan event to EDDN (Detailscan von 8)
Sent Scan event to EDDN (Detailscan von 6)
Sent Scan event to EDDN (Detailscan von 6 a)
Sent Scan event to EDDN (Detailscan von 3)
Sent Scan event to EDDN (Detailscan von 2)
Sent Scan event to EDDN (Detailscan von 5)
Sent Scan event to EDDN (Detailscan von 4)
Sent Scan event to EDDN (Detailscan von 4 a)
Sent FSSAllBodiesFound event to EDDN (VSS alle Körper gefunden)
In System Zunu TJ-Y d1-2319 angekommen. Besuch Nr. 1
Sent FSDJump event to EDDN (Springe zu Zunu TJ-Y d1-2319)
Sent Scan event to EDDN (Automatischer Scan von A)
INARA Reports: Exception QuickJSON.JToken+JsonException: Eine Ausnahme vom Typ "QuickJSON.JToken+JsonException" wurde ausgelöst.
   bei QuickJSON.JToken.ParseError(IStringParserQuick parser, String text, ParseOptions flags, String& error)
   bei QuickJSON.JToken.Parse(String text, ParseOptions flags)
   bei QuickJSON.JObject.ParseThrowCommaEOL(String text)
   bei EliteDangerousCore.Inara.InaraClass.Send(List`1 events, List`1& datalist) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\Inara.cs:Zeile 93.

**Comment by Eahlstan** [comment]
Bitte öffne `shell:SavedGames\Frontier Developments\Elite Dangerous` und lade die .log-Datei von der Spielesession in der dieser Fehler ausgelöst wurde hoch.

**Comment by centurio** [comment]
Log File Uploaded

[Journal.2022-12-07T181432.01.log](https://github.com/EDDiscovery/EDDiscovery/files/10178887/Journal.2022-12-07T181432.01.log)

**Comment by Eahlstan** [comment]
Kannst du mir bitte noch ein Journal von vor etwa einer Woche geben? Im heutigen ist etwas seltsam und ich will sehen ob das schon länger so ist, oder ob es erst heute aufgetaucht ist.

**Comment by Eahlstan** [comment]
Fixed by Artie, he sent broken responses.
