### ISSUE TITLE
There was an unhandled UI exception

### ISSUE THREAD

**Issue by jammedjackal** [EDDiscovery/EDDiscovery#3359]
### Exception Details:
>EDDiscovery v16.0.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: Current cell cannot be set to an invisible cell.
>   at System.Windows.Forms.DataGridView.set_CurrentCell(DataGridViewCell value)
>   at EDDiscovery.UserControls.UserControlOrganics.DrawGrid() in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlOrganics.cs:line 256
>   at EDDiscovery.UserControls.UserControlOrganics.Discoveryform_OnHistoryChange(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlOrganics.cs:line 135
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshCompleteonUI(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 291
>===== END =====
>```

**Comment by Eahlstan** [comment]
Strange.
Does this happen every time you open the organics panel (or in case you use the overlay if approaching a body)?
Please upload your journal file from that session ( shell:SavedGames\Frontier Developments\Elite Dangerous ).

**Comment by jammedjackal** [comment]
This is actually not related to running Elite. I have organics panel embedded in tab based on splitter (top right). This happen immediately after I start EDDiscovery even without running Elite.

**Comment by Eahlstan** [comment]
If you hold shift while starting EDD a [safe mode](https://github.com/EDDiscovery/EDDiscovery/wiki/Safe-Mode) menu comes up that has an option to reset your tabs.
The error itself is pretty self explanatory (although we were never able to trigger it), so we will be able to fix it without knowing what exactly causes it - so this tab resetting is only for you to be able to use EDD until a fix is deployed.

**Comment by robbyxp1** [comment]
Found and fixed, thanks for the report!
