### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by dylan-k** [EDDiscovery/EDDiscovery#3360]
### Description
Left the app running a while to download data, came back to this error: Unhandled UI Exception

### Exception Details:
>EDDiscovery v16.0.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.Collections.ArrayList.get_Item(Int32 index)
>   at System.Windows.Forms.DataGridViewColumnCollection.get_Item(Int32 index)
>   at DataGridViewControlHelpersStaticFunc.SaveColumnSettings(DataGridView dgv, String root, Action`2 saveint, Action`2 savedouble) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\WinForms\DataGridViewHelpers.cs:line 597
>   at EDDiscovery.UserControls.UserControlEstimatedValues.Closing() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlEstimatedValues.cs:line 92
>   at EDDiscovery.UserControls.UserControlForm.OnFormClosing(FormClosingEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Form\UserControlForm.cs:line 314
>   at System.Windows.Forms.Form.WmClose(Message& m)
>   at ExtendedControls.SmartSysMenuForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\SmartSysMenuForm.cs:line 219
>   at ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\DraggableForm.cs:line 169
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
The stack trace suggests that the popout window was being closed.

Where the error in SaveColumnSettings occurred should be impossible, and seems to suggest a bit flip.

**Comment by robbyxp1** [comment]
This sounds like a random thing, we will keep it monitored. thanks for the report.
