### ISSUE TITLE
EDSM data is crashing EDD Scan panel in 16.0.3 and below update to 16.0.4 or turn off EDSM lookup in scan panel and other places - Unhandled UI execption

### ISSUE THREAD

**Issue by richardbuckle** [EDDiscovery/EDDiscovery#3362]
There was an unhandled UI exception.
```
==== BEGIN ====
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at EliteDangerousCore.JournalEvents.JournalScan.DisplayString(Int32 indent, List`1 historicmatlist, List`1 currentmatlist, Boolean includefront) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalScan_Display.cs:line 32
   at EliteDangerousCore.SystemDisplay.DrawNode(List`1 pc, ScanNode sn, List`1 historicmats, List`1 curmats, Image notscanned, Point position, Boolean xiscentre, Rectangle& imagepos, Size size, DrawLevel drawtype, Nullable`1 backwash, String appendlabeltext) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplayNodes.cs:line 60
   at EliteDangerousCore.SystemDisplay.DrawSystem(ExtPictureBox imagebox, Int32 widthavailable, SystemNode systemnode, List`1 historicmats, List`1 curmats, String opttext, String[] filter) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplay.cs:line 120
   at EDDiscovery.UserControls.ScanDisplayUserControl.DrawSystem(SystemNode systemnode, List`1 historicmats, List`1 curmats, String opttext, String[] filter) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplayUserControl.cs:line 59
   at EDDiscovery.UserControls.UserControlScan.<DrawSystem>d__20.MoveNext() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:line 231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
===== END =====
```

Let me know if you need more context or journals.

**Comment by louisrousseau** [comment]
### Description
Looks like the same stack trace.

### Additional Information
Got a new data material following a Thargoid interdiction which judging by the stack trace might be of interest, unsure if the crash happened at that exact moment or not.

### Exception Details:
>EDDiscovery v16.0.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: L'index était hors limites. Il ne doit pas être négatif et doit être inférieur à la taille de la collection.
>Nom du paramètre : index
>   à System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   à EliteDangerousCore.JournalEvents.JournalScan.DisplayString(Int32 indent, List`1 historicmatlist, List`1 currentmatlist, Boolean includefront) dans C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalScan_Display.cs:ligne 32
>   à EliteDangerousCore.SystemDisplay.DrawNode(List`1 pc, ScanNode sn, List`1 historicmats, List`1 curmats, Image notscanned, Point position, Boolean xiscentre, Rectangle& imagepos, Size size, DrawLevel drawtype, Nullable`1 backwash, String appendlabeltext) dans C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplayNodes.cs:ligne 60
>   à EliteDangerousCore.SystemDisplay.DrawSystem(ExtPictureBox imagebox, Int32 widthavailable, SystemNode systemnode, List`1 historicmats, List`1 curmats, String opttext, String[] filter) dans C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplay.cs:ligne 120
>   à EDDiscovery.UserControls.ScanDisplayUserControl.DrawSystem(SystemNode systemnode, List`1 historicmats, List`1 curmats, String opttext, String[] filter) dans C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplayUserControl.cs:ligne 59
>   à EDDiscovery.UserControls.UserControlScan.<DrawSystem>d__20.MoveNext() dans C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:ligne 231
>--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by robbyxp1** [comment]
Its not obvious - there is no obv indexer around line 32 of the DisplayString causing it.

**Comment by AndrewGaspurr** [comment]
Get this every time I enter a star system:

### Description


### Additional Information


### Exception Details:
>EDDiscovery v16.0.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.
>Parametername: index
>   bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   bei EliteDangerousCore.JournalEvents.JournalScan.DisplayString(Int32 indent, List`1 historicmatlist, List`1 currentmatlist, Boolean includefront) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalScan_Display.cs:Zeile 32.
>   bei EliteDangerousCore.SystemDisplay.DrawNode(List`1 pc, ScanNode sn, List`1 historicmats, List`1 curmats, Image notscanned, Point position, Boolean xiscentre, Rectangle& imagepos, Size size, DrawLevel drawtype, Nullable`1 backwash, String appendlabeltext) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplayNodes.cs:Zeile 60.
>   bei EliteDangerousCore.SystemDisplay.DrawSystem(ExtPictureBox imagebox, Int32 widthavailable, SystemNode systemnode, List`1 historicmats, List`1 curmats, String opttext, String[] filter) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplay.cs:Zeile 120.
>   bei EDDiscovery.UserControls.ScanDisplayUserControl.DrawSystem(SystemNode systemnode, List`1 historicmats, List`1 curmats, String opttext, String[] filter) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplayUserControl.cs:Zeile 59.
>   bei EDDiscovery.UserControls.UserControlScan.<DrawSystem>d__20.MoveNext() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:Zeile 231.
>--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
>   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by robbyxp1** [comment]
I think we need the last few journal files of things causing this issue. If you can just post the last few in here (you can just drop them into the comment box) that would be invaluable.

**Comment by robbyxp1** [comment]
Yep, so its not going wrong, but that might be because you don't have the journal scan entries in those three logs for the systems your in - and it looks like the scan display was the thing that was going wrong.

It needs more journals to find it.  If your on discord, we could exchange the whole set privately. ;-)

**Comment by robbyxp1** [comment]
I think its caused by EDSM data - creating an empty parent array - but not null, and excepting on

JournalScanBaryCentre barycentrejs = Parents?[0].Barycentre;

Parents.Count = 0 will crash it!

I'll do a new EDD today to round up some issues we have seen

thanks

**Comment by richardbuckle** [comment]
Log attached 
[Journal.2022-12-11T230223.01.log](https://github.com/EDDiscovery/EDDiscovery/files/10207345/Journal.2022-12-11T230223.01.log)

**Comment by KitsuneNoBaka** [comment]
Have the same

`### Description


### Additional Information


### Exception Details:
>EDDiscovery v16.0.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Indeks był spoza zakresu. Musi mieć wartość nieujemną i mniejszą niż rozmiar kolekcji.
>Nazwa parametru: index
>   w System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   w EliteDangerousCore.JournalEvents.JournalScan.DisplayString(Int32 indent, List`1 historicmatlist, List`1 currentmatlist, Boolean includefront) w C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalScan_Display.cs:wiersz 32
>   w EliteDangerousCore.SystemDisplay.DrawNode(List`1 pc, ScanNode sn, List`1 historicmats, List`1 curmats, Image notscanned, Point position, Boolean xiscentre, Rectangle& imagepos, Size size, DrawLevel drawtype, Nullable`1 backwash, String appendlabeltext) w C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplayNodes.cs:wiersz 60
>   w EliteDangerousCore.SystemDisplay.DrawSystem(ExtPictureBox imagebox, Int32 widthavailable, SystemNode systemnode, List`1 historicmats, List`1 curmats, String opttext, String[] filter) w C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplay.cs:wiersz 120
>   w EDDiscovery.UserControls.ScanDisplayUserControl.DrawSystem(SystemNode systemnode, List`1 historicmats, List`1 curmats, String opttext, String[] filter) w C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplayUserControl.cs:wiersz 59
>   w EDDiscovery.UserControls.UserControlScan.<DrawSystem>d__20.MoveNext() w C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:wiersz 231
>--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
>   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>`

**Comment by schmstqa** [comment]
Same here when starting the application:

### Description


### Additional Information


### Exception Details:
>EDDiscovery v16.0.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   at EliteDangerousCore.JournalEvents.JournalScan.DisplayString(Int32 indent, List`1 historicmatlist, List`1 currentmatlist, Boolean includefront) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalScan_Display.cs:line 32
>   at EliteDangerousCore.SystemDisplay.DrawNode(List`1 pc, ScanNode sn, List`1 historicmats, List`1 curmats, Image notscanned, Point position, Boolean xiscentre, Rectangle& imagepos, Size size, DrawLevel drawtype, Nullable`1 backwash, String appendlabeltext) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplayNodes.cs:line 60
>   at EliteDangerousCore.SystemDisplay.DrawSystem(ExtPictureBox imagebox, Int32 widthavailable, SystemNode systemnode, List`1 historicmats, List`1 curmats, String opttext, String[] filter) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplay.cs:line 120
>   at EDDiscovery.UserControls.ScanDisplayUserControl.DrawSystem(SystemNode systemnode, List`1 historicmats, List`1 curmats, String opttext, String[] filter) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplayUserControl.cs:line 59
>   at EDDiscovery.UserControls.UserControlScan.<DrawSystem>d__20.MoveNext() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:line 231
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by robbyxp1** [comment]
Turn off EDSM lookup

Anthor has changed something..

**Comment by robbyxp1** [comment]
16.0.4. should solve this
