### ISSUE TITLE
"There was an unhandled UI exception." 

### ISSUE THREAD

**Issue by bobbyroberts99** [EDDiscovery/EDDiscovery#3363]
Running 16.0.2.0

"There was an unhandled UI exception." 
### Description

Not sure. Flying or in station. Sorry.
### Exception Details:
>EDDiscovery v16.0.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   at EliteDangerousCore.JournalEvents.JournalScan.DisplayString(Int32 indent, List`1 historicmatlist, List`1 currentmatlist, Boolean includefront) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalScan_Display.cs:line 32
>   at EliteDangerousCore.SystemDisplay.DrawNode(List`1 pc, ScanNode sn, List`1 historicmats, List`1 curmats, Image notscanned, Point position, Boolean xiscentre, Rectangle& imagepos, Size size, DrawLevel drawtype, Nullable`1 backwash, String appendlabeltext) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplayNodes.cs:line 60
>   at EliteDangerousCore.SystemDisplay.DrawSystem(ExtPictureBox imagebox, Int32 widthavailable, SystemNode systemnode, List`1 historicmats, List`1 curmats, String opttext, String[] filter) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplay.cs:line 120
>   at EDDiscovery.UserControls.ScanDisplayUserControl.DrawSystem(SystemNode systemnode, List`1 historicmats, List`1 curmats, String opttext, String[] filter) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplayUserControl.cs:line 59
>   at EDDiscovery.UserControls.UserControlScan.<DrawSystem>d__20.MoveNext() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:line 231
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by Eahlstan** [comment]
Update to 16.0.4
