### ISSUE TITLE
[Request] Event filter for combat tab. 

### ISSUE THREAD

**Issue by Jugom** [EDDiscovery/EDDiscovery#3365]
To have the option to filter what events are shown in the combat tab. 
Mostly because all the hull damage events one after another kinda clutter the whole thing and it gets a bit annoying to read.
I know, I know. you are busy with other things, just an idea. 😄 
Cheers.

**Comment by robbyxp1** [comment]
Will look into it

**Comment by robbyxp1** [comment]
Added to worklist
