### ISSUE TITLE
EDDiscovery gives fatal error when starting on Linux

### ISSUE THREAD

**Issue by Ovi05** [EDDiscovery/EDDiscovery#3366]
Here's what it says: 

A fatal exception was encountered while initializing EDDiscovery.

```
==== BEGIN ====
System.NullReferenceException: Object reference not set to an instance of an object
  at EDDiscovery.EDDiscoveryForm.ApplyTheme (System.Boolean panelrefreshaswell) [0x0000c] in <164147078cf048a3ac061ee692a52c7b>:0 
  at EDDiscovery.EDDiscoveryForm.Init (System.Action`1[T] msg) [0x005bb] in <164147078cf048a3ac061ee692a52c7b>:0 
  at (wrapper remoting-invoke-with-check) EDDiscovery.EDDiscoveryForm.Init(System.Action`1<string>)
  at EDDiscovery.EDDApplicationContext.InitialiseEDD (System.Object sender, System.EventArgs e) [0x00274] in <164147078cf048a3ac061ee692a52c7b>:0 
===== END =====
```

**Comment by klightspeed** [comment]
This suggests that `ExtendedControls.Theme.Current` is `null`.

045f12eb changed the default theme to `Elite Verdana Small`, which is not available if the `Verdana` font is not available.

The fallback default of the "Windows Default" theme should really be put back above the `if (!EDDOptions.Instance.NoTheme)` line so that a theme is always set.

As a workaround until this is fixed, please try adding the `-notheme` option to the EDDiscovery command line.

**Comment by Ovi05** [comment]
Thanks! It worked!

**Comment by robbyxp1** [comment]
Yep, needs an if probably on the OS version..

**Comment by robbyxp1** [comment]
if (!EDDOptions.Instance.NoTheme)
            {
                string deftheme = Environment.OSVersion.Platform == PlatformID.Win32NT ? "Elite Verdana Small" : "Windows Default";
                ThemeList.SetThemeByName(deftheme);                // this is the default theme we use normally
                var theme = GetThemeFromDB();
                if (theme != null)
                    ExtendedControls.Theme.Current = theme;
            }
            else
                ThemeList.SetThemeByName("Windows Default");                    // this is the default theme we use for notheme

**Comment by robbyxp1** [comment]
This is on the tip master code.

**Comment by klightspeed** [comment]
Why not `ThemeList.IsFontAvailable("Verdana") ? "Elite Verdana Small" : "Windows Default";`

**Comment by robbyxp1** [comment]
True, but as you said, its probably the best just to force windows default, and then let them take their own risk.

**Comment by robbyxp1** [comment]
Closing, next version will have this in it.
