### ISSUE TITLE
[16.0.4.0] History Panel: Filter entries based on Event Type button no longer works

### ISSUE THREAD

**Issue by ZenonSeth** [EDDiscovery/EDDiscovery#3368]
As title says, I'm running version 16.0.4.0.

Either from within the default History tab or trying to add a new History panel, pressing the "Filter entries based on event type" button does not show anything. I believe it previously showed a dropdown list of event types.

**Comment by Eahlstan** [comment]
We recently had a guy on our Discord that had the same problem. A complete system restart fixed it, die you already restart Windows? (No matter the answer please restart Windows before answering.)

**Comment by ZenonSeth** [comment]
Thanks for the quick reply - I restarted and the filters now appear. That's a weird issue, hopefully it remains "fixed" on my computer now.

**Comment by Eahlstan** [comment]
The other guy never mentioned it again, we guess that something was hanging in Windows.
