### ISSUE TITLE
EDDiscovery crashing on launch, after C drive ran out of space

### ISSUE THREAD

**Issue by VIgilanteofLight** [EDDiscovery/EDDiscovery#3369]
EDDiscovery crashes on launch with the following error. Happened exactly when my C drive ran out of space. I cleared some space on the drive and the error still happens. Happening after reinstallation leading me to believe there is a file somewhere from my game files or logs that is causing the crash.
![EDDiscovery Error Messages](https://user-images.githubusercontent.com/121089248/208620521-e1ff4514-b916-4ac0-ab78-a9ab9da69c72.png)

**Comment by Eahlstan** [comment]
See https://github.com/EDDiscovery/EDDiscovery/issues/3352 or https://github.com/EDDiscovery/EDDiscovery/issues/3277#issuecomment-1154352044

**Comment by VIgilanteofLight** [comment]
much appreciated :)
