### ISSUE TITLE
Some on-foot buy/sell events not showing in the Ledger view

### ISSUE THREAD

**Issue by svensven** [EDDiscovery/EDDiscovery#3372]
"[Buy Suit](https://github.com/EDDiscovery/EliteDangerousCore/blob/master/EliteDangerous/JournalEvents/JournalSuits.cs#L23)", "[Sell Suit](https://github.com/EDDiscovery/EliteDangerousCore/blob/master/EliteDangerous/JournalEvents/JournalSuits.cs#L62)", "[Buy Weapon](https://github.com/EDDiscovery/EliteDangerousCore/blob/master/EliteDangerous/JournalEvents/JournalWeapons.cs#L23)" and presumably "[Sell Weapon](https://github.com/EDDiscovery/EliteDangerousCore/blob/master/EliteDangerous/JournalEvents/JournalWeapons.cs#L64)" events don't show up yet.

Buying consumables does show up, as micro-resources.

**Comment by Eahlstan** [comment]
Thanks for the report, I added them so they should be on the ledger in the next version.

https://github.com/EDDiscovery/EliteDangerousCore/pull/114

**Comment by robbyxp1** [comment]
Fixed on tip, thanks for the report.
