### ISSUE TITLE
Unhandled UI exception while doing nothing (viewing the "Hidden Log")

### ISSUE THREAD

**Issue by GlowyHedgehog** [EDDiscovery/EDDiscovery#3373]
### Description
Had created a couple of console commander accounts, linked to EDSM and the Frontier API, and afaik they had completed the update from Frontier. The EDSM database had been downloaded and was in the middle of being processed. Looked at the "Hidden Log" to see what it was, then was doing nothing when the exception box appeared. However, it's possible that the touchpad on the laptop was brushed, causing something to be activated (it can be very sensitive), but no idea what.

### Additional Information
Can be contacted for additional info via Discord, user GlowyHedgehog.

### Exception Details:
>EDDiscovery v16.0.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlSysInfo.<Display>d__54.MoveNext() in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSysInfo.cs:line 612
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by klightspeed** [comment]
In <https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/UserControls/Overlays/UserControlSysInfo.cs#L614>, there is a potential race, where `GetLast` returned something before the async `FindSystemAsync` call, then returned nothing (or an entry with no system) after the `FindSystemAsync` call.

**Comment by robbyxp1** [comment]
Yes, if the commander was changed during the async computation, it could end up with getlast being null.
I'll put defense in.

                        if (sys != null && sys.HasCoordinate && DiscoveryForm.History.GetLast != null)       // check we have data - defense against #3373

thanks for the report
