### ISSUE TITLE
Unhandled UI exception on Journal grid

### ISSUE THREAD

**Issue by svensven** [EDDiscovery/EDDiscovery#3376]
### Description
Right-clicked on the top left header cell.
Can reproduce on other grids that have header row and column - route finder, expedition

### Additional Information
![image](https://user-images.githubusercontent.com/5736616/213343622-6737e16a-0218-4b8f-bbed-0c7da4d388bf.png)

### Exception Details:
>EDDiscovery v16.0.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.Collections.ArrayList.get_Item(Int32 index)
>   at System.Windows.Forms.DataGridViewColumnCollection.get_Item(Int32 index)
>   at BaseUtils.DataGridViewColumnControl.ColumnContextMenu_Opening(Object sender, CancelEventArgs e) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\WinForms\DataGridViewColumnControl.cs:line 90
>   at System.Windows.Forms.ToolStripDropDown.OnOpening(CancelEventArgs e)
>   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
>   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
>   at System.Windows.Forms.ContextMenuStrip.ShowInternal(Control source, Point location, Boolean isKeyboardActivated)
>   at System.Windows.Forms.DataGridView.WmContextMenu(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Thanks - seen will be patched in 16.1

**Comment by robbyxp1** [comment]
Fixed on tip, thanks
