### ISSUE TITLE
When EDDiscovery is launched, this message appears. -- FleetCarrier

### ISSUE THREAD

**Issue by MichaelLuebke** [EDDiscovery/EDDiscovery#3377]
### Exception Details:
>EDDiscovery v16.0.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at CAPI.FleetCarrier.MergeCargo(List`1 list) in C:\Code\EDDiscovery\CAPI\CAPI\Fleetcarrier.cs:line 268
>   at EDDiscovery.UserControls.UserControlCarrier.DisplayCAPI(FleetCarrier fc) in C:\Code\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlCarrier.cs:line 941
>   at EDDiscovery.UserControls.UserControlCarrier.ClearDisplayFontJournalCAPI() in C:\Code\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlCarrier.cs:line 317
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshCompleteonUI(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 291
>===== END =====
>```

**Comment by robbyxp1** [comment]
Avoid selecting the capi tabs in Carrier panel for now.

If you can't get it to run, then run safemode (hold down shift and double click the EDD icon) then reset the Tabs, Remove PopOuts to reset the UI.

Will investigate. Thanks for the report.

**Comment by robbyxp1** [comment]
I've found the problem, will be fixed in 16.1 at least
