### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by Batosei** [EDDiscovery/EDDiscovery#3378]
### Exception Details:
>EDDiscovery v16.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
>no such table: Sectors
>   bei System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   bei System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   bei System.Data.SQLite.SQLiteDataReader.NextResult()
>   bei System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   bei System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   bei EliteDangerousCore.DB.SystemsDB.FindStar(String name, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetStars.cs:Zeile 47.
>   bei EliteDangerousCore.DB.SystemCache.FindSystemInCacheDB(ISystem find, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:Zeile 139.
>   bei SQLLiteExtensions.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:Zeile 355.
>===== END =====
>```

**Comment by Batosei** [comment]
It worked Yesterday 22.01.23 without any problem, today after reboot it wont work.

**Comment by Eahlstan** [comment]
See https://github.com/EDDiscovery/EDDiscovery/issues/3352 or https://github.com/EDDiscovery/EDDiscovery/issues/3277#issuecomment-1154352044

**Comment by Batosei** [comment]
#3352  worked! Thanks!
