### ISSUE TITLE
Feature Request: Auto-Copy Next In Route Expeditions Tab

### ISSUE THREAD

**Issue by emarcelcom** [EDDiscovery/EDDiscovery#3380]
Add Auto-Copy Next In Route to the clipboard - Expeditions Tab.

It would be great if the next system from the route would be copied automatically to the clipboard after the jump to the system. 
Example route: HIP 1933 > Lao Zi > AONII > CHUNZA > 

After jumping from HIP 1933 to Lao Zi the AONII has been copied to a clipboard automatically, and so on ....

**Comment by Eahlstan** [comment]
Open a Surveyor and let it load your expedition/route. Set the route settings to "auto copy waypoint".
