### ISSUE TITLE
No Updates from CAPI since 2023-01-24 (Console Commander)

### ISSUE THREAD

**Issue by GTRasH** [EDDiscovery/EDDiscovery#3381]
I am using a Console commander, but i cant get any updates to my history since 2023-01-24.
Last Update i got was 2023-01-24 11:30am (Local time Germany)
Message in the Log is always the same:
[2023-01-28T11:07:54.365Z] Journal Check day 2023-01-24 @ 2023-01-28T11:07:54.365Z
[2023-01-28T11:07:54.609Z]   No response to 2023-01-24 (ServiceUnavailable) will try again

i haven't been able to find any information on a possible problem with the api in the frontier forums.

I can reproduce this on multiple Systems. Just adding the commander. i do not have another commander to check whether it is a problem with this specific commander or because of it being a console commander.

Sample Trace i got:
[Trace_2023-01-28-12-04-45.0.log](https://github.com/EDDiscovery/EDDiscovery/files/10527075/Trace_2023-01-28-12-04-45.0.log)

**Comment by robbyxp1** [comment]
Frontier CAPI problem or internet problem - its saying ServiceUnavailable..  I Presume the log window is saying 'CAPI Logged in'

**Comment by GTRasH** [comment]
Yes it does say that I successfully logged in. Tried multiple machines in multiple networks. No luck so far. So I would assume that the internet is fine.

**Comment by Eahlstan** [comment]
"multiple machines in multiple networks"

Multiple installations or the same folders copied from machine A to machine B?

**Comment by GTRasH** [comment]
Multiple real installations on different machines. No copies.

**Comment by Eahlstan** [comment]
What happens if you try to open https://legacy-companion.orerve.net/journal

**Comment by GTRasH** [comment]
401 Unauthorized.
<img width="671" alt="lc" src="https://user-images.githubusercontent.com/1790630/215289529-a06171f4-9fca-4290-83a8-b0bd43d95225.png">

**Comment by Eahlstan** [comment]
Any chance you got a fleet carrier?

**Comment by GTRasH** [comment]
No, still 4 billion short on this

**Comment by Eahlstan** [comment]
I built a [CAPIdemo](https://github.com/EDDiscovery/CAPI). You can download it from my [GDrive](https://drive.google.com/file/d/13S4fru9aBrdVsVgikMXbyjWgXLaRqIVd/view?usp=sharing).
Please extract it to c:\code run it, check the "legacy" option in the top left, click "login one", log in, then click "Journal" and report what it says.

**Comment by GTRasH** [comment]
Tried different dates i definitely played:

C:\code\CAPIDemo\CAPIDemo.exe
DDE Server setup
-------------------------
Login One: Legacy https://legacy-companion.orerve.net/
URL Callback eddiscovery://auth/?code=bccc3e43-759f-4d72-8441-5841f4e705da&state=u2iViTzBQyI
------------------------- JOURNAL
Journal Response ServiceUnavailable
------------------------- /JOURNAL
------------------------- JOURNAL
Journal Response ServiceUnavailable
------------------------- /JOURNAL

**Comment by GTRasH** [comment]
i think i have found the reason: I've loggid in with my frontier account like always, which gave me no response in the journal. i tried using my xbox account instead and it works. i guess somehow my link got lost. i think we can close this issue

**Comment by Eahlstan** [comment]
Great to hear.
