### ISSUE TITLE
3D map causes EDDiscovery to lock up

### ISSUE THREAD

**Issue by DriftPunch** [EDDiscovery/EDDiscovery#3385]
Latest version of EDD.  Issue started a month or so ago.  When opening the 3D map, the panel opens but the display remains blank.  The program appears "busy" and cannot be used.  It has to be killed via taskman or via Windows' "App is not responding" window -> Close the program.

Attempted reinstallation, and followed the instructions on the previous issue to set the graphics performance for the program in Windows.

**Comment by Eahlstan** [comment]
Upload a trace.......log file from a time when that happened found in the Logs folder of EDDiscovery ( %localappdata%\EDDiscovery on default).
Any chances you're using something other than an SSD?

**Comment by DriftPunch** [comment]
No recent trace log.  (.../appdata/local/EDDiscovery/log) 

I can upload what I have, but that's from December and unrelated to recent issues.

Yes, old fashioned spin drive in RAID 1 for the EDD/Elite installation, but the OS and the rest are on SSD.  Whatever it's worth, there haven't been any system changes that coincide with the map problem.  It was working fine up until a month or so ago.

**Comment by DriftPunch** [comment]
[Trace_2023-02-10-18-32-10.0.log](https://github.com/EDDiscovery/EDDiscovery/files/10712087/Trace_2023-02-10-18-32-10.0.log)


That did it.

**Comment by Eahlstan** [comment]
The 3D map does many reads when loading. That's no fast thing when using HDDs (especially if you enabled the EDSM systems download).
My bet is that if you keep it loading for quite a while it will finally display something.

**Comment by DriftPunch** [comment]
I'll give it a shot.  Would it help to remove previous flight logs or break them up into separate, smaller chunks?

**Comment by klightspeed** [comment]
Flight logs shouldn't be a problem (unless you have hundreds of thousands of rows and have not set a filter on how much to keep in memory).  The main issue will be the EDDSystem.sqlite which contains all of the systems downloaded from EDSM.

**Comment by Eahlstan** [comment]
For testing you could limit the loaded events to 7 days on the settings panel. And if you're downloading EDSM systems close EDD, rename EDDSystem.sqlite, start EDD and select 'None' if asked what to download to avoid that DB to be read.

**Comment by DriftPunch** [comment]
Ok, I'm shifting my flight data over to an "archive" commander and will start with a blank slate and see how that goes.
