### ISSUE TITLE
EventEDDBPopulation error in log at every jump

### ISSUE THREAD

**Issue by wbovela** [EDDiscovery/EDDiscovery#3386]
This error occurs in the log at every jump:

Error: Function expand: Function ifnonzero: Parameter 1: Parameter 'EventEDDBPopulation' is not an number or a variable name
At Step 7 in VoicePackV17::FSDResponse:1213: Set

also note: "not an number" is incorrect: should be "not a number".

**Comment by Eahlstan** [comment]
Use the updated VoicePack, the newest version is 19.

**Comment by wbovela** [comment]
Thanks
