### ISSUE TITLE
EDDiscovery is crashing. This is what I get... 

### ISSUE THREAD

**Issue by flylow2023** [EDDiscovery/EDDiscovery#3387]
An unhandled fatal exception has occurred.

==== BEGIN ====
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Speech.Internal.ObjectTokens.ObjectToken.ISpObjectWithToken.SetObjectToken(ISpObjectToken pToken)
   at System.Speech.Internal.ObjectTokens.ObjectToken.CreateObjectFromToken[T](String name)
   at System.Speech.Internal.Synthesis.VoiceSynthesis.GetComEngine(VoiceInfo voiceInfo)
   at System.Speech.Internal.Synthesis.VoiceSynthesis.GetProxyEngine(VoiceInfo voiceInfo)
   at System.Speech.Internal.Synthesis.VoiceSynthesis.ThreadProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by Eahlstan** [comment]
At what point is it crashing?

**Comment by flylow2023** [comment]
Right at launch, it does not even launch. It was working fine last time I checked. I installed the Lite version and it's working, but this is what I am used to. Can't remember having installed anything else, just new NVIDIA drivers

**Comment by Eahlstan** [comment]
You already restarted Windows, didn't you?
Are you using your nVidia card to output sound?

Anyways, speech synthesis should only be called by addons, so assuming you're using addons please move the content of the Actions folder inside EDDs appdata folder ( %localappdata%\EDDiscovery if using the installed version with default settings) to a backup location to see if the error is gone.

**Comment by flylow2023** [comment]
I've restarted Windows, but I also uninstalled EDD to reinstall it again and now I've no EDD folder in appdata... Anyways, the app was installed on drive D could that be the reason? I've Nvidia card and I am using it to output sound to my speakers, and I also have VoiceAttack+ HCS Voicepacks+ EDDI, but none of them has been updated in the last days, as far as I remember.

**Comment by flylow2023** [comment]
I found out the app giving me the error. It's IVONA 2, which I bought years ago because of the voice AMY, used for commands in ED and Voice Attack. I don't use it for ED now but as it gave me an error the other day - use the voice for Windows - I reinstalled the pack. Apparently, EDD does not like it.

**Comment by Eahlstan** [comment]
> installed on drive D could that be the reason

Yes, as I said my location was the default one, yours is most likely inside the folder on your d drive.

I vaguely remember that someone had IVONA problems in the past, but they also didn't have a valid license and also didn't cause a crash.
@robbyxp1 once said he uses IVONA voices, so he can be used as a crash confirmer :D

Could you try if EDD crashes if EDD is the only app running that uses voice synthesis? - Running multiple synthesising apps can be a pain.
Also please take a look at the Windows event viewer and copy the content of every event surrounding entries of EDD crashes in the application section (please use common sense to judge if an event could be related).

**Comment by flylow2023** [comment]
Apparently everything is working fine. I do not use EDD for voice synthesis, just so to have logs. I use VoiceAttack and EDDI and HCS VoicPacks and they all appear to be working as they should. As I don't think I need the Amy voice right now, I will not reinstall the pack. As for now, EDD is not crashing, I've opened and closed it and gone through menus and it keeps working fine, so no problem there at the moment. If I find something else I will get back to you.

I've  checked the Event Viewer, besides information about a IVONA error - "Application popup: IVONA ControlCenter.exe - System Error : The code execution cannot proceed because MSVCR110.dll was not found. Reinstalling the program may fix this problem." there is nothing else there. Windows did make some security updates at about the same time I found I had a problem with EDD, but I don't think it's related. IVONA may well be the culprit, as everything went back to normal as soon 
I removed it. Thanks for getting back to me, that's what pointed me in the right direction: voices.

**Comment by Eahlstan** [comment]
That's a file from the Microsoft C++ redistributable. This can be caused by Windows update errors and is normally fixable by reinstalling it.
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by flylow2023** [comment]
Well, for now I got what I wanted: EDD is working. As for Amy, she will probably retire as I've enough voices in my ED cockpit right now. Thanks, anyway, great support.

**Comment by Eahlstan** [comment]
Well, missing that file can cause other programs to fail too. It's a rather important file, so even if you trash that voice you should try to get that file back.

**Comment by flylow2023** [comment]
Ok, again thanks. I reinstalled the Microsoft C++ redistributable, following your suggestion.

**Comment by robbyxp1** [comment]
Closing, solved
