### ISSUE TITLE
Eddiscovery not "receving" body data from EDSM

### ISSUE THREAD

**Issue by edi3d3d** [EDDiscovery/EDDiscovery#3388]
I've been using EDDiscovery for a while now and this is the first time it's done this.
I cannot receive the EDSM body data, I've checked the EDSM API, reinstalled EDDiscovery, changed the EDSM API key, synchronized with EDSM multiple times and its still not receiving the data.

I have the "Estimated Values" tab opened in EDDiscovery and the "Get and show information from EDSM" button is activated, but i'm not receiving EDSM body data, all I'm receiving is my data that I scanned with the ingame "D-scanned".

before I scanned a planet:
![Screenshot 2023-02-16 161546](https://user-images.githubusercontent.com/74777571/219389059-447e0177-b2b6-42c6-8014-6fe52784d401.png)

![Screenshot 2023-02-16 161708](https://user-images.githubusercontent.com/74777571/219389814-6c5fb8f7-3de9-4eea-8448-9baaf300b879.png)

after I scanned a planet:
![Screenshot 2023-02-16 161818](https://user-images.githubusercontent.com/74777571/219389774-35635935-2480-4040-9a1f-1f0fc4dfff94.png)

![Screenshot 2023-02-16 161949](https://user-images.githubusercontent.com/74777571/219390022-0ad176b3-6a41-4f3c-a4f1-ad33ebbef640.png)

What should I do to get the body data from EDSM?

**Comment by Eahlstan** [comment]
Can't receive data from EDSM if EDSM doesn't have data from that system.

**Comment by edi3d3d** [comment]
Ok, makes sense
