### ISSUE TITLE
There is some wrong lines in my 3D MAP

### ISSUE THREAD

**Issue by sunqian119** [EDDiscovery/EDDiscovery#3389]
3D Map:
![image](https://user-images.githubusercontent.com/40993130/222161370-0ecfdc18-08a3-4a55-a256-5bedb5dc4423.png)

2D Map:
![image](https://user-images.githubusercontent.com/40993130/222161532-74cc1e6c-4641-41f6-baed-8b4200db59f5.png)

the route lines in 2D map is right. and the map in v15.1.4 is right too. however ,the map goes wrong when the new 3d map added in EDDdiscovery, and continues to this day.

**Comment by Eahlstan** [comment]
I need all your journals (located in shell:SavedGames\Frontier Developments\Elite Dangerous ) to see what's going wrong.

**Comment by robbyxp1** [comment]
Our discord is a better method of sharing that data

**Comment by sunqian119** [comment]
> Our discord is a better method of sharing that data

It's hard for me to share the data in discord. so I have sent my journal logs to you by email.

**Comment by sunqian119** [comment]
> I need all your journals (located in shell:SavedGames\Frontier Developments\Elite Dangerous ) to see what's going wrong.

I have sent the data to Robbyxp1, you can ask for the data from him.

**Comment by robbyxp1** [comment]
Thank you - we will look into this and get back in the next few days.

**Comment by Eahlstan** [comment]
Multicrew events weren't ignored. Fixed and sent to Robby for review.

![Screenshot 2023-03-03 150406](https://user-images.githubusercontent.com/59618179/222742219-e05f4560-8096-4587-a2f6-5e33181577a6.png)

**Comment by robbyxp1** [comment]
Fix merged in, thanks for reporting, will be in next EDD
