### ISSUE TITLE
Crashing on startup of the app.

### ISSUE THREAD

**Issue by peterbanner55** [EDDiscovery/EDDiscovery#3390]
### Exception Details:
>EDDiscovery v16.0.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>SQLLiteExtensions.SQLProcessingThreadException: SQL logic error
>no such table: Systems ---> System.Data.SQLite.SQLiteException: SQL logic error
>no such table: Systems
>   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at EliteDangerousCore.DB.SystemsDB.FindStar(String name, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetStars.cs:line 69
>   at EliteDangerousCore.DB.SystemCache.FindSystemInCacheDB(ISystem find, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 139
>   at SQLLiteExtensions.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 355
>   --- End of inner exception stack trace ---
>   at SQLLiteExtensions.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 374
>   at SQLLiteExtensions.SQLAdvProcessingThread`1.Execute[T](Func`1 func, Boolean write, UInt32 warnthreshold, String jobname) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 258
>   at SQLLiteExtensions.SQLAdvProcessingThread`1.DBRead[T](Func`2 func, UInt32 warnthreshold, String jobname) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 42
>   at EliteDangerousCore.DB.SystemCache.FindSystem(ISystem find, Boolean checkedsm) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 85
>   at EliteDangerousCore.DB.SystemCache.FindSystem(String name, GalacticMapping glist, Boolean checkedsm) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 53
>   at EDDiscovery.UserControls.FindSystemsUserControl.SetXYZ() in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\FindSystemsUserControl.cs:line 275
>   at EDDiscovery.UserControls.FindSystemsUserControl.Init(DBSettingsSaver db, Boolean showexcel, EDDiscoveryForm disc) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\FindSystemsUserControl.cs:line 67
>   at EDDiscovery.UserControls.SearchStars.Init() in C:\Code\EDDiscovery\EDDiscovery\UserControls\Search\SearchStars.cs:line 51
>   at EDDiscovery.UserControls.UserControlSearch.<Init>b__2_1(TabStrip tab, Control ctrl, Int32 si) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Search\UserControlSearch.cs:line 51
>   at ExtendedControls.TabStrip.PostCreate() in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\TabStrip.cs:line 199
>   at ExtendedControls.TabStrip.ChangePanel(Int32 i) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\TabStrip.cs:line 131
>   at EDDiscovery.MajorTabControl.LoadTabs() in C:\Code\EDDiscovery\EDDiscovery\MajorTabControl.cs:line 106
>   at EDDiscovery.EDDiscoveryForm.EDDiscoveryForm_Load(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 520
>   at System.Windows.Forms.Form.OnLoad(EventArgs e)
>   at System.Windows.Forms.Form.OnCreateControl()
>   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>   at System.Windows.Forms.Control.CreateControl()
>   at System.Windows.Forms.Control.WmShowWindow(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.Form.WmShowWindow(Message& m)
>   at ExtendedControls.SmartSysMenuForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\SmartSysMenuForm.cs:line 219
>   at ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\DraggableForm.cs:line 169
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```
![Screenshot 2023-03-05 110005](https://user-images.githubusercontent.com/112392939/222956513-e197da8d-d592-4b7c-8366-c112a946e9cb.jpg)

**Comment by robbyxp1** [comment]
Your system DB is broken, as the text says. Hold down shift and run the program, then delete the system DB, and let it rebuild. 

If your using the system DB on anything other than a good SSD, then you should not be downloading many stars, or preferably no stars at all.
