### ISSUE TITLE
Wake from sleep - Unhandled UI Exception

### ISSUE THREAD

**Issue by fatlazycat** [EDDiscovery/EDDiscovery#3391]
### Description
Everytime i wake my computer from sleep i get the following issue with EDDiscovery

### Exception Details:
>EDDiscovery v16.0.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>OpenTK.Graphics.GraphicsContextException: Failed to make context 65537 current. Error: 0
>   at OpenTK.Platform.Windows.WinGLContext.MakeCurrent(IWindowInfo window) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Platform\Windows\WinGLContext.cs:line 279
>   at EDDiscovery.UserControls.UserControl3DMap.SystemTick(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\UserControl3DMap.cs:line 106
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
See #3271

**Comment by fatlazycat** [comment]
Get the same issue. Have set to high performance via that article.

![image](https://user-images.githubusercontent.com/338975/223666650-b16d0596-501d-4470-933b-be88d0c9f997.png)

**Comment by robbyxp1** [comment]
Its the sleep which is killing it - openGL does not handle sleeping very well.
