### ISSUE TITLE
unhandled UI exception.

### ISSUE THREAD

**Issue by Astermast3r** [EDDiscovery/EDDiscovery#3392]
### Exception Details:
>EDDiscovery v16.0.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
>database is locked
>   in System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
>   in System.Data.SQLite.SQLiteDataReader.NextResult()
>   in System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   in System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   in System.Data.SQLite.SQLiteCommand.ExecuteScalar(CommandBehavior behavior)
>   in SQLiteCommandExtensions.ExecuteScalar[T](DbCommand cmd, T def) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLExtensions.cs:riga 93
>   in EliteDangerousCore.DB.SystemsDB.FindAlias(Int64 edsmid, String name, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBEDSMSystemAliases.cs:riga 153
>   in EliteDangerousCore.DB.SystemCache.FindSystemInCacheDB(ISystem find, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:riga 146
>   in SQLLiteExtensions.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:riga 355
>===== END =====
>```

**Comment by Astermast3r** [comment]
Hi, often the EDDiscovery stops with this UI exception, opening Galaxy map on Elite Odyssey. OS: Windows 11 64b.

**Comment by robbyxp1** [comment]
Database is locked shows up when multiple clients are are trying to access the DB at the same time.

I'm presuming your running only one EDD at a time?

I've not seen this error recently, so have no other suggestions at this time.

Worse case, delete the system DB (via safe mode, hold down shift when running EDD) and build again

**Comment by robbyxp1** [comment]
Closing
