### ISSUE TITLE
capi failed

### ISSUE THREAD

**Issue by gnarfinger** [EDDiscovery/EDDiscovery#3396]
CAPI failed to get market data, retrying
CAPI failed to get shipyard data, retrying
CAPI failed to get market data, give up
CAPI failed to get shipyard data, give up

 Getting this message since 3-4 days now.

**Comment by robbyxp1** [comment]
I'll ask and see if capi is broken by frontier.

**Comment by robbyxp1** [comment]
Frontier have broken the CAPI request. We are awaiting a fix from frontier.
