### ISSUE TITLE
Surface Temperature Display Option for Surveyor

### ISSUE THREAD

**Issue by SirTedDanson** [EDDiscovery/EDDiscovery#3400]
The Surveyor already has display options for Show Gravity, Atmospheres, Volcanism, Signals, and I think adding a filter for 'Show Temperature' to 'Display Options' in the Surveyor would be a good enhancement. 

I use the surveyor to inform about landable bodies for discovering exobiology and geology. Currently the pertinent filtering the Surveyor provides:

-Has Atmosphere
-Is Landable
-Has Biological Signals

And provides the information

-Body Type
-Atmosphere Type
-Distance
-Gravity

All of this information is useful for exobiology and the Surveyor has proved invaluable as an explorer. However one additional piece of information is important for exobiology, and that is Surface Temperature. 

Surface Temperature along with Body Type, Gravity, Distance, and Atmosphere Type determine the occurrence of particular exobiology. Knowing the surface temperature communicates to the CMDR whether or not certain high value exobiology is likely to be present on the surface. I think it would be very helpful as an explorer to be able to look at the surveyor and immediately know a concerned planets surface temperature.

**Comment by robbyxp1** [comment]
We can add temperature output to SurveyorInfoLine

You can also add temperature trip searches to the discovery searches system in the surveyor to trip on temperature conditions, such as above, below, a temperature.

**Comment by Eahlstan** [comment]
Strange. I would have bet that it's added when checking "Show more info", but it isn't.

I'm thinking about: If it's landable and it has an atmosphere and "show atmosphere" is checked then display the surface temperature.

![Screenshot 2023-03-31 181151](https://user-images.githubusercontent.com/59618179/229173941-d9bbeb57-d4d7-450d-90ba-aba6acaa3124.png)

Or should it be bound to other triggers?

**Comment by SirTedDanson** [comment]
Awesome. I think that looks perfect Eahlstan. You guys are so fast to this stuff, great devs!

**Comment by Eahlstan** [comment]
> Awesome. I think that looks perfect Eahlstan. You guys are so fast to this stuff, great devs!

Would you prefer a switch to toggle it on all landables instead of my approach of adding it just to atmospheric landables when displaying the atmosphere?
I'm not sure what's better.
