### ISSUE TITLE
Version 16.1.1 has internally still 16.1 as Version number, so update notification still comes

### ISSUE THREAD

**Issue by lwt-pressy** [EDDiscovery/EDDiscovery#3405]
After installing the new Version 16.1.1 I still get the notification to update to 16.1.1 

checking about the installation still shows the old version number 16.1

even deleting Folder "C:\Program Files\EDDiscovery" and installing 16.1.1 new does not change it.

**Comment by robbyxp1** [comment]
Sorry - reinstall the current one.

**Comment by Eahlstan** [comment]
To be more precise: There was an internal error on our side. Please redownload the 16.1.1 release, it's now fixed.

**Comment by lwt-pressy** [comment]
thx, for the fast fix. Worked for me and also thx for the nice product.
