### ISSUE TITLE
16.1.1 does not take AppData\Local for configuration

### ISSUE THREAD

**Issue by pdario** [EDDiscovery/EDDiscovery#3406]
I just updated to v 16.1.1 (exe installer) and choosed AppData\Local as configuration location, but when it starts it crashes because it does not fine data directory in its installation directory.

I don't know how to start the program now

**Comment by Eahlstan** [comment]
Can you please look in the install directory and see if there are any .txt files in there and upload them here?

**Comment by pdario** [comment]
I found optionsportable.txt, content:

-AppFolder Data
-Portable

**Comment by Eahlstan** [comment]
I just tried it, looks like the installer doesn't delete the old options files if there were any.
Please rename that file to something else (optionsportable.txt.old maybe?) and then try it again.
Also: Did you always use the installed version?

**Comment by pdario** [comment]
Ok, it started: I did try the zip version because I thought it was just easier to overwrite the installed versione with that.

**Comment by Eahlstan** [comment]
Ah, yeah. That one contains that text file. But as it wasn't able to write in the specified directory (guess you're using %programfiles% or a similar protected directory) it failed.
Glad it was just that.

**Comment by pdario** [comment]
BTW: latest version is recognized as a threat by Norton 360

**Comment by Eahlstan** [comment]
Some AVs do this some times. There's little to nothing that we can do about it

**Comment by pdario** [comment]
Isn't this strange for this sort of application?

**Comment by Eahlstan** [comment]
Not really. Most AVs use fully automated AI detections. They aren't exactly precise, so they flag all kind of software that contains certain things.
Might be that EDD is able to download add-ons, might be it has a DLL interface. Might be some other thing the current AI doesn't like.
Most AV companies do have a "report false alert" form somewhere, so if you want to you can try that. It's just too many AVs out there to be worth the time doing that every time everywhere on every false alert.
