### ISSUE TITLE
ED Discovery Wont Close

### ISSUE THREAD

**Issue by KraziyK** [EDDiscovery/EDDiscovery#3408]
Since I started using EDDiscovery, which is the last 2-3 versions. The app opens and appears to function as intended. However it won't close in any way other than using the task manager to force it to close. It will say "goodbye commander" and show the message "closing please wait" and then nothing else appears to happen even after letting it sit for hours.

I just updated to the latest version a day or two ago and I'm still having this problem. While I don't entirely mind using the task manager to close it, it's weird and something that I can't seem to figure out why it's doing that.

**Comment by robbyxp1** [comment]
Are you using the voice pack?
I wonder if the sound system is preventing a shutdown.

**Comment by KraziyK** [comment]
I do have the voice output enabled. I attached the log from 4/11, when I used the app last.
[Trace_2023-04-11-19-20-13.0.log](https://github.com/EDDiscovery/EDDiscovery/files/11266948/Trace_2023-04-11-19-20-13.0.log)

**Comment by Eahlstan** [comment]
I see you're using an old version. Please try if the newest version does the same.

**Comment by KraziyK** [comment]
It shows 16.1.1. on the latest version page and my program shows 16.1.1.0. It still isn't closing.

**Comment by Eahlstan** [comment]
There's a folder called action (I think, not on the PC to check, sorry) in the same place as the log folder that contains your downloaded and active addons. Please move all of them - except the Canonn one - to a backup location and see if it shuts down without them.

**Comment by KraziyK** [comment]
It did shut down after removing those add-ons.

**Comment by Eahlstan** [comment]
Great. Leave it this way until Robby wrapped his mind around this.
 Please tell us which files you moved.

**Comment by KraziyK** [comment]
I moved 
freevoocecontrolv4.acf & .sha
Voicepackv19.act & .sha

I left the Canon mod in place

**Comment by robbyxp1** [comment]
try putting the voicepackv19 back and see what happens

**Comment by KraziyK** [comment]
I moved the voicepack19 files back into the action folder and did two tests. Both times it closed with no problem.

**Comment by robbyxp1** [comment]
No idea.  There is no evidence of any problem with EDD, if so, we would be having many reports.

Can't do anything futher really.

**Comment by Eahlstan** [comment]
> I moved the voicepack19 files back into the action folder and did two tests. Both times it closed with no problem.

And when you move the other file back?

**Comment by robbyxp1** [comment]
Closing, no user response
