### ISSUE TITLE
EDDiscovery v16.1.1.0 There was an unhandled UI exception.

### ISSUE THREAD

**Issue by A-vives** [EDDiscovery/EDDiscovery#3409]
### Exception Details:
>EDDiscovery v16.1.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: El índice estaba fuera del intervalo. Debe ser un valor no negativo e inferior al tamaño de la colección.
>Nombre del parámetro: index
>   en System.Collections.ArrayList.get_Item(Int32 index)
>   en System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
>   en System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
>   en EDDiscovery.UserControls.UserControlExpedition.<UpdateSystemRows>d__29.MoveNext() en C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlExpedition.cs:línea 280
>--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
>   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by Eahlstan** [comment]
Please describe what you did when this happened.

**Comment by klightspeed** [comment]
Were you deleting an expedition in EDDiscovery?  If so, this seems to be a reappearance of #3308

**Comment by robbyxp1** [comment]
updatingsystemrows, set true during async update of rows, should stop these buttons working, and produce a beep.

I notice cutToolStripMenuItem_Click(object sender, EventArgs e) is missing the check for this variable..

pasteToolStripMenuItem_Click(object sender, EventArgs e) as well, insert... drag drop.

maybe one of those triggered.  Another review of the code here is needed. Will do.

**Comment by A-vives** [comment]
I only try to make a expedition with my rute nav
first: The route dont import good, start's from latest sistem, not
actually begin
second, when I go a system that is in the route, why not delete himself
when I visited?
third: I can't make a route like "only stars With fuel scoop, hight % to
appear a water-world..." and import to elite
Only the problem I have is when I go to see if the objective system is
visited or not

sorry 4 my bad english, im practice every day

**Comment by robbyxp1** [comment]
Expedition systems don't delete themselves 
EDD does not have any information on the bodies in the system when you make an expedition.

**Comment by robbyxp1** [comment]
Going to be fixed in next release, thanks
