### ISSUE TITLE
Name_Localised

### ISSUE THREAD

**Issue by AdiMaste** [EDDiscovery/EDDiscovery#3410]
![Screenshot_19](https://user-images.githubusercontent.com/131433515/233558160-fe6071a9-3f0b-4ac2-b076-3e7742ebbae0.png)
Name != Name_Localised

**Comment by klightspeed** [comment]
The destination comes from `Status.json`.  Is `.Destination.Name_Localised` present in `Status.json` when you have a USS targeted?

**Comment by robbyxp1** [comment]
UIDestination only reads Name

Journal doc only has 

o	Destination:
o	System
o	Body
o	Name

Frontier does not give the localisation name, so thats the best we can do for now. We don't encode what Scenario 78 is internally.

thanks for the report.

**Comment by robbyxp1** [comment]
I've created a card ticket, we may be able to do some sort of translation from data in your journal

https://github.com/EDDiscovery/EDDiscovery/projects/3#card-88957991
