### ISSUE TITLE
EDDiscovery doesn't seem to display income in the ledger when missions are completed

### ISSUE THREAD

**Issue by serjevski** [EDDiscovery/EDDiscovery#3413]
When I complete the mission and receive the EDD reward, I don't see it. And only the next time you start the game, make adjustments to finances.

**Comment by serjevski** [comment]
![Снимок экрана 2023-05-03 002703](https://user-images.githubusercontent.com/2284313/235790007-f143aa06-65bf-4035-960e-732cca6df1f6.png)
Here is a screenshot of these corrections

**Comment by Eahlstan** [comment]
Please provide your journal files so I can check what's going on.

**Comment by robbyxp1** [comment]
Its the ledger, the code on main looks right.  We need to see the journal to see why its not reporting it.

The cash adjustments are very large, more than you'll get from some missions.  Something else is going on.

**Comment by serjevski** [comment]
Here is a journals.. 
[Journal.2023-05-03T133158.01.log](https://github.com/EDDiscovery/EDDiscovery/files/11381652/Journal.2023-05-03T133158.01.log)
[Journal.2023-05-03T104456.01.log](https://github.com/EDDiscovery/EDDiscovery/files/11381653/Journal.2023-05-03T104456.01.log)
[Journal.2023-05-03T100153.01.log](https://github.com/EDDiscovery/EDDiscovery/files/11381654/Journal.2023-05-03T100153.01.log)
[Journal.2023-05-03T002213.01.log](https://github.com/EDDiscovery/EDDiscovery/files/11381655/Journal.2023-05-03T002213.01.log)
[Journal.2023-05-02T215704.01.log](https://github.com/EDDiscovery/EDDiscovery/files/11381656/Journal.2023-05-02T215704.01.log)
[Journal.2023-05-02T215324.01.log](https://github.com/EDDiscovery/EDDiscovery/files/11381657/Journal.2023-05-02T215324.01.log)

**Comment by serjevski** [comment]
> Its the ledger, the code on main looks right. We need to see the journal to see why its not reporting it.
> 
> The cash adjustments are very large, more than you'll get from some missions. Something else is going on.

We flew several missions in the wing, each brought 40-50 million credits, approximately. The EDD version is the latest.

**Comment by Eahlstan** [comment]
Sadly Frontier is to blame.
MissionCompleted events (and maybe other similar events) are only written to the journal of the guy that accepted the wing mission (the wing leader I guess? I'm neither a mission nor a wing player.)
So there's no way for any app to see if that mission got completed and what rewards were given, therefore there's no way to correctly calculate your bank account. As you could see the only possible thing to do is to use the statistics written at the start of a new session to correct the value.

**Comment by serjevski** [comment]
Ok, I see :)
