### ISSUE TITLE
Crashed upon launch

### ISSUE THREAD

**Issue by KitsuneNoNatsu** [EDDiscovery/EDDiscovery#3414]
### Exception Details:
>EDDiscovery v16.0.4.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object
>  at EDDiscovery.EDDiscoveryForm.ApplyTheme (System.Boolean panelrefreshaswell) [0x0000b] in <4ef0aa7a8d984063bdf108deabf92c3d>:0 
>  at EDDiscovery.EDDiscoveryForm.Init (System.Action`1[T] msg) [0x0052e] in <4ef0aa7a8d984063bdf108deabf92c3d>:0 
>  at (wrapper remoting-invoke-with-check) EDDiscovery.EDDiscoveryForm.Init(System.Action`1<string>)
>  at EDDiscovery.EDDApplicationContext.InitialiseEDD (System.Object sender, System.EventArgs e) [0x00250] in <4ef0aa7a8d984063bdf108deabf92c3d>:0 
>===== END =====
>```

**Comment by Eahlstan** [comment]
Old version, please upgrade.
