### ISSUE TITLE
Deleting a route that is not fully loaded

### ISSUE THREAD

**Issue by binick** [EDDiscovery/EDDiscovery#3416]
### Description
In the Expedition tab I loaded a saved route and immediately afterwards tried to delete it.

### Exception Details:
>EDDiscovery v16.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.Collections.ArrayList.get_Item(Int32 index)
>   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
>   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
>   at EDDiscovery.UserControls.UserControlExpedition.<UpdateSystemRows>d__29.MoveNext() in C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlExpedition.cs:line 280
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by Eahlstan** [comment]
Fun fact: I just triggered the same error, although I wanted a new expedition while another one was loaded (which might also delete the old expedition first).

Thanks for your report, we'll look into it.

**Comment by robbyxp1** [comment]
Addressing in 16.2, thanks
