### ISSUE TITLE
 Feature-Request: Display the price for organic scans after the first scan

### ISSUE THREAD

**Issue by Plotnik01** [EDDiscovery/EDDiscovery#3418]
I have a feature request. Could the price be displayed in the organic scans tab right from the first scan? Perhaps in italics to indicate that the price estimation is preliminary and subject to change if prices are updated. Either the prices can be taken from the already scanned organic data or from https://canonn.science/codex/vista-genomics-price-list/. This way, we wouldn't have to check every time.

**Comment by Eahlstan** [comment]
It's more or less going to be something like this, please add your feedback:

![Screenshot 2023-05-26 230756](https://github.com/EDDiscovery/EDDiscovery/assets/59618179/8445aee1-83c0-4fe0-aae6-da34354bf54a)
![Screenshot 2023-05-26 231033](https://github.com/EDDiscovery/EDDiscovery/assets/59618179/de31b9fb-475e-4cd1-b962-3ab8bf98a027)
![Screenshot 2023-05-26 231139](https://github.com/EDDiscovery/EDDiscovery/assets/59618179/31ef1c32-362b-4c82-b461-4246b3402e26)

**Comment by Plotnik01** [comment]
Great! Thank you for the quick response. I really like the suggestion. From my side, it can be incorporated as is.

**Comment by Plotnik01** [comment]
It would also be great if you could use different symbols for bio or geological signals in the scan subpanel

**Comment by robbyxp1** [comment]
Moved to worklist
