### ISSUE TITLE
star names re-appear in 3d map

### ISSUE THREAD

**Issue by ironfbody** [EDDiscovery/EDDiscovery#342]
I switch off star names in the 3d map, especially in a close up view.  When I change the zoom or the position of the view, the star names re-appear and I have to switch them off again, and again and again.

**Comment by finwen** [comment]
Oh. we should fix that hopefully in 4.2.1 soon :)


2016-08-16 16:01 GMT+02:00 ironfbody <notifications@github.com>:

**Comment by robbyxp1** [comment]
Fixed on my branch for 4.2.1

**Comment by robbyxp1** [comment]
Fixed in release.
