### ISSUE TITLE
Display freezes when running 2 instances of EDO

### ISSUE THREAD

**Issue by BannorPhil** [EDDiscovery/EDDiscovery#3421]
I have a 'main' Elite Dangerous character and an 'alt' character. Both have Odyssey. Sometimes, for example when farming materials, I have them both active at the same time - two separate instances of ED running simultaneously on the same PC (Windows 10 x64). 
When I do this, the display of EDD 'freezes' - it does not update, I cannot swap commanders nor can I select another profile, tab or do anything. I *think* the app still works in the background, and I can still shut it down normally - but I can't actually use it for anything useful while playing. It works fine with either single character, just not with both together.

**Comment by Eahlstan** [comment]
That's not supported (and never will be), so there's nothing that can (or will) be done about such a "bug".

Sorry.
