### ISSUE TITLE
Exporting EDSM System Information when none exists triggers an exception

### ISSUE THREAD

**Issue by designerzim** [EDDiscovery/EDDiscovery#3422]
### Description
Set up a small custom expedition with systems that have "No body information found on EDSM". Only 11 systems covering 2480 LY in a 1400 LY distance.

I clicked Export to File and selected "EDSM System Information" from the drop down and used the default file name offered. 

An exception is thrown after selecting Save with the file name defined.

### Additional Information
It appears to happen with any system that is not in EDSM. 

Try it (currently) with **Swoirks TO-F c25-0**

### Exception Details:
>EDDiscovery v16.2.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlExpedition.buttonExtExport_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlExpedition.cs:line 775
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
I will investigate, thanks for the report.

**Comment by Eahlstan** [comment]
I can't reproduce it. Which version of EDDiscovery are you using?

**Comment by klightspeed** [comment]
It suggests that `EDSMClass.GetBodiesList` is returning `null` at <https://github.com/EDDiscovery/EDDiscovery/blob/4988ef0bff45b189241fa6430d53a46238877667/EDDiscovery/UserControls/RoutesExpeditions/UserControlExpedition.cs#L775-L776>

This makes sense if the system is not on EDSM, since a system that doesn't exist in EDSM isn't going to return any bodies.

Note that unlike `ValueTuple` (a value-type), `Tuple` is a class, and can be null.

You probably want line 776 to be:
```cs
List<JournalScan> sysscans = jl?.Item1;
```

**Comment by robbyxp1** [comment]
Moved to worklist
