### ISSUE TITLE
Transparent panels visible only when game is running?

### ISSUE THREAD

**Issue by Ejsstiil** [EDDiscovery/EDDiscovery#3423]
Hi there,
as the title says - I am using this feature quite a lot, but these are displayed all the time, even if the game Elite is not running.
Its this feature [Transparent panels](https://github.com/EDDiscovery/EDDiscovery/wiki/Using-the-Mission-Overlay-Panel) 

I think, that for EDD isn't hard or even maybe it does know already, whether game is running or not, hide/show panels based on that? Globally for all panels would suffice just fine.

Thank so much!
CMDR Ejsstiil

**Comment by robbyxp1** [comment]
We do not do this at the moment.  It would be intensive in processing to constantly check if Elite.exe is running at the time and react to it.  So not implemented, and probably won't.  I'll give it a bit of thought. Moved to worklist

**Comment by Ejsstiil** [comment]
Thank you for your consideration..
It doesn't have to be a constant process of monitoring the game process... Could be a much simpler, ie. "if journal events are silent for certain time", or even better - there is a "Shutdown" event in the Journal or just provide GUI/Tray button/option to hide them... Anything would be better than closing that panels when one does not want to close EDD between playing sessions ;)
