### ISSUE TITLE
Consider other icon formats

### ISSUE THREAD

**Issue by Artoria2e5** [EDDiscovery/EDDiscovery#3424]
The current EDDis program has about 3/4 of its size in a 27 MB icon-assembly, consisting mostly of png resources. I see that many of the files have already been quantized to 256 indexed colors, the standard for making small PNGs.

However, some icons are just more "photographic" compared to "textual" and do not actually need lossless compression. This applies to most of the stars and planets: the surface is grainy already and lossy compression would work better. Alpha is the biggest concern still -- WebP (lossy or lossless for both alpha and colors) is a good candidate with okay browser support, but passing WebP to System.Drawing.Imaging requires Windows 10 1809. Doing a jpg + png mask does not sound very neat.

The 112 KB "A.png" image is brought down to 61 KB using GIMP's default settings for webp (q90 for color, q100 for alpha). Zooming in shows the same bunch of starspots.

**Comment by klightspeed** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.drawing.imaging.imageformat.webp?view=windowsdesktop-7.0

WebP is only supported by System.Drawing in .NET 7 and 8, and is not supported in .NET Framework (which EDDiscovery is built on).

To support it, a library would be required.  I don't think you want the 87MB Magick.NET library or the 4.3MB SixLabors.ImageSharp library just to shave a couple of MB off the icon assembly.

**Comment by Artoria2e5** [comment]
Considering that they are all round, perhaps... a transparent mask on top of a jpg is the way forward here? :/

**Comment by robbyxp1** [comment]
Thanks for the idea, but the effort IMO is not worth the reward. 27 mb is nothing in todays world.
