### ISSUE TITLE
Crashing on open after fresh install

### ISSUE THREAD

**Issue by Cosmonautilis** [EDDiscovery/EDDiscovery#3425]
### Description
Program had just installed and was opening for first time.

### Additional Information
Happens when small opener window is on "Loading Translations"

### Exception Details:
>EDDiscovery v16.2.0.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.ArgumentException: Absolute path information is required.
>   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
>   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
>   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
>   at System.Environment.InternalGetFolderPath(SpecialFolder folder, SpecialFolderOption option, Boolean suppressSecurityChecks)
>   at EliteDangerousCore.ScreenShots.ScreenShotConverter..ctor() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Screenshots\ScreenShotConverter.cs:line 44
>   at EDDiscovery.EDDiscoveryForm.Init(Action`1 msg) in C:\Code\EDDiscovery\EDDiscovery\EDD\EDDiscoveryForm.cs:line 269
>   at EDDiscovery.EDDApplicationContext.InitialiseEDD(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDD\EDDApplicationContext.cs:line 243
>===== END =====
>```

**Comment by Eahlstan** [comment]
Solved on Discord, something blocked EDD access to its own folder in program data. Moved it to another folder as workaround.
