### ISSUE TITLE
crashing after scanning a system

### ISSUE THREAD

**Issue by lolgamerz89** [EDDiscovery/EDDiscovery#3426]
### Description
<was doing exo/bio scans. also coming up when jumping systems>

### Exception Details:
>EDDiscovery v16.2.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
>   at System.Reflection.RuntimeAssembly.GetResource(RuntimeAssembly assembly, String resourceName, UInt64& length, StackCrawlMarkHandle stackMark, Boolean skipSecurityCheck)
>   at System.Reflection.RuntimeAssembly.GetManifestResourceStream(String name, StackCrawlMark& stackMark, Boolean skipSecurityCheck)
>   at System.Reflection.RuntimeAssembly.GetManifestResourceStream(String name)
>   at BaseUtils.Icons.IconSet.Get(String name) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\IconSet\IconSet.cs:line 225
>   at BaseUtils.Icons.IconSet.GetIcon(String name) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\IconSet\IconSet.cs:line 262
>   at EliteDangerousCore.SystemDisplay.DrawNode(List`1 pc, ScanNode sn, List`1 historicmats, List`1 curmats, Image notscanned, Point position, Boolean xiscentre, Rectangle& imagepos, Size size, DrawLevel drawtype, Nullable`1 backwash, String appendlabeltext) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplayNodes.cs:line 61
>   at EliteDangerousCore.SystemDisplay.CreatePlanetTree(List`1 pc, ScanNode planetnode, List`1 historicmats, List`1 curmats, Point leftmiddle, String[] filter, Boolean habzone, Int32& planetcentre) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplay.cs:line 331
>   at EliteDangerousCore.SystemDisplay.DrawSystem(ExtPictureBox imagebox, Int32 widthavailable, SystemNode systemnode, List`1 historicmats, List`1 curmats, String opttext, String[] filter) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDisplay\SystemDisplay.cs:line 220
>   at EDDiscovery.UserControls.ScanDisplayUserControl.DrawSystem(SystemNode systemnode, List`1 historicmats, List`1 curmats, String opttext, String[] filter) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\ScanDisplayUserControl.cs:line 59
>   at EDDiscovery.UserControls.UserControlScan.<DrawSystem>d__18.MoveNext() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:line 211
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by Eahlstan** [comment]
What's your operating system?
Also there's a log folder in EDDs data directory (default location %localappdata%\EDDiscovery ), please upload the latest trace_*.log (not the .hlog file that one has sensitive data in it).

**Comment by lolgamerz89** [comment]
yeah ive done reboots. i did do a windows update last night im using current version of 11. ill get the files when im back at the computer.

**Comment by klightspeed** [comment]
HRESULT `0x80070008` => `ERROR_NOT_ENOUGH_MEMORY`

I wonder if the process is running as a 32-bit process, and is running into memory fragmentation, or if the icons are being allocated in graphics ram, and that is running out?

**Comment by robbyxp1** [comment]
closing, no more responses
