### ISSUE TITLE
Missions tab <font> tag doesn't resolve

### ISSUE THREAD

**Issue by sbtegze** [EDDiscovery/EDDiscovery#3427]
The active misison titles include font color tags, but they aren!t resolved. See screenshot.
![image](https://github.com/EDDiscovery/EDDiscovery/assets/76405119/906d84d1-95ce-4383-b626-94433d9317ed)

**Comment by klightspeed** [comment]
Perhaps EDDiscovery should strip SGML tags out of the mission `LocalisedName`?

**Comment by Eahlstan** [comment]
Sometimes I hate Frontier for doing things like this.

Example event for Robby:

`{ "timestamp":"2023-02-26T01:26:35Z", "event":"MissionAccepted", "Faction":"HIP 20485 Corp.", "Name":"Mission_TW_Massacre_Hydra_Plural", "LocalisedName":"Eliminate <font color='#FFFFFF'>1</font> Hydras", "TargetType":"$MissionUtil_FactionTag_Hydra;", "TargetType_Localised":"Thargoid Hydra", "TargetFaction":"HIP 20485 Corp.", "KillCount":1, "DestinationSystem":"HIP 20485", "DestinationStation":"Bachman Port", "Expiry":"2023-02-27T08:34:34Z", "Wing":true, "Influence":"+", "Reputation":"++", "Reward":30601466, "MissionID":917749415 }`

**Comment by robbyxp1** [comment]
Closing, moving to work list

**Comment by robbyxp1** [comment]
Thanks for the report.
