### ISSUE TITLE
Crashes while loading

### ISSUE THREAD

**Issue by tbojustin** [EDDiscovery/EDDiscovery#3429]
### Exception Details:
>EDDiscovery v16.2.0.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.BadImageFormatException: Could not load file or assembly 'EDDiscovery.Icons, Version=1.0.8539.21292, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
>File name: 'EDDiscovery.Icons, Version=1.0.8539.21292, Culture=neutral, PublicKeyToken=null'
>   at EDDiscovery.EDDiscoveryForm.Init(Action`1 msg)
>   at EDDiscovery.EDDApplicationContext.InitialiseEDD(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDD\EDDApplicationContext.cs:line 243
>
>WRN: Assembly binding logging is turned OFF.
>To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
>Note: There is some performance penalty associated with assembly bind failure logging.
>To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
>
>===== END =====
>```

**Comment by klightspeed** [comment]
One of the DLLs being missing suggests that it didn't install properly.  Please try re-installing.

**Comment by robbyxp1** [comment]
Closed as answered
