### ISSUE TITLE
Main Screen and Screen "estimated scan values" System display Question

### ISSUE THREAD

**Issue by Boernie25** [EDDiscovery/EDDiscovery#3430]
In an estimated 80-90% of the systems that I fly to, the EDDiscovery system map remains, both on the main screen and
as well as in the "Estimated Scan Values" ​​window, empty. In the Ingame "system map" (ED-Odyssey and ED-Horizon > 3.8)
all celestial bodies are displayed as they are displayed after a successful VSS scan. 

Do I scan the NAV buoy in the system, all celestial bodies appear in those two EDD-Windows after about 60-90s
together with the corresponding status.

I observed that after scanning the nav buoy, EDDiscovery sends the data to EDDN and to
the response from EDDN, it fills the two windows in EDDiscovery..

That looks to me like you're reading the data at the wrong place.

In my opinion, this is also confirmed by a second error that I've noticed: I recently lost my ship in the game,
all already scanned and not yet sold system data have been lost in the Game and are shown that way, but in EDDiscovery
however, they still appear as finished scanned (map) in the two windows mentioned, along with the higher Cr values.

If I reach a system that is still completely unknown, i.e. the suns are also marked as "not explored" in the game
displayed, everything works as it should...

I have re-read the journal data several times and EDDiscovery has been reinstalled twice, without success

I have created a few examples, with screenshots, which I am happy to send to you if it can help with troubleshooting, 
plus all the journal data you need to do so. Just tell me, what you need...

Regards, Bernd
cattarius@web.de
![ED-SystemsMap LHS 1918](https://github.com/EDDiscovery/EDDiscovery/assets/67825179/5d15f8af-fb54-4be0-9aab-25809aeb9f40)
<img width="1219" alt="EDD8" src="https://github.com/EDDiscovery/EDDiscovery/assets/67825179/88b6d558-7037-42ca-9c2b-4b92ce70c943">
<img width="1219" alt="EDD-afterNavbuoy-Scan" src="https://github.com/EDDiscovery/EDDiscovery/assets/67825179/6d8bd589-acbe-424f-8c95-0443349e0aaf">

**Comment by Eahlstan** [comment]
Some in game systems are hard coded as pre-discovered. Thus they can't be FSSed as they are completely known to all commanders. The only way to get body data of those systems is to scan the nav-beacon - just as you did. This scan can fill your journal with dozens of scan events at the same time, causing some processing lag.
The same is true for systems you previously visited and scanned and then the journal holding those events was deleted.

There's no event that provides reliable info about which body data you sold, so it's impossible to track sold bodies and thus it's impossible to reset anything to "the game thinks this is unscanned".

**Comment by robbyxp1** [comment]
Closing, answered question.
