### ISSUE TITLE
[Feature Request] Option to pull data from CAPI for Geforce Now users

### ISSUE THREAD

**Issue by WarmedxMints** [EDDiscovery/EDDiscovery#3431]
Is it possible to pull periodically from the CAPI for PC users playing on Geforce Now, please?

**Comment by klightspeed** [comment]
In your commander settings what options do you have in the Frontier CAPI section?

**Comment by robbyxp1** [comment]
You should be able to pull using a console commander (see help for how to set that up in the settings panel - click on ?) if you know your fdev login information.

**Comment by robbyxp1** [comment]
Actually, if you set it up as a console commander, you'll be pulling from the legacy galaxy, not the live galaxy.  So it won't work unless your playing Horizons on GE Force now.

**Comment by klightspeed** [comment]
You might want to use a service like Journal Limpet <https://journal-limpet.com/> to grab your journals.

**Comment by Eahlstan** [comment]
> Actually, if you set it up as a console commander, you'll be pulling from the legacy galaxy, not the live galaxy. So it won't work unless your playing Horizons on GE Force now.

Actually, there's a live Horizons too. So he'd need to play the "Legacy Horizons" or "Legacy Elite Dangerous" version.

**Comment by robbyxp1** [comment]
Closing.  You can use the console commander options in the legacy universe. No support for live mode. Added to worklist.
