### ISSUE TITLE
Importing bookmarks that were exported with commas as decimal separators doesn't work

### ISSUE THREAD

**Issue by wenkman-007** [EDDiscovery/EDDiscovery#3434]
I've now tried a few things to import bookmarks, I've created several CSV files and tried to load them exactly (unchanged) (yes, I deleted the bookmarks beforehand), it doesn't work somehow.

**Comment by Eahlstan** [comment]
Well, it would be much easier to say anything about this if you provided the file you tried to import.

**Comment by wenkman-007** [comment]
i found the error, when you export the bookmarks, the numbers are output with "", the program can't handle that if you want to load them again

**Comment by Eahlstan** [comment]
Well that sounds like a bug. I'm reopening so I don't forget to try this myself.
Your files would stil be usefull.

**Comment by wenkman-007** [comment]
[Bookmarks.csv](https://github.com/EDDiscovery/EDDiscovery/files/12286024/Bookmarks.csv)
i hope it help

**Comment by wenkman-007** [comment]
[EXO_exportiert_koma.csv](https://github.com/EDDiscovery/EDDiscovery/files/12286041/EXO_exportiert_koma.csv)
and this i generated with my programm, this file work

**Comment by Eahlstan** [comment]
I see the bug, thanks for the files.

**Comment by Eahlstan** [comment]
Quick question: Was "Gesammt" added by you? I tried to find where I made that error, but I'm unable to locate that spelling error.

**Comment by robbyxp1** [comment]
Noted and will be fixed.
