### ISSUE TITLE
Target System not updating correctly 

### ISSUE THREAD

**Issue by MaineMan2012** [EDDiscovery/EDDiscovery#3439]
Hi,

I'm having an issue with the surveyor not selecting the next target correctly. When set to auto it selects the system that I am currently in and not the next waypoint.

Any help would be appreciated.

**Comment by Eahlstan** [comment]
Please elaborate. Right now I can't wrap my mind around your problem.

**Comment by MaineMan2012** [comment]
What I am trying to do is use the Surveyor tab with the auto-set target and auto-copy next waypoint commands. I believe this will allow me to go into the galaxy map and ctrl+v the next waypoint into the search and select it as the route. 

I have created a route inside the expedition tab. I then selected that route in the surveyor tab. In the route settings under the surveyor, I have checked on; auto-copy way point, auto-set target, and show target information. My issue is instead of targeting the next system in the list the auto-targeting keeps choosing the system I am currently in.  ie  (WP) 19 = HIP 10921 ( current location)  and (WP) 20 = HIP 11329 (next WP in the list).  Auto Targeting is choosing (WP) 19 = HIP 10921 and not (WP) 20 = HIP 11329 

T - >  HIP 10921

So I can not go directly to the galaxy map and ctrl+v the next (WP) in the search because it pastes the system I am currently in. ie (WP) 19 = HIP 10921
Hopefully, that explains the issue.
I have uninstalled and reinstalled V 16.2.0.0 and I have also tried it in V16.1.0.0.
I have also made another expedition and loaded that on but it continues to auto-target the system I am currently in.

**Comment by robbyxp1** [comment]
string name = closest.nextsystem.Name;

                        if (lastsystemroute == null || name.CompareTo(lastsystemroute) != 0)
                        {
                            if (IsSet(RouteControl.autocopy))
                                SetClipboardText(name);

                            if (IsSet(RouteControl.settarget))
                            {
                                if (TargetClass.SetTargetOnSystemConditional(name, closest.nextsystem.X, closest.nextsystem.Y, closest.nextsystem.Z))
                                {
                                    DiscoveryForm.NewTargetSet(this);
                                }
                            }

                            lastsystemroute = name;
                        }

looks like its copying the next system

What is on the clipboard.. go into a word processor and ctrl-v in there.  Is it an image. 

Other sources of clipboard is trilat page, screenshots, clicking on a cell in the nearest star panel, route page, expedition page, sysinfo when you click in a textbox.

**Comment by MaineMan2012** [comment]
hi, so I'm currently in Col 285 Sector WE-Q c5-11,  which is (WP 21) in my expedition tab. my next waypoint should be (WP 22) HIP 6668. If I start my surveyor with this expedition it set this as my target. When I ctrl v into notepad it past "Col 285 Sector WE-Q c5-11". Col 285 Sector WE-Q c5-11 also shows as being my target. it seams it is copy-pasting correctly but it is choosing the incorrect waypoint.

**Comment by MaineMan2012** [comment]
The target system does not update to the next waypoint when I jump into a new system. It updates but it targets the system I just jumped into.

**Comment by Eahlstan** [comment]
Yeah, we already circled the bug in the SavedRouteClass, we just wait for it to surrender.

**Comment by MaineMan2012** [comment]
Thanks
