### ISSUE TITLE
Feature Request: Sort by parent body in journals tab

### ISSUE THREAD

**Issue by DigitalJaguar** [EDDiscovery/EDDiscovery#3440]
I'm pulling up a history of all hot spots and their contents in my journal tab, and would greatly appreciate the ability to organize it by the planetary body the ring is around. Either adding a new column that the parent body gets put in, or just moving the location info ("@ Inheretti A 3 A Ring" for example) to the beginning of the information column would be useful for that

**Comment by Eahlstan** [comment]
Why don't you use the search panel? That way you could easily make a list based on each type of hotspot.

E.g.
![Screenshot 2023-09-12 133152](https://github.com/EDDiscovery/EDDiscovery/assets/59618179/05f07308-56a8-4860-964f-0a364bd79b7e)

Would export this file:

[tritiumhs.csv](https://github.com/EDDiscovery/EDDiscovery/files/12585885/tritiumhs.csv)

Just search for each of the possible types to get a list of bodies having them.

Alexandrite
Benitoite
Bromellite
Grandidierite
LowTemperatureDiamond
Monazite
Musgravite
Opal
Platinum
Rhodplumsite
Serendibite
Tritium

(Hope I dind't miss one, I'm not a miner.)

**Comment by robbyxp1** [comment]
Answer made.
