### ISSUE TITLE
The Statistics tab does not seem to allow limiting of time

### ISSUE THREAD

**Issue by athulin** [EDDiscovery/EDDiscovery#3441]
When I run Statistics normally, I believe I get stats for the full set of journal files accessed by EDDiscovery: I see fines I paid some years ago, and one insurance claim from the same time.

When I try to limit statistics to a shorter time:

![image](https://github.com/EDDiscovery/EDDiscovery/assets/53051907/3787637d-1953-49b1-8ba6-34637492e570)

(looks like there's some localization going on in names of months) nothing changes: I still get the old fines and insurance claims as before.  I note that when I try the same for 'Organic Scans' it works fine, which is immediately visible from the lines shown.  

But for some reason it doesn't work for Statistics.

The page https://github.com/EDDiscovery/EDDiscovery/wiki/Using-the-Statistics-Panel gives no help: from it I get a strong impression that what I am trying should work.

I'm running latest EDDiscovery (16.2.0.0 according to About), newly reinstalled just in case, and also limited to not download anything from EDSM.

**Comment by Eahlstan** [comment]
Please screenshot the whole panel, nothing can be said with just the part you showed.

**Comment by athulin** [comment]
OK.  You're right -- that seems relevant.  The relevant tab -- that is, the one I was referring to for statistics -- is 'In Game':

![image](https://github.com/EDDiscovery/EDDiscovery/assets/53051907/64210e09-1e4c-43fa-8c6a-5879ad7dee65)

When I look at other tabs, such as this:

![image](https://github.com/EDDiscovery/EDDiscovery/assets/53051907/02609ad3-3931-4244-8d9b-66bc19037df4)

It does change, when the start datum is disabled:

![image](https://github.com/EDDiscovery/EDDiscovery/assets/53051907/37453b20-90f2-409e-8a76-97efc7b18a8f)

I expected the 'In Game' tab to behave the same way.

...  But it now strikes me that the In Game-info looks like it may be this account infodump that ED adds to every log file, and so not directly relevant to filter on time, except to say from which date/time log file it should be taken from? Yes, I now see the help page says it does ... 

OK, so not the problem I thought it was.  I thought it would do something more like Start infodump data 'subtracted' from To info dump, i.e. where something like Exploration / Systems Visited, Profits, ... (for example) is only for the selected time, as if the account had been 'reset' to 0 at the start date/time. 

Suggestion 1: A 'copy to clipboard' for 'In Game' (for all lines, all lines in selected node or selected leafs ) would help in extracting info (for those won't grapple with journal files)

Suggestion 2: An 'export to excel' for In Game fields, from start date and end date would allow the user to do such and other post processing himself. Requires both dates to be checked.  Otherwise, export only the checked one, if any.

Now that I think I know what I misunderstood, I can probably finagle the data I want directly from the journal files instead.

Feel free to close as misunderstanding, or treat as suggestion for future as seems best.

**Comment by Eahlstan** [comment]
You can copy it from the History (or Journal) panel. Just right click at the "Statistics" event from your desired date and click "Copy journal entry to clipboard/Log". Or double click the event to open a formatted version you can manually copy.

**Comment by Eahlstan** [comment]
Closing as completed.
