### ISSUE TITLE
[Linux] UI exception

### ISSUE THREAD

**Issue by S-K-Tiger** [EDDiscovery/EDDiscovery#3442]
### Description

Attempting to move entries of my CMDR linked to my old name to the new name.

### Additional Information

OS: Linux Mint 21.2 Cinnamon

### Exception Details:
>EDDiscovery v16.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidCastException: Specified cast is not valid.
>  at ExtendedControls.ExtPanelDataGridViewScroll.Wheel (System.Object sender, System.Windows.Forms.MouseEventArgs e) [0x0005c] in /home/lars/EDDiscovery/ExtendedControls/ExtendedControls/Controls/PanelDataGridViewScroll.cs:295 
>  at System.Windows.Forms.Control.OnMouseWheel (System.Windows.Forms.MouseEventArgs e) [0x00019] in <25c2bdf9d79a43a599eb46bd15cd77fb>:0 
>  at System.Windows.Forms.DataGridView.OnMouseWheel (System.Windows.Forms.MouseEventArgs e) [0x00000] in <25c2bdf9d79a43a599eb46bd15cd77fb>:0 
>  at System.Windows.Forms.Control.WmMouseWheel (System.Windows.Forms.Message& m) [0x0005a] in <25c2bdf9d79a43a599eb46bd15cd77fb>:0 
>  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x00204] in <25c2bdf9d79a43a599eb46bd15cd77fb>:0 
>  at System.Windows.Forms.DataGridView.WndProc (System.Windows.Forms.Message& m) [0x00000] in <25c2bdf9d79a43a599eb46bd15cd77fb>:0 
>  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <25c2bdf9d79a43a599eb46bd15cd77fb>:0 
>  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <25c2bdf9d79a43a599eb46bd15cd77fb>:0 
>  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00085] in <25c2bdf9d79a43a599eb46bd15cd77fb>:0 
>===== END =====
>```

**Comment by robbyxp1** [comment]
This is a mono issue, as the cast works in windows, as per the comment.  All we probably can do is to check if the event actually is HandledMouseEventArgs, to screen out the error.  But that means its not cancelling the event.

**Comment by klightspeed** [comment]
Instead of assuming that the passed `MouseEventArgs` is in fact a `HandledMouseEventArgs`:
```cs
                ((HandledMouseEventArgs)e).Handled = true;      // we are actually passed this class, cast to it and set we handled it.
```
perhaps it should check if it's actually the specified type:
```cs
                if (e is HandledMouseEventArgs ha)
                    ha.Handled = true;
```

**Comment by robbyxp1** [comment]
I've done that in my local copy, thanks.  I think I put the code in to prevent double scrolling of the panel due to wheel action, so no idea what it will do.

Be in next major version, out soon
