### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Jibsman** [EDDiscovery/EDDiscovery#3444]
Is player's personal equipment saved / shown somewhere?
I had some incorrect suits/equipment in Inara, deleted them, uploaded data from EDD and still no change there.
Just curious

**Comment by Eahlstan** [comment]
https://github.com/EDDiscovery/EDDiscovery/wiki/Using-the-Suits-and-Weapons-Panel
https://github.com/EDDiscovery/EDDiscovery/wiki/Using-the-Micro-Resources-Panel

Maybe?

**Comment by robbyxp1** [comment]
Answered
