### ISSUE TITLE
Feature Request since EDDB is gone

### ISSUE THREAD

**Issue by Jibsman** [EDDiscovery/EDDiscovery#3445]
Just a thought...

The app stores market prices, and if you select a station in History then look at Commodities you can see the prices at the time you were at that station (If I understand it correctly).

If you could display the latest price for each item in the db (I assume it's internal per pilot?) with a date somewhere I could at least see the historical prices for items at that time the data was collected. You could add a range - don't show prices for items over x days old.

Cheers

**Comment by robbyxp1** [comment]
The market data panel https://github.com/EDDiscovery/EDDiscovery/wiki/Using-the-Market-Data-Panel shows the commodities values that were found at your previous station (you need either use CAPI or visit the market to get Elite to log it).

EDD does not replicate the functionality of web sites in knowing the prices of other stations.  It has no way of knowing.

EDDB functionality has mostly been replicated by Inara https://inara.cz/elite/commodities/ and by Spansh https://www.spansh.co.uk/station/3534390016#station-market
