### ISSUE TITLE
Autoscanned body does not get entered in EDDiscovery history

### ISSUE THREAD

**Issue by athulin** [EDDiscovery/EDDiscovery#3446]
Body: Pencil Sector AA-Y b1-4 1

I visited this system some time ago, and did a fairly normal FSS, look for life signals, scan any found as well as rings, and move on routine.  I've just dragged up the body from my logs as one that has been autoscanned but for which no FSS scan ('Detailed') has been performed.  But when I checked my EDDiscovery history for this body, I can't find it at all.  (I find body 3 and later, though, which was not autoscanned. body 2 is another missing autoscanned entry.)

My Journal logs contain only single entry for this body:

`{ "timestamp":"2023-07-23T06:59:39Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Pencil Sector AA-Y b1-4 1", "BodyID":7, "Parents":[ {"Star":0} ], "StarSystem":"Pencil Sector AA-Y b1-4", "SystemAddress":9478590440833, "DistanceFromArrivalLS":7.439143, "TidalLock":true, "TerraformState":"", "PlanetClass":"High metal content body", "Atmosphere":"hot thick carbon dioxide atmosphere", "AtmosphereType":"CarbonDioxide", "AtmosphereComposition":[ { "Name":"CarbonDioxide", "Percent":55.505459 }, { "Name":"SulphurDioxide", "Percent":44.485737 } ], "Volcanism":"metallic magma volcanism", "MassEM":1.565679, "Radius":6941931.500000, "SurfaceGravity":12.949453, "SurfaceTemperature":1376.517700, "SurfacePressure":539676.000000, "Landable":false, "Composition":{ "Ice":0.000000, "Rock":0.670694, "Metal":0.329306 }, "SemiMajorAxis":2230198502.540588, "Eccentricity":0.000004, "OrbitalInclination":0.001047, "Periapsis":116.598501, "OrbitalPeriod":97987.502813, "AscendingNode":49.026487, "MeanAnomaly":268.157936, "RotationPeriod":98526.810800, "AxialTilt":0.335952, "WasDiscovered":true, "WasMapped":false }
`
It's not alone: I have at least half a dozen further bodies that I find in my logs as 'autoscanned but not FSS/detail-scanned' and for which I don't find any info in EDDiscovery either.

Is this intentional, or have I stumbled on a problem? 

(The reason I looked for this body in EDDiscovery was to see if I could use EDDiscovery searches of my history to check my own attempts with grep/jq, and perhaps even get faster searches done that way.) 

I have the latest EDDiscovery. I run it locally, without any db content downloaded. 
The body is on EDSM -- as far as I can see from the uploads done by EDMC.  

Let me know if you need any more info.

**Comment by Eahlstan** [comment]
Sounds like you unticked the event.

![Screenshot 2023-10-13 000905](https://github.com/EDDiscovery/EDDiscovery/assets/59618179/f33ee017-8b6c-4f83-b2c2-7b30dfb536cc)

**Comment by athulin** [comment]
I should probably have added that the  'Filter out entries based on event type' menu in History tab is unchanged from default installation: it has 'All' checked -- which as far as I can make out includes everything from 'Afmu repairs' to 'Won a Trophy ...'  I've unchecked it (by checking Scan), and then rechecked it back again just in case, but with no difference in behaviour.  I find no 'Autoscan' entry, so unless Autoscans hide in some other ways, there nothing in that menu that filters them away.

I do have Autoscan entries visible for other systems/bodies (searched for 'autoscan'), just not for the system I've mentioned.

I have tried adding a test.log file to the journal file directory with the single missing autoscan entry, in case there is a problem with the original Journal file, but without any obvious change ... I can't find any obvious record that the file is read at all, or any obvious error messages during reloading journals.

**Comment by robbyxp1** [comment]
Try opening a history window in a popout and see if it appears.  That will be a fresh version of the window with as default settings.

Ensure the scan you have seen missing is for the same commander as well if you run multiple commanders

**Comment by Eahlstan** [comment]
Please provide the full journal file from that session.

**Comment by athulin** [comment]
History in popout -- no change, still not visible

Full journal file -- see attachment.
[Journal.2023-07-23T085421.01.log](https://github.com/EDDiscovery/EDDiscovery/files/12891321/Journal.2023-07-23T085421.01.log)

**Comment by Eahlstan** [comment]
Until I'm at the PC to check it you can try doing a reread all. I think that's in the admin menu at the top.

**Comment by athulin** [comment]
Re-scan all -- tried. No change.

I should perhaps also say, that I'm not in a hurry over this.  I can do without EDDiscovery on this, so if you have more important things, that's OK.  It was just an odd thing that I thought I'd better report ...

**Comment by Eahlstan** [comment]
Looks fine to me.

![Screenshot 2023-10-13 113040](https://github.com/EDDiscovery/EDDiscovery/assets/59618179/f7f512f8-c4be-4758-8e9b-20499c2103b3)

Please screenshot the menu I screenshoted and the menu next to it.
Also please see if it's in the Journal panel.

**Comment by athulin** [comment]
Interesting.  I don't see the same entries as you have.  

History, with search for 'Pencil Sector AA-Y b1-4':
![history-with-partial-search-1](https://github.com/EDDiscovery/EDDiscovery/assets/53051907/0918a7e2-ff0a-4e1f-9906-d02cd5edf567)
![history-with-partial-search-2](https://github.com/EDDiscovery/EDDiscovery/assets/53051907/baf8d333-fb05-49fa-aa82-8a496400f73f)


History with search for body 'Pencil Sector AA-Y b1-4 1':
![history-with-full-search](https://github.com/EDDiscovery/EDDiscovery/assets/53051907/9c016a57-a8ed-4e92-940a-dc6cc11de67e)


Filter menus:
![Filter1-1](https://github.com/EDDiscovery/EDDiscovery/assets/53051907/5e06e5e2-f373-4a2a-80f2-75f512b6567f)
![Filter1-2](https://github.com/EDDiscovery/EDDiscovery/assets/53051907/a293bb71-cb48-44ee-b3d0-2697c4348861)
![Filter1-3](https://github.com/EDDiscovery/EDDiscovery/assets/53051907/63f81e5a-2087-4906-a2ed-4cfcacbb0699)
![Filter2](https://github.com/EDDiscovery/EDDiscovery/assets/53051907/39a1aea4-c0c2-4495-a6fd-3c2c27060b56)

Journal tab behaves much the same as the History tab: I see entries related to the system, but nothing related to body 1.

When I started doing the Pencil Sector scans, I uninstalled my old EDDiscovery, which downloaded the full galaxy, and instead installed a default, with no downloads at all, and no database at all.  I assume the uninstalled cleaned up everything, and that there are no registry stuff left from the older installation.

**Comment by Eahlstan** [comment]
Yeah. You're using the search bar wrong.
If you want to see all entries from a specific system use
system:"systemname"

[quote]Search text box. You can filter events by if they contain this bit of text (any Column). From 15.0 you can also use station:wildcard, stationfaction:wildcard, system:wildcard or body:wildcard to filter on on entries occurring at a specific place. Quote the wildcard if it has spaces in it.[/quote]

https://github.com/EDDiscovery/EDDiscovery/wiki/Using-the-History-Grid-Panel

**Comment by athulin** [comment]
Well, yes, I had read that piece of text, but it seems I must have misinterpreted.

It says:  'filter events by if they contain this piece of text'.   All the events (by which I mean journal log entries) do contain that piece of text in their BodyName.

Should it rather have said "filter events by if they are displayed with this piece of text in the history table"?  Because that seems to be what matters:  it is not if the events contain the text, but if the search string happens to be displayed with that string.   

Oh well, not a bug, just behaviour that violates the principle of least astonishment.
Closed as far as I am concerned.

**Comment by Eahlstan** [comment]
If you take a look at the autoscan event "Autoscan of 1" there's no "Pencil Sector AA-Y b1-4" in the description field or in the information field.
It's about the displayed text, not about what's in the raw event. If you want to search for bodies with a name that contains it you can use the search panel.

![Screenshot 2023-10-13 154801](https://github.com/EDDiscovery/EDDiscovery/assets/59618179/4a01a76d-e80d-4b0a-a59d-f786b8c5ff92)
