### ISSUE TITLE
Failure to send approach settlement event to EDDN

### ISSUE THREAD

**Issue by WarmedxMints** [EDDiscovery/EDDiscovery#3448]
As FDEV has now decided to include previously omitted information about the station in the approach settlement event, EDDN is now rejecting the data sent by EDD.   Ideally, EDDN could do with updating but in case it is not I thought I would let you know.

**Comment by klightspeed** [comment]
Thankyou - this is known about, and an update to EDDN (https://github.com/EDCD/EDDN/pull/215) is pending.
