### ISSUE TITLE
Unhandled exception  

### ISSUE THREAD

**Issue by TonyFlury** [EDDiscovery/EDDiscovery#3451]
### Description
The following unhandled UI exception occurred after my PC woke up : 

### Exception Details:
>EDDiscovery v16.2.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>OpenTK.Graphics.GraphicsContextException: Failed to make context 65537 current. Error: 0
>   at OpenTK.Platform.Windows.WinGLContext.MakeCurrent(IWindowInfo window) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Platform\Windows\WinGLContext.cs:line 279
>   at EDDiscovery.UserControls.UserControl3DMap.SystemTick(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\UserControl3DMap.cs:line 109
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by Eahlstan** [comment]
Thanks for the report.
Sadly that's a known issue and there's not much we can do about it. OpenGL really dislikes sleeping PCs, so the only viable solution is to close the 3D map before abandoning the PC.

**Comment by TonyFlury** [comment]
The 3D map was not open in this case - in fact i rarely use the 3D map.

**Comment by Eahlstan** [comment]
See my comment in your new issue.
