### ISSUE TITLE
Trilateration Panel Current Location

### ISSUE THREAD

**Issue by brownhr** [EDDiscovery/EDDiscovery#3452]
Currently, the Trilateration Panel only updates the current location when making an actual FSD jump. I would like for it to also update when the current location is updated either from a Fleet Carrier jump, or by quitting to the main menu.

The time between carrier jumps is a good opportunity to enter distances, but I currently have to undock, leave the system, re-enter the system, and re-dock in order to update the current location, which is not only time consuming and tedious, but adds a risk of missing a carrier jump should the game crash or if I need to step away. This is especially an issue if I'm being ferried on a carrier I can't control.

I'd like to request the Trilateration panel's current location be more synced with the actual current location, rather than the most recent FSD jump.

Thank you for all the hard work on a great tool!

**Comment by klightspeed** [comment]
Maybe `GetLastFSDOnly()` should be changed to `GetLastHistoryEntry(e => e.IsLocOrJump)`

**Comment by Eahlstan** [comment]
Or `GetLastFSDOnly()` should be changed. It's just used in the Trilateration panel, so it would do no harm to make it get locations from different events.

Something like

```public HistoryEntry GetLastLocation() { return historylist.FindLast(x => (x.EntryType == JournalTypeEnum.FSDJump || x.EntryType == JournalTypeEnum.CarrierJump || x.EntryType == JournalTypeEnum.Location)); }```

**Comment by robbyxp1** [comment]
Ok going to execute this for 17.0.1 thanks
