### ISSUE TITLE
Crash when System screen lock comes on

### ISSUE THREAD

**Issue by TonyFlury** [EDDiscovery/EDDiscovery#3453]
### Description
The screen lock turned on as i took a pause when playing.

### Exception Details:
>EDDiscovery v16.2.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>OpenTK.Graphics.GraphicsContextException: Failed to make context 65537 current. Error: 0
>   at OpenTK.Platform.Windows.WinGLContext.MakeCurrent(IWindowInfo window) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Platform\Windows\WinGLContext.cs:line 279
>   at EDDiscovery.UserControls.UserControl3DMap.SystemTick(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\UserControl3DMap.cs:line 109
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by TonyFlury** [comment]
Note : EDDiscovery was in the background throughout my entire play session, simply uploading data to INara and EDSM - I have not used the 3DMap although it was on a tab (but not the current tab).

**Comment by Eahlstan** [comment]
It doesn't matter if it's the active tab or not. As long as the 3D map is opened in any way OpenGL is active.
OpenGL is allergic to any form of Windows inactivity, so close it before you're going absent.

**Comment by robbyxp1** [comment]
See https://github.com/EDDiscovery/EDDiscovery/issues/3271
