### ISSUE TITLE
Disable IGAU Data Uploads

### ISSUE THREAD

**Issue by Elite-IGAU** [EDDiscovery/EDDiscovery#3460]
Since EDDN and EDSM now carry codex data, it's no longer necessary for IGAU to collect or publish codex dumps. 
Codex data is also contained in the Spansh dumps, although at this time, they've still not provided a separate codex data dump file. 

https://www.edsm.net/dump/codex.json.gz

https://www.spansh.co.uk/dumps

Please disable the "Intergalactic Astronomical Union" feature in Settings -> Commanders -> Journal Related Information -> IGAU
If needed you can confirm this request over at IGAU'S discord, which @robbyxp1 is a member of. 

Thank you!

**Comment by Eahlstan** [comment]
Not like I told you guys "a new release is coming soon, so please talk to Robby asap" 24 days ago.

Any reason I was ignored?

**Comment by robbyxp1** [comment]
Done for 17.0.1
