### ISSUE TITLE
Gas Giant Star missing in History

### ISSUE THREAD

**Issue by Deamawa** [EDDiscovery/EDDiscovery#3463]
![EDDiscovery Version 17 0 1 0 12 01 2024 14_46_47 - Kopie](https://github.com/EDDiscovery/EDDiscovery/assets/27950801/bee0ff38-c173-4021-b917-61aa71399506)
![EDDiscovery Version 17 0 1 0 12 01 2024 14_47_29](https://github.com/EDDiscovery/EDDiscovery/assets/27950801/b767ae7f-3f57-45ed-b198-5d838ca4cac3)
![EDDiscovery Version 17 0 1 0 12 01 2024 14_47_08 - Kopie](https://github.com/EDDiscovery/EDDiscovery/assets/27950801/1389b577-0ce4-450a-83b4-ff9c3e75d902)

Pictures are selfexplantory. Do I something wrong?

**Comment by Eahlstan** [comment]
Can you please upload the journal from that session?

shell:SavedGames\Frontier Developments\Elite Dangerous

Also: Even though it's self explanatory it's quite difficult to see it when it's buried in all those info presented, so for future happenings: Please always write it down too.

**Comment by Deamawa** [comment]
[Journal.2024-01-12T134601.01.log](https://github.com/EDDiscovery/EDDiscovery/files/13920277/Journal.2024-01-12T134601.01.log)

Sorry. I didn`t know that. I`ll do next time.

**Comment by Eahlstan** [comment]
I am completely unable to reproduce this. Does it look the same after restarting EDD?

**Comment by Deamawa** [comment]
After I restart EDD alll  Gas Giants are present, Thank you and your fine program. Your my Idol in this game. :)

**Comment by Eahlstan** [comment]
Very strange.
Please report if this happens again, right now I don't see any way for this to happen so I'll remember it, but will note it down as a strange hickup.

**Comment by Deamawa** [comment]
I will do
![EDDiscovery Version 17 0 1 0 12 01 2024 15_57_43](https://github.com/EDDiscovery/EDDiscovery/assets/27950801/b1ce832e-2264-47f2-b4cf-7dec1e01ad9a)
