### ISSUE TITLE
Error while trying to "Send to Inara Historic Data"

### ISSUE THREAD

**Issue by Retr0MrWave** [EDDiscovery/EDDiscovery#3465]
### Description

The regular sync with inara works fine, I think, ecause in the log it periodically says "[Inara] Data sent succesfully" and new data does show up on inara itself, but when I try the Admin>Send to Inara Historic Data button I get an exception. After that pressing continue makes the app still run normally

### Exception Details:
>EDDiscovery v17.0.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.Inara.InaraSync.HistoricList(HistoryList history) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\InaraSync.cs:line 123
>   at EliteDangerousCore.Inara.InaraSync.HistoricData(Action`1 logger, HistoryList history, EDCommander cmdr) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\InaraSync.cs:line 60
>   at EDDiscovery.EDDiscoveryForm.sendHistoricDataToInaraToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDD\EDDiscoveryForm.cs:line 1050
>   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
I just ran this, and it imported the ship list without an error.

Do you have any journals in EDD?  I'm presuming you do.  Looking at historiclist function is appears to be protected against no history or empty ship list.

**Comment by Retr0MrWave** [comment]
Well I just tried again and it just worked. I'm sorry this isn't useful for debugging this issue but unless there's some sort of internal logs which can explain what changed, I don't think I can provide any more details to the issue. But it was, probably, like you've stated, an issue with missing journals as I did run the game between trying
