### ISSUE TITLE
Gas Giant orbiting center of 2 stars not added to graphical display

### ISSUE THREAD

**Issue by FSFan** [EDDiscovery/EDDiscovery#3467]
Like it says.  Journal shows it.  Not 100% sure I can add a graphic here but will try my screen shot.
![no gas](https://github.com/EDDiscovery/EDDiscovery/assets/4210521/da8317c5-d7bf-4648-92d6-b9a527da5143)

**Comment by FSFan** [comment]
As you can see there is no graphical representation of the gas giant showing anywhere in the listing.  It should be between the 2 stars since it orbits the center of mass of the 2.  Fyi

**Comment by Eahlstan** [comment]
Does this fix itself upon restart?

**Comment by robbyxp1** [comment]
I played the file thru and it worked. No idea at this point.

**Comment by robbyxp1** [comment]
Closing, we can't find the bug at this point, but will keep it in mind
