### ISSUE TITLE
Unhandled fatal exception when starting EDDiscovery

### ISSUE THREAD

**Issue by dominuxdede** [EDDiscovery/EDDiscovery#3468]
code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked.
After the message has been displayed the application closes. But it can be reopened without the error message.
Version 17.0.1.0

**Comment by robbyxp1** [comment]
An experimental fix for this will be along in 17.0.2, out prob next week. In the meanwhile, ignore it and restart.  thanks
