### ISSUE TITLE
Unhandled Exception While Removing a Tab

### ISSUE THREAD

**Issue by kc9eye** [EDDiscovery/EDDiscovery#3470]
### Description

Removing a tab from the main screen.

### Exception Details:
>EDDiscovery v17.0.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: No row can be added to a DataGridView control that does not have columns. Columns must be added first.
>   at System.Windows.Forms.DataGridViewRowCollection.Add(DataGridViewRow dataGridViewRow)
>   at EDDiscovery.UserControls.Helpers.SpanshStationsUserControl.Draw(Boolean removesort) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\SpanshStationsUserControl.cs:line 277
>   at EDDiscovery.UserControls.Helpers.SpanshStationsUserControl.<DrawSystem>d__14.MoveNext() in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\SpanshStationsUserControl.cs:line 164
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by Eahlstan** [comment]
Can you please elaborate how you did this? What did the Spansh station panel display at that time? What did you click? etc.

**Comment by kc9eye** [comment]
I added the tab to see what it would display, I then right clicked the tab title and then clicked remove tab. That is all.

“Simplicity is the ultimate sophistication.”
- Clare Boothe Luce
________________________________

**Comment by robbyxp1** [comment]
Its probably due to the Await.. i'll defend more deeply

**Comment by robbyxp1** [comment]
Thanks for the report. will be defended against in 17.0.2
