### ISSUE TITLE
Constand "Unhandled UI Exception" error while using the Mining Overlay

### ISSUE THREAD

**Issue by SgtEpsilon** [EDDiscovery/EDDiscovery#3471]
I've been using the Mining Overlay and Compass Overlay and i keep getting this error show up for the mining overlay
### Exception Details:
>EDDiscovery v17.0.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentException: Height must be greater than 0px.
>   at System.Windows.Forms.DataVisualization.Charting.ChartPicture.InspectChartDimensions(Int32 width, Int32 height)
>   at System.Windows.Forms.DataVisualization.Charting.ChartPicture.set_Height(Int32 value)
>   at System.Windows.Forms.DataVisualization.Charting.Chart.OnResize(EventArgs e)
>   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
>   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
>   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
>   at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
>   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(Rectangle bounds, BoundsSpecified specified)
>   at System.Windows.Forms.Layout.DefaultLayout.xLayoutDockedControl(IArrangedElement element, Rectangle newElementBounds, Boolean measureOnly, Size& preferredSize, Rectangle& remainingBounds)
>   at System.Windows.Forms.Layout.DefaultLayout.LayoutDockedControls(IArrangedElement container, Boolean measureOnly)
>   at System.Windows.Forms.Layout.DefaultLayout.xLayout(IArrangedElement container, Boolean measureOnly, Size& preferredSize)
>   at System.Windows.Forms.Layout.DefaultLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
>   at System.Windows.Forms.Layout.LayoutEngine.Layout(Object container, LayoutEventArgs layoutEventArgs)
>   at System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
>   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
>   at System.Windows.Forms.Control.ControlCollection.SetChildIndexInternal(Control child, Int32 newIndex)
>   at EDDiscovery.UserControls.UserControlMiningOverlay.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlMiningOverlay.cs:line 533
>   at EDDiscovery.UserControls.UserControlMiningOverlay.Display(HistoryEntry he) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlMiningOverlay.cs:line 160
>   at EDDiscovery.UserControls.UserControlCommonBase.PerformPanelOperation(UserControlCommonBase sender, Object actionobj) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlCommonBase.cs:line 236
>   at EDDiscovery.UserControls.UserControlContainerGrid.PerformPanelOperation(UserControlCommonBase sender, Object actionobj) in C:\Code\EDDiscovery\EDDiscovery\UserControls\GridsSplitters\UserControlContainerGrid.cs:line 295
>   at EDDiscovery.MajorTabControl.RequestPanelOperationPrimary(UserControlCommonBase sender, Object actionobj) in C:\Code\EDDiscovery\EDDiscovery\TabsPanelsAndPopOuts\MajorTabControl.cs:line 350
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 599
>   at EDDiscovery.UserControls.UserControlTravelGrid.AddEntry(HistoryEntry he) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 437
>===== END =====
>```

**Comment by Eahlstan** [comment]
Please try resetting your window positions by using the [safe mode menu](https://github.com/EDDiscovery/EDDiscovery/wiki/Safe-Mode).

**Comment by SgtEpsilon** [comment]
Just occured to me, do you think using Fancy Zones from the Windows PowerToys toolbox would cause this error?

**Comment by Eahlstan** [comment]
> Just occured to me, do you think using Fancy Zones from the Windows PowerToys toolbox would cause this error?

This is definitely possible, and extremely easy to test by just not using it for a try.

**Comment by SgtEpsilon** [comment]
I completely forgot i had it turned on until after i posted this when i accidentally hit the activation key

**Comment by robbyxp1** [comment]
I've seen this in the past, but its v.hard to repo.  For me, adjusting the screen size (and therefore the chart size) in both an pop out and inside a tab does not produce any exceptions.  Adding a chart with height 0 also does not except.

No idea how this is triggered, but its super rare.

**Comment by robbyxp1** [comment]
I will cover the error up - if it happens, resize the window, close it and restart.
