### ISSUE TITLE
The app crashes when I open it

### ISSUE THREAD

**Issue by Harryb18** [EDDiscovery/EDDiscovery#3473]
An unhandled fatal exception has occurred.

==== BEGIN ====
code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   en System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   en System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   en System.Data.SQLite.SQLiteDataReader.NextResult()
   en System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   en System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   en System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   en System.Data.SQLite.SQLiteConnection.Open()
   en SQLLiteExtensions.SQLExtConnection..ctor(String dbfile, Boolean utctimeindicator, AccessMode mode, JournalModes journalmode, Boolean disallow_xthreading) en C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnection.cs:línea 67
   en EliteDangerousCore.DB.SystemsDatabase.CreateConnection() en C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDatabase.cs:línea 56
   en SQLLiteExtensions.SQLAdvProcessingThread`1.SqlThreadProc() en C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:línea 191
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
And 3464
