### ISSUE TITLE
An unhandled fatal exception has occurred.

### ISSUE THREAD

**Issue by flxln** [EDDiscovery/EDDiscovery#3474]
An unhandled fatal exception has occurred.

==== BEGIN ====
code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   bei System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   bei System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   bei System.Data.SQLite.SQLiteDataReader.NextResult()
   bei System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   bei System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   bei System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   bei System.Data.SQLite.SQLiteConnection.Open()
   bei SQLLiteExtensions.SQLExtConnection..ctor(String dbfile, Boolean utctimeindicator, AccessMode mode, JournalModes journalmode, Boolean disallow_xthreading) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnection.cs:Zeile 67.
   bei EliteDangerousCore.DB.SystemsDatabase.CreateConnection() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDatabase.cs:Zeile 56.
   bei SQLLiteExtensions.SQLAdvProcessingThread`1.SqlThreadProc() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:Zeile 191.
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
New version out today which will hopefully solve this. Thanks for the report. Just restart and its most likely will not happen
