### ISSUE TITLE
Enhancement: Market Data panel and Demand information.

### ISSUE THREAD

**Issue by Jugom** [EDDiscovery/EDDiscovery#3476]
In the Market Data panel, when you have a single station marked, it shows correctly the demand, but if you have a second station selected, as you do when you are looking for what commodities you can trade between stations, there is no information about the demand in the target station, which is important when you are deciding what commodity to trade with since arriving to a station with more commodities than they have demand for or 0 demand for can alter the price they will offer and also has other repercussions BGS wise.

as you can see in this image, not only it doesn't show the demand at the target station, but also -for whatever reason- overrides and removes the demand at the buying station.
![image](https://github.com/EDDiscovery/EDDiscovery/assets/74990247/770667e2-fe7a-4948-9640-179b538d0d5b)

additionally, for the enhancement part, I'd like to request if possible also adding the information about the type of demand in the station, represented by the 'signal bars' that show in-game next to it.
![image](https://github.com/EDDiscovery/EDDiscovery/assets/74990247/60230f75-2b95-4275-acea-d0ab07e26e44)

cheers

**Comment by robbyxp1** [comment]
Noted, will investigate

**Comment by robbyxp1** [comment]
Moved to worklist. The graphic may not be possible, as i'm not going to give a column up to it, and it still needs to sort so it still needs to be a text column.

**Comment by Jugom** [comment]
I imagined it could be something like: 12345 (+++)
