### ISSUE TITLE
Remember user data location 

### ISSUE THREAD

**Issue by wbovela** [EDDiscovery/EDDiscovery#3477]
When updating an existing installation using the installer, a previously used installation location for the user data should be remembered. Currently that location defaults to a location on the C: drive under AppData. While this may seem a wise choice due to user rights, storing large quantities of data on the system drive isn't desirable. Having stored my user data in a different location (and on a different drive) I would prefer to have the installer suggest that location for storing user data again.

**Comment by klightspeed** [comment]
Looking at the innoscript install script, it looks like the installer only honours the previous data directory if the install directory does not contain "Program Files" - e.g. installing in `F:\Programs\EDDiscovery` has it honouring the previous install data directory, while installing in `F:\Program Files\EDDiscovery` does not honour the previous install data directory.

**Comment by robbyxp1** [comment]
This was by design, its not a bug yet, i'll have to remember why i designed it this way.

**Comment by wbovela** [comment]
Please note I'm talking about user data location, not the program executable

**Comment by Eahlstan** [comment]
> This was by design, its not a bug yet, i'll have to remember why i designed it this way and retest it.

I think it was because %programfiles% is write protected folder that can be on any drive (not just c: ) and excluding it on every drive might have been the most error proof way to prevent users from using a directory that wouldn't work.

**Comment by robbyxp1** [comment]
Going to leave the script alone for now. Do not want to change the script for this use case. Thanks for the report.
