### ISSUE TITLE
crash in search tab

### ISSUE THREAD

**Issue by rocknrollbetty** [EDDiscovery/EDDiscovery#3478]
### Description

used search tab, materials / commodities,  to search on 2 materials (or). right click over one of the entries in results, select 'go to entry on grid' in popup - eddi crashes. every time.

### Additional Information

![Screen Shot 02-06-24 at 09 28 PM](https://github.com/EDDiscovery/EDDiscovery/assets/46960073/907290a8-310e-42ba-aede-ca40d711666b)

### Exception Details:
>EDDiscovery v17.0.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.SearchMaterialsCommodities.<Init>b__5_2(HistoryEntry he) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Search\SearchMaterialsCommodities.cs:line 78
>   at EDDiscovery.UserControls.Search.DataGridViewStarResults.GotoEntryToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\DataGridViewStarResults.cs:line 141
>   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by Eahlstan** [comment]
Confirmed.
Thanks for the report and the detailed reproduction steps.

**Comment by robbyxp1** [comment]
Thanks for the report, we have fixed it on our code base, and it will be fixed in the next point release.
