### ISSUE TITLE
Out of Memory Exception Adding system to Exploration 

### ISSUE THREAD

**Issue by gathooed** [EDDiscovery/EDDiscovery#3479]
### Exception Details:
>EDDiscovery v17.0.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.TypeInitializationException: Der Typeninitialisierer für "System.Drawing.Brushes" hat eine Ausnahme verursacht. ---> System.OutOfMemoryException: Eine Ausnahme vom Typ "System.OutOfMemoryException" wurde ausgelöst.
>   bei System.Drawing.Brushes..cctor()
>   --- Ende der internen Ausnahmestapelüberwachung ---
>   bei System.Drawing.Brushes.get_White()
>   bei System.Windows.Forms.Control.PaintException(PaintEventArgs e)
>   bei System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
>   bei System.Windows.Forms.Control.WmPaint(Message& m)
>   bei System.Windows.Forms.Control.WndProc(Message& m)
>   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
The fact that `PaintException` is called suggests that an exception was thrown while attempting to paint (probably also an `OutOfMemoryException`)

What were you doing when this out of memory error occurred?

Would it please be possible to get the Trace log for this session from `%LOCALAPPDATA%\EDDiscovery\Log` so we can potentially determine what caused this out of memory error?

**Comment by robbyxp1** [comment]
We need much more info to be able to do anything

**Comment by gathooed** [comment]
I hope this is going to help.

btw. Error did not apear since then......

[Trace_2024-02-08-09-17-34.0.log](https://github.com/EDDiscovery/EDDiscovery/files/14219970/Trace_2024-02-08-09-17-34.0.log)
[Trace_2024-02-08-09-41-16.0.log](https://github.com/EDDiscovery/EDDiscovery/files/14219972/Trace_2024-02-08-09-41-16.0.log)

**Comment by Eahlstan** [comment]
Thanks. I removed the logs (after downloading them) for privacy and security reasons.

**Comment by klightspeed** [comment]
It's probably not it running as a 32-bit process as I'm guessing you're running it on the same computer as Elite Dangerous is running on, so given that it was able to bring up the unhandled UI exception dialog, and it was also still processing the `Status.json` in the background (without more out of memory errors), seems to suggest that dotnet got into a state where it could not allocate any memory in the main thread's heap while painting to a scroll bar.  An overall system out of memory condition would probably have led to more noticeable issues, including game crash.

**Comment by robbyxp1** [comment]
Are you running two EDDs at the same time? The logs seems to suggest it.

**Comment by robbyxp1** [comment]
We have concluded that its a one off due to some sort of upset. I've looked for GDI/User object leaks and can't see a gross one.  If it happens again, we can reopen it.
