### ISSUE TITLE
[Enhancement Request] Custom grouping for saved bookmarks.

### ISSUE THREAD

**Issue by Jugom** [EDDiscovery/EDDiscovery#3484]
Allow users to create custom categories to group Bookmarks together and allow them to filter by said categories.

As the bookmark list grows, it can get a bit messy, so it would be nice to group them by categories and be able to hide/show only what you want for example: Squadron/Mining/EarthLikes/Farming/Pretty/FunnyNames/WhateverComesToMind.

Right now, you can partially achieve this, using the search bar and a keyword in your bookmark description, but if you wanted to show more than 1 group, you wouldn't be able to. 

Additionally, and the main reason why I think categories would be nice to have. is the implementation in the 3D maps. Being able to use that same filter to hide/show only the bookmark grouping you want to, since right now, showing all your bookmarks, when they increase in number, it's almost impossible identify who is who among the cloud of green icons.

**Comment by robbyxp1** [comment]
See https://github.com/EDDiscovery/EDDiscovery/projects/3#card-91421504

Noted, moved to worklist
