### ISSUE TITLE
Unexpected crash on start

### ISSUE THREAD

**Issue by athulin** [EDDiscovery/EDDiscovery#3485]
Started up EDDiscovery (latest) and immediately got a crash message.  (see added screenshot)
![crash1](https://github.com/EDDiscovery/EDDiscovery/assets/53051907/6f4f4546-6c17-4036-89b7-5f0c91ac84e2)

I had a ED session running when it happened.  I don't use EDDiscovery to report logs, only for looking at and searching in log files.

Incidentally, the text in that crash dialog is incorrect.  It says: "Click the Report Issue button to copy diagnostic information to your clipboard"  but there's nothing in my clipboard when I arrived at this web site (hence the screen shot).  Let me know if there's anything static you need to know.  As nothing is mentioned in the crash dialog, I'm assuming there is nothing more.

On restart, everything worked as expected.

**Comment by klightspeed** [comment]
That looks like a race condition where multiple threads tried to access the not-yet initialized commanders list at the same time.

* Thread 1: !Commanders.ContainsKey(currentcommander)
* Thread 1: if (intcmdrdict == null)
* Thread 2: if (intcmdrdict == null)
* Thread 1: LoadCommanders();
* Thread 2: LoadCommanders(); // blocked by Thread 1
* Thread 1: return intcmdrdict
* Thread 2: enter LoadCommanders();
* Thread 1: ContainsKey returns false
* Thread 2: enter critical section on locker
* Thread 1: Commanders.Count > 0 is true
* Thread 2: intcmdrdict = new Dictionary<int, EDCommander>();
* Thread 1: currentcommander = Commanders.Values.First().Id; // Commanders is an empty dictionary

**Comment by robbyxp1** [comment]
I will refactor. thanks for the report.
