### ISSUE TITLE
Feature request: Make Voice Synthesis options saveable per voice and not global

### ISSUE THREAD

**Issue by MaxiM-PL** [EDDiscovery/EDDiscovery#3486]
Hello.

It's not an issue in a traditional sense, but many, many times the NPC voices from the voice pack are waaay overmodulated with low pitch like an eldritch monster. Is there a way, or a chance to implement some form of control over that? Right now it's way overboard and honestly I would like to disable it completely. That and the NPC voices and WAY louder than the assistant voice, so a separate volume control would be amazing. When I set the overall volume to comfortably hear the computer voice, the NPC want to blow my brains out sometimes. Well, most of the time.

One last thing - separate effects for NPCs and Assistant would be great. I like my assistant to sound computer-ish, but the NPCs with the same filter are just off.

The whole thing works great overall, kudos for that - but these minor issues drag the entire experience down a notch.

**Comment by robbyxp1** [comment]
I'll have to look into how complicated this would be. Thanks for the idea. Moving to worklist.

**Comment by MaxiM-PL** [comment]
Awesome to hear! Per voice would be a dream, but even just separate settings for assistant and NPCs would be more than enough. That way we could also make the assistant voice "computerized" like the ship's voice while keeping NPC voice comms without any filter or a different one, to differentiate them from the computer voice. Thanks for a quick response and again, amazing tool you've created here! Best 2nd screen companion for ED by miles.

**Comment by robbyxp1** [comment]
this will be coming in 17.1

**Comment by MaxiM-PL** [comment]
Amazing work my man, thank you! So far it behaves admirably. Kudos for your efforts! Hope more people will find this feature useful. Cheers!
