### ISSUE TITLE
Sync with EDSM after clearing all data

### ISSUE THREAD

**Issue by dymm2000** [EDDiscovery/EDDiscovery#3488]
I did clear all data (not account) on EDSM.
Then tried to sync again. Nothing helped - "send unsynced journals", "fetch logs again", "rescan all logs", uncheck and check sync to/from EDSM in cmdr settings, new API key. Only delete user db and recreate cmdr.

**Comment by Eahlstan** [comment]
Not an issue, working as intended.
There's no way to know what EDSM knows, so as logic dictates unsynced only checks if the events in the local DB were sent.

**Comment by dymm2000** [comment]
how to force reload all logs to EDSM without conditions?
