### ISSUE TITLE
Ramdom jumps when loading to EDSM

### ISSUE THREAD

**Issue by dymm2000** [EDDiscovery/EDDiscovery#3490]
I did folloing steps before:
-cleared all data on EDSM
-deleted user db and recreated cmdr from the scratch
Then EDD started to send logs to EDSM and random jumps appeared
EDD:
![1](https://github.com/EDDiscovery/EDDiscovery/assets/12236360/a7035437-0fdd-49fb-a328-190586d0d18e)
EDSM:
![2](https://github.com/EDDiscovery/EDDiscovery/assets/12236360/ec666eb0-c7d9-4b20-8b65-15db2e717e40)
Random jumps:
![3](https://github.com/EDDiscovery/EDDiscovery/assets/12236360/eee1361f-fec2-4ed1-8007-494862b8cdeb)

**Comment by dymm2000** [comment]
I will do again clear, import journals to EDSM directly and report here

**Comment by Eahlstan** [comment]
That's either an EDSM bug (not filtering multicrew or CQC events) or your events weren't finished syncing.
Not an EDD bug.
And given this all comes from you not reading the manual  (e.g. [how to properly delete commanders and journal entries](https://github.com/EDDiscovery/EDDiscovery/wiki/Safe-Mode) ) I suspect it's just another case of user error and not a bug.

**Comment by dymm2000** [comment]
You added information about deleting commanders in the safe mode just before answered to me:
![4](https://github.com/EDDiscovery/EDDiscovery/assets/12236360/7ab5482f-d8ec-4187-9e2b-8d96df70a953)

**Comment by Eahlstan** [comment]
[Remove all journals and keep the settings was there before I did that update](https://github.com/EDDiscovery/EDDiscovery/wiki/Safe-Mode/ea95e59bbde66cd5d0230938d8db5abf8c3dc510) [and before you opened your first issue were you stated the only solution is to delete the whole DB.](https://github.com/EDDiscovery/EDDiscovery/issues/3488)

Yes, I did update the page, but the needed information was there before and you would have seen it if you had read it.
