### ISSUE TITLE
Documents text file spam

### ISSUE THREAD

**Issue by Minecrafter8001** [EDDiscovery/EDDiscovery#3495]
Can you put the ship files used for the ship/loadout menu in a folder instead of just in documents? I have 168 files in my documents, all named something like "Anaconda.2024-02-22T14.55.29," and it's getting annoying.
![image](https://github.com/EDDiscovery/EDDiscovery/assets/133237713/8ab16d39-accc-42ca-8b5a-f30152e2b10c)

**Comment by Eahlstan** [comment]
What makes you think that this is something done by EDDiscovery?

**Comment by Minecrafter8001** [comment]
![image](https://github.com/EDDiscovery/EDDiscovery/assets/133237713/75f72f08-ea41-4c41-a9f6-f56b1aa1d5ea)

**Comment by Minecrafter8001** [comment]
after looking at the code i belive i found why
https://github.com/EDDiscovery/EDDiscovery/blob/b607f49397f2879e43d9a9635e03e6a8427b2f69/EDDiscovery/Forms/SafeModeForm.cs#L153

sorry for wasting your guys time

**Comment by Eahlstan** [comment]
I can guarantee that this is not done by EDDiscovery.
EDMC has such an option on the first page of its settings menu. You might want to make sure you're not running EDMC in the background with this export option enabled.

**Comment by klightspeed** [comment]
Indeed, if the EDMC output directory is set to your Documents directory, and its export option is enabled, then it will create exactly these files.
<https://github.com/EDCD/EDMarketConnector/blob/5419e2e47f30c4dbcfc22b53308187d0c033d286/monitor.py#L2226-L2308>

**Comment by Minecrafter8001** [comment]
yup it was EDMC thanks
