### ISSUE TITLE
Crashing when opening 3D map (Due to very old Graphics Card not supporting OpenGL 4.6)

### ISSUE THREAD

**Issue by BB-MBS** [EDDiscovery/EDDiscovery#3498]
There was an unhandled UI exception.

```
==== BEGIN ====
System.InvalidCastException: Specified cast is not valid.
   at GLOFC.GL4.Shaders.GLShaderPipeline.GetShader[T]()
   at EDDiscovery.UserControls.Map3D.GalaxyStars.SetAutoScale(Int32 max) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\GalaxyStars.cs:line 55
   at EDDiscovery.UserControls.Map3D.GalaxyStars.Create(GLItemsList items, GLRenderProgramSortedList rObjects, Tuple`2 starimagearrayp, Single sunsize, GLStorageBlock findbufferresults, GalMapObjects gmos) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\GalaxyStars.cs:line 85
   at EDDiscovery.UserControls.Map3D.Map.Start(GLWinFormControl glwfc, GalacticMapping edsmmapping, GalacticMapping eliteregions, UserControlCommonBase parent, Parts parts) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\Map.cs:line 453
   at EDDiscovery.UserControls.UserControl3DMap.LoadLayout() in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\UserControl3DMap.cs:line 51
   at EDDiscovery.MajorTabControl.AddTab(PanelIDs id, Int32 tabindex) in C:\Code\EDDiscovery\EDDiscovery\TabsPanelsAndPopOuts\MajorTabControl.cs:line 160
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====
```

EDDiscovery GPU assigned in Graphics Settings:
![edd_gpu](https://github.com/EDDiscovery/EDDiscovery/assets/41962802/a7ba80f2-4bef-426b-90cc-8f9ce83ec427)

**Comment by klightspeed** [comment]
Following the code, this seems to suggest that the [GLPLVertexShaderModelWorldTextureAutoScaleConfigurable](https://github.com/Foundation-Classes-For-OpenTK/OFC/blob/22d6ebe68be77599c6aa73139ab3e7d2314f0738/OFC/GL4/Shaders/Vertex/ShadersVertexModelTexture.cs#L479-L611) shader isn't properly compiling.

Are there any lines in the trace log (in `%LOCALAPPDATA%\EDDiscovery\Log\Trace*.log`) with something like `Pipeline shader compiler report` or `Pipeline shader linker report`?

**Comment by BB-MBS** [comment]
71: 2024-03-22T03:28:06.836Z: MajorTabControl create tab Map3D  6
  72: 2024-03-22T03:28:08.332Z: GL Context 65537
  73: 2024-03-22T03:28:08.332Z: Version  4.5.0
  74: 2024-03-22T03:28:08.332Z: Version  4.5.0 NVIDIA 377.83
  75: 2024-03-22T03:28:08.332Z: Vendor  NVIDIA Corporation
  76: 2024-03-22T03:28:08.333Z: Shading lang 4.50
  77: 2024-03-22T03:28:08.333Z: Shading lang 4.50 NVIDIA
  78: 2024-03-22T03:28:08.333Z: UBS=65536
  79: 2024-03-22T03:28:08.334Z: UB v14 f14 g14 tc14 te14
  80: 2024-03-22T03:28:08.334Z: tex layers 2048 
  81: 2024-03-22T03:28:08.334Z: Vertex attribs 16 
  82: 2024-03-22T03:28:08.334Z: Shader storage buffer bindings 96 
  83: 2024-03-22T03:28:08.569Z: Pipeline shader compiler report for GLPLFragmentShaderTextureBindlessIndexed: 0(2) : error C0201: unsupported version 460
                                0(3) : error C0203: extension GL_ARB_bindless_texture not supported in profile gp5fp
                                0(3) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(10) : warning C7532: global type int requires "#version 100" or later
                                0(12) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(16) : warning C7532: global type vec4 requires "#version 100" or later
                                0(16) : warning C5060: out can't be used with non-varying color
                                0(18) : warning C7532: global struct true requires "#version 100" or later
                                
                                1: #version 460 core
                                >>> 2: #extension GL_ARB_bindless_texture : require
                                3: layout (location =0) in vec2 vs_textureCoordinate;
                                4: layout (location = 2) in VS_IN
                                5: {
                                6: flat int vs_instanced;      // not sure why structuring is needed..
                                
  84: 2024-03-22T03:28:08.852Z: Pipeline shader compiler report for GalaxyFragmentPipeline: 0(2) : error C0201: unsupported version 460
                                0(2) : warning C7532: global type vec4 requires "#version 100" or later
                                0(2) : warning C5060: out can't be used with non-varying color
                                0(3) : warning C7532: global type vec3 requires "#version 100" or later
                                0(4) : warning C7532: global type int requires "#version 100" or later
                                0(7) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(15) : warning C7532: global type vec2 requires "#version 100" or later
                                0(20) : warning C7532: global type float requires "#version 100" or later
                                0(20) : warning C7532: global function abs requires "#version 100" or later
                                0(22) : warning C7532: global function sqrt requires "#version 100" or later
                                0(24) : warning C7011: implicit cast from "int" to "float"
                                0(31) : warning C7011: implicit cast from "int" to "float"
                                0(34) : error C1115: unable to find compatible overloaded function "texture(<overloaded function>, vec3)"
                                0(35) : warning C7532: global function max requires "#version 100" or later
                                0(35) : warning C7532: global function min requires "#version 100" or later
                                
                                1: #version 460 core
                                >>> 2: out vec4 color;
                                3: in vec3 vs_texcoord;
                                4: const int galtexbinding = 1;
                                5: const int noisebinding = 3;
                                6: const int gaussiandistbinding = 4;
                                
  85: 2024-03-22T03:28:09.428Z: Pipeline shader compiler report for GLPLGeoShaderFindTriangles: 0(2) : error C0201: unsupported version 460
                                0(15) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(18) : warning C7532: global type mat4 requires "#version 100" or later
                                0(20) : warning C7532: global type vec4 requires "#version 100" or later
                                0(22) : warning C7532: global type float requires "#version 100" or later
                                0(25) : error C0000: syntax error, unexpected '}' at token "}"
                                0(42) : warning C7532: global type vec2 requires "#version 100" or later
                                0(42) : warning C7532: global type vec3 requires "#version 100" or later
                                0(45) : warning C7532: global function length requires "#version 100" or later
                                0(48) : warning C7532: global function acos requires "#version 100" or later
                                0(49) : warning C7011: implicit cast from "int" to "float"
                                0(49) : warning C7011: implicit cast from "int" to "float"
                                0(49) : warning C7011: implicit cast from "int" to "float"
                                0(49) : warning C7011: implicit cast from "int" to "float"
                                0(49) : warning C7532: global function atan requires "#version 100" or later
                                0(50) : warning C7011: implicit cast from "int" to "float"
                                0(51) : warning C7011: implicit cast from "int" to "float"
                                0(53) : warning C7011: implicit cast from "int" to "float"
                                0(59) : warning C7532: global function sign requires "#version 100" or later
                                0(61) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(75) : warning C7566: in blocks require #version 150 or later
                                0(75) : warning C0000: ... or #extension GL_ARB_gpu_shader5 : enable
                                0(81) : warning C7566: out blocks require #version 150 or later
                                0(81) : warning C0000: ... or #extension GL_ARB_gpu_shader5 : enable
                                0(82) : warning C7532: global type int requires "#version 100" or later
                                0(83) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(86) : warning C7532: global type uint requires "#version 130" or later
                                0(86) : warning C0000: ... or #extension GL_EXT_gpu_shader4 : enable
                                0(88) : error C0000: syntax error, unexpected '}' at token "}"
                                0(90) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(94) : error C0000: syntax error, unexpected '}' at token "}"
                                0(96) : warning C7532: global struct true requires "#version 100" or later
                                0(98) : warning C7532: global struct false requires "#version 100" or later
                                0(101) : warning C7011: implicit cast from "int" to "float"
                                0(103) : warning C7532: global variable gl_PrimitiveIDIn requires "#version 150" or later
                                0(103) : warning C0000: ... or #extension GL_EXT_geometry_shader4 : enable
                                0(106) : warning C7011: implicit cast from "int" to "uint"
                                0(107) : warning C7011: implicit cast from "int" to "uint"
                                0(108) : warning C7011: implicit cast from "int" to "uint"
                                0(109) : warning C7011: implicit cast from "int" to "uint"
                                0(110) : warning C7011: implicit cast from "int" to "uint"
                                0(111) : warning C7011: implicit cast from "int" to "uint"
                                0(112) : warning C7011: implicit cast from "int" to "uint"
                                0(113) : warning C7011: implicit cast from "int" to "uint"
                                0(122) : error C1115: unable to find compatible overloaded function "atomicAdd(uint, int)"
                                0(123) : warning C7011: implicit cast from "int" to "float"
                                0(129) : warning C7011: implicit cast from "int" to "uint"
                                0(131) : warning C7011: implicit cast from "int" to "float"
                                0(136) : warning C7011: implicit cast from "int" to "uint"
                                0(137) : warning C7011: implicit cast from "int" to "uint"
                                0(138) : warning C7011: implicit cast from "int" to "uint"
                                0(139) : warning C7011: implicit cast from "int" to "uint"
                                0(140) : warning C7011: implicit cast from "int" to "uint"
                                0(141) : warning C7011: implicit cast from "int" to "uint"
                                0(142) : warning C7011: implicit cast from "int" to "uint"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(156) : warning C7011: implicit cast from "int" to "uint"
                                0(158) : warning C7011: implicit cast from "int" to "float"
                                0(163) : warning C7011: implicit cast from "int" to "uint"
                                0(164) : warning C7011: implicit cast from "int" to "uint"
                                0(165) : warning C7011: implicit cast from "int" to "uint"
                                0(166) : warning C7011: implicit cast from "int" to "uint"
                                0(167) : warning C7011: implicit cast from "int" to "uint"
                                
                                1: #version 460 core
                                >>> 2: /*
                                3: * Copyright 2019-2022 Robbyxp1 @ github.com
                                4: *
                                5: * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
                                6: * file except in compliance with the License. You may obtain a copy of the License at
                                
  86: 2024-03-22T03:28:10.916Z: Pipeline shader compiler report for GLPLVertexShaderModelWorldTextureAutoScale: 0(2) : error C0201: unsupported version 460
                                0(15) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(18) : warning C7532: global type mat4 requires "#version 100" or later
                                0(20) : warning C7532: global type vec4 requires "#version 100" or later
                                0(22) : warning C7532: global type float requires "#version 100" or later
                                0(25) : error C0000: syntax error, unexpected '}' at token "}"
                                0(44) : warning C7532: global function clamp requires "#version 100" or later
                                0(46) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(55) : warning C7566: out blocks require #version 150 or later
                                0(55) : warning C0000: ... or #extension GL_ARB_gpu_shader5 : enable
                                0(56) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(67) : warning C7011: implicit cast from "int" to "float"
                                0(68) : warning C7011: implicit cast from "int" to "float"
                                0(69) : warning C7011: implicit cast from "int" to "float"
                                0(70) : warning C7532: global struct false requires "#version 100" or later
                                0(75) : warning C7011: implicit cast from "int" to "float"
                                0(79) : warning C7011: implicit cast from "int" to "float"
                                0(81) : warning C7532: global variable gl_InstanceID requires "#version 140" or later
                                0(81) : warning C0000: ... or #extension GL_EXT_draw_instanced : enable
                                0(81) : warning C0000: ... or #extension GL_EXT_gpu_shader4 : enable
                                0(87) : warning C7011: implicit cast from "int" to "float"
                                
                                1: #version 460 core
                                >>> 2: /*
                                3: * Copyright 2019-2022 Robbyxp1 @ github.com
                                4: *
                                5: * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
                                6: * file except in compliance with the License. You may obtain a copy of the License at
                                
  87: 2024-03-22T03:28:10.922Z: Pipeline shader compiler report for GLPLGeoShaderFindTriangles: 0(2) : error C0201: unsupported version 460
                                0(15) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(18) : warning C7532: global type mat4 requires "#version 100" or later
                                0(20) : warning C7532: global type vec4 requires "#version 100" or later
                                0(22) : warning C7532: global type float requires "#version 100" or later
                                0(25) : error C0000: syntax error, unexpected '}' at token "}"
                                0(42) : warning C7532: global type vec2 requires "#version 100" or later
                                0(42) : warning C7532: global type vec3 requires "#version 100" or later
                                0(45) : warning C7532: global function length requires "#version 100" or later
                                0(48) : warning C7532: global function acos requires "#version 100" or later
                                0(49) : warning C7011: implicit cast from "int" to "float"
                                0(49) : warning C7011: implicit cast from "int" to "float"
                                0(49) : warning C7011: implicit cast from "int" to "float"
                                0(49) : warning C7011: implicit cast from "int" to "float"
                                0(49) : warning C7532: global function atan requires "#version 100" or later
                                0(50) : warning C7011: implicit cast from "int" to "float"
                                0(51) : warning C7011: implicit cast from "int" to "float"
                                0(53) : warning C7011: implicit cast from "int" to "float"
                                0(59) : warning C7532: global function sign requires "#version 100" or later
                                0(61) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(75) : warning C7566: in blocks require #version 150 or later
                                0(75) : warning C0000: ... or #extension GL_ARB_gpu_shader5 : enable
                                0(81) : warning C7566: out blocks require #version 150 or later
                                0(81) : warning C0000: ... or #extension GL_ARB_gpu_shader5 : enable
                                0(82) : warning C7532: global type int requires "#version 100" or later
                                0(83) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(86) : warning C7532: global type uint requires "#version 130" or later
                                0(86) : warning C0000: ... or #extension GL_EXT_gpu_shader4 : enable
                                0(88) : error C0000: syntax error, unexpected '}' at token "}"
                                0(90) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(94) : error C0000: syntax error, unexpected '}' at token "}"
                                0(96) : warning C7532: global struct true requires "#version 100" or later
                                0(98) : warning C7532: global struct false requires "#version 100" or later
                                0(101) : warning C7011: implicit cast from "int" to "float"
                                0(103) : warning C7532: global variable gl_PrimitiveIDIn requires "#version 150" or later
                                0(103) : warning C0000: ... or #extension GL_EXT_geometry_shader4 : enable
                                0(106) : warning C7011: implicit cast from "int" to "uint"
                                0(107) : warning C7011: implicit cast from "int" to "uint"
                                0(108) : warning C7011: implicit cast from "int" to "uint"
                                0(109) : warning C7011: implicit cast from "int" to "uint"
                                0(110) : warning C7011: implicit cast from "int" to "uint"
                                0(111) : warning C7011: implicit cast from "int" to "uint"
                                0(112) : warning C7011: implicit cast from "int" to "uint"
                                0(113) : warning C7011: implicit cast from "int" to "uint"
                                0(122) : error C1115: unable to find compatible overloaded function "atomicAdd(uint, int)"
                                0(123) : warning C7011: implicit cast from "int" to "float"
                                0(129) : warning C7011: implicit cast from "int" to "uint"
                                0(131) : warning C7011: implicit cast from "int" to "float"
                                0(136) : warning C7011: implicit cast from "int" to "uint"
                                0(137) : warning C7011: implicit cast from "int" to "uint"
                                0(138) : warning C7011: implicit cast from "int" to "uint"
                                0(139) : warning C7011: implicit cast from "int" to "uint"
                                0(140) : warning C7011: implicit cast from "int" to "uint"
                                0(141) : warning C7011: implicit cast from "int" to "uint"
                                0(142) : warning C7011: implicit cast from "int" to "uint"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(156) : warning C7011: implicit cast from "int" to "uint"
                                0(158) : warning C7011: implicit cast from "int" to "float"
                                0(163) : warning C7011: implicit cast from "int" to "uint"
                                0(164) : warning C7011: implicit cast from "int" to "uint"
                                0(165) : warning C7011: implicit cast from "int" to "uint"
                                0(166) : warning C7011: implicit cast from "int" to "uint"
                                0(167) : warning C7011: implicit cast from "int" to "uint"
                                
                                1: #version 460 core
                                >>> 2: /*
                                3: * Copyright 2019-2022 Robbyxp1 @ github.com
                                4: *
                                5: * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
                                6: * file except in compliance with the License. You may obtain a copy of the License at
                                
  88: 2024-03-22T03:28:10.992Z: Pipeline shader compiler report for GLPLVertexShaderModelWorldTextureAutoScale: 0(2) : error C0201: unsupported version 460
                                0(15) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(18) : warning C7532: global type mat4 requires "#version 100" or later
                                0(20) : warning C7532: global type vec4 requires "#version 100" or later
                                0(22) : warning C7532: global type float requires "#version 100" or later
                                0(25) : error C0000: syntax error, unexpected '}' at token "}"
                                0(44) : warning C7532: global function clamp requires "#version 100" or later
                                0(46) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(55) : warning C7566: out blocks require #version 150 or later
                                0(55) : warning C0000: ... or #extension GL_ARB_gpu_shader5 : enable
                                0(56) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(67) : warning C7011: implicit cast from "int" to "float"
                                0(68) : warning C7011: implicit cast from "int" to "float"
                                0(69) : warning C7011: implicit cast from "int" to "float"
                                0(70) : warning C7532: global struct false requires "#version 100" or later
                                0(75) : warning C7011: implicit cast from "int" to "float"
                                0(79) : warning C7011: implicit cast from "int" to "float"
                                0(81) : warning C7532: global variable gl_InstanceID requires "#version 140" or later
                                0(81) : warning C0000: ... or #extension GL_EXT_draw_instanced : enable
                                0(81) : warning C0000: ... or #extension GL_EXT_gpu_shader4 : enable
                                0(87) : warning C7011: implicit cast from "int" to "float"
                                
                                1: #version 460 core
                                >>> 2: /*
                                3: * Copyright 2019-2022 Robbyxp1 @ github.com
                                4: *
                                5: * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
                                6: * file except in compliance with the License. You may obtain a copy of the License at
                                
  89: 2024-03-22T03:28:10.995Z: Repeated 2: Pipeline shader compiler report for GLPLGeoShaderFindTriangles: 0(2) : error C0201: unsupported version 460
                                0(15) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(18) : warning C7532: global type mat4 requires "#version 100" or later
                                0(20) : warning C7532: global type vec4 requires "#version 100" or later
                                0(22) : warning C7532: global type float requires "#version 100" or later
                                0(25) : error C0000: syntax error, unexpected '}' at token "}"
                                0(42) : warning C7532: global type vec2 requires "#version 100" or later
                                0(42) : warning C7532: global type vec3 requires "#version 100" or later
                                0(45) : warning C7532: global function length requires "#version 100" or later
                                0(48) : warning C7532: global function acos requires "#version 100" or later
                                0(49) : warning C7011: implicit cast from "int" to "float"
                                0(49) : warning C7011: implicit cast from "int" to "float"
                                0(49) : warning C7011: implicit cast from "int" to "float"
                                0(49) : warning C7011: implicit cast from "int" to "float"
                                0(49) : warning C7532: global function atan requires "#version 100" or later
                                0(50) : warning C7011: implicit cast from "int" to "float"
                                0(51) : warning C7011: implicit cast from "int" to "float"
                                0(53) : warning C7011: implicit cast from "int" to "float"
                                0(59) : warning C7532: global function sign requires "#version 100" or later
                                0(61) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(75) : warning C7566: in blocks require #version 150 or later
                                0(75) : warning C0000: ... or #extension GL_ARB_gpu_shader5 : enable
                                0(81) : warning C7566: out blocks require #version 150 or later
                                0(81) : warning C0000: ... or #extension GL_ARB_gpu_shader5 : enable
                                0(82) : warning C7532: global type int requires "#version 100" or later
                                0(83) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(86) : warning C7532: global type uint requires "#version 130" or later
                                0(86) : warning C0000: ... or #extension GL_EXT_gpu_shader4 : enable
                                0(88) : error C0000: syntax error, unexpected '}' at token "}"
                                0(90) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(94) : error C0000: syntax error, unexpected '}' at token "}"
                                0(96) : warning C7532: global struct true requires "#version 100" or later
                                0(98) : warning C7532: global struct false requires "#version 100" or later
                                0(101) : warning C7011: implicit cast from "int" to "float"
                                0(103) : warning C7532: global variable gl_PrimitiveIDIn requires "#version 150" or later
                                0(103) : warning C0000: ... or #extension GL_EXT_geometry_shader4 : enable
                                0(106) : warning C7011: implicit cast from "int" to "uint"
                                0(107) : warning C7011: implicit cast from "int" to "uint"
                                0(108) : warning C7011: implicit cast from "int" to "uint"
                                0(109) : warning C7011: implicit cast from "int" to "uint"
                                0(110) : warning C7011: implicit cast from "int" to "uint"
                                0(111) : warning C7011: implicit cast from "int" to "uint"
                                0(112) : warning C7011: implicit cast from "int" to "uint"
                                0(113) : warning C7011: implicit cast from "int" to "uint"
                                0(122) : error C1115: unable to find compatible overloaded function "atomicAdd(uint, int)"
                                0(123) : warning C7011: implicit cast from "int" to "float"
                                0(129) : warning C7011: implicit cast from "int" to "uint"
                                0(131) : warning C7011: implicit cast from "int" to "float"
                                0(136) : warning C7011: implicit cast from "int" to "uint"
                                0(137) : warning C7011: implicit cast from "int" to "uint"
                                0(138) : warning C7011: implicit cast from "int" to "uint"
                                0(139) : warning C7011: implicit cast from "int" to "uint"
                                0(140) : warning C7011: implicit cast from "int" to "uint"
                                0(141) : warning C7011: implicit cast from "int" to "uint"
                                0(142) : warning C7011: implicit cast from "int" to "uint"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(148) : warning C7011: implicit cast from "int" to "float"
                                0(156) : warning C7011: implicit cast from "int" to "uint"
                                0(158) : warning C7011: implicit cast from "int" to "float"
                                0(163) : warning C7011: implicit cast from "int" to "uint"
                                0(164) : warning C7011: implicit cast from "int" to "uint"
                                0(165) : warning C7011: implicit cast from "int" to "uint"
                                0(166) : warning C7011: implicit cast from "int" to "uint"
                                0(167) : warning C7011: implicit cast from "int" to "uint"
                                
                                1: #version 460 core
                                >>> 2: /*
                                3: * Copyright 2019-2022 Robbyxp1 @ github.com
                                4: *
                                5: * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
                                6: * file except in compliance with the License. You may obtain a copy of the License at
                                
  90: 2024-03-22T03:28:11.020Z: Pipeline shader compiler report for GLPLVertexShaderModelWorldTextureAutoScaleConfigurable: 0(2) : error C0201: unsupported version 460
                                0(15) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(18) : warning C7532: global type mat4 requires "#version 100" or later
                                0(20) : warning C7532: global type vec4 requires "#version 100" or later
                                0(22) : warning C7532: global type float requires "#version 100" or later
                                0(25) : error C0000: syntax error, unexpected '}' at token "}"
                                0(44) : warning C7532: global function clamp requires "#version 100" or later
                                0(46) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(58) : warning C7566: out blocks require #version 150 or later
                                0(58) : warning C0000: ... or #extension GL_ARB_gpu_shader5 : enable
                                0(59) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
                                0(70) : warning C7532: global struct true requires "#version 100" or later
                                0(75) : warning C7011: implicit cast from "int" to "float"
                                0(79) : warning C7011: implicit cast from "int" to "float"
                                0(81) : warning C7532: global variable gl_InstanceID requires "#version 140" or later
                                0(81) : warning C0000: ... or #extension GL_EXT_draw_instanced : enable
                                0(81) : warning C0000: ... or #extension GL_EXT_gpu_shader4 : enable
                                
                                1: #version 460 core
                                >>> 2: /*
                                3: * Copyright 2019-2022 Robbyxp1 @ github.com
                                4: *
                                5: * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
                                6: * file except in compliance with the License. You may obtain a copy of the License at
                                
  91: 2024-03-22T03:28:11.043Z: ==== UNHANDLED UI EXCEPTION ====
                                System.InvalidCastException: Specified cast is not valid.
                                   at GLOFC.GL4.Shaders.GLShaderPipeline.GetShader[T]()
                                   at EDDiscovery.UserControls.Map3D.GalaxyStars.SetAutoScale(Int32 max) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\GalaxyStars.cs:line 55
                                   at EDDiscovery.UserControls.Map3D.GalaxyStars.Create(GLItemsList items, GLRenderProgramSortedList rObjects, Tuple`2 starimagearrayp, Single sunsize, GLStorageBlock findbufferresults, GalMapObjects gmos) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\GalaxyStars.cs:line 85
                                   at EDDiscovery.UserControls.Map3D.Map.Start(GLWinFormControl glwfc, GalacticMapping edsmmapping, GalacticMapping eliteregions, UserControlCommonBase parent, Parts parts) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\Map.cs:line 453
                                   at EDDiscovery.UserControls.UserControl3DMap.LoadLayout() in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\UserControl3DMap.cs:line 51
                                   at EDDiscovery.MajorTabControl.AddTab(PanelIDs id, Int32 tabindex) in C:\Code\EDDiscovery\EDDiscovery\TabsPanelsAndPopOuts\MajorTabControl.cs:line 160
                                   at System.Windows.Forms.Control.OnClick(EventArgs e)
                                   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
                                   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
                                   at System.Windows.Forms.Control.WndProc(Message& m)
                                   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
                                   at System.Windows.Forms.Button.WndProc(Message& m)
                                   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
                                ==== cut ====

**Comment by Eahlstan** [comment]
Which GPU are you using?
377.83 is a very old driver (2018) for the Quadro series. It might be that your card (or the drivers) doesn't support the needed OpenGl in extension bindless_textures

**Comment by BB-MBS** [comment]
This is a secondary computer with a Quadro 2000 graphic card - dedicated to EDDiscovery. The driver is the last supported version. It is funny that it can run Odyssey, but cannot withstand the EDDiscovery 3D map.

**Comment by klightspeed** [comment]
It looks like OpenGL 4.6 was introduced in the Geforce 397.31 driver.

> It is funny that it can run Odyssey, but cannot withstand the EDDiscovery 3D map.

I think Odyssey uses DirectX 11, while the EDDiscovery 3D map uses OpenGL. The game would code defensively and have fallbacks when the graphics card doesn't support some features, while EDDiscovery has no such fallbacks.

**Comment by BB-MBS** [comment]
I tried 397.31 - "This graphics driver could not find compatible graphics hardware". Is there a simple way to workaround?

**Comment by klightspeed** [comment]
Unfortunately it would require a re-architect of the EDDiscovery 3D map to support older hardware (including having fallbacks when the hardware or driver doesn't support certain features), which Robby is probably not going to do.

**Comment by BB-MBS** [comment]
I assumed the possibility of forced installation of a driver or replacing/changing some files or editing a registry. Perhaps you know the way.

**Comment by robbyxp1** [comment]
There is only but a few of us doing this, not a big team, so I'm afraid there has to be a support cut of somewhere. The GC needs to support OpenGL 4.6 for the 3dmap to work.

On the bright side the rest of the program will function fine!

**Comment by robbyxp1** [comment]
Here is an old post..

https://www.reddit.com/r/linux_gaming/comments/6qolq2/nvidia_drivers_with_opengl_46_support_released/

It mentioned Quadro P2000 in its list of 4.6 supported cards

**Comment by klightspeed** [comment]
Quadro 2000 and Quadro P2000 are two different video cards, with the former being released in 2010, and the latter being released in 2017.

**Comment by robbyxp1** [comment]
Did you look thru this https://www.nvidia.co.uk/Download/index.aspx?lang=en-uk

A quandro p2000 (if thats it) is mentioed under Nvidia RTX/Quandro - Quandro Series and Quandro Notebook

**Comment by robbyxp1** [comment]
So, to conclude, the GC is too old to support modern 3G work.  Closing
