### ISSUE TITLE
History Refresh Error: System.Collections.Generic.KeyNotFoundException

### ISSUE THREAD

**Issue by athulin** [EDDiscovery/EDDiscovery#3499]
For your information. The problem was not directly repeatable: a second attempt at starting EDDiscovery worked without problems, and as far as I can see without lacunae in the logs.

On starting EDDiscovery after an earlier, and normal (i.e. no obvious errors observed) session, resulted in an empty history, and the following message in the log:

Scanning for bmp screenshots in C:\Users\Anders Thulin\Pictures\Frontier Developments\Elite Dangerous
*** Web server is disabled ***
Profile Default Loaded
Loaded Bindings C:\Users\Anders Thulin\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\Custom.4.0.binds
CAPI Installed
Get galactic mapping from EDSM.
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
History Refresh Error: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDD\EDDiscoveryControllerHistory.cs:line 166
History refresh complete.
Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 2024-03-24 06:28:33 to 2024-03-24 15:10:48
Systems update complete with 6 009 systems

**Comment by robbyxp1** [comment]
near 166 is:                 System.Diagnostics.Trace.WriteLine($"{BaseUtils.AppTicks.TickCountLap()} EDC Load history for Cmdr {args.CurrentCommander} {EDCommander.Current.Name}");

EDCommander.Current.Name is a dictionary lookup

Sort of implies that current=> Commanders[CurrentCmdrID]  CurrentCmdrID is not valid..

CurrentCmdrID is set in LoadCommanders.

Can't see the path why it would not be set.  LoadCommanders is called way back at DiscoveryForm::Init

**Comment by athulin** [comment]
I did make a switch between commanders somewhere about this time, and
that may have been a reason, but I've done that before without problems.
Not sure just when I started EDDiscovery: before I closed the first 
session, or after, but before I logged in with my normal commander, or ... .

I'll do some more tests on those scenarios and related ones to see if I 
can trigger it again.


On 2024-03-25 10:28, Rob wrote:
> near 166 is:                 System.Diagnostics.Trace.WriteLine($"{BaseUtils.AppTicks.TickCountLap()} EDC Load history for Cmdr {args.CurrentCommander} {EDCommander.Current.Name}");
> 
> EDCommander.Current.Name is a dictionary lookup
> 
> Sort of implies that current=> Commanders[CurrentCmdrID]  CurrentCmdrID is not valid..
> 
> CurrentCmdrID is set in LoadCommanders.
> 
> Can't see the path why it would not be set.  LoadCommanders is called way back at DiscoveryForm::Init
> 

-- 
/A. Thulin                http://www.anders.thulin.name

**Comment by Eahlstan** [comment]
You're using the latest version, right?

**Comment by klightspeed** [comment]
This definitely looks like a non-fatal version of #3485 - there is probably not enough time to sneak in a commander delete between the `LoadCommander()` in `EDDiscoveryForm.Init()` and the `DoRefreshHistory()` in the `BackgroundWorkerThread()` started in `PostInit_Shown()` called when the window is shown.

Note that the fixed version (17.1) still has the pre-release tag - 17.0.4 was released before this bug was fixed.

**Comment by robbyxp1** [comment]
Okay, thanks

**Comment by robbyxp1** [comment]
Try 17.1.1 thanks
