### ISSUE TITLE
Hi-Res Screenshot Deletion fails

### ISSUE THREAD

**Issue by galaxyutii** [EDDiscovery/EDDiscovery#35]
Hello,
I'm away from my gaming computer at the moment, but what happens is that when the "delete screenshot" checkbox is enabled and I take a hi-res screenshot, EDD throws an error for the "ImageConvert" process. It still successfully renames and converts to a png, but it won't process any new images or delete anything until the alert is dismissed. I don't believe this happens with standard-res screenshots, although I haven't done extensive testing.

I *think* the problem is that when I take a high-res screenshot, it takes a few seconds to save it, which interrupts the deletion process. If you need a specific error message or more specific tests, I can provide them to you next week once I'm back at home. Any way I can help, please let me know! Great product, by the way!

Zach

**Comment by gregmalcolm** [comment]
I think sone changes have happened in this area. This still happening?

**Comment by galaxyutii** [comment]
I ended up switching to ScreenShotChanger for screenshot conversion as it has customizable naming schemes and can also handle videos, so I'm not sure if it still fails.

**Comment by robbyxp1** [comment]
Its been rewritten and works on my system perfectly since the 22 dec.. I think this is an old issue.

Additional naming schemes have been introduced.

I'm closing this as #119 fixes it.
