### ISSUE TITLE
You can create a custom search with an empty name, which is then impossible to delete without external tools

### ISSUE THREAD

**Issue by LikeLakers2** [EDDiscovery/EDDiscovery#3500]
Hi there! I found a bug in the Search panel where you can give a custom search an empty name while saving it. This custom search then becomes impossible to delete without using external tools.

Of note, while I was able to do this, it did not result in corrupted data - EDDiscovery continued to operate without error even after closing and reopening the program. I was even able to select the erroneous custom search from the Search panel's dropdown, and have it load without incident.

**Reproduction steps:**
1. Open up any Search panel
2. Click on the floppy disk to save the current search
3. Keep the "Name" box blank, and hit OK.
4. Try to delete this blank-named search from within EDDiscovery, only to get an error

**I expected to see this happen:**
I expected one of the following:
* Leaving the name field blank would overwrite the currently-selected search
* Leaving the name field blank would return an error (or otherwise prevent me from saving it)
* I would be able to delete the blank-named search.

**Instead, this happened:**
* I was able to save the search without a name
* I was unable to delete the search without using an external tool (thankfully, I had such a tool on hand)

Thank you for your hard work! I hope this can be fixed soon.

**Comment by klightspeed** [comment]
With the "blank name", I'm guessing this is specifically when you have scans (the wireframe sphere) selected, as the save button won't do anything for the stars search if you have not performed a search yet.

<https://github.com/EDDiscovery/EDDiscovery/blob/341c0f0945f9c882918a02c75f21697f5a6ca97e/EDDiscovery/UserControls/Search/SearchScans.cs#L177-L193>
```cs
                if (name != null)
```
should probably be
```cs
                if (!string.IsNullOrWhitespace(name))
```

**Comment by Eahlstan** [comment]
`if (!string.IsNullOrWhitespace(name))`

I dislike that, I got a few whitespace searches to show bodies on the Surveyor without expanding everything with the search names.

**Comment by Eahlstan** [comment]
> HasChars()

I like that, it doesn't let me save an empty name, but whitespace names work.

Thought: Empty name doesn't throw an error message, it would be good if it does.

**Comment by LikeLakers2** [comment]
> [@klightspeed] With the "blank name", I'm guessing this is specifically when you have scans (the wireframe sphere) selected [...]

Yes, that's what I meant. Sorry for that, I forgot that scans weren't the only thing you can search, as I'm not only new-ish to EDDiscovery, but the vast majority of my usage of the Search panel has been to search my scans.
