### ISSUE TITLE
Stutter in Voice Pack

### ISSUE THREAD

**Issue by Jugom** [EDDiscovery/EDDiscovery#3501]
It is Rare and Random, but present. 
Very minor glitches of less than half a second every so often but at least once every couple of sessions as bad as the following example.
Let me know what additional data you might require.

https://github.com/EDDiscovery/EDDiscovery/assets/74990247/4b6f5591-40ee-4bc2-b914-7e9ad441e325

**Comment by Eahlstan** [comment]
Can confirm this. Although I don't play with the VP enabled the few times I enable it to debug stuff it stutters frequently.

**Comment by robbyxp1** [comment]
A lot of variables in here (windows, the program, priorities, etc)

It does not stutter like this on my PC. 

I need to be able to reproduce to see what is causing it.

**Comment by Eahlstan** [comment]
Well since I can reproduce it: Anything I can look at?

**Comment by robbyxp1** [comment]
See EDD Discord.
