### ISSUE TITLE
Only updating system list from EDSM on startup

### ISSUE THREAD

**Issue by psdevil** [EDDiscovery/EDDiscovery#3503]
I'm not sure if this is a bug or if this is deliberate.

Whenever I start EDD, the EDSM system list is imported. After that nothing. I'm sure it used to update about every 6 hours.
[no updates from EDSM.zip](https://github.com/EDDiscovery/EDDiscovery/files/14979476/no.updates.from.EDSM.zip)

I've attached a few logs from the EDD log folder since the program was last started on the 12th of April.

**Comment by Eahlstan** [comment]
> So, the download, by design, of the star data is once per start up of the program. The system databases held by Spansh and EDSM are not real time, they can have long delays on them (days) before data becomes available to the end point we download from.  So doing it once per invokation is fine.  there is no point rechecking them. We have to be considerate of EDSM/Spansh and not poll them too many times and increase the load on their servers 
> your use case of leaving EDD running for days is the first time i've heard of it.  Most people start EDD up with Elite.
> the design as of now stays.

Said Robby some months ago. Therefore not a bug.

**Comment by psdevil** [comment]
Thank you for the information. Now I know
