### ISSUE TITLE
Captain's log treats Time column as string instead of chronological value when sorting

### ISSUE THREAD

**Issue by unfo** [EDDiscovery/EDDiscovery#3504]
Reporting this UI bug for sorting dates.

As seen in this screenshot from my Captain's log, the values are sorted by Time ascending (note small upward arrow in the column)

![image](https://github.com/EDDiscovery/EDDiscovery/assets/2683/13a44d5a-815a-45bc-860c-b6c0192cc30d)

And the values are treated as strings since the order is 17, 19, 2 for the dates 17-Apr, 19-Mar, 2-Apr instead of being 19.3. - 2.4. - 17.4. for those three dates, but in reality there are many more entries in between.

Or as an alternate example, sorting Descending sets the "latest" entry to be 9th April (9.4.2024) instead of 17th April (today) when I have made my latest entry as seen in the first screenshot.

![image](https://github.com/EDDiscovery/EDDiscovery/assets/2683/b88430e4-37e6-4fb6-9cc0-eef7740fa00a)

For US users the `mm/dd yyyy` or similar will mostly mask this issue since it orders almost the same way as ISO 8601 of `yyyy-mm-dd`.

But regardless of date formatting, the values should be sorted as chronological timestamps instead of their string representation.

Of note: the export as CSV does actually output in a sensible datetime format:

```
Time;System;Body;Note;Tags
2024-04-09 22:50;Bla Gree GH-Y c3-3;Bla Gree GH-Y c3-3;Immediate heat warning when jumping into the system -- K-M binary at 0 and 5 Ls;
2024-04-09 19:04;Bla Gree ZE-H d10-0;Bla Gree ZE-H d10-0;67,29 @ full tank 32/32 -- target is 67,2;
```

Workaround could be to always display in the date in the exported `yyyy-mm-dd hh:mm` format so it would sort properly.

Running version 17.1.1.0 as portable exe.

**Comment by Eahlstan** [comment]
Thanks for the report, I could reproduce the issue.

![Screenshot 2024-04-17 194522](https://github.com/EDDiscovery/EDDiscovery/assets/59618179/0d1a7c7b-1834-4063-aa91-8daa1c9c637c)
![Screenshot 2024-04-17 194509](https://github.com/EDDiscovery/EDDiscovery/assets/59618179/e454682a-bd95-418b-a30c-fb3ccc31e426)

I was also able to fix the issue.

![Screenshot 2024-04-17 195653](https://github.com/EDDiscovery/EDDiscovery/assets/59618179/5da98222-6307-48d0-9824-5c7d34564028)
![Screenshot 2024-04-17 195641](https://github.com/EDDiscovery/EDDiscovery/assets/59618179/3488df07-00a3-4153-9acd-7cbc61b762ed)

The wrong sorting algorithm was applied to this column.

https://github.com/EDDiscovery/EDDiscovery/pull/3505

**Comment by robbyxp1** [comment]
Next version , out soon
