### ISSUE TITLE
UI exception when planning a route with the Spansh Galaxy Plotter module 

### ISSUE THREAD

**Issue by poncelef** [EDDiscovery/EDDiscovery#3509]
### Description
UI exception when planning a route with the Spansh Galaxy Plotter module 

### Additional Information
![EDDiscovery_splansh_crash](https://github.com/EDDiscovery/EDDiscovery/assets/57759721/bd847d19-c760-40f5-9a5a-92511e629b43)

### Exception Details:
>EDDiscovery v17.1.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
>   à EliteDangerousCore.Spansh.SpanshClass.RequestGalaxyPlotter(String source, String destination, Int32 cargo, Boolean is_supercharged, Boolean use_supercharge, Boolean use_injections, Boolean exclude_secondary, ShipInformation si, String algorithm) dans C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Spansh\SpanshClassRouters.cs:ligne 273
>   à EDDiscovery.UserControls.UserControlRoute.extButtonSpanshGalaxyPlotter_Click(Object sender, EventArgs e) dans C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlRouteSpansh.cs:ligne 328
>   à System.Windows.Forms.Control.OnClick(EventArgs e)
>   à System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   à System.Windows.Forms.Control.WndProc(Message& m)
>   à System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   à System.Windows.Forms.Button.WndProc(Message& m)
>   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
The ship information logged to EDD is not complete (Elite did not write out that) and we did not trap it properly

this is fixed in the main code and will be fixed in the version.

It is most likely solved now as you've logged into Elite and made it write that bit of missing info.
