### ISSUE TITLE
Crash when the computer goes to sleep and the EDDiscovery is in the route finder.

### ISSUE THREAD

**Issue by rcruz63** [EDDiscovery/EDDiscovery#3510]
I frequently, but not always, encounter the application with this error when I wake up the computer after it was suspended.
I have seen the other error, but it is not the same case since at no time has it happened to me while on the 3D map

```
There was an unhandled UI exception.

==== BEGIN ====
OpenTK.Graphics.GraphicsContextException: Failed to make context 65537 current. Error: 0
   en OpenTK.Platform.Windows.WinGLContext.MakeCurrent(IWindowInfo window) en C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Platform\Windows\WinGLContext.cs:línea 279
   en EDDiscovery.UserControls.UserControl3DMap.SystemTick(Object sender, EventArgs e) en C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\UserControl3DMap.cs:línea 111
   en System.Windows.Forms.Timer.OnTick(EventArgs e)
   en System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====
```

**Comment by klightspeed** [comment]
Do you have a 3D map tab present when this occurs (it does not matter if it is the currently focused tab)

**Comment by robbyxp1** [comment]
See #3271 its a known issue.

**Comment by robbyxp1** [comment]
Maybe implement https://stackoverflow.com/questions/16747146/c-sharp-sleep-detection-powermodechanged

**Comment by rcruz63** [comment]
> Do you have a 3D map tab present when this occurs (it does not matter if it is the currently focused tab)

The 3d tab is part of the app, isn't it? How could I use the app without the 3D tab to avoid the issue?

**Comment by rcruz63** [comment]
> See #3271 its a known issue.

Initially, I assumed it was a new problem because I don't use the 3D Map. However, it appears to be the same issue, as the 3D map is being utilized even when it's not in focus.

**Comment by klightspeed** [comment]
> > Do you have a 3D map tab present when this occurs (it does not matter if it is the currently focused tab)
> 
> The 3d tab is part of the app, isn't it? How could I use the app without the 3D tab to avoid the issue?

You should be able to close any 3D map tab you have (right-click tab, close). I don't think any OpenGL context is created if no 3D map tab or popout is open.

**Comment by robbyxp1** [comment]
Closing
