### ISSUE TITLE
Error on rendering 3D map

### ISSUE THREAD

**Issue by feamsr00** [EDDiscovery/EDDiscovery#3511]
Greetings!
Whenever I go to load the 3D Map, after a short delay, the following render errors are displayed.
```
Pipeline shader compiler report for GLPLFragmentShaderTextureBindlessIndexed: ERROR: 0:14: '' : array size too big 


Pipeline shader compiler report for GLPLFragmentShaderBindlessTexture: ERROR: 0:11: '' : array size too big 
```
(Note: this is not an application exception. Unfortunately, the trace logs appear to contain no further detail)
```
  92: 2024-06-27T18:02:15.090Z: MajorTabControl create tab Map3D  4
  93: 2024-06-27T18:02:15.473Z: GL Context 65537
  94: 2024-06-27T18:02:15.473Z: Version  4.6.0
  95: 2024-06-27T18:02:15.473Z: Version  4.6.0 - Build 31.0.101.5333
  96: 2024-06-27T18:02:15.473Z: Vendor  Intel
  97: 2024-06-27T18:02:15.474Z: Shading lang 4.60
  98: 2024-06-27T18:02:15.474Z: Shading lang 4.60 - Build 31.0.101.5333
  99: 2024-06-27T18:02:15.474Z: UBS=65536
 100: 2024-06-27T18:02:15.474Z: UB v14 f14 g14 tc14 te14
 101: 2024-06-27T18:02:15.474Z: tex layers 2048 
 102: 2024-06-27T18:02:15.474Z: Vertex attribs 16 
 103: 2024-06-27T18:02:15.474Z: Shader storage buffer bindings 16 
 104: 2024-06-27T18:02:15.585Z: Pipeline shader compiler report for GLPLFragmentShaderTextureBindlessIndexed: ERROR: 0:14: '' : array size too big 
                                
                                
 105: 2024-06-27T18:02:21.263Z: Pipeline shader compiler report for GLPLFragmentShaderBindlessTexture: ERROR: 0:11: '' : array size too big 
                                
                                
```

Windows 10 22H2
EDDiscovery version: 17.1.1.0
GPU: Intel A750 
![image](https://github.com/EDDiscovery/EDDiscovery/assets/983484/810faf7d-7e73-4e3f-b698-bfb5693af34d)
https://www.techpowerup.com/gpu-specs/intel-arc-a750-limited-edition.b9918

(and yes EDD is using the correct GPU)
![image](https://github.com/EDDiscovery/EDDiscovery/assets/983484/d9e351d9-99b3-41ad-b413-23ad1796a786)

Otherwise EDD seems to be operating well.

I welcome your thoughts.

**Comment by klightspeed** [comment]
I'm guessing the new Intel Arc GPUs can't handle 256 element texture arrays.
https://github.com/Foundation-Classes-For-OpenTK/OFC/blob/master/OFC%2FGL4%2FShaders%2FFragment%2FShadersFragmentBindless.cs#L79

**Comment by robbyxp1** [comment]
This shader used by 
   public GLBindlessTextureBitmaps(string name, GLRenderProgramSortedList rlist, int arbblock = 3,
                                            bool cullface = true, bool depthtest = true, bool yfixed = false, int maxbitmaps = 1024)

which is used by EDDiscovery map.cs line 185

               usertexturebitmaps = new GLOFC.GL4.Bitmaps.GLBindlessTextureBitmaps("UserBitmaps", rObjects, userbitmapsarbblock, false);

changing it to

               usertexturebitmaps = new GLOFC.GL4.Bitmaps.GLBindlessTextureBitmaps("UserBitmaps", rObjects, userbitmapsarbblock, false, NNNN);

and seeing which NNNN worked would be a useful thing (if you can compile EDD)

I can't find an obvious GL_ variable (as of now) which would tell me the limit of this sampler array.  The Arc one must be smaller than NVidia or AMD as we had not had reports of this before.

**Comment by Eahlstan** [comment]
Out of curiosity: Can you please install [this program](https://www.realtech-vr.com/home/?page_id=142), run it, hit the save button and upload the resulting file?

**Comment by robbyxp1** [comment]
Here is my 1080 ancient graphics card output
[glview-NVIDIA GeForce GTX 1080PCIeSSE2-1.zip](https://github.com/user-attachments/files/16039699/glview-NVIDIA.GeForce.GTX.1080PCIeSSE2-1.zip)

I can't see anything obv, but then at the moment I don't know what I'm looking for.  I can't find an obvious parameter which says the limit size of a 2d sampler..

**Comment by Eahlstan** [comment]
Of course `NNNN` doesn't exist. You're supposed to enter a number instead of it. Currently 1024 is used which seems to be too big for your card, so try a smaller value.

**Comment by robbyxp1** [comment]
public GLPLFragmentShaderBindlessTexture(int arbblock, bool usealphablending = false, bool discardiftransparent = false, bool useprimidover2 = true)

has fixed     sampler2D tex[256];

        public GLPLFragmentShaderTextureBindlessIndexed(int offset, int arbbinding = 1, bool alphablend = false, Color? alphazerocolour = null, int maxbitmaps = 1024)

has     sampler2D tex[maxbitmaps];

These are the only two places where sampler2D is an array in the code.

I found this:

https://community.intel.com/t5/Graphics/Access-violation-in-glLinkProgram-using-sampler2D-texture-array/m-p/1544316/highlight/true?profile.language=ko

They have a bodge at the bottom of the stupid replies.

I think this is a bad OpenGL implementation by Intel.

**Comment by robbyxp1** [comment]
Closing
