### ISSUE TITLE
Exception while searching commodities on "Spansh Stations" tab

### ISSUE THREAD

**Issue by GlowyHedgehog** [EDDiscovery/EDDiscovery#3513]
### Description
I had changed my PC resolution to 100% (from 150%) in order to see all commodities when doing a search using the "Spansh Stations" tab. I did a search, then changed the resolution back. I then went to do another search, but knowing that the commodity was earlier alphabetically, I didn't bother to change the resolution. Upon clicking "Search Now" this exception occurred; the search results did not update.

Exiting EDD and restarting, then repeating the process at 100% gave no error.

### Additional Information
None.

### Exception Details:
>EDDiscovery v17.1.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
>Parameter name: startIndex
>   at System.String.Substring(Int32 startIndex, Int32 length)
>   at EDDiscovery.UserControls.Helpers.SpanshStationsUserControl.<>c__DisplayClass26_0.<<extButtonSearchCommodities_Click>b__1>d.MoveNext() in C:\Code\EDDiscovery\EDDiscovery\UserControls\Helpers\SpanshStationsUserControl.cs:line 452
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by robbyxp1** [comment]
Thanks, there is a bug around line 452 etc which may be causing this. I'll fix and we can see if it ever comes back
