### ISSUE TITLE
"Unknown Module" reportings

### ISSUE THREAD

**Issue by Canthor** [EDDiscovery/EDDiscovery#3514]
Apparently, you like to see the below "Unknown Module" reportings. Nothing critical, as far as I understand.
I hope this is the right spot to report it, otherwise move it where you think it belongs to. 

_Reading travel history_
*** Unknown Module { "paintjob_type7_vibrant_green", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paintjob Type 7 Vibrant Green") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "nameplate_passenger02_white", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Nameplate Passenger 2 White") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_cobramkiv_gradient2_01", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Cobra Mk IV Gradient 2 1") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_type7_vibrant_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paintjob Type 7 Vibrant Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "bobble_christmaspresents", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Bobble Christmaspresents") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "python_industrial1_spoiler1", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Python Industrial 1 Spoiler 1") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "python_industrial1_wings1", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Python Industrial 1 Wings 1") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "python_industrial1_tail1", new ShipModule(-1,ShipModule.ModuleTypes.UnknownType,"Python Industrial 1 Tail 1") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "python_industrial1_bumper1", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Python Industrial 1 Bumper 1") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_eagle_hotrod_03", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Eagle Hotrod 3") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_eagle_pax_south_pax_south", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Eagle Pax South Pax South") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "eagle_shipkit1_spoiler3", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Eagle Shipkit 1 Spoiler 3") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "eagle_shipkit1_wings4", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Eagle Shipkit 1 Wings 4") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "eagle_shipkit1_bumper1", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Eagle Shipkit 1 Bumper 1") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "eagle_shipkit1_bumper3", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Eagle Shipkit 1 Bumper 3") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_diamondbackxl_christmas_01", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paintjob Diamondbackxl Christmas 1") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_diamondbackxl_christmas_02", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paintjob Diamondbackxl Christmas 2") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "independant_trader_shipkit1_spoiler4", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Independant Trader Shipkit 1 Spoiler 4") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "independant_trader_shipkit1_wings1", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Independant Trader Shipkit 1 Wings 1") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "independant_trader_shipkit1_bumper2", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Independant Trader Shipkit 1 Bumper 2") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_federation_gunship_gradient2_01", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Gunship Gradient 2 1") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_testbuggy_chase_03", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paintjob SRV Chase 3") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "krait_mkii_shipkit1_spoiler3", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Krait Mkii Shipkit 1 Spoiler 3") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Slots unknown BuggyCargoHatch
*** Slots unknown BuggyCargoHatch
*** Unknown Module { "decal_titanreward1", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Titanreward 1") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
_History refresh complete._

Fly safe, CMDR Canthor

**Comment by robbyxp1** [comment]
thank you, incorporated for next release
