### ISSUE TITLE
EDD error notification after update 18.0.2.0

### ISSUE THREAD

**Issue by alanasaba** [EDDiscovery/EDDiscovery#3515]
The following lines appeared in red in my log by first start the new update 28.0.2.0 of EDD: 

  *** Unknown Module { "paintjob_cutter_calligraphy_02", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Cutter Calligraphy 2") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_belugaliner_ember_white", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Belugaliner Ember White") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_mamba_tactical_grey", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Mamba Tactical Grey") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_sidewinder_tactical_grey", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Sidewinder Tactical Grey") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists

**Comment by robbyxp1** [comment]
thanks, will be added to next version
