### ISSUE TITLE
Unknown modules appearing after update to 18.0.2.0

### ISSUE THREAD

**Issue by Banjomel** [EDDiscovery/EDDiscovery#3516]
Reading travel history
*** Unknown Module { "paintjob_diamondbackxl_mechanist_05", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Diamondbackxl Mechanist 5") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "decal_military_elite", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Military Elite") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "decal_titanreward2_black", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Titanreward 2 Black") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists

**Comment by robbyxp1** [comment]
thanks
