### ISSUE TITLE
Unknown Modules after 18.0.2 upgrade

### ISSUE THREAD

**Issue by FatLes12** [EDDiscovery/EDDiscovery#3518]
Reading travel history
*** Unknown Module { "paintjob_ferdelance_militaire_earth_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Ferdelance Militaire Earth Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "decal_alien_sympathiser_g", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Alien Sympathiser G") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_asp_tactical_blue", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Asp Tactical Blue") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_dolphin_vibrant_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Dolphin Vibrant Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_ferdelance_gradient2_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Ferdelance Gradient 2 Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_cobramkiii_snakewrap_02", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Cobramkiii Snakewrap 2") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_mamba_tactical_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Mamba Tactical Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_type9_vibrant_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Type 9 Vibrant Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_typex_3_military_vibrant_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Typex 3 Military Vibrant Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_diamondbackxl_horus2_02", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Diamondbackxl Horus 2 2") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_asp_tactical_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Asp Tactical Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_type7_tactical_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Type 7 Tactical Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "decal_alien_sympathiser_e", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Alien Sympathiser E") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Ship/Suit/Actor: { "megashipdocka", new Actor("Megashipdocka") },
*** Unknown Module { "paintjob_empire_courier_tactical_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Empire Courier Tactical Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_sidewinder_tactical_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Sidewinder Tactical Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_adder_tactical_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Adder Tactical Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_cobramkiii_tactical_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Cobramkiii Tactical Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_viper_mkiv_tactical_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Viper Mkiv Tactical Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_type6_vibrant_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Type 6 Vibrant Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_eagle_tactical_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Eagle Tactical Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_empire_eagle_tactical_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Empire Eagle Tactical Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_federation_corvette_horus2_03", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Corvette Horus 2 3") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_krait_light_vibrant_blue", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Krait Light Vibrant Blue") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_anaconda_gradient2_01", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Anaconda Gradient 2 1") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Ship/Suit/Actor: { "poi_turretbunkera", new Actor("Poi Turretbunkera") },
*** Slots unknown Turret2
*** Unknown Module { "paintjob_typex_luminous_stripe_04", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Typex Luminous Stripe 4") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_krait_mkii_gradient2_crimson", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Krait Mkii Gradient 2 Crimson") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Slots unknown Turret2
*** Unknown Ship/Suit/Actor: { "poi_turretplatforma", new Actor("Poi Turretplatforma") },
History refresh complete.
CAPI Refresh Succeeded
CAPI User Logged in to Live using xxxxxx xxxxxx
*** Unknown Ship/Suit/Actor: { "megashipdocka", new Actor("Megashipdocka") },
*** Unknown Ship/Suit/Actor: { "poi_turretbunkera", new Actor("Poi Turretbunkera") },
*** Unknown Ship/Suit/Actor: { "poi_turretplatforma", new Actor("Poi Turretplatforma") },
Inara Data sent successfully (3 events)

**Comment by robbyxp1** [comment]
thanks
