### ISSUE TITLE
A couple New Modules for 18.0.2

### ISSUE THREAD

**Issue by Fixitman333** [EDDiscovery/EDDiscovery#3519]
*** Unknown Module { "decal_exobio_directionless", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Exobio Directionless") }, 
*** Unknown Module { "paintjob_sidewinder_tactical_grey", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Sidewinder Tactical Grey") },

**Comment by robbyxp1** [comment]
Thanks
