### ISSUE TITLE
Even more "Unknown Modules" after upgrade to 18.0.2

### ISSUE THREAD

**Issue by bal6765** [EDDiscovery/EDDiscovery#3520]
*** Unknown Module { "decal_met_brewercorporation_gold", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Met Brewercorporation Gold") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "decal_met_exploration_silver", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Met Exploration Silver") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Slots unknown Turret2
*** Slots unknown Turret2
*** Unknown Module { "bobble_trophy_trade", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Bobble Trophy Trade") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Ship/Suit/Actor: { "thargonswarm", new Actor("Thargonswarm") },
*** Unknown Ship/Suit/Actor: { "titan", new Actor("Titan") },
*** Unknown Ship/Suit/Actor: { "thargonswarm", new Actor("Thargonswarm") }

**Comment by robbyxp1** [comment]
Thanks
