### ISSUE TITLE
'Unknown Module' still appearing

### ISSUE THREAD

**Issue by Banjomel** [EDDiscovery/EDDiscovery#3521]
Reading travel history
*** Unknown Module { "decal_military_elite", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Military Elite") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "decal_titanreward2_black", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Titanreward 2 Black") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_diamondbackxl_mechanist_05", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Diamondbackxl Mechanist 5") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 17/07/2024 20:09:10 to 18/07/2024

**Comment by robbyxp1** [comment]
It will do until I produce a new version, which will be shortly
