### ISSUE TITLE
Multicrew events weren't ignored. 

### ISSUE THREAD

**Issue by sunqian119** [EDDiscovery/EDDiscovery#3523]
Multicrew events weren't ignored. Fixed and sent to Robby for review.

![Screenshot 2023-03-03 150406](https://user-images.githubusercontent.com/59618179/222742219-e05f4560-8096-4587-a2f6-5e33181577a6.png)

_Originally posted by @Eahlstan in https://github.com/EDDiscovery/EDDiscovery/issues/3389#issuecomment-1453590836_

**Comment by sunqian119** [comment]
hello, this issue occurs in 18.0.3 again, and i don't play in multicrew after that time.
![EDDISCOVERY BUG](https://github.com/user-attachments/assets/e1b2b551-47fa-479b-a33c-518bb78c2563)

**Comment by sunqian119** [comment]
the same to 2d map

**Comment by robbyxp1** [comment]
The next version, out today, may fix this. Please try it and let us know.

**Comment by sunqian119** [comment]
> The next version, out tomorrow, may fix this. Please try it and let us know.

It doesn't work. and I sent you my latest journal logs by email, hope it will be helpful.

**Comment by Eahlstan** [comment]
I can't reproduce this in any version. Please restart EDD, reopen the 3D map, screenshot it if it's still like that with the map options visible.

**Comment by robbyxp1** [comment]
I can't repo it either from the journal logs.  Maybe something you imported (such as from EDSM) which is not present in the journal files did this?

**Comment by sunqian119** [comment]
> I can't repo it either from the journal logs. Maybe something you imported (such as from EDSM) which is not present in the journal files did this?

Yeah, my flight routes in EDSM map are also in chaos. data could be uploaded in an earlier version that had the bug, and sync form EDSM all the time.
Now, I cleared all user data and re-install it. Everything works fine.
thanks a lot.

**Comment by sunqian119** [comment]
> I can't reproduce this in any version. Please restart EDD, reopen the 3D map, screenshot it if it's still like that with the map options visible.

I cleared all user data and re-install it. the data sync form EDSM maybe is saved as user data.
