### ISSUE TITLE
EDD reads paint jobs as modules and a decal as unrecognised modules

### ISSUE THREAD

**Issue by BobDenBeste** [EDDiscovery/EDDiscovery#3524]
After updating to version 18.0.3.0, EDD showed several "***Unkown Module" in the logs just after it read the travel history. Tried closing and opening it again, but the same thing happened. Might've had something to do with how I installed it. I downloaded the .exe file and ran it, did the necesary stuff, chose "Use local data" or whatever is's called exactly instead when it asked where it should store the appdata and then finished up the installation and that's when it began.

Here the full logs for when I first opened the new version

Scanning for bmp screenshots in C:\Users\willi\OneDrive\Billeder\Frontier Developments\Elite Dangerous
*** Web server is disabled ***
Profile Default Loaded
Loaded Bindings C:\Users\willi\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\Custom.4.0.binds
CAPI Installed
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
*** Unknown Module { "paintjob_diamondbackxl_militaire_earth_yellow", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Diamondbackxl Militaire Earth Yellow") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_federation_corvette_operator_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Corvette Operator Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_feddropship_mkii_icarus_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Feddropship Mkii Icarus Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "decal_military_gunslinger", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Military Gunslinger") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_federation_corvette_razormetal_gold", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Corvette Razormetal Gold") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_federation_gunship_operator_green", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Gunship Operator Green") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_eagle_lrpo_azure", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Eagle Lrpo Azure") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
History refresh complete.
CAPI Refresh Succeeded
CAPI User Logged in to Live using BobDenBeste
Inara Data sent successfully (3 events)

Second time's logs:

Scanning for bmp screenshots in C:\Users\willi\OneDrive\Billeder\Frontier Developments\Elite Dangerous
*** Web server is disabled ***
Profile Default Loaded
Loaded Bindings C:\Users\willi\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\Custom.4.0.binds
CAPI Installed
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
*** Unknown Module { "paintjob_diamondbackxl_militaire_earth_yellow", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Diamondbackxl Militaire Earth Yellow") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_federation_corvette_operator_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Corvette Operator Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_feddropship_mkii_icarus_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Feddropship Mkii Icarus Red") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "decal_military_gunslinger", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Military Gunslinger") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_federation_corvette_razormetal_gold", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Corvette Razormetal Gold") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_federation_gunship_operator_green", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Gunship Operator Green") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_eagle_lrpo_azure", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Eagle Lrpo Azure") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
History refresh complete.
CAPI Refresh Succeeded
CAPI User Logged in to Live using BobDenBeste
Inara Data sent successfully (3 events)

**Comment by Eahlstan** [comment]
Thanks for the report, added the unknown modules to our list.

Note: As it says in the error message this doesn't affect the work of EDD at all, so you can continue using it without any problems.
