### ISSUE TITLE
Unknown Module

### ISSUE THREAD

**Issue by Pandahma** [EDDiscovery/EDDiscovery#3525]
Since updating to version 18.0.2, I have received the following error messages.

*** Unknown Module { "paintjob_anaconda_industrial_02", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Anaconda Industrial 2") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "anaconda_industrial1_wings1", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Anaconda Industrial 1 Wings 1") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists

.........................

*** Missing Translate ID: ScanDisplayUserControl.Genuses: "! Genuses !" @

**Comment by Eahlstan** [comment]
Thanks for the report, added them to our list.
