### ISSUE TITLE
Paint Jobs message

### ISSUE THREAD

**Issue by Tredwell** [EDDiscovery/EDDiscovery#3526]
*** Unknown Module { "paintjob_federation_corvette_vibrant_yellow", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Corvette Vibrant Yellow") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_federation_corvette_winter1_02", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Corvette Winter 1 2") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_diamondbackxl_spring_04", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Diamondbackxl Spring 4") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_federation_corvette_colourgeo_orange", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Corvette Colourgeo Orange") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_anaconda_galnet_galnet", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Anaconda Galnet Galnet") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_diamondbackxl_christmas_03", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Diamondbackxl Christmas 3") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists

**Comment by Tredwell** [comment]
The message end: It would be nice to report it to us.

**Comment by robbyxp1** [comment]
Thanks
