### ISSUE TITLE
Messages on startup of latest version (fresh upgrade)

### ISSUE THREAD

**Issue by SenorKarlos** [EDDiscovery/EDDiscovery#3528]
*** Unknown Module { "paintjob_cutter_fullmetal_brass", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Cutter Fullmetal Brass") }, - this will not affect operation but it would be nice to report it to us so we can add it to known module lists
**** Unknown crime type onFoot_assault
**** Unknown crime type onFoot_assault
**** Unknown crime type onFoot_assault
**** Unknown crime type onFoot_assault
**** Unknown crime type onFoot_assault
**** Unknown crime type onFoot_assault
**** Unknown crime type onFoot_assault
**** Unknown crime type onFoot_assault

I haven't done on foot content in ages nor do I have any bounties or notoriety currently

**Comment by robbyxp1** [comment]
Thanks
