### ISSUE TITLE
18.0.4.0 Unknown Modifier

### ISSUE THREAD

**Issue by FatLes12** [EDDiscovery/EDDiscovery#3529]
*** Engineering unknown modifier Hpt_guardian_gausscannon_fixed_small GuardianModule_Sturdy  GuardianModuleResistance
*** Engineering unknown modifier Hpt_guardian_gausscannon_fixed_small GuardianModule_Sturdy  GuardianModuleResistance

**Comment by robbyxp1** [comment]
Could you please post the full journal file loadout in here (you can see it in the journal file of the ship with GuardianModuleResistance on).  I need the journal line, starting with timestamp etc..

thanks

**Comment by robbyxp1** [comment]
Sorted, thanks for the report.

**Comment by FatLes12** [comment]
Sorry, I was away on holiday last week - do you still need the journal?

**Comment by Eahlstan** [comment]
No thanks. I found one with the same bug in our collected stash.
