### ISSUE TITLE
Missing Paint Jobs

### ISSUE THREAD

**Issue by Flying-Fin** [EDDiscovery/EDDiscovery#3531]
ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Cobra Mk III Merc") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_vulture_vibrant_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Vulture Vibrant Red") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists

**Comment by robbyxp1** [comment]
Thanks
