### ISSUE TITLE
Unknown Modules & Unknown Ship/Suit/Actor

### ISSUE THREAD

**Issue by mjwish** [EDDiscovery/EDDiscovery#3532]
*** Unknown Module { "paintjob_vulture_faction1_04", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Vulture Faction 1 4") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_federation_corvette_predator_lime", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Corvette Predator Lime") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_orca_ember_purple", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Orca Ember Purple") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_type9_militarystripe_green", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Type 9 Militarystripe Green") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Ship/Suit/Actor: { "outpostcommercial", new Actor("Outpostcommercial") },
*** Unknown Module { "paintjob_diamondback_predator_teal", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Diamondback Predator Teal") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists

**Comment by SirAdams** [comment]
*** Unknown Module { "paintjob_asp_icarus_yellow", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Asp Icarus Yellow") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists

**Comment by robbyxp1** [comment]
Thanks
