### ISSUE TITLE
Unknown Mudules

### ISSUE THREAD

**Issue by Pit1962** [EDDiscovery/EDDiscovery#3536]
Aktualiserung der Historie abgeschlossen.
*** Unknown Module { "paintjob_vulture_vibrant_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Vulture Vibrant Red") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_hauler_vibrant_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Hauler Vibrant Red") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_empire_fighter_gladiator_redblack", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Empire Fighter Gladiator Red Black") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_type9_largelogometallic_05", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Type 9 Largelogometallic 5") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
Inara Data sent successfully (3 events)
*** Unknown Ship/Suit/Actor: { "outpostcommercial", new Actor("Outpostcommercial") },
*** Unknown Module { "decal_military_warrior", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Military Warrior") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_asp_mechanist_01", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Asp Mechanist 1") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Missing Translate ID: Allegiances.PlayerPilots: "! Player Pilots !" @
Sent 10 Events to EDSM
Inara Data sent successfully (50 events)

**Comment by rmw00** [comment]
Similar:

*** Unknown Module { "paintjob_dolphin_corporatefleet_fleetb", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Dolphin Corporatefleet Fleetb") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_cutter_synth_white", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Cutter Synth White") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_federation_corvette_corrosive_04", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Corvette Corrosive 4") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_type9_militarystripe_blue", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Type 9 Militarystripe Blue") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_orca_geometric_purple", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Orca Geometric Purple") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_vulture_operator_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Vulture Operator Red") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists

**Comment by HolliDolli** [comment]
metoo:

*** Unknown Module { "paintjob_sidewinder_default_02", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Sidewinder Default 2") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_asp_halloween02_012", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Asp Halloween 2 12") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
