### ISSUE TITLE
Error when application startup (18.0.5.0)

### ISSUE THREAD

**Issue by kennyshu** [EDDiscovery/EDDiscovery#3538]
Here is the error when I run the program (portable version):
---
?前正在??位于C:\Users\xxx\Pictures\Frontier Developments\Elite Dangerous文件?的bmp格式的截?
*** Web server is disabled ***
配置文件“Default”已加?
Loaded Bindings C:\Users\xxx\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\Custom.4.1.binds
CAPI Installed
?查新的?航?据中
??，??以及?河星?已加?。
?取航行??中
History Refresh Error: SQLLiteExtensions.SQLProcessingThreadException: database disk image is malformed
database disk image is malformed ---> System.Data.SQLite.SQLiteException: database disk image is malformed
database disk image is malformed
   於 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   於 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   於 System.Data.SQLite.SQLiteDataReader.NextResult()
   於 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   於 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   於 EliteDangerousCore.JournalEntry.<>c__DisplayClass26_0.<GetTableData>b__0(SQLiteConnectionUser cn) 於 C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntryDB.cs: 行 342
   於 SQLLiteExtensions.Job`1.Exec() 於 C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs: 行 487
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 SQLLiteExtensions.Job`1.Wait() 於 C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs: 行 507
   於 SQLLiteExtensions.SQLAdvProcessingThread`1.ExecuteAndWait[T](Func`1 func, Boolean write, UInt32 warnthreshold, String jobname) 於 C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs: 行 392
   於 SQLLiteExtensions.SQLAdvProcessingThread`1.DBRead[T](Func`2 func, UInt32 warnthreshold, String jobname) 於 C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs: 行 46
   於 EliteDangerousCore.JournalEntry.GetTableData(CancellationToken cancel, Int32 commander, Nullable`1 startdateutc, Nullable`1 enddateutc, JournalTypeEnum[] ids, Nullable`1 allidsafterutc) 於 C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntryDB.cs: 行 0
   於 EliteDangerousCore.HistoryList.LoadHistory(HistoryList hist, Action`2 reportProgress, CancellationToken cancelRequested, Int32 commanderid, String cmdname, Int32 fullhistoryloaddaylimit, JournalTypeEnum[] loadedbeforelimitids, Nullable`1 maxdateload) 於 C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryList.cs: 行 147
   於 EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) 於 C:\Code\EDDiscovery\EDDiscovery\EDD\EDDiscoveryControllerHistory.cs: 行 0
同步至EDSM和EDDB已被禁用，??置面板重新??
航行??刷新完成。
CAPI Refresh Succeeded
CAPI User Logged in to Live using xxx
---

I've tried delete the "Data" folder and setup all the settings again. It works for a while (couple days), and then the same error happened again. 

![image](https://github.com/user-attachments/assets/c44ac57f-a41b-499d-97eb-465996154d42)

**Comment by robbyxp1** [comment]
Your user database is broken.  "database disk image is malformed"

then only thing to do is use safe mode (hold down shift and launch the program) then select "Delete/Rebuild User DB"

Hopefully you still have your journal logs.

Causes of database corruption are widely varied.

**Comment by kennyshu** [comment]
> Your user database is broken. "database disk image is malformed"
> 
> then only thing to do is use safe mode (hold down shift and launch the program) then select "Delete/Rebuild User DB"
> 
> Hopefully you still have your journal logs.
> 
> Causes of database corruption are widely varied.

That "Delete/Rebuild User DB" works. Thanks!
I propbably know why this happened. Last time I select download start database from EDSM, and when I close the application it takes TOO LONG... So I force close it.
