### ISSUE TITLE
CAPI problem

### ISSUE THREAD

**Issue by Banjomel** [EDDiscovery/EDDiscovery#3539]
Starting EDD opens a Frontier authorisation page which seems to do nothing. EDD reports CAPI failure as : 'CAPI awaiting callback' and 'CAPI Authorisation Failed.

Regards,
Banjo

**Comment by robbyxp1** [comment]
Most probable a temp web situation or a frontier capi problem, which we are not logging properly and can't do anything about.

Try logging in again.

**Comment by Banjomel** [comment]
I agree with your view that it’s a Frontier problem. I can get to the login page but the button is unresponsive.
Thanks,
Mel
Sent from my iPhone

On 3 Aug 2024, at 10:50, Rob ***@***.***> wrote:

﻿

Most probable a temp web situation or a frontier capi problem, which we are not logging properly and can't do anything about.

Try logging in again.
