### ISSUE TITLE
reporting not an error but unknown stuff ;)

### ISSUE THREAD

**Issue by JappeF** [EDDiscovery/EDDiscovery#3540]
*** Unknown Module { "nameplate_alliance01_white", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Nameplate Alliance 1 White") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_orca_vibrant_purple", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Orca Vibrant Purple") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "nameplate_alliance02_white", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Nameplate Alliance 2 White") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_independant_trader_vibrant_green", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Independant Trader Vibrant Green") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_testbuggy_luminous_white", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job SRV Luminous White") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "nameplate_alliance02_black", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Nameplate Alliance 2 Black") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists

**Comment by Ohmegalisk** [comment]
*** Unknown Module { "bobble_trophy_political", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Bobble Trophy Political") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "bobble_trophy_political_b", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Bobble Trophy Political B") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "bobble_trophy_political_s", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Bobble Trophy Political S") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_diamondbackxl_tactical_green", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Diamondbackxl Tactical Green") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_federation_corvette_militaire_sand", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Corvette Militaire Sand") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_anaconda_squadron_orange", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Anaconda Squadron Orange") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "decal_playergroup_galcop", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Playergroup Galcop") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_type9_military_operator_pink", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Type 9 Military Operator Pink") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
