### ISSUE TITLE
Not parsing gap in logs

### ISSUE THREAD

**Issue by SenorKarlos** [EDDiscovery/EDDiscovery#3551]
Between these dates I had several play sessions where EDD was not running, PC rebooted and I forgot to relaunch before playing.

Normally it just catches up, but this time it seems to refuse. There are journal files locally for the sessions played on those days. I was also on 18.0.6.0 and updated to 18.0.8.0 when noticing the issue, I let it finish 'catching up' before closing and installing the new one.

I'm also not entirely sure it matters, but I am 99% sure it has always filled in the blanks, there were times I was on actual expeditions and forgot it until mid-session or missing one entirely, and it would all be there

![image](https://github.com/user-attachments/assets/2d26305e-d6ea-48e9-8215-0a0e6efd79fe)

**Comment by klightspeed** [comment]
Does it fill in the gap when you use `Admin` -> `Re-scan all journal files`?

**Comment by SenorKarlos** [comment]
I did try that (forgot to mention) and no, it doesn't

**Comment by klightspeed** [comment]
If you have a look at the journal files in the gap, do they have a `LoadGame` event with the appropriate commander and game version?

**Comment by SenorKarlos** [comment]
They appear to yes

**Comment by Eahlstan** [comment]
Did you ever delete a commander in EDD?

**Comment by SenorKarlos** [comment]
never

**Comment by Eahlstan** [comment]
Hm. Somehow I doubt that.
This whole thing reads exactly like the unintended consequences that occurred in 18.0.6 when the handling of deleted commanders was changed. (Journal reading prioritized low ID commanders over non-deleted commanders with the same name and thus events were linked to deleted (actually hidden) commanders.)

Anyways: If you still got all your journals the easy fix is to go to the safe mode menu (can be done using the settings panel) and click on "delete journals & commanders". This way you'll keep your general EDD settings and all journals will be reread on a new start which will recreate all commanders (you'll have to re-enter all API keys on them).
If you don't have all your journals you'd need to edit the DB to see what happened.

I wonder if the "undelete" button on your settings panel is clickable...

**Comment by SenorKarlos** [comment]
I've literally had one commander since day one.... other than the Odyssey prelaunch. I did use the same name, but did not run EDD while testing and afaik should not have any conflict.

I can see literally no reason for this occurrence. I'll try just resetting as suggested, but that answers nothing, just plasters it over.

Ty anywho, I'll let you know if it happens again I suppose :)

**Comment by Eahlstan** [comment]
Don't forget to set your API-keys and sync options in your commanders options.
