### ISSUE TITLE
Problems with installing EDDiscovery-18.0.8 on Windows 11

### ISSUE THREAD

**Issue by LuckyLuigi** [EDDiscovery/EDDiscovery#3552]
My single User account is also Administrator.
When I try to run the exe as before, I get you must install this program as an administrator user.
If I wait long, I get the UAC popup
Afterwards I get the error popup again
If I wait long, the installer does start and work.
It's just odd, I haven't had issues in years of upgrading.

Also in the log it says
*** Unknown Module { "paintjob_type9_militaire_earth_yellow", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Type 9 Militaire Earth Yellow") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_cobramkiii_hotrod_03", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Cobra Mk III Hotrod 3") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists

Thanks for making the best tool in ED universe :)

**Comment by klightspeed** [comment]
The long delay with the installer sounds like it's being executed from either slow storage or a network drive (e.g. OneDrive)

**Comment by LuckyLuigi** [comment]
The installer is run from my desktop which is on my SSD.
________________________________
Van: Ben Peddell ***@***.***>
Verzonden: maandag 19 augustus 2024 00:12
Aan: EDDiscovery/EDDiscovery ***@***.***>
CC: LuckyLuigi ***@***.***>; Author ***@***.***>
Onderwerp: Re: [EDDiscovery/EDDiscovery] Problems with installing EDDiscovery-18.0.8 on Windows 11 (Issue #3552)


The long delay with the installer sounds like it's being executed from either slow storage or a network drive (e.g. OneDrive)

**Comment by Eahlstan** [comment]
I just tried it on my Windows 11 machine (all updates installed).
There was neither a "you have to run this as admin" dialogue, nor a delay when installing. Just the usual "are you sure you want to trust this app to make changes to your system" dialogue.
So whatever it is that causes those warnings and the delay on your side: It's a Windows problem, not an EDDiscovery problem. Most likely some sort of UAC setting (admin warning) and security software (delay). There's nothing we can do about this and none of us will recommend changingyour AC and/or security software settings.

**Comment by LuckyLuigi** [comment]
It's what I expected but I thought I'd let you know in case other also run into this problem.
Thanks for your time 🙂
________________________________
Van: Eahlstan ***@***.***>
Verzonden: maandag 19 augustus 2024 00:43
Aan: EDDiscovery/EDDiscovery ***@***.***>
CC: LuckyLuigi ***@***.***>; Author ***@***.***>
Onderwerp: Re: [EDDiscovery/EDDiscovery] Problems with installing EDDiscovery-18.0.8 on Windows 11 (Issue #3552)


I just tried it on my Windows 11 machine (all updates installed).
There was neither a "you have to run this as admin" dialogue, nor a delay when installing. Just the usual "are you sure you want to trust this app to make changes to your system" dialogue.
So whatever it is that causes those warnings and the delay on your side: It's a Windows problem, not an EDDiscovery problem. Most likely some sort of UAC setting (admin warning) and security software (delay). There's nothing we can do about this and none of us will recommend changingyour AC and/or security software settings.

**Comment by Eahlstan** [comment]
Just for info: A few days ago someone had an extremely slow EDD. In this case (and a few others in the distant past) it was caused by Acronis.
