### ISSUE TITLE
[Request] Alternative view for Materials tab. 

### ISSUE THREAD

**Issue by Jugom** [EDDiscovery/EDDiscovery#3561]
The current Materials Tab has all the materials information you might ever need. It is however not great for having a quick and easy general overview of your current materials situation. 

It would be nice to have an alternative, simplified version just to know who's full and who's empty. 
Here's a dirty spreadsheet of the suggested distribution. don't mind he aesthetics, didn't spend much doing it =]

![image](https://github.com/user-attachments/assets/9edf59ba-2c2c-4b3e-9a2d-1fc0bc5ad556)

Additionally, if you could revisit #3070, the % column for the current materials tab wouldn't hurt either so we can sort by it.

cheers.

**Comment by robbyxp1** [comment]
Very nice idea. I'll move this to the worklist.
