### ISSUE TITLE
Malformed database disk image, via GetSystemBySqDistanceFrom

### ISSUE THREAD

**Issue by TeamGormless** [EDDiscovery/EDDiscovery#3562]
Hello EDD. Love the program, I've been using it for years now. This is the only issue I've ever had.

In the current version (18.0.9.0) I get a fatal exception on start up. Stack trace is attached.

Some additional info: 
- This exception happens on start up, after the 'creating journal entries' stage and the 'creating journal history' stage. During the 'refresh displays' stage.
- When I upgrade to a new version of EDD, I always copy my Data folder over from the previous version. If this is what the database disk image is referring to, there could be some inconsistency in how that Data directory is managed between version of EDD and/or Elite? Just a thought, possibly a red herring.

[ed_discovery_error_18_0_9_0.txt](https://github.com/user-attachments/files/17001806/ed_discovery_error_18_0_9_0.txt)
[ed_discovery_console_trace.txt](https://github.com/user-attachments/files/17001845/ed_discovery_console_trace.txt)

**Comment by robbyxp1** [comment]
Your system database is dead - for whatever reason. Could be a multitude of reasons.

Just delete it (EDDSystems.sqlite)  and redownload it (takes a while).

**Comment by TeamGormless** [comment]
Yep that fixed the issue. Thanks for the speedy reply!

**Comment by robbyxp1** [comment]
np
