### ISSUE TITLE
Unknown Module { "paintjob_dolphin_clown_01"

### ISSUE THREAD

**Issue by alanasaba** [EDDiscovery/EDDiscovery#3563]
*** Unknown Module { "paintjob_dolphin_clown_01", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Dolphin Clown 1") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists

**Comment by robbyxp1** [comment]
thanks
