### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by dmrazor** [EDDiscovery/EDDiscovery#3567]
### Description
Closing the game, which got stuck so I killed the task in Taskmanager

### Additional Information
No additional info available

### Exception Details:
>EDDiscovery v18.0.9.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>OpenTK.Graphics.GraphicsContextException: Failed to make context 65537 current. Error: 0
>   at OpenTK.Platform.Windows.WinGLContext.MakeCurrent(IWindowInfo window) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Platform\Windows\WinGLContext.cs:line 279
>   at EDDiscovery.UserControls.UserControl3DMap.SystemTick(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\UserControl3DMap.cs:line 111
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
Were you affected by #3271?

**Comment by dmrazor** [comment]
Not sure. I wasn't actively using the 3D map in EDD but it is on one of my tabs.

**Comment by robbyxp1** [comment]
Lets presume that was it.
