### ISSUE TITLE
Record on the log

### ISSUE THREAD

**Issue by Tredwell** [EDDiscovery/EDDiscovery#3568]
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
*** Unknown Module { "decal_ruby1", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Ruby 1") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_belugaliner_geometric_yellow", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Beluga Liner Geometric Yellow") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 30/09/2024 05:06:37 to 30/09/2024 17:06:37
History refresh complete.
CAPI Refresh Succeeded
CAPI User Logged in to Live using Tredwell
Systems update complete with 5,529 systems
*** Unknown Module { "paintjob_typex_operator_pink", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Typex Operator Pink") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
Inara Data sent successfully (3 events)

**Comment by robbyxp1** [comment]
thanks
