### ISSUE TITLE
Custom Group Filter on Materials Tab Not Saving

### ISSUE THREAD

**Issue by TechieInHell** [EDDiscovery/EDDiscovery#3571]
Steps to reproduce:
Show materials tab.
Click Filter icon in top left of tab.
Select a subset of materials, then click Create New Group
New group will be available under the filter menu and works as expected.
Close the application and open; all custom groups will be gone.

**Comment by robbyxp1** [comment]
Noted, thanks

**Comment by robbyxp1** [comment]
Fixed, will be in 18.1 this weekend. Thanks for the report
