### ISSUE TITLE
Unknown Module alert in travel history log

### ISSUE THREAD

**Issue by jmunoz2141** [EDDiscovery/EDDiscovery#3575]
The following registered in the travel history:
*** Unknown Module { "paintjob_python_nx_ruby_01", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Python Mk II Ruby 1") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists

**Comment by Chequers2** [comment]
The following registered in the travel history:

*** Unknown Module { "paintjob_ferdelance_slipstream_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Fer-De-Lance Slipstream Red") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "decal_ruby1_gold", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Ruby 1 Gold") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_diamondback_salvage_03", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Diamondback Salvage 3") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists

**Comment by Imathil** [comment]
*** Unknown Module { "paintjob_independant_trader_militaire_forest_green", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Independant Trader Militaire Forest Green") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_type9_military_squadron_green", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Type 10 Defender Squadron Green") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "decal_salvage", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Salvage") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_type9_military_tactical_green", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Type 10 Defender Tactical Green") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_independant_trader_militaire_dark_green", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Independant Trader Militaire Dark Green") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists

**Comment by zedayseekay23** [comment]
*** Unknown Module { "paintjob_feddropship_mkii_vibrant_green", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Feddropship Mk II Vibrant Green") }

**Comment by danieloneill** [comment]
*** Unknown Module { "paintjob_diamondbackxl_operator_pink", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Diamondbackxl Operator Pink") }

Are you collecting screenshots for these? If so, what's the preferred type?

**Comment by jellowiggler** [comment]
*** Unknown Module { "decal_titanreward5_black", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Decal Titanreward 5 Black") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
