### ISSUE TITLE
New ship and module types

### ISSUE THREAD

**Issue by skoops** [EDDiscovery/EDDiscovery#3577]
As of client 4.0 there are new ships available now. 
I got a "Mandalay" and - as expected - it wasn't known to EDDiscovery, so I'd like to report the error messages and module/ship IDs that are being used in frontier production clients:

*** Unknown FD ship ID:mandalay
*** Unknown Ship Name:mandalay
*** Unknown Module { "paintjob_mandalay_02_02", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Mandalay 2 2") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "mandalay_armour_grade1", new ShipModule(-1,ShipModule.ModuleTypes.UnknownType,"Mandalay Armour Grade 1") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "mandalay_shipkita_spoiler1", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Mandalay Shipkita Spoiler 1") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "mandalay_shipkita_wings1", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Mandalay Shipkita Wings 1") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "mandalay_shipkita_bumper1", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Mandalay Shipkita Bumper 1") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "mandalay_cockpit", new ShipModule(-1,ShipModule.ModuleTypes.UnknownType,"Mandalay Cockpit") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown FD ship ID:mandalay
*** Unknown Ship Name:mandalay

**Comment by sdang-git** [comment]
A few more:
*** Unknown Module { "mandalay_armour_grade2", new ShipModule(-1,ShipModule.ModuleTypes.UnknownType,"Mandalay Armour Grade 2") },
*** Unknown Module { "mandalay_armour_grade3", new ShipModule(-1,ShipModule.ModuleTypes.UnknownType,"Mandalay Armour Grade 3") },
*** Unknown Module { "mandalay_armour_mirrored", new ShipModule(-1,ShipModule.ModuleTypes.UnknownType,"Mandalay Armour Mirrored") },
*** Unknown Module { "mandalay_armour_reactive", new ShipModule(-1,ShipModule.ModuleTypes.UnknownType,"Mandalay Armour Reactive") },

**Comment by robbyxp1** [comment]
Thank you, new version today
