### ISSUE TITLE
Star database not updating

### ISSUE THREAD

**Issue by sezlony** [EDDiscovery/EDDiscovery#3581]
After a long time started playing ED again and installed a newer version of EDDiscovery also.

As far as I remember, it used to start downloading updates immediately after booting up and there were status lines at the bottom, showing how many systems it has updated.

Now it does nothing - seemingly, no network traffic, no disk operations, nothing. After hours it still shows "star database update complete 0" and eddsystems.sqlite file is 68k in size only.

What did I mess up, or how can I fix it?

**Comment by Eahlstan** [comment]
EDSM dumps are broken for several weeks now. Please use Spansh as source.
