### ISSUE TITLE
Crash on Materials tab

### ISSUE THREAD

**Issue by Hojo-Norem** [EDDiscovery/EDDiscovery#3584]
### Description
Clicking the icon to switch between display styles causes a 'continuable' crash.  Clicking the icon again switches to a blank window.  Restarting the app at this point brings back the new style.

### Exception Details:
>EDDiscovery v18.1.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: Nullable object must have a value.
>   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>   at EDDiscovery.UserControls.UserControlMaterialCommodities.DisplayMCMR(Boolean repaintgrid) in C:\Code\EDDiscovery2\EDDiscovery\UserControls\CurrentState\UserControlMaterialCommodities.cs:line 467
>   at EDDiscovery.UserControls.UserControlMaterialCommodities.Display(Nullable`1 mcl, Boolean repaintgrid) in C:\Code\EDDiscovery2\EDDiscovery\UserControls\CurrentState\UserControlMaterialCommodities.cs:line 348
>   at EDDiscovery.UserControls.UserControlMaterialCommodities.PerformPanelOperation(UserControlCommonBase sender, Object actionobj) in C:\Code\EDDiscovery2\EDDiscovery\UserControls\CurrentState\UserControlMaterialCommodities.cs:line 321
>   at EDDiscovery.MajorTabControl.RequestPanelOperationPrimaryTab(UserControlCommonBase sender, Object actionobj) in C:\Code\EDDiscovery2\EDDiscovery\TabsPanelsAndPopOuts\MajorTabControlPanelActions.cs:line 38
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery2\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 626
>   at EDDiscovery.UserControls.UserControlTravelGrid.Display(HistoryList hl, Boolean disablesorting) in C:\Code\EDDiscovery2\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 317
>   at EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged() in C:\Code\EDDiscovery2\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 212
>   at System.Action.Invoke()
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshCompleteonUI(HistoryList hist) in C:\Code\EDDiscovery2\EDDiscovery\EDD\EDDiscoveryControllerHistory.cs:line 296
>===== END =====
>```

**Comment by Eahlstan** [comment]
Can you please upload your journal from the session when this happened so I can see your material counts?

**Comment by Hojo-Norem** [comment]
[Journal.2024-11-07T223434.01.zip](https://github.com/user-attachments/files/17689907/Journal.2024-11-07T223434.01.zip)
Hi.  This is the one that was current at the time.

**Comment by robbyxp1** [comment]
Found it. I will do another version later today to fix it. Thanks for the report.
