### ISSUE TITLE
Comma missing for high values

### ISSUE THREAD

**Issue by Greymagic27** [EDDiscovery/EDDiscovery#3586]
Hi

Not sure if it's just me not having usecd it for a while but I'm sure there used to be a comma when values were high. Now it makes it hard to read if they are large numbers.

![image](https://github.com/user-attachments/assets/b45de994-dce2-4eae-bc3f-af178383f866)

**Comment by Eahlstan** [comment]
Already fixed in the code, will be in the next version.

Thanks for the report.

**Comment by Greymagic27** [comment]
Thanks :)
