### ISSUE TITLE
Estimated values tab '0' button does not hide 0 values

### ISSUE THREAD

**Issue by psdevil** [EDDiscovery/EDDiscovery#3587]
In the 18.1.2 release, selecting the '0' button on the 'Estimated Values' tab to hide everything with a zero value no longer works.

Toggling it on and off many times has no effect.

![image](https://github.com/user-attachments/assets/2115f407-9d50-4f76-a2b0-4fd721707040)

**Comment by Eahlstan** [comment]
This code definitely wasn't deleted in error when changing other things. No, no, no.

Thanks for the report.

**Comment by robbyxp1** [comment]
Noted, idiot told off, will be in next version. thanks for the report.
