### ISSUE TITLE
Times from is set to +1

### ISSUE THREAD

**Issue by GoldenGnu** [EDDiscovery/EDDiscovery#3589]
When setting the time:
![2024-11-14 (4)](https://github.com/user-attachments/assets/bf4eca8c-da69-4040-af1b-469d09b2791b)
The from datetime is set to +1 hour (21 instead of 20). I don't know if it's important, but, I am in a GMT+1 timezone
![2024-11-14 (5)](https://github.com/user-attachments/assets/6cd46e01-72e0-4a6b-8c42-9960b31fbf3e)

Using version 18.1.2.0

**Comment by robbyxp1** [comment]
Its a TimeZone issue vs UTC, i'll double check the code. thanks

**Comment by Eahlstan** [comment]
See my comment on the commit and on Discord.

Reopening so we don't forget about it.
