### ISSUE TITLE
Show indication from EDSM that this star is a first discovery

### ISSUE THREAD

**Issue by robbyxp1** [EDDiscovery/EDDiscovery#359]
In the latest EDSM, we have a response field to a new star..

systemCreated=true

Seen by us when SendTravelLog gets the json response to a submission.

So, store this in the travel history, and show an indication on screen that this is an EDSM first discovered item

This may be delayed due to our refactoring of the db.

**Comment by klightspeed** [comment]
We can store this in either the VisitedSystems / JournalFSDJumps table or in a separate FirstDiscoveredSystems table.

It would be nice if there were an EDSM API to get what other systems the commander has been the first to discover on EDSM.

**Comment by robbyxp1** [comment]
I vote for a separate table ;-)

**Comment by finwen** [comment]
we can store it in json data too. No need for a table or extra columns
then.  Little slower to search but not a problem i think for this type of
data.


2016-08-30 19:38 GMT+02:00 robbyxp1 <notifications@github.com>:

**Comment by paparomeo1969** [comment]
In the Player Journal the event for selling cartogtaphic data contains a section listing the stellar bodies that have been discovered. So this could be used to pull and display stats on player's own discoveries.

**Comment by robbyxp1** [comment]
Removed from EDSM. Closing
