### ISSUE TITLE
Unknown Module

### ISSUE THREAD

**Issue by MardanteS** [EDDiscovery/EDDiscovery#3592]
*** Unknown Module { "paintjob_asp_shatter_01_03", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Asp Shatter 1 3") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_asp_autumn_07", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Asp Autumn 7") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists

**Comment by thorules** [comment]
*** Unknown Module { "paintjob_typex_3_military_tactical_blue", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Alliance Challenger Military Tactical Blue") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
