### ISSUE TITLE
crash when trying to mark multiple history grid entries

### ISSUE THREAD

**Issue by rwetmore** [EDDiscovery/EDDiscovery#3595]
when attempting to mark multiple ~~log~~ _history grid_ entries simultaneously the app crashes.  when this happens I also have a search filter applied to the ~~log~~ _history grid_.  

e.g. search "Analyse" then attempt to shift+click multiple entries.  right-click and mark.  that is when the app crashes (without fail)  

thanks!

### Exception Details:
>EDDiscovery v18.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlTravelGrid.quickMarkToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery2\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 1198
>   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by Eahlstan** [comment]
```rightclickhe was null```

This has nothing to do with filters, it happens when multiple rows are highlighted and then right clicking a cell to mark it.
It doesn't crash when right clicking on the index number to mark it - only clicking a cell crashes it.

Site note: There doesn't seem to be a way to mark multiple rows and once, is it possible to implement it?

**Comment by robbyxp1** [comment]
Thanks, fixed on master, missing:

            quickMarkToolStripMenuItem.Enabled = rightclickhe != null;
