### ISSUE TITLE
EDD Log indicates undocumented vanity modules

### ISSUE THREAD

**Issue by belpolaris** [EDDiscovery/EDDiscovery#3596]
*** Unknown Module { "paintjob_type8_convoy_05", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Type 8 Convoy 5") }

*** Unknown Module { "paintjob_python_nx_venom_10", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Python Mk II Venom 10") }

*** Unknown Module { "bobble_pp_arissalavignyduval", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Bobble Pp Arissalavignyduval") }

*** Unknown Module { "python_nx_venture_spoiler1", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Python Mk II Venture Spoiler 1") }

*** Unknown Module { "python_nx_venture_bumper1", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Python Mk II Venture Bumper 1") }

**Comment by patmc6** [comment]
here is another one

> *** Unknown Module { "paintjob_federation_corvette_colourgeo2_red", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Federation Corvette Colourgeo 2 Red") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
