### ISSUE TITLE
Crash on open 3D map for expedition

### ISSUE THREAD

**Issue by completelybaked** [EDDiscovery/EDDiscovery#3597]
### Description

Loaded active route as an expedition, forgot save it, clicked open 3d map. Immediate crash. Managed to save expedition after crash report was closed.

### Additional Information

[Journal.2024-11-23T112238.01.log](https://github.com/user-attachments/files/17905001/Journal.2024-11-23T112238.01.log)

![image](https://github.com/user-attachments/assets/89999f63-dfa9-4551-aaac-ad68fc2d2418)

Device name	DESKTOP-52JIA5P
Processor	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.60 GHz
Installed RAM	64.0 GB (63.8 GB usable)
Device ID	00C42518-2540-40DE-897E-A8A3AE6DA98B
Product ID	00325-81709-59800-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### Exception Details:
>EDDiscovery v18.0.9.0 An unhandled fatal exception has occurred.
>```
>==== BEGIN ====
>System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>   at OpenTK.Graphics.OpenGL4.GL.DrawElementsInstancedBaseVertexBaseInstance(PrimitiveType mode, Int32 count, DrawElementsType type, IntPtr indices, Int32 instancecount, Int32 basevertex, Int32 baseinstance) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Graphics\OpenGL4\GL4.cs:line 17747
>   at GLOFC.GL4.GLRenderableItem.Render()
>   at GLOFC.GL4.Controls.GLControlDisplay.Render(GLRenderState currentstate, UInt64 ts)
>   at System.Action`1.Invoke(T obj)
>   at GLOFC.WinForm.GLWinFormControl.GlControl_Paint(Object sender, PaintEventArgs e)
>   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
>   at OpenTK.GLControl.OnPaint(PaintEventArgs e) in I:\work\github\opentk\src\OpenTK.GLControl\GLControl.cs:line 287
>   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
>   at System.Windows.Forms.Control.WmPaint(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.UserControl.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```
[Journal.2024-11-23T112238.01.log](https://github.com/user-attachments/files/17905010/Journal.2024-11-23T112238.01.log)

**Comment by Eahlstan** [comment]
> Device name DESKTOP-52JIA5P Processor Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz 2.60 GHz Installed RAM 64.0 GB (63.8 GB usable) Device ID 00C42518-2540-40DE-897E-A8A3AE6DA98B Product ID 00325-81709-59800-AAOEM System type 64-bit operating system, x64-based processor Pen and touch No pen or touch input is available for this display


So no dedicated GPU?

**Comment by completelybaked** [comment]
Yes, sorry:
![image](https://github.com/user-attachments/assets/6c003650-df43-445c-baf6-2f31959d11f9)
and here's an export of system info--prolly more than you want, but more is better I reckon:
[SystemInfo_25NOV24.txt](https://github.com/user-attachments/files/17908389/SystemInfo_25NOV24.txt)

**Comment by completelybaked** [comment]
> This is a GPU related problem with the integrated GPU and its lack of compatibility with openGL 4.6.

OK, just wanted to share the details in my instance in case it helps at some point. ;)
Thanks for a nice application!!!

**Comment by Eahlstan** [comment]
> Yes, sorry: ![image](https://private-user-images.githubusercontent.com/3321852/389687470-6c003650-df43-445c-baf6-2f31959d11f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NzExMzYsIm5iZiI6MTczMjU3MDgzNiwicGF0aCI6Ii8zMzIxODUyLzM4OTY4NzQ3MC02YzAwMzY1MC1kZjQzLTQ0NWMtYmFmNi0yZjMxOTU5ZDExZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjVUMjE0MDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjY4ZmQxZDlmYjM5ZjM1YzI2MzNjNmFjYzlkNWE5ZmJhMDczY2Y3NDI0YjUwN2E3ODE4YmM3YzMyZWNlMmZkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.eMpe8xODwJmmmWmP3COtcvJNnSPQqVKXjloW7POhmJk) and here's an export of system info--prolly more than you want, but more is better I reckon: [SystemInfo_25NOV24.txt](https://github.com/user-attachments/files/17908389/SystemInfo_25NOV24.txt)

Well, there's a pinned issue here describing how to fix that.

**Comment by robbyxp1** [comment]
Closing, please configure EDD to use the better card as per the issue.

**Comment by completelybaked** [comment]
Thank you.


    On Tuesday, November 26, 2024 at 06:04:58 PM EST, Rob ***@***.***> wrote:  
 
 


Closing, please configure EDD to use the better card as per the issue.

**Comment by completelybaked** [comment]
Set up my laptop to use NVidia GPU. All good! Thanks again.
![image](https://github.com/user-attachments/assets/83e1b646-2cc5-4664-b0ac-0daec8032719)
