### ISSUE TITLE
Unable to select multiple lines in the Ledger grid

### ISSUE THREAD

**Issue by psdevil** [EDDiscovery/EDDiscovery#3598]
I tried to copy a number of entry lines but can only select a single line that does not copy either.

I have tried selecting lines other than starting with the first and failed to select all as well.

As stated earlier, using ^C to copy the single highlighted failed to go to the clipboard.

**Comment by robbyxp1** [comment]
You can only click on one row at a time so that the grid syncs with the graph below, this is per its design.

If you want to export the ledger, use the export option to CSV.

**Comment by psdevil** [comment]
I used to be able to use Ctrl-C (^C is ancient IT worker shorthand) to just select the lines I wanted 🙁
________________________________

**Comment by robbyxp1** [comment]
I can't let it select multiple lines - won't work with the chart.  And I'm not sure what help just copying one line is.
