### ISSUE TITLE
Search tab / Scans requires keyhole operation for search expression: field too small and can't be adjusted

### ISSUE THREAD

**Issue by athulin** [EDDiscovery/EDDiscovery#3601]
Latest version of EDDiscovery.

Problem:

The Search / Scans subtab starts with a 'create search expression' field.  Unfortunately, this field shows only one and a half expression part, and doesn't allow vertical size adjustment. This is how it looks like:

![{933F7605-E672-4015-B327-3004FA80516E}](https://github.com/user-attachments/assets/70388508-9d71-4bc8-8d56-a3d76033e0d5)

The second term of the 'and' term requires scrolling to see.  While it can be used, it is apt to errors and mistakes  in the user's mental reconstruction of the total expression,

Suggestion:  

Add a 'resize handle' between the upper field (search expression) and the lower fields (sort specification and search hits).

**Comment by Eahlstan** [comment]
>and doesn't allow vertical size adjustment

That's wrong. Move your mouse at the divider that's just above the headers of the grid and click and drag it to your liking.

There's no autoresize button coming, as it's impossible to autofit on every possible size (yours isn't even maximised.)

**Comment by robbyxp1** [comment]
Closing, not an issue.
