### ISSUE TITLE
Missing Item in Micro Resources List

### ISSUE THREAD

**Issue by DustyShoe** [EDDiscovery/EDDiscovery#3603]
Hello.

First, i'd like to thank you for awesome software i'm using every time i play ED.

I did notice that `Combatant Performance` Data item not present in micro resources list.

Cheers!

**Comment by Eahlstan** [comment]
Are you screening out items you don't have? If your "0" on the micro resources panel is read the answer is "yes".

![Screenshot 2024-12-08 205117](https://github.com/user-attachments/assets/f290129e-213d-4b86-97d8-3922ba11233c)

**Comment by DustyShoe** [comment]
Yeah, that was the case. Sorry for making trouble. Issue can be closed.

Cheers!
