### ISSUE TITLE
How to switch from EDSM to Spanish

### ISSUE THREAD

**Issue by danw-eth** [EDDiscovery/EDDiscovery#3604]
Hi Guys,
The latest update recommends switching to Spanish instead of EDSM.
But as hard as I try, I can't find the option in the settings.
Also searched the FAQ but there's no information on how to switch to spanish.
How do I make the change?
many thanks

**Comment by Eahlstan** [comment]
Click "reload DB" (or whatever it's called, too lazy to look) on the settings panel.

**Comment by danw-eth** [comment]
That works, thanks!
