### ISSUE TITLE
Unknown starport type

### ISSUE THREAD

**Issue by CMDR-Lens-Larque** [EDDiscovery/EDDiscovery#3618]
*** Unknown starport type `OutpostScientific`
*** Unknown starport type `OutpostScientific`
*** Unknown starport type `OutpostScientific`
(Direct copy, appears three times at opening op EDDiscovery)

**Comment by robbyxp1** [comment]
Thanks. Can you post in the journal log where one of these occur, as we need to check where its coming from. thanks

**Comment by klightspeed** [comment]
Would the stations happen to be Talos 1 and Talos 2, from between April 2018 and January 2019?

**Comment by CMDR-Lens-Larque** [comment]
In the journal I can't find any mention of a OutpostScientific

I do have a Journal for the 2018 BETA account that gives 7 of these mentions in the log. In both account I have been to Peregrina system and Talos 1

If I search for "Type Unknown" in the Journal, I get 1 mention for a at location in my normal account: Qwent Research Base (entry from 2016)
In the BETA account I get 5 locations: Farseer Inc, Deciat / Martinez Vision, HIP 39470 / Lambert Base, Salikians / Auld Prospect, HIP 38531 / Talos 1, Peregrina

Some entries in the BETA Journal also crash EDDiscovery with the following notification:

### Description


### Additional Information


### Exception Details:
>EDDiscovery v18.1.6.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.Ship.<>c.<GetFSDSpec>b__102_0(ShipModule x) in C:\Code\EDDiscovery2\EliteDangerousCore\EliteDangerous\Ships\Ship.cs:line 234
>   at EliteDangerousCore.Ship.<>c__DisplayClass70_0.<FindShipModules>b__0(KeyValuePair`2 kvp) in C:\Code\EDDiscovery2\EliteDangerousCore\EliteDangerous\Ships\Ship.cs:line 97
>   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>   at EliteDangerousCore.Ship.GetFSDSpec() in C:\Code\EDDiscovery2\EliteDangerousCore\EliteDangerous\Ships\Ship.cs:line 234
>   at EDDiscovery.UserControls.UserControlSysInfo.<Display>d__28.MoveNext() in C:\Code\EDDiscovery2\EDDiscovery\UserControls\Overlays\UserControlSysInfo.cs:line 500
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

I only found this after messing around looking for the info. None of it is in the way of my enjoyment of EDDiscovery. If there is anything I can add to help, let me know.

**Comment by Eahlstan** [comment]
Please send us all of your journals so we can reproduce it.

**Comment by robbyxp1** [comment]
public ShipSlots.Slot[] FindShipModules(Predicate<ShipModule> test)
        {
            return Modules.Where(kvp => test(kvp.Value)).Select(x=>x.Key).ToArray();
        }

from               
var gmodules = FindShipModules(x => x.GetModuleUnengineered().ModType == ItemData.ShipModule.ModuleTypes.GuardianFSDBooster);

x.Value is a ShipModule

        public ItemData.ShipModule GetModuleUnengineered()
        {
            return ItemData.TryGetShipModule(ItemFD, out ItemData.ShipModule sm, false) ? sm : null;
        }

could return null, if the module did not exist in item data.

Maybe its an unknown module?

I'd love to see the journals to identify the module.

Meanwhile, it should be (Line 234):

var gmodules = FindShipModules(x => x.GetModuleUnengineered()?.ModType == ItemData.ShipModule.ModuleTypes.GuardianFSDBooster);
                
Its missing the ?

rob


Must not have found one?  A ship without a declared FSD, very unusual.

**Comment by CMDR-Lens-Larque** [comment]
> Would the stations happen to be Talos 1 and Talos 2, from between April 2018 and January 2019?

Spot on!
![2024-12-30_12h03_49](https://github.com/user-attachments/assets/ff7e501b-8ee7-4c48-8dad-d5f2d511b760)

**Comment by CMDR-Lens-Larque** [comment]
> Please send us all of your journals so we can reproduce it.

I recently moved to a new computer, so I combined both old and new Journal files in this zip.
[ED_Journals_CMDR_Lens_Larque.zip](https://github.com/user-attachments/files/18274248/ED_Journals_CMDR_Lens_Larque.zip)

**Comment by Eahlstan** [comment]
Are these really ALL of your journals? I can't get the ship crash to happen.

**Comment by robbyxp1** [comment]
It may be the records are in the edduser.sqlite but not in the journals you have left.

**Comment by CMDR-Lens-Larque** [comment]
> Are these really ALL of your journals? I can't get the ship crash to happen.

I can create the crash by clicking this entry (and a few others):

![image](https://github.com/user-attachments/assets/3feaffb9-ade4-453c-9467-d56a4f5a385c)

**Comment by Eahlstan** [comment]
The journals you sent only contain 965 entries for your beta commander.

**Comment by CMDR-Lens-Larque** [comment]
> It may be the records are in the edduser.sqlite but not in the journals you have left.

[EDDUser.zip](https://github.com/user-attachments/files/18274646/EDDUser.zip)

I did copy all of the .sqlite files over when moving to my new computer, maybe that caused it? I'm no developer, so...

**Comment by Eahlstan** [comment]
Thanks, that contains the crash.

**Comment by robbyxp1** [comment]
Thanks for the zip, that identified a few areas where we needed more protecting against frontier not giving you the loadout of the ship completely.  That was causing the crash.

**Comment by CMDR-Lens-Larque** [comment]
Thank you all contributors for all the hard work and dedication!

Can you close this issue when required, or do I need to do that?

**Comment by robbyxp1** [comment]
I'll close it. The next 18.1.x will solve the crashing on your beta commander.  In normal use, this won't happen as the loadout of the ship is written at every game start.

thanks for the very useful help
