### ISSUE TITLE
Spansh Window how to use it - Autotrack, use of route finder/surveyor

### ISSUE THREAD

**Issue by AirHunter47** [EDDiscovery/EDDiscovery#3619]
Hi, I've been using EDDiscovery for about a week now and I LOVE it. I only had one situation with SPANSH tool addition, I recently had a trip to Colonia and I was using the neutron highway, and I wanted to use SPANSH through EDDiscovery but every time I jumped to a new system, the page would refresh with the system's information and thus taking a way my planned trip, any settings that I could change in order to stop that from happening?

**Comment by robbyxp1** [comment]
Thats its designed behaviour, and that why its there, over just using Spansh in a firefox window.  Its supposed to autotrack your route and show spansh info for the current system your in.

There is a checkbox button on the toolbar to turn off this behaviour (auto track).

The best way to operating spansh/edd together is to 👍 

1. Using the route panel, import a spansh route into it (there are buttons to do this) and create an expedition with that route (you can see the expedition stars again using the expedition panel)
2. Use the surveyor panel (preferably overlay it over Elite (have elite in borderless mode)) and tell the surveyor panel to use the expedition you set up in 1.

Surveyor will track your route, showing your next system, autocopying the name to the clipboard for use in Elite if you ask it.  And it will show you discoveries (Like ED Observatory) and interesting bodies as you scan.

See video https://www.youtube.com/watch?v=dcuNn4o7gJ4 and https://www.youtube.com/watch?v=zw_RlzX0yn4
Rob

**Comment by AirHunter47** [comment]
That is so awesome! I will definitely implement this on my next Elite Session. You know I'm not a techy person, and stuff like this usually scares me a little because I'm afraid to touch something and destroy the software or application. But everyone so far in the ED third party community is very helpful and understanding.

Thank you.
