### ISSUE TITLE
Screenshot conversion fails when theres an * in the name

### ISSUE THREAD

**Issue by gregmalcolm** [EDDiscovery/EDDiscovery#38]
I noticed when in Barnard's Loop that automatic screenshot conversion fails when the intended filename includes invalid characters. For example, `* tet02 Orionis C` or `Cl* NGC 1981 AR 131`.

A simple character stripper would prevent that. Also if conversion fails it would be nice if the error was handled without a messagebox as the user isn't likely to discover it until they Alt+tab back to EDDiscovery. Perhaps a log message instead.

I may well tackle this myself, but thought it's about time I logged this as an issue

**Comment by finwen** [comment]
Should be easy to add a filter to remove forbidden charachters in a filename. Good catch

**Comment by robbyxp1** [comment]
See #108, which I independently found.  I have a fix in my code, will be rolled in soon
