### ISSUE TITLE
Feature Request - Neighborhood Map

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#380]
I find myself using two apps: EDDiscovery, almost for everything; and EDToolbox, just for the Neighborhood Map, which is lovely and very convenient.

Sometime I feel that the 3D Map, implemented in EDDiscovery, although awesome, is too cumbersome. I think that would be very useful to have a neighborhood window, which can be conveniently positioned - who knows, even overlaid... - which display a 3D cube (os sphere, which could be most appropriate...) of user defined range: 25Ly, 35Ly, 50Ly, ??Ly - and so one. A default range would be predefined in settings, and a multi select list will display some more defined range. Exactly the way EDToolbox works.

I simply do not think that it wise to run a second apps just to have such a tool...

Anyone likes the idea?

**Comment by robbyxp1** [comment]
Hmmm. a 5.1+ UC window, good idea.

Not sure we can run openGL in one (its a bit picky) but we could draw one

No ETA.

**Comment by andreaspada** [comment]
Great!

**Comment by robbyxp1** [comment]
Closed, its going to be too hard and we need to address the 3dmap first, to move it to a faster implementation.
