### ISSUE TITLE
Feature Request - Organize Screenshots in sub-folders

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#382]
When navigate through my huge screenshots folder, to record discoveries in "Elite Galaxy Online" or other web tools, I found that could be easier if the folder was organized in sub-folders.
Is it possible?

**Comment by andreaspada** [comment]
I'm proposing quite a lot of feature request. I also suggest that, to help in development of that splendid tools, to subscribe the project on "patron", so I - and other users - can support with donations...

**Comment by klightspeed** [comment]
Perhaps we could add an option in the image handler tab to enable organizing into directories, with possible options including by date, by system, by coordinate grid block, or custom.

**Comment by andreaspada** [comment]
That will be awesome!

**Comment by andreaspada** [comment]
No chances to have this implemented?

**Comment by Gimi1967** [comment]
This needs a little bump. With the great improvements we are seeing in 5.1.X, organising screenshots in folders is the only thing missing and holding me back from using the screenshot functionality in EDD.

Any chance at all?

**Comment by robbyxp1** [comment]
I'll add it to the list

**Comment by robbyxp1** [comment]
Will be in the 5.1 branch, with options to name subfolders after system, time.  Further options to name files as HH-MM-SS sysname, HH-MM-SS, sysname (in which case you get files sysname_1, sysname_2 etc)

**Comment by robbyxp1** [comment]
DOne

**Comment by Gimi1967** [comment]
Great, thank you, brilliant. 👍
