### ISSUE TITLE
Release data in .portable

### ISSUE THREAD

**Issue by IamKnowjaun** [EDDiscovery/EDDiscovery#390]
I have your .portable release with files dated 9/2/2016 11:01 AM and It doesn't launch; I have no idea what release I have, 4.2..0, 4.3.1, or 4.3.2.  The github page refers to the releases as 'released this 2 days ago', released this 3 days ago, and 'released this 4 days ago.'  I know the comment is easy... but inside the .zip file, without a readme or any other readable text and NO other release info makes it very hard to keep in sync.  A 1 line readme file would really help and then you could close out this issue... better yet, a running list of the bug fixes!

I'd like to tell you it was GREAT and heap a lot of accolades but it is throwing an exception right off the bat (in sql) with a file not available error.  I just need to find out what I'm doing wrong.  Thanks, Iam

**Comment by klightspeed** [comment]
You should be able to right-click the executable and look at its properties - the version should be there.

**Comment by IamKnowjaun** [comment]
I did create a sub-directory called data and moved System.Data.SQLite* files there. Does anything else belong there?  

EDDiscovery does launch after creating the 'data' dir but quickly fail with an exception.   Is there an obvious place where the .zip file needs to be unpacked?  Right now it is in a directory in my d drive off of root (d:\), where do you want it?

I know you guys know where everything goes and how it operates... it is not self-evident, I really want to get it working!

From Event Viewer...
Application: EDDiscovery.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at EDDiscovery.DB.SQLiteDBClass.InitializeDatabase()
   at EDDiscovery.DB.SQLiteDBClass.CreateCN()
   at EDDiscovery.DB.SQLiteConnectionED..ctor()
   at EDDiscovery.DB.SQLiteDBClass.GetSettingInt(System.String, Int32)
   at EDDiscovery.EDSM.GalacticMapping..ctor()
   at EDDiscovery.EDDiscoveryForm..ctor()
   at EDDiscovery.Program.Main()

**Comment by klightspeed** [comment]
Please move the System.Data.SQLite.* files back to the main executable directory.

The data directory is where the program stores its data files.

**Comment by IamKnowjaun** [comment]
thanks, that fixed it...
