### ISSUE TITLE
Play a sound file when entering a new system not known in EDSM

### ISSUE THREAD

**Issue by nickschurch** [EDDiscovery/EDDiscovery#395]
I'd be great if a feature could be added to EDDiscovery so that it could play a sound to notify us that a new system is not known in EDSM and needs trilateration.

I always travel with EDDiscovery open but sometimes I'm not paying attention and end up missing systems, and it would be great to have a reminder sound. It'd also prove very useful for people playing in VR since the can't see the EDDiscovery window without removing their headsets.

Anyway, just a thought...

**Comment by klightspeed** [comment]
Explicit trilateration is no longer required, as the Elite Dangerous log provides the system position.

**Comment by nickschurch** [comment]
oooh, interesting, I didn't know that! So we don't need to log positions
any more at all?!

**Comment by klightspeed** [comment]
That is correct - See https://forums.frontier.co.uk/showthread.php/245254-Add-system-coordinates-to-netlog

Note also that EDDiscovery by default automatically submits new travel log entries to EDSM.

**Comment by AnthorNet** [comment]
@nickschurch Nope, you do not it to enter distances anymore. Coordinates are stored on EDSM on the fly.

**Comment by nickschurch** [comment]
Awesome - oh, and well done on creating such a brilliant tool! I have
another suggestion, but I'll put that in another issue...

**Comment by robbyxp1** [comment]
Closed
