### ISSUE TITLE
4.3.1.0 - Constantly Asking for a Rebuild of the Distances

### ISSUE THREAD

**Issue by BlueDrache** [EDDiscovery/EDDiscovery#412]
"There is a problem with the distances file.  Please rebuild on next startup of the program through the Admin menu."  (Text is paraphrased from actual error window)

I've done this.  A number of times now.  Still getting the error.

**Comment by klightspeed** [comment]
This is probably related to the frequent 500 errors EDSM has been getting.

**Comment by klightspeed** [comment]
Is this resolved now that EDSM is back online?

**Comment by BlueDrache** [comment]
It seems to have gone away.  I left the program running overnight and it does an update request every 15 minutes as long as the screen-saver or monitor power-save isn't running.  Even while playing for about an hour, I didn't receive any errors.  

I believe that this is resolved.
