### ISSUE TITLE
Add Prospecting

### ISSUE THREAD

**Issue by finwen** [EDDiscovery/EDDiscovery#43]
Add a may to record prospecting of minerals. 

And a way to view known planets with minerals you wants.

**Comment by gregmalcolm** [comment]
Some random thoughts:

One thing I've learned from using the shared spreadsheet: The commonest 4
or 5 ingredients are worthless to log. Everywhere has them in abundance.

To me the most valuable information is details on the single rarest item
the planet yields. IE Polonium or Yttrium.

Another thing the spreadsheet has taught me: quantities are fairly
meaningless. Either a planet has a material or it doesn't. It's the metal
quality of the big rock you bust open that decides how good the drops can
be.

One other piece of data I would find useful: terrain difficulty. That is,
how flat, and what gravity? I figure the easier the terrain the more you're
going to pick up. This could be implemented as simply as a drop down box of
difficulty (easy to hard).

Btw, I've mentioned the spreadsheet quite a bit. It has been useful but I
think it's greatest failings have been in the amount of pages to fill out
and the amount of geological knowledge assumed. I don't know or care what
most of the surface types it lists are. It's assumption of one big rock
type per survey is obviously flawed. Personally I don't think it matters
where you prospect on a world at the moment, you can still get all the
known mats the world can yield.

**Comment by finwen** [comment]
I think we will start with it simple.

Still debating with myself if  add numbers of materials or just a check-box
to indicate that its found....

Only a check box is needed but numbers foung might be more fun.



2016-01-01 16:32 GMT+01:00 Greg Malcolm <notifications@github.com>:

**Comment by gregmalcolm** [comment]
Already came up in conversation on Skype earlier, but to reiterate for the record, I think checkbox is the more useful option. But saving the backend data as an integer might give you more leeway to change your mind later (using 0 and 1 for checkbox values).

That probably wouldn't be hard to upgrade the database from binary to integer data, so my suggestion is  perhaps breaking the YAGNI rule... :D

**Comment by Red13x3** [comment]
Ooh, brilliant! Does EDDB store that data or will it be local data only?

--
Mark Jelic
iPhone: 0402 322 901

**Comment by Red13x3** [comment]
Certainly gravity would be good to know as that can determine the type of skip you can take fun there. 

But certainly just a pop-up page of checkboxes for the materials will do. No need for quantities etc. 

--
Mark Jelic
iPhone: 0402 322 901

**Comment by Red13x3** [comment]
I vote just checkboxes. 

--
Mark Jelic
iPhone: 0402 322 901

**Comment by finwen** [comment]
CREATE TABLE "Objects" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "SystemName" TEXT NOT NULL , "ObjectName" TEXT NOT NULL , "ObjectType" INTEGER NOT NULL , "Gravity" FLOAT, "Terrain" INTEGER, "C" BOOL, "Fe" BOOL, "Ni" BOOL, "P" BOOL, "S" BOOL, "As" BOOL, "Cr" BOOL, "Ge" BOOL, "Mn" BOOL, "Se" BOOL NOT NULL , "V" BOOL, "Zn" BOOL, "Zr" BOOL, "Cd" BOOL, "Hg" BOOL, "Mo" BOOL, "Nb" BOOL, "Sn" BOOL, "W" BOOL, "Sb" BOOL, "Po" BOOL, "Ru" BOOL, "Tc" BOOL, "Te" BOOL, "Y" BOOL)

Or should we change to int for possible counting?  Not that i think we will use it now

**Comment by finwen** [comment]
Updated with Commander och updatetime.

CREATE TABLE "Objects" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "SystemName" TEXT NOT NULL , "ObjectName" TEXT NOT NULL , "ObjectType" INTEGER NOT NULL , "Gravity" FLOAT, "Terrain" INTEGER, "C" BOOL, "Fe" BOOL, "Ni" BOOL, "P" BOOL, "S" BOOL, "As" BOOL, "Cr" BOOL, "Ge" BOOL, "Mn" BOOL, "Se" BOOL NOT NULL , "V" BOOL, "Zn" BOOL, "Zr" BOOL, "Cd" BOOL, "Hg" BOOL, "Mo" BOOL, "Nb" BOOL, "Sn" BOOL, "W" BOOL, "Sb" BOOL, "Po" BOOL, "Ru" BOOL, "Tc" BOOL, "Te" BOOL, "Y" BOOL, "Commander"  Text, "UpdateTime" DATETIME )

**Comment by maddavo** [comment]
I'd like to suggest that the prospecting tool include planetary rings and asteroid belts.  I've contacted gregmalcolm about adding this into EDMaterializer.  I have found a number of "Material Content: High" asteroids in some planetary rings where the materials can be mined.

**Comment by gregmalcolm** [comment]
Heh heh, yeah I will not roll out a v5 api interface for EDM at some point to cope with this. It means stars are now prospectable. Although probably doesn't happen much

**Comment by robbyxp1** [comment]
Is this idea dead in the water?

**Comment by finwen** [comment]
prospecting part will be dead in water after 2.2 but the viewing of it will
be valid.   And we will still send prospecting data from jpournal
somewhere....    Should maybe create a new issue for it

2016-07-30 10:02 GMT+02:00 robbyxp1 <notifications@github.com>:

**Comment by robbyxp1** [comment]
Superceeded by 2.2 ED
