### ISSUE TITLE
EDDiscovery is slow to start, slower to exit

### ISSUE THREAD

**Issue by lemmy04** [EDDiscovery/EDDiscovery#434]
On my machine (8 core i7 with 32gb ram) EDDiscovery take AGES to start (25 minutes so far, still doing nothing). Any suggestions on how to find out what is getting in the way?

**Comment by lemmy04** [comment]
I have uninstalled EDDiscover,y, cleaned up all folders left behind by it, and deleted all my netlogs from E:D.

On the first try of running a newly installed EDD it worked fine, since the second try it is stuck at "processing log file netlog.xxxxxx" again.

...after maybe 15 minutes it got over whatever it was doing and seems to work for now.

**Comment by robbyxp1** [comment]
We will be rewriting the core code for 2.2, and hopefully will fix this.

**Comment by finwen** [comment]
IS this still a issue with 5.x?

**Comment by lemmy04** [comment]
It is faster now, but resyncing the whole star catalog with EDSM still takes a long time. It does _not_ get stuck like before anymore (so far).
