### ISSUE TITLE
Feature Request: Cancel Route calculation

### ISSUE THREAD

**Issue by muthan** [EDDiscovery/EDDiscovery#437]
When you are plotting a route you can't cancel the calculation. If you want to plot another route
instead it is even worse because then it is calculating both. 

Can you please add the functionality to cancel the calculation process

**Comment by robbyxp1** [comment]
No need, it works really fast in the next build..

**Comment by klightspeed** [comment]
@muthan was this with a long route with many jumps?

@robbyxp1 have you checked with a long route with at least 100 jumps running from a mechanical HDD?

**Comment by robbyxp1** [comment]
Lets release the 2.2 ED Discovery and see what speed it brings before we alter anything.

Sol to beagle point is less than 2 seconds 68 jumps on a SSD 1000ly jumps, same with 500ly.

Its a low priority request at the moment.

**Comment by muthan** [comment]
if that is the case then it is really not needed. I am fine with waiting.

@klightspeed it was basically that => Jaques to Beagle Point with 1kly jumps with HDD

**Comment by robbyxp1** [comment]
on my HDD the route plotter takes less than 2 seconds for a 138 jump plot to beagle point

I think its the new indexing of the db in the new version

will keep and eye on it, thanks for reporting

**Comment by robbyxp1** [comment]
Keep this open, i'll probably add it when things settle.

**Comment by jthorpe4** [comment]
Hi there, robbyxp1 I've noticed that plotting a route can take a longer if the connection between edsm goes either my isp drops or edsm is going a little slow. I think I was just plotting colonia 2 Jonai in 1000ly jumps.

**Comment by robbyxp1** [comment]
EDSM is not used during route calc. its all local.

closing this, its old
