### ISSUE TITLE
Feature Request- Diffrent colour for system name in Travel history

### ISSUE THREAD

**Issue by Gimi1967** [EDDiscovery/EDDiscovery#475]
Priority low
It would be nice if the system name in the Travel History log showed up in a different colour to the rest of the text on that line.
With the added text "Jump to" in front of the name the screen has become somewhat busy.

This may well apply to other events as well, but I have not had time to test much yet.

**Comment by klightspeed** [comment]
We would likely need to implement a rich text column to support this.

**Comment by robbyxp1** [comment]
Closing as old.
