### ISSUE TITLE
Beta 5.0.1.0 Database duplication when syncing with EDSM (Time stamp related)

### ISSUE THREAD

**Issue by Gimi1967** [EDDiscovery/EDDiscovery#476]
I seem to have an issue with beta, but I'm not sure what exactly is happening.
First my setup.
I have EDDiscovery running on 2 computers. The one I actually use for the game is on a laptop and reads the logs from my gaming computer over my LAN.
I have 4.3.5 installed and use that for ED 2.1.
I also have 5.0.1b installed and use it for beta. 5.0.1b has read all my previous data nicely.
I sync all logs to EDSM.

Next I have EDDiscovery 4.3.5 installed on a second laptop for reference and looking around the 3D map etc. It gets all my data from EDSM and so far it's been working fine and has kept in sync.
Now I have installed 5.0.1 on the second laptop and initially it worked fine. It got all my 2.1 data inn. This laptop does not have access to my logs or the beta journals.
Both laptops are running English Windows 10 64bit with country and region set to Norway.

The issue now is that on the 5.0.1b installations the data in the db has been duplicated with a different time.  I have been able to reproduce this on both my setups, and it happens when I do a sync with EDSM.  (I had both "From EDSM" and "To EDSM" ticked). 

With further testing I'm able to reproduce this if I only have FROM EDSM ticked, and the time shown for the event by EDD is +2 hours compared to the event that is read from the logs.

The duplicated data shows one entry with what seems to be GMT and one entry that has a time offset by 1 hour for entries during winter time and 2 hours for entries during summer time.
Odd thing is that it looks like the data downloaded from EDSM gets 2 hours (summer) added to it, but from what I can tell that time is already GMT +2.

The laptop that gets all it's data from EDSM (has no access to logs) also seems to download and display data in summer time, while the laptop that reads the data from logs seems to display data in GMT:
Same jump Example: Laptop that reads the logs:
06.10.2016 21.55.16     Jump to Sothis  35,38 ly
Laptop that gets all its data from EDSM
06/10/2016 23:55:16     Jump to Sothis  35.38 ly
Log entry:
{21:55:16} System:"Sothis" StarPos:(-352.781,10.500,-346.344)ly Body:1 RelPos:(-3.03858e+06,-1.41377e+07,7.92734e+06)km Supercruise
As displayed by EDSM web log:
 Sothis     06/10/2016, 21:55:16    494.49 Ly   35.38 Ly 

Same jump Example: Laptop that reads the logs (Entry is duplicated only been there once):
30.07.2016 23.47.24     Jump to Sagittarius A\*  22,29 ly    Sagittarius A*
30.07.2016 21.47.24     Jump to Sagittarius A\*  1105,53 ly  Sagittarius A*
Laptop that gets all its data from EDSM
30/07/2016 23:47:24     Jump to Sagittarius A\*  22.29 ly    Sagittarius A*
Log entry:
{21:47:24} System:"Sagittarius A_" StarPos:(25.219,-20.906,25899.969)ly Body:1 RelPos:(-2.19641e+07,1.27481e+07,-2.26227e+07)km Supercruise
As displayed by EDSM web log:
Sagittarius A_  30/07/2016, 21:47:24    25,899.99 Ly    22.29 Ly        

Winter time same jump Example: Laptop that reads the logs (Entry is duplicated):
03.01.2016 19.55.23     Jump to HIP 20524   9,95 ly
03.01.2016 18.55.23     Jump to HIP 20524   9,95 ly
Laptop that gets all its data from EDSM
03/01/2016 19:55:23     Jump to HIP 20524   9.95 ly
Log Entry:
{18:55:23} System:47(HIP 20524) Body:42 Pos:(269.226,798.57,538.333) NormalFlight
As displayed by EDSM web log:
HIP 20524   03/01/2016, 18:55:23    156.51 Ly   9.95 Ly 

Note: Both machines are running EDD 4.3.5 as well.

Lot of text here. I hope you can make some sense out of it. I'm not sure what is happening, but it seems like the time stamps on events are being converted into GMT/summer/winter time and then treated as a new entry owing to time mismatch. I also have indications that summer/winter time events are treated as GMT and are getting 1 or 2 hours added to it.
Could also be that data is being read from both the old database and from EDSM and that causes a mismatch.

**Comment by klightspeed** [comment]
Data in the old database was recorded in Local time, without any timezone.  As of 5.0.0, we are now storing times in UTC, converting from local time to UTC when converting the old database, and converting from UTC to local time for display.  Unfortunately, as no timezone was stored, and the logs are not currently referenced in order to determine the correct timezone, the program can only assume the timezone was the local timezone of the computer.

EDSM stores and displays times in UTC, so it would appear that the computer's timezone when the log was sent to EDSM was GMT.

What is the first line of each of the logs in question?
Did you copy the EDDiscovery DB from one computer to the other?
What version of EDDiscovery sent the logs to EDSM, when were they sent, and what was the sending computer's timezone set to?

Please try the following on the computer with the logs:
* Log onto https://beta.edsm.net/, and remove some of the old travel logs in question
* Make a shortcut to EDDiscovery 5.0
* Edit the shortcut
* Add the following option to the commandline:
  - ` -AppFolder EDDiscoveryBeta1 -EDSMBeta`
* Start EDDiscovery from the shortcut
* Uncheck the `From EDSM` option
* From the admin menu, select `Read 2.1 and former log files`
* Check that the times in the UI are correct
* Click `EDSM Sync`
* Check that the times on beta.edsm.net are the correct UTC times
* Check the `From EDSM` option
* Click `EDSM Sync`
* Check that no duplicates are created.

**Comment by AnthorNet** [comment]
Beta is on http://beta.edsm.net:8080/

Port 8080 and no HTTPS.

**Comment by Gimi1967** [comment]
Ok.
I have done all this now. I was unable to provoke the full duplication by doing this. I wonder what's causing it on my live db. Maybe something with me accessing EDSM with two different EDD installations.
I did find some oddities though. I have logs that I have never loaded into EDD or uploaded. That is going to fixed.
Also, when I did the EDSM sync the number of jumps increased by about 300.
These seem to be duplicates that are off by 4 or 5 seconds. No idea why that is happening.
Log entry:
{22:29:39} System:37(HIP 6486) Body:0 Pos:(9.67326e+009,4.44805e+009,1.29063e+010) Supercruise
EDD beta
19.03.2016 22.29.43		Jump to HIP 6486	
19.03.2016 22.29.39		Jump to HIP 6486	27,69 ly
EDSM entry
HIP 6486 	19/03/2016, 22:29:43 	191.87 Ly 	27.69 Ly 
It's not duplicated in EDSM.
Systems affected are jumps uploaded from 20 Feb 2016 to 21 March 2016. Most jumps from that period are duplicated but not all.
These are not duplicated in my live db for some reason though. Live EDSM has the 4/5 seconds offset.
I wonder if these are the logs that I uploaded directly to EDSM at one time.

Anyway, I can't recreate to original issue, but found another. :(

**Comment by Gimi1967** [comment]
To answer your questions further (I got too hung up on testing).

    What is the first line of each of the logs in question?

Same jump Example: Laptop that reads the logs:
06.10.2016 21.55.16 Jump to Sothis 35,38 ly
Laptop that gets all its data from EDSM
06/10/2016 23:55:16 Jump to Sothis 35.38 ly
Log entry:
{21:55:16} System:"Sothis" StarPos:(-352.781,10.500,-346.344)ly Body:1 RelPos:(-3.03858e+06,-1.41377e+07,7.92734e+06)km Supercruise
As displayed by EDSM web log:
Sothis 06/10/2016, 21:55:16 494.49 Ly 35.38 Ly
First line: 16-10-06-21:27 W. Europe Summer Time  (19:27 GMT) - part 1

Same jump Example: Laptop that reads the logs (Entry is duplicated only been there once):
30.07.2016 23.47.24 Jump to Sagittarius A* 22,29 ly Sagittarius A*
30.07.2016 21.47.24 Jump to Sagittarius A* 1105,53 ly Sagittarius A*
Laptop that gets all its data from EDSM
30/07/2016 23:47:24 Jump to Sagittarius A* 22.29 ly Sagittarius A*
Log entry:
{21:47:24} System:"Sagittarius A" StarPos:(25.219,-20.906,25899.969)ly Body:1 RelPos:(-2.19641e+07,1.27481e+07,-2.26227e+07)km Supercruise
As displayed by EDSM web log:
Sagittarius A 30/07/2016, 21:47:24 25,899.99 Ly 22.29 Ly
First line: 16-07-30-19:37 W. Europe Summer Time  (17:37 GMT) - part 1

Winter time same jump Example: Laptop that reads the logs (Entry is duplicated):
03.01.2016 19.55.23 Jump to HIP 20524 9,95 ly
03.01.2016 18.55.23 Jump to HIP 20524 9,95 ly
Laptop that gets all its data from EDSM
03/01/2016 19:55:23 Jump to HIP 20524 9.95 ly
Log Entry:
{18:55:23} System:47(HIP 20524) Body:42 Pos:(269.226,798.57,538.333) NormalFlight
As displayed by EDSM web log:
HIP 20524 03/01/2016, 18:55:23 156.51 Ly 9.95 Ly 
First line: 16-01-03-18:54 W. Europe Standard Time  (17:54 GMT) - part 1	
	

    Did you copy the EDDiscovery DB from one computer to the other?
<Im pretty sure I didn't. The second EDD installation was done when I was traveling. Given all my fideling there is no garantee though>
	
    What version of EDDiscovery sent the logs to EDSM, when were they sent, and what was the sending computer's timezone set to?
<I have been using EDD since around April 2015, so various versions since then have been used to upload logs. I did upload a whole bunch of logs manually through the EDSM web interface though>

**Comment by klightspeed** [comment]
In the EDSM Settings (https://www.edsm.net/settings), is the timezone set to UTC or to your local timezone?  This is the timezone that is used to display times in the EDSM UI.

The duplication around February/March suggests an upload of those logs after 21st March (when summer time would have started for you).

**Comment by Gimi1967** [comment]
Time zone in EDSM settings is set to "Europe/Oslo"
Question: What time zone are the network logs written in. I have always assumed it's local time. (I'm at work, can't check right now).
If so, that would mean that my logs are uploaded in local time "Europe/Oslo", and displayed by EDSM in local "Europe/Oslo". When I then do a sync, something is assuming that the times received from EDSM are GMT and adding 1 or 2 hours for winter time and summer time respectively.
Question then is, will setting the time zone in EDSM to GMT solve that sync problem?

Also, regarding duplications around March. These are off by between 4 and 6 seconds. I fail to see how that can be time zone related.

Thanks for taking the time to help me sorting this out.

**Comment by AnthorNet** [comment]
Hey ^^
EDSM should only takes UTC time in the API, so even our importer convert everything in UTC, based on the timezone indicated in the first line of the netLog.

**Comment by klightspeed** [comment]
The EDSM API should not be affected by the timezone set in the EDSM settings - all times sent through the API are UTC times.

Please:
* Grab your API key
* Download the data from https://www.edsm.net/api-logs-v1/get-logs?commanderName=#yourCmdrName#&apiKey=#yourApiKey#
* Search for `Sagittarius A*`
* Confirm that the entry containing that is something like:
  - `{"system":"Sagittarius A*","firstDiscover":false,"date":"2016-07-30 19:47:24"}`
* If the date is `2016-07-30 21:47:24`, then try setting the EDSM timezone to UTC and try again.

If the date returned by the API is `2016-07-30 21:47:24` when the timezone is `Europe/Oslo`, and `2016-07-30 19:47:24` when the timezone is `UTC`, then that's bad.

If the duplicates around February-March were added by EDDiscovery 5.0 beta, that suggests that the time in your logs jumped backward by between 4 and 6 seconds (possibly due to the Windows Time service stepping the computer's clock backwards).  The new log handling adjusts the timezone offset when necessary in order to ensure all log entries in a log are in chronological order - see https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/EliteDangerous/NetLogReader.cs#L69

**Comment by AnthorNet** [comment]
To avoid duplicate in EDSM, we check the next and previous log to ensure it is not in the same system.

**Comment by Gimi1967** [comment]
Pulled the data and the EDSM TZ didn't change anything, so that is working as intended.
EDSM TZ set to GMT+2 {"system":"Sagittarius A*","firstDiscover":false,"date":"2016-07-30 19:47:24"}
EDSM TZ set to GMT {"system":"Sagittarius A*","firstDiscover":false,"date":"2016-07-30 19:47:24"}

I'm still unsure about the 4-6 seconds offset. Will this cause problems when I start syncing with EDSM live using 5.0
The data that has the offset of 4s-6s was added to EDSM a long time ago by whatever version of EDD that was current at the time or by log upload to EDSM.
The data was read into the EDD database by verison 5.0.1. I did as you said and reread all the logs into EDD.

**Comment by Gimi1967** [comment]
Downloaded and installed v5.0.2.
All my jumps/systems are still being duplicated with the summer time/winter time / GMT bug when I do a sync from EDSM. I have no idea why or how to avoid this. I'm certainly willing to test more if it can be of any use.
I guess syncing from EDSM is a big no no for now.

**Comment by klightspeed** [comment]
Please use [DB Browser for SQLite](http://sqlitebrowser.org/) or something similar to open `%LOCALAPPDATA%\EDDiscovery\EDDiscovery.sqlte` and `%LOCALAPPDATA%\EDDiscovery\EDDUser.sqlite`

In EDDiscovery.sqlite, please look in the `VisitedSystems` table for some of the systems that you are having issues with, and check that the times in the DB match the local times in the logs.  You can use the following SQL query, replacing `<sysname>` with the system name:
```
SELECT * FROM VisitedSystems WHERE Name = '<sysname>'
```

In EDDUser.sqlite, please look in the `JournalEntries` table for the same systems, and check that the times of the systems you checked above are the correct UTC times.  You can use the following SQL query, replacing `<sysname>` with the system name:
```
SELECT * FROM JournalEntries WHERE EventType = 'FSDJump' AND EventData LIKE '%"StarSystem": "<sysname>"%'
```

**Comment by Gimi1967** [comment]
Sorry for late reply. I have been travelling.

So I got the following result.
In EDDiscovery.sqlite:
`"19514"	"Sagittarius A*"	"2016-07-30 21:47:24"	"netLog.160730193710.01.log"	"0"	"588"	"1"	"-65281"		"25.219"	"-20.906"	"25899.969"	`

In EDDUser.sqlite: 
```
"20480"	"20480"	"588"	"0"	"280"	"FSDJump"	"2016-07-30 21:47:24Z"	"{
  ""timestamp"": ""2016-07-30T19:47:24Z"",
  ""event"": ""FSDJump"",
  ""StarSystem"": ""Sagittarius A*"",
  ""StarPos"": [
    25.219,
    -20.906,
    25899.969
  ],
  ""EDDMapColor"": -65281,
  ""JumpDist"": 22.291822938494132
}"	"0"	"1"
```
Your second query didn't work with the following error:

> no such table: j: SELECT j.*, t.name AS Unit FROM JournalEntries JOIN TravelLogUnit t ON t.id = j.TravelLogId WHERE EventType = 'FSDJump' AND EventData LIKE '%"StarSystem": "Sagittarius A*"%'

I had to march through the table. I hope I got the relevant information. 
Question: Has only one time value converted to Z-time in conversion or am I missing something?

I have yet to upgrade to 5.0.3. I will take a backup of the databases before installation and then let 5.0.3 do a conversion from the old EDDiscovery. Seems you guys have fixed a lot.

**Comment by klightspeed** [comment]
Found the issue that caused the incorrect timestamp in the converted table.

**Comment by Gimi1967** [comment]
Thank you for your work, and not least patience, klightspeed.

**Comment by klightspeed** [comment]
Be aware that with E:D 2.2, if you import both netlogs and journals for the same period, the netlog entry for a jump to a system is logged up to 30 seconds before the journal entry for the same jump.

**Comment by Gimi1967** [comment]
Good to know.
From my understanding EDD by default only reads the Journal now. Netlogs are only read if you go through the admin menu. Is this correct?
Are the two correlated so you don't get duplicates?

**Comment by robbyxp1** [comment]
Yes netlogs thru the Admin menu only, and it should not duplicate if the name and time matches
Closed, fixed
