### ISSUE TITLE
Visiting a duplicate system is unrecognized.

### ISSUE THREAD

**Issue by Moleculor** [EDDiscovery/EDDiscovery#477]
[netLog.161012173302.01.txt](https://github.com/EDDiscovery/EDDiscovery/files/526059/netLog.161012173302.01.txt)

See in this log how I visit BD+56 521? And then I visit another system with the same name, BD+56 521. 

EDDiscovery doesn't recognize visiting the second system.

I'm using 4.3.3. I tried upgrading to 4.3.5, don't know if that would have changed anything, but I'm not seeing my proper route listed.

**Comment by klightspeed** [comment]
This should be resolved in 5.0

With E:D 2.2 just around the corner, it seems unlikely that there will be an EDDiscovery 4.3.6

**Comment by Moleculor** [comment]
Is 5.0 compatible with E:D 2.1? I heard it had a legacy netlog reader. I recognize that #479 isn't released yet, and I'd need to wait until >5.0.1, but if 5.x is compatible with 2.1 I don't see a reason not to switch the moment >5.0.1 gets released.

**Comment by finwen** [comment]
5.0 is not made for  ED 2.1   IT wil not scan netlogfiles in realtime.
 just convert the old database to new format and then look for journals
from ED 2.2

So use ED 4.3.x for ED 2.1

2016-10-14 18:21 GMT+02:00 Moleculor <notifications@github.com>:

**Comment by robbyxp1** [comment]
Closed
