### ISSUE TITLE
[Feature Request(s)] Check for updates, (auto)update?

### ISSUE THREAD

**Issue by Moleculor** [EDDiscovery/EDDiscovery#478]
Would love to see an option to check for updates, check for updates automatically, update, and/or update automatically.

**Comment by finwen** [comment]
Yes its something i want to improve in the future.

2016-10-13 5:59 GMT+02:00 Moleculor <notifications@github.com>:

**Comment by finwen** [comment]
https://github.com/octokit/octokit.net/blob/master/docs/releases.md#get-all   Might be the solution

**Comment by finwen** [comment]
Working on this with githubs webapi,

https://api.github.com/repos/EDDiscovery/EDDiscovery/releases/latest
