### ISSUE TITLE
Prospecting Backend API (EDDB)

### ISSUE THREAD

**Issue by gregmalcolm** [EDDiscovery/EDDiscovery#49]
@finwen : Did EDDN work out as a place to store prospector data?

The reason I ask is I'm going to be stuck with the mac laptop next week while out at a coding convention. Putting together a quicky backyend api/db project would be a fun thing to work on while out there. No obligation to stick with it if something better becomes available.

**Comment by finwen** [comment]
A quck backend  would be good.  EDDB will support it in the future but it
will take some time. And EDSM might support it to.  Not talked to Anthornet
yet. He has been busy with work and sick kids.

But i guess that a solution from others are maybe months away,



Den 4 jan 2016 05:44 skrev "Greg Malcolm" <notifications@github.com>:
>
> @finwen : Did EDDN work out as a place to store prospector data?
>
> The reason I ask is I'm going to be stuck with the mac laptop next week
while out at a coding convention. Putting together a quicky backyend api/db
project would be a fun thing to work on while out there. No obligation to
stick with it if something better becomes available.

**Comment by AnthorNet** [comment]
Hello,
Would have to see with EDDB which one would support it, but we could do it!

I think themroc was asking for help in how it works to model it and I think I need to.

May be we should open an issue on EDDB to discuss it

**Comment by gregmalcolm** [comment]
Sounds good, EDDB ultimately would be an ideal place for it. Where is EDDB the codebase hosted btw?

In the interim my app can just act as a api placeholder/prototype. Any preference on the schema? I could just mirror whatever is already in the codebase if it's in the master branch. I haven't actually looked too close to see what you've pushed up yet.

**Comment by finwen** [comment]
Still working on a simple schema. I hope to get a idea finnished later
today (after i get the kids to sleep)

2016-01-04 18:47 GMT+01:00 Greg Malcolm <notifications@github.com>:

**Comment by Majkl578** [comment]
> Where is EDDB the codebase hosted btw?

EDDB is sadly a closed-source project. Maybe @themroc5 could share his vision here.

---

If we want/need, I'd be willing to create an API for this, or a just prototype for now, whatever we want.

**Comment by themroc5** [comment]
Yes I want to add body mapping to EDDB. I'm still planning how to approach this but it is coming closer to reality. I don't want to release half finished stuff, so it got to be right. 

My initial plan was: 

* Add the possibility to describe every kind of body with every kind of data available on ROSS.
* Make this properly seachable on EDDB. Similar to the station finder.
* Make the data available via the JSON dumps. 

Now those questions arised:

* Do you want/require to upload data from EDDiscovery via an API? Or would it be enough to only have ROSS as the user input location. At first I'd prefer the latter.
* EDDB can only have systems with coords from EDSM. Is this a problem? I assume to make it usable for further usage EDDB would require a more often update from EDSM than the current nightly. This could be done easily, even every 10 minutes.
* Do you require a more often dump of certain data than the nightly period?

I'm afraid I can't offer any realtime data. Still I'd be happy to help wherever I can.

**Comment by finwen** [comment]
Would be good if EDDiscovery could upload at least new data thats nonexistent in EDDB.

For prospecting in Distant worlds expedition we will record materials on many planets. Even if i will get coordinates for those i prospect on i imagine that not every one will do so.  So yes it will be a problem. 

Nightly json export might be little slow for prospectinginfo to spread.

**Comment by gregmalcolm** [comment]
As we have a good EDDB discussion going here I've renamed the issue and will talk about the API prototype in another issue. So we don't keep crossing the streams.

**Comment by gregmalcolm** [comment]
I'm closing this one out for now. We can always create fresh issues if EDSM starts expanding into prospecting data.
