### ISSUE TITLE
Journal Log path override not recognised. EDD 5.0.3 beta portable

### ISSUE THREAD

**Issue by Gimi1967** [EDDiscovery/EDDiscovery#491]
Not sure if this is a quirk with my installation or a bug. Decided to flag it just in case as 2.2 is nearing release.

I have done a fresh install of **beta 5.0.3 portable** and let it convert the old 4.3.5 db. 
In this scenario EDD beta refuses to recognise my network path to the journal logs as entered in the override field for the current commander.

Installing over a pre-existing beta installation (standard installer) seems to work fine, but in that case the path was already working in beta 5.0.2.

Steps to reproduce:

Run EDD over a network or use journal log path override in the settings tab.
Remove the db files for previous beta installations
Install the latest beta.
Let 5.0.3 beta update from EDSM and  convert your old 4.3.5 db.
Enter the correct path to your Journal directory on the network.
EDD does not accept the Journal log path override in my case.
I keep getting error messages:

`Start Monitor exception: The directory name C:\Users\<user name>\Saved Games\Frontier Developments\Elite Dangerous\ is invalid.`

This happens regardless of what I put in the path fields under the settings tab.
It's like the path has been hard coded.
If I select "Show Journal Files Directory of Current Commander" in the Admin menu EDD does open the right directory on the network though. So it's does not seem to be a network problem.

**Comment by klightspeed** [comment]
Does the `Data\Log\Trace_<datetime>.log` contain `New watch on <directory>` where directory is the directory you have set?

A workaround until the next version is released is to ensure "%USERPROFILE%\Saved Games\Frontier Development\Elite Dangerous" exists.

**Comment by Gimi1967** [comment]
Thank you, I see you have a fix here. I'm beginning to think (though I doubt it) my setup is unique and that I'm bothering you with stuff that is largely irrelevant. 

Yes, the `Data\Log\Trace_<datetime>.log` does indeed contain the relevant directories. Your work around has solved it for now though. Thank you.
