### ISSUE TITLE
Star map color changes are lost after refresh (or restart)

### ISSUE THREAD

**Issue by finwen** [EDDiscovery/EDDiscovery#51]
I changes some systems map color to green.

Works fine in the map.

Press refresh.  And its back to red.....

**Comment by finwen** [comment]
EDDiscovery2.exe!EDDiscovery.TravelHistoryControl.starMapColourToolStripMenuItem_Click(object sender, System.EventArgs e) Line 1009	C#

Calls

>	EDDiscovery2.exe!EDDiscovery2.DB.InMemory.VisitedSystemsClass.Update() Line 22	C#

And update does nothing...   That update should go to disk to not only memory.

**Comment by lazarov27** [comment]
Method hiding instead of override, so DB.VisitedSystemsClass.Update doesn't get invoked

**Comment by finwen** [comment]
Solved by commit 487aa62e5450a0172755b1e423d5b6ff1bcab9d5
