### ISSUE TITLE
Integrate AppVeyor CI

### ISSUE THREAD

**Issue by Majkl578** [EDDiscovery/EDDiscovery#52]
It'd be cool to have this, at least for continuous/nightly builds for now.
This might also be used for deployment etc., see: https://www.appveyor.com/docs/deployment/agent

**Comment by klightspeed** [comment]
@finwen now that the necessary config files are in the repository, and both Appveyor and Travis builds are succeeding, do you want to set up Appveyor and/or Travis-CI for the main repo?

**Comment by finwen** [comment]
For a build / test sderver?  that could be nice.

2016-07-30 7:55 GMT+02:00 Ben Peddell <notifications@github.com>:

**Comment by klightspeed** [comment]
@finwen I think you'll have to set this up.

**Comment by robbyxp1** [comment]
Old and closed

**Comment by klightspeed** [comment]
Are we not interested in actually setting up AppVeyor or Travis?  We have the config files, but only a repo admin can set up the AppVeyor or Travis instance.

**Comment by finwen** [comment]
Yes but i have had not had time and energy to lern  how to set it up yet.


2016-11-25 11:12 GMT+01:00 Ben Peddell <notifications@github.com>:

**Comment by klightspeed** [comment]
https://github.com/EDDiscovery/EDDiscovery/wiki/Setting-up-Continuous-Integration
