### ISSUE TITLE
Unix port

### ISSUE THREAD

**Issue by Majkl578** [EDDiscovery/EDDiscovery#53]
I'm not sure how many players out there are playing on Mac or how many of them would be interested to use Mac port of EDDiscovery, but if there any, it may be worth it to investigate this.
Currently the only way seems to be Mono, which was a bit glitchy last time I tried it. .NET (https://github.com/Microsoft/dotnet) was not yet ready on non-Windows platforms at that time, not sure how it stands now.

**Comment by gregmalcolm** [comment]
Funnily enough I'm playing with EDDiscovery from a mac this week. Though from a windows partition. 

I think it would be nice to have a mac version but I suspect it'll be harder to keep it supported unless someone among us is truly dedicated. I can't help thinking a lot of mac users would be the types that have a windows install somewhere for the better tooling but like to play it from their mac laptop as well. Wild guess I know.

I'd imagine it would be easier to support a minimalist port as it'll be easier to support with the ongoing firehose of windows EDDiscovery changes. The minimal version would at least allow someone who uses mac an windows to keep logging when they're on the mac.

Anyway, highly subjective comments, I'm probably wrong. Not sure I'd want to invest to heavily in it, but it could be a fun sub-project none the less.

Regarding technologies, as far as I known Mono works pretty well these days, but it's never going to be able to run all the same libraries and windows .NET. The essence of EDDiscovery is an sqlite database and some forms so you could probably port to any form any mac development environment. We could even just make a HTML5 flavor, a version that runs on some kind of local weberver (like node.js)  and just works with the local filing system. Sound's a little silly, but this would be truly cross platform so it would be possible for windows users to help support it. Writing it in COCOA could be fun too. Never tried that personally but I would imagine it just depends on who wants to run with the idea.

**Comment by Majkl578** [comment]
I spent some time on trying to run EDDiscovery under Mono on Linux.
First thing I had to fix were backslashes used as path separators, that really doesn't work on Unix, so I replaced them with `Path.DirectorySeparatorChar`.

Unfortunately I wasn't able to resolve SQLite interop issues, that thing just doesn't seem to work...
![debug info](https://cloud.githubusercontent.com/assets/144181/12369381/5d04fae6-bbf6-11e5-9b19-be9a7ae7f553.png)

Base commit 1006414.

**Comment by gregmalcolm** [comment]
Yep, you would need to change the doll reference to a month equivalent and modify the sqlite interface.

http://www.mono-project.com/docs/database-access/providers/sqlite/

**Comment by Red13x3** [comment]
Can I wave the flag for this, as well?
The question I have is: How come EDMarketConnector (also here on GIT) seems to be able to have both Windows and Mac versions running from the same code-base?  What have they done that we haven't?

**Comment by SamMackrill** [comment]
Because EDMarketConnector is written in Python which runs just about anywhere. In the long run it would probably be more efficient to use something like [Electron](http://electron.atom.io/). Take a look at [GitKraken](https://www.gitkraken.com/)

**Comment by jgoode** [comment]
I have thought about making a OS X/Linux migration to Xamarin/Mono, but would need to make the current client less-fat to make it easier for cross-platform migration and maintenance. I would entertain the idea further if someone is willing to help. 

Converting everything to another platform/programming language like Javascript/Electron would be a fairly large undertaking. Could reuse code in Web and Mobile versions too.  I would also entertain that idea if someone was willing to help.

**Comment by jgoode** [comment]
Ben,

Are you building the project in an IDE or directly?

**Comment by klightspeed** [comment]
I'm building it using xbuild.  There is also a .travis.yml file that builds it and runs the tests.

```
git clone https://github.com/EDDiscovery/EDDiscovery.git -b Mono-sqlite
cd EDDiscovery
nuget restore EDDiscovery.sln
xbuild EDDiscovery.sln
```

**Comment by noberasco** [comment]
There is also https://github.com/EDDiscovery/EDDiscovery-Mac which is essentially a native OS X rewrite made (by me) in obj-c.

It only has the bare bones now (netlog parsing, edsm syncing, jump history and (now obsoleted) trilateration. Next addition will probably be 2D maps.

**Comment by Red13x3** [comment]
Why is trilateration obsoleted??

--
Mark
iPhone: 0402 322 901

**Comment by klightspeed** [comment]
Trilateration is obsolete for getting the location of the current system, as Elite Dangerous now has the system locations in the netlog.  Trilateration is still useful for reverse trilaterating other systems (such as unreachable beacon stars).

**Comment by robbyxp1** [comment]
Closed. Mono addresses linux
