### ISSUE TITLE
5.0.9.0 Cross link of scanned planet with system in EDDB (Acihaut)

### ISSUE THREAD

**Issue by Charybdis** [EDDiscovery/EDDiscovery#534]
Found a system that is cross linked on EDDB, from an earlier version of EDDiscovery.

System: Acihaut
Planet: Col 359 Sector MM-U d3-26 1
EDDB link: https://eddb.io/system/bodies/440

ROSS indicates this was uploaded by EDDiscovery 5.0.9.0
https://ross.eddb.io/body/update/24751

**Comment by finwen** [comment]
{ "timestamp":"2016-11-17T11:47:56Z", "event":"FSDJump", "StarSystem":"Pachamama", "StarPos":[3.844,-61.813,
{ "timestamp":"2016-11-17T11:48:24Z", "event":"Scan", "BodyName":"Gliese 893.3 B", "DistanceFromArrivalLS":0
{ "timestamp":"2016-11-17T11:50:50Z", "event":"FuelScoop", "Scooped":0.864920, "Total":27.893442 }
{ "timestamp":"2016-11-17T11:52:07Z", "event":"Scan", "BodyName":"Pachamama B 1", "DistanceFromArrivalLS":92

Another example with journal log

Thery.   Then exploration server lags   scan event can arrive much later in journal log.   And if you jump before then scan event comes after jumping to new system

**Comment by Charybdis** [comment]
Good observation. A scan that completes "during the jump countdown" might be enough.

However the original example has a separation of 504Ly, which would be a delay of ~10 minutes (est. 10 jumps @50Ly range).

Possibly a player death and return to last system. Another possibility is a timestamp change on the client machine.

**Comment by finwen** [comment]
We now has a safetycheck so it cant send scans on a wrong system anymore

**Comment by Charybdis** [comment]
Thanks!
