### ISSUE TITLE
Bug Report: Error on deleting empty row

### ISSUE THREAD

**Issue by Septolum** [EDDiscovery/EDDiscovery#535]
If you select an empty row in the Routes/Expeditions tab (one with an \* for its number), and then delete it, an unhandled exception is thrown.
Error log attatched
[Trace_20161030222431.log.txt](https://github.com/EDDiscovery/EDDiscovery/files/560802/Trace_20161030222431.log.txt)

**Comment by finwen** [comment]
Solved with #536
