### ISSUE TITLE
EDDB links sometimes not working

### ISSUE THREAD

**Issue by EoD** [EDDiscovery/EDDiscovery#547]
On some system, EDDisovery does nothing when I click the EDDB icon(s), next to the EDSM link. It doesn't even show the text overlay saying "Click to show...".

One example is system "Hyades Sector BC-T b4-5".

**Comment by klightspeed** [comment]
We need to grey out the EDDB icon on unpopulated systems like this.

**Comment by EoD** [comment]
I have been mapping quite some planetary bodies further out (and hence systems) via EDDN and they all ended up on EDDB. 

The [ED Market Connector](https://github.com/Marginal/EDMarketConnector) actually seems to have an internal mapping, as I all EDDB links seem to work fine.

**Comment by klightspeed** [comment]
EDMC only links to the station on EDDB.  It links to the system on EDSM.

EDDB does create systems in its database as soon as the FSDJump journal entry is submitted to EDDN, but it will not fill in the EDSM ID until the its next EDSM update.

I have asked how best to programmatically link to a recently submitted system on EDDB.

**Comment by EoD** [comment]
EDMC actually links to the system if you are not docked.

**Comment by klightspeed** [comment]
Click on the system link and you'll find it takes you to EDSM and not EDDB.

**Comment by EoD** [comment]
Click on the "x" (= no station) and it will take you to EDDB :)

**Comment by klightspeed** [comment]
It sounds like you are jumping to systems already in EDDB, in which case the system would have been in https://eddb.io/archive/v5/systems.csv

EDMC shows nothing in the Station field when the system you are jumping to was not already in EDDB.

**Comment by EoD** [comment]
I see, I have always seen a "x". Apparently I have submitted only non-existing bodies to already existing systems.

**Comment by klightspeed** [comment]
We can't link to brand new systems in EDDB at the moment.

Without either a 500MB download or a download of EDSM->EDDB ID mappings, we can't link to systems that don't have a station in EDDB.

**Comment by EoD** [comment]
500MB is the uncompressed version. I assume that download the (e.g.) gzip-compressed systems.csv, is probably <10% of the original file and hence an option imho.

I personally would prefer to download those 50MB once and then use the systems_recently.csv  (~5MB) to update the systems (as long as we are in the 7 day window). This is better than having no link at all.

I guess you checked how EDMS is doing this? From my experience, even EDMC does not have all the systems links of eddb, but it has much more than EDDiscovery.

**Comment by EoD** [comment]
I downloaded both the systems.csv and the systems_recently.csv with gzip compression. Here is the actual downloaded sizes:

* systems.csv: 693,326 kB, with gzip compressed it is 140.58 MB
* systems_recently.csv: 24,553 kB, with gzip compression it is 5.44MB

**Comment by robbyxp1** [comment]
Closed, due to age. please resubmit if its still a problem

**Comment by klightspeed** [comment]
There was talk of EDDB getting a https://eddb.io/systems/edsm/<n> interface, but I don't think that went anywhere.

**Comment by qigel** [comment]
This still occures. As I see, EDDiscovery don't send any data to EDDB for a day.

**Comment by Eahlstan** [comment]
> This still occures. As I see, EDDiscovery don't send any data to EDDB for a day.

Please open a new issue and describe your problem.
As much as I like that you searched old issues it doesn't make much sense to use an issue that old (you can still link it in the new issue if you think it's related).
