### ISSUE TITLE
3D map is mirrored to the galaxymap ingame

### ISSUE THREAD

**Issue by muthan** [EDDiscovery/EDDiscovery#55]
the 3D map has not the same presentation of the galaxy as the galaxymap ingame. It is mirrored over the horizontal layer.
So in my understanding the 3D map shows the inverse of the y values of the star coordinates

**Comment by finwen** [comment]
Yes it looks like its mirrored upside down now.

**Comment by gregmalcolm** [comment]
Really? That's very odd!

This is what I see 2.6.4.0 when I open the map:

![map](http://i.imgur.com/CIqaipH.png)

Which I believe matches the game. So are you both seeing this upside down?

I suppose it's possible there could be a camera bug. Which Star's are you starting from?

**Comment by finwen** [comment]
That view is correct.
and it shows only X and Z values.
If you look at it from the side you see y values and then its upside down.



2016-01-06 16:38 GMT+01:00 Greg Malcolm <notifications@github.com>:

**Comment by gregmalcolm** [comment]
Ah! I understand now, thanks! Yeah, side of effect of me making the points true coordinate representations of the real world coordinates. Guess we just need another world transformation that does the mirroring at the beginning of the rendering process.

**Comment by muthan** [comment]
still an issue in 2.6.8

**Comment by finwen** [comment]
Yes its inverted again.... strange

**Comment by gregmalcolm** [comment]
Odd. I thought I'd fixed by adding an inversion of Z in the Scaling transformation in the rendering process:

```
           GL.Scale(_zoom, _zoom, -_zoom);
```

I can look into it when I'm next at my gaming PC, but probably won't happen till tomorrow.

**Comment by gregmalcolm** [comment]
Ok, finally sorted it out
