### ISSUE TITLE
Uploading scans to EDDN

### ISSUE THREAD

**Issue by jfrob** [EDDiscovery/EDDiscovery#557]
Currently (at least on v5.0.17.0) the scan results from journal are uploaded to EDDN when EDDiscovery is running. I am not sure if there is any configuration on this behaviour, can it be toggled on or off by "Sync to Eddn" checkbox for Commander. 

In any case, it does look like that if EDDiscovery is started, and there are new logs since last time, the new systems are uploaded to EDSM (either automatically, but at least when clicking EDSM sync, not sure) but unless I'm mistaken, nothing is uploaded to EDDN. If there are no technical reasons preventing it, I would like some kind of option to upload new scans to EDDN even when they are not 'live' events. Is it possible or doable?

Also, sometimes it would be convenient to not upload new data as it is added to the game logs, but just monitor them and only upload it (EDSM and EDDN both) when manually syncing. If I understand the settings present, this is not currently an option.

**Comment by klightspeed** [comment]
We are only sending fresh data to EDDN.  Manually sending data to EDDN risks sending stale data to EDDN.

Perhaps we could allow sending FSDJump and Scan events to EDDN manually, provided they are less than a certain age.

**Comment by jfrob** [comment]
I'm assuming Scan data is probably as pretty much static (kinda like stellar position data is?) so would there be an issue even if it is few hours (or even a day or so) old? 

I'm not exactly familiar with the things involved here, so pardon the dumb questions..

**Comment by finwen** [comment]
wa plan to send  older data to later to EDDN. Just not finished wuth that
function yet.

2016-11-12 15:57 GMT+01:00 jfrob <notifications@github.com>:

**Comment by finwen** [comment]
Solved in EDDiscovery 5.1
