### ISSUE TITLE
Feature Request - Enable EDSM commander stat sync

### ISSUE THREAD

**Issue by XanatosX** [EDDiscovery/EDDiscovery#558]
Please add the ability to synchronize the commander stats like credits, current ship and ranks (factions and elite ranks).

Most of the data is already logged in the history, seems like there is a only a get request missing.

![image](https://cloud.githubusercontent.com/assets/10531466/20237973/f8633250-a8e0-11e6-93d2-a067a73da7f2.png)

![image](https://cloud.githubusercontent.com/assets/10531466/20237974/01c2d45e-a8e1-11e6-8f0f-dcb118cacdf0.png)

Thank you and sorry if this one was asked before and i didn't see it.

**Comment by finwen** [comment]
Plan to add this to EDDiscovery 5.1

**Comment by robbyxp1** [comment]
Its in 5.1
