### ISSUE TITLE
Feature Request: Network access to monitor travels

### ISSUE THREAD

**Issue by Shand359** [EDDiscovery/EDDiscovery#559]
Wondering if it would be possible to set this up on my laptop to monitor the travels of the game on my main PC system.

I used to be dual monitor but a minor catastrophe has reduced me to 1 now. I would like to use my laptop to run EDDiscovery and monitor and show the travels of my CMDR on the laptop instead of my main system.....

**Comment by klightspeed** [comment]
An easy way to do this would be to share your journal directory on your network, connect to that share on your laptop, and override the journal directory for your commander in EDDiscovery to that directory.

**Comment by Shand359** [comment]
I did try this but for some reason it would not work. I assume it's searching for the game on the laptop and not finding it.....

**Comment by klightspeed** [comment]
By "it did not work", do you mean it spat out an error, or that it didn't find any journals in the specified directory, or something else?

Do any of the recent Trace logs in %LOCALAPPDATA%\EDDiscovery\Log contain lines starting with anything like:
* `New watch X:\`
* `Scanned X:\`
* `File Read X:\Journal.161112xxxxxx.01.log`

**Comment by Nepukadnezar** [comment]
maybe creating a symbolic ( https://en.wikipedia.org/wiki/Symbolic_link ) link to the journal located on the network share would do?

**Comment by robbyxp1** [comment]
closed due to age
