### ISSUE TITLE
Bug: When Dying the respawn System doesn't count as visited System

### ISSUE THREAD

**Issue by muthan** [EDDiscovery/EDDiscovery#560]
I did die yesterday. But the respawn System doesn't show in my log as visited at that point in time since the respawn event isn't counted as a travel event.

This results in the 3D map as a big jump from the System I died in to the first System I jumped after respawn. (As a result to that also not send to EDSM)

Version 5.0.17

**Comment by robbyxp1** [comment]
Resurrect does not carry location
You should have had a location event after this..
The 3dmap at the moment only considers FSDJumps, not Location, so does not account for this

Fix 3dmap to understand locations when making up the travel history and break the path if required.

**Comment by muthan** [comment]
It's not only for the 3d map. Syncing to edsm does the same.

And there is a location event since it recognizes where you are docked.
When I remember correctly it states system and station
(at work at the moment so have to check later)
