### ISSUE TITLE
spurious commander entry in database

### ISSUE THREAD

**Issue by draeath** [EDDiscovery/EDDiscovery#561]
ID 1 seems to prepopulate for me with empty values. Rather than explain further, please check the screenshot of the application, and of the EDDUser.sqlite Commanders table.

I have done nothing yet but run the application, wait for initial network DB syncs, and restarted when prompted. I then exit and examined the sqlite db.

![2016-11-13_2251](https://cloud.githubusercontent.com/assets/987449/20252889/480335b2-a9f4-11e6-941e-d0a65a053bf4.png)

![2016-11-13_2253](https://cloud.githubusercontent.com/assets/987449/20252890/4ab76bd4-a9f4-11e6-9b90-bd279f8eee71.png)

**Comment by draeath** [comment]
I dropped the spurious commander, changed the ID of the real commander, and then /w a few SQL statements updated the other tables (`update tablename set CommanderId = '1' where CommanderId = '2'`)

This seems to have worked, with no visibly adverse effects.

**Comment by robbyxp1** [comment]
Fixed in 5.1, when you run a fresh install, and the first commander is found, it replaces row 1 with the new commander
