### ISSUE TITLE
Unhandled exception when updating material counts in popout window

### ISSUE THREAD

**Issue by andybish** [EDDiscovery/EDDiscovery#572]
[Trace_20161122173745.log.txt](https://github.com/EDDiscovery/EDDiscovery/files/607199/Trace_20161122173745.log.txt)

**Comment by andybish** [comment]
Seems to be caused by adding conductive ceramics with the dropdown, adding a number, then clicking apply

**Comment by robbyxp1** [comment]
Reproduced the bug by copying one Name row entry to next, DB table disallows multiple entries where name and category is the same.

Added code to screen this out, name changes to another identical name/cat is disallowed on a row.

Also, fixed price not being saved on a new entry in commodities

Will be fixed in next 5.1.X release.

**Comment by Tomparkes93** [comment]
still occurring in v 10.6.0.0 - 

### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: SplitterDistance must be between Panel1MinSize and Width - Panel2MinSize.
>   at System.Windows.Forms.SplitContainer.set_SplitterDistance(Int32 value)
>   at System.Windows.Forms.SplitContainer.ApplyPanel1MinSize(Int32 value)
>   at System.Windows.Forms.SplitContainer.set_Panel1MinSize(Int32 value)
>   at EDDiscovery.UserControls.UserControlShoppingList.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\EngineeringSynthesis\UserControlShoppingList.cs:line 317
>   at EDDiscovery.UserControls.UserControlSynthesis.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\EngineeringSynthesis\UserControlSynthesis.cs:line 304
>   at EDDiscovery.UserControls.UserControlSynthesis.Discoveryform_OnNewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\EngineeringSynthesis\UserControlSynthesis.cs:line 183
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 447
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 434
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(Tuple`2 entries) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 186
>===== END =====
>```
