### ISSUE TITLE
Feature Request - Comdr Note Log

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#578]
Before anything, congratulations and thanks for all the improvements made on the last release and the huge add-ons in the beta. It's quite stunning!

I don't feel good in propose one more feature request - even more after you announced that we will have screenshots organized in sub-folders! - but there's only one thing I really miss: a cmdr note log. 

I found that some time I need to put some specific annotations - like peculiar system features, factions reputation, tasks, interstellar factor and black market in station... - which are connected to the current system I am. This way, whenever I enter the system, they are displayed in a grid, sorted by date (or something else...). 
Other notes must be sticky - as some material I need to find, or to remember me that I'm currently wanted by a faction, etc... - and will be very welcome sticky somewhere (another window?).
I know I can use the note linked to EDSM, but I found this field to be pretty 'exploration oriented', as far as I understand EDSM. Also, as there's only one field, it can be messy with many heterogeneous info...

I know is something not too hard to be done, but I lack all the skill needed, so I have to request for someone else to do that. But I'll happily donate some bucks to further support the development. This is also something I wish to understand: how can I donate some bucks? There's a paypal mail for which I can send some money? I feel that anyone who can and want, would be happy to support such development effort as EDDiscovery is. 

All the best, and thanks again!
Andrea

**Comment by robbyxp1** [comment]
We do it for love, not money

**Comment by robbyxp1** [comment]
You can note each journal entry.  but we don't support multiple notes per journal entry, just the ability to edit them more fully... hmmm is that what you want.

I suppose a new User control panel could be made with extended notes, keyed per journal entry... with dates against each entry (a DGV)

**Comment by andreaspada** [comment]
I know you do it for love, not for money. Is the way I work too: please, do not misunderstand me, I did not intended to offend. Just I felt that, as I placed many requests, I could help in some ways - as I'm not good in coding, I can at least pay a beer or a pizza, or something like...

But yes, I strongly feel the need for a better user notation system. The field is really small!

**Comment by robbyxp1** [comment]
Right click, select  Set note, now opens a bigger window, which i presume addresses this issue.

**Comment by andreaspada** [comment]
This is pretty good, thanks. However, I think that we can address this in a different ways.

A new SQL table, whith each entries refere to to:
a) CMDR
b) a SYSTEM

With some fields in:

F0) id 
F1) timestamp 
F2) Category
F3) Note

This way, we can have a table (like the materials list, i.e.) that display, for each system, a table of notes.

Examples:

#1
CMDR: Spadino
System: 78 Ursae Majoris
---
Entry: 1
       ---
       Date: 1/11/3301 - 13:04:32
       Category: Reputation
       Note: I'm almost done with the Alioth permit, as I close to became an ally of Alioth Independents.

---
Entry: 2
        ---
        Date: 4/11/3301 - 22:12:45
        Category: Materials
        Note: I discovered a moon with high jumponium materials...

#2
CMDR: Spadino
System: Sagittarius A*
---
Entry: 1
       ---
       Date: 21/12/3301 - 23:04:53
       Category: Travel
       Note: Finally, I managed to return to the center of the galaxy. This time, I chosen a different way, as I did not want to pass through Colonia before reach it. I took some time to explore the east side of the galaxy, quite under-visited yet...
However, what a gorgeous, badass monster this bad guy is!

And so on...

 I can try to figure out by myself, than propose a pull request, but certainly there's someone which can do it very quickly. 
After this is implemented, we can kindly ask for EDSM owner to allow to multiple private notes in EDSM db, which will be synced as the already functional notes...

Does this sound good?

P.S. sorry for the - possible - bad formatting. I'm writing this from my phone...

**Comment by andreaspada** [comment]
Maybe something like:

Such a table:

```
CREATE TABLE `Annotations` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Time`	NUMERIC,
	`StarName`	TEXT,
	`Commander`	INTEGER,
	`Title`	TEXT,
	`Annotation`	TEXT
);
```

StarName must link to a system in the travel log, of course. Not sure if the term is that. Commander is pretty self explanatory: each commander will have it's proper annotations...

"Title" and "Annotation" are user editable fields.

Than, a simple table listing - which could also be opened as a popup, like materials, modules, etc... - that display the entries as a simple list.

Not so difficult, but I can't understand how to start... sorry!
