### ISSUE TITLE
5.0.19.0 several Unhadled Exceptions when entering distances

### ISSUE THREAD

**Issue by Inhumierer** [EDDiscovery/EDDiscovery#579]
When entering distances -as usual- the actual EDD likes to crash.
![edd 5 0 19 crash](https://cloud.githubusercontent.com/assets/5598887/20628774/42bb953a-b328-11e6-8094-cc3ff8f4db87.png)

[Trace_20161125151007.log.txt](https://github.com/EDDiscovery/EDDiscovery/files/613479/Trace_20161125151007.log.txt)

**Comment by klightspeed** [comment]
That says that for whatever reason the clipboard was inaccessible.  Looks like we need to swallow the exception in `EDDiscovery.TrilaterationControl.SelectNextEditableCell`.

**Comment by klightspeed** [comment]
Fixed in #581
