### ISSUE TITLE
Many errors after 5.0.19 update and also in 5.1.1.0 Beta...

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#582]
So, I update my EDDiscovery from 5.0.18 to 5.0.19, and I receive lots of errors, and my history log abruptly disappeared!

```
EliteDangerous is not running.
Checking for new EDDiscovery maps
Loaded Notes, Bookmarks and Galactic mapping.
Scanning for bmp screenshots in d:\Users\andrea\Pictures\Frontier Developments\Elite Dangerous
Reading travel history
Map check complete.
History Refresh Error: Exception has been thrown by the target of an invocation.
Indexing systems table
Checking for new EDSM systems (may take a few moments).
Downloading systems from 25-Nov-16 13:41:19 to 25-Nov-16 14:16:00
System download complete
EDSM updated 1168 systems.
Loading completed, total of 4461709 systems
Refresh due to updating systems
History Refresh Error: Exception has been thrown by the target of an invocation.
Refreshing complete.
```

If I ask to reload my journal and rescan the netlog entries, it give me Unhadled Exceptions and close.

Also, when working on EDDiscovery 5.1.1.0 Beta, when I try to update the material and the commodity quantities it give me Unhadled Exceptions and close the app.

**Comment by klightspeed** [comment]
Please post the trace log.

**Comment by andreaspada** [comment]
Where I find that?

**Comment by andreaspada** [comment]
Got it. No, got them! I have 11 trace timestamped today. Here they are:

**Comment by andreaspada** [comment]
Here they are:

[Trace_25Nov2016.zip](https://github.com/EDDiscovery/EDDiscovery/files/613657/Trace_25Nov2016.zip)

**Comment by klightspeed** [comment]
This has been fixed in 5.1 - @finwen shall we backport the fix to 5.0.x?

**Comment by andreaspada** [comment]
There's any major problem if I install the 5.1.1 beta overwriting the 5.0.19 setup?

Enviado do meu iPhone

**Comment by andreaspada** [comment]
So, I followed the instructions to get freshly compiled portable builds with appveyor. Currently running 5.1.2.0 and everything's running smoothly. I notice also many performance improvements, the app is running fast than before.
KUDOS!
