### ISSUE TITLE
Where my EDSM annotations are and how to retrieve them again?

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#585]
After a previous EDDiscovery update - not sure what - my EDSM comments desapear from my history. My CMDR has an EDSM api key and is setup to send AND receive from EDSM. So, why my notes do not get synced?

Currently I'm running 5.1.2 and I wiped all my previous history (did backup, of course), than synced back with my journal and old netlogs. I thought that I could sync with EDSM and my comments would appear at the system. I'm missing something?

Thanks

**Comment by klightspeed** [comment]
Note sync etc. are only triggered on pressing the `EDSM Sync` button.

Are the comments in <https://www.edsm.net/settings/comments/list>?

https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/EDSM/EDSMSync.cs#L116 should be bringing the comments in.  If you use SQLiteBrowser to open `EDDUser.sqlite`, and browse the `SystemNote` table, are the notes there?

https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/UserControls/UserControlTravelGrid.cs#L183 should be grabbing those system notes that the above sync pulled in.

**Comment by andreaspada** [comment]
Thanks for the answer. So, I knew that EDSMSync was the responsible, and I try it at the very first. My comments are all at https://www.edsm.net/settings/comments/list - pages and pages - and when I browse EDDUser.sqlite do not appear any old comment. Just the few I made in this days...

Than, unexpectedly, I try again and, voila!, here it are my comments. I updated EDDiscovery with the last commitemens which maybe made a difference, though I do not understand why...

Anyway, in the meanwhile, I found another bug. When I'm exploring, and scanning a system, if I logoff and return, the body I scan after that do not appear in the scan window. There's a way to manually insert them, using the journal?

**Comment by klightspeed** [comment]
This sounds like the scan ledger is tripping up on either the new session or the `Location` event at the start of the session.  Note that the scan ledger gathers body info at runtime, and so as long as the scan events exist it should pick up on bodies in the system.

Are the missing bodies of the form `<SystemName> A 1 b` (i.e. prefixed with the system name), or are they named bodies that are not prefixed with the system name?

**Comment by andreaspada** [comment]
Well, not sure if I understood your question. Let me see...

Let imagine I'm scanning a system. I already scanned the main star and a couple of planets. Then, I have to logoff from ED. I logon after a while, and return scanning the system. No newly scanned body appear in the scan window.  
Do you can reproduce this?

**Comment by robbyxp1** [comment]
closed due to age
