### ISSUE TITLE
Some improvement suggestions - work in progress

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#592]
After using the latest EDDiscovery builds, I found some improvements I would suggest to be evaluated. They maybe are very low priority, much more oriented to daily use that something else.

1) Screenshots
As the scan window display the scanned information of the selected system, I would like to have my screenshots window display the (UI buttons here!)[last,first,random] screenshots of the selected system in history. Not sure how can be achieved: if the shots are organized per folder, which is a new feature, is almost trivial, but may be solved using journal, which track when a screenshot is taken, using the timestamp.

2) Cmdr Diary - #578
You rocksHave a popup window which has as many fields as needed to write down comments related to the cmdr: wanted state, faction reputation, materials needed for a particular recipe, mission related reminder, etc...
2a) The notes could be filtered in some ways. If are related to the current system they were write, they could be filtered to show the notes taken on a particular system. 
2b) Also it could exist a field which display, when you enter a system, the last note taken on the closest system.

3) Neighborhood map
A popup which display a small 3d map with a user defined range which display the neighborhood of the current position. A predefined range is used as well a dropdown list with some predefined ranges - 20Ly, 40Ly, 60Ly, 80Ly, 100Ly?
I found it especially useful when you are exploring a specific portion of the galaxy: I like to see where I already explored and what already recorded stars are close to me. I find that this could be less memory consumptive than the full galaxy map..

4) Materials and Data somewhat separated, or separable by filter
When I browse my materials list, I found that I would prefer to browse materials and data separately, especially if I need to sync with my current storage. 

---

As the title suggest, this is a work in progress, and just a resume of the feature I currently miss for an almost perfect tool. Currently, EDDiscovery - as per 5.1.5 - is stunning and extremely useful. 
Thanks to all the coders and involved for such effort! 
**You rocks!**

**Comment by robbyxp1** [comment]
1) hmmm the effort vs use would have to be determined
2) expansion of notes. doable.
3) is difficult not sure we can get opengl to co-operate.
4) may be difficult due to FD lack of info in journals

**Comment by andreaspada** [comment]
Just ad addiction:

5) First Discovery tag when check in EDSM. Currently, the EDSM API has this implemented. I can dig in the code to implement this... what is the class called when we enter a system?

**Comment by klightspeed** [comment]
Manual sync occurs at https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/EDSM/EDSMSync.cs#L82

Sending a log entry after a jump occurs at https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/EDSM/EDSMSync.cs#L266

The function that sends the request and parses the result is at https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/EDSM/EDSMClass.cs#L399

The json should contain a `systemId` attribute (which could be used with the submitted data to create the system in the EdsmSystems / SystemNames tables), and if it was newly created it should have a `systemCreated` attribute.

Perhaps we could have either a HistoryEntry object or out edsmid and discovered parameters to `SendTravelLog`, which are filled with the EDSM ID and whether the system was discovered by the submitter.

**Comment by AnthorNet** [comment]
The setLog API should reply wether a system was created in EDSM or not.
I can recheck my code for the exact field. But it was added the the same use in EDMC.

**Comment by robbyxp1** [comment]
Closed due to age.. please resubmit if required individually.
