### ISSUE TITLE
Feature request: Count selected systems

### ISSUE THREAD

**Issue by lausianne** [EDDiscovery/EDDiscovery#593]
I'd like to know how many jumps I made on my last trip. Easy solution: Show the number of selected systems. Ideally it will also show the time difference between first and last jump.

**Comment by robbyxp1** [comment]
Solved.  In the next issue, use the right click start marker/end marker and it will show totals

**Comment by lausianne** [comment]
Wow, that speed. Thank you, looking forward to it.
