### ISSUE TITLE
5.1.4 First chance exception

### ISSUE THREAD

**Issue by kahvipapu** [EDDiscovery/EDDiscovery#594]
Just downloaded 5.1.4 as program suggested, after starting exception fires, see attachment log file.

[Trace_20161129170532.txt](https://github.com/EDDiscovery/EDDiscovery/files/619346/Trace_20161129170532.txt)

Cant update to 5.1.3 since installers implies newer is already installed. Should i uninstall (and lose something?) or is the way to force it?

**Comment by klightspeed** [comment]
That suggests that the assembly redirection in `EDDiscovery.exe.config` isn't applying.

Would you please be able to confirm that `EDDiscovery.exe.config` exists in the same directory as `EDDiscovery.exe`?

**Comment by kahvipapu** [comment]
Yup, file exists in same dir as .exe file, in C:\Program Files\EDDiscovery\EDDiscovery. Renamed to .txt and attached here:

[EDDiscovery.exe.config.txt](https://github.com/EDDiscovery/EDDiscovery/files/619779/EDDiscovery.exe.config.txt)

**Comment by kahvipapu** [comment]
OpenTK.dll in my executable directory is v2.0.0.0, the error mentioned OpenTK v1.1.0.0. Could that be the cause?

**Comment by finwen** [comment]
Looks like you have an old version of EDDiscovery.exe.config.   I will checl that installer overwrites it correctly on install..

Test with the attached file

[EDDiscovery.exe.zip](https://github.com/EDDiscovery/EDDiscovery/files/619908/EDDiscovery.exe.zip)

**Comment by kahvipapu** [comment]
That config file is working, application started normally.

**Comment by finwen** [comment]
And i found the error in the installer. should overwrite file correctly in next release
