### ISSUE TITLE
5.1.4.0 unhandled exception

### ISSUE THREAD

**Issue by wickednoreaster** [EDDiscovery/EDDiscovery#597]
I'm not sure what happened, but here's the log file, as well as a screenshot of the crash notification:
![eddcrash](https://cloud.githubusercontent.com/assets/24266826/20744997/0d5d404a-b6ad-11e6-8727-880f5dc278c7.PNG)

[Trace_20161129235349.txt](https://github.com/EDDiscovery/EDDiscovery/files/621257/Trace_20161129235349.txt)

**Comment by klightspeed** [comment]
That seems to suggest that it's trying to send an update to a scan window that has been closed.

**Comment by wickednoreaster** [comment]
Well thank you. I wasn't overly worried because it opened right back up, but I know you guys like to get all the feedback you can to optimize stuff. I appreciate it!

**Comment by robbyxp1** [comment]
Will be fixed on master, added a deregister of newentry.. missing

**Comment by finwen** [comment]
solved with  #a32b3eaa440f8d9b4dc0b6e01e6b9a95cf4019b

and will be in release 5.1.5
