### ISSUE TITLE
Ledger Sell events not adding to balance correctly

### ISSUE THREAD

**Issue by svensven** [EDDiscovery/EDDiscovery#598]
On a Market Sell event, the ledger is adding 1 unit's sale price to the balance, rather than number-of-units * sale price.
E.g.:
![eddiscovery ledger](https://cloud.githubusercontent.com/assets/5736616/20773772/6c96a9b8-b74b-11e6-98c4-42fe94cc6aff.PNG)

**Comment by svensven** [comment]
At a guess, the 5th parameter on line 50 of EliteDangerous/JournalEvents/JournalMarketSell.cs
should be TotalSale rather than SellPrice?

**Comment by eproces** [comment]
Having same issue, attempting a fix now.

**Comment by svensven** [comment]
Fixed in 5.1.6.0. Thanks :)
