### ISSUE TITLE
2.2.0.0 Crashes

### ISSUE THREAD

**Issue by Bear67** [EDDiscovery/EDDiscovery#6]
I can load it up before I start Elite, but as soon as I do it'll report a crash and exit. If I start it after I have elite running I get two popup window's (Attaching).
![screenshot_5_a](https://cloud.githubusercontent.com/assets/5138687/8278158/d62ddc46-188e-11e5-88e7-a7dc593db028.jpg)
![screenshot_6_a](https://cloud.githubusercontent.com/assets/5138687/8278160/d8ec74ce-188e-11e5-83c6-3703e454c46e.jpg)

**Comment by Majkl578** [comment]
This seems to happen when you run E:D with elevated privileges (e.g. as administrator) and EDDiscovery with normal privileges.
As a workaround you can either not run E:D as administrator or run EDDiscovery as administrator.
