### ISSUE TITLE
Feature request - long distance route planning

### ISSUE THREAD

**Issue by ChrisJ66** [EDDiscovery/EDDiscovery#600]
Any chance of a multi-stage route planner? I'm thinking of when trying to return from a long exploration back to 'the bubble' and having the 1000ly limit within the game so when planning a route with EDD it either shows the accumulted jump distance or highlights each magic 1000LY waypoint. Plus the ability to then save that route within EDD for the next leg

**Comment by klightspeed** [comment]
Just set the "jump range" to 950ly or 1000ly and plan the route.

**Comment by ChrisJ66** [comment]
thanks klightspeed, simple fix :-)
