### ISSUE TITLE
 5.1.5.0 not sending credit value changes to EDSM

### ISSUE THREAD

**Issue by Nepukadnezar** [EDDiscovery/EDDiscovery#604]
All the credit changes are not beeing sent to EDSM. Flight logs etc is working fine. The Credit Balance though, doesnt change on the EDSM Website.
please check or proof me wrong.

**Comment by klightspeed** [comment]
We are working on support for sending commander profile updates (including credits) to EDSM.

**Comment by robbyxp1** [comment]
closed issue. being addressed
