### ISSUE TITLE
EDD 5.1.5 - Ledger not deducting donation missions from balance

### ISSUE THREAD

**Issue by CMDRLucienn** [EDDiscovery/EDDiscovery#605]
EDDiscovery v5.1.5 does not appear to be deducting donation missions from the running balance. It only corrects itself on the Load Game event:

![image](https://cloud.githubusercontent.com/assets/7802122/20946121/d0317d2a-bbc6-11e6-93bc-0df8519e0a58.png)

It seems that EDDiscovery is not reading the "Donation":XXXXXX field of the Mission Complete event.

**Comment by svensven** [comment]
Confirming fixed in 5.1.6.0.
