### ISSUE TITLE
Feature Request: Support for different Data Format

### ISSUE THREAD

**Issue by Pisisip** [EDDiscovery/EDDiscovery#61]
I can't sync with EDSM because it say wrong data format. I have the Italian locale so the format of the date is DD/MM/YYYY and EDSM refuse the log with an error.

I don't know if it can be considered a feature that should implement the EDSM site or is better by your program.

**Comment by AnthorNet** [comment]
Hi,
Proper date format should be implemented in EDD and in UTC.

**Comment by gregmalcolm** [comment]
The Italian format is the same format as British format. No complaints from there as far as I can tell. Not sure what else it could be though.

**Comment by Pisisip** [comment]
I have this error:

EDSM: Sending41 flightlog entries
EDSM sync ERROR:206:Date is not in the format YYYY-MM-DD HH:MM:SS
EDSM sync Done

![cattura](https://cloud.githubusercontent.com/assets/16593158/12180880/51a8f580-b57f-11e5-9b0d-82b3d4e77a5e.PNG)

**Comment by Pisisip** [comment]
It appears also this exception:

GetEDSMDistances exception:Stringa non riconosciuta come valore DateTime valido.
   in System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   in EDDiscovery.DB.DistanceClass.ParseEDSM(String json, String& date)
   in EDDiscovery.EDDiscoveryForm.GetEDSMDistances()

**Comment by finwen** [comment]
Can you go to the settings tab and enable EDSM logging.

And then add logfile here.     You will find it in  %localappdata%\EDDiscovery\Log

**Comment by Pisisip** [comment]
Here the log.
01.48.43; GET http://www.edsm.net/api-logs-v1/get-logs?startdatetime=2011-01-01+00.00.00&amp;apiKey=cf47f429cb8c99a51d97b0f53e408a836bfbbd86&amp;commanderName=Pisisip; 01.48.44; {"msgnum":100,"msg":"OK","logs":[]}; 01.48.44; GET http://www.edsm.net/api-logs-v1/set-log?systemName=V2578+Ophiuchii&amp;commanderName=Pisisip&amp;apiKey=cf47f429cb8c99a51d97b0f53e408a836bfbbd86&amp;dateVisited=2016-01-03+13.15.39; 01.48.44; {"msgnum":206,"msg":"Date is not in the format YYYY-MM-DD HH:MM:SS"}; 01.50.12; ExceptionRichiesta annullata: Timeout dell'operazione..; 




----Messaggio originale----

Da: notifications@github.com

Data: 07/01/2016 23.46

A: "EDDiscovery/EDDiscovery"<EDDiscovery@noreply.github.com>

Cc: "Pisisip"<pisi78@inwind.it>

Ogg: Re: [EDDiscovery] Feature Request: Support for different Data Format (#61)




Can you go to the settings tab and enable EDSM logging.


And then add logfile here.     You will find it in  %localappdata%\EDDiscovery\Log

**Comment by finwen** [comment]
Thanks.  I see the error now. Should be solved easy in next version

2016-01-09 1:54 GMT+01:00 Pisisip <notifications@github.com>:

**Comment by finwen** [comment]
starttime.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture))

Needed to add Invariant culture.  Otherwise   time part was translated to  ex 12.23.45  for cultures with .  for time format.
