### ISSUE TITLE
5.1.6.0 Route finder many-jumps confirmation dialog ignores clicking "No"

### ISSUE THREAD

**Issue by svensven** [EDDiscovery/EDDiscovery#610]
The check on finding routes >100 jumps doesn't do anything. Route finding runs regardless of whether you click "Yes" or "No".
E.g. Finding a route from Sol to Colonia.

Can't tell just from looking at the code what the problem is.
https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/RouteControl.cs#L114

**Comment by klightspeed** [comment]
Looks like the idea was to return from the function but since the `return` is in a lambda (aka anonymous function) it just returns from the lambda.

Probably need a local variable outside the lambda, which is set when `Yes` is not clicked, and which is tested after returning from the lambda.
