### ISSUE TITLE
Screenshot conversion only takes place upon screenshot save

### ISSUE THREAD

**Issue by Aterfax** [EDDiscovery/EDDiscovery#62]
We could do with a feature enhancement where the program will convert all screenshots if the renamed equivalent at any time rather than relying on a new file causing the conversion.

I'm aware this might be intentional with respect to doing it only to new screenshots however it does make it difficult to convert existing screenshots even if you have your netlogs.

**Comment by Red13x3** [comment]
+1 this idea! I love it. I have thousands of screenshots of systems that do not have the proper system name. And that's all I want! I don't need the files converted to another format - that's my job to set at capture time. EDD should just worry about file names.

--
Mark
iPhone: 0402 322 901

**Comment by robbyxp1** [comment]
Will add a button later to do this..

**Comment by robbyxp1** [comment]
still on my list

**Comment by robbyxp1** [comment]
Closed. It more difficult and not worth pursuing.
