### ISSUE TITLE
EDDiscovery don't update my flight logs

### ISSUE THREAD

**Issue by bouricofus** [EDDiscovery/EDDiscovery#63]
Hello, I'm trying to use EDDiscovery with Horizon to update my flight logs and send them to EDSM, but I seem like there is an error in something. I indicate the correct folder of my logs with Horizon (C:\Program Files (x86)\Steam\steamapps\common\Elite Dangerous Horizons\Products\elite-dangerous-64\Logs) but I think there are corrupted cause EDDiscovery forget them and everything else work (http://prntscr.com/9nv4zz).

**Comment by finwen** [comment]
Are you sure vorboselogging are enabled in the logfile?  Need to reenable that after each  Elite Dangerous patch. 

Check this section in appconfig.xml 

    <Network
      Port="0"
      upnpenabled="1"
      LogFile="netLog"
      DatestampLog="1"
      VerboseLogging="1"
      >

**Comment by bouricofus** [comment]
Yes, it's enable and still don't work.

**Comment by finwen** [comment]
mail you appconfig.xml to me and 1 or 2 of your latest logfiles  so can i
check deeper.

robert.l.wahlstrom@gmail.com

2016-01-09 12:43 GMT+01:00 bouricofus <notifications@github.com>:

**Comment by bouricofus** [comment]
Mail sent

**Comment by gregmalcolm** [comment]
This resolved?

**Comment by bouricofus** [comment]
Yes, thank you.

2016-03-02 14:56 GMT+01:00 Greg Malcolm <notifications@github.com>:

**Comment by gregmalcolm** [comment]
Great to hear! :)
