### ISSUE TITLE
Exporter doesn't properly export MassEM value for planets

### ISSUE THREAD

**Issue by EfilOne** [EDDiscovery/EDDiscovery#630]
MassEM doesn't shows up in the csv at all regardless of the settings, probably due to the following :

In _EDDiscovery/EDDiscovery/Export/ExportScan.cs_ // Line 167 :

`writer.Write(MakeValueCsvFriendly((scan.nMassEM.HasValue) ? scan.nMassEM.Value : 0));`

Looks like it should be 
`writer.Write(MakeValueCsvFriendly(scan.nMassEM.HasValue ? scan.nMassEM.Value : 0));`
instead (syntax)

EfilOne o7

**Comment by klightspeed** [comment]
By "doesn't show up at all", do you mean that the column is not output, or that all values are 0?

**Comment by EfilOne** [comment]
Did those tests to see if it was specific to one given setting, without luck :
- USA/UK delimiter, with header, without header, all scans, planets only
- EU delimiter, with header, without header, all scans, planets only

Summed up, I have tried all settings combination possible to see if it was tied to some wrong set up on my end, without result.
On __every__ cases (both using "All", "Stars" and "Planets" modes), the MassEM column doesn't write at all

**Comment by iainross** [comment]
Very odd, it did work here when I wrote that line but I can have another look...

**Comment by iainross** [comment]
@EfilOne are you running the latest code or the last release?  MassEM was missing in the last release, I've added it since so I wouldn't expect it to work in build until 5.2 appears.

**Comment by EfilOne** [comment]
@iainross Running 5.1.6 here, so that must be it !

**Comment by iainross** [comment]
There you go then, I've already fixed it for the next release :)
