### ISSUE TITLE
Not reading flight logs with v5.1.6.0

### ISSUE THREAD

**Issue by ChrisJ66** [EDDiscovery/EDDiscovery#633]
Just noticed my flight logs have not updated since early Nov, I have download a couple of updates to EDD since then and have also tried uninstall/reinstall tonight

**Comment by klightspeed** [comment]
Is this the flight logs in EDDiscovery, or the flight logs on EDSM?

**Comment by ChrisJ66** [comment]
This is on EDDiscovery. I remember with earlier versions you had to point it to the right directory after every upgrade but thought that had been fixed a while ago

**Comment by iniaes** [comment]
I have this issue where it will be looking in my admin files whereas the game journal files are in my gaming account files, double check your directory pointers in ADMIN¬SHOW JOURNAL FILES DIRECTORY FOR CURRENT COMMANDER, and if needed amend this in the settings tab and setting the directory path in 'OVERRIDE JOURNAL LOCATION' for your commander.

**Comment by klightspeed** [comment]
EDDiscovery will by default look in the saved games directory of whichever user you are running it as.  If you are running it as a different user, then it will look in the saved games directory of that user.

**Comment by ChrisJ66** [comment]
Resolved.
For some reason it had changed to a different CMDR name, even though I only have 1.
