### ISSUE TITLE
Unhandled Exception on trying to open 3D map in route planner (out of memory?)

### ISSUE THREAD

**Issue by iniaes** [EDDiscovery/EDDiscovery#636]
[Trace_20161220135731.zip](https://github.com/EDDiscovery/EDDiscovery/files/663929/Trace_20161220135731.zip)

**Comment by klightspeed** [comment]
That suggests that it was running as a 32-bit program.

**Comment by iniaes** [comment]
Resolved by fix detailed in https://github.com/EDDiscovery/EDDiscovery/issues/637
