### ISSUE TITLE
Unhandled exception on trying to open 2D map from History Tab (Parameter is not valid?)

### ISSUE THREAD

**Issue by iniaes** [EDDiscovery/EDDiscovery#637]
[Trace_20161220143659.zip](https://github.com/EDDiscovery/EDDiscovery/files/663933/Trace_20161220143659.zip)

**Comment by iainross** [comment]
That zip file is empty when I download it...

**Comment by iniaes** [comment]
[Trace_20161220143659.zip](https://github.com/EDDiscovery/EDDiscovery/files/666280/Trace_20161220143659.zip)


Try this one,

**Comment by iainross** [comment]
That parameter is just a file name to load as a bitmap, I get the same error if I delete the jpg for my default map so one of yours has presumably gotten lost or corrupted somehow.

If you go to C:\Users\%user%\AppData\Local\EDDiscovery and delete the Maps directory then restart the application then it should re-download the maps.  Give that a go and let us know if it solves your problem.

**Comment by iniaes** [comment]
This has resolved both of my issues, many thanks o7
