### ISSUE TITLE
ED-Materializer backend api prototype

### ISSUE THREAD

**Issue by gregmalcolm** [EDDiscovery/EDDiscovery#64]
I put together a rudimentry first draft backend prototype while I was stranded on an old mac laptop last week.

Schema information is here:

https://github.com/gregmalcolm/ed-materializer/blob/master/schema.md

The app is currently deployed to heroku using a cheap one server node freebie package.

https://ed-materializer.herokuapp.com/api/v1/world_surveys

It's very, very basic right now and probably making a bunch of faulty assumptions. It supports basic CRUD operations on a single World Surveys table. It currently has no security and the api interface could definitely be improved on lots. For example, it cold be smarter about handling updates/inserts. Plus the data schema is likely way off base.

I went with the assumption that there could be one entry per commander per world, with the sum of changes being what's shared. That assumption is probably way off, but had to start somewhere.

I really don't know if this thing will be even slightly useful or not as EDDB is clearly the ideal place for the data to live longterm, but it was just something to play with for a bit. If we need any improvements or tweaks that should be pretty easy to do. I can also find better hosting for it if there's ever a need. And if it doesn't end up getting used, that's fine too.

**Comment by finwen** [comment]
Great. 

I just want a few more items in the schema now.

ArrivalPoint   float
Atmosphere_type  int
Vulcanism_type int

And maybee radius  to  got a suggestion of that,

**Comment by Red13x3** [comment]
Apparently Gravity is important to know.

--
Mark
iPhone: 0402 322 901

**Comment by gregmalcolm** [comment]
Very!

Columns have been added. The database schema looks like this now:

https://github.com/gregmalcolm/ed-materializer/blob/master/db/schema.rb
https://ed-materializer.herokuapp.com/api/v1/world_surveys

**Comment by finwen** [comment]
One question.

world_type  should we have it as string  or as an integer with defined types?

**Comment by gregmalcolm** [comment]
I currently have it set as a full string in the api database. It's a little
easier to eyeball the data that way and I don't really  anticipate it
needing good index or being used in joins. But if that were the case a good
strategy might be to make it 4 or 5 character string field that translates
as an short acronym. Why? Very small strings are probably fine as index
fields for use in joins and filtering. But you also get the benefit of
being human readable when looking at the DB direct.

But I digress. It's currently a string, but I'm happy to switch to an
integer or a 5 char string if you want it to be indexable or consistent
with the sqlite db.

One other comment: When you see a string def in my Ruby based db schema,
it's 255 chars unless you see a "limit" clause adjusting it. Like in the
case of "Notes" which I made 4000 chars.

**Comment by Red13x3** [comment]
Defined types so we can use a drop list in the program. :)

--
Mark
iPhone: 0402 322 901

**Comment by Red13x3** [comment]
The human readable short form is fine too, as long as you can still use it in conjunction with a drop list in the program. For example "ELW" for Earth Like World.

--
Mark
iPhone: 0402 322 901

**Comment by gregmalcolm** [comment]
Mark: We don't really need the full names in the DB for droplists because we can just hard code the full names with mappings to the DB representations. It's a very finite list after all.

**Comment by gregmalcolm** [comment]
Nearly done with the essential features. I just need to write an EDD PR to use the new auth code and we're set... :D

**Comment by gregmalcolm** [comment]
Ok Auth is in. I think all the essential features about in. 

Though I'll tweak how the Debug build/Heroku server is set up before closing out, so that persons without the Release credentials can still test Prospector features. Because I really don't think everyone who contributes wants to have to ask me for an admin account first.

**Comment by QV** [comment]
I uploaded json export for systems, worlds, surveys and logs from monster google sheet. Diff can help a lot.




[monster sheet json export.zip](https://github.com/EDDiscovery/EDDiscovery/files/113781/monster.sheet.json.export.zip)

**Comment by gregmalcolm** [comment]
Thanks!

**Comment by gregmalcolm** [comment]
Materializer is up to v2 on the schema now so probably about time we closed this issue down. For further discussion just open threads on Materializer:

https://github.com/gregmalcolm/ed-materializer
