### ISSUE TITLE
SQL logic error or missing database

### ISSUE THREAD

**Issue by jthorpe4** [EDDiscovery/EDDiscovery#641]
After updating to the latest code, i get this error message and the system wont start up.
Going to try recreating them like ian666 suggested

[Log.zip](https://github.com/EDDiscovery/EDDiscovery/files/667683/Log.zip)

**Comment by jthorpe4** [comment]
After recreating the EDDSystem.sqlite, the program opened fine.  Not sure what corrupted my file as both the old and new files where both about 1.2gb.  Also it's worth noting that SQLBrowser thought the old file was encrypted and was prompting for a password.

**Comment by klightspeed** [comment]
None of our code applies any encryption or password protection to the database.  Perhaps if the EDDSystems.sqlite DB is detected to be corrupt, we should rename it and create a new DB.

**Comment by jthorpe4** [comment]
Hi klightspeed, yes that's what I was thinking just a corrupted file, not sure how I damaged it (disk checks came back fine).  But following Ian666 suggestion of moving and letting it recreate worked.
I'm happy for this to be closed but we probably should do the bad database detection, just incase a normal user gets it, at least reporting the filename it was trying to open, we guessed EDDSystems from the callstack.

**Comment by klightspeed** [comment]
Perhaps also do something similar for EDDUser.sqlite, except create periodic backups, and revert to a backup if the User DB is found to be corrupt.  With the systems DB, we would recreate it from the Systems.json and populated_systems.json

**Comment by robbyxp1** [comment]
Closed due to age
