### ISSUE TITLE
EDD 5.1.6: Unhandled exception when exporting visited stars.

### ISSUE THREAD

**Issue by Gimi1967** [EDDiscovery/EDDiscovery#644]
EDD 5.1.6.
Running EDD on a separate laptop.
Accesses journal path through Symlink to gaming PC journal path.
Override journal path is not set as the Symlink points to the default journal path on the laptop.
Symlink path = "C:\Users\gmhafenbradl\Saved Games\Frontier Developments\Elite Dangerous"

Not sure if this path stuff is relevant, but I'm including it as that is a deviation from a standard installation of EDD.

I get the following error when I try to export: See screen shots and trace logs.

![exception export visited stars](https://cloud.githubusercontent.com/assets/1433251/21451345/c75f34f4-c8fe-11e6-9cc2-08e1fbb495df.JPG)
![exception opening visited stars folder](https://cloud.githubusercontent.com/assets/1433251/21451344/c75e7aa0-c8fe-11e6-997b-57e70b57df4b.JPG)

[Trace_20161223103517.txt](https://github.com/EDDiscovery/EDDiscovery/files/670570/Trace_20161223103517.txt)
[Trace_20161223105323.txt](https://github.com/EDDiscovery/EDDiscovery/files/670569/Trace_20161223105323.txt)

**Comment by klightspeed** [comment]
Does the mentioned path `C:\Users\gmhafenbradl\AppData\Local\Frontier Developments\Elite Dangerous` exist?

**Comment by Gimi1967** [comment]
The path does not exist on the machine/laptop running EDD. It does of course exist on the game PC.
