### ISSUE TITLE
Screenshot can get position of wrong commander.

### ISSUE THREAD

**Issue by finwen** [EDDiscovery/EDDiscovery#648]
From Zed:

I just noticed a small bug with EDDiscovery.
When taking screenshots it uses the location of the commander that's selected rather than the one that's being played. 
Obviously it's only an issue for people that more than one commanded who then like me, start EDDiscovery and don't check it has the commander selected that they are playing.

**Comment by robbyxp1** [comment]
Think this is a bit esoteric.  We only support the currently selected commander at the moment, hooking it up to the last recorded commander would be interesting.

**Comment by klightspeed** [comment]
The `Screenshot` journal event records when a screenshot is taken in-game, and includes the system and body name, as well as the virtual path to the image (where `\ED_Pictures` refers to the path of the Elite Dangerous pictures directory).  Perhaps the screenshot directory watcher can wait a few seconds for the screenshot event to come through, and process the image when either the screenshot event has come through or the timeout has expired?

**Comment by phroggster** [comment]
Delaying when the image gets processed won't change anything affecting this issue. In order to resolve this, EDDiscovery either needs to automatically track the active commander and update a whole mess of UI, or FDev needs to implement a proper multi-commander interface.

**Comment by phroggster** [comment]
Wait, ignore that last post that I can't delete on mobile... You want to use the body information included in the journal event to determine the file name. That's doable.

**Comment by klightspeed** [comment]
Because the journal is associated with the commander, the commander can be extracted from the event.

**Comment by klightspeed** [comment]
#736 now uses the Screenshot journal event to link a new screenshot to a system.

**Comment by robbyxp1** [comment]
Closed Bravada addressed this
