### ISSUE TITLE
3D Map  add a grid for sectors.

### ISSUE THREAD

**Issue by finwen** [EDDiscovery/EDDiscovery#650]
Redfox - Today at 8:49 PM
Idea/suggestion for the 3D map. We already have two types of grids: coarse and fine. How about adding a grid showing the borders between the sectors on the X and Z axis? Personally I sometimes like to know/see where sectors start/end, especially when doing sector-specific exploration. Thoughts?

AFAIK that info is known or easily compiled, as I've done during some recent sector-'work' in the N/W quadrant. A sector's width and length are 1.28kly and the initial placement starts with a coordinates-offset of X=-0.06 and Z=+0.21 (and Y is around -0.02, but naturally not relevant for such a grid). That's as exact as I got it, but can look-up/confirm in the GalMap thread on the forum (will do that regardless)

According the Alot this is the exact offset (in ly): [-65, -25, 215]. Together with the side length of 1280ly that's the info needed for a grid overlay. But still, only to be considered if I'm not the only one interested in such a thing :wink:

Thadius Wynter - Today at 9:59 AM
+1. Sector grids would be pretty neat. :smiley:

**Comment by klightspeed** [comment]
Perhaps layer -2/-1/0/1/2 grids or a cubic grid with sector names?

**Comment by robbyxp1** [comment]
I looked and prototyped this in the summer..

But it makes the map look horrible when I did it, because you end up with just sector lines just dominating.. 

I would only do it if they faded into view at high zoom, just like was done with the fine lines.

**Comment by RedfoxCh** [comment]
> But it makes the map look horrible when I did it, because you end up with just sector lines just dominating when i tried to put the y lines on it..

The initial idea was to add a basic 2D grid (like the existing ones), so it would pretty much look the same as the regular 1kly grid. 3D sector-cubes would be an awesome addition, although I imagine the mess all those edges would make.

To limit the mess: As somewone "working" with sectors now and then I'm usually only interested in one layer of them, so maybe have an option to display/hide specific layers of sectors? And maybe filter by quadrants? And maybe filter by sepcific sectors? And only display sectors that have stars in them?

**Comment by robbyxp1** [comment]
Going to retire this as it appears that is not a priority.
