### ISSUE TITLE
[Feature Request] Export VisitedStars.txt to folder of choice on non ED gaming machines

### ISSUE THREAD

**Issue by Gimi1967** [EDDiscovery/EDDiscovery#654]
Low priority.

EDD version 5.2.0 beta.

In the beta EDD currently returns "Could not find VisitedStarsCache.dat file" when I try to export visited stars.
EDD is running on a separate machine apart from my gaming computer.

Would it be possible for EDD to allow us to save VisitedStars.txt in a folder of our choice or in a default location when the ED game files are not available locally on the computer running EDD. 

Alternative is to provide the path to EDD when exporting or to give EDD access to the game files path in settings somehow.

**Comment by Gimi1967** [comment]
Now if I could just get the title of this request right  :(

**Comment by jthorpe4** [comment]
Don't see why not, I've found the line of code I'll check with Finwen

**Comment by Gimi1967** [comment]
I see there is a commit to the code to do this now. 
Thank you very much.
