### ISSUE TITLE
Better filtering in Materials panel.

### ISSUE THREAD

**Issue by finwen** [EDDiscovery/EDDiscovery#661]
shimozu | vashts6583 - Could I ask for better filtering within the S-Panel?  Specifically for materials.  Can't see only Encoded materials to get them up to date and the like
so if I only wanted to see Encoded materials, and then sort those by name

Finwen (EDDiscovery) - Igår 21:22
could probably add a filter for Category?

**Comment by robbyxp1** [comment]
We could.. low priority for me at the moment

**Comment by robbyxp1** [comment]
Closed at the moment, we are not going to address this due to complexity.
