### ISSUE TITLE
"Remove zero items" doesn't delete last item.

### ISSUE THREAD

**Issue by Uriei** [EDDiscovery/EDDiscovery#662]
In the commodities section, even if I have "Remove zero items" permanently enabled, there is always 1 item there with quantity 0, so far, always the last item I had before selling it.

![eddiscovery_2017-01-03_12-38-58](https://cloud.githubusercontent.com/assets/6078221/21606726/a51c0866-d1b1-11e6-899e-017ff4732e4f.png)
![image](https://cloud.githubusercontent.com/assets/6078221/21606739/bc289006-d1b1-11e6-9dd1-e07db5fe5ee5.png)

**Comment by robbyxp1** [comment]
This is on purpose.. it deletes it on the next material update.. this is to allow you to see that the item has gone to zero
