### ISSUE TITLE
Extremely large trace_*.log file.

### ISSUE THREAD

**Issue by tivec** [EDDiscovery/EDDiscovery#665]
I started getting notifications that my harddrive space was running low, so I tracked down my largest files. In my %appdata%\Local\Eddiscovery\Log folder, I had a Trace_*.log file that was 44GB of size.

This seems a bit excessive - what could have caused this?

If it is just a log file, and isn't vital for the operation of the software, perhaps you should consider making it a rolling log that keeps at a maximum size.

Edit: Should be noted that I deleted the log file, I had 300mb free on my drive...

**Comment by klightspeed** [comment]
How long had EDDiscovery been running at this stage?

From that volume of logging, either there were a tonne of exceptions being thrown and swallowed, or something was going to town with logging minutiae.

Perhaps we should consider some sort of log spam detection - e.g. "last message repeated n times" and/or a stack trace followed by silencing of a log source (a caller of Trace.WriteLine, Console.WriteLine or a first-chance exception) when that log source writes more than e.g. 100 lines within a certain amount of time.

We need to audit where exceptions are swallowed, and make sure either only expected exceptions are swallowed or that the try/except blocks are as small as possible.  e.g. DB exceptions mean that depending on the exception we need to either retry the transaction or abort.  Once that audit is complete, we could attach the first-chance exception logging to e.g. a command-line option.

**Comment by tivec** [comment]
I may have left EDDiscovery running over night, without the game running, and it was the first day I was using it, so there couldn't have been that much data to log... Unfortunately, considering the size of the log, I wasn't even able to open it in a text editor.

A log spam detection is probably wise :)

**Comment by klightspeed** [comment]
5.2.2 contains #667, which should prevent this from occurring.

**Comment by tivec** [comment]
Cheers! When is 5.2.2 expected to land (if I many ask)? :)

**Comment by tivec** [comment]
Scratch that! I saw it was already released.
