### ISSUE TITLE
Trilateration - Add All Button

### ISSUE THREAD

**Issue by thadius856** [EDDiscovery/EDDiscovery#668]
Strange, I know, but some of us are still silly enough to still do trilateration. Usually en masse.

Have been dumping 100-500 systems into local wanted. When I go to trilaterate, it takes several minutes to individually click each system in the right panel to move them to the left panel. Is it possible to have an `Add All` button added? Or separate `Add All Local` / `All All EDSM` buttons would be great too. 🙏

**Comment by iainross** [comment]
Also added in https://github.com/EDDiscovery/EDDiscovery/pull/670 (went for separate all local and all edsm options)
