### ISSUE TITLE
Trilateration - Warning When System is Not Last in History

### ISSUE THREAD

**Issue by thadius856** [EDDiscovery/EDDiscovery#669]
It's happened before where I've forgotten to click the `Start New` button, then found and submitted 50+ distances. They all made their way to EDSM, but landed on the wrong system... one I had been at a few or dozens of jumps ago.

When this happens you have to go into EDSM and manually delete each distance (which can take quite a while when there's 100 of them). Then I have to screenshot each page of the distances before I click `Start New` and wipe them, then re-type and re-submit them against the correct system.

Is it possible to add a check once `Submit Distances` is clicked to make sure the system listed in the `System` field matches the last system in History? If they don't match, suggest just popping up a warning to the effect of:

```
:WARNING: System & History Mismatch

The system you are about to submit distances to does not match the last system
from your travel history. Distances will be sent to $sys. Please double-check you
collected this distances from this system.

• Continue submitting •     • Update system and submit •     • Cancel •
```

**Comment by AnthorNet** [comment]
Sounds like a good idea ^^

**Comment by iainross** [comment]
I'll do that later.

**Comment by iainross** [comment]
Added in https://github.com/EDDiscovery/EDDiscovery/pull/670
