### ISSUE TITLE
Unhanded UI exception, while running the master version

### ISSUE THREAD

**Issue by jthorpe4** [EDDiscovery/EDDiscovery#674]
[Trace_20170106234119.0.log.zip](https://github.com/EDDiscovery/EDDiscovery/files/691129/Trace_20170106234119.0.log.zip)

**Comment by iainross** [comment]
Looks like https://github.com/EDDiscovery/EDDiscovery/pull/680 too

**Comment by finwen** [comment]
Yes it should be solved now
