### ISSUE TITLE
5.2.3.0 does not display correctly on my second monitor

### ISSUE THREAD

**Issue by mp1963** [EDDiscovery/EDDiscovery#675]
From the release of 5.2.2.0 ED Discovery is no longer usable on my second display. 5.2.3.0 does not remedy the issue. Screenshot attached.
![eddiscovery5230](https://cloud.githubusercontent.com/assets/24973059/21740800/870099a6-d4bc-11e6-9b4d-cef259082f21.JPG)

**Comment by klightspeed** [comment]
This looks like the UI settings are screwed up, though I'm not sure why the tabs are not showing up, or why there is what appears to be a huge border.

What is the display DPI set to on the secondary monitor?
Is the window maximized on the secondary monitor?

**Comment by mp1963** [comment]
Screen resolution is set at 1920x1080 .. the DPI is whatever Win 10 sets it at but I would guess its 72. The window was not maximised because I can’t see any of the window controls. This whole thing started about 3 versions back. Up till then it all worked perfectly.

**Comment by klightspeed** [comment]
> the DPI is whatever Win 10 sets it at

If this is a small 1920x1080 monitor (e.g. 15"-19" or thereabouts), then Windows 10 will actually set the DPI ("size of text, apps and other items") to 125% (120dpi), while with e.g. a 20" or larger monitor it'll set the DPI to 100% (96dpi).

So, did it work correctly in 5.2.1 and/or 5.2.0, or are those also broken for you?

**Comment by mp1963** [comment]
I think, only because I don’t recall the version numbers, that 5.2.1 worked otherwise I would have filed a bug on Github ..

**Comment by mp1963** [comment]
Oh and for what its worth Win 10 says text size is 100% on my secondary monitor.

**Comment by mp1963** [comment]
Just to confirm 5.2.5 is still broken. No change.

**Comment by klightspeed** [comment]
Is there an `EDDiscovery.exe.manifest` file in `C:\Program Files (x86)\EDDiscovery\EDDiscovery`?

**Comment by mp1963** [comment]
No there is no such directory or file on my system.

**Comment by klightspeed** [comment]
What about `C:\Program Files\EDDiscovery\EDDiscovery`?

**Comment by klightspeed** [comment]
Does the issue still occur if you try running the portable version?

**Comment by mp1963** [comment]
Hmmm never tried that one. Will go and grab it.

**Comment by mp1963** [comment]
No the result is the same.

**Comment by klightspeed** [comment]
I am unable to replicate this.  Please show us a screenshot of the window when using the portable version.

**Comment by mp1963** [comment]
Screenshot as requested.
![ed discovery portable](https://cloud.githubusercontent.com/assets/24973059/21748805/768a5344-d586-11e6-8aac-e4ef15657584.JPG)

**Comment by mp1963** [comment]
Filed on GitHub

**Comment by mp1963** [comment]
Second screenshot of the portable version
![ed discovery portable 2](https://cloud.githubusercontent.com/assets/24973059/21748815/c42712c2-d586-11e6-801b-2a5fee84bdf5.JPG)

**Comment by klightspeed** [comment]
I am able to sort of replicate this by setting my primary display to something other than 100% and re-logging.  I'm guessing from the serious scaling that your primary display is a 4K display, and is set to something like 200% display scaling?

Please try this:
Right-click the EDDiscovery executable and click Properties
Click Compatibility
Check "Disable display scaling on high DPI settings"
Click OK

**Comment by mp1963** [comment]
Ok that half fixes the problem because now the fonts are so massive I can’t do anything with the screen. The font size is now fixed at huge, I am going to reinstall 5.1.6 and see if it works. What do I need to get rid off to ensure there is no trace of ED Discovery on my system ?

**Comment by mp1963** [comment]
Installed 5.1.6.0. HighDPI setting unticked. Works perfectly. Screenshot attached.
![ed discovery 5160](https://cloud.githubusercontent.com/assets/24973059/21748952/6e4f84f2-d58a-11e6-8b9d-7e67ad4b7cee.JPG)

**Comment by klightspeed** [comment]
That suggests that the system display scaling is still taking effect despite that "Disable display scaling" option being enabled - likely due to the system font sizes still being used.

I can confirm that the issue was introduced between 5.2.0 and 5.2.1

**Comment by mp1963** [comment]
Will you let me know when you have fixed this ? I won’t upgrade to 5.2.5 or later until you let me know its ok :-)
