### ISSUE TITLE
Version 5.2.4 does not display correctly on my second monitor

### ISSUE THREAD

**Issue by mp1963** [EDDiscovery/EDDiscovery#677]
As with the last few versions the app does not render correctly. Screenshot attached.
![eddiscovery5240](https://cloud.githubusercontent.com/assets/24973059/21742324/3b482416-d4e4-11e6-90b9-11fedaecdc8a.JPG)

**Comment by phroggster** [comment]
Can you confirm that your issue was addressed in 5.2.5 and later versions?

**Comment by mp1963** [comment]
Should have got back to you earlier, sorry. All problems with displays now resolved :-) Many thanks.
