### ISSUE TITLE
Unhandled UI Exception - 5.2.4.0

### ISSUE THREAD

**Issue by Big-Gaz** [EDDiscovery/EDDiscovery#678]
I encountered the attached exception. Sorry about it being an image - I couldn't seem to c'n'p it as text.

After shutting EDD down and starting again it came up a second time.

![eddiscoveryerror](https://cloud.githubusercontent.com/assets/24977745/21743446/61b3a132-d4fa-11e6-8fbe-e13491b017fc.png)

Log file also attached

[Trace_20170107164943.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/691584/Trace_20170107164943.0.txt)

**Comment by iainross** [comment]
Should be resolved by https://github.com/EDDiscovery/EDDiscovery/pull/680
