### ISSUE TITLE
5.2.4 not drawing system diagram

### ISSUE THREAD

**Issue by ACDChook** [EDDiscovery/EDDiscovery#679]
After downloading the new release, it loaded up fine the first time, and initially drew the system diagram for what I had scanned so far, but when I scanned a new body, it had an unhandled exception. Reading through it, the trace mentions a file at V:\RobertW? Not sure if this is a path that's been hardcoded in for a dev's machine instead of finding the path on mine. The trace file is attached.

[Trace_20170108010519.0.log.txt](https://github.com/EDDiscovery/EDDiscovery/files/691599/Trace_20170108010519.0.log.txt)

**Comment by iainross** [comment]
Should be resolved by https://github.com/EDDiscovery/EDDiscovery/pull/680

**Comment by finwen** [comment]
v:\Robertw is the catalog i have my EDDiscovery project on. and itts the callstack showing functions and files then we get an error. So its the path at compiletime for the files,  Its just debug info.
