### ISSUE TITLE
Enhancement: Add a "Copy next system name in route to clipboard"

### ISSUE THREAD

**Issue by Uriei** [EDDiscovery/EDDiscovery#684]
In the Route/Expedition tab, just add an option that copies the next system name waypoint in the loaded route to the computer's clipboard each time you reach a waypoint, so we don't need to switch to EDD to copy the name then paste it on the Galaxy Map, with this, we would just need to paste and go.

**Comment by jthorpe4** [comment]
I was thinking of adding that to the new route tracker panel, so as you fly pass a waypoint it loads the next into the clipboard.
