### ISSUE TITLE
Idea: Neutron route planner

### ISSUE THREAD

**Issue by Uriei** [EDDiscovery/EDDiscovery#685]
I think it would be a nice feature to add a Neutron route planner option in the Route tab, in a way that it adds a line per time you need to open your Galaxy Map, something like:
From: Sol
To: Sag A*

0. Sol
1. "Nearest Neutron within minimum deviation from normal path, probably Jackson's Lighthouse."
2. "Somewhere you have to jump to from the previous Neutron, maybe even another Neutron."
3. "If the previous one was a Neutron, same as step 2, if not, next Neutron with normal pathing."
And go on until Sag A*

Then an option to Export this to Route/Expedition and save that, so you can save that route for future uses, and really useful combined with the other idea I already posted here in #684, because we will need to use GalMap a lot more than regular travel.

**Comment by thadius856** [comment]
If this is to be implemented, might suggest partnering with Spansh, the author of this neutron plotter:

http://www.spansh.co.uk/

He's on Fuelrats IRC and Discord, as well as a few other EDCD-like places. ;)

**Comment by Uriei** [comment]
I wrote this because there is no reference at all in the website of who I have to contact and how to send feedback, which in my book is a dead website, so I picked the next best thing, asking someone else I know that can do this same thing.

**Comment by spansh** [comment]
The website Isn't dead, though I just added contact details into it (and some new features) :)

**Comment by Uriei** [comment]
Neat, thanks :P

**Comment by robbyxp1** [comment]
Its been talked about.. we need to get the neutron list from EDDB somehow to finwen server, then we can download it and update the route planner

**Comment by robbyxp1** [comment]
No data available. Retired.

**Comment by spansh** [comment]
Assuming you're already downloading the system list from eddb and the bodies list from eddb then you already have the list of available neutron stars.

However, that said, would this help:  https://www.spansh.co.uk/api/neutrons

It's not updated realtime and is precalculated on a daily basis but it may help.  The only thing I would ask is to make sure it's downloaded compressed

**Comment by finwen** [comment]
We are not downloading bodies information from EDDB we only have star name
and positions. Only bodyinformatopn for the system you have visited...



2017-04-21 1:18 GMT+02:00 spansh <notifications@github.com>:
