### ISSUE TITLE
All distances not loading when program starts

### ISSUE THREAD

**Issue by aTUNEd** [EDDiscovery/EDDiscovery#7]
Great program! Hope this is the right place for a bug report.

Most of the times I start the program there are some distances in my log that don't load. In order for them to show up I have to do a combination of waiting and switching between the different "Show history for last".

If it's due to some sequential downloading from a server then I suggest some form of indication that distances are still loading =)

**Comment by finwen** [comment]
Yes its a known problem in version 2.2.   Thanks for reminding med. 

Distances are loaded in another thread and arrives later sp right now it shows first the you press resfreh (after loading is done)

**Comment by finwen** [comment]
Solved in 2.3.
