### ISSUE TITLE
Feature Enhancement: Filter by list in Scan Panel

### ISSUE THREAD

**Issue by Uriei** [EDDiscovery/EDDiscovery#702]
I think it would be great to be able to filter the Scan Panel by a user-defined filter for materials, so we would only see the materials wanted from each planet, per example, I only want to see Arsenic, Niobium, Yttrium and Polonium (Jumponium Tier3), so I only see those icons in the Scan Panel; right now, the only filtering option is hiding "Common" materials, and I think that's not good enough.

**Comment by andreaspada** [comment]
Great! I would love this too!

**Comment by robbyxp1** [comment]
Going to retire this one.. some integration between the new synthesis panel requirements and planets needs to be done, but probably not this way
