### ISSUE TITLE
System notes disappearing

### ISSUE THREAD

**Issue by tivec** [EDDiscovery/EDDiscovery#704]
I have noticed that the notes I do on systems sometime disappear, usually if a scan finishes as I am typing it into the notes box.

Steps to reproduce:
* Jump into an unoccupied system.
* Target the star in front of you and let the scan start.
* Type in a quick note on the "jump to" event.
* Wait for the scan of the star to complete.
* Watch as the note is first duplicated onto the scan event, and sometimes the note disappears from the jump event.

Reproduces at a seemingly random rate.

**Comment by andreaspada** [comment]
Already noticed this behavior. It's quite common, as I always type when I'm scanning some bodies and really happens as you state.
