### ISSUE TITLE
Autoscroll travel/history grids if you are at the top

### ISSUE THREAD

**Issue by jeoffman** [EDDiscovery/EDDiscovery#705]
I like the grid to scroll automatically and keep the latest/newest info at the top - only auto scroll if the top line or no line is currently selected, that way you can scroll down and click on any other line to get the old (non-auto-scrolling) behavior back.

**Comment by phroggster** [comment]
If you ask me, it's poorly worded, but does the checkbox setting named "History cursor to new Journal Entry automatically" solve your needs?

**Comment by finwen** [comment]
Should be fixed in 5.3.0
