### ISSUE TITLE
Errors in pre-defined routes

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDDiscovery/EDDiscovery#713]
When loading the pre-defined routes on the Routes/Expeditions tab, two systems are marked as "not found":
1) Ceeckia ZQ-L c24-0 because it was renamed to Beagle Point
2) Eactainds GN-W c1-6 because it was renamed to Rendezvous Point

In both cases, EDSM will display the old system name with a comment "system is hidden and moved to <new name>".

Please either fix the included routes, or extend the function that does the EDSM look-up to follow the renaming.

**Comment by phroggster** [comment]
This was fixed in release 4.0.3, which was deployed on July 26, 2016. Please try updating to a newer version.

**Comment by phroggster** [comment]
I think I meant to ask this 2 days ago, but can you confirm that this is still happening in release 5.2.8?

**Comment by klightspeed** [comment]
Pre-defined routes are editable, and are not replaced when the program is updated.

You should be able to edit and save those two routes to change those systems to the correct systems in your database.

**Comment by CMDR-Cometborne** [comment]
The update behaviour was the explanation why I still had the wrong names in my routes.  In hindsight, it is obvious.

I would still prefer it if entering "Eol Prou RS-T d3-94" as system name in a new route would lead to "Colonia" being added, instead of the "system is unknown" I still get in 5.2.10.0.  However, that is an enhancement request and not a bug, so I am closing this one

**Comment by klightspeed** [comment]
We could use the alias table to suggest alternative names when the system is unknown.

**Comment by phroggster** [comment]
I'm reopening this, as I already had branch going with some of the work done.

**Comment by phroggster** [comment]
This is somewhat resolved with 551fa72c1a52660ff091a1312eece13fe58998d7, but it doesn't actually update the displayed system name. I'm still working on a refactor for SavedRouteExpedition that'll handle it.

**Comment by robbyxp1** [comment]
Closed, too old. Reopen if still an issue.
