### ISSUE TITLE
Pasting in Routes/Expeditions always inserts at the top

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDDiscovery/EDDiscovery#714]
When using "Paste" in the system list on the Routes/Expeditions tab to add multiple systems, the systems are always inserted at the top rather than at the currently selected position.  "Insert Copied Rows" inserts at the currently selected position.

While I can see the point of having an "Insert at the top" functionality, calling it "Paste" is less than ideal.

**Comment by klightspeed** [comment]
`Paste` will insert the rows at the top if no rows are selected.  Otherwise, it will replace the selected rows with the pasted systems.

**Comment by klightspeed** [comment]
Is this resolved in 5.2.9 / 5.2.10?  #719 should have resolved this.

**Comment by klightspeed** [comment]
No response, so assumed to be fixed.
