### ISSUE TITLE
Single quote in Expedition name breaks dropdown

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDDiscovery/EDDiscovery#715]
If you use a single quote in the Expedition name on the Routes/Expedition tab and save the route, it will be correctly added to drop-down.  However, if you create another route/expedition afterwards, it will be added to the drop-down with an empty name.  The empty entry still works to load the expedition, but it is confusing.

To recover, you need to change the name of the expedition with a single quote in it to no longer contain the quote, and restart ED Discovery.

**Comment by phroggster** [comment]
Thanks Cometborne, we'll look into it. That said, I wonder if this is Bobby Droptables's fault...

**Comment by klightspeed** [comment]
I think the issue is that we currently only update the dropdown when a saved route is created or deleted.

**Comment by phroggster** [comment]
The submitted PR should clear this one up.

**Comment by phroggster** [comment]
Just discovered that the fix didn't get merged into the release branch, so it wasn't included in 5.2.9 nor 5.2.10. I just merged it in, so this should be resolved in the next release.
