### ISSUE TITLE
(enhancement) load expeditions from EDSM

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDDiscovery/EDDiscovery#716]
The routes/expeditions tab currently only contain two expeditions: Distant Worlds 3302 and Sagittarius-Carina.  It would be nice if it was possible to import expeditions from EDSM, rather than having to manually copy&paste the waypoints from the forum posts.

**Comment by jthorpe4** [comment]
That was on my to-do list to contact the EDSM team and ask about an API. EDSM does allows you to export routes to file that can be loaded into EDD via the import file button.

**Comment by jthorpe4** [comment]
I checked with EDSM, they currently don't have an API but it is something they could add in the future maybe. So I'll keep an eye out.

**Comment by phroggster** [comment]
There aren't all that many expeditions listed on EDSM, we should probably just include them in the installer as loadable files or even pre-populated in the menu.

**Comment by AnthorNet** [comment]
Generating a JSON tomorrow

**Comment by robbyxp1** [comment]
No interface for this from EDSM, closing
