### ISSUE TITLE
Release 5.2.8

### ISSUE THREAD

**Issue by VonDugard** [EDDiscovery/EDDiscovery#720]
Having downloaded this last patch, I find that it sits in the top left hand corner of my screen and I'm unable to open it.

**Comment by phroggster** [comment]
An issue was identified that may be causing this, and a [solution ](https://github.com/EDDiscovery/EDDiscovery/pull/717 )has been devised. Until the next version gets rolled out, the easiest thing to do is as follows (for Windows 10):

1. Exit EDDiscovery if it is running.
2. Search your Start Menu for EDD.
3. Right-click the entry, and select "Open file location."
4. Copy the EDDiscovery shortcut, then paste it somewhere, such as your desktop.
5. Right-click the new shortcut, and select properties.
6. In the Shortcut tab, add -NoRepositionWindow to the end of the Target field. It should end up being something like `"C:\Program Files\EDDiscovery\EDDiscovery.exe" -NoRepositionWindow`
7. Click OK, then double-click this new shortcut. The window should now launch at a reasonable size and position.

**Comment by finwen** [comment]
This should be improved lots in 5.2.9  and can also hold down shift button to skip reposition and resizing of windows on start.
