### ISSUE TITLE
Editing materials, hitting "remove zero" before hitting apply undoes all changes

### ISSUE THREAD

**Issue by xxiii23** [EDDiscovery/EDDiscovery#727]
I edited all my materials to match my actual inventory. I then checked the "remove zero items" option. This appears to have undone all my changes and reverted to the pre-edited state. (this is non-intuitive / not what I would expect to happen).

**Comment by xxiii23** [comment]
v5.2.8.0

This issue also affects the Commodities panel.

**Comment by klightspeed** [comment]
https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/UserControls/UserControlMaterialCommodities.cs#L218

This currently requests that the materials/commodities ledger be re-calculated, which will result in the materials and commodities panels being refreshed.  We probably should hook the cell modification events, and store any user-entered data over a refresh so it can be included in the refreshed materials/commodities display.

**Comment by klightspeed** [comment]
PR #729 should fix this.

**Comment by klightspeed** [comment]
Is this fixed with 5.2.10?

**Comment by robbyxp1** [comment]
Closed, no response, presumed fixed
