### ISSUE TITLE
in materials panel, remove zero doesn't work, alters sort-order with incorrect indicator

### ISSUE THREAD

**Issue by xxiii23** [EDDiscovery/EDDiscovery#728]
In the materials panel, checking/unchecking remove zero items doesn't seem to have any effect, at least for Encoded items. Additionally, it causes the panel to be redrawn sorted by name, but the header still shows the up/down sort arrow indicator on whatever column was last sorted by (even though the panel is no longer sorted by that (if it wasn't "Name"))

The sort-order problem also applies to the Commodities panel (but it does remove zeros correctly).

v5.2.8.0

**Comment by xxiii23** [comment]
I just edited (and applied) my commodities to remove an item I don't have, and this item (with a 0 "Number") still shows up when I check "Remove zero items".

**Comment by klightspeed** [comment]
The `DataViewScrollerPanel` needs to expose the `SortedColumn` and `SortOrder` properties and the `Sort(DataGridViewColumn, ListSortDirection)` method.  Then the `SortedColumn` and `SortOrder` needs to be captured in `Display()` and used as parameters in the `Sort()` method.

To fix numbers being sorted lexicographically, one option would be to expose the `SortCompare` event and use that to override the comparison.

**Comment by klightspeed** [comment]
PR 729 should have fixed the sorting issue.

**Comment by klightspeed** [comment]
Is the incorrect sort order fixed with 5.2.10?

**Comment by robbyxp1** [comment]
Closed, presumed fixed
