### ISSUE TITLE
commiting old data for new system

### ISSUE THREAD

**Issue by muthan** [EDDiscovery/EDDiscovery#73]
I think I did the following (not 100% shure)

* At first I trilaterate a new system so I get the coordinates, submit it to EDSM, normal as always.
* fly to the next system
* want to trilat it but instead of fillng the distance cells i submitted data, and suddenly the old data is submitted

the thing where I am not shure is how i got to the trialeration tab. either the tab or button. and I don't remember if the cells were filled with old data or not first guess would be I used the button an submitted empty cells.

after that I typed in the new ones submittet them and the also where on edsm.
really weird bug.

I am on version 2.6.8.0

**Comment by iainross** [comment]
If you click 'Start New' on the trilateration tab then it should blank all the distances - if you then try to submit the blank grid to EDSM the app should ignore you.

If you move in ED and then hit Submit on the trilateration tab without clicking 'Start New' then it will (re)submit the distances to the target system on the trilateration tab - NOT the latest system in the travel history.

So unless you've found a way to change the target system without the distances to the old target being blanked then everything should be fine - and if you'd done that you'd see the dodgy distances in EDSM.  Assuming you don't then I don't think there's an issue here.

**Comment by AnthorNet** [comment]
From what we see on EDSM, that problem occurs a lot of time.

**Comment by finwen** [comment]
YEs its a strange problem. I am looking for it but have not understand why it happends yet.

**Comment by AnthorNet** [comment]
Any news on that issue? Still removing lot of wrong double distances.

**Comment by finwen** [comment]
Dont know yet how to reproduce it.  I know it has happend to me just dont
know how yet.

Anyone know how to make this happend atleast more often?  Then i can easier
find and fix it.

2016-02-04 13:49 GMT+01:00 AnthorNet <notifications@github.com>:

**Comment by iainross** [comment]
I'm fairly sure it's never happened to me - but I did re-write the code that prepares the collection of distances to submit when I allowed submission of distances to positions without known co-ordinates so there's a chance I may have incidentally fixed it...  Hard to say without knowing why it was happening before but it'd be good to know if EDSM stops seeing the wrong double distances from the next version.

**Comment by AnthorNet** [comment]
I will monitor that as giving you some access to our admin tools, just need to change some things to make them available.

**Comment by iainross** [comment]
If "first guess would be I used the button an submitted empty cells" is what's really happening then I should have made it go away.  It was previously getting the distances to submit from EDD's last trilateration result but since I excluded unknown system positions from that collection I had to make submitting to EDSM go back to the grid for the distance data.  So if the problem is down to there being  a way to have the grid being blanked without the last trilateration result's collection of systems and distances being nulled and that collection then being submitted against a new target system if you hit the submit button before you do anything else to trigger a new trilateration in EDD then it should be solved, if it's some other problem then I'm unlikely to have effected it.

**Comment by AnthorNet** [comment]
Then we can assume it's fixed, I'll monitor that.
What is your CMDR name on EDSM?

**Comment by iainross** [comment]
CMDR Cruento Mucrone

**Comment by finwen** [comment]
Will release a new version soon so we can see if this error will happens
less.

2016-02-04 15:27 GMT+01:00 iainross <notifications@github.com>:

**Comment by iainross** [comment]
@AnthorNet has this reduced in frequency since my changes went live?  Maybe even disappeared if everybody updates to a new version when it's available (ha ha).

**Comment by AnthorNet** [comment]
As far as I concerned, issue can be closed.
I did not see anything related to that, for now.
I'll try to do some database scan today just to be sure.
