### ISSUE TITLE
Enhancement: Select events from start point

### ISSUE THREAD

**Issue by tivec** [EDDiscovery/EDDiscovery#730]
I like to have several EDDis popouts open when I am exploring, and one of them is the Travel History window showing only my FSD jumps. 

As an enhancement, would it be possible to get, in the "time" menu or elsewhere, an option to display since the last start/stop point? I think the time menu would be a good place for something like this.

![Feature Suggestion Image](http://i.imgur.com/IagumQw.png)

**Comment by robbyxp1** [comment]
Finally being done!
