### ISSUE TITLE
Application window not accessible

### ISSUE THREAD

**Issue by skndn60** [EDDiscovery/EDDiscovery#733]
With 5.2.8.0 the main application window is now a tiny inaccessible strip in the top left of my screen. No matter what I do, I'm unable to resize it to its normal proportions. I tried to reinstall and various desktop window settings (cascade windows) but to no avail.

**Comment by phroggster** [comment]
See my comments in https://github.com/EDDiscovery/EDDiscovery/issues/720

If they helped you, please close this issue. 5.2.9 should be coming very soon, which will correct this issue for good.

**Comment by skndn60** [comment]
Yup that did it, thanks.
