### ISSUE TITLE
Feature request : Allow EDDUser.sqlite location to be changed

### ISSUE THREAD

**Issue by mpfj** [EDDiscovery/EDDiscovery#734]
I run ED on 2 PCs (home and work).

I'm currently using Captain's Log to track my progress, and this allows me to specify where the db file is located.  This allows me to placed my db file in my Dropbox folder, so I can keep things synced between PCs.

I know I could use the portable EDDiscovery version on a USB stick, but that seems a bit backward.

Could I request that the EDDiscovery user db location be changable ?

AFAICT all other files are "common" between the PCs ... it's only the user db that holds the dynamic log data.

**Comment by klightspeed** [comment]
So you're wanting the User DB to be stored separately to all of the other files?

We could add a command-line option and/or a EDDiscovery.exe.config setting to change the path to EDDUser.sqlite - much in the same vein as the `-Appfolder` option, which overrides the entire app data directory location.

**Comment by mpfj** [comment]
Yes ... a config setting to change the path would be perfect :)

**Comment by klightspeed** [comment]
#735 added this option - this will allow one to use either `-UserDBPath /path/to/db/file` or add `<add key="UserDatabasePath" value="/path/to/db/file" />` to the `appSettings` section of `EDDiscovery.exe.config`

This should be available in 5.3

**Comment by mpfj** [comment]
Well, that's amazingly quick :open_mouth:

Thank you

**Comment by mpfj** [comment]
Can't be 100% but I think when you update EDD, this config setting didn't seem to be copied over.

**Comment by klightspeed** [comment]
Perhaps we should have a separate config file in the executable directory from which options are loaded (in addition to the .config file and the command-line options), as EDDiscovery.exe.config is one of the files that are replaced by the installer.

**Comment by klightspeed** [comment]
As of #784, you should be able to put an `options.txt` file into your install directory, which will be processed at startup, and specifies options to EDDiscovery.  For example, to specify the user DB path, add the following line to options.txt:
```
UserDBPath /path/to/db/file
```

**Comment by mpfj** [comment]
I see this isn't currently in the v6 branch.

Is that by design ?

**Comment by phroggster** [comment]
Tracking these things can be a pain, but it was cherry-picked on Feb 1 in time for the 6.0.3 release: 495584dc5eab613cf6f2506e3eb491bda87f9f20

**Comment by phroggster** [comment]
Oh, and the original PR #735 (to actually allow modifications, plus some other functionality) made it into 5.3: ee7a6f3e7884817dc26705089c9234fd76c699b7

**Comment by mpfj** [comment]
Ah yes, so it is.

In that case, looking at the code, the options names need to be lowercase, as in:-

`userdbpath /path/to/db/file`

... rather than `UserDBPath` as in the example given above :)

**Comment by phroggster** [comment]
Touché. It's typical practice to treat short parameters with case-sensitivity, but I don't see any of those. Some more `.ToLowerInvarient()` calls definitely appear warranted.

**Comment by klightspeed** [comment]
Probably need to change `kvp[0]` to `kvp[0].ToLowerInvariant()` at https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/EDDConfig.cs#L172

Either that, or add `optname = optname.ToLowerInvariant()` before https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/EDDConfig.cs#L202
