### ISSUE TITLE
5.2.9 does not start, cannot revert

### ISSUE THREAD

**Issue by lausianne** [EDDiscovery/EDDiscovery#739]
Hi,
I had an old version and installed the latest, 5.2.9 today. Now EDDiscovery does not start anymore. No error message on screen. This is in the logs (sry, german, I don't know how to change the language):

-------------

_Name der fehlerhaften Anwendung: EDDiscovery.exe, Version: 5.2.9.0, Zeitstempel: 0x58808cb0
Name des fehlerhaften Moduls: unknown, Version: 0.0.0.0, Zeitstempel: 0x00000000
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00007ffacc8ceda1
ID des fehlerhaften Prozesses: 0x15e4
Startzeit der fehlerhaften Anwendung: 0x01d2742ff0ee668a
Pfad der fehlerhaften Anwendung: C:\Program Files\EDDiscovery\EDDiscovery\EDDiscovery.exe
Pfad des fehlerhaften Moduls: unknown
Berichtskennung: d3453f61-3a09-4098-8090-06029059a74e
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:_  

_Anwendung: EDDiscovery.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.NullReferenceException
   bei EDDiscovery.EDDiscoveryForm.EDDiscoveryForm_Resize(System.Object, System.EventArgs)
   bei System.Windows.Forms.Control.OnResize(System.EventArgs)
   bei System.Windows.Forms.Form.OnResize(System.EventArgs)
   bei System.Windows.Forms.Control.OnSizeChanged(System.EventArgs)
   bei System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32, Int32, Int32)
   bei System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32)
   bei System.Windows.Forms.Control.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   bei System.Windows.Forms.Form.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   bei System.Windows.Forms.Control.ScaleControl(System.Drawing.SizeF, System.Windows.Forms.BoundsSpecified)
   bei System.Windows.Forms.ScrollableControl.ScaleControl(System.Drawing.SizeF, System.Windows.Forms.BoundsSpecified)
   bei System.Windows.Forms.Form.ScaleControl(System.Drawing.SizeF, System.Windows.Forms.BoundsSpecified)
   bei System.Windows.Forms.Control.ScaleControl(System.Drawing.SizeF, System.Drawing.SizeF, System.Windows.Forms.Control)
   bei System.Windows.Forms.ContainerControl.Scale(System.Drawing.SizeF, System.Drawing.SizeF, System.Windows.Forms.Control)
   bei System.Windows.Forms.ContainerControl.PerformAutoScale(Boolean, Boolean)
   bei System.Windows.Forms.ContainerControl.PerformNeededAutoScaleOnLayout()
   bei System.Windows.Forms.ContainerControl.OnLayoutResuming(Boolean)
   bei System.Windows.Forms.Control.ResumeLayout(Boolean)
   bei EDDiscovery.EDDiscoveryForm.InitializeComponent()
   bei EDDiscovery.EDDiscoveryForm..ctor()
   bei EDDiscovery.Program.Main()_

-------------

Trying to install an older version, I get "A more recent version of EDDiscovery is already installed on this computer."

**Comment by phroggster** [comment]
You can revert to 5.2.8 by uninstalling 5.2.9 and then installing 5.2.8. Or, you could use the portable zip file, located on the project's [releases](https://github.com/EDDiscovery/EDDiscovery/releases) page.

As far as why this is happening, what operating system are you using? Are you running any special window manager, theming, or desktop composition utilities like Windowblinds, UxStyle, or SharpEnviro, etc?

**Comment by phroggster** [comment]
Nevermind, I've found the root cause of this. It appears to only be triggered when running in a non-English locale, combined with a few specific form settings that we utilize (`Form.AutoScaleMode`, plus an unassigned `Form.Font`). I'll push a PR up to correct this shortly.

**Comment by phroggster** [comment]
5.2.10 is now available from the [releases page](https://github.com/EDDiscovery/EDDiscovery/releases). Please let me know if this build resolves your issue.

**Comment by lausianne** [comment]
Yes, 5.2.10 seems to work fine. Thanks!
