### ISSUE TITLE
BITMAP convert - exception raised 

### ISSUE THREAD

**Issue by robbyxp1** [EDDiscovery/EDDiscovery#74]
If you turn the delete original after conversion, it raises an exception.

This is because the BITMAP object keeps the file locked until its disposed.

quote from documentation BITMAP: Open from file:
The file name and path can be relative to the application or an absolute path. Use this constructor to open images with the following file formats: BMP, GIF, EXIF, JPG, PNG and TIFF. For more information about supported formats, see Types of Bitmaps. The file remains locked until the Bitmap is disposed. 

And there is another problem, the watcher is starting BEFORE the systems are loaded. This means if you hit take screenshot too quickly (as I did during debugging), you will get an exception on imagehandler.cs:131 ISystem cursys = _discoveryForm.TravelControl.GetCurrentSystem();

To fix:
imagehandler.cs:54 remove startwatcher at the end of InitControl
eddiscoveryform.cs:147 add imageHandler1.StartWatcher(); (just below Text +=)

Finally to fix the remove problem, in imagehandler.cs:

.. code
                    else
                    {
                        ED_PIC.Save(output_folder + "\\" + new_name + pic_ext, System.Drawing.Imaging.ImageFormat.Png);
                    }

                    ED_PIC.Dispose();   // need to release lock on files..
                    Screenshot_PIC.Dispose();

                    if (checkBoxRemove.Checked) // Remove original picture
                    {
                        File.Delete(e.FullPath);
                    }

                    Invoke((MethodInvoker)delegate { TravelHistoryControl.LogText("Converted " + e.Name + " to " + new_name + pic_ext + Environment.NewLine ); });
}
The last Invoke provides a handy confirmation that the image was converted... Not strictly necessary but useful.

Rob

**Comment by gregmalcolm** [comment]
Thanks for researching this! Any interest in putting in a Pull Request for this? It'll get your name on the contributors list... ;)

**Comment by robbyxp1** [comment]
i work, but the repository I'm working on has a bigger change to the route planner tab. Can I do a pull request just of one file?

**Comment by robbyxp1** [comment]
I would I mean ;-)

**Comment by robbyxp1** [comment]
Ignore the pull requests I created.. Its not working as I think it does.

**Comment by gregmalcolm** [comment]
Absoluetly! Tou can create pull requests with commits in them. The trick is to to push up different git branches. 

This sequence would  get you there:

Note: Commands given are to be run from git bash, assuming you are in the project folder. I'm also assuming you are working off your own github fork:

1) Check in your live changes. Run `git status` to make sure theres nothing left.
2) `git checkout -b saved-changes-branch` <-- Create a branch for your existing change. Takes you to that branch. Run `git branch` to confirm you're in that branch.
3) `git checkout master` (return to mat
4) Update your local master branch with any new changes: `git fetch origin`, `git rebase origin/master` and `git pull origin master`
5) `git checkout -b bitmap-convert-fix` <-- Start a new branch for your pull request
6) Transfer your bug fix to the code. Test and commit it. Push it up with `git push origin bitmap-convert-fix`
7) Make a pull request

Apologies if I've over explained it. Any questions let me know.

**Comment by robbyxp1** [comment]
You can't overexplain it.. i'm confused! I'll have a play and work it out

**Comment by iainross** [comment]
If you're totally lost then https://git-scm.com/book/en/v2 may help.

**Comment by gregmalcolm** [comment]
If you want clarification on what any of those steps are doing for you let
me know

**Comment by robbyxp1** [comment]
I'm starting from scratch and will just try and commit these changes..

**Comment by robbyxp1** [comment]
I've created a pull request.. lets see if that okay
