### ISSUE TITLE
Enhancement: Show estimate of exploration value in scan panel

### ISSUE THREAD

**Issue by radioactiv** [EDDiscovery/EDDiscovery#741]
I think it would be useful to be able to see the approximate value of scanning a body when hovering over them in the scan panel, especially for bodies that are populated from EDSM.  It would make it a lot easier to know if it's work the trip to scan that object, or to ignore it.  

The approximate values are on this steam page.  http://steamcommunity.com/sharedfiles/filedetails/?id=605162240

**Comment by iainross** [comment]
Those ranges'll get stuck in your head if you look at the table enough times...

I have been toying with the idea of digging out the more exact formulae that have been mostly worked out on the forums and implementing that in the scan details.  

However I won't be doing that before my return to the bubble in a few months where I can actually test it properly and I'm still slightly reticent about implying a commitment to put in the legwork to derive the new formulae if FDev decide to rework the payouts again...

**Comment by tonkepen100** [comment]
Yes sir. This would be sensational, but sensational, by God try to do, I repeat would be really good.

**Comment by robbyxp1** [comment]
This is very hard to do accurately and probably won't be right. Closing

**Comment by finwen** [comment]
It done need to be right  just a  good hint is fun.   

I want it to be dine for fun too and we will see if iainross or i makes it first :)

**Comment by RedfoxCh** [comment]
Nice work! This currently shows the scan value per scanned body (either by yourself or fetched from EDSM) exclusively on the scan panel - right? (I might have overlooked it elsewhere)

So, as for the inevitable follow-up question ;-)
- Can the values of self-scanned bodies be added and summed up in the Statistics window?
- In the Statistics window, can a default/average value be used for unscanned systems? Someone on the forums had posted a seemingly well based/established figure for what amount of CR can be expected on average from just ADS-honking. I'll try to find that figure if there's interest in this

**Comment by tonkepen100** [comment]
Spectacular, but ...

I think the good thing would be the following (if you can make this clear). I'm going to put an example, since my English is nefarious.

For example I want to go from exploration of Sun to Sagittarius A, well and p frame exit flag in Sun and I go route, the program is adding my scans made, the program in a box shows the value of the last scan and at the same time the Approximate sum of the exploration, that data could be put in a box for example here ....

![captura1](https://cloud.githubusercontent.com/assets/4571086/23397095/3e3b1f08-fd97-11e6-9283-61e2dd4a4301.PNG)


Or on routes and expeditions, for example here ...

![captura2](https://cloud.githubusercontent.com/assets/4571086/23397104/44ad1206-fd97-11e6-9826-f6a4194e4e5f.PNG)


In this way the pilot will always have knowledge of the total of his approximate exploration in a route.

Thank you for your attention.

**Comment by klightspeed** [comment]
EDDiscovery will only know about planets or stars you have actively scanned.  It cannot know how many bodies are in systems you have only honked.

Estimating the per-body scan value is the first step.  We could use the existing start/stop markers to delimit scan estimate ranges, and add all of the estimates from the selected system back to the nearest start marker.

**Comment by finwen** [comment]
Will start by adding it to stats panel....

2017-02-28 9:45 GMT+01:00 Ben Peddell <notifications@github.com>:

**Comment by tonkepen100** [comment]
If that would be sensational, the subject is to know approximately the sum total that a pilot has scanned in a route,

**Comment by finwen** [comment]
[image: Infogad bild 1]

Will be in 6.2.0

2017-02-28 11:07 GMT+01:00 Tonique <notifications@github.com>:

**Comment by finwen** [comment]
![image](https://cloud.githubusercontent.com/assets/9721644/23401433/f2bccb2e-fda7-11e6-8328-84553a880f19.png)

Added in stats panel on travel tab. 

Will be in 6.2

**Comment by RedfoxCh** [comment]
@finwen Will you be adding the "Scan value" to the scan tab as well? Seeing the values per body type might me interesting as well.

**Comment by tonkepen100** [comment]
> Added in stats panel on travel tab.
> 
> Will be in 6.2

Good good and good

**Comment by radioactiv** [comment]
FYI, they're changing the exploration values in 2.3.
https://forums.frontier.co.uk/showthread.php/332399-2-3-The-Commanders-Beta-Changelog

> Increased the credit values of exploration data for scans after this release. Unsold data from previous scans is unaffected by this change.

**Comment by radioactiv** [comment]
Some bodies don't seem to have an estimate, most of the planets with rings I've seen don't have a value, but rarely a non-ringged planet has no value.  Example system: Tjingola  First planet has value, 2nd (with rings) doesn't, 3rd (no rings) doesn't.

**Comment by callahan44** [comment]
Is it showing the correct 2.3 estimate values now?
~627,000 for an earth-like?
terraformable water-worlds, ~695,000

**Comment by finwen** [comment]
Think we solved it enough for this now.  will improve showing on  scan values in program with time.
