### ISSUE TITLE
Installation not successful

### ISSUE THREAD

**Issue by DeepstarOne** [EDDiscovery/EDDiscovery#745]
Hi,
after upgrading to v 5.2.9.0 and starting EDDiscovery I get the error message that the program is not working correctly and the following additional information. The error message is displayed on every start.
After downgrading ro v 5.2.8.0 EDDiscovery works normally again. I tried to download and upgrade sveral times, always with the same result. I'm using Win7 64bit Ultimate with all updates. Any hints what's the reason for this crash?
Thanks!
--------------- original error information (German) ---------------
Problemsignatur:
  Problemereignisname:	CLR20r3
  Problemsignatur 01:	EDDiscovery.exe
  Problemsignatur 02:	5.2.9.0
  Problemsignatur 03:	58808cb0
  Problemsignatur 04:	EDDiscovery
  Problemsignatur 05:	5.2.9.0
  Problemsignatur 06:	58808cb0
  Problemsignatur 07:	361
  Problemsignatur 08:	21
  Problemsignatur 09:	System.NullReferenceException
  Betriebsystemversion:	6.1.7601.2.1.0.256.1
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	1ded
  Zusatzinformation 2:	1deda76a4b134d8aa44a6f758b45cc8a
  Zusatzinformation 3:	94dc
  Zusatzinformation 4:	94dc656e798b0b2ef5dd289e39328972

--------------- translated error information (not necessarily perfect )---------------
problem signature:
  problem incident name:	CLR20r3
  problem signature 01:	EDDiscovery.exe
  problem signature 02:	5.2.9.0
  problem signature 03:	58808cb0
  problem signature 04:	EDDiscovery
  problem signature 05:	5.2.9.0
  problem signature 06:	58808cb0
  problem signature 07:	361
  problem signature 08:	21
  problem signature 09:	System.NullReferenceException
  operating system version:	6.1.7601.2.1.0.256.1
  locale ID:	1031
  additional information 1:	1ded
  additional information 2:	1deda76a4b134d8aa44a6f758b45cc8a
  additional information 3:	94dc
  additional information 4:	94dc656e798b0b2ef5dd289e39328972

**Comment by klightspeed** [comment]
If it's the same problem as in #739, it should be fixed in 5.2.10

**Comment by DeepstarOne** [comment]
Sorry, haven't seen #739 as it has been closed already.

**Comment by phroggster** [comment]
No need to apologize, in fact you have my apologies as my code caused this problem. 5.2.10 should be deploying in the next few hours, and should resolve this.

**Comment by phroggster** [comment]
5.2.10 is now available from the releases page [1]. Please let me know if this build resolves your issue.

[1]: https://github.com/EDDiscovery/EDDiscovery/releases

**Comment by DeepstarOne** [comment]
Hi,
Yes, everything is working fine now! Thanks for the fast bug-fix! :-)
