### ISSUE TITLE
Edit Theme: Cannot save, cannot close window

### ISSUE THREAD

**Issue by lausianne** [EDDiscovery/EDDiscovery#748]
Clicking on "Edit Theme", a window with theme settings opens. I see no button to save settings, or to close the window.

V5.2.10.0 on Windows 10

**Comment by phroggster** [comment]
This appears to also be related to locale. I'm installing the de_DE language pack now and will see what can be done, or if I just get confused looking at a debug-schnittstelle.

**Comment by phroggster** [comment]
Meanwhile, it appears that the OK button is selected when the window is displayed (even if it's not visible). This means that you should be able to simply press space to close the window.

**Comment by lausianne** [comment]
Indeed, pressing space closes the window.

**Comment by phroggster** [comment]
I'm having troubles reproducing this, despite significant attempts to completely render my computer unusable to me. Optionen > Umgebung > Internationale Einstellungen > Sprache is a live saver to a predominately-English Visual Studio user, by the way.

Can you advise if you've made any "unusual" changes to system settings like font sizes, default fonts, monitor scaling, and/or font remapping? I think that I've tried everything available, but I must be missing something.

**Comment by klightspeed** [comment]
For display scaling, one could try setting 125% display scaling then logging out and back in to apply to apps not aware of per-display scaling.

**Comment by finwen** [comment]
can you take a screenshot so we see how it looks?  might give some clues

**Comment by phroggster** [comment]
I was finally able to get it by remapping Microsoft Sans Serif to Trebuchet MS in the registry (HKLM\Software\Microsoft\Windows NT\CurrentVersion\Fonts). Here a [screenshot](https://cdn.discordapp.com/attachments/151322154133225472/273621463246831616/Untitled.png) of it afterwards.

Will spend some time to figure out the best path forward to handle this.

**Comment by klightspeed** [comment]
Trebuchet MS is apparently the default windows font for Windows XP, whereas Segoe UI is the default windows font for Vista onwards.

Have you upgraded from something like Windows 2000, through XP, through Windows 7 to Windows 10 without re-installing?  Or did you apply an XP theme to Windows 7 or Windows 10 at some point?

**Comment by phroggster** [comment]
To confirm, I'm not sure what font luasianne is using, but I was about to recreate his issue by remapping the font. I merely choose Trebuchet at random.

**Comment by klightspeed** [comment]
Everything is anchored to the top left.  The OK button should be anchored to the bottom right, and the groups should be anchored to both left and right.

**Comment by phroggster** [comment]
lausianne: You should see this resolved when the next update comes out.

klightspeed: I've pushed a commit to perform the minimum necessary to resolve this issue (both to master and the release 5.2 branch). I do agree that a redesign would be a good idea, but another day. Despite changing to a couple of outrageous fonts, I haven't seen the GroupBoxes extend beyond the form; just the button.

**Comment by lausianne** [comment]
Wow, you've been busy. fixing the close button is not the most urgent thing for me, but it seems to be related to the overall management of monitor resolutions. I haven't set up anything funky, never changed the font. But I do use two monitors of very different sizes and had to change some size and resolution settings for the larger monitor, which causes issues with many programs when displayed on the smaller monitor. Windows 10, upgraded from Win 7.
The little one is an old 19", something like 1280x1024 or less (can't check now). The other one is 34" 3440x1440. Obviously, the big one is my main monitor, fontsize and scaling set up for that one. On the 19" many things are now much too big. I keep EDDiscovery open on the 19", and it does not display very well - everything is too big, and the many areas are heavily cropped (worked a bit better with the older version of EDD). The Windows theme works best, but is also the ugliest ...
The close button does not appear on either of the screens. If it helps, I can send screenshots later today.

**Comment by klightspeed** [comment]
If you look at your primary display under Display Settings, it'll probably have a display scaling of something like 175% or 200%.  The display scaling on the primary monitor under Windows 8.1 and above sets the system DPI scaling for applications that are not per-monitor DPI aware.

If you've used compatibility options to disable display scaling on EDDiscovery, then Windows won't scale the window down on the secondary monitor.  Same if the second monitor for whatever reason is also set to have a high display scaling.

It is apparently not too hard System.Windows.Forms windows per-monitor DPI aware under Windows: <https://emoacht.wordpress.com/2013/10/30/per-monitor-dpi-aware-in-windows-forms/>

Basically, we would need to:
* Use an application manifest including the following under the `assembly` element:
```
  <asmv3:application xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
    <asmv3:windowsSettings
         xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>True</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>
```
* In the `WndProc` overridden method of each top-level window, we'd have to watch for the `WM_DPICHANGED` event and call a rescale function
* In the `OnLoad` overridden method of each top-level window, we'd have to get the DPI of the monitor on which most of the window is shown, and call the rescale function
* In the rescale function, rescale all of the controls and text as appropriate.

We could theoretically have a subclassed `CustomForm` that does all of the above, and from which all other forms (top-level windows) are subclassed.

**Comment by klightspeed** [comment]
💩 Some parts of the UI are rather badly behaved when trying to make the UI DPI aware.

**Comment by lausianne** [comment]
Thanks for your suggestions, klightspeed. I've redone all my screen settings. Scaling was 150% for the smaller monitor, 225% for the large one. Both are now 100% and only text objects scaled. Things are a bit small on the highres monitor, but not too bad. EDDiscovery looks fine now. Someday, I hope, M$ will fix this mess.
