### ISSUE TITLE
Enhancement: Better toggles in scan view

### ISSUE THREAD

**Issue by tivec** [EDDiscovery/EDDiscovery#753]
The buttons are incredibly hard to see if they are toggled or not. Maybe change the color to green when they are on?

In this image, the first button is not selected:
![Image of first button unselected](http://i.imgur.com/Z82CE8m.png)
In this image, the first button is selected:
![Image of first button selected](http://i.imgur.com/sTaGxNv.png)

There is a slight tint, but at a glance it is definitely not enough..

**Comment by finwen** [comment]
Thanks for the reminder.  We are aware of the problem and its on our TODO
list to improve.  Annoying many times to not see if its selected.

2017-01-26 9:14 GMT+01:00 Tivec <notifications@github.com>:

**Comment by tivec** [comment]
Good to hear! :) Want me to close this since it is on the todo? (is the todo visible?)

**Comment by finwen** [comment]
No we close it then we have improved the visibility

2017-01-26 9:18 GMT+01:00 Tivec <notifications@github.com>:

**Comment by robbyxp1** [comment]
Fixed in master.
