### ISSUE TITLE
Any way to prevent discoveries being posted to eddb until I return to sell my data ?

### ISSUE THREAD

**Issue by mpfj** [EDDiscovery/EDDiscovery#758]
Been using EDDiscovery for a couple of weeks now, but have only just realised (duh!!) that my discovery data is auto-uploaded to eddb.io.

As such, it's visible to anyone who cares to search for it ... and they could potentially zoom out to my ELW discoveries before I get back from my trip to Beagle Point and sell my data.

Is there any way / option / setting to limit what is uploaded ?

I like the journal logging and "Commanders Map", but not too keen on my first discoveries being tagged by someone else.

Or am I just being over paranoid ?

**Comment by klightspeed** [comment]
Try disabling the `Sync to EDDN` setting.

If you're out in the black, then all the `Sync to EDDN` setting does is enables syncing these bodies to EDDN (and by extension to EDDB and EDSM).  Systems will still be sent to EDSM, but bodies won't be sent until you explicitly use the "Sync unsynced bodies to EDDN" feature.

**Comment by mpfj** [comment]
Aha, simple when you know how !!

I guess I should RTFM :)
