### ISSUE TITLE
Vers. 5.3.1.0 Captures error

### ISSUE THREAD

**Issue by tonkepen100** [EDDiscovery/EDDiscovery#764]
Hello:

With this latest update, when capturing always misses an error, attached photo to be appreciated.

Thank you very much for your interest.

![error](https://cloud.githubusercontent.com/assets/4571086/22399750/744f2c34-e5a4-11e6-9929-02498d40dcb9.JPG)

**Comment by klightspeed** [comment]
Are any exceptions logged in the latest trace log (`%LOCALAPPDATA%\EDDiscovery\Logs\Trace_*.log`)?

**Comment by Gimi1967** [comment]
I get the same error. Trace log entry:

>

>  [2017-01-28 22:43:19Z] New entry 28.01.2017 21.43.22 Screenshot
> [2017-01-28 22:43:20Z] Exception watcher: A generic error occurred in GDI+.
> [2017-01-28 22:43:20Z] Trace:    at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
> 
> [2017-01-28 22:43:20Z]    at EDDiscovery2.ImageHandler.ImageHandler.Convert(String inputfile, String cur_sysname, Boolean removeinputfile, Boolean previewinputfile, JournalScreenshot ss, Int32 cmdrid) in V:\RobertW\EDDiscovery\EDDiscovery\ImageHandler.cs:line 361

**Comment by tonkepen100** [comment]
Here I leave them for you to review.

Thank you.

(Do not let me put a zip, nor a rar, I put it in my mega, for download)

link: https://mega.nz/#!dkwxgZQQ!HpNGra1k0ORQgt8lQGJN-_0PMZZWysY3Jr7gQVuzsy8
