### ISSUE TITLE
Unhandled exception EDD 5.3.1 When displaying EDSM "Scan" data.

### ISSUE THREAD

**Issue by Gimi1967** [EDDiscovery/EDDiscovery#769]
I get and unhandled exception when I try to display system scan data in the lower left panel or in any pop out panel.
Other panels work fine.

Edit: Turns out this was related to displaying scan data from EDSM.

![exception](https://cloud.githubusercontent.com/assets/1433251/22400246/9b198d54-e5af-11e6-83a1-3c61134e39b4.JPG)

![exception2](https://cloud.githubusercontent.com/assets/1433251/22400248/a2a68f40-e5af-11e6-9b7c-abfe923b9ff3.JPG)

![exception3](https://cloud.githubusercontent.com/assets/1433251/22400250/a87e9aa2-e5af-11e6-9c2f-fb765a23a181.JPG)

[Trace_20170128231231.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/737173/Trace_20170128231231.0.txt)

**Comment by klightspeed** [comment]
It sounds like you have the EDSM planet fetch enabled.  There is a typo in the timestamp formatting (https://github.com/EDDiscovery/EDDiscovery/blob/Branch_Release_5.3/EDDiscovery/EDSM/EDSMClass.cs#L679).  I am drafting a fix to this.

**Comment by Gimi1967** [comment]
Correct. Pushing "Show/Hide Body Data from EDSM" triggers the Exception on all panels. So the problem is related to that. Is that button/functionality dependant on "Sync from EDSM" by any chance, as I have that disabled.

**Comment by klightspeed** [comment]
If you can, would you please confirm that the build at https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.445/artifacts fixes the issue?

**Comment by Gimi1967** [comment]
That build does indeed fix the problem. At least anything I did to trigger it is fixed. Scan data from EDSM now displays and I can feely use the button to switch between local scan data and EDSM.

**Comment by klightspeed** [comment]
This fix should be in 5.3.3

**Comment by phroggster** [comment]
Gimi1967, can you confirm that [5.3.3](https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_5.3.3) has resolved this for you? It should be good, but just wanted to double-check before closing.

**Comment by Gimi1967** [comment]
I have been away travelling, so away from my gaming setup. I'll check this evening and report back.
Sorry for the delay.

**Comment by Gimi1967** [comment]
All good on my side. Thanks for the tremendous work you all do.

**Comment by phroggster** [comment]
And thank you for the report and follow-up. Fly safe commander. o7
