### ISSUE TITLE
Screenshot converter's Issue because ED_Pictures pattern was seeked while filename starts with Highres_Screenshot

### ISSUE THREAD

**Issue by Rogh64** [EDDiscovery/EDDiscovery#775]
Screenshot converter don't work because "ED_Pictures" pattern was seeked in filename (in ImageHandler.cs at line 201) while filename starts with HighResScreenShot_.

Maybe if the pattern becomes a parameter this would most simple for you.

Sorry for my bad english.

**Comment by klightspeed** [comment]
`GetScreenshotPath()` is only called when the screenshot path comes from a journal entry.

If you look at journal entries for in-game screenshots, you will find that the `Filename` property starts with `\ED_Pictures\Screenshot_` or `\ED_Pictures\HighResScreenShot_`.

```
{ "timestamp":"2017-01-28T23:15:32Z", "event":"Screenshot", "Filename":"\\ED_Pictures\\Screenshot_0340.bmp", "Width":1920, "Height":1080, "System":"HD 76133", "Body":"HD 76133 1" }
{ "timestamp":"2017-01-28T23:16:44Z", "event":"Screenshot", "Filename":"\\ED_Pictures\\HighResScreenShot_2017-01-28_23-16-44.bmp", "Width":7680, "Height":4320, "System":"HD 76133", "Body":"HD 76133 1" }
```

This `\ED_Pictures\` virtual path refers to the Elite Dangerous screenshots directory.

```
 Directory of D:\Users\klightspeed\Pictures\Frontier Developments\Elite Dangerous

29/01/2017  09:16 AM    <DIR>          .
29/01/2017  09:16 AM    <DIR>          ..
29/01/2017  09:16 AM    <DIR>          Converted
29/01/2017  09:16 AM        99,532,854 HighResScreenShot_2017-01-28_23-16-44.bmp
29/01/2017  09:15 AM         6,220,854 Screenshot_0340.bmp
```

**Comment by Rogh64** [comment]
My bad.
It's true.
Issue is elsewhere.

**Comment by klightspeed** [comment]
Are you using 5.3.2 or 5.3.3?

**Comment by Rogh64** [comment]
5.3.3

**Comment by Rogh64** [comment]
I try to reinstall Framework Dotnet redist.

**Comment by klightspeed** [comment]
Are you taking in-game screenshots using `F10` or `Alt-F10`?  Or are you taking screenshots using something else (e.g. Steam or GeForce Experience or Fraps)?

If using in-game screenshots, are there any `Screenshot` journal events?

If using external screenshots, are there any lines in the Trace log (in `%LOCALAPPDATA%\EDDiscovery\Logs\Trace_*.log`) logging the conversion of the screenshots?

**Comment by Rogh64** [comment]
I use in-game screenshot.
After dotnet redis re-installation it's work.
Sorry for the inconvenience.
