### ISSUE TITLE
Enhancement: Allow screenshot upload to imgur ?

### ISSUE THREAD

**Issue by mpfj** [EDDiscovery/EDDiscovery#782]
Any chance of adding a feature allowing screen-shots to be auto-uploaded to imgur ?

**Comment by finwen** [comment]
yes i have thought of adding that in the future.


2017-02-01 11:21 GMT+01:00 Mark Jackson <notifications@github.com>:

**Comment by klightspeed** [comment]
https://api.imgur.com/oauth2
https://api.imgur.com/endpoints/image#image-upload

Doesn't look too complex.  Standard OAuth2 auth flow, and simple POST to upload image, title and description in one request.

**Comment by phroggster** [comment]
Treat it like EDSM: force the end-user to generate their own API token, then copy it into EDDiscovery. Not sure whether imgur would like that model, though.

**Comment by klightspeed** [comment]
It'd be a bit more involved for the user than just copying an API key:
* Go to https://api.imgur.com/oauth2/addclient and register
* Copy and paste both the client_id and client_secret
* Click on an Authorize button, which would take the user to a browser window where they would authorize the application
* Copy and paste the resulting code (or if the application owns the window - e.g. if it uses System.Windows.Forms.WebBrowser - then the application can get the code from its Url)
* The application would exchange the code for an access token and a refresh token

**Comment by tivec** [comment]
If this is added, please make it possible to specify an album for upload. Also, the ability to turn it off and on easily. I tend to go on a screenshot spree every now and then :P

**Comment by klightspeed** [comment]
So the program would call https://api.imgur.com/3/account/me/albums (see http://api.imgur.com/endpoints/account#albums) to get all of the user's albums when a button is pressed, so they can be selected from a dropdown, then if an album is selected, add it in the `album` parameter of the image upload.

**Comment by Disorganise** [comment]
+1  been running EDD exclusively passed few weeks and miss the auto imgur upload of Captains Log 2

**Comment by robbyxp1** [comment]
Closing this. Had another look into it.  It needs a callback URL therefore server to authorize the upload to a users folder. We are not planning on providing a server to do this.  Also, applications have a limit on uploads, which can block the whole thing from a month.  This would cause mayhem.
