### ISSUE TITLE
Enhancement: Add ability to keep History grid locked to most recent item (line #1)

### ISSUE THREAD

**Issue by mpfj** [EDDiscovery/EDDiscovery#783]
It would be nice to be able to somehow keep the History log stuck showing the most recent journal entry.

**Comment by klightspeed** [comment]
Does the Settings -> `History cursor to new Journal Entry automatically` setting not do this for you?

**Comment by mpfj** [comment]
Aha ... so it does :)

**Comment by phroggster** [comment]
Mark: would "Auto-scroll to newest entry" or "Auto-scroll journal to newest entry" or any other variation make the option clearer? I've been trying to figure out how to rephrase it for simplicity, and your help would be appreciated.

**Comment by mpfj** [comment]
Yes ... although I hadn't actually looked at the Settings page at all.

I king of assumed that if the scrollbar had been moved to the highest position (against the "up" arrow), then it would auto-stick.

AFAIK that's how other (Microsoft?) scrollbars work ... they stick to the top/bottom if you've scrolled to the top/bottom.

**Comment by phroggster** [comment]
Thanks for the feedback. Will got something figured out for a future update.
