### ISSUE TITLE
ListControlCustom Naughty List

### ISSUE THREAD

**Issue by phroggster** [EDDiscovery/EDDiscovery#799]
[Debug image](https://cdn.discordapp.com/attachments/151322154133225472/277157123123707905/OnPaint_fail_with_multiple_combobox_clicks.png)

ListControlCustom OnPaint() ArgumentOutOfRangeException

Set theme to anything with gradient buttons (such as orange delight), find an empty combobox control (such as SavedRouteExpeditionControl after you've deleted all your routes), and click the combobox twice.

I'll get to this one eventually if no one else does before me.

**Comment by phroggster** [comment]
While there, it also appears that semi-transparent themes (Verdana Grey, Blue Wonder at least) don't invalidate the combo box text after an item is removed (and text reverts to string.empty), at least until a mouseover or other invalidation event. Opaque themes are not impacted.

**Comment by robbyxp1** [comment]
Also there is a bug with the combo box in theme mode - ie. ours.  clicks seem to leak thru to the window below.  Example is the actions form, if you make it so its pops up (by moving the window bottom right at the bottom of the screen) then use the program combo box, if you click on a program it sometimes leaks the click so you end up with both the program opening AND another dialog from the parameter setting opening.

**Comment by robbyxp1** [comment]
The leak thru bug has been fixed on the latest master.
