### ISSUE TITLE
Enhancement:  Separate scan text to a separate window

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#800]
I was wondering if it would be possible to split off the 'Scan Display' in the S-panel to a separate window?  Reason being, when the test shows, the entire S-Panel expands - this can cause issues with the mouse jumping 'out' of the game and into the S-panel instead.
I generally have the S-panel as a 2 line strip across the top and would like the scan display bit to be a small rectangle over on the right where my mouse is unlikely to go.

**Comment by iainross** [comment]
You can open more than one.  Turn the scan info off in the one you currently use and open another one.  Add the scan info but no history and put it where you want it.  That will save as 'SPanel2' and should reappear with those settings when you open a second one.

**Comment by Disorganise** [comment]
ahh...you're right :)  hadn't worked that out...thanks

**Comment by iainross** [comment]
np
