### ISSUE TITLE
Enhancement:  Add system security info - ideally to S-panel

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#801]
Can the system security info be added to main window - maybe below 'home'?
http://i.imgur.com/fNJBPis.png

Ideally, the Allegiance, Economy, security etc could be placed in another overlay screen.  the security status would ideally be colour coded text (eg, red bold for anarchy, red for low, green for high).   This info is useful when trying to find thinks like USS's that produce chemical manipulators, but also recently on a livestream it was suggested there's populations we have not found - a handy indicator of security would be a prompt to investigate further

**Comment by robbyxp1** [comment]
Agree, good idea.  We can add it as optional info to s-panel

**Comment by jthorpe4** [comment]
I was thinking of adding this info to the next time I update the trip panel, as I'm engineering at the moment and would find this information useful too, but if the s-panel is a better location I'm cool with that.

**Comment by robbyxp1** [comment]
For 8.3
