### ISSUE TITLE
Graphical visualisation of scanned systems sometimes not displayed correctly

### ISSUE THREAD

**Issue by DeepstarOne** [EDDiscovery/EDDiscovery#802]
Hi,
sometimes the graphical visualisation of scanned systems is not displayed correctly.
Example:
System in Frontier:
![system_launa_ed_frontier](https://cloud.githubusercontent.com/assets/25210660/22625458/e8acac0c-eb97-11e6-9045-d9622870da1b.jpg)
System visualisation by EDDiscovery:
![system_launa_eddiscovery](https://cloud.githubusercontent.com/assets/25210660/22625478/66d383a8-eb98-11e6-835b-d8f09362a6df.jpg)

**Comment by klightspeed** [comment]
We really need some sort of list mapping custom-named bodies to their generated names.

Looks like Star A is "Lauma" and not "Lauma A" as the program was expecting, and Star B is "Gl 836.9 B".  Meanwhile all of the other bodies in the system used "Lauma A" and "Lauma B".

**Comment by DeepstarOne** [comment]
Indeed, in ED the first star is named "Lauma" and the second one "Gl 836.9 B"

**Comment by robbyxp1** [comment]
This has already been noted.  If you turn on EDSM systems, then turn it off, it does not draw properly. I know why, and will fix it as soon as possible.  Leave it to me.

**Comment by klightspeed** [comment]
There are about 500 custom-named bodies in the EDDB data.  We could have a json in EDDiscovery-Data which maps those custom names to the generated names.  That file would be read either during init or on the first scan panel refresh.

**Comment by klightspeed** [comment]
This should be fixed in 6.2 (PR #868).
