### ISSUE TITLE
Font issue is back in 5.3.4 ...

### ISSUE THREAD

**Issue by mp1963** [EDDiscovery/EDDiscovery#807]
The font problem is back ....
![capture](https://cloud.githubusercontent.com/assets/24973059/22663415/69e34936-eca4-11e6-8eb6-b62c5d3c8815.JPG)

**Comment by phroggster** [comment]
Did you make any DPI settings since #675? Did 5.3.1-5.3.3 work appropriately? What about reverting back to 5.3.3; does that version still work?

**Comment by mp1963** [comment]
No DPI changes made. 5.3.2 worked fine. 

Marek

**Comment by klightspeed** [comment]
The fix in #687 was probably a bit fragile (it depended on the UI caching the DPI scaling before `OpenTK.Toolkit.Init()` enabled DPI scaling).

We could try cherry-picking the commit from #772 into 5.3.x and see if that fixes the issue - that fix should be more robust.

**Comment by klightspeed** [comment]
Does 6.0.1 beta fix the issue?

**Comment by mp1963** [comment]
Will download it and try it this morning. Watch this space.

**Comment by mp1963** [comment]
6.0.1 Beta works just fine thank you :-)

**Comment by phroggster** [comment]
@mp1963 Please check out the freshly released (5.3.5)[https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_5.3.5] which should resolve this issue. I will go ahead and close this, but please reopen it if you see it again in 5.3.5.
