### ISSUE TITLE
6.0.0 Issues

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#809]
1) Just noticed that screenshot seems do not properly be managed. Sometime, EDDiscovery do not remove the original screenshot - even if requested to do so - and many screenshots are missed, the app do not seems to catch them all. 
2) Also, 3d Map is very, very slow... I feel the needs for a smaller filtered 3d map - as already requested - with a limited rendered range (user selected: 50ly - 1000ly). My computer is not on the low down (32Gb RAM) and, yet, when opened, the 3d map hugely impact the game FPS.

**Comment by phroggster** [comment]
Issue 1) This should have been resolved in the [6.0.1 beta](https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_6.0.1Beta) release (from commit cf6fbd2d62c0a1f9fa5be6b43b99f28c0c17545e onwards). Please try updating to see if it is still occuring.

Issue 2) I'll mark it as an enhancement request, but I'm not sure what all can be done to improve system utilization.

**Comment by phroggster** [comment]
It seems like #812 may just solve your second issue. Give it a few days before it gets tested and into a release, but that should make a huge improvement from the looks of things.

**Comment by andreaspada** [comment]
Thanks, guys! Indeed, the 6.0.1 patch solved the screenshot's issue. I'll wait some days for the next patch - to the galmap - be applied. KUDOS!

**Comment by klightspeed** [comment]
With point 2, it appears that the StarGrids are still being updated, and still sending the points to GPU memory, even when show all stars is disabled.

**Comment by robbyxp1** [comment]
The 3dmaps need rewriting for shaders.  I see little point in messing about with the current implementation when we can shove most of the work to the GPU.  The stars are purposely calculated during stars off so they will switch on instantanly.

So closing this, until we rewrite the 3dmaps, we need to just leave it mostly alone.

first is solved.
