### ISSUE TITLE
Feature Request: CMDR log note!

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#813]
Sorry, I already asked for this a couple of times, but I really feel the needs for this. Could we have a simple cmdr log with multiple entry for each system? Like the currently available note field, but with multiple entries. So, if I want to write something specially related to the system I am, it do not clutter the note field (which is something related to EDSM, and more exploration oriented, like to note anything special on the system map or alike...).

A really simple dated log could help a lot! To record bounties, fines, local factions reputation, etc...

Please!!!! ;)

**Comment by klightspeed** [comment]
Perhaps it would create e.g. a custom "EDDCommanderNote" journal entry in the database, which would be created or edited using a popout?

**Comment by andreaspada** [comment]
Seems great!

**Comment by andreaspada** [comment]
My previously request: #578

**Comment by robbyxp1** [comment]
#1014
