### ISSUE TITLE
Enhancement:  Auto-hide overlay windows

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#814]
Could you please add the option for the overlay windows (S-panel, trip) to only show whilst the game is running?   Rightly or wrongly, I tend to leave EDD running all the time and the overlays can get in the way - since EDD knows when the game starts and presumably can check if the exe is still running, it should be possible to auto show and hide the overlay windows

**Comment by robbyxp1** [comment]
We are now not monitoring ED state, if its running, as we no longer need this. So this idea is not going to be implemented.
