### ISSUE TITLE
UI Frequently freezes

### ISSUE THREAD

**Issue by inktomi** [EDDiscovery/EDDiscovery#822]
Version 6.0.3.0
Windows 10 64bit

I frequently have the entire UI of EDDiscovery frozen. It seems like whenever it's processing something or doing network calls it freezes up, as if this stuff is done on the main UI thread. Is there any way this can be offloaded so that it does not impact the UI?

I'm happy to create dumps or anything you'd like while it's frozen.

**Comment by robbyxp1** [comment]
Can you tell from the log window what it is doing when it freezes.

Do you have the voice pack installed, thats new and may be a factor?

**Comment by inktomi** [comment]
I'll recreate it and see from the log. I'm a new user and didn't know it
kept one.

When it's frozen I cannot switch tabs.

I am using the voice pack.
