### ISSUE TITLE
TravelHistoryControl shows distance to Sol instead of distance to Home

### ISSUE THREAD

**Issue by Big-Gaz** [EDDiscovery/EDDiscovery#823]
I've changed the Home System on the 3D Map, which has worked for the Home button on the 3D Map but doesn't seem to translate back to the Top Right View of the History Page, which remains as Sol. I also can't find any other setting to change the Home System in the Top Right View of the History Page.

Am I missing something?

**Comment by phroggster** [comment]
You should be able to merely type in that Home System field on the History page. This should also update the map view.

That said, will need to research why the map doesn't update the History field.

**Comment by Big-Gaz** [comment]
I think I must be missing something, then, as I can't see a Home System field on the History page - please see screenshot.

![eddhistorypage](https://cloud.githubusercontent.com/assets/24977745/22865158/0f375d18-f156-11e6-9209-e2b11e3ee48d.png)

**Comment by phroggster** [comment]
337.99 is apparently your home system. Odd place to live, methinks.

**Comment by Big-Gaz** [comment]
It's the distance from Sol to PLEIADES SECTOR HR-W D1-57, which was my location at the time. I've now jumped to PLEIADES SECTOR XF-N B7-2 and the home system field now shows 314.05, which again is the distance to Sol. I can left-click and highlight the field, but typing doesn't do anything, and right-clicking gives me a context menu where the only highlighted options are "Copy",  "Right to left Reading order", "Show Unicode control characters" and "Insert Unicode control character" with a sub-menu. There's no option to edit it.

**Comment by phroggster** [comment]
I think I misunderstood the issue, and misunderstood the nature of the field, but I've got a better grasp now and can confirm what you're stating. The field only shows distance to Sol, and there's presently nothing that can be done to influence that.

Dev's, here's the [source line](https://github.com/EDDiscovery/EDDiscovery/blob/eb2684f288776364d107b000569c499285ef3509/EDDiscovery/TravelHistoryControl.cs#L459) responsible for it if I don't get to it first.

**Comment by Big-Gaz** [comment]
Phew! I thought I was either being completely stupid or going completely mad for a second there!!

Thank you.

**Comment by robbyxp1** [comment]
There are reasons why its Sol.  The home system only applies to the 3dmap.  Now i've looked into doing something different before, but never actioned it.

Its not really a bug.
