### ISSUE TITLE
No longer auto refreshes

### ISSUE THREAD

**Issue by Finlas** [EDDiscovery/EDDiscovery#829]
Hi, Ever since updating to latest EDD the program no longer keeps track of my trip automatically. I have to go to the force reload via "read 2.1 and former logs" menu option. Without this forced reload the program does not keep up to date.

It also does not any longer sync my flight logs to EDSM. Last log for my cmdr on EDSM is from 19th January 2017

Program version 5.2.9.0 and below ( basically all versions since since January 19)

**Comment by phroggster** [comment]
An issue was identified recently where EDD would cease reading logs if an error was encountered, and I randomly suspect that this is what is causing your issues. Unfortunately, the fix has not made it into any 5.x series release yet, but the 6.0.3 beta does include a fix.

As such, I'd suggest either of the following, depending on your comfort level:

- Attach here the most recent log file from `%LOCALAPPDATA%\EDDiscovery\Trace\` to aid in troubleshooting.
- Update to version 6.0.3 and report whether the problem is still evident

**Comment by Finlas** [comment]
Hey thanks for the update. Will update to latest and let you know if it
happens again

**Comment by robbyxp1** [comment]
Closed old issue.

**Comment by Finlas** [comment]
Please re open issue. Continues to happen in EDDiscovery 6.1.2.0

Attached zip contains:

Elite Dangerous app.config
Elite Dangerous net log
EDDiscovery logs
EDDiscovery logs after forced reload of log files ( which adds the current system )

Please let me know if you need any further files for review 
[ED Discovery- force Reload Issue.zip](https://github.com/EDDiscovery/EDDiscovery/files/825671/ED.Discovery-.force.Reload.Issue.zip)

**Comment by klightspeed** [comment]
```
[2017-03-07 19:34:32Z] Change in file, scan C:\Users\admin\Saved Games\Frontier Developments\Elite Dangerous\Journal.170307193430.01.log
[2017-03-07 19:34:32Z] New entry 07/03/2017 19:34:30 Fileheader
[2017-03-07 19:36:38Z] TLU C:\Users\admin\Saved Games\Frontier Developments\Elite Dangerous updated with commander 2
[2017-03-07 19:36:38Z] New entry 07/03/2017 19:36:37 LoadGame
[2017-03-07 19:36:38Z] New entry 07/03/2017 19:36:37 Rank
[2017-03-07 19:36:38Z] New entry 07/03/2017 19:36:37 Progress
[2017-03-07 19:37:06Z] New entry 07/03/2017 19:37:05 Location
[2017-03-07 19:57:26Z] New entry 07/03/2017 19:57:26 FSDJump
[2017-03-07 19:58:31Z] New entry 07/03/2017 19:58:29 FuelScoop
```
So it sees the journal, and reads a few events

```
[2017-03-07 20:03:01Z] Unknown event: StartJump
```
And you're playing the beta.  Which means the events should appear under your `[BETA]` commander

```
{19:36:39} System:"Hegua WI-K d8-1" StarPos:(-2779.906,133.594,-2889.219)ly Body:0 RelPos:(-5.27896e+07,-4.70533e+06,-1.37867e+08)km NormalFlight
```
This matches the `LoadGame` event

```
{19:37:06} System:"Hegua WI-K d8-1" StarPos:(-2779.906,133.594,-2889.219)ly Body:0 RelPos:(-5.27896e+07,-4.70533e+06,-1.37867e+08)km NormalFlight
```
This matches the load-up `Location` event

```
{19:56:59} System:"Hegua WI-K d8-1" StarPos:(-2779.906,133.594,-2889.219)ly Body:0 RelPos:(-5.27896e+07,-4.70533e+06,-1.37867e+08)km NormalFlight
```
I'm guessing this is getting ready for a jump

```
{19:57:15} System:"Hegua MP-M b35-0" StarPos:(-2740.219,138.719,-2864.406)ly Body:0 RelPos:(1.45055e+06,-1.04157e+07,1.16835e+07)km Supercruise
```
This matches the hyperspace transition before the `FSDJump` event.

**Comment by Finlas** [comment]
Perhaps it is because of the fact that it thinks it is "Commander 2" ?

I only have main elite account, so perhaps my "commander 1" is actually the beta product instead?

Do you want me to try getting logs when beta is running ?

Or perhaps I re install both ED and ED Beta ( don't really want to do that ) ?

**Comment by klightspeed** [comment]
If you played the 2.2 beta, and did not have EDDiscovery installed before the 2.2 beta, then it's likely that the first journal entries it saw were from the 2.2 beta, and so that would have been the first commander it saw.

Does the first listed commander have a `[BETA]` prefix?
