### ISSUE TITLE
How do I "ignore" the pictures directory setting that's stored in the user db ?

### ISSUE THREAD

**Issue by mpfj** [EDDiscovery/EDDiscovery#835]
I share my UserDB across two PCs (via DropBox), but I can see from the code that textBoxScreenshotsDir is populated by the db "ImageHandlerScreenshotsDir" value, with a fallback to the default Windows MyPictures folder.

But once the db has been populated, it *always* uses the db value, even if the folder doesn't exist.  My two PCs have two different login names, so the db pictures folder isn't common between the PCs.

One fix is to check if the the db folder exists, and fallback to the default MyPictures if it doesn't.

Would that be an acceptable solution ?  If so, I'll code something up.

**Comment by klightspeed** [comment]
Perhaps we should look at separating the settings from the travel history etc.

**Comment by klightspeed** [comment]
A workaround might be to create a junction point or a directory symlink pointing to your user's pictures directory, and set that junction point as your pictures directory.

e.g.:
```
mklink /j C:\ElitePictures "%USERPROFILE%\Pictures\Frontier Developments\Elite Dangerous"
```

**Comment by robbyxp1** [comment]
A check of the existance of the folder, and a fall back to a windows standard folder would be easy..

**Comment by klightspeed** [comment]
I added some commits to phroggster's [master-configchanged-events](https://github.com/phroggster/EDDiscovery/tree/master-configchanged-events) branch which separates the paths out of the database and into userpaths.json (for global paths) and commanderpaths.json (for netlog / journal path overrides).

**Comment by robbyxp1** [comment]
For now, placed a check in there for existance of output and screenshots dir, and a fall back if not there

**Comment by klightspeed** [comment]
The fallback should be in 6.1; the user paths in json files looks like it'll be in 6.2

**Comment by mpfj** [comment]
6.1 seems to work fine.  Cheers.
