### ISSUE TITLE
Bad trilaterate suggestions when travel history is empty by filter.

### ISSUE THREAD

**Issue by muthan** [EDDiscovery/EDDiscovery#84]
As I understand you determine the the suggestions for trilateration based on the last travel history entry before the new one. When it's empty the you get 6 standard suggestion from within and near the bubble.
But this happens also when the history empty by the "show history for last" filter. (with empty i mean ther is only the data from the first jump of the day)

To clarification this is what I have done:

I am roughly ~7kly away from sol.
I jumped to a new system.
This was the only entry of the day 
there are many others but not shown because the filter was set to last 6 hours and it was the first jump of the day.
Now I tried to trilat the system but I only got the standard ones like sol, maia, ... 

when I set the filter to another setting like last 20 it works normal as before.

**Comment by gregmalcolm** [comment]
Just for added clarity: I would  assume only fully trilaterated systems count as visited points in this scenario. As otherwise there is no way to know your coordinates.

I'm sure you get that, but in theory you could travel 7k from Sol without trilaterating or encountering a trilaterated point and then find all the suggestions are Sol orientated quite legitimately.

I doubt it's that scenario, but just wanted to rule it out.

**Comment by muthan** [comment]
Shure. The last visited system that is not in the filtered list is one that has indeed coordinates (since I always trilaterate the system I am in. It's part of the fun for me). 

So when I conclude correctly this should happen with every scenarion in which the last system with known coordinates is not in the filtered travel history.

**Comment by iainross** [comment]
I'll take a look at this one at the weekend as well

**Comment by iainross** [comment]
If you change the filter to show the last known system and then change it back to your preferred filter it will remember the last known system's location - it's currently only assigning the system data to the history list when it adds to the travel history - but it doesn't take it away when you re-apply the filter and remove it from the grid again.

I'm testing a fix but that workaround might be of help until the next release.
