### ISSUE TITLE
Feature Request/Enhancement: Mixer setting for TTS

### ISSUE THREAD

**Issue by CRCError1970** [EDDiscovery/EDDiscovery#842]
I have multiple sound output devices on my rig and it would be very helpful to me if I could select a sound output device for the TTS feedback. Right now it seems to go the the primary output device by default with no way of changing it.

**Comment by robbyxp1** [comment]
Good idea... have to investiage how to enumerate them

**Comment by CRCError1970** [comment]
I would certain appreciate it. I have a set of Astro A40's and the MixAmp lets me mix two sources separately . Makes it easy to isolate Discord chat from game audio.

**Comment by robbyxp1** [comment]
Will be implemented in 6.1
