### ISSUE TITLE
Upload shipdata to edsm

### ISSUE THREAD

**Issue by Antigotchie** [EDDiscovery/EDDiscovery#848]
It would be nice if EDDiscovery would the Shipdata to EDSM correctly - like ED Market Connector do

**Comment by robbyxp1** [comment]
This is in progress, we are aiming for this in the next month or so.

**Comment by finwen** [comment]
We already does some limited updates now but full function will arrive with EDDiscovery 7.0 and Companion API functions.

**Comment by Antigotchie** [comment]
Great thanks a lot

**Comment by robbyxp1** [comment]
Being done
