### ISSUE TITLE
Feature Request: per-CMDR screenshot folder

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#849]
Just opened my second account a week ago, and noticed that I would find very interesting and useful if I could split the CMDRS screenshots in different folders (or with CMDR name attached). Could it be made?

**Comment by robbyxp1** [comment]
Yes, i've added CMDRName and CMDRName SysName to folder options, should be in 6.1

**Comment by andreaspada** [comment]
Awesome!!! KUDOS!!!!!

**Comment by RedfoxCh** [comment]
Very cool feature!
