### ISSUE TITLE
Feature Request: Keep-on-top

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#85]
Add an option to keep the EDDiscovery Window on top (or suggest a utility which can be used to do so).

I've tried several utilities, but they stuff up Alt-Tabbing between ED and EDD.

**Comment by muthan** [comment]
this would really help to enter distances if you only have one monitor

**Comment by gregmalcolm** [comment]
I think that could be really handy when you're trilaterating

**Comment by muthan** [comment]
i think this one can be closed since this feature is already in the release ;)
