### ISSUE TITLE
Feature request: Route optimiser for multiple waypoints

### ISSUE THREAD

**Issue by vatekaru** [EDDiscovery/EDDiscovery#859]
Problem: You have 20ish systems to visit that are spread out in the galaxy (or even in the bubble). What is the most efficient route to visit all in no particular order but with shortest amount of travel time. 

I've used the EDDs route by importing all the systems I want to visit. Then used the 3D map of the route and manually adjust the order into an approximation of the effective route. Problem with this is that the 3D map is a bit clumsy and I would imagine adding an automated optimisation to the route tab should be possible.

**Comment by klightspeed** [comment]
So a travelling salesman with 20! possible paths, but somehow trying to evaluate as few paths as possible out of those 20! paths.

**Comment by robbyxp1** [comment]
I'm going to retire this. This is not in our scope at this point.
