### ISSUE TITLE
Feature Request: Fast-travel mode - focus "Distance to Next System" when Windows becomes active

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#86]
During Fast-travel where a long route is entered I only enter the distance to the next system (and trilaterate every 10th system or so).

So, jump into system, honk, turn to next system, start up FSD, throttle-full, check galaxy-map for distance to next system (2 decimals), alt-tab to EDDiscovery, use mouse to select "Distance to next System", enter data, alt-tab back to ED.

It would be nice to be able to switch the App into a "Fast Travel" mode, in which the App focuses on the "Distance to Next System" input field when the window becomes activate. That way I wouldn't have to use the mouse during jumping.

Even better: have a hotkey which pops up a small "Distance to Next System" dialog. No need to alt-tab etc.

**Comment by Red13x3** [comment]
Yup, I suggested this exact same thing a long while back. Like I think it's request #15 or so. Not had any feedback or progress on it. 

But I'll add a +1 to this, as it supports mine. ;)

--
Red_XIII
