### ISSUE TITLE
Feedback/Suggestions regarding Statistics

### ISSUE THREAD

**Issue by RedfoxCh** [EDDiscovery/EDDiscovery#867]
The information within the "Statistics" window are really great and fun to browse through!

Nonetheless, here's some feedback/suggestions on some small stuff ;-)
- Tab "General": Table shouldn't be sortable
- Tab "General": Add thousands separator for number-fields
- Tab "General": Any reason why the "Time" control is not available on this tab?
- **Fixed** Tab "Travel" and "Scan": Number fields sort as string, not as numbers
- **Fixed** Tab "Travel" and "Scan": Right-align number-fields
- Tab "Travel" and "Scan": Remove decimals on number-fields
- Tab "Travel" and "Scan": Add thousands separator for number-fields
- Tab "Travel" and "Scan": Consider adding more "Time" options (e.g. user-defined time-frame, popular expeditions)
- Tab "Travel" and "Scan": Sometimes it's visually difficult to see wich key (left-most) align exactly with which value (far right). Any chance to highlight the entire row (e.g. when clicking into it)?
- Tab "Scan": First column content should be taken from Phroggie's text substitution pattern (instead of using string from Journal). Maybe add subtype (e.g. "DAB") to distinguish the different row per subtype
- **Fixed** Tab "Scan": First column header "Last" should be named sth like "Body Type"  
- Tab "Scan": Add option to display all Body Types in addition to the ones that aleady have >0 scans. Seeing what types have *not yet* been scanned is interesting, too, and is good material for new exploration goals
- Tab "Scan": Consider removing the "0" in order to make it better visible where there are values the where there are gaps

**Comment by finwen** [comment]
Thanks for your feedback.  Some of your wishes will be granted

**Comment by finwen** [comment]
Tab "General": Any reason why the "Time" control is not available on this tab?

Would be time constraints on availible time developing the stats panel :)
