### ISSUE TITLE
Feature Suggestion: Integration with INARA

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#874]
Just knew that it was released a tool that allow for integration with INARA from the log files. Maybe, the coders could be interested in integrate it with EDDiscovery...
https://github.com/jtickle/Picard

**Comment by robbyxp1** [comment]
We are not addressing this at this time. We have enough on our plate at the moment. Closing as it's not a bug

**Comment by finwen** [comment]
I will probably do this later in the future. looks like a easy  thing to add  sometime later

**Comment by AnthorNet** [comment]
Not sure it is worth the time to implement something not relying on an API.

**Comment by finwen** [comment]
We will see.  Might do it  and will keep this until decided.

2017-03-07 8:56 GMT+01:00 AnthorNet <notifications@github.com>:

**Comment by finwen** [comment]
Inara is working on a API.  We will wait for it before doing any work.

**Comment by robbyxp1** [comment]
Still no API.  No indication of timing. Closing and will reopen if it ever appears

**Comment by pioto** [comment]
Looks like there's an API now? https://inara.cz/inara-api/

**Comment by klightspeed** [comment]
Docs: https://inara.cz/inara-api-docs/

It looks like INARA only uses data available in the journal - e.g. no ship modules or module engineering.
