### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by t-konran** [EDDiscovery/EDDiscovery#875]
I have this alert since two days (when I start EDD) :
https://puu.sh/uqV4J/9c90251a15.png

On the last version 6.1.10. Desinstall and re-install but nothing better.

I don't know what to do... can you help me ?

**Comment by finwen** [comment]
Something wrong in parsing of journal files it looks like. 

Go to Users/Saved  Games/Frontier Developments   directory.
pack the whole directory and send it to robert.l.wahlstrom@gmail.com and then i will solve it quickly,

**Comment by klightspeed** [comment]
Null reference exception in the JournalScan constructor when processing bodies from EDSM.

**Comment by t-konran** [comment]
It's weird... this morning, there's no alert anymore. And the history is update.

Yesterday, I have empty the EDD log's directory, I don't know if there is a link...

I'm waiting if it's stable but thanks to you for the responses !

**Comment by finwen** [comment]
It is from data from EDSM's homepage.  The data isnt complete fpr spme
systems (in your case and did leade to an exception for us).  NExt version
will be more tollerant to EDSM data no fully filled in the case you had.

2017-03-03 9:28 GMT+01:00 t-konran <notifications@github.com>:

**Comment by t-konran** [comment]
OK I understand ! Thank you very much, guys, and very nice work by the way... this EDD is awesome !

**Comment by t-konran** [comment]
Just for information : the same alert again this evening... and I am docked in LHS 3447 system.
