### ISSUE TITLE
Unhandled Exception 6.1.1.0

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#878]
Upgraded this morning to 6.1.0 and noticed it was not updating.  Alt tabbed out and found an exception I didn;t note but looks the same as this one.  Killed task.  Opened and found notification to 6.1.1 so downloaded and installed that.  Similar issue.  Left it and went to work.

Now I start 6.1.1 and get the exception:
[img]http://i.imgur.com/Npka7uf.png[/img]

Log attached:  (by the way, dot logs are not allowed to be uploaded, I had to rename to dot txt - perhaps change your extension to dot txt so it's a straight drag n drop)
[Trace_20170303185346.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/816142/Trace_20170303185346.0.txt)

Additional notes;
EDD runs on 2nd monitor and I have 3 overlays on the main

**Comment by Disorganise** [comment]
After hitting retry then closing down gracefully and re-opening, the exception now changes to
[img]http://i.imgur.com/k0iFM5k.png[/img]

I noticed also the 2nd s-panel has not appeared.  [Game is not running at the moment either btw]
[Trace_20170303190724.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/816157/Trace_20170303190724.0.txt)

**Comment by Disorganise** [comment]
After hitting ignore on the previous error, EDD seems to continue to run, but there are graphical issues:
[img]http://i.imgur.com/4kHhYzg.png[/img]
[img]http://i.imgur.com/ahsjmi0.png[/img]

**Comment by klightspeed** [comment]
@finwen are the builds still including the PDB file?  The lack of line numbers suggests that either the PDB isn't included in the installer, or the PDB doesn't match the EXE.

The error suggests that something is wrong with the history entry icon.

**Comment by klightspeed** [comment]
Looks like some of the cells and all of the images are not being drawn in the history list.

**Comment by Disorganise** [comment]
I restarted it again and it looked fine.
So started up the game (normal, not beta) and then realised the updates weren't coming through.  Alt tabbing revealed another exception.  This time I hit abort and it popped up another exception momentarily before disappearing.  Got the log though
[Trace_20170303192329.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/816187/Trace_20170303192329.0.txt)

I *think* it is probably the 2nd spanel - maybe it was too near the border of the other monitor or something.  Is there a simple way to reset the panels?  [I have it set to save and load on start up....if I untick load will that make it only start the main window?]

**Comment by Disorganise** [comment]
so I went ahead and did that;  started EDD, hit ignore to exception, went to settings and unticked load on startup.  closed EDD and relaunched.  It opened with main windows only.  I made a jump and it registered and voicepack kicked in telling me fuel etc.  so it seems to be working now.  I have not tried recreating the overlay panels yet.

**Comment by finwen** [comment]
Looks like some elemts in a panel got to small.  Will fix the exception in next release
