### ISSUE TITLE
Different home systems for different commanders

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#882]
Hi! Just playing with an additional CMDR by a couple of weeks, and I noticed that I cannot specify different home system for each CMDR. I thought that will be much better to have an individual home for each CMDR.

**Comment by finwen** [comment]
Companion API is just for test now.  Will take some time before its ready
for release...  Now its just a login test  and in debugger i can test my
parsing of the data :)

2017-03-04 15:10 GMT+01:00 Andrea Spada <notifications@github.com>:

**Comment by finwen** [comment]
Removed  from text...    already solved and another ongoing thing

Also, I just installed the last master branch, with the addition of the CompanionAPI and I do not understand how will it work with multiple CMDR...

I'm enjoying a lot the new addition for include the CMDR name in the screenshot conversion tool, and I would like to know if is it possible to split it in another subfolder: "CMDR name subfolder" / "System name subfolder".

**Comment by robbyxp1** [comment]
We need to redesign the commander data entry anyway.. roll into that

**Comment by andreaspada** [comment]
Cool! It could be interesting to think in have multiple Companion API account, also... for who have multiple simultaneous accounts. Does it seems possible?

**Comment by finwen** [comment]
Yes

Den 30 mars 2017 00:34 skrev "Andrea Spada" <notifications@github.com>:
