### ISSUE TITLE
3dMap enhancement - option to disable rendering of far-away stars

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#883]
Would be nice to specify up to how far away from your current position / the camera stars can be rendered in the 3d Map.  Auto-disable this feature when zooming out.

Use-Case: With the amount of stars now in EDD, it is difficult to see the stars in your neighbourhood.

**Comment by mwerle** [comment]
Actually nvm, it appears the current build (6.1.2) already does this if you toggle "show all stars" to off. (Last time I tried that it only showed my own stars).

**Comment by klightspeed** [comment]
I think what you're seeing is the discs from `Show Discs` - I think those ignore the `Show all stars` setting.
