### ISSUE TITLE
Network Unhandled Exception Error

### ISSUE THREAD

**Issue by St3vet** [EDDiscovery/EDDiscovery#885]
EDDiscovery crashed on my laptop when my game PC was rebooted.

Apparently this reporting system does not support .log type.  I have renames the file with .txt.
[Trace_20170304155440.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/818756/Trace_20170304155440.0.txt)

**Comment by klightspeed** [comment]
So I guess we have to treat the file disappearing as if we just hit an EOF.

**Comment by klightspeed** [comment]
This should be fixed in #888

**Comment by finwen** [comment]
Solved in 6.1.3

**Comment by St3vet** [comment]
Thank you.  You guys are great.
