### ISSUE TITLE
EDDiscovery threw up error, told to log it here

### ISSUE THREAD

**Issue by The-Grim-Beaker** [EDDiscovery/EDDiscovery#892]
As I was arriving at a planetary landing pad in Elite Dangerous the EDDiscovery threw a wobbler and crashed, leaving a prompt to log it here. Got a secondary dialog error upon restarting the app. Not sure what any of it means but hey ho.
I'm running ver 6.1.2.0.
I've attached screenshots of the error text and the requested files;

[Trace_20170305201545.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/819822/Trace_20170305201545.0.txt)
[Trace_20170305223530.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/819823/Trace_20170305223530.0.txt)
![edd error text 1](https://cloud.githubusercontent.com/assets/26208397/23592274/37c35fec-01f6-11e7-9455-a5660d00b4ee.PNG)
![edd error text 2](https://cloud.githubusercontent.com/assets/26208397/23592275/37c7741a-01f6-11e7-9db7-dda63832c73c.PNG)

I'm guessing this all will mean something to someone

**Comment by klightspeed** [comment]
The cause of the first exception is probably the same as the cause of the second exception - the first exception doesn't seem to have printed the inner exception.

The exception occurring in GetPlanetClassImage() suggests that PlanetClass is null.
