### ISSUE TITLE
Cannot add scan to system

### ISSUE THREAD

**Issue by mpfj** [EDDiscovery/EDDiscovery#902]
Cannot add scan to system - alert the EDDiscovery developers using either discord or Github (see help)
Scan object Iorant PD-K d8-4 A in Macedonica's Leap

Journal entry #2
```
31.83 ly Fuel 4.2t
StarPos(-923.6, -8.3, 65005.2), System Allegiance:, System Economy:None, System Government:None, 
System Security:Low Security, Fuel Level Left 20.0t
Travelling distance 31568.7 LY, 1037 jumps, time 2.02:19:20
```

Journal entry #1
```
Scan Iorant PD-K d8-4 A, 0.0 ls from arrival point, G type star, 1.0 stellar masses, 
719590.3 km radius, 4.7 absolute magnitude, Age_MY:6406, Surface Temperature:5863.0K, 
Semi Major Axis:26976630865.9km, Eccentricity:0.141361, Orbital Inclination:45.110149, 
Periapsis:252.209442, 4690010.3 days orbit, 3.2 days rotation
Travelling
```

**Comment by klightspeed** [comment]
Looks like EDSM renamed `Iorant PD-K d8-4` to `Macedonica's Leap` because it was renamed in the 2.3 Beta.

Sounds like we need to have a curated list of systems that have been renamed, so old scans can be assigned to renamed systems.

**Comment by robbyxp1** [comment]
Code added on master. Declared fixed
