### ISSUE TITLE
Feature Request: Add Synthesis Shopping List

### ISSUE THREAD

**Issue by RedfoxCh** [EDDiscovery/EDDiscovery#906]
Currently, a spreadsheet is needed to calculate how many of which material are needed for a desired amount of synthesis charges, e.g. 20x Basic FSD, 20x Standard FSD, 20x Standard FSD, 10x Standard SRV Repair, etc.

This then needs to be compared with the naterials currently in the inventory to finally come up with the 'Shopping List', i.e. how many of which material needs to be collected. Then, while collecting materials, the new inventory values need to be updated. All-in-all a not very exciting activity ;-)

With the data available (material changes, material per synthesis) and a manually entered baseline of the inventory such a shopping list could be automatically maintained within a pop-out.

Combined with #702 and #873 EDD could then produce a TTS-notification, telling the player that he a) is in a system that has >=x of the needed materials or b) has just scanned a body that has >=y of the needed materials. That would be awesome :-)

**Comment by robbyxp1** [comment]
7.0 has this
