### ISSUE TITLE
Crash on entering system

### ISSUE THREAD

**Issue by vaegue** [EDDiscovery/EDDiscovery#909]
I believe the crash happened on entering a system. I didn't notice the crash till quite a while after it happened. I was unable to force it to happen again, but it has happened a few times in the last few days.
[Trace_20170314114348.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/843225/Trace_20170314114348.0.txt)

**Comment by klightspeed** [comment]
This should be fixed in 6.1.3 when it comes out (fixed in 1778a3e).
