### ISSUE TITLE
Trilateration tests

### ISSUE THREAD

**Issue by gregmalcolm** [EDDiscovery/EDDiscovery#91]
I'm a relatively new contributor to EDD so I don't know the full history, so apologies if I'm asking questions that have already been dealt with but I was wondering if we have any formal testing for checking EDD trilateration against EDDB/EDSMs?

I was thinking it might be worth writing some unit tests at some point to confirm our behavour is at least in sync with EDDBs for establishing when trilateration is complete. It would be useful in that vein to write tests where we know what the expectations are from EDDB's point of view to try to figure out why we get variations on "trilateration readiness".

@AnthorNet: Do you mind if I ask if there's any testing data that could help with this?

/cc @finwen

**Comment by AnthorNet** [comment]
Such as ?
Sorry not sure I understood what you want :)

**Comment by finwen** [comment]
In the beginning EDDiscovery used EDSC and i converted Redwizzards trilatation routine from js to C# and optimized it.

RedWizard and EDSC's algorithm was similar so we used to get solve on the same result mostly. 
EDSM has a different algorithm ao sometimes EDD solves before and sometimes we need more distances. 

I see the built in trilatation more like a preview.
If we implement the algorithm from EDSM (if allowed)  in the future then users would be less confused by solution of different number of distances.

**Comment by finwen** [comment]
But it should not be hard to make a unittest.  just add some stars with distances and check if the result is correct.

**Comment by AnthorNet** [comment]
I can clean up our algorithm, but the main difference is situated where EDD accept coordinates as exact when the best has two more valid distances than the previous. That case we do not accept.

I was thinking about saving the alternative and flag them to be recalculated because they are generally close to the final solution.

**Comment by gregmalcolm** [comment]
Yeah, my questions are pretty much what Finwen described. I'm interested in trynig to figure out if we're doing testing expected vs actual results in known trilaterations as automated tests. And also syncing up our algorithms so we get to the same result at about the same time.

One thing that might be causing problems, if a user enteres a bad distance and submits, then corrects it, adds more distances and submits again, does the bad entry mess up the ability to finish the job? I'm envisioning a scenario where the bad distance is stored and never corrected, just marked as suspect.

**Comment by gregmalcolm** [comment]
BTW for those watching, I'm not assigning myself to the task writing unit tests just yet so if anyone wants to "steal" this task, go for it.

**Comment by gregmalcolm** [comment]
Trilateration calculations between EDSM and EDD seem to be way more consistent now. I'm just going to go ahead and close this. We can always reopen if the need arises.

**Comment by AnthorNet** [comment]
Is something was changed?

**Comment by gregmalcolm** [comment]
Heh, I kinda thought something may have changed on the EDSM side because of late I've not been seeing many false positives when sending the trilaterated data to EDSM. Maybe it's still bad on the outer rim. We should still write those unit tests I suggested but I honestly don't see anyone getting around to it for a while.

**Comment by AnthorNet** [comment]
We clean the database a lot, that might be that ;)
Also we put online a bot scanner to check the systems in the background.

**Comment by gregmalcolm** [comment]
Well I think that might have done it, so thanks! :)
