### ISSUE TITLE
Synchronize with http://inara.cz

### ISSUE THREAD

**Issue by grozeille** [EDDiscovery/EDDiscovery#916]
I use http://inara.cz 
It's quite complete: information about yourself, about your ships, you can import flight logs and screenshots.

It would be nice to update the information about the commander & ships on this website, and import flight logs automatically.
It would be nicer to be able to select screenshots to import (I have to convert them into jpg to import them manually)

**Comment by andreaspada** [comment]
Already submitted. #874

**Comment by robbyxp1** [comment]
Frontier API sync and to EDMC is coming.  We already export and import from EDSM.  I

**Comment by robbyxp1** [comment]
when we can get to this is indeterminate

**Comment by robbyxp1** [comment]
CLosing, 874
