### ISSUE TITLE
Waypoint planning for 1k ly hops

### ISSUE THREAD

**Issue by Gerdofal** [EDDiscovery/EDDiscovery#92]
I'd love to see the capability for EDD to display suggested waypoints when we're on a very long trip.

Given:
- Current system and destination system

Return:
- Waypoints <1000 ly apart that can be put into the galactic map as a route toward the destination

**Comment by gregmalcolm** [comment]
Oh, so if you wanted to do a Buckyball Run from sol to Sag A it could plot a series of places to set in the nav computer?

Had to think a bit on the intent, but now the penny has dropped that does sound useful. Though for some less travelled routes it may come back empty for some waypoints.

**Comment by Gerdofal** [comment]
Yes, you have the idea. Ideally, it could calculate those waypoints for any start and finish calculation. 

Basic Steps

1 - Find coordinates of start location
2 - Find coordinates of end location
3 - Plot a straight line from start to end location. Calculate a point on that line about 950 ly away.
4 - Perform a search of stars near this point and pick one as the waypoint. Make sure it's within 1000ly of start. Fail and exit search if nearest known star is too far off course.

Repeat steps 1-4 with the waypoint as the new start.

This kind of calculation would get much more reliable as we fill in more of the map, but for common routes it should work right now.

**Comment by Gerdofal** [comment]
I was poking around the edsm api.  They have a way to query for systems in a sphere. Would make this type of routine very easy

http://www.edsm.net/api-v1/sphere-systems

**Comment by finwen** [comment]
could get a spere easy from EDDiscovery local data too. I can make a such
function if you want

2016-01-30 9:37 GMT+01:00 Gerdofal <notifications@github.com>:

**Comment by Gerdofal** [comment]
I think it would be useful. I actually made a quick and dirty web based version here as a test of theory: http://gerdofal.net/ed/1krouting.php

Unfortunately, I can't make it work right now because of memory limitations. I'm having trouble getting the EDSM data into the local database, not enough memory to parse the JSON, so routes that go too far will time out because I have to make multiple queries against EDSM. Still seeking a workaround for that one.

Test data that does work:

Start: Sol
End: Prieluia SD-B b14-5

**Comment by Gerdofal** [comment]
Ok, fixed. Data loaded to local db and working now:

http://gerdofal.net/ed/1krouting.php

**Comment by robbyxp1** [comment]
I'm coding a way-point generator which will give intermediate galaxy co-ords between either systems, or x/y/z co-ords, now..  I may include the nearest star to each waypoint.

**Comment by robbyxp1** [comment]
Update on this.

I've recoded the GUI portion to allow for entry of either stars or gal co-ords, and made the dialogs interactive to verify data before allowing routing.

Then improved the routing code.  

But there is a problem - even with the enhancement I made to limit the number of stars to a bounding box, the routing code just dies a death due to out of memory or slowness if you try and route very large distances (say 900ly).  Thats because it creates so many arcs that the alogrithm just collapses.

I'm investigating using a different algorithm for routing, one which will cope with long distances,and cope if there is no star in the database on the path (it will output the gal-coords instead for you to pan the map to and pick a random star).

Will keep you up to date..

**Comment by Gerdofal** [comment]
The way I did it for my website was using vectors and then the distance formula around the waypoint to find stars. That way you don't actually need to worry about stars along the route, just pick the coordinates of the waypoint and then do your search for stars near that point. Let the in-game map worry about your route.

I'm not sure what your back-end data structure is like for your stars and coordinates. I'm using SQL queries and they aren't having any trouble returning results. It's really just a few square root computations.

My current planning task for my website is improving my "best waypoint system" algorithm so that it returns systems that will route quickly on the in-game map when near the core. (ref https://forums.frontier.co.uk/showthread.php?t=151389 )

**Comment by robbyxp1** [comment]
I've done something very similar.  Push it next week.
    
    On 19/02/2016 08:45, Gerdofal wrote:
    
    
      The way I did it for my website was using vectors and then the
        distance formula around the waypoint to find stars. That way you
        don't actually need to worry about stars along the route, just
        pick the coordinates of the waypoint and then do your search for
        stars near that point. Let the in-game map worry about your
        route.
      I'm not sure what your back-end data structure is like for your
        stars and coordinates. I'm using SQL queries and they aren't
        having any trouble returning results. It's really just a few
        square root computations.
      My current planning task for my website is improving my "best
        waypoint system" algorithm so that it returns systems that will
        route quickly on the in-game map when near the core. (ref https://forums.frontier.co.uk/showthread.php?t=151389
        )
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by robbyxp1** [comment]
So,to update, I have it working, but looking to improve the metric for selecting the best star. That needs some 3D vector point from a line stuff which I'm trying to remember from university. 

Will probably include a check box to allow you to select from Miniminum distance from Waypoint or minimum deviation from path (both may not be the same). Minimum deviation from path would mean more waypoints generated, but would keep you in a straight line.

That means calculating the distance of a point from a 3D vector! Hence I need to remember and do some research.  

Will commit something on monday, but may come back and improve the alogrithm later if I can't get it working in time.

**Comment by Gerdofal** [comment]
I spent some time working on vectoring and distances and angles from vectors when I made my original functions, but finally decided that keeping close to the vector wasn't what really mattered when evaluating a waypoint. What really mattered was what I called "efficiency". Or, for every ly you travel, how much closer do you actually get to your final destination. 1:1 would then be perfect. (Expressed as 100%).

So I just look at one waypoint at a time and use a "move" formula to calculate the coordinates of the next waypoint.

function g_move($ax,$ay,$az,$bx,$by,$bz,$dmove)
{
	//a is our current waypoint
	//b is the final destination of the route
	$dactual = g_3d_dist($ax,$ay,$az,$bx,$by,$bz);
	if ($dactual>$dmove)
	{
		//If we have more to go to wp
		//Move dmove from point a toward point b
		$dx=$ax+(($dmove/$dactual)*($bx-$ax));
		$dy=$ay+(($dmove/$dactual)*($by-$ay));
		$dz=$az+(($dmove/$dactual)*($bz-$az));
		return array($dx,$dy,$dz);
	} else {
		//If we are in range of end, just go there
		return array ($bx,$by,$bz);
	}
}

I avoid the memory errors you referred to above by selecting stars for each waypoint and clearing that array once we're done with that waypoint. I found it impossible to to load all the stars in the bounding box for the whole route.

My basic SQL query is below. The "prior" coordinate is the last waypoint. The x, y, z are the current waypoint.

SELECT
			name,x,y,z
	FROM
			ed_stars
	WHERE
		SQRT(
			   pow(`x`-" . $priorx . ",2)+
			   pow(`y`-" . $priory . ",2)+
			   pow(`z`-" . $priorz . ",2)
			    ) < " . $maxdist . "
		AND
			SQRT(
			   pow(`x`-" . $x . ",2)+
			   pow(`y`-" . $y . ",2)+
			   pow(`z`-" . $z . ",2)
			    ) < " . $maxoffset . "

**Comment by Gerdofal** [comment]
Of course, the ideal solution is to check all stars in a cylinder defined by the start and end points and a radius. Unfortunately, I haven't yet been able to turn that into an algorithm that I can give a SQL query. Still working on that one.

**Comment by robbyxp1** [comment]
I will commit before wedneday stage 1

This will use a new waypoint calculator, and I'll include an option on which metric to use. This can either be 1) closes to, 2) Minimum deviation from path, 3) combination of above (Waypointdist+Deviation, or waypointdist+2*deviation - make is more important not to deviate from path and accepting closer stars).

But with the minimum deviation calc, Later I can use the AStar algorithm and only add stars to be considered that is within X lys of the path.  That should reduce the number of stars and maybe allow that mechanism to work.  That needs experimentation.

**Comment by Red13x3** [comment]
I'm not sure if this data is held in the EDDB (or whatever global DB it is we use - it gets so confusing!) but is the star class held in the DB?

The reason I ask is that if I'm on a long trip out to the black, I tend to jump only to G and K class worlds as that gives the best results in terms of finding habitable worlds.

Could this new feature be able to filter to desired star classes?


Red_13

--
Mark
iPhone: 0402 322 901

**Comment by finwen** [comment]
No class is not stored yet.  But it will be soon......

2016-02-21 23:16 GMT+01:00 Mark <notifications@github.com>:

> I'm not sure if this data is held in the EDDB (or whatever global DB it is
> we use - it gets so confusing!) but is the star class held in the DB?
>
> The reason I ask is that if I'm on a long trip out to the black, I tend to
> jump only to G and K class worlds as that gives the best results in terms
> of finding habitable worlds.
>
> Could this new feature be able to filter to desired star classes?
>
>
> Red_13
>
> --
> Mark
> iPhone: 0402 322 901
>
>

**Comment by robbyxp1** [comment]
Pull request #125 addresses this mostly.

Not the final answer, I want to work on the AStar one more using the deviation from the path calculation to add only stars along a path for consideration.

**Comment by robbyxp1** [comment]
Route finder gives either stars or waypoints if none are close.  It works over great distances. Addressed and closed.
