### ISSUE TITLE
File not found exception

### ISSUE THREAD

**Issue by dernil** [EDDiscovery/EDDiscovery#928]
I am not able to start EDDiscovery in Windows 10.
This is what I get from event viewer:

System.IO.FileNotFoundException
in EDDiscovery.EDDiscoveryController.InitializeConfig(Boolean)
in EDDiscovery.EDDiscoveryController.Initialize(Boolean)
in EDDiscovery.Forms.SplashForm..ctor()
in EDDiscovery.Program.Main()

Thank you for your attention

**Comment by klightspeed** [comment]
Is this 6.1.3 or 6.2 beta?

**Comment by dernil** [comment]
It's 6.1.3
I start it from the windows ' start menu so I don't  use options

**Comment by dernil** [comment]
It's a Steam installation

**Comment by dernil** [comment]
If I launch EDDiscovery.exe -Readjournal from prompt nothing happens

**Comment by klightspeed** [comment]
The stack trace you have given seems incomplete.  There are no calls within `InitializeConfig` that would directly throw a file not found exception.

Does `%LOCALAPPDATA%\EDDiscovery` exist?

Was this a new install, or did you upgrade from a previous version of EDDiscovery?

**Comment by dernil** [comment]
Yes, it exists, and this is a new install.

**Comment by klightspeed** [comment]
If you open `%ProgramFiles(x86)%\EDDiscovery\EDDiscovery`, is there an `options.txt` file?  If so, try removing it and trying again.

**Comment by dernil** [comment]
No, there isn't an options.txt file.

**Comment by robbyxp1** [comment]
Closed, no further reports from user
