### ISSUE TITLE
Sort by distance in Trilateration

### ISSUE THREAD

**Issue by ZexMaxwell001** [EDDiscovery/EDDiscovery#930]
I don't think sort by distance is meant to be this way :/
![image](https://cloud.githubusercontent.com/assets/1289187/24438725/ffb02330-140e-11e7-91be-8470815ef6cd.png)

**Comment by klightspeed** [comment]
I don't think the column sort for the trilateration table is overridden, so it is sorting distances lexicographically.

**Comment by ZexMaxwell001** [comment]
It would be cool if we can sort by distance. that way once we enter in the current distance batch, we can go the nearest system and upload by visiting.
