### ISSUE TITLE
Feature Request: Screenshot conversion - add optional crop/resize

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#94]
It would be nice to be able to specify a screenshot cropping and/or resizing when converting screenshots.

For example, my game window is 4800x1200 (because, reasons). I'd like to crop it to 2134x1200 starting at 1333x0. This would crop screenshots to roughly 16:9, centered on my game view. Anything beyond that tends to be so badly distorted as to be useless for a screenshot anyway.

Yes, there are existing tools which can automatically do this. But if it's relatively easy to do, it'd be a nice additional feature for an all-in-one solution.

**Comment by robbyxp1** [comment]
See issue #115 which fixes some issues with the code.

**Comment by robbyxp1** [comment]
Closed
