### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by Insinnergy** [EDDiscovery/EDDiscovery#945]
Open App. Click on Panel Select Dropdown. Choose top option: S-Panel.
Summary panel opens, but throws an Unhandled UI exception.
Attached: Screenshot of Error and Requested Log file.
[Trace_20170406232556.0.log.txt](https://github.com/EDDiscovery/EDDiscovery/files/902390/Trace_20170406232556.0.log.txt)
![error1](https://cloud.githubusercontent.com/assets/26964009/24752454/fe540a14-1b21-11e7-8388-05d66ee191a5.jpg)

**Comment by klightspeed** [comment]
What is the version you are running?

**Comment by Insinnergy** [comment]
My version is 6.1.3 I'll fire you a screenshot. 
Let me know if I can provide you with any further information also. 
(Props for this program by the way... it's fantastic. Thanks for all the work put in).
![error2larger](https://cloud.githubusercontent.com/assets/26964009/24776116/a424d7a6-1b73-11e7-966e-64aae9a18f14.jpg)

**Comment by robbyxp1** [comment]
Unfortunately not been able to reproduce.. appears the Icon has zero width, but tested all the journal entries and they come back with a icon.  Can't see a vector for it to say get_width not valid - yet!

**Comment by robbyxp1** [comment]
Hit wrong button, still current

**Comment by robbyxp1** [comment]
Think its solved in 7.0.1

**Comment by robbyxp1** [comment]
Going to assumbe its solved, please re-report if you see it in 7.0.1 on

**Comment by Insinnergy** [comment]
Confirmed fixed in 7.0.1.
Many thanks. :)
