### ISSUE TITLE
Error Displaying planets when they have two word names

### ISSUE THREAD

**Issue by Insinnergy** [EDDiscovery/EDDiscovery#946]
Just flew through Gateway system and spotted what seems to be an odd bug. Had a quick hunt for any previous log for this, or any comments and haven't found anything so thought I'd add it here for your consideration. (Love your program by the way!)

Planetary Names that have two words such as "Graham's Claim" and "Saunder's Rock" display a "fake" or null planet in the main page titled with the first word of the planet's name... then a second planet with the correct information and image underneath that titled with the second word of the planet's name.

It appears to be splitting multi-word planet names into multiple planets on the space in the name. It's particularly noticeable in Gateway since nearly every planet has a double barreled name.

Please delete if you're already aware of this, or it's a setup issue on my end.
Screenshot attached: I've circled the odd planets in Red.
![odd system information](https://cloud.githubusercontent.com/assets/26964009/24752838/bdd26754-1b23-11e7-991b-679cbb27f3f1.jpg)

**Comment by klightspeed** [comment]
This should be fixed in 6.2.x

**Comment by Insinnergy** [comment]
Superb. Many Thanks. :)
