### ISSUE TITLE
End crew session is an unknown event 

### ISSUE THREAD

**Issue by willyb321** [EDDiscovery/EDDiscovery#955]
http://i.imgur.com/ak3NFGe.png  an example on EDD
`{ "timestamp":"2017-04-12T11:32:30Z", "event":"EndCrewSession", "OnCrime":false }` and the journal event

**Comment by finwen** [comment]
Yes that was a late add to journal  (last beta i guess)  Will add it to EDD soon.

**Comment by finwen** [comment]
Should be solved in 7.0.1
