### ISSUE TITLE
Screenshot folder location not saved. EDD 7.0.0 Portable

### ISSUE THREAD

**Issue by Gimi1967** [EDDiscovery/EDDiscovery#956]
EDD reports "_Folder specified for image conversion does not exist, check settings in the Screenshots tab_"
upon launch.
After I enter settings and specify screenshot folder location and folder for storing converted screenshots, everything works for the current session.
When I lunch EDD the next time, the folder locations for both Picture folder and folder for storing converted pictures are reset back to default.  C:\User\......etc

(I run EDD on a separate computer, and access the Screenshots over the network through mapped network folders. Converted pictures are stored in a separate location on the computer running EDD.)

Issue not seen in previous versions of EDD.

Running EDD 7.0.0 Portable
OS: Windows 10 on both computers.

**Comment by Gimi1967** [comment]
Additional Information.
It seems that EDD does not find the path to the specidied folders on start.
The folders are as follows:
Screenshots: _Q:\Frontier Developments\Elite Dangerous_ (Mapped network folder)
Store converted screenshots: _D:\Elite Dangerous\Screenshot_ (Local D-drive)

Tracelog, just in case
[Trace_20170412182452.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/917231/Trace_20170412182452.0.txt)

**Comment by 67MistakeNot** [comment]
I have a very similar problem, version 7.0.0, installed rather than portable. 

Alternative destination for _Store Converted Pictures_ to a different volume not saving after application closed and re-opened.

Screenshots: C:\Users\XXXX\Pictures\Frontier Developments\Elite Dangerous
Destination:  D:\My Documents\Pictures\Elite Dangerous

I don't get an error message, it just doesn't work. Has worked OK with previous versions

**Comment by klightspeed** [comment]
Please test if the build at https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.936/artifacts fixes the issue.

**Comment by 67MistakeNot** [comment]
No, I'm afraid not, issue the same as before.

**Comment by Gimi1967** [comment]
I'm getting the same result with the test build. EDD is not finding the specified folders on start-up, and reverting to default folders. 
Tracelog shows the same result as above.

**Comment by klightspeed** [comment]
Please try the build at https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.937/artifacts

**Comment by Gimi1967** [comment]
Yes, that last test build did the trick here. Thank you.

**Comment by 67MistakeNot** [comment]
Working for me too now, thank-you!
