### ISSUE TITLE
EDDiscovery ver 7.0 crashing elite and dangerous 

### ISSUE THREAD

**Issue by felipecrica** [EDDiscovery/EDDiscovery#959]
Before the update of 7.0 version everything was working fine and with 7.0 it makes the game come to a  complete  standstill it just locks up the game and computer up is there a way of installing the older ver before 7.0?

**Comment by robbyxp1** [comment]
Please provide more details on how it is locking up the whole computer.

Yes you can use a previous version, but it won't know about any 2.3 features

**Comment by VonDugard** [comment]
Unable to Sync with EDSM, has been working to till last update I keep getting ( date is not in the format yyyy-mm-dd hh:mm:ss )

**Comment by felipecrica** [comment]
Hi thank you for getting to me well eddiscovery when i run it alone it takes up about 4,350 mb and it starts to slow down the computer can't even move the mouse to click on elite and if already running elite it be working fine but once i start eddiscovery it all comes to a standstill. I didn't have that problem with the other version before 7.0.  I also used an unstaller program to wipe the program and the Windows registry setting and did a clean installation and still having the problem

Is there a way to restall the older version of eddiscovery? I really like the program

Felipe


On Apr 13, 2017, at 12:42 AM, robbyxp1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Please provide more details on how it is locking up the whole computer.

Yes you can use a previous version, but it won't know about any 2.3 features

**Comment by felipecrica** [comment]
Kinda sounds what is happening with me too i lift it on all night and still it was taking so much ram out of my computer 4,350 mb or more and if i startup elite the computer comes to a crawl

Felipe


On Apr 13, 2017, at 4:48 AM, VonDugard <notifications@github.com<mailto:notifications@github.com>> wrote:


Unable to Sync with EDSM, has been working to till last update I keep getting ( date is not in the format yyyy-mm-dd hh:mm:ss )

**Comment by klightspeed** [comment]
When it is taking 4GB of RAM, do you have the 3D map open?

**Comment by felipecrica** [comment]
No nothing is open but the Journal

Sent from my iPhone

On Apr 13, 2017, at 1:27 PM, Ben Peddell <notifications@github.com<mailto:notifications@github.com>> wrote:


When it is taking 4GB of RAM, do you have the 3D map open?

**Comment by klightspeed** [comment]
When you say it's taking 4350MB, is this from Task Manager, or is it from the disk usage in `%LOCALAPPDATA%\EDDiscovery`?

After a sync, the `%LOCALAPPDATA%\EDDiscovery` directory is about 3GB in size, with 99% of that taken by EDSM data.

Without the 3D map having been opened, I got a peak working set size of 548MB, and a peak private bytes size (what task manager shows) of 416MB.  After completing the EDSM sync, this fell to about 270MB.
![image](https://cloud.githubusercontent.com/assets/147116/25024986/a7febf8e-20e3-11e7-8577-6936971bf172.png)

This is with about 15k entries in my travel history.

Once the 3D map was opened, the peak memory usage increased to 1.5GB.
![image](https://cloud.githubusercontent.com/assets/147116/25025455/b2f44b96-20e5-11e7-930e-15653d3e5a14.png)

If you click S-Panel and click Statistics, how many jumps does it say you have made?

![image](https://cloud.githubusercontent.com/assets/147116/25025719/acffe956-20e6-11e7-9505-543ce06e3e21.png)

If you go to `%USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous`, and get the folder properties, how many MB do all the files in it take up?

![image](https://cloud.githubusercontent.com/assets/147116/25025747/c5b2ba78-20e6-11e7-9d0b-8d6116210b44.png)

**Comment by robbyxp1** [comment]
Closed, no response from user..
