### ISSUE TITLE
Unknown event "system shutdown"

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDDiscovery/EDDiscovery#960]
I received a note in my journal that I should notify the ED Discovery Team about an unknown event "Systems Shutdown".  This was in 7.0.0, I just updated to 7.0.1, and I am getting the same message.

Context from the journal:

{ "timestamp":"2017-04-12T19:58:24Z", "event":"StartJump", "JumpType":"Hyperspace", "StarSystem":"HIP 17999", "StarClass":"A" }
{ "timestamp":"2017-04-12T19:58:44Z", "event":"FSDJump", "StarSystem":"HIP 18154", "StarPos":[-64.188,-118.531,-292.438], "SystemAllegiance":"", "SystemEconomy":"$economy_None;", "SystemEconomy_Localised":"None", "SystemGovernment":"$government_None;", "SystemGovernment_Localised":"None", "SystemSecurity":"$SYSTEM_SECURITY_low;", "SystemSecurity_Localised":"Low Security", "JumpDist":8.180, "FuelUsed":0.296603, "FuelLevel":31.703398 }
{ "timestamp":"2017-04-12T19:58:59Z", "event":"SystemsShutdown" }

This is the unknown event reported, the journal continues with:

{ "timestamp":"2017-04-12T20:00:25Z", "event":"MaterialCollected", "Category":"Encoded", "Name":"unknownshipsignature", "Count":3 }
{ "timestamp":"2017-04-12T20:01:04Z", "event":"MaterialCollected", "Category":"Encoded", "Name":"unknownwakedata", "Count":3 }

As you can probably guess, this was created when I was pulled over by the Pleiades Flower Power Patrol, so it might be somewhat difficult to reproduce...

**Comment by klightspeed** [comment]
I noticed this in someone else's trace log as well.  Seems like an undocumented journal event (it isn't documented in http://hosting.zaonce.net/community/journal/v10/Journal_Manual_v10.pdf)
