### ISSUE TITLE
Fuel Scoop data

### ISSUE THREAD

**Issue by HIghwaywarrior** [EDDiscovery/EDDiscovery#961]
Every time I use the fuel scoop, the data is recorded as 2 events not one and rather than state the full amount scooped I get 2 amounts which added together equals the total amount of fuel that I actually scooped.
![scoop](https://cloud.githubusercontent.com/assets/27449274/25023629/7b8a17a6-2092-11e7-8b62-e1ea7ff4ebc4.PNG)

Thanks

HW

**Comment by klightspeed** [comment]
It looks like the Fuel Scooping in Elite Dangerous was updated in 2.3 to log an event every 5t and when the fuel scooping reaches zero (e.g. when leaving the corona, when the tank is full, or when the fuel scoop is disabled).

In 2.2, it wouldn't log an event until several seconds after leaving the corona.

**Comment by robbyxp1** [comment]
So, its working as per 2.3, unless we want to start mergining events I suggest its left as it is.

**Comment by Taomyn** [comment]
Whereas I agree it's not an EDD issue per-se and actually an improvement, when you have a 128T fuel tank refilling at over 800/sec, the reporting at every 5T becomes a bit tiresome. I'm happy for it to report every xT but it needs to be relative to the tank size.

**Comment by finwen** [comment]
Not sure how to fix this in a good way yet.

**Comment by robbyxp1** [comment]
Yep, we need to see how to handle this.  We don't have a mech in there for event merging.  We ~could~ say merge FS events occuring within 30 (pick) second of one another..

**Comment by finwen** [comment]
Solved in 8.0.0
