### ISSUE TITLE
Historical EDSM data no being downloaded

### ISSUE THREAD

**Issue by mp1963** [EDDiscovery/EDDiscovery#963]
I had to reinstall win10, elite and ED Discovery 7.01 yesterday. I completed my CMDRs details and ED Discovery appears to start to download my data from EDSM but then stopped. I am now unable to restart the download process.

**Comment by klightspeed** [comment]
Please try removing `edsmsystems.json`,  `edsmsystems.json.etag`, and EDDSystem.sqlite from `%LOCALAPPDATA%\EDDiscovery`, and try again.

**Comment by mp1963** [comment]
Problem got resolved in a different way. Had a major overheat problem with my Asp 12000Ly from Beagle Point and the ship exploded. Because EDSM can’t be bothered to write some code to let me delete all my flight entries in one go I created a new account. Don’t need to download old data now.

Marek

marekpaul@me.com
---------------------------------------------------------------------------------------------------------------------------------
"Due to recent cutbacks the light at the end of the tunnel has been turned off until further notice."
---------------------------------------------------------------------------------------------------------------------------------

**Comment by klightspeed** [comment]
So it's the download of commander logs that stopped, not the download of EDSM systems that stopped.

As EDSM recently put a rate limit on how often the API can be queried (1 query every 10 seconds) and a limit on how many log entries can be in a single request (7 days worth), and will return only the last 7 days worth of logs if start and end times are not provided, we'll have to work out how best to fetch them.

Perhaps we could store the earliest and latest times fetched.  The fetch could first work backwards from the earliest time (or `now` if not set) back to the gamma start date (`2014-11-22T04:00:00Z`), then forwards from the most recent fetched date to `now`.  At the moment, that would be about 120 requests, which would take no less than 20 minutes.

**Comment by VonDugard** [comment]
Can some one help me since the update I have been having trouble downloading info to EDSM, I hope this file can help.

<!DOCTYPE html><html class="APPLICATION_ENV_production" lang="en">
<head>
    <title>Flight Logs / Settings / EDSM - Elite: Dangerous Star Map</title>    <meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
<meta name="google" content="notranslate" >    
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    
    <link href="/css/bootstrap/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/css/global.css" rel="stylesheet" type="text/css" />
    <link href="/css/languages.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet" type="text/css" />
        
    <script src="/js/require.js" data-main="/js/EDSM.js"></script>
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png" />
    <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="/favicon-194x194.png" sizes="194x194" />
    <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
    <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192" />
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16" />
    <link rel="manifest" href="/manifest.json" />
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <meta name="msapplication-TileColor" content="#da532c" />
    <meta name="msapplication-TileImage" content="/mstile-144x144.png" />
    <meta name="theme-color" content="#272b30" />
    
    <meta property="og:url" content="https://www.edsm.net" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="EDSM - Elite: Dangerous Star Map" />
    <meta property="og:description" content="The Galactic Positioning System of Elite: Dangerous at your service." />
    <meta property="og:image" content="https://www.edsm.net/android-chrome-192x192.png" />
    
            <link rel="alternate" href="https://www.edsm.net/en/settings/logs/import" hreflang="en" />
        <link rel="alternate" href="https://www.edsm.net/de/settings/logs/import" hreflang="de" />
        <link rel="alternate" href="https://www.edsm.net/es/settings/logs/import" hreflang="es" />
        <link rel="alternate" href="https://www.edsm.net/fr/settings/logs/import" hreflang="fr" />
        <link rel="alternate" href="https://www.edsm.net/ja/settings/logs/import" hreflang="ja" />
        <link rel="alternate" href="https://www.edsm.net/ru/settings/logs/import" hreflang="ru" />
        <link rel="alternate" href="https://www.edsm.net/uk/settings/logs/import" hreflang="uk" />
        <link rel="alternate" href="https://www.edsm.net/zh/settings/logs/import" hreflang="zh" />
        
    </head>
<body>
        <div id="header-navbar-placeholder"></div>
    <nav class="navbar navbar-default navbar-fixed-top" id="header-navbar">
            <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar .navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img src="/img/miniLogo.svg" />
                                        <span class="visible-xs-inline">EDSM</span>
                    <span class="hidden-xs">Elite: Dangerous Star Map</span>
                                    </a>
            </div>
        
            
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/en/expeditions">
                            Expeditions                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Galactic Mapping <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="/en/galactic-mapping">
                                    Galactic Map                                </a>
                            </li>
                            <li>
                                <a href="/en/galactic-routes">
                                    Routes                                </a>
                            </li>
                            <li>
                                <a href="/en/map/users">
                                    Commanders Map                                </a>
                            </li>
                            <li>
                                <a href="/en/map/traffic">
                                    Traffic reports                                </a>
                            </li>
                            <li>
                                <a href="/en/map/holo-me">
                                    Holo-Me Album                                </a>
                            </li>
                        </ul>
                    </li>                    
                    <li>
                        <a href="/en/poi-visitors-list">
                            POI's visitors list                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Top 100 <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="/en/top/logs">
                                    Flight logs entries                                </a>
                            </li>
                            <li>
                                <a href="/en/top/discovered">
                                    Systems discovered first                                </a>
                            </li>
                            <li>
                                <a href="/en/top/visited-systems">
                                    Visited systems                                </a>
                            </li>
                            <li>
                                <a href="/en/top/distances">
                                    Distances submitted                                </a>
                            </li>
                        </ul>
                    </li>
                    
                                                                    
                                                
                        <li class="dropdown active">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <span class="visible-xs-inline">My account</span>
                                                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="/en/dashboard">
                                        Dashboard                                                                            </a>
                                </li>
                                
                                <li role="separator" class="divider"></li>
                                
                                <li>
                                    <a href="/en/settings">
                                        Settings                                    </a>
                                </li>
                                <li>
                                    <a href="/en/settings/api">
                                        API Key                                    </a>
                                </li>
                                <li role="separator" class="divider"></li>
                                
                                <li>
                                    <a href="/en/user/profile/id/6410/cmdr/Von_Dugard">
                                        My profile                                    </a>
                                </li>
                                <li>
                                    <a href="/en/user/fleet/id/6410/cmdr/Von_Dugard">
                                        My fleet                                    </a>
                                </li>
                                <li>
                                    <a href="/en/user/inventory/id/6410/cmdr/Von_Dugard">
                                        My inventory                                    </a>
                                </li>
                                <li>
                                    <a href="/en/user/diary/id/6410/cmdr/Von_Dugard">
                                        My logbook                                    </a>
                                </li>
                                <li>
                                    <a href="/en/user/flight-logs/id/6410/cmdr/Von_Dugard">
                                        My flight log                                    </a>
                                </li>
                                <li>
                                    <a href="/en/user/travel-map/id/6410/cmdr/Von_Dugard">
                                        My travel map                                    </a>
                                </li>
                                
                                <li role="separator" class="divider"></li>
                                
                                <li>
                                    <a href="/en/login/logout">
                                        Log out                                    </a>
                                </li>
                            </ul>
                        </li>
                                        
                                    </ul>
            </div>
        </div>
    </nav>
    
    <nav class="navbar navbar-default" id="subNavigation"><div class="container"><ul class="nav navbar-nav"><li><a href="/en/settings">General</a></li><li><a href="/en/settings/password">Password</a></li><li><a href="/en/settings/public-profile">Public Profile</a></li><li><a href="/en/settings/api">API Key</a></li></ul></div></nav>    
        
        
        
        
    <div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>
                <a href="/en/settings">
                    Settings                </a>
                &gt; <a href="/en/user/flight-logs/id/6410/cmdr/Von_Dugard">Flight Logs</a>
                &gt; Import
            </h3>
        </div>
    </div>
</div>

<div class="container" id="fileDropzone">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default" id="dropzone">
                <div class="panel-body">
                    
                        <div class="text-center h2">
                            <strong>Drop your netLog or Journal file here or click to upload.</strong>
                        </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container" id="fileStatus">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body text-center">
                    <p class="status text-center">
                        Waiting for file...
                    </p>
                    <div class="progress" style="display: none;">
                        <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" style="width: 0%;">
                            0%
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container" id="fileEntries" style="display: none;">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>System</th>
                            <th>Coordinates</th>
                            <th>Date visited</th>
                            <th width="33%" class="text-center">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="import-wrong-name" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Wrong file name</h4>
            </div>
        
            <div class="modal-body">
                <p>The file provided has the wrong name, it should be something like: <strong>netLog.XXXXXXX.XX.log</strong> or <strong>Journal.XXXXXXX.XX.log</strong>.</p>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
require(['EDSM'], function(){
    require(['jquery', 'moment', 'fileDrop'], function($, moment, fd){
        $(document).ready(function(){
            var currentDate     = null;
            var firstDate       = null;
            var lastSystem      = null;
            var lastCoordinates = null;
            var lastSystemDate  = null;
            var totalSystem     = 0;
            var sendSystem      = 0;
            
            var alreadyActive   = false;
            fd.logging          = false;
            fd.jQuery();
            
            var handleJournal   = function(file){
                alreadyActive = true;
                $('#fileStatus .panel-body .status').html('Reading journal...');
                $('#fileStatus .panel-body .progress').show();
                $('#fileEntries').show();
                
                file.readData(
                    function(str){
                        var journal = str.split('\n');
                        
                        journalLength = journal.length;
                        
                        $.each(journal, function(line, content){
                            updateProgress(line+1, journalLength);
                            
                            if(content != '')
                            {
                                content = JSON.parse(content);
                                
                                if(content.event == 'FSDJump')
                                {
                                    var okToAdd = false;
                                    
                                    if(content.StarSystem != undefined)
                                    {
                                        okToAdd             = true;
                                        lastSystem          = content.StarSystem;
                                        
                                        x                   = content.StarPos[0];
                                        y                   = content.StarPos[1];
                                        z                   = content.StarPos[2];
                                        
                                        currentSystemDate   = moment(content.timestamp);
                                    }
                                        
                                    if(okToAdd === true)
                                    {
                                        totalSystem++;
                                        
                                        var tr = $('<tr>').append('<td style="line-height: 62px;">' + lastSystem + '</td>')
                                                          .append('<td style="line-height: 62px;" data-x="' + x + '" data-y="' + y + '" data-z="' + z + '">' + (parseInt(x * 32) / 32) + ' / ' + (parseInt(y * 32) / 32) + ' / ' + (parseInt(z * 32) / 32) + '</td>')
                                                          .append('<td style="line-height: 31px;">' + currentSystemDate.utc().format('DD/MM/YYYY HH:mm:ss') + ' (UTC)</td>')
                                                          .append('<td data-date="' + currentSystemDate.utc().format('YYYY-MM-DD HH:mm:ss') + '"><svg version="1.1" id="animatedLogo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100%" height="52" viewBox="0 0 960 960" enable-background="new 0 0 960 960" xml:space="preserve"> <path fill="#FFFFFF" d="M289.253,242.47c32.203,12.904,57.848,38.699,70.546,71.006c12.904-32.203,38.698-57.848,71.005-70.545 c-32.202-12.904-57.848-38.699-70.546-71.005C347.354,204.127,321.561,229.772,289.253,242.47z" class="star1" /> <path fill="#FFFFFF" d="M463.75,365.491c29.247,11.72,52.538,35.147,64.071,64.488c11.719-29.247,35.145-52.538,64.486-64.07 c-29.246-11.72-52.537-35.147-64.068-64.488C516.518,330.668,493.092,353.959,463.75,365.491z" class="star2" /> <path fill="#FFFFFF" d="M667.417,230.336c50.782,20.35,91.224,61.028,111.25,111.976c20.349-50.783,61.024-91.226,111.973-111.25 c-50.782-20.35-91.224-61.028-111.247-111.975C759.041,169.871,718.365,210.313,667.417,230.336z" class="star3" /> <path fill="#FFFFFF" d="M793.417,615.483c30.308,12.145,54.443,36.423,66.396,66.829c12.144-30.309,36.42-54.445,66.826-66.396 c-30.308-12.145-54.443-36.422-66.395-66.828C848.1,579.396,823.823,603.532,793.417,615.483z" class="star4" /> <path fill="#FFFFFF" d="M71.488,754.347c49.385,19.79,88.715,59.349,108.188,108.894c19.79-49.386,59.348-88.715,108.893-108.188 c-49.385-19.79-88.715-59.349-108.188-108.893C160.591,695.546,121.034,734.874,71.488,754.347z" class="star5" /> </svg></td>');
                                        
                                        tr.appendTo('#fileEntries table tbody');
                                    }
                                }
                            }
                        });
                        
                        // Now handle sending data...
                        startSendingData();
                    },
                    function(e){
                        alert('Terrible error!')
                    },
                    'text'
                );
            };
            
            var handleNetLog    = function(file){
                var re = /^{(.*)} System:(\d+)\((.*)\) Body:(.*)/; // Pre 1.6/2.1
                var re2 = /^{(.*)} System:"(.*)" StarPos:\((.*),(.*),(.*)\)ly(.*)/; // 1.6/2.1
                
                alreadyActive = true;
                $('#fileStatus .panel-body .status').html('Reading netLog...');
                $('#fileStatus .panel-body .progress').show();
                $('#fileEntries').show();
                
                file.readData(
                    function(str){
                        var netLog = str.split('\n');
                        
                        netLogLength = netLog.length;
                        
                        $.each(netLog, function(line, content){
                            updateProgress(line+1, netLogLength);
                            
                            if(line == 0)
                            {
                                firstDate       = '20' + content.substr(0, 8);
                                currentDate     = moment(firstDate + 'T' + content.substr(9, 5) + ':00');
                                lastSystemDate  = currentDate;
                            }
                            else
                            {
                                match = content.match(re);
                            
                                if(match && content.search("ProvingGround") == -1)
                                {
                                    if(lastSystem != match[3])
                                    {
                                        lastSystem = match[3];
                                        totalSystem++;
                                        
                                        // Check date, if new date is before then it is next day...
                                        var currentSystemDate = moment(firstDate + 'T' + match[1]);
                                        
                                        if(currentSystemDate.isBefore(lastSystemDate))
                                        {
                                            var tempTomorrow = moment(firstDate);
                                            tempTomorrow.add(1, 'days');
                                            firstDate = tempTomorrow.format('YYYY-MM-DD');
                                        }
                                        
                                        lastSystemDate      = moment(firstDate + 'T' + match[1]);
                                        currentSystemDate   = moment(firstDate + 'T' + match[1]);
                                        
                                        var tr = $('<tr>').append('<td style="line-height: 62px;">' + lastSystem + '</td>')
                                                          .append('<td style="line-height: 62px;" class="text-danger">Not provided</td>')
                                                          .append('<td style="line-height: 31px;">' + currentSystemDate.format('DD/MM/YYYY HH:mm:ss') + '<br />' + currentSystemDate.utc().format('DD/MM/YYYY HH:mm:ss') + ' (UTC)</td>')
                                                          .append('<td data-date="' + currentSystemDate.utc().format('YYYY-MM-DD HH:mm:ss') + '"><svg version="1.1" id="animatedLogo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100%" height="52" viewBox="0 0 960 960" enable-background="new 0 0 960 960" xml:space="preserve"> <path fill="#FFFFFF" d="M289.253,242.47c32.203,12.904,57.848,38.699,70.546,71.006c12.904-32.203,38.698-57.848,71.005-70.545 c-32.202-12.904-57.848-38.699-70.546-71.005C347.354,204.127,321.561,229.772,289.253,242.47z" class="star1" /> <path fill="#FFFFFF" d="M463.75,365.491c29.247,11.72,52.538,35.147,64.071,64.488c11.719-29.247,35.145-52.538,64.486-64.07 c-29.246-11.72-52.537-35.147-64.068-64.488C516.518,330.668,493.092,353.959,463.75,365.491z" class="star2" /> <path fill="#FFFFFF" d="M667.417,230.336c50.782,20.35,91.224,61.028,111.25,111.976c20.349-50.783,61.024-91.226,111.973-111.25 c-50.782-20.35-91.224-61.028-111.247-111.975C759.041,169.871,718.365,210.313,667.417,230.336z" class="star3" /> <path fill="#FFFFFF" d="M793.417,615.483c30.308,12.145,54.443,36.423,66.396,66.829c12.144-30.309,36.42-54.445,66.826-66.396 c-30.308-12.145-54.443-36.422-66.395-66.828C848.1,579.396,823.823,603.532,793.417,615.483z" class="star4" /> <path fill="#FFFFFF" d="M71.488,754.347c49.385,19.79,88.715,59.349,108.188,108.894c19.79-49.386,59.348-88.715,108.893-108.188 c-49.385-19.79-88.715-59.349-108.188-108.893C160.591,695.546,121.034,734.874,71.488,754.347z" class="star5" /> </svg></td>');
                                        
                                        tr.appendTo('#fileEntries table tbody');
                                    }
                                }
                                // Test the new logs from 1.6/2.1
                                else
                                {
                                    match = content.match(re2);
                            
                                    if(match && content.search("ProvingGround") == -1)
                                    {
                                        if(lastSystem != match[2] || lastCoordinates != '' + match[3] + match[4] + match[5])
                                        {
                                            lastSystem      = match[2];
                                            lastCoordinates = '' + match[3] + match[4] + match[5];
                                            totalSystem++;
                                            
                                            // Check date, if new date is before then it is next day...
                                            var currentSystemDate = moment(firstDate + 'T' + match[1]);
                                            
                                            if(currentSystemDate.isBefore(lastSystemDate))
                                            {
                                                var tempTomorrow = moment(firstDate);
                                                tempTomorrow.add(1, 'days');
                                                firstDate = tempTomorrow.format('YYYY-MM-DD');
                                            }
                                            
                                            lastSystemDate      = moment(firstDate + 'T' + match[1]);
                                            currentSystemDate   = moment(firstDate + 'T' + match[1]);
                                            
                                            x                   = match[3];
                                            y                   = match[4];
                                            z                   = match[5];
                                            
                                            var tr = $('<tr>').append('<td style="line-height: 62px;">' + lastSystem + '</td>')
                                                              .append('<td style="line-height: 62px;" data-x="' + x + '" data-y="' + y + '" data-z="' + z + '">' + (parseInt(x * 32) / 32) + ' / ' + (parseInt(y * 32) / 32) + ' / ' + (parseInt(z * 32) / 32) + '</td>')
                                                              .append('<td style="line-height: 31px;">' + currentSystemDate.format('DD/MM/YYYY HH:mm:ss') + '<br />' + currentSystemDate.utc().format('DD/MM/YYYY HH:mm:ss') + ' (UTC)</td>')
                                                              .append('<td data-date="' + currentSystemDate.utc().format('YYYY-MM-DD HH:mm:ss') + '"><svg version="1.1" id="animatedLogo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100%" height="52" viewBox="0 0 960 960" enable-background="new 0 0 960 960" xml:space="preserve"> <path fill="#FFFFFF" d="M289.253,242.47c32.203,12.904,57.848,38.699,70.546,71.006c12.904-32.203,38.698-57.848,71.005-70.545 c-32.202-12.904-57.848-38.699-70.546-71.005C347.354,204.127,321.561,229.772,289.253,242.47z" class="star1" /> <path fill="#FFFFFF" d="M463.75,365.491c29.247,11.72,52.538,35.147,64.071,64.488c11.719-29.247,35.145-52.538,64.486-64.07 c-29.246-11.72-52.537-35.147-64.068-64.488C516.518,330.668,493.092,353.959,463.75,365.491z" class="star2" /> <path fill="#FFFFFF" d="M667.417,230.336c50.782,20.35,91.224,61.028,111.25,111.976c20.349-50.783,61.024-91.226,111.973-111.25 c-50.782-20.35-91.224-61.028-111.247-111.975C759.041,169.871,718.365,210.313,667.417,230.336z" class="star3" /> <path fill="#FFFFFF" d="M793.417,615.483c30.308,12.145,54.443,36.423,66.396,66.829c12.144-30.309,36.42-54.445,66.826-66.396 c-30.308-12.145-54.443-36.422-66.395-66.828C848.1,579.396,823.823,603.532,793.417,615.483z" class="star4" /> <path fill="#FFFFFF" d="M71.488,754.347c49.385,19.79,88.715,59.349,108.188,108.894c19.79-49.386,59.348-88.715,108.893-108.188 c-49.385-19.79-88.715-59.349-108.188-108.893C160.591,695.546,121.034,734.874,71.488,754.347z" class="star5" /> </svg></td>');
                                            
                                            tr.appendTo('#fileEntries table tbody');
                                        }
                                    }
                                }
                            }
                        });
                        
                        // Now handle sending data...
                        startSendingData();
                    },
                    function(e){
                        alert('Terrible error!')
                    },
                    'text'
                );
            };
            
            var startSendingData = function(){
                $('#fileStatus .panel-body .status').html('Sending flight logs...');
                if(sendSystem < totalSystem)
                {
                    var current = $('#fileEntries table tbody tr:eq(' + sendSystem + ')');
                    
                    if(current.length > 0)
                    {
                        sendSystem++;
                        
                        updateProgress(sendSystem, totalSystem);
                        
                        // Build API URL
                        var endPoint = '/api-logs-v1/set-log';
                        endPoint    += '?systemName=' + encodeURIComponent(current.find('td:eq(0)').html());
                        endPoint    += '&commanderName=Von_Dugard';
                        endPoint    += '&apiKey=4a42fb8dbe3c5ac309e495530d7d26d10c5a606f';
                        endPoint    += '&dateVisited=' + encodeURIComponent(current.find('td:eq(3)').attr('data-date'));
                        endPoint    += '&fromSoftware=EDSM+-+Front+End';
                        
                        // Pass coordinates from new logs 
                        if(current.find('td:eq(1)').attr('data-x') != undefined && current.find('td:eq(1)').attr('data-y') != undefined && current.find('td:eq(1)').attr('data-z') != undefined)
                        {
                            endPoint += '&x=' + encodeURIComponent(current.find('td:eq(1)').attr('data-x'));
                            endPoint += '&y=' + encodeURIComponent(current.find('td:eq(1)').attr('data-y'));
                            endPoint += '&z=' + encodeURIComponent(current.find('td:eq(1)').attr('data-z'));
                        }
                        
                        $.getJSON(endPoint, function(data){
                            // Return Status
                            if(data.msgnum == 100)
                            {
                                current.find('td:eq(3)').addClass('text-center alert-success').css('line-height', '62px').html('Flight entry added.');
                            }
                            else if(data.msgnum == 401)
                            {
                                current.find('td:eq(3)').addClass('text-center alert-info').css('line-height', '62px').html('Flight entry already exists.');
                            }
                            else
                            {
                                current.find('td:eq(3)').addClass('text-center alert-warning').css('line-height', '31px').html('Error: ' + data.msgnum + '<br />' + data.msg);
                            }
                            
                            setTimeout(function(){ startSendingData(); }, 50);
                        });
                    }
                    else
                    {
                        $('#fileStatus .panel-body .status').html('Done!');
                        $('#fileStatus .panel-body .progress').remove();
                    }
                }
                else
                {
                    if(totalSystem > 0)
                    {
                        $('#fileStatus .panel-body .status').html('Done!');
                        $('#fileStatus .panel-body .progress').remove();
                    }
                    else
                    {
                        $('#fileStatus .panel-body .status').html('Done! No system were found in that file!<br />If you used netLog, be sure to activate verboseLogging to grab your flight logs.');
                        $('#fileStatus .panel-body .progress').remove();
                    }
                }
            };
            
            var updateProgress = function(current, total){
                var value = Math.round(current / total * 100);
                
                $('#fileStatus .panel-body .progress .progress-bar').css('width', value + '%')
                                                                      .html(value + '%');
            };
            
            var options = {
                multiple: false,
                dragOverClass: 'panel-success'
            };
            var dropzone = $('#dropzone');
            
            dropzone.filedrop(options)
                    .on('fdsend', function (e, files) {
                        if(alreadyActive == true)
                            return;
                        
                        // Occurs when FileDrop's 'send' event is initiated.
                        $.each(files, function (i, file) {
                            if(/^netLog./.test(file.name) == true && /.log$/.test(file.name))
                            {
                                $('#fileDropzone').remove();
                                handleNetLog(file);
                            }
                            else
                            {
                                if(/^Journal./.test(file.name) == true && /.log$/.test(file.name))
                                {
                                    $('#fileDropzone').remove();
                                    handleJournal(file);
                                }
                                else
                                {
                                    $('#import-wrong-name').modal('show');
                                }
                            }
                        })
                    });
        });
    });
});
</script>

<style type="text/css">
/* Hides <input type="file"> while simulating "Browse" button: */
.fd-file {
  opacity: 0;
  font-size: 118px;
  position: absolute;
  right: 0;
  top: 0;
  z-index: 1;
  padding: 0;
  margin: 0;
  cursor: pointer;
  filter: alpha(opacity=0);
  font-family: sans-serif;
}

.panel-success {
    background-color: #62c462;
    border-color: #62bd4f;
    color: #ffffff;
}
</style>    
    <div class="container"> 
                        <div class="row">
                            <div class="col-md-12"><div class="panel panel-default">
                                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                   
                   <ins class="adsbygoogle"
                        style="display:block"
                        data-ad-client="ca-pub-0147194324405413"
                        data-ad-slot="6794179391"
                        data-ad-format="auto"></ins>
                   <script>
                   (adsbygoogle = window.adsbygoogle || []).push({});
                   </script>
                            </div></div>
                        </div>
                    </div>    
    <footer>
        <div class="navbar navbar-default">
            <div class="container">
                <p class="navbar-text">
                    EDSM - Elite: Dangerous Star Map © 2015-2017 <br />
                    <a href="https://www.elitedangerous.com/" target="_blank">Elite: Dangerous</a> © 2012, 2013 Frontier Developments plc. All rights reserved.                </p>
                <ul class="nav navbar-nav navbar-right dropup">
                    <li>
                        <a href="/en/donation">
                            Support us                        </a>
                    </li>
                    <li>
                        <a href="/en/faq">
                            FAQ                        </a>
                    </li>
                    <li>
                        <a href="/en/timeline/galnet">
                            Galactic News                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Tools <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="/en/systems/pairs">
                                    Systems pairs
                                </a>
                            </li>
                            <li>
                                <a href="/en/systems/duplicates">
                                    Systems with duplicate names                                </a>
                            </li>
                            <li>
                                <a href="/en/systems/unresolved">
                                    Unresolved systems                                </a>
                            </li>
                            <li>
                                <a href="/en/systems/front">
                                    Featured systems                                </a>
                            </li>
                        </ul>
                    </li>
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            API <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="/en/nightly-dumps">
                                    Nightly Dumps                                </a>
                            </li>
                            <li>
                                <a href="/en/api-status-v1">
                                    API Status v1                                </a>
                            </li>
                            <li>
                                <a href="/en/api-commander-v1">
                                    API Commander v1                                </a>
                            </li>
                            <li>
                                <a href="/en/api-logs-v1">
                                    API Logs v1                                </a>
                            </li>
                            <li>
                                <a href="/en/api-v1">
                                    API Systems v1                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div class="navbar navbar-default">
            <div class="container text-center">
                <p class="navbar-text social">
                    <a href="https://bugsnag.com/blog/bugsnag-loves-open-source" target="_blank" class="btn btn-default btn-sm">
                        <span class="socialIcon-bugsnag"></span>
                        Bugsnag
                    </a>
                    <a href="http://git.edsm.net:9090/" target="_blank" class="btn btn-default btn-sm">
                        <span class="socialIcon-git"></span>
                        GitLab
                    </a>
                    <script>window.twttr = (function(d, s, id) {
                      var js, fjs = d.getElementsByTagName(s)[0],
                        t = window.twttr || {};
                      if (d.getElementById(id)) return t;
                      js = d.createElement(s);
                      js.id = id;
                      js.src = "https://platform.twitter.com/widgets.js";
                      fjs.parentNode.insertBefore(js, fjs);
                    
                      t._e = [];
                      t.ready = function(f) {
                        t._e.push(f);
                      };
                    
                      return t;
                    }(document, "script", "twitter-wjs"));</script>
                    <a class="twitter-follow-button btn btn-default btn-sm" href="https://twitter.com/EDSM_NET" lang="en">
                        Follow @EDSM_NET                    </a>
                    <style type="text/css">
                    .twitter-follow-button {
                        vertical-align: middle;
                    }
                    </style>
                    <a href="https://discord.gg/0sFOD6GxFZRc1ad0" target="_blank" class="btn btn-default btn-sm">
                        <span class="socialIcon-discord"></span>
                        Discord
                    </a>
                    <a href="https://forums.frontier.co.uk/showthread.php?t=179063" target="_blank" class="btn btn-default btn-sm">
                        Forum
                    </a>
                </p>
            </div>
        </div>
    </footer>
    
        <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    
      ga('create', 'UA-496332-22', 'auto');
      ga('send', 'pageview');
    </script>
    </body>
</html>

**Comment by klightspeed** [comment]
PR #970 (which should be in v7.0.2) should resolve this.
