### ISSUE TITLE
Version 7.01 does not show if a planet is terraformable or not..

### ISSUE THREAD

**Issue by mp1963** [EDDiscovery/EDDiscovery#964]
After reinstalling ED Discovery 7.01 I noticed that History no longer reports a planet as terraformable.

**Comment by klightspeed** [comment]
Is this with existing scans or new scans?

**Comment by mp1963** [comment]
Only with new scans

Marek

marekpaul@me.com
---------------------------------------------------------------------------------------------------------------------------------
"Due to recent cutbacks the light at the end of the tunnel has been turned off until further notice."
---------------------------------------------------------------------------------------------------------------------------------

**Comment by klightspeed** [comment]
Do you have a Detailed Surface Scanner equipped?

Without a Detailed Surface Scanner, the `TerraformState` property will be absent from the journal entry.
With a Detailed Surface Scanner, if the planet is not terraformable, then the `TerraformState` will be an empty string.

**Comment by mp1963** [comment]
I am in an Asp X with all scanners fitted and operational.

Marek

marekpaul@me.com
---------------------------------------------------------------------------------------------------------------------------------
"Due to recent cutbacks the light at the end of the tunnel has been turned off until further notice."
---------------------------------------------------------------------------------------------------------------------------------

**Comment by klightspeed** [comment]
Please send us a journal with a scan, and a screenshot of the window showing the missing terraform state.

**Comment by mp1963** [comment]
Ok as soon as I leave for Beagle Point (this morning) and come across stuff worth scanning.

Marek

marekpaul@me.com
---------------------------------------------------------------------------------------------------------------------------------
"Due to recent cutbacks the light at the end of the tunnel has been turned off until further notice."
---------------------------------------------------------------------------------------------------------------------------------

**Comment by tivec** [comment]
I can confirm it working for me, just scanned a terraformable high metal content world.

**Comment by mp1963** [comment]
Ok two screenshots enclosed. One from ED itself showing the planet data (terraformable) and one from ED Discovery showing the missing Terraformable tag. Please bear in mind this is a clean 7.0.1 install not an upgrade …

**Comment by klightspeed** [comment]
Please post these on the Github issue, as the Github email receiver stripped them.

**Comment by mp1963** [comment]
![eol prou ls-q c19-96 20170415-074547](https://cloud.githubusercontent.com/assets/24973059/25065479/b8382d6a-2208-11e7-9b09-bb1b1f260150.jpg)
![no terraforming](https://cloud.githubusercontent.com/assets/24973059/25065481/bb22c1de-2208-11e7-9083-799e44103540.JPG)

**Comment by klightspeed** [comment]
Please switch to the journal tab, and select the body, then take a screenshot.

If at all possible, please also search for `"event":"Scan", "BodyName":"Eol Prou LS-Q c19-96 1"` in your journals, and paste the journal line.

**Comment by mp1963** [comment]
{ "timestamp":"2017-04-15T07:44:53Z", "event":"Scan", "BodyName":"Eol Prou LS-Q c19-96 1", "DistanceFromArrivalLS":374.841553, "TidalLock":false, "TerraformState":"Terraformable", "PlanetClass":"High metal content body", "Atmosphere":"carbon dioxide rich atmosphere", "AtmosphereType":"CarbonDioxideRich", "AtmosphereComposition":[ { "Name":"Nitrogen", "Percent":89.184120 }, { "Name":"CarbonDioxide", "Percent":10.618563 }, { "Name":"SulphurDioxide", "Percent":0.107041 } ], "Volcanism":"", "MassEM":0.653127, "Radius":5352605.000000, "SurfaceGravity":9.086078, "SurfaceTemperature":280.894379, "SurfacePressure":31865.412109, "Landable":false, "SemiMajorAxis":112339812352.000000, "Eccentricity":0.000356, "OrbitalInclination":0.562280, "Periapsis":62.611637, "OrbitalPeriod":22406358.000000, "RotationPeriod":371229.906250 }

![journalscreen](https://cloud.githubusercontent.com/assets/24973059/25065761/0b099d68-220d-11e7-98bd-feed7ceb22cd.JPG)

**Comment by mp1963** [comment]
As requested

**Comment by klightspeed** [comment]
![image](https://cloud.githubusercontent.com/assets/147116/25065819/72808348-2259-11e7-8de0-26cbf7e65d69.png)

**Comment by mp1963** [comment]
The History log used to show if a planet was terraformable or not. That data is no longer being displayed. This has nothing to do with the Journal!!\

**Comment by klightspeed** [comment]
Perhaps we need to move that `Candidate for terraforming` closer to the top, or include it in the first line.
