### ISSUE TITLE
Statistics not clearing before writing new values - numbers overlayed

### ISSUE THREAD

**Issue by markjfisher** [EDDiscovery/EDDiscovery#965]
In the stats window, the figures are not clearing before updating, so there are ghost numbers until you either swap tabs and back or resize the window.

This was both 7.0.0 and 7.0.1

![image](https://cloud.githubusercontent.com/assets/1616940/25061877/94bf175a-21b7-11e7-8b03-522a4fb0badc.png)

**Comment by robbyxp1** [comment]
I think this is a effect of windows/c# .net/win forms. We just use a standard DGV grid.  Can't reproduce. Closing
