### ISSUE TITLE
Add extra reference systems far from galatic plane if position is far from sol (>10k?)

### ISSUE THREAD

**Issue by finwen** [EDDiscovery/EDDiscovery#97]
Sometime then trillatation for out from sol its hard to get a good calculation on Y position.

To help with it it is good if we add some system with very big Y value and low Y values to suggested systems.

**Comment by RedfoxCh** [comment]
I've recently been trilaterating some of these systems, at -20kly from the Sol-SagA line, as far up/down from the plane as possible. I'll just add them here, possibly they are of use for this:

- CHOOMAU RD-V B21-0
- HYPUA PRIAE RY-H C10-0
- NASO JI-R C18-1
- FOIJAI XH-W C17-0
- PLOOE AUD RW-W C1-0
- FLYAI PREIA WO-Z D1
- PRAEI CHRIA JX-A D1-0
- SWUEMU NR-W D1-0
- DRYAEA CHREAU CC-A C15-0
- DRYOOE BLUA SE-P D6-0
- PHA BRI RZ-F D11-0
- PHROOE GRU AB-N D7-0
- BLEOU FROA NX-B D0
- BLUE PRIAE XY-A D0
- BLEOU CHREAU NX-T D3-0
- YUETAO XU-W D2-0
- ROTHAI HS-B D13-0
- BUQOA BV-X D1-0
- PLOOE BRI ND-J D9-0

**Comment by RedfoxCh** [comment]
Just noticed that I also have a few of those at +20kly from the Sol-SagA line:

- CLOOMAI TP-J C11-0
- HYPAA PRI BK-G C11-0
- OWAIRPHS LS-J D9-0
- HYPAA BLOO VZ-N D7-1
- PLAE AUDST MN-B D13-0
- FLYUE PRI PI-B D13-0
- PREOU CHREA KC-B D1-0
- THROSOA TM-W D1-0
- IOJAIST BU-Z C13-0
- DRYAE BLOO YZ-O D6-0
- PHOO BREAE YZ-G D10-0
- LYSEAFAI KI-I D10-0
- BLIE AUB PC-C D0
- CHRAITEE GC-C D13-0
- BLIE CHREA QF-C D14-0
- EOGAK TO-Z D13-0

**Comment by finwen** [comment]
this is obsolete now
