### ISSUE TITLE
"Unknown Type" in Journal when scanning S- and MS-class stars

### ISSUE THREAD

**Issue by RedfoxCh** [EDDiscovery/EDDiscovery#973]
When scanning S- and MS-class stars the Information in the EDD Journal begins with "Unknown Type [MS/S] Star, Mass [etc.]". This "Unknown" also carries over into the speech output.

Example of a ED Journal entry: 
`{ "timestamp":"2017-04-16T00:08:43Z", "event":"Scan", "BodyName":"Gru Dryiae GA-Q d5-4 A", "DistanceFromArrivalLS":0.000000, "StarType":"MS", "StellarMass":1.039063, "Radius":21198338048.000000, "AbsoluteMagnitude":0.343216, "Age_MY":10130, "SurfaceTemperature":2940.000000, "SemiMajorAxis":16337067835392.000000, "Eccentricity":0.093918, "OrbitalInclination":-11.088440, "Periapsis":139.143387, "OrbitalPeriod":149888303104.000000, "RotationPeriod":8553741.000000 }`

**Comment by robbyxp1** [comment]
Fixed in 8.0
