### ISSUE TITLE
7.0.2 not showing mission rewards/donation costs in ledger

### ISSUE THREAD

**Issue by svensven** [EDDiscovery/EDDiscovery#978]
Reward credits and donation debits aren't being picked up, and so the balance gets way off:
![ledger 2017-04-18](https://cloud.githubusercontent.com/assets/5736616/25109848/a3427d40-23d7-11e7-8d19-9395743cb77f.PNG)

**Comment by robbyxp1** [comment]
Bug fixed on 7.0.3 and master
