### ISSUE TITLE
nvoglv64.dll Crashes When Opening 3D Map On Windows 10 Creators Update

### ISSUE THREAD

**Issue by jusaari11** [EDDiscovery/EDDiscovery#982]
Clicking on the 3d map button, the map window opens but shows only the toolbar and immediately displays "EDDiscovery has stopped working" and pressing cancel, EDDiscovery exits. 

Event viewer shows:
"Application: EDDiscovery.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 0000000066D1035D"
and
"Faulting application name: EDDiscovery.exe, version: 7.0.2.0, time stamp: 0x58f5316c
Faulting module name: nvoglv64.DLL, version: 22.21.13.8165, time stamp: 0x58df0143
Exception code: 0xc0000005
Fault offset: 0x0000000000c1035d
Faulting process id: 0x658
Faulting application start time: 0x01d2b8342d70cc64
Faulting application path: G:\Program files\EDDiscovery\EDDiscovery\EDDiscovery.exe
Faulting module path: C:\WINDOWS\SYSTEM32\nvoglv64.DLL
Report Id: 583f724a-dce1-4e15-b19c-877e7f3c357d
Faulting package full name: 
Faulting package-relative application ID: "

EDDiscovery version is 7.0.2.0
OS is Windows 10

**Comment by klightspeed** [comment]
That's strange that the unhandled exception handler was never invoked.  The nVidia OpenGL DLL must have made a mess of the stack.

What are the last few lines of the most recent trace log in `%LOCALAPPDATA%\EDDiscovery\Log`

**Comment by jusaari11** [comment]
[2017-04-18 22:48:10Z] Start Monitor on C:\Users\Juha\Saved Games\Frontier Developments\Elite Dangerous
[2017-04-18 23:13:06Z] Grids 522 Database Stars 8281531 mid 44 far 26
[2017-04-18 23:13:08Z] Shown

Event log shows that the errors occured at 23:13:09

**Comment by klightspeed** [comment]
What graphics card are you using?  What nVidia driver version do you have installed?

**Comment by phroggster** [comment]
>What graphics card are you using? What nVidia driver version do you have installed?
Also, have you yet upgraded to Windows 10 Creator's Update? There's some significant graphics driver changes in that update that seem to be ruffling feathers at Nvidia.

**Comment by jusaari11** [comment]
NVIDIA GeForce 950, Driver version  381.65. Yes I upgraded to Creators, and now that I think of it the problems started after the upgrade.

**Comment by phroggster** [comment]
Looking around, some people have had luck clearing their shader cache (removing everything inside of `%APPDATA%\NVIDIA\GLCache`), but I don't think that'll work for us. Others have had luck performing a clean install of the official NVIDIA drivers. You did do a clean install of the official NVIDIA drivers after the Windows 10 upgrade, right? Otherwise, you're likely using the automatically and silently installed ~~naughty~~ drivers from Windows Update.

**Comment by jusaari11** [comment]
Doing a clean install of NVIDIA drivers resolved this issue. Thanks for the support!

**Comment by phroggster** [comment]
Glad to hear that it's working again.

I imagine that we'll be seeing this with increasing frequency over the next few months... Half tempted to leave this issue open to make it more obvious for users searching it out.

**Comment by robbyxp1** [comment]
Closed.. no more reports.
