### ISSUE TITLE
Lag when entering Notes

### ISSUE THREAD

**Issue by adermon** [EDDiscovery/EDDiscovery#983]
There is a delay of about 1 to 8 seconds when entering notes. To be precise the character entry delay between pressing a key on the keyboard and it appearing in the Notes window has variable delay that makes it difficult to use. This was occurring in 6.1.3 at random times but seems worse now in 7.0.

**Comment by mwerle** [comment]
Possible work-around: don't open the 3dMap. (Even opening it and closing it probably causes this issue).

**Comment by finwen** [comment]
should be solved in 7.0.3
