### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by VonDugard** [EDDiscovery/EDDiscovery#994]
Just downloaded new update, now EDDiscovery will not open at all

**Comment by VonDugard** [comment]
I hope this helps?

![2017-04-19](https://cloud.githubusercontent.com/assets/17255194/25180923/b2967770-2507-11e7-80b6-fd54ad786a95.png)

**Comment by mpfj** [comment]
Possible duplicate of #993

**Comment by finwen** [comment]
Thanks for the image.  I know why it can happends.  Will work on a solution
tonight

2017-04-19 15:03 GMT+02:00 Mark Jackson <notifications@github.com>:

**Comment by VonDugard** [comment]
thanks alot...
