### ISSUE TITLE
Sort by Value is left-justified

### ISSUE THREAD

**Issue by vashts6583** [EDDiscovery/EDDiscovery#995]
On the Loadout panel, when sorting modules by Value, it sorts them as though they were left-justified, not right-justified.  For instance, a module worth 90000 is listed before a module worth 5000000.
![value_sort](https://cloud.githubusercontent.com/assets/15353221/25199225/120d9052-2518-11e7-806b-3b1d2ffc4643.png)

**Comment by robbyxp1** [comment]
It needs a custom sorted, not difficult.

**Comment by robbyxp1** [comment]
Fixed on master.
